### ISSUE TITLE
Attributes still not applied as properties on invalid test

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1012]
The problem initially described in #747 still appears to be unresolved in some cases. In the NUnit 3 Adapter demo program, the method AsyncVoidTestIsInvaild has a property attribute, but the property does not show up in the XML. 

It's possible that the fix missed a corner case or that it didn't deal with the XML output.

**Comment by CharliePoole** [comment]
Nobody has cared about this for five years, so I'd recommend closing it.

**Comment by mikkelbu** [comment]
I agree, then we can solve this problem if/when somebody needs it.
