### ISSUE TITLE
Ensure NUnit API assembly updates with MSI installs

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#1014]
We are currently versioning the assembly at 3.0.0.0  with the intention that the API will not change. The internals may change occasionally, but if the version doesn’t change, then the MSI won’t update it.
 
We’ll need to figure out how to ensure it gets updated. I can think of a few ways;

- Force uninstall on install in the MSI. 
- Continually increment the third digit of the file version and just leave the assembly version the same.
- Don't distribute the console/engine as an MSI
- Use a different installer like NSIS

**Comment by CharliePoole** [comment]
This is critical if 3.0.1 includes an msi and if the api assembly changes. If there is no change, then this is critical for 3.2.

**Comment by CharliePoole** [comment]
@rprouse Can you take a look at this and see what we need to do?

**Comment by rprouse** [comment]
No problem. I think incrementing the file version, but not the assembly version will give us what we want. I will make the changes and test.

**Comment by CharliePoole** [comment]
Closed by PR #1069
