### ISSUE TITLE
Specifying .nunit project and --framework on command line causes nunit3-console.exe to crash.

### ISSUE THREAD

**Issue by staticcat** [nunit/nunit#1015]
The command line that is run:
```ShellSession
C:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe" "I:\OpenSource\GitHub\nunit\EngineAndConsoleTests.nunit" --trace=verbose --framework=v3.0
```
The output that is received. 

```ShellSession
NUnit Console Runner 3.0.5790
Copyright (C) 2015 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 6.3.9600.0
  CLR Version: 4.0.30319.42000

Test Files
    I:\OpenSource\GitHub\nunit\EngineAndConsoleTests.nunit

Could not load file or assembly 'nunit.framework' or one of its dependencies. The system cannot find the file specified.
```
Running the command line with the test library directly and the framework specified gives. 
```ShellSession
C:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe" "I:\OpenSource\GitHub\nunit\bin\Debug\nunit.engine.tests.dll" --trace=verbose --framework=v3.0
```

```ShellSession
NUnit Console Runner 3.0.5790
Copyright (C) 2015 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 6.3.9600.0
  CLR Version: 4.0.30319.42000

Test Files
    I:\OpenSource\GitHub\nunit\bin\Debug\nunit.engine.tests.dll

=> NUnit.Engine.Tests.RuntimeFrameworkTests.CanListAvailableFrameworks
Available: Net 2.0.50727
Available: Net 3.0
Available: Net 3.5
Available: Net 4.0 - Full
Available: Net 4.5 - Full
Available: Net 4.0 - Client
Available: Net 4.5 - Client
Available: Net 4.0 - Client

Errors and Failures
...
```
I am not certain if this is by design, and NUnit is simply missing a guard condition to not allow .nunit projects to not be specified with the framework option.

Should the framework command be allowed to be specified with a nunit project, or is this an invalid test of the feature? I also have a sense that the error being reported is a path issue with the tests files themselves.

**Comment by CharliePoole** [comment]
On my machine, this happens if I leave off --framework and use --inprocess!

We obviously need to fix this for the release. We also need to examine all the various paths through the creation of the AppDomain, depending on settings, simplify the logic and ensure that all paths work the same  way.

**Comment by Roemer** [comment]
This is still happening to me.

If I call ```nunit3-console\nunit3-console.exe TestStack.White.nunit``` I get the exception mentioned above.
If i directly use ```nunit3-console\nunit3-console.exe ..\..\src\TestStack.White.UnitTests\bin\Debug\TestStack.White.UnitTests.dll ``` (which is what I added to the .nunit file) it works correctly.

**Comment by CharliePoole** [comment]
@Roemer That's the problem with generalized symptoms like "nunit3-console crashes" :-)

I know we fixed the original problem that was causing a crash and tested it, so I'm guessing that something more is coming into play here... possibly the use of `..\..` in your project. (BTW, did you use the project editor or create it by hand?)

This may be a separate bug but for now can you provide us with a (sanitized) copy of your nunit project to serve as a repro?

**Comment by Roemer** [comment]
Sure. See here: https://github.com/TestStack/White/blob/nunit/tools/NUnit/RunTests.bat
There I commented out the crashing call.

**Comment by CharliePoole** [comment]
Your project uses the default for application base, which is the directory containing the project file. Your assemblies live outside of that base, so .NET cannot load them.

You can add the appbase attribute to either the Settings element or the config element.

Alternatively, the project editor does all this stuff for you.

**Comment by Roemer** [comment]
I don't really get it. The nunit.framework.dll sits beside each assembly I want to test. So when giving the  assemblies directly to nunit3-console.exe it seems to use the path of the assembly to test as appbase. So each assembly there has it's own appbase. I don't see a way to do this with the .nunit file. Only a global appbase which is for all assemblies.

**Comment by Roemer** [comment]
Okay, for some reason I got it working. This is the final file:
```
<NUnitProject>
  <Settings activeconfig="Debug" processModel="Default" domainUsage="Default" appbase="..\..\src" />
  <Config name="Debug" binpathtype="Auto" appbase="">
    <assembly path="TestStack.White.ScreenObjects\bin\Debug\TestStack.White.ScreenObjects.UITests.dll" />
    <assembly path="TestStack.White.UITests\bin\Debug\TestStack.White.UITests.dll" />
    <assembly path="TestStack.White.UnitTests\bin\Debug\TestStack.White.UnitTests.dll" />
    <assembly path="TestStack.White.WebBrowser.UITests\bin\Debug\TestStack.White.WebBrowser.UITests.dll" />
    <assembly path="TestStack.White.WebBrowser.UnitTests\bin\Debug\TestStack.White.WebBrowser.UnitTests.dll" />
  </Config>
</NUnitProject>
```

**Comment by CharliePoole** [comment]
@Roemer Sounds like you do get it. :-) NUnit works differently for assemblies specified on the command-line and those listed in a project.

Assemblies on the command-line use the directory containing them as the application base if they are all run in different AppDomains. (If you force them into into the same AppDomain, NUnit tries to figure out a common base and errors if it can't find one.)

Assemblies in a project file default to using the location of that file as an appbase. You can change it for each config or globally, but not for each assembly. The logic for this is that allowing you to specify it for each assembly would create the possibility of several conflicts in the file, for which we would have to generate error messages. The current approach keeps it simple but does not allow you to place assemblies in a project unless they have a common appbase. We could conceivably change the default behavior, but this would be at the expense of having different defaults depending on the settings for domainUsage and processModel. I think that would be even more confusing.

Your project file changes are exactly what is needed. You could, of course, remove the Default entries, giving you

```
<Settings activeconfig="Debug" appbase="..\..\src" />
  <Config name="Debug">
```

As you discovered, a hand-edited project file must specify the path to each assembly relative to the ApplicationBase. Relative paths are used externally with absolute paths constructed upon execution. Using the Project Editor, the paths should always be saved in the correct format.

**Comment by Roemer** [comment]
Thanks! Then I figured it out correctly! I think what you wrote above would fit somewhere in the wiki pretty good.

**Comment by CharliePoole** [comment]
I think it's all on this page...
  https://github.com/nunit/nunit/wiki/NUnit-Project-XML-Format

Finding the page is the trick, even just now for me. :-)

**Comment by CharliePoole** [comment]
Maybe I should add some of what I wrote here as a note.

**Comment by Roemer** [comment]
Yes, and maybe a small example :) like the file I have not in the end.
