### ISSUE TITLE
Running One Parallelizable selected test in VS2013 gives an error 

### ISSUE THREAD

**Issue by aharrim** [nunit/nunit#1016]
So am new to the whole NUnit framework so be patient with me . I've contacted the customer service of "Sauce Labs" and they recommended it me to Use NUnit over Mbunit and they gave me an example . I tried to run one selected test , it gave me : System.Reflection.TargetInvocationException, Exception thrown executing tests . but using running all , it works . I asked the customer service he told me , it is a known issue and i can't run one selected Parallelizable  test at a time . Is it true ?!!
* P.S  I attached the file here , thanks :) 
[example.docx](https://github.com/nunit/nunit/files/33094/example.docx)

**Comment by rprouse** [comment]
I assume you are using the Visual Studio test adapter to run your tests. This was a known issue. Please update your project to use RC 2 of the NUnit Framework and update the NUnit Visual Studio Extension to CTP 6 and restart Visual Studio. This should fix the issue.

Please let us know if it works for you so we can close the issue.

**Comment by aharrim** [comment]
Yup it is working , Thanks :)

**Comment by CharliePoole** [comment]
For the record, since others may see this issue, the fix is due to a general incompatibility between NUnit and that version of the adapter. There has been no past problem with running a single parallelizable test. A single test just runs by itself. :-)
