### ISSUE TITLE
Return better information about assembly load failures

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1026]
A non-runnable test suite is returned when an assembly cannot be loaded for one reason or another. The only information that distinguishes various reasons for an invalid suite is the message contained in the _SKIPREASON property.

This is a problem when a special runner (like the VS adapter) is calling the engine. The VS adapter currently tests the message and changes it to a different message that makes sense in the context of the adapter. Message text can change and may be localized, so it would be better to have an error code of some kind as an XML attribute.

**Comment by rprouse** [comment]
No progress or comments since 2016, closing.
