### ISSUE TITLE
Support additional types for built in tolerance

### ISSUE THREAD

**Issue by appel1** [nunit/nunit#1029]
Sometimes it would be useful if you could use the built-in tolerance mechanism with custom types. At least delta tolerance could be done by looking for subtract operator and less than operator alternatively IComparable/IComparable<T>.

**Comment by CharliePoole** [comment]
I think it's a good idea to generalize this. The current structure of NUnitEqualityComparer might need to change.

One alternative to your suggestion would be to have objects implement a method for comparing within a tolerance. Such a method might be provided by an extension method in your tests.

**Comment by appel1** [comment]
Related, but perhaps a separate issue, would be to allow for different kinds of tolerances. Continuing your extension method idea it could be done by annotating the extension methods with a key you can then specify together with the tolerance.

**Comment by CharliePoole** [comment]
Are you referring to other kinds of tolerance than those already supported
by the Tolerance Type?

**Comment by appel1** [comment]
Yes. Not sure how important it is though since you can work around it by using a custom comparer instead. But it would be nice so that the tolerance method and value is included in the test failure output as the built-in tolerance does.

**Comment by CharliePoole** [comment]
More precisely, I was asking what added types of tolerance you can imagine.
The ToleranceMode enum supports Linear, PerCent and Ulps. Is this the level
at which you would hope to see it extensible, or do you mean something else
by "different kinds" - I'd just like to spell out what we might potentially
do with this idea.

**Comment by appel1** [comment]
I had missed that Ulps already existed. Sorry about that.

**Comment by appel1** [comment]
Unfortunately Ulps doesn't quite meet our needs. What we want is to compare with a number of significant digits but Ulps doesn't work if one of the compared values is 0.

**Comment by CharliePoole** [comment]
I'm glad we pursued this discussion then. I would view significant digits as a fundamentally new way to specify tolerance, which could be added to NUnit. Should we change the title of this issue to cover that or would you rather create a new issue?

**Comment by appel1** [comment]
I'll create a new issue since the original topic in this issue, supporting tolerance for custom types, is still valid.

**Comment by rprouse** [comment]
@nunit/contributors do you think we should promote this from an idea to the backlog?

I vote to close.

**Comment by CharliePoole** [comment]
I vote to close as well.

**Comment by rprouse** [comment]
I am closing old Idea issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
