### ISSUE TITLE
`&quot;` appearing in wiki documentation

### ISSUE THREAD

**Issue by jamiehumphries** [nunit/nunit#1036]
The documentation has`&quot;` a few times where there should be `"`. For example on [the Category Attribute page](https://github.com/nunit/nunit/wiki/Category-Attribute) :

```csharp
  [TestFixture]
  [Category(&quot;LongRunning&quot;)]
  public class LongRunningTests
  {
    // ...
  }
```

There are quite a few bits like this actually, e.g. `&lt;` and `&gt` on [Explicit Attribute](https://github.com/nunit/nunit/wiki/Explicit-Attribute):
```vb
Imports System
Imports Nunit.Framework

Namespace Nunit.Tests

  &lt;TestFixture(), Explicit()&gt;
  Public Class ExplicitTests
    &#39; ...
  End Class
End Namespace
```

**Comment by CharliePoole** [comment]
As you may have guessed, the docs were copied from an html representation. We'll fix these as we find them. The two pages you pointed out are fixed now.

**Comment by jamiehumphries** [comment]
Is there any way to submit patches or pull requests for the docs? I've noticed a few things as I have gone through that I could tidy up along the way.
