### ISSUE TITLE
Async tests not working on Windows 10 Universal

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#1037]
Copied from nunit/nunit.xamarin#35 reported by @tofutim. I have confirmed that this is an issue with the portable framework, so may be an issue with other platforms.

From the other issue

Is this a UWP, nunit, nunit.runners issue? I added this to the tests in this solution after seeing it in mine. This is a result from the UWP emulator (Windows 10 mobile) in VS2015 on Server 2012 R2.

        [Test]
        public async Task AsyncTest()
        {
            var result = await anInt();
            Assert.AreEqual(42, result);
        }

        private async Task<int> anInt()
        {
            return 42;
        }

![image](https://cloud.githubusercontent.com/assets/157766/11246511/cef21880-8dcc-11e5-88cf-613c49124dc2.png)

**Comment by rprouse** [comment]
The offending code is in `AsyncInvocationRegion.cs`

```C#
        private class AsyncTaskInvocationRegion : AsyncInvocationRegion
        {
            private const string TaskWaitMethod = "Wait";
            private const string TaskResultProperty = "Result";
            private const string SystemAggregateException = "System.AggregateException";
            private const string InnerExceptionsProperty = "InnerExceptions";
            private const BindingFlags TaskResultPropertyBindingFlags = BindingFlags.Instance | BindingFlags.Public;

            public override object WaitForPendingOperationsToComplete(object invocationResult)
            {
                try
                {
                    invocationResult.GetType().GetMethod(TaskWaitMethod, new Type[0]).Invoke(invocationResult, null);
                }
                catch (TargetInvocationException e)
                {
                    IList<Exception> innerExceptions = GetAllExceptions(e.InnerException);

#if NET_4_5 || PORTABLE
                    ExceptionDispatchInfo.Capture(innerExceptions[0]).Throw();
#elif NET_4_0
                    PreserveStackTrace(innerExceptions[0]);
                    throw innerExceptions[0];
#endif
                }

                PropertyInfo taskResultProperty = invocationResult.GetType().GetProperty(TaskResultProperty, TaskResultPropertyBindingFlags);

                return taskResultProperty != null ? taskResultProperty.GetValue(invocationResult, null) : invocationResult;
            }
        }
```

Notice, we reference methods and properties by name, then use reflection to access them. This is dangerous on multiple platforms where they may not be available. In this case, the Result property is not available when we try to get the `taskResultProperty`

I think this is pretty serious, possibly a candidate for a 3.0.1 release?

**Comment by tofutim** [comment]
should async tests work in UWP?

**Comment by rprouse** [comment]
They should work in UWP, but they don't because of the code outlined in this issue. To test async in UWP, we will need to fix and push an update to the framework.

**Comment by tofutim** [comment]
probably you saw this already? http://stackoverflow.com/questions/20446555/in-winrt-why-does-calling-task-result-from-a-synchronous-context-block-my-app and http://blogs.msdn.com/b/pfxteam/archive/2011/01/13/10115163.aspx.

**Comment by tofutim** [comment]
I think 'Result' is in UWP. https://msdn.microsoft.com/en-us/library/dd321468(v=vs.110).aspx

**Comment by rprouse** [comment]
I have a fix for this. I have tested in a Windows 10 app, but don't know how to write unit tests for it. The code above needs to be changed to the following.

```C#
        private class AsyncTaskInvocationRegion : AsyncInvocationRegion
        {
            private const string TaskWaitMethod = "Wait";
            private const string TaskResultProperty = "Result";
            private const string VoidTaskResultType = "VoidTaskResult";
            private const string SystemAggregateException = "System.AggregateException";
            private const string InnerExceptionsProperty = "InnerExceptions";
            private const BindingFlags TaskResultPropertyBindingFlags = BindingFlags.Instance | BindingFlags.Public;

            public override object WaitForPendingOperationsToComplete(object invocationResult)
            {
                try
                {
                    invocationResult.GetType().GetMethod(TaskWaitMethod, new Type[0]).Invoke(invocationResult, null);
                }
                catch (TargetInvocationException e)
                {
                    IList<Exception> innerExceptions = GetAllExceptions(e.InnerException);

#if NET_4_5 || PORTABLE
                    ExceptionDispatchInfo.Capture(innerExceptions[0]).Throw();
#elif NET_4_0
                    PreserveStackTrace(innerExceptions[0]);
                    throw innerExceptions[0];
#endif
                }

                var args = invocationResult.GetType().GetGenericArguments();
                if (args != null && args.Length == 1 && args[0].Name == VoidTaskResultType)
                {
                    return null;
                }
                PropertyInfo taskResultProperty = invocationResult.GetType().GetProperty(TaskResultProperty, TaskResultPropertyBindingFlags);

                return taskResultProperty != null ? taskResultProperty.GetValue(invocationResult, null) : invocationResult;
            }
        }
```

This happens for all tests that have the signature `public async Task TestMethod()`. On some platforms, you cannot get the result property if the invocation result is of type `Task<VoidTaskResult>` (which I think is mapping to plain old `Task`), it will throw an exception. I check if the result is of that type and return null instead of trying to pull the value out of the result because I know there won't be one.

I tested with tests with a very long `await Task.Delay(20000)` to ensure that this does not return before the test ran to completion. The WaitForPendingOperationsToComplete is blocking in the call to `invocationResult.GetType().GetMethod(TaskWaitMethod, new Type[0]).Invoke(invocationResult, null);` so it isn't a problem.

@CharliePoole, I haven't checked in a PR for this because I wanted to confirm that this is worthy of a 3.0.1 release, possibly along with a few other issues you have flagged. If that is so, I will start a 3.0.1 release branch and create the PR off of that.

If you have time, can you let me know if you agree with that plan? Thanks.

**Comment by CharliePoole** [comment]
I'm too tired tonight to think clearly, so I'll look at it in the AM. 

Some stuff off the bat: if this is framework only, do we have to release everything else? Could we just do a new framework release for those who need it on myget? Could we bundle an updated framework with the runner until we can bring both projects in sync?

I'll look at the code tomorrow.

**Comment by rprouse** [comment]
I want to test this with. NET Core too. It could be a more general issue on
multiple platforms which would negate a runner only update.

**Comment by tofutim** [comment]
Not sure if it helps, but I did not see this problem in Win32, iOS or
Android.
