### ISSUE TITLE
Documentation: is there a default timeout for tests?

### ISSUE THREAD

**Issue by DerekSMorin** [nunit/nunit#1040]
I looked here:

https://github.com/nunit/nunit/wiki/Timeout-Attribute

and here: 
https://github.com/nunit/nunit/wiki/MaxTime-Attribute

But what I want to know is if neither of these are specified will the test run forever, or is there a default timeout like ten minutes, or an hour? ( assuming I have a really long running test, or an infinite loop )

I am not suggesting that there SHOULD be a default timeout, I just want to know what the behaviour is.

**Comment by CharliePoole** [comment]
There is no default timeout (or if you prefer, it's zero).

I updated the TimeoutAttribute doc page to make this clear.

**Comment by DerekSMorin** [comment]
Perfect!  Thanks!

**Comment by komdil** [comment]
It would be great to have a default timeout. We have some scenarios that we need it:https://stackoverflow.com/questions/73386546/setting-default-timeout-in-nunit-tests
