### ISSUE TITLE
NUnit2XmlResult Writer is reporting Sucess when test fails

### ISSUE THREAD

**Issue by dpkano** [nunit/nunit#1041]
File: nunit/src/NUnitEngine/Addins/nunit-v2-result-writer/NUnit2XmlResultWriter.cs
240: if (label != null && label != string.Empty)
241:            resultState += ":" + label;

Seems incompatible with the implementation of:

244: xmlWriter.WriteAttributeString("result", TranslateResult(resultState, label));

This is making a failing tests pass. e.g. resultState=='Failed', label=='Error' ===> Translates to 'Success'

**Comment by CharliePoole** [comment]
I confirmed this from looking at the code. I called it priority high, although I realize it could be a show-stopper for some folks who rely on the V2 Xml output. If we get more "critical for a subset of users" bugs, we may want to re-classify them all as critical and trigger a 3.0.1 release.

**Comment by rprouse** [comment]
I should have taken this when I was fixing the other NUnit 2 XML issue. Grabbing it now.

**Comment by rprouse** [comment]
@dpkano excellent bug report, thanks, it made it very easy to fix the problem. The hardest part was reading through the XML produced by our mock assemblies to create a test case for this :+1:

**Comment by rprouse** [comment]
Closed with PR #1077
