### ISSUE TITLE
NUnit2 reports on 3.0 is different than 2.6.4

### ISSUE THREAD

**Issue by dpkano** [nunit/nunit#1042]
NUnit.Framework.DescriptionAttribute and NUnit.Framework.CategoryAttribute are mapped under Properties xml tag. NUnit.Framework.DescriptionAttribute used to be a test-case description attribute and NUnit.Framework.CategoryAttribute used to be under Categories xml tag.

This is not critical and the following xslt can be used to transform the xml

```xml
  <xsl:template match="test-case/properties">
    <xsl:for-each select="property[@name!='_CATEGORIES']">
      <xsl:attribute name="{@name}">
        <xsl:value-of select="@value"/>
      </xsl:attribute>
    </xsl:for-each>
  
    <categories>
      <xsl:for-each select="property[@name='_CATEGORIES']">
        <xsl:element name="category">
          <xsl:attribute name="name">
            <xsl:value-of select="@value"/>
          </xsl:attribute>
        </xsl:element>
      </xsl:for-each>
    </categories>
  </xsl:template>
```

Example:
NUnit3 repoting v2:
```xml
  <test-case name="Dummy" executed="True" result="Success" success="False" time="5.823" asserts="1">
     <properties>
        <property name="_DESCRIPTION" value="Dummy" />
        <property name="_CATEGORIES" value="SmokeTest" />
      </properties>
```
NUnit 2.6.4:
```xml
<test-case name="Dummy" executed="True" result="Success" success="False" time="5.823" asserts="1" description="Dummy">
    <categories>
        <category name="SmokeTest" >
    </categories>
```

**Update:**
     1)
     On NUnitv2 the testcase name contains the full name of the method: 'namespace'.'classname'.'methodname' on NUnitv3 reporting v2 just the method name is displayed.
      This can be fixed by changing the NUnit2XmlResultWriter.cs file at line 214 from:
```C#
xmlWriter.WriteAttributeString("name", result.GetAttribute("name"));
```

to

```C#
xmlWriter.WriteAttributeString("name", result.GetAttribute("fullname"));
```

     2)
     The NUnit version attribute on NUnitv2 shows: <environment nunit-version="1.0.0.0"
     Because it is fetching the version from the addin assembly version which is 1.0.0.0

**Comment by CharliePoole** [comment]
Although easily corrected by the user, I think it's still a high-priority bug because it doesn't correctly match what programs that read the V2 format expect to find. I'm surprised that nobody noticed this all through the multiple alphas and betas, but here we are!

**Comment by imakowski** [comment]
There is also a difference when you run nunit3 with output to nunit2 format. test-suite type was ParameterizedTest in Nunit2 and now it is ParameterizedMethod
Nunit2
`
<test-suite type="ParameterizedTest" name="PointTest" executed="True" result="Success" success="True" time="0.068" asserts="0">
	<results>
		<test-case name="PointTest(&quot;String&quot;,&quot;a&quot;)" executed="True" result="Success" success="True" time="0.016" asserts="2" />
		<test-case name="PointTest(&quot;String[]&quot;,System.String[])" executed="True" result="Success" success="True" time="0.005" asserts="2" />
	</results>
</test-suite>
`
Nunit3
`
<test-suite type="ParameterizedMethod" name="PointTest" executed="True" result="Success" success="True" time="0.026" asserts="48">
	<results>
		<test-case name="PointTest(&quot;String&quot;,&quot;a&quot;)" executed="True" result="Success" success="True" time="0.016" asserts="2" />
		<test-case name="PointTest(&quot;String[]&quot;,System.String[])" executed="True" result="Success" success="True" time="0.005" asserts="2" />
	</results>
</test-suite>
`

**Comment by rprouse** [comment]
@imakowski thanks for the report. Rather than track this in a closed issue, I am going to create a new issue for it.

**Comment by CharliePoole** [comment]
Since this reported issue has been fixed , closed and released in an update, it would be better to report a new issue if the problem affects your reports. It will get attention that way. Of course, any transforms that just look at test cases won't be affected.
