### ISSUE TITLE
Re-order Test Summary Errors/Failures

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#1044]
This is a little detail that has always bugged me but I have never fixed. Our current test summary looks like this,

```
Test Run Summary
    Overall result: Failed
   Tests run: 29, Passed: 28, Errors: 0, Failures: 1, Inconclusive: 0
     Not run: 0, Invalid: 0, Ignored: 0, Explicit: 0, Skipped: 0
  Start time: 2015-11-19 21:14:28Z
    End time: 2015-11-19 21:14:28Z
    Duration: 0.344 seconds
```

Our main purpose is Passed/Failed tests, but Errors come before Failures. I also think Failures should be renamed to Failed to match Passed.

I think it should look like this,

```
Test Run Summary
    Overall result: Failed
   Tests run: 29, Passed: 28, Failed: 1, Errors: 0, Inconclusive: 0
     Not run: 0, Invalid: 0, Ignored: 0, Explicit: 0, Skipped: 0
  Start time: 2015-11-19 21:14:28Z
    End time: 2015-11-19 21:14:28Z
    Duration: 0.344 seconds
```

If we do this NUnitLite will probably need to be changed too.

**Comment by CharliePoole** [comment]
Internally, TestStatus.Failed includes Failures, Errors, Cancelled and Non-Runnable. I agree that this needs to be worded in a way that makes sense to the user, but I think we should also keep it in sync with our internal statuses, even if that means changing some names internally.
