### ISSUE TITLE
Broken link on "Breaking Changes" wiki page

### ISSUE THREAD

**Issue by ermshiperete** [nunit/nunit#1047]
The [Breaking Changes](https://github.com/nunit/nunit/wiki/Breaking-Changes) page links to https://github.com/nunit/nunit/wiki/SetUp-and-TearDown which doesn't exist.

It should link to https://github.com/nunit/nunit/wiki/SetUp-and-TearDown-Changes instead.

**Comment by CharliePoole** [comment]
Thanks, I updated the page.
