### ISSUE TITLE
Wiki: Add TestStatus NUnit3 migration tips

### ISSUE THREAD

**Issue by linquize** [nunit/nunit#1051]
Wiki: Please add `TestStatus` NUnit3 migration tips

From NUnit2
```
TestContext.CurrentContext.Result.Status == TestStatus.Failed
TestContext.CurrentContext.Result.State == TestState.Failure
```
to NUnit3
```
TestContext.CurrentContext.Result.Outcome == ResultState.Failure
```

**Comment by CharliePoole** [comment]
So you are looking for a description of how the NUnit 3.0 TestContext is different from NUnit V2? I suppose this could go in "Breaking Changes."

I'll have to look at the code, but I hope the Intellisense gives you what you need!

**Comment by linquize** [comment]
Yes, I am talking about breaking changes to document in wiki.
About TestState / TestStatus: what are the difference?

**Comment by CharliePoole** [comment]
See the docs.

The exact meaning of TestState and TestStatus for NUnit V2 is described here:
    http://nunit.org/index.php?p=testContext&r=2.6.4

The meaning of the various members of Outcome are described here:
    https://github.com/nunit/nunit/wiki/TestContext 

I have added a reference to TestContext to the Breaking Changes page.
