### ISSUE TITLE
NUnit 3.0.0 without nunit.exe

### ISSUE THREAD

**Issue by leandrosa** [nunit/nunit#1052]
Mrs, when I donwloaded the last version NUnit (3.0.0), I missed the file nunit.exe. Where are it in this new version?

Best Guards.
Thks

**Comment by rprouse** [comment]
nunit.exe is the GUI runner. We do not currently have a GUI runner for NUnit 3.0, it will be released separately in the future. I would suggest you run your tests on the console with nunit3-console, or in Visual Studio using the test adapter.

**Comment by leandrosa** [comment]
Thanks for your help. Regards.
