### ISSUE TITLE
nunit3 console runner --where option does not return error on invalid selection string

### ISSUE THREAD

**Issue by Inirit** [nunit/nunit#1055]
The nunit3 console runner --where option does not return an error on an invalid selection string.

For a while I was trying to use the following selection string:
--where "cat == Pri1 AND cat != WIP"

This selection string was not properly filtering out "WIP" tests and was instead just running all "Pri1" tests. After rereading the documentation it occurred to me that "AND" (with all capital letters) is not a valid logical operator in this context. Switching this out for "&&" or "and" results in the expected filtering.

My usage of the --where option is technically incorrect, but with this incorrect usage I would have expected an error claiming that my string was not of a valid format. Instead the console runner silently continued with test execution with an incorrect subset of tests.

It would also be cool if "AND" (and other similar operators with capital letters) was valid, but that's just my opinion.

**Comment by CharliePoole** [comment]
I confirmed this by examining the code.

**Comment by rprouse** [comment]
Fixed by PR #1085
