### ISSUE TITLE
Remove "Version 3" from NUnit Nuget Package

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#1060]
The title in NuGet shows up as NUnit Version 3 3.0.0 which is redundant and confuses some users looking for 2.6.4.

https://www.nuget.org/packages/NUnit/

**Comment by rprouse** [comment]
I created a 3.0.1 milestone. If we decide to do a hotfix, we should do this then. If not, it can be moved to 3.2.

**Comment by CharliePoole** [comment]
Probably good to have a bug that documents the change. It's already fixed. (You will see it when nuget re-indexes it)

Re milestones: I've been doing the opposite - putting things in 3.2 with the idea they could move to 3.0.1. My logic is that a hotfix is not something you plan but it doesn't matter really. One of us is an optimist I guess - don't know which is which though. :-)

**Comment by rprouse** [comment]
I am reopening so we can remove the Version 3 from the nuspec so that it doesn't mistakenly change the title with the next release.

**Comment by CharliePoole** [comment]
Looks like GitHub may not closer linked issues until they are merged into master. In this situation, I think it's better tracking to close it, however.
