### ISSUE TITLE
Console.WriteLine statements int "OneTimeSetUp" and "OneTimeTearDown" annotated methods are not directed to the console when using nunit3-console.exe runner

### ISSUE THREAD

**Issue by kdubau** [nunit/nunit#1062]
Given this test fixture: 
```csharp
	[TestFixture]
	public class TestClass
	{
		[OneTimeSetUp]
		public void FixtureSetup ()
		{
			Console.WriteLine ("FixSetUp");
		}

		[SetUp]
		public void SetUp ()
		{
			Console.WriteLine ("SetUp");
		}

		[TearDown]
		public void TearDown ()
		{
			Console.WriteLine ("TearDown");
		}

		[OneTimeTearDown]
		public void FixtureTearDown ()
		{
			Console.WriteLine ("FixTearDown");
		}

		[Test]
		public void Test ()
		{
			Console.WriteLine ("Test");
		}
	}
```

It would be expected that `Console.WriteLine ("FixSetUp");` and `Console.WriteLine ("FixTearDown");` are correctly printed to the console. However the actual output is as follows:

```
NUnit Console Runner 3.0.5797 
Copyright (C) 2015 Charlie Poole

Runtime Environment
   OS Version: MacOSX 15.0.0.0 
  CLR Version: 4.0.30319.17020

Test Files
    bin/Debug/XQA.XS.Tests.dll

Test Filters
    Test: XQA.XS.Tests.TestClass.Test

=> XQA.XS.Tests.TestClass.Test
SetUp
Test
TearDown

Run Settings
    WorkDirectory: <omitted>
    NumberOfTestWorkers: 4

Test Run Summary
    Overall result: Passed
   Tests run: 1, Passed: 1, Errors: 0, Failures: 0, Inconclusive: 0
     Not run: 0, Invalid: 0, Ignored: 0, Explicit: 0, Skipped: 0
  Start time: 2015-11-23 20:02:32Z
    End time: 2015-11-23 20:02:32Z
    Duration: 0.063 seconds

Results (nunit3) saved as TestResult.xml
```
Notice there is no appearance of "FixSetUp" or "FixTearDown" - this is a major issue for build systems that rely on Console output to trigger events (such as the [mono build system] (https://github.com/mono/monkeywrench)).

Thanks!

**Comment by CharliePoole** [comment]
Seems like it should work, especially since the redirection happens before any tests run. I suspect we are capturing it and throwing it away, since it does not apply to any individual test output.

When you  talk about the output triggering events, I hope you are not expecting it to be synchronous. Output from each test does not go to the console until the test is finished. Unless we do something new and different, Output for a suite will not arrive until the suite is finished.

Have you tried using error output?

Depending on how this is used, we may want to make capture of text output an option. If we don't capture it, folks wanting to write to the test output would have to use the TestContext to write messages.

**Comment by kdubau** [comment]
We do not need it to be synchronous, printing at the end of the tests should be fine. The events are things such as "Upload file: path-to-file.file".

`Console.Error.WriteLine ("FixSetUp");` exhibits the same behavior (does not print to console).

**Comment by kdubau** [comment]
> folks wanting to write to the test output would have to use the TestContext to write messages.

Are you implying `TestContext.WriteLine ("FixSetup")` should work in the "OneTimeSetUp" and "OneTimeTearDown" annotated methods? I tested this and it is does not print (same behavior as Console) - FYI.

**Comment by CharliePoole** [comment]
That's good info. I believe you will actually find the output in the xml result file even though the console is not picking it up. That tells us a bit about where the problem is.

**Comment by rprouse** [comment]
I can confirm that neither the `Console` nor the `TestContext` is output to the console for `OneTimeSetUp` or `OneTimeTearDown`, but as you expected @CharliePoole, they are in the test result file.

**Comment by tfabris** [comment]
This was marked as closed:done in November 2015. I just ran into this issue in November 2016 with version 3.5 of Nunit. Console.WriteLine from inside [OneTimeSetup] and [OneTimeTearDown] does not produce output, but Console.WriteLine from inside [Test] does produce output.

Is this expected to have been fixed?

**Comment by CharliePoole** [comment]
This issue was the start of the discussion that eventually led to the provision of immediate output.

To summarize, NUnit supports two kinds of output: standard and immediate.

Standard output is produced using Console.Write and TextContext.Write. The text is attached to the test result.

Immediate output is produced by Console.Error, TextContext.Error and TextContext.Progress. It is displayed immediately when received.

Standard output comes to the console runner at the end of the test. It is displayed for test cases but not currently for suites. The OneTimeSetUp is associated with the suite (fixture). Normally, the console only displays info from the fixture if the OneTimeSetUp fails.

You could create an issue to change this behavior or you could use immediate output.

**Comment by tfabris** [comment]
Thanks! I'll try TestContext.Progress.WriteLine() as a work-around. That will write to STDOUT instead of STDERR, correct?

**Comment by CharliePoole** [comment]
The console runner uses stdout to write everything that comes from a test, so it goes to the console screen unless you used a command-line option to redirect it. In the case of error output, it displays in red.

**Comment by GrimaceOfDespair** [comment]
I'm experiencing a similar issue. I've got a static constructor, which can throw an exception, resulting in:
```
Test Name:	GivenAServiceContract_WhenListingTheOperationContracts_ThenTheirNamesShouldBeUnique
Test FullName:	ServiceContractTests.GivenAServiceContract_WhenListingTheOperationContracts_ThenTheirNamesShouldBeUnique
Test Source:	C:\Src\ServiceContractTests.cs : line 27
Test Outcome:	Failed
Test Duration:	0:00:00.0000001

Result Message:	
OneTimeSetUp: System.TypeInitializationException : The type initializer for 'ServiceContractTests' threw an exception.
  ----> System.Exception : Foo bar
```

I'm trying to use TestCases based on the outcome of that static constructor:
```c#
[TestFixture]
public class ServiceContractTests
{
    private static HashSet<Type> ServiceContracts;

    static ServiceContractTests()
    {
        TestContext.Progress.WriteLine("Custom message");
        TestContext.Error.WriteLine("Custom message");
        Console.WriteLine("Custom message");
        Console.Error.WriteLine("Custom message");
        throw new Exception("Foo bar");
    }

    [Test]
    [TestCaseSource("ServiceContracts")]
    public void GivenAServiceContract_WhenListingTheOperationContracts_ThenTheirNamesShouldBeUnique(Type interfaceType) {
    }
}
```

None of the `Custom message`s end up in my Visual Studio test console.

**Comment by CharliePoole** [comment]
Our advice on test class constructors has remained the same for many years.
They should be very sparse if they exist at all. Remember that NUnit makes
no guarantees as to when or even how many times your class is constructed.
That's why the various setup methods exist.

In your case, there is the added problem of trying to use TextContext at a
time when no test is being executed. That output is simply discarded.

**Comment by GrimaceOfDespair** [comment]
Ok, clear. Sorry for having disregarded these apparently long lasting guidelines, so thanks for your patience on that :)

By the nature of the error message, I was under the impression that under the hood, OneTimeSetup would result in the same behaviour as a static constructor. Deducting from that, I was expecting some data in the output, if it wasn't for the fact that the exception details _do_ end up in there.

Otoh, quite frankly, I try avoid static constructors in tests too, but as far as I could tell, that's the only way of using TestCaseSource. So would you advice on ditching TestCaseSource altogether and refactoring my test? Or am I actually missing on how to properly apply TestCaseSource for my scenario?

**Comment by rprouse** [comment]
@GrimaceOfDespair you are using `TestCaseSource` incorrectly. I assume that your static constructor is being used to initialize your `TestCaseSource`. That works, but most people make the `TestCaseSource` a property or method that contains the code that you have in your static constructor and then `yield return` the results.

Another small tip, if you have the `TestCaseSource` on a test, you don't need the `[Test]` attribute.

**Comment by tfabris** [comment]
I tried using TestContext.Progress.WriteLine() and I get the same result: I only get ouput from the [Test] methods and no output from the [OneTimeSetUp] and [OneTimeTear Down] methods.

**Comment by CharliePoole** [comment]
Here's what I get from the current code, runing the ConsoleOutputTests fixture (it's explicit and so has to be run by name):

```
D:\Dev\NUnit\nunit-console\bin\Debug>nunit3-console nunit3-console.tests.dll -te
st NUnit.ConsoleRunner.Tests.ConsoleOutputTests
NUnit Console Runner 3.6.0 (Debug)
Copyright (C) 2016 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.10586.0
  CLR Version: 4.0.30319.42000

Test Files
    nunit3-console.tests.dll

Test Filters
    Test: NUnit.ConsoleRunner.Tests.ConsoleOutputTests

=> NUnit.ConsoleRunner.Tests.ConsoleOutputTests
OneTimeSetUp: Console.Error.WriteLine()
=> NUnit.ConsoleRunner.Tests.ConsoleOutputTests.ConsoleEncoding
SetUp: Console.Error.WriteLine()
TearDown: Console.Error.WriteLine()
SetUp: Console.WriteLine()
SetUp: TestContext.WriteLine()
ÑÜnit·
TearDown: Console.WriteLine()
TearDown: TestContext.WriteLine()
=> NUnit.ConsoleRunner.Tests.ConsoleOutputTests.Test
SetUp: Console.Error.WriteLine()
Test: Console.Error.WriteLine()
TearDown: Console.Error.WriteLine()
SetUp: Console.WriteLine()
SetUp: TestContext.WriteLine()
Test: Console.WriteLine()
Test: TestContext.WriteLine()
TearDown: Console.WriteLine()
TearDown: TestContext.WriteLine()
=> NUnit.ConsoleRunner.Tests.ConsoleOutputTests
OneTimeTearDown: Console.Error.WriteLine()
OneTimeSetUp: Console.WriteLine()
OneTimeSetUp: TestContext.WriteLine()
OneTimeTearDown: Console.WriteLine()
OneTimeTearDown: TestContext.WriteLine()

Run Settings
    DisposeRunners: True
    WorkDirectory: D:\Dev\NUnit\nunit-console\bin\Debug
    ImageRuntimeVersion: 2.0.50727
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    NumberOfTestWorkers: 4

Test Run Summary
  Overall result: Passed
  Test Count: 2, Passed: 2, Failed: 0, Inconclusive: 0, Skipped: 0
  Start time: 2016-11-15 04:45:19Z
    End time: 2016-11-15 04:45:19Z
    Duration: 0.364 seconds

Results (nunit3) saved as TestResult.xml
```

This test dates back before we had TestContext.Progress, but I would expect that to display in the same way that the Error output displays.

Note that the non-immediate output does appear, but only after the fixture has run completely. The immediate (Error) output appears in the order that one would expect.

Based on the experiment, I would say this issue fixed what it was supposed to fix. @tfabris Do you get different output on similar tests? You can copy the test file ConsoleOutputTests.cs from github and run with that if you like.

**Comment by GrimaceOfDespair** [comment]
just fyi, this is my VS console output on [these tests](https://github.com/nunit/nunit-console/blob/master/src/NUnitConsole/nunit3-console.tests/ConsoleOutputTests.cs):

![image](https://cloud.githubusercontent.com/assets/228782/20299332/cd1bbef0-ab1a-11e6-8d05-2ea6aab0229d.png)

**Comment by CharliePoole** [comment]
@GrimaceOfDespair Are you running vstest.console? That would be a completely different issue. None of these writes are displayed directly. They are events that each runner has to handle. This issue was about how the nunit console runner handles it. We probably need another for the nunit VS adapter.

**Comment by GrimaceOfDespair** [comment]
I was under the impression, again wrongly, that the Standard Output was "just a capture" of the same stuff that came out of the console. I guess in theory it is, but in practice, there's a difference.

Apparently, I'm a bit confused as to which project I should be talking to whom, though that probably will most of the time be you :) You want me to file an issue with nunit3-vs-adapter?

**Comment by rprouse** [comment]
@GrimaceOfDespair I will copy this issue across to the adapter project and edit it to reflect your issues.

**Comment by AndreasKarz** [comment]
This works -- use **TestContext.Progress.WriteLine**

```csharp
using NUnit.Framework;

namespace MyFunkyTests
{
    [SetUpFixture]
    public class NUnitGlobalHooks
    {
        [OneTimeSetUp]
        public void RunBeforeAnyTests()
        {
            TestContext.Progress.WriteLine("=========>OneTimeSetUp");
        }

        [OneTimeTearDown]
        public void RunAfterAnyTests()
        {
            TestContext.Progress.WriteLine("=========>OneTimeTearDown");
        }
    }
}

```
