### ISSUE TITLE
My ISuiteBuilder extension isn't being picked up

### ISSUE THREAD

**Issue by jon-p** [nunit/nunit#1075]
I have an ISuiteBuilder extension that isn't being picked up by NUnit3. 

    [NUnit.Engine.Extensibility.Extension(Path = "/NUnit/Engine/TypeExtensions/ISuiteBuilder")]
    public class EnvironmentSuiteBuilder : ISuiteBuilder

It isn't clear to be where I should put a .addins file for NUnit to pick it up.

If it helps I'm using NCrunch to run the tests...

**Comment by CharliePoole** [comment]
There is no ISuiteBuilder extension point in NUnit. See the documentation at 
    https://github.com/nunit/nunit/wiki/Engine-Extensibility
which has a list of the three extension points currently available.

I believe that NCrunch bypasses the engine anyway, so it's a moot point.

Framework extensibility is handled in a different way in NUnit 3.0. See
    https://github.com/nunit/nunit/wiki/Framework-Extensibility
Unfortunately, you probably want a custom attribute, for which the documentation is not yet available. Take a look at how TestFixtureAttribute does it for now.

**Comment by jon-p** [comment]
Thanks Charlie.
I'd spotted there was still a ISuiteBuilder so got my hopes up there would be a quick conversion to NUnit3. However I see what you mean from looking at the engine extensions. Apologies for wasting your time.

As you suggested i can do my test filtering with an attribute layered on top of TestFixtureAttribute. 

Thanks for all the work on NUnit3.
