### ISSUE TITLE
NUnit.Console nuget package fails to run if installed console is in the path

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#1078]
I found this while testing a Cake build script

**Steps to Reproduce**

1. Install NUnit 3.0 MSI
2. Add `C:\Program Files (x86)\NUnit.org\nunit-console` to your path
3. Add the NUnit.Console nuget to a test solution
4. Attempt to run tests in the test solution using the nuget console runner

**Results**

```
NUnit Console Runner 3.0.5797
Copyright (C) 2015 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 6.3.9600.0
  CLR Version: 4.0.30319.42000

Test Files
    ./nunit-v3/bin/Release/nunit-v3.dll

Failed to start RemoteTestAgent
```

I watched process explorer and i can't see the agent starting. If it does start, it crashes immediately.

Pretty annoying for people like me who install NUnit and add it to their path, but also work with projects with build scripts that use the NuGet runner.

**Comment by CharliePoole** [comment]
@rprouse What did you want to do with this as far as the release goes?

**Comment by rprouse** [comment]
If I can figure out why it is happening and the fix is not risky, then let's include it, but I don't think it is worth holding up 3.0.1 over. Does that sound good or do you think it is serious enough to wait for?

**Comment by CharliePoole** [comment]
Sounds good. Since you found it, I was hoping you had an idea. :-)

**Comment by rprouse** [comment]
I wish I did have an idea. I tried to debug it, but didn't have any luck. My best guess is that assemblies are being loaded from the path first, but why should that be a problem if they are the same? Maybe addins are failing to load? I may just have to dive down into Fuslog and I hate that :smile:

**Comment by CharliePoole** [comment]
@rprouse Is this still an issue?

**Comment by rprouse** [comment]
I have retested with 3.4 and this is no longer happening. Possibly because we are using a local engine now?

Closing as fixed?
