### ISSUE TITLE
"No source data found" for Generic tests

### ISSUE THREAD

**Issue by ericnewton76** [nunit/nunit#1080]
Upgraded to Nunit hoping to see this issue resolved with Nunit 3.0 but apparently its still not able to figure out source data from Generic based unit test fixtures?

I get "No source data found" messages for a generic base unit test fixture that is intended to fully test many different interface-implementing classes I have built.

**Comment by ericnewton76** [comment]
```c#
[TestFixture]
public class AssetRepoTest<T> : where T : IAssetRepo
{
    protected T Repo;
    [SetUp] protected virtual void SetUp() { Repo = CreateRepo(); }
    protected abstract T CreateRepo();
    [Test] public void SomeTest1() { }
}
```

```c#
[TestFixture]
public class FileAssetRepoTest : AssetRepoTest<FileAssetRepo>
{
    override FileAssetRepo CreateRepo() { return new FileAssetRepo("some_path_to_files"); }
    
    [Test] public void FileAssetRepo_specific_test() { /* test folder exists after some init operation */ }
}
```

```c#
[TestFixture]
public class SqlAssetRepoTest : AssetRepoTest<SqlAssetRepo>
{
    override SqlAssetRepo CreateRepo() { return new SqlAssetRepo("connection_string"); }
    
    [Test] public void SqlAssetRepo_specific_test() { /*test that some record exists after some op */ }
}
```

**Comment by CharliePoole** [comment]
@ericnewton76 Can you point me to the issue that you had hoped would be resolved? 

What is not happening in NUnit that you would like to have happen here? Have you tried setting a break on your SetUp method?

**Comment by ericnewton76** [comment]
Hi Charlie.

I was hoping to see in the Test Explorer with Nunit VS test runner:

[>] SqlAssetRepoTest (2)
  [  ] SqlAssetRepo_specific_test >>source: File3, line 6
  [  ] SomeTest >>source: File1, line 7
[>] FileAssetRepoTest (2)
  [  ] FileAssetRepo_specific_test >>source: File2, line 6
  [  ] SomeTest >>source: File1, line 7

**Comment by ericnewton76** [comment]
So I just pulled down the Nunit vs adapter "Demo" project, and I see what I would expect, and the source data seems to be matched up, so now I'm scratching my head for my project

![image](https://cloud.githubusercontent.com/assets/2211788/11508993/94c0c186-9829-11e5-990c-6a360c999ca3.png)

**Comment by ericnewton76** [comment]
Yeah, sorry charlie...  :)

Let's put this one on hold, it seems after a few days, that its working... not sure why...

**Comment by CharliePoole** [comment]
It could be that your upgrades didn't all get fetched at the same time. You need to be running CTP-7b of the adapter with the NUnit 3.0 release.

I'm going to close this. If you need to repopen an NUnit3 Adapter issue later, you can reference this for background.
