### ISSUE TITLE
[Setup] attribute is not picked up in  NUnit 3.0 in visual studio 2013/15

### ISSUE THREAD

**Issue by RavishankarSivasothy** [nunit/nunit#1081]
Method attributed with [Setup] in the base class is not picked up after updating to NUnit 3.0 from NuGet
Works fine with NUnit 2.6.4

Code snippet for further clarification

Derived class
------------------
[TestFixture]
    class LoginTest:TaskManagerBaseTest
    {
        [Test]
        public void VerifySuccessfulLogin()
        {
            Assert.AreEqual("Adra Login", BasePageObject.GetPageTitle());
////

Base class
--------------
[TestFixture]
    public class TaskManagerBaseTest
    {
        [SetUp]
        public void Init()
        {
            BasePageObject.Initialise();
///

**Comment by CharliePoole** [comment]
Please tell us what your environment is. It's not clear if you have only updated the NUnit framework or if you have also updated the console runner and (if you are using it) the adappter.

**Comment by RavishankarSivasothy** [comment]
I was trying this on both Visual Studio 2013 & 2015 installed on windows 10 64 bit.
The solution was built with C# as programming language with installed NuGet packages Selenium WebDriver, Selenium.support.UI classes and NUnit 3.0. 

The issue was solved when I downgraded NUnit version from 3.0 back to 2.6.4

**Comment by CharliePoole** [comment]
Did you
1. Update all your references to NUnit 3.0?
2. Recompile the tests against NUnit 3.0?

How do you execute your tests?

**Comment by RavishankarSivasothy** [comment]
Yes, I did 1 & 2. 
I have been using a unit testing add-in for Microsoft Visual Studio .NET - TestDriven.NET 
The current release of TestDriven.NET supports multiple unit testing frameworks including NUnit, MbUnit, MSTest etc. 
It allows to run (or debug!) tests from within Visual Studio.

http://www.testdriven.net/quickstart.aspx (A quick elaboration with screen shots)

**Comment by rprouse** [comment]
We are working with TestDriven.Net to add support for NUnit 3.0, but at this time, it runs NUnit 3.0 tests as if they are 2.6, so it doesn't work correctly. For now, you can use the NUnit 3 Test Adapter available in Visual Studio extensions. 

On Nov 29, 2015 5:05 AM, RavishankarSivasothy <notifications@github.com> wrote:

Yes, I did 1 & 2. 
I have been using a unit testing add-in for Microsoft Visual Studio .NET - TestDriven.NET 
The current release of TestDriven.NET supports multiple unit testing frameworks including NUnit, MbUnit, MSTest etc. 
It allows to run (or debug!) tests from within Visual Studio.

http://www.testdriven.net/quickstart.aspx (A quick elaboration with screen shots)

**Comment by jansotola** [comment]
FYI: The same issue occurs when using some older versions of NUnit (2.2.7 in my case).
Switching to NUnit 2.6.0 has solved it as well.

**Comment by bartvanderwal** [comment]
Just in case this helps someone:
For me this was resolved by checking the case.

I was using `[Setup]` attribute as given in the **description(( above. But I got the error 
>The type or namespace name 'SetupAttribute' could not be found (are you missing a using directive or an assembly reference?)

It simply needed to be `[SetUp]` with a capital U. Like in the given **code example** above.

Note I already had a `using NUnit.Framework;`

**Comment by CharliePoole** [comment]
Ah... and none of us noticed the spelling difference in all the discussion. How embarrassing!

**Comment by bartvanderwal** [comment]
@CharliePoole, thanks for the quick response. But like I said the casing WAS correct in the code example given. So the silly typo I described is another issue. This is confirmed when I look at the NUnit 2.6 documentation, which shows SetUp was already with a uppercase `U` in that version.
http://nunit.org/index.php?p=setup&r=2.6.4

Perhaps I shouldn't have mentioned it.
