### ISSUE TITLE
TestResult.xml missing environment element

### ISSUE THREAD

**Issue by harefoot55** [nunit/nunit#1082]
I started using the 3.0 nunit3-console.exe yesterday and noticed that my output file was missing the environment element. According to this document (https://github.com/nunit/nunit/wiki/test-result-xml-format) it is still supposed to be there. Am I missing something?

![screencap_20151128_082457](https://cloud.githubusercontent.com/assets/16060436/11452842/be8c449a-95a9-11e5-9de9-5ea662f67bd9.png)

**Comment by CharliePoole** [comment]
The environment element has been moved under each assembly-level test-suite element, since some of the attributes may have different values for each assembly. 

We'll keep this issue as a reminder to update the documentation.

**Comment by harefoot55** [comment]
Thanks for the quick reply! We searched the output and don't have an 'environment' element at all.

**Comment by CharliePoole** [comment]
In that case, please add some info about your environment: OS, target runtime of the test assembly, NUnit framework version, console-runner (I assume that's what you are using) version.

**Comment by harefoot55** [comment]
[debug to upload.xml.txt](https://github.com/nunit/nunit/files/46396/debug.to.upload.xml.txt)
![screencap_20151128_103757](https://cloud.githubusercontent.com/assets/16060436/11453350/20d020d8-95bc-11e5-9243-202427776f81.png)

I think these files have everything you asked for. OS is Server 2012R2 and I think the exact version info is in the output, but please let me know if not.

**Comment by CharliePoole** [comment]
What about the NUnit framework and console runner? I'm wondering if you may have a mismatch there.

**Comment by CharliePoole** [comment]
Also, what build of the framework are you using (net-4.5, portable, etc.)

**Comment by harefoot55** [comment]
Does this have the information you are asking for? It does look like there is a mismatch.
![screencap_20151128_145909](https://cloud.githubusercontent.com/assets/16060436/11454445/2aedbd6c-95e1-11e5-8da8-91aa6ec5860b.png)

**Comment by CharliePoole** [comment]
That's OK. What I really want is the package version. The final release packages of NUnit 3.0 include those two assemblies, so I gather you downloaded one of them. Was it the msi, a zip file, the nuget package, or what?

Then, in running your tests, what do you enter on the command-line.

**Comment by harefoot55** [comment]
I downloaded this:
NUnit.3.0.0.msi

I'll also give a picture of its contents, in case that helps.
![screencap_20151128_211854](https://cloud.githubusercontent.com/assets/16060436/11455451/b56e5134-9615-11e5-99e9-bb4f0de06f59.png)


Here's an example of what I ran:
nunit3-console.exe "ccomm.nunit" --config=prod-ohms-chrome --test=Intz.Ccomm.Web.Selenium.Tests.CcommSeleniumTests.MaleNoPrenatalCareMatches

For what it's worth, I have a workaround now, so it isn't really urgent. Also, I'm really excited about this version of NUnit; thanks for all the work on it. Everything basically works, but I just don't get the environment element.

**Comment by CharliePoole** [comment]
Did you replace all the references to NUnit V2 in your tests and recompile them?

**Comment by harefoot55** [comment]
I didn't... I didn't think about the fact that it might not be backward compatible and we still haven't fully switched over for v3. Since we have a workaround for now (we're injecting the info we need into the xml right after running the test for the time being), I'll close the issue. Thanks for all the quick responses.
