### ISSUE TITLE
TestSelectionParserTests

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1087]
The TestSelectionParser is not part of the framework, but the TestSelectionParserTests are in the framework tests.

Shouldn't the TestSelectionParserTests be in the console or nunitlite tests, and not in the framework tests?

I may have missed something?

**Comment by CharliePoole** [comment]
Quite right. TestSelectionParserTests is in common and is included in the console and framework tests. It should be in the console and nunitlite tests.

It does no harm where it is, so I'm making it low priority to move for 3.0.1.

**Comment by CharliePoole** [comment]
@oznetmaster Where are you seeing this - which projects, that is? Initially, I thought I saw it in framework tests as well, but now I can't find it!

**Comment by oznetmaster** [comment]
Actually, it apparently was moved at some point.  It is in nunitlite.tests, where it belongs.

 

I apparently missed that move :(

 

Sorry.
