### ISSUE TITLE
OneTimeSetUp is not fired

### ISSUE THREAD

**Issue by OlgaCoop** [nunit/nunit#1089]
I use NUnit 3.0 and run it in Visual Studio 2012.
Seems method with attribute OneTimeSetUp is never fired.
  
    [TestFixture]
    public class InitializationTest
    {
        private string _initString;

        [OneTimeSetUp]
        public void Init()
        {
            _initString = "Init it";
        }

        [Test]
        public void InitCheckTest()
        {
            Assert.AreEqual("Init it", _initString);
        }
    }

**Comment by rprouse** [comment]
What do you use to run your tests in Visual Studio. Resharper does not support NUnit 3.0 yet. You need to use the NUnit 3 Test Adapter. 

On Nov 29, 2015 8:09 AM, OlgaCoop <notifications@github.com> wrote:

I use NUnit 3.0 and run it in Visual Studio 2012.
Seems method with attribute OneTimeSetUp is never fired.

[TestFixture] public class InitializationTest { private string _initString; [OneTimeSetUp] public void Init() { _initString = "Init it"; } [Test] public void InitCheckTest() { Assert.AreEqual("Init it", _initString); } }

**Comment by CharliePoole** [comment]
Or the console runner. :-)

Specifically, since NUnit 3.0 just came out you should not expect any third-party runner to support it yet. If you use such a runner, encourage them to support us!

**Comment by OlgaCoop** [comment]
hi guys,
thanks, I made it work :) I have installed adapter as you advised and run. It was passed.
And yes, I used to run test using Resharper :)
