### ISSUE TITLE
Add documentation on runners that support NUnit 3.0

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#1090]
There seems to be some confusion with people attempting to run NUnit 3 tests with older runners like Selenium, Resharper and TestDrivent.NET. I have also seen some confusion on how to run Xamarin and .NET core.

I think we should add a new top level page to the wiki, or add to an existing top level page a matrix of runners capable of running NUnit 3 tests and what platforms they support. For tools like Resharper, once it supports NUnit 3, include the version that supports it.

I am thinking a large table similar to the one that XUnit does, [Test Runner Compatibility](https://xunit.github.io/#runners). Hopefully it will prevent some of the issues and will give us something to link to when those issues are reported.

I am entering this as a docs issue although we may want to create some example code in the examples repositories. I see this as a living document that we encourage third party runners to keep updated and maybe even include links to their products and their help pages on using NUnit with their products.

I am assigning to 3.0 extras since it is independent of any releases. I am also assigning to myself. I will get it started and then people can update as needed.

**Comment by CharliePoole** [comment]
I'm OK with this so long as we don't load ourselves with the responsibility of testing those runners. The difference with xunit is that they publish either the runners themselves or the adapters that allow them to work.

Given our time limits and our tendency to want to "eat our own dogfood" I think we are better off if we list info that is given to us by the vendors. We could also allow users to add comments where appropriate.

I'm not too keen on links to commercial projects without some sort of sponsorship agreement.

**Comment by CharliePoole** [comment]
@rprouse Seems like this could be in Backlog.

**Comment by rprouse** [comment]
@CharliePoole I agree and I have moved it. I was actually thinking we might want a documentation milestone since those issues seldom block releases? What do you think? I could go either way since we might want to ensure some documentation gets done for a release.

Is the tag enough and only have doc issues in a release other than backlog if they block the release?

**Comment by CharliePoole** [comment]
It seems to me that we want to maintain documentation continuously, rather than in iterations, with the possible exception of documenting new features that come out in a release.

Perhaps we should use the docs project to create issues for most things and introduce milestones there but only for new features in new releases. For our leftover documentation issues in the nunit project, we could just work them down by making sure they are all assigned to someone.

**Comment by CharliePoole** [comment]
Issue moved to [nunit/docs #72](https://github.com/nunit/docs/issues/72) via [**ZenHub.io**](https://www.zenhub.io/)
