### ISSUE TITLE
Getting Test Directory in TestCaseSource

### ISSUE THREAD

**Issue by afscrome** [nunit/nunit#1092]
What is the recommended way of getting the Test Directory in a TestCaseSource?

In NUnit 2, this was simply done by using a relative path, however this no longer works in NUnit 3 as the CurrentDirectory is not set to the test directory.  The breaking change documentation at https://github.com/nunit/nunit/wiki/Breaking-Changes suggests to use `TestContext.TestDirectory` to get the directory, however this results in a null reference exception when called in a TestCaseSource (which sort of makes sense).

Should `TestContext.CurrentContext.TestDirectory` work when  being called from a TestCaseSource, or is there another API that should be called to get the TestDirectory at this point?

The scenario is that I have a number of sample inputs stored in files on the filesystem, and I'm generating one test case for each file, roughly like the following

```csharp
public class Tests
{
    [TestCaseSource(nameof(TestCases))]
    public void SomeTest(string fileName)
    {
        Assert.Pass();
    }

    public static IEnumerable<string> TestCases()
    {
        //The following line throws a null reference exception
        var testDir = TestContext.CurrentContext.TestDirectory;

        var testCasesPath = Path.Combine(testDir, "../../Templates");
        return Directory.GetFiles(testCasesPath);
    }
}
```

I'd expect that running the above code would pass, but it actually results in a null reference error.

```
Test Name:	SomeTest
Test FullName:	IronVelocity.Tests.TemplateExecution.Tests.SomeTest
Test Source:	SomeTest.cs
Test Outcome:	Failed
Test Duration:	0:00:00.001

Result StackTrace:	
at NUnit.Framework.TestContext.get_TestDirectory()
   at IronVelocity.Tests.TemplateExecution.Tests.<TestCases>d__1.MoveNext()
   at NUnit.Framework.TestCaseSourceAttribute.GetTestCasesFor(IMethodInfo method)
Result Message:	System.NullReferenceException : Object reference not set to an instance of an object.
```

**Comment by CharliePoole** [comment]
NUnit tests are run within a TestContext, which you can access through TestContext.CurrentContext. At a point in time when you are not running any tests, no context has been established, so CurrentContext returns null.

If your TestCaseSource is only used for tests in one assembly, you can access the assembly through one of its known types and find out where the assembly was loaded from.

If you don't mind using an internal NUnit method, you can make use of NUnit.Framework.Internal.AssemblyHelper.GetAssemblyPath(Type type) to return the path. Or take a look at the method and extract the code.

We should probably provide some easy way to access this info at load time, although it's not clear how to do it. Formally, the TestCaseSource doesn't know what it is generating data for.
