### ISSUE TITLE
Perform build and packaging on different machines

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#11]
Currently, it's only possible to do a release of NUnitLite on a machine with all the runtimes we support installed. This makes it difficult for contributors to handle releases. It would be better if the builds could be completed on different machines and then aggregated on a separate server.

The main changes needed to the build script to accomplish this are:
1. Provide a remote location to which builds are published
2. Add a target to copy builds to that location.
3. Modify package targets to use that location.

In order to make sure that all the builds for a release are all based on the same source, we will need to tag the published packages with a revision number and/or date.

From https://bugs.launchpad.net/nunit-3.0/+bug/1176462

**Comment by rprouse** [comment]
Closing as a stale issue.
