### ISSUE TITLE
Can't use TestCaseData from base class

### ISSUE THREAD

**Issue by LazyPotato** [nunit/nunit#1103]
Hi,
I've recently updated from NUnit.3.0.0-beta-2 to NUnit.3.0.0 release version and now i've got next problem.
I've got a child fixture class which uses BaseTestCaseSource defined in base class. 
```
public class BaseClass
{
        public static readonly object[] BaseTestCaseSource = 
        {
             new TestCaseData("testCase")
        };
}

[TestFixture]
public class ChildClass : BaseClass
{
    [TestCaseSource("BaseTestCaseSource")]
    public void ChildTest(string argument)
    {
       ...
    }
}
```
Everything worked perfectly, but now i've got an error "No arguments were provided" running this test. Defining BaseTestCaseSource in ChildClass solves the problem, as do alternative constructor calling
```
[TestCaseSource(typeof(BaseClass), "BaseTestCaseSource")]
public void ChildTest(string argument)
{
    ...
}
```
Is it a bug, supposed behaviour or just me doing something wrong?

**Comment by CharliePoole** [comment]
I think this should work. When you say you updated to the release version, does that mean your test was recompiled against NUnit 3.0 release and you are using the NUnit 3.0 release console runner?

If you are running with a third-party runner, it probably won't work.

We are releasing NUnit 3.0.1 tonight, so it would be great if you can get back to us quickly with more information.

**Comment by rprouse** [comment]
I will confirm this with 3.0.1 before I release.

**Comment by CharliePoole** [comment]
@rprouse I just came across this issue nunit/nunit-vs-adapter#6 which may apply

@LazyPotato Are you by any chance using the adapter? :-)

**Comment by rprouse** [comment]
I have confirmed that this is an issue. I am looking at what the resolution is and if we should include it in 3.0.1.

**Comment by rprouse** [comment]
I've decided to postpone this issue. The workaround of specifying the class that the static data source is in works fine and is fairly straightforward. In fact, I am inclined to make this a documentation issue as the convention is that you should refer to static on the class it is defined on. Maybe I am being overly pedantic though :smile: 

As stated in the initial report, the following works, so I am not going to delay the 3.0.1 release. If anyone disagrees, speak now or forever hold your peace. Or at least until 3.2 :smile: 

```C#
[TestCaseSource(typeof(BaseClass), "BaseTestCaseSource")]
public void ChildTest(string argument)
{
    ...
}
```

**Comment by LazyPotato** [comment]
Sorry for my late reply.
If that helps, I've tried to launch it with:
1. nunit3-console runner
2. NUnit 3.0.7.0 test adapter in VS 2012

It fails in both cases, also the adapter doesn't display full test name (something like ChildTest("testCase")), only ChildTest.

Thanks for the response

**Comment by rprouse** [comment]
By default, the reflection API's that we use do not pick up static members of base classes. We probably just didn't pass in the BindingFlags needed in this case. It is probably an easy fix and we will get it in the next release, but I didn't want to delay the release or risk it by rushing a fix.

I hope the workaround of specifying the class works for you for now.

**Comment by lundmikkel** [comment]
This problem shows itself even if the test is in the same class as the test case source:

    [TestFixture]
    public class BaseClass
    {
        public static readonly IEnumerable<int> EvenInts = new[] { 2, 4, 6, 8 };
        
        [Test]
        [TestCaseSource(nameof(EvenInts))]
        public void MyTestMethod(int i)
        {
            Assert.That(i % 2 == 0);
        }
    }

    [TestFixture]
    public class ChildClass : BaseClass { }

This is the output in the Test Explorer:

![1][1]


  [1]: http://i.stack.imgur.com/CzMva.png
