### ISSUE TITLE
DomainManagerTests.CanCreateDomainWithApplicationBaseSpecified() fails when not 3 directories deep

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#1105]
Found while testing the 3.0.1 release. The 'fix' for this unit test bb2e37b2 doesn't work if the test is not at least 3 directories deep. The code is correct but the test is not, so I am not going to delay the release for this.

**Comment by rprouse** [comment]
To elaborate a bit, I ran these tests with the command line `.\nunit3-console.exe .\nunit.engine.tests.dll`

If the tests are three directories deep, they pass, if not, they fail with the error 

```
1) Error : NUnit.Engine.Services.Tests.DomainManagerTests.CanCreateDomainWithApplicationBaseSpecified
System.NullReferenceException : Object reference not set to an instance of an object.
   at NUnit.Engine.Services.Tests.DomainManagerTests.CanCreateDomainWithApplicationBaseSpecified() in D:\src\nunit\nunit\src\NUnitEngine\nunit.engine.tests\Services\DomainManagerTests.cs:line 74
```

If it is one level deep (in d:\tmp) or 

```
1) Failed : NUnit.Engine.Services.Tests.DomainManagerTests.CanCreateDomainWithApplicationBaseSpecified
  PrivateBinPath
  Expected: Path matching "mp\nunit"
  But was:  "tmp\nunit"
at NUnit.Engine.Services.Tests.DomainManagerTests.CanCreateDomainWithApplicationBaseSpecified()
```

if it is two levels deep (d:\tmp\nunit)

**Comment by CharliePoole** [comment]
You know, I knew that was there and figured I would get back to it. It's best to record such things.

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit-console #17](https://github.com/nunit/nunit-console/issues/17) via [**ZenHub**](https://www.zenhub.com/)
