### ISSUE TITLE
The Throw method seems to have disappeared from the  TestCaseData class in 3.0

### ISSUE THREAD

**Issue by tomcap** [nunit/nunit#1107]
I just downloaded and started using NUnit 3.0 in VS 2015. From the documentation and blogs online, I was hoping to use the Throws method of the TestCaseData class. Unfortunately, it does not seem to be there any more.

**Comment by CharliePoole** [comment]
As explained on the Breaking Changes page of the documentation, we eliminated ExpectedExceptionAttribute in 3.0. This was done after long discussions on our mail list, knowing that it would impact many users.

We also eliminated the Throws property, which is the TestCase equivalent to ExpectedException, but neglected to list it on that page. I just added it. The current documentation for TestCaseData is correct: https://github.com/nunit/nunit/wiki/TestCaseData (It was a bit hard to find, so I added it to the right-hand side menu.)

In the case of Test cases, the rationale is that mingling tests that succeed with those that throw an exception is a bad practice. It's better to create error test cases separately from "happy path" cases. If you prefer to keep the test cases together, simply add a boolean argument like 'throwsException' and use it to conditionally call Assert.Throws.
