### ISSUE TITLE
SetCulture / SetUICulture does not work if applied at class level

### ISSUE THREAD

**Issue by shatl** [nunit/nunit#1111]
Following test fails in .NET 4.5 + NUnit 3.0.1
```
[TestFixture]
[SetCulture("ru-RU")]
class Test {
  [Test]
  //[SetCulture("ru-RU")]
  public void NunitSetCultureTest()
   {
      Thread.CurrentThread.CurrentCulture.Name.Should().Be("ru-RU");
   }
 }
```

**Comment by constructor-igor** [comment]
Strange, but I cannot reproduce the test (.NET 4.5 + NUnit v3.0.1):
```c#
    [TestFixture]
    [SetCulture("ru-RU")]
    class NUnitIssue1111
    {
        [Test]        
        public void NunitSetCultureTest()
        {
            Assert.That(Thread.CurrentThread.CurrentCulture.Name, Is.EqualTo("ru-RU"));
        }
    }
```
The test passes under NUnit console, Test adapter and R#.

**Comment by CharliePoole** [comment]
Not so strange to me. :-) We test for this in the NUnit test suite. I'm experimenting with a new way of accepting bugs... assume it's correct and prioritize accordingly. I actually had doubts this would be confirmed.

@shatl How are you executing the tests?

**Comment by rprouse** [comment]
@constructor-igor are you using the preview releases of R#? I wouldn't expect it to run the tests correctly or apply the culture.

**Comment by shatl** [comment]
I'm using R# 10 continuous testing.

**Comment by CharliePoole** [comment]
@rprouse Actually, I can imagine it working. Under 3.0, the adapter changes the culture. Under 2.x the core assembly sees a property on the test and changes the culture. I think the 3.0 attribute is close enough in implementation to the 2.x one that the property gets set and the change should occur.

But as always when running 3.0 via 2.x, it's a crapshoot!

**Comment by CharliePoole** [comment]
As I said, it's a crapshoot. :-)

The NUnit 3.0 framework is a completely new implementation but it looks enough like NUnit 2 that many runners will try to run the tests. That is, they will find most of the same attributes there. For safety, in 2.6.4 we updated the NUnit runners to detect 3.0 and refuse to run the tests. We advised 3rd party runners to use that component, but I dont' think any of them did. Consequently, tests appear to run until they fail to run correctly.

Until R# actually announces 3.0 support, I suggest you use the console runner. The 3.0 console has color and provides much better information than the onld one. You can hook it up to F5 in the IDE and run your tests that way. Unfortunately, you lose the ability to get selected tests without actually typing a command. 

Additionally, CTP 8 of our VS Test adapter can be used to run tests, although I would not use it (or any TestWindow adapter) to run an extremely large test suite.

**Comment by constructor-igor** [comment]
@rprouse I has used last versions on all the products (R#, Test adapter and NUnit console).
See nunit version's details:
![image](https://cloud.githubusercontent.com/assets/1849690/11552314/d665ad46-998b-11e5-8f93-d3be65f93a41.png)
