### ISSUE TITLE
Console runner and xml output consistency 

### ISSUE THREAD

**Issue by staticcat** [nunit/nunit#1113]
Currently I have a set of tests which are reporting the following in the console runner summary;

````
Test Run Summary
    Overall result: Failed
   Tests run: 59, Passed: 56, Errors: 1, Failures: 1, Inconclusive: 1
     Not run: 8, Invalid: 1, Ignored: 4, Explicit: 1, Skipped: 2
  Start time: 2015-12-03 04:27:39Z
    End time: 2015-12-03 04:27:39Z
    Duration: 0.489 seconds
````

The same test run produces the following test-run node in my XML output. 

````
<test-run id="2" testcasecount="67" result="Failed" total="67" passed="56" failed="3" inconclusive="1" skipped="7" asserts="11" engine-version="3.0.5797.27553" ..... >
````

After some thinking I can work out what the elements total, passed, failed, inconclusive, and skipped in the test-run node relate to in the console summary. The request is to simplify this process and place the same summary elements from the console into the XML node.

Thank you.

**Comment by CharliePoole** [comment]
As you probably figured out, Failed is the sum of Errors, Invalid and simple Failures. Skipped in the XML is the sum of Ignored, Explicit and Skipped in the console.

Essentially, NUnit 3.0 has four fundamental test outcomes, as listed in the XML. We support a number of subtypes of both failed and skipped tests and may add others in the future.

Essentially, the terminology in the XML represents the way that NUnit actually handles test outcomes, while the console currently follows the terminology used in NUnit V2. We are planning to modify the console report to reflect the new handling of results. We'll use this issue to track the change.

**Comment by rprouse** [comment]
Would the changes we are proposing in pull request #1101 satisfy this issue?

**Comment by CharliePoole** [comment]
That's what I was referring to.
