### ISSUE TITLE
Unable to find unit tests with NUnit v3.0.1

### ISSUE THREAD

**Issue by mglodack** [nunit/nunit#1119]
NUnit VS Adapter is unable to find my project's unit tests when I'm using v3.0.1. I get this response in my output. ```Attempt to load assembly with unsupported test framework in some\path\to\project.dll```

If I use v2.6.4 my tests are able to be found.

Is there a breaking change that I am missing?

**Comment by CharliePoole** [comment]
You say NUnit VS Adapter. If that's what you are actually using, it won't work. You need the NUnit 3 VS adapter. There is one adapter for NUnit V2 tests and another for NUnit 3.0.

**Comment by mglodack** [comment]
Thanks.
