### ISSUE TITLE
Region may be disposed before test delegate is executed

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#1122]
See @oznetmaster's comments on https://github.com/nunit/nunit/commit/394243999c7a096f2cc99523b9b1435234ddd872

>This appears invalid, since region is could/will be disposed before the delegate is executed?

>This was not an issue when region was only referenced within the using statement.

And

>When compiled for the CF build, this results in the compile error:

>Error 2 The type arguments for method 'NUnit.Framework.Constraints.Constraint.ApplyTo(TActual)' cannot be inferred from the usage. Try specifying the type arguments explicitly.

**Comment by rprouse** [comment]
Put into milestone 3.2 since this is a potential regression.

**Comment by oznetmaster** [comment]
Note that these two are totally unrelated problems.  One is relevant for all builds, and one for the CF build only.

**Comment by rprouse** [comment]
I grouped them as one issue because they will likely be fixed together. If not, we can split them.

**Comment by rprouse** [comment]
CF compile error is fixed. This leaves the region being disposed which does look like a problem.
