### ISSUE TITLE
Wiki typo

### ISSUE THREAD

**Issue by pjc0247** [nunit/nunit#1124]
Hi, I found a typo in [this](https://github.com/nunit/nunit/wiki/NUnitLite-Runner) page.

![image](https://cloud.githubusercontent.com/assets/1961216/11704002/222da18e-9f27-11e5-8ca2-afb67eaa99b1.png)
This example code not working and it should be `new AutoRun().Execute(args);`.

**Comment by CharliePoole** [comment]
Thanks! I fixed it.
