### ISSUE TITLE
Remove ExpectedException

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#113]
Remove ExpectedExceptionAttribute as well as ExpectedException-related properties of TestCaseAttribute and TestCaseData.

Since we would like to support this as an extension, it will make sense to move the code to a separate assembly and archive it first.

**Comment by mgravell** [comment]
So can I ask: where would this be located now? if I pull NUnit 3.0.0-beta-1 from nuget: nada

**Comment by rprouse** [comment]
I am pretty sure the sample ExpectedException is in the C# samples repository. Let me know if you don't find it and I will track it down when I am back at a computer.

**Comment by CharliePoole** [comment]
The NUnit C# samples project is here: https://github.com/nunit/nunit-csharp-samples

**Comment by mgravell** [comment]
Thanks

**Comment by polterguy** [comment]
Hi Charlie, and thx for a great chit chatter in Madrid apprx~ 8 years ago BTW ...

Anyway, 

Just updated from 2.2 to 3.0.1, and I've now got 63 compilation errors (thx dude! :P ;) )

So how do I go about fixing these now ...?
They all come from the fact that ExpectedException no longer seems to be around ...?

**Comment by polterguy** [comment]
OK, never mind, figured it out, and I actually like the new solution. But it's a mess having to change code in 63 methods ...!! :P

Maybe you should have considered rather marking the attribute obsolete, or something ...?

**Comment by rprouse** [comment]
63 methods aren't that bad ;P

We made a conscious decision to force people to switch, but knowing that
some people may have very large test suites with many more tests to
convert, we added a minimal ExpectedException attribute to the CSharp
samples project on GitHub as an example NUnit extension. I would recommend
converting now, but copying the ExpectedException sample into your code
could get you up and running quickly.

On 12 December 2015 at 09:56, Thomas Hansen <notifications@github.com>
wrote:

> OK, never mind, figured it out, and I actually like the new solution. But
> it's a mess having to change code in 63 methods ...!! :P
>
> Maybe you should have considered rather marking the attribute obsolete, or
> something ...?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nunit/nunit/issues/113#issuecomment-164159658>.
>



-- 

Rob Prouse



I welcome VSRE emails. Learn more at http://vsre.info/

**Comment by CharliePoole** [comment]
We should add that we made that conscious decision after lots of discussion
with the community. The conversion isn't all that hard to do, for most
tests, it's fairly mechanical. I think you'll end up happier with the
result if you just do it!

**Comment by Talwinder** [comment]
@rprouse . Hi Rob, I have around 2000+ test cases using ExpectedException attribute. Is there any way I can change them all to Assert.That syntax with some utility. Request you to please help me to tackle this situation

**Comment by rprouse** [comment]
I responded to this question via email.
