### ISSUE TITLE
Sometimes unhandled exception while running nunitlite tests terminates the dnx host process.

### ISSUE THREAD

**Issue by jeremymeng** [nunit/nunit#1131]
I am using nunitlite in a Dnx console project.  Sometimes an unhandled exception would crash the Dnx host process.  I would expect that an unhandled exception are handled and logged as failure by nunitlite but in this case it is not.

My `Program.cs` has just the following line in `Main()` body:

``` csharp
    return new AutoRun().Execute(typeof(TestBase).GetTypeInfo().Assembly, Console.Out, Console.In, args);
```

The exception is thrown from a thread-pool thread:

```
    StackExchange.Redis!StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl<System.TimeSpan>(StackExchange.Redis.Message message, StackExchange.Redis.ResultProcessor<System.TimeSpan> processor, StackExchange.Redis.ServerEndPoint server) Line 2008    C#
    StackExchange.Redis!StackExchange.Redis.RedisBase.ExecuteSync<System.TimeSpan>(StackExchange.Redis.Message message, StackExchange.Redis.ResultProcessor<System.TimeSpan> processor, StackExchange.Redis.ServerEndPoint server) Line 80  C#
    StackExchange.Redis!StackExchange.Redis.RedisBase.Ping(StackExchange.Redis.CommandFlags flags) Line 23  C#
    StackExchange.Redis.Tests!StackExchange.Redis.Tests.Locking.AggressiveParallel.AnonymousMethod__0(object obj) Line 31   C#
    mscorlib.ni.dll!System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(object state) Line 1261 C#
    mscorlib.ni.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Line 92  C#
    mscorlib.ni.dll!System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() Line 1239 C#
    mscorlib.ni.dll!System.Threading.ThreadPoolWorkQueue.Dispatch() Line 815    C#
    mscorlib.ni.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() Line 1148    C#
```

The source of `ExecuteSyncImpl`: https://github.com/StackExchange/StackExchange.Redis/blob/1.1.0-alpha2/StackExchange.Redis/StackExchange/Redis/ConnectionMultiplexer.cs#L2008

The source of the test: https://github.com/StackExchange/StackExchange.Redis/blob/1.1.0-alpha2/StackExchange.Redis.Tests/Locking.cs#L12-L39,
with the current line at https://github.com/StackExchange/StackExchange.Redis/blob/1.1.0-alpha2/StackExchange.Redis.Tests/Locking.cs#L37
while the exception was thrown.

**Comment by rprouse** [comment]
Thanks. I hope to get full NUnit Engine support in for DNX for 3.2 in the new year which should handle this, but we could also add some global exception handlers to NUnitLite. I expect this will be a problem across all the supported frameworks for NUnitLite.

**Comment by rprouse** [comment]
Closing as I don't believe this is relevant anymore.
