### ISSUE TITLE
Test cases with apostophe in them confuse NUnit test runner in Resharper

### ISSUE THREAD

**Issue by IanMercer** [nunit/nunit#1135]
Not sure if this is an NUnit issue or a Resharper NUnit Test Runner issue.

I have a TestCase: 
       [TestCase("October '78", 1978, 10)]
 
When I run all tests I get two occurrences of this TestCase in the UI:
![image](https://cloud.githubusercontent.com/assets/347540/11764273/ec7360d4-a0dd-11e5-9912-205d43829e9d.png)

**Comment by rprouse** [comment]
Are you using NUnit 3? R# does not support NUnit 3 if you are. It may appear to work for some tests, but it does not run tests properly.

I also believe that this is a Resharper bug. AFAIK, they handle their own test exploration and identification in NUnit 2.x.

I am going to close this as not our bug. If you disagree, please let me know and I can reopen. Also, feel free to ask additional questions in this issue if you need help, we will see them and do our best to help.

**Comment by CharliePoole** [comment]
Easiest way to tell what NUnit does with this case is to run it under the
console runner with --labels:All and see how many names come up.
