### ISSUE TITLE
Equals/ReferenceEquals methods exception

### ISSUE THREAD

**Issue by MaceWindu** [nunit/nunit#1140]
1. XML comments documentation specify that they will throw AssertException for all *Assert and Assume classes, but methods in Assert class throw InvalidOperationException.
2. Also Assume.Equals has comment:
```
// TODO: This should probably be InvalidOperationException
throw new AssertionException("Assert.Equals should not be used for Assertions");
```

Looks like documentation and/or excetion type should be fixed.

**Comment by CharliePoole** [comment]
Yes, they should all throw InvalidOperationException and the comments should be fixed.
