### ISSUE TITLE
Explicit Tests get run when using --where with some filters

### ISSUE THREAD

**Issue by stffabi** [nunit/nunit#1141]
Running an Assembly with a TestFixture like the following, the Explicit Tests will be run by the console-runner if the following --where argument is used.

nunit3-console.exe NUnitFailers.dll --where="cat!=test AND cat!=test2"

```
    [TestFixture]
    public class ExplicitTest
    {
        [Test]
        [Explicit]
        public void ExplicitTestCase()
        {
            Assert.Fail("Should never be run, even not if using exclude for categories.");
        }
    }
```

>Test Run Summary
>    Overall result: Failed
>   Tests run: 1, Passed: 0, Errors: 0, Failures: 1, Inconclusive: 0
>     Not run: 0, Invalid: 0, Ignored: 0, Explicit: 0, Skipped: 0
>  Start time: 2015-12-16 14:07:53Z
>    End time: 2015-12-16 14:07:53Z
>    Duration: 0.078 seconds

Similar bug was found in a NUnit3-beta #741

**Comment by CharliePoole** [comment]
Are you using the 3.0.1 release for both the framework and console runner?

The beta bug was a simpler version and was fixed in beta-4. The more complex problem with use of AND is was dealt with and should be corrected in 3.0.1.

**Comment by stffabi** [comment]
I'm using the 3.0.1 NuGet Packages for both framework and console runner.

Console-Runner File Version: 3.0.5813.39037
Framework File-Version:3.0.5813.39031

**Comment by constructor-igor** [comment]
I executed 4 tests:

id | status | parameters
-----------------------------
N1 | **skipped** | NUnit_v3_samples.dll --test=NUnit_v3_samples.NUnitIssue1141
N2 | **skipped** | NUnit_v3_samples.dll --test=NUnit_v3_samples.NUnitIssue1141 --where="cat!=test AND cat!=test2"
N3 | **skipped** | NUnit_v3_samples.dll
N4 | **failed** (expected **skipped**) | NUnit_v3_samples.dll --where="cat!=test AND cat!=test2"

N3:
```xml
      <test-suite type="TestFixture" id="0-1036" name="NUnitIssue1141" fullname="NUnit_v3_samples.NUnitIssue1141" classname="NUnit_v3_samples.NUnitIssue1141" runstate="Runnable" testcasecount="1" result="Passed" start-time="2015-12-25 08:04:05Z" end-time="2015-12-25 08:04:05Z" duration="0.001399" total="1" passed="0" failed="0" inconclusive="0" skipped="1" asserts="0">
        <test-case id="0-1037" name="ExplicitTestCase" fullname="NUnit_v3_samples.NUnitIssue1141.ExplicitTestCase" methodname="ExplicitTestCase" classname="NUnit_v3_samples.NUnitIssue1141" runstate="Explicit" seed="1002758134" result="Skipped" label="Explicit" start-time="2015-12-25 08:04:05Z" end-time="2015-12-25 08:04:05Z" duration="0.000982" asserts="0">
          <properties>
            <property name="_SKIPREASON" value="" />
          </properties>
          <reason>
            <message><![CDATA[]]></message>
          </reason>
        </test-case>
      </test-suite>
```

N4:
```xml
      <test-suite type="TestFixture" id="0-1036" name="NUnitIssue1141" fullname="NUnit_v3_samples.NUnitIssue1141" classname="NUnit_v3_samples.NUnitIssue1141" runstate="Runnable" testcasecount="1" result="Failed" site="Child" start-time="2015-12-25 08:05:14Z" end-time="2015-12-25 08:05:14Z" duration="0.003103" total="1" passed="0" failed="1" inconclusive="0" skipped="0" asserts="0">
        <properties />
        <failure>
          <message><![CDATA[One or more child tests had errors]]></message>
        </failure>
        <test-case id="0-1037" name="ExplicitTestCase" fullname="NUnit_v3_samples.NUnitIssue1141.ExplicitTestCase" methodname="ExplicitTestCase" classname="NUnit_v3_samples.NUnitIssue1141" runstate="Explicit" seed="1002758134" result="Failed" start-time="2015-12-25 08:05:14Z" end-time="2015-12-25 08:05:14Z" duration="0.001354" asserts="0">
          <properties>
            <property name="_SKIPREASON" value="" />
          </properties>
          <failure>
            <message><![CDATA[Should never be run, even not if using exclude for categories.]]></message>
            <stack-trace><![CDATA[at NUnit_v3_samples.NUnitIssue1141.ExplicitTestCase() in d:\My\@gh\TechSugar\TestingLab\NUnitSamples\NUnit_v3_samples\NUnitIssue1141.cs:line 12
]]></stack-trace>
          </failure>
        </test-case>
      </test-suite>
```

**Comment by CharliePoole** [comment]
I thought we had a bug on this problem already, but perhaps it was only discussed in the mail list.

Anyway, it seems to be pretty specific to the use of a top-level AND filter over two NOTs.

**Comment by stffabi** [comment]
Is there a timeframe when a fix could be expected for this one? This bug unfortunately prevents us from upgrading to NUnit 3.x

**Comment by rprouse** [comment]
@stffabi unfortunately, we haven't had time to look at this one. If you have time to do some investigation and point out the code that you think is causing the problem, or even submit a PR, then we will get it in much sooner. Beyond that, we are pulling issues in relative priority order, but we are all volunteers, so there is no hard schedule.

**Comment by stffabi** [comment]
@rprouse I've looked into the problem and tried to fix it. Please see the PR. The problem seems to be related to the IsEcplicitMatch function not beeing correctly overriden in composite filters.

A test for that would be nice, but I couldn't get a goot overview of the internal NUnit tests.

Hope this PR helps you...

**Comment by Stefan-Ilic** [comment]
Hi,

I discovered that this bug persists in NUnit v2.7.0 and v2.7.1, specifically using `NUnit.ConsoleRunner v3.11.1` with `NUnit.Extension.NUnitV2Driver v3.8.0`. I was wondering if not backporting the fix was deliberate or if you didn't know about this until now.

**Comment by mikkelbu** [comment]
I was not part of the project at that time, but I would say that it was "deliberate", meaning that for a long time it looked like NUnit v 2.6.4 would be the last release of NUnit 2, so changes and bugfixes were for a time only done in NUnit 3. Lately, NUnit 2 has been receiving a few bug-fixes, but mostly driven by individual PRs. Also note that NUnit 2 has a different code structure than NUnit 3, so it is not always easy to backport changes.

Given that you are using the console runner for NUnit 3 with the NUnitV2Driver I'm not sure where one would solve this issue, but I guess in either the NUnitV2Driver or the framework, or a combination. It sounds related to nunit/nunit-v2-framework-driver#21, so a guess would be in this project.
