### ISSUE TITLE
Documentation: Apartment is wrong for Methods

### ISSUE THREAD

**Issue by Roemer** [nunit/nunit#1145]
In the wiki (https://github.com/nunit/nunit/wiki/Apartment-Attribute), the attribute for Methods is wrong.
It says:
> [Test, ApartmentState(ApartmentSTate.STA)]
> [Test, ApartmentState(ApartmentSTate.MTA)]

but should be
> [Test, Apartment(ApartmentState.STA)]
> [Test, Apartment(ApartmentState.MTA)]

**Comment by CharliePoole** [comment]
Thanks... it's fixed.

**Comment by Roemer** [comment]
It's still not correct, the attribute is Apartment and not ApartmentState

**Comment by CharliePoole** [comment]
Ah... didn't see that.
