### ISSUE TITLE
Help page of OneTimeTearDown Attribute uses [TestFixtureSetUp] and [TestFixtureTearDown] in example

### ISSUE THREAD

**Issue by algon-irek** [nunit/nunit#1147]
**Issue**:
Help page of OneTimeTearDown Attribute uses [TestFixtureSetUp] and [TestFixtureTearDown] in example
https://github.com/nunit/nunit/wiki/OneTimeTearDown-Attribute
**Screenshot**
![image](https://cloud.githubusercontent.com/assets/7578895/11928176/d566c75a-a7d1-11e5-993a-1a632bfc2f03.png)
**Expected**:
Example section should use OneTimeSetUp and OneTimeTearDown Attributes.

BTW: Help page of OneTimeSetUp Attribute have correct example.

**Comment by rprouse** [comment]
Thanks, I have fixed it.
