### ISSUE TITLE
Superset 

### ISSUE THREAD

**Issue by rpfister51** [nunit/nunit#1148]
Example of Use for CollectionSupersetConstraint is in error.  The current example throws an error.

int[] iarray = new int[] { 1, 2, 3 };
Assert.That( new int[] { 1, 3 }, Is.SupersetOf( iarray ) );

{ 1, 3 } is not a superset of { 1, 2, 3 }, but { 1, 2, 3, 4 }, for example, would be.

**Comment by CharliePoole** [comment]
Thanks for reporting. It's fixed.
