### ISSUE TITLE
Possible Bug: Unexpected Exception with Aysnc methods

### ISSUE THREAD

**Issue by ravensorb** [nunit/nunit#1149]
I am getting the following with an async test case and I am not really sure how to track down the issue or if this a bug in how NUnit handles async methods.

    Test Name:	GetEventByIDTest
    Test FullName: TestCase.GetEventByIDTest
    Test Source:	TestCase.cs : line 49
    Test Outcome:	Failed
    Test Duration:	0:00:00.412

    Result1 Name:	GetEventByIDTest
    Result1 Outcome:	Failed
    Result1 Duration:	0:00:00.33
    Result1 StackTrace:	
    at TestCase.TestCase.<GetEventByIDTest>d__2.MoveNext() in TestCase.cs:line 56
    --- End of stack trace from previous location where exception was thrown ---
    at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunAsyncTestMethod(TestExecutionContext context)
    Result1 Message:	
    Expected: not null
    But was:  null

I do know that if I write a console (or winforms) app that uses multiple thread the code I am test behaves as I would expected it to -- this leads me to the possible conclusion that this might just be an NUnit issue?

Side note -- if I step through the test then I always get a success result.

Another side note - this issue seems to be somewhat random with my test cases. I have several hundred and on average about 40% fail with this error - its just a different 40% each run :smile:

**Comment by CharliePoole** [comment]
I don't recognize the format of your output. What are you using to run your tests? What version of NUnit are you using in your tests?

**Comment by ravensorb** [comment]
Knew I forgot something in the write-up.  I am using Visual Studio 2015 w/Update 1 and NUnit (Engine build 3.0.5813.39036) as well as Nunit3 TestAdapter 3.0.8.0 (ctp 8 I think)

**Comment by rprouse** [comment]
Can you give us some info about the tests that are failing? A code example would be helpful.

**Comment by ravensorb** [comment]
The actual unit test is tiny - the hard part is the business logic is based on a set of task continuations (http async requests -- all of which return in less than 10ms locally)

    public async Task GetEventByIDTest()
    {
        var da = Resolver.Resolve<IEventEntityDataProvider>();

        var evt = UnitTestDataModel.Current.ExistingEvent;

        var result = await da.GetByID(evt.ID);

        Assert.NotNull(result);
        Assert.AreEqual(evt.ID, result.ID);
        Assert.AreEqual(evt.Name, result.Name);
    }

**Comment by ravensorb** [comment]
Interestingly enough if I add a logging statement it looks like even when I execute a single test case it runs twice.  Is there anything in the latest test adapter that might cause this?

**Comment by ravensorb** [comment]
Ignoring the duplicate execution for a second -- I have two thoughts/questions 

* is it possible that NUnit is trying to "bubble up" an exception and is not handling a re-throw very gracefully?
* could there be an issue if the async method returns null when no data is found?

**Comment by rprouse** [comment]
I am not sure about the test getting executed twice, we can look at that separately, but I am not seeing it myself. Are you using a data driven test fixture of some sort?

Looking at your test and the error result that you first posted, it just looks like your test is failing randomly. What in your error other than the callstack makes you think that it is not just your `await da.GetByID(evt.ID)` returning null occasionally? That is how I am reading it, what am I missing? :smile:

**Comment by ravensorb** [comment]
Fair question :smile: 

If I debug and step through the test it works 100%.  If I write a windows forms app that just does this call, it also works 100%.  It is only failing right now in NUnit.

**Comment by CharliePoole** [comment]
What result do you get if you run this with the NUnit 3 console? IOW, I'd like to know if this is really an NUnit issue or if it's an adapter issue.

**Comment by ravensorb** [comment]
Great though -- just ran 4 tests via the console and while it was a bit of a pain to select the 4 I wanted, I got them to run and they worked as expected.

**Comment by CharliePoole** [comment]
Well, both R# and our Adapter would appear to have a bug. :-)

**Comment by rprouse** [comment]
You said that your tests only fail 40% of the time. Have you run them in a loop from the console to ensure they pass 100% of the time?

**Comment by ravensorb** [comment]
@rprouse this issue seems to be more with the test framework than the unit test itself.  I ran the "unit test" in a threaded console and windows app (5 threads, 500 iterations) -- all completed with 100% success.

**Comment by CharliePoole** [comment]
@ravensorb Based on your console test, it seems to an issue with the adapter rather than the framework. I'll close this and create an issue for the adapter.
