### ISSUE TITLE
Failure output is different depending on if value is array or just IEnumerable

### ISSUE THREAD

**Issue by appel1** [nunit/nunit#1150]
When using for example `Assert.That(actual, Is.EquivalentTo(expected))` the output is different depending on whether the actual and expected values are arrays or IEnumerable. 

If a value is an IEnumerable the output is truncated at 10 items. If the value is an array the output isn't truncated at all. 

I think it'd make sense if both behaved the same.

**Comment by CharliePoole** [comment]
It will help if either the OP or whoever confirms it checks out 
 * whether this also happens with Is.EqualTo
 * whether it happens when the two collections are the same size

**Comment by appel1** [comment]
With EqualTo the content isn't shown at all, the ToString representation is used instead. 

When comparing enumerable:
```
Result StackTrace:	at EqualToExpectedShorter() in Dummy.cs:line 37
Result Message:	
Expected is <System.Linq.Enumerable+WhereSelectEnumerableIterator`2[System.Int32,System.Char]>, actual is <System.Linq.Enumerable+<TakeIterator>d__24`1[System.Char]>
  Values differ at index [11]
```

```
Result StackTrace:	at EqualToSameLength() in Dummy.cs:line 28
Result Message:	
Expected is <System.Linq.Enumerable+WhereSelectEnumerableIterator`2[System.Int32,System.Char]>, actual is <System.Linq.Enumerable+<ConcatIterator>d__58`1[System.Char]>
  Values differ at index [11]
  Expected: 'l'
  But was:  'z'
```

When comparing arrays:
```
Result StackTrace:	at EqualToWithArrayExpectedShorter() in Dummy.cs:line 55
Result Message:	
Expected is <System.Char[12]>, actual is <System.Char[11]>
  Values differ at index [11]
  Missing:  < 'l' >
```

```
Result StackTrace:	at EqualToWithArraySameLength() in Dummy.cs:line 46
Result Message:	
Expected and actual are both <System.Char[12]>
  Values differ at index [11]
  Expected: 'l'
  But was:  'z'
```

When both actual and expected are arrays another difference when using EqualTo is that it lists the missing values. Could this be done for enumerables as well?

With EquivalentTo there's no difference if both have the same length.

**Comment by CharliePoole** [comment]
That's helpful as it narrows it down to EquivalentTo. It makes sense because equivalence is an NUnit-defined concept with it's own algorithm and error reporting. I've been vaguely aware that the error display was somewhat lacking, but it hasn't been documented as an issue up to now. I'm adding this to our backlog.

**Comment by stevenaw** [comment]
I can't reproduce this on the latest version of the framework
