### ISSUE TITLE
Add "error" test status of the test to TestStatus enum

### ISSUE THREAD

**Issue by darthKwisatzHaderach** [nunit/nunit#1153]
NUnit have "failed" status and "error" status for tests. I think, that "failed" status means that some functionality of system under test is broken. But "error" status means that actually my test is broken. I use NUnit with Selenium Webdriver. In my code I take screenshot when test is failed, but I also want to take screenshot when test fall with error. 

In TearDown method I call:

```csharp
if (TestContext.CurrentContext.Result.Outcome.Status.Equals(TestStatus.Failed))
{
	Driver.TakeScreenshot(Path.Combine(PathProvider.ResultsFolderPath, "FailedTests"));
}
```

But I can't find Error status in TestStatus enum.

If I misinterpreted statuses, please explain to me how it was conceived.

Thank you!

**Comment by rprouse** [comment]
@darthKwisatzHaderach, you have the meanings backwards. Failed means that your test failed an assertion whereas Error means that your test threw an unexpected exception.

It is a bit confusing, but `TestStatus.Failed` is set if your test Failed or is in Error, so your above code will catch both cases. If you want to differentiate between the two types of failure, you need to look at the `Outcome.Label` which will be set to the string Error for errors and will be empty for failures.

```C#
[TearDown]
public void TearDown()
{
    if (TestContext.CurrentContext.Result.Outcome.Status.Equals(TestStatus.Failed))
    {
        if(TestContext.CurrentContext.Result.Outcome.Label == "Error")
            Console.WriteLine("Test is in Error");
        else
            Console.WriteLine("Test Failed");
    }
}
```

**Comment by rprouse** [comment]
I am closing this as won't fix because there is a lot of code that depends on the statuses being the way they are and third party runners also rely on it not changing.

**Comment by CharliePoole** [comment]
I updated https://github.com/nunit/nunit/wiki/TestContext to give more information about the meaning of the fields.

**Comment by darthKwisatzHaderach** [comment]
Thanks for the explanation!
