### ISSUE TITLE
Support Constraints on unsafe/pointer types

### ISSUE THREAD

**Issue by damageboy** [nunit/nunit#1159]
I'm using unsafe code in C#, and I would like to be able to write tests like:

``` c#
void *p1 = SomeAPI();
void *p2 = SomeOtherAPI();

Assert.That(p1, Is.EqualTo(p2))
```

But unfortunately, the current NUnit Syntax does not allow for this easily, since the argument of type `void *` cannot be automatically converted to an argument of type `object`

This can be circumvented by replacing/wrapping each tested pointer as an `IntPtr`, but this is error prone, and greatly reduces the testing code readability...

Would it be correct / fair to request a specific Is.Pointer class of constraints that accepts `void *`? (all c#  pointer types easily cast into `void *`)

The `Pointer` constraint class would support things such as: `IsSame()`, `IsGreaterThan()` and so on...

Additionaly, NUnit would of course have to accept `void *`as an actual type for `Assert.That`, just as it does `object` and `bool`

**Comment by roji** [comment]
+1 for this, being able to test unsafe APIs is a very important feature...

**Comment by rprouse** [comment]
Sounds reasonable. Assigning to the backlog.

**Comment by rprouse** [comment]
Nobody has picked this up and nobody else has asked for this so closing.
