### ISSUE TITLE
Problem in TestCaseSource

### ISSUE THREAD

**Issue by tdsleandrorodrigues** [nunit/nunit#1162]
When used in a TestCaseSource Test, involves the same function twice.

**Comment by rprouse** [comment]
Do you mean that the TestCaseSource is executed twice?

**Comment by tdsleandrorodrigues** [comment]
That's it

**Comment by CharliePoole** [comment]
Can you post some sample code?

**Comment by tdsleandrorodrigues** [comment]
I created a new design and TestCaseSource worked. I will try to identify the problem in the project.
 Thanks

**Comment by CharliePoole** [comment]
One thing you may not have realized: if multiple test methods use the same TestCaseSource, then the source method will be executed multiple times.

**Comment by rprouse** [comment]
@tdsleandrorodrigues we haven't heard back from you, so I am going to close this issue. If you find that the problem is with NUnit, feel free to reopen this issue.
