### ISSUE TITLE
TestCaseData - Method has non-void return value.

### ISSUE THREAD

**Issue by xtratio** [nunit/nunit#1165]
Using code fromTestCaseData example:
https://github.com/nunit/nunit/wiki/TestCaseData

I get the error:
```
Test Name:	DivideByZero
Test FullName:	NUnitTests.MyTests.DivideByZero
Test Outcome:	Failed
Test Duration:	0:00:00,001

Result Message:	Method has non-void return value, but no result is expected
```

VS 2013 update 5.
NUnit 3.0.1
NUnit3 TestAdapter 3.0.8.0

Please help. What's wrong?

**Comment by xtratio** [comment]
Undestand. Last variant is has no expected result;
```
yield return new TestCaseData( 0, 0 )
                .SetName("DivideByZero")
                .SetDescription("An exception is expected");
```

**Comment by CharliePoole** [comment]
Yes, the docs are in error.

**Comment by CharliePoole** [comment]
I corrected the page. Thanks for pointing it out.
