### ISSUE TITLE
"Include" parameter doesn't work in NUnit 3

### ISSUE THREAD

**Issue by koreyba** [nunit/nunit#1166]
I use the latest version of NUnit that exists now (3.1). **I run my tests using console runner.**

**My console string looks like**: "C:\Program Files (x86)\NUnit3.0\bin\nunit3-console.exe" **--include="Selenium"** "C:\Users\Denis\Documents\Visual Studio 2013\Projects\LottoSend.com - Copy (2)\LottoSend.com\App.nunit"  

**I run tests using Jenkins. When I run them I see the next error in console:**
Invalid argument: --include=Selenium

What is wrong with this argument? I tried to use it without quotes ("") but still doesn't work.

**Comment by koreyba** [comment]
The answer is here https://github.com/nunit/nunit/search?utf8=%E2%9C%93&q=The+console+runner+no+longer+accepts+the+--include+and+--exclude+options

**Comment by CharliePoole** [comment]
Glad you were able to find the answer. You could also check the docs, particularly the "Breaking Changes" page or run nunit3-console --help.
