### ISSUE TITLE
Method Unprocessed() always returns false

### ISSUE THREAD

**Issue by constructor-igor** [nunit/nunit#1167]
Method Unprocessed() (file nunit\src\Common\nunit) always returns false. Is it OK?
Found by PVS-Studio.

```c#
        private static bool Unprocessed (ICollection<string> extra, Option def, OptionContext c, string argument)
        {
            if (def == null) {
                extra.Add (argument);
                return false;
            }
            c.OptionValues.Add (argument);
            c.Option = def;
            c.Option.Invoke (c);
            return false;
        }
```

**Comment by CharliePoole** [comment]
This is in Options.cs i.e. Mono.Options, which we did not write. We have only made the most necessary changes up to now, including changing the namespace to avoid conflicts with user code.

We may replace this class in the future with a modified version of our own, but for now I don't think we should fix minor things like this.
