### ISSUE TITLE
NUnit 3 documentation updates

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#1169]
Noted a few things down recently while updating a project to NUnit 3 - mainly just typos and outdated examples, listed below:

https://github.com/nunit/nunit/wiki/TestCase-Attribute
- Example uses named parameter Result, which has been replaced by ExpectedResult.

https://github.com/nunit/nunit/wiki/Console-Command-Line
- Removed --noxml option is referred to

https://github.com/nunit/nunit/wiki/SetUp-and-TearDown-Changes
- First bulletted list: TestFixtureSetUpAttrribute (typo)

https://github.com/nunit/nunit/wiki/Custom-Constraints
- What's exposed here from Constraint appears to have changed

https://github.com/nunit/nunit/wiki/TestFixture-Attribute
https://github.com/nunit/nunit/wiki/Platform-Attribute
and more throughout
- xml special chars are showing escaped in examples

Is there a preferred way of submitting such issues? I considered cloning the wiki and making the changes myself, however, there didn't appear to be a built-in way to submit a pull request to a Github wiki.

**Comment by rprouse** [comment]
Unfortunately, AFAIK, [there isn't an easy way to fork GitHub wikis](http://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github). People have [suggested a workflow](http://fusiongrokker.com/post/how-you-can-contribute-to-taffy-documentation), but it seems fairly complicated for small changes like this.

**Comment by rprouse** [comment]
@CharliePoole I thought that we had a workflow in mind for this. Do you remember what it was?

**Comment by ChrisMaddock** [comment]
I found the same page @rprouse, but for minor changes, it seemed like it would be easier for someone with access rights to apply them by hand.  I don't know if something like the below may be more suitable for NUnit?

http://nerds.inn.org/2014/05/19/applying-git-to-github-wikis/

**Comment by rprouse** [comment]
That looks like a decent way to allow others to contribute to the Wiki. @CharliePoole , what do you think?

**Comment by CharliePoole** [comment]
Actually, it had not crossed my mind before that adding the wiki to the nunit project limited us in this way. I thought it could be merged in the same way as we did on the separate dev wiki!

I figured that most updates would be done through the wiki and that we would give people rights to edit it if they wanted to work on the wiki. I set up an editors group for that purpose. But again, it seems like having the wiki as a part of the nunit project means that you have to make people commiters in order for them to edit.

What about setting up a documentation wiki? It would be easy enough for one of us to pull everything from the existing wiki and push it up again. If we did that, should we combine all our docs, including the adapters, in one place? Or would you prefer to keep it with the nunit project?

**Comment by CharliePoole** [comment]
BTW, I've made the changes suggested in the original comment, with the exception of Custom Constraints, which I simply marked as draft. Some of our documentation has not yet been updated from V2 and we should make that clear.

**Comment by ChrisMaddock** [comment]
Thanks for making the changes @CharliePoole. On the Custom Constraints page, I can't see any public change, I presume that was your intention?

**Comment by CharliePoole** [comment]
I added the notation "Page Under Development" but I must not have clicked Save. Just did it again.
