### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by rpfister51** [nunit/nunit#1172]
I'm working my way through the documentation for NUnit 3; and have come across some broken links.  In each case clicking on the link navigates me to the NUnit 3 documentation Home.  I identified four:

- Writing Tests / Assumptions

- Summary

- Contraints / EmptyCollectionConstraint

- Constraints / EmptyStringConstraint

I really appreciate your product, and hope this is helpful.

**Comment by rprouse** [comment]
Thanks. All of those show up as red for me as missing wiki pages and lead me to an edit page. These are all just placeholders that we missed. I will leave this issue open as a reminder to fill in those parts of the documentation.

**Comment by CharliePoole** [comment]
Status update:
 * Assumptions page is filed as an issue in the docs repo
 * Summary menu item has been removed
 * EmptyCollectionConstraint and EmptyStringConstraint pages have been added.
Closing this issue... thanks for filing it.
