### ISSUE TITLE
NUnitEngineException not displayed anywhere by ConsoleRunner

### ISSUE THREAD

**Issue by espenalb** [nunit/nunit#1179]
Observed when running a test suite of ~500 tests - some ignored, one inconclusive.

NUnit3-Concole returns -1, which seems to be ```INVALID_ARG``` in [ConsoleRunner.cs](https://github.com/nunit/nunit/blob/master/src/NUnitConsole/nunit3-console/ConsoleRunner.cs#L45)

Since the tests _are_ executing, this is not the  ```INVALID_ARG``` returned by program.cs (I think) - which leads me to suspect that the runner got a [NUnitEngineException](https://github.com/nunit/nunit/blob/master/src/NUnitConsole/nunit3-console/Program.cs#L123).

The code then _should_write an error message - but nothing appeared. This is the console output:
```
14:38:45          Run Settings
14:38:45              DisposeRunners: True
14:38:45              WorkDirectory: J:\Jenkins\jobs\GS01-3.1.0\workspace\test\windows\SensorSimulatorTests
14:38:45              NumberOfTestWorkers: 4
14:38:45          
14:38:45          Test Run Summary
14:38:45              Overall result: Warning
14:38:45             Tests run: 512, Passed: 511, Errors: 0, Failures: 0, Inconclusive: 1
14:38:45               Not run: 18, Invalid: 0, Ignored: 18, Explicit: 0, Skipped: 0
14:38:46            Start time: 2016-01-08 10:04:07Z
14:38:46              End time: 2016-01-08 13:38:43Z
14:38:46              Duration: 12876.232 seconds
14:38:46          
14:38:46          Results (nunit3) saved as J:\Jenkins\jobs\GS01-3.1.0\workspace\artifacts\TestResults\IntegrationTests\SensorSimulatorTests.xml
14:38:47          Results (nunit2) saved as J:\Jenkins\jobs\GS01-3.1.0\workspace\test\windows\\TestResults\\NUnit-SensorSimulatorTests.xml
14:38:47          The command "J:\Jenkins\jobs\GS01-3.1.0\workspace\test\windows\\packages\NUnit.Console.3.0.1\tools\nunit3-console.exe J:\Jenkins\jobs\GS01-3.1.0\workspace\test\windows\SensorSimulatorTests\\bin\Debug\\SensorSimulatorTests.dll --where="cat=~.*" --result=J:\Jenkins\jobs\GS01-3.1.0\workspace\artifacts\TestResults\IntegrationTests\SensorSimulatorTests.xml;format=nunit3 --dispose-runners --result=J:\Jenkins\jobs\GS01-3.1.0\workspace\test\windows\\TestResults\\NUnit-SensorSimulatorTests.xml;format=nunit2" exited with code -1.
```

I checked the SensorSimulatorTests.xml and it is well-formed and contains no traces of problems.

Any ideas what may be wrong? Shouldn't I have seen an error message somewher?

**Comment by CharliePoole** [comment]
In the NUnit3 XML output, what is shown for the assembly-level test-suite?

**Comment by espenalb** [comment]
This is the log from a later run - with the same exit code from console - the only difference in this test run is that ```--verbose``` was added:
```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-run id="2" testcasecount="530" result="Skipped" label="Ignored" total="530" passed="510" failed="0" inconclusive="2" skipped="18" asserts="0" engine-version="3.0.5813.39036" clr-version="4.0.30319.42000" start-time="2016-01-09 07:27:28Z" end-time="2016-01-09 11:06:21Z" duration="13132.806402">
  <command-line><![CDATA[J:\Jenkins\jobs\GS01-3.1.0\workspace\test\windows\\packages\NUnit.Console.3.0.1\tools\nunit3-console.exe  J:\Jenkins\jobs\GS01-3.1.0\workspace\test\windows\SensorSimulatorTests\\bin\Debug\\SensorSimulatorTests.dll --where="cat=~.*" --result=J:\Jenkins\jobs\GS01-3.1.0\workspace\artifacts\TestResults\IntegrationTests\SensorSimulatorTests.xml;format=nunit3 --dispose-runners --verbose --result=J:\Jenkins\jobs\GS01-3.1.0\workspace\test\windows\\TestResults\\NUnit-SensorSimulatorTests.xml;format=nunit2]]></command-line>
  <filter>
    <cat re="1">.*</cat>
  </filter>
  <test-suite type="Assembly" id="0-1571" name="SensorSimulatorTests.dll" fullname="J:\Jenkins\jobs\GS01-3.1.0\workspace\test\windows\SensorSimulatorTests\bin\Debug\SensorSimulatorTests.dll" runstate="Runnable" testcasecount="530" result="Skipped" label="Ignored" start-time="2016-01-09 07:27:28Z" end-time="2016-01-09 11:05:42Z" duration="13093.864050" total="530" passed="510" failed="0" inconclusive="2" skipped="18" asserts="0">
    <environment framework-version="3.0.5813.39031" clr-version="4.0.30319.42000" os-version="Microsoft Windows NT 6.1.7601 Service Pack 1" platform="Win32NT" cwd="J:\Jenkins\jobs\GS01-3.1.0\workspace\test\windows\SensorSimulatorTests" machine-name="GS-BUILD-01" user="Jenkins" user-domain="GS-BUILD-01" culture="en-US" uiculture="en-US" os-architecture="x64" />
    <settings>
      <setting name="DisposeRunners" value="True" />
      <setting name="WorkDirectory" value="J:\Jenkins\jobs\GS01-3.1.0\workspace\test\windows\SensorSimulatorTests" />
      <setting name="Verbose" value="True" />
      <setting name="NumberOfTestWorkers" value="4" />
    </settings>
    <properties>
      <property name="_PID" value="288" />
      <property name="_APPDOMAIN" value="test-domain-" />
    </properties>
    <reason>
      <message><![CDATA[One or more child tests were ignored]]></message>
    </reason>
```

Could this be a resource-related exception? This is observed when we use NUnit for our integration tests. These heavily use the logging features - and the generated XML is ~58MB.

We started seeing this error after instrumenting some code with debug statements which significantly increased the log size. We use ```TestContext.Writeline``` for logging...

I will try to remove the extra debug statements and see if the exit code goes back to 0. (This is not a trivial bug, for instance I see that the next test run had exit code 7, which is correct because the test  run actually _had_ 7 failures.

**Comment by rprouse** [comment]
All of your test runs are from Jenkins. Have your tried running on a developer machine using the console? It could be that an error is reported on the console that is not showing up in the test reports that might give us more of a clue as to what the problem is.

**Comment by espenalb** [comment]
I can try that - but will it make any difference? I execute NUnit from jenkins yes, but it is executed inside MSBuild:
```

	<PropertyGroup>				
		<NUnit2XmlLogFile>$(TestResultsDir)\NUnit-$(AssemblyName).xml</NUnit2XmlLogFile>
		<NUnit3XmlLogFile>$(TestReportDir)\$(AssemblyName).xml</NUnit3XmlLogFile>
		<IncludeCategories Condition="$(IncludeCategories)==''">.*</IncludeCategories>
		<NUnitTestSelector Condition="$(NUnitTestSelector)==''">cat=~$(IncludeCategories)</NUnitTestSelector>
		<NUnitTestSelector Condition="'$(ExcludeCategories)'!=''">$(NUnitTestSelector) AND cat!~$(ExcludeCategories)</NUnitTestSelector>			
		<NUnitArgs>$(ProjectDir)\$(OutputPath)\$(AssemblyName).dll</NUnitArgs>		
		<NUnitArgs>$(NUnitArgs) --where="$(NUnitTestSelector)"</NUnitArgs>
		<NUnitArgs>$(NUnitArgs) --result=$(NUnit3XmlLogFile);format=nunit3</NUnitArgs>
		<NUnitArgs>$(NUnitArgs) --dispose-runners</NUnitArgs>
		<NUnitArgs>$(NUnitArgs) --verbose</NUnitArgs>
		<NUnitArgs Condition="$(IsRunningOnJenkins)"   >$(NUnitArgs) --result=$(NUnit2XmlLogFile);format=nunit2</NUnitArgs>
		<NUnitArgs Condition="$(PlatformTarget)=='x86'">$(NUnitArgs) --x86</NUnitArgs>
		
	</PropertyGroup>
	<Target Name="EnsureTestReportDirectories">
		<SetEnvironmentVariableTask Name="ARTIFACT_DIR" Value="$(ArtifactDir)" Condition="$(ARTIFACT_DIR)==''"/>
		<SetEnvironmentVariableTask Name="TestReportDir" Value="$(TestReportDir)" Condition="$(TestReportDir)==''"/>
		<Message Text="Starting tests with ARTIFACT_DIR=$(ARTIFACT_DIR) and TestReportDir=$(TestReportDir)" Importance="High" />		
		<Message Text="TestReportDir=$([System.IO.Path]::GetFullPath('$(TestReportDir)'))" Importance="High" />
		<MakeDir Directories="$(TestReportDir)" Condition="!Exists('$(TestReportDir)')"/>
		<MakeDir Directories="$(TestResultsDir)" Condition="$(IsRunningOnJenkins) AND !Exists('$(TestResultsDir)')"/>
	</Target>
	
	<Target Name="Test" DependsOnTargets="Build; FindTool; EnsureTestReportDirectories">
		<Exec Command="$(NUnitRunner) $(NUnitArgs)" IgnoreExitCode="True">
			 <Output TaskParameter="ExitCode" PropertyName="NUnitExitCode"/>
		</Exec>
		<Exec Command="$(ReportUnitPath) $([System.IO.Path]::GetFullPath('$(TestReportDir)'))\" />
		<Error Condition="$(NUnitExitCode)!=0" Text="$(NUnitRunner) returned exit code $(NUnitExitCode)" />
	</Target>
```
And as you can see - there is no text in the MSBuild log...
I guess the only "sure" way to catch more info is to run the console in debugger and use a breakpoint...

**Comment by CharliePoole** [comment]
@espenalb Where running directly will make a difference is that you can control the command-line arguments.  The example you are running has a lot of odd arguments that are apparently generated by Jenkins. It's even possible that one of those arguments is the key to figuring out what is happening.

One of the first things I would suggest to remove would be --dispose-runners, since it serves no useful purpose when running tests in a single assembly.

You haven't included the full NUnit output, but your summary report suggests to me that there may be an unreported failure in a OneTimeSetUp or OneTimeTearDown method. Not reporting such a failure was a bug we fixed rather late in the game. Are you running NUnit 3.0.1?

**Comment by espenalb** [comment]
I control the command-line arguments, and they are:
- The test assembly
- Generate NUnit3 xml report (Picked up by ReportUnit and converted to HTML)
- Generate NUnit2 xml report (Picked up and used by Jenkins)
- 

it is "my" MSbuild target that is executing. I agree about the --dispose-runners, that was added before I realized what it was for. We _are_ running NUnit 3.0.1.

I will email you the complete test log directly, but for confidentiality reasons, I would prefer not to post it openly here as it contains sensitive data.

I still have not had time to execute tests in debugger - I know that I have some kind of race condition/deadlock in my test fixture - I am seeing strange timing in the log printout - I suspect this is related to the exception - but since there is no trace of the exception apart from the return value, it is hard to tell.

I will execute the test suite in debugger as soon as our build system is available. (We are in a release process right now, so things are a bit tight. As always. :smile: )

**Comment by rprouse** [comment]
@espenalb have you made any progress on this? I would like to close confirm issues that don't have any progress.

**Comment by espenalb** [comment]
Unfortunately I have not made any progress so far. Close the issue, I can reopen it if I have any more input.

**Comment by rprouse** [comment]
@espenalb thanks for getting back to me. Post if you find anything and we will reopen.
