### ISSUE TITLE
ITestAssemblyRunner.StopRun as implemented by NUnitTestAssemblyRunner

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1187]
NUnitTestAssemblyRunner.StopRun (true) seems to leave the system in a chaotic state.

It does correctly abort any threads that are started by ParallelWorkItemDispatcher and SimpleWorkItemDispatcher.

However, if the Workitem starts a thread of its own, it seems to never be aborted.

Also, it appears that the original NUnitTestAssemblyRunner.Run method never returns, and there is never any indication that NUnitTestAssemblyRunner.RunAsync has completed.

It seems like some housekeeping is getting lost here.

I realize I may be the first to ever exercise this code?

**Comment by CharliePoole** [comment]
At one point, I had a test bed that exercised it and became aware of the problem. Since we had no code to exercise it, I pushed it off until we had a GUI, which will definitely need it. See issue #166, which is marked status:blocked.

WorkItem doesn't start any threads. Do you mean that the user code starts them?

Tests that start threads of their own have always been a problem for NUnit, so it's no surprise that they cause a problem here. I think this probably should be solved for the simpler cases first.

**Comment by oznetmaster** [comment]
WorkItem starts a thread whenever there is a timeout on a Test.

Actually, looking deeper, much of what I said is incorrect.  The only externally visible problem is that TopLevelWorkItem.Completed is never called when StopRun is called.  This leaves everything hanging.

In NUnitTestAssemblyRunner:

```
			log.Info ("Running tests");
			if (LoadedTest == null)
				throw new InvalidOperationException ("The Run method was called but no test has been loaded");

			CreateTestExecutionContext (listener);

			TopLevelWorkItem = WorkItem.CreateWorkItem (LoadedTest, filter);
			TopLevelWorkItem.InitializeContext (Context);
			TopLevelWorkItem.Completed += OnRunCompleted;

			StartRun (listener);
```

**Comment by oznetmaster** [comment]
One possible solution for tests that start their own thread is to go ahead and run the TearDown method for an aborted Test.  Currently, the TearDown method is not run if the test is aborted.

**Comment by oznetmaster** [comment]
It is possibly related that the ITestListener.TestFinished event is only raised once if  StopRun is called - for the currently running test.  Not for parent tests, or for the fixture or assembly.

**Comment by CharliePoole** [comment]
The theory is that the detection of a cancelled test should ripple upward
through all the containing tests. It's fragile though.

**Comment by CharliePoole** [comment]
@oznetmaster Are you working this issue? (from your comments, it seems so) 

Do we have enough of a test bed to verify if it works both in and out of CF?

I was very keen to fix  #166, but it seemed I would be spinning my wheels without a main program that allowed cancelling tests.

**Comment by oznetmaster** [comment]
Yes, I am working on the issue.  I am assuming that whatever the problem is, it affects all builds, and if fixed, it will be fixed everywhere.  Will keep you informed.

**Comment by oznetmaster** [comment]
And yes, I definitely have enough of a test bed.

**Comment by oznetmaster** [comment]
It appears that some real re-architecting of the abort mechanism may be required.

Since the only code in a thread which really survives a thread.abort is that which is in finally clauses, all of the bookkeeping for an aborted test needs to either be there, or outside of the thread entirely.

What seems to be happening is that only a few levels unwind before the thread just disposes itself, and there is no thread for the bookkeeping code to run on.

I am investigating both options.  Putting the bookkeeping/unwinding code outside of the thread the work item is running on may be the cleanest, but putting it into finally clauses may be easier.

**Comment by CharliePoole** [comment]
Ah! I'm on my phone and can't check this but here's what I suspect...

It unwinds successfully so long as the test is the last remaining test of the containing test. But at that point it quits. See if that helps.

**Comment by CharliePoole** [comment]
Why is this closed?

**Comment by oznetmaster** [comment]
Github said you closed it.  I transferred the discussion to #166.  We do not really need both, since they are the same issue.  I assumed that was why you closed it?

**Comment by oznetmaster** [comment]
Not sure that is it.

I can make it fail with a single test being run, so every test is the last remaining test of the containing test.

**Comment by CharliePoole** [comment]
I didn't intend to close it as you were working on it. I don't have access
to that from my phone so feel free to reopen if you like.

Github said you closed it. I transferred the discussion to #166
<https://github.com/nunit/nunit/issues/166>. We do not really need both,
since they are the same issue. I assumed that was why you closed it?

—
Reply to this email directly or view it on GitHub
<https://github.com/nunit/nunit/issues/1187#issuecomment-170502033>.

**Comment by oznetmaster** [comment]
"It unwinds successfully so long as the test is the last remaining test of the containing test. But at that point it quits."

That seems related to the problem.  Can you take a look at the code when you have a chance, and let me know.  It is difficult to understand what is being done there.

**Comment by CharliePoole** [comment]
I have to pick up my wife who is coming home from out of town. If I get some time this evening I'll take a look then, else tomorrow.

**Comment by oznetmaster** [comment]
@CharliePoole  Any thoughts yet?

**Comment by CharliePoole** [comment]
A few... this is all based only on code reading for the moment.

1. It may behave differently in NETCF. There are a few places where calls to Thread.ResetAbort are eliminated. The logic assumes that the thread abort can be prevented after the catch ends and that a more controlled abort can take its place.

2. Try instrumenting CompositeWorkItem.CheckForCancellation to report each test checked and the result.

3. As you noted, tests don't run on the worker thread may behave differently.


I was only able to spend a little time as family activities took priority in the afternoon. It's bedtime now, but I'll try to spend more time tomorrow if you let me know what progress you make.

**Comment by oznetmaster** [comment]
I am pretty sure that ResetAbort is not available on other platforms as well?

I cannot find it listed as supported for Silverlight, Portable, Core, but the documentation has been wrong before.

I think we need to find a reliable way of unwinding that does not rely on ResetAbort.

**Comment by oznetmaster** [comment]
It seems, on first glance, that the cleanest methodology is to simply utilize the existing child thread that is currently only used for a test with timing, and use it for all tests.  Only these threads would ever be aborted.  This needs to be cleaned up anyway, since currently, these child threads are left orphaned.

The parent thread woudl abort the child, and then do the cleanuip/unwrap, and then simply exit.

All the ResetAbort calls could probably be eliminated.

I am investigating further.

**Comment by CharliePoole** [comment]
I've run some experiments and I see one possibility for the source of the problem. 

1. Both the cooperative stop and the forced cancel rely on the ExecutionStatus field in the execution context.

2. The field is examined between tests. If it's not set to "Running" then exection is supposed to terminate.
2.1 If it's set to StopRequested, shutdown is more orderly. No tests are started but teardowns are allowed to run.
2.2 If it's set to AbortRequested, shutdown is immediate. No teardowns are run.

3. For a forced stop (cancel) the execution thread is aborted. That's what causes the context field to be examined.

4. For this to work, it's necessary that all contexts should be connected. An isolated context without a parent context will result in the AbortRequested value not being passed up the chain. There is code in TestExecutionContext.CurrentContext that will create such an isolated context if it fails to get one in the normal way. The code works differently for Silverlight, Portable, CF and other runtimes. I think we need to find out if these isolated contexts are indeed being created.

**Comment by oznetmaster** [comment]
I appreciate all that research.  I had already determined a number of those issues, but not all.

I have significantly changed the abort process, and am testing it.  This was necessary to properly handle the extra threads created when a timeout or thread type is specified, which were being left orphaned.

I think this new way is also significantly cleaner.  It never results in having to handle ThreadAbortException or to use ResetAbort, on any platform.

Once I have something working, I will create a new branch and post the changes to it so that you can review it.

**Comment by oznetmaster** [comment]
I am actually walking down the child test chain, not up, and setting the ExecutionStatus for each child test.

This way, I believe that all the contexts will be handled.

**Comment by oznetmaster** [comment]
So, the CancelRun_WhenTestIsRunning_StopsTest test now works 100% of the time, with the WaitForCompletion having a Timeout.Infinite argument!

This is the desired behavior.

I am adding a number of additional test,

This new methodology does run every test on its own thread (in WorkItem) whether it "needs" its own thread or not.  So abort is only aborting that "child" thread.  All other threads clean themselves up normally, just as if the workitem had completed without being aborted.  This gets rid of any special cases for ThreadAbort anywhere (since there are no other threads being aborted), and hence no ResetAbort either.

Also, I think that this may make some other code redundant, so I am seeing what can be removed.

**Comment by oznetmaster** [comment]
This really helps.

I can now stop/abort the test run using my RunAsync based console, and I get all the results up to that point in time, and the point at which it was stopped shows as Failed:Cancelled.

Working on cleanup.

**Comment by oznetmaster** [comment]
@CharliePoole Was the pushing of the ExecutionStatus up the context chain only for stop/abort?
If so, I can remove that since I now walk the test chain down, and set all the ExecutionStatus that way.

**Comment by oznetmaster** [comment]
Should we differentiate between failed:cancelled(stop) and failed:cancelled(aborted)?

**Comment by oznetmaster** [comment]
We also need to revisit the issue of whether TearDown perhaps should be executed after a Test is aborted.  It could provide a solution to the problem of orphaned user created threads.

Alternatively, we could add a AbortedCleanUpAttribute which indicates a method to be executed if the test was aborted, allowing for cleanup code to be written.

**Comment by oznetmaster** [comment]
I needed to change IWorkItemDispatcher.  How much is this used by third parties?

If it is, I will add a new IWorkItemDispatcher2 interface, and have it derive from IWorkItemDispatcher, and put the new method in it.  Then will fix things to work correctly.  

It is a bit of a pain, so if only we use this interface, it should not be necessary.

**Comment by CharliePoole** [comment]
@oznetmaster I'm going to try to answer questions and comment on multiple comments you have made above. Let me know if it's not clear what I'm responding to...

* Good you got it to work. Unfortunate that you got it to work by creating an extra thread for each item. We were on a path of removing those threads - for example, we used to create a separate thread for running in the STA but now we have a queue for that. However, if it can only be made to work using the extra thread universally, then I guess we should do that and file a separate issue for the purpose of removing them again.

* You say you are walking down the chain of child tests... do you mean not the work items? I'm particularly wondering how this will work when there is no longer a one-to-one mapping of work items to tests and when we have dynamic tests. There could be some issues but it might be  better to get a PR out there so we can all see the diffs and comments. (Don't think of a PR as something you only do when you are "done" - Rob and I do them for work in process all the time as a better way to share ideas than trying to describe code in text.)

* Now that I have noticed it, I think we should deal with those "isolated" contexts - if that code is actually being used. There are many reasons why all contexts have to be in a connected tree. They form the connection across all work items no matter how the threading is set up. However, if it's not causing this particular problem it's probably better as a separate issue.

* Let's not ask whether to run teardown after an abort, since that's an implementation detail and since we use Thread.Abort for several different purposes. The real question is whether to run it after a forced cancel. I would say the answer is no. If we are cancelling a run, then we are cancelling it and should not be starting to run new user code. In summary...
    * After a non-forced stop, we should run it all teardowns and onetime teardowns
    * After a forced stop, we should not run them
    * After an internal stop (e.g. timeout or maxtime exceeded), we should run them.
Of course, it's the internal use of abort that has led to all the complexities here. Otherwise cancele and abort would be the same thing!

* IWorkItemDispatcher is an internal interface, allowing us to have more than one dispatcher type. There should be no need for a second interface, which would only lead to confusion, I think.

**Comment by CharliePoole** [comment]
@oznetmaster Here's one I missed...

* I don't think we need to have a different result for forced and non-forced stop. 
    * In the case of a non-forced stop, all test cases will have normal (success, failure, etc.) results. Some suites, including the topmost suite, will have failed:cancelled, while others may have already completed successfully. This should fall out automatically, since we don't cancel any threads in this case and only stop execution between tests.
    * For a forced stop, some test cases will also have failed cancelled. It seems like the suites should end up just about the same as for non-forced, unless there is something I'm not thinking of.

**Comment by oznetmaster** [comment]
I plan to post a PR today, hopefully, once the Patriots playoff game is over.

**Comment by oznetmaster** [comment]
Yes, I meant the chain of child WorkItems.

**Comment by oznetmaster** [comment]
As far as I can tell, Thread.Abort is only used for two purposes, to cancel timed out tests, and to abort a test.  Am I missing something?

As I thought about the issue of running code after an abort, I realized that if a test wants to clean up on an abort, it can do so by putting a try/catch for a ThreadAbortException itself.  That makes it the test's concern, and not ours.

**Comment by CharliePoole** [comment]
I misspoke. MaxTime does not abort the thread, but waits for it to finish.
The distinction is between cancelling a test and cancelling a run.

**Comment by oznetmaster** [comment]
I tried to open the current github solution in VS 2015, and it will not open.  It tells me that it does not know about projects of type .wixproj.

This apparently keeps me from doing anything with the solution :(

**Comment by oznetmaster** [comment]
Apparently it defaulted to the wrong solution for some reason.  It is ok now.

**Comment by oznetmaster** [comment]
Waiting for comments on the PR

**Comment by CharliePoole** [comment]
I was waiting for the tests to pass. I restarted the Travis test for you. It looked like a problem with the Travis infrastructure and is now passing. Regarding the representation of Infinity, is it possible that you have not set up the thread cultureinfo correctly? The symbolic representation of things like NaN and Infinity can be different depending on the CultureInfo.

**Comment by oznetmaster** [comment]
All I can see is that all tests pass in both .NET 4.5 build and the regular CF build when run under VS.  This implies that the culture is being handled correctly.

I know nothing of either of the two CI environments.

**Comment by oznetmaster** [comment]
The relevant code seems to be:

```
        public TestExecutionContext()
        {
            _priorContext = null;
            this.TestCaseTimeout = 0;
            this.UpstreamActions = new List<ITestAction>();

            _currentCulture = CultureInfo.CurrentCulture;
            _currentUICulture = CultureInfo.CurrentUICulture;
```

If the default CultureInfo.CurrentCulture and CultureInfo.CurrentUICulture from the environment in which the tests are being run is different, then the symbolic representation of infinity could be different.  But why would this be different in the AppVeyor context?

**Comment by oznetmaster** [comment]
It is also confusing:

```
        public TestExecutionContext(TestExecutionContext other)
        {
            _priorContext = other;

            this.CurrentTest = other.CurrentTest;
            this.CurrentResult = other.CurrentResult;
            this.TestObject = other.TestObject;
            this.WorkDirectory = other.WorkDirectory;
            _listener = other._listener;
            this.StopOnError = other.StopOnError;
            this.TestCaseTimeout = other.TestCaseTimeout;
            this.UpstreamActions = new List<ITestAction>(other.UpstreamActions);

            _currentCulture = CultureInfo.CurrentCulture;
            _currentUICulture = CultureInfo.CurrentUICulture;
```
does not copy the CultureInfo from the other context, but reinitializes it.

**Comment by CharliePoole** [comment]
I don't think it's Appveyor. It's only that you aren't running the
Silverlight tests anywhere else.

**Comment by oznetmaster** [comment]
So, when I try to run the SL 5.0 tests with nunit3-console, I get the error:

```
C:\Projects\GitHub\nunit\bin\Debug\sl-5.0>..\nunit3-console nunit.framework.tests.dll
NUnit Console Runner 3.0.5860 (Debug)
Copyright (C) 2015 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.10586.0
  CLR Version: 4.0.30319.42000

Test Files
    nunit.framework.tests.dll

The NUnit 3.0 driver does not support the portable version of NUnit. Use a platform specific runner.
```

Since I am running the Silverlight build, the error seems incorrect?

**Comment by oznetmaster** [comment]
When I run the SL 5.0 tests with the nunitlite-runner.exe, I get the following single failure:

```
Errors and Failures

1) Failed : NUnit.Framework.Constraints.EqualConstraintTests.FailsWithBadValues(double.NaN,"NaN")
  Expected string length 32 but was 37. Strings differ at index 27.
  Expected: "  Expected: 4\r\n  But was:  NaN\r\n"
  But was:  "  Expected: 4\r\n  But was:  ?? ?????\r\n"
  ----------------------------------------^
at NUnit.Framework.Constraints.ConstraintTestBase.FailsWithBadValues(Object badValue, String message) in C:\Projects\GitHub\nunit\src\NUnitFramework\tests\Constraints\ConstraintTestBase.cs:line 72

Run Settings
    Work Directory: C:\Users\njc\Documents
    Internal Trace: Off


Test Run Summary
  Overall result: Failed
  Test Count: 2996, Passed: 2882, Failed: 1, Inconclusive: 109, Skipped: 4
    Failed Tests - Failures: 1, Errors: 0, Invalid: 0
    Skipped Tests - Ignored: 0, Explicit: 4, Other: 0
  Start time: 2016-01-20 11:45:21Z
    End time: 2016-01-20 11:45:37Z
    Duration: 15.304 seconds
```

Not the four errors in AppVeyor.  So there seems to be definitely something different in the execution environments?

**Comment by oznetmaster** [comment]
Since I apparently do not know how to correctly run Silverlight tests, nor do I know anything about the Silverlight framework, I am at a loss to debug this inconsistent problem.

The Silverlight build appears to pass all its Culture related tests, and yet fails on a single test due to a culture related problem (or four tests under appveyor)).

I guess I am at a dead end on this.  I certainly do not have time to learn the Silverlight environment or framework to solve this problem :(

**Comment by CharliePoole** [comment]
My wife has a medical procedure this morning but I'll pull the code down and try to debug it in the afternoon. FYI, we normally test the full build by running "build -t TestAll" in the root directory. This builds and tests the release build in the same way it is done on the CI servers.

**Comment by rprouse** [comment]
My guess is that when you re-arranged the code, the current culture on the thread is not being set in one place, or is not correctly being set. I can't see the difference by looking at the diff's.

You are seeing different results on different machines and environments because those machines are likely running different cultures. Looking at the one test case above that is failing, 

```C#
        static object[] FailureData = new object[]
            {
                new TestCaseData(5, "5"),
                new TestCaseData(null, "null"),
                new TestCaseData("Hello", "\"Hello\""),
                new TestCaseData(double.NaN, double.NaN.ToString()),
                new TestCaseData(double.PositiveInfinity, double.PositiveInfinity.ToString())
            };

        [Test, TestCaseSource("FailureData")]
        public void FailsWithBadValues(object badValue, string message)
        {
            string NL = Env.NewLine;

            var constraintResult = theConstraint.ApplyTo(badValue);
            Assert.IsFalse(constraintResult.IsSuccess);

            TextMessageWriter writer = new TextMessageWriter();
            constraintResult.WriteMessageTo(writer);
            Assert.That( writer.ToString(), Is.EqualTo(
                TextMessageWriter.Pfx_Expected + expectedDescription + NL +
                TextMessageWriter.Pfx_Actual + message + NL ));
        }
```

The `double.NaN.ToString()` is likely happening on a different thread with a different culture than that the test is being run as. You could check that by adding in the CurrentCulture in both places and debugging through it.

This likely isn't a Silverlight only problem, it is probably just showing up in Silverlight because of different culture formatting on that platform?

**Comment by oznetmaster** [comment]
I have examined things pretty closely, and the threads culture is being set exactly as it was previously.

If you look at WorkItem.RunTest, which has not been touched, you will see the it calls _context.EstablishExecutionEnvironment, which does:

```
         Thread.CurrentThread.CurrentCulture = _currentCulture;
         Thread.CurrentThread.CurrentUICulture = _currentUICulture;
```

Also, when a new thread is spun up, the code:

```
		private void RunThread (int timeout)
			{
			thread.CurrentCulture = Context.CurrentCulture;
			thread.CurrentUICulture = Context.CurrentUICulture;

			thread.Start ();
```

(seemingly redundantly) sets the new threads culture info from the context, just as it always has.

I suspect that the changes have perhaps exposed a bug which has always been there, but only would have shown itself  if a test were run on its own thread, which most tests were not previously.

Note that all of the specific culture related tests pass without any problems.

However, it does only appear in the Silverlight build, and that is why I need help testing, since I do not understand the Silverlight environment at all.

**Comment by oznetmaster** [comment]
As I suspected, my changes have uncovered a problem seemingly elsewhere in the code.

When this test fails, TestExecutionContext.CurrentContext.Culture is "ru-RU"!  The threads that the test is running on has its culture set correctly, it is also "ru-RU".

This culture uses the infinity symbol for its positive and negative infinity, as the AppVeyor tests showed.

It appears that the problem is that in the past, the thread the test was running on did not have its culture set to the same as the context TestExecutionContext specified, and now it does.

I have no idea where the culture "ru-RU" came from.  I assume from some previous test.

None of the code I modified had anything to do with setting the TestExecutionContext culture information.

Not sure where to look now :(

**Comment by oznetmaster** [comment]
The problem seems to be the one I pointed out above.

When a new TestExecutionContext is constructed based on a previous one, as is done CompositeWorkItem.RunChildren, the code used is:

```
            foreach (WorkItem child in _children)
            {
                if (CheckForCancellation())
                    break;

                child.Completed += new EventHandler(OnChildCompleted);
                child.InitializeContext(new TestExecutionContext(Context));

                Context.Dispatcher.Dispatch(child);
                childCount--;
            }
```

This is correct, as far as I can see.

However, as I pointed out above, the constructor for TestExecutionContext (TestExecutionContext other) contains suspect code:

```
        public TestExecutionContext(TestExecutionContext other)
        {
            _priorContext = other;

            this.CurrentTest = other.CurrentTest;
            this.CurrentResult = other.CurrentResult;
            this.TestObject = other.TestObject;
            this.WorkDirectory = other.WorkDirectory;
            _listener = other._listener;
            this.StopOnError = other.StopOnError;
            this.TestCaseTimeout = other.TestCaseTimeout;
            this.UpstreamActions = new List<ITestAction>(other.UpstreamActions);

            _currentCulture = CultureInfo.CurrentCulture;
            _currentUICulture = CultureInfo.CurrentUICulture;
```

I would have thought that the last two lines should have been:

```
            _currentCulture = other.CurrentCulture;
            _currentUICulture = other.CurrentUICulture;
```

In the specific test that is failing, CultureInfo.CurrentCulture is "ru-RU", for some reason.  However, Context.CultureInfo is "en-US", as it should be.  If the new TestExecutionContext had used the culture info from the previous Context, as one would expect, the new context would have been initialized correctly, and the problem would never have occured.

I could change the TestExecutionContext constructor to work as would seem to be correct, but I am hesitant to modify code that has been there for a long time, and was written by someone else who may have had a reason for doing this.

I have no idea how many other tests this could affect if changed (corrected?).  It would fix the problem being exhibited by the tests for this PR.

**Comment by oznetmaster** [comment]
So I changed TestExecutionContext to work the way it seemed that it should work, and ran the build/test the way @CharliePoole indicated above (build -t TestAll), and EVERY test passed.

So I am going to commit this change.

The conclusion seems to be that the changes in this branch exposed a bug that has been around for a long time.  I am only commenting empirically here, since I do not know if some other reason was behind the seemingly incorrect code.

**Comment by oznetmaster** [comment]
BTW.  This sort of implies that somewhere else in the code, it is possible the Silverlight build is not saving/restoring the current culture info correctly when it changes it.  Otherwise, every build would have the same problem.  Perhaps some code conditioned incorrectly somewhere?

I will leave this to someone more familiar with the Silverlight environment.

**Comment by oznetmaster** [comment]
I appear to have found a case where this implementation will fail, but which was never tested for :(

The same failure would have occurred in the past in any test situation where a new thread was spun up for any reason.

Specifically, the TestFixture class containing the Test in question grabbed a thread synchronization object that was then used by the Test itself, with the assumption that the two things would happen on the same thread.  Obviously, that is no longer the case.  This resulted in the Test hanging forever because it could not use the synchronization object because it was owned by a different thread.

This is easy to work around in the test itself, but is definitely a compatibility issue with the previous methodology.  Not sure if this constitutes good test writing, but it was there.

Need some input on this.

**Comment by oznetmaster** [comment]
The easy work around is to put the code that is thread specific in the StartUp method for the tests, rather than in the class constructor.  Since the StartUp method is run on the same thread as the Test itself, this will always work.

As far as I can tell. all of the existing tests that use thread synchronization objects do this, which is why they all work.

We can try to fix it (hard), or document it (easy).

**Comment by CharliePoole** [comment]
I'm confused... is this an existing failing test or just something that **could** happen happen if somebody wrote a test incorrectly? Also, what do you mean by StartUp method? If it's SetUp, then that's not a problem as SetUp always runs on the same thread.

If this turns out to be a new issue... it should be written as a new issue.

**Comment by oznetmaster** [comment]
It is an existing failing test in a third party test suite.  So yes, it is happening.

And yes, I meant SetUp.  Worn out fingers :(

The issue is that the TestFixture does not have a SetUp method.  It initializes these thread specific objects in its class constructor.

I fixed it by moving the initialization to a new SetUp method, but I am now worried about compatibility with other existing test suites.

**Comment by CharliePoole** [comment]
I don't see that it's an issue on that case, in spite of the changed
behavior.

We've been telling people not to rely on constructors initialization for
many years because the frequency and timing of calls to the constructor is
not easily predicted by the user. SetUp and OneTimeSetUp are the
recommended ways to initialize the class.

**Comment by rprouse** [comment]
I agree with Charlie, this is not a recommended practice, so as you suggest
Neil, I think we should just document and close.

On 27 January 2016 at 06:21, CharliePoole <notifications@github.com> wrote:

> I don't see that it's an issue on that case, in spite of the changed
> behavior.
>
> We've been telling people not to rely on constructors initialization for
> many years because the frequency and timing of calls to the constructor is
> not easily predicted by the user. SetUp and OneTimeSetUp are the
> recommended ways to initialize the class.
> On Jan 27, 2016 12:02 AM, "Neil Colvin" <notifications@github.com> wrote:
>
> > It is an existing failing test in a third party test suite. So yes, it is
> > happening.
> >
> > And yes, I meant SetUp. Worn out fingers :(
> >
> > The issue is that the TestFixture does not have a SetUp method. It
> > initializes these thread specific objects in its class constructor.
> >
> > I fixed it by moving the initialization to a new SetUp method, but I am
> > now worried about compatibility with other existing test suites.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/nunit/nunit/issues/1187#issuecomment-175471460>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nunit/nunit/issues/1187#issuecomment-175568525>.
>



-- 

Rob Prouse



I welcome VSRE emails. Learn more at http://vsre.info/

**Comment by oznetmaster** [comment]
Sounds good to me.  Where/who should document this?  I have never touched the documentation.

**Comment by CharliePoole** [comment]
I'll write something, but I'm not sure where to put it. We no longer seem to have a page that talks about how classes represent test fixtures and methods represent test cases - the basics. I'm pretty sure we had it at one time, but it isn't in the current wiki or even in the 2.6.4 docs.

If I wrote such a page, it could either go under Usage Notes or at some top level point in the menu. What do you think?

**Comment by CharliePoole** [comment]
It could also go under the individual attributes like TestFixture, OneTimeSetUp, SetUp, but it seems better to have them link to a page that covers the overall equivalence of language features and testing concepts.

**Comment by oznetmaster** [comment]
I like the idea of a single page that covers the equivalence of language features and testing concepts.

**Comment by CharliePoole** [comment]
As usual, putting more than one thing in an issue has led to the issue being lost. It seems to be especially prone to happen when somebody re-opens a completed issue for "one more thing" needed as in this case with the documentation.

@oznetmaster The problem here is that we have an open issue, assigned to you, but which I have agreed to work on. Changing the assignee loses information as to who originally fixed it, so I don't want to do that. I have created a new issue, which we probably should have done in the first place.
