### ISSUE TITLE
System.ArgumentNullException for Action attribute

### ISSUE THREAD

**Issue by elv1s42** [nunit/nunit#1188]
I have a problem with running NUnit tests from Visual Studio (NUnit 3.0).

I use *Action Attribute*:
```csharp
[AttributeUsage(AttributeTargets.Method, AllowMultiple = false)]
    public class TestActionAttribute : NUnitAttribute, ITestAction
    {
        public void BeforeTest(ITest test)
        {
            //...
        }

        public void AfterTest(ITest test)
        {
            //...
        }

        public ActionTargets Targets
        {
            get { return ActionTargets.Test; }
        }
```

Here is the simple test I try to run:
```csharp
[TestFixture]
    public class TestClass1
    {
        [Test, TestAction]
        public void TestMethod1()
        {
            Assert.AreEqual(1, 1);
        }
    }
```

But this test is not working, I get the following message:

**SetUp : System.ArgumentNullException : Value cannot be null.
Parameter name: type
TearDown : System.ArgumentNullException : Value cannot be null.
Parameter name: type**

`at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at NUnit.Core.TestAction.CreateTestDetails(ITest test)
   at NUnit.Core.TestAction.Execute(ITest test, String methodPrefix)
   at NUnit.Core.ActionsHelper.ExecuteActions(ActionPhase phase, IEnumerable```1 actions, ITest test)
   at NUnit.Core.TestMethod.ExecuteActions(ActionPhase phase)
   at NUnit.Core.TestMethod.RunTest()
--TearDown
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at NUnit.Core.TestAction.CreateTestDetails(ITest test)
   at NUnit.Core.TestAction.Execute(ITest test, String methodPrefix)
   at NUnit.Core.ActionsHelper.ExecuteActions(ActionPhase phase, IEnumerable```1 actions, ITest test)
   at NUnit.Core.TestMethod.ExecuteActions(ActionPhase phase)
   at NUnit.Core.TestMethod.RunAfterActions(TestResult testResult)`

The same test works fine without TestAction Attribute. How can I fix this issue?

**Comment by appel1** [comment]
NUnit.Core is from NUnit 2.x afaik. Are you using both NUnit 2.x and NUnit 3 somehow?

**Comment by elv1s42** [comment]
No, I'm using Nunit 3 only (https://github.com/nunit/nunit/wiki/Action-Attributes)
Maybe there is some problem with test adapter. Tests work fine when I run them with Nunit-console.

**Comment by appel1** [comment]
Do you use the NUnit 2 or NUnit 3 test adapter?

**Comment by elv1s42** [comment]
I use Nunit 3.0 Test Adapter installed with Nuget.

**Comment by rprouse** [comment]
What is confusing is the callstack. There is no `NUnit.Core` namespace in NUnit 3, that is from NUnit 2. NUnit 3 contains an NUnit 2 driver with that namespace, but it is not part of the Visual Studio adapter.

Are you sure you are not running in the Resharper test runner? Can you show us a screenshot of the test run to confirm we are talking about the same thing? Can you also try running your code using the nunit3-console?

**Comment by elv1s42** [comment]
Well, the problem appeared because NUnit3 Test Adapter extension was disabled.
(solution for vs-2012: click TOOLS -> Extensions and Updates -> find *'NUnit3 Test Adapter'* -> click 'Enable' and restart Visual Studio).

With nunit3-console tests work fine.

Btw, will Resharper test runner support Nunit3? 
Custom NUnit installation (https://www.jetbrains.com/resharper/help/Reference__Options__Tools__Unit_Testing__NUnit.html) is not working for NUnit3.

**Comment by appel1** [comment]
Resharper 10.0.2 supports NUnit 3. 

https://blog.jetbrains.com/dotnet/2015/12/21/enters-resharper-ultimate-10-0-2/

**Comment by elv1s42** [comment]
Thank you, I used old Resharper version, 8.1
Looks like it's time to get latest version.
