### ISSUE TITLE
Showing  Error in Assembly and Framework

### ISSUE THREAD

**Issue by gopich512** [nunit/nunit#1192]
When i load a project It showing error " This Assembly was not built with any known testing framework"
![nunit error](https://cloud.githubusercontent.com/assets/16700643/12320432/ba9f5756-bace-11e5-98d0-db41ba041b35.PNG)
And Also i found an error that basic Files given by NUnit i uploaded screen shot of that following 
![nunit error 2](https://cloud.githubusercontent.com/assets/16700643/12320578/65c98a3e-bacf-11e5-9a00-3c371478bc15.PNG)
please give me a solution

**Comment by rprouse** [comment]
For the first problem, it looks like your FirstTest.dll does not reference nunit.framework.dll. Can you share more information about your tests?

For the second, I am not sure why that one test is failing for you, but unless it can be shown to be a common general error in NUnit 2.6.4, we will not spend much time looking at it. Did you try running the tests again, it could be transitory. Work has stopped on 2.6.x and all new development is on NUnit 3.x. We will only release updates to 2.6 for serious bugs.

**Comment by rprouse** [comment]
We haven't heard back and this is 2.6, so closing.

**Comment by hellboy81** [comment]
I have the same issue.

The error dialog shows sporadically.

**Comment by rprouse** [comment]
We no longer support the NUnit 2 GUI, but what version of NUnit Framework are you using in your tests?
