### ISSUE TITLE
Error "Could not load file or assembly nunit.framework" occurs when the user starts tests via a nunit project file for several testing assemblies.

### ISSUE THREAD

**Issue by NikolayPianikov** [nunit/nunit#1193]
The case 1 shows the error. The cases 2,3,4 work fine.
Folders HellowWorld.Tests and HellowWorld.Tests2 have different versions of nunit.framework.dll

HellowWorld.Tests has this reference:
```
<Reference Include="nunit.framework, Version=3.0.5813.39031, Culture=neutral, PublicKeyToken=2638cd05610744eb, processorArchitecture=MSIL">
      <HintPath>..\packages\NUnit.3.0.1\lib\net45\nunit.framework.dll</HintPath>
      <Private>True</Private>
    </Reference>
```

HellowWorld.Tests2 has this:
```
    <Reference Include="nunit.framework, Version=3.0.5813.39032, Culture=neutral, PublicKeyToken=2638cd05610744eb, processorArchitecture=MSIL">
      <HintPath>..\packages\NUnit.3.0.1\lib\net40\nunit.framework.dll</HintPath>
      <Private>True</Private>
    </Reference>
```
from one NuGet package NUnit.3.0.1

See [examples to reproduce](https://github.com/nunit/nunit/files/90417/example.zip)

**Comment by NikolayPianikov** [comment]
When the user does it under OS X he has other exception: TypeLoadException: Could not load type 'NUnit.Framework.Api.FrameworkController' from assembly ''.
See https://youtrack.jetbrains.com/issue/TW-43836.

Should we have the same ordering in the "binpath" attribute and in the "assembly" elements?

**Comment by CharliePoole** [comment]
You haven't given the nunit project file.

**Comment by NikolayPianikov** [comment]
example.zip->example\*.nunit

**Comment by rprouse** [comment]
Looking at the project files you uploaded, it looks like it fails if the binpath is in a different order than the assemblies.

Fails;

```xml
<NUnitProject>
    <Settings activeconfig="active" appbase="bin"/>
    <Config binpath="HellowWorld.Tests2;HelloWorld.Tests" name="active">
        <assembly path="HelloWorld.Tests\HelloWorld.Tests.dll"/>
        <assembly path="HellowWorld.Tests2\HelloWorld.Tests2.dll"/>
    </Config>
</NUnitProject>
```

Works

```XML
<NUnitProject>
    <Settings activeconfig="active" appbase="bin"/>
    <Config binpath="HelloWorld.Tests;HellowWorld.Tests2" name="active">
        <assembly path="HelloWorld.Tests\HelloWorld.Tests.dll"/>
        <assembly path="HellowWorld.Tests2\HelloWorld.Tests2.dll"/>
    </Config>
</NUnitProject>
```

**Comment by NikolayPianikov** [comment]
You could change the order of assemblies for case 1. It does not help.

**Comment by rprouse** [comment]
But changing the order of the binpath does help. Very strange.

As far as I can see, the order of the binpath is the deciding difference. @NikolayPianikov, so you see anything else I missed?

**Comment by NikolayPianikov** [comment]
Yes. I think you are right, the key is in the sequency in the binpath. "HellowWorld.Tests2;HelloWorld.Tests" does not work for any cases of multiple assemblies.

What do you think, should we have different build numbers for different version of .net frameworks? I know it is not related question, but ...

**Comment by rprouse** [comment]
Ah, insightful, I assume it is loading nunit.framework.dll from the first item in the binpath. @CharliePoole, is a semi-colon delimited binpath even supported? I would need to look at the code...

**Comment by CharliePoole** [comment]
It is supported. Or more exactly, .NET supports it. All we do is provide the binpath.

I would be interested to see what happens if the binpath is not specified. The result will be the same only if NUnit generate the same binpath.

I should note that these nunit files seem over-specified to me. You would not normally provide both a binpath and a complete relative path to each assembly.

However, the real issue is trying to force the loading of two entirely different nunit.framework assemblies into the same process and AppDomain by use of the given command-line arguments. If a user submitted this issue, I'd just close it saying "don't do that." In this case, I guess we first need to know whether @NikolayPianikov has a special reason that TC requires running all the tests in process.

Regarding the format of nunit project files... It has been a problem for many folks in the past. I have always advised that they first experiment by using the Project Editor to create the file. It knows how to create them correctly and you can then imitate what it does in your programmatically created file. That would not get around the issue of loading two different assemblies of the same name into a domain, however.

**Comment by NikolayPianikov** [comment]
@CharliePoole if we use ``` "C:\Program Files (x86)\NUnit.org\bin\nunit3-console.exe" 1.nunit --work=bin ``` it also shows the same error. I think the ability to load different signed versions of the assembly is common scenario. The usage of "appBase" and "binpath" as a set of relative paths (from "appBase") is a true way to run tests from different locations for nunit project files, if I am right ...

**Comment by rprouse** [comment]
I'm not sure, it seems that you are effectively setting a search path for referenced assemblies that causes the wrong version of the nunit.framework to be found first. I also don't think it is common to set the appBase or binpath unless there is a compelling need and if you do, you need to think about the consequences. 

The NUnit project itself tests assemblies targeting different versions of the framework in multiple subdirectories using project files and we do not set either.

**Comment by CharliePoole** [comment]
When you manually set appbase or binpath in the project file you are
setting them the same for every assembly. If you let nunit handle it, it is
determined separately for each AppDomain.

This is simply a limitation of the project format.

**Comment by NikolayPianikov** [comment]
@rprouse The issue, when project file is located in the root directory relatively to assemblies and NUnit did not work propertly, was fixed in the 3.0.0 rc-3. See the case 1 in [example2.zip](https://github.com/nunit/nunit/files/92180/example2.zip)

But what if project files are not located in the root? See the case 2.
For example TeamCity creates them in the temp directory or an user could store them somewhere. NUnit tries to find the testing assemblies in the path relatively to project file. Ok, TeamCity could fix paths to meet this behavior, but NUnit can't find dependencies for the testing assemblies, see the case 3.

Thus to compensate this behavior we are doing these strange project files :) And as it turns out it does not work for the some cases. Do you have any ideas how to fix it?

**Comment by NikolayPianikov** [comment]
TeamCity may suggest a workaround - to run tests separatly for each assembly 
for the current issue, but it looks not good. Also we could run tests using just a command line - it does not work for numerous numbers of assemblies, because the lenght of command line is limited.

**Comment by NikolayPianikov** [comment]
Or anoter example: we have the set of command line arguments. Just imagine we are passing them via text file containing following:

--noresult
--noheader
--framework=net-4.0
--process=InProcess
--agents=1
--workers=0
--trace=Off

It solves issues :)

**Comment by CharliePoole** [comment]
The project file in a temp directory can be an issue. In that case, set the appbase to the root and make the assembly paths relative to that location and do not specify the binpath at all. Let NUnit run each test in a separate project or AppDomain. I'm pretty sure this will work.

BTW, on second thought, I **think** that it is probably OK to use --inprocess because NUnit will still default to running each test in a separate AppDomain. You should probably avoid setting the ProcessModel or DomainUsage in both the command-line and the project file - pick one of them.

Try without setting binpath and let us know what happens.

**Comment by CharliePoole** [comment]
@NikolayPianikov Are you suggesting a feature where we allow a list of files and options to be included in a file? Using the @ convention perhaps?

**Comment by CharliePoole** [comment]
I set up issue #1197 for the purpose of collecting ideas about extensions to the nunit project format.

**Comment by NikolayPianikov** [comment]
@CharliePoole suggested way is working, but it is not applicable, because temp directory could be placed for example on an other logic drive. 
Yes. Thanx. It is a good feature from my point of view.

**Comment by CharliePoole** [comment]
@NikolayPianikov I'm pretty sure it doesn't matter where the temp directory containing the project file is. Of course, you would have to specify an absolute path for the appbase, still leaving the binpath to be determined automatically.

**Comment by NikolayPianikov** [comment]
I've checked, it works. Thank you.

**Comment by NikolayPianikov** [comment]
@CharliePoole 

Does the cmd args "--agents=1 --process=Separate" mean NUnit runs all tests from all assemblies in the one separated process and successively?

Does the cmd args "--agents=1" mean NUnit runs tests in the separated process for each assembly and also successively?

**Comment by CharliePoole** [comment]
The agents arg is meaningless unless you are using multiple processes.
Assemblies are executed one at a time unless you are using multiple
processes.

Aside from that. Yes and yes.

When am argument is meaningless in context, as in your first example, we
simply ignore it. Do you think a warning would be better?

**Comment by NikolayPianikov** [comment]
@CharliePoole If we described similar implicit behaviours somewhere it would be enough from my point of view. Warnings is good idea too. Also we could create the table explaining how cmd args is working together I mean --process, --domain, --agents, --workers, --InProcess. And any other limitations of combinations, for example --InProcess and --x86 on the 64-bit OS

**Comment by rprouse** [comment]
@CharliePoole and @NikolayPianikov should this be converted to a doc issue?

**Comment by CharliePoole** [comment]
Rather than converting, I referenced this from an existing doc issue.
