### ISSUE TITLE
Enhanced NUnit project format

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1197]
The NUnit project format remains unchanged from V2. In a way, this is convenient, since the existing Project Editor can still be used. However, the format may need some additions.

I'm setting up this issue as an "idea" so we can collect a wishlist of features for the format. If the list of features we accept is small and compatible with the .nunit format, we can extend it. If not, we can create a new format (maybe .package) for 3.0.

Right now the important thing is to collect features.

**Comment by CharliePoole** [comment]
Issue #1193 suggests the possibility of expanding the information we can supply on a per-assembly basis. Currently, assemblies have a path and no other attributes. Possibilities for specifying by assembly include the appbase and probing path. Anything else?

**Comment by CharliePoole** [comment]
Since we now create packages that include multiple projects, it may be valuable to allow nesting of projects in the new format. This feature would tend to favor use of a new extension, like .package.

**Comment by CharliePoole** [comment]
@NikolayPianikov We have talked about some addtiions to the nunit project format. This issue would be the place to record any specific ideas you have.

**Comment by NikolayPianikov** [comment]
I can suggest several ideas. 

First of all we could support  the new command line argument for example "--args=some_text_file" to pass all command line arguments via a simple text file with "new line" delimeters. The content of the text file could be:
tests1.dll
tests2.dll
tests3.dll
--work=bin
--agents=10
--teamcity

and the cmd line could be nunit3-console.exe --args=myargs.txt

The second direction is to provide an ability to setup appdomain (appvase, binpath, config file name/bytes)/process bitness/processor affinity mask/version of .net framework/environment variables/windows user account/.net evidence and any other options to run a group of tests. Simples groups could be all tests, assemblies or groups with filter "where" ... or something similar. Also we could provide these options from the code by the [TheoryAttribute] and some othe special attribute, for example [EnvironmentAttribute]/[EnvironmentsSourceAttribute].  It is just an idea.

**Comment by CharliePoole** [comment]
@NikolayPianikov Your first suggestion seems to be covered by #890, although I find the specific proposal to be overly complicated. I'm used to the @ character as a prefix for an options file, but maybe that is not used so much in Windows. I'll do some research on it.

The second idea is interesting for the project file format. Right now, the only assembly groupings we support are "configs", which may map to VS configs or may simply be arbitrary groupings. But the key thing with configs is that you can only select one of them.

Do you have any specific suggestions for how we would express such groupings within the project format?

**Comment by rprouse** [comment]
This issue is marked as an idea but hasn't had contributions in years so I am closing. If anyone is interested in working on this idea, post your interest and the team will consider reopening.
