### ISSUE TITLE
Test assembly that references a mixed mode assembly that depends on native assembly can't locate it

### ISSUE THREAD

**Issue by novaterata** [nunit/nunit#1205]
Pretty much my entire test suite depends on a mixed mode media accessor that depends on native libraries located in the same directory as the test dll. This worked fine in 2.6.x, but when I run nunit3-console.exe against the test assembly dll it's quite clear that the mixed mode assembly is unable to find it's native dlls.

**Comment by CharliePoole** [comment]
This could be a side-effect of NUnit 3.0 no longer changing the current directory. The simplest solution may be for you to add the location of the native libraries to your path.

**Comment by rprouse** [comment]
We test for this and I personally have many mixed mode tests written in C++/CLI that link to native assemblies in the same directory. Can you share the command line that you are using to test, your directory structure and the output from NUnit console?

**Comment by rprouse** [comment]
Looks like @CharliePoole was typing at the same time as me :smile: 

He raises a good point. If you are trying to load assemblies yourself from the current directory, then it will not work. It is generally not a good idea to rely on the current directory being set correctly anyway. I always recommend loading files using a full path constructed from the path of the currently executing assembly.

**Comment by novaterata** [comment]
Unfortunately my mixed/mode assembly is a blackbox I don't have access to source, but I'll bring it up to that team. This is x64 only .NET 4.5 btw if that matters. @rprouse I'll get that information, but this is on an exploratory branch. Honestly, we normally target the .sln file as a separate .nunit file is a significant maintenance cost for us and it just worked great in 2.6.4. I also couldn't get a basic .nunit file to work either. Kept complaining about missing config node. I'll try to compile all of this stuff for you, but it's low priority right now.

**Comment by CharliePoole** [comment]
@novaterata I often suggest that people just use the NUnit project editor standalone in order to create valid .nunit files. You can get it at https://github.com/nunit/nunit-project-editor.

Alternatively, use an existing installation of NUnit 2.6.4, which includes the project editor.

**Comment by novaterata** [comment]
[mkdir] Creating directory 'D:\projects\foo\task\nunit3\build\logs'.
     [exec] Starting 'D:\projects\foo\task\nunit3\tools\NUnit-3.0.1\bin\nunit3-console.exe (/config=Debug /result=nunit2 /output=D:\projects\foo\task\nunit3\build\logs\Foo.Bar.Test.Modules.Tests.dll-test-output.xml src\Bar\Foo.Bar.Test.Modules.Tests\bin\x64\Debug\Foo.Bar.Test.Modules.Tests.dll)' in 'D:\projects\foo\task\nunit3'
     [exec] NUnit Console Runner 3.0.5813
     [exec] Copyright (C) 2015 Charlie Poole
     [exec]
     [exec] Runtime Environment
     [exec]    OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
     [exec]   CLR Version: 4.0.30319.42000
     [exec]
     [exec] Test Files
     [exec]     src\Bar\Foo.Bar.Test.Modules.Tests\bin\x64\Debug\Foo.Bar.Test.Modules.Tests.dll
     [exec]
     [exec]
     [exec] Errors and Failures
     [exec]
     [exec] 1) SetUp Error : Foo.Bar.Test.Modules.Test.Setup
     [exec] Foo.Baz.BazException : The media accessor library could not be initialized due to a missing required dll (usually XXMediaAccessor.dll or DirectShow on Windows).
     [exec]    at Foo.Baz.FooAPI.Initialize(String strLicense, String strProductKey)
     [exec]    at Foo.Common.Tests.Utility.Utilities.InitializeBaz() in d:\projects\foo\task\nunit3\src\Bar\Common\Foo.Common.Tests.Utility\Utilities.cs:line 22
     [exec]    at Foo.Bar.Test.Modules.Test.Setup.SetUp() in d:\projects\foo\task\nunit3\src\Bar\Foo.Bar.Test.Modules.Tests\Setup.cs:line 11
     [exec]
     [exec] Run Settings
     [exec]     ActiveConfig: Debug
     [exec]     WorkDirectory: D:\projects\foo\task\nunit3
     [exec]     NumberOfTestWorkers: 12
     [exec]
     [exec] Test Run Summary
     [exec]     Overall result: Failed
     [exec]    Tests run: 6, Passed: 0, Errors: 6, Failures: 0, Inconclusive: 0
     [exec]      Not run: 0, Invalid: 0, Ignored: 0, Explicit: 0, Skipped: 0
     [exec]   Start time: 2016-01-20 16:33:29Z
     [exec]     End time: 2016-01-20 16:33:30Z
     [exec]     Duration: 0.898 seconds
     [exec]
     [exec] Results (nunit3) saved as nunit2

BUILD FAILED

External Program Failed: D:\projects\foo\task\nunit3\tools\NUnit-3.0.1\bin\nunit3-console.exe (return code was 6)


Directory structure:
01/08/2016  04:41 PM        57,483,585 avcodec-55.dll
01/08/2016  04:41 PM        19,076,039 avformat-55.dll
01/08/2016  04:41 PM         1,120,873 avutil-52.dll
01/08/2016  04:41 PM        24,462,624 cublas64_60.dll
01/08/2016  04:41 PM           524,288 Hunspellx64.dll
01/08/2016  04:41 PM           442,368 Hunspellx86.dll
01/18/2016  10:27 AM           304,640 log4net.dll
01/18/2016  10:27 AM         1,533,153 log4net.xml
01/08/2016  04:40 PM            61,440 LoveSeat.dll
01/08/2016  04:40 PM           181,760 LoveSeat.pdb
01/18/2016  10:27 AM           521,216 Newtonsoft.Json.dll
01/18/2016  10:27 AM           514,743 Newtonsoft.Json.xml
01/20/2016  11:33 AM            52,736 Foo.Bar.Test.Modules.dll
01/20/2016  11:33 AM           116,224 Foo.Bar.Test.Modules.pdb
01/20/2016  11:33 AM             9,216 Foo.Bar.Test.Modules.Tests.dll
01/18/2016  10:27 AM             3,001 Foo.Bar.Test.Modules.Tests.dll.config
01/20/2016  11:33 AM            26,112 Foo.Bar.Test.Modules.Tests.pdb
01/08/2016  04:41 PM            16,896 Foo.MediaInfo.dll
01/08/2016  04:40 PM         1,807,360 Foo.TextLanguageDetector.dll
01/08/2016  04:41 PM            34,816 Foo.Time.dll
01/08/2016  04:41 PM        12,516,864 FooBaz.NET.dll
01/08/2016  04:41 PM            31,744 NHunspell.dll
01/08/2016  04:41 PM            69,120 NHunspell.pdb
01/08/2016  04:49 PM           273,920 nunit.framework.dll
01/08/2016  04:49 PM           855,401 nunit.framework.xml
01/08/2016  04:41 PM         8,647,680 XXMediaAccessor.dll
01/08/2016  04:41 PM           206,848 OptMediaAccessor.dll
01/08/2016  04:41 PM           185,544 System.Net.Http.Formatting.dll
01/08/2016  04:41 PM           192,626 System.Net.Http.Formatting.xml
01/08/2016  04:41 PM           471,240 System.Web.Http.dll
01/08/2016  04:41 PM           539,657 System.Web.Http.xml

FooBaz.NET.dll is the mixed mode assembly looking for XXMediaAcceor.dll

**Comment by novaterata** [comment]
@CharliePoole I don't want to get too off topic here, but let's just say that I've tried that and have problems with all that. I still need to do more exploration with project files. I've been using nunit for 3 years without ever having to use a .nunit file, so bear with me.

**Comment by novaterata** [comment]
@rprouse  @CharliePoole  Good news! i changed the current directory in the SetUpFixture and now it works. Thanks for your help

**Comment by rprouse** [comment]
That is one workaround. I would also talk to the team that wrote Foo.Baz.FooAPI.Initialize and see if they can fix it to load the media accessor based on the codebase of Foo.Baz.

**Comment by CharliePoole** [comment]
If you run into further issues with the project files, feel free to start an issue. If you want any new features, you can add a comment to #1197.

FWIW, I can guarantee that the project editor will not create a project file that doesn't contain any configs. Nor should you. :-)
