### ISSUE TITLE
Exception when comparing two equal arrays in the latest official NUnit 2.6.4

### ISSUE THREAD

**Issue by AqlaSolutions** [nunit/nunit#1209]
var a = new[] { new[] { 1, 2 }, new[] { 3, 4 } };
        var b = new[] { new[] { 1, 2 }, new[] { 3, 4 } };
        // if you comment these two lines the test passes
        a[0] = a[1];
        b[0] = b[1];
        Assert.That(a, Is.EqualTo(b));

Gives:

Expected and actual are both &lt;System.Int32[2][] &gt;
Values differ at index [1]
  Expected and actual are both &lt;System.Int32[2] &gt;

http://screencast.com/t/pFXNNGUD

It passes in NUnit 3 but I can't migrate now.

**Comment by rprouse** [comment]
I am going to close this as won't fix. It is fixed in NUnit 3 and we won't be putting out another 2.6 release.
