### ISSUE TITLE
Available runtimes issues

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1210]
The list of available runtimes may include `.Net 4.5 - Client`, which does not exist. This is due to our misinterpreting a registry entry intended for backword compatibility.

In addition, we return both `.Net 4.0 - Client` and `.Net 4.0 - Full` if registry entries exist for both. This is not exactly incorrect but it is misleading. If `Full` is installed, then it includes the assemblies and types for `Client`. However, we have no way to force the running of tests under `Client` only if `Full` is installed.

It may be best if we merely return a single entry for .NET 4.0, suffixing it with `Client` only if the full version is not installed. It would also be useful if the RuntimeFramework type provided a property indicating whether it represents the full or the client profile.

I marked this High priority and put it into the 3.2 milestone because it impacts the gui.

**Comment by ChrisMaddock** [comment]
@CharliePoole Have started digging in to this if that's ok, it seems fairly self contained which I thought might make a good start.

One question, is the client/full profile information only required in AvailableFrameworks? It looks like CurrentFramework doesn't currently check - should it do, or is it not relevant at that point?

**Comment by CharliePoole** [comment]
That's great. I assigned to you.

Try to keep this no more complicated than it deserves since client profile has now become a legacy thing. For now, I think it only impacts AvailableFrameworks. If we come up with a need for it, in CurrentFramework, we can add that later. Not much point making distinctions if we don't do anything about them.
