### ISSUE TITLE
Windows Installer not detecting .Net 4.0/4.5 on machine

### ISSUE THREAD

**Issue by mitchellm44** [nunit/nunit#1214]
I tried to use the Windows installer for 3.0.1 and even though I have Visual Studio 2013 and 2015 installed the installer did not correctly detect a .Net 4 and therefore refused to install

**Comment by rprouse** [comment]
Marking this as status confirm. Has anyone else seen this recently?f Anyone have ideas on the cause? Is it because .NET 2.0 is not installed?

**Comment by rprouse** [comment]
I am going to close this since it is not happening for the majority of people and we have made no progress. I will reopen if people can point us to the cause.
