### ISSUE TITLE
Generic test cases

### ISSUE THREAD

**Issue by DzonnyDZ** [nunit/nunit#1215]
Currently NUnit support test methods being generic, but it can only infer which types to supply to generic parameters if parameters of method are of the typeof generic parameter, so the type of generic parameter can be inferred from type of values in `TestCaseAttribute`.
I would like to be able to supply my own types for generic parameters, independently on values passed to the test case. This would allow me to test generic instances instantiated with generic parameters that are currently impossible to pass via parameters (e.g. custom classes), or for which we currently have to use fake parameters for.
The solution seems pretty easy, and can be even implemented outside of NUnit itself, but I would like to see it as part of NUnit, either as extension of current `TestCaseAttribute` or as a new attribute (possibly derived from `TestCaseAttribute`). BTW: It would be quite helpful for extending the framework to make some methods and properties of `TestCaseAttribute` virtual.
Below is an implementation I managed to create in just few minutes. It definitely has some flaws - the test cases defined using this attribute are not nicely shown in VS Test Explorer, nor in ReSharper, however console runner sees them and runs them, which leads me to conclusion that I'm on a right way.
I would like to implement it as a pull request for NUnit myself, but I would need a little bit guidance
- Shall I extend existing NUnit `TestCaseAttribute` or create a new derived one
- In case of writing derived attribute, am I allowed to make appropriate methods and properties of `TestCaseAttribute` virtual?
- How to make the test case name to be nicely generated, like it is currently generated for normal method parameters when `TestName` is not supplied - e.g. `"MethodName`2[System.String, MyNs.MyClass]("param1", 6)"`?

``` c#
[AttributeUsage(AttributeTargets.Method, AllowMultiple = true, Inherited = true)]
public class GenericTestCaseAttribute : TestCaseAttribute, ITestBuilder, ITestData
{
    public GenericTestCaseAttribute(params object[] arguments) : base(arguments) { }
    public Type[] Types { get; set; }
    IEnumerable<TestMethod> ITestBuilder.BuildFrom(IMethodInfo method, Test suite)
    {
        if (method.IsGenericMethodDefinition && Types != null && Types.Length == method.GetGenericArguments().Length)
        {
            var gm = method.MakeGenericMethod(Types);
            return base.BuildFrom(gm, suite);
        }
        return base.BuildFrom(method, suite);
    }
}
```

and usage

``` c#
[GenericTestCase("/aaa/bbb", Types = new[] { typeof(string) }, TestName = "GetMetadata_null<string>")]
[GenericTestCase("/aaa", Types = new[] { typeof(HelperClass) }, TestName = "GetMetadata_null<HelperClass>")]
[GenericTestCase("/", Types = new[] { typeof(HelperStruct) }, TestName = "GetMetadata_null<HelperStruct>")]
public void GetMetadata_null<T>(string path)
```

**Comment by rprouse** [comment]
@DzonnyDZ I am marking this as an idea that requires design. Feel free to propose the changes required or submit a pull request and we can move this forward.

**Comment by CharliePoole** [comment]
I would favor a design that gives TestCaseAttribute a TypeArgs property like TestFixtureAttribute. That would make for a better user experience, I think. OTOH, I think I would skip the TestFixture feature that takes leading args that are Types as type args. That has proven confusing and we may want to phase it out. In addition to TestCaseAttribute, it may make sense to add this to TestCaseData in order to support the TesetCaseSourceAttribute in the same way.

**Comment by DzonnyDZ** [comment]
@CharliePoole >> Shall it be a new attribute derived from existing TestCaseAttribute (like the GenericTestCaseAttribute I wrote above), or do you prefer extending existing TestCaseAttribute?
@rprouse >> I hope I'll have time to take a look at this soon, including TestcaseData

**Comment by CharliePoole** [comment]
As I wrote in the previous comment, we should use TestCaseAttribute. The property name should be TypeArgs, the same name we use for the same purpose on TestFixtureAttribute.

**Comment by jnm2** [comment]
Run into a great use case for this today.

**Comment by jnm2** [comment]
Ran into a great use case for this today. Have to use this workaround:

```cs
[TestCase(typeof(object))]
[TestCase(typeof(string))]
[TestCase(typeof(int?))]
public static void ActualMayBeNullForNullableTypes(Type type)
{
    var methodInfo = typeof(PredicateConstraintTests)
        .GetMethods(BindingFlags.NonPublic | BindingFlags.Static)
        .Single(method => method.Name == nameof(ActualMayBeNullForNullableTypes) && method.GetParameters().Length == 0)
        .MakeGenericMethod(type);

    ((Action)methodInfo.CreateDelegate(typeof(Action))).Invoke();
}

private static void ActualMayBeNullForNullableTypes<T>()
{
    Assert.That(null, Is.InstanceOf<T>().And.Matches<T>(actual => true));
}
```

**Comment by stevenaw** [comment]
This would've proven helpful today at work while writing serialization tests to round-trip a string.

@nunit/framework-team Does this still need more design? The discussion above focuses on TestCase, but would we want TestCaseSource to behave similarly too?

**Comment by OsirisTerje** [comment]
@stevenaw Do we need to update documentation for this?

**Comment by stevenaw** [comment]
Oh yes, thank you for the reminder @OsirisTerje
