### ISSUE TITLE
NullReferenceException when loading TestFixtures with params in UWP .NET Native

### ISSUE THREAD

**Issue by jhogins** [nunit/nunit#1216]
The following error occurs when using a TestFixture with parameters in a UWP .NET Native test assembly:

An exception was thrown while loading the test.
System.NullReferenceException: Object reference not set to an instance of an object.
   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.CheckTestFixtureIsValid(Framework.Internal.TestFixture fixture)
   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildFrom(Framework.Interfaces.ITypeInfo typeInfo, Framework.Interfaces.ITestFixtureData testFixtureData)
   at SharedLibrary!<BaseAddress>+0x2d9e144d
   at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom(Framework.Interfaces.ITypeInfo typeInfo)

Repro attached.

[NativeNUnit.zip](https://github.com/nunit/nunit/files/105827/NativeNUnit.zip)

**Comment by CharliePoole** [comment]
How are you running your tests? NUnit3-console?

**Comment by rprouse** [comment]
We currently only have a Xamarin based runner for UWP and I doubt it would work with .NET Native yet. Were you able to get any tests running UWP?

As @CharliePoole says, how are you trying to run the tests?

**Comment by jhogins** [comment]
See the attached project. It is a UWP app which calls into NUnitLite's
AutoRunner to run the tests. We have used a similar method to get all of
our (3000+) tests running in .NET Native on UWP.

On Wed, Jan 27, 2016 at 4:03 AM, Rob Prouse <notifications@github.com>
wrote:

> We currently only have a Xamarin based runner for UWP and I doubt it would
> work with .NET Native yet. Were you able to get any tests running UWP?
>
> As @CharliePoole <https://github.com/CharliePoole> says, how are you
> trying to run the tests?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nunit/nunit/issues/1216#issuecomment-175586745>.
>



-- 

Jon Hogins

**Comment by MattWhilden** [comment]
Hello! I work on the .NET Native Compiler and Runtime team. I suspect this has to do with a known issue where we don't properly handle Attributes with Arrays as parameters. It turns out we just return an Array of the proper length but full of nulls. This will be fixed for Update 2 that should be out sometime around //BUILD. 

I'm investigating this project a bit further as there appears to be another .NET Native issue lurking right behind the one reported here.

@jhogins It would be great if you could email us so we can try and get you sorted out. You can reach me here: dotnetnative@microsoft.com.

**Comment by jhogins** [comment]
Thanks @MattWhilden . I am realizing that we've run into this problem with ValuesAttribute as well. My workaround for the TestFixture issue has been to create subclasses which pass in the correct parameters to the constructor. We've worked around the ValuesAttribute issues by subclassing ValuesAttribute and setting _this.data_ to the desired array of values.

**Comment by CharliePoole** [comment]
Given the native compiler issue, I'm marking this as blocked for now.

**Comment by MattWhilden** [comment]
@jhogins Glad to hear that you were able to work around the issue.

@CharliePoole Sounds completely reasonable. I'll add updates here as necessary and hopefully the bug existing will keep folks from burning too much time investigating.

**Comment by MattWhilden** [comment]
I've sent a private build of our tools with loads of fixes to @jhogins to kick the tires on. If someone else from nunit would like to play with them, let me know. Just need to know who to send invites to. 

I'm also happy to try and get any UWP tests you have on top of these bits (can save some round trips). I crawled through some of the links into the Dev wiki but it wasn't immediately obvious.

**Comment by MattWhilden** [comment]
I fired off an updated build to @jhogins. Hopefully it'll lead to good news. If someone else here is interested in kicking the tires, let me know.

**Comment by NCarter3** [comment]
I just ran the attached repro. This does seem to be fixed under update 2 :)

**Comment by MattWhilden** [comment]
Wonderful news. Thanks for the update. Do let me know if there are other oddities.

**Comment by rprouse** [comment]
@NCarter3 thanks for the update. I am going to close this issue. If anyone else has similar problems, we can reopen.
