### ISSUE TITLE
Corrupt NUnit3Settings.xml causes crash

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#1217]
Reported on the mailing list, need to determine if this is a general framework issue (I think I fixed it early in 3.0 dev) or just the adapter not reporting the error correctly. Either way, we should probably recover.

>New to NUnit and was somewhat concerned to find that for some reason the tests would not run or appear in Visual Studio 2015 Test Explorer for my WPF application.  This is even though it worked on two of my teams set-up, and worked on my main pc.  The Tests output gave me nothing to go on - the adapter was looking at my dll's... just not finding anything.

>I struggled for hours looking at every stackexchange resource, extensive googling and what limited documentation I can find for NUnit 3.  I reinstalled the adapter twice, repaired VS, redownloaded the git, reinstalled nunit nuget packages, moved my repository out of a network share (parallels) to a local folder.  I even downloaded the NUnit GUI app (which was hard to track down) and it wouldn't even start without throwing an error - something about RecentFilesService not initialising properly.

>I gave up and decided that maybe a paid app would have better support - and downloaded DotCover - success!  It recognised all my tests. I clicked run and boom - it failed again!!!!  Something about a RecentFilesService not initialising!

>Got my hands dirty, dug into the source and error messages and discovered that this was the root cause:

>'C:\Users\nathanielarmer\AppData\Local\NUnit\Nunit30Settings.xml'

>Somehow this file got corrupted, and instead of throwing an error or warning (at least in VS/test Adapter) it just silently failed.  Delete that file and suddenly tests start appearing, and I can hit run and have one fail (but at least the *test* failed!)

>In summary, this appears to be a great tool with lots of kudos, but I lost many valuable hours because of the lack of any error message, let alone a big neon sign!  It might be an idea to write some unit tests to ensure this doesn't happen again ;)

**Comment by NPSF3000** [comment]
The file, when correct contains the following xml:

<?xml version="1.0"?>

-<NUnitSettings>

<Settings/>

</NUnitSettings>

The file I had appears blank, but contains some selectable (albiet blank) text.  I've attached it, and here's the hex dump from an online tool:

file name: Nunit30Settings.xml
mime type: 

0000-0010:  00 00 00 00-00 00 00 00-00 00 00 00-00 00 00 00  ........ ........
0000-0020:  00 00 00 00-00 00 00 00-00 00 00 00-00 00 00 00  ........ ........
0000-0030:  00 00 00 00-00 00 00 00-00 00 00 00-00 00 00 00  ........ ........
0000-0040:  00 00 00 00-00 00 00 00-00 00 00 00-00 00 00 00  ........ ........
0000-004b:  00 00 00 00-00 00 00 00-00 00 00                 ........ ...

(.txt to bypass upload restrictions)
[Nunit30Settings.xml.txt](https://github.com/nunit/nunit/files/109410/Nunit30Settings.xml.txt)

**Comment by constructor-igor** [comment]
Seems, nunit v3.0.5813 shows correct behavior for corrupted Nunit30Settings.xml file:

```
NUnit Console Runner 3.0.5813
Copyright (C) 2015 Charlie Poole

Error loading settings C:\Users\igor-z\AppData\Local\NUnit\Nunit30Settings.xml.
Root element is missing.
```

![image](https://cloud.githubusercontent.com/assets/1849690/13202170/06b897e6-d899-11e5-8faf-27e47c15807c.png)

**Comment by CharliePoole** [comment]
It would appear that the adapter, which is what the OP was using doesn't handle it then.

**Comment by CharliePoole** [comment]
Trying out ZenHub feature to move this issue to the adapter!

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit3-vs-adapter #192](https://github.com/nunit/nunit3-vs-adapter/issues/192) via [**ZenHub.io**](https://www.zenhub.io/)
