### ISSUE TITLE
code typo in ThrowsConstraint wiki page

### ISSUE THREAD

**Issue by MSK61** [nunit/nunit#1219]
I don't know where else I can report this as the wiki don't have their own issues, let alone the missing forking and pull request features for wiki. Anyway in the ThrowsConstraint page under this section https://github.com/nunit/nunit/wiki/ThrowsConstraint#examples-of-use, the last example should be

    Assert.That(() => { throw new ArgumentException(); }, Throws.ArgumentException);
The original text missed `new` and the braces.

**Comment by CharliePoole** [comment]
Thanks, it's fixed now.

It's fine to report the issue here. We are moving the documentation wiki to it's own repo, so you'll be able to file issues there in the future.
