### ISSUE TITLE
Async tests hang when run in a group

### ISSUE THREAD

**Issue by corliss** [nunit/nunit#1223]
This seems related to #756. I have a group of async unit tests, which run individually. However when run as a group they hang.

There is no explanation or usable workaround in #756 - the workaround to use async void instead of async Task does not work in NUnit 3, which disallows tests that return async void.

Could someone please explain what the issue is, and also what I can do to work around this? I've spent a lot of time assuming the bug was in my code :(.

Cheers

**Comment by CharliePoole** [comment]
Issue #756 is about a specific Windows Forms problem under NUnit 2.6.4. It may have as much to do with the use of the STA as it does with async. And, as you note, async support is changed in NUnit 3.0. For those reasons, you are right to create a new issue.

That said, now you have to tell us the details of your particular problem. :-) Ideally, try to create a simple set of tests that reproduce it.

**Comment by rprouse** [comment]
@corliss can you define what you mean by run in a group? The NUnit project itself has dozens (or hundreds?) of async tests and our test suites never hang unless we wrote the tests incorrectly.

**Comment by rprouse** [comment]
@corliss can you give us more information or a reproducible test case that we can work with? I would like to close confirm issues that don't have any progress.

**Comment by CharliePoole** [comment]
@rprouse It just struck me that "run as a group" may mean that he is using the VS adapter, in which case it's no surprise that nobody has confirmed it.

**Comment by rprouse** [comment]
@corliss  I am closing since we have not heard back from you. If you have more information, add it to this issue and we will reopen.
