### ISSUE TITLE
The --teamcity option should really be an extension

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1225]
It's a bit odd that teamcity support is native to NUnit and no other CI server is supported. It would be best if this could be made into an extension.

Doing that requires two things:

1. Actually creating the extension point and extension in the engine, as we have done for other purposes. This one would be some kind of EventListener extension point, and so could be used for a lot of different purposes.

2. Figuring out how to support the console option. Currently, the console is not extensible.

**Comment by CharliePoole** [comment]
Depends on #1302

**Comment by CharliePoole** [comment]
This can now be worked on, since #1302 is completed.

**Comment by CharliePoole** [comment]
With completion of issue #1010, the console runner no longer needs to support extensions itself in order to implement this. A teamcity extension can be enabled throught the IExtensionService interface based on the presence of the --teamcity option.

**Comment by CharliePoole** [comment]
@NikolayPianikov Working on this issue I noticed something that seems strange... if the user specifies both `--teamcity` and `--outfile` the team city commands are sent to the file. Is this intended? It seems that the commands should always go to the Console so that team city can intercept them.

**Comment by CharliePoole** [comment]
@NikolayPianikov Another question... I see that the teamcity code for NUnitLite is different from the code for the console runner. Is this just an oversight? Should they be sharing code at some level?

**Comment by NikolayPianikov** [comment]
@CharliePoole Yes, you are right (about --teamcity and --outfile). We should do something on this. Should we make a special console for console output only or may some other ideas? 
We are recomending to use nunit3-console for our users. And if it could work for lite version it would good. I will see what I have to change to support this.

**Comment by CharliePoole** [comment]
As I changed it for this PR only the test output goes to the file. The team city commands go to the original stdout and include the output commands.

For nunitlite the events are test or result objects while they are XML for the engine. I think I'll refactor so we have two front ends using a common class that actually generates the messages.
