### ISSUE TITLE
Build may silently fail some tests

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1231]
I just discovered this in running `build -t TestAll` locally. I haven't seen it in the CI build, but it would require scanning down all the results to find it.

When we used msbuild for the build, we were able to make use of a setting that allowed further tests to continue if one failed. But at the end, the build was reported as failed. We need to acheive the same effect with Cake.

**Comment by ChrisMaddock** [comment]
@CharliePoole just been browsing build issues, believe this one is done? Apologies if I've missed something.

**Comment by CharliePoole** [comment]
I agree.
