### ISSUE TITLE
Have default NUnitLite Runner Program.cs return exit code

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#1234]
On Charlie's advice, we've started using the NUnitLite Runner nuget package in our test projects as we convert them to NUnit 3. This is brilliant - doing exactly what we need, and simplifying our downstream CI by not relying on an installed NUnit.

One adjustment we're having to make for every project, is to alter the default Program.cs that is added to pipe through the exit code from `AutoRun.Execute();` - the default Main method returns void. Is there a particular reason for this, or could it be changed so the appropriate status code is returned from the .exe also? Will be happy to submit a PR for this, but thought I'd check it would be worthwhile first.

**Comment by oznetmaster** [comment]
Seems reasonable to me.

Alternatively, another "auto runner" could be written which has a set of return codes.

They are small pieces of code.

I use an alternative "auto runner" in my CF build, for instance, that truly runs the entire test asynchronously.

**Comment by CharliePoole** [comment]
@ChrisMaddock It does make sense. Feel free to submit the PR. You should modify both Program.cs and Program.vb, which are found in the nuget directory.

Although it's not necessary in order to submit a PR, I'll send you an invite to the Contributors team. That would let us put your name to the issue.

**Comment by ChrisMaddock** [comment]
Thanks Charlie, will get it done in the next couple of days.

@oznetmaster: Not sure what you're suggesting, sorry? The AutoRun.Execute() method already returns the standard return codes, these just aren't returned from the default Program.cs entry point which is added to a project when installing the NUnitLite Runner Nuget package.

**Comment by rprouse** [comment]
Fixed by #1242
