### ISSUE TITLE
Make Appveyor NuGet feed more useable

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1236]
Because the nuget feed uses the AppVeyor build number, you have to look on AppVeyor to figure out the nature of each artifact. You can't just take the latest one.

We don't want to have multiple feeds, so we need to encode more information in the extended version number, after the existing 3.1.0-CI-nnnn

* For pull requests, append -PR- plus the PR # Normally, folks don't want these.

* For merges into master (builds of master that are not PRs), add an identifying suffix. This could be -MASTER or something shorter that won't be confused with anything else. Folks who want the "latest" build should take the most recent of these.

* For builds of other branches, we could append the branch name just as for master. The only problem is that we may run into problems if the version tag exceeds some maximum length. I've seen this happen in some experiments. In that case, we should truncate.

**Comment by CharliePoole** [comment]
@rprouse Please review above as a spec

**Comment by rprouse** [comment]
Looks good to me. Appending the branch sounds reasonable. The team standard is  issue-xxx. We occasionally use other naming, but if we know to keep it short, then it is our issue. It should only be an issue for the team since AppVeyor does not build branches in forks.
