### ISSUE TITLE
Make TestDirectory accessible when TestCaseSource attributes are evaluated

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#1241]
TestDirectory is currently a property of the TestExecutionContext, which means it is unavailable at the point TestCaseSource's are evaluated. This prevents test setup's such as the below:

    [Test, TestCaseSource(nameof(TestCases))]
    public void ImportFileDoesNotThrow(string fileName)
    {
       Assert.DoesNotThrow(() => importer.Import(fileName));
    }

    private static IEnumerable<string> TestCases
    {
        get { yield return TestContext.CurrentContext.TestDirectory + "filepath"; }
    }

This came out of a [support query](https://groups.google.com/forum/#!topic/nunit-discuss/YvFwSfvF7aU) on the Google Group - to quote @CharliePoole's considerations:

> Things we could consider include: 
>  * Making TestDirectory a static property of TestContext and basing it on the executing assembly rather than the executing test. 
>  * Moving TestDirectory to some other static class and doing the same thing. 
>  * Leaving it where it is but having TestContext create a "fake" CurrentContext when no test is running. 
> Most likely, if I had thought of this in the first place, I would have put TestDirectory somewhere else entirely.

**Comment by CharliePoole** [comment]
@nunit/core-team Any opinions on which way to go with this? Bear in mind that we have released 3.0 now, so we have backward compatibility to worry about.

**Comment by jhamm** [comment]
I ran a test using the example. I was able to get it working by adding a check to the TestCaseSourceAttribute.BuildFrom method:
````csharp
        public IEnumerable<TestMethod> BuildFrom(IMethodInfo method, Test suite)
        {
            // added:
            if (TestExecutionContext.CurrentContext != null && TestExecutionContext.CurrentContext.CurrentTest == null)
                TestExecutionContext.CurrentContext.CurrentTest = suite;

            foreach (TestCaseParameters parms in GetTestCasesFor(method))
                yield return _builder.BuildTestMethod(method, suite, parms);
        }
````

The rest of the tests ran just fine. I also ran cake with the TestAll target with no issues. I am not sure if this would impact anything else though.

From what I can see, this seems to work without modifying the API so it should be ok with backward compatibility.

**Comment by CharliePoole** [comment]
@jhamm It's tempting but a bit of a hack, since TestExecutionContext.Current is not really supposed to exist when tests are not being run. I'm concerned that it could have side effects.

**Comment by jhamm** [comment]
I agree that it is an ugly hack. I figured that it was at least worth a mention.

**Comment by CharliePoole** [comment]
I think we want to stop basing the TestDirectory on the existence of a CurrentTest and just look at the currently executing assembly. We always have one of those. :-)
