### ISSUE TITLE
Separate assertions from test framework

### ISSUE THREAD

**Issue by JakeGinnivan** [nunit/nunit#1243]
It would be great if nUnits assertions could be pulled out of the main library into a separate one like xUnit does.

Then you have nUnit.Core which is just the test framework, nUnit.Assertions which is just the assertions then nUnit just references both. 

One of the main reasons I choose xunit over nunit at the moment is my preference for assertions is [shouldly](https://github.com/shouldly/shouldly) but when using nUnit team members/contributors use the built in assertions.

**Comment by CharliePoole** [comment]
This duplicates #502, which will now show a link to your comment.
