### ISSUE TITLE
Possible missing items in separate thread for each test in #1187

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1244]
@CharliePoole You commented a while back (in #1187) "In that case, the test won't be a TestMethod".

I sort of ignored that comment at the time, but now want to make sure I did not forget something.

When should a Test which is not a TestMethod be run on its own thread?  It seems like none of the other classes that are derived from Test ever need to be run on their own threads, but I may be missing something.

**Comment by CharliePoole** [comment]
When a TestFixture is annotated as requiring the STA it will have to run in a separate thread if the SimpleWorkItemDispatcher is in use.

I'm not clear why you're creating an issue to ask a question. Where do you want to go with this?

**Comment by oznetmaster** [comment]
I want to fix it if it makes sense to.

I am currently running all of the TestMethods for a TestFixture on a STA thread.  What other code needs to run on the STA thread?

**Comment by CharliePoole** [comment]
I think this was fixed by #1187 and other merges but was not reference with a "fixes" reference. I'll close it now, but we can re-open if something is still needed.
