### ISSUE TITLE
Introduce Is.Zero syntax to test for zero

### ISSUE THREAD

**Issue by lundmikkel** [nunit/nunit#1246]
Would it be possible to introduce an Is.Zero syntax? Something that would allow you to write code like

    Assert.That(value, Is.Zero);
    Assert.That(value, Is.Not.Zero);

It is a bit more readable than

    Assert.That(value, Is.EqualTo(0));
    Assert.That(value, Is.Not.EqualTo(0));

And it would fit well with

    Assert.That(value, Is.Negative);
    Assert.That(value, Is.Positive);

**Comment by rprouse** [comment]
It would be fairly easy to add. Any thoughts from the rest of the team?

**Comment by CharliePoole** [comment]
Sure. Low-pri feature, easy fix IMO

**Comment by CharliePoole** [comment]
Nice exercise for someone who wants to get into constraints... how we write them, how we test them, how we create the syntactic elements and test those.

**Comment by rprouse** [comment]
Sounds good, promoting to a low priority feature.

**Comment by lundmikkel** [comment]
Great :+1:

**Comment by lundmikkel** [comment]
Okay, so I did a search for Negative in the library and added Zero as a combination of Negative and EqualTo methods. I push a commit to my own fork, as seen above.

Am I in any way on the right track here?

**Comment by CharliePoole** [comment]
It looks good to me and is how I would do it. 

However, let's stop talking about a Zero Constraint, which you didn't create and which would have been overkill anyway. I changed the issue title accordingly so it shows up correctly in our release notes.

Give us a PR. :-)

**Comment by lundmikkel** [comment]
I've created a [PR](https://github.com/nunit/nunit/pull/1248) now.

**Comment by rprouse** [comment]
Fixed by #1248
