### ISSUE TITLE
Equality comparison is hard to understand, filled with special cases

### ISSUE THREAD

**Issue by CraigStuntz** [nunit/nunit#1249]
One of the most fundamental tasks I have to do in an NUnit test is compare two objects to see if they're equal. Most of my tests end with something like:
```csharp
Assert.That(actual, Is.EqualTo(expected));
```
However, it's not always clear how NUnit will make this comparison. Languages like C# and F# have different, but very easy to state, notions of equality. NUnit's notion of equality is [fragile](https://github.com/nunit/nunit/issues/1209), not principled, and [isn't even well-understood by its own maintainers](https://github.com/nunit/nunit/issues/524#issuecomment-77736382):

> We should check under NUnit 2.6.4. If it works there, it should be made to work in 3.0 as well.

When you look at [the code which implements the comparison](https://github.com/nunit/nunit/blob/4e10f475d88fec980f080461a64e6fc4b1e54b2b/src/NUnitFramework/framework/Constraints/NUnitEqualityComparer.cs), it's easy to see why: It's filled with special cases, plugins, and options. You can scarcely describe its behavior, never mind concisely. Whether or not 2 instances are "equal" depends very much on which of these special cases you fall into, which can be hard to predict. Nobody is completely certain what it _should_ do.

### Examples
This has negative consequences in the real world. I spent the better part of an hour one evening wondering why the following test (written in F#, but running in NUnit; I think this was 2.6.4)...

```fsharp
    [<Test>]
    member this.``structural equality``() =
        let actualList: char list = []
        [(actualList, "")] |> should equal [([], "")]
```
...failed with the message:
```
    Expected: [([], "")], 
      but was [([], "")]
```
This is despite the fact that they are in fact equal, per normal F# structural equality:
```fsharp
> let actualList: char list = [];;
   val actualList : char list = []
> [(actualList, "")] = [([], "")];;
   val it : bool = true
```

Further testing revealed that the following very similar looking tests *do* pass (as they should!):
```fsharp
    [<Test>]
    member this.``structural equality success``() =
        let actualList: char list = []
        [actualList] |> should equal [[]]

    [<Test>]
    member this.``structural equality success 2``() =
        let actualList: char list = []
        [(actualList, "")] |> should equal [([]:char list), ""]
```
### What Does Equal Mean?
Equality is the bedrock on which we build the notion of what it means for a unit test to pass at all. It should be consistent and easy to explain. However, there are multiple notions of equality in play. It's maybe a little annoying that they are all called "equal," but each of these is at least fairly simple and internally consistent:

* C# value types use structural equality. This means different things for, say, floats and ints, but most developers understand this.
* C# classes use reference equality. It's not really principled, but it's fast, easy to understand, and totally consistent.
* The .NET BCL supports arbitrary definitions of equality via `Object.Equals`
* F# uses structural equality by default. 
* There are arguably types which should not have an inbuilt notion of "equal." For example, the SML programming language won't let you test if floats are equal (as opposed to a comparison via an epsilon). 

Although I prefer F#'s structural equality, C# shows that it's OK to use multiple definitions of "equal" if the boundaries are clearly defined. Developers can understand this.

### Which Definition of Equality Do I Want In a Unit Test? 
I think there are really only two possible answers to this. Both are valid in their way and a test framework probably needs to support both.
* Structural equality. NUnit's current behavior seems to be an attempt to slowly get here, as I think even C# developers usually prefer this in a test assertion
* Use the language's inbuilt `=` operator (if that doesn't happen to already use structural equality)

One could imagine constraints like `Is.EqualTo` and `Is.EquivalentTo` for default C# and structural equality, for example? (I know there's an existing `EquivalentTo`, but it seems to cater to people who want to use a `List` as a `Set`. Sets [already have reasonable `SetEquals` methods](https://msdn.microsoft.com/en-us/library/bb346516(v=vs.110).aspx).) I'm not totally sold on these names, though; just raising them as strawmen for discussion.

Here's what I never want:
* An unpredictable mishmash of structural and reference equality, which changes from minor version to version and has so many options and plug-ins that its behavior can't be predicted or specified even after reading the source code that implements it.

### But Backwards Compatibility!
Yes, people's test suites are going to break if this is implemented as I describe. There should be some consideration for backwards compatibility. I'm not sure what that looks like, but I acknowledge the problem.

**Comment by rprouse** [comment]
Well written and well thought out. :+1: 

I will admit that I also find some aspects of equality in NUnit troubling. In my opinion, we have allowed 'features' to be added that broaden the scope of equality. I've always felt that NUnit's definition of equality should mirror that of the language you are working in. I try to set the bar there, but it  can be difficult when users request new comparisons pointing to legacy support as justification.

Personally, I think that if we support special cases of equality, then it should be through explicit methods, not the everything channeling through the standard equality asserts. 

As you say, the problem is that it will be very hard to change the existing framework without breaking backwards compatibility and without adding additional complexity or confusion to the interface. We have many users with many thousands of unit tests. We cannot expect them to comb through their tests updating everything because we change the existing definition of equality.

I am going to mark this issue as an idea. If we can find a way forward where we do not cause major disruption for users relying on the current state of equality, we can promote it to design or enhancement.

I look forward to hearing other people's thoughts on this :smile:

**Comment by rprouse** [comment]
This hasn't received any feedback, design or further interest from the community, so I am going to close.
