### ISSUE TITLE
SIGABRT using ./build.sh in Cake at <unknown> <0xffffffff>

### ISSUE THREAD

**Issue by maxpa1n87** [nunit/nunit#1253]
Hi, I'am trying to build master branch of nunit. 
I'am getting the following SIGABRT message from mono runtime.
I installed mono 4.3.3 from git and PCL Reference Assemblies from github.

    max@laptop:~/nunit$ ./build.sh --prefix=/usr
    Analyzing build script...
    Processing build script...

    * Assertion at icall.c:5337, condition mono_error_ok (&error) not met

    Stacktrace:

    at <unknown> <0xffffffff>
    at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes
    (System.Reflection.Assembly,bool) <0x00060>
    at System.Reflection.Assembly.GetTypes () <0x00016>
    at Cake.Core.Scripting.ScriptAliasFinder.FindAliases (System.Collections.Generic.IEnumerable 1<System.Reflection.Assembly>) <0x0019f>
    at Cake.Core.Scripting.ScriptRunner.Run
    (Cake.Core.Scripting.IScriptHost,Cake.Core.IO.FilePath,System.Collections.Generic.IDictionary 2<string, string>) <0x00669>
    at Cake.Commands.BuildCommand.Execute (Cake.CakeOptions) <0x00042>
    at Cake.CakeApplication.Run (System.Collections.Generic.IEnumerable 1<string>) <0x000a0>
    at Cake.Program.Main () <0x000df>
    at (wrapper runtime-invoke) <Module>.runtime_invoke_int (object,intptr,intptr,intptr) <0x000e7>

    Native stacktrace:

    mono() [0x4abdb6]
    /lib/x86_64-linux-gnu/libpthread.so.0(+0xf8d0) [0x7ff8619ce8d0]
    /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37) [0x7ff861433147]
    /lib/x86_64-linux-gnu/libc.so.6(abort+0x148) [0x7ff861434528]
    mono() [0x6495ef]
    mono() [0x6493dc]
    mono() [0x64953d]
    mono() [0x53ee29]
    mono() [0x5401c8]
    [0x41c3a041]

    Debug info from gdb:

    Got a SIGABRT while executing native code. This usually indicates
    a fatal error in the mono runtime or one of the native libraries 
    used by your application.

    ./build.sh: Zeile 62: 2654 Abgebrochen mono $CAKE_EXE $SCRIPT -verbosity=$VERBOSITY -configuration=$CONFIGURATION -target=$TARGET`

OS is Debian/Jessie 64bit running mono 4.3.3 from git. I have read that there is some issues converting UTF-16 -> UTF-8 or something which causes mono runtime to SIGABRT because an assertion fails. The line icall.c:5337 says it clearly.

**Comment by CharliePoole** [comment]
I'm at a loss. @patriksvensson does this look like a Cake configuration error?

**Comment by patriksvensson** [comment]
@CharliePoole Nothing that we've seen before and an SIGABRT hints about this being something caused by the Mono runtime. There is an issue by @maxpa1n87 (see https://github.com/cake-build/cake/issues/676) that is Mono related, so maybe this is as well.

@maxpa1n87 You something about using Mono 4.3.3 with PCL reference assemblies (compiled from source) in the Cake issue. I would recommend that you try installing Mono 4.2.2.30 which is the latest stable version and see if the error persists. You can find instructions for this here: http://www.mono-project.com/download/#download-lin

**Comment by maxpa1n87** [comment]
Thank you I think I'll try mono 4.2.2.30 to see if it is persists. I'll get back to you if it is mono related.

**Comment by maxpa1n87** [comment]
Hi, I tried mono 4.2.2.30, now nunit does build. How can I install nunit system wide? Is there a target in the ./build.sh cake script? Thanks.

**Comment by maxpa1n87** [comment]
Can be closed. Everything is fine now. :100: :8ball:
