### ISSUE TITLE
Way to set count of parallel tests when Parallelizable flag is in use

### ISSUE THREAD

**Issue by ChipV223** [nunit/nunit#1257]
I'm currently running tests to the Sauce Labs platform using Visual Studio 2015 and NUnit 3.0.1. That when I launch the tests in parallel using the [Parallelizable(ParallelScope.Fixtures)] flag, the tests come through in Sauce Labs in groups of 4, despite me using more than 4 TestFixtures in my code. I was curious if in its current form, is there an NUnit attribute flag that can be used to see the count for parallel tests. Here's an example of a project I'm working on:

`
    [TestFixture("firefox", "44", "Windows 8.1", "", "")]
    [TestFixture("firefox", "43", "OS X 10.10", "", "")]
    [TestFixture("chrome", "48", "Windows 7", "", "")]
    [TestFixture("chrome", "47", "Windows 8", "", "")]
    [TestFixture("safari", "9", "OS X 10.11", "", "")]
    [TestFixture("internet explorer", "11", "Windows 10", "", "")]
    [TestFixture("internet explorer", "8", "Windows 7", "", "")]
    [TestFixture("MicrosoftEdge", "20.10240", "Windows 10", "", "")]

    [Parallelizable(ParallelScope.Fixtures)]
    public class SeleniumTest
    {
        private IWebDriver driver;
        private String browser;
        private String version;
        private String os;
        private String deviceName;
        private String deviceOrientation;
        private String sessionId;

        public SeleniumTest(String browser, String version, String os, String deviceName, String deviceOrientation)
        {
            this.browser = browser;
            this.version = version;
            this.os = os;
            this.deviceName = deviceName;
            this.deviceOrientation = deviceOrientation;
        }

        [SetUp]
        public void Init()
        {
            DesiredCapabilities caps = new DesiredCapabilities();
            caps.SetCapability(CapabilityType.BrowserName, browser);
            caps.SetCapability(CapabilityType.Version, version);
            caps.SetCapability(CapabilityType.Platform, os);
            caps.SetCapability("public", "public");
            caps.SetCapability("deviceName", deviceName);
            caps.SetCapability("deviceOrientation", deviceOrientation);
            caps.SetCapability("username", System.Environment.GetEnvironmentVariable("SAUCE_USERNAME"));
            caps.SetCapability("accessKey", System.Environment.GetEnvironmentVariable("SAUCE_ACCESS_KEY"));
            caps.SetCapability("name", TestContext.CurrentContext.Test.Name);

            driver = new RemoteWebDriver(new Uri("http://ondemand.saucelabs.com:80/wd/hub"), caps, TimeSpan.FromSeconds(840));
           
        }

        [Test]
        public void googleTest()
        {
            driver.Navigate().GoToUrl("www.google.com");
            StringAssert.Contains("Google", driver.Title);
            IWebElement query = driver.FindElement(By.Name("q"));
            query.SendKeys("Sauce Labs");
            query.Submit();
        }

        [TearDown]
        public void CleanUp()
        {
            bool passed = TestContext.CurrentContext.Result.Outcome.Status == NUnit.Framework.Interfaces.TestStatus.Passed;
            try
            {
                // Logs the result to Sauce Labs
                ((IJavaScriptExecutor)driver).ExecuteScript("sauce:job-result=" + (passed ? "passed" : "failed"));
            }
            finally
            {
                // Terminates the remote webdriver session
                driver.Quit();
            }
        }
`

**Comment by CharliePoole** [comment]
See the docs.

To set it with an assembly level attribute...
https://github.com/nunit/docs/wiki/LevelOfParallelism-Attribute

To set it from the command-line (--workers option)...
https://github.com/nunit/docs/wiki/Console-Command-Line

**Comment by ChipV223** [comment]
Thank you for the information Charlie

I see that links talk about how to set the LevelOfParallelism through command line but I don't see anything to set it through an IDE like Visual Studio, which is why I opened this ticket. Do you have any documentation on how to set to through there or is not possible?

**Comment by CharliePoole** [comment]
There is currently no way to set it from the adapter other than through the attribute.

**Comment by CharliePoole** [comment]
Please open an issue on the adapter itself if you would like us to put that feature into the backlog... https://github.com/nunit3-vs-adapter/issues
