### ISSUE TITLE
Question/clarify: Retry attribute doesn't run

### ISSUE THREAD

**Issue by andrejohansson** [nunit/nunit#1260]
The current documentation for the [Retry Attribute](https://github.com/nunit/docs/wiki/Retry-Attribute) claims that:

> It is not currently possible to use RetryAttribute on a TestFixture or any other type of test suite. Only single tests may be repeated.

> Since a parameterized test method represents a suite, RetryAttribute is ignored when it appears on such a method.

> If a test has an unexpected exception, an error result is returned and it is not retried. Only assertion failures can trigger a retry.

In my case, I have a test that is __not__ parametirized but it still doesn't get any retries:
```
[Test]
[Retry(TestHelper.DefaultRetryCount)]
public void Fail_Invalid_Login_On_Customer_Branded_SubDomain()
{
  ...
}
```

My fixture however, have a base class whose fixture is parameterized:
```
[Parallelizable(ParallelScope.Fixtures)]
public class LoginPageTests : BaseTestFixture {
...
```

```
[TestFixture("IE", "11.0", "Windows", "8.1")]
[TestFixture("Chrome", "47.0", "Windows", "8.1")]
[TestFixture("Firefox", "43.0", "Windows", "8.1")]
[Parallelizable(ParallelScope.Fixtures)]
public class BaseTestFixture
{
```

Should this affect the retries? If so, please clarify in the documentation. If not, then there is something not triggering the retries in my setup that needs to be investigated further.

**Comment by CharliePoole** [comment]
The attributes on the fixture should have nothing to do with it.

Is your test actually failing? That is, is an AssertionException being thrown? Nothing else will trigger a retry. For example, if a login failure is triggered by some other kind of exception, NUnit views that as an error rather than a failure.

**Comment by andrejohansson** [comment]
I tested before by adding a try catch on everything (catching exception) and in that catch I called Assert.Fail. But still no go, I can test an empty test with just assert.fail I guess?

**Comment by CharliePoole** [comment]
Yes, an empty test with an Assert.Fail should run the number of times you specify before finally reporting a failure.

Can you post one of your tests with retry that is not failing? Show all the attrbutes on the test method.

**Comment by andrejohansson** [comment]
This test executes the retries:

```
        [Test]
        [Retry(TestHelper.DefaultRetryCount)]
        [Category("FailureTest")]
        public void Dummy_Test_Should_Run_Three_Times()
        {
            // Test to figure out https://github.com/nunit/nunit/issues/1260
            Assert.Fail();
        }
```

So, I guess that is my usage of selenium that is incorrect:

I thought this would work:
```
        [Test]
        [Retry(TestHelper.DefaultRetryCount)]
        [Category("FailureTest")]
        public void Dummy_Test_Should_Run_Three_Times()
        {
            try
            {
                // Selenium code
            }
            catch (Exception)
            {
                // Test to figure out https://github.com/nunit/nunit/issues/1260
                Assert.Fail();
            }
        }
```

Anyway, the issue seems to be outside nunits scope, sorry to bother!

**Comment by CharliePoole** [comment]
Your code is throwing an exception inside an exception block, which won't give you the result you want. To use the try / catch workaround, you would have to do something like

```C#
bool failed = false;

try
{
    // Selenium code
}
catch(Exception)
{
    failed = true;
}

if (failed) Assert.Fail();
```

However, I think the best approach is to remove the try/catch and simply observe just what kind of error or exception is being reported. Then we would know how to fix it.

**Comment by andrejohansson** [comment]
I opted for this style of tests and it seems to be working:

```
        [Test]
        [Retry(TestHelper.DefaultRetryCount)]
        public void Customer_Login_On_Branded_SubDomain()
        {
            Assert.DoesNotThrow(() => {
                ...selenium code here
            });
        }
```

Maybe some guidance in the documentation would be good? Thank you!

**Comment by CharliePoole** [comment]
Do you have some specific suggestions for the docs? Note 3 on the RetryAttribute page is intended to cover this situation. Maybe we should add that some third party products throw other kinds of exceptions?

**Comment by andrejohansson** [comment]
Yes, note 3 covers it for sure, I would maybe suggest that you link to the [ExceptionAsserts](http://www.nunit.org/index.php?p=exceptionAsserts&r=2.5) page to give developers a hint that they exist.

**Comment by CharliePoole** [comment]
Good idea. Your link is to the NUnit 2.5 documentation. You should always try to use the current documentation. For NUnit 3.0, this is now on our docs wiki at https://github.com/nunit/docs/wiki

I put a link on the page to the ThrowsConstraint.
