### ISSUE TITLE
TypeHelper.GetDisplayName generates the wrong name for generic types with nested classes

### ISSUE THREAD

**Issue by Green-Bug** [nunit/nunit#1261]
Having classes:
```cs
public class Class1<T,S>
{
    public class Class2<K>
    {
        public void T()
        {}
    }
}
```
For variable:
```cs
     var s = new Class1<int, string>.Class2<long>();
```
GetDisplayName returns `"Class1<Int32,String,Int64>"` but it should return `"Class1<Int32,String>+Class2<Int64>"`

**Comment by constructor-igor** [comment]
reproduced
test class:
```c#
    [TestFixture]
    public class NUnitIssue1261
    {
        public class Class1<T, S>
        {
            public class Class2<K>
            {
                public void T()
                { }
            }
        }

        [Test]
        public void GetDisplayName()
        {
            var s = new Class1<int, string>.Class2<long>();

            string actual = TypeHelper.GetDisplayName(s.GetType());
            Assert.That(actual, Is.EqualTo("NUnitIssue1261+Class1<Int32,String>+Class2<Int64>"));
        }
    }
```
error's message:
![image](https://cloud.githubusercontent.com/assets/1849690/13047301/c9386632-d3e6-11e5-88cb-c0469a09435f.png)

**Comment by CharliePoole** [comment]
Thanks for confirming @constructor-igor 

I recall going to a lot of trouble making the name come out that way for inherited classes. Not sure why it's happening for nested classes as well.

**Comment by CharliePoole** [comment]
@nunit/core-team Does everyone agree that the name should be as the test above expects it?
