### ISSUE TITLE
Opinion: Generated test names for parametrized generic functions are hard to read

### ISSUE THREAD

**Issue by Green-Bug** [nunit/nunit#1265]
When writing tests for #1261 I've realized that the generated names include the namespace for the generic parameter and the names used are the .Net internal names not the C# friendly names.
Example for function:

``` cs
[TestCase(typeof(C<List<char[]>, long>.D<IDictionary<int,byte[]>,string>), ExpectedResult = "TypeHelperTests+C<List<Char[]>,Int64>+D<IDictionary<Int32,Byte[]>,String>")]
[TestCase(typeof(C<,>.D<,>), ExpectedResult = "TypeHelperTests+C<T1,T2>+D<T3,T4>")]
public string GetDisplayNameTests(Type type)
{
    return TypeHelper.GetDisplayName(type);
}
```

Leads to the test names:

```
Test Name:  GetDisplayNameTests(NUnit.Framework.Internal.TypeHelperTests+C`2+D`2[System.Collections.Generic.List`1[System.Char[]],System.Int64,System.Collections.Generic.IDictionary`2[System.Int32,System.Byte[]],System.String])
Test FullName:  NUnit.Framework.Internal.TypeHelperTests.GetDisplayNameTests(NUnit.Framework.Internal.TypeHelperTests+C`2+D`2[System.Collections.Generic.List`1[System.Char[]],System.Int64,System.Collections.Generic.IDictionary`2[System.Int32,System.Byte[]],System.String])
```

and

```
Test Name:  GetDisplayNameTests(NUnit.Framework.Internal.TypeHelperTests+C`2+D`2[T1,T2,T3,T4])
Test FullName:  NUnit.Framework.Internal.TypeHelperTests.GetDisplayNameTests(NUnit.Framework.Internal.TypeHelperTests+C`2+D`2[T1,T2,T3,T4])
```

I would have liked to not have the namespace (there are arguments both for and against) and to use the C# friendlier names like this:

```
Test Name:  GetDisplayNameTests(TypeHelperTests.C<List<Char[]>,Int64>.D<IDictionary<Int32,Byte[]>,String>)
Test FullName:  NUnit.Framework.Internal.TypeHelperTests.GetDisplayNameTests(TypeHelperTests.C<List<Char[]>,Int64>.D<IDictionary<Int32,Byte[]>,String>)
```

and

```
Test Name:  GetDisplayNameTests(TypeHelperTests.C<T1,T2>.D<T3,T4>)
Test FullName:  NUnit.Framework.Internal.TypeHelperTests.GetDisplayNameTests(TypeHelperTests.C<T1,T2>.D<T3,T4>)
```

What is the general opinion, should the names be more readable? Should they include the namespace or not? I could try a fix for this if the consensus is that the names should be shorter/more readable. However, after a quick glance I think the change will be somewhat big as a lot of the tests depend on the current naming.

**Comment by CharliePoole** [comment]
Do you have a specific example, where these names are used externally? TypeHelper is an internal class, so readability really only comes in to it when we use it's methods for some purpose. For example, I have not encountered test names displayed using the internal format in the gui. Let's figure out just what this affects before worrying about it too much.

**Comment by Green-Bug** [comment]
Those are not internal strings that's the name of the test as displayed in the Test Explorer in Visual Studio when a test function has generic parameters. This isn't related to `TypeHelper`, it just so happened that a good example was the test function for it.
The exact same names are shown when exploring the test assembly with `nunitlite-runner.exe`, for example an already existing test:
```cs
[TestCase(typeof(List<int>), ExpectedResult="List<Int32>")]
public string GetDisplayNameTests(Type type)
{
    return TypeHelper.GetDisplayName(type);
}
Is named:
NUnit.Framework.Internal.TypeHelperTests.GetDisplayNameTests(System.Collections.Generic.List`1[System.Int32])
```

**Comment by CharliePoole** [comment]
OK, let me explore this a bit more. In this case we are looking at generic arguments of a method. The other cases I can think of are (1) the name of a generic method itself and (2) the name of a generic fixture itself. Each of those may appear as either open or closed in the adapter or the gui.

I have one of those vague recollections that there might be some reason I decided to use the internal format for method arguments, as opposed to the other uses. I'll check back in NUnit V2 and see if I can find the reason there.

**Comment by jnm2** [comment]
How much do we want to favor C# over other languages? We're all used to having to look at `Type.ToString()` representation. The .NET reflection API does its job well by exposing the IL spec's type/string serialization and deserialization. It's the easiest thing in the world to do ([after this](https://github.com/jnm2/ApiContractGenerator/blob/v1.0.0/src/ApiContractGenerator/SerializedTypeReader.cs) lol), but should we do it?

And should we stop showing namespaces of arguments that are `Type` objects? I'm willing to be convinced, but right now I see no reason to treat them differently from any other domain object of any other API. The domain object tells you what its default textual representation should be through `ToString()`. Customizing that is why we have the TestName property (and are adding SetArgDisplayNames).

**Comment by rprouse** [comment]
If we change the test names it will break the Visual Studio adapter. Visual Studio 2017 has code that uses Roslyn to generate test names to improve the performance of the various test adapters rather than compiling and use the adapters to explore the tests. The do this to improve performance.

**Comment by jnm2** [comment]
@rprouse If I understand correctly, this issue is not talking about the type name of the containing class (as in `{C}`) but rather the display representation of any `Type` parameters to a parameterized method (or constructor). I feel like we should be able to customize that without breaking the VS adapter, right?

**Comment by rprouse** [comment]
@OsirisTerje can you weigh in on this issue? You have been more involved with this, I've just attended a few meetings with the VS team :bowtie:

**Comment by jnm2** [comment]
Just as an example, I might use `new TestCaseData(false).SetName("{m}()")` and
`new TestCaseData(true).SetName("{m}(with foo)")`. Visual Studio doesn't seem to get lost when I take control of the display of the bool parameter like that . I would have the same expectation about any parameter type, including parameters of type `System.Type` which this issue discusses.

**Comment by rprouse** [comment]
I am closing old Idea issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
