### ISSUE TITLE
SetCultureAttribute does not work if set on assembly level

### ISSUE THREAD

**Issue by Suremaker** [nunit/nunit#1266]
Hello,

I was trying recently to specify the invariant culture for all the tests run in my project.
I have found that in NUnit 3, the [SetCulture] attribute allows to control culture used in test(s) and it can be applied on method, class or assembly.

It looks however that if I specify it on assembly level, the culture is not applied to tests.

Below, there is a test reproducing this issue (I run it in VS2015 with R# 10.0.2 and NUnit 3.0.1):

```c#
using System.Globalization;
using NUnit.Framework;
[assembly: SetCulture("")]

namespace ClassLibrary1
{
    //[SetCulture("")]
    [TestFixture]
    public class SetCultureTests
    {
        [Test]
        public void It_should_set_proper_culture()
        {
            Assert.That(CultureInfo.CurrentCulture, Is.EqualTo(CultureInfo.InvariantCulture));
        }
    }
}
```

Thanks,
Wojtek

**Comment by constructor-igor** [comment]
the issue reproduced with help of console nunit:

![image](https://cloud.githubusercontent.com/assets/1849690/13046788/a35db398-d3e3-11e5-92b2-e3488511f9e2.png)

report:

```xml
<environment framework-version="3.0.5813.39031" clr-version="4.0.30319.42000" os-version="Microsoft Windows NT 6.1.7601 Service Pack 1" platform="Win32NT" cwd="...\NUnitSamples\NUnit_v3_samples" machine-name="MACHINE" user="constructor" user-domain="HOME" culture="en-US" uiculture="en-US" os-architecture="x64" />
```

**Comment by rprouse** [comment]
Thanks @constructor-igor, marking confirmed an moving to the backlog.

**Comment by CharliePoole** [comment]
There's actually a TODO comment in NUnitTestAssemblyRunner that says we need to do something about attributes that implement IApplyToContext!
