### ISSUE TITLE
Plan to support UWP?

### ISSUE THREAD

**Issue by xied75** [nunit/nunit#1271]
Dear Team,

Is there plan/work to support UWP? (Testing on UWP library would be good enough, not really need to handle UI/XAML for now).

Best

**Comment by rprouse** [comment]
I need to document it, but you can test UWP currently using NUnitLite. I am pretty sure that my steps for [testing .NET Core using NUnit](http://www.alteridem.net/2015/11/04/testing-net-core-using-nunit-3/) will work for a UWP assembly with minor modifications.

Another option is to use the NUnit Xamarin runner to test your UWP code which gives you a limited UI runner. A variation of the instructions for [testing Xamarin projects using NUnit 3](http://www.alteridem.net/2015/12/21/testing-xamarin-projects-using-nunit-3/) should work. I am pretty sure you don't need a Xamarin license or Xamarin installed for the UWP bits.

We are working on a more streamlined approach for UWP for an upcoming release. That is part of issue #1138, so I am going to close this as a duplicate. 

Feel free to add comments to this issue if you have any problems getting it working and I will help you out.

**Comment by xied75** [comment]
Close is fine, I'll track the other issue. As long as you are working on UWP testing, then all is well. :+1:
