### ISSUE TITLE
Cast exception

### ISSUE THREAD

**Issue by TigerLuHu** [nunit/nunit#1274]
I'm using Nunit 2.6.4 in VS2010 through resharper, and I got the exception below in one test,

[A]NMS.Data.Configurations.SystemSettingInstanceConfigNode cannot be cast to [B]NMS.Data.Configurations.SystemSettingInstanceConfigNode. Type A originates from 'NMS.Data.Configurations, Version=1.0.8.4631, Culture=neutral, PublicKeyToken=null' in the context 'LoadNeither' at location 'D:\WorkArea\Neusoft\MR\Platfrom\1_Source_Code\NMS\Host\Bin\NMS.Data.Configurations.DLL'. Type B originates from 'NMS.Data.Configurations, Version=1.0.8.4631, Culture=neutral, PublicKeyToken=null' in the context 'Default' at location 'C:\Users\Administrator\AppData\Local\Temp\e4anrsxt.jm0\xfh1b0gh.inv\NMS.MR.Review.TwoD.Test\assembly\dl3\6ed9682d\3d335d25_8910d101\NMS.Data.Configurations.DLL'. 

The dll in D:\ is which I use, the dll in C:\ should be auto copied from d:\, I compared they are same dll.
why this happened and how to get rid of this exception?

**Comment by rprouse** [comment]
You will need to provide more information on your tests for us to help you. I am closing, but if you are still having problems, add more info to the issue and we will try to help.
