### ISSUE TITLE
nunit3 only finds some tests

### ISSUE THREAD

**Issue by RedX2501** [nunit/nunit#1277]
I'm trying to use nunit3 with [SpecsFor.Mvc](http://specsfor.com/SpecsForMvc/default.cshtml). This worked fine in nunit2 but with nunit3 all tests that derive from SpecsFor\<MvcWebApp\> are not being found. Neither nunit3-console is able to run them nor the Nunit3Adapter shows them

All other tests derived from SpecsFor\<[Any other class I wish to test]\> show up fine.

There are no warnings or compilation error on the test project. Also no warnings or errors when running in the console.

I have also reported the issue on the SpecsFor repo (https://github.com/MattHoneycutt/SpecsFor/issues/87).

This can easily be reproduced by using the SpecsFor repo and replacing Nunit2 with Nunit3 in SpecsFor.Mvc.Demo.AcceptanceTests and trying to run it with nunit3-console. One can see 2 explicit tests are listed and nothing else. Looking at the code there are many tests though.

**Comment by CharliePoole** [comment]
I've done a search through the SpecsFor repo and it appears to be based on NUnit V2. NUnit 3.0 is a major break from V2 and most 3rd party products using NUnit have had to make changes and announce a new version that uses NUnit 3.0.

We'll wait to see what results from the issue you filed with SpecsFor, but there's nothing for us to fix unless the author identifies something that he depended on, which is not being supported in 3.0.

**Comment by RedX2501** [comment]
Thank you for the quick answer.

I have looked myself into the code and being new to NUnit i think i missed many spots where the coupling might be tight and was hoping for some pointers.

All I saw were the attributs in the SpecsFor class that point me to the NUnit integration. What have i missed?

If you can point me to some documentation where i could learn about these topics i mght be able to provide a patch to the library.

**Comment by CharliePoole** [comment]
All I know about SpecsFor is what I googled last night. :-)

You could look to see how they use NUnit. Is it referenced somewhere? If their code is referencing one version of the framework, you probably can't reference a different version in your tests.

**Comment by rprouse** [comment]
I am going to close this since it is an issue with SpecsFor, not with NUnit
