### ISSUE TITLE
Fix optional parameters in TestCaseAttribute

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#1278]
e.g.

```
[TestCase(1, 2, 3)]
[TestCase(1, 2)]
public void Addition(int a, int b, int c=1)
...
```

Attempted this the other day, to find the reflection method throws a `TargetParameterCountException`. Is there any design-reason why this shouldn't be supported?

**Comment by ChrisMaddock** [comment]
Actually, I wonder if this is a bug, rather than a feature request?

`CheckTestMethodSignature()` [seems to look for optional parameters](https://github.com/nunit/nunit/blob/66770788ea6ee1e970efd65aba81ccae23af8cd8/src/NUnitFramework/framework/Internal/Builders/NUnitTestCaseBuilder.cs#L159). The issue is perhaps just that the reflection `Method.Invoke` should be passing in `Type.Missing` in place of optional parameters.

**Comment by CharliePoole** [comment]
Yes, this feature was added for 3.0 alpha-5 by PR #457, resolving issue #257. Tests were added to TestCaseBuilderTests.cs in that PR. You should compare those tests to yours to see what broke. Since you have started a PR for this, I'll go ahead and assign to you.

**Comment by CharliePoole** [comment]
@ChrisMaddock You have to precede the ref to the issue (#1278) wtih the word fix or fixes in order to make it close automagically when the PR is merged. Closing manually
