### ISSUE TITLE
value of the time attribute in nunit2 outputs depends on the machine culture

### ISSUE THREAD

**Issue by mnivet** [nunit/nunit#1286]
When using nunit3 xml format as output result, all duration are always in invariant format (example: duration="0.000383")

But when using nunit2 xml format (because we have still some parts of our CI tools that doesn't understand the new format), the durations in the time attribute follow the culture of the machine (example with a machine in frecnh: time="0,083" instead of time="0.083")

This cause time measures to be misinterpreted due to the use of commas where dots are expected.
And this was not the case before we start moving to nunit3.

**Comment by rprouse** [comment]
Are you suggesting that we update the nunit2 format to use the invariant culture?

I would agree, but would also worry about breaking backwards compatibility/incompatibility.

**Comment by mnivet** [comment]
With the nunit2 console (nunit-console.exe) the format was invariant (we still have some projects using it so I'm sure of that)

My request is to fix the issue in the nunit3 console because it's a backward incompatibility.

**Comment by rprouse** [comment]
Thanks for the clarification. I will see if we can get this fixed quickly.

**Comment by CharliePoole** [comment]
@mnivet So we're talking about the nunit2 output produced by NUnit 3.0?

**Comment by mnivet** [comment]
@CharliePoole Yes

**Comment by mnivet** [comment]
Thanks
