### ISSUE TITLE
Execute tests in interactive user session

### ISSUE THREAD

**Issue by ghost** [nunit/nunit#1287]
It would be great if nunit supports this feature. To execute tests that can interact with desktop we need execute nunit*.exe process in interactive user session. We need it because we are testing User Interface. To reach this goal we use [PsExec](https://technet.microsoft.com/en-us/sysinternals/psexec.aspx) tool. This tool takes _-i_ argument and executes a process in specified user session. The reason of why we use this tool that our tests can interact with UI, usually with Desktop Elements.

If nunit can support this feature from the box it would be very good. I saw that nunit-agent can work as a service, I can allow this service to interact with desktop. I am not sure that this service will work properly if windows user is logged off (service is running).

I am able to test something UI specific to approve/decline the nunit functionality what I expect.

**Comment by CharliePoole** [comment]
NUnit-agent is not strictly speaking a service. In fact, it's a client of the TestAgency, a component of the NUnit engine. TestAgency is a service, operating at a specified IP address. NUnit-agent connects to that service and registers itself. After it connects, it waits for the agency to give it a job to run, runs it and then terminates it. So, after it first connects as a client, it operates a bit like a service for the original service, which operates as if it were a client. This is very much like the way that an XTerminal works.

To move this request forward, we need to understand it a little better. Can you provide an example of using psexec to run a test that works correctly (no ui) and another that does not work?

**Comment by caspernick** [comment]
I created a simple UI test. Sources are on [github](https://github.com/caspernick/myfirstproject). Results are [here](https://ci.appveyor.com/project/caspernick/myfirstproject/build/1.0.12/tests). If you execute this test on your local machine manually this test passes.

The cause of issue is that test was executed in inactive user session (on CI), so CI cannot interact with desktop.

I understand that this feature request is more related to CI tool. Yes, you are right, this is responsibility of CI configuration.

**Comment by rprouse** [comment]
@caspernick I am going to mark this as an enhancement and move to ideas. It needs some design before someone works on it. If you want this to move forward, feel free to help with the design and possible implementation.

**Comment by rprouse** [comment]
I think the new command line option `--loaduserprofile` which causes the User Profile to be loaded into the NUnit Agent process solves this need. @caspernick can you test?

**Comment by CharliePoole** [comment]
We put that option in pretty quickly. One question I had about it is why is it an option? Shouldn't we use the profile of the current user in any process we launch without being told? Are there times when that would be bad?

However, it doesn't look to me like it solves the problem of wanting to use an __arbitrary__ user identity, if that's what is being asked for here.

**Comment by rprouse** [comment]
Good point on this issue @CharliePoole. For the command line, I decided not to make that option the default because the Microsoft documentation states that doing so is an expensive operation and should be avoided unless it is necessary.

**Comment by CharliePoole** [comment]
Fair enough.

**Comment by rprouse** [comment]
@ghost I am closing since we have not heard back from you. If you have more information, add it to this issue and we will reopen.
