### ISSUE TITLE
Is.EqualTo doesn't fail the test when a RuntimeBinderException is thrown

### ISSUE THREAD

**Issue by fourpastmidnight** [nunit/nunit#1288]
I'm using NUnit 3.0.1. I have the following SpecFlow scenario step code:

```csharp
[Then(@"the server returns the (?:newly )?posted entry")]
public void ThenTheServerReturnsTheNewlyPostedEntry()
{
    dynamic expectedJournalEntry = _context.Get<dynamic>("journalEntry");
    var response = _context.Get<HttpResponseMessage>();
    dynamic actualJournalEntry = response.Content.ReadAsJsonAsync().Result.entries[0];

    Assert.That<dynamic>(actualJournalEntry.time, Is.EqualTo(expectedJournalEntry.time));
}
```

I know that I don't need to explicitly specify the type for `Assert.That<>`, but I want to make it clear that I'm trying to assert equality on two dynamics.

I expected this test to fail because I'm not returning the correct entry from the HTTP server. However, the test passed. So, I'm scratching my head.

Next, I ran the debugger and looked at the values of `actualJournalEntry` and `expectedJournalEntry`. They are indeed _not equal_. But, when I step over the Assert, everything is fine and the test passes.

So then I use the Visual Studio Immediate Window and manually type in the assertion:

```
NUnit.Framework.Assert.That(actualJournalEntry.time, Is.EqualTo(expectedJournalEntry.time))

'NUnit.Framework.Assert.That(actualJournalEntry.time, Is.EqualTo(expectedJournalEntry.time))' threw an exception of type 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException'
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2146233088
    HelpLink: null
    InnerException: null
    Message: "Cannot implicitly convert type 'void' to 'object'"
    Source: "Anonymously Hosted DynamicMethods Assembly"
    StackTrace: "   at CallSite.Target(Closure , CallSite , Type , Object , Object )\r\n   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)"
    TargetSite: {System.Object CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Type, System.Object, System.Object)}
```

So, even though a `Microsoft.CSharp.RuntimeBinder.RuntimeBinderException` is being thrown, NUnit is not getting this exception and the test is still passing.

**Comment by fourpastmidnight** [comment]
So, I expected this step to fail due to the fact that I never read anything from the database.

So, in my original code example above, the following line seems to execute just fine:

```csharp
dynamic actualJournalEntry = response.Content.ReadAsJsonAsync().Result.entries[0];
```

And then, after that, the assertion:

```csharp
Assert.That<dynamic>(actualJournalEntry.time, Is.EqualTo(expectedJournalEntry.time));
```

Again, this assertion never triggers a test failure even though a `RuntimeBinderException` is thrown.

However, if I change the code as follows:

```
dynamic actualJournalEntries = response.Content.ReadAsJsonAsync().Result.entries;
dynamic actualJournalEntry = actualJournalEntries[0]

Assert.That<dynamic>(actualJournalEntry.time, Is.Equalto(expectedJournalEntry.time));
```

Then, an exception is thrown on the second line: `ArgumentOutOfRangeException`. This is totally expected because there's nothing in the list because the SUT never reads from the database (yet).

So, why doesn't the `EqualToConstraint` fail on `RuntimeBinderException`?

**Comment by appel1** [comment]
This test succeeds for the same reason as #1289 does. Both your time objects are empty enumerables and so are considered equal by nunit by default. 

The following assert fails as expected. 
```charp
Assert.That<dynamic>(actualJournalEntry.time, Is.EqualTo(expectedJournalEntry.time).Using(JToken.EqualityComparer));
```

No clue about the RuntimeBinderException but it seems specific to running expressions in the immediate window. It does not happen when the test is executed using the R# runner or console runner.

**Comment by CharliePoole** [comment]
@appl1 Well spottted! I was distracted by the `dynamic` and didn't notice that they were enumerables.

**Comment by CharliePoole** [comment]
@fourpastmidnight I'll wait for any further comments from you before closing this but it does not appear to be a bug - at least not in NUnit. :-)

**Comment by fourpastmidnight** [comment]
@appel1 Ah, you're right, this issue and #1289 are the same, then.

@CharliePoole In xUnit, this test "just works"--i.e. it fails. I was a bit shaken by this passing NUnit test when I expected it to fail. I was lucky in that I knew it was supposed to fail ahead of time (I was watching a video training course). If I hadn't known the test was supposed to fail, I would've gotten a false positive and went merrily on my way. I'm not sure how I feel about this behavior, even though, from the explanation given by @appel1 you'd be hard pressed to say that it was "wrong", because, in another way, it is actually "correct".

The scary thing is, for this test, it can both pass and fail for different reasons. Maybe, then, the test that was demonstrated in the video was a bad test? It wouldn't be the first time I've seen a bad test in a training course about testing.

**Comment by CharliePoole** [comment]
You're not the first person to be confused by NUnit's definition of equality in the context of an assert. It's documented, but maybe not emphasized enough.
