### ISSUE TITLE
CollectionAssert.Contains not failing on collections which don't contain the item

### ISSUE THREAD

**Issue by fourpastmidnight** [nunit/nunit#1289]
Ok, another possible issue. Just some more context: I'm working through a PluralSight course from Mark Seeman, Outside-in Testing, so the sample application is a work in progress. I decided to use NUnit with SpecFlow instead of xUnit (which Mark uses in the course). However, I verified this scenario with standard NUnit tests (i.e. without SpecFlow) and the same issue is occurring.

The setup is, we've written a two tests that POST data to a WebApi that track's a runner's journal entries for their runs. Currently, the WebAPI is storing the entries in a static list within the controller. Here's what the list looks like in JSON: 

```json
{
    "entries": [
        {
            "time": "2016-02-25T20:18:21-05:00",
            "distance": 8500,
            "duration": "00:44:00"
        },
        {
            "time": "2016-02-25T20:18:22-05:00",
            "distance": 8500,
            "duration": "00:44:00"
        }
    ]
}
```

We are at the point in our outside-in testing where we are introducing a non-volatile persistence store, i.e. a database. So the next test is to write an entry to the database and attempt to retrieve the entry from the database. However, practicing "test first", the WebAPI doesn't yet read from the database (it only returns the static list held by the controller), so the test should fail because the entry we're looking for is not returned. Here's the test:

```csharp
// Given a journal entry exists in the database
// When a HTTP client visits the home page
// Then the server returns the entry in the database

[Given(@"[Aa] journal entry exists in the database")]
public void GivenAJournalEntryExistsInTheDatabase()
{
    GivenAHTTPClient();

    dynamic entry = new ExpandoObject();
    entry.time = DateTimeOffset.Now;
    entry.distance = 6000;
    entry.duration = TimeSpan.FromMinutes(31);

    var expected = new JsonContent((object)entry).ReadAsJsonAsync().Result;
    _context.Set<dynamic>(expected, "journalEntry");

    var connStr = ConfigurationManager.ConnectionStrings["RunningJournal"].ConnectionString;
    var db = Database.OpenConnection(connStr);
    var userId = db.User.Insert(UserName: "foo").UserId;
    entry.userId = userId;
    db.JournalEntry.Insert(entry);
}

[When(@"(?:[Aa]|[Tt]he) HTTP client visits the home page")]
public void WhenTheHTTPClientVisitsTheHomePage()
{
    var client = _context.Get<HttpClient>();
    var response = client.GetAsync("").Result;
    _context.Set<HttpResponseMessage>(response);
}

[Then(@"the server returns the (?:newly )?posted entry")]
[Then(@"the server returns the entry in the database")]
public void ThenTheServerReturnsTheNewlyPostedEntry()
{
    var expectedJournalEntry = _context.Get<dynamic>("journalEntry");
    var response = _context.Get<HttpResponseMessage>();
    var actualJournalEntries = response.Content.ReadAsJsonAsync().Result.entries;

    // I expect this assert to fail because expectedJournalEntry is not in the
    // list of actualJournalEntries entries.
    CollectionAssert.Contains(actualJournalEntries, expectedJournalEntry);
}
```

Again, `actualJournalEntries` will contain the list of objects shown as JSON above, while `expectedJornalEntry` contains the data created in the "given" method in the test. This test should fail, but it passes.

**Comment by fourpastmidnight** [comment]
I just tried using the following assertion in the "Then" portion instead, and the test still passes:

```csharp
Assert.That(actualJournalEntries, Has.Some.EqualTo(expectedJournalEntry));
```

**Comment by CharliePoole** [comment]
How is this different from #1288? Isn't it what you would expect given the behavior on each individual item?

**Comment by fourpastmidnight** [comment]
No, this is not the same.

I happened to post these two issues very close together in succession as I'm working through the PluralSight course.

In the first issue, #1288, I actually had something wrong in the test--so the actual item that I was testing against, while `dynamic`, was null. So, `null.time` leads to a `RuntimeBinderException`, but in #1288, the test didn't fail--it passed!

Once I figured out that my test was invalid due to bad data, I corrected the test data; and when I had non-null values, the Equals constraint worked as expected. I still think there's an issue in #1288 when it comes to `dynamic` values that are null and trying to dereference a (non-existent) property leading to a `RuntimeBinderException`. But it should be investigated further to confirm the behavior.

For this issue, however, I have a non-null item that I'm trying to test for whether it exists in a collection (per the JSON collection shown in my original issue description above). I know for a fact that the item doesn't exist in the collection (as can be seen in the JSON and C# code snippet), so I expect that `CollectionAssert.Contains(...)` should fail. However, it passes.

**Comment by fourpastmidnight** [comment]
The only way I could get this test to fail the way I expected is to change my assertion as follows:

```csharp
// It turns out, even though actualJournalEntries is dynamic, 
// it's real type is JArray from NewtonSoft.Json
Assert.That(
    actualJournalEntries.Children().Any(
        e => e["time"] == expectedJournalEntry.time &&
             e["distance"] == expectedJournalEntry.distance && 
             e["duration"] == expectedJournalEntry.duration
    ), 
    Is.True
);
```

**Comment by CharliePoole** [comment]
We'll leave them both here then. I suspect that the underlying cause is simply that we make no special allowance for dynamic values in the framework and don't test for them either.

**Comment by appel1** [comment]
I think this is because all Newtonsoft.Json objects implements IEnumerable. So when NUnit compares two entries it compares them as IEnumerable. Those enumerables contain three elements. When NUnit then compares those elements they also implement IEnumerable but are empty since the object that represents for example the "time" value has no children. From NUnit's point of view all Newtonsoft.Json elements are equal as long as they have the same structure. 

So this test fails:
```csharp
        [Test]
        public void CollectionContains()
        {
            const string actualJson = @"{
    ""entries"": [
        {
            ""time"": ""2016-02-25T20:18:21-05:00"",
            ""distance"": 8500,
            ""duration"": ""00:44:00""
        },
        {
            ""time"": ""2016-02-25T20:18:22-05:00"",
            ""distance"": 8500,
            ""duration"": ""00:44:00""
        }
    ]
}";

            const string expectedJson = @"{
    ""foo bar"": [
        {
            ""x"": 123,
            ""gh"": ""foo bar"",
            ""asdfdsg"": ""00:11:00""
        },
        {
            ""asdfsdg"": ""2016-02-25T20:18:22-05:00"",
            ""dsgsd"": 34234434,
            ""gf3"": ""00:01:00""
        }
    ]
}";

            dynamic expected = JsonConvert.DeserializeObject<dynamic>(expectedJson);
            dynamic actual = JsonConvert.DeserializeObject<dynamic>(actualJson);

            Assert.That(actual, Is.Not.EqualTo(expected));
        }
```
```
  Expected: not equal to < < < < < <empty> >, < <empty> >, < <empty> > >, < < <empty> >, < <empty> >, < <empty> > > > > >
  But was:  < < < < < <empty> >, < <empty> >, < <empty> > >, < < <empty> >, < <empty> >, < <empty> > > > > >
```

To get the expected behavior you need to use a custom comparison for JToken with your asserts.
```csharp
Assert.That(actual, Is.Not.EqualTo(expected).Using(JToken.EqualityComparer));
```
Don't think there's any way to register such a comparison globally in NUnit.

**Comment by fourpastmidnight** [comment]
That's very interesting and unexpected. Do you think this behavior is specific to JSON.net, or are things like what I'm seeing in my test going to popup due to the use of `dynamic`s and the C# DLR in general?

**Comment by fourpastmidnight** [comment]
This issue has the same root cause as #1288 and is not a bug.

**Comment by CharliePoole** [comment]
@appel1 I'm looking at a future way to register equality comparisons. However, in this case, does the NewtonSoft.Json object implement equality comparison itself in any way? it has been requested that we detect and use existing definitions of equality __even__ if the object is an enumerable.

**Comment by fourpastmidnight** [comment]
@CharliePoole Looking through the NewtonSoft.Json GitHub project, it appears that all the `J*` classes inherit from `JToken`, including `JObject`. There's also a class called `JTokenEqualityComparer`, which is what @appel1 accessed in #1288 through a static property that lives off the `JToken` class, though, `JTokenEqualityComparer` can also be instantiated by outside parties. `JToken` defines a whole slew of explicit and implicit conversion operators, but doesn't itself override `System.Object.Equals` nor implement `IEquatable<T>`.

`JValue` inherits from `JToken` as well, but in addition to that, it also implements `IEquatable<JValue>` and `IComparable<JValue>`.

Hope this helps.

**Comment by CharliePoole** [comment]
Thanks for the info. It sounds as if the proposed enhancement wouldn't help you either then.
