### ISSUE TITLE
Implement arguments for SetUpFixture, the same way as for TestFixture

### ISSUE THREAD

**Issue by AniaDomachowska** [nunit/nunit#1300]
Would it be possible to implement arguments for SetUpFixture, so that all the tests this global fixture covers would be repeated for different conditions?

For example, I would like to run set of 10 fixtures for several different databases. Those databases would be set up in the SetUpFixture as different arguments.

Cheers,
AD

**Comment by sms1** [comment]
Hi,
Would like to know if this feature is added? I need to run the same testcases for two different DB.
Thanks,
Stephly

**Comment by CharliePoole** [comment]
No, as you see, it's classified as an idea rather than a feature. That means it's something to discuss, find out if many people would want to use it and decide whether to implement it at some time in the future.

**Comment by jcansdale** [comment]
@sms1,

You should be able to use abstract test fixtures for this. I.e. you have an abstract class with your test methods. You extend these and create concrete classes with your database SetUpFixture.

I haven't tried this with NUnit 3.x but it worked in previous versions of NUnit (TestDriven.Net had support for targeting tests in the abstract test fixture).

**Comment by rprouse** [comment]
I am closing old Idea issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
