### ISSUE TITLE
Create EventListener ExtensionPoint for the Engine

### ISSUE THREAD

**Issue by caspernick** [nunit/nunit#1302]
In NUnit2 I used EventListener interface for add-in. What is new approach in NUnit3? I am wondering only in events. Thanks all in advance.

**Comment by CharliePoole** [comment]
NUnit no longer supports addins in the framework and supports addins using a different architecture in the engine, which is a new component. For extending the framework, you can design custom attributes. Which approach to use depends on the purpose. Ideally, I would suggest that you extend the framework only for operations that are part of with your test and extend the engine for things like logging, saving results, etc. which are __about__ your test but separate from it. This separation of concerns should make your tests usable under multiple runners and platforms.

WRT EventListener: Unfortunately, this is not yet an extension point for the engine, but will be added. Most uses of EventListener really belong in the engine.

In the framework, it's possible to create an ActionAttribute that runs before and after every test. You could use that to simulate the use of EventListener in the early version. Whether or not this is feasible will depend on what you want to do in the listener. Hopefully, any such solution would be short-term and you would replace it  when we add a test listener extension point to the engine.

**Comment by CharliePoole** [comment]
I have renamed this issue to indicate that we will create such an extension point - priority to be determined.
