### ISSUE TITLE
NoItemConstraint different behavior of Has.None and Has.No

### ISSUE THREAD

**Issue by Thorarin** [nunit/nunit#1308]
According to https://github.com/nunit/docs/wiki/NoItemConstraint, the **Has.None** and **Has.No** syntaxes should behave exactly the same. This is not the case however:

    [TestFixture]
    public class MyTests {
        private class MyItem {
            public bool IsDeleted { get; set; }
        }

        [Test]
        public void HasNone_Test() {
          var items = new List<MyItem> { new MyItem() };
          Assert.That(items, Has.None.Matches<MyItem>(w => w.IsDeleted));  // Succeeds
        }

        [Test]
        public void HasNo_Test() {
          var items = new List<MyItem> { new MyItem() };
          Assert.That(items, Has.No.Matches<MyItem>(w => w.IsDeleted));  // Fails
        }
    }

The **Has.No** syntax seems much more intuitive to me in this case, but it fails with the following error:

> System.ArgumentException : The actual value is not of type MyItem
> Parameter name: actual

The error message suggests that NUnit is checking something else entirely. I believe this to be a bug, but if this is intended behavior then at the very least the documentation pages should explain the difference between **Has.No** and **Has.None**.

I'm using NUnit 3.0.1. The test fails when running `nunit3-console.exe MyTestAssembly.dll` (using CLR 4.0)

**Comment by CharliePoole** [comment]
In fact, it's so intuitive that I mistakenly put it the docs. In the current code, it's equivalent to Is.Not.

For the moment, I've removed Has.No from that page. I want to research what it did in older versions of NUnit before deciding what's the best course of action.

**Comment by CharliePoole** [comment]
It turns out that the V2 docs have exactly the same problem, so I'll need to change those docs as well.

Looking at some of our own tests, I think the idea was that 'No' works well in constraints like
```C#
Assert.That(myActual, Has.No.Property("X").EqualTo(42)
```

as opposed to 

```C#
Assert.That(myArray, Has.None.With.Property("X").EqualTo(42)
```

It turns out making the syntax fluent and intuitive in all cases isn't as easy as one may thing.

I also checked the Intellisense for `Has.No` and `Has.Not` and it does distinguish them correctly.
