### ISSUE TITLE
Ignore attribute not working when running as part of a nunit file with multiple dlls

### ISSUE THREAD

**Issue by DerekSMorin** [nunit/nunit#1309]
I have a dll with one test class that has been marked as "Ignore".

If I run this, the test is ignored:
"C:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe" --process=InProcess --workers=1 --wait ActivityReport.dll

If I run it as part of an nunit file with only the one test dll in it it is still ignored.

But if it is part of an nunit file with multiple dlls in it, the test is no longer ignored.

We run tests nightly with about 40 dlls and use the ignore mechanism to turn off problematic tests if they need to be worked on.

**Comment by DerekSMorin** [comment]
Never mind - this was confusing because cruise control was making it look like this test was still running.  I think it is actually the next test that is still running.  I've been confused by this before because nunit doesn't flush any logging until the test run completes.

**Comment by CharliePoole** [comment]
Actually, NUnit does flush it's logging as the test runs. I think you may mean that the final console report is not produced until after the run completes. The final report is not intended as a progress notification but as a ... final report!
