### ISSUE TITLE
Getting CF framework unit tests running on CI build

### ISSUE THREAD

**Issue by dicko2** [nunit/nunit#1317]
from #1305  

New issue for getting the unit tests running on Compact framework.

Two suggestions to fix.

1. Getting an emulator running some how to run the tests on a device
2. relaxing the rules so we will execute the CF framework code on windwos

There is 10 failing tests, listed below, some of them don't look platform related. But haven't had a detailed look yet.

Errors and Failures

1) Failed : NUnit.Framework.Api.TestAssemblyRunnerTests.Load_BadFile_ReturnsNonRunnableSuite
  Expected: String starting with "File or assembly name" and containing "mock-assembly.pdb"
  But was:  "Could not load file or assembly 'mock-assembly.pdb' or one of its dependencies. The system cannot find the file specified."
at NUnit.Framework.Api.TestAssemblyRunnerTests.Load_BadFile_ReturnsNonRunnableSuite() in d:\SOURCE\Repos\nunit\src\NUnitFramework\tests\Api\TestAssemblyRunnerTests.cs:line 121

2) Failed : NUnit.Framework.Api.TestAssemblyRunnerTests.Load_FileNotFound_ReturnsNonRunnableSuite
  Expected: String starting with "File or assembly name"
  But was:  "Could not load file or assembly 'file:///D:\SOURCE\Repos\nunit\bin\Release\netcf-3.5\junk.dll' or one of its dependencies. The system cannot find the file specified."
at NUnit.Framework.Api.TestAssemblyRunnerTests.Load_FileNotFound_ReturnsNonRunnableSuite() in d:\SOURCE\Repos\nunit\src\NUnitFramework\tests\Api\TestAssemblyRunnerTests.cs:line 104

3) Failed : NUnit.Framework.Api.TestAssemblyRunnerTests.Run_BadFile_ReturnsNonRunnableSuite
  Expected: String starting with "File or assembly name" and containing "mock-assembly.pdb"
  But was:  "Could not load file or assembly 'mock-assembly.pdb' or one of its dependencies. The system cannot find the file specified."
at NUnit.Framework.Api.TestAssemblyRunnerTests.Run_BadFile_ReturnsNonRunnableSuite() in d:\SOURCE\Repos\nunit\src\NUnitFramework\tests\Api\TestAssemblyRunnerTests.cs:line 234

4) Failed : NUnit.Framework.Api.TestAssemblyRunnerTests.Run_FileNotFound_ReturnsNonRunnableSuite
  Expected: String starting with "File or assembly name"
  But was:  "Could not load file or assembly 'file:///D:\SOURCE\Repos\nunit\bin\Release\netcf-3.5\junk.dll' or one of its dependencies. The system cannot find the file specified."
at NUnit.Framework.Api.TestAssemblyRunnerTests.Run_FileNotFound_ReturnsNonRunnableSuite() in d:\SOURCE\Repos\nunit\src\NUnitFramework\tests\Api\TestAssemblyRunnerTests.cs:line 216

5) Failed : NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_BadFile_ReturnsNonRunnableSuite
  Expected: String starting with "File or assembly name" and containing "mock-assembly.pdb"
  But was:  "Could not load file or assembly 'mock-assembly.pdb' or one of its dependencies. The system cannot find the file specified."
at NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_BadFile_ReturnsNonRunnableSuite() in d:\SOURCE\Repos\nunit\src\NUnitFramework\tests\Api\TestAssemblyRunnerTests.cs:line 321

6) Failed : NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_FileNotFound_ReturnsNonRunnableSuite
  Expected: String starting with "File or assembly name"
  But was:  "Could not load file or assembly 'file:///D:\SOURCE\Repos\nunit\bin\Release\netcf-3.5\junk.dll' or one of its dependencies. The system cannot find the file specified."
at NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_FileNotFound_ReturnsNonRunnableSuite() in d:\SOURCE\Repos\nunit\src\NUnitFramework\tests\Api\TestAssemblyRunnerTests.cs:line 301

7) Failed : NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetMethodByNameAndBindingFlags(NUnit.Framework.Tests.Compatibility.DerivedTestClass,"Goodbye",Instance, NonPublic,True)
  Expected: True
  But was:  False
at NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetMethodByNameAndBindingFlags(Type type, String name, BindingFlags flags, Boolean shouldFind) in d:\SOURCE\Repos\nunit\src\NUnitFramework\tests\Compatibility\ReflectionExtensionsTests.cs:line 260

8) Failed : NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetPropertyWithBindingFlags(NUnit.Framework.Tests.Compatibility.DerivedTestClass,"Private",Instance, Public, NonPublic,True)
  Expected: True
  But was:  False
at NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetPropertyWithBindingFlags(Type type, String name, BindingFlags flags, Boolean shouldFind) in d:\SOURCE\Repos\nunit\src\NUnitFramework\tests\Compatibility\ReflectionExtensionsTests.cs:line 224

9) Failed : NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetPropertyWithBindingFlags(NUnit.Framework.Tests.Compatibility.DerivedTestClass,"Private",Instance, Static, NonPublic,True)
  Expected: True
  But was:  False
at NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetPropertyWithBindingFlags(Type type, String name, BindingFlags flags, Boolean shouldFind) in d:\SOURCE\Repos\nunit\src\NUnitFramework\tests\Compatibility\ReflectionExtensionsTests.cs:line 224

10) Failed : NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.GetsPrivateMemberOnBaseClass
  Expected: 1
  But was:  0
at NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.GetsPrivateMemberOnBaseClass() in d:\SOURCE\Repos\nunit\src\NUnitFramework\tests\Compatibility\ReflectionExtensionsTests.cs:line 151

I've comment out the tests in the cake file so that it'll be easy to add them back in when we want to tackle this.

**Comment by CharliePoole** [comment]
Are you assuming we are going to merge @1305 without the tests, leaving this part incomplete? I mean we may, but right now, it's still all one PR aimed at issue  #331. I pulled down the branch to try to fix the tests, but the release took precedence.

[FYI, you'll find that we tend to push other things to the back of the pile when doing a release. It can be a little disconcerting for those nunit developers not actively working on getting the release out.]

**Comment by CharliePoole** [comment]
Most of these errors seem to be non-robust tests, but there is one thing that disturbs me. I can't see why CF is giving a FileNotFound for mock-assembly.pdb when I can see it's present. It should give an exception that says it can't load it, not that it can't find it. @oznetmaster any ideas?

**Comment by CharliePoole** [comment]
Ah! I didn't see the last line of your comment: "I've comment out the tests in the cake file so that it'll be easy to add them back in when we want to tackle this."

I am reading the comments on the two PRs in the wrong order. Do you have CF experience and can you work on it? Otherwise I can look at it when time permits.

**Comment by dicko2** [comment]
What I've done @CharliePoole is given us the option, I'm pretty sure 1305 is done, or almost done, so we can merge in when ready and it'll start picking up build breaking errors.

Then we can proceed with doing the tests as a second increment. Not to say the tests should be a low priority, but one of the proposed courses of action could take us some time was my concern, where as we have some immediate benefit from just building the code without the tests.

I've done three projects on CF in the past, two in recent years on CF 2.0 and one a long time ago on CF 1.0. So i can have a crack at it. But don't have much time in the next few weeks.

Not sure about the mock assembly file missing.

**Comment by CharliePoole** [comment]
Keep in mind that the tests were all passing in the emulator. They are only failing on the desktop as far as I know, although I haven't run them for a while.

**Comment by oznetmaster** [comment]
I run all the tests on an actual CF device, and they all pass there as well.

**Comment by CharliePoole** [comment]
I think it's some artifact of running in the desktop environment. IIRC, you get the desktop .NET implementation and possibly System.dll and everything else uses CF assemblies. I figured this all out once a long time ago, but I'll have to refresh my memory. I think just compiling gives us a lot already but it would be cool to run the tests too. We just have to decide how much effort it's worth as compared to other stuff.

**Comment by CharliePoole** [comment]
@dicko2 Since you won't be able to do much for a few weeks, I'm assigning this to myself. Feel free to chime in or chip in as you are able.

I have all the tests passing locally now, by checking for CF at runtime rather than compile time. I think it's just a matter of plugging in the test code from your old branch.
