### ISSUE TITLE
NUnit console runner fails with error code -100

### ISSUE THREAD

**Issue by janno-p** [nunit/nunit#1318]
I'm using NUnit3 console runner in build server and lately build does not complete, because NUnit console runner process fails. I see two NUnit related exception stacks in my build log:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at NUnit.Engine.Internal.ResultHelper.Merge(IList`1 results)
   at NUnit.Engine.Runners.AggregatingTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.NUnit.Engine.ITestRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
   at NUnit.ConsoleRunner.Program.Main(String[] args)
Running build failed.
Error:
Fake.UnitTestCommon+FailedTestsException: NUnit test failed. Process finished with exit code UnexpectedError (-100).
```

```
Unhandled Exception: System.ArgumentException: Cannot have '] ]>' inside an XML CDATA block.
   at System.Xml.XmlTextWriter.WriteCData(String text)
   at System.Xml.XmlElement.WriteElementTo(XmlWriter writer, XmlElement e)
   at System.Xml.XmlNode.get_OuterXml()
   at NUnit.Engine.TestEngineResult..ctor(XmlNode xml)
   at NUnit.Engine.Runners.ProcessRunner.CreateFailedResult(Exception e)
   at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.TestExecutionTask.Execute()
   at NUnit.Engine.Runners.ParallelTaskWorkerPool.ProcessTasksProc()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by rprouse** [comment]
It looks like we are not escaping `]` in the output. Can you narrow it down to tests that you added recently, maybe a `TestCase` or new data with a `]` in it? If you can narrow it down and post some code here, we can likely get this fixed fairly quickly. 

I was planning on doing the 3.2 release this weekend, so if you have time to work with me, I would like to get it fixed and in the release.

**Comment by rprouse** [comment]
Looking at the exception more closely, it looks like you have `] ]>` in a failure message. We handle `]]>` without the space. I am trying to reproduce now.

**Comment by rprouse** [comment]
So far, I cannot reproduce. I've tried adding `] ]>` into failing tests as part of the failure message and as a part of the test name by using it in a TestCase. I will keep trying for a bit, but if I continue to not be able to reproduce I will not be able to get this into the 3.2 release.

**Comment by rprouse** [comment]
@janno-p I still cannot reproduce, so I am lowering the priority. I am going to leave this in the 3.2 milestone for now, but I will not hold up the release. Once you can find the failing test in your code and provide us with a reproducible test case, I will take another look.

**Comment by CharliePoole** [comment]
@janno-p Are you using some sort of custom runner here?

The ProcessRunner is getting an exception thrown from the remote runner. We would need to see the stack trace from the agent itself to know why. The XML error occurs when the process runner tries to create a failure result for the assembly as a whole, incorporating the message and stack trace from the remote runner. It uses an extension method in XmlHelper to create the CDataSection. Looking at that code, I can see that it relies entirely on XmlDocument to correctly create the CDataSection. In other places, we have added special code to detect content that needs to be escaped before creating the CDataSection. We probably need to do that here.

@rprouse I don't think this is for 3.2. :-)

**Comment by rprouse** [comment]
@CharliePoole, he states that he is using the nunit3-console runner and the callstack makes it look like it is wrapped in a Fake build task. I am not holding up 3.2 for this, I just thought it would be an easy fix to slip in. As you stated, probably just an update to our escaping.

**Comment by CharliePoole** [comment]
Ah, Fake! I was thinking it was the name of some sort of test substitute he had created. :-)

**Comment by janno-p** [comment]
Finally I can provide some updates about the issue.

First thing, is that the first stack I provided is a bit misleading. Error complains about `]]>`, not `] ]>`. In a hurry I copied the stack-s from my build server log, and it seems that ccnet makes it's own escaping before producing output for web dashboard.

I'll try to narrow it down to specific tests.

**Comment by janno-p** [comment]
Did some detective work, and after cleaning up, here's the failing test example for you:

```csharp
[TestFixture]
public class StringAssertFailsWithCData
{
    [Test]
    public void Test()
    {
        StringAssert.Contains("xxx", @"<?xml version=""1.0"" encoding=""utf-8""?><SOAP-ENV:Envelope xmlns:SOAP-ENV=""http://schemas.xmlsoap.org/soap/envelope/""><SOAP-ENV:Body><SOAP-ENV:Fault><faultcode>Client.UnknownType</faultcode><faultstring><![CDATA[Unknown type `{http://producers.etoimik.xtee.riik.ee/producer/etoimik}test`.----- LOGI ID: 103667]]></faultstring><faultactor>Adapter.Etoimik</faultactor></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>");
    }
}
```

**Comment by janno-p** [comment]
On significant detail: it occurs in nunit3-console + nunit2 framework setup.

**Comment by ChrisMaddock** [comment]
Have reproduced this, running in the Nunit3 console with the test build against the NUnit 2.6.4 framework, as @janno-p stated. Can probably take a look later in the week, if nobody else gets there first!

**Comment by CharliePoole** [comment]
Didn't close automatically because comment was not in precise form "Fixes #nnn" or "Fix #nnn" as required by github.
