### ISSUE TITLE
CF Build Framework Test "TypeHelperTests.GetDisplayNameTests" Fails

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1321]
```
        [TestCase(typeof(C<List<char[]>, long>.D<IDictionary<int,byte[]>,string>), ExpectedResult = "TypeHelperTests+C<List<Char[]>,Int64>+D<IDictionary<Int32,Byte[]>,String>")]
```
This test fails running the CF 3.2 build in the emulator.

Strangely, it does not fail running the same test in an actual CF device.

```
  Expected string length 31 but was 37. Strings differ at index 18.
  Expected: "TypeHelperTests+C<String,Int64>"
  But was:  "TypeHelperTests+C<List<Char[]>,Int64>"
  -----------------------------^
```

**Comment by rprouse** [comment]
Which emulator? I ran on a 2003 SE emulator and all tests passed.

**Comment by oznetmaster** [comment]
I always test on the USA Windows Mobile 5.0 Pocket PC R2 Emulator.  That was what I thought that @CharliePoole had indicated that he used as well.

**Comment by CharliePoole** [comment]
Yes, I generally use the Mobile 5.0 emulator. I've also run the 2003 emulator in the past but haven't used it for a while. When I get a chance I'll run the tests as well.

**Comment by CharliePoole** [comment]
It's a strange-looking error for sure. A List of char arrays rather than a string? Weird.

**Comment by CharliePoole** [comment]
I'm not seeing this. I pulled down the latest changes and all tests pass on CF on that emulator.
