### ISSUE TITLE
Is there any way to make code being executed when all tests are finished?

### ISSUE THREAD

**Issue by Suremaker** [nunit/nunit#1322]
Hello,

I am working on a project that allows to create and execute BDD style tests.

One of the feature I want to implement is to generate a test execution report after test run.
In order to do it, I have to find out a way to execute a custom code when all NUnit tests are finished... and I want to implement it in seamless way from project users perspective.

To give more clarity on what I want to achieve is to:
* Create a project, lets say *NUnit3Integration*, that would contain the code executing after all tests, and it will contain the registration of it,
* Create a sample test project with NUnit tests, referencing NUnit3Integration project, that when executed, it would automatically execute code registered in NUnit3Integration after all tests finish.

So far I tried to look at:
* ITestAction and apply it on assembly level, but I noticed that I have to use it in all the assemblies which have tests - if I just apply it to *NUnit3Integration* assembly, it does not work,
* SetUpFixtureAttribute - same as above,
* IDriverFactory/NUnit3DriverFactory/NUnit3FrameworkDriver, but I have not managed to get working sample and I am not sure if it is possible to customise behaviour of NUnit3FrameworkDriver - it sounds like I would be able to just add a totally new one.

Is there any way to implement such behaviour seamlessly?

Best regards,
Wojtek

**Comment by CharliePoole** [comment]
If you are running tests, reporting on tests, etc. it seems like good design to have those activities separate from the tests themselves. Except for the driver, all the things you mention are actually part of your test code. Over the years, many folks have adapterd the features of the framework to do reporting, but I think that this approach is a violation of the single responsibility principle. A test's job is to test something. The job of reporting on what tests are run ought to be the responsibility of another component.

In the NUnit 3 architecture, that responsibility is in the engine. It decides how and where to run tests and creates a result when they are done. The FrameworkDriver is part of the engine, but it's responsibility is for the tests run using a particular framework in a specific domain. Each framework instance deals with tests in a single assembly and no more.

We have talked about providing an engine extension point to handle various events in the execution of a set of tests. That would be the best way to go in my view, but the extension points don't yet exist.

A workaround at this point could be to implement a ResultWriter extension. It would be called with the complete result of all the tests in our standard XML format and you could create a file containing the report. Your report would only be produced if requested on the command-line, which may be seen as a feature or a problem, depending on how you look at it.

**Comment by CharliePoole** [comment]
See issue #1302. I'm closing this as an answered question, but feel free to ask for more info if you need it.
