### ISSUE TITLE
Remove CollectionContainsConstraint

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1324]
See the note at the bottom of [this page](https://github.com/nunit/docs/wiki/CollectionContainsConstraint).

We could do away with the constraint and have all the syntactic elements generate a SomeItemsConstraint. It would remove one small class and a test class from our codebase.

OTOH, if there are people who actually construct the constraint, it would break their code. There can be other things like this under Constraints, so let's decide on whether to keep such code or remove it.

**Comment by rprouse** [comment]
Would the plan be to use SomeItemsConstraint in Has.Member(), Contains.Item() and Does.Contain() instead?

I doubt many people use our constraints directly. Even then, should we deprecate for one release?

**Comment by CharliePoole** [comment]
Even simpler: `return Has.Some.EqualTo(expected)`

I think there's a benefit to eliminating any unneeded constraints, since I often find my self searching through and comparing those that work in a similar way. It's a time sink.

The trick would be to deprecate the constructor of the constraint while avoiding deprecating Has.Member(), etc. Perhaps by adding an internal static factory method for use by the syntax elements. Or we could just not worry about it and remove. :-)

**Comment by CharliePoole** [comment]
@rprouse We already discussed this. Shall we move it to Backlog at a low priority?

**Comment by rprouse** [comment]
I say just not worry and remove.
