### ISSUE TITLE
Unable to build without Compact Framework

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#1329]
Have just updated my repository, and no longer appear to be able to run the build script without the compact framework installed. (As a result of #1305, I presume)

```
nunit\src\NUnitFramework\framework\nunit.framework-netcf-3.5.csproj(463,11): 
error MSB4019: The imported project "C:\Windows\Microsoft.NET\Framework\v3.5\Microsoft.CompactFramework.CSharp.targets" was not found. 
Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
An error occured when executing task 'BuildAllFrameworks'.
```

I have no prior knowledge of CF, but it doesn't seem to be a simple matter of installing the relevant framework - is there, or should there be a built-in option to ignore the CF build? 

My only reason to build is to run the tests before submitting a PR, so being able to exclude CF allow me to check the majority, and then the CI would catch CF issues afterwards.

**Comment by CharliePoole** [comment]
It could be #1305 or #1328, which was just merged.

Originally, @dicko2 had CF as a separate command, but I asked him to make it as part of the AllFrameworks target when on Windows. The build does work on AppVeyor, where we go ahead and install everything that's needed. We might not want to do that on user machines, however.

@rprouse What do you think is the right way for this to work?

**Comment by CharliePoole** [comment]
I should have asked: How do you run the script, precisely?

**Comment by CharliePoole** [comment]
OK... Here's the scoop... On AppVeyor, appveyor.yml runs a bootstrap program in appveyor-tool.ps1, which installs the necessary CF components.

I think this is a critical problem, since it impacts all our contributors, but we should pause a beat and figure out how we actually __want__ it to work before doing anything. Do we want to install CF components on the machine of every developer who runs the build script?

**Comment by ChrisMaddock** [comment]
I normally run 'build -t TestAll'. (Although this fails on the build task i.e. just running 'build') I run on Windows.

I'd personally be in favour of all relevant components being installed by default - I imagine seeing different test results locally to those on a PR could be frustrating.

**Comment by CharliePoole** [comment]
The alternative is detecting the presence of the CF components and only building if they are present. Come to think of it, we probably want to do that before installing anyway. At the moment, I'm not sure how to do that.

**Comment by dicko2** [comment]
Could just check for the presence of the CF framework files in the cake script. Or only run the CF build if using the appveyor target might be better. just adding an if for now maybe.

@ChrisMaddock short term to get it running run the build script with -target appveyor and it'll install the CF on your machine, if you want to go down that road.

I've got a little free time now, i'll have a crack at a solution

**Comment by ChrisMaddock** [comment]
Great, thanks @dicko2. I'd instead deleted the CF chunks of the script - didn't see there was an option to install the CF required components. Cheers!

**Comment by ChrisMaddock** [comment]
All sorted - thanks @dicko2!
