### ISSUE TITLE
Add Assert.Zero and Assert.NotZero

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1334]
I have been asked by a number of my users if these two forms of Assert could be added to compliment the addition of the Is.Zero and Is.Not.Zero constraints (#1246 and #1248).

It seems reasonable given that we have Assert.Null and Assert.NotNull.

Easy to do, but does this violate some philosophical issue?

**Comment by CharliePoole** [comment]
Well, only that we have not been updating the collection of what we call legacy asserts (aka classical) for a long time. We actually discussed removing them entirely, but decided that we should keep them for compatibility reasons. I'm don't feel strongly, however. @rprouse,  what do you think?

**Comment by oznetmaster** [comment]
Probably should be a separate issue, but there appears to be no documentation for the Zero constraint?

**Comment by ChrisMaddock** [comment]
It's documented under the Equal Constraint. Perhaps sensible, unless you are explicitly looking for it?

https://github.com/nunit/docs/wiki/EqualConstraint

**Comment by oznetmaster** [comment]
I think it should be in the alphabetical list of constraints.

**Comment by rprouse** [comment]
We haven't been adding to the classic constraints and I don't use them anymore, but I have been looking at quite a few projects in the wild lately and my feeling is the majority of users are still writing classic asserts. I can sort of see why, they are shorter to write and you get intellisense earlier.

So, I am ok with adding limited and clear new methods, as long as it doesn't become a slippery slope where we support every combination of the constraint syntax :smile:

**Comment by CharliePoole** [comment]
We didn't create a new constraint, so we can't document one. :-)

Maybe there should be a list of syntactic elements with links to the
constraints they create.

**Comment by CharliePoole** [comment]
I think it depends on the size of the list. I would start with a single page, since it elminates one click.I created an issue in docs for this.

I'm OK with Assert.Zero and Assert.NotZero as well. Shall we add it to the backlog?

**Comment by rprouse** [comment]
Labeled and added to backlog

**Comment by oznetmaster** [comment]
I agree with @rprouse observation that "the majority of users are still writing classic asserts".  And for exactly the reasons he indicated, shorter, and intellisense.  I am also told that most find them more readable.

Has any consideration ever been given to making the classic asserts first class citizens again, and adding to them whenever it seems appropriate (like in the case of zero)?

**Comment by CharliePoole** [comment]
I don't think we want to go back to adding new implementation code in the Assert class as we used to. There should always be a Constraint that actually implements the predicate in question.

I also don't think we should normally add equivalents of new constraint-based syntax. Considering individual cases seems like the right approach.

**Comment by CharliePoole** [comment]
I notice we didn't add Positive or Negative to Assert. Will it seem odd to have Zero and NonZero without adding four more for those? If so, this may be a slippery slope, leading to our having to maintain a double system.

**Comment by oznetmaster** [comment]
If the majority of NUnit users are still using the classic assertions, as @rprouse indicates, perhaps the decision concerning classic asserts needs to be revisited?  There are obviously substantial reasons why classic assertions are seemingly still the most used.

**Comment by CharliePoole** [comment]
I guess you would have to define  what you mean by reconsidering or revisiting.

To put it in a bit of perspective, we backed away from the classic asserts when we introduced the fluent syntax in 2007. The decision was to stop developing them, continue to support them for a while and eventually remove them. Most of them were removed from the separate build of NUnitLite at that time.

Periodically over the past nine years, we have considered deprecating them as a first step to removal. Each time we have found they still had a lot of use and users told us to keep them. So we kept them. In the early development of 3.0, dumbed down the classic assert set to only include what was in NUnitLite. There was user pushback and I replaced them, commiting to retain them indefinitely.

During the same time period, there has been no significant pushback from users regarding our not adding new features to the classic assert syntax. It has generally been accepted that you need to use the new syntax to get certain new features.

With all that in mind, if we revisit this, what would that mean as far as code goes?

**Comment by CharliePoole** [comment]
BTW, my own perception is that the reason most users are using classic asserts is that we have had an __enormous__ influx of new users over the same time period. Those users came to us from MsTest and - to a lesser extent - MbUnit. Consequently, they use the syntax they are familiar with.

Back when the fluent syntax was introduced, it seemed like a bad idea to me. I was forced to it by user pressure and the majority of the users who were talking to me appeared to be converting to it. 

I see the same phenomenon now on SO, where more experienced users direct newcomers to the new syntax when they need it.

Obviously, this is merely my own observation and can only be based on who talks to us. :-)

**Comment by jplebre** [comment]
Maybe the documents could be made really obscure for the old assert style? :)
I remember when nunit 3 came out that everyone in my circle was saying "this is it, time to move to the fluent styles"

Also, the majority of projects I work which are a few years old are using nunit and then libraries like "Shouldly" (which I absolutely dislike, but that's another topic). My point being that in my circle seems like fluent-ish syntax is a + 

Is this a go for implementing?

**Comment by CharliePoole** [comment]
Definitely. Are you interested in working on it?

**Comment by jplebre** [comment]
Yeah sure I'll give this a go, good way to look into both libraries
