### ISSUE TITLE
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

### ISSUE THREAD

**Issue by evans1dd** [nunit/nunit#1335]
Had everything working at one time.  Ran test yesterday and got the attached error.  Reinstalled NUnit 3 through Visual Studio 2015.  Nothing changed.  Installed from img file.  Nothing changed.

I do have ReSharper installed.

Here is my sample test method:

        private TransactionScope scope;

        [SetUp]
        public void TestStart() {
            scope = new TransactionScope(TransactionScopeOption.RequiresNew);
            ResetForSetup();
            //dataRollbackContext = TransactionControlBlock.Get();
        }

        [TearDown]
        public void TestEnd() {
            if (scope != null) {
                scope.Dispose();
            }
            //dataRollbackContext.Rollback();
        }

        [Test]
        public void TestMethod1() {
        }

I tried your sample code and that won't even compile.
Your sample code is looking for nunit.core which does not exist.
My code does not reference nunit.core.  But it never did.

![capture](https://cloud.githubusercontent.com/assets/17768029/13676738/f72b5ad2-e6b4-11e5-9a77-90377ea5560f.PNG)

**Comment by CharliePoole** [comment]
Please explain what sample code you are talking about. FYI nunit.core is an internal component of nunit v2.

**Comment by evans1dd** [comment]
[cid:image001.png@01D17AC6.D63B5160]

**Comment by rprouse** [comment]
@evans1dd also, can you answer a few questions?

1. How are you running your tests when you get that error? The callstack looks like Resharper. If so, what version?
2. Are you saying that the sample code in this issue won't compile?
3. What version of NUnit is your test assembly referencing, 2.6.x or 3.x?
4. How do you reference NUnit? Do you use NuGet for that?

**Comment by evans1dd** [comment]
I took a screen shot (copy paste) and sent it to you.  Don’t know why it got changed to that garbage.

Anyway,  I’ve downloaded from:

https://dist.nuget.org/index.html    (nugget.exe – latest (v3.3.0), VS 2015 VSIX – latest (v3.3.0))
And I downloaded and installed NUnit.3.2.0.img from your site.

I can’t tell you specifically which one of those installed the sample programs.  I simply hit the start button on Windows 10 and type nunit and they showed up.  So I selected the one for C# and it loaded VS with the solution.  I wanted to use that to see if the problem was in my solution or something else.  I assumed everything would work with your samples unless there was something specifically wrong with my installation.

I don’t think I mentioned that I’m using VS 2015.  Sorry about that.

**Comment by evans1dd** [comment]
We are using ReSharper version 10.0.2.  I noticed in my search for a fix that ReSharper was mentioned so I put that in my original post.  Figured too much information was better than too little.

To run a test, I have tried several different scenarios:

-          Normally, I would simply go to the code and select the green/yellow icon next to the test method because I’m creating that one specific test.

-          I would try the icon to run all tests in a class

-          I have tried right-clicking on the class my NUnit project

-          When I read someplace about ReSharper, I tried to run all tests through ReSharper

All scenarios gave me the same results.

At one time I did notice a message scroll by about not being able to find any tests.  That seamed strange since I do have the icons for them.

Yes, I am saying that the sample code won’t compile.  I tried both the VB and C# ones.  I get 189 Errors.  Things from Win32Dialogs.SecurityAlertDialog.Handle(): no suitable method found to override to The name ‘DialogButton’ does not exist in the current context.  The only reference that fails is nunit.core.  This is how I knew nunit.core exists.

Nunit.framework is version 3.2.0.0
                                Runtime Version v4.0.30319
                                Path: C:\Program Files (x86)\NUnit.org\framework\3.2.0.0\portable\nunit.framework.dll

(I hope “portable” does not mean that it’s made for a phone app.)

Our main application is a web application.
All projects, including the NUnit test project use .NET Framework 4.6

(Hope that’s a clue)

**Comment by rprouse** [comment]
I am not sure where those samples came from. As far as I know, we do not ship sample code in any of our packages. Our samples are GitHub repositories that we don't ship. We also have NUnit Templates as a Visual Studio Extension, but you wouldn't find those under the Win10 start button, but from File | New Project in Visual Studio.

To test a simple project, just create a new test project, add NUnit 3 from the NuGet package manager and add the test code from this issue above fixed up with proper references.

I would also try running your tests using the nunit3-console.exe that you installed. You will find it in `C:\Program Files (x86)\NUnit.org\nunit-console`. If they run there, then it is likely a Resharper bug.

**Comment by rprouse** [comment]
>Nunit.framework is version 3.2.0.0
                                Runtime Version v4.0.30319
                                Path: C:\Program Files > (x86)\NUnit.org\framework\3.2.0.0\portable\nunit.framework.dll

Try switching your reference to point to `C:\Program Files > (x86)\NUnit.org\framework\3.2.0.0\net-45\nunit.framework.dll`, I don't think Resharper can run portable tests. NUnit console can't either, you need to create self-executing tests for that.

**Comment by evans1dd** [comment]
YEAH !!!!  THAT FIXED IT!!!!

I have no idea how the reference got screwed up.  Really appreciate this!!!!!!

Dave.

**Comment by rprouse** [comment]
Glad you got it working. I am closing this issue.
