### ISSUE TITLE
BUILDING.txt is outdated

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#1338]
Following on from #1332, would someone with a more comprehensive knowledge mind updating BUILDING.txt?

From my point of view, I'm interested the definitive way to run all tests. I currently run `build -t TestAll`. From what I gather, if I run `appveyor-tool.ps1` - this will install the dependencies that allow me to also build/run CF tests? 

Would be good to also document other required dependencies - the first time I pulled, I manually installed the Silverlight SDK to keep VS happy - was this a necessary step, or does the build script take care of this?

**Comment by CharliePoole** [comment]
I still have some outstanding changes to merge into the script, but I'll update the file to the current release and push the change and then do another update as changes are made. I think I'll put a comment into the build script reminding folks to edit BUILDING.txt.

**Comment by CharliePoole** [comment]
Regarding Silverlight, I think we should deal with it in the same way as we are handling CF - skip if not installed and give a warning. It's a bad idea for our scripts to change the user environment by installing stuff. We can and should tell them what they need to install in this file, however.
