### ISSUE TITLE
Unable to run tests for Universal Class Library

### ISSUE THREAD

**Issue by godrose** [nunit/nunit#1342]
Running tests for Universal Class Library results in inconclusive status.
System: 
Windows 10 64 bit
Resharper 10.0.0
VS 2015
NUnit 3.2.0

Error message:
![image](https://cloud.githubusercontent.com/assets/7791651/13721907/36d36f92-e83d-11e5-9a48-0f0720870470.png)

**Comment by rprouse** [comment]
Neither Resharper, NUnit VS Adapter or even NUnit Console can run UWP tests yet. To get the tests running, you need to make your tests self executing using NUnitLite. I have instructions for [running NUnit tests for .NET Core](http://www.alteridem.net/2015/11/04/testing-net-core-using-nunit-3/) which is similar. Give them a try.

I am going to close this issue, but feel free to comment here or on the blog post I linked to and I will help you out if you run into any problems. I am hoping to have full runner support for UWP in 3.4 by summer, but no guarantees :smile:

**Comment by godrose** [comment]
Thanks for the reply.
What is the relevant project type in the case of the UWP? Is it 'Unit Test App' ?
There's no Console Application in UWP... @rprouse

**Comment by godrose** [comment]
Tried the described approach with a 'Blank Universal App' by putting the `AutoRun` code inside the `App.xaml.cs`. Threw an exception.

**Comment by rprouse** [comment]
Sorry, I didn't think of that. I don't do any UWP development at the moment so forgot that there isn't a console app. Can you add a .NET Core console app and use that? They are both corefx, do they play nicely together?

Another option, although not as good is to use the [Xamarin runner](http://www.alteridem.net/2015/12/21/testing-xamarin-projects-using-nunit-3/). I know it works with UWP, but it is a graphical runner. I am pretty sure that UWP with Xamarin doesn't require a license.
