### ISSUE TITLE
Running nunit 3 with Jenkins

### ISSUE THREAD

**Issue by sbhanderi** [nunit/nunit#1350]
I was wondering if there is a native reader of the generated xml file.
So
"c:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe" --x86 -verbose --labels=All --timeout=300000 --trace=Verbose Genesyslab.Lync.Test.dll --testlist=%testlist% --result=%WORKSPACE%\nunit-result-%testGroup%.xml;format=nunit2

This will create an xml file with the results.
If I change the option file option to format=nunit3
Jenkins cannot read the xml file. Due to extra bits within it.

Is there an update to NUnit test result report plugin fot Jenkins yet ?

**Comment by dicko2** [comment]
I noticed the same thing with TFS (VSTS) and TeamBuild. Any word from the powers that be on support for v3 format guys?

**Comment by sbhanderi** [comment]
It looks like the Jenkins team are aware of this issue.
See
https://issues.jenkins-ci.org/browse/JENKINS-33493?jql=project%20%3D%20JENKINS%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20component%20%3D%20%27nunit-plugin%27
So probably can close this here, and wait for resolution within the nunit plugin.
