### ISSUE TITLE
Make PlatformAttribute available in Portable build

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1353]
Currently, we don't define PlatformAttribute in the portable build because the information needed to determine the platform is not available. That means whenever you use the attribute in a multi-platform test - like NUnit's own - you need to surround it with an #if / #endif. That's a pain!

Options:
1. A do-nothing PlatformAttribute. Might be confusing, since it wouldn't do what it appeared to do.

2.Reject all platforms under which the Portable build doesn't work and accept all those for which it does work. Similarly confusing.
1. Actually make it work correctly. We would only need to test for platforms for which we provide the portable build, which simplifies things slightly. For example, you will never be on CF when you are running with the Portable build of the framework. Actually detecting the platform will require some sort of interface implemented for each platform we support.

Clearly, if we can do it, option 3 is to be preferred.

**Comment by CharliePoole** [comment]
@rprouse  I propose closing this since we will be eliminating portable.

**Comment by ChrisMaddock** [comment]
Closing, as we no longer have portable, and a .NET Standard implementation is tracked here: https://github.com/nunit/nunit/issues/2432
