### ISSUE TITLE
Unable to run test with FsUnit: UnsupportedFrameworkException: unsupported version of the nunit.framework 3.2.0

### ISSUE THREAD

**Issue by palutz** [nunit/nunit#1356]
Hi guys,
trying to run some test in a new little F# project using FsUnit.
Running on both Ubuntu (MonoDevelop) and Mac (Xamarin Studio) but getting always the exception on the title.
It's a 4.5 Mono/.Net project.
Any idea why?

Thanks,
Stefano

**Comment by rprouse** [comment]
It looks like FsUnit is not using the NUnit engine correctly and is therefore not reporting the reason the framework is unsupported. Is your test library a PCL, or does it reference the PCL version of the NUnit framework? If so, the NUnit engine does not support running PCL tests yet. They must be run by creating a self-executing test runner using NUnitLite. I don't think that is possible with FsUnit?

Can your tests target .NET 4.5? That should fix it.

**Comment by palutz** [comment]
Hi,
I've got the same message both with a Nunit test project inside Xamarin Studio and with a "simple" library project.
This is the packages.config

`<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="FSharp.Core" version="4.0.0.1" targetFramework="net45" />
  <package id="FsUnit" version="2.1.0" targetFramework="net45" />
  <package id="NUnit" version="3.2.0" targetFramework="net45" />
</packages>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="4.4.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>`

**Comment by rprouse** [comment]
We have seen issues where you need to reference and use the NUnit Framework somewhere in your tests otherwise we cannot determine the test framework you are using. Just an attribute is good enough. Can you give that a try and report back?

**Comment by rprouse** [comment]
I am closing since we have not heard back from you. If you have more information, add it to this issue and we will reopen.
