### ISSUE TITLE
Compilation error in NUnitPortableDriverTests.cs: 

### ISSUE THREAD

**Issue by corsairmarks** [nunit/nunit#1359]
I discovered a compilation error in `master`.  It appears that it was assumed `System.Xml.Linq.XContainer.Elements(System.Xml.Linq.XName)` returned a type with a `Count` property.  However, because it is a `System.Collections.Generic.IEnumerable<T>` it instead has access to the `System.Linq.Count<TSource>(this IEnumerable<TSource>)` extension.  Because the property was expected to be an `int` and instead is a method group, that caused ambiguity with `Assert.That`.  It is possible I am failing to build correctly, but I followed the instructions in BUILDING.md and the [documentation](https://github.com/nunit/dev/wiki/Packaging-NUnit-3.0).

From the compiler:

```
NUnitPortableDriverTests.cs(77,13): error CS0121: The call is ambiguous between the following methods or properties: 'NUnit.Framework.Assert.That<int>(NUnit.Framework.Constraints.ActualValueDelegate<int>, NUnit.Framework.Constraints.IResolveConstraint, string, params object[])' and 'NUnit.Framework.Assert.That(NUnit.Framework.TestDelegate, NUnit.Framework.Constraints.IResolveConstraint, string, params string[])' [C:\Source\git\nunit\src\NUnitEngine\Portable\nunit.portable.agent.tests\nunit.portable.agent.tests.csproj]
NUnitPortableDriverTests.cs(92,13): error CS0121: The call is ambiguous between the following methods or properties: 'NUnit.Framework.Assert.That<int>(NUnit.Framework.Constraints.ActualValueDelegate<int>, NUnit.Framework.Constraints.IResolveConstraint, string, params object[])' and 'NUnit.Framework.Assert.That(NUnit.Framework.TestDelegate, NUnit.Framework.Constraints.IResolveConstraint, string, params string[])' [C:\Source\git\nunit\src\NUnitEngine\Portable\nunit.portable.agent.tests\nunit.portable.agent.tests.csproj]
NUnitPortableDriverTests.cs(141,13): error CS0121: The call is ambiguous between the following methods or properties: 'NUnit.Framework.Assert.That<int>(NUnit.Framework.Constraints.ActualValueDelegate<int>, NUnit.Framework.Constraints.IResolveConstraint, string, params object[])' and 'NUnit.Framework.Assert.That(NUnit.Framework.TestDelegate, NUnit.Framework.Constraints.IResolveConstraint, string, params string[])' [C:\Source\git\nunit\src\NUnitEngine\Portable\nunit.portable.agent.tests\nunit.portable.agent.tests.csproj]
```

Code in question:

```csharp
Assert.That(result.Elements("test-suite").Count, Is.EqualTo(0), "Load result should not have child tests");
```

Fixed:

```csharp
Assert.That(result.Elements("test-suite").Count(), Is.EqualTo(0), "Load result should not have child tests");
```

**Comment by CharliePoole** [comment]
@rprouse We are still not running the portable driver tests in CI.

**Comment by rprouse** [comment]
@CharliePoole the portable driver is under the TestDriver task which is a dependency of Test and TestAll. That means they are running in AppVeyor doesn't it?

@corsairmarks I merged your pull request, but I want to understand why it isn't compiling for you, but it is for me. Are you getting that build failure compiling on the command line, or in Visual Studio? Are you using VS 2015? If command line, what versions of VS or Mono are in your path?

**Comment by CharliePoole** [comment]
@rprouse It runs but just displays help. Apparently something wrong in the command-line. I didn't want to get into it as I'm not clear how the test works so I sent you a note a while back.

**Comment by corsairmarks** [comment]
@rprouse I'm happy to provide details.

In both cases, I started with a clean repository at nunit@4387d66978b1b706f62a0887352c9078c006c711 (the same commit my recent PRs were based on)

Build on the command line (using PowerShell): `.\build.cmd` while in the `~/nunit/` directory - Fails with the messages as provided

Built with Visual Studio 2013 Update 5 (Professional): Open the `nunit.sln` file, press `ctrl` `shift` `b` (Build > Build Solution) - Fails with the same message

My %PATH%: `C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Perforce\DVCS\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\TortoiseHg\;C:\Users\Durandal\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files (x86)\GitExtensions\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\NUnit.org\nunit-console`

**Comment by corsairmarks** [comment]
One additional quirk: I run my account as user-mode, not administrator.

I am using Windows 10 Professional with all current updates installed.
