### ISSUE TITLE
Setting with a null value

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1373]
I happened to add a setting to runSettings that had a valid value of null.

Everything worked correctly until the results were written.  

FrameworkController.AddSetting throws an exception if the value of a setting is null.

This may be unique to my use of runSettings, but I still think that AddSetting should not crash on a null setting value?

**Comment by rprouse** [comment]
Can you provide a repro for this? I am going to mark it as a bug and put it in the backlog, but an easy repro would help newer developers fix this.

**Comment by OmicronPersei** [comment]
Closed by merge #2493 .
