### ISSUE TITLE
Add a command line option to specify the default ordering for tests

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1374]
Previously, the default ordering for tests just happened to be alphabetical, even though that ordering was never specified or guaranteed.

It would be useful to be able to specify a precise ordering for the tests if desired.

I suggest a command line option --order with possible values of "alphabetical", "specified" (the order the tests are listed on the command line), "occurrence" (the order the tests occur in the test assembly), and perhaps others.

**Comment by rprouse** [comment]
Thanks for the idea, but this isn't in keeping with our vision of where we want to take NUnit, so I am closing.
