### ISSUE TITLE
NUnit Should Use DebuggerDisplay When ToString() is Not Available

### ISSUE THREAD

**Issue by lundmikkel** [nunit/nunit#1376]
It happens that I use `System.Diagnostics.DebuggerDisplay` instead of `ToString()` to get a nice output when I debug:
```C#
namespace NUnit3TestLibrary
{
    [System.Diagnostics.DebuggerDisplay("This string is not used by NUnit even if ToString() is not available")]
    public class DebugClass
    {
        //public override string ToString() => "This string is used by NUnit if present";
    }
}
```
Before C# 6.0 that often made more sense, as you could nicely inline variables in the string. The problem, however, is that the `DebuggerDisplay` is ignored when testing with NUnit:
```
Expected: <NUnit3TestLibrary.DebugClass>
But was:  <NUnit3TestLibrary.DebugClass>
```
NUnit should use `ToString()` when available, but otherwise try to use the `DebuggerDisplay` message when that is available instead.

(See also [NUnit Discuss](https://groups.google.com/forum/#!topic/nunit-discuss/dPLEWuC8ahE))

**Comment by CharliePoole** [comment]
Of course To String is always there. We would have to reflect on each Type to see if it has been overridden.

**Comment by lundmikkel** [comment]
That is very true. I see how that would generate unnecessary overhead most of the time. A global/local setting could however ensure the overhead is only there, when we need it.

**Comment by rprouse** [comment]
I am going to mark this as an idea and that it requires further design. I like the idea in principle, but agree with @CharliePoole that the overhead may make the feature not worth it.

**Comment by rprouse** [comment]
Thanks for the idea, but this isn't in keeping with our vision of where we want to take NUnit, so I am closing.
