### ISSUE TITLE
Console returns 0 for invalid fixtures

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#1379]
Separated out from #1346, if the console encounters invalid test suites, it still returns zero. Invalid assemblies and invalid tests contribute to the return code, but not invalid test suites.

Should we add an additional return code for this? -3 FIXTURE_NOT_FOUND currently appears to be unused - what was the intention of that, for invalid filtering?

```
public static readonly int OK = 0;
public static readonly int INVALID_ARG = -1;
public static readonly int INVALID_ASSEMBLY = -2;
public static readonly int FIXTURE_NOT_FOUND = -3;
public static readonly int UNEXPECTED_ERROR = -100;
```

**Comment by CharliePoole** [comment]
As mentioned on the other issue, I thought we had fixed this. Looking at the code in ConsoleRunner, it appears not.

FIXTURE_NOT_FOUND was an error we gave when the obsolete /fixture option was used and no such fixture was found. We no longer give an error when no tests are found but perhaps we should, changing the name of course.

In principle, if a fixture is bad, we should return the number of tests that would have been run. However, depending on the nature of the error, we may not know what that number is. Simply counting fixture failures as well as test cases would work for some purposes but it  sounds a bit sloppy. So I would say we need an extra negative code for this. 

A crazy alternative I just thought of: count every bad fixture as 1000 errors. A result like 1002 would mean 1 bad fixture and 2 failing test cases. It breaks down for over 999 failures, but so what? Drawback - which is probably why it's crazy - is that every CI runner might need to interpret it.

**Comment by CharliePoole** [comment]
@ChrisMaddock Educational note! :-) I marked it as a bug, because it seems like one to me... good enough reason. I did __not__ mark it as requiring confirmation (status:confirm) because I was able to verify that's what the code does by a quick glance. I assigned it to Backlog, 'cause that's what we do.

Hope this helps.

**Comment by ChrisMaddock** [comment]
@CharliePoole Is there any advantage to using  p

**Comment by CharliePoole** [comment]
IIRC we have code to only count errors that originated in the fixture. However, I agree with you about adding a new negative code.
