### ISSUE TITLE
Use array argument contents in name of parameterized tests rather than just array type.

### ISSUE THREAD

**Issue by yaakov-h** [nunit/nunit#1382]
TestCase and TestCaseSource make it too easy to create tests with duplicate names.

Case 1: Arrays

Arrays are not formatted further, only their type name becomes part of the test name by default. For example, given the following test fixture:

```
using NUnit.Framework;

namespace NUnitDuplicateTests
{
    public class DuplicateTestFixture
    {
        [TestCase((object)new[] { "John", "Smith" })]
        [TestCase((object)new[] { "Emperor", "Palpatine" })]
        [TestCase((object)new[] { "Groot" })]
        public void EverybodyHasAtLeastTwoNames(string[] nameParts)
        {
            Assert.That(nameParts, Has.Length.GreaterThanOrEqualTo(2));
        }
    }
}
```

Only one test is discovered: `NUnitDuplicateTests.DuplicateTestFixture.EverybodyHasAtLeastTwoNames(System.String[])`.

Only one test shows up in the Visual Studio test explorer.

Only one unique test shows up with `nunit3-console --explore`, but is printed 3 times.

This creates issues for applications that use the Explore API, if they wish to track each test individually for various purposes.

I would expect the test name to be something along the lines of `NUnitDuplicateTests.DuplicateTestFixture.EverybodyHasAtLeastTwoNames(["Emperor", "Palpatine"])`.

Case 2: Test Names

I would logically expect a test name from TestCaseAttribute or TestCaseData to be local to the method that declares the test. It is often convenient to use the same test data for multiple test methods, e.g.

```
using System.Collections;
using NUnit.Framework;

namespace NUnitDuplicateTests
{
    public class DuplicateTestFixture
    {
        [TestCaseSource(nameof(Names))]
        public void EverybodyHasAtLeastTwoNames(string[] nameParts)
        {
            Assert.That(nameParts, Has.Length.GreaterThanOrEqualTo(2));
        }

        [TestCaseSource(nameof(Names))]
        public void EverybodyIsOnTheImperialPayroll(string[] nameParts)
        {
            // TODO: Talk to the Payroll division on Coruscant.
        }

        public static IEnumerable Names
        {
            get
            {
                yield return new TestCaseData(new[] { "Emperor", "Palpatine" }).SetName("Our grand Emperor");
                yield return new TestCaseData(new[] { "Darth", "Vader" }).SetName("Luke's Dad");
            }
        }
    }
}
```

Although this fixture declares four tests, there are only two unique test names - `NUnitDuplicateTests.DuplicateTestFixture.Our grand Emperor` and `NUnitDuplicateTests.DuplicateTestFixture.Luke's Dad`.

I would expect there to be four, somewhat resembling the following:
1. `NUnitDuplicateTests.DuplicateTestFixture.EverybodyHasAtLeastTwoNames."Our grand Emperor"`
2. `NUnitDuplicateTests.DuplicateTestFixture.EverybodyHasAtLeastTwoNames."Luke's Dad"`
3. `NUnitDuplicateTests.DuplicateTestFixture.EverybodyIsOnTheImperialPayroll."Our grand Emperor"`
4. `NUnitDuplicateTests.DuplicateTestFixture.EverybodyIsOnTheImperialPayroll."Luke's Dad"`

Case 3: String truncation

String parameters are truncated to 40 characters, which makes it difficult to use long strings (such as URLs) in test cases. e.g.:

```
using NUnit.Framework;

namespace NUnitDuplicateTests
{
    public class DuplicateTestFixture
    {
        [TestCase("The Imperial Death Star is a collossal waste of money. The Empire could better use those funds on supplies and soldiers.")]
        [TestCase("The Imperial Death Star is a collossal monument to the power of the Empire.")]
        public void AllOpinionsAreValid(string opinion)
        {
            Assert.That(opinion, Is.Not.Null, "Not having an opinion is not in itself an opinion.");
        }
    }
}
```

This fixture only has one unique test name, `NUnitDuplicateTests.DuplicateTestFixture.AllOpinionsAreValid("The Imperial Death Star is a collossa...")`.

From this, I see three resolutions:
1. Can test names be made smarter by introspecting arrays?
2. Can explicit test names be made local to their method, not local to their fixture?
3. Can strings be not truncated, or the truncation limit be increased well beyond 40 characters?

**Comment by yaakov-h** [comment]
For the record, I have managed to solve all 3 in my own project by subclassing `TestCaseAttribute` and `TestCaseSourceAttribute`, but:

1. This requires that I create my own implementation of every test case builder shipped with nunit.framework. I haven't rebuilt `ValueSourceAttribute`, for example.
2. This unfortunately requires either complete duplication of the NUnit attribute classes, or subclassing and using reflection to access the internal field `TestMethod.params`. I haven't found another way to do this.

Is this something that NUnit itself can handle?

**Comment by CharliePoole** [comment]
It's fairly well-known that NUnit neither requires nor creates unique test names. As a user, you can set the name of every testcase to "MyTest" and NUnit will happily run them. Of course, this raises the problem that the test then becomes very difficult to identify in the output.

You propose three improvements:

1. "Introspecting arrays" By this do you mean that the array should be represented by listing it's contents?

2. "Explicit test names made local to their methods" By specifying template arguments in the name, this is already possible, e.g.: "{m}_Some_Suffix"

3. "Strings not truncated" "{m}{a}" or "limit increased" "{m}{a:100}

So of the three - and assuming I understand what you are suggesting - the first is a possible change, while the other three are already available.

**Comment by yaakov-h** [comment]
1. Yes
2, 3.: Wait, what? Where is this documented? I haven't heard of this feature before.

**Comment by yaakov-h** [comment]
Looks like `{m}{a}` is still truncated, but `{m}{a:100}` does increase the truncation limit.

**Comment by CharliePoole** [comment]
The specification we worked from is here: https://github.com/nunit/dev/wiki/Generation-of-Test-Names

It should have been transfered to the documentation wiki! I'll make a note of that.

I'll have to look more closely at the code to see what {a} is supposed to do - I was referring to it from memory.

**Comment by yaakov-h** [comment]
> Note that in this usage, it will generally only make sense to use `{m}`, `{a}` or `{o}` specifiers. However, NUnit will use whatever is provided.

`{o}` isn't mentioned anywhere else on that page - do you recall what this one does?

**Comment by CharliePoole** [comment]
I think it's an older planned format, replaced by {0} through {9}

I don't think all of this is implemented. I'll have to figure that out when I copy some of it to the docs. Code is at https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/TestNameGenerator.cs

**Comment by rprouse** [comment]
@CharliePoole should we mark this as a documentation issue, or is there any coding we should consider for this?

**Comment by CharliePoole** [comment]
I created nunit/docs#38 for updating the docs. The issue of uniqueness may require more work but it's actually covered in several existing issues.

**Comment by rprouse** [comment]
I am going to close then.

**Comment by yaakov-h** [comment]
What about array introspection (1)?

**Comment by CharliePoole** [comment]
By that do you mean the use of the content of an array in it's representation as an argument?

I think we have that as an issue somewhere, but I'm unable to find it!

**Comment by yaakov-h** [comment]
Yep. Is it worth creating/duplicating then?

**Comment by CharliePoole** [comment]
I searched and still can't find it. This issue has the best description, as case 1 above, so I'm re-opening and re-titling it appropriately.

**Comment by kuskmen** [comment]
Hey guys, do you plan implementing this array introspection?

Thanks,
kuskmen

**Comment by CharliePoole** [comment]
Best guess answer: Low priority features are usually not implemented unless one of the team gets excited about doing it. Contributions are accepted but a change in how we name tests would be a moderately advanced bit of work and so might require somebody familiar with the internals to work with the contributor.

Other way to go: start a discussion and get the priority raised. 😸

**Comment by yaakov-h** [comment]
I already have the code for that in a custom test attribute. I might see if I can figure out how to upstream it.

**Comment by CharliePoole** [comment]
@yaakov-h That would be appreciated!

**Comment by yaakov-h** [comment]
Turns out if I put it in NUnit framework itself, I only have to do it in one place, not four. 😄

**Comment by CharliePoole** [comment]
Let's document and discuss the format. Based on your code, I think we are saying...

1. Array arguments are represented by square brackets containing the array contents.

2. Contents are represented as nunit would represent them if they were bare arguments.

3. If an array contains another array, square brackets may be nested.

4. Multidimensional arrays NEED TO BE SPECIFIED.

5. Other types of collections are not covered by this issue.

@yaakov-h Does that cover it?

@nunit/framework-team Do you agree with this approach?

**Comment by CharliePoole** [comment]
BTW I do like this format myself.

**Comment by ChrisMaddock** [comment]
That spec looks fine to me.

Question (for @CharliePoole probably) - do we need to think about any sanitation here at all - are the currently any restrictions on what characters can be in a test name? e.g. for Test Selection Language filtering? I imagine the answer is 'no' - given we already include user-strings in test names.

**Comment by ChrisMaddock** [comment]
>Other types of collections are not covered by this issue.

If we were to do this for IOrderedCollection instead of array, would there be any additional overhead? 

We shouldn't do unordered collections (at least, in this issue), as that could mean non-repeatable test names, which can cause downstream problems.

**Comment by CharliePoole** [comment]
I'd say no. We're only adding s specialized use of square brackets, which are not used in TSL.

**Comment by CharliePoole** [comment]
However, you reminded me of something else!

@OsirisTerje will the square brackets mess up the Test Explorer?

**Comment by jnm2** [comment]
I like this approach. At first glance I'd want it to only apply to arguments which are array instances.

**Comment by CharliePoole** [comment]
@jnm2 I agree as far as this issue goes. We should leave out other collections as well as arrays with rank greater than 1 and deal with them in separate issues if they come up.

**Comment by yaakov-h** [comment]
As far as I know, this works in Visual Studio's Test Explorer - like I said, I have a similar custom test attribute that does this (and a few other things), and it works well there.

The custom attribute does all `IEnumerable`s, but since it's selectively applied to tests, that's not a problem. I don't think we should do that here, otherwise you pick up things like `IDictionary` and unordered collections, etc.

The only enumerable type that you can put into an attribute (`TestCase` or `Values`) is an array. For other types in `TestCaseSource` and `ValueSource` - Collections, ObservableCollections, ImmutableArrays... - consumers can override the test name as we can already do today.

@CharliePoole I like the edited spec, but I am slightly concerned about nesting. I'd hope nobody nests arrays 3 or 4 levels deep, or we'll print 5^N items and get rather long test names anyway. Perhaps we should only recurse one level, or just represent child arrays as `[ ... ]`?

**Comment by jnm2** [comment]
> The only enumerable type that you can put into an attribute (TestCase or Values) is an array. For other types in TestCaseSource and ValueSource - Collections, ObservableCollections, ImmutableArrays... - consumers can override the test name as we can already do today.

Just a note. You can override the test name using `[TestCase(..., TestName="...")]`.

**Comment by jnm2** [comment]
> I like the edited spec, but I am slightly concerned about nesting. I'd hope nobody nests arrays 3 or 4 levels deep, or we'll print 5^N items and get rather long test names anyway. Perhaps we should only recurse one level, or just represent child arrays as [ ... ]?

I don't really have an opinion. Can we start without recursion, just to simplify and get https://github.com/nunit/nunit/pull/2597 though? We can always adjust when someone reaches an opinion through a real-world encounter.

**Comment by CharliePoole** [comment]
@jnm2 I'm OK with that but we need code to recurse or not recurse when a nested array is found. What I mean is we have to do __something__ in the case of nesting.

**Comment by yaakov-h** [comment]
Looking at it now... I think the simplest thing to do is when iterating through an array, represent a child array element as a fixed string.

**Comment by CharliePoole** [comment]
Maybe not fixed, but "SomeType[]"
