### ISSUE TITLE
Bug when using Assert.Equals() with types that explicitly implement IEquatable<T>

### ISSUE THREAD

**Issue by daveaglick** [nunit/nunit#1386]
If a type involved in `Assert.Equals()` implements `IEquatable<T>`, the implementation of `IEquatable<T>` is used for the comparison (as expected). However, if a type *explicitly* implements `IEquatable<T>` then the corresponding `.Equals()` method isn't found and the comparison falls back to the default (typically reference equality).

I've isolated the problem to the `NUnit.Framework.Constraints.NUnitEqualityComparer.GetCorrectGenericEqualsMethod()` method. Here's a simple repro (from LINQPad) with the current head code for `GetCorrectGenericEqualsMethod()` that demonstrates the problem:

```csharp
void Main()
{
	MethodInfo a = GetCorrectGenericEqualsMethod(typeof(A), typeof(A));
	a.Dump(); // null
	MethodInfo b = GetCorrectGenericEqualsMethod(typeof(B), typeof(B));
	b.Dump(); // correct method found
}

MethodInfo GetCorrectGenericEqualsMethod(Type first, Type second)
{
	MethodInfo[] methods = first.GetMethods();
	foreach (var method in methods)
	{
		if (method.Name == "Equals")
		{
			ParameterInfo[] prms = method.GetParameters();
			if (prms.Length == 1 &&
				prms[0].ParameterType != typeof(Object) &&
				prms[0].ParameterType.IsAssignableFrom(second))
			{
				return method;
			}
		}
	}
	return null;
}

public class A : IEquatable<A>
{
	bool IEquatable<A>.Equals(A other)
	{
		return false;
	}
}

public class B : IEquatable<B>
{
	public bool Equals(B other)
	{
		return false;
	}
}
```

I plan to submit a PR for this soon - just opening an issue for tracking purposes.

**Comment by CharliePoole** [comment]
Aside from a PR, what would help to convince us this is a problem is a failing test case that we all agree should have passed. In theory we should only be using an explicit implementation if we are called with an instance specifically typed as the interface. That said, the fact that we currently lose the typing of the arguments (they are treated as objects) in NUnitEqualityComparer may force us to either always use the explicit implementation or never use it.

A perfect solution probably has to wait until we have a generic implementation of the comparer and everything leading up to it - a tall order - so compromise may be necessary. I'll be interested to see how far you can take it in your PR.

**Comment by CharliePoole** [comment]
I made this an "idea" for the reasons stated in my previous comment. An "idea" for us is something we might work on some day, but have not yet decided. With a good failing example, I'd probably call it a "bug", which is something we will work on ourselves or accept PRs on.

**Comment by daveaglick** [comment]
@CharliePoole I think the real problem here might actually be in `NUnitEqualityComparer.AreEqual()`. Consider the following code from that method:

```
if (FirstImplementsIEquatableOfSecond(xType, yType))
    return InvokeFirstIEquatableEqualsSecond(x, y);
else if (xType != yType && FirstImplementsIEquatableOfSecond(yType, xType))
    return InvokeFirstIEquatableEqualsSecond(y, x);
            
return x.Equals(y);
```

First we do a check with `FirstImplementsIEquatableOfSecond()` whether `IEquatable<T>` is implemented. This check returns `true` for a type that explicitly implements `IEquatable<T>`. *However*, when we go to evaluate the method (that we just said *does exist*) we can't find it and so `InvokeFirstIEquatableEqualsSecond()` returns `false` in every case.

This gets to the heart of it - it seems "icky" that while the `if` clause is (correctly) reporting an `Equals()` method is available, the code that actually gets run to evaluate it can't find it.

What if `FirstImplementsIEquatableOfSecond()` returned a MethodInfo instead of a `bool` and the did the check based on whether the `MethodInfo` was null or not? Then we could just pass the `MethodInfo` we found to `InvokeFirstIEquatableEqualsSecond()` instead of trying to find it again.

**Comment by daveaglick** [comment]
As for your follow-on, the judgement of whether this behavior is desirable (bug vs. idea) probably is a matter of opinion. From the user's perspective, it comes down to how much "smarts" `Assert.AreEqual()` should have. I was a little surprised when my tests were failing, even though I implemented `IEquatable<T>`. It especially surprised me when they were failing for some objects that implemented it explicitly but not for others that implemented it implicitly. My gut says it should either support the `IEquatable<T>` or not and the implicitness of the implementation shouldn't matter.

Regardless, I'll go ahead and submit a PR with one (or more) failing test(s) as well as a fix that supports explicit `IEquatable<T>` implementations since I don't anticipate it being very difficult. You can decide whether to pull it in or not at that point (no hard feelings if not).

**Comment by CharliePoole** [comment]
@daveaglick I agree. That code is definitely wrong if the InvokeX method is not calling what was found in the first place and your suggestion would be much cleaner way to ensure that happens.

That said, there are still two ways to fix this:
1. Fix so the explicit implementation is called
2. Fix so the explicit implementation is not seen at all

FYI, when we put in this code, we knew it was a bit odd. We planned to come back, but never did. :-(

**Comment by daveaglick** [comment]
> That said, there are still two ways to fix this

Yep, agree. I'd err on (1) for the reasons above and since that matches what `EqualityComparer<T>.Default` does. That said, (2) would also be a valid fix.

Lemme see what I can come up with...

**Comment by CharliePoole** [comment]
As devil's advocate, I have to say that it __often__ makes a difference in C# code whether an interface is implemented implicitly or explicitly. When it's explicit and you call using an object of the implementing type, the explicit method is not available. When you call with the interface type, it is.

Ideally, it seems as if NUnit should work like that. Practically, it's not possible, since the type used in making a call to assert is lost by the time we get down to this level.

That's to say, it's not possible without a complete reorganization of not just how we do equality, but of all constraints and assertions. I've worked on this at several different times as have others on the team. We keep running into roadblocks and abandoning the effort.

Like I said, though. I'm interested to see what you come up with. I think we have to simply choose whether (1) or (2) is the better compromise.

**Comment by daveaglick** [comment]
> it often makes a difference in C# code whether an interface is implemented implicitly or explicitly

Yeah, I see your point too. For example, in the example code at the top:

```
A a1 = new A();
A a2 = new A();
a1.Equals(a2).Dump(); // false

B b1 = new B();
B b2 = new B();
b1.Equals(b2).Dump(); // true
```

Also totally agree on the ideal solution. If `NUnitEqualityComparer` was generic or otherwise kept the generic type information that was used in the assert call, using that would be the way to go.

Thanks - this was a great discussion. And I think you talked me down from my original assumption, I see equal merit in both options now. I'll go ahead and submit some code and then it's all yours to deal with as you see fit :)
