### ISSUE TITLE
--testlist with file with blank first line causes IndexOutOfRangeException

### ISSUE THREAD

**Issue by NCarter3** [nunit/nunit#1390]
When I run a testlist file with a blank first line (and properly formatted test names on the remaining lines), NUnit crashes:

`Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.                                                                                                                                                at NUnit.Common.CommandLineOptions.<ConfigureOptions>b__111_1(String v)                                                                                                                                                                      at NUnit.Options.Option.Invoke(OptionContext c)                                                                                                                                                                                              at NUnit.Options.OptionSet.ParseValue(String option, OptionContext c)                                                                                                                                                                        at NUnit.Options.OptionSet.Parse(String argument, OptionContext c)                                                                                                                                                                           at NUnit.Options.OptionSet.Parse(IEnumerable`1 arguments)                                                                                                                                                                                    at NUnit.ConsoleRunner.Program.Main(String[] args) `

Perhaps this case could be handled more gracefully :)

**Comment by CharliePoole** [comment]
Indeed! What version of NUnit are you running?

**Comment by NCarter3** [comment]
I'm on 3.0.5813. Thanks!

**Comment by CharliePoole** [comment]
Confirmed by inspecting the code in CommandLineOptions.cs.

The code that reads the test file contains a line ` if (line[0] != '#')` the line length should be checked before indexing it at 0.
