### ISSUE TITLE
nunit.portable.agent.tests fail to build under VS2013

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#1391]
There are three compile errors in the assembly - ambiguous refs -  that don't show up in
2015.

**Comment by rprouse** [comment]
@CharliePoole I can't reproduce this. Are you sure you weren't working with an older copy of the source or on an older branch? I am pretty sure it was fixed by #1360

**Comment by rprouse** [comment]
I am going to close this as already fixed. @CharliePoole, reopen if it is not fixed for you and I will look at it.

**Comment by CharliePoole** [comment]
I came up with it when I was reviewing someone else's branch, so maybe it was out of date.
