### ISSUE TITLE
Accessing a test's arguments from a test action

### ISSUE THREAD

**Issue by mdvtj** [nunit/nunit#1395]
I would be interested to know if there is a specific reason why it is currently not possible to access the arguments passed to a parameterized test from a test action.

In the debugger I can see this information as part of an internal `Arguments` property of the `ITest` implementation (`TestMethod` in this situation).

Access to a test's arguments collection would be *extremely* helpful for designing test actions that provide a somewhat dynamic behavior (based an certain argument values).

**Comment by CharliePoole** [comment]
Before prioritizing this, it would be helpful to have an actual use case.

**Comment by mdvtj** [comment]
Our use case is the usage of a `ValueSourceAttribute` that initially should provide expensive and disposable objects. After fully understanding the docs (and that the values in this scenario are created a long time before the first test is started and furthermore are not disposed when the associated test has finished) we considered to let test actions create and dispose the expensive objects that are used by the tests:

* **Phase 1 (test detection):** `ValueSourceAttribute` provides some primitive unique information (we have chosen enum values)
* **Phase 2 (test execution):** A custom `ITestAction` decides before the test is started which object should be created (based on the actual test method argument value) and takes care of disposing that object when the test has finished. The expensive object is stored in the test's properties where it is fetched from by the test via some static (extension) method.

At the moment this test action requires reflection to access the actual test method argument value. :-(

**Comment by rprouse** [comment]
Thanks for the idea, but this isn't in keeping with our vision of where we want to take NUnit, so I am closing.
