### ISSUE TITLE
Cannot run STA thread tests

### ISSUE THREAD

**Issue by pcalin** [nunit/nunit#1398]
It seems nunit3 runs each test in a different thread. When testing UI this causes problems because only owner thread can manipulate UI objects. 

Testing WPF with nunit3.

Cheers, 
Călin

**Comment by CharliePoole** [comment]
This was an error introduced in 3.2. As a workaround you can revert to 3.0.1.

This issue duplicates #1333 which has been fixed in the source repository. The fix will be in the next binary release, either 3.4 or 3.2.1 if we do a point release.
