### ISSUE TITLE
Culture taking in account in test results in "nunit2" format using 3.0.1 but not with 2.6.4

### ISSUE THREAD

**Issue by reeflog** [nunit/nunit#1401]
Hello,

I've noticed a difference in the way culture for test results (the xml file) are handled between 2.6.4 and  3.0.1 with "nunit2" format.
"current-culture" is set in both in the good way but the formatting is not the same. On 2.6.4 "time" are always in "en-US" culture, for instance 1.234 (one second and 234 milliseconds). On 3.0.1 with "nunit2" format, it's formatted with the value of "current-culture", for instance 1,234 (one second and 234 milliseconds) for a french one.

Is it on purpose ?

I asking because some tools (like the plugin xUnit for Jenkins) were working fine with 2.6.4 but we have issues using the "nunit2" format with 3.0.1.

Thanks,

**Comment by ChrisMaddock** [comment]
I believe this was fixed in v3.2. Have a look at #1286.

**Comment by reeflog** [comment]
Yes, it seems so. Thanks.
