### ISSUE TITLE
TextCapture is not threadsafe but is used to intercept calls that are expected to be threadsafe.

### ISSUE THREAD

**Issue by jtattermusch** [nunit/nunit#1406]
It looks like the TextWriter used in https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/Execution/TextCapture.cs is not thread safe, but the TextCapture is used to intercept  Console.WriteLine (which itself is thread safe).

A solution would be to use a synchronized TextWriter?

This is the stack trace I'm seeing in one of my tests
```
Unhandled Exception:
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: destinationIndex
  at System.Text.StringBuilder.ThreadSafeCopy (System.Char* sourcePtr, System.Char[] destination, Int32 destinationIndex, Int32 count) <0x1909ea0 + 0x000aa> in <filename unknown>:0 
  at System.Text.StringBuilder.Append (System.Char* value, Int32 valueCount) <0x1909970 + 0x0004c> in <filename unknown>:0 
  at System.Text.StringBuilder.Append (System.Char[] value, Int32 startIndex, Int32 charCount) <0x1906ec0 + 0x000a4> in <filename unknown>:0 
  at System.IO.StringWriter.Write (System.Char[] buffer, Int32 index, Int32 count) <0x185b9a0 + 0x0009f> in <filename unknown>:0 
  at System.IO.TextWriter.WriteLine (System.String value) <0x185e090 + 0x00174> in <filename unknown>:0 
  at NUnit.Framework.Internal.Execution.TextCapture.WriteLine (System.String value) <0x7d0900 + 0x0004a> in <filename unknown>:0 
  at System.Console.WriteLine (System.String value) <0x1b1a540 + 0x00045> in <filename unknown>:0 
```

**Comment by jtattermusch** [comment]
I believe this is where the TextWrapper gets created.

https://github.com/nunit/nunit/blob/526534e93202f1da3f371d57d2b358341238c29f/src/NUnitFramework/nunitlite/TextRunner.cs#L123

**Comment by jtattermusch** [comment]
Based on https://msdn.microsoft.com/en-us/library/system.io.streamwriter(v=vs.110).aspx System.IO.StreamWriter is not thread-safe. Perhaps ExtendedTextWrapper can add the synchronization while wrapping TextWriter methods?

**Comment by CharliePoole** [comment]
Two clarifications please:
1. Are you encountering this running with NUnitLite? If not - that is if you are using another runner - then the NUnitLite code you mention doesn't come into play.
2. Do you have multiple threads in one test creating output?

**Comment by jtattermusch** [comment]
Yes, I am using NUnitLite.

here's my Main method:
```
public static int Main(string[] args)
 {
            return new AutoRun().Execute(args);
 }
```

I also have multiple tests printing to Console.Out (which gets redirected by NUnitLite). From looking at the code, it seems it creates a new ColorConsoleWriter() to capture the output.

**Comment by CharliePoole** [comment]
I understand that ColorConsoleWriter is not thread-safe. I need to figure out why it needs to be and if it always needs to be so. I thought we had designed so we always did our writes to it from the same thread. What platform build of nunitlite+framework are you using?

**Comment by CharliePoole** [comment]
Note to anyone working this: I believe TestCapture should always be writing to a buffer, not to ColorConsoleWriter. That buffer should be different for every test executed - more precisely for every TestExecutionContext. If multiple threads are running as part of the same test, then that requires synchronization, but we expect it to work across different tests without any locking.

**Comment by jtattermusch** [comment]
I think ColorConsoleWriter needs to be thread-safe because  it captures output from Console.WriteLine and there's no good reason why users should be limited to only doing writes from one particular thread (I have plenty of tests cases that use multiple threads - and basically any of these threads can print to console and they expect Console.Out to be threadsafe).

I am using NUnit and NUnitLite  3.2.0  on MacOSX (mono), target framework of my project is .NET 4.5.

**Comment by jtattermusch** [comment]
Thinking about this more - ColorConsoleWriter don't need to be threadsafe if it's just writing to the original Console.Out (because that one is threadsafe).  But if   Console.Out is set by NUnit to some other destination (which I believe is what TestCapture is doint), that destination needs to be thread-safe (and from the code it seems that there are at least some cases where this is not the case).

**Comment by CharliePoole** [comment]
Yes, that's what I meant. When we capture the text, we write to a string writer with a buffer in the current Test executioN context. I think that's the code we need to deal with.

**Comment by jtattermusch** [comment]
I've done a bit of debugging and context.CurrentResult.OutWriter seems to be  set to a plain old System.IO.StringWriter - but based on MSDN, this one is supposed to be threadsafe. Still, the stacktrace I pasted above seems to be pretty convincing.

https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/Execution/TextCapture.cs#L93

```
var context = TestExecutionContext.GetTestExecutionContext();
if (context != null && context.CurrentResult != null)
                context.CurrentResult.OutWriter.WriteLine(value);
```

**Comment by jtattermusch** [comment]
As a workaround - is there an option for NUnitLite to not capture output of my tests at all?

**Comment by CharliePoole** [comment]
I think the issue may be with that _defaultWriter that gets used if there is no TestExecutionContext. We'll look into it.

BTW, you had not answered me about whether your individual tests are creating their own threads. It makes a difference whether we are just dealing with different tests each on their threads or a test that creates multiple threads.

**Comment by jtattermusch** [comment]
Yes, my tests are definitely starting other threads. I am using target framework .NET 4.5 (but running on mono).

**Comment by jtattermusch** [comment]
See above *I am using NUnit and NUnitLite 3.2.0 on MacOSX (mono), target framework of my project is .NET 4.5.*

**Comment by jtattermusch** [comment]
Ah, looks like I misread the MSDN documentation for StringWriter:
*Any public static (Shared in Visual Basic) members of this type are thread safe. Any instance members are not guaranteed to be thread safe.*

So, let me review once again the behavior I'm seeing:

I have a test that spins up multiple threads that at some point write to Console.Out.
Within the test, the test execution context is set (is not null) and Console.Out gets redirected to a StringWriter.
StringWriter is not thread safe based on MSDN docs https://msdn.microsoft.com/en-us/library/system.io.stringwriter(v=vs.110).aspx.

```
var context = TestExecutionContext.GetTestExecutionContext();
if (context != null && context.CurrentResult != null)
                context.CurrentResult.OutWriter.WriteLine(value);
```
https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/Execution/TextCapture.cs#L93

As a result I sometimes get this error:

```
Unhandled Exception:
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: destinationIndex
  at System.Text.StringBuilder.ThreadSafeCopy (System.Char* sourcePtr, System.Char[] destination, Int32 destinationIndex, Int32 count) <0x1909ea0 + 0x000aa> in <filename unknown>:0 
  at System.Text.StringBuilder.Append (System.Char* value, Int32 valueCount) <0x1909970 + 0x0004c> in <filename unknown>:0 
  at System.Text.StringBuilder.Append (System.Char[] value, Int32 startIndex, Int32 charCount) <0x1906ec0 + 0x000a4> in <filename unknown>:0 
  at System.IO.StringWriter.Write (System.Char[] buffer, Int32 index, Int32 count) <0x185b9a0 + 0x0009f> in <filename unknown>:0 
  at System.IO.TextWriter.WriteLine (System.String value) <0x185e090 + 0x00174> in <filename unknown>:0 
  at NUnit.Framework.Internal.Execution.TextCapture.WriteLine (System.String value) <0x7d0900 + 0x0004a> in <filename unknown>:0 
  at System.Console.WriteLine (System.String value) <0x1b1a540 + 0x00045> in <filename unknown>:0 
```

To solve this, using TextWriter.Synchronized method might be useful:
`https://msdn.microsoft.com/en-us/library/system.io.textwriter.synchronized(v=vs.110).aspx`

**Comment by CharliePoole** [comment]
Good summary. One bit of info you may be missing is that the reference to TestExecutionContext.CurrentContext is stored in TLS. So each test gets a separate context. However, if you create a thread of your own, it doesn't have anything in TLS current context and we write to the _defaultWriter that was provided to the constructor of the TestCapture instance. I think that's where we are getting into trouble.

I'll need to set up a repro for this and then experiment. I'd like to find the a relatively low-overhead fix that only locks on the calls that actually require it.

**Comment by jtattermusch** [comment]
What you are saying makes sense. When I was looking at the code though, I didn't quite see how _defaultWriter could get buffered to a StringWriter. It seemed that the ConsoleColorWriter would just write everything to the original Console.Out which in my case is the actual console of my console app.

Btw, possibly unrelated, but does the TestExecutionContext (seems to be CallContext) flow with async calls?

**Comment by CharliePoole** [comment]
Our TestExecutionContext is stored in the CallContext, which is a .NET thing. Well, actually, it's only stored there on platforms that have a CallContext, but that includes yours.

Off the top of my head, I think it does flow through async calls as you suggest because .NET maintains the correct CallContext for us.

I'll know more when I have time to actually work in the code.
