### ISSUE TITLE
Assert.DoesNotThrow() should accept a generic argument

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [nunit/nunit#1407]
Hello,

In order to let `Assert.DoesNotThrow(___, message)` apply the message to a more specific exception, the generic type parameter should be allowed and to let other exceptions pass through and not have the `message` parameter "applied" to them (as the message does not "apply" to them, they should be let through).

**Comment by rprouse** [comment]
I am closing old Idea issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
