### ISSUE TITLE
Confusion in the understanding of a Suite

### ISSUE THREAD

**Issue by virenv** [nunit/nunit#1411]
I was trying to learn Nunit to use it in my project. I am confused in the what Nunit things of as a suite?
-
Context on problem: I have implemented the ITestEventListener and am using it to intercept all the different calls so that I can build my test reporters.

Problem: ITestEventListener::OnTestEvent call comes generally in this sequence
1. <start-suite> for assembly load
2. <start-suite> for Namespace load
..
..
..
--- <start-suite> for Class load
---<start-test> for test method load.

We can see that start-suite comes multiple times depending on how deep in hierarchy you test is. Fo r example I have a test class in  FunctionalTests.Payments.WebService.ErrorTests
In this case I get 5 start-suite calls. This is very confusing, we have to write extra logic to determine when a genuine call came in (We want to report tests per class). What is the right way to handle these scenarios? I am using NUnit 3.XX

**Comment by CharliePoole** [comment]
Test case and suite are logical constructs in NUnit, separate from their implementation in any programming language. A test case is a simple test containing no other tests. A test suite is any collection of tests - which may include cases or other suites.

A test case is represented in C# by a method plus any arguments it takes.

A test suite may be represented by an assembly, a namespace, a class, a group of classes (for example an open generic) or a test method without the arguments.

In XML the test-suite element contains an attribute 'type' whose value tells you what kind of suite it is. Unfortunately, that information is not contained in the start-suite element. That might be a mistake on our part, but it's how it is right now, so you can only determine if something is a TestFixture when you get the test-suite event, that is at the end of the fixture.
