### ISSUE TITLE
Lazy initialization of OutWriter in TestResult is not thread safe

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#1425]
As pointed out by @jtattermusch in #1415, the lazy initialization is not thread safe and doesn't buy us much since it is always instantiated. We should change to early initialization and also review other instances of lazy initialization.

I am going to assign to 3.4 milestone to ensure it gets done for the next release.

**Comment by CharliePoole** [comment]
I used a regular expression to find properties with lazy initialization. I'll write individual comments about each of these as needed.

1. ParallelWorkItemDispatcher.ParallelQUeue
2. ParallelWorkItemDispatcher.ParallelSTAQUeue
3. ParallelWorkItemDispatcher.NonParallelQUeue
4. ParallelWorkItemDispatcher.NonParallelSTAQUeue
5. OSPlatform.CurrentPlatform
6. Randomizer.SeedGenerator
7. TestResult.Children
8. RuntimeFramework.CurrentFramework
9. TestExecutionContext.CurrentContext
10. TestExecutionContext.Dispatcher
11. TestExecutionContext.RandomGenerator

**Comment by oznetmaster** [comment]
There is a .NET class Lazy<T> which implements lazy initialization in a thread safe manner.  Perhaps all of these lazy initializations should be changed to use it?

It was not introduced in .NET until 4.0, but the mono version is available, and works on earlier versions of .NET.

I use the mono version heavily in my CF builds.

**Comment by oznetmaster** [comment]
For those who have not used `Lazy<T>`, it simplifies the code, and makes it easier to read and understand.

**Comment by CharliePoole** [comment]
Thanks for the idea. I'll take a look at using it. However, I think I'll first find those lazy initializations that are not needed and get rid of them as @jtattermusch suggested. That turned out to be the case with OutputWriter and it looks to me like it's also true for some of these others.

**Comment by oznetmaster** [comment]
Lazy initialization is only useful if the object is not always used, and the resources required to do the initialization are substantial (significantly exceed the overhead of lazy initialization).

Otherwise, using early initialization makes the most sense.

**Comment by oznetmaster** [comment]
Not sure why you think that TestResult.Outwriter is being initialized in a thread safe manner, because it isn't.

The real issue is whether the class containing the lazy initialization is, in itself, defined as being thread safe.  If not, then the thread safety of its lazily initialized members is irrelevant.

If the class is defined as being thread safe on all of its members, then the thread safety of any lazily initialized objects must be maintained.

**Comment by CharliePoole** [comment]
@oznetmaster There are several versions of the code and you haven't said to which you are referring... current master, issue-1425, other?

**Comment by oznetmaster** [comment]
Sorry, master.  I have not looked at all the branches :(

**Comment by oznetmaster** [comment]
However, unless TestResult has been significantly rewritten, for example, the issue is really moot, since TestResult is not thread safe on any of its methods, so, the thread safety of its lazy initializers is not an issue.

**Comment by oznetmaster** [comment]
I see that you changed that one lazy initializer to an early initializer in issue-1425.

My comment above still holds, however.

**Comment by CharliePoole** [comment]
You're quite right. There is going to be a lot of work before we get this
right. Hopefully, we can subdivide it into multiple issues so that each PR
is easy to deal with.

My plan is to pick some low-hanging fruit and leave behind additional
issues with info about what else needs to be done. Perhaps you would like
to grab one of those issues, since this relates to CF as well as other
platforms.

**Comment by oznetmaster** [comment]
From briefly looking at the various lazy initializations you list above, I see no reason to change any of them, since they all appear to be located in classes which are not thread safe.  I would not even bother with TestResult.OutWriter.

Perhaps what is really needed is explicit documentation that all these classes are not thread safe on their instance measure, the same as Microsoft says in their documentation.

Also, maybe some of these classes need to be thread safe, in which case the entire class should be made thread safe.

**Comment by oznetmaster** [comment]
Note that this has nothing to do with making the TestResult.OutWriter TextWriter synchronized, which was necessary.

**Comment by CharliePoole** [comment]
You have me almost convinced. :-) 

But as devil's advocate, let's say a class has only one method that we call from multiple threads. Would you still say we need to make the entire class thread-safe? It's not as if these are general purpose classes that might get used in unpredicatable ways.

**Comment by CharliePoole** [comment]
To put it in another way... what criteria should we use in deciding which classes need to be made thread-safe?

**Comment by oznetmaster** [comment]
That I cannot answer.  I am not sure I know (but I hope you do) what classes can be used on multiple threads, and within those classes, if more then one method is called on those multiple threads.

Generically though, I have always written code with classes that are either 100% thread safe, or not.  Having shades of grey makes things very hard to maintain, debug, and use.

I guess that in very specific use cases, have a non-thread safe class with a single thread safe method might make sense, if you can guarantee that only that method will ever be called from multiple threads.  Usually hard to do :(

**Comment by CharliePoole** [comment]
The general division, I suppose, will be methods called to create and initialize an object versus methods that may be called, directly or indirectly, from the test execution threads.

I take your point that fixing the trivial stuff first may not be the best use of time. Maybe my limited time is better used on documenting which classes fall into which category.

**Comment by oznetmaster** [comment]
For instance, in the majority of my multi-threaded program, I now use the concurrent versions of of the various generic collections in every class which I want to be thread safe, or in every static usage where they can be accessed by multiple threads.  Perhaps it is overkill, but I never have to worry about thread safety with them.  Also use a lot of Interlocked methods in the code.

I also use the Atomic<T> and AtomicValue<T> libraries to declare atomic variables so that I can just access them in the code without worrying about using Interlocked (the Interlocked usage is hidden in the type itself).

**Comment by oznetmaster** [comment]
If you can document which cases fall into which category I will be happy to undertake fixing those that need to be fixed.  That makes for a reasonable division of labor :)

It might be reasonable to also consider using the mono ConcurrentGenericCollections code to allow the use of those classes in pre 4.0 builds.  I use it in my CF builds without a problem.

**Comment by CharliePoole** [comment]
@rprouse When you get a chance, please comment. Is this a reasonable way to go?

**Comment by CharliePoole** [comment]
I'm going to start documenting in any case, since that's the first step to anybody fixing these.

**Comment by oznetmaster** [comment]
BTW.  I fully agree that using lazy initialization when it is not necessary (like in the case of TestResult.OutWriter) is something that should be cleaned up as well.  That should be determined by the criteria I indicated earlier.

**Comment by CharliePoole** [comment]
Starting with documenting our use of queue creation in ParallelWorkItemDispatcher.

There can be up to four queues but they may not all be needed for a given test run. For example, if there are no tests requiring the STA, then ParalellelSTAQueue and NonParallelSTAQueue never need to be created.

The dispatcher starts with no queues. When the first item is dispatched, it decdes what queue to add it to based on it's characteristics. As a result of referencing that Queue through the property, it gets created. All other queues are created as the existing CompositeWorkItems create and dispatch child work items. For example, if the child item is not parallelizable, then the NonParallelQueue will get created as part of dispatching it.

There is a risk of two different threads trying to dispatch an item and create a new queue at the same time. Let's say we are running the first shift (parallel) with four worker threads. Two of them discover a child item that requires the STA queue. Both will be trying to create it.

We probably want to retain the lazy initialization here. In fact, we may want to expand it's use in the future by allowing the number of workers to change dynamically. I think this means that ParallelWorkItemDispatcher must be at least partially thread-safe - that is, at least insofar as it's creation of queues.

The queues themselves are already threadsafe, using a home-brew approach. We could decide to clean this up and use a concurrent queue from the mono code as @oznetmaster has suggested. This should be discussed before we commit to it.

I don't see other methods that need to be made thread-safe. The Enqueue method would be an obvious choice, but it hands the job to the queue itself, so I'm thinking we are OK there.

@oznetmaster Would you review this and tell me what you think of it in terms of
1. Is this the info that you feel is needed to work on it?
2. Do my conclusions make sense?

**Comment by CharliePoole** [comment]
Thread-safety of TestResult and derived classes...

This one is an obvious candidate for making thread-safe. As any test finishes, on its own thread, a Countdown object is used to decide whether it is the last child of it's parent to finish. In that case, the parent test result is set.

The Children property should probably be a concurrent list. Also, it should be initialized in advance and probably moved out of the base class to TestSuiteResult. Test cases don't have children.

The SetResult method should use a lock. Other public methods that call it probably don't need one but this should be reviewed.

**Comment by CharliePoole** [comment]
@oznetmaster Right. I plan to clean that up where there appears to be no other major work needed on a class. If there seems to be major work, as with the two I already documented, then it can be done as a part of that work.

**Comment by CharliePoole** [comment]
@oznetmaster This is a helpful discussion. What about a static property that is lazily initialized from multiple threads? Does `Lazy<T>` deal with that?

**Comment by oznetmaster** [comment]
Yes, it does.  In fact, it is most often used for static objects, where thread safety almost always rears its head.

`Lazy<T>` has multiple different thread safety modes as well.  One is no thread safety. In the first thread safe mode, the object factory (creator) is always run (perhaps multiple times), but only one resultant object is ever used.  In the other thread safe mode, the object factory is only ever called once.  Different process, performance and overhead for each mode.

**Comment by oznetmaster** [comment]
There is no ConcurrentList<T> class :(  However, the ConcurrentBag<T> might work, although it is unordered.  If ordering is needed, mono has an ConcurrentOrderedList<T> that I often use.

I will look at the use of Children and decide what is the best way to go.

**Comment by oznetmaster** [comment]
I would probably use ConcurrentQueue<T> to replace the List<T> for TestResult.Children, if we agree to use the mono library for those builds before 4.0.

It can be enumerated over, which is how it is used about 98% of the time.  Also, the first item of the queue (List[0]) can be gotten, which is seemingly the other 2% of the usage.

**Comment by CharliePoole** [comment]
@oznetmaster I created three more issues related to thread-safety and assigned them to you since you appear to have the best handle on what is needed: #1434, #1435 and #1436.

If you look at the list of items in the earlier comment, you'll see that I haven't dealt with the three last ones at all. I you have time to look at them and indicate what you think should be done that would be great - I'm out of time!

**Comment by oznetmaster** [comment]
Before I do anything, there needs to be a decision as to whether we are going to include the Lazy ConcurrentGenericCollections from mono for those builds before 4.0?

It would be my preference, but there are other ways of solving these issues.

**Comment by CharliePoole** [comment]
As a TDD guy, I'd be less inclined to make a big upfront decision about it. Off the top of my head, I'd say we need Lazy itself but I'm not so sure about the collections.

Can we take one issue at a time?

**Comment by oznetmaster** [comment]
This decision significantly affects possible solutions to #1434 and #1435.

**Comment by CharliePoole** [comment]
I'm not seeing the connection for #1435, although I do for #1434, which was the one I thought needed to be done first. What if you just looked at what is involved and came up with a plan? Or two plans? :-)

One of the things you told me earlier was that the Concurrent collections did not include a Concurent list. We currently use the ability of the list to sort child work items. Wouldn't this impact your choice?

**Comment by oznetmaster** [comment]
There was no indication the WorkItem or any of it derivatives was an issue.  I was referring to TestResult and its derivatives, where  Children are never sorted.  As I indicated, ConcurrentQueue works perfectly for that collection.

If we CompositeWorkItem.Children needs to be made thread safe, then I would use the mono ConcurrentOrderedList class, which would eliminate the need to sort, since it is already ordered.

**Comment by CharliePoole** [comment]
My mistake... No, I see no reason why they would need to be thread-safe. The parent CompositWorkItem does all the adding and sorting by the value of the OrderAttribute, and it is all done before any child test threads are even created.

Are you OK with merging the changes in PR #1433?

**Comment by oznetmaster** [comment]
The Concurrent classes and the Lazy class do not have to be used to solve thread safety issues.  Old fashioned lock as well as the Interlocked class does work.  It just can affect performance.

For low incidence usage of thread shared data, lock is just fine.  It is the high usage data where it can get in the way.

So not only does that thread safety needs of a particular class and its data need to be determined, its usage pattern does as well.  If it is frequent read and limited write, then a ReaderWriterLock may well be a better choice then just lock/Monitor or a Concurrent collection.
