### ISSUE TITLE
projectloader extension .nunit is already handled by another extension

### ISSUE THREAD

**Issue by shankbond** [nunit/nunit#1429]
Hi,

I am getting this exception when I am running below command for nunit3-console.exe either on command prompt or in a batch file.

**`..\..\..\..\.\packages\NUnit.ConsoleRunner.3.2.1\tools\nunit3-console.exe  Myproject.Tests.dll`**

**Environment:** Windows 7 64 bit
**Note:** On my machine I have a copy of entire solution and in one directory the above command works perfectly but on second directory, I am getting this error.

**Comment by ChrisMaddock** [comment]
This is an issue with the v3.2.1 packages - take a look at #1427.

The workaround is remove the files for the old 3.2.0 packages from your packages directory.
