### ISSUE TITLE
Visual Studio Update2: Exception NUnit.Core.UnsupportedFrameworkException, Exception thrown executing tests in

### ISSUE THREAD

**Issue by braekstuv** [nunit/nunit#1437]
Hello,

Since Visual studio Update 2, we're receiving an exception at the end of our tests:

Exception NUnit.Core.UnsupportedFrameworkException, Exception thrown executing tests in <path to test dll>

All tests pass, but the CI Build fails because of this exception.

Does anyone with update 2 get this error as well?

Please let me know if you need more information.

**Comment by rprouse** [comment]
`UnsupportedFrameworkException` usually means that you are trying to run unit tests that reference an unknown or unsupported test framework. You say all tests pass, so it sounds like your CI is trying to run tests for projects that do not contain tests.

1. Which CI server do you use?
2. How do you run your tests in that CI server?

It could be that your CI server is just passing your solution file to NUnit. Running solution files is unfortunately a bit buggy. Microsoft keeps adding new project types and we are never going to keep up. It is much more reliable to pass in your compiled assemblies.

**Comment by rprouse** [comment]
I am closing since we have not heard back from you. If you have more information, add it to this issue and we will reopen.
