### ISSUE TITLE
Linq

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1441]
Currently, NUnit does not use Linq, or specifically Linq lambda expressions, because of the need to be compatible with the .NET 2.0 framework.

Has any consideration been given to including the mono or corefx Linq library in the NET 2.0 build of NUnit so that Linq lambda expressions could be used?  

It would greatly simplify some code, and increase its maintainability. And it would only be required in the NET 2.0 builds.

**Comment by CharliePoole** [comment]
I added Linq support to allow a .NET 2.0 build of Mono.Addins when we were using that package. It was lots more than 2 files. Personally, I've never felt the lack of Linq, but then that's me. :-)

**Comment by rprouse** [comment]
I would be okay with this. I do really miss using Linq as people have probably noticed reviewing my portable specific code. I think that Linq is one of those things that only becomes 'indispensible' after you have used it for awhile.

We seem to have a different opinion on how many files would be required though. @oznetmaster, can you confirm?

**Comment by CharliePoole** [comment]
I'm OK if we can add code we don't need to maintain. As an aside, let's decide once and for all how we treat file headers for such classes.

**Comment by CharliePoole** [comment]
Here is a link to the directory of files from mono I needed to add to get Mono.Addins to work under .NET 2.0 ...

https://github.com/nunit/nunit/tree/3e1c4f6ed889a75060d7d0d5fe003ed67580a719/src/NUnitEngine/mono-addins/Compatibility

It's possible there is more stuff here than what @oznetmaster is talking about adding.

**Comment by oznetmaster** [comment]
That seems about right.  I will confirm.  However, many of those are very small files, one or two function, or an interface.  Enumerable is by far the major one.

**Comment by oznetmaster** [comment]
I am curious.  How many people still use the .NET 2.0 build?  This is a similar question to how many still use the CF build (besides me :) )

**Comment by oznetmaster** [comment]
Would the preference be to use the mono version, or the corefx version?  They both use the MIT license.  However, the corefx version is being actively maintained, and mono is rapidly converting to use corefx as its basis.

**Comment by oznetmaster** [comment]
Probably the version from mono 3.12 might be the best, since  it is C# 3.0 compatible, where the corefx and mono 4.x use C# 6 in some places, and would have to be converted.

**Comment by oznetmaster** [comment]
It would be worth considering building the NUnit version of System.Linq as an assembly for the 2.0 build, rather then including the set of source files in the framework build.  That way, it could easily be used anywhere in the 2.0 build that was desired.

**Comment by oznetmaster** [comment]
Also, note that adding the subset of System.Linq that @CharliePoole listed would also add Tuple to the source tree, and could make the use of tuple possible in all build that do not have it (any before 4.0)

**Comment by CharliePoole** [comment]
If we are using somebody else's source, my leaning would be to use something that is stable and doesn't require our modifying it.

Having a separate assembly would mean that the 2.0 framework would have a dependency. Traditionally, we have always kept it as a single assembly. However, there has been discussion of splitting it in the future, so maybe that's not such a big deal any longer, particularly nowadays when the unit of reference is the package rather than the assembly.

The main downside of this idea is that it's a refactoring that does not produce any direct or immediate benefit for users, while taking time away from stuff that does. That's a decision we have to make.

**Comment by CharliePoole** [comment]
Let's not add anything speculatively. The list I created was the exact minimum necessar to allow compiling Mono.Addins under 2.0 without change. If we later feel a strong need to add more files, we can always do it.

**Comment by oznetmaster** [comment]
I was not suggesting adding more files, but the possibility of removing some.  However, I am happy with that list.

**Comment by oznetmaster** [comment]
It is only a refactoring if we retroactively change existing code to use Linq.  If we only use it going forward as code is added, updated or rewritten, then I do not see the why it would take time away from anything.

**Comment by oznetmaster** [comment]
My question about the NET 2.0 usage still remains.  It is not meant to be a deciding factor, but just for my curiosity.

**Comment by oznetmaster** [comment]
I have no problem just adding it to the 2.0 framework assembly, if a separate assembly is not desirable.    It seemingly would make little if any difference, and might be easier.

**Comment by CharliePoole** [comment]
Ah... I hadn't thought of doing it that way. It's a possible way to go.

Regarding 2.0 usage, we did a survey about two years ago. Of those responding, 9.41% ran tests under .NET 2.0 on Windows.

**Comment by oznetmaster** [comment]
Maybe a current survey could be useful? I am curious about current usage of both 2.0 and CF.

**Comment by oznetmaster** [comment]
With this many files, would it be better to condition them all, or to just include them only in the 2.0 projects (framework and nunitlite)? (I am assuming we just add them to the framework, and not make a separate assembly.

**Comment by CharliePoole** [comment]
That survey was what we used to decide what to support in 3.0. I'd do another if we were thinking of de-supporting something for 4.0, but that's not imminent. For CF we do have download stats, since it is a separate download.

**Comment by CharliePoole** [comment]
I would just include them where needed, since we may not want to edit them at all.

**Comment by oznetmaster** [comment]
PR #1444 adds SystemLinq to the 2.0 build.  This is a .NET 3.5 (include CF 3.5) compatible subset of System.Linq.  No IQueryable based classes.

It also adds, as a side effect, NET 3.5 compatible versions of HashSet, Action, and Func.
