### ISSUE TITLE
Display test names in stdout not working? nunit 3.2.1

### ISSUE THREAD

**Issue by bigangrydog** [nunit/nunit#1442]
When I run nunit3-console, I am unable to see a list of test cases. I'm trying to get it to show a list of test case names, along with Assert.Pass() information. All I get is a summary report, which only shows the number of tests run/passed.

Here is my command line:

CleromTest.csproj /config:Debug /work:Results /out:TestResult.txt /wait /labels:On

The "labels" and "full" parameters seem to do nothing (at least for me).

** Additionally, the output directed to "TestResult.txt" only ever generates an empty file. **

Am I missing something here, or is there a problem?

Andy

**Comment by bigangrydog** [comment]
Just to add, my tests are passing. I do see failure information if they fail.

**Comment by CharliePoole** [comment]
With labels:On, which is the default, you should see labels for tests that produce output. With labels:All you should see the name of every test.

A message you pass to Assert.Pass isn't text output. It appears in the XML only.

The --full option is implemented and should not be accepted. We will take a look at that.

**Comment by bigangrydog** [comment]
Thanks for getting back to me. What do you mean by "produce output"?

I see the test names in the xml file, but not on screeen. Here is my command line:

nunit3-console /work:Results /out:TestResult.txt /labels:All /wait /verbose CleromTest.csproj

And here is the output:

NUnit Console Runner 3.2.1
Copyright (C) 2016 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.10586.0
  CLR Version: 4.0.30319.42000

Test Files
    CleromTest.csproj

Test Run Summary
  Overall result: Passed
  Test Count: 2, Passed: 2, Failed: 0, Inconclusive: 0, Skipped: 0
  Start time: 2016-04-23 18:34:15Z
    End time: 2016-04-23 18:34:15Z
    Duration: 0.079 seconds

Results (nunit3) saved as TestResult.xml

Any thoughts?

**Comment by CharliePoole** [comment]
By "produce output" I mean create text output by use of Console.Write, Console.Writeline, TestContext.Write or TestContext.WriteLine.

Does the problem only arise when you redirect output to a file?

**Comment by bigangrydog** [comment]
Yes! That's it. The test names appear when I remove "/out:..."

Also note with "/out" all I get is an empty file. Is there any way of writing text files to disk?

**Comment by CharliePoole** [comment]
Are your tests producing any output as defined above?

The /out option has been around for about 15 years and has always redirected the output created by the tests to a file, not the output from NUnit itself. The reason for this choice is simple: If you want both kinds of output in a file, you can use command-line redirection as provided by the OS. The option is only necessary if the two kinds of output need to go to different places.

It's entirely possible that the label output is not going to the right place and it would be great if you could check it out. Any label produced by --labels:On (the default) should end up in the same place as the text output itself. --labels:All is used for a different purpose and may not be redirected by /out.

If you want to text to disk from your tests, you only need to use Console.Write with output redirected to the disk file. I use this routinely, so if you are getting an empty file, it may be that your Writes are not being executed.

**Comment by bigangrydog** [comment]
>The /out option has been around for about 15 years and has always redirected the output created by the tests to a file, not the output from NUnit itself.

That wasn't clear to me, but I understand now.

So the only issue here is that test names don't show up in the console output if the option "/out" is used. Or is that defined behaviour?

**Comment by CharliePoole** [comment]
It's defined to show up wherever text output is going: either on the console or in the file specified by the /out option. That's because it's purpose is to provide separators for the text output. It sounds as if that is not happening for you.

**Comment by bigangrydog** [comment]
OK. Thank you for your help. And well done on a great piece of software!
