### ISSUE TITLE
CommandLineTests should be in common

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1443]
Both nunit3-console.tests and nunitlite.tests contain CommandLineTests.

It would seem that CommandLineTests could be moved to Common.tests, so that the issue of keeping the two in sync would go away.

The recent addition of ShouldNotFailOnEmptyLine to nunit3-console.tests.CommandLineTests and not to nunitlite.tests.CommandLineTests is an example.

If any tests are specific to one or the other then conditions could be used, but it appears there are only a few of those.

**Comment by CharliePoole** [comment]
The framework and console runner will most likely end up as completely separate projects. Rob and I have been talking about the timing of this, which is uncertain. It won't be before fall I think.

So, there may be a move to reduce Common code shared between those two projects before then.

**Comment by rprouse** [comment]
While it would be cleaner to move it to common, we will be separating the repositories, so I am going to close this.
