### ISSUE TITLE
Silverlight detection doesn't work when building on 32-bit OS

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1450]
The fix made to build.cake so that Silverlight would be skipped if not installed is not working correctly on my 32-bit Windows system, causing the build and test to always be skipped. There is no ProgramFiles(x86) environment variable on this system, only ProgramFiles.

**Comment by ChrisMaddock** [comment]
I guess not! :-) Spent a while trying to work out if there was a registry key to detection or something, but checking the default install location was the only option I could find. And I'm not sure of a better solution to this then checking a different default install location if on 32 bit. Sorry about that one!

**Comment by CharliePoole** [comment]
You could of course check both environment variables, before constructing the path to check. That may be easier than figuring out what OS you are running on.
