### ISSUE TITLE
Improve DelayedConstraint with polling to succeed immediately if possible

### ISSUE THREAD

**Issue by chm-tm** [nunit/nunit#1460]
Consider the following code snippet:

``` csharp
for (int i = 0; i < size; i++) {
    Expect(() => fifo.IsFull, False.After(Timeout, 0));
    fifo.Enqueue(data); 
}
```

The intent of the code is to not delay execution when the FIFO isn't full. If the FIFO is full, it should busy loop until it is no longer full. Hence the polling interval is set to 0.
In other words, the code should behave like the following, while implementing a timeout.

``` csharp
for (int i = 0; i < size; i++) {
    while (fifo.IsFull) Thread.Sleep(0);
    fifo.Enqueue(data);
}
```

The code using the constraint is robust against all cases where the FIFO implementation is broken, in that it won't block test execution. This robustness comes with a minimal change in one line, which is still easy to understand and compact.

However, the `DelayedConstraint` cannot currently used like this for two reasons:
1. Passing 0 for the `pollingInterval` parameter is like not passing the argument at all, causing a delay of `Timeout` ms every time the constraint is called.
2. If a polling interval is considered, the constraint is not checked before pausing at least once.
- Consider changing the semantics of the `pollingInterval` parameter such that passing 0 as argument doesn't mean no polling, but polling in a busy loop.
- Consider testing the constraint prior any delay whenever the `pollingInterval` argument is passed.

**Comment by CharliePoole** [comment]
I marked this as an idea because I think we need to give it some thought before designing a feature. It's actually a rather good idea in my book.

Rather than redefining the meaning of a zero polling interval, I think we should provide one or more modifiers to the syntax indicating how the delay should be handled. I think this could be clearer than making zero a magic number.

We may want to consider modifiers for various new behaviors:
 * Continuous polling
 * Use of Interlocked
 * Checking initially

In addition, it might be desirable to allow a waitable argument to After or to add a Wait syntax.

All in all, I think DelayedConstraint may be ready for a re-design.

**Comment by chm-tm** [comment]
A new design might cause a bit more work than required with respect to the requirements I described.
It could help to clarify the meaning of `pollingInterval == 0`, though.
Actually, it's just the current implementation which handles zero in a magic way, by not even polling. The proposal in turn doesn't handle zero differently than any other `pollingInterval`. It's just from an implementation perspective, where you can no longer handle the `After` overload with one parameter the same way like `pollingInterval == 0`.

A new design would help maintaining backward compatibility, even though I wonder if there is a `pollingInterval == 0` in the wild.

Some spontaneous proposals for a new syntax:
```csharp
Expect(del, True.AfterPolling(pollingInterval);
Expect(del, True.AfterPolling(pollingInterval, timeout);
Expect(del, True.Poll(pollingInterval));
Expect(del, True.Poll(pollingInterval, timeout));
```

**Comment by Haukinger** [comment]
With the new syntax, can we get something like `After(1).Minutes.CheckNowAndPollEvery(5).Seconds` ?

**Comment by rprouse** [comment]
I am closing old Idea issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
