### ISSUE TITLE
Should TestResult.AssertCount have a public setter?

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1463]
It seems that TestResult.AssertCount should not have a public setter.  ITestResult does not require it.

Not sure why it is public?

**Comment by CharliePoole** [comment]
There are a few tests that set it and it's set by the derived classes. For the tests, it could be internal and for the derived classes protected. You could satisfy both by making it internal with a protected backing field. I opted for the simplicity of over-exposure.

FWIW, this disregard for keeping things private has been fairly typical of most unit testing frameworks, which originated in languages that didn't have visibility levels.

**Comment by oznetmaster** [comment]
The introduction of thread safety makes this more of an issue.  I would prefer that it were internal, at least.

**Comment by CharliePoole** [comment]
Another option might be to examine those tests and see why they are doing it and if it's really necessary.
