### ISSUE TITLE
TNode.EscapeInvalidXmlCharacters recreates Regex continually

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1464]
TNode.EscapeInvalidXmlCharacters has a Regex that is creates on every call to the method.

In normal .NET, the Regex can often be cached, and this will incur little penalty.  However, on the CF build, a large percentage of the time in writing the output it actually spent in creating this Regex!

This Regex should be static like all the other Regex are.

**Comment by rprouse** [comment]
Good catch.
