### ISSUE TITLE
Assert.AreEqual in a loop

### ISSUE THREAD

**Issue by anilrepala505** [nunit/nunit#1477]
How to use Assert.AreEqual in a for loop using C#.
Example:
List<String> listA = new List<String>();
List<String> listB = new List<String>();
for (int a = 0; a < 10; a++)
                {
                    Assert.AreEqual(listB[a] , listA[a]);
                }

loop has to continue even after failing at some point.

**Comment by appel1** [comment]
Until NUnit supports multiple asserts, #391, you'd need to do the loop first and compare data yourself and then use something like Assert.Fail after the loop completes.

**Comment by rprouse** [comment]
I am closing this as a question. @anilrepala505 feel free to continue to post to this issue if you need more help.

**Comment by nimalas** [comment]
You can use Assert.Multiple anilrepala505

            Assert.Multiple(() =>
                {
                    foreach (var expected in expectedValues)
                    {
                        Assert.AreEqual(expected, actual);
                    }
                }
            );
