### ISSUE TITLE
NUnit 3.2.1 compatibility with Visual studio 2015 

### ISSUE THREAD

**Issue by anilrepala505** [nunit/nunit#1478]
Hi,
When i use nunit 2.x version test methods are visible in test explorer of visual studio and tests are getting executed. But, when i use nunit 3.2.1 tests are not getting displayed in test explorer and while executing its throwing an error 'No tests were found'.

**Comment by appel1** [comment]
Are you using the NUnit 3 test adapter?

**Comment by anilrepala505** [comment]
@appel1 In visual studio 2015, NUnit test adaptor version 2.0.0 is available

**Comment by appel1** [comment]
There's also a NUnit3 Test Adapter.

https://github.com/nunit/docs/wiki/VS-Adapter-Documentation
https://visualstudiogallery.msdn.microsoft.com/0da0f6bd-9bb6-4ae3-87a8-537788622f2d

**Comment by anilrepala505** [comment]
@appel1 thanks for the help
