### ISSUE TITLE
Parallel execution, speed gain stops at 8 workers

### ISSUE THREAD

**Issue by hackle** [nunit/nunit#1482]
I have a fair sized unit test projects with over 10 thousand of unit tests. When running in parallel with NUnit3 console, I can clearly see the speed gain if I increase the number of workers, until it reaches 8, then increasing the number only results in loss of speed.

For example at --workers = 8, total time is 132 seconds.
Then at --workers = 16, total time is 147 seconds.

I've tried it on different machines with different numbers of CPU cores, although the total time is slightly different the bottleneck appears similar.

I could see that the tests are evenly distributed amongst the 16 workers, which means although they run in parallel, somehow no more speed can be gained.

I presume there must be some overhead in spawning up workers. This might not be an issue pe se but would be sweet to get some insights or even have it documented.

**Comment by oznetmaster** [comment]
How many cores on the processor / number of processors are the tests being run on?

**Comment by hackle** [comment]
So I tried 8 cores / 2 - 32 workers, 16 cores / 2 - 32 workers to figure out the patterns.

**Comment by oznetmaster** [comment]
You only posted one set of results.  Was that with 8 cores or 16 cores.  With 8 cores, I would expect to see things slow down with 16 workers.  With 16 cores, I would expect 16 workers to be faster.

**Comment by hackle** [comment]
I think you must be right - it must be most efficient to have one worker per core.

**Comment by rprouse** [comment]
The most efficient number of workers really depends on your tests. If your tests are CPU bound, then one worker per core is most efficient. If your tests block on calls to databases, web pages, REST APIs, etc, then you will likely find two or more workers per core to be faster. That is why we allow you to tune the value to your needs from the command line.

I am going to close this issue unless people have suggestions for tuning the defaults.
