### ISSUE TITLE
Remoting exceptions during test execution

### ISSUE THREAD

**Issue by vgriph** [nunit/nunit#1483]
In the process of migrating from NUnit 2.6 to 3.2.1 I repeatedly run into errors with tests that fail to report the result during the execution, and the internal trace files of the test run fills up with remoting exceptions similar to this on:

> System.Runtime.Remoting.RemotingException: Object '/4f1134d2_f841_416d_b1a9_a0a78447fc4a/upwuhw+18ooxwlbxdcaourel_1.rem' has been disconnected or does not exist at the server.
> 
> Server stack trace: 
>    at System.Runtime.Remoting.Channels.ChannelServices.CheckDisconnectedOrCreateWellKnownObject(IMessage msg)
>    at System.Runtime.Remoting.Channels.ChannelServices.DispatchMessage(IServerChannelSinkStack sinkStack, IMessage msg, IMessage& replyMsg)
> 
> Exception rethrown at [0]: 
>    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
>    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
>    at NUnit.Engine.ITestEventListener.OnTestEvent(String report)
>    at NUnit.Engine.RunTestsCallbackHandler.ReportProgress(String state)
>    at NUnit.Engine.CallbackHandler.RaiseCallbackEvent(String eventArgument)
>    at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
>    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
> 
> Exception rethrown at [1]: 
>    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
>    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
>    at System.Web.UI.ICallbackEventHandler.RaiseCallbackEvent(String eventArgument)
>    at NUnit.Framework.Internal.TestProgressReporter.TestFinished(ITestResult result)

After the first such exception no further similar exceptions are reported. It seems to occur whenever a test takes "long" time to report progress, which usually happens for us when there is some errors in the test. However finding the errors is challenging when the result is not reported. Any tests that has not completed before the first error fails to report status to TeamCity, so it looks as if the that is missing rather than not executed at all/executed with failure.

Full trace of a failed test execution:
[remoting-error.txt](https://github.com/nunit/nunit/files/253803/remoting-error.txt)

**Comment by CharliePoole** [comment]
Among other things, it looks like an exception in reporting a TestFinished event is logged and the run continues. That makes sense for some exceptions but not for this one. If we can't communicate results back to the runner, we should abort.

**Comment by CharliePoole** [comment]
@vgriph Can you tell us what command-line is being passed to NUnit?

**Comment by vgriph** [comment]
@CharliePoole Sure. The command line was:
nunit3-console.exe"  "Source\Build\Test.Integration.dll" "Source\Build\Test.Performance.dll" "-where=cat == SIP && cat != Unstable && cat != Manual && cat != Performance && cat != LyncCallManager && cat != LyncAdapter" -process=Separate -noheader -x86 -teamcity -trace=Debug -v -work=. -result=Build/Reports/TestResults.integration.xml

I attach all nunit logs as well as the report file if you want to look at some other logs as well.
[logs-bug-1483.zip](https://github.com/nunit/nunit/files/253856/logs-bug-1483.zip)

**Comment by ChrisMaddock** [comment]
@vgriph - I presume #1489 fixed this issue?

**Comment by ChrisMaddock** [comment]
Nevermind, just spotted the issue number in the pull request title! Closing.

**Comment by ivanball** [comment]
Good morning. Where can I download an nunit console with this issue fixed?
