### ISSUE TITLE
Comparing Equality using IEquatable<T> Should Use Most Specific Method

### ISSUE THREAD

**Issue by lundmikkel** [nunit/nunit#1484]
Consider this example:
```C#
public class EquatableObject : IEquatable<EquatableObject>
{
    public int SomeProperty { get; set; }
    public bool Equals(EquatableObject other)
    {
        if (other == null)
            return false;

        return SomeProperty == other.SomeProperty;
    }
}

public class InheritingEquatableObject : EquatableObject, IEquatable<InheritingEquatableObject>
{
    public int OtherProperty { get; set; }
    public bool Equals(InheritingEquatableObject other)
    {
        if (other == null)
            return false;

        return OtherProperty == other.OtherProperty && Equals((EquatableObject) other);
    }
}
```
The following test currently fails:
```C#
[Test]
public void InheritingAndOverridingIEquatable()
{
    var obj1 = new InheritingEquatableObject { SomeProperty = 1, OtherProperty = 2 };
    var obj2 = new InheritingEquatableObject { SomeProperty = 1, OtherProperty = 2 };
    var obj3 = new InheritingEquatableObject { SomeProperty = 1, OtherProperty = 3 };
    var obj4 = new InheritingEquatableObject { SomeProperty = 4, OtherProperty = 2 };

    Assert.That(obj1, Is.EqualTo(obj2));
    Assert.That(obj1, Is.Not.EqualTo(obj3)); // <-- Fails
    Assert.That(obj1, Is.Not.EqualTo(obj4));
}
```
The second test fails, because the `EquatableObject`'s `Equals()` is used. It should be `InheritingEquatableObject`'s `Equals()` instead.

This is because [`NUnitEqualityComparer.FirstImplementsIEquatableOfSecond()`](https://github.com/nunit/nunit/blob/6f5c24f0a46d152a1fbffd907941e7e44c0058d7/src/NUnitFramework/framework/Constraints/NUnitEqualityComparer.cs#L250-257)  just returns the first usable method from the list generated by [`NUnitEqualityComparer.GetEquatableGenericArguments()`](https://github.com/nunit/nunit/blob/6f5c24f0a46d152a1fbffd907941e7e44c0058d7/src/NUnitFramework/framework/Constraints/NUnitEqualityComparer.cs#L259-275):
```C#
ivate static MethodInfo FirstImplementsIEquatableOfSecond(Type first, Type second)
{
    var equatableGenericArguments = GetEquatableGenericArguments(first);
    foreach (var xEquatableArgument in equatableGenericArguments)
        if (xEquatableArgument.Key.IsAssignableFrom(second))
            return xEquatableArgument.Value;

    return null;
}
```
The result from `GetEquatableGenericArguments()` should somehow be sorted, or `FirstImplementsIEquatableOfSecond()` should return the best match, not just the first. The second approach seems to make most sense.

**Comment by lundmikkel** [comment]
I'll just leave this here for later reference: [How to check if a class inherits another class without instantiating it?](http://stackoverflow.com/questions/8699053/how-to-check-if-a-class-inherits-another-class-without-instantiating-it)

**Comment by lundmikkel** [comment]
Btw, is it okay to use LINQ here? There is a simple filter that could be done with `Enumerable.Where()`, and [`GetEquatableGenericArguments()`](https://github.com/lundmikkel/nunit/blob/e4cbfe6b870c092b69a8431fe2b898fe5bfacf70/src/NUnitFramework/framework/Constraints/NUnitEqualityComparer.cs#L264-265) even seems to have a comment about a previous solution that seems easily solvable with LINQ.

**Comment by CharliePoole** [comment]
In the past, that would have been a NO, because the framework needs to build in .NET 2.0. Recently, however, we added our own System.Linq implementation taken from Mono. I think it's partial but it satisfies most requirements we have. So long as your 2.0 project builds, you are OK.

**Comment by lundmikkel** [comment]
Great, I thought I had seen that you added LINQ for .NET 2.0. I'll note that for the future. This one should work for now. I'm not sure if there are other more complex scenarios that should be tested. Everything seems to work; even the new tests described above.

Is there any release data on the next version?

**Comment by CharliePoole** [comment]
We are trying to release on an approximate quarterly schedule, which you can see by looking at the milestones on forgive. The 3.4 release is planned for June 29.
