### ISSUE TITLE
Can't test a class containing 100k methods

### ISSUE THREAD

**Issue by NikolayPianikov** [nunit/nunit#1485]
Error occurred: "Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information." For examples for these [assemblies](https://github.com/nunit/nunit/files/256848/mocks.zip). But I am not sure this is error, perhaps there is a some limitation.

**Comment by iCodeIT** [comment]
This seems to be a limitiation in the .NET framework itself. See for instance http://programmers.stackexchange.com/questions/193295/implications-of-a-large-partial-class

**Comment by godrose** [comment]
Any limitations as to separating the class into several smaller classes?

**Comment by rprouse** [comment]
@iCodeIT thanks for the link. It looks like a .NET limitation. To be honest, I am not surprised :smile: 

@NikolayPianikov I am going to close this as not our bug. Feel free to comment if you feel that is incorrect.
