### ISSUE TITLE
Running unit test on TFS 2015 Update 2 (2015.2) with code coverage will be crashed.

### ISSUE THREAD

**Issue by regionbbs** [nunit/nunit#1490]
I use NUnitTestAdapter.WithFramework v2.0.0 to integrate TFS 2015.2 autobuild testing.

If I checked "Code Coverage" test option then start build, it failed with error message "Process had terminated unexpected". but **it works without code coverage option checked.**

I can't sure this issue map to TFS or NUnit.

**Comment by rprouse** [comment]
If it is an NUnit issue, then it is likely an Adapter issue, not an NUnit issue.

That said, we will need more information to help you diagnose this issue. Can you get more detailed error reports? Many of us don't have Ultimate subscriptions, so don't use the Microsoft code coverage. That is what it is, correct?

**Comment by regionbbs** [comment]
I were prompted some methods to get dump log, but I think that's for Microsoft Engineer only.

My environment built with TFS express 2015.2, and use Visual Studio Community edition 2015.2, so I think you can use free version of TFS and VSCE to try it.

**Comment by rprouse** [comment]
I am closing this because it has been inactive for so long. If anyone has further info, we can reopen.

**Comment by aidanhorton** [comment]
I have the same issue using NUnitTestAdapter.WithFramework v2.0.0 and TFS build 2015.

Here's the pastebin error I get when I try to enable code coverage: https://pastebin.com/QxbutNbg
(X is just me obfuscating the names).

**Comment by mikkelbu** [comment]
Hi @aidanhorton 
I don't use TSF, but the logs from pastebin mentions that there could be information in dump files _"... To investigate further, open file:///C:/Users/X/AppData/Local/CrashDumps/TE.ProcessHost.Managed.exe.1460.dmp file in Visual Studio and choose "Debug in mixed mode"...."_ Have you tried to do this?

**Comment by aidanhorton** [comment]
[http://tfs.malvern.com:8080/tfs/DefaultCollection/Sustaining%20Software/_workitems?_a=edit&id=95653](Dump file image) I can't see anything in there that means anything to me.
Running in 'Debug in mixed mode' just gives an error when trying to launch.

**Comment by aidanhorton** [comment]
[Dump file image](http://i577.photobucket.com/albums/ss215/aidanhorton/Image_zpsd0odujkj.png) - I can't see anything in there that means anything to me in the dump file, and trying to 'Debug in mixed mode' just gives an error.

**Comment by mikkelbu** [comment]
Hi @aidanhorton 

Not that it is much help, but I don't think that this is (solely) an NUnit problem. If I search for code coverage + parts of the error message then I get following pages 
* https://social.msdn.microsoft.com/Forums/en-US/8835ad39-d1a0-4fc5-a567-d8edef71b772/tfs-2015-build-test-run-crashes-when-running-the-build-agent-as-a-user-different-than-quotnt?forum=tfsbuild
* http://answers.flyppdevportal.com/MVC/Post/Thread/a3e93060-4fda-4e22-9e7a-a60d90f3ab78?category=vstest
* https://social.msdn.microsoft.com/Forums/sqlserver/en-US/a77bd888-ecb0-45c9-a3af-f218c1e31406/visual-studio-20151-test-runner-crashes?forum=vsunittest

and only the last page contains NUnit. So I guess that you can get more help at https://github.com/Microsoft/vstest

**Comment by aidanhorton** [comment]
Thanks @mikkelbu 
These links are very useful, and since this isn't an NUnit issue there's nothing else to say on my side, I'll follow it up elsewhere.
Thanks!
