### ISSUE TITLE
Investigate adding a CLA to the project

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#1491]
We have discussed it in the past, but haven't moved forward, so I am assigning myself an issue to remind me :smile: 

We should have some sort of Contributor License Agreement (CLA) to the project that assigns license or copyright of all contributions over to the NUnit project and asserts that the contributions are original work and the contributor has the rights to the code.

I prefer a granting of license, but an assignment of copyright would work too. Does any of the @nunit/core-team have strong feelings about this?

One option that integrates with our GitHub workflow is [CLAHub](https://www.clahub.com/) which plugs into the pull request pipeline. If we are going to do this, I think it needs to be as painless as possible.

Another option is to join a foundation that provides this service. This is a much bigger decision though, so we will need to discuss and evaluate the benefits. An interim solution for just CLAs would likely be a better first step.

**Comment by CharliePoole** [comment]
@rprouse it's OK to track this here, but let's think of it as related to all the nunit organization projects unless we run into some reason to make a distinction.

**Comment by mikkelbu** [comment]
@rprouse Since we have joined .Net Foundation we now have https://github.com/dnfclas, so I think this issue can be closed.
