### ISSUE TITLE
NUnit 3 results for nunit2 adapter are wrong

### ISSUE THREAD

**Issue by imakowski** [nunit/nunit#1492]
There is a difference when you run nunit3 with output to nunit2 format. test-suite type was ParameterizedTest in Nunit2 and now it is ParameterizedMethod
Nunit2
 <test-suite type="ParameterizedTest" name="PointTest" executed="True" result="Success" success="True" time="0.068" asserts="0"> <results> <test-case name="PointTest(&quot;String&quot;,&quot;a&quot;)" executed="True" result="Success" success="True" time="0.016" asserts="2" /> <test-case name="PointTest(&quot;String[]&quot;,System.String[])" executed="True" result="Success" success="True" time="0.005" asserts="2" /> </results> </test-suite>
Nunit3
 <test-suite type="ParameterizedMethod" name="PointTest" executed="True" result="Success" success="True" time="0.026" asserts="48"> <results> <test-case name="PointTest(&quot;String&quot;,&quot;a&quot;)" executed="True" result="Success" success="True" time="0.016" asserts="2" /> <test-case name="PointTest(&quot;String[]&quot;,System.String[])" executed="True" result="Success" success="True" time="0.005" asserts="2" /> </results> </test-suite>

**Comment by CharliePoole** [comment]
Actually, #1493 is the duplicate, but we already closed it.
