### ISSUE TITLE
NUnit 2 test results report ParameterizedMethod but should be ParameterizedTest

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#1493]
As reported by @imakowski;

There is also a difference when you run nunit3 with output to nunit2 format. test-suite type was ParameterizedTest in Nunit2 and now it is ParameterizedMethod

### Nunit2

```xml
<test-suite type="ParameterizedTest" name="PointTest" executed="True" result="Success" success="True" time="0.068" asserts="0">
	<results>
		<test-case name="PointTest(&quot;String&quot;,&quot;a&quot;)" executed="True" result="Success" success="True" time="0.016" asserts="2" />
		<test-case name="PointTest(&quot;String[]&quot;,System.String[])" executed="True" result="Success" success="True" time="0.005" asserts="2" />
	</results>
</test-suite>
```

### Nunit3

```xml
<test-suite type="ParameterizedMethod" name="PointTest" executed="True" result="Success" success="True" time="0.026" asserts="48">
	<results>
		<test-case name="PointTest(&quot;String&quot;,&quot;a&quot;)" executed="True" result="Success" success="True" time="0.016" asserts="2" />
		<test-case name="PointTest(&quot;String[]&quot;,System.String[])" executed="True" result="Success" success="True" time="0.005" asserts="2" />
	</results>
</test-suite>
```

**Comment by rprouse** [comment]
As initially reported in #1042

**Comment by imakowski** [comment]
I've created pull request for that https://github.com/nunit/nunit/pull/1494

**Comment by ChrisMaddock** [comment]
@rprouse: Is this a hand-modified example, or an actual test run? In your samples above, the test-suite `asserts` count is also different.

cc @imakowski

**Comment by ChrisMaddock** [comment]
@imakowski: The asserts counts are also different here in the `test-suite` element, I presume that's just a result of manually editing the xml for an example?

**Comment by CharliePoole** [comment]
@ChrisMaddock In creating the nunit2 result extension, I aimed to make the format compatible but not to give the exact results you would get from actually running NUnit 2.x. NUnit 3 counts asserts differently, so that's what is shown.

**Comment by ChrisMaddock** [comment]
Thanks @CharliePoole - I assumed it was meant to be identical!
