### ISSUE TITLE
Nunit Crashes intermittently.

### ISSUE THREAD

**Issue by mnarad** [nunit/nunit#1496]
I am using NUnit3 with parallelism. Most of the time it worked fine, However sometimes it get crashed. I looked at the logs of team city server and found the following logs in the eventviewer.

Faulting application name: nunit3-console.exe, version: 3.2.0.0, time stamp: 0x56db309a
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x000007fe00000000
Faulting process id: 0x77a4
Faulting application start time: 0x01d1ac20a1f16563
Faulting application path: E:\BuildAgent\work\d8502f117c433acb\libs\NUnit.ConsoleRunner.3.2.0\tools\nunit3-console.exe
Faulting module path: unknown
Report Id: 94ba9b7d-1814-11e6-88be-00155d3ae400

**Comment by NikolayPianikov** [comment]
It could relate to https://github.com/nunit/nunit/issues/1432
As workaround - try to add arg "--agents=1"

**Comment by CharliePoole** [comment]
What do you mean by "with parallelism?" NUnit supports two levels of parallelism, one within the process and the other between processes.

**Comment by CharliePoole** [comment]
@mnarad Please give the additional information requested. Otherwise we can't work on this.

Are you using parallel processes (--process:Multiple) or parallel threads (ParallelizableAttribute)?

**Comment by rprouse** [comment]
I am closing since we have not heard back from you. If you have more information, add it to this issue and we will reopen. There have been a number of threading issues fixed for 3.4, so hopefully that will solve your problem.
