### ISSUE TITLE
Erratic Assert counts for async tests

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1499]
This was first reported against the nunit.xamarin project but appears to be a problem with the framework itself. I created a branch `assert-counts` with a test class that demonstrates the problem. 

Errors are intermittent and may indicate a race condition in updating the TestExecutionContext. Errors show up more frequently in the portable build than in others. That could be significant since the TestExecutionContext is created differently in the portable build.

Since I'm travelling with limited equipment, I'm leaving this unassigned. Feel free to grab the test class from my branch if you work on this. You'll have to be familiar with how the TEC is created and with the .NET implementation for async if you work on this.

**Comment by jadarnel27** [comment]
I know there was recently some significant work done around parallelism.  What are the odds that #2476 fixed this?  I can't find the `assert-counts` branch mentioned in the description (I imagine it may have been deleted at some point in the last year and a half) to verify it's fixed.

**Comment by jadarnel27** [comment]
Oops. I accidentally conflated "async" and "parallelism" while reading this issue.

**Comment by mikkelbu** [comment]
@CharliePoole I could not find the branch `assert-counts`, and given that we don't have the portable build anymore and nobody else have reported issues about this (as far as I can search), I propose that we close this issue. Then we can reopen it if somebody runs into this problem.

**Comment by CharliePoole** [comment]
@mikkelbu Yes, I didn't review this one recently but that's what I would do. FYI very old issues I wrote with wording like "This was reported..." mean I just copied it from elsewhere. We didn't always have the ability to transfer issues between projects and some were even hand-copied from other sites where our project used to live. I probably typed in 50 to 100 from Launchpad alone at one time.

**Comment by mikkelbu** [comment]
Ok. I'll close it then. (sounds like a lot of work back then :) )
