### ISSUE TITLE
Improve inference of type arguments in generic test methods

### ISSUE THREAD

**Issue by michaelamaura** [nunit/nunit#150]
Currently the deduction of type arguments in NUnit is somewhat limited.

For example the following will work:

``` C#
public static ITestCaseData[] TestCasesForEqualitiy =
{
    new TestCaseData(1, 1).Returns(true), 
    new TestCaseData(1, 2).Returns(false), 
};

[Test]
[TestCaseSource("TestCasesForEqualitiy")]
public bool Equality<TElement>(TElement left, TElement right)
{
    return left.Equals(right);
}
```

While the following won't work:

``` C#
public static ITestCaseData[] TestCasesForEqualitiy =
{
    new TestCaseData(1, 1).Returns(true), 
    new TestCaseData(1, 2).Returns(false), 
};

[Test]
[TestCaseSource("TestCasesForEqualitiy")]
public bool Equality<TElement>(TElement? left, TElement? right)
{
    return left.Equals(right);
}
```

As far as I can see the modification would be local to `NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.GetTypeArgumentsForMethod(...)`.

I have coded a somewhat complex type inference logic for another project. I'll check into it and will happily supply it to NUnit project.

**Comment by CharliePoole** [comment]
This seems to be a bug with a proposed fix rather than just an "idea" I would promote it and invite PR submittal.

**Comment by ChrisMaddock** [comment]
I agree.

**Comment by ChrisMaddock** [comment]
This seems similar to #1850, in that the handling of nullable values looks to be done separately in every instance - e.g. I _think_ this would work with TestCaseAttribute, but not TestCaseData. We should see if we can push this down a level, and standardise like we want to with `params` and optional parameters.

**Comment by rprouse** [comment]
I agree and am promoting to the backlog.

**Comment by stevenaw** [comment]
Assigning this to myself to confirm if this was fixed by https://github.com/nunit/nunit/pull/4872
I'll also check if `[Values]` works and as test coverage if it does. 

If this _is_ now fixed then I suspect we can close it as the remaining `params` item is separately covered under #1850
