### ISSUE TITLE
Re running failing test

### ISSUE THREAD

**Issue by tanvirhussain** [nunit/nunit#1501]
Hi 

I am trying to use the console to re run the failed test but don't know whether I can use the --where arguments. 

Help is much appreciated.

Thanks Tanvir

**Comment by CharliePoole** [comment]
The --where argument will let you select the test by name or category. You would have to enter the named of the failed tests.

It's not possible for the console runner to rerun failed tests without entering their names because it only does one run and then exits. Our coming GUI will be able to rerun failed tests.

**Comment by tanvirhussain** [comment]
HI Charlie,

That's cool. So if I can store the failed tests in a file and run through a loop with the test names it should work?

Tanvir

**Comment by CharliePoole** [comment]
If you have the test names in a file, one per line, you can instead use the --testlist option.

**Comment by tanvirhussain** [comment]
Hi Charlie,

I have tested with the --testlist option, it seems it can read the file but not picking up the test to run. As the end result looks like this
Test Count: 0, Passed: 0, Failed: 0, Inconclusive: 0, Skipped: 0
Am I doing something wrong?

Here is the test output.

PS C:\Projects\ReRun...\....\....\bin\Debug\bin\Debug> nunit3-console.exe .\TeamGener
ator.UnitTest.dll -testlist="failedtest.txt"
NUnit Console Runner 3.2.1
Copyright (C) 2016 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.10586.0
  CLR Version: 4.0.30319.42000

Test Files
    .\TeamGenerator.UnitTest.dll

Test Filters
    Test: TestWhenAddingNonActiveTeamMemberTheTeamIsNotReadyToWork


Run Settings
    WorkDirectory: C:\Projects\ReRun...\....\....\bin\Debug
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.5.2
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    NumberOfTestWorkers: 8

Test Run Summary
  Overall result: Passed
  Test Count: 0, Passed: 0, Failed: 0, Inconclusive: 0, Skipped: 0
  Start time: 2016-05-18 10:20:04Z
    End time: 2016-05-18 10:20:04Z
    Duration: 0.055 seconds

Results (nunit3) saved as TestResult.xml
PS C:\Projects\ReRun...\....\....\bin\Debug\bin\Debug>

**Comment by CharliePoole** [comment]
The name of the selected test doesn't look like an NUnit test name at all. Run the console program against your dll with the --explore option to see what test names look like.

**Comment by tanvirhussain** [comment]
Thanks!


This is was the issue needed to save the full name not the name.

using (System.IO.StreamWriter file =
                            new System.IO.StreamWriter("failedtest.txt", true))
                    {
                        file.WriteLine(TestContext.CurrentContext.Test.FullName);
                        //file.WriteLine(TestContext.CurrentContext.Test.Name);
                    }


Great! things are working as expected.

**Comment by akshaysarode31** [comment]
> Thanks!
> 
> This is was the issue needed to save the full name not the name.
> 
> using (System.IO.StreamWriter file = new System.IO.StreamWriter("failedtest.txt", true)) { file.WriteLine(TestContext.CurrentContext.Test.FullName); //file.WriteLine(TestContext.CurrentContext.Test.Name); }
> 
> Great!

@tanvirhussain If you help me here a bit, how did you solve this issue? I am not a developer so do you mind helping me with the code
