### ISSUE TITLE
Is there a bug in "--where" parameter in console runner

### ISSUE THREAD

**Issue by pavzaj** [nunit/nunit#1502]
Hello,
I have used console runner with "--where" parameter with value "cat != FunctionalTest && cat != IntegrationTest && cat != StressTest".

The result was:
**Test Run Summary
  Overall result: Failed
  Test Count: 7986, Passed: 1971, Failed: 6014, Inconclusive: 1, Skipped: 0
    Failed Tests - Failures: 4, Errors: 6010, Invalid: 0
  Start time: 2016-05-17 14:02:14Z
    End time: 2016-05-17 14:21:15Z
    Duration: 1140,198 seconds**

Without "--where" parameter the result was:
**Test Run Summary
  Overall result: Passed
  Test Count: 1948, Passed: 1947, Failed: 0, Inconclusive: 1, Skipped: 0
  Start time: 2016-05-17 14:24:39Z
    End time: 2016-05-17 14:25:27Z
    Duration: 48,151 seconds**

How is this possible? That was the only change in parameters.

**Comment by CharliePoole** [comment]
Please post the exact command-lines and tell us what version of NUnit you are running.

**Comment by pavzaj** [comment]
It's Nunit 3.2.0.
The command is (someDll stands for many different names of dlls containing unit tests):
D:\BuildAgent\work\fc4e349a75c97b97>D:\NUnit-3.2.0\bin\nunit3-console.exe .\out\release\someDllName.dll .\dev\libs\Test\Reporting.Tests\bin\Release\someDllName.dll .\dev\out\Release\someDllName.dll .\out\release\someDllName.dll .\out\release\someDllName.dll .\out\release\someDllName.dll .\out\release\someDllName.dll .\out\release\someDllName.dll .\out\release\someDllName.dll .\out\release\someDllName.dll .\out\release\someDllName.dll .\out\release\someDllName.dll  --where="cat != FunctionalTest && cat != IntegrationTest && cat != StressTest"

**Comment by CharliePoole** [comment]
A number of bugs related to this problem were fixed in 3.2.1. If you are not able to upgrade you might try changing the where to !(...) where ... is an appropriate or expression.

**Comment by pavzaj** [comment]
Thanks. Unfortunately neither of these solutions worked.
Maybe there is something specific in my test suite.

**Comment by pavzaj** [comment]
I've returned to this topic after a while.
The tests themselves were wrtitten with Nunit framework 2.6.4, but the runner was 3.2.1.
The error was caused by executing "Explicit" test cases.
When I updated test libraries to 3.2.1 the execution was correct as no explicit test were executed.
Probably there is an error in launching old tests in new runner or in test filter translation from 3.2.1 to 2.6.4 format.

**Comment by CharliePoole** [comment]
That's important information for sure. Before closing this bug, we should examine how the filtering is being translated into NUnit 2.6.4 filters, which are different. Even if there is nothing to fix (since we are not doing new 2.x releases) we may need to document that some command-line options do not work with 2.x.

**Comment by rprouse** [comment]
I am closing old confirm issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
