### ISSUE TITLE
nunit3-console.exe -- additional -exclude option for when parsing a .Sln file.

### ISSUE THREAD

**Issue by joschmo80** [nunit/nunit#1503]
Until recently, my build servers called the x64 nunit-console.exe one at a time, in serial, with a dll or exe as an argument.  Using this approach, I was able to skip certain files, say if they were obfuscated or compiled as x86.

With the introduction of NUnit3, I investigated improving the build servers to call nunit3-console.exe once with my main .sln as an arg, to take advantage of the new parallelism.

Unfortunately, this results in an "INVALID" error when it attempts to load my obfuscated dll's.  I have tried telling nunit3-console to run on a .sln file but ignore certain .csproj refs, but have not had luck so far.  What I have tried: 
1) Adding a "where" clause to skip all tests with a certain string.
2) Running nunit3-console with /explore first, removing all obfuscated test refs, then running again.

Both 1) and 2) do not work, because NUnit3 attempts to load the obfuscated dlls BEFORE applying filters.

What I would like is something like "nunit3-console Foo.sln /exclude=Obf1.csproj,Obf2.csproj".  Or, as an alternative, something like "nunit3-console Foo.sln /excludelist=c:\exclude.txt", where c:\exclude.txt contains the name of all .csproj refs to ignore, one per line.

**Comment by rprouse** [comment]
As a workaround, would an NUnit project file work for you?

**Comment by joschmo80** [comment]
I have integrated 3.4.1, and was able to workaround my issue by relaxing obfuscation settings.

Correct me if I am wrong, but there is no way to auto-generate an NUnit project file from a VS.NET solution file.  So, it will be prone to get out of sync as VS.NET projects are added and removed.  I suppose a workaround could be to write a build-server-script which auto-generates the NUnit project file from the solution file after compilation and before unit tests -- but that would be a pain.

Having said all that, I am marking this complete, as my issue is resolved.  Thank you for such an awesome product.

**Comment by CharliePoole** [comment]
Actually, there is a way... it involves using the NUnit Project Editor,
which is unfortunately a gui and so hard to script.

However, this introduces the same limitations from which you already
suffer. The project editor creates an nunit project file that includes all
the projects in the solution... whether they have tests or not, whether
they are of a project type that nunit can deal with. So all it does is
remove the problem from nunit/nunit and add it to
nunit/nunit-project-editor!

Writing a script would have the same issue unless you have some
convention-based way to distinguish your test projects form
non-test-projects.
