### ISSUE TITLE
[Question] debug nunit tests in dnx project

### ISSUE THREAD

**Issue by bastienJS** [nunit/nunit#1504]
I have a visual studio 2015 solution with asp.net core nugets/projects with project_framework_settings: "**dnx451**".

These are my dependencies:

```
    "NUnit": "3.2.1",
    "NUnit.Runners": "3.2.1",
    "NUnit3TestAdapter": "3.0.10"
```

When I rebuild my solution then the Test Explorer window does not show any nunit annotated tests.

When will this feature be available, that I can debug my unit tests easily from within visual studio 2015?

**Comment by rprouse** [comment]
@bastienJS sorry this slipped through the cracks. NUnit doesn't currently have a test runner for DNX that works in Visual Studio. Currently you need to make your DNX tests self-executing. For more information, see [Testing .NET Core RC2 Using NUnit 3](http://www.alteridem.net/2016/05/18/testing-net-core-rc2-using-nunit-3/).

We hope to have full DNX support with the 3.4 release around the time of the RTM of .NET Core late next month.
