### ISSUE TITLE
indirect path in .nunit project file causes nunit3-console.exe 3.2.1 to crash

### ISSUE THREAD

**Issue by toomanypeople** [nunit/nunit#1505]
A project file `tests.nunit` with contents

`<NUnitProject>
  <Settings activeconfig="Release"/>
  <Config name="Release">
    <assembly path="..\MyProject.Test\bin\Release\MyProject.Test.dll"/>
  </Config>
</NUnitProject>`

run from cmd like so:
`D:\projects\MySolution\MyTestStuff>"nunit3-console.exe" tests.nunit`

causes the nunit console to crash with this error message: 

_Could not load file or assembly 'nunit.framework' or one of its dependencies. The system cannot find the file specified._

Moving everything back a directory and updating the tests.nunit like so causes the test to run normally.  The crash seems to be caused by the "..\" in the project file path.

`<assembly path="MyProject.Test\bin\Release\MyProject.Test.dll"/>`

Doing this from the command-line also works correctly:

`D:\projects\MySolution\MyTestStuff>"nunit3-console.exe" ..\MyProject.Test\bin\Release\MyProject.Test.dll`

**Comment by CharliePoole** [comment]
In the first (failing) command, the appease is set to the location of the project file by default. This makes it impossible to load assemblies that are not in or below that directory.

Options...

1. Move the project file into a directory that encloses all the assemblies to be loaded.

2. Set the soonest explicitly in the project file.

**Comment by toomanypeople** [comment]
Charlie, would you mind explaining what you mean by 'appease' and 'soonest'?  Just looking at the .nunit config file example in the docs I can't figure out what you're talking about.

`https://github.com/nunit/docs/wiki/NUnit-Test-Projects`

**Comment by CharliePoole** [comment]
I hate auto-correct! Appbase in both cases.

**Comment by toomanypeople** [comment]
Heh, thanks.  That makes _much_ more sense.
