### ISSUE TITLE
Nunit engine tools do not exit after test run

### ISSUE THREAD

**Issue by BenChand** [nunit/nunit#1511]
Hello,

I have a basic console application that is trying to use Nunit engine to run some tests from a compiled class library and output their results. My issue is that the actual console window refuses to close after the program finishes. I have attached the code I was using to achieve this:

```csharp
using NUnit.Engine;
using System;

namespace NunitEngineTest
{
    public class Program
    {
        // Simple listener that does nothing useful
        public class Listener : ITestEventListener
        {
            public void OnTestEvent(string report)
            {
                Console.WriteLine(report + "\r\n");
            }
        }

        //Fields used to run tests:
        private static ITestEngine _Engine;
        private static TestPackage _Package;
        private static ITestRunner _Runner;

        static void Main(string[] args)
        {
            // Initialise a new nunit-agent:
            _Engine = TestEngineActivator.CreateInstance();
            _Package = new TestPackage(@"ExampleTestSuite.dll");
            _Runner = _Engine.GetRunner(_Package);

            // Run all discovered tests:
            _Runner.Run(new Listener(), TestFilter.Empty);
        }
    }
}

```

The end result is the test result xml being written to a console that never closes unless done manually:

![image](https://cloud.githubusercontent.com/assets/3618457/15454218/f4f271de-2029-11e6-9ccf-ea412f6d43fb.png)

Is there a way to force the console window to close?

Thanks

**Comment by CharliePoole** [comment]
Are you running this from VS or from the command-line? When you run from VS, the window is generally kept open so you can see the results. When you run from a command-line, the program exits but the command-line window stays open.

**Comment by BenChand** [comment]
I was running it from Visual Studio. Just ran it from the command line and the process closed fine. I was trying to integrate Nunit Engine into an ASP web service the other day and noticed that the nunit-agent process would not close down with the rest of the solution meaning I had to terminate the process in Task Manager before re-running the solution. I was hoping re-creating the issue with a simple command line program would help illustrate this but I was mistaken

**Comment by CharliePoole** [comment]
Since the agent may be used by a gui, it doesn't exit after the test runs. It will exit when the test is unloaded, however.
