### ISSUE TITLE
Error while running nunit with nunit3-console program from dotnet enviromnet.

### ISSUE THREAD

**Issue by RajuIpl** [nunit/nunit#1515]
When we use console program to run the tests its running perfectly.

`nunit3-console path to dll`

From vs program i tried to run the same but am getting the folllowing error
"Either assembly contains no tests or proper test driver has not been found."
code is 
```
string path = @"path to dll";
NUnit.ConsoleRunner.Program.Main(new[] { path });
```

**Comment by CharliePoole** [comment]
This is not a normal use of the console program, so it would be better to discuss in a forum, where many users can give you advice, rather than filing a problem report. However, since it's here, let's try to come up with an answer.

In order to execute the console runner Main, you must have referenced it. Did you set local copy to true? Is it referenced from your tests or from some other assembly?

What other NUnit assembly references have you referenced in this way?

What is your on-disk layout. That is, how do the location of your main program, your tests and the nunit assemblies relate to one another?

**Comment by RajuIpl** [comment]
In my console application where am calling console runner main i referenced the nunit3-console.exe and my console program invoking it perfectly with the path given.

In my test project i referenced the latest nunit binaries 3.2.1 version. My test call is like
`namespace FirstAppiumScript
{
    [TestFixture]
    public class WhatsAppTest
    {
        AppiumDriver<IWebElement> driver;
        string statusText = "Testing";

        [SetUp]
        public void Initialize()
        {
            Console.WriteLine("Appium Script execution starting...");

            DesiredCapabilities caps = new DesiredCapabilities();
            caps.SetCapability("deviceName", "Xperia Z1");
            caps.SetCapability("platformVersion", "5.1.1");
            caps.SetCapability("platformName", "Android");

            caps.SetCapability("appPackage", "com.whatsapp");
            caps.SetCapability("appActivity", "com.whatsapp.Main");
            driver = new AndroidDriver<IWebElement>(new Uri("http://127.0.0.1:4723/wd/hub"), caps);
            //System.Environment.GetEnvironmentVariable("Appium")
            driver.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(20));
            Console.WriteLine("Appium driver Initialized");
        }

        [Test]
        public void ChangeWhatsAppStatus()
        {
            Console.WriteLine("Test - ChangeWhatsAppStatus Execution Started");

            //Click on more options
            driver.FindElement(By.Name("More options")).Click();
            //Select Status and click
            driver.FindElement(By.Name("Status")).Click();
            //Click on status edit button com.whatsapp:id/round_more_btn
            driver.FindElement(By.Id("com.whatsapp:id/round_more_btn")).Click();
            //Select input - clear and change text com.whatsapp:id/edit_text
            driver.FindElement(By.Id("com.whatsapp:id/edit_text")).Clear();
            driver.FindElement(By.Id("com.whatsapp:id/edit_text")).SendKeys(statusText + " - ");
            //Click on emoji icon com.whatsapp:id/emoji_btn
            driver.FindElement(By.Id("com.whatsapp:id/emoji_btn")).Click();
            //Click on people icon com.whatsapp:id/emoji_people_btn
            driver.FindElement(By.Id("com.whatsapp:id/emoji_people_btn")).Click();
            //Select emoji android:id/list/View[1]/View[1]
            driver.FindElement(By.XPath("//android.view.View[@index='0']/android.view.View[@index='0']")).Click();
            //Click Ok com.whatsapp:id/ok_btn
            driver.FindElement(By.Id("com.whatsapp:id/ok_btn")).Click();
            //Go Back android.widget.ImageButton
            driver.FindElement(By.ClassName("android.widget.ImageButton")).Click();
        }

        [TearDown]
        public void ClearTest()
        {
            driver.Quit();
        }
    }
}`

**Comment by CharliePoole** [comment]
Still some unanswered questions:

 * Did you use copy local or are you referencing the console runner where it is installed?
 * Are the other required assemblies used by console runner present in the same directory or is the runner having to find them somewhere - which it will do, but it may find an older engine version.
 * What assemblies are in your output directory?

And a new question: Is the console runner producing any output? Can you post it?

**Comment by RajuIpl** [comment]
referencing from where the console runner is installed. also referenced nunit.engine and nunit.engine.tools packages from nuget package manager and in the outout directory i can see the following assemblies.

- nunit.engine
- nunit.engine.api
- nunit.framework
- nunit3-console.exe
- nunit-agent.exe
- nunit-agent-x86.exe
- NunitConsoleRunner.exe
- TestResult.xml

**Comment by RajuIpl** [comment]
I got the error nunit3-console.exe is not able to handle the tests which are created with lower version nunit.

When i create the tests using 3.2.1 in visual studio and trying to run these tests using nunit console runner then its working as expected.
When i create the tests using 2.6.4 in visual studio and trying to run these tests using nunit console runner then am experiencing this problem.

But i have one question how come the console program is handling all the versions i.e
using command prompt if i run `nunit3-console.exe "path to dll"` then regardless of the nunit version which the tests are created are running as expected.

**Comment by rprouse** [comment]
@RajuIpl if you are just trying to create self executing tests, it would be much better to use the NUnitLite package which is designed for this.  It would be helpful to know more about why you are trying to do what you are doing.

To create an NUnitLite test, add the NuGet package and change your main to something like this;

```C#
        public static int Main(string[] args)
        {
            return new AutoRun(typeof(Program).GetTypeInfo().Assembly)
                .Execute(args, new ExtendedTextWrapper(Console.Out), Console.In);
        }
```

**Comment by CharliePoole** [comment]
You are running with a bare copy of the engine, and no extensions. The engine contains a driver for running V3 tests but V2 support is provided by an extension.

Basically, installing NUnit and it's extensions in proper relation to one another is a bit more complex than either Visual Studio or Nuget can handle without help.

The nunit.engine.tools package is an experimental package that may eventually replace the nunit.engine package. It installs the same assemblies, but in a different way. You should use one package or the other, not both. The nunit.engine package gives you the required references and puts the assemblies in your output directory, so that's probably what you want.

To get the v2 driver, you would need to install the nunit.v2.driver package.

An alternative to all these packages would be to install the nunit.runners package, which includes the console runner and a number of standard extensions. This is a tool package, which means that it is not referenced by your code and therefore not copied to the output directory. You could do the referencing manually, however.

**Comment by CharliePoole** [comment]
Following up on @rprouse 's comment... if you decide to use nunitlite, it should be used **in place of** all the other packages you currently use.

Rob's question is a good one, however. I've been assuming you have some valid reason for doing what you are doing. :-) Do you?

**Comment by RajuIpl** [comment]
I want to achieve the following 
though a program i want to run any Appium test suite which is written in c# and while running the suite i have to capture the execution log to report certain parameters like start time end time if test case is failure then the reason for that, the error information etc..

Charlie specified the recent way of running tests using NUnit.Engine API in some other post of mine. I am going through the documentation of it and i will try to create a sample.

I dont know about NUnitlite i have to read about this and try.

**Comment by CharliePoole** [comment]
Why do you need to do this through a program? What do you want to achieve that can't be done by simply running the NUnit runner itself?

**Comment by RajuIpl** [comment]
wants to handle a automated process where the users upload their script then i will build and run through a service then create a report depending upon the execution.

**Comment by CharliePoole** [comment]
One option is to simply run with the NUnit console runner and then produce reports by reading the output XML file.

However, if you want to do it programmatically, I think you need to go down a level from the console runner and use the engine API.

**Comment by RajuIpl** [comment]
I tried an example using Engine services and working as expected in case of nunit version 3.2.1 but the same error while running the tests created by a lower version of nunit (2.6.4).
Here is the sample code:

       `static void Main(string[] args)
         {
            // set up the options
            string path = @"Path to dll";
            
            TestPackage package = new TestPackage(path);
            package.AddSetting("WorkDirectory", Environment.CurrentDirectory);

            // prepare the engine
            ITestEngine engine = TestEngineActivator.CreateInstance();
            var _filterService = engine.Services.GetService<ITestFilterService>();
            ITestFilterBuilder builder = _filterService.GetTestFilterBuilder();
            TestFilter emptyFilter = builder.GetFilter();

            using (ITestRunner runner = engine.GetRunner(package))
            {
                // execute the tests            
                XmlNode result = runner.Run(null, emptyFilter);
                Console.WriteLine(result.InnerXml);
                Console.ReadLine();
            }
        }`

referred latest Nunit test engine package(3.2.1) to my console program through nuget package manager.

**Comment by ChrisMaddock** [comment]
I think you may need the v2 framework driver extension - I don't think it's included with the default engine nuget package.

https://www.nuget.org/packages/NUnit.Extension.NUnitV2Driver/

**Comment by RajuIpl** [comment]
But how come  3.2.1 is not able to execute tests which are created by 2.6.4. Always latest versions should support the lower version.

**Comment by ChrisMaddock** [comment]
It should do, with the NUnit V2 Driver nuget package.

I believe the NUnit Engine nuget package contains just the core test-running functionality. Running NUnit 2 tests is implemented as a separate extension, you should just need to add the relvent nuget package, and the engine will be able to find it and run the v2 tests.

**Comment by RajuIpl** [comment]
@ChrisMaddock  We cant use both versions in a single program. Am writing service for which i will pass the dll to execute the scripts in it. How can we know the scripts are created with 2.6.4 OR 3.2.1?

**Comment by ChrisMaddock** [comment]
The engine should be able to work that out based on the version of the nunit.framework package which is referenced. The extension allows NUnit 2 tests to be ran additionally to NUnit 3 tests, not 'instead of'.

**Comment by rprouse** [comment]
@Rajulpl, @ChrisMaddock is correct, the engine will inspect your tests to determine if you use NUnit 2.x or 3.x and run them with the correct driver. The driver for NUnit 3 is built in, but the driver for NUnit 2 is not, so you must add it to your project using NuGet and include it in the `.addins` file.

If you look at an install of NUnit in the console directory, you can see the addin file and the addins directory. It also contains addins for writing out test results in the v2 format, loading tests from project files, etc.

I am going to close this since it isn't an issue, but feel free to continue asking questions and we will do our best to answer.

**Comment by RajuIpl** [comment]
Ok, One more question related to Nunit Engine API. Is there any way of getting a callback when a test started and ended execution?

**Comment by rprouse** [comment]
@RajuIpl to get callbacks, implement an `ITestEventListener` and pass it into the `Run` method of the `ITestRunner` that gets returned from the API and you are using to run your tests. Your example code above is currently passing in `null`.

**Comment by CharliePoole** [comment]
When you run tests using the API, you pass in an object that implements ITestListener. This listener receives all the callbacks from your test in a single method that takes an XML-formatted string as an argument. It's up to you to distinguish the different callbacks and act accordingly.

You may receive any of the following events:

```
   <start-run ...>
   <start-suite ...>
   <start-test ...>
   <test-case ...>
   <test-suite ...>
   <test-run ...>
```

You can check the docs at https://github.com/nunit/docs/wiki/XML-Formats for more info or just watch what you receive and act accordingly. :-)

**Comment by CharliePoole** [comment]
@rprouse I'm surprised that null even works!!!

**Comment by RajuIpl** [comment]
Thanks you for your support to resolve many issues with NUnit and its been great learning to me talking to you people. 

Great news to hear that i can use the listener. I went through the documentation but unable to find about itestlistener. Can you point me to a location where i can find the sample usage of itestlistener?

**Comment by CharliePoole** [comment]
Surprisingly, I can't find docs for ITestListener either! The best docs for what you are working on can be found on these pages...

 * https://github.com/nunit/docs/wiki/Test-Engine-API-Spec
 * https://github.com/nunit/docs/wiki/XML-Formats

Lacking a complete description of ITestEventListener (which I will try to add) you should look at some of our own code that implements it...

 * https://github.com/nunit/nunit/blob/master/src/NUnitConsole/nunit3-console/TestEventHandler.cs
 * https://github.com/nunit/nunit/blob/master/src/NUnitEngine/Addins/teamcity-event-listener/TeamCityEventListener.cs

In reviewing the docs, be sure to look at developer docs, which are more suited to what you are doing than the user docs.
