### ISSUE TITLE
TeamCity Event Listener references non-existent attribute

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1523]
The TeamCityEventListener references a `parentid` attribute in the NUnit code. There is no such attribute. There had been an earlier request for us to add such an attribute, which we turned down.

@NikolayPianikov Unfortunately, I'm working in this code and could remove the reference if that's the right thing to do. I don't have your email, so the only way I know to ask you about this is via a bug report! Your unit tests simulate the call to the listener as if NUnit contained such an attribute, so they are basically invalid tests. Since I have already changed a number of things in the code in order to make it compatible with NUnitLite, I'd like some guidance about how you want to handle this problem.

**Comment by NikolayPianikov** [comment]
@CharliePoole  see class TestProgressReporter line 66 and 92 (Support TC service messages #684). We use it to be able to define the hierarchy of tests/suites when results from tests are produced from several processes/threads simultaneously.

**Comment by CharliePoole** [comment]
@NikolayPianikov I know that code, but I thought that test.Parent was always null in this situation. However, it is not - I checked in debug. One small issue: the code creates a parentId attribute with an empty value if Parent is null. That's not our standard - we always eliminate optional attributes if there is no value. However, there's no point to changing it now. I'll close this.
