### ISSUE TITLE
Handling of TeamCity messages is different between the engine and nunitlite

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1524]
We need to examine whether the differences are OK before making changes.The main one is that there is no flowid used in nunitlite. There are other minor differences.

Once we determine what should be the same versus different, we may be able to implement some common code.

@NikolayPianikov We could use some comments from you here!

**Comment by CharliePoole** [comment]
@NikolayPianikov After looking more closely at the differences, the biggest is that there is no flowid in nunitlite. Thinking about it, I'm still not sure why you need flowid. I understand why it was needed when NUnit failed to attach any test id to each output, but now there is no need for you to make a logical deduction about which test produced output because it is all tagged with the name and id of the test.

So maybe it's the simple approach in NUnitLite that is more correct now.

**Comment by NikolayPianikov** [comment]
My comments about flowId: we should have real unique id's to distinguish tests in the specific period of time. The test's name (or id) is not unique for example when we run tests for similar assemblies (release/debug or different platforms .net 1.1/2/4 or something like) and we can not rely in these id's. As we discussed, flowId is required in cases when test tool produces results from different tests simultaneously. And the pair testId and flowId can play a role of unique id (as I said before, in the specific period of time only). Also we should have ability to see hierarchy of tests in this case.
Bu if nunitlite does not produce results simultaneously for several tests flowId is not required.

**Comment by CharliePoole** [comment]
NUnitLite runs a single assembly but may run with multiple threads. Each test has a separate id. Do you need flowid in that situation?

In general, whether using nunitlite or the engine, every test has a unique id. The only way duplicate ids would be produced is if you ran two entirely different copies of NUnit, which we definitely don't recommend for several reasons. NUnit expects only one copy of the engine to be active in a primary role at one time.

**Comment by NikolayPianikov** [comment]
FlowId is needed, because we should correctly identify start and finish of a test in the case of intersection in time. FlowId could be just a test id. And parentId is not required because we have only one assembly.

**Comment by CharliePoole** [comment]
That makes sense to me. In fact, I don't yet see why parentid is needed with multiple assemblies. If flowid is always the id of the test, then that's a unique value even across multiple assemblies.

**Comment by NikolayPianikov** [comment]
For example:

start suite abc.dll
start suite xyz.dll
start test aaa
start test xxx
finish test aaa
finish test xxx
finish suite abc.dll
finish suite xyz.dll

How we can find a relation between a test and an assembly?

**Comment by CharliePoole** [comment]
The id is coded. The first part indicates the assembly.

**Comment by NikolayPianikov** [comment]
I am not sure I understand. A listener gets the message like <start-suite id="0-1019" parentId="0-1018" name="dotNet40NUnitTests" fullname="dotNet40NUnitTests"/> for test. The "parentId" attribute is an only way to correlate this message to the "start-suite" message like <start-suite id="0-1018" parentId="" name="dotNet40NUnitTests.dll" fullname="c:\mydir\dotNet40NUnitTests.dll"/>.

**Comment by CharliePoole** [comment]
You asked about finding the assembly, not suites in general. All ids that start "0-1" are in the same assembly. Other test fixtures and suites are a different matter. I was not aware you needed that information. Are you trying to reconstruct the entire tree from the run messages?

If you are, the most certain way is to get result of loading the assembly. However, because you are running through the console runner instead of using the engine API, that's not available to you.

So... __if__ you need the entire test hierarchy - assembly, namespace, fixture, test cases - then you do need the parent id. If you do need it, I'd be interested to know how you use it. Getting it this way will probably miss some ignored or otherwise skipped items, so you should especially check for that.

BTW - in case you didn't know - the parentId is only present in the event messages. It's not in the final XML, where it would be redundant.

**Comment by CharliePoole** [comment]
Unfortunately, I didn't merge this before creating the new repo - that would have been simple!

I guess at this point, the best way is for you to clone the new repo and create a branch and PR with identical code. The code for the extension right now is exactly the same in both repos.

Since you have write access to the new repo, you can simply clone it and create a branch - no need to fork unless you prefer to do it that way.  In the usual way for NUnit, merging to master in the new repo will require review by one other committer.

I'll move the related issues into the new repo as well.

**Comment by CharliePoole** [comment]
Issue moved to [nunit/teamcity-event-listener #1](https://github.com/nunit/teamcity-event-listener/issues/1) via [**ZenHub**](https://www.zenhub.com/)
