### ISSUE TITLE
Cleanup #1476

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1532]
#1476 removed support for synchronous events in the event queue, but left a few remnants behind.  This results in some compilation warnings, but no actual problem.

I will make a PR which cleans up these remnants.

**Comment by oznetmaster** [comment]
I just noticed I had this assigned to me :(

I was looking at a problem I created in my build, and discovered that FrameworkPackageSettings.SynchronousEvents was still defined, and was processed in NUnitTestAssemblyRunner.

However, there appears to be no way to ever set that settting, nor does there appear to be a test for it.

Should this be removed?

The reason I was looking at it is that I actually wanted to use it to find a specific problem!

**Comment by CharliePoole** [comment]
See PR #889 and issue #830.

Essentially, it's here specifically because NCrunch needed to have it. We probably should have added a comment to avoid confusion.

**Comment by Parshudar** [comment]
Hi. I'm new to the contributing world and I notice this is marked as a Good first issue and I'd like to help with the Cleanup if possible.

**Comment by rprouse** [comment]
@Parshudar you are welcome to submit a PR for this if you can figure out which code @oznetmaster is talking about. This may be obvious, I haven't looked, but it might be difficult to identify the code that needs to be cleaned up after all this time...

**Comment by mikkelbu** [comment]
I'm closing this issue as it is not clear what needs to be done. If we figure this out we can reopen the issue.
