### ISSUE TITLE
NUnit 3.2.1 (3.2.0) - converting output using "format=nunit2" fails on Windows Server 2012 R2

### ISSUE THREAD

**Issue by sivanov-hill30** [nunit/nunit#1535]
There seems to be a bug(?!) on Windows Server 2012 R2. We have a build setup on mentioned OS and builds started to fail as we tried to convert output to nunit2 format so that GO CD would understand it. Builds started to fail and investigation showed that command line that worked perfectly on DEV machine with Win7 x64 started to fail on the build machine. Could you look into the issue? 

Command line 
c:\temp\NUnit.ConsoleRunner.3.2.1\tools\nunit3-console.exe TestLibrary.dll --result=smokeoutput.xml;format=nunit2 --test=MyLibrary.MyClass.TestMethod

**Windows Server 2012 R2 output**
NUnit Console Runner 3.2.1_
Copyright (C) 2016 Charlie Poole

Unknown result format: nunit2

**Windows7 x64 output:** 
...
Results (nunit2) saved as smokeoutput.xml

Prerequisites:
- NUnit binaries are copied between 2 systems, they are identical
- Command line is identical on both systems (only directory names may vary)

Reproduced on versions: 3.2.0, 3.2.1

**Comment by CharliePoole** [comment]
The NUnit 2 output format is supported by an extension. It seems pretty clear that you have the extension installed on the dev machine ut not on the build machine. The message you see is the one you get when asking for a format that is not installed on your machine.

What is in the addins directory of your build machine? What is contained in the .addins file in the engine directory?

**Comment by sivanov-hill30** [comment]
I didn't realize there has to be an addin for this functionality. On build machine tests were run using an executable contained in the "packages" folder, there were no addins. After an investigation I copied required plugins and nunit.engine.addins file and that solved the issue.
Clearly not a bug :)

Thank you!
