### ISSUE TITLE
--Explore option does not show full parameter

### ISSUE THREAD

**Issue by GitHubAre** [nunit/nunit#1537]
Hello,

Our team is using NUnit for a very long time and now we are planning to upgrade to version 3.2.1, however we are facing an issue:

I am using: "C:\PathToAssembly.dll" --explore="D:\ExploreOutput.xml";format=nunit3
To create .xml with list of all test cases from a given assembly.
My team is using parameters in the test case name, but if parameter is too long, it is trimmed at the end by "...".
Which results into:
FUN_GRD_ACPT.VCA.E2E.VCA_Scenarios(Native).Scn_VCSelectMACKey_00_032(&quot;Application&quot;,&quot;01 02 03 04 05 06 07 08 09 0A 0B 0C 0...&quot;)
Is there some workaround for this?
Thank you!

**Comment by CharliePoole** [comment]
By default, tests are named using a naming pattern of {m}{a:40}, where {m} represents the method name and {a:40} represents the set of args in parentheses, with strings truncated to a max length of 40.

You can change this on each individual test case by setting the name to something else - for example {m}{a:100} See https://github.com/nunit/docs/wiki/Generation-of-Test-Names-Spec for more detailed information.

Note that you can only do this on test cases and only for one test case at a time. We previously floated the idea of having some global setting (e.g.: command-line option) that would control the format and/or truncation level, but got no response from users on it.

**Comment by GitHubAre** [comment]
Thank you very much for quick response! I will communicate this to our test engineers.
