### ISSUE TITLE
TC wild cards causeing: System.IO.FileNotFoundException : Could not load file or assembly

### ISSUE THREAD

**Issue by Ashtonian** [nunit/nunit#1539]
I'm not sure why this is happening. Building in TC with the TC plugin and NUnit-2.6.4.

Repo Structure:
```
.sln
/source/csproj
/source/testcsproj
packages
```

The testcsproj references the csproj above. Before the NUnit step MSBUILD successfully runs both projects and creates the appropriate build artifacts. Both of them build to ```bin\{Debug|Release}\```. The test runner in teamcity "Run tests from:" setting is ```**\*Tests.dll``` which finds the appropriate test assemblies accordingly. It seems to build some of the tests but as soon as any tests rquire a 3rd party nuget package or the related project it fails with ```System.IO.FileNotFoundException : Could not load file or assembly.``` This is a bit weird because all the required .dlls are in the output folder with the .dll folder.

**Comment by Ashtonian** [comment]
after some experimentation changing  ```**\*Tests.dll``` to ```**\\*Tests\bin\\**\*Tests.dll``` fixed the problem. Would someone be able to explain this to me? Also does anyone know where/who maintains the TC-plugin?

**Comment by CharliePoole** [comment]
I'm not sure what you mean by "TC-plugin" but it's not an nunit thing at least. NUnit has nothing to do with interpreting the wildcards. They are used by TC to decide what assemblies to pass to NUnit.

**Comment by CharliePoole** [comment]
Since this doesn't seem to have anything to do with NUnit, I'm closing this. If new information comes, we'll be glad to reopen it.

**Comment by Ashtonian** [comment]
Just for clarification - and in case anyone else comes across this. The TC-Plugin i'm referring to is the NUnit Test runner which is maintained by and owned Jetbrains. This particular issue has been an issue since 2012 initially documented [here](https://youtrack.jetbrains.com/issue/TW-24220) and opened  [here](https://youtrack.jetbrains.com/issue/TW-45533).

**Comment by NikolayPianikov** [comment]
I am responsible for it in TC. But I am on vacation now. I will try to help after 2 weeks.
