### ISSUE TITLE
Remove old .NET Core Projects

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#1540]
Not sure why they are still in the repo, but there are still a couple of unused .NET Core projects in the source tree.

https://github.com/nunit/nunit/tree/master/src/NUnitFramework/framework/nunit.framework-netcore

and 

https://github.com/nunit/nunit/tree/master/src/NUnitFramework/tests/nunit.framework.tests-netcore

**Comment by CharliePoole** [comment]
I didn't know we ever had them! Anyway, if we wanted to do a .NET Core framework build, we wouldn't create a new folder - at least not according to our current standard setup.

**Comment by rprouse** [comment]
A new directory was required for .NET Core. It conflicts with `msbuild` style projects causing them to not build because the `project.json` file is not correct for the other projects. .NET Core is going to go back to `msbuild` in the near future though, so we should be able to create a .NET Core framework to our standard then.

In the meantime, I will clean this up. It confused one of the Microsoft developers that are helping me with the .NET Core work.

**Comment by rprouse** [comment]
All that said, the `project.json` style was pretty cool. It would have allowed us to target nearly all of our current frameworks with one project that builds them all. You just added new frameworks like `net45` and `net20` to the `project.json`. It didn't work on Linux at the time and wasn't quite ready for prime-time when I was playing with it though.

Hopefully when they finally release, there will be something similar that we can use. It would be great to reduce all of our framework projects down.

**Comment by CharliePoole** [comment]
I've probably said this before - It's a maxim I use when coaching teams... You have to create duplication before you can remove it. :-)

**Comment by BrainCrumbz** [comment]
Not sure, but just in case: isn't [this line](https://github.com/nunit/nunit/blob/cb95ec2d23f8929f8aa545d5c12afa2248f4ffea/global.json#L3) in `global.json` also a leftover from previous .NET Core projects?

HTH, cheers
