### ISSUE TITLE
NUnitEqualityComparer.GetEquatableGenericArguments should explicitly order arguments

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#1546]
`NUnitEqualityComparer.GetEquatableGenericArguments(...)` returns arguments in order from the base class up to the derived class, but that behaviour is not guaranteed, it just happens to work. This may not work on all platforms.

See the discussion in #1544 for more information.

**Comment by lundmikkel** [comment]
@rprouse [I have added a comment to the original pull request.](https://github.com/nunit/nunit/pull/1544#discussion_r65989843) I don't think there is a problem as long as we only have one "chain" of inheritance. It could be inconclusive which interface was used, if there are more unrelated interfaces as described in my comment.

**Comment by stevenaw** [comment]
I've spent some time looking at the Equatables comparer recently, and am familiar with this issue. Could it please be assigned to me?
