### ISSUE TITLE
Create separate assembly for System.Linq compatibility classes

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1547]
Our .NET 2.0 build includes mono classes from System.Linq namespace. It's not the full set AFAIK but it helps us write cleaner, more consistent code across the various builds. 

These classes are not referenced anywhere else right now, but they would be useful in the engine, which has to be built for 2.0 and possibly in the adapter, which we changed from 2.0 to 3.5 in order to use System.Linq.

We should investigate putting these in a separate assembly and repository and creating a package. It would essentially be a package for our own use, although others could download it. Once it has everything we want in it, I would  expect it to remain unchanged for long periods, however, we would want to version the packages just in case.

@nunit/core-team What do you think?

**Comment by rprouse** [comment]
I don't think it is needed for the adapter. The earliest supported version of Visual Studio ships with and I believe runs internally 4.5. De we even have the ability to running the adapter in .NET 2.0.

If we don't use it in the adapter, then I guess that leaves the engine, console and 2.0 version of the framework. It would make sense to have a separate assembly for those. Maybe pull in the other 2.0 specific compatibility classes like the attribute for extension methods and call it `nunit.compatibility.dll`?

**Comment by CharliePoole** [comment]
The adapter has to run under the entire you are targeting for the tests,
since it can only run tests in process.
On Jun 7, 2016 6:43 PM, "Rob Prouse" <notifications@github.com> wrote:

I don't think it is needed for the adapter. The earliest supported version
of Visual Studio ships with and I believe runs internally 4.5. De we even
have the ability to running the adapter in .NET 2.0.

If we don't use it in the adapter, then I guess that leaves the engine,
console and 2.0 version of the framework. It would make sense to have a
separate assembly for those. Maybe pull in the other 2.0 specific
compatibility classes like the attribute for extension methods and call it
nunit.compatibility.dll?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nunit/nunit/issues/1547#issuecomment-224464353>, or mute
the thread
<https://github.com/notifications/unsubscribe/ACjfhWgvtMT6h1nPOz13BbOySBr_wIEHks5qJh4tgaJpZM4IvK7D>
.

**Comment by CharliePoole** [comment]
I'm promoting this to a feature and I'll give it a shot.

It strikes me that each of our components needs to have some developer doc that explains why it targets what it targets. For example, nunit3-console targets net-2.0 so people can run it on a test machine that has only net-2.0. That way, when discussions come up about re-targetting, folks can at least be addressing the motivations that went into the older decision.

Anyway, I see this potentially being used the net-2.0 framework build, the engine and only maybe the vs adapters. They currently target 3.5. Time permitting, someone could experiment with how VS sandboxes the adapter if you say you want to test under 2.0. If it breaks, then this could be a solution.
