### ISSUE TITLE
Changing default behavior for generating test case names

### ISSUE THREAD

**Issue by GitHubAre** [nunit/nunit#1549]
Hello,

Last week I have created issue: https://github.com/nunit/nunit/issues/1537#issuecomment-222730218
It is bigger issue for us, since we have more than ten thousand test cases spread across different visual studio projects. It would be easier for us to actually change the code of NUnit to simply not trim the test case name.
Could this feature be considered in next release?
OR
Can you please point out, which file we will need to change inside the NUnit source code, so that we would "hard code" the maximum value for test case arguments ourselves?

**Comment by CharliePoole** [comment]
Yes, as noted in my comment on the earlier issue, it could be useful to add a way of setting the default. Someone merely needs to start the discussion.

Design issues:

1. Do we want to be able to change the truncation length only or more generally the template itself?

2. Should this be a command-line option? A file setting? Both?

**Comment by GitHubAre** [comment]
Our team as an example is not changing the default behavior of test case name generation. 
Therefore this "trimming" of arguments larger than 40 characters is undesired behavior. It would make sense that by default there is no limitation in characters (arguments are expanded to its full length), but user can limit it by using the current approach or by setting it globally from command line.

**Comment by oznetmaster** [comment]
I am really confused by all of this :(

I thought the --name-format option was implemented to solve problems like this?

**Comment by GitHubAre** [comment]
This option can specify the format e.g. Nunit 2 or Nunit 3 format, but it does not affect arguments that are passed to the test method.

**Comment by oznetmaster** [comment]
@CharliePoole  wrote in #912:

"The spec describes a console option --name-format, allowing the user to change the default template. I threw that in but I'm not sure if we should really have it."

**Comment by CharliePoole** [comment]
@Oznetmaster that's what I was referring to as the idea previously floated but never implemented.

I put that into the spec but it had no takers and was therefore not implemented. It would certainly be an option in this case.

**Comment by oznetmaster** [comment]
It seems like the perfect solution.

**Comment by CharliePoole** [comment]
@GitHubAre doesn't seem to think we should go this way but should change the default to no truncation.

But it was precisely because of errors in the adapter that we introduced it. Visual Studio enforces a strict limit on the overall length of a test name and won't truncate them itself. If we weren't passing the names to VS, then a default of no truncation would be possible. There is a possibility of doing that but not in the short term. I'll write it up later today.


Meanwhile, the only thing we can reasonably expect to do for 3.4 is a setting, a command-line option or a change to the default.

I'd like to help these folks out but first need feedback. Thanks for your.

**Comment by CharliePoole** [comment]
Here's a whole new thought!!!

What if we make the default template used in the framework non-truncating, but provide a setting (PackageSetting) to change the template. In that way, the runners that need a different default (like the VS adapter) could simply provide it as a setting. 

It would be up to the runner whether or not to expose that default as something users could change. The console runner might (or might not) have an option. The adapter might (or might not) allow a setting in the `.runsettings` file. 

@nunit/core-team What do you think?

**Comment by rprouse** [comment]
@CharliePoole, that sounds like a good alternative. It is really only GUI
runners that may want truncated tests right?

**Comment by CharliePoole** [comment]
Well, our old gui runner never required it, although it could theoretically lead to some very hard-to-read entries in the tree. But I think giving the control to (or through) the particular runner makes sense.

So...

1. I'll change the default in the framework to `{m}{a}` changing the meaning of `{a}` to be no truncation.

2. I'll give the console an option to set the template, i.e. `--name-format` passing the value in with the test package if provided.

3. I'll change the adapter to pass in `{m}{a:40}` - hardcoded - so it keeps working as it now does.

**Comment by CharliePoole** [comment]
@GitHubAre It seems like the above should work for your team, but please comment if not.

**Comment by GitHubAre** [comment]
Perfect, that would be great solution for us.
Thank you so much for this quick analysis.
Because of this we are delaying upgrade from 2.6.4 to 3.2.1, if you implement this feature, it will be in 3.4 release?

**Comment by CharliePoole** [comment]
I expect so... I recently wrote - about a different issue - "This is a pretty simple change and should be easy to get done. " I apparently jinxed myself, so I'm not doing that again. 

However, this does look pretty simple to implement, provided there are no unintended consequences of changing the default.

**Comment by CharliePoole** [comment]
@GitHubAre It seems like the above should work for your team, but please comment if not.

**Comment by CharliePoole** [comment]
PRs for both NUnit and the NUnit 3 adapter are ready for review. As a minor change, I used --test-name-format as the name of the console option. It's less ambiguous and it's length seems fine do an option we don't expect folks to use frequently.
