### ISSUE TITLE
Allow ordering tests to be done in multiple properties

### ISSUE THREAD

**Issue by labilbe** [nunit/nunit#1553]
On SQL queries, I tend to order by multiple columns and not only one.
I would like NUnit handles this case and allows unit testing not only on one property but on multiple properties.

The general idea is to be able to do the following:

`var list = new List<Tuple<string, string>>`
`{`
`    new Tuple<string, string>("aaaa", "bbbb"),`
`    new Tuple<string, string>("bbbb", "aaaa"),`
`    new Tuple<string, string>("aaaa", "cccc"),`
`    new Tuple<string, string>("cccc", "bbbb")`
`};`
`var ordered = list.OrderBy(p => p.Item1).ThenBy(p => p.Item2);`

`Assert.That(ordered, Is.Ordered.By("Item1").By("Item2"));`
or
`Assert.That(ordered, Is.Ordered.By("Item1").And.By("Item2"));`
or
`Assert.That(ordered, Is.Ordered.By("Item1").ThenBy("Item2"));`

I was looking for this feature on [SO](http://stackoverflow.com/questions/37676739/how-to-check-list-orders-further-properties-with-nunit/) and Charlie Poole sent me here.

Thank you.

**Comment by CharliePoole** [comment]
Thanks for filing this. 

The And.By option would require `And` to have different meanings based on context. We try to avoid that although there are a few places where it happens.

Just repeating `By` would work but I like `ThenBy` because it makes clear the order of application.

What do others think?

**Comment by ChrisMaddock** [comment]
I would agree with `ThenBy` - it matches up to LINQ behaviour.

We'd get some use out of this functionality too, we do a few similar tests. I've always got round it the lazy way - by ordering my own list, then asserting that `SequenceEqual()`.

**Comment by CharliePoole** [comment]
Looks pretty straightforward. All code is in the constraint class. It needs a new modifier and should save a list of property names rather than just one name. We could avoid checking the sequence of By, ThenBy... by letting them both do the same thing, or we could check... By would expect an empty list, ThenBy a non-empty one. The hardest part would be to construct a comparator using the list of properties, but not so hard as all that really. :-)

**Comment by jnsn** [comment]
I created a pull request for this. The pull requests adds 3 additional methods to accommodate the requested feature:

- `ByDescending`
- `ThenBy`
- `ThenByDescending`

The descending methods were added to match the LINQ behavior and to allow for the existing `Descending` constraint to keep existing and not depend on whether or not one or more properties are added to the sort requirement.

**Comment by labilbe** [comment]
Can't we re-use existing features like?

`Assert.That(ordered, Is.Ordered.By("Item1").Descending.ThenBy("Item2")).Descending`

**Comment by jnsn** [comment]
@labilbe The `ThenByDescending` method I implemented has the exact same effect as `ThenBy("Item2").Descending`.

**Comment by CharliePoole** [comment]
I think that was @labilbe 's point. :-) Do we want to add two new elements to our syntax if the existing elements can do the job?

It's definitely a valid question. NUnit's existing syntax tries to separate actions into individual modifiers. ByDescending and ThenByDescending each do two things. It may be more Linq-like, but it's less NUnit-like. I'd like to see what others think, especially @nunit/core-team and @nunit/contributors.

**Comment by lundmikkel** [comment]
I'm with @labilbe on this one. I would much rather reuse what we have, than start adding new stuff. It makes it a lot more easy to find the right syntax without having to read the documentation.

**Comment by CharliePoole** [comment]
Yes, we should not discount the "cost" of adding more stuff for users to remember!

I'm still in a quandary though about what this should mean...

```C#
   Assert.That(collection, Is.Ordered.Descending.By("Prop1").ThenBy("Prop2");
```

We could refuse it (say it's ambiguous), apply descending just the first property or apply it to both properties.

**Comment by labilbe** [comment]
I like 'apply to both properties'.

**Comment by jnsn** [comment]
OK, I'll try to find some time in the next couple of days to change this.

**Comment by CharliePoole** [comment]
Let's wait another day for feedback. Reviewing new feature ideas always takes a while as people in different time zones make comments, then get comments back, etc. The Q&A cycle is pretty long.

@rprouse @OsirisTerje @oznetmaster What do you guys think?

**Comment by MSK61** [comment]
I opt for not adding descending-variant functions. nUnit should provide the basic features while letting users mix and match them the way they like.

Also probably being far from others' thoughts, I'm proposing the idea of adding versions of `By` and `ThenBy` that might take a custom comparator for the property. That'll make it easy to specify a descending order or any other ordering criteria.

**Comment by ChrisMaddock** [comment]
If `Descending` applies to all subsequent constraints, is there any way to force back to ascending ordering? e.g.

    Assert.That(collection, Is.Ordered.Descending.By("Prop1").Then.Ascending.By("Prop2");

I feel like a standalone `Descending` could be ambiguous however implemented. Should we deprecate it in favour of explicit `ByDescending()` and `ThenByDescending()`? There's no ambiguity that way, and it matches the LINQ implementation.

**Comment by CharliePoole** [comment]
@ChrisMaddock We don't currently have an `Ascending` modifier. I was thinking about it myself, solely for the purpose of documentation.

Having `Then` as a separate do-nothing item in the syntax is reminiscent of `With`, which we currently support. If our intent is to have `By` and `ThenBy` do the same thing, then that makes sense as well.

I guess  the key question is whether Descending (and Ascending) should apply to one item only or to all the following items - when not contradicted.

**Comment by ChrisMaddock** [comment]
@CharliePoole: Apologies, I think a typo in my example confused my point - I wasn't suggesting an standalone `Then`. I like `ThenBy`. Being less familiar with the 'non-mainstream' functionality of NUnit, I already struggle to work out the correct chain of constraints sometimes - `ThenBy` means Intellisense can suggest it to me right away. :-) 

My query was that, if `Descending` was to affect all following items, do we currently have a method to overwrite that later in the constraint-chain, or would an `Ascending` be required, if we chose that option?

Additionally, I'd wonder if it's worth deprecating the standalone `Descending` in favour of @jnsn's new `ByDescending` and `ThenByDescending` - as there is this ambiguity, and I'm not sure either option would give someone 100% without checking docs) in what to expect.

**Comment by CharliePoole** [comment]
For a long time we talked about creating an alternate or extended constraint syntax. Several of the options were based on use of lambdas with Linq expressions. @simoneb was a big champion of this idea. The effort kind of died out but is somewhat documented at https://github.com/nunit/docs/wiki/Extended-Constraint-Syntax-Spec

I'm still intrigued by the idea of a Linq-like _alternative_ syntax. I'm less favorable to making gradual changes so that the NUnit syntax becomes more Link-like. I think our syntax is its own thing so I'm interested in new features looking like the features we already have. This is just my opinion, of course.

Currently, we support three different syntaxes: classic, constraint-based and constraint-based with inheritance (AssertionHelper). Of course, we currently do it by having all three in the same assembly but the direction we want to go is to support adding on new syntaxes using external assemblies. I'm going to experiment with doing this for AssertionHelper, which is an easy one.

So... wherever we go with this issue, if you are interested in an alternative syntax, feel free to pick up the torch. :-)

**Comment by CharliePoole** [comment]
So... here's where I am on this issue, taking into account the feedback so far...

1. I think we need both `Ascending` and `Descending` modifiers.

2. I like the suggestion that @ChrisMaddock made - even if it was a typo - to make `Then` a separate modifier. Externally, it would serve to make the constraint expression more readable. We already do this with `With`. Internally, it would serve as a break between two columns. For example, it would help distinguish two meanings for the following two constraints.

```C#
   Is.Ordered.By("A").Descending.Then.By("B")
   Is.Ordered.By("A").Then.Descending.By("B")
```

3. I would get rid of `ByDescending`, `ThenBy` and `ThenByDescending`.

4. I would keep the default where ascending is applied everywhere unless `Descending` is specified on that column. Initial `Descending` would not have any special meaning.

Try out some experiments with this syntax and see what you think.

**Comment by CharliePoole** [comment]
If `Then` is optional, then the following expression is potentially ambiguous...

   ```C#
   Is.Ordered.By("A").Descending.By("B")
   ```

I would like to reject that statement, preferably at compile time. If folks agree, I can help @jnsn with the implementation.

**Comment by lundmikkel** [comment]
Just a thought: if you have both `Ascending` and `Descending` couldn't you end up in scenarios where you could apply both? For instance:
```C#
Is.Ordered.Ascending.By("A").Descending
```
It would probably require multiple helper objects to create different paths that ensure no ambiguities.

Other than that, I do like the syntax you proposed @CharliePoole.

**Comment by CharliePoole** [comment]
Or even 

```C#
Is.Ordered.Ascending.Descending
```

Yes, I'm afraid my compile approach requires a bit more compile-time error-checking than what we ahve in the PR. @jnsn I may take a shot at coding something when I finish what I'm currently working on.

**Comment by CharliePoole** [comment]
Somehow we thought this would be easy!

**Comment by CharliePoole** [comment]
@jnsn Checking old issues in progress, I came on this. What can I do to help get it moving again?

**Comment by CharliePoole** [comment]
Odd... I merely made a comment mentioning @jnsn and GitHub says I unassigned him. Is this some of the new magic in GitHub comments? :-)

**Comment by CharliePoole** [comment]
Hmmm... He's not available to re-assign so he must have dropped out of our contributors team.

**Comment by CharliePoole** [comment]
That will teach us to be faster in getting PRs handled. :-( I'll complete.
