### ISSUE TITLE
NUnit Agent allocates a lot of memory 

### ISSUE THREAD

**Issue by Silv3rcircl3** [nunit/nunit#1559]
When I run my specs the `NUnit Agent` allocates around 6GB of ram, regardless of whether I run them via R# or directly via the console runner. 

![image](https://cloud.githubusercontent.com/assets/6583600/15957636/b641a916-2ef0-11e6-9253-3e96c82a4a8c.png)

The project is available [here](https://github.com/Silv3rcircl3/reactive-streams-dotnet/tree/tck) including a build script, so you only need to navigate into the folder and run `Build.cmd All`.

Thanks, Marc

**Comment by ChrisMaddock** [comment]
This is potentially the same issue as #1430 - maybe best to check once a fix is in for that one.

**Comment by Silv3rcircl3** [comment]
@ChrisMaddock thx, will do so.

**Comment by rprouse** [comment]
Closing as duplicate of #1430

**Comment by Silv3rcircl3** [comment]
I tried the latest release 3.4.0 but unfortunately the problem remains.
It is maybe related to tests or fixtures that are marked as skipped, because from what I can see, at the end of the tests all warnings for the skipped tests are printed to the console line and during that process the memory is released.

**Comment by ChrisMaddock** [comment]
@Silv3rcircl3

3.4 solves my memory issues, but we don't have many skipped tests. Are you able to verify if that is the cause of the retained memory? It didn't cross my mind when doing the PR, although I wouldn't have expected skipped tests to even be initialised - @CharliePoole do you have a better idea of what's expected?

**Comment by Silv3rcircl3** [comment]
@ChrisMaddock sorry, I should have done that before. 
I profiled the agent during execution with dotMemory and found the reason in my implementation code. 
Without this particular tests it's working like a charm :+1:

**Comment by rprouse** [comment]
Thanks for letting us know @Silv3rcircl3. Nice to hear you've figured it out.

**Comment by lanzelot1989** [comment]
@Silv3rcircl3 Can you expand on what was wrong with your tests?

**Comment by Silv3rcircl3** [comment]
Sorry @lanzelot1989 I can't remember what the issue was.

**Comment by lanzelot1989** [comment]
An unfortunate case of RAMnesia, I suppose. :-D
