### ISSUE TITLE
NUnit 3 parallel execution Assembly-level one-time setup

### ISSUE THREAD

**Issue by b-lal** [nunit/nunit#1577]
Hi,
I have a task where I must initialize my system before running 2-3 tests in parallel, and a cleanup that should run exactly one time after all test runs are finished.
Is there a way in NUnit 3 to do that?

I am aware of the Suite concept in NUnit 3 and thought it would be useful to me, but this is not what I'm looking for, I'm looking for something like the Suite in **TestNG** which starts before and ends after all running tests.

Are there any plans to implement this capability? Or is there any workaround I can use?

Many thanks and great work (I'm a follower!) :+1:

**Comment by CharliePoole** [comment]
Yes, create TestFixtureSetUp class outside of any namespace. It's OneTimeSetUp method will run before any tests and it's OneTimeTearDown will run after.
