### ISSUE TITLE
log4net and NUnit 3.2 and console output in VS

### ISSUE THREAD

**Issue by zelenij** [nunit/nunit#1588]
In my NUnit 2.6 tests I used to see log4net log messages in the output window of Visual Studio, in the Tests section. Since I switched to NUnit 3.2, they are no longer displayed, which is very inconvenient. I tried searching and the best "solution" I came up with was to dump everything into debug strings, which can be viewed either via DebugView utility from SysInternals or when I actually debug a test - then the messages are shown in Debug section. However, I would really like to see my log lines in the Visual Studio even when not debugging. Any ideas? Visual Studio 2015.

More info as well as a recommendation to open an issue in this SO post: http://stackoverflow.com/questions/37893952/log4net-and-nunit-3-2-and-console-output-in-vs

**Comment by CharliePoole** [comment]
Although we don't want to maintain internal support for various third-party loggers, it seems like we could provide something that the user could install to convert log messages to immediate output events in NUnit - now that we have such events. This may be some kind of extension but it will take a bit of design to figure it out. Ideally, we want to enable user s to  write this sort of thing.

**Comment by zelenij** [comment]
Any solution, even if it will only expose new API to be used in an external log4net+nunit3 adapter is better than nothing! :)

**Comment by rondoe** [comment]
Did you check your log4net configuration? In my case the log4net configuration through 

`ConfigureAndWatch("log4net.config")`

 wasn't working. I added the BaseDirectory path and now the console output is back. In addition to that, I switched from ConsoleAppender to TraceAppender.

**Comment by zelenij** [comment]
I am pretty sure the configuration is picked, because I supply the full path.  If yours is working, maybe you could share it please?

**Comment by rondoe** [comment]
I'm sorry, but i tried to figure out, why this is working. but i have no clue. i tried to prepare a new solution with my configuration, but it's not logging to console. my original project is using hangfire, unity and owin selfhost. so i think this could be related.

**Comment by zelenij** [comment]
I see.... well, thanks for trying anyway!

**Comment by leevva** [comment]
How about 
Console.SetOut(TestContext.Progress);

**Comment by CharliePoole** [comment]
@leeva The only drawback, assuming that worked, would be that __all__ console output would be redirected, which may not be what is desired. But it's an interesting idea!
