### ISSUE TITLE
Split the nunit repository into multiple repositories

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1589]
Now that 3.0, 3.2 and 3.4 have been released, our APIs are relatively stable. Although some changes may continue to occur, we don't expect them to be frequent. There is now much less need for developers to be working, for example, on framework and engine changes at the same time.

The current repository can be split up in several ways, so we should take this a step at a time. Here's one possible order:

1. Remove the portable agent from this repo.

2. Remove the installer project from this repo.

3. Split the repo into nunit-framework and nunit-engine repositories, retaining the console code in the engine repo. In the future we could consider splitting engine and console, however the console is relatively small so this doesn't give a lot of benefit.

**Comment by rprouse** [comment]
I assume you mean **once** 3.4 has been released :smile:

**Comment by CharliePoole** [comment]
Yup... it's in the 3.6 milestone.

**Comment by CharliePoole** [comment]
One subtask here is to figure out how to handle code that is now used in common between the parts that are being split. We currently use source code in `src/Common`. For example, there are a number of classes shared between nunitlite and the console runner.

Alternatives...
1. Duplicate the code and live with it.
2. Use GitHub submodules for source-level sharing.
3. Create one or more helper assemblies.

In fact, this could be handled as a separate issue before we split anything.

**Comment by oznetmaster** [comment]
I would love to comment on this, but have no idea what is involved with 2, which seems like the best option from afar.

**Comment by CharliePoole** [comment]
I left in 1, because I think we should bear in mind that it's possible, even if annoying. Particularly, if we are left with some small number of things that can't be handled any other way.

There is lots of literature about how submodules cause problems, etc. This is especially so when you allow the including projects to modify the submodule. A change to console might inadvertently break nunitlite, for example. We would need to be disciplined about it.

A separate assembly would work well in some cases, particularly for utilities like the color console. It seems less good for what I call "policy code" like deciding what options are supported by a program.

**Comment by CharliePoole** [comment]
Using this to try out ZenHub's Epic feature - you will only see the included projects if you have ZenHub installed in your browser.

**Comment by CharliePoole** [comment]
@rprouse One conclusion about Epics: the titles of the included issues need to be short, or at least have their key words at the beginning, because of the two-column listing format.

**Comment by rprouse** [comment]
@CharliePoole this is the first time I've seen the Epic feature in use. I agree that we should probably keep the titles short, or at least make them identifiable by the first few words. I like the feature though, it could be useful for larger themes like this. :+1:

**Comment by CharliePoole** [comment]
The Epic feature doesn't give you much of a way to specify ordering or dependency of the contained issues. So here's how I'm planning to get this done, in three phases...

1. Preliminary Steps

 * Eliminate code sharing across projects (#1596) We could do this as as part of phase 2 but I think it makes sense to do it first. There is a set of to-do items listed in the issue, some of which I'm doing while others are awaiting someone to take them on. There are comments with a proposed approach to each item.
     *  Creating a helper assembly to cover some of the code-sharing
items (#1621) is actually a sub-task of the above. It will deal with
more than half of the sharing issues. I'm working on it.

 * Moving the portable agent out of the nunit repo (#1573). @rprouse already did this one.

 * Separate installer project (#1595). Not 100% necessary but I don't think we want to end up with installer projects in each repo. Rather, I'd like to see a project by itself that initially does the
msis but eventually does any bundling we do across multiple projects. I assigned it to myself but haven't done anything on it if you want to do it. An alternative to this step would be to stop producing msis entirely.

 * Refactor Cake script. (#1610) I created this issue with a different purpose in mind, but I think I'll extend it so that the top level division of packaging tasks is by framework/engine/console rather than by kind of package. I'll leave out the msis if we get the installer split off. This is a pretty small and therefore optional preliminary step.

2. The Big Split

 * Split the framework and engine. (#1598) We would create an nunit.engine repo, remove all the framework stuff from it and make it work. Only then would we remove the engine and console from the nunit project, which I would rename as nunit.framework.

 * Separating extensions from the engine (#1600). I think the teamcity extension is the only one that's mandatory. The others might reasonably stay bundled. We will need to discuss that. This could be
done before the big split, but there doesn't seem to be any particular advantage in that.

3. Further Splits
    Each of these is optional, to be discussed but clearly come after the big one. No point in discussing them until then.

 * Split out Compact Framework project (#1599)

 * Split out Silverlight project (#1601)

 * Split or remove AssertionHelper (#1212)

 * Separate assembly for constraints (#502)

**Comment by rprouse** [comment]
Since this is an Epic that is spanning multiple releases (SL and CF will come post release), I am moving this to the next milestone as I prepare for release.

**Comment by rprouse** [comment]
@CharliePoole we have one idea and one low priority feature left in this epic. I'm not sure it is worth keeping open for those. Shall we close as complete and track the two remaining issues on their own?

**Comment by CharliePoole** [comment]
Done!
