### ISSUE TITLE
FloatingPointNumericTests.MirroredFloatReinterpretation test fails on arm processor

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1591]
This test uses the FloaringPointNumerics ReinterpretAs... methods to see if 12345 can be mirrored as a float and then back as an int again

Unfortunately 12345 interepreted as a float is 1.729903E-41 which is an invalid float number.  Float exponents can only be between -38 and +38.

Apparently some of the current ARM 7 processors automatically normalize a float when they load it, so the float represented by 12345 (0x00003039) is normalized to 0.0, causing the test to fail.

Probably the best thing to do is to pick an integer which is actually the representation of a valid float for the test.

**Comment by CharliePoole** [comment]
I made it low priority, but I imagine it might be higher for someone with one of those processors!

AFAIK, you are the only one seeing the error, so feel free to grab this and fix it. :-)

**Comment by rprouse** [comment]
Nobody has picked this up and nobody else has asked for this so closing.
