### ISSUE TITLE
How to get the type of exception that was thrown

### ISSUE THREAD

**Issue by SemenetsLeonid** [nunit/nunit#1592]
Hello,
I use Action attribute to invoke events of [Allure report framework](https://github.com/allure-framework),
and I would like to have type of exception to determine test failed or broken.
NUnit recognizes that test is broken when it throws NoSuchElementException (Selenium exception).
In my case it must be failed state.

Can I somehow get the exception that was thrown or type of exception? Maybe from TestContext?
Or set a list of exceptions under which test will be recognized as failed?

        public void AfterTest(ITest test)
        {
            var suiteId = GetSuiteId(test);
            var finishedEvent = new TestCaseFinishedEvent(DateTime.Now) { SuiteUid = suiteId };
        
            if (!TestContext.CurrentContext.Result.Outcome.Status.Equals(TestStatus.Failed))
            {
                Allure.Lifecycle.Fire(finishedEvent);
                return;
            }

            var failureEvent = new TestCaseFailureEvent
            {
                SuiteUid = suiteId,
                StackTrace = TestContext.CurrentContext.Result.StackTrace,
                Throwable = TestContext.CurrentContext.Result.Outcome.Label.Equals("Error")
                    ? new Exception(TestContext.CurrentContext.Result.Message)
                    : new AssertionException(TestContext.CurrentContext.Result.Message)
            };

            Allure.Lifecycle.Fire(failureEvent);
            Allure.Lifecycle.Fire(finishedEvent);
        }

Thank you.

**Comment by CharliePoole** [comment]
As your code shows, NUnit does not actually recognize the exception you get from Selenium as a failure. Rather, it reports an error (different from failure) because an unknown exception has been thrown. The only information about the type of exception would be found in the message or stack trace from the exception.

Using an ActionAttribute for reporting about tests seems like a misuse of NUnit. The ActionAttribute is actually part of the test and the test could still fail or error out after the action attribute completes.

Reporting _about_ tests is better handled completely outside of the tests. The NUnit engine provides an ExtensionPoint for this purpose, using a user-implemented class that implements ITestEventListener.

**Comment by SemenetsLeonid** [comment]
Thanks for answer.

I looked in the direction of implementation ITestEventListener, but it provides already generated data. It is not enough information for me. I can not get access to the test and its attributes to get the test name, description, severity or feature that covered by test or anything else.

Simple example of my implementation.

        [Test]
        [Issue("12345"]
        [Features("Authentication")]
        [Severity(severitylevel.critical)]
        [Title("Authentication with valid login")]
        [Description("Valid login", descriptiontype.html)]
        public void AuthenticationWithValidData()
        {
            var login = Config.BackendLogin;
            var password = Config.BackendPassword;
            var customerCode = Config.BackendCustomerCode;

            AuthenticationSteps(new AuthenticationPage(Driver), login, password, customerCode);

            var mainPage = new MainPage(Driver);
            Assert.That(mainPage.Header.UserName.Text, Is.EqualTo(login), "Incorrect user name");
            Assert.That(mainPage.Tree.Displayed, Is.True, "Menu tree is not displayed");

            CheckJavaScriptErrors();
        }

Is there any tips on how correctly to solve my problem or implementation of ITestEventListener is the only way?

Thank you.

**Comment by CharliePoole** [comment]
@SemenetsLeonid Don't your custom attributes save properties in the test? Those would all be in the xml that is sent to the event listener.

**Comment by SemenetsLeonid** [comment]
I did not know that data which transmitted through property attribute will be in result xml. It makes all the difference, I can now get access to all the necessary data.

Next time I will read the documentation more closely.
I got the answer to my question. Many thanks!

**Comment by CharliePoole** [comment]
Good! I'm glad it works for you. :-)
