### ISSUE TITLE
Nunit Console Runner 3.2.1 and Mono 4.4 throws RemotingException

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1593]
This happens at the end of a run...

> Unhandled Exception:
>> System.Runtime.Remoting.RemotingException: Channel not registered
>>   at System.Runtime.Remoting.Channels.ChannelServices.UnregisterChannel(IChannel chnl) <0x7fa0eab712d0 + 0x001c1> in <filename unknown>:0
>>   at NUnit.Engine.Internal.ServerBase.Stop () <0x41d21220 + 0x00075> in <filename unknown>:0
>>   at NUnit.Engine.Internal.ServerBase.Dispose (Boolean disposing) <0x41d232a0 + 0x0002d> in <filename unknown>:0
>>   at NUnit.Engine.Internal.ServerBase.Dispose () <0x41d23270 + 0x00025> in <filename unknown>:0
>>   at NUnit.Engine.Services.ServiceManager.Dispose (Boolean disposing) <0x41d20e80 + 0x00118> in <filename unknown>:0
>>   at NUnit.Engine.Services.ServiceManager.Dispose () <0x41d20e50 + 0x00015> in <filename unknown>:0
>>   at NUnit.Engine.TestEngine.Dispose (Boolean disposing) <0x41d20df0 + 0x0003b> in <filename unknown>:0
>>   at NUnit.Engine.TestEngine.Dispose () <0x41d20d90 + 0x00018> in <filename unknown>:0
>>   at NUnit.ConsoleRunner.Program.Main (System.String[] args) <0x41c78350 + 0x00a90> in <filename unknown>:0

Mono seems to be unregistering the channel pre-emptively! In any case, we need to catch and ignore the exception.

**Comment by sergey-tihon** [comment]
[I still see this error](https://github.com/fsprojects/SwaggerProvider/pull/36) in latest nuget package from appveyor `3.4.0-CI-2776-PR-1562` 

https://travis-ci.org/fsprojects/SwaggerProvider/builds/139583374#L2106

That's how I run it:
> mono  "/home/travis/build/fsprojects/SwaggerProvider/packages/test/NUnit.ConsoleRunner/tools/nunit3-console.exe" "--noheader" "--labels=All" "--timeout=1200000" "/home/travis/build/fsprojects/SwaggerProvider/tests/SwaggerProvider.ProviderTests/bin/Release/SwaggerProvider.Tests.dll" "/home/travis/build/fsprojects/SwaggerProvider/tests/SwaggerProvider.Tests/bin/Release/SwaggerProvider.Tests.dll"

**Comment by sergey-tihon** [comment]
The `nunit.engine.dll` from `NUnit.ConsoleRunner.3.4.0-CI-2776-PR-1562.nupkg` does not contains this fix ... __Why?__
![image](https://cloud.githubusercontent.com/assets/1197905/16283621/2d4532fa-38d6-11e6-8b64-fcac33269369.png)

**Comment by CharliePoole** [comment]
Your comment is not on GitHub for some reason, so I'm replying by mail in
hopes it finds you!!!

You are looking at a pull request from 12 days ago. The fix was merged
yesterday, so it's naturally not there.

In general, you should only be testing master builds, which appear on
AppVeyor _after_ we merge in the fix, or specific issue branches, which you
know you are interested in. A build of a PR merely shows what the master
would look like __if__ we merged tht fix.

Since there have been a number of merges over the past 12 days, I'm not
sure why this was the latest one you could find. You may be better off
looking at our MyGet feed, which only includes builds that are committed to
master.

Charlie

**Comment by sergey-tihon** [comment]
Hi,

 

Thank you for your reply.

 

But latest master version cannot be installer from appveyor aither from myget

Because feeds do not contain 

NUnit.Extension.TeamCityEventListener 3.3.0-CI-2867-master



 

Sergey

**Comment by CharliePoole** [comment]
Thanks, you have highlighted a problem we didn't know about.

The TeamCityEventListener is a new extension and so is versioned as 1.0.0. The previous four extensions have already been released using the same version number as NUnit and so have to continue using  numbers in that series. I think you will discover that the version labelled 1.0.0 is the most recent.

There are actually two problems here:
* The packages in the 3.3 series will have to be removed so it's clear that 1.0.0 is the latest.
* The package didn't have the CI modifier applied, so every build is overwriting the previous one.

Fortunately, we have not yet released to the general public on nuget.org, so we can fix this!

FYI, the reason for the versioning change for teamcity is that it will be moved to a separate repo from the core of nunit and maintained separately in the future.
