### ISSUE TITLE
Separate installer project

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1595]
Assuming we are going to continue with at least some msi installers, they should be in a separate project repo. There is already a separate solution in the nunit repo, so the main change will be in designating where the installer finds the source files to include in the installers.

There seems to be no reason to have separate projects for _each_ installer, however. They can remain together in one project.

**Comment by ChrisMaddock** [comment]
@CharliePoole - what so you see this looking like? 

The simple method would be to just have an empty dir in the new repository, where the user would manually copy the files that they want packaging up. 

Alternatively, could we have nuget do the heavy lifting? So we'd have a packages.config which always pulls the latest packages. (Or allows a specific version to be specified if required.) Then the release process would just involve releasing the nuget packages before building a new installer.

**Comment by CharliePoole** [comment]
@ChrisMaddock I think that would be a strong possibility. Alternatively, we could have "feeds" that use other formats, like simply zipping all the files. That would mean less knowledge needed in the installer about how each item is structured within the nuget package.

This issue is on hold at the moment while @rprouse and I have been discussing it offline. There are a few issues...

1. If we are not going to release any more msis (my favorite option) then removing this from the nunit repo is all we have to do.

2. If we are not going to release a separate msi for the framework, then we can cut this down in size.

3. Depending on who is going to maintain it, we may want to structure it in different ways. That may just be my own issue - if I'm going to do it, I don't want a VS solution because I find that VS makes WiX harder to use, not easier. But somebody else may feel differently and should get to do it as they prefer.

For the moment, we have so much stuff going on that this has  basically been just sitting there.

**Comment by rprouse** [comment]
What if we drop the framework installer and just leave the engine/console installer in that repo? I think relying on installed libraries is bad development practice, so we should follow xUnit's lead and only distribute via NuGet (or the Zip file for NuGet haters). I am fine with installing the console runner since it is a tool not a library, but I wouldn't mind dropping it either.

So, I vote for 2, but would be fine with 1. Personally, I think 3 is too much of a hassle for the few people who use it.

**Comment by rprouse** [comment]
To add some stats, looking back at 3.0.1 since it was out the longest, 

- the MSI had 42,865 downloads (12%)
- the ZIP had 13,810 (4%)
- the NuGet package for the framework had 290,142 (84%)

I would also argue that most people use the MSI for the console. I say this because there is a bug in the MSI registry settings. It adds all the frameworks to the registry. If you target .NET 4.5, it favours the PCL version over the 4.5 version for some reason and the PCL version doesn't work with the console. Since it took until 3.4 for someone to report it, I expect few people are using the install of the framework.

**Comment by CharliePoole** [comment]
@rprouse I think the reason we got stuck in our offline conversation, is that I'm trying to defer to you as the guy who is going to stick around! So taking it in that light, I think 2 is a good choice.

"I think 3 is too much of a hassle for the few people who use it."

I'm not clear what you mean by that. Item 3, in my mind, is simply about setting up the project so it's efficient for whomever maintains it. We can, of course, move it using the existing technology and decide that later but if somebody is going to take on that project as project lead, then they should be able to structure it as they like, so long as the same thing comes out of it for the users.

Personally, I'm willing to transfer it as is, so long as I don't have to make lots of changes beyond dropping the framework. I have found that maintaining this through a VS WiX project takes me three or four times longer than it used to take using notepad plus WiX. (I think vsCode would make it even more efficient.)

Historically, you have maintained this. I only raised the issue, and volunteered take it on, because it seems like you are falling into the same pattern I had in the past... that of wearing too many hats. If it's not me, then IMO you should find somebody else to manage the bundling of multiple NUnit components - that's a clear separation that is fairly common in the linux world and that I think we could adopt to our advantage. I don't have any particular desire to do this, however. I'm just trying on different ideas of where I may contribute when I stop being a leader of this project.

**Comment by rprouse** [comment]
By hassle, I am mainly referring to having to coordinate the release between the two projects. We would like to get to a point where the two projects get onto their own release cycle which to me seems to contradict a single installer.

As for the Visual Studio solution, the WXS files shouldn't be any different than a non-project based approach except for a couple of variables. I edit them in VSCode myself. I don't mind if we switch to pure WiX though.

**Comment by CharliePoole** [comment]
If it becomes a "distribution" as I was imagining, then there is no need of coordinating releases. When a new release of Ubuntu comes out, it contains whatever versions of specific software the packagers decided to include. I was imagining that our "install" project would become like that, albeit on a smaller scale. If you wanted the latest, you would have to get the nuget packages, but periodically, there would be a bundle containing a set of compatible releases.

**Comment by ChrisMaddock** [comment]
I also use the msi installer just for the console. Up till restructuring for NUnit 3, our CI relied on an installed console. I guess it's would be no different for me to manually download the nuget package, unzip, put in position, and add to path, but as the msi already exists, I think it'd be a shame to get rid.

Removing the framework from the installer does sound sensible however.

As Rob said, keeping it in the engine repo would then sound sensible - unless we do go ahead and move the 'other' addins out to separate repositories?

**Comment by CharliePoole** [comment]
If you were going to do that, you may as well use the zip we provide for that purpose.

As I wrote above, I have always envisioned a separate "bundling" or "distribution" project where a user would get a set of tools from us, tools that were all released separately on their own schedule, but integtrated for their use. That might include the engine, console, gui, extensions, etc. It __could__ include a recent copy of the framework or we could provide that only separately. 

The difference between the tools and the framework is that our approach has always been to encourage people to use the latest tools, but not necessarily the latest framework. It can be disruptive to change framework versions in the middle of a project, which is why we support multiple framework versions being in use at the same time.

**Comment by ChrisMaddock** [comment]
Ah, I hadn't realised it was also planned to include gui. That would potentially be a reason against nuget packages.

Charlie - you mentioned on the other issue that you were open to help on this one - would be happy to take a look if we decide where it's going. It looks like, at minimum, resolving whether we have a framework msi or not is a block on splitting engine/framework.

**Comment by CharliePoole** [comment]
Well, I may be guilty of thinking more broadly than the problem we need to solve immediately. @rprouse What would you like to see happen for 3.5 with regard to this?

**Comment by rprouse** [comment]
I would like to drop the framework MSI for 3.5 and just distribute tools (console, engine, eventually gui, maybe add the project editor) as an MSI. I think the best approach is to split the repo into console/engine and framework as we have been planning, then adjust the installer for the console/engine as needed. We can leave the framework wix files in the framework repo for one release just in case there is a huge public outcry.

Everyone in agreement?

**Comment by ChrisMaddock** [comment]
Sounds sensible to keep this simple until there's a GUI to distribute.

@CharliePoole - do you want me to submit something separating off the framework installers, or would you prefer to look at it?

**Comment by CharliePoole** [comment]
@ChrisMaddock It's all yours! :-)

Do you plan to make changes in place or do you need me to create a new repo?

**Comment by ChrisMaddock** [comment]
@CharliePoole - I took from Rob's post he was suggesting keeping the installers just in the engine/console and framework repos for now? 

I was planning to just split the framework/engine in to separate solutions/subdirectories so they're ready for the engine/framework split. If they're going to end up as a separate repo at some point however, then it does perhaps make more sense to do that now.

Happy to do either - I don't actually have to use them, so whatever will be easiest! If they are going to a separate repo however, we probably need to work out where the dlls are coming from (Nuget or otherwise.)

**Comment by CharliePoole** [comment]
@ChrisMaddock The nunit-install solution includes two msi projects, one for the framework and one for everything (console, engine and framework). Splitting them into two solutions would be easy. Removing the framework from the combined project would be a bit more work, but easy enough if you understand wix projects and how the XML works.

IME moving the whole thing to a separate repo is the easiest It leaves open the issue of how we populate a source directory with the appropriate dlls, but we might even leave that as an open question for now, since we only build and distribute msis every three months.

How you handle this is probably more dependent on your level of familiarity with WiX than anything else. If you have time to do it (and neither of us does) then I'd say pick the approach that presents problems you already know how to solve! @rprouse Would you agree?

In terms of priorities... getting this out of the way of splitting the framework and engine is the big one. So long as there is a possibility of our going entirely to nuget distributions, there's a chance that extra effort on this one will be wasted.

I'm still interested in a future nunit "bundles" project, which would combine various nunit programs in a way that users could easily get started. But if I were doing that, my first step would be to look at alternative installers, preferably cross-platform, rather than going with the Windows installer automatically.

**Comment by ChrisMaddock** [comment]
>So long as there is a possibility of our going entirely to nuget distributions, there's a chance that extra effort on this one will be wasted. 

Agreed.

I like Rob's idea of a console/engine only installer, will go for splitting off the framework from that, and then keeping the framework installer separate for now, in case of outcry.

If it goes to a seperate repo, plugging in a nuget restore shouldn't be too taxing (If everything involved is currently on nuget!) We could then revisit in future when the GUI is involved, if it may be a fresh start anyway.

If they're staying in-repo, the problem goes away! Will hold off making a start till @rprouse comments.

**Comment by CharliePoole** [comment]
@ChrisMaddock Just so you understand there is no console/engine installer currently. You can easily split the framework installer off from the master installer - they are two separate projects. But the master installer incorporates framework, engine and console. IOW, we currently have two msi installers that include the framework.
