### ISSUE TITLE
Move Portable agent to its own repository

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1597]
@rprouse Would you add a real description here?

**Comment by rprouse** [comment]
Closing as a duplicate of #1573

The portable agent is now in https://github.com/nunit/nunit.portable.agent

**Comment by CharliePoole** [comment]
I looked for an issue, but didn't realize it was closed. However, I still see the portable agent in the tree for the nunit repo.

**Comment by rprouse** [comment]
Opps, my miss. I forgot to remove it. I will reopen and clean it up.
