### ISSUE TITLE
Object graph comparison

### ISSUE THREAD

**Issue by AlexArchive** [nunit/nunit#160]
Would you consider adding support for *object graph comparisons*? 

Fluent assertions [supports this](https://github.com/dennisdoomen/fluentassertions/wiki#object-graph-comparison) and some make-shift approaches have been discussed [here](http://stackoverflow.com/a/318238/2015959).

**Comment by rprouse** [comment]
Thanks for the idea, but this isn't in keeping with our vision of where we want to take NUnit, so I am closing.
