### ISSUE TITLE
TeamCity package has no pre-release suffix

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1605]
As pointed out on #1593, there are ~~two~~ three problems with the Appveyor and MyGet feeds for the new teamcity extension:

1. The package was previously deployed as development version 3.3, but is being  released as version 1.0. Consequently, older packages in the 3.3 series must be removed.

2. The package is not getting a -CI-nnnn suffix added as should be done, so it appears as 1.0.0 in both feeds. This needs to be fixed.

3. The NUnit.Console nuget package is still depending on the same version because the dependency is being generated automatically.

**Comment by sergey-tihon** [comment]
Note that nunit.console still depend on team city extension with the same version
![image](https://cloud.githubusercontent.com/assets/1197905/16286276/17a85c20-38e4-11e6-8f55-f25f220a625d.png)

**Comment by CharliePoole** [comment]
OK, that would be point 3 then. :-) I  added it above.

This actually highlights a greater problem we should deal with after the release. In general, we can't deduce what version of an extension to bundle with the runner. So we need to either stop bundling or create a more general way of specifying what to bundle, correct version included.

**Comment by rprouse** [comment]
@CharliePoole, assuming that extensions are completely stand-alone and only depend on the engine.api in common, should the dependencies all be `>=` not specific versions so that the engine gets the latest? If we start updating extensions out of band, that will likely be important.

**Comment by CharliePoole** [comment]
Yes... that's part of the "greater problem" I was referring to. I'll take a look. It would be best to get that fixed in 3.4, but it may be simpler to just hard-code everything for the release and look at it again afterwards.

**Comment by CharliePoole** [comment]
@rprouse According to https://docs.nuget.org/create/versioning#Specifying-Version-Ranges-in-.nuspec-Files the form we are using does mean >= what is listed.

**Comment by CharliePoole** [comment]
@rprouse Item 3 is a problem... Maybe we should bite the bullet and leave the TC extension out of the package - folks would have to install it separately.

It's obviously not undoable, but we would need to upgrade Cake in order to pass additional replacement properties to the nuspec file. Given that it's only a few days until you want to release, that seems potentially destabilizing.

Are you using a higher version of Cake on any of your other projects?

**Comment by rprouse** [comment]
I am using the latest version of Cake for a project at work and had no problems with it. I also didn't encounter any breaking changes. Would you like me to submit a quick PR upgrading it? I think we are on 0.6.4, so there have been 8 releases since then.

For me, upgrading was as simple as re-downloading the build.ps|sh files then changing the packages.config in tools. As I said, no breaking changes.

**Comment by CharliePoole** [comment]
@rprouse I'd say do it and make sure we aren't doing anything that causes it to break. I'd worry less for a less complex build script. 

OTOH, as a quick and easy alternative, which I thought of after my first post, I can just launch a process that runs nuget from the command-line.

This is why I prefer scripting languages... i.e. languages where anything that's not part of the syntax is a command that gets executed.

**Comment by CharliePoole** [comment]
@rprouse I think I have it working with the latest changes, without the upgrade. We should do it soon after release anyway.
