### ISSUE TITLE
Upgrade Cake build to latest version

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1609]
Currently seems to be 0.13

**Comment by ChrisMaddock** [comment]
When this get's done, it might be nice to also make use of cake-build/cake#908. :-)

**Comment by CharliePoole** [comment]
@ChrisMaddock I agree!

**Comment by ChrisMaddock** [comment]
#1615 should probably be investigated before this. :-)

**Comment by ChrisMaddock** [comment]
It's probably worth now waiting for Cake v15, which I believe is coming soon. It will have required fixes for  cake-build/cake#908, and also full error messages from the NUnit3 tool, which might make it a preferable alternative. 

This might even be better done with a bit of a refresh, post-split.

**Comment by CharliePoole** [comment]
Seems fair. BTW, I'm using Cake 0.14 for the teamcity extension and having some issues with mono 3.2.8. So we'll need to see if that gets fixed.

**Comment by ChrisMaddock** [comment]
Good to know.

Reopening this issue as I presume closing it was accidental?

**Comment by CharliePoole** [comment]
@ChrisMaddock Some of us can't use Cake 16+ due to a bug. I've been using 15.2 in all the latest updates to other projects. NUnit-Console and our own four extensions have now been updated to use the latest bootstrap scripts from Cake as well as having tools/packages.config updated to 15.2. You may be able to simply copy .gitignore, build.sh and build.ps1 from those projects.

**Comment by ChrisMaddock** [comment]
Thanks Charlie - I'd been using 16.1. Will go back a version!

**Comment by ChrisMaddock** [comment]
@CharliePoole - looks like Cake 16.2 has just been released today. 

Was this the bug you were referring to: https://github.com/cake-build/cake/issues/1247? I'll go ahead using 16.2 if it's fixed, else I'll stick to 15.2.

**Comment by CharliePoole** [comment]
No. It's an issue I discussed in chat. I should file an issue report on it.

In any case, I think it's best to get everything on the same level, then
continue to upgrade things in sync. I'm working on something to facilitate
that.
