### ISSUE TITLE
Refactor dependencies in build.cake

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1610]
The biggest problem here is that some actions depend on Build while others don't. I'd like to use this issue to discuss and decide how we want things to work for devs who build, test and package from the command-line and then implement any changes.

Key issues:

 * Packaging does _not_ depend on Build. I did it that way initially because I was working on packaging a lot and didn't want to rebuild each time in order to test packages. We could have a BuildAndPackage command, of course. Or we could make Package depend on Build and have a JustPackage or PackageOnly or TestPackage command.

 * Individual framework tests like Test45 do not depend on building. All other test commands depend on the full build, whether they need it or not. We should decide how we want this to work in a standard way. For me, if I am modifying and testing the console runner, I don't want to wait for every framework to rebuild.

@nunit/core-team Please add your comments, including any other issues you see.

**Comment by jasonwilliams200OK** [comment]
Just my $0.2 for perhaps future consideration:

We can look into using `dotnet pack` and `dotnet publish` commands of dotnet-cli project, which work for net20 to net462 and netstandard1.0 to netstandard1.5. Then we won't be needing cake to manage the build; the entire manifest targeting multiple frameworks will reside in one JSON file per project: project.json -- and dotnet-cli commands are executable on multiple PJs in batch at once (e.g. `dotnet build **/project.json`).

**Comment by CharliePoole** [comment]
@jasonwilliams200OK This bears looking at but might be a bit of a separate issue. :-)

No matter what tech we use for our builds, we need to decide how we want the commands to work. Note that I'm expressly targeting work by developers on their own machines here. When it comes to CI builds, it's less of an issue because you always want to do everything.

This will get simpler when framework, engine, console and extensions are not all being built together. Well, simpler in one way anyway. :-)

**Comment by ChrisMaddock** [comment]
> Individual framework tests like Test45 do not depend on building. [...]

I personally only ever run `TestAll`, but I'd want `Test45` to rebuild that project also. Agreed the best way may be to have each `TestX` task depend on the relevant `Build` task, and `BuildAll`/`TestAll` target tasks as they currently do. 

I never touch packaging with NUnit. My build scripts would always have packaging depend on build/test, but if there's still a common need to repackage without building, then it seems sensible for that to be default.

**Comment by rprouse** [comment]
We do not have a dependency between packaging and building at the moment. Our current release process builds everything, runs initial tests, then packages. Because we have so many projects and dependencies, there are often minor packaging errors that creep in between releases. It is much easier to not have to rebuild and retest binaries to fix packaging errors. The release already takes way too long to do :smile: 

Once we split projects back out into separate repositories, we might want to look at automatically building, testing and packaging, but as it stands, that is a project for at least 3.6.

@jasonwilliams200OK I like the idea of switching the various framework builds over to the `dotnet` toolchain and have been planning on experimenting when I add a .NET Core target. I like the idea of one project that targets all of the current platforms rather than the multiple that we currently have, but I believe it will also lock our developers into newer versions of Visual Studio which we will need to discuss.

**Comment by CharliePoole** [comment]
I've been caught a few times lately testing packages that were not up to date. I think for most purposes packaging should depend on build. It's only when I'm working on the script that generates the packages that I want faster turnaround. I could do that by editing the build.cake file but then I might check in the edit by mistake. So I guess some special target for packaging without building would make sense.

**Comment by rprouse** [comment]
@CharliePoole don't get me wrong, I want to get to the point where we just update a version number (or even better that is automatic to) and build the package target and we have a release ready to go. I think that will be more achievable once we split the repositories and don't have so many different packages being produced at once.

Maybe that is part of the theme for 3.6, deconsolidate? :smile:

**Comment by CharliePoole** [comment]
@rprouse Agree completely. However, this issue about dependencies doesn't have a lot to do with the CI or release builds we do with AppVeyor. For them, we have a special target that sequences the exact targets we always want to run. In this issue, I'm addressing needs of developers who run the script locally.

At the time I created the Package targets, I was (obviously) working on that part of the script, so I made it easy to run packaging without rebuilding. Now I think I should make it a little harder to do that because that's not what most people - or even me most of the time - work on. If you run Package, you should get a newly built package. When I do the PR, I'll pick some other target to mean JustPackageWithoutRebuilding and we can debate what to call it, but it should be something that  will lead you to __only__ use it if you are testing packaging as opposed to testing the package itself.

**Comment by CharliePoole** [comment]
I added this to the "Split nunit" Epic because the build script contains multiple dependencies across the projects we want to split. Some of them are directly fixable in the script and others are implicit. For example, if you only build the engine and test it, without building everything else. All our DirectoryFinder tests fail, because they look at the entire project directory structure. Hence, the script is a good thing to work on, because it will highlight other problem areas.
