### ISSUE TITLE
.Net 4.6.1 and Nunit 3.2.1 not running tests

### ISSUE THREAD

**Issue by kamran-pervaiz** [nunit/nunit#1625]
Hi Guys,

I have created a very dummy test class and i am trying to run the unitTests.dll using Nunit console runner but it's giving below info(error)

> Invalid : C:\Projects\ethical_resourcing\src\EthicalSourcing.Client.Services.UnitTests\bin\Release\EthicalSourcing.Client.Services.UnitTests.dll
> No suitable tests found in 'C:\Projects\ethical_resourcing\src\EthicalSourcing.Client.Services.UnitTests\bin\Release\EthicalSourcing.Client.Services.UnitTests.dll'.
> Either assembly contains no tests or proper test driver has not been found.

I have installed VS 2015 Enterprise and created a unit tests proj. First problem was using VS test classes, so I installed Nuget NUnit and below is my code

```
using System.Collections.Generic;
using System.Linq;
using EthicalSourcing.Client.Services.Controllers;
using NUnit.Framework;

namespace EthicalSourcing.Client.Services.UnitTests.Controllers
{
    [TestFixture]
    public class HomeControllerTest
    {
        [Test]
        public void Get()
        {
            // Arrange
            HomeController controller = new HomeController();

            // Act
            IEnumerable<string> result = controller.Get();

            // Assert
            Assert.IsNotNull(result);
            Assert.AreEqual(2, result.Count());
            Assert.AreEqual("value1", result.ElementAt(0));
            Assert.AreEqual("value2", result.ElementAt(1));
        }

        [Test]
        public void GetById()
        {
            // Arrange
            HomeController controller = new HomeController();

            // Act
            string result = controller.Get(5);

            // Assert
            Assert.AreEqual("value", result);
        }

    }
}

```

my powershell script is below

```
cd C:\Projects\ethical_resourcing\src\

# Set nunit path test runner
$nunit = "C:\Projects\tools\nunit\3.2.1\bin\nunit3-console.exe"
$tests = (Get-ChildItem -Recurse -Include "*Tests.dll" -ErrorAction SilentlyContinue | Where-Object { $_.FullName -match 'bin\\release' })

Write-Debug $tests


& $nunit --framework:"net-4.5" --out="C:\Projects\ethical_resourcing\src\_release\Tests.nunit.xml" $tests
```

If i use net-4.6 it gives error that unknown framework so I used net-4.5 but it's still giving same error. any suggestion would be great. I am not sure if it's NUnit 3.2.1 issue or anything else.

**Comment by CharliePoole** [comment]
Are you sure your tests are referencing nunit 3? That message us what you would get if they reference nunit 2 without the v2 driver extension installed.

**Comment by kamran-pervaiz** [comment]
![image](https://cloud.githubusercontent.com/assets/2331946/16382834/65458608-3c7a-11e6-97cb-7de2b66e3cc6.png)

yes I referenced the latest assembly

**Comment by CharliePoole** [comment]
Can you echo the entire command-line as it is being created?

**Comment by kamran-pervaiz** [comment]
when I hard coded the string to dll it seemed to work, so power lies not in nunit rather powershell script

$tests = (Get-ChildItem -Recurse -Include "*Tests.dll" -ErrorAction SilentlyContinue | Where-Object { $_.FullName -match 'bin\\release' })

the solution was below line in PS version 4

$TestDlls = Get-ChildItem -Path $SolutionFolder -Recurse  -Include $TestsPattern | Select-Object -expandproperty FullName | Where {$_ -NotLike "*\obj\*"}

thanks for your help.
