### ISSUE TITLE
Could not load file or assembly NUnit.System.Linq when running under .net Framework 2

### ISSUE THREAD

**Issue by NikolayPianikov** [nunit/nunit#1631]
[ICanRunTestForDifferentPlatforms_Version20_AnyCpu_System.String[].zip](https://github.com/nunit/nunit/files/336959/ICanRunTestForDifferentPlatforms_Version20_AnyCpu_System.String.zip)

**Comment by NikolayPianikov** [comment]
See integration tests [here](http://win10nik.cloudapp.net/viewType.html?buildTypeId=NUnit_NUnit3IntegrationTests).

**Comment by CharliePoole** [comment]
Doesn't seem like a bug. NUnit.System.Linq.dll isn't in the mocks directory.

**Comment by NikolayPianikov** [comment]
Ok, but it works under 4.5 and 4.0

**Comment by CharliePoole** [comment]
See the release notes... we bundle a basic System.Linq implementation with the 2.0 build so that we can remove some of our #if statements. Originally it was right in the nunit.framework source but we just moved it to a separate assembly. You have it in your nunit directory but not in mock.
