### ISSUE TITLE
NUnit addins configuration

### ISSUE THREAD

**Issue by BlackGad** [nunit/nunit#1634]
Is there any way to setup addins folder via command line?

I have same error like here (https://github.com/nunit/nunit/issues/1551) 
1) Invalid : C:\TeamCity\buildAgent\temp\buildTmp\fHz0v8K0KeWMqFUeAGIjXbAG22pExfA3.nunit
File type is not supported

With 3.2.1 runners there was default addins configuration in runner tools folder. Now with 3.4 default addins configuration is gone. So i need to place it somehow into nuget packages folder. Is it reasonable to add command line param -addins "addins path with wildcard"?

**Comment by rprouse** [comment]
I don't have the issue number because I am on my phone, but the issue with TeamCity has been fixed and we are trying to get a 3.4.1 hotfix out today. The addin probing doesn't need an addin file for NuGet in 3.4. The issue was a mistake in the TeamCity extension.
