### ISSUE TITLE
What about adding an overload to Assert.AreEqual() that takes a Func<object, object, string>

### ISSUE THREAD

**Issue by JohanLarsson** [nunit/nunit#1637]
I'm thinking:

```
[Test]
public void Foo()
{
    var expected = 1;
    var actual = 1;
    Assert.AreEqual(expected, actual, GetCustomErrorMessage);
}

private static string GetCustomErrorMessage(object expected, object actual)
{
...
}
```

I often miss this for CollectionAssert where it would be nice to print out the entire lists above each other if they are short.

**Comment by appel1** [comment]
Perhaps you can use TestContext.AddFormatter, https://github.com/nunit/docs/wiki/TestContext, to customize how your collections are formatted if they are short or fall back to the default behavior when they are not.

**Comment by CharliePoole** [comment]
I think this pretty much duplicates #144 but I'm not sure what you are asking for will actually serve your purpose so let's keep this open for a few beats.

The third argument to the assert is the user message, which appears before the standard NUnit "Expected: ... But was: ..." message. It sounds like you would actually like to replace the layout of how both expected and actual values are displayed.

If that's the case, then @appel1 's suggestion will do the job. Adding your own formatter would replace the content of the expected and actual values as shown by the standard message. It also has the advantage of not being evaluated unless the assertion fails.

The only drawback of TestContext.AddFormatter is that the formatter will be used for all assertions, not just EqualTo constraints. This might produce more output than you want in some situations. I suggest you experiment with it and come back with your thoughts on whether it does the job or if something else is required.

**Comment by JohanLarsson** [comment]
@appel1 Thanks for the link, didn't know about that one. Without trying it could be a bit heavy.

**Comment by CharliePoole** [comment]
@JohanLarsson Actually, the code you would write to format it would be pretty much the same you would write if we supported the use of a Func returning the user message. Basically, you take a value and return a string to represent it.

**Comment by JohanLarsson** [comment]
Ok, I'll look into it, thanks.

**Comment by rprouse** [comment]
@JohanLarsson I am closing this since there haven't been any updates. Please comment and reopen if you feel I shouldn't have closed the issue.
