### ISSUE TITLE
Passing command line parameters to tests

### ISSUE THREAD

**Issue by nadvolod** [nunit/nunit#1643]
Hello,

I looked through some notes here, but I am still unclear regarding if this is possible. So I apologize in advance if this has already been resolved.

I would like to be able to pass command line parameters to my tests to run in different environments for example. Like dev, test, prod. I'm running functional tests, so this is necessary for me. What is the best way for me to do this with NUnit?

Thanks a lot for your help.

**Comment by CharliePoole** [comment]
This duplicates #720, which was completed and released in NUnit 3.4.

In the docs, see the command-line paramters page or the format of the --params option and the TestContext page for how to access them in your tests.
