### ISSUE TITLE
.Net 4.5.2 System.Lazy<> conflicts with nunit 3.4.1 System.Lazy<>

### ISSUE THREAD

**Issue by robsonj** [nunit/nunit#1644]
Looks like an issue introduced with v3.4.1. We're experiencing compilation errors due to a usage of System.Lazy<> in our test infrastructure. It is conflicting with the nunit version.

Any pointers on how to resolve this please?

**Comment by CharliePoole** [comment]
We need some more info as to how NUnit.System.Linq is being referenced in your 4.5.2 test. We only use it for .NET 2.0.

**Comment by robsonj** [comment]
Aaarg, we resolved it thank you. Our devop's dept. added the .Net 3.5 version into our dependency management system. Sorry about that!
