### ISSUE TITLE
Can't load 'System.Runtime' assembly from 'nunit3-console' but can from 'NUnit3TestAdapter'

### ISSUE THREAD

**Issue by jcansdale** [nunit/nunit#1650]
The following test fails when run with 'nunit3-console.exe', but passes with NUnit3TestAdapter or TestDriven.Net. I've been stuck on this for a while and can't figure out what's different in the console environment!

```
[Test]
public void LoadSystemRuntime()
{
    Assert.DoesNotThrow(() =>
        Assembly.Load("System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")
    );
}
```

Any ideas?

**Comment by CharliePoole** [comment]
Security? What gets thrown?

**Comment by CharliePoole** [comment]
Also, there could be version differences. Until last week, the latest adapter was behind the latest NUnit release.

**Comment by jcansdale** [comment]
It's actually not specific to the nunit-console app. The same thing happens if you call it directly from a console application project.

`
{"Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.":"System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"}
`

What I can't figure out it why it works when called from inside the Visual Studio or TestDriven runners. I don't think it's to do with the Target Framework, x64/x86 or thread apartment model. There must be some other magic going on.

**Comment by jcansdale** [comment]
Here is a fusion dump:

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at ConsoleApplication1.Program.Main() in C:\scratch\temp\ConsoleApplication1\ConsoleApplication1\Program.cs:line 18

=== Pre-bind state information ===
LOG: DisplayName = System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/scratch/temp/ConsoleApplication1/ConsoleApplication1/bin/Debug/
LOG: Initial PrivatePath = NULL
Calling assembly : ConsoleApplication1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\scratch\temp\ConsoleApplication1\ConsoleApplication1\bin\Debug\ConsoleApplication1.vshost.exe.Config
LOG: Using host configuration file:
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: Attempting download of new URL file:///C:/scratch/temp/ConsoleApplication1/ConsoleApplication1/bin/Debug/System.Runtime.DLL.
LOG: Attempting download of new URL file:///C:/scratch/temp/ConsoleApplication1/ConsoleApplication1/bin/Debug/System.Runtime/System.Runtime.DLL.
LOG: Attempting download of new URL file:///C:/scratch/temp/ConsoleApplication1/ConsoleApplication1/bin/Debug/System.Runtime.EXE.
LOG: Attempting download of new URL file:///C:/scratch/temp/ConsoleApplication1/ConsoleApplication1/bin/Debug/System.Runtime/System.Runtime.EXE.
```

**Comment by KirillOsenkov** [comment]
Looks like they have a custom handler for `AppDomain.CurrentDomain.AssemblyResolve`. Look in:
`C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\Extensions\Microsoft.VisualStudio.TestPlatform.Extensions.VSTestIntegration.dll`, `Microsoft.VisualStudio.TestPlatform.MSTestFramework`. It has an OnResolve() method that grovels through search paths.

**Comment by jcansdale** [comment]
@KirillOsenkov Thanks for looking into this!

It turns out there *was* some magic going on, but it wasn't anything the test runners were doing. I have TypeMock installed and this was injecting itself into the test runner processes (but not console apps). It appears to look for any system assembly loading and automatically resolve them to the current version number. This makes calls like `Assembly.Load("System, Version=666.0.0.0")` and `Assembly.Load("System")` work that never normally should!

This conspired to make some code that reads the `TargetFrameworkName` attribute of an assembly work with .NET Core assemblies when it shouldn't have. It now works fine when TypeMock isn't loaded with some `AssemblyResolve` events. :rocket:

@CharliePoole Sorry for the false alarm. :blush:
