### ISSUE TITLE
Too little information passed on ReflectionTypeLoadException in DefaultTestAssemblyBuilder.GetCandidateFixtureTypes

### ISSUE THREAD

**Issue by chm-tm** [nunit/nunit#1651]
When a required assembly isn't found, an exception like this is thrown by the Console Runner and framework 3.4.1:
```
    1) Invalid : [...]\UnitTestProject1.dll
    Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
```
Since I didn't initially guess the root cause, I used the NUnit source code to track down the `ReflectionTypeLoadException`, which is thrown in `DefaultTestAssemblyBuilder.GetCandidateFixtureTypes` upon calling `GetTypes` on `assembly`.
It would be helpful to propagate information from the `LoaderExceptions` into the test result.
Repro sample project: [UnitTestProject1.zip](https://github.com/nunit/nunit/files/351691/UnitTestProject1.zip)

**Comment by ChrisMaddock** [comment]
This has been brought up before as #1238. Will close this issue as a duplicate, the sample project should be useful for whoever eventually works on it however - good shout!
