### ISSUE TITLE
Need an ordered collection equivalent constraint

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1654]
@jnm2 commented on [Thu Jul 07 2016](https://github.com/nunit/docs/issues/82)

The current `CollectionEquivalentConstraint` does an unordered comparison ([docs](https://github.com/nunit/docs/wiki/CollectionEquivalentConstraint)). I need an ordered comparison. I do this a lot; in fact, I can't imagine a scenario in which I would ever want an unordered comparison.

For an `IEnumerable` to be equivalent to (replaceable by) another `IEnumerable`, they should return the same value as each other after each enumerator `MoveNext`. That's just the way the `IEnumerable` contract is.

Expanding to consider lists in general, equivalence doesn't really carry a connotation of being unordered or ordered (that I know if) so I don't like the ambiguity. I think this would probably be better:

```c#
Assert.That(list, Is.EquivalentInThisOrder(new[] { ... }));
Assert.That(list, Is.EquivalentInAnyOrder(new[] { ... }));
```

Or this, which feels more natural and more clear to me:

```c#
Assert.That(list, Has.ItemsInExactOrder(new[] { ... }));
Assert.That(list, Has.ExactItemsInAnyOrder(new[] { ... }));
```

I think it's better than a `bool ordered` parameter added to `Is.EquivalentTo`. What do you think?

**Comment by CharliePoole** [comment]
The nunit/docs repo is for documentation issues. Since this relates to a change in the software, I moved it here.

It sounds like you want us to change the meaning of Is.EquivalentTo to match what we do for Is.EqualTo in the case of enumerables. Why not just use Is.EqualTo?

I haven't checked the exact dates, but off the top of my head I would say that collection equality meaning "having the same content in the same order" has been in NUnit for about 15 years and "equivalence" meaning "having the same content without regard to order" for about 10. It would disrupt a lot of things if we were to change it now, although we probably could have considered it in the transition from 2.x to 3.0 - we didn't however. :-(

**Comment by jnm2** [comment]
My bad about the placement, didn't think to check.

`Is.EqualTo` is not comparing equal contents. It's giving me an error saying the types don't match. I assume from its name and the fact that it cares about the specific types that it's more of an `object.Equals` type comparer. The docs referenced `Is.EqualTo` but it's not clear if it's talking about comparing item equality or actually comparing native equality. Given my outcome, I assumed it must be the latter.

To be clear I *don't* think it would be a good idea to change 15 years worth of standing semantics! If `Is.EqualTo` works, that's great. Not as clear as `Has.ItemsInExactOrder` but I can live with that. Doing some digging to see why `Is.EqualTo` isn't working. Maybe I need to file bug report.

**Comment by jnm2** [comment]
Ehhhhm... so this is embarrassing: I was doing `Is.EqualTo(new { item1, item2 })` instead of `Is.EqualTo(new[] { item1, item2 })`. NUnit is fine. I just passed over `Is.EqualTo` too quickly.

Now if we had a type-safe method, like say `Has.ItemsInExactOrder(IEnumerable)`, that couldn't happen. ;-) Actually, I was going to ask if there could be a `params object[]` version as well to save on typing. What's your opinion on that?

**Comment by CharliePoole** [comment]
The docs do explain this at https://github.com/nunit/docs/wiki/EqualConstraint but you are far from the first person to miss it! I think it's because people don't automatically think they need to read what equality means. But NUnit has always defined things from the point of view of "What's useful in writing a test?" rather than "What is the standard mathematical meaning of  X?" For example, you should read how we handle the comparison of NaN. :-)

In this case, we asked ourselves, "What would somebody typically want when comparing two arrays?" Object equality is covered by Is.SameAs, so they must want something else. In later versions of NUnit, this got extended to collections and finally all enumerables. And finally,  there's all those years of doing it a certain way.

We can transform this into a request for a params argument to Is.EqualTo if you like. It wouldn't have to go any deeper, just a bit of syntactic sugar to pass in an array. I'd have to look at the code to see if it should be object[] or a generic - depends on the other overloads.

**Comment by jnm2** [comment]
Here's my only concern with `params` on `Is.EqualTo`- if you have code with `Is.EqualTo(a, b, c)`, sooner or later you'll have nearby code with `Is.EqualTo(a)` which will not pick the params overload, but in your head it will match the pattern you used with the multiple item cases. Contrast that with `Has.ItemsInExactOrder(a)`.

**Comment by CharliePoole** [comment]
Yeah, I think you have a point there with the overload.

String doesn't have any ambiguity for us because we treat it as a string explicitly. But it can seem ambiguous to users sometimes.

I'm thinking there's nothing to do here. :-(

**Comment by jnm2** [comment]
I'm sorry for the goose chase but I really do appreciate your quick responses.

If you don't mind, I think it would be good to update [CollectionEquivalentConstraint](https://github.com/nunit/docs/wiki/CollectionEquivalentConstraint) and change the Notes section to:

> To compare items in order, use Is.EqualTo.

That would have confirmed which path to zone in on, since it's less obvious from the API itself.

**Comment by CharliePoole** [comment]
Done!

**Comment by jnm2** [comment]
Heh this is an insignificant nitpick but `Is.EqualTo()` refers unambiguously to a specific overload which happens to be unambiguously incorrect in this case, whereas `Is.EqualTo` refers to a method group.

**Comment by CharliePoole** [comment]
True enough... not changing... :-)
