### ISSUE TITLE
Cancelled test run may not signal completion

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#166]
`When a test run is cancelled under NUnit using the Parallel dispatcher, it may terminate without the Completion event ever being called. Currently, our test of cancellation uses a time delay to make the test pass, but this won't be sufficient when we have a Gui and the user is able to cancel a test run.

We need to ensure that the event is signalled in all cases after the cancelled test has terminated and a result is availble.

**Comment by CharliePoole** [comment]
Marking this low-priority to simplify our bookkeeping. We can increase the priority when we get to the GUI.

**Comment by oznetmaster** [comment]
BTW.  This happens with the Simple dispatcher as well.

**Comment by oznetmaster** [comment]
I made a bunch of comments on the now closed issue #1187 , which I will not repeat here.

**Comment by CharliePoole** [comment]
@oznetmaster You self-assigned this back in January and indicated you had started. It's still shown as "In Progress." Are you still working on it?

**Comment by CharliePoole** [comment]
@oznetmaster Repeating the previous question... are you still working on this? 

I actually kind of doubt it but since I think it's policy (as well as common courtesy) that only the assignee or the project lead will remove somebody's assignment, perhaps you could do something about it.

**Comment by CharliePoole** [comment]
@framework-team @rprouse 

I was about to report this issue but something told me I may have reported it before, and indeed I did. The issue was impacting development of theTestCentric GUI and it still is. To a lesser degree it continues to impact the engine and console runner.

History:
I created the issue in 2014
@oznetmaster self-assigned it in 2016
In 2019 I asked @oznetmaster to remove himself if he wasn't working on it.
Nothing else. No others have even commented on it.

I marked this it a bug when I reported it but I don't know whether the @nunit/framework-team agrees with that or if you are taking the position that cancelled tests should __not__ report completion and runners should just deal with that. I recognize that is a possible point of view although I don't happen to agree with it. Even so, it would be nice to know and then see this closed.

Even better, from my point of view, would be to see the issue worked on and resolved. :smiley:

**Comment by rprouse** [comment]
> Even better, from my point of view, would be to see the issue worked on and resolved. 

I think that we could ensure that cancellation is sent and then do our best to clean up, so I think that this is still a worthwhile issue.

**Comment by CharliePoole** [comment]
Because I'm working on this in the context of the GUI it would be very valuable if somebody verified it with either the console runner or nunitlite. If nobody else does, I'll try to get to it soon.

**Comment by OsirisTerje** [comment]
@oznetmaster Hi!  Been some time here, but any chance for a revisit to this item?

@manfred-brands  This is close to what you have been working on.  Should you have a look?

**Comment by manfred-brands** [comment]
@OsirisTerje There are tests for this` TestAssemblyRunnerTests.StopRun_WhenTestIsRunning_StopsTest`
However, Cancelling a test is only supported on .NET Framework 
If done on .NET Core or later, which has no `Thread.Abort` the operation is a NoOp.
As it does nothing, the test state is hence not set to `Cancelled`.

The `ParallelWorkItemDispatcher` eventually uses `SimpleWorkItem` workers which are cancelled.
It waits for each of the workers to finish and then sets each of those to Cancelled.

There was a commit (40c6afdc9bc7066c69309dce78dc97ec198128c7) 5 years ago, by @CharliePoole that added that last code with the message: _Dispatcher cleans up all unfinished tests_ which could have addressed the original problem.

**Comment by CharliePoole** [comment]
FWIW I wrote the PR as a contributor and called it "a start on fixing" the problem. Since I was no longer a member of the team at the time, I figured others would decide whether it should  be merged or not. Even so, I was quite surprised when an inactive member merged it without waiting for further comments from the team.

In any case, this issue is now over nine years old and any substantive details are now out of date. If I were you, I'd close it and ask folks to create new issues for any residual problems.

**Comment by mikkelbu** [comment]
I think Charlie's comment makes sense, so I'll close the issue.
