### ISSUE TITLE
A call to nunit3-console.exe to test a x86 assembly compiled for net3.5 hangs

### ISSUE THREAD

**Issue by LarsMengel** [nunit/nunit#1662]
A call to nunit3-console.exe to test a x86 assembly compiled for net3.5 runs in an infinte loop(?) when called from a working directory other than the assemblies directory.

I did some experiments with cake. All unit testing worked well until I tried to run my cake script with one of our older x86 net3.5 projects. After some reserach I found the original call in my TestResult.xml.
Here is the call:
....\tools\nunit3-console.exe "myUnitTest.Project/bin/Release/UnitTest.Project.dll" "--result=mySolutionPath/BuildResults/TestResult.xml"

I tried to run Nunit3-console.exe using the same call twice both on a Windows7 64 bit machine.
In the first run my current directory was the solution directory. That resulted in an infinite loop. The only entry logged to the result file is the command line above.
In the second run my current directory was the test assemblies directory (myUnitTest.Project/bin/Release/). All worked well.

I could be happy with that but unfortunately I´m not able to run Nunit3-console.exe from a specific working dirctory calling it from a cake script. The WorkingDircetory property of the Nunit3Settings class in cake seems to change nothing.

**Comment by LarsMengel** [comment]
The Version of Nunit3-console.exe is 3.4.1.0

**Comment by rprouse** [comment]
The NUnit unit tests run using Cake from the solution directory calling into the bin directory like yours and we have .NET 3.5 tests,  so I doubt this is a common problem.

Is there anything different about your .NET 3.5 tests compared to your other tests? Does it do any file access that might be retrying and failing? Are you sure it is in an infinite loop and not blocking? Can you create a small test suite that reproduces the behaviour that we can debug?

**Comment by CharliePoole** [comment]
Beginning with NUnit 3.0, NUnit does nothing whatsoever to affect the current directory. It never sets or changes it. NUnit 2 previously set the current directory, but we removed that in preparation for running tests in parallel and NUnit now runs with the cd set just as it was when NUnit is initiated.

From your description, it sounds as if you are using the Cake NUnit3 tool. It would be up to the tool to set the cd to the specified working directory. As @rprouse says, we use Cake for NUnit's own tests. However, we don't use the NUnit3 tool. Rather we call nunit3-console as directly using the StartProcess method. That may be a workaround for you as well.

**Comment by CharliePoole** [comment]
@rprouse I left the confirm label on this, but I don't think there is really anything to confirm or fix. NUnit has nothing to do with what the CD is set at once it is run.

**Comment by rprouse** [comment]
@CharliePoole I agree with you on the working directory. I would just like more information on what **hang** means and be sure it has nothing to do with NUnit.

**Comment by CharliePoole** [comment]
Fair enough. It seems unlikely that `--verbose` would be causing that in itself though. Do other arguments listed after `--` pass OK without causing an issue?

**Comment by rprouse** [comment]
@CharliePoole are you thinking of the other `dotnet-test-nunit` issue or am I missing something?

**Comment by CharliePoole** [comment]
Sorry... posted in the wrong place.

**Comment by LarsMengel** [comment]
@rprouse: Yes these tests are accessing MsAccess files. The path to these files is a relative path.
Thinking about that this might be the problem. On the other hand I did my tests with different command line switches like --verbose and --labels=All. I never saw any labels until I set the timeout for each test. Is it possible to get some info on the output saying "Test 'whatsoever' has been started"?
I´ll try to create an example project with the same behavior and will let you know about the result.
By the way, I found a workaround by setting the TargetWorkingDir of the surounding DotCover-Session. Doing this Nunit is started using the given WD and all works well.

**Comment by LarsMengel** [comment]
Trying the debug switch of the Nunit console runner I found the problem. The code I was testing with contains a little sequence which tries to save to a specific file -which couln´t be found. Unfourtunately there is also a retry loop with a counter which is never incremented. => infinite loop
I´m sorry for blaming you for our internal code quality. :-(
Thanks for your advice and also thanks a lot for all your good work.
