### ISSUE TITLE
Find way to hide NUnit.Compatability.Path from intellisense

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#1663]
@jcansdale commented on [Wed Jul 13 2016](https://github.com/nunit/dotnet-test-nunit/issues/52)

The .NET Core version of `nunit.framework` contains a public class called `Path`. This shows up in intellisense at the top when you try to auto-complete a reference to `Path`. This can be annoying because `Path` is a commonly used class.

![compat](https://cloud.githubusercontent.com/assets/11719160/16804634/a3c3856a-4904-11e6-8f37-00d98200d810.png)

---

@rprouse commented on [Wed Jul 13 2016](https://github.com/nunit/dotnet-test-nunit/issues/52#issuecomment-232357771)

@jcansdale I am pretty sure it is gone in the latest versions on master. It was annoying me to, so I removed it from the compatibility classes in the portable driver because it wasn't really needed. It was left over from when the driver was a PCL.

I just searched the code and can't find it, but I'll leave this open until the next release just in case I'm blind :smile: 

---

@jcansdale commented on [Wed Jul 13 2016](https://github.com/nunit/dotnet-test-nunit/issues/52#issuecomment-232359236)

@rprouse,

This was with 'nunit.framework' v3.4.1 (lousy bug report missing that).

Good to hear you're on top of it. :smile: 

---

@rprouse commented on [Wed Jul 13 2016](https://github.com/nunit/dotnet-test-nunit/issues/52#issuecomment-232359917)

Ah, that is where it was coming from. Most people won't be including the NUnit.Compatibility namespace when using the PCL, but it should probably be internal anyway. We might also be able to drop it when we switch the PCL to .NET Standard. 

I am going to move this to the main NUnit repo. I am pretty sure it belongs there.

**Comment by CharliePoole** [comment]
The only way making this and other classes internal should mess us up is if NUnitLite is also using it through a reference to the framework.

**Comment by rprouse** [comment]
If NUnitLite is using the compatibility classes from the framework, we could make them InternalsVisibleTo. I set this as low priority though since it likely only affects NUnit developers who end up pulling in the NUnit.Compatibility namespace. It was annoying working on `dotnet-test-nunit` though as I kept having conflicts between the Compatibility.Path and the real Path and had to scope them.

**Comment by jcansdale** [comment]
(moved comment over here)

> Most people won't be including the NUnit.Compatibility namespace when using the PCL, but it should probably be internal anyway.

The problem is with intellisense, if you don't already have a `using System.IO`. This is compounded by the fact that `System.IO.Path` is in a separate assembly if you're using .NET Core (therefore appears further down the intellisense suggestions).

**Comment by jcansdale** [comment]
> If NUnitLite is using the compatibility classes from the framework, we could make them InternalsVisibleTo.

InternalsVisibleTo has given me so much pain over the years when trying to write tests that use other people's code. Microsoft seems to be particularly fond of it.

Another possibility is:
`[EditorBrowsable(EditorBrowsableState.Never)]`

**Comment by CharliePoole** [comment]
@jcansdale Now that you say it, it's the obvious solution.

**Comment by FantasticFiasco** [comment]
Is this PR still up for grabs?

**Comment by CharliePoole** [comment]
No more... it's yours now. :-) 

Since you're a contributor, I believe you can assign an issue to yourself, but I could be wrong.

**Comment by FantasticFiasco** [comment]
Oh, I didn't know. I'll try next time.
