### ISSUE TITLE
Visual Studio Test Explorer ignores [Explicit]

### ISSUE THREAD

**Issue by adamralph** [nunit/nunit#1664]
When invoking "Run All" in the VS Test Explorer, all tests are run, whether they have `Explicit` or not.

Is this a know problem?

**Comment by rprouse** [comment]
@adamralph this is a known issue that has been reported at nunit/nunit3-vs-adapter#47 if you want to track it there.  Please see that issue for more information.

**Comment by adamralph** [comment]
Thanks @rprouse

**Comment by CharliePoole** [comment]
Based on subsequent discussion, this is a separate issue from nunit/nunit3-vs-adapter#47. It has been moved and re-opened as nunit/nunit-vs-addapter#125
