### ISSUE TITLE
TeamCity does not parse service messages inside errors/output of tests

### ISSUE THREAD

**Issue by NikolayPianikov** [nunit/nunit#1672]
TeamCity now parses service messages inside other service messages, but only if original message was tagged with tc:parseServiceMessagesInside. Example:
##teamcity[testStdOut name='test1' out='##teamcity|[buildStatisticValue key=|'my_stat_value|' value=|'125|'|]' tc:tags='tc:parseServiceMessagesInside']

Such parsing is supported for the following types of service messages: message, testStdOut, testStdErr.

**Comment by CharliePoole** [comment]
@NikolayPianikov I don't understand this issue. How are such messages generated in the first place? NUnit doesn't create them. We give users the ability to write error messages, of course. Are you saying that users themselves may place TC service messsages in their own output for some reason?

**Comment by NikolayPianikov** [comment]
Yes, for example user could send some statistic to TC form his tests

**Comment by CharliePoole** [comment]
That's a real eye-opener! It completely changes my understanding of service messages, which I thought were __only__ generated by the extension.

Question 2 :-)...

How would the service messages become nested?

**Comment by NikolayPianikov** [comment]
When test writes something to the console we send message
##teamcity[testStdOut name='abc' out='Console output !!!|r|n' ...]

When test writes nested TC message to the console we send
##teamcity[testStdOut name='abc' out='##teamcity|[ ... |]' ... ]

**Comment by NikolayPianikov** [comment]
TC uses special tags to check nested messages to improve the perfomance

**Comment by CharliePoole** [comment]
So you are saying that the user might write something like...

```C#
Console.WriteLine("##teamcity..."); // 1
Console.WriteLine("Some output ##teamcity...."); //2
Console.Error.WriteLine("##teamcity..."); // 3
Console.Error.WriteLine("Some output ##teamcity...."); //4
```

Please tell me if you think the following is correct...

Example 1 and 2 would generate tc message as part of the output element of the test result. There would be no nesting in that case. The addin will send the message and it will also continue on as a part of the Xml output that NUnit generates.

Example 3 would generate a test-output event consisting entirely of the TC message, with Stream set to Error. There is no nesting.

Example 4 would also generate a test-output event consisting of some text followed by the TC message. There still seems to be no nesting as far as I can see.

I hope this helps you see why I am confused. :-) Where does the nesting come from?

**Comment by NikolayPianikov** [comment]
1 and 2 will be nested because these messages will be wrapped by ##teamcity[testStdOut name='abc' out='##teamcity|[ ... |]' ... ]

stdOut will be ignored by TC, because it could contain some useless strings

3 and 4 will not use any TC service messages and will not be nested
TC handle them without any TC service messages

**Comment by CharliePoole** [comment]
So for 1 and 2, it's your code in the extension that creates the nesting, correct?

For 3 and 4, I don't understand... they contain service messages starting with ##teamcity and I thought that handling them was the purpose of this issue.

Maybe we need to do a chat - either voice or text as you like. What do you think?

**Comment by NikolayPianikov** [comment]
@CharliePoole I am not in the city now and my internet connection is not good, so let's make a chat via Skype. My account is NikolayP

**Comment by CharliePoole** [comment]
Skipe is good. My id is cpoole98370... 

When is good for you - and what is your time zone anyway?

**Comment by NikolayPianikov** [comment]
@CharliePoole Time Zone +3, let's chat when my skype is online, from 10:00 to 23:00 in my TZ if it is possible

**Comment by CharliePoole** [comment]
@NikolayPianikov Is this still good after our discussion? If it's still needed, I'll merge.

**Comment by CharliePoole** [comment]
Issue moved to [nunit/teamcity-event-listener #6](https://github.com/nunit/teamcity-event-listener/issues/6) via [**ZenHub**](https://www.zenhub.com/)
