### ISSUE TITLE
InRange-Constraint must work with object

### ISSUE THREAD

**Issue by NUnitTester** [nunit/nunit#1674]
The following code does work even if myObj is from a class no special interface is implemented:

``` C#
Assert.That(myObj, Is.EqualTo(expcted).Using(myComparer));
Assert.That(myObj, Is.InRange(expcted1, expcted2).Using(myComparer));
```

There must be a inheritance of IComparable, or it does not compile.  (NUnit 3.4.1)
This is an error, because it must also work with objects.
- the type of myObj and expected1 I cannot change, because it is a external type from a library
- a comparer is supported, so it should work
- the constructor of InRangeConstraint calls the Compare-Methode of IComparable of expected1 not regarding the comparer in the Using to check the relation between from and to. This is a big bug in my eyes, using the wrong comparer.

**Comment by CharliePoole** [comment]
This has been the definition of RangeConstraint for many years. I take it you are saying that it should be sufficient for the two expected values to implement IComparable. Is that right?

Can you post a bit of code that shows what you would like to see working differently?

As possibly a second issue, I think you are saying that the comparer in Using is being ignored. Again, an example we can work from would help.

**Comment by NUnitTester** [comment]
First issue: There is no possible way that I can add a IComparable to a class because it is from a library or not useful in productive case. So I wrote a Comparer for NUnit-Test only wanting to be used in Range-Asserts.

`public class MyVersionClass /* : IComparable */
{
...
}

MyVersionClass expectedObject = ...;

Assert.That(myObject, Is.InRange(expectedObject, expectedObject)
    .Using(myComparer));`
Error, does not compile, but 
`Assert.That(myObject, Is.EqualTo(expectedObject)
    .Using(myComparer));`
does!

**Comment by NUnitTester** [comment]
Second issue: Look at the constructor of the RangeConstraint, then the error is obvious:

`public RangeConstraint(IComparable from, IComparable to)
      : base((object) from, (object) to)
    {
      **if (this.comparer.Compare((object) from, (object) to) > 0)
        throw new ArgumentException("from must be less than to");**
      this.from = from;
      this.to = to;
    }`
The Comparer ist called to check if from is not greater than to. Is is not right because the comparer given by using does give other results. And of cause, see issue 1, the objects should not be comparable at all. It should also work **only** with a given comparer in using.

**Comment by CharliePoole** [comment]
@NUnitTester 
First Issue: Does this work if you use `Is.GreaterThanOrEqualTo(from).And.LessThanOrEqualTo(to)`?

We should definitely handle these two expressions consistently.

Second issue: 
So, we are using the default comparer before it's replaced. That's an error for sure.

**Comment by NUnitTester** [comment]
`Assert.That(myObject, Is.GreaterThanOrEqualTo(from).And.LessThanOrEqualTo(to).Using(myComparer));`
Next Bug: myObject is < than _from_. Passes Assert because LessThanOrEqualTo uses not the given Comparer, only GreaterThanOrEqualTo.
Or is this expected in an other way?

**Comment by CharliePoole** [comment]
Yes, Using applies to each comparison separately due to the left-to-right processing of the expression. That's one of the main reasons for having a range constraint.

I think this definitely shows the problem as a bug. If the expanded expression works, the range expression is expected to work.

**Comment by JustinRChou** [comment]
Would it be possible to check if the user did use Using for objects that did not implement IComparable?

Or default it to a IComparer comparing on the ToString()?

**Comment by NUnitTester** [comment]
If `Using` is used, always the comparer given by using must be used. Only if there is no using at all, `IComparable` is used.
It is also a common case to give an other comparer for nunit as the implementation does by implementing `IComparable`.

In my eyes, the test, if `from` is smaller or equal `to `must be done later, not in constructor at all.

**Comment by JustinRChou** [comment]
I am going through this to see if my PR is missing anything.

So far InRange issue when passing objects without IComparer in the constructor is resolved. 

And using
`InRange(from, to).Using(myComparer)`
isn't producing a different result from `Is.GreaterThanOrEqualTo(from).Using(myComparer)).And.LessThanOrEqualTo(to).Using(myComparer)`

**Comment by NUnitTester** [comment]
Fine, I will look forward to the next release and see it in production.

**Comment by NUnitTester** [comment]
I'm not really glad with your tests:
`            Assert.Throws<AssertionException>(() =>
            {
                Assert.That(from, Is.InRange(testObj, to).Using(comparer));
            });
`
The lines seem to be for universal cases, but they are not! If testObj == from it will fail and this is an allowed option. That's only because things are mixed that should not. I will come back.
That's the next point. The number of testcases is too small. You have only one in the middle. 
from = 1, test = 30, to = 46
What about the cases test = from and test = to? And you also need tests beside the from and to.
You have tried to put these two principal cases (inside range and outside range) in one test. But each case should be separately. Positive and negative tests should not be merged. Thats my opinion.

**Comment by JustinRChou** [comment]
At that time, I was only thinking about testing the new constructor.
I didn't think it was necessary to do a coverage test since that shifts the focus to the comparer.

**Comment by NUnitTester** [comment]
Nevertheless, positive and negative tests are different cases and should never be merged in one case. The approach you have made is quite well with test cases, but try to add one with always the same object, from = to = test. The test is not written universal but used so.

**Comment by NUnitTester** [comment]
I have had a look at the implementation:

`        private ComparisonAdapter comparer = ComparisonAdapter.Default;

        /// <summary>
        /// Initializes a new instance of the <see cref="RangeConstraint"/> class.
        /// </summary>
        /// <remarks>from must be less than or equal to true</remarks> 
        /// <param name="from">Inclusive beginning of the range. Must be less than or equal to to.</param>
        /// <param name="to">Inclusive end of the range. Must be greater than or equal to from.</param>
        public RangeConstraint(IComparable from, IComparable to) : base( from, to )
        {
            // Issue #21 - https://github.com/nunit/nunit-framework/issues/21
            // from must be less than or equal to to
            if (comparer.Compare(from, to) > 0)
                throw new ArgumentException( "from must be less than to" );

            this.from = from;
            this.to = to;
        }
`

The constructors are different. This one does test from < to, the others don't.

Write an test with a class implementing IComparable and use Using with an reverse IComparable implementation. You will see, the copied constructor will fail. As I have said in the beginning, it is not allowed to do the from-to check in the constructor at all.

**Comment by NUnitTester** [comment]
The right position seems to me to be the three methods like
`public RangeConstraint Using(IComparer comparer)`

**Comment by NUnitTester** [comment]
Hi @ChrisMaddock: Sorry, I don't want to close it!

**Comment by JustinRChou** [comment]
That is a good point in moving the check from the constructor into the Using.
@nunit/core-team 
Would it be good to move 
```
if (comparer.Compare(from, to) > 0)
                throw new ArgumentException( "from must be less than to" );
```
into the Using methods and maybe ApplyTo as well? 
I really don't know about removing the IComparable constructors though.
