### ISSUE TITLE
Nunit-agent-x86 process never exits when created through TestEngineActivator API in 3.4

### ISSUE THREAD

**Issue by ethantang95** [nunit/nunit#1679]
When a test engine/runner is created through the TestEngineActivator API and after the test process finishes, the Nunit-agent-x86 process never exits and therefore is taking up memory still. On Task manager, it is listed as an active process.

This happens even after calling

`
            _testRunner.StopRun(false);
            _testRunner.Unload();
            _testEngine.Dispose();
`

The runner is invoked through this code

`
            var testPackage = new TestPackage(_assemblyInfo.AssemblyFullPath);
            AddTestParameters(testPackage, config);
            var filter = CreateTestFilter(config);

```
        _testEngine = TestEngineActivator.CreateInstance();
        _testRunner = _testEngine.GetRunner(testPackage);

        var listener = new RecordKeepingTestListener(_assemblyInfo.Assembly, this);

        var result = _testRunner.RunAsync(listener, filter);
```

`

The tests themselves do successfully finishes and no uncaught exceptions are thrown in this process. In this case, the same test package can then be ran again through the TestEngineActivator but the old test package process is still in memory

**Comment by ChrisMaddock** [comment]
Issue moved to [nunit/nunit-console #296](https://github.com/nunit/nunit-console/issues/296) via [**ZenHub**](https://www.zenhub.com/)
