### ISSUE TITLE
NUnitLite under .net core doesn't support TeamCity output

### ISSUE THREAD

**Issue by damageboy** [nunit/nunit#1681]
Hi,
When compiling a project with NUnitLite under a full .NET Framework, the `--teamcity` option exists.

When trying to run the same project compiled for .NET core, the `--teamcity` option is gone.

Digging into the code, @ [CommandLineOptions.cs:379](https://github.com/nunit/nunit/blob/8927ec6f6c4977531b241749adc08170b3af8f91/src/Common/nunit/CommandLineOptions.cs#L379) and the surrounding area, it's pretty clear that under PORTABLE compilation, the `--temcity` command line option, and perhaps more code around it is left out of the compilation of the NUnit Engine...

Is it possible to bring back more options when compiling with NUnitLite?

Perhaps, it for general Portable build adding the teamcity addin is impossible, it might make sense to provide explicit `netstandard` builds of NUnit that add back more functionality lost with completely `PORTABLE` builds?

**Comment by CharliePoole** [comment]
At first glance, there appears to be no serious reason why the option can't be supported in the portable framework build. It was left out mainly because it takes a little refactoring and there was no particular call for it.

In the longer term, a netstandard build is in the cards.
