### ISSUE TITLE
Existence of SerializableAttribute in .NET Core

### ISSUE THREAD

**Issue by FantasticFiasco** [nunit/nunit#1683]
I have a question regarding the class `SerializableAttribute` that is being part of _nunit.framework.dll_ for .NET Core.

I do understand that the class is a shim or polyfill (I don't really know the different) for .NET Core, because I've added the class myself in the assembly I am writing. My problem is that I get a compiler error stating that the class exists both in _nunit.framework.dll_ and in my assembly. I can of course remove my declaration of  `SerializableAttribute` and reference NUnit from my assembly, but it feels wrong to reference something intended for tests.

That do you propose me to do?

**Comment by CharliePoole** [comment]
Maybe we shouldn't have it in the framework. It's only purpose is so that we don't have to use conditonal complilation every place the attribute is used.

**Comment by FantasticFiasco** [comment]
Yes, that is the same purpose I have it in my assembly. One almost wishes that there was a shim/polyfill NuGet package we could both reference.

**Comment by FantasticFiasco** [comment]
Another possible solution would be that you mark the attribute as internal. I would be happy to produce a PR if you consent.

**Comment by CharliePoole** [comment]
Seems like a good idea if you're willing to create a pr.

**Comment by FantasticFiasco** [comment]
I'd be honored. I would like one clarification though, strictly speaking the PR would be considered a breaking change, if NUnit is following semver that would mean incrementing the major version, or am I wrong?

**Comment by CharliePoole** [comment]
I don't think it's a breaking change. We only treat something as a breaking chnage if it modifies a Type or method that we have exposed _intentionally_ for use by users. NUnit has a long histrory of internally used classes and methods being public, which we are in the process of getting away from.

In any case, you don't have to worry about versioning in doing a PR. That happens when we do a release.

**Comment by CharliePoole** [comment]
Closed via PR #1691
