### ISSUE TITLE
Invalid links in CONTRIBUTING.md

### ISSUE THREAD

**Issue by FantasticFiasco** [nunit/nunit#1685]
There is at least one invalid link in _CONTRIBUTING.md_. I will happily do a PR with your consent.

**Comment by CharliePoole** [comment]
That would be great... Looking at it I saw three problem links...

"our documentation" should go to https://github.com/nunit/docs/wiki/NUnit-Documentation

"release notes" should go to https://github.com/nunit/docs/wiki/Release-Notes

The NUnit Dev Wiki no longer exists. The text should probably say something like "Please read through the developer section of the nunit documentation, linking "nunit documentation" the same url as the first link.
