### ISSUE TITLE
R# fails to run tests in assembly that references cecil

### ISSUE THREAD

**Issue by SimonCropp** [nunit/nunit#1686]
today i updated to a new beta build of the cecil nuget that has some breaking changes.

I am using the r# test runner (a version that is compat with nunit 3)

when i run i get this dialog

![image](https://cloud.githubusercontent.com/assets/122666/16971199/06b351e0-4e65-11e6-9a9f-ff8915da3212.png)

Which had me confused until i debugged into the test run and got this exception stack trace.

```
System.MissingMethodException occurred
  HResult=-2146233069
  Message=Method not found: 'Mono.Collections.Generic.Collection`1<Mono.Cecil.TypeReference> Mono.Cecil.TypeDefinition.get_Interfaces()'.
  Source=nunit.engine
  StackTrace:
       at NUnit.Engine.Services.ExtensionService.DeduceExtensionPointFromType(TypeReference typeRef)
       at NUnit.Engine.Services.ExtensionService.FindExtensionsInAssembly(String assemblyName)
  InnerException: 
```

So it seems in scanning for extensions is done in a appdomain that results in two conflicting versions of mono cecil to be loaded. 

Simplest fix i can think of is ILMerging cecil  into nunit.engine. thoughts

**Comment by jbevain** [comment]
Another simple fix is to build and ship a custom version of Cecil with a custom strong name using:

https://github.com/jbevain/cecil/blob/3b21b22e454faec782d1b21ad1e98b88fd297a2a/Mono.Cecil.settings#L75-L108

This is what Xamarin and VSTU are using to override the default Cecil build and avoid in VS conflicts.

**Comment by SimonCropp** [comment]
@jbevain in fody we work around it by doing the weaving in a custom appdomain. so we dont share the VS or MS build appdomain

**Comment by CharliePoole** [comment]
@SimonCropp Before looking for solutions, it would help to understand the problem better. The NUnit Engine does use reference mono.cecil. in the AppDomain in which it is running, normally the primary AppDomain. However, test code isn't loaded in that domain, which leads me to wonder how the conflict is actually arising.

**Comment by CharliePoole** [comment]
@SimonCropp Looking for more info to decide whether this is a bug for us or not. As far as I can figure out (see previous comment) there should be no way for user code to run in the same AppDomain as the engine, so I'd like to understand how that's happening in your case.

**Comment by jcansdale** [comment]
@jbevain, Do you set the `AppDomainSetup.ApplicationBase` of your custom app domain? This property defaults to the base directory of the process (nunit-console.exe in this case?), not the `ApplicationBase` of the current (test) app domain. I wonder if that could be causing the issue? (it has caught me out many times)

**Comment by SimonCropp** [comment]
so it seems this is specific to r# 

here is a repro https://github.com/SimonCropp/nunit_cecil_issue/

but it doesnt fail for NUnit 3 Test Adapter https://visualstudiogallery.msdn.microsoft.com/0da0f6bd-9bb6-4ae3-87a8-537788622f2d?SRC=VSIDE

**Comment by SimonCropp** [comment]
i will raise an issue with jetbrains and link back here

**Comment by SimonCropp** [comment]
link back https://youtrack.jetbrains.com/issue/RSRP-459932

**Comment by SimonCropp** [comment]
@CharliePoole up to u if u want to keep this open as a track back?

**Comment by rprouse** [comment]
I am closing this since it is not our bug and therefore shouldn't be on our radar. People can still find it if they have the same issue...
