### ISSUE TITLE
How can I set the same Timeout to the whole solution/for each tests?

### ISSUE THREAD

**Issue by kam1k** [nunit/nunit#1688]
I want to set the same [Timeout(x)] for each tests in my solution. Solution includes many projects with tests. 
Way -> set [assembly: NUnit.Framework.Timeout(x)] is very uncomfortable for me.
Any idea?
P.S.
Sorry for my English :)

**Comment by ChrisMaddock** [comment]
Are you running your tests with the console? You can also pass a default timeout on the command line to the console, using the `--timeout` option.

**Comment by kam1k** [comment]
Yes, I run tests with the console. Your option helped me.
Thank you!
