### ISSUE TITLE
Create NuGet package which allows running tests without any additional steps

### ISSUE THREAD

**Issue by NikolayPianikov** [nunit/nunit#1689]
Scenario 1:
- user installs this package via "nuget.exe install" command with all well-known extensions
- user uses nunit3-console.exe from this package to run tests without any additional steps

Scenario 2:
- user installs this package via "nuget.exe install" command
- user installs package for required extensions via "nuget.exe install" command
- user uses nunit3-console.exe from this package to run tests without any additional steps

Scenario 2 supposes using of ps1 scripts for installation and that is not so good from the security side.
This package could be use in CI servers to restore NUnit

**Comment by CharliePoole** [comment]
How would this differ from the existing NUnit.Console package (or old name - NUnit.Runners)

**Comment by NikolayPianikov** [comment]
I had troubles using TeamCity extension, but it was error in my configuration.
