### ISSUE TITLE
2 unit tests fail due to localization

### ISSUE THREAD

**Issue by FantasticFiasco** [nunit/nunit#1693]
The following unit tests fail on my computer due to localization:

`NUnit.Framework.Tests.TestParametersTests.GetDecimal_ValueIsCorrect`
`NUnit.Framework.Tests.TestParametersTests.GetDouble_ValueIsCorrect`

Here in Sweden we write a numerical value with decimals as _1,234_ instead of _1.234_.

I would happily produce a PR that will make the tests pass indifferent of the localization.

**Comment by rprouse** [comment]
Sure, we always appreciate the help.

**Comment by CharliePoole** [comment]
Your help on this would be appreciated. We should first decide how it should work.

When NUnit produces messages, it generally uses the InvariantCulture. Should we expect parameters to use invariant cultulre or local culture? Our tests are expecting InvariantCulture to work, but that's not what we are using. Should we change the or should we change the implementation?

**Comment by ChrisMaddock** [comment]
I'd personally be a fan of enforcing invariant culture on the command line - I'd want the same command line to work in the same way on different machines. 

That said, en-GB is pretty similar to Invariant, so not too painful for me, maybe @FantasticFiasco would think differently?

**Comment by rprouse** [comment]
I think that all formatting in our messages should be invariant too because it is in the XML results and I don't want it to change based on the CI server my tests are running on. 

That said, invariant is also easy for me because it is similar to en-CA, so I would like to to get the opinion of non-English speakers.

**Comment by FantasticFiasco** [comment]
I also think that invariant culture is the way to go. Current culture will always burn you on the CI server since it almost never run the same culture as the developers might have on their machines.

Regarding the culture setup for non-English developers, I think we have a complicated picture there. I don't think there is one configuration that everyone use, it comes down to personal preference. Me for instance, I run with _CurrentCulture=sv-SE_ and _CurrentUICulture=en-US_ to get English UI but numbers, currency and time displayed in the format I am used to (what's up with AM and PM anyway ;-))

**Comment by CharliePoole** [comment]
In that case, nothing to fix here?

**Comment by FantasticFiasco** [comment]
If we want to enforce invariant culture, shouldn't we specify that in method `TestParameters.Get<T>(string, T)`? The method is currently written like this:

```
public T Get<T>(string name, T defaultValue)
{
    string val = Get(name);
    return val != null ? (T)Convert.ChangeType(val, typeof(T), null) : defaultValue;
}
```

Since we specify null as `IFormatProvider` .NET assumes current culture, but the test states:

```
_parameters.Add("SomeParm", "1.234");
```

and _1.234_ is not a valid number according to my culture. I would propose enforcing invariant culture in `TestParameters`, thus the `Get` method should be written as

```
public T Get<T>(string name, T defaultValue)
{
    string val = Get(name);
    return val != null ? (T)Convert.ChangeType(val, typeof(T), CultureInfo.InvariantCulture) : defaultValue;
}
```

**Comment by CharliePoole** [comment]
You're right.

**Comment by rprouse** [comment]
> what's up with AM and PM anyway

I would say what's up with mm/dd/yyyy? How could anyone think that order makes sense to anybody? :smile:
