### ISSUE TITLE
In nunit3-console you cannot pass parameters containing ';' because they always get splitted

### ISSUE THREAD

**Issue by SilverXXX** [nunit/nunit#1694]
When running some tests with nunit3-console.exe, if you pass with --param there is no way to pass inside a value a ';'.

It seems from [CommandLineOptions.cs](https://github.com/nunit/nunit/blob/master/src/NUnitConsole/nunit3-console/CommandLineOptions.cs#L296) the you can't escape them in any way (it's not documented so i read the source directly).
A regex to capture only not escaped char would solve the problem (i'm not a regex expert so i cant suggest exact one)

**Comment by rprouse** [comment]
See our docs, there is general information there on quoting for various operating systems. You can also have multiple --param in the command line, one per variable. 

I am closing this as a question, but feel free to add questions, we will see them and try to help.

**Comment by ChrisMaddock** [comment]
@rprouse - I think this is a potential 'issue' within NUnit, not command line usage? Looks like the options will always split on semi-colon, and then throw if it's not a valid `=` format afterwards? So I don't think there is any way pass in a test parameter with a semi-colon currently. (If that's to be a supported thing to do!)

**Comment by SilverXXX** [comment]
Yes @ChrisMaddock, i would have tried to create a pull request to show a possible solution, it actually require only a one line change and a sensible regexp, but i'm quite bad at it (a connection string is a simple example of an impossible paramater to pass right now)

**Comment by rprouse** [comment]
Sorry, reading issues on my phone, I missed the detail :frowning:

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit-console #23](https://github.com/nunit/nunit-console/issues/23) via [**ZenHub**](https://www.zenhub.com/)
