### ISSUE TITLE
Console runner fails - Unable to acquire remote process agent 

### ISSUE THREAD

**Issue by greg73** [nunit/nunit#1698]
Hi,

We have installed NUnit 3.4.1 on our build server (Windows 2008 R2) running Jenkins.
Randomly the console runner fails to start with the following error. After an error, if the build is re-run manually the console runner works correctly without error.

The stack trace is 

```
System.Exception: Unable to acquire remote process agent
   at NUnit.Engine.Runners.ProcessRunner.LoadPackage()
   at NUnit.Engine.Runners.AbstractTestRunner.Load()
   at NUnit.Engine.Runners.AggregatingTestRunner.LoadPackage()
   at NUnit.Engine.Runners.AbstractTestRunner.Load()
   at NUnit.Engine.Runners.MasterTestRunner.LoadPackage()
   at NUnit.Engine.Runners.AbstractTestRunner.EnsurePackageIsLoaded()
   at NUnit.Engine.Runners.MasterTestRunner.NUnit.Engine.ITestRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
   at NUnit.ConsoleRunner.Program.Main(String[] args)
```

The command line we are using is 

`"C:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe" [paths to test dlls] --result:nunit-result.xml;format=nunit2`

Thanks

**Comment by greg73** [comment]
I have now confirmed that the same error occurs when running from the command prompt. Immediately re-entering the same command results in the tests running successfully.

**Comment by CharliePoole** [comment]
The only answer I can see is that the process runner times out. Are you using a large number of test assemblies?

**Comment by greg73** [comment]
No, this is quite a small project, only 3 test assemblies

**Comment by MistyKuu** [comment]
Having the same issue on TeamCity

**Comment by rprouse** [comment]
@greg73  and @MistyKuu, we will need more information to move forward with this issue.

**Comment by greg73** [comment]
@rprouse 
The error is not reproducible, i.e. it will happen once and then when immediately running the same tests again the error won't happen. I think it may be related to available memory, if the server is swapping memory and the build is running slowly the error seems more likely to happen.

**Comment by CharliePoole** [comment]
Not sure if we will be able to fix this, but moving it to the right project anyway. 😄

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit-console #117](https://github.com/nunit/nunit-console/issues/117) via [**ZenHub**](https://www.zenhub.com/)

**Comment by mbogi** [comment]
I'm getting similar issue, can some one help.

     [exec] System.Exception: Unable to acquire remote process agent
     [exec]    at NUnit.Engine.Runners.ProcessRunner.CreateAgentAndRunner()
     [exec]    at NUnit.Engine.Runners.ProcessRunner.LoadPackage()
     [exec]    at NUnit.Engine.Runners.AbstractTestRunner.Load()
     [exec]    at NUnit.Engine.Runners.MasterTestRunner.LoadPackage()
     [exec]    at NUnit.Engine.TestEngine.GetRunner(TestPackage package)
     [exec]    at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
     [exec]    at NUnit.ConsoleRunner.ConsoleRunner.Execute()
     [exec]    at NUnit.ConsoleRunner.Program.Main(String[] args)

BUILD FAILED

C:\TeamCity\buildAgent\work\GIT_Security\source\BuildTools\buildscripts_GIT\default.build(56,6):
External Program Failed: C:\Program Files\NCover Code Central\ncover (return code was -100)

Total time: 38.8 seconds.

This is what it gives with below script from nant.

<exec
              program="ncover"
              basedir="C:\Program Files\NCover Code Central\"
              workingdir="${Workspace.Path}\UnitTesting\UnitTests"
              commandline="run --project=&quot;&quot;UnitTests&quot;&quot; --build-id=${build.Version} -- &quot;&quot;${Workspace.Path}\Tools\Nunit\nunit-console\nunit3-console.exe&quot;&quot; UnitTests.sln /out:TestResult.txt"
              failonerror="true" verbose="true">
    </exec>

**Comment by greg73** [comment]
@mbogi Can you update the open issue https://github.com/nunit/nunit-console/issues/117

**Comment by CharliePoole** [comment]
Closing this as it duplicates nunit/nunit-console#117
