### ISSUE TITLE
TestContext.CurrentContext.Test.MethodName get Unnamed job in sauce labs

### ISSUE THREAD

**Issue by giang-hai-nguyen** [nunit/nunit#1707]
I got this issue when i want to get method name in sauce labs.
`caps.SetCapability("name", TestContext.CurrentContext.Test.MethodName);`
Pls help me if anyone has solution on this? thanks

Also, (maybe this is sauce labs issue instead) when i run a class and this class have 2 TCs (1 Pass, 1 Fail). However, This class marked Pass

**Comment by CharliePoole** [comment]
@giang-hai-nguyen We would need more informatio to help you with this.

What's the context? Where does this line of code live? Is it in a test? In a setup method? somewhere else? How does sauce labs work with NUnit? Bear in mind that we know NUnit, but we (at least I) don't know much about what sauce labs is or how it works.

**Comment by giang-hai-nguyen** [comment]
Hi Charlie,
I am new with sauce labs too. Here is the example for sauce labs (You need to register an account to fill info SAUCE_USERNAME & SAUCE_ACCESS_KEY to run this example). In the setup method, i called the `TestContext.CurrentContext.Test.MethodName` (get Method Name) of Nunit but it doesn't work.
Noticed that in this case, `TestContext.CurrentContext.Test.Name` method (get Class Name) of Nunit works fine. Thanks
```
using NUnit.Framework;
using System;
using Selenium;
using System.Web;
using System.Text;
using System.Net;
using OpenQA.Selenium;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
 
namespace Saucey_Selenium {
    [TestFixture("chrome", "45", "Windows 7", "", "")]
    public class SauceNUnit_Test
    {
        private IWebDriver driver;
        private String browser;
        private String version;
        private String os;
        private String deviceName;
        private String deviceOrientation;
 
        public SauceNUnit_Test(String browser, String version, String os, String deviceName, String deviceOrientation)
        {
            this.browser = browser;
            this.version = version;
            this.os = os;
            this.deviceName = deviceName;
            this.deviceOrientation = deviceOrientation;
        }
 
        [SetUp]
        public void Init()
        {
            DesiredCapabilities caps = new DesiredCapabilities();
            caps.SetCapability(CapabilityType.BrowserName, browser);
            caps.SetCapability(CapabilityType.Version, version);
            caps.SetCapability(CapabilityType.Platform, os);
            caps.SetCapability("deviceName", deviceName);
            caps.SetCapability("deviceOrientation", deviceOrientation);
            caps.SetCapability("username", "SAUCE_USERNAME");
            caps.SetCapability("accessKey", "SAUCE_ACCESS_KEY");
            caps.SetCapability("name", TestContext.CurrentContext.Test.MethodName);
 
            driver = new RemoteWebDriver(new Uri("http://ondemand.saucelabs.com:80/wd/hub"), caps, TimeSpan.FromSeconds(600))
 
        }
 
        [Test]
        public void googleTest()
        {
            driver.Navigate().GoToUrl("http://www.google.com");
            StringAssert.Contains("Google", driver.Title);
            IWebElement query = driver.FindElement(By.Name("q"));
            query.SendKeys("Sauce Labs");
            query.Submit();
        }
 
        [TearDown]
        public void CleanUp()
        {
            bool passed = TestContext.CurrentContext.Result.Status == TestStatus.Passed;
            try
            {
                // Logs the result to Sauce Labs
                ((IJavaScriptExecutor)driver).ExecuteScript("sauce:job-result=" + (passed ? "passed" : "failed"));
            }
            finally
            {
                // Terminates the remote webdriver session
                driver.Quit();
            }
        }
    }
}
```

**Comment by CharliePoole** [comment]
MethodName should work in SetUp. Can you explain what you mean by "it doesn't work?"

**Comment by giang-hai-nguyen** [comment]
Hi Charlie,
You can see the below screenshot of sauce labs for more details.
The **Unnamed job** displays when i use `TestContext.CurrentContext.Test.MethodName` 
And the class name displays as expected when i use `TestContext.CurrentContext.Test.Name`
![name](https://cloud.githubusercontent.com/assets/15973559/17182563/1bf2e87e-544e-11e6-9d7c-e51f27177d97.png)

**Comment by giang-hai-nguyen** [comment]
It works fine in local without sauce labs. So maybe that is not a bug :(

**Comment by CharliePoole** [comment]
Well, not ours anyway. :-)
