### ISSUE TITLE
Move installer to new repository

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#1716]
With moving all the engine extensions to separate repositories, the msi installer will no longer have direct access to most of the assemblies it packages. As such, I suggest we go ahead with moving it to a separate repository, and retrieve the required assemblies via NuGet restore.

If we did this, a component release would be two stage:
1. Build the release-assembly itself, and package, and publish the individual NuGet package.
2. Run a script in the new repository, which retrieves the new package, and all other dependencies from NuGet, and creates a new msi installer.

In future, it might make sense to even wrap a script round this whole process, so a "ReleaseEngine" task fetches the relevant sources from GitHub, increments versions, builds, packages and publishes all individual and "group" NuGet packages and installers. But that's perhaps a way down the line!

This new repository would also seems like a sensible place for other combined packages e.g. NUnit.Runners to live - but I think that should be handled as a separate issue. 

In terms of how this fits in with the 'big split' - as far as I can see, it can be done completely independently. I'd expect to `filter-branch` out the msi files from a clone of nunit-master, and then transfer that back as a new repository. At some point the exisiting msi files should be removed from the new engine repository, but that can be done at any point, before or after the split. 

Thoughts? :-)

**Comment by ChrisMaddock** [comment]
I forgot a bit. Regarding whether msi's are something we stick with long-term, I don't think that's too much of a concern here. The work involved would be reusable for any kind of multi-component distribution we do, the bit in the middle (initially a Wix project) should be interchangeable.

**Comment by CharliePoole** [comment]
What you say makes sense. If you can just pull it out and start making it work, then that won't interfere with the big split.

Details...

I think this particular project can simply be exported, as we have done for other minor splits. The history isn't that interesting.

I'd like to see us stop carrying around the framework WiX files. We haven't done a framework msi release for about a year and have no plans to do one. Nuget is, in fact, perfect for the framework.

I don't think such a packager should aim at eventually rebuilding the projects. It should package what has already been released without change. In fact, I'm hoping we can avoid rebuilding when we deploy releases to nuget as well, by using myget as the initial point of deployment.

**Comment by ChrisMaddock** [comment]
> I'd like to see us stop carrying around the framework WiX files. We haven't done a framework msi release for about a year and have no plans to do one. Nuget is, in fact, perfect for the framework.

I agree. To clarify, the framework wix files were also used to package the framework in the master installer, which was used in 3.4, they're not just the beta framework installer. I think @rprouse was wary about deleting them, in case it turned out there was a significant use case for framework being installed (via the master installer), and we needed to put it back. 

To my mind, it's easy enough to retrieve them from the history, if we need to revert. (So long as we make sure we don't lose that history in a three way split!) 

> In fact, I'm hoping we can avoid rebuilding when we deploy releases to nuget as well, by using myget as the initial point of deployment.

That sounds good.

**Comment by rprouse** [comment]
>>I'd like to see us stop carrying around the framework WiX files. We haven't done a framework msi release for about a year and have no plans to do one. Nuget is, in fact, perfect for the framework.

>I agree. To clarify, the framework wix files were also used to package the framework in the master installer, which was used in 3.4, they're not just the beta framework installer. I think @rprouse was wary about deleting them, in case it turned out there was a significant use case for framework being installed (via the master installer), and we needed to put it back.

As @ChrisMaddock says, I was just going to keep them around for one release in case there is a backlash. We could retrieve them from history, but thought is was easier to leave them there and delete them later.

**Comment by CharliePoole** [comment]
Fair enoug then!

**Comment by ChrisMaddock** [comment]
Any suggestions on a name for the new repo? With a view to the repo eventually also including things like NUnit.Runners and chocolatey packaging.

nunit-packaging?

**Comment by CharliePoole** [comment]
Not packaging I'd say, since we do packaging in the individual repos as well. This is for certain kinds of packages.

I was thinking of nunit-bundles or nunit-distribution as possibilities. @rprouse?

I'd say that our actually hosting chocolatey is only an idea right now. Obviously, that would be a way around not being able to get cooperation from the chocolatey folks, but how it works needs to be discussed.

Similarly, I don't think it's a forgone conclusion that NUnit.Console / NUnit.Runners would go into the new repo.

**Comment by ChrisMaddock** [comment]
@CharliePoole @rprouse 

Have put something together at https://github.com/ChrisMaddock/nunit-distribution. Would you mind taking a look?

This uses Cake to fetch the latest NuGet packages from nuget.org, and then builds the msi using them. There's bits of refactoring I want to do, but wanted to keep this as close to the current set-up as possible, and do the rest as PRs, to make it easier to review. 

### Changes
- Previously there was a display version, and package version - the latter derived from the engine assembly. That wouldn't make sense with different assemblies on different versions, so there's now just a single, user-specified version.

### Unanswered questions
- The changelog is currently a static file in this repository. Not sure how we'd best amalgamate a changelog across different components, needs some thought.

### To do (as PRs)
- Refactor out `common` from the wix
- Add TC addin back in
- Consider future of bundled NuGet packages
- Consider chocolatey

I was hoping I would be able to transfer this to nunit, and leave it queued for approval or something, but that doesn't seem to be the case. When we're happy, can one of you guys move it over?

**Comment by ChrisMaddock** [comment]
@CharliePoole @rprouse 

Sorry to bump on this one, I know it's far from top priority at the moment! Just to say I'm away for a month shortly - if it's possible for someone to take a look in the next couple of days, I should have a bit of time to tweak before I go - otherwise I'll leave it with you till I'm back. Thanks!

**Comment by rprouse** [comment]
@ChrisMaddock we've got the initial refactoring of the installer done. Personally, I think the remaining work might be easier to do once we get the repositories split. What do you think @CharliePoole?

**Comment by CharliePoole** [comment]
@ChrisMaddock I like this approach of using various nuget packages. I think that @rprouse is right to suggest that it wait till after the split though.

Other comments...

DisplayVersion was used for display. When you do an RC, for example, you want the package to be named "-RC" but you want the dialogs to just have the version number. That way, you don't have to change anything if you release the RC.

GitVersion - yes, I think that's the future. But we have it partially implemented in two repos already without bringing it to full production status. I think we need to finish making our decisions before we should use it elsewhere. That said, I don't know if we want to use it here. This is a bundle of packages, which may have various versions attached. We may need some sort of manifest that indicates what to include and what version of it to include.

The changelog should not show actual changes to programs. Rather, it should show entries like

```
 * Updated Teamcity event listener to 1.0.1
```

We can copy and rename individual change logs where they exist. Of course, so long as there is only one component, it's pretty trivial.

I agree with your future list except I think that "Consider future..." should come before any specific actions. It's easy to get into individual tasks because you "know" they have to be done anyway. It turns out, in my experience, that one knows the future even less than one imagines. :-)

Charlie

**Comment by ChrisMaddock** [comment]
Great - thanks guys, sounds good. Will revisit this in a month or so then!

**Comment by ChrisMaddock** [comment]
@CharliePoole , @rprouse,

I'm back online and happy to move on with this and then potentially #452, now 'the split' has taken place. 😄 (I'll take from removing the blocked label, you agree it's ready to move on Charlie!)

I agree with Charlie's comments on the changelog, and gitversion. Regarding the 'DisplayVersion', I would personally choose to have a single consistent version throughout, and expect that difference in the dialogs between RC and release, but happy to switch that back to how it was if people disagree.

I can make the above changes next week (currently 35,000 over the Pacific ✈️) - is there anything else blocking this that I should be doing? Or anything that came out of doing the split that affects this move? Thanks!

**Comment by CharliePoole** [comment]
The definition of an RC as I learned it at Microsoft (there certainly can be other definitions) is that it can be released as is, without rebuilding, if no problems arise. We are not there yet, but if we want that to be the goal, then the separate display version is a tiny step toward it. IOW, in a true RC, the external name of the file should be the only thing different that has to change in order to create a release. Obviously, we can discuss this at a later time no matter how you do the msi.

My only proviso about this issue is that you shouldn't add any bells and whistles to what we have. I still see at least the possibility that we will drop the msi in the future. In a few months, I think we will have a clearer direction and we can move ahead with installer features. I think that goes for #452 as well: we may want to hold off on it for now in favor of some of our own higher priorities, of which there are many!

**Comment by ChrisMaddock** [comment]
Ok, I've made @CharliePoole's changes from above:
- New changelog
- Return display version

This is ready for review/transfer again. (I was hoping there would be a 'transfer for approval' mechanism, but apparently not!)

Updated to-do list, based on 'no bells and whistles': :smile: 
* Refactor out common from the wix
* Add TC addin back in
* Remove wix files from nunit/nunit
* <s>Consider future of bundled NuGet packages</s>
* <s>Consider chocolatey</s>

Was planning to do these as separate PRs in a new repo, to make reviewing easier.

**Comment by CharliePoole** [comment]
So @rprouse and I should review your nunit-distribution repo again?

**Comment by ChrisMaddock** [comment]
@CharliePoole - Yes please. 

From my point of view - ChrisMaddock/nunit-distribution is now ready to be copied over to nunit as is, and the remaining changes done as pull requests to a future nunit/nunit-distribution. Of course, pending review or any change in direction! :smile:

**Comment by rprouse** [comment]
@ChrisMaddock I have reviewed your repo and it looks good. We will need to download and test it, but I would be okay transferring it into the NUnit organization at any time. The easiest way might be to temporarily give you admin rights to the organization so you can do the transfer using GitHub. Another option would be for @CharliePoole or I to create the repo and you add and push to a new remote.

With this (and all the other changes), we will need to update the developer documentation at https://github.com/nunit/docs/wiki/Packaging-NUnit, but that doesn't block the move. I am going to have to give myself extra time for the 3.5 release to iron out the kinks and document the process.

@CharliePoole have you had a chance to look at the repo? Should we pull it into the organization now?

**Comment by CharliePoole** [comment]
I think it's ready to come into the organization. 

@ChrisMaddock I gave you temporary admin authority. Would you follow the directions here:
https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

**Comment by ChrisMaddock** [comment]
Ok - it's moved over. I added it to the Contributor/Core/Engine teams to start with, not sure how you wanted this one to be set up.

Will leave this issue open for now, and do a PR in a bit to remove the msi files from this repo. Thanks both for reviewing!

**Comment by CharliePoole** [comment]
Good... I think those teams make sense for now.

**Comment by ChrisMaddock** [comment]
> With this (and all the other changes), we will need to update the developer documentation at https://github.com/nunit/docs/wiki/Packaging-NUnit, but that doesn't block the move. I am going to have to give myself extra time for the 3.5 release to iron out the kinks and document the process.

@rprouse - I've just created separate issues for everything talked about in this thread, this is nunit/docs#117

**Comment by ChrisMaddock** [comment]
@CharliePoole / @rprouse - It looks like I can still commit to master on the new repository, which I assume I shouldn't be able to do without admin permissions. I presume I've just missed a checkbox, can one of you have a look? Thanks.

**Comment by CharliePoole** [comment]
Did you see the note I just sent out about team reorganization? We've kept you in the newly defined "Core Team", which has write access to everything. Please use your power for Good! :-)

**Comment by ChrisMaddock** [comment]
Ah - ok. I didn't realise that includes commit-to-master, I assumed it was just the same write permissions as before, just over more repositories. Great - thanks!

**Comment by CharliePoole** [comment]
Not sure what you mean by commit-to-master - everyone with commit authority has the ability to commit to master or any other branch except to the extent that the branches are protected. You need admin authority to override protection. The existence or level of branch protection varies for each repo.

**Comment by ChrisMaddock** [comment]
> The existence or level of branch protection varies for each repo.

Sorry, didn't realise that. I thought 'protect master' was a GitHub permissions level thing, rather than per-repo.
