### ISSUE TITLE
Remove Cake target TestAll

### ISSUE THREAD

**Issue by FantasticFiasco** [nunit/nunit#1723]
Remove the Cake target _TestAll_ since it is exactly the same as the target _Test_. This duplicity is confusing for new contributors since they expect there to be differences is the amount of tests being executed.

Also remove any references to the _TestAll_ target. At the time of writing the target is referenced from _BUILDING.md_.

**Comment by CharliePoole** [comment]
We left both targets in place because some folks were in the habit of using them. But your point about new contributors is a good one.

@rprouse What do you think?

**Comment by rprouse** [comment]
I'm happy to remove TestAll. It will make even less sense once the repositories are split.

**Comment by CharliePoole** [comment]
@FantasticFiasco Did you want to take this?

**Comment by FantasticFiasco** [comment]
@CharliePoole I would be happy to, although it seems that I haven't got the permissions to assign myself to it.

**Comment by CharliePoole** [comment]
Well, at least we've learned something new about GitHub.

**Comment by FantasticFiasco** [comment]
If you wouldn't mind, can you assign me to the issue?

**Comment by CharliePoole** [comment]
Sorry, I thought I did that earlier.
