### ISSUE TITLE
Consider hiding `Is.Equals` using `[EditorBrowsable(EditorBrowsableState.Never)]`

### ISSUE THREAD

**Issue by jcansdale** [nunit/nunit#1726]
I don't know if this is possible, but I find `Is.Equals` showing up in IntelliSense annoying. :)

**Comment by jcansdale** [comment]
Let me know what you think and assign it to me if you think the idea might have legs.

**Comment by rprouse** [comment]
If it works, go for it. It annoys me to. Just make sure we don't see info for the base version :smile:

**Comment by jcansdale** [comment]
I was hoping something like this would work:
http://blogs.clariusconsulting.net/kzu/how-to-hide-system-object-members-from-your-interfaces/

Alas, the `Equals` that shows up is the `static bool Equals(object, object)` method that is defined on `System.Object` (not an instance method). I tried hiding this on the `Is` class like so:

```
        [EditorBrowsable(EditorBrowsableState.Never)]
        public static new bool Equals(object ob1, object ob2)
        {
            throw new NotImplementedException();
        }
```

The `EditorBrowsable` attribute appears to hide this method, but the original method is still visible (even though it's no longer callable). Frustrating!

Any suggestions or do you think what I'm trying to do is impossible?

**Comment by rprouse** [comment]
I thought that might be the case :frowning: If the base method starts showing up, then it is worse because we will see the docs for that method rather than the warning not to use from our docs.

I'm afraid I don't have any suggestions. Anybody else?

**Comment by CharliePoole** [comment]
The technique in the article may work further along the chain, for example on ConstraintExpression. But since Is is a static class, I don't think it's possible. FWIW we tried lots of ways to hide this many years back, to no success. By now, I hardly see those methods. :-)

**Comment by jcansdale** [comment]
Luckily since it takes 2 parameters and returns a bool, it's unlikely to be used by mistake. It's just a same it always seems to appear first in IntelliSense.

Anyway, I'll close off this issue as can't fix. :sob:

**Comment by jcansdale** [comment]
I had a bit of a rant at @Johnmont and @drunkvs: 😉 
https://twitter.com/jcansdale/status/788698134939566080

**Comment by jcansdale** [comment]
My failed attempt to use `[EditorBrowsable(EditorBrowsableState.Never)]`, is probably related to this:
https://github.com/dotnet/roslyn/issues/4434

**Comment by CharliePoole** [comment]
You could verify that by trying it in VS2013.

**Comment by jcansdale** [comment]
> You could verify that by trying it in VS2013.

Verified!

You can see below, `Equals` is no longer visible in Visual Studio 2013:

![equalsvs2013](https://cloud.githubusercontent.com/assets/11719160/19559183/86e0341a-96c6-11e6-9a22-5db66b559f18.png)

This means we can successfully nuke `Equals` and `ReferenceEquals` using the following:

```c#
        [EditorBrowsable(EditorBrowsableState.Never)]
        new public static bool Equals(object ob1, object ob2)
        {
            throw new NotImplementedException("I'm afraid I can't do that");
        }

        [EditorBrowsable(EditorBrowsableState.Never)]
        new public static bool ReferenceEquals(object ob1, object ob2)
        {
            throw new NotImplementedException("I'm afraid I can't do that");
        }
```

Hopefully this bug will be fixed in Visual Studio "15" or they will hide static methods on `object` by default (on types other than `object`).

**Comment by Pilchie** [comment]
We'll try to fix it for VS "15", but I can't promise it at the moment.  In the meantime, I would recommend adding the `new`, method as above so it is hidden in VS2013, and will start being hidden whenever we fix the bug.  However, a couple of tweaks I'd suggest:

1. Add a better message, explaining what users should do instead.
2. Add an `[Obsolete]` attribute, so that the compiler can at least tell users when they are doing it wrong.

Something like:
```C#
        private const string message = "Use 'object." + nameof(Equals) + "' for equality, and '"
            + nameof(Assert) + "." +nameof(EqualTo) +"' for assertion.";

        [Obsolete(message, error: true), EditorBrowsable(EditorBrowsableState.Never)]
        public static new bool Equals(object l, object r)
        {
            throw new InvalidOperationException(message);
        }
```

**Comment by jcansdale** [comment]
@Pilchie,

Thanks for the suggestion. There are two related issues.

1. New users who accidentally use the wrong method (your suggestion works great for this).
2. Regular users who enter `Assert.That(x, Is.EqualTo(y)` multiple times per day.

The second issue is quite subtle, but I find it infuriating because of this:

> The history of most recently used members is cleared between each session in the IDE.
https://msdn.microsoft.com/en-us/library/43f44291.aspx

This feature means a certain combination of keys becomes muscle memory, but I get tripped up the next time I launch Visual Studio. It then starts working again until next time I open a solution. I find this inconsistency when entering something I use a lot to be quite jarring. I'm never completely confident about that's going to happen when I press a combination of keys!

(I know this feature can be turned off, but I don't want to do that because it works most of the time.)

Does that make sense?

**Comment by JustinRChou** [comment]
Should `Equals` and `ReferenceEquals` be overridden in `Is` as well?

**Comment by OsirisTerje** [comment]
Seems this is fixed in a later version of Visual Studio, so closing this.
