### ISSUE TITLE
Update target information in BUILDING.md

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#1730]
Some of the target information is outdated in BUILDING.md. Some targets no longer exist, others have incorrect dependency information (e.g. testing relying on building.)

Suggest this waits until after the split, as I'm sure it will only change more - maybe we also rewrite it in a more future-proof way. :smile:

**Comment by CharliePoole** [comment]
Duplicating this in both repositories.

**Comment by ChrisMaddock** [comment]
This was done at some point.
