### ISSUE TITLE
Silverlight not found in Appveyor CI

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#1731]
The latest merge to master failed the Appveyor build as Silverlight could not be found.

https://ci.appveyor.com/project/CharliePoole/nunit/build/3.5.0-dev-03128

Nothing relevant seems to have changed at our end, I've re-ran the build on a fork and hit the same issue again.

**Comment by ChrisMaddock** [comment]
Have checked that Silverlight is 'definitely' missing, rather than just our path in Cake being wrong. 

https://ci.appveyor.com/project/ChrisMaddock/nunit/build/3.5.0-dev-00069

Haven't opened an issue with Appveyor, as I won't be around much longer to respond to it - sorry!

**Comment by CharliePoole** [comment]
This issue seemed to disappear in subsequent builds so I marked it not a bug. We can re-open if it turns up again.
