### ISSUE TITLE
Test assembly that targets .NET 3.5 but references CF is not supported by the engine.

### ISSUE THREAD

**Issue by still-dreaming-1** [nunit/nunit#1734]
Hello. I am maintaining a Windows Mobile 5 app that runs in the .Net Compact Framework 3.5. I realize this is old technology, but we have many clients who still use it, and we actually still get new ones who prefer Windows Mobile devices for some reason... Anyway, I just tried upgrading from NUnit 3.0 to the latest 3.4.1 release. Now I am getting the following error message when I run the tests: ".NETCompactFramework test assemblies are not yet supported by the engine".

Some clarification. I have never been into trying to run these tests on the .Net Compact Framework on a mobile device or emulator. That would be too slow, and I have found it to be unnecessary. dlls compiled for the .Net Compact Framework are actually supposed to be able to run just fine in the full .Net Framework, and I have found this to be the case, as long as they don't use certain things that are CF specific. So I just run our NUnit tests on the full framework using our .dlls compiled for the CF. As such, I am not using NUnitCF, just the regular NUnit.

**Comment by still-dreaming-1** [comment]
Further clarification: Actually the project that contains the tests is a full .Net Framework 3.5 project, not a CF or Windows Mobile project. But it references the dlls from the Windows Mobile 5 CF 3.5 project. That is why this normally works.

**Comment by rprouse** [comment]
If your test assembly is NET 3.5, referencing the NET 3.5 version of NUnit should get your tests running in the console. Is this not the case?

**Comment by CharliePoole** [comment]
@still-dreaming-1 Which build of the nunit framework does your test assembly reference?

The engine can't run tests that use the CF framework build because it uses remoting to talk to the framework. You should be able to run tests built against the .NET 3.5 version of the framework.

**Comment by still-dreaming-1** [comment]
I will answer those questions as well as provide some other information.

**Configuration when it was working with Nunit 3.0**:

* nunit.framework.dll from the net-2.0 directory
* using command prompt to run"nunit3-console.exe"
which is passed:
1. the .csproj path of the project that only contains the unit tests (this is a .NET 3.5 project, not CF, but it does reference a CF 3.5 dll)
2. /framework:net-3.5
For some reason when it runs, it says it is running in "CLR Version: 4.0.30319.42000". That does not make sense to me as I thought the 3.5 means it should run in that CLR version. In a way it makes sense that it is not running in .Net 3.5 because I don't have that installed, but it still does not totally make sense given that I don't actually .Net 4.0 installed. I do have 4.6.1 installed though, maybe that is the 4.0 CLR? Anyway, I don't have .Net 3.5 installed on my computer for reasons I can't remember. Maybe I will try installing it. I know I tried installing it before, but I can't remember why I left it uninstalled.
Anyway, even though that seems strange, the code builds and the tests run and pass.
I also tried:
* nunint.framework.dll from net-4.0 directory. This caused an error at the build step before trying to run it.
* nunit.framework.dll from net-4.5 directory. This also caused a build error.
* nunit.framework.dll from portable directory. This also caused a build error.
There are no other directories with compiled dll files with the 3.0 release.

**Configuration when it does not work with Nunit 3.4.1**:
* nunit.framework.dll from the net-2.0 and 3.5 directories:
Everything builds, but running the tests gives me that ".NETCompactFramework test assemblies are not yet supported by the engine" message.
* nunint.framework.dll from "net-4.0", "net-4.5", and "portable" directories:
These caused an error at the build step before trying to run the tests.

**Comment by CharliePoole** [comment]
@oznetmaster 
Do you want to take a look at this? If not, I may find some time on the weekend.

@still-dreaming-1 
Your message starting "CLR Version..." describes the runtime under which nunit3-console is running, not the runtime under which your tests are running (notice it displays before your tests ever start).

Forget about all those nunit builds > 3.5. They can't possibly be loaded if you are running in a .NET 3.5 process. They simply won't load.

Consider using NUnitLite as I mentioned.

The message you are seeing was added in 3.4 or 3.4.1 because we were trying to run CF tests and failing in a non-obvious way. Obvious failures are clearly better. However, this should only be happening if the tests are built against the CF version of the framework.

**Comment by oznetmaster** [comment]
I really do not understand exactly what @still-dreaming-1 is doing, or what they want to do.

I only run NUnitLite for CF on the CF device.  I have never configured or run it in any other fashion, nor have any of the users that I support.

**Comment by still-dreaming-1** [comment]
I just want to exercise my CF code in the full .NET framework when running the tests so the tests will run faster. With the setup I described it has worked flawlessly up until that error message in the new version of NUnit.

**Comment by still-dreaming-1** [comment]
I also get that message in NUnit 3.4, but not in NUnit 3.2.1

**Comment by CharliePoole** [comment]
@oznetmaster OK. I understand what he wants to do so I'll look at it on the weekend.

@still-dreaming-1 Whatever fix we do, you'll have to wait for a new release, so I suggest giving nunitlite a try. If you can create a simple repro

**Comment by still-dreaming-1** [comment]
@CharliePoole Thanks. Yeah I can wait. I will just use 3.2.1 for now. I don't have any desperate need to update. I just didn't want to lose the option of ugrading to new versions and running my tests this way. Thanks.

**Comment by CharliePoole** [comment]
@still-dreaming-1 Examining the code that was added in 3.4 to detect CF assemblies, which we cannot run, I see that it looks at the TargetFrameworkAttribute. In the case where the TargetFrameworkAttribute is not available, we have special handling for CF. We check to see if you reference the CF mscorlib. If you do, then we treat it as a CF assembly.

So one workaround is to add a TargetFrameworkAttribute yourself. Another is to stop referencing the CF mscorlib from your tests. I suspect you can't do the latter as the assembly under test most likely references it.

Please let me know if you try either of these and what happens. I'll experiment with it myself as well. We use a similar test setup in our own tests with a .NET 4.5 test assembly that references the CF assembly. it would be good to be able to use the console runner with it.

**Comment by OlHall** [comment]
Sorry to resurrect an old thread, but has there been any movement on this?

I'm hitting a similar challenge (same error).  It only occurs when I include a test that gets a reference to a Dicitonary<> object (which is part of a class in the CF assembly).

**Comment by OlHall** [comment]
Using the suggestion above, I've worked around the issue by compiling my CF assembly against the x86 mscorlib, so no urgency, but I suspect I'm not doing things the "right" way here.

**Comment by CharliePoole** [comment]
Once we stopped supporting the compact framework, this was kind of forgotten. However, as I understand it, you don't want CF support exactly, just the ability for your SUT to reference it. Your test assembly would still use the desktop. Have I got that right?

**Comment by CharliePoole** [comment]
Once we stopped supporting the compact framework, this was kind of forgotten. However, as I understand it, you don't want CF support exactly, just the ability for your SUT to reference it. Your test assembly would still target the desktop. Have I got that right?

**Comment by OlHall** [comment]
Exactly

**Comment by CharliePoole** [comment]
I'll have to dig out some old code in the next few days to see what's possible.

**Comment by rprouse** [comment]
@OIHall and @still-dreaming-1 just curious, with the CF framework, OS and Visual Studio 2008 going end-of-life mid-next year, are you continuing to develop for CF, or are you migrating to newer technologies?

**Comment by still-dreaming-1** [comment]
@rprouse We would prefer to get completely away from Windows CE based technologies, but this is not an easy thing to accomplish. I don't see it happening very soon, but I hope it eventually will, and I am trying to use my influence to make this happen.

One thing that would help is some links to very clear, official statements about end of life for different CE products, and what that means exactly. That might help me convince the company we need to move off of CE.

One of the biggest hurdles for us to overcome is we use Hydrus Luna devices for radio reading of Badger, Ramar, and Blue Tower meters. It is possible to get that device with an antenna attached, and we can communicate with the antenna from the app. We are not aware of any such capabilities for an Android device. I believe this device is made by Northrop Grumman.

Also, I'm no longer concerned about CF support for newer versions of NUnit. We rarely make changes to our CE based software, and the older versions of NUnit fill our needs adequately.

I believe we have a partnership with the company that makes the radio board, perhaps we should encourage them to this for an Android device...

**Comment by rprouse** [comment]
@still-dreaming-1 Oddly, I've been going through the same thing at work today. It depends on which version of CE or embedded you are using. [Support for Windows Embedded CE 6.0 is scheduled to end on June 10, 2018, while Windows Embedded 8.1 Handheld and Windows Embedded Handheld 6.5 will reach end of life on June 9, 2019 and January 14, 2020 respectively.](https://support.microsoft.com/en-us/lifecycle/search?sort=PN&alpha=Windows%20Embedded&Filter=FilterNO)

At our company, we have decided to end support for our CE app next month. It has only received minor fixes for a number of years, but testing it to ensure it works with each release of our server was getting expensive. Our customers are also having trouble buying hardware. It is tough when you are coupled with a hardware manufacturer that isn't switching.

The final nail in the coffin for us is that Visual Studio 2008 is the last version we can build our software in and it is also [end of life in April](https://blogs.msdn.microsoft.com/visualstudio/2017/04/10/end-of-support-for-visual-studio-2008-in-one-year/)

**Comment by rprouse** [comment]
Housekeeping, I am going to close this as won't fix.
