### ISSUE TITLE
Explore implementing MultipleAsserts using existing extensibility mechanism 

### ISSUE THREAD

**Issue by jcansdale** [nunit/nunit#1737]
I'd like to investigate the feasibility of adding the following test attribute:

```
        [MultipleAsserts(3)]
        public IEnumerable<Action> TestWitAsserts()
        {
            var hello = "hello, world";
            yield return () => Assert.That(hello, Does.StartWith("H"));
            yield return () => Assert.That(hello, Does.EndWith("!"));
            yield return () => Assert.That(hello, Does.Contain("World"));
        }
```

This attribute would make `TestWitAsserts` appear as 3 test methods. The `TestWitAsserts` method would be executed in 3 sections, one for each `yield return`.

**Comment by jcansdale** [comment]
I'm looking at the following method `public IEnumerable<TestMethod> BuildFrom(MethodInfo method, Test suite)` from `ITestBuilder`. Is it possible for the `TestMethod(s)` returned to target a custom method and suite (something other than the `method` and `suite` passed in)? In this case I would need to execute the `Action(s)` returned instead of targeting the attributed method directly.

**Comment by CharliePoole** [comment]
I marked it as an "idea", which in our lingo basically means it's not something we have decided to do. I assigned it to you. Mainly, this labelling business is to keep contributors from grabbing it and running with an idea that we may end up not implementing.

As a matter of design approach, I'm not very comfortable with starting from the attribute and working up to the higher levels from there. In part, that's probably just a matter of style - you have yours and I have mine. In part, it's because I think the attribute implementation is the easy part. I already implemented it once, although not in quite the way you propose. To reduce risk in a case like this I like to start with the hard part, which to me is figuring out how the outside world (runners and engine) will deal with the feature while maintaining the desired isolation across the layers.

That said, see what you can do but let's continue to work on the other aspects of the overall approach under issue #391.

BTW, be sure to deal with the interaction with other attributes, particularly those related to test data.

**Comment by CharliePoole** [comment]
In principle, the test you return (testmethod) must be a member of the suite. That doesn't mean that the method must belong to the class, because tests and suites are abstract entities. 

That's in principle. In practice, it's possible that you'll break something because we have not sufficiently maintained the ideal level of abstraction. :-)

**Comment by jcansdale** [comment]
> I think the attribute implementation is the easy part.

The challenge for me at the moment is understanding what is and isn't possible with the attribute extensibility and how to use it in a sensible way. :smile:

I'm currently interested in whether a `TestMethod` can implement custom execution logic or whether I'd need to use a different attribute?

**Comment by CharliePoole** [comment]
OK... as an intro to how this works in 3.x...

TestMethod doesn't execute __any__ implementation logic. In NUnit 2, test objects like TestSuite and TestCase executed themselves. In NUnit 3, commands are generated that are eventually executed. At execution time, we have WorkItems, which hold a chain of Commands to execute. The Test is available for reference, but doesn't do anything.

At load time (i.e. discovery in VS terms) attributes are able to register themselves to participate in building the command structure for a test before it is executed. That structure is only built if the test is actually going to be run. 

So the place to look is in the code that generates those commands for a normal test method. Once you see where that lives, you should have an idea of what to do.

**Comment by CharliePoole** [comment]
You could start here: https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/Execution/CommandBuilder.cs#L99

**Comment by jcansdale** [comment]
Thanks for the explanation and link!

It looks like `IWrapTestMethod` may be what I'm after. :smile:

**Comment by jcansdale** [comment]
I've made some progress:

![multi_assert](https://cloud.githubusercontent.com/assets/11719160/17640649/651fbd8c-60fc-11e6-847a-6742a27e9d97.png)

The code is really rough though, but unfortunately I'm out of time. :disappointed:

Here's the sample test:

```
    public class Tests
    {
        [MultiAssert(3)]
        public static IEnumerable<Action> HelloAsserts()
        {
            var hello = "hello, world!";
            yield return () => Assert.That(hello, Does.StartWith("H"));
            yield return () => Assert.That(hello, Does.EndWith("!"));
            yield return () => Assert.That(hello, Does.Contain("World"));
        }
    }
```

And here's the *very* rough test attribute:

```
    using System;
    using System.Collections.Generic;
    using NUnit.Framework.Interfaces;
    using NUnit.Framework.Internal;
    using Internal.Commands;

    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = true)]
    public class MultiAssertAttribute : NUnitAttribute, IImplyFixture, ITestBuilder, IWrapTestMethod
    {
        int assertCount;
        static IEnumerator<Action> actions; // shouldn't be static!

        public MultiAssertAttribute(int assertCount)
        {
            this.assertCount = assertCount;
        }

        public IEnumerable<TestMethod> BuildFrom(IMethodInfo method, Test suite)
        {
            var testMethodList = new List<TestMethod>();
            for (int n = 1; n <= assertCount; n++)
            {
                var testMethod = new TestMethod(method, suite);
                testMethod.Name += "(" + n + ")";
                testMethod.FullName += "(" + n + ")";
                testMethodList.Add(testMethod);
            }

            return testMethodList;
        }

        public TestCommand Wrap(TestCommand command)
        {
            var targetTestMethod = (TestMethod)command.Test;
            IEnumerable<Action> enumerableAction = (IEnumerable<Action>)targetTestMethod.Method.Invoke(null);
            actions = enumerableAction.GetEnumerator();

            var method = new MethodWrapper(GetType(), new Action(nextAssert).Method);
            var testMethod = new TestMethod(method);
            var testMethodCommand = new TestMethodCommand(testMethod);
            return testMethodCommand;
        }

        static void nextAssert()
        {
            actions.MoveNext();
            actions.Current();
        }
    }
```

Improvements and suggestions welcome! :smile:

**Comment by CharliePoole** [comment]
Can you post the XML that gets generated when you run this?

**Comment by jcansdale** [comment]
Sure, it looks like this:

```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-run id="2" testcasecount="3" result="Failed" total="3" passed="1" failed="2" inconclusive="0" skipped="0" asserts="3" engine-version="3.4.1.0" clr-version="4.0.30319.42000" start-time="2016-08-13 11:52:58Z" end-time="2016-08-13 11:52:59Z" duration="0.391231">
  <command-line><![CDATA[packages\NUnit.ConsoleRunner.3.4.1\tools\nunit3-console.exe  Tests\bin\Debug\Tests.dll]]></command-line>
  <test-suite type="Assembly" id="0-1005" name="Tests.dll" fullname="C:\scratch\NCrunchExperiments\Tests\bin\Debug\Tests.dll" runstate="Runnable" testcasecount="3" result="Failed" site="Child" start-time="2016-08-13 11:52:58Z" end-time="2016-08-13 11:52:58Z" duration="0.262344" total="3" passed="1" failed="2" inconclusive="0" skipped="0" asserts="3">
    <environment framework-version="3.4.1.0" clr-version="4.0.30319.42000" os-version="Microsoft Windows NT 10.0.14393.0" platform="Win32NT" cwd="C:\scratch\NCrunchExperiments" machine-name="ORANGE" user="Jamie" user-domain="ORANGE" culture="en-GB" uiculture="en-US" os-architecture="x64" />
    <settings>
      <setting name="WorkDirectory" value="C:\scratch\NCrunchExperiments" />
      <setting name="ImageRuntimeVersion" value="4.0.30319" />
      <setting name="ImageTargetFrameworkName" value=".NETFramework,Version=v4.5.2" />
      <setting name="ImageRequiresX86" value="False" />
      <setting name="ImageRequiresDefaultAppDomainAssemblyResolver" value="False" />
      <setting name="NumberOfTestWorkers" value="4" />
    </settings>
    <properties>
      <property name="_PID" value="15664" />
      <property name="_APPDOMAIN" value="test-domain-" />
    </properties>
    <failure>
      <message><![CDATA[One or more child tests had errors]]></message>
    </failure>
    <test-suite type="TestSuite" id="0-1006" name="Tests" fullname="Tests" runstate="Runnable" testcasecount="3" result="Failed" site="Child" start-time="2016-08-13 11:52:58Z" end-time="2016-08-13 11:52:58Z" duration="0.236851" total="3" passed="1" failed="2" inconclusive="0" skipped="0" asserts="3">
      <failure>
        <message><![CDATA[One or more child tests had errors]]></message>
      </failure>
      <test-suite type="TestFixture" id="0-1000" name="Tests" fullname="Tests.Tests" classname="Tests.Tests" runstate="Runnable" testcasecount="3" result="Failed" site="Child" start-time="2016-08-13 11:52:58Z" end-time="2016-08-13 11:52:58Z" duration="0.232395" total="3" passed="1" failed="2" inconclusive="0" skipped="0" asserts="3">
        <failure>
          <message><![CDATA[One or more child tests had errors]]></message>
        </failure>
        <test-suite type="ParameterizedMethod" id="0-1004" name="HelloAsserts" fullname="Tests.Tests.HelloAsserts" classname="Tests.Tests" runstate="Runnable" testcasecount="3" result="Failed" site="Child" start-time="2016-08-13 11:52:58Z" end-time="2016-08-13 11:52:58Z" duration="0.225179" total="3" passed="1" failed="2" inconclusive="0" skipped="0" asserts="3">
          <failure>
            <message><![CDATA[One or more child tests had errors]]></message>
          </failure>
          <test-case id="0-1001" name="HelloAsserts(1)" fullname="Tests.Tests.HelloAsserts(1)" methodname="HelloAsserts" classname="Tests.Tests" runstate="Runnable" seed="0" result="Failed" start-time="2016-08-13 11:52:58Z" end-time="2016-08-13 11:52:58Z" duration="0.185144" asserts="1">
            <failure>
              <message><![CDATA[  Expected: String starting with "H"
  But was:  "hello, world!"
]]></message>
              <stack-trace><![CDATA[at Tests.Tests.<>c__DisplayClass0_0.<HelloAsserts>b__0() in c:\scratch\NCrunchExperiments\Tests\Tests.cs:line 17
at NUnit.Framework.MultiAssertAttribute.nextAssert() in c:\scratch\NCrunchExperiments\Tests\MultiAssertAttribute.cs:line 49
]]></stack-trace>
            </failure>
          </test-case>
          <test-case id="0-1002" name="HelloAsserts(2)" fullname="Tests.Tests.HelloAsserts(2)" methodname="HelloAsserts" classname="Tests.Tests" runstate="Runnable" seed="0" result="Passed" start-time="2016-08-13 11:52:58Z" end-time="2016-08-13 11:52:58Z" duration="0.001484" asserts="1" />
          <test-case id="0-1003" name="HelloAsserts(3)" fullname="Tests.Tests.HelloAsserts(3)" methodname="HelloAsserts" classname="Tests.Tests" runstate="Runnable" seed="0" result="Failed" start-time="2016-08-13 11:52:58Z" end-time="2016-08-13 11:52:58Z" duration="0.005217" asserts="1">
            <failure>
              <message><![CDATA[  Expected: String containing "World"
  But was:  "hello, world!"
]]></message>
              <stack-trace><![CDATA[at Tests.Tests.<>c__DisplayClass0_0.<HelloAsserts>b__2() in c:\scratch\NCrunchExperiments\Tests\Tests.cs:line 19
at NUnit.Framework.MultiAssertAttribute.nextAssert() in c:\scratch\NCrunchExperiments\Tests\MultiAssertAttribute.cs:line 49
]]></stack-trace>
            </failure>
          </test-case>
        </test-suite>
      </test-suite>
    </test-suite>
  </test-suite>
</test-run>```

**Comment by jcansdale** [comment]
Here's a slightly less terrible implementation. :wink:

It still assumes all test-asserts will be executed in the same run, but this is fixable.

```C#
    using System;
    using System.Collections.Generic;
    using NUnit.Framework.Interfaces;
    using NUnit.Framework.Internal;
    using Internal.Commands;

    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = true)]
    public class MultiAssertAttribute : NUnitAttribute, IImplyFixture, ITestBuilder, IWrapTestMethod
    {
        int assertCount;

        public MultiAssertAttribute(int assertCount)
        {
            this.assertCount = assertCount;
        }

        public IEnumerable<TestMethod> BuildFrom(IMethodInfo method, Test suite)
        {
            var testMethodList = new List<TestMethod>();
            for (int n = 1; n <= assertCount; n++)
            {
                var testMethod = new TestMethod(method, suite);
                var label = "#" + n;
                testMethod.Name += label;
                testMethod.FullName += label;
                testMethodList.Add(testMethod);
            }

            return testMethodList;
        }

        public TestCommand Wrap(TestCommand command)
        {
            var testMethod = (TestMethod)command.Test;
            return new ActionTestMethodCommand(testMethod);
        }

        class ActionTestMethodCommand : TestMethodCommand
        {
            TestMethod testMethod;

            public ActionTestMethodCommand(TestMethod testMethod) : base(testMethod)
            {
                this.testMethod = testMethod;
            }

            public override TestResult Execute(TestExecutionContext context)
            {
                if (Actions == null)
                {
                    IEnumerable<Action> enumerableAction =
                        (IEnumerable<Action>)testMethod.Method.Invoke(testMethod.Fixture);
                    Actions = enumerableAction.GetEnumerator();
                }

                Actions.MoveNext();
                Actions.Current();

                context.CurrentResult.SetResult(ResultState.Success);
                return context.CurrentResult;
            }

            IEnumerator<Action> Actions
            {
                get
                {
                    return (IEnumerator<Action>)testMethod.Parent.Properties.Get("Actions");
                }

                set
                {
                    testMethod.Parent.Properties.Set("Actions", value);
                }
            }
        }
    }
```

**Comment by jcansdale** [comment]
Here's a fixed version where assert methods can be executed in any order. I've also changed the test naming to use # (to imply tests are actually parts of a method):

```c#
    using System;
    using System.Collections.Generic;
    using NUnit.Framework.Interfaces;
    using NUnit.Framework.Internal;
    using Internal.Commands;

    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = true)]
    public class MultiAssertAttribute : NUnitAttribute, IImplyFixture, ITestBuilder, IWrapTestMethod
    {
        int assertCount;

        public MultiAssertAttribute(int assertCount)
        {
            this.assertCount = assertCount;
        }

        public IEnumerable<TestMethod> BuildFrom(IMethodInfo method, Test suite)
        {
            var testMethodList = new List<TestMethod>();
            for (int n = 0; n < assertCount; n++)
            {
                var testMethod = new TestMethod(method, suite);
                testMethod.Properties.Set("AssertIndex", n);
                var label = "#" + (n + 1);
                testMethod.Name += label;
                testMethod.FullName += label;
                testMethodList.Add(testMethod);
            }

            return testMethodList;
        }

        public TestCommand Wrap(TestCommand command)
        {
            var testMethod = (TestMethod)command.Test;
            return new ActionTestMethodCommand(testMethod);
        }

        class ActionTestMethodCommand : TestMethodCommand
        {
            TestMethod testMethod;

            public ActionTestMethodCommand(TestMethod testMethod) : base(testMethod)
            {
                this.testMethod = testMethod;
            }

            public override TestResult Execute(TestExecutionContext context)
            {
                var action = getActionFor(testMethod);
                action();

                context.CurrentResult.SetResult(ResultState.Success);
                return context.CurrentResult;
            }

            static Action getActionFor(TestMethod testMethod)
            {

                var actionEnumerator = (IEnumerator<Action>)testMethod.Parent.Properties.Get("ActionEnumerator");
                if (actionEnumerator == null)
                {
                    IEnumerable<Action> enumerableAction =
                        (IEnumerable<Action>)testMethod.Method.Invoke(testMethod.Fixture);
                    actionEnumerator = enumerableAction.GetEnumerator();
                    testMethod.Parent.Properties.Set("ActionEnumerator", actionEnumerator);
                    testMethod.Parent.Properties.Set("ActionList", new List<Action>());
                }

                var assertIndex = (int)testMethod.Properties.Get("AssertIndex");
                var actionList = (List<Action>)testMethod.Parent.Properties.Get("ActionList");
                while (actionList.Count <= assertIndex)
                {
                    actionEnumerator.MoveNext();
                    actionList.Add(actionEnumerator.Current);
                }

                return actionList[assertIndex];
            }
        }
    }
```

**Comment by jcansdale** [comment]
I'm wondering if it's possible to run custom code as part of the `ParameterizedMethod` setup and tear down? For example, I'd like to complete running the attributed method as part of the fixture tear down and check the expected number of actions were returned.

**Comment by CharliePoole** [comment]
If I understand correctly (from reading - I haven't tried it) this implementation requires that the attributed test method consist __only__ of a number of asserts. There can't be code before after or between the asserts. Have I got that right?

As to teardown of the parameterized method... I'm not sure what you mean. Once we are in teardown, the test is done. You can't do anything to change the result. TearDown is  for... tearing down. :-)

**Comment by jcansdale** [comment]
No, there can be code before and after the asserts. It behaves as if the test method is actually split into a number of separate tests. The asserts are yielded as `Action`s so they can be executed without terminating the attributed method.

I'd like the fixture teardown to complete running the test (in case there is any cleanup code at the end). It would also be nice if it could check there weren't more or less `Actions` yielded than the attribute declares. Alternatively the last test could assert that it is indeed the last.

**Comment by CharliePoole** [comment]
Why does the number of asserts have to be pre-declared? Normally, for example, a TestCaseSource just returns what it returns and that's the number of tests we create.

**Comment by jcansdale** [comment]
For a couple of reasons. I wanted to avoid mixing test discovery and test execution. By declaring the number of asserts, we know ahead of time how many tests to expect. Also, I want to make available the pass/fail status as early as possible. If we enumerated all of the `Action`s before running the asserts, the method would need to fully execute before getting any test results.

**Comment by CharliePoole** [comment]
That's interesting. I think you just implemented a version of what I've been calling "dynamic test cases" which are only discovered at execution time. Right now, it's just an idea but one that I wanted to eventually implement.

Current enumeration is "static" in the sense that it happens at discovery time,

**Comment by jcansdale** [comment]
I actually like the way that test discovery is static. It seems that the MSTest [DataSource] functionality is more dynamic. This makes their UI problematic and confusing. The first time a test with a [DataSource]
runs, the test returns multiple results. On subsequent runs it knows how to show these results as tests on the list. These tests are effectively discovered at execution time.

This is why I'm keen to declare ahead of time how many test/assert actions to expect. That way static test discovery works without mixing test code with discovery code.

**Comment by CharliePoole** [comment]
In fact, we've considered making NUnit look like MsTest in this regard in the adapter - just to make it easier to interface with the TestWindow.

Still, even with our "static" test loading, NUnit doesn't need to know in advance how many test cases will be returned from a TestCaseSource or ValueSource. I think the difference in your case is that the "data" (actions) is only created by executing the test, so it has to be more dynamic.

This is pretty interesting stuff, I have to say. Nevertheless, it doesn't seem to satisfy the request for a more traditional-looking MultipleAssert capability. :-(

In the long term, I think NUnit tests will need to return multiple results for various reasons. I listed three of them originally. Interfacing with the TestExplorer is probably a fourth, since I have no reason to expect Microsoft to change their overall design, which is modeled on MsTest. If that's going to happen, I think it's worth your while to be part of the discussion on #391 about how those results are presented to runners, what fallbacks are availble, etc.

**Comment by CharliePoole** [comment]
Since Multiple Asserts has been implemented using a different approach, I'm closing this.
