### ISSUE TITLE
mono 4.4 nunit 3.4.1, windows does not work (did i do something incorrect?)

### ISSUE THREAD

**Issue by dbones** [nunit/nunit#1744]
hi I am trying use mono,, at the moment on windows, but ultimately on Linux.

i have tried framework set to mono, mono-4.0, 4.0 and 4.5.

here is the command and the output.

```

C:\dev\bitbucket\arm-chair\tools>mono C:\dev\bitbucket\arm-chair\tools/nunit/bin/nunit3-console.exe /result:test-results.xml /framework=mono  /work:C:\dev\bitbucket\arm-chair\output/test C:\dev\bitbucket\arm-chair\src\ArmChair.Tests\bin\Debug\ArmChair.Tests.dll
NUnit Console Runner 3.4.1
Copyright (C) 2016 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 6.2.9200.0
  CLR Version: 4.0.30319.42000

Test Files
    C:\dev\bitbucket\arm-chair\src\ArmChair.Tests\bin\Debug\ArmChair.Tests.dll

The requested framework mono is unknown or not available.
```

**Comment by dbones** [comment]
ps i also tried the same test using 2.6.4, but it hangs on windows.

this person seems to have run into the same issue.
http://stackoverflow.com/questions/31186867/how-to-run-nunit-3-0-with-mono-4-0-runtime

however the given answer is not what i would want, (I download the version of nunit in my build script, and would like to use that version, not the mono provided one as it seems to be outdated, 2.4.8)

**Comment by CharliePoole** [comment]
I believe you are running into #1645
