### ISSUE TITLE
TestCase Attribute should support a named parameter for Properties

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1747]
@utcntt commented on [Mon Aug 15 2016](https://github.com/nunit/docs/issues/103)

Right now, TestCase Attribute doesn't support any named parameter for Properties. In case users want to set a property for a test case, they have to use TestCaseData (https://github.com/nunit/docs/wiki/TestCaseData). In my company, we are going to use a Property to link a test case with an issue number => Developers fix an issue, we can execute all related test cases to make sure that the issue is really fixed.

**Comment by utcntt** [comment]
Thank you, @CharliePoole !

**Comment by phillipsj** [comment]
@ChrisMaddock I would like to give this a try.

**Comment by ChrisMaddock** [comment]
Thought I recognised your name @phillipsj - I see you did those Cake NUnit Labels PRs. Welcome to NUnit! 😄 

The issues all yours - look forward to the PR. 🙂 Shout up if you have any questions - I've assigned this to myself to track progress.

**Comment by ChrisMaddock** [comment]
@phillipsj - did you have an idea of what you were planning in terms of an API for this? I'm not sure the best way to specify string/value pairs in an attribute to be honest.

@CharliePoole - did you have any thoughts about what this would look like when you moved it over?

**Comment by CharliePoole** [comment]
To be honest, I didn't give it much. It does present a problem, since we have to specify two things in one property value. The only obvious solution I can see is "key=value", limiting the values to strings.

@phillipsj If it turns out that it was a bad idea to accept this issue in the first place, that's a vaild outcome as well.

**Comment by ChrisMaddock** [comment]
> The only obvious solution I can see is "key=value", limiting the values to strings.

This reminds me of our current 'escaping separators' problem with `TestContext.TestParameters` - I wouldn't be too keen to add that to another place...

Unless we can come up with with a nice API, I personally think we should close the issue as wont-fix - with using TestCaseData being the requirement. Will leave this open a little longer to see if anyone else has any inspired ideas for how we can wrap this up.

@phillipsj - did you have a particular interest in this functionality, or were you looking around for good first-nunit-issues? If the former, feel free to make your case, if the latter, I'm sure we can find something similar!

**Comment by CharliePoole** [comment]
While this isn't quite as bad as the parameters issue, I'm inclined to agree with Chris.

As a potential workaround for the OP, I wonder if an extension method would work on an attribute.

**Comment by phillipsj** [comment]
I seen it was marked for beginning.  I haven't given it much thought yet,
but it does seem a challenging implementation to be clean.

**Comment by ChrisMaddock** [comment]
Without any better API suggestions, I'm going to go ahead and close this issue.

Sorry about that @phillipsj - can we help you find something else? I'd love someone to take on https://github.com/nunit/nunit/issues/2405 *whistles*
