### ISSUE TITLE
Error message "File type is not supported" when uses .nunit configuration file

### ISSUE THREAD

**Issue by NikolayPianikov** [nunit/nunit#1748]
Version dev-03141
[714679585.zip](https://github.com/nunit/nunit/files/418109/714679585.zip)
NUnit.Extension.NUnitProjectLoader.3.5.0-dev-03141 exists in the "packages" directory.

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit-console #30](https://github.com/nunit/nunit-console/issues/30) via [**ZenHub**](https://www.zenhub.com/)
