### ISSUE TITLE
*QUESTION* Create new Fixture for every Test

### ISSUE THREAD

**Issue by k0st1x** [nunit/nunit#1752]
Is there any method to run a new TestFixture for every Test (like in xunit workflow)?
(this question is similar to http://stackoverflow.com/q/6905406/453092 )

**Comment by rprouse** [comment]
That isn't possible in NUnit, but you can get the same effect by re-initializing all of your member variables in a `[SetUp]` method.

**Comment by CharliePoole** [comment]
We have periodically considered it as an optional feature, but have never implemented it. It's possible we will consider it again in the future.

Jim's view that creating only one instance of the fixture for all tests was a mistake is an opinion of his, not of everyone who worked on and works on NUnit. If we agreed with him, we would have changed it. :-)

That said, you have to be aware that changes you make in the object state can impact other tests. OTOH, with xunit, you have to be aware that changes in the object state won't live past the execution of the single test. 

BTW, having one object for all the tests is what enables OneTimeSetUp, formerly called TestFixtureSetUp. Jim and I disagree on the value of that feature too. :-)

**Comment by jcansdale** [comment]
It's tempting to create a new test attribute called [Fact] with xUnit like semantics. :wink:

**Comment by rprouse** [comment]
Careful @jcansdale, you could get yourself banned around here for such crazy talk :laughing:

**Comment by k0st1x** [comment]
Single Fixture per Test will be great for Parallel Test Execution.
