### ISSUE TITLE
NUnit console runner cannot run tests with .nunit project file?

### ISSUE THREAD

**Issue by niks-** [nunit/nunit#1754]
Have the same issue as in the ticket #1525.
I don't understand how to setup my environment to use NUnit.Runners instead of NUnit.ConsoleRunner.

I have two build steps. 
First is executed on one machine. It builds MS VisualStudio solution which has all these packages http://prntscr.com/c75o6u
Second is executed on other machine. It copies build result files to this machine with all packages and execute command "NUnit.ConsoleRunner.3.4.0\tools\nunit3-console.exe C:\......\project.nunit"

Is it possible to re-configure to use NUnit.Runners instead of NUnit.ConsoleRunner?

Please note that I have "tools\nunit3-console.exe" only in "NUnit.ConsoleRunner.3.4.0" folder out of all these folders http://prntscr.com/c75o6u
All packages were added to solution via NuGet Package Manager

**Comment by CharliePoole** [comment]
Your list of packages installed has unnecessary packages. NUnit.Console is the same as the old NUnit.Runners. Both of them are virtual packages used to install a list  of other packages. The nunit3-console program is in the NUnit.ConsoleRunner package only.

You can copy the packages to .another machine if you keep all the directories in the same relative location to one another.

**Comment by niks-** [comment]
This is what I did. Copied all packages to another machine within the same relative location. 
However when I run NUnit.ConsoleRunner.3.4.0\tools\nunit3-console.exe C:......\project.nunit, it fails with File Type is not supported error

**Comment by niks-** [comment]
Moved VisualStudio solution build and NUnit test run to the same machine.
If you don't copy NUnit packages manually, it works fine.

**Comment by CharliePoole** [comment]
In principle, you should be able to do it manually. When I'm developing the structure of new packages, I always create it manually first, get it working and then write a nuspec file that builds the same structure.

Things that you might miss in copying: 
 * Any references created by a package (doesn't apply to tools)
 * Any content files that are copied to the output directory

For NUnit and its extensions, the key is to have the correct .addins file in the directory that holds nunit.engine.dll. NUnit _only_ finds extensions that are pointed to by this file. This particular error seems to indicate that it can't find the extension that loads .nunit files.
