### ISSUE TITLE
Option to implement IXmlNodeBuilder on ConstraintResult

### ISSUE THREAD

**Issue by brian-reichle** [nunit/nunit#1756]
It would be nice if we could implement `IXmlNodeBuilder` on custom `ConstraintResult`'s and have it contribute to the test's result node.

**Rationale:**
Sometimes I create a custom constraint that would benefit from supplemental detail which cannot be adequately expressed in text form. For example, I created a constraint that compares the area covered by two [geometries](https://msdn.microsoft.com/en-us/library/system.windows.media.geometry%28v=vs.110%29.aspx), expressing the differences between the geometries in text form results in something that is difficult to visualize. But if I can add supplemental detail to the result xml, then my corresponding xslt can generate an embedded SVG that makes it clear why it failed.
I can already achieve something similar (to a limited degree) by combining the constraint with an attribute implementing `IWrapSetUpTearDown`, but this requires all the supplemental detail to be included in the message (in a parse-able form), is error prone and doesn't scale well to situations like comparing [regions's](https://msdn.microsoft.com/en-us/library/windows/desktop/dd162913%28v=vs.85%29.aspx).

**Comment by CharliePoole** [comment]
Rather than initially dealing with the implementation detail of using `IXmlNodeBuilder` at first, I think it would help if you could give an example of the sort of Xml you would like to see in the result.

There are a couple of ways this would help:

1. There may be a feature where users are able to add to the XML __without__ creating any custom extensions - something like the way we allow text to be added to the test result now.

2. We already have issue #1743, which anticipates the possiblility of having individual results for any given assert. Your request brings up some questions about the design for that feature, which should logically be implemented first.

**Comment by brian-reichle** [comment]
In the case of the constraint comparing geometries, I would like to add elements containing path information representing the actual, expected, missing and extra areas. It would also be useful to include size/scale information and some guide lines that don't make sense in message but are helpful in the image.

    <failure>
      <message>
        <![CDATA[  Expected: M15.5,12L103.5,12C105.432998657227,12,107,13.7908611297607,107,16L107,103C107,104.656852722168,105.432998657227,106,103.5,106L15.5,106C13.0147190093994,106,11,104.656852722168,11,103L11,16C11,13.7908611297607,13.0147190093994,12,15.5,12z (9010.87049087584)
      Tolerance: 0.0001
      Actual: M15.5,12L107,12 107,103C107,104.656852722168,105.432998657227,106,103.5,106L15.5,106C13.0147190093994,106,11,104.656852722168,11,103L11,22C11,16.4771518707275,13.0147190093994,12,15.5,12z (9008.00099728012)
      Extra: F1M103.5,12L107,12L107,16C107,13.7908611297607,105.432998657227,12,103.5,12z (3.28235325577623)
      Missing: F1M15.5,12C13.0147190093994,12,11,16.4771518707275,11,22L11,16C11,13.7908611297607,13.0147190093994,12,15.5,12z (6.1518410924938)
    ]]>
      </message>
      <stack-trace>...</stack-trace>
      <path-data width="120" height="120" scale="2">
        <expected><![CDATA[M15.5,12L103.5,12C105.432998657227,12,107,13.7908611297607,107,16L107,103C107,104.656852722168,105.432998657227,106,103.5,106L15.5,106C13.0147190093994,106,11,104.656852722168,11,103L11,16C11,13.7908611297607,13.0147190093994,12,15.5,12z ]]></expected>
        <actual><![CDATA[M15.5,12L107,12 107,103C107,104.656852722168,105.432998657227,106,103.5,106L15.5,106C13.0147190093994,106,11,104.656852722168,11,103L11,22C11,16.4771518707275,13.0147190093994,12,15.5,12z ]]></actual>
        <extra><![CDATA[M103.5,12L107,12L107,16C107,13.7908611297607,105.432998657227,12,103.5,12z ]]></extra>
        <missing><![CDATA[M15.5,12C13.0147190093994,12,11,16.4771518707275,11,22L11,16C11,13.7908611297607,13.0147190093994,12,15.5,12z ]]></missing>
        <guides><![CDATA[M10,10h100v100h-100zM11,12h96v94h-96z]]></guides>
      </path-data>
    </failure>

My transform is then able use the content of the `path-data` element to generate an svg to include in the test results.

    ...
    <svg width="240" height="240" xmlns="http://www.w3.org/2000/svg">
      <g transform="scale(2,2)">
        <path class="AreaActual" d="M15.5,12L107,12 107,103C107,104.656852722168,105.432998657227,106,103.5,106L15.5,106C13.0147190093994,106,11,104.656852722168,11,103L11,22C11,16.4771518707275,13.0147190093994,12,15.5,12z "></path>
        <path class="AreaExtra" d="M103.5,12L107,12L107,16C107,13.7908611297607,105.432998657227,12,103.5,12z "></path>
        <path class="AreaMissing" d="M15.5,12C13.0147190093994,12,11,16.4771518707275,11,22L11,16C11,13.7908611297607,13.0147190093994,12,15.5,12z "></path>
        <path class="Guides" d="M10,10h100v100h-100zM11,12h96v94h-96z"></path>
      </g>
    </svg>
    ...

In the case of comparing window regions, I would like to be able to provide a base64 encoded bitmap depicting the differences and getting the xslt to turn it into an embedded image with a data URI.

Having thought more about this; being able to supply structure would be nice, but all I really need is to be able to have the custom `ConstraintResult` supply a series of key-value pairs that are made available in the resulting xml.

**Comment by brian-reichle** [comment]
Of course, if constraints are allowed to provide key-value pairs, it might be a good idea to take this a step further and extract the expected/actual values from the messages of standard constraints and give runners/custom style sheets more formatting options.

**Comment by rprouse** [comment]
I am closing old Idea issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
