### ISSUE TITLE
Run test for multiple iteration will start multiple nunit agent

### ISSUE THREAD

**Issue by levimm** [nunit/nunit#1761]
Hi Guys,

I'm using this pattern to run test for multiple iterations.

`
string[] arg = {@"someDll.dll", "--dispose-runners" };`
`
    for (int i = 0; i < 3; i++)
        ConsoleRunner.Program.Main(arg);`

In second iteration, two nunit-agent.exe are running, and in third iteration, three agents are running.
I notice the dll is always added to InputFiles in CommandLineOptions so the created testPackage contains multiple subpackages.
Is this intented?

Cheers

**Comment by CharliePoole** [comment]
@levimm Moving this to our new nunit-console repository. Don't feel bad, it is brand new. You're probably only the first to get caught this way.

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit-console #40](https://github.com/nunit/nunit-console/issues/40) via [**ZenHub**](https://www.zenhub.com/)
