### ISSUE TITLE
Test Attribute - Ignore() doesn't work (Works only for TestCase attribute)

### ISSUE THREAD

**Issue by Haxy89** [nunit/nunit#1762]
This doesn't work:
```
[Test]
        [Ignore("Need fix")]
        public void testMethod()
        {
}
```
This works:
```
[TestCase]
        [Ignore("Need fix")]
        public void testMethod()
        {
}
```

**Comment by rprouse** [comment]
@Haxy89 I am pretty sure that the ignore attribute does work as listed, it is very widely used. It is probably a problem with the test runner you are using. Probably an older NUnit 2 test runner with NUnit 3 tests.

1. What version of NUnit are you using?
2. How are you running your tests?
3. Which test runner are you using?

I am going to leave this open for now and mark this as a question. Please get back to me and we will help you figure out what is wrong.

**Comment by Haxy89** [comment]
Ok, I need to clarify this. Ignore doesn't work when is before Test: 

`[Ignore("")]
[Test]`

**Comment by rprouse** [comment]
We can confirm that, but order shouldn't make any difference since we are using reflection to find the attributes by type and order doesn't matter. Can you provide the info I asked for above so we can check your setup?

**Comment by rprouse** [comment]
@Haxy89 you must have a problem with your setup or your runners. I am closing this issue, but feel free to post the information I asked for so I can help you.

I created the following test class,

```C#
[TestFixture]
public class IgnoreTests
{
    [Ignore("NUnit Issue #1762")]
    [Test]
    public void IgnoreBeforeTest()
    {
        Assert.Fail("This test should be ignored");
    }

    [Test]
    [Ignore("NUnit Issue #1762")]
    public void IgnoreAfterTest()
    {
        Assert.Fail("This test should be ignored");
    }

    [Ignore("NUnit Issue #1762")]
    [TestCase(1)]
    public void IgnoreBeforeTestCase(int i)
    {
        Assert.Fail("This test should be ignored");
    }

    [TestCase(1)]
    [Ignore("NUnit Issue #1762")]
    public void IgnoreAfterTestCase(int i)
    {
        Assert.Fail("This test should be ignored");
    }
}
```

All tests are ignored and the test suite passes with the Visual Studio Adapter,

![image](https://cloud.githubusercontent.com/assets/493828/18006403/501d827c-6b6d-11e6-82a3-7870d231941f.png)

And on the command line using nunit3-console.exe

```
Tests Not Run

1) Ignored : nunit.v3.IgnoreTests.IgnoreAfterTest
NUnit Issue #1762

2) Ignored : nunit.v3.IgnoreTests.IgnoreAfterTestCase(1)
OneTimeSetUp: NUnit Issue #1762

3) Ignored : nunit.v3.IgnoreTests.IgnoreBeforeTest
NUnit Issue #1762

4) Ignored : nunit.v3.IgnoreTests.IgnoreBeforeTestCase(1)
OneTimeSetUp: NUnit Issue #1762
```
