### ISSUE TITLE
Add auto message option to command line

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1763]
I am suggesting this out of laziness :)

I am often given large test suites to work with that have limited, or no, messages on the asserts.  Sometimes a single test will have > 20 asserts in it.

Without wanting to discuss the merits of this kind of test suite implementation, it is very difficult at times to determine why a particular test is failing.   Which assert actually failed?  Yes, every assert could have a message added to ti, and probably should, but if the suite has 10000 asserts...

It would seem that an option to automatically define a message for each assert that does not have one already might be very useful.  The message could be as simple as the ordinal position of the assert in the test ("#1", "#2", ...).  If an assert already has a message it would be used, but the ordinal would still be incremented for the next assert.

This way, when a failure occurs, finding the failing assert would only involve counting the asserts to find the correct one.

**Comment by CharliePoole** [comment]
It doesn't seem as if the assert count would be easier than the line number, which is already given.

OTOH I've often thought we should generate a default message like "Equal constraint failed" when the user did not supply one.

**Comment by oznetmaster** [comment]
CF does not have line numbers :(

**Comment by oznetmaster** [comment]
Any further thoughts on this?

**Comment by rprouse** [comment]
I think this is one of those issues that highlights the need to split out
the framework. It seems unneeded everywhere except CF which doesn't have
line numbers.

I also feel that you should be putting in the work on an as needed basis to
improve your tests by adding messages to long tests that fail rather than
adding more complexity to the framework. I don't want to take on the
maintenance costs. Lazy on the other side ;-)

**Comment by rprouse** [comment]
I also don't think this would be an easy fix with parallel test runs and
async/await within tests. I am inclined to close as won't fix.

**Comment by oznetmaster** [comment]
> 20,000 asserts, with NO messages.  I do not write the test suite.  Just trying to make it work.  From what I have seen, this is not a unique situation.

Parallel would not be an issue, since the ordinal of the asserts could be determined statically.  The order the tests run in is not relevant.

**Comment by rprouse** [comment]
I don't think a static counter would work, multiple test methods could be running at the same time. We could probably add something to the test context.

> 20,000 asserts, with NO messages. I do not write the test suite. Just trying to make it work. From what I have seen, this is not a unique situation.

I feel your pain, but I still feel that this is a very limited use case scenario. It is limited to CF because of no line numbers. That is why I am reticent to add it to all platforms to work around limitations in one.

**Comment by rprouse** [comment]
Wouldn't we also have to put the counter at the entry point of every assert (or at least the final overload)? We can't do it in the constraints because they can be chained. Seems to me that we could easily miss asserts now or in the future. Do we also add to assumptions or the assert helpers?

**Comment by rprouse** [comment]
| OTOH I've often thought we should generate a default message like "Equal constraint failed" when the user did not supply one.

I would be okay with something like this. At least it would narrow down which of the asserts are failing and might even be useful in chained constraints.

**Comment by CharliePoole** [comment]
@oznetmaster So CF stack traces never have line numbers? I didn't realize that.

Would a default message per constraint help?

**Comment by oznetmaster** [comment]
It might help.  But if 20 asserts in a test are the same kind of assert, it is of limited value :(

**Comment by CharliePoole** [comment]
I don't see this as being of general use.
