### ISSUE TITLE
Ability to derive from TestCaseSourceAttribute

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1764]
I need to derive a new attribute from TestCaseSourceAttribute, but have discovered that all of the needed helper methods are private :(

Wouldn't it make sense to make them protected so that a derived attribute would have access to them?

The only alternative is to copy all the source code into the new attribute, which make it really not a derived attribute, but a new one.

**Comment by CharliePoole** [comment]
On the one hand, the idea was to make all attributes stand on their own, depending only on interfaces.

On the other hand, data sourcing attributes are quite complex and it's a hassle to have to implement all the functionality to create an attribute that is only slightly different.

And on the third hand, I'm delinquent in my task of documenting custom attribute creation.

Can you identify what you want to use? Can we break some functionality out in helper classes and avoid having to support our attributes as base classes?

**Comment by oznetmaster** [comment]
This is how xUnit does it.  It is very easy:
```
    /// <summary>
    /// Operates as per <see cref="MemberDataAttribute"/>, but adds a final boolean value to the list of arguments,
    /// permuted through both false and true.
    /// </summary>
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true, Inherited = true)]
    internal class PerCompilationTypeAttribute : DataAttribute
    {
        private static readonly object s_boxedFalse = false;
        private static readonly object s_boxedTrue = true;

        private readonly MemberDataAttribute delegatedTo;

        public PerCompilationTypeAttribute(string memberName, params object[] parameters)
        {
            delegatedTo = new MemberDataAttribute(memberName, parameters);
        }

        public override IEnumerable<object[]> GetData(MethodInfo testMethod)
        {
            // Re-using the arrays would be a nice optimization, and safe since this is internal and we could
            // just not do the sort of uses that would break that, but xUnit pre-loads GetData() results and
            // we'd therefore end up with multiple copies of the last result.
            foreach (object[] received in delegatedTo.GetData(testMethod))
            {
                object[] withFalse = new object[received.Length + 1];
                object[] withTrue = new object[received.Length + 1];

                withFalse[received.Length] = s_boxedFalse;
                withTrue[received.Length] = s_boxedTrue;

                for (int i = 0; i != received.Length; ++i)
                {
                    object arg = received[i];
                    withFalse[i] = arg;
                    withTrue[i] = arg;
                }

                yield return withFalse;
                yield return withTrue;
            }
        }
    }
```

**Comment by CharliePoole** [comment]
If I read the code right, this oddly named attribute gets the set of arguments from the base class and then adds an extra argument of type bool at the end, returning two sets of args for each one received, with the final bool set to true and false. Is this what you are trying to do? Is this part of your project of converting some xunit tests to nunit?

It would be better to know what you are trying to do, since NUnit has other ways of doing the same thing, including ways of filling in a boolean argument with true and false values.

That said, if we were to go ahead and make some methods protected, which methods would that be? Why are you using TestCaseSourceAttribute in particular?

**Comment by oznetmaster** [comment]
Yes, that is what it does.  It modifies the xUnit equivalent of any TestCaseSource as you noted.

How would you do the same thing in NUnit, which really would mean merging two data source by append one to the end of the other, and iterating over all possible values.

**Comment by CharliePoole** [comment]
It's available only when you are specifying the data separately for each argument, using combinatorial, pairwise or sequential test case generation. If the type is bool or enum and no other data is given, then all possible values are used.

It may not work here, if you are specifying all the other arguments together.

Of course, you can use a test case source method that reads a list of arguments and does the same thing, but the code would be in your test itself, not in an attribute.

**Comment by CharliePoole** [comment]
I can see that being able to reuse test case sources by combining them in various ways would be useful. You might want to select only certain args, add args as here or join data from two sources. Currently, we can only do that if you are using ValueSource.

**Comment by rprouse** [comment]
I am closing old Idea issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
