### ISSUE TITLE
NUnit3: ExpectedException with TestCase

### ISSUE THREAD

**Issue by niks-** [nunit/nunit#1769]
I have the following test in Nunit 2
```C#       
[TestCase(false, TestName = "SendEmail_MissingTo_Error_Sync", ExpectedException = typeof(ArgumentOutOfRangeException))]
        [TestCase(true, TestName = "SendEmail_MissingTo_Error_Async")]
        public void SendEmail_MissingTo_Error(bool useAsync)
        {
            _message = new MailMessage();
            _message.From = new MailAddress("UnitTests1@sosonlinebackup.com");
            SendEmail(useAsync);
            //_config.VerifyAllExpectations();
            _log.AssertWasNotCalled(x => x.Debug(Arg<string>.Is.Anything));
            _log.AssertWasNotCalled(x => x.Warn(Arg<string>.Is.Anything));
            //_log.AssertWasCalled(x => x.Error(Arg<string>.Is.Anything));
            _log.AssertWasCalled(x => x.Error(Arg<string>.Is.Anything, Arg<Exception>.Is.Anything));
        }
```

Is there a way in NUnit3 to use the same test code with parameters but in one case it pass and in other one it throws expected exception? Or there should be two separate tests

**Comment by rprouse** [comment]
@niks- you should split tests like this up into two tests, one for the success cases and one for the failure cases. It also allows you to name your tests to better indicate their purpose rather than relying on the `TestName`.

**Comment by rprouse** [comment]
I also assume that all of your `_log.Assert` calls are not executed when the exception is thrown, so are misleading and unnecessary code for the one test case. There is also no indication in that test which line you expect to throw. I assume it is the `SendEmail`, but it is always better to explicitly state your expectations.

**Comment by niks-** [comment]
@rprouse Thanks for reply. Will do as you mentioned.
