### ISSUE TITLE
Mono under Windows misreports current framework

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1774]
Under Windows, when running tests under mono 4.5 profile, the current framework is reported as mono-4.0. With .NET, this works as expected: if you run under net-4.5, that's what the current framework reports. 

This should also be tested to see what happens on linux.

NOTE: there may be limitations here, since the newer versions of mono only support a single "profile." The latest mono supports 4.6.1, although the directory is still named 4.5. Ideally, we should report what is actually used, in cases where it differs from what is asked for. But it should always be >= what is asked for. Running under 4.0 (only) is not a valid option if the user asked for 4.5, but running under 4.5 when the user asked for 4.0 is reasonable if 4.5 is what's available. Essentially, what's reported should be accurate in terms of the actual capabilities represented.

**Comment by rprouse** [comment]
Nobody has picked this up and nobody else has asked for this so closing.
