### ISSUE TITLE
TestFixture attribute Category constructor suggests property allows comma separated list

### ISSUE THREAD

**Issue by chriscore** [nunit/nunit#1786]
The help tooltip for the code [TestFixture(Category = "test")] says that: 

> "Gets and sets the category for this fixture. May be a comma-separated list of categories", 

but when adding a CategoryAttribute explicitly, the help shows the following tooltip: 

> "Construct attribute for a given category based on a name. The name may not contain the characters ',', '+', '-' or '!'. However, this is not checked in the constructor since it would cause an error to arise at as the test was loaded without giving a clear indication of where the problem is located. The error is handled in NUnitFramework.cs by marking the test as not runnable."

Does this mean that using the former, we may or may not use comma separated categories, as the latter seems to suggest its isn't allowed and one seems to contradict the other?

**Comment by CharliePoole** [comment]
Yes, that's true. Each CategoryAttribute can only specify one category while the Category property of TestFixture allows a comma-separated list.

The reason for the difference is twofold:

1. You can have multiple CategoryAttributes but not multiple properties of the same name.

2. CategoryAttribute is designed to allow inheritance. For example, if you derive `UrgentAttribute` from category attribute, it will apply category Urgent to any tests on which it appears.

**Comment by chriscore** [comment]
Thanks for the detailed response Charlie
