### ISSUE TITLE
Async setup with CallContext.LogicalSetData not working as expected.

### ISSUE THREAD

**Issue by GreenMoose2** [nunit/nunit#1788]
When I use CallContext.LogicalSetData in a async setup method it is not visible via LogicalGetData in the test method.

```
[TestFixture]
public class TestFixture
{
    [SetUp]
    public async Task TestFixtureSetUp()
        //public void TestFixtureSetUp() //Will make test pass
    {
        await Task.Delay(10);
        CallContext.LogicalSetData("key", 1);
    }
    [Test]
    public void Test()
    {
        Assert.AreEqual(1, CallContext.LogicalGetData("key")); //Fails
    }
}
```

**Comment by CharliePoole** [comment]
Interesting issue... we'll investigate.

As an aside... Hopefully you know your method named TestFixtureSetUp is not actually a TestFixtureSetUp in NUnit's sense. That is, it would be called once per method if you had more tests.

**Comment by GreenMoose2** [comment]
> Hopefully you know your method named TestFixtureSetUp is not actually a TestFixtureSetUp in NUnit's sense. That is, it would be called once per method if you had more tests.

Yeah, thanks (method was named as a result of a macro which names it according to the class name, hence the ambiguous name).

**Comment by jnm2** [comment]
Just found this issue. Marking as a duplicate since I had previously answered. Please see https://github.com/nunit/nunit/issues/1895#issuecomment-385130267.
