### ISSUE TITLE
Working with third-party Assertion Frameworks

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1803]
This is something we have not paid much attention to up to now, but it has come up in discussing how we will implement Multiple Assertions.

For the moment, I see this as a design issue. Clearly, we don't want to break third-party frameworks. However, we can only speculate about what might break them, because we don't know what they use or how they use it. In some cases (Open Source using a compatible license) we can look at the code. In others, we might have to be careful - perhaps the author or somebody who doesn't work on the nunit framework could look at the code for any incompatible licenses. In the case of commercial apps - if there are any - we can only ask the authors who may or may not want to cooperate.

In spite of the difficulty, I think we should at least try this. Let's start by creating a list of third-party assertion frameworks. Then we can look at popularity and select a number that we will look into more deeply. We should include at least one that uses NUnit assertions and one that is more standalone.

The list goes here. I'll start it with the ones I know about and edit the list if people post comments.
- Shoudly
- Fluent Assertions

**Comment by immeraufdemhund** [comment]
So I'm confused. I've used FluentAssertions before and they just used an extension method to hook into their own assertion methodology. (I'm kind of a fan of it, but our constraint model is close to theirs, I actually feel that they have a little more to offer with the class EquivalantOf...but that's beside the point) What is the idea behind working with them?

Or is this talking about chaining like they do? something like

```
Assert.That(objectToTest)
    .IsNotNull
    .IsEquivalentTo(expectedObject);
```

**Comment by CharliePoole** [comment]
You have to view this issue in the context of the overall Epic it's part of (#391). Some folks have said that we may break assertion frameworks that depend on NUnit if we are not careful. So I started this issue to try to create a list of what frameworks we should test with our new features, in order to avoid breaking them. 

Since I don't use any third-party stuff - it's called eating your own dogfood - I just put down the two that I've heard of. I don't actually know whether FluentAssertions references NUnit, throws it's own exceptions or what - only that I've heard NUnit users say they use it with with NUnit. I'm hoping to learn more from comments on this issue. :-)

**Comment by oznetmaster** [comment]
I use FluentAssertions with NUnit on CF!  So I know it works in that environment.

**Comment by CharliePoole** [comment]
@oznetmaster If you know anything about how it interfaces with NUnit, please post it here. I'm interested in

* Whether it references the framework and, if so, which version
* How it tells NUnit about failures and whether NUnit handles them correctly
* Any limitations you have encountered

Ultimately, we will use this to figure out what "API" they are using - that is, what must we avoid changing in order for it to keep working.

**Comment by jcansdale** [comment]
There's also mocking frameworks like NSubstitute, Moq and TypeMock that are commonly used with NUnit. They have assert like functionality when verifying called methods. It would be nice if these checks could be made inside a multi-assert (or at least not break NUnit's multi-assert functionality).

**Comment by CharliePoole** [comment]
@jcansdale That would be a change. That is, those frameworks have never worked correctly with NUnit. We treat their private exceptions as errors, not failures. Since we have already said that an unexpected exception (error) inside a multiple assert would terminate it, that's what would happen with them. That's obviously not the best solution. I'm just saying it's not a new problem.

I suggested figuring out a way to handle NSubstitute errors as failures a few years back. I figured I'd work on that one and then extend the solution to other mocking frameworks. However, the author didn't see any particular problem with their failures being treated as errors, since the messages display anyway. This feature might  be the place where the mock folks would change their mind and say "No, we want to be failures!" :smiley:

That said, it might be a lower priority. When I use mocks, I don't generally verify the result until the very end of my test anyway. In a multiple assert context, I'd do it after the Assert.Multiple block.

**Comment by CharliePoole** [comment]
@nunit/core-team @nunit/contributors I'd prefer not to keep this open as a discussion item. Can we either close it or decide on some thing concrete we need to do?

**Comment by rprouse** [comment]
Assuming each of these frameworks throws specific mocking exceptions, could the solution to this be as simple as having a list of exceptions as their string names. When we catch exceptions, if the names match, treat them as failures instead?

For now, I would vote to switch this to design and move to the backlog. Someone can go out to the mocking frameworks we want to support and find the exceptions we want to handle.

**Comment by CharliePoole** [comment]
I agree. Let's do that.

The original issue was assertion frameworks, with mocking frameworks added to the mix in @jcansdale 's comment. However, this solution works for them as well, so long as the designer includes any such frameworks that we want treated as errors. Anything we miss can always be added through a bug report in the future.

**Comment by CharliePoole** [comment]
I made it low priority but of course anybody can still work on it.

**Comment by CharliePoole** [comment]
This really isn't about Multiple Assertions, but applies to any exceptions from third-party frameworks. I'm removing it from the Multiple Assertions Epic.

**Comment by rprouse** [comment]
Shouldly and FluentAssertions are working and haven't made requests to us. This issue is marked as an idea/design/discussion but hasn't had contributions in years so I am closing. If anyone is interested in working on this idea, post your interest and the team will consider reopening.
