### ISSUE TITLE
Error message "arguments provided for method not taking any" seems incomplete / doesn't make much sense

### ISSUE THREAD

**Issue by heltonbiker** [nunit/nunit#1805]
I got an error message while using NUnit with `TestCaseSource` attribute.
The message is:

> Arguments provided for method not taking any

And is found in the line below:

https://github.com/nunit/nunit/blob/5f6b47144c2d7b69caa52b3ae24dbb740444f347/src/NUnitFramework/framework/Internal/Builders/NUnitTestCaseBuilder.cs#L217

I couldn't figure out what this means, since the sentence seems to be missing some part, it is grammatically weird. Taking any _what_?

My code, for context:

    [TestFixture]
    public class TransformaçãoLinearTestes
    {
        private TransformaçãoLinear target;

        [Test, TestCaseSource("Valores")]
        public void TransformNãoModificaValorPorDefault(double entrada)
        {
            target = new TransformaçãoLinear();
            Assert.AreEqual(entrada, target.Transform(entrada));
        }

        public static double[] Valores = new double[]
        {
            0, 1, -1, 0.5, -0.5
        };

    }

**Comment by ChrisMaddock** [comment]
The error message can be read as: "Arguments provided for method not taking any **_arguments_**". It's shown when you've given a parameter to a test method, but no source for this, e.g. if you have no `TestCaseSource` attribute in the above code. Any suggestions for how to improve that error message?

The issue at hand: I can't reproduce this problem with your code on NUnit 3.4.1. Which version of NUnit are you using?

**Comment by CharliePoole** [comment]
The message could be misleading, arising from some other error. In particular, it may be that NUnit can't decide whether the arguments are individual doubles or the entire array. As an experiment, try replacing the data source with this longer form:

```C#
        public static TestCaseData[] Valores = new TestCaseData[]
        {
            new TestCaseData(0.0),
            new TestCaseData(1.0),
            new TestCaseData(-1.0),
            new TestCaseData(0.5),
            new TestCaseData(-0.5)
        };
```

**Comment by heltonbiker** [comment]
Thanks, I already got everything running. I think perhaps there was some other quirk, the tests ran without recompiling, I don't know.

Anyway, the reason that I wrote here was not to get help getting my code running, but alert about a very confusing, and thus unhelpful message, IMO.

**Comment by heltonbiker** [comment]
@ChrisMaddock regarding your comment (which I only saw later), I could suggest some options, just as food for thought (I am not a native english speaker).

Instead of

> Arguments provided for method not taking any

some combination from the [optional] terms below could be used:

> Arguments provided [for method [\<name of method\>]] are not being [taken | consumed] [by that method][, please make sure [your provided method|\<methodName\>] [has the correct signature[for \<format of provided data\>]|[receives \<format of provided data> as argument[s]].

(sorry for the nested optionals...)

**Comment by CharliePoole** [comment]
Maybe "Arguments provided for method not taking arguments" :-)



2016-09-23 12:13 GMT-07:00 heltonbiker <notifications@github.com>:

**Comment by heltonbiker** [comment]
Or better yet:

> Arguments provided for method \<MethodName\> are not being used.[ Verify that your test method has the right number and type of parameters]

**Comment by CharliePoole** [comment]
@heltonbiker That sounds a little too gentle... more like a warning than an error. After all, we are marking the method as invalid.

My guess is you would have understood the message better if the circumstances were not so strange.

However, pronouns are always strange in a foreign language, and "any" used that way is OK but a bit unusual.

**Comment by ChrisMaddock** [comment]
I think there is a little room for improvement here. As the method name is already available at this point, including that in the error message might highlight to a user exactly where to look. 

@CharliePoole @heltonbiker - how do you both feel about a combination of both the above and going for:

> Arguments were provided for method: \<MethodName\>, which has no parameters.

I'll do a PR in time for 3.5, if this is agreed on. 😄

**Comment by heltonbiker** [comment]
@ChrisMaddock I believe the message you suggested is great. I would only replace "which" by "but it", since it is more clearly indicative of some kind of problem. Thus:

> Arguments were provided for method: <MethodName>, but it has no parameters.
