### ISSUE TITLE
[Parallelizable] by default

### ISSUE THREAD

**Issue by slipdef** [nunit/nunit#1807]
Is there a way to say that all tests in a particular assembly should be run in parallel? If I understood the docs correctly I must mark each and every test with [Parallelizable] attribute.

**Comment by CharliePoole** [comment]
Yes, put the `ParallelizableAttribute` on the assembly, like so...

```C#
[assembly: Parallelizable(ParallelScope.Children)]
```

This will give you as much parallelism as NUnit currently supports. That is, fixtures will run in parallel but methods within a fixture will run sequentially.

See the docs at https://github.com/nunit/docs/wiki/Parallelizable-Attribute for details.
