### ISSUE TITLE
Assert.AreEqual fails for Complex on Linux

### ISSUE THREAD

**Issue by pfgherardini** [nunit/nunit#1809]
Hi

The following test:

``` C#
[Test]
public void TestComplexWorks()
{
        Assert.AreEqual(new Complex(1, 100), new Complex(1, 100));
}
```

is failing for me on 3.4.1 on Linux. The same test works fine on Windows.

```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64
```

**Comment by rprouse** [comment]
When you run it on Windows, are you also using .NET Core 1.0.0-preview2-003131?

**Comment by pfgherardini** [comment]
Yes 

```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by rprouse** [comment]
Thanks, my guess is that there is a difference between the .NET Core implementation of `Complex` on Linux and Windows, or possibly a difference in reflection causing us to not use the `IEquatable<Complex>` interface.

**Comment by rprouse** [comment]
I am removing the Confirm tag and moving to the backlog.

**Comment by mikkelbu** [comment]
In #2069 there were references to  https://codeblog.jonskeet.uk/2017/10/08/diagnosing-a-linux-only-unit-test-failure/ and dotnet/coreclr#14391 about problems with "pair of doubles" and reflection on Linux 1.0.x runtime. It could be the same error here.
