### ISSUE TITLE
Build.ps1 fails if spaces in path

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#1811]
If the nunit repo is in a location with spaces in the path, the build.ps1 bootstrapping script fails.

The [latest version from Cake](https://github.com/cake-build/cake/blob/develop/build.ps1) (26/09/2017) appears to fix this issue. It does however:

- Specify a specific Cake version. I haven't yet looked at how this interacts with our current method of specifying in packages.config, but we should look in to that.
- Install the .NET Core cli. Are we ok with this?

Duplicating this in nunit-console, as it looks to have the same build.ps1

**Comment by rprouse** [comment]
I am okay with it installing the .NET Core CLI, we are going to need it soon anyway and it is a small install. Would it worry you @CharliePoole?

**Comment by CharliePoole** [comment]
@rprouse Assuming that it merely installs the package for Cake's or Roslyn's use, I don't see an issue. If it's in tools, our projects wouldn't be referencing it anyway.

@ChrisMaddock Rob and I have talked about setting up a common location for build files we share across projects. I'm going to initially set something up that works across the extensions I'm separating. This doesn't prevent working separately on this issue or the console if it's a problem, of course, but I hope we will end up with a single point for this sort of thing in the near future.

One question... AFAIK, the Cake guys don't version the scripts. Any suggestion for how we identify what we are talking about other than "the latest"? In a few months, this conversation may not make much sense to folks reading it. Maybe we could refer to the date of the last commit.

**Comment by ChrisMaddock** [comment]
> [...]setting up a common location for build files we share across projects[...]

Great - I imagine this is best waiting until then. I'll edit my original post with a script date

**Comment by CharliePoole** [comment]
@ChrisMaddock Will this be fixed by Cake 15.2?

**Comment by ChrisMaddock** [comment]
@CharliePoole - it was fixed by the updated build.ps1 that was added in #1832. 😄
