### ISSUE TITLE
What should happen?

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1813]
Porting a test suite from V2.

Lots of tests like this:
```
		[Test]
		public void BindTwice ()
			{
			var sock = new CrestronClientSocket ();
			IPEndPoint ep1 = new IPEndPoint (IPAddress.Loopback, 1256);
			IPEndPoint ep2 = new IPEndPoint (IPAddress.Loopback, 1257);

			sock.Bind (ep1);

			try
				{
				sock.Bind (ep2);
				Assert.Fail ("BindTwice #1");
				}
			catch (SocketException ex)
				{
				Assert.AreEqual (10022, ex.ErrorCode, "BindTwice #2");
				}
			catch
				{
				Assert.Fail ("BindTwice #3");
				}
			finally
				{
				sock.Close ();
				}
			}
```
The assumption is that if there is no exception the first Assert.Fail (#1) will be the one that is reported.  What is happening is that the #3 is being reported.

Is this the expected behavior in V3?

**Comment by oznetmaster** [comment]
It appears that the first Assert.Fail (#1) is throwing an exception which is then being caught by the empty catch clause, and then the Assert.Fail (#3) is happening.

**Comment by rprouse** [comment]
I'm surprised that worked in NUnit 2. Are you sure #2 was ever hit? You can fix it by catching the nunit exception and throwing.
