### ISSUE TITLE
NUnitLite on .NET Core - impossible to know which test is crashed.

### ISSUE THREAD

**Issue by xplicit** [nunit/nunit#1820]
Sometimes tests can crash on .NET Core (StackOverflowException,  hanging, etc). In this case extremely useful to know which tests is crashed from  a huge test suite. To know about it it would be great to output test case name at the beginning of the test and at the end of the test. But such functionality is absent in NUnitLite on .NET Core.

For example:

Option `--labels=On` does not work at all, option `--labels=All` shows test name only when test is finished, but not when started.
I could use `--labels=All` with `--explore` option to know the order of the tests to run (get the tests list by `--explore`) and find the last test was executed (with `--labels=All`), but `--explore` is absent in NUnitLite for .NET Core.

I could write my own `ITestEventListener` and output test names in the output on test start/finish, but `ITestEventListener` is defined in `NUnit.Engine` which is not supported on .NET Core.

So I have no way how to know which test is crashed/hang with NUnit. And it's very difficult to find that test manually in the suite of couple of thousands tests. NUnitLite should have ability which helps to know which test is started to execute.

**Comment by CharliePoole** [comment]
It sounds to me as if nunit/nunit-console#24 would resolve your problem, if ported to nunitlite.

Would you take a look at it and see if you agree?

**Comment by rprouse** [comment]
@xplicit I also think this is fixed in the latest version of `dotnet-test-nunit`. See nunit/dotnet-test-nunit#56

Is there any reason you prefer NUnitLite over the .NET Core test runner?

**Comment by xplicit** [comment]
@CharliePoole yes, it would be a great if the feature was ported to NUnitLite

@rprouse `dotnet-test-nunit` is not released yet and we set some settings/params at start of each assembly run,  so we have to move them somehow to config files. Is there a documentation how to use configuration files with .NET Core test runner?

**Comment by rprouse** [comment]
Nobody has picked this up and nobody else has asked for this so closing.
