### ISSUE TITLE
Unexpected time of array's testing.

### ISSUE THREAD

**Issue by constructor-igor** [nunit/nunit#1825]
```Assert.AreEqual(expected, actual);``` takes 1.5 seconds
```Assert.That(actual, Is.EquivalentTo(expected));``` continues minutes (stopped after **~10 minutes**)

```c#
        [Test]
        public void AreEqual_1024()
        {
            byte[,] actual = new byte[1024, 1024];
            byte[,] expected = new byte[1024, 1024];
            
            Assert.AreEqual(expected, actual);
        }
        [Test]
        public void EquivalentTo_1024()
        {
            byte[,] actual = new byte[1024, 1024];
            byte[,] expected = new byte[1024, 1024];

            Assert.That(actual, Is.EquivalentTo(expected));
        }
```

**Comment by constructor-igor** [comment]
A test (from real project) checks different ways of "big data [1024,1024]" processing and compares results.
I like Assert.That and changed Assert.AreEqual to Assert.That ;).

Sure, I can continue to use Assert.AreEqual in the case, but probably possible to implement special case for arrays?

**Comment by CharliePoole** [comment]
Hmmm... Isn't the special case for any extremely large collection rather than arrays? Or do you have an idea for an optimization that applies to arrays only?

**Comment by appel1** [comment]
Is it really an equivalent check you want in this case? Do you not care about the order of bytes?

**Comment by constructor-igor** [comment]
oops
yes, I need same order and it's enough to use ```Assert.That(actual, Is.EqualTo(expected));```
So, the issue can be closed.
