### ISSUE TITLE
Add Retry for failed tests only

### ISSUE THREAD

**Issue by meijin007** [nunit/nunit#1828]
Is it possible somehow?

**Comment by CharliePoole** [comment]
NUnit includes a `RetryAttribute` for tests that should be retried up to a maximum number of times if they fail. Please review the documentation.

**Comment by meijin007** [comment]
This is working only for tests without parameters. Is there any why to pass a parameters when we are using retry?

**Comment by CharliePoole** [comment]
If it isn't working for a particular use case we can reopen this issue. Please provide an example.

**Comment by meijin007** [comment]
This is the documentation on https://github.com/nunit/docs/wiki/Retry-Attribute :
"Since a parameterized test method represents a suite, RetryAttribute is ignored when it appears on such a method."

**Comment by CharliePoole** [comment]
@meijin007 Thanks for reminding me of that restriction, which I had forgotten. I'll reopen this and take a closer look.

**Comment by CharliePoole** [comment]
The documentation statement was a hold-over from NUnit 2 and is not correct. I have added a test to verify that Retry works on Test Cases. Note that the retry applies to each test case when used this way.

**Comment by ammark1** [comment]
Hi Charlie, I am facing a problem with Retry Attribute. NUnit is retaining the previous Failed value in 
TestContext.CurrentContext.Result.Outcome and hence my Test Case is Failed even if it is actually Passed in the second attempt. Please see the below code snippet, my code goes inside the First if loop because currentContext.Result.Outcome value is "Failed" in the second attempt as well in the TearDown method(although my Test gets passed during the second attempt):

[TearDown]
        public void TearDown()
        {
            try
            {
                var currentContext = TestContext.CurrentContext;
                var message = TestContext.CurrentContext.Result.Message;
                var stackTrace = TestContext.CurrentContext.Result.StackTrace;
                if (currentContext.Result.Outcome != ResultState.Success)
                {
                    var testName = currentContext.Test.Name;
                    string rootPath = AppDomain.CurrentDomain.BaseDirectory;
                    String filename = rootPath+"\\Report\\" + this.GetType().FullName + "." + testName + "_" + DateTime.Now.ToString("yyyy-MM-dd-HH-mm-ss") + ".png";
                    Console.WriteLine("filename: " + filename);
                    UtilityHelper.TakeScreenshot(_driver, filename);
                    if (Global.tempCount <= 1)
                        Global.test.Log(Status.Fail, stackTrace + message);
                }
                Log.Info("Teardown test");
                _driver.Quit();
            }
            catch { _driver.Dispose(); }
        }

**Comment by CharliePoole** [comment]
@ammark1 This specific issue was fixed and has been closed for a while. If you have a new problem, it's best to file a new issue.

**Comment by ammark1** [comment]
@CharliePoole New ticket created: #2619

**Comment by lakshmikrishnamurthy30** [comment]
Hi , 

By using Retry functionality, is it possible to rerun all failed tests at the end instead of immediately after the failed test?

**Comment by ChrisMaddock** [comment]
Not currently, no.
