### ISSUE TITLE
NUnitLite accepts --params option but does not make any use of it.

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1829]
At the time of implementing the --params option for the console, we put the option definition into CommandLineOptions.cs, which was then shared by nunit3-console and nunitlite, but we never implemented the option in TestRunner.cs. The intent was that somebody would implement it, but that never happened.

At this time, the option is recognized without error, but is never passed to the framework by the runner.

We should either implement the option or remove it from nunitlite so that an invalid option error is displayed.

**Comment by oznetmaster** [comment]
My CF build of nunitlite does recognize it, so I must have ported the code to do so from somewhere, but I do not remember doing so, and do not have it conditioned in any way.  So I never realized it was not supposed to be supported in nunitlite :(  I certainly believe it should be.  Do not see any reason for it not to be.

**Comment by KWodarczyk** [comment]
Hi Thanks for the feedback Charlie. Any reason why NUnitLite should not take same set of arguments as Console app ? Is it a lot of work ?

**Comment by CharliePoole** [comment]
No reason. I was just trying to lay out the options for whomever works on this.

**Comment by KWodarczyk** [comment]
Ok so I understand that this will be supported in near future ?

**Comment by oznetmaster** [comment]
I will back-port my CF code to propogate this to nunitlite, and also the tests.
