### ISSUE TITLE
Add --labels switch changes to nunilite and nunitlite tests

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1830]
As per @CharliePoole, I am opening this issue to make sure that the --label changes (issue24 nunit/nunit-console#78) made to the console are also made to nunitlite and its tests.

**Comment by CharliePoole** [comment]
That's what issue #1829, on which you just commented, is about. :-)

**Comment by oznetmaster** [comment]
No, it is not.  One is about --params, the other is about --labels. No relationship at all!

**Comment by CharliePoole** [comment]
Sorry... my mistake.

**Comment by CharliePoole** [comment]
I corrected the reference in your description, which was not pointing to the --labels issue but to PR #78 in this repository. Use `nunit/REPONAME#nn` to refer to issues and PR that are in another repo.

**Comment by oznetmaster** [comment]
I will implement this as soon as the nunit-console PR is merged, and my pending PR for @filename is merged, since it also modifies the same files as need to be modified for this.

**Comment by CharliePoole** [comment]
@oznetmaster We're still waiting for comments on that console PR about --labels, regarding a possible change to what we show for each option. It would be great to hear from you and @rprouse, as well as others!

**Comment by oznetmaster** [comment]
I am actually indifferent to the decision.  As long as the desired information is available by selecting the correct set of options, the rest is syntactic sugaring.

**Comment by oznetmaster** [comment]
Any progress on getting the console version of this merged?

**Comment by CharliePoole** [comment]
This is issue nunit/nunit-console#24 and PR nunit/nunit-console#124, which are still being worked on.
