### ISSUE TITLE
Get the time duration of a Test Script in Test TearDown

### ISSUE THREAD

**Issue by pradeeparutla** [nunit/nunit#1843]
Steps to reproduce:
1. Run a test script
2. Try to capture the Test duration in **TestScript TearDown** using TestExecutionContext.CurrentContext.CurrentResult(Return type of this object is TestResult) object.

Expected: It should show the actual time take to execute a test script.
Actual: It is showing the time duration as '0' ms  irrespective of time taken to run the tests.

Note: If we use the same object TestExecutionContext.CurrentContext.CurrentResult in **AssemblyCleanup(TestRun TearDown)**, then it is displaying the Time taken to execute a test script.

**Comment by CharliePoole** [comment]
You are referring to some classes internal to nunit like TestExecutionContext and to others that do not exist like TestScriptTeardown. Are you sure you are using nunit?

If you are, the test is not finished during TearDown so the duration is not yet set.

**Comment by pradeeparutla** [comment]
Hi Charlie,

I am using NUnit. When I say TestScriptTeardown, I mean the [teardown] attribute applied to a method which will be called at the end of each test script.
If TestExecutionContext is not the proper way to get the duration in TearDown, is there any way to get the test duration in the tearDown?

**Comment by CharliePoole** [comment]
An NUnit test case is defined as SetUp+Test Method+TearDown. The timing that we report includes all three of those phases. The duration is applied to the test result by the system after the TearDown returns. 

The result is that a test can never know it's own duration. It can, of course, time parts of itself. Theoretically, NUnit could make available some intermediate timer value for use in teardown but it doesn't seem to be necessary for any use cases that we would want to encourage.

The NUnit test engine, which runs tests for you, is extensible. One of the extension points is for test event listeners that report or do other processing on tests at particular points. In particular, you could create a listener that would do whatever you like at the time the test is complete. For example, you could create database entries about each test, including things like duration.

Putting such code inside the test assembly itself is not something we want to encourage. It's a violation of the single responsibility principle. A test should be a test, not a test reporting system.
