### ISSUE TITLE
NonGeneric TestFixtures derived from generic TestFixture does not work

### ISSUE THREAD

**Issue by fsalas** [nunit/nunit#1844]
Hi, the following code does not work as I expected

Given a base abstract test

```C#
[TestFixture]
public abstract class MyBaseTest<T>
{

    [Test]
    public CommonTest()
    {
...
    }

}
```

and a derived class

```C#
[TestFixture]
public class MyDerivedTest : MyBaseTest<MyClass>
{
   [Test]
   public void MySpecializedTest()
   {
  ....
   }
}
```

Neither base or derived tests appears in the runner, tested with vs runner and nunit-gui , if I remove the attributes in the base class then the derived tests appears.
I think this is an issue or I'm missing something

Thanks for the great work

**Comment by rprouse** [comment]
Have you tested this with the Console? We have similar reports against the VS Adapter, but those reports say it works in the console.

**Comment by fsalas** [comment]
no, I didn't check it with the console, but I do checked with nunit-gui master and the results are the same, so it is not just a vs adapter problem I think, I'm not used to console runner, couple of tries couldn't get it working yet

**Comment by rprouse** [comment]
@fsalas I think there must be something wrong with your code that is causing the failure. I tested with an abstract base class, generic base class and an abstract generic base class and all work as expected using the latest version of the framework (3.5) and the latest VS adapter.

Here is my test code if you want to try it,

```C#
[TestFixture]
public abstract class AbstractGenericBase<T>
{
    [Test]
    public void AbstractGenericBaseTest()
    {
        Assert.Pass("AbstractGenericBase");
    }

    public abstract void MustImplement();
}

[TestFixture]
public class DerivedAbstractGeneric : AbstractGenericBase<string>
{
    [Test]
    public void DerivedAbstractGenericTest()
    {
        Assert.Pass("DerivedAbstractGeneric");
    }

    public override void MustImplement()
    {
    }
}
```

Here is a screenshot of the test showing up in Visual Studio,

![image](https://cloud.githubusercontent.com/assets/493828/19402874/b8125340-9231-11e6-9a6c-22de4050c33e.png)

And here is the adapter output from VS,

```
------ Run test started ------
NUnit Adapter 3.4.1.0: Test execution started
Running all tests in C:\src\nunit\nunit-tests\nunit-v3\bin\Debug\nunit-v3.dll
NUnit3TestExecutor converted 52 of 52 NUnit test cases
SetUp failed for test fixture nunit.v3.GenericBase<T>
Fixture type contains generic parameters. You must either provide Type arguments or specify constructor arguments that allow NUnit to deduce the Type arguments.
NUnit Adapter 3.4.1.0: Test execution complete
========== Run test finished: 51 run (0:00:05.7826975) ==========
```

Note the error about the generic base class. That is expected, NUnit cannot construct a generic without knowing the type you want.

I am going to close this issue, but feel free to post if you have questions, we will see it.

**Comment by CharliePoole** [comment]
The TestFixture attribute on the abstract base is an error.

**Comment by rprouse** [comment]
>The TestFixture attribute on the abstract base is an error.

Yes, but I was trying to reproduce with the code given 😄

**Comment by CharliePoole** [comment]
I got that... I wanted to be sure that @fsalas understood.
