### ISSUE TITLE
Dll has no TestFixtures

### ISSUE THREAD

**Issue by joel-cass** [nunit/nunit#1849]
This works in 3.4.1 but not 3.5

1. Clone project https://github.com/nunit/nunit-csharp-samples
2. Open in VS, build, run tests = OK
3. Download nunit 3.5 zip from https://github.com/nunit/nunit/releases/tag/3.5
4. Run tests
```
"C:\dev-tools\NUnit-3.5.0\bin\net-4.5\nunitlite-runner.exe" cs-money.dll
NUnitLite 3.5.0 (.NET 4.5)
Copyright (C) 2016 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 6.2.9200.0
  CLR Version: 4.0.30319.42000

Test Files
    cs-money.dll

Errors and Failures

1) Invalid : C:/temp/nunit-csharp-samples-master/money/bin/Debug/cs-money.dll
Has no TestFixtures

Run Settings
    Number of Test Workers: 8
    Work Directory: C:\temp\nunit-csharp-samples-master\money\bin\Debug
    Internal Trace: Off

Test Run Summary
  Overall result: Failed
  Test Count: 0, Passed: 0, Failed: 0, Inconclusive: 0, Skipped: 0
  Start time: 2016-10-17 21:42:36Z
    End time: 2016-10-17 21:42:36Z
    Duration: 0.005 seconds
```

5. Download 3.4.1 zip from https://github.com/nunit/nunit/releases/3.4.1 and run:

```
"C:\dev-tools\NUnit-3.4.1\bin\net-4.5\nunitlite-runner.exe" cs-money.dll
NUnitLite 3.4.1 (.NET 4.5)
Copyright (C) 2016 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 6.2.9200.0
  CLR Version: 4.0.30319.42000

Test Files
    cs-money.dll

Run Settings
    Number of Test Workers: 8
    Work Directory: C:\temp\nunit-csharp-samples-master\money\bin\Debug
    Internal Trace: Off

Test Run Summary
  Overall result: Passed
  Test Count: 21, Passed: 21, Failed: 0, Inconclusive: 0, Skipped: 0
  Start time: 2016-10-17 21:44:49Z
    End time: 2016-10-17 21:44:49Z
    Duration: 0.113 seconds
```

To me this looks like a bug. Nothing in the documentation/change list suggests that the framework has changed; if extra packages are required in order to detect tests from the command line, it should be mentioned in the release notes.

**Comment by CharliePoole** [comment]
If I understand you correctly, you are mixing the 3.4.1 version of NUnit with NUnitlite 3.5. NUnitlite is a shortcut approach to running a test in a single assembly but, unlike the console runner and engine, the versions must match.

Since the NUnit 3.5 release just came out, the samples have not been updated to use it. You can update the references yourself.

**Comment by rprouse** [comment]
I am going to close this as a question. Normally you would run the tests using `nunit3-console.exe`, not the NUnitLite runner which is tied to a specific version of the framework as @CharliePoole stated.
