### ISSUE TITLE
Nunit test runner picking up ignored tests (ish) in tfs

### ISSUE THREAD

**Issue by dgee2** [nunit/nunit#1853]
Hi,

I'm running tests in TFS using the NUnit3TestAdapter nuget package. We have a test fixture that is completely ignored at the class level. We are getting error messages in the output saying: `The specified test case was not found in the current result context (mapping test id to test node).` I can't find any information in the documentation to say that this is not supported and it indeed has been in previous versions of NUnit but I can't explain why this error would happen after the upgrade to the new runner.

It should be noted that I don't see this error when running the tests within either Visual Studio, NCrunch or Resharper.

This seems to be similar but different to the following issue: #427

If anyone can shed any light on this, I would greatly appreciate it.

**Comment by CharliePoole** [comment]
Please try to select the right project when reporting errors. That way the right people are looking at it. Since you identified this as an adapter issue, I'm moving it there.

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit3-vs-adapter #241](https://github.com/nunit/nunit3-vs-adapter/issues/241) via [**ZenHub**](https://www.zenhub.com/)
