### ISSUE TITLE
No .msi provided for 3.5

### ISSUE THREAD

**Issue by joce** [nunit/nunit#1854]
Despite [mention](https://github.com/nunit/nunit/releases/tag/3.5) of an .msi containing the binaries in the wiki,

> This is also the first release where the NUnit Framework will not be included in the installer. Only
the console runner, engine and extensions will be available as an MSI installer. 

no such file appears to be available for download.

**Comment by ChrisMaddock** [comment]
The NUnit framework and NUnit console have been split in to two separate repositories, the msi for the console can now be found under that repository.

https://github.com/nunit/nunit-console/releases

Out of interest, what link did you follow to look for the new release, was it via nunit.org? @rprouse @CharliePoole - we should probably update that soon!

I'll close this issue now as a question - please feel free to comment further if you hit a problem! 😄

**Comment by joce** [comment]
Ha!  Thanks!

It was the link I found at the top of this page.
http://www.nunit.org/index.php?p=download

Having a ling to https://github.com/nunit/nunit-console/releases from
https://github.com/nunit/nunit/releases/tag/3.5 could maybe be preferable?
(as one might only want to have access to the framework from the nunit.org
link... but at the end of the day, it's your call!)

**Comment by ChrisMaddock** [comment]
The plan is that the framework and console may no longer always be released in sync, so there may not be a 3.6 console at the same time as the 3.6 framework - which would cause problems with linking between the two. But I agree it may have been helpful for the first release where the downloads were in separate places!

**Comment by joce** [comment]
Then post both links separately from nunit.org would definitely be helpful.
:-)

**Comment by rprouse** [comment]
Just went to the website repo to enter an issue for this, but I see you've already done it @ChrisMaddock. Thanks. 👍
