### ISSUE TITLE
build -testall

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1858]
this seems to only build everything now :(

how do I build and then test everything in one command?

**Comment by ChrisMaddock** [comment]
`build -t Test`

There used to be `build -Test` and `build -TestAll` which both did the same thing - then `TestAll` was removed. If you run the script with an 'invalid' target, it just runs the default, which is just to build.

Will close this now - go ahead and reopen if there's more to say!

**Comment by oznetmaster** [comment]
Is this documented somewhere?  If not, shouldn't it be?

**Comment by ChrisMaddock** [comment]
https://github.com/nunit/nunit/blob/master/BUILDING.md

Building.md was updated at the time, to remove `TestAll`. (There's #1730 to update it again for the console/framework split stuff, but that's a separate issue!) 

Is there somewhere else that still suggests `TestAll`?

**Comment by oznetmaster** [comment]
That page is inaccurate.  It lists the tasks that can be run.  One of these is "* TestAllFrameworks   Runs all framework tests. Dependent on Build.".  However, if that is used, an error occurs: Error: The target 'TestAllFrameworks' was not found.

I did not test all the others to find other errors in the documentation.

**Comment by CharliePoole** [comment]
I've been wondering about these Building.md pages. It seems as if they require a bunch of effort to keep up to date. Why don't we just tell people to read the build.cake file that actually contains the targets?

**Comment by rprouse** [comment]
We should probably add descriptions to our build tasks in the cake file. Then you can use the `--showdescription` command line option to show all the tasks. Here is the current output for this project,

```
λ .\build.ps1 --showdescription
Preparing to run build script...
Running build script...
Analyzing build script...
Processing build script...
Compiling build script...

Task                          Description
===============================================================================
Clean
InitializeBuild
Build45
Build40
Build35
Build20
BuildPortable
BuildSL
BuildCF
CheckForError
Test45
Test40
Test35
Test20
TestPortable
TestSL
TestCF
PackageSource
CreateImage
PackageFramework
PackageZip
PackageCF
UploadArtifacts
Rebuild
Build
Test
Package
Appveyor
Travis
Default
```

**Comment by CharliePoole** [comment]
That makes perfect sense.

**Comment by rprouse** [comment]
PR for the change is up and reviewed, so I am changing this from question to a build task.

**Comment by oznetmaster** [comment]
Is --showdescription documented somewhere? I am assuming it is.  I just do not seem to be able to find it.

**Comment by rprouse** [comment]
Show description is documented on `Cake.exe`, but that is non-obvious, so I added it to the BUILDING.md as part of the PR.

**Comment by oznetmaster** [comment]
Thank you.
