### ISSUE TITLE
Wrapping MethodInfo.Invoke or improving TestCommand wrappers

### ISSUE THREAD

**Issue by tomekpaszek** [nunit/nunit#1861]
Hi! 

First of all, great job with the product and the recent changes to the architecture. 

I was able to use extension points to achieve most things I needed for implementing nUnit in the tools I'm working on besides few small things. What I would like to achieve is to delegate the test's code invocation to a separate thread that I have control of (not just to spawn on a separate thread). In most places (besides TestMethodCommand) the invocation happpens via the Reflect class. Luckily the I was able to wrap the TestMethodCommand command without a problem but I couldn't find a soution for doing it globally or for the other points the Reflect.InvokeMethod method is used (like SetUpTearDownCommand). 

My solution was to introduce a global delegate field in Reflect that could be set before the run happens. Then, the method.Invoke in Reflect.InvokeMethod would be passed to the delegate if it's set. 

```
        public static Func<Func<object>, object> MethodCallWrapper { get; set; }
        public static object InvokeMethod( MethodInfo method, object fixture, params object[] args )
        {
            if(method != null)
            {
                try
                {
                    if (MethodCallWrapper != null)
                        return MethodCallWrapper(() => method.Invoke(fixture, args));
                    else
                        return method.Invoke(fixture, args);
                }
(...)
```

It's not the nicest solution but it was simple. Ideallly I would like to do it via wrappers or extension point but the IWrapTestMethod is flexible enough. What would be the best approach in your eyes for solving this problem so I could eventually make PR?

Tomek

**Comment by CharliePoole** [comment]
I think we dropped the ball on this question, which has been unanswered for a long time. Rob just closed it for lack of activity, but I thought I would give you a brief answer...

I don't think we would want a PR that allows injecting a global change into the way we do reflection internally. Additionally, such a change would affect __all__ calls through `Reflect.InvokeMethod`, not just calls to tests, and would __not__ affect any calls that we do using the .NET API directly.

It appears that you can do what you want using an attribute, one test at a time. You want to do it in a more general, crosscutting way. That's a good objective and it's the biggest lack in our extensibility API right now. We need to develop some API that allows generally injecting wrappers in all test cases, suites or both. If you have any ideas, please file another issue!
