### ISSUE TITLE
Two unit test projects are not testable, one is

### ISSUE THREAD

**Issue by XdX-Software** [nunit/nunit#1865]
Hi, 

I have a strange issue, I have three NUnit 3 unit test projects in one solution.
In one project I can execute all unit tests, but in the other two projects I get a strange error message.

No handler for message 'TestExecution.TestResult' when at state 'TestExecutionSentTestRunnerProcessStartInfo'
An exception occurred while invoking executor 'executor://dotnetunittestexecutor/v1': Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.
An existing connection was forcibly closed by the remote host

You can pull the solution here:
https://github.com/XdX-Software/XdX.FluentES
But, you must Pull the Branch "feature/more-and-better-unit-tests".

Unit tests are working in project "Tests.XdX.FluentES" and not working in the two other ones "Tests..."

Hope you can find the issue.

**Comment by rprouse** [comment]
It looks like you are using  .NET Core. This is a known and fixed issue that will be released soon. Please confirm so I can close.

**Comment by XdX-Software** [comment]
How should I confirm that the issue is solved, if the version where the issue is presumed fixed, is not released yet and I can not use it  :)

**Comment by rprouse** [comment]
Sorry, if you could confirm that you are using .NET Core, then it is a known issue in that repo that was fixed last week.

**Comment by rprouse** [comment]
See nunit/dotnet-test-nunit#58

**Comment by XdX-Software** [comment]
Ah, OK.

Yes, I confirm that this are .NET Core projects.

I hope you can release it this weekend like you planned it.

**Comment by rprouse** [comment]
Thanks, I am going to close this as a duplicate.
