### ISSUE TITLE
pnunit test framework

### ISSUE THREAD

**Issue by sevenkingdoms2** [nunit/nunit#1867]
Hi,

I got a project which used pnunit test for testing.  This is part of nunit binaries in 2.6.+.zip.  But I cannot find it in 3.+.  Does anyone know what happens to it?

Also, in the current 2.6.+ version, I notice a problem. Say two pnunit-agents are launched, and punit-launcher executes test.  One of the pnunit-agent gets tests and executes fine, but the other one get stuck at 
PNUnit.Agent.PNUnitTestRunner - Entering MakeTest.

Strange thing is, if the first instance of the punit-agent is killed, then the second punit-agent starts executing.  Has anyone seen this or better, known any workaround to this?

Thank you

Yang

**Comment by rprouse** [comment]
PUnit isn't an NUnit project, it is a separate project that uses NUnit and I don't think it has been updated in years. You will need to ask them for help, none of the NUnit team uses it.

https://www.plasticscm.com/documentation/technical-articles/pnunit-parallel-nunit.html

NUnit 3 can run tests in parallel, although not across machines. You may want to look at our docs, https://github.com/nunit/docs/wiki/Parallelizable-Attribute

**Comment by rprouse** [comment]
Sorry, my mistake, I read PUnit, but see you wrote PNUnit which was part of 2.6.x. It is not distributed as part of NUnit 3 which is a complete rewrite.

I am going to reopen this as a question for a short period to allow people to help you with the agents. This issue belongs in the v2 repository, but I will leave it here for now because more people will see it.

**Comment by CharliePoole** [comment]
PNUnit is developed by plasticscm and was distributed with NUnit. Our version under V2 was slightly changed from theirs to work with the latest 2.6.x version of NUnit.

I have written to the author to ask if they have tried to make it work with NUnit 3 and invited him to respond on this issue.

**Comment by rprouse** [comment]
This hasn't seen any further comments, so I am closing. Please reopen if anyone has comments or can help further.
