### ISSUE TITLE
EqualConstraint result failure message for DateTime doesn't show sufficient resolution

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1870]
As reported on PR #1868 the failure message does not show ticks, which may cause the two values to be displayed the same even though they are not equal. We should use 'F' rather than 'f' in the format string.

**Comment by Corniel** [comment]
I'm willing to fix this.

**Comment by CharliePoole** [comment]
Great. I invited you as a contributor, which will allow me to assign it to you.

I think we only need the change you already made to the MsgUtils in the other PR plus a test.

**Comment by Corniel** [comment]
I'll do that. Actually, I'll already did that in first request. I can do that again I guess. :)

**Comment by CharliePoole** [comment]
Yes... thanks for doing it again.

**Comment by Corniel** [comment]
You're welcome. :)
