### ISSUE TITLE
Build fails when targeting .net 4.0, profile=client

### ISSUE THREAD

**Issue by mogikanin** [nunit/nunit#1874]
I have an assembly foo.dll which is  .net 4.0, profile=client, and foo.tests.dll which has same target framework.
When I'm trying to build solution, there is a warning and build errors.
![nunit_clientprofile](https://cloud.githubusercontent.com/assets/840681/19836231/bbaf84d4-9eaa-11e6-96e4-790f55259791.png)

If set full .net4.0 for foo.tests.dll, then build works fine.

Does it mean that test assemblies no more support v4.0, profile=client?

**Comment by rprouse** [comment]
The .NET Framework is compiled using full .NET 4.0 support, so I would expect that your test assembly also has to be. You will get the same behavior running under the full framework, you will just get access to the more classes.

You asked, "Does it mean that test assemblies no more support v4.0, profile=client?".  I don't think it ever did.

I am going to leave this open for a bit to discuss. @nunit/core-team do you think it is worth targeting the client profile for .NET 4.0 if it is possible? Client profile was a short lived idea and I believe tests run the same under full profile, so my thinking is no, but some people may want to run on the target machine with client profile only. If that is the case, then the console runner would also need to be .NET 4, client profile, or they would need to use NUnitLite.

Thoughts?

**Comment by mogikanin** [comment]
Yes, I agree that for tests assemblies behaviour will be same. I just updated from nunit 2.x which works fine with client profile assemblies (though really never tested it on computer where only client profile installed), and the question is appear.

**Comment by ChrisMaddock** [comment]
We had the same issue upgrading from 2.x to 3, we just targeted full profile instead.

I don't know how much would need to be changed to provide client profile support. If its just another target, I don't see the harm. (Does xproj support it? We should make this decision with a view to when we have a single project with multiple targets.)

If this requires a number of changes, then Id say were best not. Its been unsupported since 3.0, and there's only been a couple of issues raised.

**Comment by rprouse** [comment]
I think we should close this as won't fix. Any objections?

**Comment by ChrisMaddock** [comment]
I agree. There's insufficient demand - and building from source is always an option.
