### ISSUE TITLE
AttributeUsage for various Attributes

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1880]
I have noticed that many the attributes do not have the AttributeUsageAttribute applies to them.

For instance, the RandomAttribute, which only applies to a parameter, is not constrained by an AttributeUsageAttribute with a AttributeTargets.Parameter flag set.

It seems like it should be.

I have not examined all of the attributes, but there may be others that are not constrained that should be.

**Comment by CharliePoole** [comment]
Indeed. We may fix some of these as we work in the code but at some point somebody should make them all explicit.

**Comment by oznetmaster** [comment]
The only attribute missing this appears to be the RandomAttribute
