### ISSUE TITLE
Support TestContext.Parameters.Get<xxx[]> ()

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1886]
I recently had occasion to want to pass an array of integers as a test parameter.

There is no problem doing so on the command line (--p:par1=1,2,3,4).

However, I then had to manually parse and convert that to an array of integers in the test.

Since Parameters.Get<> already knows how to do conversions to the requested type, it would be useful if that could be extended to allow Get<xxx[]>, which would return an array of the specified type.

**Comment by oznetmaster** [comment]
No thoughts on this?

**Comment by CharliePoole** [comment]
I don't see it as an extremely high priority. If you implemented it, would you limit it to arrays of those types we already support? How would you handle decimal representations in languages that use a comma to separate the decimal part?

**Comment by rprouse** [comment]
I also think this is fairly low priority and might even be inclined to decline the feature as it becomes a slippery slope of supporting more and more types. If I needed this sort of thing in my tests, I would likely just add a string extension method to my test project to split the string and return the array.

**Comment by oznetmaster** [comment]
I use the current culture to obtain the list separator character.  That solves the decimal problem.

Since I support all types that can be converted from string (see #1881), even custom user defined types are supported.

I have one test that takes a parameter containing an array of Point, for instance.

**Comment by rprouse** [comment]
@nunit/contributors do you think we should promote this from an idea to the backlog?

My vote is to close.

**Comment by CharliePoole** [comment]
I would close it.
