### ISSUE TITLE
Modify nunitlite to display multiple assert information

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1889]
Currently, the nunitlite runner uses the single failure message created for compatibility in order to display the result of a test using multiple asserts. It should use the actual result of each assert to display both the message and stack frame.

**Comment by rprouse** [comment]
Do we need to do the same in the adapter and dotnet-test-nunit?

**Comment by CharliePoole** [comment]
Yes. The code should be capable of porting pretty easily among nunitlite, the console and dotnet-test-nunit, while the adapter poses special challenges. I thought I'd use nunitlite to set a standard for what the text-based display should look like and deal with the adapter last.

**Comment by CharliePoole** [comment]
I created issues for dotnet-test-nunit and nunit3-vs-adapter.
