### ISSUE TITLE
Constraint Throws.Exception does not catch exception with async lambdas

### ISSUE THREAD

**Issue by KrzysFR** [nunit/nunit#1899]
After converting tests from NUnit 2.6.4 to 3.5.0, a few of them starting failing for no reason. After a quick diagnostic, all of them use the constraint `Throws.Exception` with an async lambda (don't care about the actual exception type, just checking that it fails on invalid input).

The behavior is that the test case fails by throwing the actual Exception, instead of catching it.

I have other places that use `Throws.Exception` with regular non-async lambda, and all of them work as intended.

Finally, I noticed that if I replace `Throws.Exception` with `Throws.Exception.TypeOf(...)` then the test pass properly with async lambdas.

Simple repro here:
```CSharp
namespace Tests
{
	using System;
	using System.Threading;
	using System.Threading.Tasks;
	using NUnit.Framework;

	[TestFixture]
	public class Test_Throw_Exception
	{

		[Test]
		public void Test_Blocking()
		{
			Assert.That(() => { Thread.Sleep(1000); throw new Exception("KAPOW"); }, Throws.Exception);
			// => PASS
		}

		[Test]
		public async Task Test_Async_1()
		{
			Assert.That(async () => { await Task.Delay(1000); throw new Exception("KAPOW"); }, Throws.Exception);
			// => will throw
		}

		[Test]
		public async Task Test_Async_2()
		{
			Assert.That(async () => { await Task.Delay(1000); throw new Exception("KAPOW"); }, Throws.Exception.TypeOf(typeof(Exception)));
			// => PASS
		}

	}
}
```

With NUnit 2.6.4, all three test cases pass.

With NUnit 3.5.0, tests `Test_Blocking` and `Test_Async_2` pass, but test `Test_Async_1` fails with the following output:
```
Test 'Tests.Test_Throw_Exception.Test_Async_1' failed: System.Exception : KAPOW
	Project\Test.cs(310,0): at Tests.Test_Throw_Exception.<>c.<<Test_Async_1>b__1_0>d.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at NUnit.Framework.Internal.ExceptionHelper.Rethrow(Exception exception)
	at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
	at NUnit.Framework.Constraints.Constraint.ApplyTo[TActual](ActualValueDelegate`1 del)
	at NUnit.Framework.Assert.That[TActual](ActualValueDelegate`1 del, IResolveConstraint expr, String message, Object[] args)
	at NUnit.Framework.Assert.That[TActual](ActualValueDelegate`1 del, IResolveConstraint expr)
	Project\Test.cs(310,0): at Tests.Test_Throw_Exception.<Test_Async_1>d__1.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at NUnit.Framework.Internal.ExceptionHelper.Rethrow(Exception exception)
	at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
	at NUnit.Framework.Internal.Commands.TestMethodCommand.RunAsyncTestMethod(TestExecutionContext context)

0 passed, 1 failed, 0 skipped, took 1,95 seconds (NUnit 3.5.0).
```

Tested with Resharper, TestDriven.net and NUnit.ConsoleRunner.3.5.0 package, under VS2015

**Comment by rprouse** [comment]
Thanks for the report and reprol. We will look into it.

I initially thought is that your lambda is `async void` and therefore we cannot await it properly, but that is not the case. I have confirmed your issue and tried several variations. As a workaround, change to `Throws.InstanceOf<Exception>()`.

I initially prioritized this as High, but I am going to lower that because we recommend that people don't use `Throws.Exception` on its own, https://github.com/nunit/docs/wiki/ThrowsConstraint

> Throws.Exception may be followed by further constraints, which are applied to the exception itself as shown in the last two examples above. It may also be used alone to verify that some exception has been thrown, without regard to type. This is not a recommended practice since you should normally know what exception you are expecting.

**Comment by KrzysFR** [comment]
> As a workaround, change to Throws.InstanceOf<Exception>().

That's what I did to fix my tests.

The real issue here would be for people converting from 2.6.4 or older,  that will probably spend a few minutes wondering why some tests fail all of the sudden. Hopefully they will find this issue and apply the workaround.

> "[..] This is not a recommended practice since you should normally know what exception you are expecting."

The words "not a recommended practice" can be interprented as "it works, but it's ugly" by some. Also, I confess that I did not read again ALL the documentation when migating from 2.x to 3.x, only the new parts :)

Maybe if you want to discourage using it, especially for async lambdas, you could specifically mention that it does not work, and maybe if it does sometimes, that's an implementation detail that could go away anytime (like it did in 3.5, intentionally or not) ? If this warning was in the XML comments, it would show up in intellisense right in Visual Studio.

Or, for the purpose of "I want to test that it fails, but I don't care how", you could introduce a dedicated constraint, something like `Does.Fail` ?

**Comment by KrzysFR** [comment]
While I'm at it, a quick question about async lambdas:

The two async tests in the repro above do show the compiler warning `This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.` because they don't have an await in their body (the only await is in the test delegate lambda).

Do you know if this can be handled more gracefully? Does `Assert.That(async () => { await ....; } ...)` really need to be in an async method itself, for it to work? or can I change both `Test_Async_x()` to be regular void methods if the only instances of `await` are inside test delegate lambdas? Would this work also with delegates that return a Task<T> that will be checked by `Is.EqualTo(..)` or equivalent?

i.e:

```CSharp
[Test]
public void Test_Async_Only_In_Lambdas()
{
    Assert.That(async () => { await Task.Delay(...); /* do something */ }, ...);
    Assert.That(async () => await someIterator.MoveNextAsync(), Is.True);
    Assert.That(async () => await someFile.ReadLineAsync(), Is.EqualTo("Hello"));
}
```

**Comment by rprouse** [comment]
We recommend not using `Throws.Exception` alone, but that is only a best practice and as you say, it should work with async. I lowered the priority only because it is hopefully not widely used.

As for your question about the warning on your async tests. You don't need `async Task` on your tests. `Assert.That` is not async and we handle executing your lambda within an async invocation region within the test framework. You only need to use the `async Task` if you are directly calling and awaiting async methods within your test.

**Comment by fredericDelaporte** [comment]
NHibernate 8000+ tests has some cases using bare `Throw.Exception` too. Going to search replace with the workaround.

**Comment by jnm2** [comment]
PR: https://github.com/nunit/nunit/pull/2547

**Comment by jnm2** [comment]
@rprouse Does it help you for me to throw tiny PRs like this in 3.9 for visibility, knowing you can pull them out if need be, or would you rather I didn't?

**Comment by rprouse** [comment]
@jnm2 I am fine with you adding PRs that are ready to review and include. If they don't make the cut, I will just move them out.
