### ISSUE TITLE
Do not add failed tests to Test Result XML

### ISSUE THREAD

**Issue by deepak--sharma** [nunit/nunit#1900]
Below is my call to Nunit3 tests in MSBUILD 
**_<NUnit3 ContinueOnError="WarnAndContinue"  Workers="1"  TextOutputFile ="E:\Logs\tests\TestResult.txt" OutputXmlFile="$(ProjectTestDir)\TestResults.xml;format=nunit2"
           Assemblies="@(TestAssemblies)"  Process="Single" ToolPath="$(NUnit3Dir)" Where="cat == Sequential"  />_**

As I'm using ContinueOnError="WarnAndContinue" feature, I want my build to progress even if some tests break, which is working fine. However, the issue I'm facing is the failed tests are added to TestResults.xml. 

So my requirement is Exclude the failed tests from TestResult.xml

**Comment by CharliePoole** [comment]
First off, NUnit has no knowledge of the script that calls it. So nothing in that script can affect how NUnit works unless the script also passes the info - perhaps as an argument - to NUnit.

More importantly, NUnit does not have an option to exclude failed tests from the XML file and we would not accept a request to do so. The test result file is intended to report what actually happened and showing that 100% of your tests passed when some actually failed would be incorrect.

It's fine to modify the actions your script takes as a result of the test failure, but a test failure is still a test failure.

**Comment by deepak--sharma** [comment]
Yes, makes sense now. But still I would want to delete failed tests nodes which I'll do it manually using xpath because I want error messages to be suppressed as I'm using WarnAndContinue, anyways thanks!

**Comment by CharliePoole** [comment]
Well, before you go to the trouble, are you  talking about the error messages that are displayed by the console runner? Is that what the msbuild task runs? I ask because those messages are produced before the file is ever created. IOW, make sure that whatever you are trying to suppress is actually affected by the content of the XML file.

Frankly, it may be simpler to change your tooling and run compile, test and whatever else as separate steps in a script.

**Comment by deepak--sharma** [comment]
Nope I'm not talking about console errors. Here is my story:- 

I'm running nunit 3 tests from a build step onTeamCity. There are a few flaky tests that break at times intermittently and they get successful when re-ran. So what we have done is used the ContinueOnError="WarnAndContinue" in Nunit 3 task, this suppresses the 1st attempt failures and proceeds to run remaining tests. Now the failed tests in 1st attempt are tracked and re-ran again in the same build and this time they succeeds. All good except the 1st attempt failures get logged in TestResult.xml due to which TeamCity reports build failure even though the end result is SUCCESS.  So I'm writing a custom code to remove failed test nodes from TestResult.xml.

**Comment by CharliePoole** [comment]
And RetryAttribute won't work for you? If not, it could be because those tests should not be run in parallel. Things to try: 
 * [Parallelizable(ParallelScope.None)] on the fixture
 * --workers=0
 * [Retry(some number)] on the test 
 * Combinations of the above

**Comment by CharliePoole** [comment]
Bottom line, it seems to me in your best interest to actually solve the problem that requires you to rerun the test rather than ignoring the first failure.
