### ISSUE TITLE
Nunit3 runs all tests in Teamcity

### ISSUE THREAD

**Issue by gachu16** [nunit/nunit#1908]
I recently upgraded to Nunit3.21 from 2.6.4. Some of the tests are running successfully, 
When i try to debug a failing tests, it runs all the other tests before running the specific test, I wasnt seeing this behavior in the earlier versions.
Any help or input would be useful.

**Comment by NikolayPianikov** [comment]
@gachu16 try using `--where`, see for details https://github.com/nunit/docs/wiki/Test-Selection-Language

**Comment by rprouse** [comment]
I am closing this as a question. @gachu16 if you still have problems, ask in this issue, we will see your questions.
