### ISSUE TITLE
Run tests using the NUnit Console Runner

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#1924]
When we split the repositories, we switched the test runs from using the NUnit Console to using the NUnitLite runner. This works, but using the released version of the NUnit Console will provide a small measure of integration testing between the projects.

**Comment by CharliePoole** [comment]
I'm OK with either replacing or supplementing the targets that use nunitlite to test the framework, as you prefer. If you replace the targets, then I think the tests should go back to being a simple dll.
