### ISSUE TITLE
Nunit failure from teamcity & command line

### ISSUE THREAD

**Issue by mbogi** [nunit/nunit#1928]
Im getting below error when I don't provide the path of nunit, something like below.

[exec] Run Environment: NCOVER_USING_PROJECT[6471E3B9202D8311D439C110FAF65D996658CBDB]
[11:23:21][exec] Run Environment: NCOVER_BUILD_ID[17.1.0_CI_308]
[11:23:21][exec] Run Environment: COR_ENABLE_PROFILING[1]
[11:23:21][exec] Run Environment: COR_PROFILER[NCover.ProfilerLauncher]
[11:23:21][exec] Unable to start requested process: nunit3-console.exe
[11:23:22][exec] EXCEPTION: 2016-12-14T11:23:21 Error starting process:  --> System.ComponentModel.Win32Exception: The system cannot find the file specified
[11:23:22][exec]    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
[11:23:22][exec]    at ? .???.??(String[] ?  , ?  ?  )

Script used in nant that ran through team city.
**<exec
              program="ncover"
              basedir="C:\Program Files\NCover Code Central\"
              workingdir="${Workspace.Path}\UnitTesting\UnitTests"
              commandline="run --project=&quot;&quot;UnitTests&quot;&quot; --build-id=${build.Version} -- nunit3-console.exe UnitTests.sln /out:TestResult.txt"
              failonerror="true" verbose="true">
    </exec>**

From command line above script works fine.

I have tried below approach to fix, but it fails with different error now.
**<exec
              program="ncover"
              basedir="C:\Program Files\NCover Code Central\"
              workingdir="${Workspace.Path}\UnitTesting\UnitTests"
              commandline="run --project=&quot;&quot;UnitTests&quot;&quot; --build-id=${build.Version} -- &quot;&quot;${Workspace.Path}\Tools\Nunit\nunit-console\nunit3-console.exe&quot;&quot; UnitTests.sln /out:TestResult.txt"
              failonerror="true" verbose="true">
    </exec>**

Error in command line
![image](https://cloud.githubusercontent.com/assets/24561300/21172216/a5262afa-c1f6-11e6-9fa4-feb599c6ac06.png)

     [exec]
     [exec] Time Elapsed 00:00:04.06
     [exec] Starting 'C:\Program Files\NCover Code Central\ncover (run --project=""UnitTests"" --build-id=17.1.0_CI_309 -- ""C:\TeamCity\buildAgent\work\GIT_Security\source\Tools\Nunit\nunit-console\nunit3-console.exe"" HostAnalytics.Pl
ln /out:TestResult.txt)' in 'C:\TeamCity\buildAgent\work\GIT_Security\source\UnitTesting\Tests\Tests'
     [exec] NCover v5.5.3543.583 x64 (Administrator)
     [exec] Copyright (c) 2007 - 2016 NCover LLC
     [exec] Starting: NCover Code Central on Microsoft Windows NT 6.1.7601 Service Pack 1
     [exec] Server Root: http://127.0.0.1:11235
     [exec] Run Environment: NCOVER_USING_PROJECT[6471E3B9202D8311D439C110FAF65D996658CBDB]
     [exec] Run Environment: NCOVER_BUILD_ID[17.1.0_CI_309]
     [exec] Run Environment: COR_ENABLE_PROFILING[1]
     [exec] Run Environment: COR_PROFILER[NCover.ProfilerLauncher]
     [exec] NUnit Console Runner 3.4.1
     [exec] Copyright (C) 2016 Charlie Poole
     [exec]
     [exec] Runtime Environment
     [exec]    OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
     [exec]   CLR Version: 4.0.30319.34209
     [exec]
     [exec] Test Files
     [exec]     HostAnalytics.Planning.Tests.sln
     [exec]
     [exec] System.Exception: Unable to acquire remote process agent
     [exec]    at NUnit.Engine.Runners.ProcessRunner.CreateAgentAndRunner()
     [exec]    at NUnit.Engine.Runners.ProcessRunner.LoadPackage()
     [exec]    at NUnit.Engine.Runners.AbstractTestRunner.Load()
     [exec]    at NUnit.Engine.Runners.MasterTestRunner.LoadPackage()
     [exec]    at NUnit.Engine.TestEngine.GetRunner(TestPackage package)
     [exec]    at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
     [exec]    at NUnit.ConsoleRunner.ConsoleRunner.Execute()
     [exec]    at NUnit.ConsoleRunner.Program.Main(String[] args)

Total time: 38.8 seconds.

**Comment by CharliePoole** [comment]
This is not an nunit framework problem but a problem with the console runner. I see you have found a relevant issue there and added your information, so I'm closing this one.
