### ISSUE TITLE
Nunit 3.5.0 on Visual Studio Mac with .NET Core 1.1

### ISSUE THREAD

**Issue by nambrose** [nunit/nunit#1930]
This may be a longshot but I wanted to run the above config
I create a project and edit the csproj to target .NET Core 1.1

Then I add the NUint 3.5.0 nuget package and can see in the screen that it supports DotNet core 

However the nuget log says this:
Which seems like it does not include .NET Core

Is this supported or not yet ?
I have 1.0 Preview 2 of the SDK tools. Do I need to get preview3 from github maybe ?

(Restore target) -> 
  /Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/xbuild/NuGet.targets : error : Package NUnit 3.5.0 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package NUnit 3.5.0 supports: [/Users/nicka/dotnet-test/xy/xy/xy/xy.csproj]
/Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/xbuild/NuGet.targets : error :   - dotnet (.NETPlatform,Version=v5.0) [/Users/nicka/dotnet-test/xy/xy/xy/xy.csproj]
/Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/xbuild/NuGet.targets : error :   - net20 (.NETFramework,Version=v2.0) [/Users/nicka/dotnet-test/xy/xy/xy/xy.csproj]
/Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/xbuild/NuGet.targets : error :   - net35 (.NETFramework,Version=v3.5) [/Users/nicka/dotnet-test/xy/xy/xy/xy.csproj]
/Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/xbuild/NuGet.targets : error :   - net40 (.NETFramework,Version=v4.0) [/Users/nicka/dotnet-test/
xy/xy/xy/xy.csproj]
/Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/xbuild/NuGet.targets : error :   - net45 (.NETFramework,Version=v4.5) [/Users/nicka/dotnet-test/xy/xy/xy/xy.csproj]
/Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/xbuild/NuGet.targets : error :   - portable-monoandroid10+monotouch10+net45+win8+wp8+wpa81+xamarinios10+xamarinmac (.NETPortable,Version=v0.0,Profile=net45+win8+wp8+wpa81+Xamarin.Mac+MonoAndroid10+MonoTouch10+Xamarin.iOS10) [/Users/nicka/dotnet-test/xy/xy/xy/xy.csproj]
  /Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/xbuild/NuGet.targets : error : One or more packages are incompatible with .NETCoreApp,Version=v1.1. [/Users/nicka/dotnet-test/xy/xy/xy/xy.csproj]

**Comment by rprouse** [comment]
We support .NET Core, not sure about running within VS for Mac, but the command line `dotnet test` works. You need to add `portable-net45+win8` to your imports statement in `project.json` to pull in the PCL version of the NUnit framework.

There are a few other steps you will need to do. See http://www.alteridem.net/2016/06/18/nunit-3-testing-net-core-rc2/ for more information.
