### ISSUE TITLE
NUnit Warn class should be removed from stack trace by filter

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1932]
The Warn class is in the same category as Assert and Assume. The standard filter should be updated to include it.

**Comment by mahasak** [comment]
Hi,
I want to help contribute to NUnit, Can i start by pick this one ?

**Comment by CharliePoole** [comment]
You're welcome to do a PR for it.

**Comment by CharliePoole** [comment]
Fixed in PR #2118
