### ISSUE TITLE
Should full c# style escaping be supported TestParameters?

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1936]
The discussion in #1885 has focused on the problems related to having semicolons in the value of a --params option.

In considering that issue, I had the realization that other characters requiring escaping should be allowed in the parameter value as well (such as control characters).

It therefore seems like the various front ends should allow full C# (or other model) character escaping in the value of the test parameter in addition to the semicolon (and the escape character, whatever it is).

**Comment by jnm2** [comment]
I would say yes except that we'd be buying into gotchas like this: https://github.com/AMVSoftware/Cake.SqlServer#gotchas

**Comment by jnm2** [comment]
Also: we'd be inconsistent because `\;` is an incalid C# escape sequence. I think our escaping and C#'s escaping need to stay well defined, far away from each other.

**Comment by CharliePoole** [comment]
My experience is that users typing a command line don't normally think of C# escaping rules and would most likely expect `\\` to remain `\\`. For users editing XML in a `.runsettings` file, there is even less expectation that things will be get escaped, except for the need to use things like `&gt;` in context. 

I think this is rather proving the point that expectations may differ based on the runner being used.

**Comment by oznetmaster** [comment]
Users typing a command line already have to deal with spaces (requiring double quotes), so the are in fact dealing with "escaping".  Also, they are used to using "" or ^" to escape the double quotes.  Escaping is everywhere, and it is totally inconsistent :(

That was why I suggested we pick one "standard" and use it.  Right now, there is no way to include a new line in the parameter, for instance.  `\n` would be nice to have.

**Comment by jnm2** [comment]
> `\n` would be nice to have.

And `c:\users\nsmith\source\repos\nunit\src\nunitframework\nunitlite\nunitlite-netstandard.csproj` would not be nice to have to deal with.

**Comment by jnm2** [comment]
> `\n` would be nice to have.

And `c:\users\nsmith\source\repos\nunit\src\nunitframework\nunitlite\nunitlite-netstandard.csproj` would not be nice to have to deal with escaping. That's 6. And they aren't all `\n`. Did you notice?

**Comment by oznetmaster** [comment]
I indicated that I did not care what the escape character was.  The windows command line uses ^ for instance.  Perhaps that would be a better choice, since it probably is not used as much in parameter values.

However, if full escaping is enabled, then the cost is escaping the escape character, whatever it is.

**Comment by jnm2** [comment]
>  The windows command line uses ^ for instance. 

Wouldn't that make it hard to use at the command line? You'd have to double-escape `^` etc.

**Comment by rprouse** [comment]
I am closing old Idea issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
