### ISSUE TITLE
Ability to access name of suite for which test case source is being executed

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#1939]
I have code like this all over the place:

```c#
public static IEnumerable<TestCaseData> AllThings(string suiteName)
{
    return
        from [...]
        select new TestCaseData(thingInfo1, thingInfo2)
            .SetName($"{suiteName}({thingInfo1.Name}, {thingInfo2.Name})");
}

[TestCaseSource(typeof(ThingTests), nameof(AllThings), new object[] { nameof(TestAspectOfThing) })]
public void TestAspectOfThing(Type thingInfo1, FieldInfo thingInfo2)
{
}
```

I would much rather write something like this:
```c#
public static IEnumerable<TestCaseData> AllThings()
{
    return
        from ...
        select new TestCaseData(thingInfo1, thingInfo2)
            .SetName($"{TestContext.CurrentContext.Test.Name}({thingInfo1.Name}, {thingInfo2.Name})");
}

[TestCaseSource(nameof(AllThings))]
public void TestAspectOfThing(Type thingInfo1, FieldInfo thingInfo2)
{
}
```

The problem is that `TestContext.CurrentContext.Test` is null at this time.
Is something like this possible?

A perhaps even better alternative, which I could also implement via extension method if I had  `TestContext.CurrentContext.Test.Name` or something similar:

```c#
public static IEnumerable<TestCaseData> AllThings()
{
    return
        from ...
        select new TestCaseData(thingInfo1, thingInfo2)
            .SetParameterNames(thingInfo1.Name, thingInfo2.Name);
}

[TestCaseSource(nameof(AllThings))]
public void TestAspectOfThing(Type thingInfo1, FieldInfo thingInfo2)
{
}
```

The overarching reason to do this that the default `.ToString()` parameter naming results in extremely long test names and I need the parameter names to be easily absorbed.

**Comment by jnm2** [comment]
Or, perhaps this is a better alternative in the same vein as DebuggerDisplay:

```c#
[ParameterDisplay("{0.Name}, {1.Name}")]
public static IEnumerable<TestCaseData> AllThings()
{
    return
        from ...
        select new TestCaseData(thingInfo1, thingInfo2);
}

[TestCaseSource(nameof(AllThings))]
public void TestAspectOfThing(Type thingInfo1, FieldInfo thingInfo2)
{
}
```

I don't like it quite as well.

**Comment by jnm2** [comment]
For completeness, this is another alternative:

```c#
[ParameterDisplay("{0.Name}, {1.Name}")]
public static IEnumerable<TestCaseData> AllThings()
{
    return
        from ...
        select new TestCaseData {
            { thingInfo1, thingInfo1.Name },
            { thingInfo2, thingInfo2.Name } };
}

[TestCaseSource(nameof(AllThings))]
public void TestAspectOfThing(Type thingInfo1, FieldInfo thingInfo2)
{
}
```

**Comment by CharliePoole** [comment]
Going back to your original example, I would just normally use `{M}` in the string to get the full class name but I don't know how that will play with C# string substitution.

**Comment by jnm2** [comment]
@CharliePoole That would be the best solution yet! `{` and `}` in C# string interpolation is just escaped as `{{` and `}}`.

Is this documented yet?

**Comment by CharliePoole** [comment]
@jnm2 The feature has been around since 3.4 but it's not documented. There is a specification page for it at https://github.com/nunit/docs/wiki/Generation-of-Test-Names-Spec

There's also a command-line option for the console to change the default pattern - `--test-name-format` - that's not documented either. :disappointed:

**Comment by jnm2** [comment]
Awesome! Looks like I want `{m}`.

**Comment by CharliePoole** [comment]
Yes, you're right there. SetName affects the test case name, not the suite. The suite gets added automatically when creating the full name.

**Comment by jnm2** [comment]
```c#
public static TestCaseData SetNameParameters(this TestCaseData testCaseData, params string[] parameterNames)
{
    return testCaseData.SetName($"{{m}}({string.Join(", ", parameterNames)})");
}
```

All I need now is a `TestNameGenerator.Escape` method to protect against parameter names happening to contain `{n}`, `{c}`, `{C}`, `{m}`, `{M}`, `{a}`, `{i}`, `{0}`, `{1}`, `{2}`, etc.

**Comment by jnm2** [comment]
```c#
public static TestCaseData SetNameParameters(this TestCaseData testCaseData, params string[] parameterNames)
{
    return testCaseData.SetName($"{{m}}({string.Join(", ", parameterNames)})");
}
```

All I need now is a `TestNameGenerator.Escape` method to protect against parameter names happening to contain `{n}`, `{c}`, `{C}`, `{m}`, `{M}`, `{a}`, `{i}`, `{0}`, `{1}`, `{2}`, etc.
