### ISSUE TITLE
Escaping test method name patterns

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#1943]
When you use TestCaseData.SetName, there are a number of substitutions made for such patterns as `{n}`, `{c}`, `{C}`, `{m}`, `{M}`, `{a}`, `{i}`, `{0}`, `{1}`, `{2}`, etc. [(docs)](https://github.com/nunit/docs/wiki/Generation-of-Test-Names-Spec_)

What I am often required to do in my test case sources, due to the length and unhelpfulness of the `.ToString()` rendering of some parameter types, is this: `.SetName($"{{m}}({param1.Name}, {param2.Name})")`

The unfortunate thing is that if any parameter happens to contain, say, `{c}` or `{1:20}`, it will be interpreted as a substitution rather than a literal.

In other scenarios similar to this one (command line parameters, regex, URLs, XML), we escape literal text to protect it. I'd like to be able to use `string TestNameGenerator.Escape(string literal)` in the same manner as I would if I was escaping anything else:

`.SetName($"{{m}}({TestNameGenerator.Escape(param1.Name)}, {TestNameGenerator.Escape(param2.Name)})")`

For the underlying escaping mechanism, I'd suggest escaping `{` as `{{` and `}` as `}}` because this has precedent in .NET format strings and C# interpolation. There are also more scenarios where it _won't_ have to be double-escaped than scenarios where it will.

With an eye to backwards compatibility, escaping is probably better to implement ahead of time rather  than when needed.

Willing to PR.

**Comment by CharliePoole** [comment]
Making this a discussion item as I _think_ we have some other issues that come at the problem of how to convert arguments to strings in different ways. I'll try to find those and list them.

**Comment by CharliePoole** [comment]
@jnm2 Well, changing this to Discussion had no effect at all! Feel free take this and PR if you want. Folks can comment on it then. :smile:

**Comment by stewart-r** [comment]
I was going to have a look at this one but, unless I am missing something (entirely possible!), there is no way to implement this as described in the initial post _without_ it being a breaking change.

For example, right now if I have: `.SetName("{{m}}")` then my test gets the display name '{{m}}', whereas if we introduce changes allowing us to  escape a '{' as '{{' then this would change my test's display name to '{m}'. 

The same principle applies no matter what the escape sequence is that we choose - If someone out there in the wild is already using the escape sequence in a test name then it would change the display name of their test and hence be a breaking change, no? We could, of course, minimise that risk by choosing a longer or really contrived escape sequence but surely that's starting to get messy.

A potential solution would be for the `TestCaseParameters` class to hold a flag to indicate we are using escape sequences which we could set with a new optional parameter to the `SetName()` method. This would mean we could change jnm2's example to something like:

    .SetName($"{{m}}({TestNameGenerator.Escape(param1.Name)},{TestNameGenerator.Escape(param2.Name)})", 
        useEscapedLiterals = true)

which would allow jnm2 to use the new proposed escaping and interpolation rules without breaking anything that may exist out there already.

Does that sound like a sensible approach?

**Comment by jnm2** [comment]
You are entirely correct that there is never a way to introduce escaping in a backwards compatible way. (We are having the same discussion about console test parameters with semicolons.)

The judgment call is, do we think anyone really will have been using `{{m}}`? If so, we will need to decide whether to break them (😓), and if not, the out-of-band approach like the one you demonstrate will be required. The more time goes by, the more likely people are using it in more interesting ways.

What if we add a `FormattableString` overload which automatically escapes interpolated values for you?
Less typing, more likely to be used than the Escape method.
(I had this idea that FormattableString could be used to parameterize SQL queries, and Entity Framework Core 2.0 is also now doing this, so there is precedent amd it seems to occur naturally to people.)

**Comment by jnm2** [comment]
Thw FormattableString idea will break anyone who had used string interpolation in conjunction with literal `{{m}}` (or if inside the interpolated part, `{{{{m}}}}`). But really, how likely is that?

Of course the danger with having the original string overload is that `SetName($"{{{{m}}}}({x})")` will escape `x` but `SetName($"{{{{m}}}}({x})" + "")` will not because it will switch to the string overload instead of causing a compile error. So scratch that unless it requires another parameter or uses a different method name.

**Comment by stewart-r** [comment]
Personally, I prefer the idea of being explicit that we are using interpolation & escape sequences, be that through a new optional parameter, an overload or a new method name though I absolutely accept the point of it being a pretty low risk of actually breaking someone doing something funky enough with their display names to fall foul of it.

Another idea:

If we went one step further we could add an overload that allows clients to pass in a 'strategy' for display name generation with the new string interpolation rules being just one implementation of a new `ITestNameGenerator` interface that can be passed to the `SetName()` method. 

If so, your call would change to something like:

    .SetName(new EscapedTextTestNameGenerator($"{{m}}({TestNameGenerator.Escape(param1.Name)},{TestNameGenerator.Escape(param2.Name)}))")

in order to achieve the same effect. and

Doing it this way would mean other users of the method would then also be free to implement `ITestNameGenerator` in whichever way they saw fit for whatever funky display name format they choose. They could then pass their own custom implementation in the same way:

    .SetName(new MyFunkyNameGenerator())

Thoughts? Is this overkill?

[P.S. I'm less than thrilled with the cumbersome name `EscapedTextTestNameGenerator` but hopefully it conveys the point well enough for the purpose of this discussion! :-) ]

**Comment by stewart-r** [comment]
If we went down the route of passing in a strategy maybe it's more natural to use another method rather than an overload to`SetName()`? Maybe something like `SetNameGenerationStrategy()` is a little more intuitive?

**Comment by jnm2** [comment]
I don't know the strategy is starting to seem pretty heavy for something where people will want to do minimal typing and have it just do the right thing.

A strike against FormattableString is that in this conversation, it was used wrong: `$"{{m}}`
I will invariably forget, catch it, and then update it to `$"{{{{m}}}}` and wish it didn't have to look so ridiculous.

**Comment by stewart-r** [comment]
Hmmm, but providing thier own implementation would be entirely optional. They can choose to just use the standard implementation provided by us. In the majority of cases where the 'right thing' for them happens to agree with the very sensible rules you are proposing they just use our implementation. In which case the additional typing isn't any worse than passing in an extra parameter? no?It's only if they want to do something peculiar or different that they might want to provide thier own implementation.On 6 Sep 2017 01:45, Joseph Musser <notifications@github.com> wrote:I don't know the strategy is starting to seem pretty heavy for something where people will want to do minimal typing and have it just do the right thing.
A strike against FormattableString is that in this conversation, it was used wrong: $"{{m}}
I will invariably forget, catch it, and then update it to $"{{{{m}}}} and wish it didn't have to look so ridiculous.

**Comment by CharliePoole** [comment]
Good brainstorming here, but it all seems to go beyond the purpose of `TestCaseData`. Maybe allowing changing name patterns at all was the initial step too far. :frowning_face: 

We've always tried to keep things that are commony used in tests separate from extensions to the framework. What's being discussed here is starting to sound like a new way to extend the framework, i.e. you can implement some class that will take over figuring out the names. If we want to do that, I'd like to see it as a separate thing.

**Comment by jnm2** [comment]
Let's square away what the purpose of `TestCaseData.SetName` is. I'd say, first and foremost it's to provide disambiguation in case multiple test cases end up with the same name by default. Secondly it's for aesthetics even bordering on documentation, as in:

 ```cs
new TestCaseData(false).SetName("{m}(without foo)")
new TestCaseData(true).SetName("{m}(with foo)")
```

But since the main advantage to `TestCaseData` is that it can be autogenerated, it's fully the responsibility of the generating method to convert the parameters to text uniquely and aesthetically via `SetName`.

The simplest and nicest thing going forward is (as always) to break people.
Today if someone does `{{m}}`, they get `{Test.Method.Name}`. After this change, they will get `{m}`. Is this likely and/or bearable as a break?

**Comment by jnm2** [comment]
Can I ask the @nunit/framework-team to comment on the potential break, especially Rob when you get a chance?

**Comment by CharliePoole** [comment]
@jnm2 To be clear, my comment was addressing the generalization of the approach, which you and @stewart-r  were discussing, not the specific break around `{{m}}`, etc.

Regarding the potential break, here's my two cents:

Having `{{m}}` change from `{SomeMethod}` to `{m}` is definitely a breaking change and likely to be confusing to users. The problem it "fixes" is very much a niche use case, in my view. So I would not break compatibility to make this work.

**Comment by jnm2** [comment]
Excuse me, I was incorrect. `{{m}}` currently stays `{{m}}` and it would change to `{m}`.

Just clarifying: not only is it a breaking change as we know, but 1. you think there is a good chance it would actually affect someone and 2. we don't consider that break acceptable. :+1:

> The problem it "fixes" is very much a niche use case

I don't think it's niche. Per my rationale above, only purpose of `SetName` is to allow you to disambiguate and aestheticize test cases that differ only in parameter values in a primarily _autogenerated_ context. That means taking each parameter into account and creating a string from it. If any parameter's string just happens to contain `{0}`, `{1}`, `{2}`, `{c}`, `{C}`, `{m}`, `{M}`, `{a}`, `{i}`, etc, you'll get substitutions that will be surprising and for which there are currently no recourse.

I'm next in favor of @stewart-r's original suggestion: a new overload with a `bool useEscaping` parameter.

**Comment by ChrisMaddock** [comment]
> I'm next in favor of @stewart-r's original suggestion: a new overload with a bool useEscaping parameter.

I'm struggling to see this issue to be wide-reaching enough to warrant an addition to the API.

@jnm2 - I think I'm following this, but this thread seems to be a bit of a moving target. Could you write up a quick summary of the issue, current state, and proposed solutions?

My main question right now: Why do you need to use a curly brace in your test name, as opposed to a square brace or something? Why do we want to further complicate this feature to involve escape characters, as opposed to just disallow using curly braces in test names?

**Comment by jnm2** [comment]
@ChrisMaddock I don't need a curly brace per se, but I'm not always control of what the parameter's textual representation is. I may be doing `parameter.SomeProperty.ToString()` on a third-party object. I ran into this organically at work– I'm trying to remember the context now 😳– but now that you bring it up I'm going to absolutely need one of these things:

 1. A `TestNameGenerator.Escape` method together with an escaping mechanism in `SetName`.
    This is more complex but allows full fidelity control over the resulting name.

 2. A `TestNameGenerator.Sanitize` method which replaces `{` with `[` and `}` with `]`, or something similar.
     This provides safety. No matter what expansions NUnit maintains now or in the future, I know that the resulting string won't get an unexpected expansion in the middle. I lose the ability to actually put a literal `{m}` or `{1}` in the string.

Sounds like you and Charlie would be more favorable towards option 2. I'd say option 2 is the very least we can do.

**Comment by stewart-r** [comment]
When 2 very experienced contributors with a much deeper understanding of the code base in question both politely suggest a different approach then it's probably time to acquiesce and trust in their superior wisdom... but... the more I think about it, the more I prefer the `ITestNameGenerator` approach.  Indulge me with one last attempt to try to make my case before I submit to your superior experience? :-)

My preference is predicated on the decision that we don't make this a breaking change (which seems to be the way the discussion is going). I entirely agree with jnm2 that the 'nicest' solution is to break people but if we accept that it's not worth introducing a breaking change for such a niche use case then, as I see it, we have broadly 3 options:

(I have used ridiculous names here only to highlight the point)

**Option 1 - introduce an optional 'flag' parameter to indicate we are using the new rules**

`.SetName("{{m}}", useNewEscapingRules = true)`

**Option 2 - introduce a new method to indicate we are using the new rules**

`.SetNameUsingNewEscapingRules("{{m}}")`

**Option 3 - introduce some kind of "wrapper" object for the name pattern and a new overload to `SetName`**

`.SetName(new NewEscapingRulesNameGenerationStrategy("{{m}}"))`

Thinking only from the perspective of the use case jnm2 originally described, of the three options I probably dislike option 2 and cannot split Option 1 or Option 3. Both are only very slight amendments to the API and read pretty similarly from the point of view of the calling code, 

From the point of view of the implementation, testability, customisability, etc. I think option 3 wins hands down. We have a defined interface which we can implement to do exactly this:

> That means taking each parameter into account and creating a string from it

We's then provide an out-of-the-box implementation for the new proposed escaping rules. There is already an out-of-the-box implementation for the existing name generation logic (which would remain as the default) but devs using the library could _optionally_ implement `ITestNameGenerator` in some custom way themselves if neither of these implementations suit thier needs. (Or we could in a future commit without having to change the API if someone comes along with another use case that doesnt fit with either of the current implementations).

@ChrisMaddock As I understand it the issue isn't so much about wanting to use curly braces in a test's display name - it's more about the scenario where the parameters you are using to auto-generate a test's display name happen to contain a curly brace. This scenario feels pretty likely as many 'edge cases' devs want to test centre around curly braces for similar reasons to the bruhah we are wading through here...

**Comment by CharliePoole** [comment]
@stewart-r 
The template formats used internally by NUnit to generate test names were exposed in `.SetName` some time back. That was my decision and I believe it was a mistake. 

The issue we were trying to resolve at the time was that of truncating string arguments. We wanted to give users a way to specify that arguments should either not be truncated or truncated to a different length than our default of 40 characters. I exposed the entire internal mechanism because I could imagine more requests for various settings - like add a guid to the name, use different lengths for different args, etc. In so doing the internal workings of NUnit became visible in a way that's rather ugly. I wouldn't do it that way today.

At the same time, the mechanism made no allowance for substitution strings, which either didn't exist at the time or at least weren't on my radar. (They really still aren't - I think they look too much like Perl or php to belong in a C# program. :smile:)

Your issue is clearly a real problem to you. It only arises, however, from the desire to use substitution in the string, without any awareness of the content of the value being substituted. That would have worked in the old `.SetName` (before use of templates). It obviously doesn't work now. Basically, the feature was created with the idea that you would be using constant valued strings and would therefore have full control over them.

What if we removed the ability to use templates completely, reverting to the original purpose of `SetName`? We could do that by use of an optional argument to `SetName` or a different property entirely. So long as you don't want to use the template approach at all, that would appear to solve the immediate problem. Since `.SetName` already exposes the template (unfortunately) we'd have to keep that working the same way. My preference would be for an overload like

```C#
.SetName(string name, bool asis = false)
```

This doesn't break anyone because it doesn't require escaping. It's downside is that you can't use a string that contains curly braces both with and without the intention of using the template.

I'd also introduce a new method `SetNameTemplate` with the plan of phasing out the use of templates in `SetName` down the road - quite a distance down the road. 😄

Would this work for you?

Your idea of a implementing ITestNameGenerator is a very good one. I just think it belongs in our extensibility mechanisms and not in the normal stuff used by test creators.

**Comment by jnm2** [comment]
@CharliePoole I like that even better than the two alternatives I thought of, so long as the test case source has access to the test name to maintain consistency and so it can be used by multiple test methods.

However, *not* wanting to provide the test name to the test case source was your reason for [pointing me to templating](https://github.com/nunit/nunit/issues/1939#issuecomment-269430949). (And apparently, the [reason this issue was needed](https://github.com/nunit/nunit/issues/1939#issuecomment-269566560).)

**Comment by CharliePoole** [comment]
@jnm2 That issue and comment from last year related to getting the name if the test **suite** rather than the test case.

It's also incorrect to talk about my "not wanting" to provide the test case name to TestCaseSource. It's simply not possible.

TestCaseSource is the source of the test case. No test case exists until it has been created by code in the attribute using the info returned from TestCaseSource. It produces tests so it can't consume them.

I'd it actually the method name you were hoping for? That's possible even though I think it's undesirable.

**Comment by jnm2** [comment]
Sorry for the lack of precision. I said ‘suite’ in that issue even though [what I really wanted was ‘method’](https://github.com/nunit/nunit/issues/1939#issuecomment-269484503).

You think it's undesirable to provide the `{m}`-equivalent (method name) to the test case source but that's the only way I expect anyone would be able to use the suggested `.SetName(..., asIs: true)`.

**Comment by ChrisMaddock** [comment]
@jnm2 @stewart-r Thanks for clarifying. To be clear - I wasn't proposing any particular view-point, just wanting to understand the issue properly! `ToString()` naming from 3rd party objects was a good example!

I'm not totally keen on adding any additional options to `.SetName()` or methods on TestCaseData, as I feel like this adds API/Intellisense noise for a niche case. I'd say that user's dynamically generating test case names, should be responsible for sanitising those themselves - although I can see there's currently no way to reliably do that.

> Your idea of a implementing ITestNameGenerator is a very good one. I just think it belongs in our extensibility mechanisms and not in the normal stuff used by test creators.

I do like this idea, however. NUnit could expose an ITestNameGenerator, and have a default implementation which contains all the template-expansion code. The user could then chose to override this, and implement a version with no/different template-expansion - or any other handling they wished. No breaking change, no API noise, and a specific extensibility point available to those who may need it.

> What if we removed the ability to use templates completely, reverting to the original purpose of SetName? 

FWIW, I use this a fair bit, and wouldn't want to see it go. It's helpful to explain my intentions, when the .ToString() of my test case arguments doesn't cut it. 

That's my thoughts - although I think I'll bow out of this issue now, as there's plenty of people more opinionated than I am on the matter. 🙂

**Comment by CharliePoole** [comment]
@jnm2 I think it's undesirable because it would allow/encourage use of one test case source returning different cases depending on the test. I don't think we want to do that __in TestCaseSource__.

`TestCaseSourceAttribute` is designed to return the same set of cases to every method.  We made it require `static` (except in one corner case) in part to signal that. We have accepted one or two issues that ask us to optimize its behavior by only executing the code once and caching the result for all the tests that use the same source. I'd like to see us do that.

What that means to me is that this feature - this __useful__ feature - you are asking for needs to be in a different data provider attribute from `TestCaseSource`. Of all the possible extensions to the framework, creating new data providers is one of the easiest to do. The attribute needs to implement an interface, but it can call on various helpers to do the job. That's how I would deal with some sort of a data source returning variable information depending on the test.

**Comment by CharliePoole** [comment]
@ChrisMaddock Exposing an interface like ITestNameGenerator and letting users implement it is exactly how all our other framework extensibility works. I'm all for that. I'm just not for doing it as a part of `TestCaseData`, which is a user-facing class in the `NUnit.Framework` namespace.

Regarding my comment about removing templating... I meant it only for those who choose to use the option. I think an option that ignores curly braces entirely, except as text, is much simpler and easier for users to understand than a more complicated escape mechanism. Most users, I suspect, never use the  template features at all. Still, it does no harm and is non-breaking to keep it as the default.

**Comment by stewart-r** [comment]
Thanks very much for the clarification on this issue and the history behind the `SetName()` method. There was certainly nuance here that I hadn't appreciated! 

I really like the idea of exposing that `ITestNameGenerator` interface although, having read though your explanations, I can now understand the reluctance for it to live in the same space as `TestCaseData` class.

Is the best way forward for me to open a new issue making the case for exposing such an interface and seeking a little guidance on how to best make the changes whilst keeping to the same structure as the existing extensibility bits (something I'm not so familiar with right now)? I'd love to have a go at a PR for this...

@jnm2 This would give you at least a _partial_ solution, too, yes? Albeit with a bit more friction than you'd envisaged. 

As an aside, having read this:

> Your issue is clearly a real problem to you.

I suspect have been overstating my case. Definitely much more towards the "minor quirk" end of the spectrum than "real problem" for me :-)

**Comment by ChrisMaddock** [comment]
> Exposing an interface like ITestNameGenerator and letting users implement it is exactly how all our other framework extensibility works. I'm all for that. I'm just not for doing it as a part of TestCaseData, which is a user-facing class in the NUnit.Framework namespace.

@CharliePoole - that was how it looked in my head, sorry I didn't make it clear!

**Comment by CharliePoole** [comment]
@stewart-r Would the option of turning off templating in the call to `.SetName` (i.e. `asis` argument) work for you at all?

**Comment by stewart-r** [comment]
@CharliePoole Yes, it would (sincere apologies for getting so sidetracked & ommiting to answer that question in my earlier comment!!) 

I have something a little like this (which I am pretty sure is the same problem @jnm2 has?):
```Csharp
    [TestFixture]
    public class WhenWorkingUpAStorm
    {
        public static IEnumerable<TestCaseData> TestCases()
        {
            var data = new List<Person>
            {
                new Person{Age = 100, Name = "Charlie"},
                new Person{Age = 37, Name = "Stewart"},
                new Person{Age = 101, Name = "Stewart {C} Robertson"}
            };

            return data.Select(p => new TestCaseData(p).SetName($"{{C}}.GivenPersonIsNamed{p.Name}"));
        }

        [Test]
        [TestCaseSource(nameof(TestCases))]
        public void CanDoSomethingVerifiable(Person p)
        {

        }
    }
```
Where the first 2 test cases are fine but the third one gets a funky name.

I could easily change it to something like this if the `asIs` flag existed:

```Csharp
   return data
                .Select(p => new TestCaseData(p)
                .SetName($"{nameof(WhenWorkingUpAStorm)}.{nameof(CanDoSomethingVerifiable)}.GivenPersonIsNamed{p.Name}"), 
                    asIs = true);
```

**Comment by stewart-r** [comment]
happy to try to implement the `asIs` flag and issue a PR in due course if this is the solution we are settling on?

**Comment by jnm2** [comment]
I've got almost the same scenario, since you ask, but I'm also using the test case source in four test methods so I'd have to send the test method name in via `[TestCaseSource(nameof(TestCases), new object[] { nameof(Test1) })]`.

**Comment by stewart-r** [comment]
Hmm - actually my real world case is in more than one method too! I can't believe I'd forgotten about that. Doh! 

Nonetheless, I accept CharliePoole's point that we really ought not to have testcases from a single `TestCaseSource` differing depending on the test method. 

In my own case, if the `asIs` suggestion was implemented, it'd be trivially easy for me to wrap the original data source in a new `TestCaseSource` per method without having any performance concerns whatsoever so I still consider this a solution. 

I've never really looked at the custom data providers CharliePoole mentions here:

> What that means to me is that this feature - this useful feature - you are asking for needs to be in a different data provider attribute from TestCaseSource. Of all the possible extensions to the framework, creating new data providers is one of the easiest to do. The attribute needs to implement an interface, but it can call on various helpers to do the job. That's how I would deal with some sort of a data source returning variable information depending on the test.

but get the point and can take it on trust that a straightforward enough solution could be found here if ever the situation arose where I did have a pressing need to use one data source for many methods.

**Comment by jnm2** [comment]
What do you all think about providing a `.SetParamNames(params object[])` method?
Whatever you pass in as arguments will be output as-is:

```cs
// x = new Person { Name = "Stewart {C} Robertson" }, y = 42
new TestCaseData(x, y, z).SetParamNames(x.Name, y)
```

Outputs:

`Namespace.FixtureName.MethodName(Stewart {C} Robertson, 42)`

I don't know of a way to implement this via extension method without access to NUnit internals but I believe it would capture just about all use cases.

**Comment by ChrisMaddock** [comment]
I've removed up-for-grabs as it doesn't look like we ever came up with a clear spec here. Please correct me if I'm wrong!

**Comment by jnm2** [comment]
@ChrisMaddock yeah, you're not wrong. However, I'm really curious what everyone thinks about my last proposal? Actually it should be `SetArgNames`, not `SetParamNames`:

```cs
// x = new Person { Name = "Stewart {C} Robertson" }, y = 42
new TestCaseData(x, y, z).SetArgNames(x.Name, y)
```

Outputs:

`Namespace.FixtureName.MethodName(Stewart {C} Robertson, 42)`

Does this capture everyone's use cases?

**Comment by CharliePoole** [comment]
I think we've kicked this around for too long. ☹️

**Comment by jnm2** [comment]
@CharliePoole Hey, it hasn't been a year yet! 😆 

@stewart-r Looks like you and I are the only people who happen to use `SetName` and use curlies at the same time. Does [`SetArgNames`](https://github.com/nunit/nunit/issues/1943#issuecomment-335970889) look interesting to you?

**Comment by stewart-r** [comment]
@jnm2 It would certainly give me a solution, I'm just not sure I have a need for the extra params in my method name so (for my own particular scenario) it doesn't give me anything beyond Charlie's `asIs` suggestion and would come at the expense of being just a fraction less intuative IMO.

I'd be perfectly happy with either proposal though.

>  Looks like you and I are the only people who happen to use SetName and use curlies at the same time.

Maybe I am guilty of seeing the world through the prism of my own recent experience but I have to say am **really** surprised that it doesn't seem to affect more people. People test edge cases, any strings with curly braces are edge cases for string manipulation code.... where is the tsunami!?? :-p

**Comment by jnm2** [comment]
@stewart-r Just to reiterate, `asIs` doesn't help me because I don't have access to the test method name from inside the test case source so I need the `{m}` part which `asIs` won't help with.

Since my proposal sounds equally good to you, and it seems to be the only thing so far that covers both our use cases, I'll start a new issue to clear the waters here and cc you.

> Maybe I am guilty of seeing the world through the prism of my own recent experience but I have to say am **really** surprised that it doesn't seem to affect more people. People test edge cases, any strings with curly braces are edge cases for string manipulation code.... where is the tsunami!?? :-p

Me too, honestly.

The thing that makes me uncomfortable here is that NUnit forces use to use SetName because otherwise the autogenerated test names collide, which in turn forces us to replace curlies with some other character. Feature holes are fine unless the feature is forced on you.

**Comment by jnm2** [comment]
Closing in favor of https://github.com/nunit/nunit/issues/2536.
