### ISSUE TITLE
Removing Compact Framework workarounds

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#1944]
Browsing through the code, I noticed some references to compromises made in order to support CF, or documentation of CF quirks:

- [x] <s>[/src/NUnitFramework/framework/Constraints/NUnitEqualityComparer.cs#L260](https://github.com/nunit/nunit/blob/d01935d8620f8f125bd1a77f89cb1fc8fd370910/src/NUnitFramework/framework/Constraints/NUnitEqualityComparer.cs#L260)</s>

   > [@CharliePoole] Just a comment - somebody wanted to use methods that are not in CF - note that "original" in this context doesn't mean original NUnit code, just that person's original idea of how to code. No change except maybe the useless comment.

- [x] [/src/NUnitFramework/framework/Interfaces/ITestResult.cs#L95](https://github.com/nunit/nunit/blob/d01935d8620f8f125bd1a77f89cb1fc8fd370910/src/NUnitFramework/framework/Interfaces/ITestResult.cs#L95)

   > [@CharliePoole] Useless comment - we haven't supported CF 1.0 for MANY years.

- [x] <s>[/src/NUnitFramework/framework/Internal/Reflect.cs#L162](https://github.com/nunit/nunit/blob/d01935d8620f8f125bd1a77f89cb1fc8fd370910/src/NUnitFramework/framework/Internal/Reflect.cs#L162)</s>

   > [@CharliePoole] Another comment. This one could be acted on by changing the code when somebody is actually working in the file.

- [ ] <s>[/src/NUnitFramework/framework/Internal/StackFilter.cs#L96](https://github.com/nunit/nunit/blob/d01935d8620f8f125bd1a77f89cb1fc8fd370910/src/NUnitFramework/framework/Internal/StackFilter.cs#L96)</s>

   > [@CharliePoole] I think the comment may be wrong and that other platforms may need that code. It was probably true when written.

- [x] <s>[/src/NUnitFramework/framework/Internal/TestNameGenerator.cs#L165](https://github.com/nunit/nunit/blob/d01935d8620f8f125bd1a77f89cb1fc8fd370910/src/NUnitFramework/framework/Internal/TestNameGenerator.cs#L165)</s>

   > [@CharliePoole] This would be a reasonable change if we know all platforms support TryParse. No sense changing when we aren't working in the file though.

- [ ] <s>[/src/NUnitFramework/tests/Internal/StackFilterTests.cs#L52](https://github.com/nunit/nunit/blob/d01935d8620f8f125bd1a77f89cb1fc8fd370910/src/NUnitFramework/tests/Internal/StackFilterTests.cs#L52)</s>

   > [@CharliePoole] Comment is obsolete but the test remains valid in case we do get deeper stack traces. This stack trace behavior seems to change with different releases of the framework.

- [x] [/src/NUnitFramework/nunitlite/CommandLineOptions.cs#L128](https://github.com/nunit/nunit/blob/d01935d8620f8f125bd1a77f89cb1fc8fd370910/src/NUnitFramework/nunitlite/CommandLineOptions.cs#L128)

   > [@CharliePoole] The NETCF code should be removed, since we removed it in most other places.

- [x] <s>[/src/NUnitFramework/nunitlite/CommandLineOptions.cs#L324](https://github.com/nunit/nunit/blob/d01935d8620f8f125bd1a77f89cb1fc8fd370910/src/NUnitFramework/nunitlite/CommandLineOptions.cs#L324)</s>

   > [@CharliePoole] As earlier, I'd use TryParse when I next work work in this file

- [x] [/src/NUnitFramework/nunitlite/DebugWriter.cs#L31](https://github.com/nunit/nunit/blob/d01935d8620f8f125bd1a77f89cb1fc8fd370910/src/NUnitFramework/nunitlite/DebugWriter.cs#L31)

   > [@CharliePoole] The class should probably be removed at some point as we don't use it.

- [x] [/src/NUnitFramework/nunitlite/TextUI.cs#L138](https://github.com/nunit/nunit/blob/d01935d8620f8f125bd1a77f89cb1fc8fd370910/src/NUnitFramework/nunitlite/TextUI.cs#L138)

   > [@CharliePoole] This impacts users so should get an issue and be fixed.

If I understand correctly, this repo will never support CF again. In that case some cleanup might be desirable. Willing to help with this.

**Comment by CharliePoole** [comment]
Most of these are rather unimportant because we already removed the conditional code for CF. Some of them are just one programmer commenting that he would have done it differently without CF.

I'll go through the list and edit in comments for each, then we can see what it adds up to.

**Comment by CharliePoole** [comment]
See above comments. I only see two items that need direct fixing...

* The conditional code in CommandLineOptions = PR only
* The erroneous help message in TextUI = New Issue

When we fix a minor error like the first, we will do a PR without an issue associated. It's just cleanup and doesn't get reflected in any release notes.

All the other items are worth fixing when working in that code, but I wouldn't do a separate programming / review effort. Where the comments suggest a stylistic change to the code rather than a real improvement, I'd just ignore them. The next person working may change the style back.

**Comment by jnm2** [comment]
One other one bothered me. What about swallowing exceptions rather than using TryParse?

**Comment by jnm2** [comment]
Oh, you answered inline in my post. Somehow missed that!

**Comment by jnm2** [comment]
Opened issues and PRs for everything. I'm not going to touch the stack filter stuff or explanation comments.
