### ISSUE TITLE
CompositeWorkItem reports all skipped tests as 'OneTimeSetUp: '

### ISSUE THREAD

**Issue by Nysosis** [nunit/nunit#1946]
Tested against v3.5.0

Given the following set of test fixtures:

```csharp
	[TestFixture, Explicit]
	public class ExplicitTests {
		[Test]
		public void Test1() {
			Assert.Pass();
		}
	}

	[TestFixture, Explicit("Some reason")]
	public class ExplicitTestsWithReason {
		[Test]
		public void Test1() {
			Assert.Pass();
		}
	}

	[TestFixture]
	public class TestsWithExplicitOnlyTest {
		[Test, Explicit]
		public void Test1() {
			Assert.Pass();
		}
	}

	[TestFixture]
	public class TestsWithExplicitReasonOnlyTest {
		[Test, Explicit("Some reason")]
		public void Test1() {
			Assert.Pass();
		}
	}

	[TestFixture]
	public class TestsWithExplicitAndNonExplicitTests {
		[Test, Explicit("Some reason")]
		public void Test1() {
			Assert.Pass();
		}

		[Test]
		public void Test2() {
			Assert.Pass();
		}
	}
```

Running them gives the following output:

```bash

Tests not run

1) Explicit : NUnitTests.ExplicitTests.Test1
OneTimeSetUp:

2) Explicit : NUnitTests.ExplicitTestsWithReason.Test1
OneTimeSetUp: Some reason

3) Explicit : NUnitTests.TestsWithExplicitAndNonExplicitTests.Test1
Some reason

4) Explicit : NUnitTests.TestsWithExplicitOnlyTest.Test1

5) Explicit : NUnitTests.TestsWithExplicitReasonOnlyTest.Test1
Some reason
```

Note that some (but not all, presumably due to them being handled by something different?) of them are saying `OneTimeSetUp` for the given reason, when I've not used the attribute at all.

Culprit seems to be [https://github.com/nunit/nunit/blob/4e2dc9d1acf30040a74e7152f11cb4d0ab5f2da1/src/NUnitFramework/framework/Internal/Execution/CompositeWorkItem.cs#L317](CompositeWorkItem.cs#L317) where it's been hard coded in. To me it seems like it should just render the value of `resultState` as the prefix

**Comment by CharliePoole** [comment]
The label means that the test was skipped due to something that happened in the one time setup phase of execution. In this case, because the Fixture was seen to be explicit.

One time setup for a fixture includes creating the fixture instance, running any OneTimeSetUp method and running any Before methods on fixture-level action attributes.
