### ISSUE TITLE
VS tests gets passed when running in Visual Studio 2015 Community Version but when running the same code through Nunit3 Console runner Test cases gets pass and fail.

### ISSUE THREAD

**Issue by Ganeshankarthik** [nunit/nunit#1949]
Hi everyone,
Apologies for the lengthy post.

I have created VS tests in visual studio 2015 community version. When i run the test cases my test cases gets passed constantly.

I want to run my VS tests without visual studio software in remote machine, so I created the bat file with pointing nunit3 console.exe followed by my dll file. But the tests gets pass for first time and gets failed for third , fourth time , and fifth time it gets passed. The result is not constant. 

I would like to know where the problem is ? Can anyone suggest me please.

**Comment by CharliePoole** [comment]
@Ganeshankarthik Not really so lengthy. :smile: 

How are you running the tests in VS 2015 when they pass if you are not using the adapter? What software do you use to run them?

Your title says the problem occurs using the NUnit3 Test Adapter but the text says it happens using nunit3-console.exe. These are entirely different things.

We need to know:
* What version of the nunit framework is referenced by your tests
* Exactly how do you run them when they pass? Include versions.
* Exactly how do you run them when they fail intermittently? Include versions.
* Do you get errors (exceptions) or just test failures?

**Comment by Ganeshankarthik** [comment]
Hi Charlie,

Sorry for the typo in the title.

1. I am using Nunit test adapter 3.6.1.0 in visual studio to execute the VS tests. 

![nunit vs tests](https://cloud.githubusercontent.com/assets/24904232/21633944/60ab71d0-d279-11e6-9b49-012a75b7d64e.png)

2. What version of the Nunit framework is referenced by your tests - **Nunit 3.5.0**
3. Exactly how do you run them when they pass? Include versions – **I will run the tests using Visual Studio 2015 with Nunit Adapter 3.6.1.0. But in my remote machine I am running the tests using Nunit Console Runner. 3.5.0.**
4. Exactly how do you run them when they fail intermittently? Include versions – **We used to provide some wait statements and run again with the Nunit Console Runner with the updated .dll file.**
5. Do you get errors (exceptions) or just test failures? – **No exceptions only test failures.**

I would like to elaborate my issue.

•	Tests are created in VS 2015 and when I execute in Visual Studio it works fine.
•	Actual query is that I need to execute the same tests in my remote machine without installing Visual Studio .So I created the .bat file with pointing the nunit3-console.exe along with the Project.dll file. Please find my code snippet below.
:1
"%~dp0\NUnit.ConsoleRunner.3.5.0\tools\nunit3-console.exe" "%~dp0\MMH Automation.dll" --where "cat=User Login"
GOTO TextPath
:2
"%~dp0\NUnit.ConsoleRunner.3.5.0\tools\nunit3-console.exe" "%~dp0\MMH Automation.dll" --where "cat=ClinicalProvider_AppointmentTemplate"
GOTO TextPath

•	When I execute the tests in my remote machine, the tests gets passed for 1st and if I run again it will get failed at 2nd time and will get pass at 3rd time. But when i execute in Visual Studio test scenario is passing but when i try to execute the same in the remote machine using Nunit console runner i am getting failed.

• Remote machine has the same CLR version 4.0.30319.42000 and .NET framework - 4.5.2 

•	There is no constant in the execution results. I am bothered that what mistakes i have done or any new idea please suggest. 

Really thanks for your help.

Thanks,
Ganeshan

**Comment by Ganeshankarthik** [comment]
Can anyone help me I am facing more sync issues so that my test results is not stable in remote machine

**Comment by rprouse** [comment]
> We used to provide some wait statements and run again with the Nunit Console Runner with the updated .dll file.

Can you explain this statement? I am not sure what you mean by providing wait statements. As in `.Wait()` on and `async` method?

If your tests are passing on the 1st run, then failing 2nd run, then passing again on the 3rd run, my guess is that your test code is holding locks on some resource that are not getting cleaned up properly. You may also have background threads that cause the test process to continue until they are cleaned up. Try running the tests from the console with Task Manager open. After the tests finish and report, do you see any `nunit-agent.exe` processes still running? If so, do they shut down eventually.

**Comment by Lechus** [comment]
Nunit 3.6.1
Similar issue here. Visual Studio 2015 U3 with ReSharper. All test passed.
Using Console runner - one test failed - where Moq for mocking injected dependency is used.
