### ISSUE TITLE
async teardown called early?

### ISSUE THREAD

**Issue by tofutim** [nunit/nunit#1953]
Hi, I have a bunch of async tests. Most of these run well but every once in awhile, esp. when first tested, some of the tests do not complete correctly. When I run them again it usually works. It looks like "Teardown" is being run maybe about 200 ms after the async test runs, which usually gives enough time but sometimes doesn't. Is async testing actually not supported? Have I been fooling myself all this time? 📦 

My expectation is that
```
[Test]
public async Task ATest() {
   .. bunch of stuff
  ... sometimes Teardown happens here!
  .. more bunch of stuff
}

[TearDown]
public void Teardown() {
  .. Debug.WriteLine("here I am tearing down")
}
```

I also tried using an async Teardown but it didn't help.

**Comment by CharliePoole** [comment]
TearDown shouldn't run till after the test completes. Can you provide a test case that demonstrates the problem? It's likely to vary based on the "stuff". Watch for any sync calls without an await.

**Comment by tofutim** [comment]
Teardown gets called before an Assert, so I don't think it is a sync call.
I have

```
await ...
Assert
```
and the Teardown happens between await and Assert. I'll try to make a test
case.

**Comment by tofutim** [comment]
Thank you Charlie for your quick response.

**Comment by CharliePoole** [comment]
It wasn't, by any chance, an async Assert, was it?

**Comment by rojaadi** [comment]
Hello ,

I am also facing same issue, but for me it is sporadic different time different tests are getting failed.
my code base has await asynchronous calls , and I cant change my code base .
can you help me in resolving the issue .
in test scenario they have used dispatcher.yield for asynchronous calls to get completed

**Comment by rojaadi** [comment]
> It wasn't, by any chance, an async Assert, was it?

Hello ,

I am also facing same issue, but for me it is sporadic different time different tests are getting failed.
my code base has await asynchronous calls , and I cant change my code base .
can you help me in resolving the issue .
in test scenario they have used dispatcher.yield for asynchronous calls to get completed
