### ISSUE TITLE
Change Error Message for Assert.Equals

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#1954]
Based on the number of votes on this StackOverflow question, http://stackoverflow.com/questions/11584429/nunits-assert-equals-throws-exception-assert-equals-should-not-be-used-for-ass, many users find the message in our `Assert.Equals` override to be confusing. It currently says "Assert.Equals should not be used for Assertions", we should change it to be "Assert.Equals should not be used for Assertions, use Assert.AreEqual(...) instead".

**Comment by JustinRChou** [comment]
Should the summary and ReferenceEquals also be updated?

**Comment by CharliePoole** [comment]
@JustinRChou That makes sense
@rprouse Since we are unable to use EditorBrowsable in this context, I suggest that the intellisense should start with something like "DO NOT USE"!

**Comment by CharliePoole** [comment]
Whoops! 😄

**Comment by JustinRChou** [comment]
Also looks like following classes needs updating too.
```
Assume
CollectionAssert
DirectoryAssert
FileAssert
StringAssert
Warn
```
And subsequent test cases.

**Comment by CharliePoole** [comment]
@rprouse Can of worms? :smile: I think most of this can wait till after the release though.

**Comment by JustinRChou** [comment]
When is the next release? 
And I have updated as such before I start applying it to the rest.
```
        /// <summary>
        /// DO NOT USE! Use Assert.AreEqual(...) instead.
        /// The Equals method throws an InvalidOperationException. This is done 
        /// to make sure there is no mistake by calling this function.
        /// </summary>
        /// <param name="a"></param>
        /// <param name="b"></param>
        [EditorBrowsable(EditorBrowsableState.Never)]
        public static new bool Equals(object a, object b)
        {
            throw new InvalidOperationException("Assert.Equals should not be used for Assertions, use Assert.AreEqual(...) instead.");
        }
```

And should the EditorBrowsable attribute be applied to ReferenceEquals? I am not too familiar on how the attribute works.

**Comment by CharliePoole** [comment]
@JustinRChou In a few days.
I like what you have done as a comment. I would usually drop the param elements if not using them. Are you planning to do a PR?

After much experimentation, I believe we have found that EditorBrowsable is no help at all for these messages. Feel free to experiment further. 😄

**Comment by JustinRChou** [comment]
Sure.

Might not have to update the test cases since those use StartsWith.

**Comment by JustinRChou** [comment]
@nunit/core-team 
Created the PR.
And am I doing something wrong with my fork? I seem to have way more merge commits showing up.
Do I need to use the merge with the squash commit option?

**Comment by CharliePoole** [comment]
I commented on the PR. I'm a little confused about what you did. You only created the PR an hour ago, how did it end up having so many things merged into it? Did you create your branch from an updated master branch?

**Comment by JustinRChou** [comment]
That was what I am trying to figure out.

Before that, I was updating my fork with the new updates and I created another branch from that for the PR.

So I am guessing that I am doing something incredibly wrong in my fork.

**Comment by JustinRChou** [comment]
Rebased my fork and recreated the PR.
