### ISSUE TITLE
Compare DateTimeOffsets including the offset in the comparison

### ISSUE THREAD

**Issue by RichardReeves** [nunit/nunit#196]
This came from a bug in our code where someone had used "Convert.ToDateTime" when they should have used "DateTimeOffset.Parse"; but the unit test passed, indicating that there was no problem. Here is some code to replicate the issue.

			DateTime localDateTime = new DateTime(2014, 1, 30, 12, 34, 56);
			TimeSpan localTimeOffsetFromUtc = new TimeSpan(6, 15, 0);
			DateTimeOffset expected = new DateTimeOffset(localDateTime, localTimeOffsetFromUtc);

			string value = new XAttribute("x", expected).Value;
			DateTimeOffset actual = Convert.ToDateTime(value); // They should have used DateTimeOffset.Parse

			Assert.That(actual, Is.EqualTo(expected)); // Expect this to fail because (for example) the DateTime and Offset values are different (but this assertion passes!). For example, the next two asserts will fail.
			Assert.That(actual.DateTime, Is.EqualTo(expected.DateTime));
			Assert.That(actual.Offset, Is.EqualTo(expected.Offset));

**Comment by voloda** [comment]
@CharliePoole I would try this one...
