### ISSUE TITLE
TestContext.Progress.Write working on my machine but not colleagues'

### ISSUE THREAD

**Issue by SamJongenelen** [nunit/nunit#1961]
Heya,

I am currently using the _TestContext.Progress.Write()_ functionality, which works perfectly fine on my machine. 

However, my colleagues' test executing engine doesn't show the writes. 

Any clue as where to look? Our .runsettings etc. are fully the same

Both me and colleague are using VS2015, NUnit 3.x and Resharper 2016

**Comment by CharliePoole** [comment]
Do you both run tests in the same way? I don't personally know if Resharper handles immediate output (Progress and Error) from NUnit. The exact version of any NUnit software you are using (framework, adapter) would be very relevant here.

**Comment by SamJongenelen** [comment]
Ok ill close the bug -- I don't think it has anything to do with NUnit itself.
 
Visual Studio or Resharper did not log to Console.Out and updating to latest version of R# fixed it :1st_place_medal:
