### ISSUE TITLE
A Theory with no data passes

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1962]
As a result of changes made for issue #1933, an internal problem was made visible. A Theory, for which no data is supplied, will pass.

If a Theory has data but all of it is unsuitable (assumptions fail), then the Theory itself fails. It's somewhat inconsistent for a Theory without data to pass - it should fail as well.

The source of the problem is in how NUnit runs test suites with no test cases. In NUnit V2, such suites were not handled in a special way. Any one-time setup (TestFixtureSetUp) and teardown (TestFixtureTearDown) was run, whether there were tests or not. In NUnit 3, we decided to change this behavior and only run one-time setup and teardown if there are actually child tests to be run. This saves wasted cycles when the one-time setup performs a lot of work, which is more common these days with folks doing database and web testing using NUnit.

Unfortunately, we did not change how Theories examine the result of their individual cases and decide whether they should pass or faill. This was (and is still) done by a special command added to the one-time teardown for the parameterized test suite representing the theory. Since one-time teardown is not run when there are no tests (i.e. no data) the command is never run.

To fix this requires re-thinking how we want to handle the overall result of a suite. In the general case, this is done each time a test case result is added to the suite result. In the case of Theories, a special action is taken to override the default behavior of suites. We will probably want to handle this by creating a special result for Theories with it's own aggregation behavior.

Since this is part of the fundamental architecture of the framework, I'm assigning it to myself for now.

**Comment by agray** [comment]
Does this issue affect release 3.6?

**Comment by CharliePoole** [comment]
@agray Yes, that is the problem exists now and will continue to exist in 3.6, which is coming out early next week. Do you have a use case where this situation occurs?

**Comment by agray** [comment]
Hi Charlie,

No, just asking.  Release of Saucery3 v3.6 will follow that of NUnit 3.6.

Regards,

Andrew

**Comment by CharliePoole** [comment]
Glad to hear it - I was counting on this being a low-frequency occurence. :smile:

**Comment by CharliePoole** [comment]
There were two steps needed here:
1. Make a Theory with no data runnable - as opposed to a test wiith no data. We already did that.
2. Make that Theory fail - that's what this issue is about.

**Comment by CharliePoole** [comment]
Plus... of course others are also welcome to review!
