### ISSUE TITLE
Investigate removing SpecialValue

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#1963]
`SpecialValue.cs` has the comment:

    /// Null represents a null value, which cannot be 
    /// used as an argument to an attribute under .NET 1.x

We no longer support .NET 1.x, so we should check if there are any uncommented dependencies, and whether it can be removed. 

There's also a very similar `NUnitNullType` - perhaps these can be combined, if SpecialValue can't be removed.

**Comment by CharliePoole** [comment]
IIRC @rprouse added NUnitNullType for internal processing, whereas SpecialValue was originally intended for users to use.

**Comment by CharliePoole** [comment]
It looks to me as if this can be gotten rid of. It was intended for users to use as an argument to a TestCaseAttribute in .NET 1.x. There are references to eliminate, as well.
