### ISSUE TITLE
NUnitLite cannot find .dll file

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#1970]
@la-yumba commented on [Mon Jan 09 2017](https://github.com/nunit/nunitlite/issues/2)

## Environment:

- .NET Core 1.1
- SDK version: "1.0.0-preview2-1-003177"

project.json looks like:

```javascript
{
   "dependencies": {
      "NUnit": "3.5.0",
      "NUnitLite": "3.5.0",
      "System.Reflection.TypeExtensions": "4.3.0"
      // etc...
   },
   "frameworks": {
      "netcoreapp1.1": {
         "imports": [
            "dnxcore50"
         ]
      }
   },

   "buildOptions": {
      "emitEntryPoint": true,
      "preserveCompilationContext": true,
      "xmlDoc": false
   },
}
```

and Program.cs looks like:

```csharp
new AutoRun(typeof(Program).GetTypeInfo().Assembly)
   .Execute(args, new ExtendedTextWrapper(Console.Out), Console.In);
```

## Scenario

start the program to run the tests with `dotnet run`

## Expected

it runs the test

## Actual

```
NUnitLite 3.5.0 (Portable)
Copyright (C) 2016 Charlie Poole

Test Files
    C:\myPath\to\MyAssembly\bin\Debug\netcoreapp1.1\MyAssembly.dll

Could not load file or assembly 'test, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
```

Note:

- The .dll is there at the named path. 
- The same issue occurs on Windows and OSx

---

@rprouse commented on [Mon Jan 09 2017](https://github.com/nunit/nunitlite/issues/2#issuecomment-271458331)

NUnitLite has been merged into the main framework, so I am moving this issue there.

**Comment by la-yumba** [comment]
Thanks @rprouse

**Comment by rprouse** [comment]
Most of this code has been rewritten with the new .NET Core and .NET Standard bits, so I am going to close this. If this is happening with 3.7.1, we can reopen.
