### ISSUE TITLE
Switch CHANGES.txt to Markdown

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#1971]
Our `CHANGES.txt` is currently nearly in Markdown format except for the headings. When the changes are copied into releases or the release notes in the docs, they need to be modified to Markdown format. I propose that we just switch `CHANGES.txt` to `CHANGES.md` and format it accordingly.

I am putting this out there as an idea. If the @nunit/core-team likes the idea, we can create issues for the other repos that have CHANGES files.

**Comment by CharliePoole** [comment]
The changes for release notes are pretty minimal. I've always thought of the file as primarily for the purpose of distribution to users in our packages, where text seems to make more sense.

**Comment by ChrisMaddock** [comment]
I think markdown is readable enough as plain text - and anything which saves work is a bonus. I like the idea!

**Comment by smwentum** [comment]
can i try?

**Comment by ChrisMaddock** [comment]
Let's make a decision here, so we can handle @smwentum's pull request 😄 

@nunit/core-team @nunit/framework-team - any further opinions? @CharliePoole - how averse to the change are you?

As above, my personal thoughts are that the benefit of doing this would outweigh the negative.

**Comment by CharliePoole** [comment]
I really don't see this as a useful improvement for users. It's not a file that GitHub treats specially and we already have the release notes for those who view it online.

So the reason to do it is because we want to make our own lives easier. Fair enough. But why focus on making the __manual__ process we hope to replace easier?

Still, I'd be OK with it if we can remember to keep it legible as text by using only very simple markdown.

**Comment by rprouse** [comment]
I only propose that we add the # characters for the titles and change the extension to MD. I think the hash characters don't detract much from TXT readability. Users can also click on the `CHANGES.md` file in GitHub to see a formatted version.

Our target audience is also developers, many of which will have Markdown support enabled in Visual Studio.

**Comment by ChrisMaddock** [comment]
I think ideally we'd want to keep the current format - save changing everything/having mixed formats for older releases. That would look like this, raw:

```
###NUnit 3.6 - January 9, 2017

This release of the framework no longer includes builds for Compact Framework or for SilverLight, but adds a .NET Standard 1.6 build. If anyone still using Compact Framework or SilverLight and would like to continue development on those versions of the framework, please contact the NUnit team.

####Framework

 * .NET Standard 1.6 is now supported

####Issues Resolved

 * 406 Warning-level Assertions
...
```

**Comment by CharliePoole** [comment]
Fair enough... 

I didn't know that there was markdown support for VS. I'll have to try it.

**Comment by jnm2** [comment]
I think having a space after the hashes is slightly more readable as plain text:

```markdown
### NUnit 3.6 - January 9, 2017

This release of the framework no longer includes builds for Compact Framework or for SilverLight, but adds a .NET Standard 1.6 build. If anyone still using Compact Framework or SilverLight and would like to continue development on those versions of the framework, please contact the NUnit team.

#### Framework

 * .NET Standard 1.6 is now supported

#### Issues Resolved

 * 406 Warning-level Assertions
...
```

That is the big strength of markdown, is that it can be formatted but it's also just as easy to read in plain text. I write markdown in plain text files all the time.

**Comment by jnm2** [comment]
Btw, I just discovered that you can do this:

````
```markdown
#### This

 * Will be syntax highlighted
```
````

Produces:

```markdown
#### This

 * Will be syntax highlighted
```

**Comment by rprouse** [comment]
>I didn't know that there was markdown support for VS. I'll have to try it.

It requires an extension, but it is part of the web tools by Mads Kristensen and is one of the more popular extensions, https://marketplace.visualstudio.com/items?itemName=MadsKristensen.MarkdownEditor

Visual Studio Code also support Markdown out of the box. I tend to use it these days.

**Comment by ChrisMaddock** [comment]
I think we've made a decision here. I'll update the Pull Request.

**Comment by ChrisMaddock** [comment]
Here's a summary of what we think this should involve:

Here's what we think the best plan of action is:

1. Convert CHANGES.md to CHANGES.txt, and just keep a single file. The references should also be updated in the solution too.

2. Format the new CHANGES.md as the current formatting in the docs repo - this means 3rd level headers for the main headers, and 4th level for the sub headers. The result should follow this style:

```markdown
### NUnit 3.6 - January 9, 2017

This release of the framework no longer includes builds for Compact Framework or for SilverLight, but adds a .NET Standard 1.6 build. If anyone still using Compact Framework or SilverLight and would like to continue development on those versions of the framework, please contact the NUnit team.

#### Framework

 * .NET Standard 1.6 is now supported

#### Issues Resolved

 * 406 Warning-level Assertions
...
```

3. CHANGES.TXT is also referenced in our nuspec files, and build script - there are three references in the below files which will also need updating. 
https://github.com/nunit/nunit/blob/f35783fc5463d003a24619c82d9fbe55e6290eab/nuget/nunitlite/nunitlite.nuspec
https://github.com/nunit/nunit/blob/f35783fc5463d003a24619c82d9fbe55e6290eab/nuget/framework/nunit.nuspec
https://github.com/nunit/nunit/blob/f35783fc5463d003a24619c82d9fbe55e6290eab/build.cake

**Comment by smwentum** [comment]
sure but it might have to wait until tommorw

**Comment by ChrisMaddock** [comment]
No rush - will leave it with you. Thanks! 👍
