### ISSUE TITLE
$RANDOM_SEED$ is appearing in non-test project build output

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#1982]
This is messing up the installer generated by CI. Now I _can_ update my build script to find and exclude those files, but they should not be appearing at all because there are no test assemblies in those folders.

**Comment by CharliePoole** [comment]
What installer, for what project?

This file has nothing to do with NUnit but is created by the NUnit3 adapter. There is an adapter issue that renamed this file so you must be using the last adapter release to get that name. Anyway, the file will appear in the output directory for any nunit3 test assembly. It should not be created for other assemblies that don't share the same output directory. If it does, that's an adapter bug.

Do I need to move this or just close it?

**Comment by jnm2** [comment]
Oh, I didn't know this was an adapter thing. Can I turn it off? If the console runner doesn't need it, why do I want it?

> Do I need to move this or just close it?

Depends- is the fact that it's showing up in the build output of a non-test project a  bug?

**Comment by CharliePoole** [comment]
Erase it and figure out what you do that creates it. It should only be created by running the NUnit3 adapter on that project. Of course, if you have it installed as a vsix, it is run every time you open the project.

**Comment by CharliePoole** [comment]
Does the output directory contain any test projects, in addition to the non-test project?

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit3-vs-adapter #298](https://github.com/nunit/nunit3-vs-adapter/issues/298) via [**ZenHub**](https://www.zenhub.com/)
