### ISSUE TITLE
NUnitLite ignores --workers option

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1986]
I came across this working on #164. Changing the number of test workers with the command-line `--workers` option didn't have any effect on the duration of the test. On investigation, it's clear that although the option is accepted there is no code to transmit it to the framework as a setting.

**Comment by oznetmaster** [comment]
```
#if PARALLEL
		private int GetLevelOfParallelism ()
			{
			return Settings.ContainsKey (FrameworkPackageSettings.NumberOfTestWorkers)
				? (int)Settings[FrameworkPackageSettings.NumberOfTestWorkers]
					 : (LoadedTest.Properties.ContainsKey (PropertyNames.LevelOfParallelism)
						 ? (int)LoadedTest.Properties.Get (PropertyNames.LevelOfParallelism)
						 : NUnitTestAssemblyRunner.DefaultLevelOfParallelism);
			}
#endif
```

**Comment by oznetmaster** [comment]
Not sure why you think it is not used?

**Comment by CharliePoole** [comment]
Experimentally and because there's no code for it in NUnitLite. NUnit has code to properly handle the setting, if it's there - as you show above. NUnitLite accepts it as a command-line setting but never passes that setting to the framework.

**Comment by CharliePoole** [comment]
I didn't see your first example, only the second. The code you cite is pretty much what I had to add to TextRunner.cs to get it to work. It's not in the master.

**Comment by oznetmaster** [comment]
That code was in nunitlite for a long time. No idea when it was removed. I did not write it.

**Comment by oznetmaster** [comment]
As far as I can tell it was there when I started working on 3.0

**Comment by oznetmaster** [comment]
I have been using that command line option to test the cf build for a long time.

**Comment by CharliePoole** [comment]
This isn't actually helping.

**Comment by oznetmaster** [comment]
Neither of those pieces of code are samples. They we're copied from my cf source.

**Comment by oznetmaster** [comment]
It might be relevant to determine when and why they were removed. Might be other related issues as well?

**Comment by CharliePoole** [comment]
I've been back as far as the first alpha release of 3.0. There has never been code to make the option work. Of course, the default setting has always worked, absent the command-line override.

**Comment by oznetmaster** [comment]
It was added to my CF build on 3/21/2015 at 12:01 PM, according to my version control system.

That was the only change on that date.

That was about eight days after I started working on NUnit.

**Comment by CharliePoole** [comment]
Unfortunately, nobody ever added it to the master repository.
