### ISSUE TITLE
Retarget PCL build to .NET Standard

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#1989]
@rprouse mentioned somewhere during the 3.6 release that we may want to retarget the PCL build as a .NET Standard build. .NET standard is essentially the replacement for PCLs. I did a little experimentation - Visual Studio automates the retargetting to .NET Standard 1.0 quite happily, with no additional changes needed.

I wonder if we should consider targeting a higher .NET standard version, which would allow us to renable more functionality - I think the lowest platform we have runners for is UWP/netstandard 1.4? Of course, people could be using the PCL on other platforms via NUnitLite. I haven't investigated how much extra we would gain, by increasing a standard version or two. 

Thoughts? Rob - I'm very much stealing your idea and running with it here - you're welcome to have it back if you had other plans!

|.NET Platform              | 1.0| 1.1| 1.2| 1.3| 1.4| 1.5| 1.6| 2.0|
|:--------------------------|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|
|.NET Core                  |&rarr;|&rarr;|&rarr;|&rarr;|&rarr;|&rarr;|   1.0| vNext|
|.NET Framework             |&rarr;|  4.5 | 4.5.1|   4.6|&rarr;|&rarr;|&rarr;| 4.6.1|
|Mono                       |&rarr;|&rarr;|&rarr;|&rarr;|&rarr;|&rarr;|   4.6| vNext|
|Xamarin.iOS                |&rarr;|&rarr;|&rarr;|&rarr;|&rarr;|&rarr;|  10.0| vNext|
|Xamarin.Android            |&rarr;|&rarr;|&rarr;|&rarr;|&rarr;|&rarr;|   7.0| vNext|
|Universal Windows Platform |&rarr;|&rarr;|&rarr;|&rarr;|  10.0|&rarr;|&rarr;| vNext|
|Windows                    |&rarr;|   8.0|   8.1|      |      |      |      |      |
|Windows Phone              |&rarr;|&rarr;|   8.1|      |      |      |      |      |
|Windows Phone Silverlight  |   8.0|      |      |      |      |      |      |      |

**Comment by rprouse** [comment]
My plan was to add back as much functionality as possible in the netstandard16 version and convert the PCL to the lowest version possible to give it the widest support possible. That said I could easily be convinced to go to netstandard13 instead.

As for taking it off me, I don't have a problem there. We need to concentrate on adding netstandard support to the engine somehow and getting the VS adapter working with CSPROJ based .NET Core projects.

For converting the PCL project, my plan was to drop the PCL project and multi-target the netstandard project then do a mass find/replace of PORTABLE with the NETSTANDARD_1x. Were you thinking the same?

@nunit/core-team, we should have some discussion about this before we move forward.

For PCL support, Scott Hanselman recently stated,

> These are "lowest common denominator" libraries that allow code sharing across platforms. Although PCLs are supported, package authors should support netstandard instead. The .NET Platform Standard is an evolution of PCLs and represents binary portability across platforms.

This is also the message I have been hearing.

**Comment by ChrisMaddock** [comment]
I was just thinking of the straight conversion initially, but anything that cuts down the number of projects would be great! At some point, it will be possible to just have a single project, multi-targeting all the frameworks, won't it? Perhaps mixing the two netstandards first would be a good first step towards that. 😄

> We need to concentrate on adding netstandard support to the engine somehow and getting the VS adapter working with CSPROJ based .NET Core projects.

Absolutely - at some point post-release madness, will you write up a summary of where we're at with this, and what we need to look at? I'd be happy to help out with some of this over the next quarter.

**Comment by ChrisMaddock** [comment]
Duplicate of https://github.com/nunit/nunit/issues/2092
