### ISSUE TITLE
Add namespace filter

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1990]
As a pre-requisite to nunit/nunit-console#162, implement a namespace filter in the framework.

Modify the TSL implementation in nunitlite to handle namespace as a keyword.

**Comment by CharliePoole** [comment]
Closed via #1995 

@tom-dudley The exact comment phrase "Fixes #1990" would have been needed in the PR in order for ths to be closed automatically by GitHub.

**Comment by jnm2** [comment]
`Fixes` and `Closes` both work. I tend to say `fixes` for bugs and `closes` for features.
