### ISSUE TITLE
TestContext.CurrentContext.Test.Properties.Get("Category") only returns first category assigned to test

### ISSUE THREAD

**Issue by randersen** [nunit/nunit#1991]
First off I'm not sure if this is expected behavior so if it is please disregard.

Nunit Version 3.4.1 (from NuGet)

I'm running a test with the following attributes

`[Test, Parallelizable, Retry(3), Category("Catalog"), Category("Production")]`

and later in the test there is a safety check to make sure that tests running in the production environment have the Production Category assigned to it. This uses:

`var category = (string) TestContext.CurrentContext.Test.Properties.Get("Category");`

Calling CurrentContext to get the Category property as shown above only returns the first category in the test decorators (in this case "Catalog"), which makes it hard if you are doing any sort of category validation within the test in a setup block like i am.

**Comment by CharliePoole** [comment]
That's how IPropertyBag works. Here's the intellisense for `IPropertyBag.Get(...)`:

> Gets a single value for a key, using the first
> one if multiple _values are present and returning
> null if the value is not found.

The key info is __first one__. If you want the list of all values, use the indexer:

```C#
var category = (string) TestContext.CurrentContext.Test.Properties["Category"];
```

**Comment by jeremysimmons** [comment]
CS0030	Cannot convert type 'System.Collections.Generic.IEnumerable<object>' to 'string'

var s = (IEnumerable<string>)TestContext.CurrentContext.Test.Properties["Category"];

**Comment by CharliePoole** [comment]
See my earlier comment (updated). Properties is a dictionary whose values are LIsts.

**Comment by mikkelbu** [comment]
@CharliePoole 
I think the comment was that your example
```c#
var category = (string) TestContext.CurrentContext.Test.Properties["Category"];
```
does not comple "Cannot convert type 'System.Collections.Generic.IEnumerable<object>' to 'string'", and then gave a variant that compiles.

**Comment by jeremysimmons** [comment]
@CharliePoole - Agreed. Sorry, I had missed the last comment you made. 
I am sure you know all of this, and no implication was made that you require such education for such matters. The comment was merely for posterity on valid ways to use the API. I often find that I run across my own comments months or years later, and they are beneficial to future-me. Thanks for all your efforts over the years on NUnit. I've really enjoyed using it lately.

Your final example
> `IList categories = TestContext.CurrentContext.Test.Properties["Category"];`

also gives a compiler error
```
CS0266	Cannot implicitly convert type 'System.Collections.Generic.IEnumerable<object>' to 'System.Collections.IList'. An explicit conversion exists (are you missing a cast?)	
```

this, however, would be valid.
```csharp
IList categories = (IList)TestContext.CurrentContext.Test.Properties["Category"]; 
```

@mikkelbu , yes, you correctly interpreted my comment. I apologize for being overly terse. It was not my intention to necro this post.

**Comment by CharliePoole** [comment]
@mikkelbu @jeremysimmons Yup! I got that!

Fixed the updated error, due to compiling in my head while using my phone. :smile:

**Comment by jeremysimmons** [comment]
@CharliePoole , I'm not sure when they're going to add that as an official option... maybe we can get some up-votes on UserVoice.com?

![image](https://user-images.githubusercontent.com/1406886/45891663-5fc65900-bd83-11e8-8d48-abf87ec151e9.png)

**Comment by MattKeenum** [comment]
Sorry for bringing this post back, but unfortunately, this does not work for me when using a `TestCaseSource`. When I use this code:

>[Test]
>[Category("MyTest1")]
>[Category("MyTest2")]
>[TestCaseSource(typeof(MyDataProvider), "TestData")]
>public void MyTest() 
>{
>     IList cats = (IList)TestContext.CurrentContext.Test.Properties["Category"];
>}

The count of `cats` is always zero. If I don't use a `TestCaseSource`, then it shows both of the MyTest categories as expected.

Now, if I use a `TestCaseSource` and return the `TestCaseData` with the following example, it works, but not in the expected way:

>yield return new TestCaseData().SetCategory("MyExample1").SetCategory("MyExample2");

It shows both of the MyExample categories, but not the MyTest categories.


I will say that all of the categories appear in the `Test Explorer` as expected. Both the category attributes and the categories attached with `.SetCategory`.

It seems that if I use a TestCaseSource, it loses the ability to see any categories attached as an attribute to the test. Is there a way I can have it return all 4 categories?

I'm using NUnit v3.11.0 and NUnit3TestAdapter v3.12.0

**Comment by Shurik1497** [comment]
@MattKeenum I have the same issue.

**Comment by mikkelbu** [comment]
Currently, properties set on a parameterized method are not accessible from the TestContext in a test method. So even though it looks like you are placing the categories on the individual tests, the categories are actually placed on the surrounding parameterized method. My guess is that the test explorer has some logic to "hide this" which is why is looks differently there.

We have several outstanding issues on this subject, see e.g. #1358 or #548 for more information, but so far nobody has worked on this as far as I know.
