### ISSUE TITLE
Question: Is this possible to attach screenshot that will be visible in TFS Build Report

### ISSUE THREAD

**Issue by sisillV** [nunit/nunit#1993]
Hi All,
I run NUnit tests with TFS Build.
In the results when we click on specific test we see Attachment:
![image](https://cloud.githubusercontent.com/assets/8655116/22109337/0784fc28-de60-11e6-9dcd-ef612988f5ac.png)
Is this possible to attach screenshot using Nunit in the TFS Build Report?

Best Regards,
Stanislava

**Comment by ChrisMaddock** [comment]
Not yet, but there's an open feature request to add that functionality at https://github.com/nunit/nunit/issues/1670. 😄 

I'll close this issue as a duplicate.
