### ISSUE TITLE
Remove unused --verbose and --full command line options

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#1997]
@thomaslevesque commented on [Fri Oct 14 2016](https://github.com/nunit/nunit-console/issues/99)

What is the `--verbose` flag supposed to do? I can't see any difference between running nunit3-console.exe with or without this flag.

(btw, is there a way to print to the console which test is currently executing? that's what I was trying to do with `--verbose`)

---

@thomaslevesque commented on [Fri Oct 14 2016](https://github.com/nunit/nunit-console/issues/99#issuecomment-253811189)

I just looked at the code: apparently the `CommandLineOptions.Verbose` property is never used (except to define it in `ConfigureOptions`). The same is true of the `Full` property.

---

@ChrisMaddock commented on [Fri Oct 14 2016](https://github.com/nunit/nunit-console/issues/99#issuecomment-253821915)

I think you're looking for `--labels`? I'll leave someone else to comment on`--verbose`

---

@thomaslevesque commented on [Fri Oct 14 2016](https://github.com/nunit/nunit-console/issues/99#issuecomment-253828074)

Thanks @ChrisMaddock, this is what I was looking for!

---

@CharliePoole commented on [Fri Oct 14 2016](https://github.com/nunit/nunit-console/issues/99#issuecomment-253849981)

Once upon a time, `--verbose` did something. When I removed that code, I thought I would be coming back to add some different verbose output. We'll either kill the option or use it.

The `--full` option was an experimental report of all tests run. We'll either remove or use this one too.

---

@ChrisMaddock commented on [Fri Jan 20 2017](https://github.com/nunit/nunit-console/issues/99#issuecomment-274046250)

This is potentially easyfix once a decision is made. 

Can I suggest we remove both unused options, with the view that they could always be re-added, if something is implemented at a later date? @nunit/engine-team - thoughts?

---

@rprouse commented on [Fri Jan 20 2017](https://github.com/nunit/nunit-console/issues/99#issuecomment-274058775)

I say remove for now

---

@CharliePoole commented on [Fri Jan 20 2017](https://github.com/nunit/nunit-console/issues/99#issuecomment-274114222)

I agree

**Comment by ChrisMaddock** [comment]
These options also exist for NUnitLite, and should be removed here too.

**Comment by GCichosz** [comment]
Can I grab this issue?

**Comment by rprouse** [comment]
@GCichosz consider it yours 👍
