### ISSUE TITLE
Author Tests assume ICustomAttributeProvider.GetCustomAttributes return order is defined

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1999]
After some research, it appears that the order of the attributes returned by ICustomAttributeProvider.GetCustomAttributes is undefined (random).

However, it seems like the assumption is made in Nunit that custom attributes are always returned in the order they appear in the source code.

For example, the AuthorAttribute allows multiple occurrences of the attribute.  The tests for multiple AuthorAttribute assumes a specific order for the values in the resulting Author element in the test's Properties.  That test can fail because the order is actually not defined.

**Comment by oznetmaster** [comment]
This is why some attributes actually have an Order property, like some of those in Asp.Net.

**Comment by oznetmaster** [comment]
I have not examined all the other AllowMultiple attributes in NUnit to see if any of them have similar problems.

**Comment by CharliePoole** [comment]
There is no such assumption in NUnit. In fact, I've made many posts warning users of this and we even have some documentation about the unreliablility of order assumptions WRT data attributes.

However, it's entirely possible that some particular test is making that assumption. One moment...

...I'm back! You're right about the Author tests. The recently added tests for multiple authors use `Is.EqualTo` to compare arrays but should use `Is.EquivalentTo`

@JustinRChou you added these tests last week, would you like to take on this issue to fix them?

@oznetmaster If you see others, please continue to report them. Too bad you didn't review @JustinRChou's PR last week!

**Comment by JustinRChou** [comment]
The Author property seemed to be well behaved in terms of the stack order. But that order is enforced by the test properties. 

Never tried comparing it to customattributes.

**Comment by oznetmaster** [comment]
I only found this when I ported these changes to my CF build, and the Author test failed.

I had never specifically thought about the issue before, perhaps intuitively just not doing it :(

**Comment by oznetmaster** [comment]
In my case, TestMethodMultipleAuthors returned them in the order Rob Prouse, NUnit, Charlie Poole.

**Comment by CharliePoole** [comment]
@JustinRChou The order of the property values is the same as the order that the attributes were found. So they will be different when using different runtimes. We sometimes see differences between Mono and .NET and always between .NET and .NETCF. Because we no longer build CF, I guess it's now easier for a mistake to slip through. In fact, IIRC, I think I suggested you use Is.EqualTo in the first place! 😊

**Comment by oznetmaster** [comment]
Changing to Is.EquivalentTo fixes the tests

**Comment by JustinRChou** [comment]
@charliepoole I could modify the tests.

**Comment by oznetmaster** [comment]
If there is a desire to allow a specific ordering of authors, then an optional property Order could be added to the AuthorAttribute.

**Comment by CharliePoole** [comment]
@JustinRChou I assigned this to you.

@oznetmaster No reason to need ordering that I can see.

**Comment by JustinRChou** [comment]
[Test]
        public void ManyProperties()
        {
            Test test5 = (Test)fixture.Tests[4];
            Assert.AreEqual(6, test5.Properties.Keys.Count);
            Assert.AreEqual("A", test5.Properties.Get("A"));
            Assert.AreEqual("B", test5.Properties.Get("B"));
            Assert.AreEqual("C", test5.Properties.Get("C"));
            Assert.AreEqual("D", test5.Properties.Get("D"));
            Assert.AreEqual("E", test5.Properties.Get("E"));
            Assert.AreEqual("F", test5.Properties.Get("F"));
        }

I am looking at some of the other attributes with `AllowMultiple == true`, so for that test, should it also test the order?

And the `DatapointAttribute` and `DatapointsAttribute`, should they be updated with `[Obsolete]`?

**Comment by CharliePoole** [comment]
The quoted test is correct, even if it could be better written.

Datapoint and Datapoints attributes are not obsoltete. They are completely unrelated to DatapointSource, in spite of the name similarlity.

I'd say just stick to fixing the error in AuthorTests to resolve this issue.
