### ISSUE TITLE
Data Driven TestFixture

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#2]
I have hierarchy like data-driven test cases that’s 3 levels deep.
Currently the TestFixture can only be instantiated only a constant
number of times. How can I parameterize the TestFixture based on
source input, same like the TestCaseSource attribute?

More info at https://bugs.launchpad.net/nunit-3.0/+bug/505700

**Comment by agray** [comment]
Given #715  has been implemented in Beta-3, can this issue be closed?

**Comment by CharliePoole** [comment]
Yes. In fa t I was looking for this one but didn't find it when you filed #715
