### ISSUE TITLE
Has.One as synonym for Has.Exactly(1).Items

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#2004]
As discussed in the context of issue #1790, we would like to implement this so that the following work:

Short Form                | Long Form
----------------------|----------------------------------
Has.One                    | Has.Exactly(1).Items
Has.One.EqualTo("X") | Has.Exactly(1).Items.EqualTo("X")

Similarly, we should add `One` wherever we now allow `Exactly`, e.g.: in `ConstraintExpression`.

**Comment by cristobalito** [comment]
@CharliePoole I'm happy to pick this up

**Comment by ChrisMaddock** [comment]
Great - have assigned it to you! 👍

**Comment by OmicronPersei** [comment]
Has there been any more movement on this?  I can pick this one up if needed.

**Comment by jnm2** [comment]
@cristobalito, it's been a while. Are you still working on this?

@nunit/framework-team I'm guessing 5 months means it's okay to just reassign, but how have we handled this before?

**Comment by rprouse** [comment]
@OmicronPersei, I have unassigned @cristobalito from this issue. Feel free to take it up and submit a PR. Sorry, I cannot assign to you until you are a member of the contributors team which I would prefer to happen after you've contributed 😄

**Comment by cristobalito** [comment]
Apologies all - this dropped off my radar in recent months. Will try and
pick up another one over the coming weeks to compensate.

Chris
