### ISSUE TITLE
Exclude empty failure messages from results xml

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#2005]
From the discussion on #1955 - if the message property for a failure is an empty string, then the message element should not be written to the xml.

To reproduce:
    
    Assert.Fail("")

will currently produce:

    <message><![CDATA[]]></message>

@cristobalito is going to take a look at this one.

**Comment by cristobalito** [comment]
So an interesting observation. If you specify a stacktrace, but no failure message, the `<message>` element is suppressed!

**Comment by CharliePoole** [comment]
@cristobalito What do you mean by specifying a stacktrace?

**Comment by cristobalito** [comment]
@CharliePoole Just going through the existing Failure tests (TestResultFailureTests.cs), trying out a few different combinations of values for message and stacktrace - the test sets these properties via SetResult. I appreciate non-test code will likely always have a reasonable value for stacktrace (or null).

My comment was just that I found it interesting that only supplying a stacktrace and a null message suppressed the `message`. Looking now at the code, that makes sense.

**Comment by CharliePoole** [comment]
I see. I thought you meant it from a user perspective, rather than internally.
