### ISSUE TITLE
Intermittent errors while running tests after updating to 3.6 

### ISSUE THREAD

**Issue by appel1** [nunit/nunit#2012]
Every now and then when we run our tests using the console runner after updating to 3.6 it fails with an error for some of the test assemblies. Tests for assemblies with this error are not discovered nor executed. It is not always the same assemblies that fails, sometimes it is one and sometimes there are more than one that fails. 

We execute the tests with: nunit3-console.exe [path to assemblies] -work=[absolute path to a directory] --result=TestResult.xml;format=nunit2

So far we've observed these errors with similar callstacks:
> Index was outside the bounds of the array.
>    at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
>    at NUnit.Engine.Services.TestAgency.LaunchAgentProcess(TestPackage package)
>    at NUnit.Engine.Services.TestAgency.CreateRemoteAgent(TestPackage package, Int32 waitTime)
>    at NUnit.Engine.Runners.ProcessRunner.CreateAgentAndRunner()
>    at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter)

> Object reference not set to an instance of an object.
>    at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
>    at NUnit.Engine.Services.TestAgency.LaunchAgentProcess(TestPackage package)
>    at NUnit.Engine.Services.TestAgency.CreateRemoteAgent(TestPackage package, Int32 waitTime)
>    at NUnit.Engine.Runners.ProcessRunner.CreateAgentAndRunner()
>    at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter)

**Comment by ChrisMaddock** [comment]
I'll move this to the console repo, and comment over there. 😄

**Comment by ChrisMaddock** [comment]
Issue moved to [nunit/nunit-console #168](https://github.com/nunit/nunit-console/issues/168) via [**ZenHub**](https://www.zenhub.com/)
