### ISSUE TITLE
OneTimeSetUp in different assembly?

### ISSUE THREAD

**Issue by gregeng** [nunit/nunit#2014]
@markikollasch and I are attempting to run tests in multiple different assemblies that will all require very similar setup. To avoid having to write that setup in every assembly, we've created an additional assembly with a single abstract class containing the `[OneTimeSetUp]` and `[OneTimeTearDown]` behavior we need. In each of the test assemblies we have created a concrete subclass with the `[SetUpFixture]` attribute, in such a way that the setup fixture is in the same namespace as the corresponding tests.

However, the one-time setup and one-time teardown methods aren't running in this configuration, and we're not sure why. Is this behavior intended, and is there a recommended way to run one-time setup methods from different assemblies?

**Comment by CharliePoole** [comment]
Although this is not something we designed for, I'd still expect what you describe to work. Someone will need to take a closer look to see why it isn't working.

Just to make sure we understand the problem, I take it that
 * All assemblies reference the NUnit framework (what version btw?)
 * The base class is abstract and public
 * The base class contains public methods with the [OneTimeSetUp] and [OneTimeTearDown] attributes
 * The derived classes have the [SetUpFixture] attribute, are public and not abstract.
 * The derived classes do __not__ contain any methods with [OneTImeSetUp] and [OneTimeTearDown]

**Comment by gregeng** [comment]
This may be a false alarm. We attempted without success to create a minimal reproduction of the issue, suggesting that the problem is specific to our project and not to our use of NUnit (3.6). Thanks for your help!

**Comment by CharliePoole** [comment]
OK... I'll close thus but we'll see any further comments or questions and can re-open if needed.

**Comment by rprouse** [comment]
@gregeng we had another user report that this happens if your two test assemblies reference different versions of the NUnit framework.
