### ISSUE TITLE
Applying an ICommandWrapper to every test in a fixture

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2015]
I wrote a custom `ICommandWrapper` (`IWrapSetUpTearDown`) which derives from `PropertyAttribute`.
This attribute is very similar to the built-in `ApartmentAttribute`. I would like to be able to specify it per fixture as well as per test. If applied per-fixture, it would have the same effect as applying it to every test method in the fixture, just like `ApartmentAttribute`.

Am I overlooking something, or is this a feature request?

**Comment by CharliePoole** [comment]
The only mechanism we currently have for an attribute that appears at a higher level but effects child tests is to leave something in the test context that will take effect when the child test is executed.

A general mechanism that will work for some uses is to define an ActionAttribute. That will often do the job if all you want is some particular thing to happen before and after each test is run.
