### ISSUE TITLE
Automatically supply boolean and enum values for a parameterized Test

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#2016]
@seraphim207 commented on [Mon Jan 30 2017](https://github.com/nunit/docs/issues/162)

I have code base working with NUnit 2 that uses [Theory] instead [Test] in most cases as commonly boolean/enum variables added as a parameters to support multiple test cases. After moving to NUnit 3 I realized (only after certain amount of time) that theory tests without parameters are just ignored and not executed as it was in NUnit 2. They are just ignored and not shown as ignored in test window of VS. 

I vote for therories without parameters to be considere as usual tests. Or [Test] should provide same auto value filling for boolean/enums as [Theory] does. This is very convenient to mark tests with single attribute and don't fear that some test would just dissapear from invocation list after removing parameter.

---

@CharliePoole commented on [Mon Jan 30 2017](https://github.com/nunit/docs/issues/162#issuecomment-276149165)

Please add a test case so we can be sure we understand the issue.

---

@seraphim207 commented on [Mon Jan 30 2017](https://github.com/nunit/docs/issues/162#issuecomment-276151355)

        [Test]
        public void ImInvoked()
        { }

        [Theory]
        public void ImInvoked(Boolean someBooleanParam)
        { }

        [Theory]
        public void ImSkipped() // not invoked by test adapter of NUnit 3, but was by NUnit 2
        { }

---

@CharliePoole commented on [Mon Jan 30 2017](https://github.com/nunit/docs/issues/162#issuecomment-276168973)

This is how it's.intended to work, with the exception that I think you should get some kind of error in the last example. You OTOH, would prefer it to work - as I understand it - as if the attribute were [Test].

In NUnit, a Theory is a set of test cases with a special interpretation of the results, different from that of a test. It must always have parameters. It has further characteristics in the implementation, beyond that definition:
 * Use of Datapoints to supply data
 * Generation of boolean and enum arguments when not supplied

You appear to be using Theory for one of it's secondary characteristics - the last one - rather than because you actually have a theory to be validated. Unfortunately, that's outside of the intent of the feature.

We could consider adding automatic generation of args to parameterized tests. Your examples don't include a parameterized test (a non-Theory, that is) without args provided, which would look like this:

```C#
[Test]
public void MyMethod(bool myarg)
{
}
```

What do others thing about this? It's currently an error, but we could check for args that we can generate and allow it.

---

@CharliePoole commented on [Mon Jan 30 2017](https://github.com/nunit/docs/issues/162#issuecomment-276169256)

Since this is not really a documentation issue, I'm moving it to the  nunit repository.

**Comment by seraphim207** [comment]
I vote for extended [Test] that supports bolean/enum (nullable too) autofilling.

**Comment by CharliePoole** [comment]
Name change reflects discussion.

**Comment by rprouse** [comment]
I don't think we should do this since we already have an explicit way of doing this using the `ValuesAttribute` which already auto-fills enums and bools, see https://github.com/nunit/docs/wiki/Values-Attribute

```C#
[Test]
public void MyEnumTest([Values]MyEnumType myEnumArgument)
{
    //...
}
```

```C#
[Test]
public void MyBoolTest([Values]bool value)
{
    //...
}
```

**Comment by seraphim207** [comment]
It looks redundant to specify Values attribute on enum and bool parameters. If user wants to narrow cases - than yes, user for example can specify only 2 of 6 enum values, but in general Test should provide all values for booleans and enums out of the box without attribute.

Btw, does mentioned [Values] approach support nullable booleans/enums?

**Comment by CharliePoole** [comment]
I changed this to be an idea for discussion. It seems to me we want to do something more for automatic generation of parameters, but maybe not this specific idea. I'd like to think about it, but only after we get this hotfix release out.

**Comment by seraphim207** [comment]
Hello,
any progress in the issue?

**Comment by CharliePoole** [comment]
@rprouse Don't you already do this?

**Comment by mikkelbu** [comment]
@CharliePoole If you refer to 
>Btw, does mentioned [Values] approach support nullable booleans/enums?

Then we do this now (since 3.11 - "ValuesAttribute now works with nullable types")

Personally, I like the distinction between simple tests and parametric tests, so I don't think we should change `[Test]` to also supply values for enums and booleans.

**Comment by CharliePoole** [comment]
@mikkelbu Yes, that's what I meant.

I agree entirely about `[Test]` since it doesn't supply any data at all. We can (or should) only change data-supplying attributes to do this. So `[TestCase]` would be fine but not IMO `[Test]`.

In which case, is there anything left to do? Can't this now be closed?

**Comment by mikkelbu** [comment]
I'll close it now.
