### ISSUE TITLE
Better message when timeout fails

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2020]
Currently when a timeout fails NUnit reports, "Test cancelled by user." While in a certain sense it's not wrong, it's confusing. It led me to believe that I was clicking the test abort icon in ReSharper. (I've been having tooling issues unrelated to NUnit.) In an integration test, it makes it sound as though the build is being canceled.

It's also missing the most relevant information about the test failure: how long it was expected to take.

Ideally it would say "Timeout of 3000 ms exceeded" or something similar. This way, you instantly know what caused the cancellation (the timeout attribute) without guessing, and you know how long it took. This is in the same spirit as every assertion message.

**Comment by jnm2** [comment]
Also, the test result should not be `ResultState.Cancelled` but `Failed`.

Places where test messages are set to `Cancelled by user`:
https://github.com/nunit/nunit/blob/3.6/src/NUnitFramework/framework/Internal/Results/TestResult.cs#L496-L499
https://github.com/nunit/nunit/blob/3.6/src/NUnitFramework/framework/Internal/Results/TestResult.cs#L533-L536
https://github.com/nunit/nunit/blob/3.6/src/NUnitFramework/framework/Internal/Execution/WorkItem.cs#L400
https://github.com/nunit/nunit/blob/3.6/src/NUnitFramework/framework/Internal/Execution/CompositeWorkItem.cs#L165
https://github.com/nunit/nunit/blob/3.6/src/NUnitFramework/framework/Internal/Execution/CompositeWorkItem.cs#L393

**Comment by CharliePoole** [comment]
The framework does exactly what you say it should do and has tests to prove it! How are you running? Can you provide a repo?

**Comment by jnm2** [comment]
> The framework does exactly what you say it should do and has tests to prove it! How are you running? Can you provide a repo?

Running via VSTest, both in the VS2017 IDE and via the Cake build script in a powershell window. Maybe it's an adapter issue then? I thought I found sufficient evidence in the framework repo to the contrary.

Here's a repro: https://github.com/jnm2/misc-codesamples/blob/master/Bug%20reports/NUnit/Test%20NUnit%20timeout%20message.zip

Just open a powershell window and run `.\build.ps1 -t test`.

**Comment by CharliePoole** [comment]
Closing as I believe it was fixed by PR #2106. Feel free to re-open if you see evidence that it was not fixed.
