### ISSUE TITLE
Make Is partial

### ISSUE THREAD

**Issue by BanksySan** [nunit/nunit#2022]
It would be useful to be able to append more constraints to the `Is` and `Has` classes.

In order to do this it would have to be made `partial`.

* Is this something that can be done?
* Is this something that I could do and submit a pull request?

**Comment by CharliePoole** [comment]
Partial classes are a compiler feature. To do what you want you would have to be compiling your changes together with NUnit, IOW, modifying NUnit.

For non-static syntax classes, like ConstraintExpression, you can create extension methods. For the static classes like `Is` or `Has` that's not an option. In that case, you can derive your own `Is` class from ours, in your own namespace, and manage visibility such that yours is always used in preference to ours. An alias may be needed in some cases.

**Comment by BanksySan** [comment]
Thanks for replying so quickly.

Your suggestion will only work if I'm pulling one set of home-brewed extensions.  I can't have separate packages pulled in as I need them.

For example:

* A set of assertions that are very specific to my application.
* `DateTime` assertions.
* `Enumerable<T>` assertions etc.

What would be the _bad thing(s)_ that might happen from a partial class?

**Comment by CharliePoole** [comment]
Well, the only bad things is that it won't work. 😞 

As I said, to use a partial class, you have to compile all the parts at the same time. You can't reference an assembly with a class - even if it was built as partial - and add more things to it.

Here's what Microsoft says about it...

> All partial-type definitions meant to be parts of the same type must be defined in the same assembly and the same module (.exe or .dll file). Partial definitions cannot span multiple modules.

**Comment by BanksySan** [comment]
Ah, yes.  That would certainly make it a bad idea.

Thanks for explaining it.
