### ISSUE TITLE
CollectionAssert.AreEqual and AreEquivalent failing on equal lists

### ISSUE THREAD

**Issue by evenflow58** [nunit/nunit#2026]
As noted by their names the first test fails while the second passes.
```
private class TestObject
{
	public int Prop1 { get; set; }

	public string Prop2 { get; set; }
};

[Test]
public void Fail()
{
	IEnumerable<TestObject> expected = new List<TestObject>
	{
		new TestObject
		{
			Prop1 = 1,
			Prop2 = "first prop",
		},
		new TestObject
		{
			Prop1 = 2,
			Prop2 = "second prop",
		},
	};

	IEnumerable<TestObject> actual = new List<TestObject>
	{
		new TestObject
		{
			Prop1 = 1,
			Prop2 = "first prop",
		},
		new TestObject
		{
			Prop1 = 2,
			Prop2 = "second prop",
		},
	};

	CollectionAssert.AreEqual(expected, actual);
}

[Test]
public void Pass()
{
	IEnumerable<TestObject> expected = new List<TestObject>
	{
		new TestObject
		{
			Prop1 = 1,
			Prop2 = "first prop",
		},
		new TestObject
		{
			Prop1 = 2,
			Prop2 = "second prop",
		},
	};

	IEnumerable<TestObject> actual = expected;

	CollectionAssert.AreEqual(expected, actual);
}
```

I believe the failure occurs because the hash codes are different so the objects are not actually equal. However, this reduces the usefulness of these comparers. While I can create an IComparer object I don't feel that should be the expected requirement. Can the hash codes be ignored or at least add a switch or another function that ignores them? 

Also, I think the error messages probably need an update. Object equality tests fail with unhelpful error messages:

> Test Name:	Fail
Test FullName:	Sapsan.Api.Tests.TeeSheet.CourseControllerTests.TestyTest
Test Source:	C:\Code\dearborn-station\Sapsan\Sapsan.Api.Tests\TeeSheet\CourseControllerTests.cs : line 116
Test Outcome:	Failed
Test Duration:	0:00:00.178
Result StackTrace:	at NUnit.Framework.CollectionAssert.AreEquivalent(IEnumerable expected, IEnumerable actual)
at Sapsan.Api.Tests.TeeSheet.CourseControllerTests.TestyTest() in C:\Code\dearborn-station\Sapsan\Sapsan.Api.Tests\TeeSheet\CourseControllerTests.cs:line 145
Result Message:	Expected: equivalent to < <Sapsan.Api.Tests.TeeSheet.CourseControllerTests+TestObject>, <Sapsan.Api.Tests.TeeSheet.CourseControllerTests+TestObject> >
  But was:  < <Sapsan.Api.Tests.TeeSheet.CourseControllerTests+TestObject>, <Sapsan.Api.Tests.TeeSheet.CourseControllerTests+TestObject> >

These tests were run in Visual Studio 2015 using NUnit 3.6.0.

**Comment by jnm2** [comment]
This is expected behavior. It doesn't have to do with the hash code though. Equality is defined by .NET's `object.Equals`. .NET does not consider your objects equal unless you override `Equals`, so neither does and neither should NUnit.

However, .NET'S equality API contract requires you to return equal hash codes for objects you define as equal, so you will have to override `GetHashCode` too. This is especially important if NUNIT uses a hash table as an implementation detail.

Of course writing an `IEqualityComparer` rather than overriding `Equals` and `GetHashCode` is an option if the logic is not really intrinsic to the objects themselves.

**Comment by jnm2** [comment]
To back up what I'm saying, compare List.Contains, Array.IndexOf, HashSet.SetEquals, try adding the objects as a key twice to a dictionary and see they are treated as different keys, and any other equality API.

**Comment by CharliePoole** [comment]
Additionally, to get a better error display, override ToString() on TestObject.
