### ISSUE TITLE
Limit Language level to C#6

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#2031]
The framework and console currently use a maximum language level of C#6 - we want to maintain that to ensure the projects can still be built by the C#6 generation of IDEs.

To enforce this, it would be great if we could add the `<LangVersion>` attribute to all the csproj's. This would prevent the projects compiling with C#7 features, help new contributors discover the required language level, and ensure no C#7 code slips through code review.

This can be set in VS by going to:
    
    Project Properties => Build tab => Advanced button => Language Version

Making that change will add a new property to the csproj file - it may be easier to edit the rest of the csproj's by hand, once the required XML has been found!

**Comment by jnm2** [comment]
I'm happy to take this one :D

**Comment by CharliePoole** [comment]
How come you reopened this?

**Comment by jnm2** [comment]
I must have done something wrong in ZenHub. I'm sorry!
