### ISSUE TITLE
NullReferenceException inside failing Assert.That call

### ISSUE THREAD

**Issue by yaakov-h** [nunit/nunit#2035]
I have some integration tests written in NUnit that test the code I have that calls the NUnit Engine APIs . This is particularly to ensure that I am treating the NUnit XML correctly and handling certain edge cases

i.e.: Test Runner Unit Tests ---> NUnit Engine ---> Dummy Unit Tests

I am in the process of upgrading this from NUnit 3.4 to 3.6.

When using the 3.6 framework and binaries for all of the above listed components, a failing Test Runner unit test throws a NullReferenceException:

```
Result StackTrace:	
at NUnit.Framework.Assert.ReportFailure(String message)
   at NUnit.Framework.Assert.ReportFailure(ConstraintResult result, String message, Object[] args)
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args)
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression)
   at My.Test.Case.Here() in C:\Path\To\File.cs:line 108
Result Message:	System.NullReferenceException : Object reference not set to an instance of an object.
```

It appears that in the process of creating, calling into and disposing of engine, `TestExecutionContext.CurrentContext.CurrentResult` becomes null.

**Comment by yaakov-h** [comment]
The error looks very much the same as #2025, #1965 and #1952, except there is no asynchronicity going on here. My tests are synchronous.

**Comment by CharliePoole** [comment]
Can you post a sample test? What framework are you targeting?

**Comment by yaakov-h** [comment]
https://github.com/yaakov-h/NUnit2035/blob/master/NUnitEngineTesting/NUnitEngineRunnerTest.cs#L10

```
Test Name:	NUnitIssue2035
Test FullName:	NUnitEngineTesting.NUnitEngineRunnerTest.NUnitIssue2035
Test Source:	C:\Temp\NUnitEngineTesting\NUnitEngineTesting\NUnitEngineRunnerTest.cs : line 11
Test Outcome:	Failed
Test Duration:	0:00:00.948

Result StackTrace:	
at NUnit.Framework.Assert.ReportFailure(String message)
   at NUnit.Framework.Assert.ReportFailure(ConstraintResult result, String message, Object[] args)
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args)
   at NUnit.Framework.Assert.That(Boolean condition)
   at NUnitEngineTesting.NUnitEngineRunnerTest.NUnitIssue2035() in C:\Temp\NUnitEngineTesting\NUnitEngineTesting\NUnitEngineRunnerTest.cs:line 17
Result Message:	System.NullReferenceException : Object reference not set to an instance of an object.
```

**Comment by CharliePoole** [comment]
I think you're special case may have to do with using the framework twice on the same thread. When `FrameworkController.RunTests` finishes running tests. It clears the current TestExecutionContext, which is non-serializable, from the `CallContext`.

As an experiment, can your test create a thread on which to call the engine? That would help verify the nature of the problem and we could then look for a more permanent solution.

**Comment by yaakov-h** [comment]
I changed just the test method to the following:

```
using System;
using System.IO;
using System.Runtime.ExceptionServices;
using System.Threading;
using NUnit.Framework;
using NUnit.Framework.Internal;

namespace NUnitEngineTesting
{
	class NUnitEngineRunnerTest
	{
		[Test]
		public void NUnitIssue2035()
		{
			Assert.That(true);

			var pathToAssembly = Path.Combine(TestContext.CurrentContext.TestDirectory, "TestAssembly.dll");
			// var xml = NUnitEngineRunner.RunAllTests(pathToAssembly);
			var xml = RunTestOnAnotherThread(pathToAssembly);

			Assert.That(false);
		}

		string RunTestOnAnotherThread(string pathToAssembly)
		{
			var xml = default(string);
			ExceptionDispatchInfo edi = null;
			var thread = new Thread(() =>
			{
				try
				{
					xml = NUnitEngineRunner.RunAllTests(pathToAssembly);
				}
				catch (Exception ex)
				{
					edi = ExceptionDispatchInfo.Capture(ex);
				}
			});
			thread.Start();
			thread.Join();

			edi?.Throw();
			return xml;
		}
	}
}
```

Now the test fails with the following, as expected:

```
Test Name:	NUnitIssue2035
Test FullName:	NUnitEngineTesting.NUnitEngineRunnerTest.NUnitIssue2035
Test Source:	C:\temp\NUnitEngineTesting\NUnitEngineTesting\NUnitEngineRunnerTest.cs : line 14
Test Outcome:	Failed
Test Duration:	0:00:01.192

Result StackTrace:	at NUnitEngineTesting.NUnitEngineRunnerTest.NUnitIssue2035() in C:\temp\NUnitEngineTesting\NUnitEngineTesting\NUnitEngineRunnerTest.cs:line 21
Result Message:	
Expected: True
  But was:  False
```

So the threading does appear to be the cause.

**Comment by CharliePoole** [comment]
@yaakov-h That tells us what we have to fix for your particular issue and it also will help with our own tests of NUnit, which need to do the same thing. Basically FrameworkController was written with the expectation that it would only ever be called from the engine, which doesn't normally have a context established. But in your case, the engine is created and called from a test, so there is a pre-existing context. I'll modify the code so that the Framework checks if there is already a context established on entry and restores it on exit rather than simply changing it to null.

**Comment by CharliePoole** [comment]
I gave this a shot for the hotfix 3.6.1 release but it's really a bit too complicated for a quick fix. I suggest using the workaround of creating a thread for now.

@rprouse @ChrisMaddock The basic problem is that we avoid null references by automatically creating a current TestExecutionContext whenever we need one and it isn't there. It's done in the getter. This has led to a number of subtle issues and I think we would be better off if the property acted like a normal property and the context was only created by an explicit call. But that involves changing a lot of stuff and I don't want to do it as part of the 3.6.1 release.

**Comment by ChrisMaddock** [comment]
Sounds good to me.

**Comment by CharliePoole** [comment]
@yaakov-h Could you try one of the framework packages here?

https://ci.appveyor.com/project/CharliePoole/nunit/build/3.7.0-ci-03706-pr-2055/artifacts

I'm hoping this fix will end up solving your problem.

**Comment by yaakov-h** [comment]
I replaced nunit-framework.dll with the net45 from the zip file there, and this does solve the issue.

I'm now getting the failing assertion rather than the null reference exception when on the same thread as the engine.

**Comment by CharliePoole** [comment]
Great! I'm marking this as closed with PR #2055

Anyone with the same problem can use our myget feed to download build 3.7.0-dev-3707 or later.

**Comment by yaakov-h** [comment]
@CharliePoole Is there a rough timeframe for a 3.7 final release?

**Comment by CharliePoole** [comment]
The milestone indicates March 10 ( https://github.com/nunit/nunit/milestones ) but since we just did 3.6.1 we'll probably hold off a few more weeks to get some other things fixed. In particular, there are about three other bugs that relate to PR 2055, but which may not be entirely fixed by it.
