### ISSUE TITLE
Run test in isolation

### ISSUE THREAD

**Issue by vSkullv** [nunit/nunit#2038]
Hi,

Is it possible to run a test method in isolation, i.e. no other tests runs in parallel?

**Comment by CharliePoole** [comment]
If you don't use the `[Parallelizable]` attribute at all, tests are not run in parallel, with one exception. If some of your tests require the STA - indicated by using `[RequiresSTA]` or `[ApartmentState(ApartmentState.STA)]` - those tests will run in parallel on the STA thread with all your other tests running in the MTA. For most users, this doesn't cause a problem.

To eliminate even this small amount of pararallel execution, you may either

* Specify `[Parallelizable(ParallelScope.None)]` at the assembly level. This will change to `[NonParallelizable]` in the next release.

* Specify `--workers=0` at the nunit3-console command-line.

**Comment by vSkullv** [comment]
This is quite useful. Thanks for letting me know.

**Comment by daniel-seitz** [comment]
With having Parallelizable(ParallelScope.Fixtures), is it possible to mark one Test (testing cleanup scenarios) to run isolated after all others have been run?

I'd like to speed up things and having all tests run in parallel, when they are ALL finished, then run the last one. Didn't find anything about it and tested ie. these here: https://www.ontestautomation.com/running-your-tests-in-a-specific-order/
