### ISSUE TITLE
When I build my own ConstraintResult, Not is not accounted for

### ISSUE THREAD

**Issue by erichjz** [nunit/nunit#2042]
I'm pretty sure this is just my lack of understanding of the API. 

NUnit, version v3.6.0.0
NUnit3TestAdapter v3.7.0

I have a method that uses the EqualConstraint and ConstraintResult objects directly (instead of nested in an Assert call). It is a workaround for some old code I am still supporting.

I ended up with the following code:

`var constraint = Is.Not.EqualTo(1.234d).Within(0.1d);`
`var result = constraint.ApplyTo(1.234d);`
`Assert.That(result.IsSuccess, Is.False);`

My Expectation is that the assertion would succeed: result.IsSuccess would be **false**, because 1.234d is equal to 1.234d.

The actual result, though, is that result.IsSuccess ends up **true**.

Is there some approach to constraints that I am not understanding? 

ETA: This is consistent regardless of the constraint type: it also happens on NullConstraint (test that a null object is not null still give result.IsSuccess true)

**Comment by CharliePoole** [comment]
See this: https://github.com/nunit/docs/wiki/ReusableConstraint

**Comment by erichjz** [comment]
Perfect: thanks for the response!
