### ISSUE TITLE
Regression in 3.6.0 when catching AssertionException

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#2043]
@pdpurcell commented on [Thu Feb 16 2017](https://github.com/nunit/docs/issues/168)

In version 3.5.0, catching a failed assertion would allow the test to continue and the test would then pass.  Version 3.6.0 continues running the code, but the final state will be set to failed.  Is this a regression?  I see no mention of this sort of behaviour change in the [release notes](https://github.com/nunit/docs/wiki/Release-Notes#nunit-36---january-9-2017).  
I have [attached an example solution](https://github.com/nunit/docs/files/780587/WithProblem36.zip) that contains two projects that have identical tests; one using 3.5.0 and one using 3.6.0.  
eg:
```
try
{
    Assert.AreEqual(0, 1);
}
catch(AssertionException)
{
    // The failed assertion is caught but in 3.6.0 the test still fails
}
```

---

@CharliePoole commented on [Thu Feb 16 2017](https://github.com/nunit/docs/issues/168#issuecomment-280498245)

The bad news is that this has __never actually been supported__ even though it's a technique promulgated on many blogs and forums. That is...

*NUnit makes no guarantee that failures cause an AssertionException that catching the exception will prevent the failure from happening. This is certainly not a guarantee in NUnit 3 and - to my memory - never was in NUnit V2 either.*

When this technique has come up, I have frequently tried to warn people off using it. There are lots of reasons to avoid it:

* It implies that your test knows something about the framework that is executing it, which is a serious violation of encapsulation - that is, unless you are actually testing the internals of framework itself.

* There are usually supported ways to accomplish whatever you are trying to do, without the  try / catch.

* Where there is an unsupported need, it makes more sense to request a feature, which will be supported now and in the future.

* It's an implementation detail of NUnit, which could change at any time.

Of course, the last point has come true in the latest release.

In NUnit 3.6, the details of the implementation have changed. We still use an exception to terminate execution of your test. It's the only way we have to unwind any nested calls you have made. However, we no longer use the exception to report that the test failed. That info is recorded before the exception is thrown. This allows us to use a consistent approach for single assertion failures, multiple assertion failures and warnings.

As you say, there is no mention of this in the release notes. That's because we felt that there was no need to document an internal change that should never be used by users. For the same reason, we didn't list this as a breaking change. From some of the feedback, it's clear that there are users who did __not__ consider this a detail of implementation and relied on it. There are already several issues.

Most of the issues - like yours - illustrate the "problem" without motivating the need to be able to intercept a failure. In each case, I have asked the submitter of the issue to give a motivating example that would help us meet the need. IOW we need to know __why__ you want to be able to prevent a failure by catching the AssertionException. In the long term, we may want to add features that make it unnecessary for you to do such a thing!

Since you're the fourth or fifth person to raise the issue, it is clear that we need to do something, in spite of my continued belief that you should not really be relying on how NUnit is implemented. I'll close this comment and start a fresh one with a proposal to partially role back the change.

---

@CharliePoole commented on [Thu Feb 16 2017](https://github.com/nunit/docs/issues/168#issuecomment-280501306)

@nunit/framework-team @nunit/core-team 
As stated in my first comment here and on several other issues, I continue to believe that folks who rely on AssertionException and particularly on catching it are making a mistake. "NUnit implements failures via an assertion exception and you can stop the failure by catching it" is __not a sentence in our documentation__ and not part of the API we provide to programmers.

Several people have pointed out reasons why it should work, however:
* Most other frameworks work that way
* It has worked in the past
* Exceptions thrown is part of the API of many methods

I could argue against all of those points, but why bother? It seems that a number of users are affected and I think there's a change that can be made. Here's what I propose...

1. Stop creating the failure message in the result before throwing an AssertionException outside of a Multiple Assert block.

2. Continue to create the failure message without throwing when inside a Multiple Assert block.

3. Upon exit from a MultipleAssertBlock in which failures have occured, throw a (new) MultipleAssertionException rather than an AssertionException, so that the framework knows that one or more failures have already been recorded and need to be reported.

4. Continue to handle warnings as we do, recording them without throwing an exception.

This will ensure that __where we do throw an AssertionException__ it works exactly as before. Those places where we don't throw one are new features so no compatibility issue arises.

I think this is critical enough to warrant a hot fix release. Please let me know if you agree with that as well as with the fix itself. I can do the fix myself pretty quickly once we agree on it.

**Comment by ChrisMaddock** [comment]
I think that sounds viable. Is there anything you can foresee, that making this change may limit us in the future Charlie?

I suggest we go one way or the other, either keep current behaviour and implement new workaround features, or make the assertion exception a documented feature.

There seems to be more user code dependent on this long-standing implementation detail than first thought. Regardless of whether official or not, perhaps we should consider it a breaking change, and weigh up pros and cons as we would with an api change.

**Comment by jnm2** [comment]
I've always considered thrown exceptions to be part of the public API. They are veritable return types whether intended that way or not.

**Comment by CharliePoole** [comment]
@jnm2 Agree for most libraries. But this is an exception you are not supposed to catch.

In any case, one is usually advised to only catch exceptions that you can actually handle, which is not the case here.

However, we can still try to minimize the surprise for users.

@ChrisMaddock I implemented it as I did to avoid introducing a new exception type. In retrospect, the new type should make things clearer.

**Comment by rprouse** [comment]
Charlie, your approach sounds good to me and I agree it is probably worth a hotfix. I will be in a place with better Wi-Fi tomorrow if you want help. We should probably make this fix as a branch off the release branch if you haven't done it yet.

**Comment by CharliePoole** [comment]
@rprouse I'll do it that way. I'm setting aside my work on #164 to do this one. Should have it this morning. You may want to check if there are other bug fixes that ought to be cherry-picked. If you can do the release tomorrow, that would be perfect!

**Comment by CharliePoole** [comment]
Turns out I already have a MultipleAssertException, so that part is done. :-)

**Comment by CharliePoole** [comment]
@pdpurcell A workaround was mentioned elsewhere already, but not here: if you use Assert.Throws rather than a try/catch, your problem disappears. That's because Assert.Throws is a supported feature and it understands how NUnit uses the exception.

**Comment by oznetmaster** [comment]
Once this is completed, is this going to become a documented API/feature?

**Comment by CharliePoole** [comment]
@oznetmaster I'd prefer to add something about our exceptions to the docs that warns people __not__ to intercept them.

**Comment by appel1** [comment]
Have you considered making it possible to opt-in to the 3.6 behavior? I can't think of any situation where we'd want to catch any assertion exceptions and we've already had a couple of situation where we'd missed test failures for some time because they were hidden by code catching Exception. Would be nice if it was possible to avoid that potential mistake.

**Comment by jnm2** [comment]
@appel1 If you were accidentally catching assertion exceptions, your catch block was too wide or a catch-all which is a deadly antipattern. If you only catch specific exceptions which it is that particular code's responsibility to expect and to recover from, you won't have this problem. It's much bigger than NUnit.

**Comment by CharliePoole** [comment]
@appel1 The mechanisms we use to report failures are such a fundamental part of NUni that I'd be hesitant to complicate things by a setting that causes it to work in two different ways. The solution in the PR is to revert to the "old" way for simple failures anuses the new mechanism for new features. As we all know, people shouldn't be catching exceptions indiscriminately.

For NUnit's own exceptions, I guess we need a warning in the docs.

**Comment by CharliePoole** [comment]
Fixed by #2046

**Comment by pdpurcell** [comment]
I've experienced same regression as I reported above but this time it's between versions 3.9 and 3.10. Is this to be expected?  I've attached a sample solution that illustrates the issue.  
I'm more interested to know if this is a regression or not.  If the plan is to no longer support this type of assertion exception handling pattern, that's fine, the test cases can be done in a different way, but it'd just be good to know if this is the direction the library will be continuing on in the future.
[NUnitRegession.zip](https://github.com/nunit/nunit/files/2234024/NUnitRegession.zip)

**Comment by pdpurcell** [comment]
Should this ticket be reopened?

**Comment by CharliePoole** [comment]
I was waiting for some current @nunit/framework-team members to respond as to how they want to handle this issue, but a new ticket would probably hasten that response. In any case, that would better document that the problem was not present in 3.9 but returned in 3.10.

Folks, I don't actually know what to tell @pdpurcell about whether this is intended to work in future. If, as I suspect, my PR #2700 caused the problem, it did it without breaking any existing tests.

**Comment by CharliePoole** [comment]
In our past discussions, I advocated not supporting this. I believe I was overruled but I was not sure, which is why I'm asking now.

**Comment by jnm2** [comment]
I don't remember anything like overruling! Looking through I see Rob supporting you and myself saying you had good points and agreeing with them.

I do think we should remove this which is no longer true:

https://github.com/nunit/nunit/blob/abbaed7dc715e6717eaa99d67e15c819fabfe7a6/src/NUnitFramework/framework/Assert.That.cs#L40-L43

**Comment by CharliePoole** [comment]
I may be mixing this up with the ability to directly call test methods, which is somewhat related. In any case, an earlier PR "fixed" this for 3.6 and then I think my unrelated PR #2700 broke it for 3.10. 

In any case, whichever way it goes, I agree the documentation should say something about it. I guess one of:

"Catching an assertion exception will prevent the test from failing."
OR
"Catching an AssertionException will not prevent the test from failing."
OR
"Do not try to catch an AssertionException in your tests as it causes undefined behavior."

**Comment by jnm2** [comment]
> "Do not try to catch an AssertionException in your tests as it causes undefined behavior."

This would be an argument for making NUnit exceptions internal.

How about:

```cs
/// <summary> 
/// Asserts that a condition is true. If the condition is false, the current test is failed
/// and the method may also throw an <see cref="AssertionException"/>.
/// </summary>

**Comment by CharliePoole** [comment]
That works as well. More critical, IMO, is that the policy behind it be clear, both to users and to yourselves.
