### ISSUE TITLE
NUnit Adapter 3.7 - Error

### ISSUE THREAD

**Issue by NUnitTester** [nunit/nunit#2044]
DataSources.TestCases has tow test cases, used in more than one test like shown below.
But the Test-Explorer shows only two tests in class Tests, expected are four. This seems to me an error in NUnit Adapter 3.7.
NUnit3TestExecutor does execute all tests, so it is possible to debug them. But is impossible to select one testcase and debug only Test1. Test2 is also executed.

`public class Tests {`
`[TestCaseSource(typeof(DataSources), nameof(DataSources.TestCases))]
[Test]
public void Test1(int value)
{    ...   }`

`[TestCaseSource(typeof(DataSources), nameof(DataSources.TestCases))]
[Test]
public void Test2(int value)
{    ...   }`

**Comment by CharliePoole** [comment]
Let's say that your data source has two int values, 100 and 200.

In that case, there will be four tests:
 * Test1(100)
 * Test1(200)
 * Test2(100)
 * Test2(200)

These are all distinct names and should be listed separately by the IDE unless you have done something to set the names of the tests yourself in creating the data source. Problems also arise if the string representation of the arguments is not distinct, but that would not be a problem with integer data as used in your example.

Can you post the data source code that is used with your tests? That will help us resolve the problem.

**Comment by NUnitTester** [comment]
Yes, all my TestCases are named and most with Description. Something like this:
`public static IEnumerable<TestCaseData> TestCases
{
	get
	{
		yield return new TestCaseData(2).SetName("Two");
		yield return new TestCaseData(3).SetName("Three");
	}
}`

What I expect:
Tests.Test1.Two
Tests.Test1.Three
Tests.Test2.Two
Tests.Test2.Three

But what I see is:
Tests.Two
Tests.Three

**Comment by NUnitTester** [comment]
Just testet now with Resharper 2016.2: A little bit better, all testcases are shown but with same name:
Tests.Two
Tests.Two
Tests.Three
Tests.Three

Perheps it helps. Seems to me that the class has been forgotten if the testcases are named.

**Comment by CharliePoole** [comment]
Your naming is defeating NUnit's attempt to keep things distinct. Your tests are named

Tests.Two
Tests.Three
Tests.Two
Tests.Three

You have removed Test1 and Test2 from the names entirely. If you look closely, you will see that each of the two names display two separate results. So the result is not lost but the organization is not so good.

If you must rename the  tests, use something like "{m}.Two" where {m} will be substituted by the method name. In my experience, the default name is clear enough for types like int.

**Comment by NUnitTester** [comment]
Oh, I don't think so. How can I rename the tests?
For all test methods the TestCaseSource is the same. That seems to me the problem. If I change the name of each TestCase in the Source, nothing change. Or what do you mean?

By the way: My TestCaseData is not really int, it has more than 5 parameters, autmated naming is terrible in this case. I only make a simple example to show the case.

**Comment by CharliePoole** [comment]
Not the class, but the method name. And it's not forgotten. Rather, NUnit is dropping it per your instructions. The phrase `SetName("Two")` basically means, call the test "Two" rather than "Test1.Two" or "Test2.Two". Theoretically, you could use `.SetName` to call every test in your assembly by the same name. It's just not a very good idea. :-)

**Comment by CharliePoole** [comment]
In that case, you may need to give your actual example. However, first try simply including "{m}" in the name to represent the name of the method. That ought to solve your problem.

**Comment by NUnitTester** [comment]
Ah great. I didn't know this feature. Where is the documentation to it? Are there more things like that? In my case I also need the TestCaseSource name.
Because I have more than one TestCaseSource per methode and the TestCases have the same name in each source but different representations. It's very special I know.

**Comment by CharliePoole** [comment]
Right now this is the best we have as docs: https://github.com/nunit/docs/wiki/Generation-of-Test-Names-Spec

We don't have a for the test case source but you can specify a different hard-coded string portion for each source to keep them separate. Your SetName would have to reflect both the source and the case.

**Comment by NUnitTester** [comment]
Thanks a lot.
