### ISSUE TITLE
Braking change in TestStatus enum

### ISSUE THREAD

**Issue by Droni** [nunit/nunit#2047]
https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Interfaces/TestStatus.cs has a braking change. If you want to change an enum, you should add new item below or you should use explicit item value, for example:

Inconclusive = 0,
Skipped = 1,
etc.

Currently the Warning item has value for Failed item in previous versions.

**Comment by CharliePoole** [comment]
These values are not exposed in any API. Can you explain what is being broken?

**Comment by Droni** [comment]
we are using these values to convert a test result to an our structure.

**Comment by CharliePoole** [comment]
The only runner that uses the defined values of the enums is the nunitlite runner, which is built along with the particular version of the framework that it references. 

For public use, we defined two APIs for running tests, the Framework API and the Engine API. Both of them return an XML result which uses the __names__ of the enum values, not the int equivalents. 

Have you built some sort of runner that links directly to the framework?

**Comment by Droni** [comment]
Yes. We are using non-public API because the XML is too expensive to performance.

**Comment by Droni** [comment]
Also from the XML is not possible determine arguments for test cases with parameters except as string value. We need much more info about test than it is possible retrieve from the XML.

**Comment by CharliePoole** [comment]
It sounds as if you need something that directly references the framework and is rebuilt for each version.

In the design of NUnit 3, we elected to name-value pairs and XML as the way to interface with the framework as a way of providing portablility and backward compatibility. That's the design. Of course, it represents a tradeoff. However, the efficiency loss using XML turned out to be very small.

Are you directly referencing the framework or are you using reflection?

**Comment by Droni** [comment]
We are using references to nunit assemblies. In most cases no needed to rebuild with new version of nunit. But some times you are made braking changes and in this case we should rebuild too. However I think that change the enum items position is not a good idea :)

**Comment by CharliePoole** [comment]
If you are referencing the assembly, it seems to make sense to use the actual enum names, such as `TestStatus.Failed` rather than the int values. The entire purpose of enumerations in C# is to decouple the enum names from the values used to represent them __so the latter can be changed__.

**Comment by Droni** [comment]
Sure, but for this we need create another brunch. Currently we have brunch for 2.4, 2.5, 3.0 and 3.4. And now we need to add another one 3.6. Eh, let's do this.
