### ISSUE TITLE
Random Error with OpenCover

### ISSUE THREAD

**Issue by SebastienCharles** [nunit/nunit#2048]
Hello

We have an issue with NUnit when running it with OpenCover. 
Our tests are executed successfully but sometime NUnit report an error. Without coverage, we don't have any problem.

We are using the the nuget package 
<package id="NUnit" version="3.6.0" targetFramework="net452" />
<package id="NUnit.ConsoleRunner" version="3.6.0" targetFramework="net452"  />
<package id="NUnit.Extension.NUnitV2ResultWriter" version="3.5.0" targetFramework="net452"  />

Starting Coverage for ABCDE
Executing: D:\abcde\lib\NUnit.ConsoleRunner\tools\nunit3-console.exe
Runtime Environment
   OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
  CLR Version: 4.0.30319.42000

Test Files
    D:\abcde\proj\bin\Debug\XYZ\ABCDE.XYZ.Unit.Tests.dll
    D:\abcde\proj\bin\Debug\ABCDE.Unit.Tests.dll

Test Filters
    Where: cat == ABCDE

Errors, Failures and Warnings

1) Error : D:\abcde\proj\bin\Debug\Sgcib.Iron.Aggregation.Plugin.XOne.Unit.Tests.dll
The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at NUnit.Engine.Services.TestAgency.AgentDataBase.get_Item(Guid id)
   at NUnit.Engine.Services.TestAgency.CreateRemoteAgent(TestPackage package, Int32 waitTime)
   at NUnit.Engine.Services.TestAgency.GetAgent(TestPackage package, Int32 waitTime)
   at NUnit.Engine.Runners.ProcessRunner.CreateAgentAndRunner()
   at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter)

Run Settings
    DisposeRunners: True
    DefaultTimeout: 600000
    WorkDirectory: C:\Users\ABCEF\AppData\Local\Temp
    MaxAgents: 4
    NumberOfTestWorkers: 1
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.5.2
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False

Test Run Summary
  Overall result: Failed
  Test Count: 8, Passed: 8, Failed: 0, Warnings: 0, Inconclusiv0, Skipped: 0
  Start time: 2017-02-17 22:31:47Z
    End time: 2017-02-17 22:34:50Z
    Duration: 182.701 seconds

Results (nunit2) saved as D:\abcde\nunit-report-ABCD.xml
Committing...
Visited Classes 216 of 1516 (14.25)
Visited Methods 750 of 8329 (9)
Visited Points 5137 of 55802 (9.21)
Visited Branches 1459 of 18950 (7.70)

Regards

Sébastien

**Comment by ChrisMaddock** [comment]
This looks to be the same error as https://github.com/nunit/nunit-console/issues/168 - introduced in NUnit Console 3.6.

As a workaround, you can use `--agents=1` - which will force your assemblies to run sequentially on a single agent, and should prevent this crash.
