### ISSUE TITLE
NullReferenceException with TestCaseSource if a property has no setter

### ISSUE THREAD

**Issue by provegard** [nunit/nunit#2052]
I've written a base class for running NSpec examples using NUnit. I just upgraded it to use NUnit 3, which worked fine. But when I try to target netstandard 1.6, I get the following when running tests:

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at NUnit.Compatibility.TypeExtensions.NotPrivate(MemberInfo info)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at NUnit.Compatibility.TypeExtensions.GetAllMembers(Type type)
   at NUnit.Compatibility.TypeExtensions.GetAllMembers(Type type)
   at NUnit.Compatibility.TypeExtensions.GetMember(Type type, String name, BindingFlags ignored)
   at NUnit.Framework.TestCaseSourceAttribute.GetTestCaseSource(IMethodInfo method)
   at NUnit.Framework.TestCaseSourceAttribute.GetTestCasesFor(IMethodInfo method)
```

The TestCaseSource attribute lives in a class that inherits the `nspec` class from NSpec, and it has properties without getters, e.g.:

```
    public virtual Expression<Action> specify
    {
      set
      {
        this.AddExample((ExampleBase) new Example(value, false));
      }
    }
```

I'm guessing that the exception happens here:

https://github.com/nunit/nunit/blob/8a9195879a7bd7f23231e5584e54663305c19597/src/NUnitFramework/framework/Compatibility/ReflectionExtensions.cs#L200

That code is only used with netstandard 1.6, which explains why things worked well before that.

**Comment by provegard** [comment]
## Minimal repro

Include the following file in a .NET Core class library targeting .NETStandard 1.6:

```
    public abstract class TestBase
    {
        public string DontGetMe
        {
            set { }
        }

        public static IEnumerable Provider()
        {
            yield return "test";
        }

        [TestCaseSource(nameof(Provider))]
        public void Test(string data)
        {
            Assert.That(data, Is.Not.Empty);
        }
    }
```

Then add the following in a .NET Core console application:

```
    public class TheTest : TestBase
    {
    }
```

**Comment by CharliePoole** [comment]
Confirmed by inspection. The cited line needs a `?.`

**Comment by GCichosz** [comment]
Can I grab this?

**Comment by CharliePoole** [comment]
All yours :smile:

**Comment by provegard** [comment]
Thanks for the fix! Will there be a hotfix release including this?
