### ISSUE TITLE
TestCaseSource attribute causes test to pass when source is not defined

### ISSUE THREAD

**Issue by estrizhok** [nunit/nunit#2062]
Steps to reproduce:
1. Create a new project,
2. Reference nunit.framework.dll version 3.6.1
3. Paste the following snippet as a class into the project:
4. Compile project and run the tests using nunit3-console.exe

```csharp
public class TestClass 
{
   [TestCaseSource("UndefinedSource")]
   public void Test(int param) { }
}
```

Observed result:
1. Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
2. TestResult.xml contains node <test-suite name="Test" result="Passed" /> with no children

Expected result:
1. NUnit should report absence of class member referenced in by the attribute as an error

**Comment by IngoVals** [comment]
This also happens if source exists but is empty. I think at least the test should be *inconclusive*.

**Comment by CharliePoole** [comment]
@IngoVals These are of course two different situations.

If the member referenced can't be found it's an error and the test is invalid.

If it exists but is empty, no data is provided so the test can't be run. It's a question of design whether this should pass or be inconclusive. It definitely can't be an error, since there are situations where people deliberately create sources that sometimes do not have data.

The design decision in NUnit up to now has been that __Tests__ with no data provided pass, while __Theories__ with no data are inconclusive. IOW, a Test is innocent till proven guilty but a Theory is a failure unless it can be proven a success. 😄

**Comment by jnm2** [comment]
Re: pass or inconclusive, think of this situation. I have integration tests going against a database. It might be a database full of data, or it might be a newly created, empty database. I have tests such as `Report_does_not_have_invalid_filter(string reportName)` and a test case source generating a case for every report in the database.

For a brand new database, there are no reports set up yet, so no test cases. Does that mean that it is inconclusive whether there are any reports with an invalid filter? No; the answer is entirely conclusive that there are no reports with an invalid filter and that I should be seeing a green light.

If I wasn't using TestCaseSource, I'd be using something like `Assert.That(reports.All(HaveValidFilter));`. If there are no reports, it succeeds. You'd intuitively expect the refactoring to a `TestCaseSource` to preserve this semantic.

**Comment by CharliePoole** [comment]
@jnm2 That's a convincing use case. Of course, folks who want it to work differently can probably come up with counter-cases. 😄 But basically, I'd have to say this is one of those things decided long ago, which can't really be changed without breaking compatibility significantly.

**Comment by jnm2** [comment]
@CharliePoole I'd say that just like you'd have to go out of your way to get an inconclusive result without TestCaseSource:

```c#
if (!resports.Any()) Assert.Inconclusive();
Assert.That(reports.All(HaveValidFilter));
```

You should also have to go out of your way to implement this semantic with TestCaseSource- *if* someone does come along and need it:

```c#
[TestCaseSource(x), InconclusiveIfEmpty]
```

Or be able to `Assert.Inconclusive` in the implementation of the TestCaseSource.

**Comment by CharliePoole** [comment]
@jnm2 I wouldn't try to decide any of those things now but wait till they come up. However, my preference would be to keep things simple in terms of what we deliver. Users can easily implement those attributes you suggest if they want them badly enough. We have an incredible backlog of stuff we actually __need__, so I hope we can concentrate on that. 😄 

I should clarify one thing I wrote. If you put [Theory] on a test, then it will remain inconclusive as the result of an empty test case source. However, if it's still inconclusive after __all__ sources have been examined, then the theory (which is a suite) fails. Inconclusive can actually only occur as a final result on a single case, not on the aggregate of all cases.

**Comment by jnm2** [comment]
@CharliePoole That is what I meant by "_if_ someone does come along and need it." 😄

**Comment by rprouse** [comment]
I agree that we should report an error if we don't find the specified test case source, but disagree that if the source returns no items it is an error. As @jnm2 says, the data might be coming from an external source that may occasionally be empty.

I am going to promote this to a bug, but only for the initial reported behaviour.

**Comment by OmicronPersei** [comment]
Looking to pick this up.  I've created a test but I'm not sure if I'm covering the bug or not.  My test looks like this (within TestCaseSourceTests):
```
[Test]
public void TestMethodIsNotRunnableWhenSourceDoesNotExist()
{
	var result = TestBuilder.RunParameterizedMethodSuite(typeof(TestCaseSourceAttributeFixture), "NonExistingSource");
	Assert.AreEqual(result.Children.ToArray()[0].ResultState, ResultState.NotRunnable);
}
```
Basically I'm trying to reference a source that does not exist within `TestCaseSourceAttributeFixture`.  When the test runs, I get an exception thrown at TestBuilder.cs(94): `Assert.Fail("Method not found: " + methodName);`.

Does this mean the test covers the bug because it does not return a `ITestResult` object with a `ResultState.NotRunnable`?  If not, how else should I look at getting this bug under test?  Thanks.

**Comment by CharliePoole** [comment]
You need to verify that the test is marked as NotRunnable in the first place, even before it is run. You should build the suite and look for `RunState.NotRunnable`. That will also give `ResultState.NotRunnable` when the test is run.

The failure from `TestBuilder` is an error in our test utility, not in the production code. It doesn't have to be fixed - just avoided in your test. IOW, don't try to run a non-runnable test.

**Comment by OmicronPersei** [comment]
@CharliePoole, Would we expect an individual test to be marked as `RunState.NotRunnable`, or the returned `TestSuite`?

**Comment by CharliePoole** [comment]
Only the test case that references that missing TestCaseSource. The way it generally works, is that any error in one of the attributes throws an exception. The code that called into the attribute is responsible for changing that error into a not runnable. You can see it happen if you have a TestCaseSource with a method that throws an exception.
