### ISSUE TITLE
NUnit 3.6.1 not working with .NET Framework 4.5.2

### ISSUE THREAD

**Issue by victory4vivek** [nunit/nunit#2063]
Latest version of **NUnit is 3.6.1**. And Microsoft **Visual Studio 2015 uses .NET Framework 4.5.2**. I wrote my first Nunit Test and it failed to run. I had to degrade (switch to a lower version) to .NET Framework 4.5 and it started working. But we do not intend to. Is there a way to use latest .NET Frameworks and write NUnit tests as well

- [ ] Next we are planning to shift to Microsoft Visual Studio 2017 which uses .NET Framework 4.6.2. We want to go with NUnit. Please suggest.

**Comment by CharliePoole** [comment]
NUnit works fine with both VS2015 and. 2017. Please give us a description of the particular problem you ran into so we can help you.

**Comment by victory4vivek** [comment]
@CharliePoole its throwing a **targeting a higher framework** warning. Exact warning are 

> Warning		The primary reference "C:\Users\q812760\Documents\Visual Studio 2015\Projects\FirstConsoleTestApplication1\FirstConsoleTestApplication1\bin\Debug\FirstConsoleTestApplication1.exe" could not be resolved because it was built against the ".NETFramework,Version=v4.6.1" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5".
> 
> Warning		The referenced project 'FirstConsoleTestApplication1' is targeting a higher framework version (4.6.1) than this project’s current target framework version (4.5). This may lead to build failures if types from assemblies outside this project’s target framework are used by any project in the dependency chain.

![nunit target framework higher error](https://cloud.githubusercontent.com/assets/7643221/23461388/bf5c7230-feaf-11e6-8d40-fb7a67f80613.jpg)

I have written a very basic Assert.AreEqual(expected, actual);

**Comment by victory4vivek** [comment]
@CharliePoole pls refer this image. Above image has extra unwanted data

![nunit target framework higher error 2](https://cloud.githubusercontent.com/assets/7643221/23461562/6eb57510-feb0-11e6-977e-533887037b8d.jpg)

**Comment by appel1** [comment]
This has nothing to do with NUnit. The warning is because FirstConsoleTestApplication1 targets 4.6.1 and FirstNUnit.Test1 targets 4.5. You can't reference an assembly targeting a newer framework version. So either change FirstConsoleTestApplication1  to target 4.5 or change FirstNUnit.Test1 to target 4.6.1 depending on your requirements.

**Comment by victory4vivek** [comment]
Thanks @charliepoole and @appel1

Both of you are correct. Got resolved. Thanks a ton.
