### ISSUE TITLE
How to execute nunit test as part of visual studio build

### ISSUE THREAD

**Issue by vpolisetti** [nunit/nunit#2064]
I have one project and added new unitTest project in VS 2015, Am able to debug or execute individual test cases using nunit3 adapter. 

When I build Visual studio how to execute Unit Test project and if any test case fails build should fail. 
How to trigger Nunit project with visual studio 2015 build. 

send me options , Is there any simple properties change required

Thanks,
Gopi

**Comment by CharliePoole** [comment]
The simplest way is to click the "Run Tests After Build" button at the top of the test explorer window.

See http://dailydotnettips.com/2015/06/12/run-tests-after-build-automatically-running-unit-test-after-build-success-in-visual-studio/ which was one of the first items that came up when I googled.

**Comment by vpolisetti** [comment]
In "TestExplorer" we dont have option "Run Tests After Build" that is the reason am asking.

**Comment by rprouse** [comment]
The "Run Tests After Build" is a Visual Studio feature that was removed in Visual Studio 2015 if I remember correctly. I used it when it was first introduced, but it was very buggy and kept locking my test assemblies. Maybe that is why it was removed.

The commercial products Resharper or NCrunch may do this, but I am not sure (pretty sure NCrunch does).

**Comment by jnm2** [comment]
NCrunch is the best. Visual Studio and ReSharper are starting to add live unit testing so we'll see how that goes.

To fail our builds in CI, we use Cake build scripts.

**Comment by CharliePoole** [comment]
My mistake... I was looking at some older docs.

**Comment by ColmBhandal** [comment]
Rob The "Run Tests After Build" is there in VS2019 as far as I can see, but it still seems buggy. Still use the console runner. Thanks!
