### ISSUE TITLE
Test method has non-void return type, but no result is expected /  Wrong number of arguments provided

### ISSUE THREAD

**Issue by NicholasBorod** [nunit/nunit#2067]
Hi Folks, 
Have a big problem with running nunit-console on mono (debian server) tests were written on VS 2015.
On Windows, VS runs perfectly without any problem
NUnit 2.6.4
NUnitTestAdapter.WithFramework 2.0.0
MONO 4.0.0
Code Example below:

TestData code:

> namespace My_Project.DataSource
> {
>     public class My_Data_Class
>     {
>         public static IEnumerable<TestCaseData> SearchFilterData
>         {
>             get
>             {
>              yield return new TestCaseData(
>                     "Some_String_1",
>                     "Some_String_2",
>                     "Some_String_3",
>                     "Some_String_4")
>                     .Returns("success")
>                     .SetCategory("Some_Categorie")
>                     .SetName("Some_Name");
>             }
>        }
>    }
> }

Test code: 

> namespace My_Project
> {
>     public class Some_Test
>     {
>         [Test, TestCaseSource(typeof(My_Data_Class), "SearchFilterData")]
>         public string Search(string text1, string text2, string text3, string text4)
>         {
>              //do something ...
>             return "success";
>         }
>     }
> }

In this case, i receive "Test method has non-void return type, but no result is expected"

If I make Search Method void:   "Wrong number of arguments provided"

Please help.

**Comment by CharliePoole** [comment]
Have you installed NUnit 2.6.4 on Debian are you using what comes in the distro? Please include output from console runner.

**Comment by NicholasBorod** [comment]
It looks like i've resolved this. Mono nunit-console 2.6.3 does not respect NUnit 2.6.4 in project dependency what is natural ... Thanks!
