### ISSUE TITLE
Error with Is Equal To on Mono

### ISSUE THREAD

**Issue by jogibear9988** [nunit/nunit#2069]
I've the following Test:

		public struct TestPoint : IEquatable<TestPoint>
		{
			public double X { get; set; }
			public double Y { get; set; }

			public TestPoint(double x, double y)
				: this()
			{
				X = x;
				Y = y;
			}

			public bool Equals(TestPoint other)
			{
				return X == other.X && Y == other.Y;
			}

			public override bool Equals(object obj)
			{
				return obj is TestPoint && Equals((TestPoint)obj);
			}

			public static bool operator ==(TestPoint x, TestPoint y)
			{
				return x.Equals(y);
			}

			public static bool operator !=(TestPoint x, TestPoint y)
			{
				return !(x == y);
			}

			public override int GetHashCode()
			{
				return X.GetHashCode() ^ Y.GetHashCode();
			}
		}
		[Test]
		public void IsEqualToTest()
		{
			var t1 = (object) new TestPoint(1, 2);
			var t2 = (object)new TestPoint(1, 2);
			if (t1 is TestPoint)
			{
				var p1 = (TestPoint)t1;
				var p2 = (TestPoint)t2;
				Console.WriteLine("p1x:" + p1.X);
				Console.WriteLine("p1x:" + p1.X.ToString("G17"));
				Console.WriteLine("p1y:" + p1.Y);
				Console.WriteLine("p1y:" + p1.Y.ToString("G17"));
				Console.WriteLine("p2x:" + p2.X);
				Console.WriteLine("p2x:" + p2.X.ToString("G17"));
				Console.WriteLine("p2y:" + p2.Y);
				Console.WriteLine("p2y:" + p2.Y.ToString("G17"));
				Console.WriteLine("=" + (p1 == p2));
				Console.WriteLine("=" + (p1.X == p2.X));
				Console.WriteLine("=" + (p1.Y == p2.Y));
				Console.WriteLine("=" + (p1.Equals(p2)));
				Console.WriteLine("=" + (object.Equals(p1, p2)));
				Console.WriteLine("=" + (t1 == t2));
				Console.WriteLine("=" + (t1.Equals(t2)));
				Console.WriteLine("=" + (object.Equals(t1, t2)));
			}
			Assert.That(t1, Is.EqualTo(t2));
		}

wich Results in 

      p1x:1
      p1x:1
      p1y:2
      p1y:2
      p2x:1
      p2x:1
      p2y:2
      p2y:2
      =True
      =True
      =True
      =True
      =True
      =False
      =True
      =True

And Assert works on Windows, but on Mono (4.8, Linux) it throws

(you can see here in my Test results https://s3.amazonaws.com/archive.travis-ci.org/jobs/207275951/log.txt  error 1) at the End of the log)

**Comment by CharliePoole** [comment]
What exception is thrown?

**Comment by jogibear9988** [comment]
No Exception, the Tests fails, because the Assert thinks they are not equal. On Windows it works!

**Comment by jogibear9988** [comment]
Should I put my Code in a Unit Test, so we see if it fails on Travis, but works on Appveyor?

**Comment by CharliePoole** [comment]
That would be helpful as my Linux box is offline. The various console writes aren't needed.

**Comment by jogibear9988** [comment]
https://github.com/nunit/nunit/pull/2070

**Comment by jogibear9988** [comment]
One more Info, we use NUnit 3.2.1.

**Comment by jogibear9988** [comment]
mhmm... seems to work on your travis. I check to update my nuget version

**Comment by jogibear9988** [comment]
I don't see, was my test started on your Travis machine?

**Comment by jogibear9988** [comment]
Also with NUnit 3.6.1 it fails on our Travis machine.

We use NetCore, maybe that has anything todo with the issue?

**Comment by CharliePoole** [comment]
It's working fine on all the platforms we build for, including .NET Standard 1.6.

We don't test specifically under .NET Core. What runner are you using to run your tests and what build of the framework are you referencing?

**Comment by jogibear9988** [comment]
Nunit Net Core Runner 3.4.0

**Comment by rprouse** [comment]
@jogibear9988 there are a few differences in the way that we find `IEquatable` interfaces in .NET Core and PCL because of remoting differences, but we have many `IEquatable` unit tests that run on both Linux and Windows. I don't think the runner itself will make a difference because it is the `NUnitEqualityComparer` in the framework that finds and executes the `IEquatable.Equals` method.

The differences are that some of the reflection methods are extension methods that we wrote because they don't exist in .NET Core or PCL. There could be a bug here, but as I said, we have many `IEquatable` tests that exercise that code, so we are going to have to track down what the difference is for you.

**Comment by CharliePoole** [comment]
So would this be our .NET standard build of the framework?

**Comment by jogibear9988** [comment]
You have my Code, this one is failing on our TravisCi System.

You also see, the comparison fails when the result are boxed structs and compared via ==

**Comment by rprouse** [comment]
It was first reported with 3.2.1, so that would be our portable build.

One difference might be running our PCL or .NET Standard under the CoreCLR vs the full CLR or Mono. Reflection might behave differently.

**Comment by jogibear9988** [comment]
can i help out more? we build this branch https://github.com/jogibear9988/linq2db/tree/linux

our travis config https://github.com/jogibear9988/linq2db/blob/linux/.travis.yml

build.sh https://github.com/jogibear9988/linq2db/blob/linux/build.sh

**Comment by CharliePoole** [comment]
@rprouse Can we add something to our CI script to test under .NET Core?

**Comment by jogibear9988** [comment]
Is there anything I can do now? (I won't like to add a workaround in our unit tests)

**Comment by jogibear9988** [comment]
maybe this is the issue: https://codeblog.jonskeet.uk/2017/10/08/diagnosing-a-linux-only-unit-test-failure/ ?

**Comment by jogibear9988** [comment]
maybe realted: https://github.com/dotnet/coreclr/issues/14391

**Comment by jskeet** [comment]
I wouldn't expect *Mono* to be affected by this bug, but if it's failing on .NET Core 1.0 but working on .NET Core 1.1, that would be suggestive that it's the same problem.

**Comment by rprouse** [comment]
I am closing old confirm issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
