### ISSUE TITLE
Object comparison errors(Expected and actual are both)

### ISSUE THREAD

**Issue by vpolisetti** [nunit/nunit#2071]
Am getting below exception eventhough both the objects has same values.

{"  Expected and actual are both <ClassA>\r\n  Values differ at index [1]\r\n  Expected: <>\r\n  But was:  <>\r\n"}

  ClassA test = GetMatch(cleanedCellText, true);
   ClassA test1 =GetMatch(cleanedCellText, true);
 Assert.AreEqual(test1, test );  // Exception 
 Assert.AreEqual(test, test );  return true

**Comment by rprouse** [comment]
I am assuming that you have not overridden `Equals` in your `ClassA` or implemented `IEquatable<ClassA>`? If you don't do that, they NUnit just does a reference equals (basically, we default to `Object.Equals()`.

A quick way to tell if you have done it right is to try `Assert.IsTrue(test1.Equals(test));`

I am going to close this issue. If I am incorrect in my assumptions, let me know and we can reopen.
