### ISSUE TITLE
Mono AOT and constraints inheriting IConstraint.ApplyTo<TActual> gives errors

### ISSUE THREAD

**Issue by hknielsen** [nunit/nunit#2074]
So when working with platforms that only support AOT, we ran into problems using nunit, because of virtual generic methods. Almost all Assert's use this Constraint hierarchy.

We fixed it on our local fork of nunit. Without a big redesign, the only fix was to change  IConstraint.ApplyTo<TActual> to IConstraint.ApplyTo(object), and boxed the value when applying the test.

Dont know if you guys would accept this solution? Otherwise a new version of nunit should work with mono AOT.

**Comment by CharliePoole** [comment]
I'm only generally familiar with AOT but I thought it was just an option, one you could avoid using for test assemblies. However, your phrase "platforms that only support AOT" suggests I may be missing something!

Can you explain that for me? What platforms support mono but not JIT?

**Comment by hknielsen** [comment]
Most platforms support mono, when using AOT.

http://www.mono-project.com/docs/advanced/aot/#known-limitations
If you depend on the full AOT option because of OS limitations, you should make sure to test your software using the “–full-aot” option to ensure that no dynamic code is used by your application.

I actually dont know the precise platforms, but if you want/need a list I could provide one, with our knowledge.

**Comment by CharliePoole** [comment]
It's enough to just explain your own use case. Why do you use AOT? What platform do you develop on? What platform do you need to test on that doesnt support JIT?

We've had AOT in Mono for a long time, but it always seemed like something that didn't affect me (or NUnit) in the past so I didn't pay much attention. Also, your issue has never come up before, so I'm wondering what exactly you are doing that's different and whether it's a forerunner of more issues to come!

Changing the ApplyTo method to use an object would be a bit of a step backward for us, so I want to have more info before taking that step. Our overall direction for the past few years has been to make everything generic where possible, so as to avoid boxing.

**Comment by hknielsen** [comment]
So the platforms we run mono AOT, and are technical requerement to be full AOT compilation: iOS and most consoles. We also run mono AOT on other platforms, but that is mostly for performance.
Dont know if anybody ran nunit on these platforms? We haven't at least. What we did before was to use the nunit runner on the host machine. Now we actually want the full nunit runtime to get executed on the target device's.

So when going trough the IL code, I actually though of a better solution, that I just tested and I was right, I will make a PR with this. Instead of the nasty boxing hack, ill move the IConstraint interface down to the respective constraints. The problem was mono AOT was trying to find the generic type on the base class, and not on the concrete type we tried to invoke.

**Comment by CharliePoole** [comment]
That sounds better. We probably need to know if this is considered a bug in mono, which they may fix at some point.

**Comment by hknielsen** [comment]
@CharliePoole How do I test nunit properly. Seems like I have errors already from the beginning on the master branch.

**Comment by ChrisMaddock** [comment]
@hknielsen - How are you currently trying to run the tests? 

Using the NUnit adapter doesn't work, I believe. We use a Cake script to run build/tests. You should just be able to do `./build -t Test` in the root directory. See [BUIDING.md](https://github.com/nunit/nunit/blob/master/BUILDING.md) for more details.

**Comment by CharliePoole** [comment]
Like Chris says plus use the nunit_Linux solution on Linux.

**Comment by hknielsen** [comment]
@ChrisMaddock - we have our own fork of nunit and there we used an older version. Havent tried to run the tests on that though.
When building with `./build -t Test` - I get lots of error with ""

**Comment by hknielsen** [comment]
Wups, not what I wanted

**Comment by ChrisMaddock** [comment]
Can you copy and paste the errors you're seeing? 🙂

**Comment by hknielsen** [comment]
Yes thx :) Lot's of errors so only took a snippet:
irectoryAssert.cs(46,10): error CS0246: The type or namespace name 'EditorBrowsable' could not be found (are you missing a using directive or an assembly reference?) [C:\code\unity\TrueNunit\nunit\src\NUnitFr amework\framework\nunit.framework-netstandard.csproj]
DirectoryAssert.cs(46,26): error CS0518: Predefined type 'System.Object' is not defined or imported [C:\code\unity\TrueNunit\nunit\src\NUnitFramework\framework\nunit.framework-netstandard.csproj]
DirectoryAssert.cs(46,26): error CS0103: The name 'EditorBrowsableState' does not exist in the current context [C:\code\unity\TrueNunit\nunit\src\NUnitFramework\framework\nunit.framework-netstandard.csproj]
DirectoryAssert.cs(59,10): error CS0518: Predefined type 'System.Object' is not defined or imported [C:\code\unity\TrueNunit\nunit\src\NUnitFramework\framework\nunit.framework-netstandard.csproj]
DirectoryAssert.cs(59,10): error CS0246: The type or namespace name 'EditorBrowsableAttribute' could not be found (are you missing a using directive or an assembly reference?) [C:\code\unity\TrueNunit\nunit\sr c\NUnitFramework\framework\nunit.framework-netstandard.csproj]
DirectoryAssert.cs(59,10): error CS0246: The type or namespace name 'EditorBrowsable' could not be found (are you missing a using directive or an assembly reference?) [C:\code\unity\TrueNunit\nunit\src\NUnitFr amework\framework\nunit.framework-netstandard.csproj]
DirectoryAssert.cs(59,26): error CS0518: Predefined type 'System.Object' is not defined or imported [C:\code\unity\TrueNunit\nunit\src\NUnitFramework\framework\nunit.framework-netstandard.csproj]
DirectoryAssert.cs(59,26): error CS0103: The name 'EditorBrowsableState' does not exist in the current context [C:\code\unity\TrueNunit\nunit\src\NUnitFramework\framework\nunit.framework-netstandard.csproj]
An error occured when executing task 'BuildNetStandard'.

**Comment by hknielsen** [comment]
On another note, do NUnit support netstandard 2.0?

**Comment by ChrisMaddock** [comment]
That's odd. The .NET standard build should check if the dependencies are installed, and skip the build if not. @rprouse - any ideas?

For now, you may be best just to skip the .NET standard build, which you can do by commenting out lines 621 and 632 of the `build.cake` file. e.g.

```
    // .IsDependentOn("TestNetStandard")
```

> On another note, do NUnit support netstandard 2.0?

Yes, we have a netstandard 1.6 build.  👍

**Comment by CharliePoole** [comment]
@ChrisMaddock I guess you meant "__No__, we have a netstandard 1.6 build." :smile:

**Comment by CharliePoole** [comment]
@hknielsen Tell us about your platform.

**Comment by hknielsen** [comment]
@ChrisMaddock @CharliePoole well 2.0 is a superset of 1.6,so it should work AFAIK. 
WIN10, recently installed vs17 if that could have any influence on the version you are targeting?

**Comment by CharliePoole** [comment]
@hknielsen Yes, a 2.0 can reference us so long as no args passed in to NUnit are unsupported in 1.6.

So, you run mono on windows? FYI, due to the talk of mono, I've been assuming Linux, which is why I suggested you use the linux solution.

**Comment by hknielsen** [comment]
@CharliePoole hehe yeah I figured :) I just used the normal .sln.
Yes, mono on windows. I work at Unity and we support a wide variate of platform, thus Mono.

So trying to fix this AOT error and with the current dependencies, there is no nice was to do it without breaking everything apart. I was really hoping to upstream some changes that could solve the error. Worst case is to only use our own fork build, with the boxing to `object`, but the more we change there, the harder its going to update to newer awesome versions you guys provide with.
So a brief explanation of what the error is:
When overriding generic methods.
```
abstract class Base
{
     public abstract T SomeMethod<T>(T argument);
     public virtualT AnotherMethod<T>(T argument)
     {
          return argument;
     }
}

class Derived : Base
{
     public override T SomeMethod<T>(T argument)
     {
          //some implementation, this will result in an error when called
     }
     public virtualT AnotherMethod<T>(T argument)
     {
          //some implementation, this will result in an error when called
     }
}
```
This is because (As far as I can see) it only partly compiles the generic type, on the Base class. And since it invokes the Base::SomeMethod<T> on the Derived class, T needs to be compiled on both.

The problem in this case, in NUnit, is `ApplyTo<T>` methods.
Fixes could be to remove ApplyTo from the base class and do it with interface on the Derived classes. But that is not that straight forward. Maybe in not just quite familiar with the code base yet, but I cant really see a nice way to do this, without tons of casting.

Any ideas?

**Comment by hknielsen** [comment]
@ChrisMaddock btw, thx. The commenting of NetStandard solved the issue building.

**Comment by ChrisMaddock** [comment]
> @ChrisMaddock btw, thx. The commenting of NetStandard solved the issue building.

Great. 🙂 This should happen automatically however... 👎 

Are you about to share what output you get for the following commands, running them in the root directory?

`dotnet --version`

`dotnet restore`

**Comment by hknielsen** [comment]
> Are you about to share what output you get for the following commands, running them in the root directory?
Yes no problem
```
\nunit [fix-AOT-abstract-generic-method-error]> dotnet --version
1.0.0
```
And for restore:
https://gist.github.com/hknielsen/6c18391c3bfedb3078498fcab535a831

**Comment by ChrisMaddock** [comment]
Thanks...although unfortunately can't say I'm any the wiser! Any ideas from @nunit/net-core-runner-team?

**Comment by hknielsen** [comment]
@CharliePoole a take on the above question?

**Comment by ChrisMaddock** [comment]
@hknielsen - did you ever sort out your .NET Standard build? Someone else has just encountered the same issue here: https://groups.google.com/forum/#!topic/nunit-developer/QmfY2s9As1E

**Comment by rprouse** [comment]
I am closing old confirm issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
