### ISSUE TITLE
CollectionAssert.AreEqual in Nunit3.0

### ISSUE THREAD

**Issue by prasha6** [nunit/nunit#2075]
Hello,

I see that CollectionAssert.AreEqual is deprecated after Nunit2.5.
How do I compare two lists using a user defined "Icomparer" for equality, in Nunit3.0 ? 
Any help is appreciated. Thanks..

**Comment by JustinRChou** [comment]
If I remember correctly,

`Assert.That(list1, Is.Equal.To(list2));`

The docs have this covered.
https://github.com/nunit/docs/wiki/CollectionEquivalentConstraint
