### ISSUE TITLE
Add support for NUnit vs .Net Core projects in VS 2017.

### ISSUE THREAD

**Issue by dmitriyse** [nunit/nunit#2077]
Currently NUnit test adapter works only with .Net Framework 4.0+ projects in VS 2017.
Please add full support for .Net core projects under VS 2017.
xUnit works with .net Core under VS 2017 RC (+ with R#) more than half of a year.
Please do not force our team to switch to xUnit. We will never back again.
P.S. Probably this is duplicate issue.

**Comment by dmitriyse** [comment]
NUnit is the last brick in a puzzle. It's block us from migrating to VS 2017 and C# 7.0.

**Comment by CharliePoole** [comment]
We recognize this as a very important issue. It's being tracked by several issues already, in the nunit3-vs-adapter repository. The framework support (this repo) is already there.

**Comment by dmitriyse** [comment]
Thank you. Glad to hear that NUnit team aware of this problem.
Does nunit3-vs-adapter project have some working developer build ?

**Comment by rprouse** [comment]
We don't have a working developer build yet. First we need a .NET Standard version of our engine which I am working on now. Once that is done, we just need to plug it into the adapter.

To hold you over, you could temporarily make your unit tests self executing with NUnitLite.

**Comment by dmitriyse** [comment]
Unfortunately this solution does not fit to our development workflow. We are hardly depends on ability to run tests solely with debug.

**Comment by dmitriyse** [comment]
VS 2015 + toolset  satisfy us. So we can wait NUnit adoption to VS 2017/Net Standard. But than later we will start migration than more code is to be reworked.

**Comment by JustinRChou** [comment]
@dmitriyse 
How is that migration process?
From what I have looked up, it does seem that you have to recreate the whole project in VS2017 as it doesn't seem to do a project conversion for you?

**Comment by dmitriyse** [comment]
project.json -> *.csproj (2017) is only one of multiple migration activities.
2) Second for us is replacing Task to ValueTask in most part of places
** Other things, that cannot be predicted right now **

**Comment by dmitriyse** [comment]
Hi! How is your progress? Does any preview build is capable to run DotNet Core NUnit tests in VS 2017  ?

**Comment by ChrisMaddock** [comment]
@dmitriyse - It's being worked on at the moment - lots of progress is being made! The two main issues for this are the ones below, I suggest you follow those. I'll close this one as a duplicate.

https://github.com/nunit/nunit-console/issues/10
https://github.com/nunit/nunit3-vs-adapter/issues/297
