### ISSUE TITLE
.NetCore 

### ISSUE THREAD

**Issue by di48l069** [nunit/nunit#2081]
Good day,

Where can I find nunit.framework on nuget for .netcore application?

**Comment by rprouse** [comment]
The NUnit nugget package contains a .NET Standard 1.6 build, just reference NUnit.

Note that if you are using VS 2017 or the new csproj format, our adapter does not run tests for that yet. For now, use NUnitLite to make your tests self executing.

**Comment by di48l069** [comment]
@rprouse Thank you, and thanks for bringing that up I am currently using VS 2017.

> Note that if you are using VS 2017 or the new csproj format, our adapter does not run tests for that yet. For now, use NUnitLite to make your tests self executing.

Is there any plans for above?

**Comment by rprouse** [comment]
We are actively working on supporting .NET Core in VS2017 using the new CSPROJ format. I hope to get it done by mid-April, but no guarantees 😄 

I am going to close this as a question. If you have more questions, feel free to add comments to this issue, we will see them.
