### ISSUE TITLE
AssemblyConfiguration not visible externally

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#2084]
Currently, the compiled configuration (Debug/Release) of the NUnit assemblies is defined in CommonAssemblyInfo.cs, and is specified in an AssemblyConfiguration attribute.

The problem is that the value of the AssemblyConfiguration attribute is not visible in file explorer, so it is difficult to determine what configuration a particular NUnit assemlby has been compiled for.

It would seem useful if the configuration (Debug/Release) was also included in the AssemblyTitle attribute.

All the other relevant configuration info is (.NET version it is compiled for).

**Comment by CharliePoole** [comment]
I can see some marginal benefit for anyone who builds NUnit, but not for general users who only have the release build. Perhaps you could display Debug for debug builds, otherwise leave as is.

**Comment by oznetmaster** [comment]
That is what the CommonAssemblyInfo does in the AssemblyConfiguration attribute for the Debug build.

All I am suggesting is that we do the same for AssemblyTitle attribute

**Comment by CharliePoole** [comment]
Yes, I understand.

**Comment by jnm2** [comment]
I think standard practice is to put it in the product version as build metadata:

```c#
[assembly: AssemblyInformationalVersion("3.6.1+DEBUG")]
```

I've seen this a fair number of times.

**Comment by oznetmaster** [comment]
I am pretty sure that does not show up in  Properties->Details in file explorer?

**Comment by jnm2** [comment]
@oznetmaster It does. `AssemblyInformationalVersion` drives Windows' fileinfo `Product Version` field which Explorer shows in Properties > Details. Been using it for that very purpose for ages.

**Comment by jnm2** [comment]
@nunit/framework-team Is lack of `+DEBUG` in `AssemblyInformationalVersion` causing anyone pain?

**Comment by ChrisMaddock** [comment]
Not personally, although I wouldn't object to merging a PR, if it's an issue for @oznetmaster

**Comment by jnm2** [comment]
I'm happy with that too. :+1: @oznetmaster can I assign you?

**Comment by rprouse** [comment]
Nobody has picked this up and nobody else has asked for this so closing.
