### ISSUE TITLE
No start-test or test-case events on Mac OS X under Mono

### ISSUE THREAD

**Issue by eDyablo** [nunit/nunit#2090]
I made a simple test event listener engine extension that handles <start-test...> and <test-case...> events. Just like  teamcity extension does. It works perfectly on Windows environment. On Mac OS X the engine doesn't send "start-test" and "test-case" reports to OnTestEvent. But it sends other types of events.

**Comment by CharliePoole** [comment]
One thing to check is whether your extension is being recognized at all. Use the console runner with `--list-extensions` to see what is being loaded.

**Comment by eDyablo** [comment]
This is the first thing I tried. I cans ee my extension in the list. And as I said it receives other types of events.

**Comment by CharliePoole** [comment]
Since I don't have a mac, I'll have to ask you to do what I would do step by step...

If you run without the extension, do all your tests execute?
If you run with it, do they execute?
If you put an immediate write inside one of the tests (Console.Error or TestContext.Progress) do you see the corresponding event?

What version of the engine is running?

Charlie

**Comment by CharliePoole** [comment]
Do the events you receive include suite-start and test-suite?

**Comment by eDyablo** [comment]
The events I receive include suite-start and test-suite. And inside the xml I see information about the tests it execute.

**Comment by eDyablo** [comment]
I use nunit-console 3.5 (with engine that comes within the package). I also tried the latest release 3.6.1. The same effect on Windows and Mac.

**Comment by CharliePoole** [comment]
Try with --trace:Error to see if there is any error related to the event listener or event pump. Failing that, use --trace:Debug and lets see if there is any sign at all of a problem. Beyond that, I think you would need to debug NUnit on your machine to get any further.

**Comment by CharliePoole** [comment]
@eDyablo Any further info?

@nunit/framework-team @nunit/core-team Anybody with a mac who wants to look at this?

**Comment by rprouse** [comment]
I am closing since we have not heard back from you. If you have more information, add it to this issue and we will reopen.
