### ISSUE TITLE
Convert Portable library to .NET Standard 1.3

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#2092]
The portable library is .NET Standard 1.3 (or possibly 1.0 or 1.1), but it cannot easily be installed in a .NET Standard 1.3 project. Attempting to do so results in the following error,

```
Restoring packages for C:\src\spikes\NetstandardLibrary\NetstandardLibrary\NetstandardLibrary.csproj...
Package NUnit 3.6.1 is not compatible with netstandard1.3 (.NETStandard,Version=v1.3). Package NUnit 3.6.1 supports:
  - monoandroid (MonoAndroid,Version=v0.0)
  - net20 (.NETFramework,Version=v2.0)
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
  - netstandard1.6 (.NETStandard,Version=v1.6)
  - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
One or more packages are incompatible with .NETStandard,Version=v1.3.
Package restore failed. Rolling back package changes for 'NetstandardLibrary'.
```

If we convert the project to the lowest .NET Standard version it supports instead of PCL, it will still work in all the PCL targets, plus it will work in .NET Standard.

Before we do this, can anyone see any issues with this approach?

**Comment by rprouse** [comment]
I should also state that I don't want to drop the 1.6 version as it adds back in functionality that is not available in the portable library or .NET Standard 1.3. I see them as complimenting each other.

**Comment by CharliePoole** [comment]
Seems like a good way to go.

**Comment by ChrisMaddock** [comment]
Sounds good to me.

**Comment by jnm2** [comment]
I like it. [According to @codito](https://github.com/nunit/nunit3-vs-adapter/issues/297#issuecomment-279120168), `netstandard1.0` is identical to what portable is currently targeting.

**Comment by rprouse** [comment]
@jnm2 I was hoping to target 1.0 if possible, 1.3 if not.

**Comment by jnm2** [comment]
@rprouse That sounds good. Since all the APIs in the portable project's current target are also in `netstandard1.0`, I would not expect a need to go higher.

**Comment by NN---** [comment]
@rprouse What is the latest NUnit version supporting .NET Standard 1.0 ?

**Comment by jnm2** [comment]
@NN--- We supported Profile259 which is equivalent to .NET Standard 1.0 (https://docs.microsoft.com/en-us/dotnet/standard/net-standard#pcl-compatibility) up to and including https://www.nuget.org/packages/NUnit/3.6.1 and then switched to .NET Standard 1.3 in 3.7.

The only use for .NET Standard 1.0-1.3 is if you target the discontinued Windows 8/Windows Phone 8/Windows Phone Silverlight frameworks:
https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support

**Comment by NN---** [comment]
I tried to install 3.6.1 on .NET Standard 1.2 and it didn't work for me.

**Comment by jnm2** [comment]
@NN--- What was the failure message?

**Comment by NN---** [comment]
```
NU1202: Package NUnit 3.5.0 is not compatible with netstandard1.2 (.NETStandard,Version=v1.2). Package NUnit 3.5.0 supports:
  - dotnet (.NETPlatform,Version=v5.0)
  - net20 (.NETFramework,Version=v2.0)
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
  - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
```

**Comment by theraot** [comment]
This is the problem: https://github.com/dotnet/sdk/issues/391

We got it installed with the workaround described there
