### ISSUE TITLE
Decimal arrays are not allowed as TestCase parameters

### ISSUE THREAD

**Issue by arthrp** [nunit/nunit#2100]
```
//Ok
        [TestCase(new double[] { 10, 10, 10 })]
        public void TestDouble(double[] numbers)
        {
            Assert.True(numbers.All(x => x == 0));
        }
//Compilation error
        [TestCase(new decimal[] {10, 10, 10})]
        public void TestDecimal(decimal[] numbers)
        {
            Assert.True(numbers.All(x => x == 0));    
        }
```
Error is "An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type".
 
That's quite strange, since ```new decimal[] { 10, 10, 10 }``` is certainly an array creation expression, isn't it?

Observed in latest version (3.6.1).

**Comment by CharliePoole** [comment]
That message is from the compiler and has nothing to do with NUnit.

C# places extreme limitations on what can be used as an argument to an Attribute construtor. See https://msdn.microsoft.com/en-us/library/86h69zty.aspx

As you can see, decimal is not one of the types permitted.

NUnit helps you with this limitation in two ways:
1. For some types, it does conversion for you. In your case, NUnit will convert the double to decimal, with the limitation that there is no way for you to specify the number of digits after the decimal.
2. You an use `TestCaseSourceAttribute` and return any types you like as arguments.

**Comment by arthrp** [comment]
Yeah, should've done a bit more research before filing this. Thanks for explanation.
