### ISSUE TITLE
NUnitLite: show detailed information about type failed to load

### ISSUE THREAD

**Issue by xplicit** [nunit/nunit#2116]
We are migrating [ServiceStack.Text](http://github.com/ServiceStack/ServiceStack.Text) to new *.csproj format. We changed projects to new format, all compile well, but when I try to run NUnitLite using command `dotnet run -f netcoreapp1.1 -- -v --trace=Verbose` I've got a message:

`Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.`

It's possible that during migrating we lost some required reference, but to know what is wrong need to see original exception at least. Currently NUnitLite does not show this information, I've got only this cryptic text (version 3.6.1 shows the same info, I tried with 3.5.0 - no info at all, 3.6.0 and 3.6.1 - same output)

```
NUnitLite 3.6.0 (NetStandard 1.6)
Copyright (C) 2017 Charlie Poole

Runtime Environment
   OS Version: Linux 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017
  CLR Version: .NET Core 4.6.25009.03

Test Files
    /home/sergey/Projects/ServiceStack/windows/ServiceStack.Text/tests/ServiceStack.Text.Tests/bin/Debug/netcoreapp1.1/ServiceStack.Text.Tests.dll

Errors, Failures and Warnings

1) Invalid : /home/sergey/Projects/ServiceStack/windows/ServiceStack.Text/tests/ServiceStack.Text.Tests/bin/Debug/netcoreapp1.1/ServiceStack.Text.Tests.dll
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

Run Settings
    Work Directory: /home/sergey/Projects/ServiceStack/windows/ServiceStack.Text/tests/ServiceStack.Text.Tests
    Internal Trace: Verbose

Test Run Summary
  Overall result: Failed
  Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2017-04-08 12:29:54Z
    End time: 2017-04-08 12:29:54Z
    Duration: 0.006 seconds
``` 

I saw that there was commit https://github.com/nunit/nunit/commit/caa1ec6112cc82ac894eda4eb2b1e189c5609479 which should fix that behaviour, but I still don't see detailed info. 

Unfortunatelly enabling "catch all exception" in debugger does not help to catch this exception, so I can't catch it during debug session.

So I would like to add some debugging info into source and try to change [this line](https://github.com/nunit/nunit/commit/caa1ec6112cc82ac894eda4eb2b1e189c5609479#diff-a2f07fbf87af197e37f7d7e593a8d716R80)
 to `true`,

but when I tried to compile netstandard build of NUnit I've got alot of error messages (#2111)

**Comment by rprouse** [comment]
Did you manage to fix this by debugging your tests? Even though your issue is likely .NET Core related, I agree that we should provide more information about type load failures to make them easier to diagnose, so I am going to promote this to an enhancement.

**Comment by xplicit** [comment]
I was able to resolve it. It's a weird new feature of .NET Core SDK 1.0.2. It does not support referencing dlls which works without issues on previous SDK version. Now `dotnet run` shows "File not found" error message if csproj references dlls. So I had to workaround this issue: partially by wrapping some references into package, partially by editing generated during the build `deps.json` file. Now I can run `nunitlite` and waiting when `nunit` will be available for csproj file.
   This feature would be very useful because new version of dotnet SDK is a hell and very hard to use: dotnet cli does not work in a lot amount of use cases, most of the time it generates "file not found" exception or "type could not be loaded"  so with detailed information it's much easier to fix the issues.

**Comment by ChrisMaddock** [comment]
I did the previous 'fix' to this. I suspect that where you particular exception is being thrown, NUnit is just recording the exception message, and not passing it through `ExceptionHelper.BuildFriendlyMessage(ex)`. I previously changed all the relevant places I could find, but no doubt there's more that I've missed.

@xplicit - if you're able to debug, and work out exactly where the exception message is being written, it would be good to get that fix in.

**Comment by jnm2** [comment]
@rprouse this is marked easyfix but I'm not sure I understand what work needs to be done or how to do it. Can you review whether this issue should have easyfix and/or up-for-grabs?

**Comment by ChrisMaddock** [comment]
From a quick look, I don't think this is easyfix - I'm not sure we even have enough information to pinpoint the error.

The line @xplicit wants to change would just change the message to:

```
1) Invalid : /home/sergey/Projects/ServiceStack/windows/ServiceStack.Text/tests/ServiceStack.Text.Tests/bin/Debug/netcoreapp1.1/ServiceStack.Text.Tests.dll
ReflectionTypeLoadException : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
```

Notice there's `BuildMessage()` and `BuildFriendlyMessage()` - which were put in to maintain backwards compat with how the error messages were previously formatted.  The key point here, is that both these methods go through https://github.com/nunit/nunit/commit/caa1ec6112cc82ac894eda4eb2b1e189c5609479#diff-a2f07fbf87af197e37f7d7e593a8d716R166 - which is the bit that retrieves the LoaderExceptions property.

My guess is that wherever @xplicit's reflection error is being thrown from, isn't even being fed through ExceptionHelper. The fix, I think, would be to find out where that exception is being logged, and run it through ExceptionHelper before writing it to the xml.

I'm not sure we have sufficient info to be able to do that right now. @xplicit - if you were able to debug and trackdown where that exception was being thrown, that would be really helpful.

**Comment by CharliePoole** [comment]
This also relates to a comment I just made on another issue. The framework is not supposed to let out any exceptions, so they should all be trapped and displayed in a very exceptional way by the engine. That ought to be in the driver if it's a named exception from the particular framework. But there also should be something in the direct runner that takes any left-over exceptions and creates a very complete message for them.

**Comment by xplicit** [comment]
@ChrisMaddock I can describe how you can reproduce the issue to debug it. 

1. Create .NET Core console project and reference NUnitLite
2. Create .NET Core library project and build it.
3. From project 1 reference project 2 as `dll` `<Reference Include="../lib/library.dll">`. It's important to reference it as dll, not as C# project.
4. Run unit test. You will get this error message.

All of these steps must be made on .NET Core 1.1 with csproj format. (I used .NET Core SDK 1.0.4). In .NET Core 2.0 the bug with referencing libraries is fixed.

It was difficult for me to track down and debug this issue in nunit because I was unable to reference nunit dlls due to this bug in .NET Core and setting up and build nuget packages to reference them from the code on each small debug change was too time consuming.

**Comment by ChrisMaddock** [comment]
Thanks @xplicit. This isn't something I have time to look at right now, but at least the information's here, for when someone does. 😄

**Comment by rprouse** [comment]
No progress since 2017, closing.
