### ISSUE TITLE
nunit-agent.exe extra new line characters

### ISSUE THREAD

**Issue by Deadpowerful** [nunit/nunit#2120]
When upgrading from NUnit Framework version 3.2.1.0 to 3.6.1.0, running nunit from the command line nunit-agent.exe outputs information from IdentityServer on one line per character.  

The message:
nunit-agent.exe Warning: 0 : [Thinktecture.IdentityServer.Core.Configuration.IdentityServerServiceFactory]: 12/04/2017 13:49:58 +00:00 -- ConsentStore not configured - falling back to InMemory

Becomes:
nunit-agent.exe Warning: 0 : 
[
T
h
i
n
k
t
e
c
t
u
r
e

etc.

I am unsure if this is related to the formatting from IdentityServer or NUnit. 

Thanks,

**Comment by CharliePoole** [comment]
This duplicates nunit/nunit-console#72 for the console runner and #1819 for nunitlite. See especially the comment on #1819 that explains what is happening.
