### ISSUE TITLE
Chained PropertyConstraint constraints report incorrect ActualValue

### ISSUE THREAD

**Issue by erica-kretsch** [nunit/nunit#2121]
When a constraint includes multiple `.Property()` calls, the actual value portion of any error message indicates the value of the first property rather than the value being compared.

In the top portion of the following example, the `ActualValue` property is set to `3`. However, the `ActualValue` property in the bottom portion is set to the anonymous type in the property `Foo`, resulting in less useful messages in the various test runners.

```CSharp
var inputObject = new { Foo = new { Bar = "Baz" } };

// Single property
var result = ((IResolveConstraint)Has
    .Length.EqualTo(3))
    .Resolve()
    .ApplyTo(inputObject.Foo.Bar);

Console.WriteLine("Expected: " + result.Description);
Console.WriteLine("Actual: " + result.ActualValue);

Console.WriteLine();

// Nested property
result = ((IResolveConstraint)Has
    .Property("Foo").Property("Bar").Length.EqualTo(3))
    .Resolve()
    .ApplyTo(inputObject);

Console.WriteLine("Expected: " + result.Description);
Console.WriteLine("Actual: " + result.ActualValue);
```

This issue was introduced November 17, 2012 as part of a [refactoring effort](https://github.com/nunit/nunit/commit/29bac2be2e8e44206fce00da75ab2ad6ceb593f0). The previous functionality could be restored by returning the `ActualValue` supplied by the `BaseConstraint` instead of the value of the property.

**Comment by CharliePoole** [comment]
The thing is, this expression...

```C#
Has.Property("Foo").Property("Bar").Length.EqualTo(3))
```

Has two reasonable (to humans) interpretations:

1. The actual value has a property Foo, which in turn has a property Bar, which in turn has a property Length equal to 3.
2. The actual value has a property Foo, another property Bar, and a third property Length equal to 3.

I'll have to dig in the code to be sure, but I'm pretty sure we implemented it in the second meaning.

This is preliminary... I'll look further.

**Comment by CharliePoole** [comment]
BTW, use the ToString() of a constraint to see a text representation of how it is interpreted.

**Comment by CharliePoole** [comment]
I verified the error as you describe it. The root of the problem is that PropertyConstraint has some special semantics not associated with other constraints: it changes the actual value used by any following constraints. A few others (e.g. AttributeConstraint) also do this and they should all probably use a derived ConstraintResult that recognizes this.

However, I find that the following change in the code for PropertyConstraint works for the simple nesting cases:

```C#
            var baseResult = BaseConstraint.ApplyTo(propValue);
            return new ConstraintResult(this, baseResult.ActualValue, baseResult.IsSuccess);
```
