### ISSUE TITLE
TestContext static values broken by some tests

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#2122]
This may be only a NUnit testing affectation, but TestContext was changed to use an internal static value for DefaultWorkDirectory, 

This is set correctly for normal testing. 

However, there are three NUnit tests: TestAssemblyRunnerTests, ActiuonAttributeTests, and SetUpFixtureTests, which  create a new DefaultTestAssemblyBuilder as part of their tests.  In doing so, the static value of DefaultWorkDirectory is changed to its default value (Directory.GetCurrentDirectory) because  the real options are not passed to these testing instances.

Any subsequent test which relies on TestContext.WorkDirectory to be correct (such as TestCaseSourceCanAccessWorkDirectory) is now broken.

Any test which modifies the static values in TestContext by instantiating DefaultTestAssemblyBuilder must save and restore those values.  Perhaps TestContext needs an internal Save/Restore capability for use during testing?

**Comment by oznetmaster** [comment]
This also breaks all of the TestParameterTests, for the same reason.

**Comment by oznetmaster** [comment]
I do not understand how the NUnit framework tests ever pass CI with this bug.

Although, its success or failure is totally dependent on the order in which the test in the suite are run.

**Comment by oznetmaster** [comment]
Ping on this issue.  I cannot get a clean framework test because of this.

**Comment by rprouse** [comment]
Are the tests failing for you building and running the tests from the master branch or in your port? How are you running the tests?

I'm not saying this isn't an issue and you are likely correct that it is test order dependent, but I am trying to understand why nobody else is seeing this.

**Comment by oznetmaster** [comment]
It happens on my computer on the master branch.  That was how I found it.  Running all tests it shows up only in the NET 3.5 build.

Not sure why, since it could show up in any build on any platform.

**Comment by CharliePoole** [comment]
I imagine the CI tests pass because we don't use the --work option anywhere.

As you know, I used a static so that we could get some value when no test context exists, as when folks tr to access it during the discovery of tests. Any other solution, for example maintaining a discovery context in addition to an execution context, seemed overly complex.

An alternative to save/restore may be that we only set the value if it is not already set.

IF we do allow it to be changed by the tests, then those fixtures should not be run in parallel.

Given that this is blocking for you, do you want to assign it to yourself and do a PR?

**Comment by oznetmaster** [comment]
I do not use the --work option anywhere either, so I am not sure why the difference :(

It is becoming difficult for me to actually submit and test PRs, since I do not usually maintain a full NUnit build environment any more.  All my work is done in VS2008 because of CF.

I can only do a PR by making the changes in the CF version, testing them there, and then manually making them in a branch, and letting CI do the testing for me.

I am not sure this is a desirable process?

**Comment by CharliePoole** [comment]
I see, that sounds like a lot of extra work.

Can you post the message you get? Is it just that the tests fail?

**Comment by oznetmaster** [comment]
Just the test fails.

The reason is pretty obvious if you look at the code.

Other tests will fail if the "only set it if it is not already set" option is used.

It needs to be saved and restored in tests that change it.

I think only the tests are affected, not the framework.

**Comment by CharliePoole** [comment]
In that case, somebody will have to fix it by saving and restoring the value and putting [NonParallelizable] on each of those fixtures.

**Comment by rprouse** [comment]
Nobody has picked this up and nobody else has asked for this so closing.
