### ISSUE TITLE
Make NUnit.Framework.Internal.Test/TestFixture internal

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#2156]
I'm continuously selecting the wrong one of these from Intellisense - when I actually wanted NUnit.Framework.TestAttribute.

Do they need to be exposed, or can we make them internal? Would users ever have need to create these manually?

**Comment by CharliePoole** [comment]
See #1426 for the issue in general.

So, who is the user in this case?

Someone using NUnit to write tests would not have a 'using' statement for the Internal namespace. Does Intellisense now list Types in an unprecedented namespace?

OTOH, a user writing a custom test type would possibly need those Types and would have such a statement.

**Comment by ChrisMaddock** [comment]
I'm the user, and I keep getting the wrong namespace imported from autocomplete. 😄

When I start typing the attribute, I get autocomplete like this:

**Comment by tom-dudley** [comment]
@ChrisMaddock If this is with ReSharper, you can use a [custom filter](https://www.jetbrains.com/help/resharper/2017.1/Using_Filters_in_Code_Completion.html)

**Comment by MaceWindu** [comment]
You should apply EditorBrowsable attribute to members you want to hide from intellisense

**Comment by CharliePoole** [comment]
I'd still like to understand the issue better. Are you seeing this when working on NUnit or in your normal work @ChrisMaddock ? Our past view was that we as dev could deal with the inconvenience, but we want to avoid it for our users.

BTW I've never gotten a display like that, which is part of why I'm digging for more info.

**Comment by ChrisMaddock** [comment]
@CharliePoole - This is as a 'user of NUnit', not working on NUnit. When I start typing TestFixture I see both options - I presumed this was standard Intellisense behaviour, as they're both public types - but maybe it is something specific to ReSharper?

@MaceWindu - if these internal classes have their uses, I'm not sure we do want to hide them from Intellisense? Or maybe we should anyway - as my use case is the 99%, compared to writing custom test types.

@tom-dudley Perfect! 😄 Didn't know they existed, thank you!

**Comment by jnm2** [comment]
It's ReSharper. I see it all the time and usually ignore it, but a few times I was moving too fast and ended up with the wrong using directives without realizing it. That was funny. :D

**Comment by CharliePoole** [comment]
That reassures me - it seems that our existing strategy works for standard Intellisense  and for those who use R# there is a way to prevent this happening. Personally, I don't want my IDE to make a lot of suggestions, particularly when it comes to adding using statements.

**Comment by ChrisMaddock** [comment]
I'll close this, sorry - didn't realise it was just ReSharper.

@CharliePoole - what is out 'existing strategy' you mention? I may file a bug report for resharper, if it's relevant.
