### ISSUE TITLE
Getting WorkerId inside Assert.Throws / DoesNotThrow returns null instead of previous non-null value

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#2157]
@jtomkiew-ITM commented on [Tue May 09 2017](https://github.com/nunit/docs/issues/190)

In NUnit versions 3.6.0 and 3.6.1 this test fails:

```cs
[Test]
public void GetWorkerIdTest()
{
    var workerId = NUnit.Framework.TestContext.CurrentContext.WorkerId;
    Assert.That(workerId, Is.Not.Null);

    Assert.That(NUnit.Framework.TestContext.CurrentContext.WorkerId, Is.EqualTo(workerId));

    Assert.DoesNotThrow(() =>
    {
        Assert.That(NUnit.Framework.TestContext.CurrentContext.WorkerId, Is.EqualTo(workerId));
    });
}
```

Result:

```
Expected: No Exception to be thrown
But was:  <NUnit.Framework.AssertionException:   Expected: "Worker#2"
But was:  null
```

The assembly has set `Parallelizable(ParallelScope.Fixtures)`.

In previous versions (3.4.1 and 3.5.0) this test passes.

---

@CharliePoole commented on [Tue May 09 2017](https://github.com/nunit/docs/issues/190#issuecomment-300234273)

I'm not clear about the purpose of this test. It appears that the first two asserts pass correctly. The second seems to fail because of the nested Asserts. The isolated execution context created by Assert.DoesNotThrow is apparently not populating the TestWorker field. 

This is a bug, but unless you have a strong motivator for why you want it to work, it's quite low priority.

**Comment by CharliePoole** [comment]
Moved from nunit/docs#190

**Comment by jtomkiew-ITM** [comment]
> I'm not clear about the purpose of this test.

We are using WorkerId to differentiate between parallel tests contexts which makes it not work when we use Assert.Throws (3.6.0+).

> This is a bug, but unless you have a strong motivator for why you want it to work, it's quite low priority

We can stick to version 3.5.0 for the time being.

**Comment by CharliePoole** [comment]
Note that you can continue to rely on the value unless you try to retrieve it in code run under by Throws.

**Comment by rprouse** [comment]
@CharliePoole I think this was closed incorrectly by your build matrix PR. Is that correct?

**Comment by CharliePoole** [comment]
No, that was intentional... see https://github.com/nunit/nunit/pull/2164/files#diff-11a1802be2fa3b7e8bb8b478b2f00c99R503
