### ISSUE TITLE
Trying to install NUnit 3.6.1 on .NET Framework asks for download of 20 more packages

### ISSUE THREAD

**Issue by Jivko1212** [nunit/nunit#2165]
I can install NUnit on .Net Framework 4.6.1 without a problem but when I try to install it via Nuget on the newly released 4.7 it asks for these packages:
![capture](https://cloud.githubusercontent.com/assets/25863991/26025879/a69c0552-37f9-11e7-83f0-460bf05f4909.JPG)

And this is only half of the list

**Comment by rprouse** [comment]
It looks like when you target 4.7 that NuGet decides to reference the .NET Standard version of NUnit rather than the .NET 4.5 version. Technically both are correct, but I would think the .NET 4.5 would be more correct.

A fix would be to put a copy of the .NET 4.5 assembly in a `net47` directory in the NuGet package. We might also be able to put a .props file in the `net47` directory that points to the DLL in the `net45` directory.

When we fix this, we should also check .NET 4.6.2 and even 4.6.1 when included from the new CSPROJ format.

Speaking of, @Jivko1212, is your .NET 4.7 project using the new CSPROJ format?

**Comment by CharliePoole** [comment]
On a slightly related note, see nunit/dotnet-test-nunit#118

**Comment by Caleb9** [comment]
> Speaking of, @Jivko1212, is your .NET 4.7 project using the new CSPROJ format?

@rprouse I'm suffering from the same issue and yes, it's CSPROJ format.

**Comment by rprouse** [comment]
@Caleb9 is it the new style 'csproj' introduced in 2017 that doesn't include any of the `cs` files, like the project file at the end of [this blog post](http://www.alteridem.net/2017/05/04/test-net-core-nunit-vs2017/)?

**Comment by Caleb9** [comment]
@rprouse I don't think so. I'm developing in VS 2017 but the project was created still in 2015 and it does contain some `<Compile Include="Properties\AssemblyInfo.cs" />` etc. references. The top of the file looks like this
```
<?xml version="1.0" encoding="utf-8"?>                                                                               ﻿
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{2FC5A3A7-A9CF-4392-AC36-1C11A71BCF45}</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>Test.Unit.Project</RootNamespace>
    <AssemblyName>Test.Unit.Project</AssemblyName>
    <TargetFrameworkVersion>v4.7</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <ProjectTypeGuids>{3AC096D0-A1C2-E12C-1390-A8335801FDAB};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>   <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">10.0</VisualStudioVersion>
    <VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>rogramFiles)\Common Files\microsoft shared\VSTT\$(VisualStudioVersion)\UITestExtensionPackages</ReferencePath>est>False</IsCodedUITest>
    <TestProjectType>UnitTest</TestProjectType>
    <TargetFrameworkProfile />
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
```
so I'm guessing it's the old style?

**Comment by rprouse** [comment]
Yup, that's old style, thanks. I will perform some tests and create a fix. I will likely wait until the .NET Standard pull request is merged otherwise there will be conflicts in the NuGet file and I also want to see how .NET Standard 1.3 behaves.

**Comment by rprouse** [comment]
Test Target | NUnit Reference | Pulls in Extra NuGet References
------------ | ------------------ | ----------------------------------
4.5.2 | 4.5 | No
4.6 | 4.5 | Yes
4.6.2 | 4.5 | Yes
4.7 | 4.5 | Yes

I created test projects targeting the above framework and referenced NUnit. Looking in the project files, they all correctly target the .NET 4.5 version of the framework, but .NET 4.6 and above project pull in all the extra dependencies.

I then tried to install another similar NuGet package and it did not display the same behaviour. The only difference I see is that theirs explicitly states no-dependencies for the .NET 4.5 and other frameworks, where we don't say anything. I am testing that hypothesis...

**Comment by rprouse** [comment]
Adding empty dependencies groups does fix the issue. I am working on the .NET Standard branch because the Nuspec files is changed too much to not conflict, so I will include the fix for this in that PR.

The dependencies in the nuspec now look like this,

```xml
    <dependencies>
      <group targetFramework="net20" />
      <group targetFramework="net35" />
      <group targetFramework="net40" />
      <group targetFramework="net45" />
      <group targetFramework="netstandard1.3">
        <dependency id="NETStandard.Library" version="1.6.0" />
        <dependency id="System.Threading.Thread" version="4.3.0" />
      </group>
      <group targetFramework="netstandard1.6">
        <dependency id="NETStandard.Library" version="1.6.0" />
        <dependency id="System.Runtime.Loader" version="4.3.0" />
        <dependency id="System.Threading.Thread" version="4.3.0" />
      </group>
    </dependencies>
```

**Comment by Jivko1212** [comment]
Just wanted to add that I am able to install NUnit on 4.6.1 without pulling extra dependencies. I had a similar issue with NSubstitute and though that this is due to the following table:

https://docs.microsoft.com/en-us/dotnet/articles/standard/library

it says here that 4.6.1 supports .NET Standard up to 2.0, while 4.6.2 doesn't.

**Comment by jnm2** [comment]
@Jivko1212 Oh boy, they keep having to clarify that chart. net462 is a superset of net461. Because net461 supports netstandard20, net462 supports netstandard20 as well. That chart is listing the *minimum* version supporting, not the *maximum* version. The change from ".NET Framework (with tooling 1.0)" to ".NET Framework (with tooling 2.0)" actually made .NET Framework more compatible earlier.

**Comment by jnm2** [comment]
@Jivko1212 Another way to look at it:

| .NET Standard                     | [1.0] | [1.1]  | [1.2] | [1.3] | [1.4] | [1.5]  | [1.6]  | [2.0] |
|-----------------------------------|-------|--------|-------|-------|-------|--------|--------|-------|
| .NET Framework (with tooling 1.0) | 4.5, 4.5.1, 4.5.2, 4.6, 4.6.1, 4.6.2, 4.7, vNext | 4.5, 4.5.1, 4.5.2, 4.6, 4.6.1, 4.6.2, 4.7, vNext | 4.5.1, 4.5.2, 4.6, 4.6.1, 4.6.2, 4.7, vNext | 4.6, 4.6.1, 4.6.2, 4.7, vNext | 4.6.1, 4.6.2, 4.7, vNext | 4.6.2, 4.7, vNext | vNext | 4.6.1, 4.6.2, 4.7, vNext |
| .NET Framework (with tooling 2.0) | 4.5, 4.5.1, 4.5.2, 4.6, 4.6.1, 4.6.2, 4.7, vNext | 4.5, 4.5.1, 4.5.2, 4.6, 4.6.1, 4.6.2, 4.7, vNext | 4.5.1, 4.5.2, 4.6, 4.6.1, 4.6.2, 4.7, vNext | 4.6, 4.6.1, 4.6.2, 4.7, vNext | 4.6.1, 4.6.2, 4.7, vNext | 4.6.1, 4.6.2, 4.7, vNext | 4.6.1, 4.6.2, 4.7, vNext | 4.6.1, 4.6.2, 4.7, vNext |

[1.0]: https://github.com/dotnet/standard/blob/master/docs/versions/netstandard1.0.md
[1.1]: https://github.com/dotnet/standard/blob/master/docs/versions/netstandard1.1.md
[1.2]: https://github.com/dotnet/standard/blob/master/docs/versions/netstandard1.2.md
[1.3]: https://github.com/dotnet/standard/blob/master/docs/versions/netstandard1.3.md
[1.4]: https://github.com/dotnet/standard/blob/master/docs/versions/netstandard1.4.md
[1.5]: https://github.com/dotnet/standard/blob/master/docs/versions/netstandard1.5.md
[1.6]: https://github.com/dotnet/standard/blob/master/docs/versions/netstandard1.6.md
[2.0]: https://github.com/dotnet/standard/blob/master/docs/versions/netstandard2.0.md

**Comment by Jivko1212** [comment]
Hi thanks for the much better chart .. it is strange though that both NUnit and NSubstitute work perfectly on 4.6.1 but ask to download ton of packages on 4.6.2 .. no idea why .. this is the reason I am developing on 4.6.1 as opposed to 4.6.2 and 4.7 now

**Comment by jnm2** [comment]
It looks like @rprouse [figured out](https://github.com/nunit/nunit/issues/2165#issuecomment-302567880) what was causing it.

Looks like NuGet uses the best matching target framework dependency group. Without the empty groups, net452 and earlier cannot match any dependency group and have no extra packages, but net46 - net47 match the `netstandard1.3` group and that is the only group they could match.

Now with the empty groups, net46 - net47 match the all the groups `net20`, `net35`, `net40`, `net45` and `netstandard1.3` instead of just `netstandard1.3`, and NuGet selects `net45` as the closest match out of the bunch.

**Comment by rprouse** [comment]
@Jivko1212 I saw 4.6.2 causing problems because I was using an updated version of NUnit that includes dependencies for .NET Standard 1.3. The released version only has dependencies for .NET Standard 1.6.

**Comment by jnm2** [comment]
Oh, I left out the fact that net461 - net47 also match the `netstandard1.6` group. But if `net45` is present that is the better match.
