### ISSUE TITLE
New icon for the 3.0 release

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#217]
The current NUnit icon is looking a bit dated. Should we create a new icon for v3 to help distinguish it from v2, especially in NuGet?

![NUnit Icon](http://nunit.org/nuget/nunit_32x32.png)

I'm not the greatest graphics artist, but I am willing to put on my pointy hat and give it a try :smile: 

While we are at it, we should also update the NUnit Organization icon on GitHub to help brand the project.

**Comment by CharliePoole** [comment]
@rprouse Seems like this is actually done isn't it?

**Comment by rprouse** [comment]
@charliepoole, yes, this is probably done now. The green icon is now our official icon and I guess the tri-color ocon can be used for other collateral like on the website. Would you like me to make an announcement on the list like you mentioned above?

**Comment by CharliePoole** [comment]
Please do.
