### ISSUE TITLE
Remove PreTestAttribute and PostTestAttribute

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#2173]
In the same file as `SetUpAttribute`, there is `PreTestAttribute` and `PostTestAttribute`. I'd never heard of them before, so went digging to try and find out what they did. 

The xmldocs are copy and pasted the same as `SetUpAttribute`, so likely incorrect. I couldn't find any reference in our main docs, or any usage in the code base, so I'm assuming they are also currently no-ops.

Are they historical? Were they designed to be inherited from? Can they be removed?

https://github.com/nunit/nunit/blob/65f0b974cb65a6588a54de96f0ce929f57e39f59/src/NUnitFramework/framework/Attributes/SetUpAttribute.cs

**Comment by CharliePoole** [comment]
See issue #49. 

The code slipped into master all by itself. 😸 Feel free to remove.

**Comment by ChrisMaddock** [comment]
Great, thanks.

If someone else picks this up before I do, note the attributes are also listed in AttributeHierachy.txt, and should be removed from there.
