### ISSUE TITLE
Question about polling and DelayedConstraint

### ISSUE THREAD

**Issue by savitskiyvm** [nunit/nunit#2175]
Excuse me for my English.

Hi, i have a question about one behavior in DelayedConstraint, that i could not implement.

I would like to refactor my testing framework for one product to use constraints instead of assertions for better code reuse such as using your class for polling some events, instead of our functions, but i had some trouble. 

I test some transactions in a system that can run, can be finished and have a result (succeed or fail). I start a transaction and run an
Assert.That(() => transaction.GetState(), (Transaction.HasState(Finished) & Transaction.Result.IsSucceed).After(Timout, Polling));

But, when transaction state is finished, transaction has result succeed or fail and this result could not change after it set (it could be set after finish, some time of execution, transaction is finished, but result is not set, so i need to poll result after transaction is finished).

But if transaction result is not success, and DelayedConstraint fails, it continue polling, so if test fails, it really continues until timeout, but not until it really can determine that condition after test is false.

So, I have a three possible states of test:

1. transaction is not finished and result is not set - DC checks if it is finished and has specific result as i whant to
2. transaction is finished and result is set - DC continues polling as I whant to
3. transaction is finished and unexpected result is set - DC continues polling.

Is it possible to determine third case and check if i _have result, but it is unexpected_  to stop polling and return (as in the case when a test pass)? And case when i not have result?

As far as I see, DC use only binary logic to check if it fail or pass, so when result is not present, I must to return false from my custom Constraint.

**Comment by CharliePoole** [comment]
DelayedConstraint was written a long time ago and could really use an overhaul!

However, there may be a simple solution to your problem. I'm not looking at the code right now, but this is what I think is happening...

You are combining two constraints using the & operator. The second constraint is a delayed constraint, but the first is not. You want a timeout to apply to the first operation. I think one or more of the following will work for you:

```C#
// Option 1
Assert.That(() => transaction.GetState(), Transaction.HasState(Finished).After(Timeout, Polling));
Assert.That(Transaction.Result.IsSucceed));

// Option 2
Assert.That(() => transaction.GetState(), (Transaction.HasState(Finished). After(Timeout, Polling) & Transaction.Result.IsSucceed));
```

You may need to adjust this - I am not sure what `Transaction` does, but I am assuming it's a static class that generates constraints, similar to `Is`.

I think the first option is the easiest to read. A third option would be to make use of `.And.` rather than `&` but I wasn't sure how your `Transaction` class would play in that situation.

If neither of these work, we probably need to make some changes to `DelayedConstraint`.

**Comment by savitskiyvm** [comment]
The Transaction is a business-logic class of an application that I test, I can access to it with an API, so it is just set of operation, that executed by my application

In my code I tried the second approach:
```
Assert.That(()` => transaction.GetState(), (Transaction.HasState(Finished). After(Timeout, Polling) & Transaction.Result.IsSucceed));
```

When I use this, assert for some reason polls transaction only once and than fails. If i start test in debug, of course, Transaction finishes, and full constraint succeeds.

Also, I would like to use DelayedConstraint to make all our tests to be time-limited, because i did not found better solution, to create some testing API for my colleagues.
Something like:

```
public void ShouldFinishWith(Transaction tran, Constraint cons)
{
    if( !(cons is DelayedConstraint) )
    {
        cons = new DelayedConstraint(cons, Polling, Timeout);
    }
    Assert.That( () => /*...*/, cons); 
}
```

If we need some special tests, that need a lot of time or different polling, we can pass to method like this a special delayed constraint, but if we not need to some special time configuration, the default timeout and polling interval will be used.

So, in this case, method that checks a busyness logic will look like this

```
Transaction tr = Transaction.Start();
tr.ShouldFinishedWith(Transaction.HasState(Finished) & Transaction.Result.IsSucceed);`
or
Transaction tr = Transaction.Start();
tr.ShouldFinishedWith( (Transaction.HasState(Cancelled) & Transaction.Result.Timeout).After(Timeout));
```

I think it could be very useful in some tests, like testing timeouts, because I do not need polling at all, just check that transaction is not running in specific time interval.

So, I suppose, create my own class that i can use as a DelayedConstraint to create time-limited polling and flexible configuration is better solution?

**Comment by savitskiyvm** [comment]
Sorry, I was not correct about your words
>I am not sure what Transaction does, but I am assuming it's a static class that generates constraints, similar to Is.

Yes, in my first example of code it just syntax helper, that checks a state of "real" busyness-logic class that represents a transaction of application that I test. I tried post only code, related to asserts, so it could be some conflicts of names, in real code used both syntax-helper Transaction class and class from application.

**Comment by CharliePoole** [comment]
OK, I assumed too much. If Transaction is just a business logic class, you are probably calling...

    Assert.That(object actual, book condition);

The actual value is immediately resolved and can never change. 

I don't understand how Polling is accepted syntactically, however.

I'm on my phone now but I'll look at this again on my computer in a while and try to give you a new example.

**Comment by CharliePoole** [comment]
Let's imagine a pair of interfaces:

```C#
public interfacer ITransaction
{
     bool IsFinished { get; }
     ITransactionResult Result { get; }
}

public interface ITransactionResult
{
    bool IsSuccess { get; };
}
```

If I have initiated a transaction, receiving an ITransaction instance in return, I can test for completion first and then assert on the result...

```C#
   Assert.That(() => transaction.IsFinished, Is.True.After(10).Seconds.PollEvery(1).Seconds, "Transaction did not complete!");
   Assert.That(transaction.Result.IsSuccess, "Transaction failed!");
```

In what ways is what you are doing different from this?
