### ISSUE TITLE
Inconsistent TestContext output handling

### ISSUE THREAD

**Issue by Suremaker** [nunit/nunit#2177]
Hello,

I have observed some inconsistency regarding how output is captured during test run.
I have made a sample project that runs 4 test classes in parallel with tests that prints some output with `TestContext.Out`: 
[UnitTestProject1.zip](https://github.com/nunit/nunit/files/1013661/UnitTestProject1.zip)

All the tests looks like that (there is 4 classes with 4 tests):
```c#
[Test]
public async Task TestMethod1()
{
    TestContext.Out.WriteLine(TestContext.CurrentContext.Test.FullName);
    await Task.Delay(1000);
    TestContext.Out.WriteLine(TestContext.CurrentContext.Test.FullName);
}
```
Test assembly is annotated with `[assembly: Parallelizable(ParallelScope.Children)]`.
Project uses following packages:
```
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="NUnit" Version="3.6.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.8.0-alpha1" />
```
----
When I run tests in Resharper 2017.1.2, the output is associated pretty randomly:
![resharper1](https://cloud.githubusercontent.com/assets/1894621/26241160/9c2889b6-3c7b-11e7-8408-cc68200bf4af.PNG)
![resharper2](https://cloud.githubusercontent.com/assets/1894621/26241171/a3e61c90-3c7b-11e7-8e3f-fbfc50b17669.PNG)

When I run tests in Visual Studio runner, the output is also inconsistent (some of the tests have it, some dont, however if they have, it is properly associated):
![vs1](https://cloud.githubusercontent.com/assets/1894621/26241176/a9ca20de-3c7b-11e7-9be0-b6da4650152b.PNG)
![vs2](https://cloud.githubusercontent.com/assets/1894621/26241181/ad09e90a-3c7b-11e7-9dba-1866f5d2c51b.PNG)

----
Finally, when I change `TestContext.Out` to `TestContext.Progress` to see immediate test outcome, the outcome is randomly captured in Resharper:
![resharper_progress](https://cloud.githubusercontent.com/assets/1894621/26241205/c6e24778-3c7b-11e7-9a96-461ac7c24051.PNG)

... and not captured at all in VS Test (none has `Output` link).

----
It would be great if output were properly captured, but I am even more interested to seeing `TestContext.Progress` outcome, while rendered immediately, be also associated with proper tests.

Thanks!

Ps. I use Visual Studio 2017

**Comment by rprouse** [comment]
If you are trying to associate output with a specific parallel test, you should not use `TestContext.Progress` which outputs immediately. You should be using `TestContext.WriteLine` which collects the output.

I don't think this is an issue with the framework itself. We do not control how ReSharper captures or displays our output, so you will need to report that there. We do however control the adapter. We might be limited by limitations in the adapter API, but the investigation and any fixes should be made in the adapter code. I am going to move the issue there.

**Comment by rprouse** [comment]
Issue moved to [nunit/nunit3-vs-adapter #368](https://github.com/nunit/nunit3-vs-adapter/issues/368) via [**ZenHub**](https://www.zenhub.com/)
