### ISSUE TITLE
Some NUnit project's tests fail on systems with CultureInfo other than en 

### ISSUE THREAD

**Issue by gcichosz** [nunit/nunit#2179]
The following tests fail on systems with comma decimal mark settings:
- NUnit.Framework.Internal.EventListenerTextWriterTests.TestWriteDecimal
- NUnit.Framework.Internal.EventListenerTextWriterTests.TestWriteDouble
- NUnit.Framework.Internal.EventListenerTextWriterTests.TestWriteStringArg2
- NUnit.Framework.Internal.EventListenerTextWriterTests.TestWriteStringArg3
- NUnit.Framework.Constraints.LessThanConstraintTests.SimpleTolerance_Failure

The following test fails on systems with CultureInfo other than en:
- NUnit.Framework.Internal.EventListenerTextWriterTests.TestWriteStringArg1

Steps to reproduce:
1. Change system region, or language settings to one with comma decimal mark ([Countries using Arabic numerals with decimal comma](https://en.wikipedia.org/wiki/Decimal_mark#Countries_using_Arabic_numerals_with_decimal_comma)), and with language other than English
2. Run the build script with `-Target Test` option
3. See aforementioned tests fail

**Comment by GCichosz** [comment]
I'm already on that issue, because it blocks me from running the tests properly, so someone can assign me to it. If not, I'm doing that anyways, and will update that issue with a PR 😉

**Comment by ChrisMaddock** [comment]
Whoops! Great, thanks!
