### ISSUE TITLE
How to use `Contains.Substring` with `And`

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2194]
Just now I needed to write a test with this constraint: 
```c#
Contains.Substring("x").And.Contains.Substring("y")
```

This would have made me even happier:
```c#
Contains.Substring("x").And.Substring("y")
```

But neither API exists. This works, but it's asymmetrical and it causes an obsoletion warning telling me to use `Constains.Substring`:
```c#
Contains.Substring("x").And.ContainsSubstring("y")
```

Since it's `And`, I can just split this into two asserts. But what _should_ this look like? Am I missing the obvious, or is NUnit missing some APIs?

**Comment by CharliePoole** [comment]
The syntax for string operations has changed many times over the years and I've never been entirely happy with it. The following also work...

```C#
Contains.Substring("x").And.Contains("y")
Does.Contain("x").And.Contains("y")
Is.StringContaining("x").And.StringContaining("y")
```

I've thought about introducing `It` because it allows using the same phrase both initially and after `And`

```C#
It.Contains("X").And.Contains("Y")
```

However, `It` might conflict with other frameworks.

**Comment by jnm2** [comment]
I saw that `.Contains` returned `CollectionConstraint` but missed the string overload several times. That's what I needed. What do you think of adding a line in the XML comment pointing people looking for a substring test to the other overload?

> Is.StringContaining("x").And.StringContaining("y")

Same problem as `ContainsSubstring`; deprecated.

I dislike `It`. It's impossible to avoid the grammar "Assert that my object it is not null."

**Comment by CharliePoole** [comment]
I'm fine with improving the comment. 

Yeah, we have several obsolete forms plus two or three that have been removed!

If you can come up with something, let us know. 😄

**Comment by jnm2** [comment]
Theoretically we could add specialized `.And` and `.Or` interfaces that extend the default APIs available off `.And` and `.Or` with context-specific APIs so that this is possible: `Contains.Substring("x").And.Substring("y")`

**Comment by MhdTlb** [comment]
Can I work on this?

**Comment by jnm2** [comment]
Sure! The change we agreed on is only to add a sentence in the XML documentation for `.And.Contains` telling people who are looking for a substring test to use `<see cref="Contains(string)" />` or whatever the correct overload is.

**Comment by nisha-kaushik** [comment]
Can I work on this?

**Comment by ChrisMaddock** [comment]
@nisha-kaushik - Great, thanks! You've see @jnm2's post above about what this issue requires?

> Sure! The change we agreed on is only to add a sentence in the XML documentation for .And.Contains telling people who are looking for a substring test instead of a collection test to use <see cref="Contains(string)" /> or whatever the correct overload is.

**Comment by ChrisMaddock** [comment]
@MhdTlb - as it's been nearly a year, I've unassigned you from this issue, as Nisha's volunteered to help out. Hope that's ok!

**Comment by nisha-kaushik** [comment]
Ok, Thanks, Can you please point me to the XML documentation. Is there a need to update samples?

[https://github.com/nunit/nunit-csharp-samples](url)

**Comment by rprouse** [comment]
@nisha-kaushik the XML docs are generated by the XMLDOC comments above each class and method and will be build alongside the framework DLL. You will only need to update the code comments to update the XML Docs.

As for samples, you are welcome to update the samples, but it is not required. It would be good to add samples though 😉

**Comment by nisha-kaushik** [comment]
Are these XML comments you are referring? Sorry for so many questions, I am new to open source contribution.

```
        /// <summary>
        /// Returns a new <see cref="SomeItemsConstraint"/> checking for the
        /// presence of a particular object in the collection.
        /// Can be used as And <see cref="AndConstraint"/> as .And.Contains for Substring Test <see cref="Contains(string)"/>.
        /// </summary>
        public SomeItemsConstraint Contains(object expected)
        {
            return (SomeItemsConstraint)this.Append(new SomeItemsConstraint(new EqualConstraint(expected)));
        }
```

**Comment by rprouse** [comment]
@nisha-kaushik sorry for the delay. Yes those are the comments.

**Comment by Dreamescaper** [comment]
Personally I prefer to combine Constraints using operators.
IMHO,
`Does.Contain("x") & Does.Contain("y")`
is more readable than
`Does.Contain("x").And.Contains("y")`

**Comment by jnm2** [comment]
@Dreamescaper Nice one! I prefer that too!
