### ISSUE TITLE
Contains.Substring with custom StringComparison

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2195]
Right now I'm not seeing an API that allows this. I would like to be able to write `Contains.Substring("str").Using(StringComparison.OrdinalIgnoreCase)`.

This would correspond to the BCL's `string.IndexOf(string, StringComparison)` being compared to `-1`.

**Comment by jnm2** [comment]
@nunit/framework-team Any objections to adding this to the backlog?

**Comment by CharliePoole** [comment]
For an easyfix, I would suggest telling the possible contributor where the fix needs to be made in our source code.

**Comment by CharliePoole** [comment]
Although, easyfix for an item not on the backlog means it will show up in searches, possibly confusing people who don't see the pipelines.

**Comment by jnm2** [comment]
Yeah, okay. For the time being I won't apply easyfix without it being approved for implementation, even if I think it is an easy fix.

**Comment by ChrisMaddock** [comment]
No objection from me

**Comment by rprouse** [comment]
Speaking earlier of feature creep, this is one feature that I think could be useful to a wider audience, so I am okay with the idea 👍

**Comment by jnm2** [comment]
Also, [`string.Contains(string, StringComparison)` is being added](https://github.com/dotnet/corefx/issues/20846) to .NET Core.

**Comment by jnm2** [comment]
Notes for implementers:

[`StringConstraint`](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Constraints/StringConstraint.cs) needs a `Using(StringComparison)` method, very similar to the `CaseInsensitive` property, and the `Matches` implementation in every subclass needs to use it if specified.

**Comment by jnm2** [comment]
Ooh, quick design question that just occurred to me: I think we should throw (and document) an `InvalidOperationException` if you use _both_ `.Using(StringComparison) and `.IgnoreCase` in either order... unless we want to define some fancy rules. Either way what I don't think we should do is have one silenty override the other because it will be misleading to anyone reading the code.

**Comment by CharliePoole** [comment]
@jnm2 Re design issue: I think we have to do whatever we already do in other classes that allow both `.Using` and `.IgnoreCase`. If we don't it will be very confusing for users.

**Comment by jnm2** [comment]
@CharliePoole I didn't think we had any, but let's follow precedent.

**Comment by CharliePoole** [comment]
EqualConstraint, for example, allows both.

**Comment by MhdTlb** [comment]
Can I work on this feature?

**Comment by jnm2** [comment]
@MhdTlb Awesome, you are welcome to! Let us know if you need anything.
We'll also send an invitation so you can be assigned to this issue.

**Comment by MhdTlb** [comment]
I pushed required changes under new branch MhdTlb/nunit/issue-2195

**Comment by rprouse** [comment]
Fixed by #2294
