### ISSUE TITLE
Add OSArchitecture Attribute to Environment node in result xml 

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#22]
To differ the results on Win7x86 and Win7x64 the user needs these information in the result file.

So my idea was to extend the environment node in the result file

<environment nunit-version="2.5.6.10205" clr-version="2.0.50727.4927" os-version="Microsoft Windows NT 6.1.7600.0" osarchiteture="x64" platform="Win32NT" cwd="C:\Program Files (x86)\NUnit 2.5.6\bin\net-2.0" machine-name="ADMIN-PC" user="Administrator" user-domain="Admin-PC" />

From https://bugs.launchpad.net/nunit-3.0/+bug/613727

**Comment by CharliePoole** [comment]
This is a trivial fix to the ResultHelper class in the engine.

**Comment by agray** [comment]
I'll have a go at this.

See my pull request
