### ISSUE TITLE
StackFIlter trims leading spaces from each line

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#2208]
I noticed in the gui that stack traces from a test failure were showing up without leading spaces before the "at" on each line, whereas error failures had it. I confirmed same behavior on the console. While not terribly important, this does make the reports of combined failures and errors look odd.

I think it's due to a `Trim()` call in StackFilter.cs, which should probably simply be eliminated.

**Comment by oznetmaster** [comment]
It seems like this fix is in the wrong place, and assumes that every stack trace line starts with whitespace, and the same whitespace.

If that ever changes, then this will break again.

Correct fix seems to be to Trim everything, and then format the reports correctly.
