### ISSUE TITLE
NUnit occasionally hangs when parallelizable TestFixture has OneTimeSetUp and OneTimeTearDown

### ISSUE THREAD

**Issue by RobinsonWM** [nunit/nunit#2209]
This issue happens sporadically and appears to be a regression in NUnit Framework 3.7.  I can reproduce it within ~10 tries with NUnit 3.7, but I cannot reproduce it with NUnit 3.6.1.  I have reproduced it with the console runner and the Visual Studio runner.  It is most easily reproduced with a batch file that calls the console runner in a loop.

I have a TestFixture with a `OneTimeSetUp` method, a `OneTimeTearDown` method, and a single `Test` method.  I have the TestFixture marked with `[Parallelizable(ParallelScope.Self | ParallelScope.Children)]` (which looks silly in this simple example, but it makes more sense in my larger project.)  Occasionally NUnit will hang after executing the Test, but before executing the OneTimeTearDown.  I was able to reproduce it in a project that contains this as the only class:
```csharp
namespace Tests
{
    using System.Diagnostics;
    using NUnit.Framework;

    [TestFixture]
    [Parallelizable(ParallelScope.Self | ParallelScope.Children)]
    public class TestFixture
    {
        [OneTimeSetUp]
        public void OneTimeSetUp()
        {
            Debug.WriteLine("OneTimeSetUp");
        }

        [OneTimeTearDown]
        public void OneTimeTearDown()
        {
            Debug.WriteLine("OneTimeTearDown");
        }

        [Test]
        public void Test()
        {
            Debug.WriteLine("Test");
        }
    }
}
```

**Comment by CharliePoole** [comment]
Does using Console.WriteLine as opposed to Debug make any difference?

**Comment by RobinsonWM** [comment]
I just switched tem to `Console.WriteLine()` and was able to reproduce it.

**Comment by CharliePoole** [comment]
Looks like a fun one. 😄

**Comment by CharliePoole** [comment]
I can't make it fail using nunit3-console. Any particular command-line options you use? I'm just specifying the assembly.

**Comment by RobinsonWM** [comment]
I was using a bunch of command line options, but I trimmed it down to just the assembly and was able to reproduce it.  Here's the batch script I was using to reproduce it.  It usually hangs within a minute or so:
```
:run
"c:\builds\ininbuild_main_systest\pub\tools\winhost\win32\nunit\3\NUnit.Console\nunit3-console.exe" nunit_tests-w64r-3-1.dll
goto :run
```

For me it has been freezing with this output showing:
```
NUnit Console Runner 3.5.0
Copyright (C) 2016 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.14393.0
  CLR Version: 4.0.30319.42000

Test Files
    nunit_tests-w64r-3-1.dll

=> Tests.TestFixture.Test
Test
```

**Comment by CharliePoole** [comment]
I ran it about 15 times manually, but I'll try again in a loop.

**Comment by CharliePoole** [comment]
I got an error (not a hang) after about 4 minutes due to the agent disconnecting. I'm wondering if you are having that problem, but the error itself is somehow being masked. Would you add `--inprocess` to your command-line and see what happens?

**Comment by CharliePoole** [comment]
A few more minutes of running and I got the hang without any agent error, so it's a separate thing. I was not able to do any debugging into the release framework of course. I'll try it with a verbose trace, although that may slow things down and prevent the hang.

**Comment by rprouse** [comment]
This sounds like a potential to include in the hotfix release we are considering, so I added a 3.7.1 milestone and added this issue.

**Comment by CharliePoole** [comment]
How very optimistic of you. 😸

**Comment by CharliePoole** [comment]
It must be Rob's optimism helping me. I set it up to run in process and leave a debug trace and kicked off the batch file. It hung on the first iteration! Here are the final entries from the  log:

```
13:05:30.872 Info  [ 9] TestWorker: Worker#4 executing Test
13:05:30.874 Info  [ 7] WorkShift: Parallel shift ending
13:05:30.875 Debug [ 7] WorkItemQueue: ParallelQueue.0 pausing
13:05:30.875 Debug [ 7] WorkItemQueue: ParallelSTAQueue.0 pausing
13:05:30.879 Info  [ 7] WorkItemQueue: ParallelQueue.0 stopping - 3 WorkItems processed, max size 1
13:05:30.879 Info  [ 8] TestWorker: Worker#3 stopping - 1 WorkItems processed.
13:05:30.879 Info  [ 6] TestWorker: Worker#1 stopping - 0 WorkItems processed.
13:05:30.880 Info  [ 7] WorkItemQueue: ParallelSTAQueue.0 stopping - 0 WorkItems processed, max size 0
13:05:30.880 Info  [10] TestWorker: Worker#STA stopping - 0 WorkItems processed.
13:05:30.880 Info  [ 7] WorkItemQueue: NonParallelQueue.0 stopping - 0 WorkItems processed, max size 0
13:05:30.880 Info  [ 7] WorkItemQueue: NonParallelSTAQueue.0 stopping - 0 WorkItems processed, max size 0
13:05:30.880 Info  [ 7] TestWorker: Worker#2 stopping - 1 WorkItems processed.
13:05:30.913 Debug [ 9] Dispatcher: Using Parallel strategy for TestFixture OneTimeTearDown
13:05:30.913 Info  [ 9] TestWorker: Worker#4 stopping - 1 WorkItems processed.
```

At 872 the test itself starts to execute. It finishes almost immediately and at 874 the dispatcher decides the shift is over. Everything begins to shut down. At 913 the dispatcher finally is ready to enqueue the fixture one-time teardown. But by this time, the end of the shift is almost complete.

The dispatcher detects end of shift by virtue of all the queues being empty and all the workers idle. It looks as if there is a small window during which that is true but the teardowns still need to be run by adding them to one of the queues. I'm not clear how or why there is such a window, but apparently there is. I'm leaving this info behind as breadcrumbs to follow in case I don't finish the issue myself.

**Comment by CharliePoole** [comment]
More breadcrumbs... The sequence of events that seem to matter is as follows:

1. The TestWorker running Test finishes and raises it's idle event
2. The WorkShift handles that event by checking to see if the shift is over. 
    * The shift is defined to be over when all queues are empty and all workers are idle..
    * The workers are idle because this is the only test
    * All queues are empty because the one-time setups already ran and the one-time-teardowns have not yet been dispatched.
    * The WorkShift raises its end of shift event
3. The Dispatcher handles the end of shift event by checking each shift, looking for one to start.
    * It starts the first one that has work (i.e. one of its queues has work in it)
    * If no shift has work, then it initiates a complete shutdown

In this case, at the very last step, we would like the dispatcher to wait for any pending one-time teardowns to complete. It may be that we should just check if the top level item is complete yet and just wait a bit if it isn't. I'll try that next. Barring that rather simple solution, I think we need to have a record of all one-time teardowns that have not yet run.
