### ISSUE TITLE
[Nunit 3.7.0] Issues with Parallelizable attribute on methods

### ISSUE THREAD

**Issue by yommgui** [nunit/nunit#2212]
Hi,

I spent some time yesterday testing the 3.7.0 Parallelizable attribute on methods and get some issues.
Here is the scenario I wanted to achieve: run multiple tests in parallel **within** a class but **not with other classes**.
I'm running test on 4 cores -> 4 tests can run in parallel.

first test class:
```
[TestFixture]
public class MainTests
{
  [Test]
  [TestCase(5000)]
  public void Test11a(int milliseconds)
  {
	 Console.WriteLine($"{DateTime.Now.ToLongTimeString()} started");
	 Thread.Sleep(milliseconds);
	 Assert.IsTrue(true);
  }

  [Test]
  [TestCase(10000)]
  public void Test11b(int milliseconds)
  {
	 Console.WriteLine($"{DateTime.Now.ToLongTimeString()} started");
	 Thread.Sleep(milliseconds);
	 Assert.IsTrue(true);
  }

  [Test]
  public void Test12()
  {
	 Console.WriteLine($"{DateTime.Now.ToLongTimeString()} started");
	 Thread.Sleep(15000);
	 Assert.IsTrue(true);
  }
}
```

second test class:
```
[TestFixture]
public class MainTests2
{
  [Test]
  [TestCase(5000)]
  [TestCase(10000)]
  public void Test21(int milliseconds)
  {
	 Console.WriteLine($"{DateTime.Now.ToLongTimeString()} started");
	 NunitParallelizable.Main.Wait(milliseconds);
	 Assert.IsTrue(true);
  }
  
  [Test]
  public void Test22()
  {
	 Console.WriteLine($"{DateTime.Now.ToLongTimeString()} started");
	 NunitParallelizable.Main.Wait(15000);
	 Assert.IsTrue(true);
  }
}
```

Parallelizable target:
Test11a and Test11b run in parallel and no others
Test12 runs alone
Test21(5000) and Test21(10000) run in parallel and no others
Test22 runs alone

Here are the different Parallelizable setup, result and comments:
**1) using Parallelizable.Self**
setup: I set Parallelizable.Self on Test11a, Test11b, Test21( for 5000 and 10000 testcases)
expected: Test11a and Test11b run in parallel, then Test12, then Test21(5000) and Test21(10000) run in parallel and finally Test22 runs.
result: all tests run sequentially Test11a, Test11b, Test12, Test21(5000), Test21(10000) and finally Test22
comment: expecting my scenario been covered with this setup

**2) using Parallelizable.All**
setup: I set Parallelizable.All on Test11a, Test11b, Test21( for 5000 and 10000 testcases)
expected: Test11a, Test11b, Test21(5000) and Test21(10000) run in parallel, then Test12 and finally Test22
result: Test11a, Test11b and Test12 run in parallel and then Test21(5000), Test(10000) and Test22 run in parallel
comment: Looks good but Test12 and Test22 without any Parallelizable attribute I would assume they would not run in parallel (corrected with next setup)

**3) using Parallelizable.All and Parallelizable.None**
setup: I set Parallelizable.All on Test11a, Test11b, Test21( for 5000 and 10000 testcases) and Parallelizable.None on Test12 and Test22
expected: Test11a, Test11b, Test21(5000) and Test21(10000) run in parallel, then Test12 and finally Test22
result: Test11a, Test11b, Test21(5000) and Test21(10000) run in parallel then Test12 and finally Test22
comment: this one is correct; From this, if Paralleliable attribute is used on methods level only (not on class or assembly) it would be great to assume Parallelizable attribute missing as Parallelizable.None not to have to specify it on every method we don't want to run in parallel.

**Conclusion:**
From the different tests my conclusion is that the correct setup would be:
**4) using Parallelizable.Self and Parallelizable.None**
Parallelizable.Self on Test11a, Test11b, Test21( for 5000 and 10000 testcases) and Parallelizable.None on test12 and Test22. Unfortunately, Parallelizable.Self does not work as expected or I'm missing something.

Please tell me if I'm missing somthing in my interpretation of Parallelizable attribute on methods.
Cheers

**Comment by CharliePoole** [comment]
I assume that when you write `Parallelizable.Self` you mean `[Parallelizable(ParallelScope.Self)]`, etc.

If I understand you correctly, you have the two fixtures (classes) which should __not__ run in parallel at all. Therefore, you should use `[NonParallelizable]` on those classes.

Within each class, you have some methods that are allowed to run in parallel and others that are not. You should use [Parallelizable] on those that are expected to be parallel and [NonParallelizable] on those that are not.

If you prefer the older syntax, you can use that as well.

**Comment by yommgui** [comment]
Hi Charlie, 
You understand my request perfectly and my syntax as well ;)
Thanks for your quick answer; I tested it but it does not work as well; all tests run sequentially.

**Comment by CharliePoole** [comment]
Would you edit your description to include the attributes you are using, where you are using them? 

Also, make sure you __are__ really running NUnit 3.7. The feature is new to that release. How are you running the tests, btw?

**Comment by CharliePoole** [comment]
Additionally, what is your target runtime?

**Comment by yommgui** [comment]
As you suggested I put:
- [NonParallelizable] on classes
- [Parallelizable] on Test11a, Test11b, Test21
and
- [NonParallelizable] on Test12 and Test22

I confirm i'm using 3.7.0 assembly from nuget and running using VS nunit adapter 3.7.0

**Comment by yommgui** [comment]
I justed test the other syntax as well:
- [Parallelizable(ParallelScope.None)] on classes
- [Parallelizable(ParallelScope.All)] on Test11a, Test11b and Test21
- [Parallelizable(ParallelScope.None)] on Test12 and Test22

this is weird as it runs Test11a, Test11b and **Test12** in parallel and then Test21(5000), Test21(10000) and **Test22** on parallel as well

**Comment by CharliePoole** [comment]
How exactly are you determining what's running in parallel? I'm wondering if it's possible that you are misunderstanding the output. 

It may also help to see how this runs under the console runner. You might try running with --trace:Info or --trace:Debug to see how the tests are being dispatched.

**Comment by yommgui** [comment]
Hi Charlie,

Sorry for the late anwser.
I did run the setup you suggested with [NonParallelizable] on class and methods I want to run not parallelized (Test12 and Test22) and with [Parallelizable] on methods I want to run in parallel inside class (Test11a, Test11b, Test21(5000/10000).

As said I confirm everything is running sequentially.
Please find trace:debug for this test, Please tell me if you see anything special.
Thanks

> InternalTrace: Initializing at level Debug
> 15:03:58.036 Debug [ 5] DefaultTestAssemblyBuilder: Loading C:\NunitParallelizable\NunitParallelizableTests\bin\Debug\NunitParallelizableTests.dll in AppDomain domain-b1c6ac51-NunitParallelizableTests.dll
> 15:03:58.077 Debug [ 5] DefaultTestAssemblyBuilder: Examining assembly for test fixtures
> 15:03:58.080 Debug [ 5] DefaultTestAssemblyBuilder: Found 2 classes to examine
> 15:03:58.187 Debug [ 5] DefaultTestAssemblyBuilder: Found 2 fixtures with 6 test cases
> 15:03:58.445 Info  [ 5] DefaultTestAssemblyRunner: Running tests
> 15:03:58.470 Debug [ 5] WorkShift: Parallel shift adding queue ParallelQueue
> 15:03:58.470 Debug [ 5] WorkShift: Parallel shift adding queue ParallelSTAQueue
> 15:03:58.470 Debug [ 5] WorkShift: NonParallel shift adding queue NonParallelQueue
> 15:03:58.470 Debug [ 5] WorkShift: NonParallelSTA shift adding queue NonParallelSTAQueue
> 15:03:58.471 Debug [ 5] WorkShift: Parallel shift assigned worker Worker#1
> 15:03:58.471 Debug [ 5] WorkShift: Parallel shift assigned worker Worker#2
> 15:03:58.471 Debug [ 5] WorkShift: Parallel shift assigned worker Worker#3
> 15:03:58.471 Debug [ 5] WorkShift: Parallel shift assigned worker Worker#4
> 15:03:58.471 Debug [ 5] WorkShift: Parallel shift assigned worker Worker#STA
> 15:03:58.471 Debug [ 5] WorkShift: NonParallel shift assigned worker Worker#STA_NP
> 15:03:58.471 Debug [ 5] WorkShift: NonParallelSTA shift assigned worker Worker#NP_STA
> 15:03:58.493 Debug [ 5] Dispatcher: Using Parallel strategy for NunitParallelizableTests.dll
> 15:03:58.501 Info  [ 5] WorkShift: Parallel shift starting
> 15:03:58.504 Info  [ 5] TestWorker: Worker#1 starting 
> 15:03:58.505 Info  [ 5] TestWorker: Worker#2 starting 
> 15:03:58.505 Info  [ 5] TestWorker: Worker#3 starting 
> 15:03:58.505 Info  [ 5] TestWorker: Worker#4 starting 
> 15:03:58.510 Info  [ 5] TestWorker: Worker#STA starting 
> 15:03:58.511 Info  [ 5] WorkItemQueue: ParallelQueue.0 starting
> 15:03:58.511 Info  [ 5] WorkItemQueue: ParallelSTAQueue.0 starting
> 15:03:58.512 Info  [ 9] TestWorker: Worker#1 executing NunitParallelizableTests.dll
> 15:03:58.561 Debug [ 9] Dispatcher: Using Direct strategy for NunitParallelizableTests
> 15:03:58.564 Debug [ 9] Dispatcher: Using NonParallel strategy for MainTests
> 15:03:58.564 Debug [ 9] Dispatcher: Using NonParallel strategy for MainTests2
> 15:03:58.565 Info  [ 9] WorkShift: Parallel shift ending
> 15:03:58.565 Debug [ 9] WorkItemQueue: ParallelQueue.0 pausing
> 15:03:58.565 Debug [ 9] WorkItemQueue: ParallelSTAQueue.0 pausing
> 15:03:58.566 Info  [ 9] WorkShift: NonParallel shift starting
> 15:03:58.566 Info  [ 9] TestWorker: Worker#STA_NP starting 
> 15:03:58.567 Info  [ 9] WorkItemQueue: NonParallelQueue.0 starting
> 15:03:58.567 Info  [14] TestWorker: Worker#STA_NP executing MainTests
> 15:03:58.568 Info  [14] Dispatcher: Saving Queue State for MainTests
> 15:03:58.569 Debug [14] WorkItemQueue: ParallelQueue.0 pausing
> 15:03:58.570 Info  [14] WorkItemQueue: ParallelQueue.1 starting
> 15:03:58.570 Debug [14] WorkItemQueue: ParallelSTAQueue.0 pausing
> 15:03:58.570 Info  [14] WorkItemQueue: ParallelSTAQueue.1 starting
> 15:03:58.570 Debug [14] WorkItemQueue: NonParallelQueue.0 pausing
> 15:03:58.570 Info  [14] WorkItemQueue: NonParallelQueue.1 starting
> 15:03:58.570 Debug [14] WorkItemQueue: NonParallelSTAQueue.0 pausing
> 15:03:58.570 Info  [14] WorkItemQueue: NonParallelSTAQueue.1 starting
> 15:03:58.582 Debug [14] Dispatcher: Using Direct strategy for Test11a
> 15:03:58.584 Debug [14] Dispatcher: Using Direct strategy for Test11a(5000)
> 15:04:03.617 Debug [14] Dispatcher: Using Direct strategy for Test11a OneTimeTearDown
> 15:04:03.628 Debug [14] Dispatcher: Using Direct strategy for Test11b
> 15:04:03.630 Debug [14] Dispatcher: Using Direct strategy for Test11b(10000)
> 15:04:13.635 Debug [14] Dispatcher: Using Direct strategy for Test11b OneTimeTearDown
> 15:04:13.637 Debug [14] Dispatcher: Using NonParallel strategy for Test12
> 15:04:13.637 Info  [14] TestWorker: Worker#STA_NP executing Test12
> 15:04:28.642 Debug [14] Dispatcher: Using NonParallel strategy for MainTests OneTimeTearDown
> 15:04:28.642 Info  [14] TestWorker: Worker#STA_NP executing MainTests OneTimeTearDown
> 15:04:28.644 Info  [14] WorkShift: NonParallel shift ending
> 15:04:28.644 Debug [14] WorkItemQueue: NonParallelQueue.1 pausing
> 15:04:28.645 Info  [14] Dispatcher: Restoring Queue State
> 15:04:28.645 Debug [14] WorkItemQueue: ParallelQueue.1 pausing
> 15:04:28.645 Info  [14] WorkItemQueue: ParallelQueue.0 starting
> 15:04:28.645 Debug [14] WorkItemQueue: ParallelSTAQueue.1 pausing
> 15:04:28.645 Info  [14] WorkItemQueue: ParallelSTAQueue.0 starting
> 15:04:28.645 Debug [14] WorkItemQueue: NonParallelQueue.1 pausing
> 15:04:28.645 Info  [14] WorkItemQueue: NonParallelQueue.0 starting
> 15:04:28.645 Debug [14] WorkItemQueue: NonParallelSTAQueue.1 pausing
> 15:04:28.645 Info  [14] WorkItemQueue: NonParallelSTAQueue.0 starting
> 15:04:28.645 Info  [14] WorkShift: NonParallel shift starting
> 15:04:28.645 Info  [14] WorkItemQueue: NonParallelQueue.0 starting
> 15:04:28.645 Info  [14] TestWorker: Worker#STA_NP executing MainTests2
> 15:04:28.645 Info  [14] Dispatcher: Saving Queue State for MainTests2
> 15:04:28.645 Debug [14] WorkItemQueue: ParallelQueue.0 pausing
> 15:04:28.645 Info  [14] WorkItemQueue: ParallelQueue.1 starting
> 15:04:28.646 Debug [14] WorkItemQueue: ParallelSTAQueue.0 pausing
> 15:04:28.646 Info  [14] WorkItemQueue: ParallelSTAQueue.1 starting
> 15:04:28.646 Debug [14] WorkItemQueue: NonParallelQueue.0 pausing
> 15:04:28.646 Info  [14] WorkItemQueue: NonParallelQueue.1 starting
> 15:04:28.646 Debug [14] WorkItemQueue: NonParallelSTAQueue.0 pausing
> 15:04:28.646 Info  [14] WorkItemQueue: NonParallelSTAQueue.1 starting
> 15:04:28.648 Debug [14] Dispatcher: Using Direct strategy for Test21
> 15:04:28.650 Debug [14] Dispatcher: Using Direct strategy for Test21(5000)
> 15:04:33.661 Debug [14] Dispatcher: Using Direct strategy for Test21(10000)
> 15:04:43.665 Debug [14] Dispatcher: Using Direct strategy for Test21 OneTimeTearDown
> 15:04:43.667 Debug [14] Dispatcher: Using NonParallel strategy for Test22
> 15:04:43.667 Info  [14] TestWorker: Worker#STA_NP executing Test22
> 15:04:58.672 Debug [14] Dispatcher: Using NonParallel strategy for MainTests2 OneTimeTearDown
> 15:04:58.672 Info  [14] TestWorker: Worker#STA_NP executing MainTests2 OneTimeTearDown
> 15:04:58.674 Debug [14] Dispatcher: Using Direct strategy for NunitParallelizableTests OneTimeTearDown
> 15:04:58.676 Debug [14] Dispatcher: Using Direct strategy for NunitParallelizableTests.dll OneTimeTearDown
> 15:04:58.682 Info  [14] WorkShift: NonParallel shift ending
> 15:04:58.683 Debug [14] WorkItemQueue: NonParallelQueue.1 pausing
> 15:04:58.683 Info  [14] Dispatcher: Restoring Queue State
> 15:04:58.683 Debug [14] WorkItemQueue: ParallelQueue.1 pausing
> 15:04:58.683 Info  [14] WorkItemQueue: ParallelQueue.0 starting
> 15:04:58.683 Debug [14] WorkItemQueue: ParallelSTAQueue.1 pausing
> 15:04:58.683 Info  [14] WorkItemQueue: ParallelSTAQueue.0 starting
> 15:04:58.683 Debug [14] WorkItemQueue: NonParallelQueue.1 pausing
> 15:04:58.683 Info  [14] WorkItemQueue: NonParallelQueue.0 starting
> 15:04:58.683 Debug [14] WorkItemQueue: NonParallelSTAQueue.1 pausing
> 15:04:58.683 Info  [14] WorkItemQueue: NonParallelSTAQueue.0 starting
> 15:04:58.684 Info  [14] WorkItemQueue: ParallelQueue.0 stopping - 1 WorkItems processed, max size 1
> 15:04:58.684 Info  [10] TestWorker: Worker#2 stopping - 0 WorkItems processed.
> 15:04:58.685 Info  [11] TestWorker: Worker#3 stopping - 0 WorkItems processed.
> 15:04:58.685 Info  [12] TestWorker: Worker#4 stopping - 0 WorkItems processed.
> 15:04:58.685 Info  [ 9] TestWorker: Worker#1 stopping - 1 WorkItems processed.
> 15:04:58.684 Info  [14] WorkItemQueue: ParallelSTAQueue.0 stopping - 0 WorkItems processed, max size 0
> 15:04:58.685 Info  [13] TestWorker: Worker#STA stopping - 0 WorkItems processed.
> 15:04:58.685 Info  [14] WorkItemQueue: NonParallelQueue.0 stopping - 6 WorkItems processed, max size 2
> 15:04:58.685 Info  [14] WorkItemQueue: NonParallelSTAQueue.0 stopping - 0 WorkItems processed, max size 0
> 15:04:58.686 Info  [14] TestWorker: Worker#STA_NP stopping - 6 WorkItems processed.

**Comment by CharliePoole** [comment]
The trace indicates that all your "parallelizable" test methods are being run using the "Direct" strategy, i.e. on the same thread as the fixture. This is what would be used if the methods have no Parallelizable attribute. Please re-post the source code with the exact attributes used for this run and I'll try it locally.

**Comment by yommgui** [comment]
first class:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using NUnit.Framework;

namespace NunitParallelizableTests
{
   //[Parallelizable(ParallelScope.None)]
   [NonParallelizable]
   [TestFixture]
   public class MainTests
   {
      //[Parallelizable(ParallelScope.All)]
      [Parallelizable]
      [Test]
      [Category("Wait")]
      [TestCase(5000)]
      public void Test11a(int milliseconds = 10000)
      {
         Console.WriteLine($"{DateTime.Now.ToLongTimeString()} started");
         Thread.Sleep(milliseconds);
         Assert.IsTrue(true);
      }

      //[Parallelizable(ParallelScope.All)]
      [Parallelizable]
      [Test]
      [Category("Wait")]
      [TestCase(10000)]
      public void Test11b(int milliseconds = 10000)
      {
         Console.WriteLine($"{DateTime.Now.ToLongTimeString()} started");
         Thread.Sleep(milliseconds);
         Assert.IsTrue(true);
      }

      //[Parallelizable(ParallelScope.None)]
      [NonParallelizable]
      [Test]
      [Category("Wait")]
      public void Test12()
      {
         Console.WriteLine($"{DateTime.Now.ToLongTimeString()} started");
         Thread.Sleep(15000);
         Assert.IsTrue(true);
      }
   }
}

```

second class:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;

namespace NunitParallelizableTests
{
   //[Parallelizable(ParallelScope.None)]
   [NonParallelizable]
   [TestFixture]
   public class MainTests2
   {
      //[Parallelizable(ParallelScope.All)]
      [Parallelizable]
      [Test]
      [Category("Wait")]
      [TestCase(5000)]
      [TestCase(10000)]
      public void Test21(int milliseconds = 10000)
      {
         Console.WriteLine($"{DateTime.Now.ToLongTimeString()} started");
         NunitParallelizable.Main.Wait(milliseconds);
         Assert.IsTrue(true);
      }

      //[Parallelizable(ParallelScope.None)]
      [NonParallelizable]
      [Test]
      [Category("Wait")]
      public void Test22()
      {
         Console.WriteLine($"{DateTime.Now.ToLongTimeString()} started");
         NunitParallelizable.Main.Wait(15000);
         Assert.IsTrue(true);
      }
   }
}

```

**Comment by yommgui** [comment]
Hi @CharliePoole 
Any news?

**Comment by rprouse** [comment]
@yommgui `Console.WriteLine` will not show you correct results because NUnit captures console output and then prints it out sequentially at the end of the test. If you want a valid test, use `TestContext.Progress.WriteLine()`

I switched your class to

```C#

namespace NunitParallelizableTests
{
    [Parallelizable(ParallelScope.All)]
    [TestFixture]
    public class MainTests
    {
        [TestCase(1000)]
        [TestCase(1500)]
        [TestCase(2000)]
        public async Task Test11a(int milliseconds)
        {
            TestContext.Progress.WriteLine($"{DateTime.Now.ToLongTimeString()} Test11a({milliseconds}) started");
            await Task.Delay(milliseconds);
            TestContext.Progress.WriteLine($"{DateTime.Now.ToLongTimeString()} Test11a({milliseconds}) ending");
            Assert.IsTrue(true);
        }

        [TestCase(2000)]
        public async Task Test11b(int milliseconds)
        {
            TestContext.Progress.WriteLine($"{DateTime.Now.ToLongTimeString()} Test11b({milliseconds}) started");
            await Task.Delay(milliseconds);
            TestContext.Progress.WriteLine($"{DateTime.Now.ToLongTimeString()} Test11b({milliseconds}) ending");
            Assert.IsTrue(true);
        }

        [Test]
        public async Task Test12()
        {
            TestContext.Progress.WriteLine($"{DateTime.Now.ToLongTimeString()} Test12 started");
            await Task.Delay(2000);
            TestContext.Progress.WriteLine($"{DateTime.Now.ToLongTimeString()} Test12 ending");
            Assert.IsTrue(true);
        }
    }
}
```

Which gives the output,

```
=> NunitParallelizableTests.MainTests.Test11a(1000)
12:29:09 PM Test11a(1000) started
=> NunitParallelizableTests.MainTests.Test11a(1500)
12:29:09 PM Test11a(1500) started
=> NunitParallelizableTests.MainTests.Test11b(2000)
12:29:09 PM Test11b(2000) started
=> NunitParallelizableTests.MainTests.Test12
12:29:09 PM Test12 started
=> NunitParallelizableTests.MainTests.Test11a(2000)
12:29:09 PM Test11a(2000) started
=> NunitParallelizableTests.MainTests.Test11a(1000)
12:29:10 PM Test11a(1000) ending
=> NunitParallelizableTests.MainTests.Test11a(1500)
12:29:11 PM Test11a(1500) ending
=> NunitParallelizableTests.MainTests.Test11b(2000)
12:29:11 PM Test11b(2000) ending
=> NunitParallelizableTests.MainTests.Test11a(2000)
12:29:11 PM Test11a(2000) ending
=> NunitParallelizableTests.MainTests.Test12
12:29:11 PM Test12 ending
```

As you can see, the tests were running in parallel.

**Comment by yommgui** [comment]
Hi Rob @rprouse 
I was able to run all tests in parallel, that is not my request. My purpose is to run **some** tests in parallel **inside** one TestFixture.
Mayde a description or my real scenario will help:
I am working on integrations with target systems. I have features and different accounts on target system. target system does not support multiple communications at the same time. From this I must test features one at a time but to reduce my tests duration I can test the different account in parallel.
From this I wrote one TestFixture per feature, implementing tests for the different accounts in each TestFixture.
This can be drawn as:
class Feature1
void TestAccount1a
void TestAccount1b
void TestAccount2
class Feature2
void TestAccount1
void TestAccount2

My expectation is then to run tests Feature1 and Feature2 one after the other to avoid communications on same account at the same time but I want to run TestAccount1 and TestAccount2 in parallel inside a Feature class as per it's on different accounts. BUT please note that TestAccount1a and void TestAccount1b must run one after the other as well inside Feature1 as per communicating with same target account.

Hope this describes a bit better my expectation.
Thanks by the way for your answer.

**Comment by CharliePoole** [comment]
@yommgui Sorry not to have gotten back to you here. I'm working on the precise issue under #2261, which narrows it down to the use of ParallelScope.None on the assembly, with parallel tests under it. 

I think that solution will also resolve your issue, but to verify please try this:

1. Remove the assembly attribute. The absence of an attribute is defined to be the same as using `ParalllelScope(None)` but the attribute is causing your bug.

2. Remove `[NonParallelizable]` from your fixture, once again allowing the default to handle it.

3. Keep `[Parallelizable]` on those test methods you want to run in parallel. You can also keep `[NonParallelizable]` on the  other method if you like, as documentation.

Let us know how this works for you. If it does, then the bugs we are already working on will eventually resolve your original problem. Even so, I think the approach outlined above is a better way to do it, since it only uses attributes when non-default behavior is needed. The collective mindset of the NUnit developers has always been to make defaults work first and to give priority to any bugs that come up when using the defaults, so folks who use the defaults get a slightly better deal from us. 😄

**Comment by yommgui** [comment]
Hi @CharliePoole ,

No worries; I appreciate you follow my issue.
I tested your suggested setup and doing this, all tests run sequentially. 
I agree, [NonParallelizable] on Assembly, TestFixture or TestCase should be default behavior and missing attribute should be considered as NonParallelizable then. Attribute should then be used to override default.
