### ISSUE TITLE
SetCultureAttribute: CultureInfo ctor should use default culture settings

### ISSUE THREAD

**Issue by Lette** [nunit/nunit#2213]
The `CultureInfo` constructor's `useUserOverride` argument defaults to `true` ([source](https://referencesource.microsoft.com/#mscorlib/system/globalization/cultureinfo.cs,325)), which has the unfortunate effect that if you call `new CultureInfo("en-US")` while on an OS that is set to use **user-modified** en-US regional settings, those modifications will get picked up. This leads to code that picks up different settings depending on which computer you run it on. By setting `useUserOverride` to `false` the problem goes away and you'll always get a fresh set of default settings for the requested culture.

This applies to both [`SetCultureAttribute.cs`](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Attributes/SetCultureAttribute.cs#L52) and [`SetUICultureAttribute.cs`](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Attributes/SetUICultureAttribute.cs#L52).

**Comment by CharliePoole** [comment]
I don't doubt that this is a bug, but it's a bug that has been around for about 12 years. Any idea why nobody has ever hit it before? Must be a little-used feature, at least in systems used for testing.

**Comment by Lette** [comment]
I've actually hit it several times, but only because my current customer insists on messing with the regional settings through group policies. So, our dev machines use Swedish regional settings with the decimal point being 'dot' instead of 'comma' which is the default for Sweden. Sometimes someone changes their local regional settings and then culture specific tests start to fail...

I guess that it is really uncommon that people mess with their regional settings.

I helped fix this in xUnit some months ago. I figured that it was about time to fix it in nUnit as well.

**Comment by CharliePoole** [comment]
Fair enough. It's certainly news to me.

**Comment by rprouse** [comment]
I often override my date settings, so I am surprised this one hasn't been an issue for me. I guess it is more likely and issue for overriding the decimal separator.

I added the easyfix label. @Lette this is marked low priority, but we do accept pull requests 😄

**Comment by Lette** [comment]
So, I decided to jump in and provide you with the PR. I pulled the source to my computer at home, ran `.\build` and everything compiled. (I'm not so lucky compiling in VS 2017, but that's probably another story.)

Then I ran `.\build -t test` just to make sure I had a nice baseline, and I had 7 test failures in each project. Turns out that those test failures happen because I have my regional settings set to Swedish. (This time the default Swedish settings, and not the modified ones I have on my work computer as mentioned above).

When run under English (U.S.) settings, everything is fine.

I can provide you with a PR that fixes these seven failures (a suggestion at least, based on my full three hours of experience with this repo) - if you'd like to have it. What do you say? (Do I need to create a new issue for this?)

**Comment by CharliePoole** [comment]
With your seven failures in Swedish, I was going to say just include them. Now that it's getting more complicated, I think we should have another issue. If you have time to work on it, that would be great, but even documenting the problem would be very useful.

**Comment by Lette** [comment]
I'll create another issue for the other culture dependent test failures.
