### ISSUE TITLE
A dedicated Roslyn analyzer project to help migrate v2 -> v3

### ISSUE THREAD

**Issue by wachulski** [nunit/nunit#2216]
Just an idea. I've plenty of nunit tests 2.6.4 in my commercial product. I wanted to upgrade to 3 and therefore to adjust their usage to 3v API. This is somewhat tedious and repeatable work. Having some automation at hand would save tons of time for developers and NUnit creators (less questions on various forums).

What about starting a little dedicated analyser project for this? I see the current analyser project is meant as a general guide to use API. If not a project, maybe a dedicated set of Roslyn analyser rules prefixed in some consistent way?

I can help you with this, I've done some Roslyn analysers in my organization before and I see its power.

**Comment by wachulski** [comment]
@ChrisMaddock 
I'd personally love to see this! It was one of the ideas thrown around on the original analyzer issue. (Sadly one of many things I wanted to look at, but never managed to get back to!)

https://github.com/nunit/nunit/issues/629#issuecomment-230166968

One question: how well does Roslyn deal with analysing non-compiling code? I've converted just about everything within reach from NUnit 2 -> 3 by this point - but my memory was always about half the work was getting things compiling again, and then the other half - runtime changes. Could both parts be helped with analysers?

Project-wise, for now at least, I would see this belonging in the same repo - but as a separate distribution, i.e. we'd build two products out of the same repo. The current analyzers work has stalled a little, but it would be great to see that moving again - I'd love to have analysers in the main NuGet package one day (although I believe that's currently a controversial opinion!)

It would be good to flesh this out a little and work out what a v0.1 might include. One particularly useful thing may be analysers to convert deprecated methods/attributes - which would be great to point people towards when we eventually removed those methods.

Will be good to hear the rest of the teams thoughts.

@wachulski
Yeah, I've seen that thread already. A few answers:

One question: how well does Roslyn deal with analysing non-compiling code?

Well, same as MSBuild/csc don't stop on the first error but report multiple errors instead. Problems might arise when for a hypothetical fix chain: [Code1 ----FixerA----> Code2 -----FixerB----> Code3], Code2 doesn't compile (then FixerB would have trouble time to offer/get into Code3). Fortunately vast majority of deprecated Assertions/Constraints and Attributes (referring to https://github.com/nunit/docs/wiki/Breaking-Changes) are independent in terms of analyze/fixing and there is now overlap between various analyzers.

Project/Repo location - well, I can adjust to everything you propose. The real value for me is to have a battery of automation to transfer API soon. Eventual relocation for the initial release shouldn't be that much of problem.

It would be good to flesh this out a little and work out what a v0.1 might include.

Sure thing! Already mentioned  Assertions/Constraints and Attributes seems so straightforward to cover with a few analyzers/fixers that I even perceive it as a 20% effort giving 80% value for potential users.

BTW here is my vision: 

0. A dev is fighting transform NUnit2 -> NUnit3 manually/regex 
1. The dev installs a dedicated migration analyzer nuget
2. The dev is instantly shown errors/warnings/info for existing v2 API
3. The dev deliberately chooses whether they want to fix the issues individually/project_wide/solution_wide:
3.a by IssueId (e.g. all Assert.IsNullOrEmpty deprecation)
3.b by Issue group (e.g. all Asserts, or all Constraints, or all Attributes) -> this is to speed up migration.
--- while executing fixers the code turns into non compiling state, but it shouldn't be a real problem as compilation error scopes should be local ---
4. The dev upgrades NUnit to v3
5. The dev compiles and it all compiles
6. The dev runs unit tests and it all passes

I know 5-6 is quite idealistic, but:
1. There should be only a small percentage of cases that would require manual polishing.
2. While we advance with this migration utility, we may cover more complex scenarios.

What do you think? Can I jump into it with some v0.1-alpha demo soon? :)

Marcin

@ChrisMaddock 
I think it sounds great - however it's not my decision to make, alone! I've nudged the Core Team members, who'll hopefully pick this up to share their thoughts soon.

Your 'vision' is what I was expecting, and sounds ideal to me. I'm not sure all v3 replacements for v2 attributes were available in NUnit 2 - so the point of switching assembly might need some thought, maybe it would be better to upgrade to NUnit 3, and then run the analysers. I also think point 6 (all unit tests pass) is potentially unacheivable re: file path changes, for example - but analyzers should definitely be able to make it a long way down that path!

@NUnit-Core-Team
Looking at downloads, we're about at the point where NUnit 3 usage is just taking over NUnit 2, but there's still a way to go. I definitely think it would add to our project-set to be able to provide tooling to aid conversion. As Marcin suggests, I'd see these being packaged as a separate tool, specifically for temporary use during the upgrade process.

I'd suggest Marcin starts contributing analyzers to the existing NUnit analyzers project - as I could see many analysers being useful in both a conversion package, and a standard NUnit 3 analysis package (e.g. deprecated attributes, static TestCaseSources). Once there's a sufficient set to brand as a 'tool' - we can test things out, and look at releasing for general use. In the long run, should the other analysers project pick up again, we may end up building two separate products out of this repo, but with the overlapping content, I think that's sensible.

What do people think?
Chris

@jnm2
I like this.

@CharliePoole 
I like the idea but I think it's separate from the existing project.

The only thing they have in common is the technology. They have different goals and serve different audiences. In particular, the other project already has a project lead, so Marcin would not be able to serve as lead for his own project.

IMO, as we (if we) proliferate projects, organization issues begin to take precedence over technical ones.

I would go ahead incubating each project separately and then wait to see what comes out of them.

Charlie

@CharliePoole 
Hmm... I wonder if "Under incubation" is another category of project - or is it the same as "Experimental"? It may be useful to have a way to indicate that a project is not necessarily going to continue.

BTW, I just realized this is all happening on the discussion list. Does anyone want to create an issue?

@wachulski
I'll create the issue and try to pretty-print this thread for further reference.

**Comment by rprouse** [comment]
I would be okay with this as a potential project and will help out as much as possible, but to be honest, I don't find the conversion difficult enough to warrant the work. The big changes are converting non-static TestCaseSources to static and handling the ExpectedException. The first is a bit of a hunt and fix which an analyzer could help with, but I don't think you would get meaningful code fixes for ExpectedException.

Beyond those two, all the projects I've worked on were just global search and replace for deprecated methods.

**Comment by ChrisMaddock** [comment]
We should move this to conclusion. Sorry @wachulski - it's been a busy few weeks.

With the above feedback, is this still a project you'd be interested in working on? I think Rob raises a valid point, that there's perhaps only so much of the upgrade process that can be automated - but in general, it looks to me like if you were interested in working on it - we'd be keen to have it as part of the organisation. 👍

**Comment by CharliePoole** [comment]
Shouldn't we discuss this as a core team governance issue? (Acceptance of a new project and project lead)

My feeling is that we should __only__ accept it as an experimental or incubator project and only if it comes with a project lead who plans to be heavily involved, perform releases, etc. I'd like to see it, but I would not like to see it take away from existing resources.

We can either move this issue or go to email, whatever you like.

**Comment by jnm2** [comment]
Let's move the issue.

**Comment by ChrisMaddock** [comment]
I'd taken the Core Team members' agreement above to cover that. Apologies if I'd misinterpreted that. If you (or any other core team member!) thinks there's more to be discussed, then yes, we should definitely do that.

An issue sounds good. Given this has been quiet for two weeks - shall we wait to hear @wachulski's thoughts before discussing much further?

And to your comment re: project lead - I agree, and had assumed that would be the case. It's probably good for to say explicitly, however. I was expecting this to be a project that @wachlulski would lead, develop and maintain - with the view that should he no longer be able to continue, and no other maintainer was found, the project may be moved out of the organization.

**Comment by CharliePoole** [comment]
I think it's OK to be informal and I'm merely stressing it because I think we are not all used to thinking as the @nunit/core-team. As chair, I want to here from every member, whether we do it under governance or here. There will eventually be a governance PR to implement this, but I would hope the main issue would be decided before then and the PR would just be documenting it.

Of the five core team members, @jnm and @ChrisMaddock have been affirmative, @rprouse and I have been a bit lukewarm and @OsirisTerje has not yet expressed himself. 

I can convert to a Yes on this, using the provisions that @ChrisMaddock laid out and provided we set it up as a project that is in the process of proving itself - whatever name we want to give that. Eventually, it will either prove itself or not and we can either promote it or remove it.

@rprouse You were doubtful but sounded mostly positive about giving @wachulski a shot. Is that a Yes?

@OsirisTerje Even if everyone says yes, our governance docs call for explicit agreement. I don't want to cut it off without your having the statutory 72 hours, but I hope you'll be quicker than that. 😄 And anyway, you may say something that will change all our minds.

**Comment by wachulski** [comment]
Thanks for your positive feedback for my idea. I like the term _incubation_ as I don't know where it will end up eventually. Should you find it unacceptable, well, it will finish its life as yet another unofficial community addon. Anyway, I’ve already started with ExpectedException transformation. 

And I agree with @rprouse on the nature of the effort, no rocket science here. Nevertheless, I’ve seen many times developers who cherished little utilities doing tedious work for them.

BTW – I picked _nunit.migrator_ name.

**Comment by jnm2** [comment]
We're still waiting for @rprouse and @OsirisTerje to respond.

**Comment by rprouse** [comment]
I would only want to accept this on a provisional status. We have many people who offer to contribute projects only to move on after the initial release (if that long) and leave the projects for us to manage.

For now, @wachulski, why don't you continue work in your account, see how far you get and then present the results to us. If it looks good, we can talk about transferring it into the organization and helping you release it and maintain it.

**Comment by rprouse** [comment]
@wachulski we have not heard anything from you and the team does not have the capacity to take this on, so I am closing.

**Comment by wachulski** [comment]
@rprouse I understand. I have actually committed to myself that I will finish that. And I'm almost there in terms of v1: https://github.com/wachulski/nunit-migrator I've been recently doing some acceptance test runs on large nunit2-based assets and I need to rectify a few things.

I'd be glad if I could just ask NUnit crew questions for how to address particular NUnit domain migration problems etc. Just Q/A, consulting, mentoring etc. And you could always raise issues for the project.

For starters: 

1. Do you know any large open source nunit2-based projects? I'd like to feed my utility with such projects.
2. Could you propose the best way to do Q/A on a regular basis with NUnit team? (github, google forum etc.)

**Comment by ChrisMaddock** [comment]
@wachulski 

This project looks brilliant! We have very few NUnit 2 projects left at ours now, but I'll be sharing this where I can!

1. Try https://github.com/ccnet/CruiseControl.NET. It's NUnit 2.5, but should be helpful.
2. Gitter or the NUnit-Discuss mailing list are probably you're best options - depending on what you have to ask. Some of the team also monitor StackOverflow.

**Comment by wachulski** [comment]
FYI: I released as 1.0.1 and used it successfully to bake https://github.com/ccnet/CruiseControl.NET/pull/259
