### ISSUE TITLE
Console runner performance varies wildly depending on environmental characteristics

### ISSUE THREAD

**Issue by mintsoft** [nunit/nunit#2217]
Hiya,

We've just rolled out NUnit 3 for the majority of our build suite, and we've found some interesting (to say the least) performance behaviour. I think this may be a duplicate of: https://github.com/nunit/nunit/issues/480

Basically we noticed that tests "are slow on CI"; after eliminating the hardware and installation etc. We've found that tests when executed through NUnit-console are quicker when Visual Studio is open, than when it's closed. This seems insane behaviour, however it is absolutely what we see (absolutely repeatable on multiple machines, including a freshly installed machine):

* With VS closed: 9.131 seconds
* With VS open: 2.54 seconds.

It happens with every test project we have with comparable performance differences (i.e. 1 minute to 4 minutes on the larger suites). When I say with Visual Studio open, I don't mean the relevant `sln` or `csproj` open, I mean just the application itself. 

Here the first run was with VS open, the next 2 with it closed and then it open again:
```
D:\code>NUnit.ConsoleRunner.3.6.1\tools\nunit3-console.exe test\Web\Tests.csproj
NUnit Console Runner 3.6.1
Copyright (C) 2017 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 6.3.9600.0
  CLR Version: 4.0.30319.42000

Test Files
    test\Web\Tests.csproj


Run Settings
    BasePath: D:\code\test\Web\bin\
    DisposeRunners: True
    WorkDirectory: D:\code
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.6.1
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    NumberOfTestWorkers: 8

Test Run Summary
  Overall result: Passed
  Test Count: 175, Passed: 175, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2017-06-04 18:37:09Z
    End time: 2017-06-04 18:37:12Z
    Duration: 2.540 seconds

Results (nunit3) saved as TestResult.xml

D:\code>NUnit.ConsoleRunner.3.6.1\tools\nunit3-console.exe test\Web\Tests.csproj
NUnit Console Runner 3.6.1
Copyright (C) 2017 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 6.3.9600.0
  CLR Version: 4.0.30319.42000

Test Files
    test\Web\Tests.csproj


Run Settings
    BasePath: D:\code\test\Web\bin\
    DisposeRunners: True
    WorkDirectory: D:\code
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.6.1
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    NumberOfTestWorkers: 8

Test Run Summary
  Overall result: Passed
  Test Count: 175, Passed: 175, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2017-06-04 18:37:20Z
    End time: 2017-06-04 18:37:29Z
    Duration: 9.131 seconds

Results (nunit3) saved as TestResult.xml

D:\code>NUnit.ConsoleRunner.3.6.1\tools\nunit3-console.exe test\Web\Tests.csproj
NUnit Console Runner 3.6.1
Copyright (C) 2017 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 6.3.9600.0
  CLR Version: 4.0.30319.42000

Test Files
    test\Web\Tests.csproj


Run Settings
    BasePath: D:\code\test\Web\bin\
    DisposeRunners: True
    WorkDirectory: D:\code
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.6.1
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    NumberOfTestWorkers: 8

Test Run Summary
  Overall result: Passed
  Test Count: 175, Passed: 175, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2017-06-04 18:37:53Z
    End time: 2017-06-04 18:38:02Z
    Duration: 9.157 seconds

Results (nunit3) saved as TestResult.xml

D:\code>NUnit.ConsoleRunner.3.6.1\tools\nunit3-console.exe test\Web\Tests.csproj
NUnit Console Runner 3.6.1
Copyright (C) 2017 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 6.3.9600.0
  CLR Version: 4.0.30319.42000

Test Files
    test\Web\Tests.csproj


Run Settings
    BasePath: D:\code\test\Web\bin\
    DisposeRunners: True
    WorkDirectory: D:\code
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.6.1
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    NumberOfTestWorkers: 8

Test Run Summary
  Overall result: Passed
  Test Count: 175, Passed: 175, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2017-06-04 18:43:47Z
    End time: 2017-06-04 18:43:50Z
    Duration: 2.685 seconds

Results (nunit3) saved as TestResult.xml

D:\code>
```

This is running on:
* Server 2012R2
* VS 2015 Pro Update 3 (14.0.25420.01 Update 3)
* We do have ReSharper 2016.2 installed (it was mentioned extensively in https://github.com/nunit/nunit/issues/480)
* Test project is a .NET 4.6.1 against NUnit 3.6.1.0 using the NUnit Console 3.6.1.0

I'm at a loss how to explain or debug this further; happy to provide any info or run any tests you like ??

**Comment by CharliePoole** [comment]
Running from the project file is somewhat unusual. That, combined with the fact that VS is involved, makes me suspicious. Can you see what happens if you just run the assembly?

**Comment by mintsoft** [comment]
@CharliePoole That's a good point, however I've just tried it with the same behaviour:
```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\Developer>cd /D D:\code

D:\code>NUnit.ConsoleRunner.3.6.1\tools\nunit3-console.exe D:\code\test\Web\bin\Tests.dll
NUnit Console Runner 3.6.1
Copyright (C) 2017 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 6.3.9600.0
  CLR Version: 4.0.30319.42000

Test Files
    D:\code\test\Web\bin\Tests.dll


Run Settings
    DisposeRunners: True
    WorkDirectory: D:\code
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.6.1
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    NumberOfTestWorkers: 8

Test Run Summary
  Overall result: Passed
  Test Count: 175, Passed: 175, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2017-06-04 20:37:00Z
    End time: 2017-06-04 20:37:07Z
    Duration: 7.195 seconds

Results (nunit3) saved as TestResult.xml

D:\code>NUnit.ConsoleRunner.3.6.1\tools\nunit3-console.exe D:\code\test\Web\bin\Tests.dll
NUnit Console Runner 3.6.1
Copyright (C) 2017 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 6.3.9600.0
  CLR Version: 4.0.30319.42000

Test Files
    D:\code\test\Web\bin\Tests.dll


Run Settings
    DisposeRunners: True
    WorkDirectory: D:\code
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.6.1
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    NumberOfTestWorkers: 8

Test Run Summary
  Overall result: Passed
  Test Count: 175, Passed: 175, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2017-06-04 20:38:17Z
    End time: 2017-06-04 20:38:20Z
    Duration: 2.540 seconds

Results (nunit3) saved as TestResult.xml

D:\code>
```

The first run (~8seconds) was with VS closed, the second (~2seconds) was with it open.

**Comment by CharliePoole** [comment]
Interesting. As developers, we are almost always running NUnit tests locally with VS running, so those are the times we see. I'll do some experiments.

**Comment by mintsoft** [comment]
> As developers, we are almost always running NUnit tests locally with VS running, so those are the times we see.
That's exactly what we found, it was only on CI that we noticed the run-time difference initially.

**Comment by CharliePoole** [comment]
I am unable to duplicate this so I'm marking it for somebody else to try to confirm.

When you did your experiments, did you try it with VS open but no solution loaded? I wonder if it could have to do with some assemblies being in memory already.

I'm assuming that neither your tests nor your SUT uses VS in any way - i.e. you are not loading the VS object model or anything like that.

**Comment by mintsoft** [comment]
@CharliePoole Yeah it was VS open with no projects loaded at all vs it unopened. The tests are totally in-memory standalone things. There's no relationship to VS in the tests at all.
What version of Windows are you using? I'm wondering if it's a Server vs Desktop runtime style difference

**Comment by CharliePoole** [comment]
I'm running on Windows 10.

**Comment by rprouse** [comment]
@mintsoft just a guess, but could you repeat the test with another .NET program running, even just a simple console app blocked in a `Console.Readline()`? It is a stretch, but I am curious if it isn't anything to do with Visual Studio, but instead the fact that a .NET program is running and therefore the CLR is in memory.

Also, are you only able to reproduce this on your CI machine or are you also reproducing this on your development machines?

**Comment by mintsoft** [comment]
@rprouse I've just tried that, the tests ran in ~9 seconds (that's the slow time) with a console application running in the background. 

I can reproduce this on dev machines easily enough even with a fresh install of windows.

I've been experimenting with other applications being open, interestingly enough it doesn't seem to be limited to Visual Studio. One that was particularly interesting is the ModernUI WPF Example application (https://github.com/firstfloorsoftware/mui/tree/master/1.0/FirstFloor.ModernUI/FirstFloor.ModernUI.App). I compiled it, ran it and found that if it's running when the tests are executed they again run at about 2.5/3 seconds (fast speed). Close it, run the tests again and I'm back to 8 seconds. I am *very* confused now

**Comment by CharliePoole** [comment]
Maybe we are looking at this wrong. Could the problem be in how we report the time?

**Comment by mintsoft** [comment]
> Maybe we are looking at this wrong. Could the problem be in how we report the time?

@CharliePoole I don't think so, when I'm watching the runs it physically takes longer to watch. I can do a video of the test if you want?

**Comment by mintsoft** [comment]
I've done a quick gif showing it: ![2017-06-05_23-08-34](https://cloud.githubusercontent.com/assets/978048/26805542/46adeacc-4a44-11e7-8eff-cc3fb869f5da.gif)

There's nothing else open at all other than ShareX, cmd and nunit-console. 

There are 3 runs that are slow (8-9 seconds), then I open the ModernUI app I've compiled (based on the one linked to earlier, but with stuff deleted from it) it's down to <3 seconds. I close the ModernUI app again, and it's back to 8-9 seconds.

I'm currently deleting stuff from the ModernUI application to see if I can delete something that will make the effect go away

**Comment by rprouse** [comment]
Looking at the pauses in the output, it looks like it is happening while starting up the remote agent. The actual running of the tests appears to be the same. Could you try running the tests with the `--inprocess` command line switch to see if it makes a difference and help narrow down the problem? I am thinking it is setting up remoting, networking or process launching.

**Comment by rprouse** [comment]
Sorry, I am wrong, the Run Settings is output at the end of the test run. It still could be related to the remote agent though, so please try the `--inprocess` switch and let me know the results.

**Comment by mintsoft** [comment]
@rprouse I've tested that anyway, the `--inprocess` has no effect on either time. It's still ~ 3seconds vs 8seconds.

**Comment by CharliePoole** [comment]
That's expected since the timing is done entirely within the framework code.

**Comment by mintsoft** [comment]
@CharliePoole I've managed to reproduce it on my Windows 10 pro laptop with basically the same behaviour. 11 Seconds normal, 3 with the ModernUI Application open. So it doesn't look like it's limited to Windows Server 2012 R2

**Comment by mintsoft** [comment]
I've also reproduced it on my personal desktop machine running Windows 10 Pro, although I had to reboot in order to get the "slow" time, then I got the same behaviour as 2012 R2 and my laptop

**Comment by Singh400** [comment]
Hi All,

I can reproduce this behaviour. With the ModernUI Application _closed_, tests take around 10-11 seconds to complete. With it _open_ tests take around 3-4 seconds.

My tests can be found [here](https://github.com/Singh400/aoc). I have attached the verbose output for the slow and fast runs.

[slow.txt](https://github.com/nunit/nunit/files/1056314/slow.txt)
[fast.txt](https://github.com/nunit/nunit/files/1056313/fast.txt)

Cheers,
Indy

**Comment by mintsoft** [comment]
@Singh400 Do you have the output xml files from the runs?

**Comment by Singh400** [comment]
@mintsoft These are from my desktop PC running Windows 10 v1703:-

[Slow_TestResult.txt](https://github.com/nunit/nunit/files/1056395/Slow_TestResult.txt)
[Fast_TestResult.txt](https://github.com/nunit/nunit/files/1056396/Fast_TestResult.txt)

Cheers,
Indy

**Comment by mintsoft** [comment]
Thanks, it's interesting. Looking at a few tests there doesn't seem to anything obvious except that the durations are longer on the slower run for all the tests :/ Strange

**Comment by Singh400** [comment]
@mintsoft I get the same behaviour if I use [**AnimationExamples**](https://github.com/Microsoft/WPF-Samples/tree/master/Animation/AnimationExamples) instead of ModernUI app.

Can you confirm?

Cheers,
Indy

**Comment by Singh400** [comment]
Found a better example; [**AnimationTiming**](https://github.com/Microsoft/WPF-Samples/tree/master/Animation/AnimationTiming).

1. Build AnimationTiming. Open and keep the .exe open.

2. Run the test suite. Test execution is slow.

3. In AnimationTiming click "Start Animations" under the tab "RepeatBehavour Example"

4. Run the test suite. Test execution is fast.

5. In AnimationTiming click "Stop" under the tab "RepeatBehavour Example"

6. Run the test suite. Test execution is slow.

Can anyone else confirm?

**Comment by mintsoft** [comment]
@Singh400 Yes I can confirm that is exactly what I'm seeing. Half of those examples didn't compile for me, however the AnimationTiming behaves exactly like you stated. 

This is really odd, it seems like maybe WPF animations are forcing the framework into some sort of high resolution timing mode which is having an effect on the way that NUnit's console runner is scheduling the test execution?

**Comment by Singh400** [comment]
@mintsoft To be honest, I have no idea. I think it is GPU/GFX related. Just played about with stopping/starting this [video](https://www.youtube.com/watch?v=sLprVF6d7Ug). I initially picked the 8K in the hopes it would make the tests fast. It didn't.  Picked 144p, and I am seeing the slow/fast behave as I stop/start the video. I embedded the video in a simple html file to ensure nothing else was having an effect.

I _think_ what is happening is that the WPFs apps hint/invoke the GPU as do playing videos in Chrome. That then has a side-effect in NUnit to make the tests go fast. My knowledge beyond this point is pretty sketchy, so I can only guess and begin to make assumptions.

**Comment by mintsoft** [comment]
> I think what is happening is that the WPFs apps hint/invoke the GPU as do playing videos in Chrome. That then has a side-effect in NUnit to make the tests go fast. My knowledge beyond this point is pretty sketchy, so I can only guess and begin to make assumptions.

Well indeed, this all feels like guesswork, however I was looking at how NUnit schedules the test runs:
https://github.com/nunit/nunit-console/blob/master/src/NUnitEngine/nunit.engine/Runners/AggregatingTestRunner.cs#L160

I can't see anywhere that `LevelOfParallelism` is actually set to anything other than 1.

**Comment by appel1** [comment]
Sounds like this could be related to changes in the windows timer resolution.

**Comment by Singh400** [comment]
@appel1 So I found this [**blog post**](https://randomascii.wordpress.com/2013/07/08/windows-timer-resolution-megawatts-wasted/). Using the utility [**ClockRes**](https://technet.microsoft.com/en-us/sysinternals/bb897568.aspx) I was able to confirm a change in the "Current timer interval" when starting and stopping the animations in AnimationTiming. Which matches the fast and slow behaviour. I also checked when watching a video in Chrome, same changes to the timer interval.

**Comment by mintsoft** [comment]
@Singh400 @appel1  That is *exactly* what it is.

If I leave this running in the background I get the performance benefit:
```
using System;
using System.Runtime.InteropServices;

namespace MakeNunitGreatAgain
{
    class Program
    {
        static void Main()
        {
            int x;
            var desiredIntervalIn100nsUnits = 5;
            NtSetTimerResolution(desiredIntervalIn100nsUnits, true, out x);
            Console.ReadLine();
        }

        [DllImport("ntdll.dll", SetLastError = true)]
        static extern int NtSetTimerResolution(int DesiredResolution, bool SetResolution, out int CurrentResolution);
    }
}
```

**Comment by CharliePoole** [comment]
As stated earlier, I don't think the performance is changing. NUnit uses the timer and converts that to time in seconds. It assumes the resolution is constant. This was good research but I'm not sure if there is a solution.

**Comment by mintsoft** [comment]
> As stated earlier, I don't think the performance is changing

@CharliePoole  I guess it depends on how you define it. It's not that the duration output in the report is wrong. The tests do *actually take longer to run*. The time that's output by `nunit-console` is accurate when compared to me timing it manually.  

Personally I *would* define that as the performance being affected?

**Comment by CharliePoole** [comment]
@mintsoft Obviously, I haven't seen this running. If the time is actually __observably__ different, then we have to ask how changing the timer resolution speeds things up. Is latency due to context switching reduced?

To eliminate as many variables as possible from the discussion, you might try running tests with NUnitLite. In that way, we don't involve any component of NUnit except for the framework and there is no remoting involved. If the phenomenon still shows up, then we should look to the framework for the cause of the difference. If it does not, we would look elsewhere.

**Comment by Singh400** [comment]
@CharliePoole I get the exact same slow/fast behavior using NUnitLite. And for me the time is observably different.

**Comment by Singh400** [comment]
Out of interest. I have compiled my test suite using NUnit v2.6.4 and used the 2.6.4 console runner for that test suite. The duration of the tests is always fast regardless of the windows resolution timer interval (confirmed using ClockRes).

[nunit-2_fast.txt](https://github.com/nunit/nunit/files/1058753/nunit-2_fast.txt)

I also used the same 2.6.4 AoC.dll test assembly with the 3.7.1 console runner and it is always fast regardless of the windows resolution timer interval.

[nunit-3_fast.txt](https://github.com/nunit/nunit/files/1058760/nunit-3_fast.txt)

**Comment by CharliePoole** [comment]
@Singh400 This narrows it down. 

When you run with NUnitLite, only the NUnit 3 framework is involved.

When you run under NUnit V2, no NUnit 3 components are involved.

When you run NUNit V2 tests under NUnit 3, the NUnit 3 console and engine are used, but the framework obviously is not.

So, whatever problem exists (I still have not been able to reproduce it) it resides in the nunit 3 framework. I would suggest to anyone taking on this issue that they use nunitlite for testing, since that simplifies things enormously. Turn off all parallel execution for the same reason.

**Comment by Singh400** [comment]
@CharliePoole I have managed to narrow this problem down further. I went back and compiled my test suite against v3.0.0 and I **could not** reproduce this problem. I kept moving up versions until the problem re-surfaced and it does so at v3.4.0. The last version that did not have this problem was v3.2.1.

Can anyone else reproduce and confirm please?

**Comment by mintsoft** [comment]
> Can anyone else reproduce and confirm please?

@Singh400 confirmed; with my test suite, 3.4.0 takes 9.174 Seconds; 3.2.1 takes 1.704 seconds

**Comment by mintsoft** [comment]
> So, whatever problem exists (I still have not been able to reproduce it)

@CharliePoole The only way I've found to be totally sure when reproducing is to use clockres that @Singh400 linked to before and look at the Current timer interval. By default it is 15.625ms, if it's at that then the run will be slow, anything else and it'll be quicker:

Random applications appear to change the timer interval, so I've been running it on every run to check that chrome or firefox hasn't changed the interval:
```
Clockres v2.1 - Clock resolution display utility
Copyright (C) 2016 Mark Russinovich
Sysinternals

Maximum timer interval: 15.625 ms
Minimum timer interval: 0.500 ms
Current timer interval: 15.625 ms
```
Open VS:
```
Clockres v2.1 - Clock resolution display utility
Copyright (C) 2016 Mark Russinovich
Sysinternals

Maximum timer interval: 15.625 ms
Minimum timer interval: 0.500 ms
Current timer interval: 1.000 ms
```

**Comment by CharliePoole** [comment]
My first reaction is that a program that changes the clock resolution, affecting other programs is somewhat poorly behaved! My second reaction is that maybe NUnit should change it. 😄 

Changing it, however, is platform-specific and that's something we tend to avoid.

I'm tied up with another problem but I'll experiment with the clock-setting program when I have a chance.

**Comment by mintsoft** [comment]
> My first reaction is that a program that changes the clock resolution, affecting other programs is somewhat poorly behaved! My second reaction is that maybe NUnit should change it. 

That is always an option! I'm currently looking through the diff between 3.2.1 and 3.4.0 to see if I can identify something that changed to make NUnit susceptible to that setting change affecting performance. However I don't know what I'm looking for or what things are affected, so it could take a while!

**Comment by Singh400** [comment]
@CharliePoole 

> My first reaction is that a program that changes the clock resolution, affecting other programs is somewhat poorly behaved!

I agree. But something changed between 3.2.1 and 3.4.0 that made NUnit sensitive to the windows resolution timer. I did try and review the changes between the two versions, but given that I am unfamiliar with the architecture of NUnit I gave up.

I put together a ZIP with everything needed to demonstrate the different durations:-

https://github.com/Singh400/nunit/blob/master/TestSuite.zip

The output looks like this:-

```
===== Current Clock Res should be 15ms. If not something is changing it.

Current timer interval: 15.627 ms

===== Running TestSuite compiled with nUnit 3.4.0. This is the SLOW run

    Duration: 7.744 seconds

===== Current Clock Res should be 15ms. If not something is changing it.

Current timer interval: 15.627 ms

===== Now changing the Clock Res

===== Current Clock Res should be 0.5ms. If not something is changing it.

Current timer interval: 0.501 ms

===== Running TestSuite compiled with nUnit 3.4.0. This is the FAST run

    Duration: 1.147 seconds

===== Now resetting the Clock Res

===== Current Clock Res should be 15ms. If not something is changing it.

Current timer interval: 15.627 ms

===== Running TestSuite compiled with nUnit 3.2.1. WITHOUT changing the Clock Res.

    Duration: 0.596 seconds

```

**Comment by mintsoft** [comment]
@Singh400 https://github.com/Singh400/nunit/blob/master/TestSuite.zip is a 404

**Comment by Singh400** [comment]
@mintsoft Just fixed it :)

**Comment by Singh400** [comment]
Playing around with `trace=Verbose` and looking at the resulting log files only reveals one difference. The log file for the run with 3.4.0 has this line in:-

`00:38:55.327 Info  [ 9] WorkItemQueue: NonParallelQueue pausing`

Whereas the log file for 3.2.1 does not.

Snippet for 3.4.0 log file:-

```
00:38:55.303 Info  [ 9] TestWorker: Worker#STA_NP executing Problem12Tests
00:38:55.304 Debug [ 9] WorkItemDispatcher: Directly executing PartOne
00:38:55.311 Info  [ 9] TestWorker: Worker#STA_NP executing Problem13Tests
00:38:55.312 Debug [ 9] WorkItemDispatcher: Directly executing TestThing
00:38:55.323 Info  [ 9] WorkShift: NonParallel shift ending
00:38:55.327 Info  [ 9] WorkItemQueue: NonParallelQueue pausing
00:38:55.327 Info  [ 9] WorkItemQueue: NonParallelQueue stopping - 18 WorkItems processed, max size 17
00:38:55.327 Info  [ 9] TestWorker: Worker#STA_NP stopping - 18 WorkItems processed.
```

Snippet for 3.2.1 log file:-

```
00:38:55.993 Info  [ 9] TestWorker: Worker#STA_NP executing Problem12Tests
00:38:55.993 Debug [ 9] WorkItemDispatcher: Directly executing PartOne
00:38:55.993 Info  [ 9] TestWorker: Worker#STA_NP executing Problem13Tests
00:38:55.993 Debug [ 9] WorkItemDispatcher: Directly executing TestThing
00:38:56.118 Info  [ 9] WorkShift: NonParallel shift ending
00:38:56.118 Info  [ 9] WorkItemQueue: NonParallelQueue stopping - 18 WorkItems processed, max size 17
00:38:56.118 Info  [ 9] TestWorker: Worker#STA_NP stopping - 18 WorkItems processed.
```
I have no idea if that is even related (pure guesswork) but searching for commits between 3.2.1 -> 3.4.0 for the keyword "pausing" reveals this commit: https://github.com/nunit/nunit/commit/bb86737a16ad03ee22777848fa6e3064b9664812

**Comment by CharliePoole** [comment]
I don't see much connection to the timing problem. Pausing a queue doesn't stop time.

It would be a bit of work, but you could continue to try builds between 3.2.1 and 3.4, doing a binary search. All builds for commits to master are on our MyGet feed.

**Comment by appel1** [comment]
@Singh400 That could be it since, unless I'm mistaken, the timer resolution determines the precision for how short time you can sleep. So Thread.Sleep(1) will sleep ~15ms if the timer resolution is 15ms. 

> The system clock ticks at a specific rate called the clock resolution. The actual timeout might not be exactly the specified timeout, because the specified timeout will be adjusted to coincide with clock ticks. For more information on clock resolution and the waiting time, see the Sleep function topic. This method calls the Sleep function from the Windows system APIs.
https://msdn.microsoft.com/en-us/library/d00bd51t(v=vs.110).aspx

**Comment by mintsoft** [comment]
> . So Thread.Sleep(1) will sleep ~15ms if the timer resolution is 15ms.

That's a good call and seems reasonably likely, however in https://github.com/nunit/nunit/commit/bb86737a16ad03ee22777848fa6e3064b9664812 the only Thread.Sleep(1) (or similiar) is within an `#if` for .net 2/3.5/compact and we're .net 4 here. I guess it's also plausible that Thread.Yield may wait for 15ms intervals, but that seems *very* long for a thread's timeslice.

**Comment by Singh400** [comment]
Hi All,

I think I found the commit that introduced this regression; 9086990

Can anyone else confirm please?

Cheers,
Indy

**Comment by CharliePoole** [comment]
Good detective work! We need to figure out just why we thought we needed this. If it was __only__ for CF, we can change it back. @oznetmaster do you remember this?

**Comment by oznetmaster** [comment]
We changed to Sleep(1) from Sleep(0) because Microsoft issued a document that basically stated that Sleep(0) should never be used!

It had nothing to do with the CF build.

I think I referenced the document in the original issue.  I have not searched for it, but it should be there.

**Comment by mintsoft** [comment]
> I think that Thread.Yield () could be used instead, but there were issues with that as well (besides the fact that it does not exist in CF).

IIRC `Thread.Yield` won't allow a thread from another core to be time-sliced in, only threads that are already scheduled for execution on the core that's yielded. I.e. it doesn't force a context switch

**Comment by appel1** [comment]
Is there a reason for the event pump thread to run with highest priority? The commit comment that it fixes a deadlock seems odd to me. Always tricky when you mess with the thread priorities.

**Comment by CharliePoole** [comment]
@appel1 Where is this coming from? The event pump thread should not have highest priority at all. It makes blocking calls to unknown event handlers.

**Comment by appel1** [comment]
@CharliePoole https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/Execution/EventPump.cs#L143

**Comment by CharliePoole** [comment]
Wow! That has been in there since NUnit 2. Back then, it made a bit more sense. We had control over the event handlers and knew what they did. And using a higher priority made it possible for Sleep(0) to work.

**Comment by appel1** [comment]
I'm most likely missing something but I can't observe any issues using nunit-console, nunit-gui or R# if I remove changing the thread priority and sleeps in dequeue even when running the tests in-process. 

What problem is that code trying to solve? Don't have access to any single core non-ht machines to test on so maybe that is it. 

```csharp
        public void Enqueue(Event e)
        {
            // Add to the collection
            _queue.Enqueue(e);

            // Wake up threads that may have been sleeping
            _mreAdd.Set();
        }

        public Event Dequeue(bool blockWhenEmpty)
        {
            do
            {
                // Dequeue our work item
                Event e;
                if (_queue.TryDequeue (out e))
                {
                    return e;
                }

                if (!blockWhenEmpty || Interlocked.CompareExchange(ref _stopped, 0, 0) != 0)
                    return null;
                
                _mreAdd.Wait(-1);

                if (Interlocked.CompareExchange(ref _stopped, 0, 0) != 0)
                    return null;

            } while (true);
        }
```

**Comment by CharliePoole** [comment]
My inclination is to drop the priority-setting and the Sleep and see what happens over the next month. We can adjust before a release if we have to.

**Comment by Singh400** [comment]
Are we any closer to choosing a solution (#2233 or #2236)? It has been 18 days since the issue was raised, and 14 days since the regression was identified in commit 9086990.

It reads like that the majority of people prefer #2236 in which case I can close #2233 and we can just focus on getting #2236 into the next release.

**Comment by CharliePoole** [comment]
The rule is that it requires two committers to approve a merge to master. Neither of these has that yet. Usually, the PR submitter simply makes some changes to get the PR approved, but in this case we appear to have devolved into a more general discussion. 😞 

Since we have two PRs, I'll summarize here...

#2233 Simply changes the Sleep period. It had one review from @jnm2 who requested changes. 
 * He wanted an explanation of why the Sleep was there in the first place, which I think I answered.
 * He wanted a test, which I'm not sure how to write. In any case, the tests of the event queue are fairly extensive.

#2236 Drops the Sleep entirely and eliminates the high priority, which is what I asked for in one of my comments. I think that's the easiest solution. However, it goes on to make a bunch of other changes that don't seem related to this problem. This has one review from @rprouse and comments from me.
 * @rprouse Approved this for merge.
 * I declined to review but made some comments. I'm concerned that the "extra" changes in this PR may break what was fixed a year ago... a general lack of responsiveness in the GUI. Frankly, I would not have known how to do what @oznetmaster did back then, so I don't want to lose it without a good reason. I do wish he had left us more comments though! Since @oznetmaster is not available, I'll go back and do one.

I'm going to add reviews to each PR. My inclination is to use #2233 right away and hold #2236 for more discussion. @oznetmaster is changing continents right now and will eventually become available again.ging #2233 will make the change available on our MyGet feed for anyone who wants an immediate fix.

**Comment by CharliePoole** [comment]
I notice that this still is marked as needing confirmation, although it was confirmed a while back. I'll fix.

**Comment by rprouse** [comment]
Since this is fixed by #2233, should we close this issue, or should we keep it open as we discuss #2236?

**Comment by CharliePoole** [comment]
I'd keep it open, since it has the most thorough discussion. It started out as a kind of puzzle and it was  only gradually turned into a workable bug by folks on the thread.

**Comment by rprouse** [comment]
@jskeet has confirmed that #2233 has resolved his issue as reported in nunit/dotnet-test-nunit#109. #2236 and this issue have been quiet, should we close?

**Comment by CharliePoole** [comment]
I think that the merge of #2233 was intended to close this.

**Comment by mintsoft** [comment]
I think judging by https://github.com/nunit/nunit/issues/2217#issuecomment-310516474 you wanted to keep it open until a decision is made with https://github.com/nunit/nunit/pull/2236

**Comment by CharliePoole** [comment]
Ah... too many issues, too many comments. :smile:

I'd still say close it. The references from the other issue will still be there.

**Comment by mintsoft** [comment]
That's fine with me

**Comment by mintsoft** [comment]
Fixed by @Singh400 in https://github.com/nunit/nunit/pull/2233

**Comment by jnm2** [comment]
By reading @indy-singh's great writeup at https://medium.com/@indy_singh/fixing-nunit-slow-test-execution-a67c284355c4, I became aware that JetBrains opted not to use Sleep(0) because it's not guaranteed to yield, as we've discussed in several threads. Instead, they use [`timeBeginPeriod`](https://docs.microsoft.com/windows/desktop/api/timeapi/nf-timeapi-timebeginperiod)/[`timeEndPeriod`](https://docs.microsoft.com/windows/desktop/api/timeapi/nf-timeapi-timeendperiod) to get Windows to switch to a more accurate resolution. (See https://youtrack.jetbrains.com/issue/PROF-715#focus=streamItem-27-2769768-0-0).
