### ISSUE TITLE
Remove Obsolete Attributes

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#2219]
We obsoleted several attributes like `FixtureSetup` with the 3.0 release. It is probably about time we removed them.

Other candidates for removal are some of the fluent syntax for constraints where we came up with better naming.

**Comment by stevenaw** [comment]
I can take this on.
Can I please be assigned to it?

**Comment by CharliePoole** [comment]
Hi @stevenaw  Sure thing. I sent you an invitation as a contributor. After you accept I'll be able to make assignments to you.

**Comment by stevenaw** [comment]
Thanks @CharliePoole , I've accepted the invite 🙂

**Comment by Lette** [comment]
Just a thought:

If we're following SemVer, we have to consider that removing these attributes might be a breaking change, which will require a bump of the major version. So, this is probably something that shouldn't be done before the 4.0 release.

**Comment by CharliePoole** [comment]
That's a point. Not sure how much into semver everyone is at this point though. @rprouse ?

**Comment by NN---** [comment]
Please do it in 4.0.
It will break my code and many other projects too.

**Comment by CharliePoole** [comment]
@rprouse How do you want to handle this? Should we have a 4.0 Milestone?

**Comment by rprouse** [comment]
If we follow SemVer to the letter, then we probably should hold off on this to a 4.0 release. I think you could argue though that since most of the attributes were obsoleted in 3.0 and there have been many releases to fix the warnings it isn't a breaking change.

AFAIK, the only obsolete feature that isn't a simple search and replace update is the `AssertHelper`. `AssertHelper` has only been obsolete for one release, so removing  it may be pre-mature. Updating everything else should only take a few minutes, even for large solutions. @NN or @Lette is there anything other than `AssertHelper` that you see as a major or difficult change?

Personally, I am surprised that people haven't already updated their code, but maybe I just hate warnings more than other people 😄 I am also surprised that people continue to use `AssertHelper` since it is so limited compared to the other asserts.

**Comment by stevenaw** [comment]
I have some of these changes sitting in a branch. Should I go back to it,
wrap it up, and open a PR?
Or should I wait until we know when we'll be releasing it?

**Comment by NN---** [comment]
I have some obsolete attributes. Not really much work to find and replace.

The main difficulty was ExpectedException attribute removal in 3.0 which I can say was a very good idea.
Too bad it existed from the beginning..

**Comment by rprouse** [comment]
@stevenaw if you want to do a PR, it might help us visualize what is changing and what the impact will be without searching through the code ourselves. If you do the PR, please put a `do not merge` in the description and you should probably hold off on doing more work until we make a final decision on this issue. @Lette and @NN--- have raised good points and I think we should evaluate the impact of this change.

**Comment by stevenaw** [comment]
@rprouse @CharliePoole  I've put up a sample PR here: https://github.com/nunit/nunit/pull/2338
It doesn't look like I'm able to update labels, so I've put a big "DO NOT MERGE" heading in the description

**Comment by stevenaw** [comment]
Sorry, I forgot to structure my GH comment so that this would close automatically.
I'm unable to manually close it. @rprouse @CharliePoole @ChrisMaddock can you guys help out?

I see we're handling obsoleted non-attributes (constraints) in a different issue (https://github.com/nunit/nunit/issues/2342)
