### ISSUE TITLE
Switch to one Release branch

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#2222]
Proposing this as an idea pending discussion and testing.

We are currently creating a release branch for every major release, then adding commits to those release branches for hotfixes. This is working but we are accumulating many branches that we are unlikely to use anymore because we only ever create hotfixes on the latest release. We also have tags for every release, so we can always get back to them.

My proposal is that we delete old `release/3.x` branches. Next, one of two options,

1. Rename the current `release/3.7` branch to `release`. As we prepare each release, we either directly merge latest from master into the release branch, or create a PR to do so.
2. Or, we continue to use `release/3.x` format for releases and delete old release branches once a new release is out.

I like the idea of a long running release branch (option 1), but option 2 has the advantage that it doesn't change our current release process and only requires a small update to our docs. It is probably also the simplest option.

Assigning to myself. My idea, I will do the work if want to do this.

**Comment by CharliePoole** [comment]
As a third option, if we tag on master, then we don't need to keep any release branch after it is merged.

Create a 3.8 branch
Do the release
Merge to master and tag
If a hotfix is needed, create a new branch off the tag on master.

Because of how we do versioning, that part of  it is a little messy, but no worse than what we now do. If we could get away from keeping the version in the repo, then it would be a lot easier.

**Comment by jnm2** [comment]
I like both your and @CharliePoole's suggestions.

**Comment by CharliePoole** [comment]
This is where you need a BD. 😄

**Comment by rprouse** [comment]
I also like @CharliePoole's suggestion although it will require some change to our build process. My only concern with that suggestion is that it could result in CI builds creating new builds using the released build number (plus the CI identifiers) after a release since we usually increment the version number post release.

I would like to see us get to a point where tagging a release builds it on AppVeyor and we just download and test the artifacts before releasing to NuGet. I would like to see us get away from developers building and testing on their own machines. @OsirisTerje has setup an initial build in VSTS, we could even use the build and release management there to fully automate the build and release. It is about time we became more DevOps'y 😄

**Comment by rprouse** [comment]
Closing, we are now on one release branch.

**Comment by stevenaw** [comment]
@rprouse This issue is still open. Did you mean to `Close with comment` in your latest reply?

**Comment by mikkelbu** [comment]
I'll close the issue, as the comment and label indicates that it is closed :)

**Comment by rprouse** [comment]
Thanks
