### ISSUE TITLE
Writing tests for awaitable methods in Visual Basic

### ISSUE THREAD

**Issue by mbrehmer** [nunit/nunit#2224]
Good Day,

I try to write Unit Tests for an existing application, written in Visual Basic.
The language has to be Visual Basic, because its the only .NET language every member of the team can read/write.
I would prefer C#, but that's no option.

Our classes provide some awaitable methods, that should also be tested.

In C# something like the following would work:
```c#
[Test]
public async void TestAsyncCode()
{
    ...
   result = await AsyncClass.AsyncMethod();
   if (!(result = Null) Assert.Pass()
}
```
I have seen such code very often in forums.

Such an async method that returns nothing seems to be impossible to write in VB.
If I try to execute a test like this:
```vb
<Test()>
Public Async Sub TestAsyncCode()
    ...
    result = Await AsyncClass.AsyncMethod()

    If Not result = Nothing Then Assert.Pass()
End Sub
```
I get the following message:
> Async test method must have non-void return type

So I change it to something like this:
```vb
<Test()>
Public Async Function TestAsyncCode() As Task
    ...
    result = Await AsyncClass.AsyncMethod()

    If Not result = Nothing Then Assert.Pass()
End Function
```
This gives me an error message that `Task(Of Boolean)` can not be converted into `Task`
So I change it again into this:
```vb
<Test()>
Public Async Function TestAsyncCode() As Task(Of Boolean)
    ...
    result = Await AsyncClass.AsyncMethod()

    If Not result = Nothing Then Assert.Pass()
End Function
```
Then I get the following message:
> Async test method must have non-generic Task return type when no result is expected

Now I am out of ideas how to write async tests in VB.

I use NUnit 3.7.1.0, NUnit3TestAdapter 3.7.0 and Visual Studio 2013 Professional.

I hope you can help me to find a solution for this issue.
Otherwise we would have to find another framework to write Unit Tests for our .NET Applications, which I would regret.

**Comment by CharliePoole** [comment]
@mbrehmer In NUnit V2, you could have used the C# code you list but in NUnit 3, based on community input, we eliminated it. You would have to substitute `Task` for `void` as the return type. Somebody wrote that `Task` is the `async` equivalent of `void` for most work except for fire-and-forget methods. An NUnit test cannot be fire-and-forget because NUnit needs to wait to see if the test passed or not.

I'm not a VB guy, but I think you want something like this...

```vb
<Test()>
Public Async Function TestAsyncCode() As Task
    ...
    temp = Await AsyncClass.AsyncMethod()

    If Not temp = Nothing Then Assert.Pass()
End Function
```

IOW, don't set result. In C#, one simply returns from a method returning Task, without giving a return value. I think this will accomplish the same in VB - or I hope so anyway. 😄

**Comment by jnm2** [comment]
Returning a value using setter notation in VB.NET would have to be `TestAsyncCode = `, and that's not allowed in an `Async` method IIRC. (And it should be banned in any method, but I digress.)

You definitely want:
```c#
<Test>
Public Async Function TestAsyncCode() As Task
```

I don't know what's causing the error that "`Task(Of Boolean)` can not be converted into Task" without seeing the rest of the method but it is not NUnit-related.

Side note. That `If` statement won't cause an error if `temp = Nothing`. This may be what you're after:

```c#
<Test>
Public Async Function TestAsyncCode() As Task
    Dim result = Await AsyncClass.AsyncMethod()

    Assert.That(result, [Is].Not.Null)
End Function
```

**Comment by mbrehmer** [comment]
> I don't know what's causing the error that "Task(Of Boolean) can not be converted into Task" without seeing the rest of the method but it is not NUnit-related.

You are right Joseph, This error came from the async method itself and was the origin of my issue.
That's the Problem, if you have to use the NUnit3 test adapter for Visual Studio. All errors are shown as caused by the test, so it's quite hard to see their real origin, even if you have the stack trace.

Now everything works fine.
Thank you guys for your great help.
