### ISSUE TITLE
Several tests for nunit fails when run in a development environment with certain regional settings

### ISSUE THREAD

**Issue by Lette** [nunit/nunit#2228]
My development PC has its regional settings set to Swedish. When running `.\build -t test` in the nunit repository I get 7 test failures in each project. Worse yet, when switching to Turkish regional settings I get 48 test failures in the 4.5/4.0 projects, 46 test failures in the 3.5/2.0 projects and another 16 in the netstandard projects.

For now, this is only a problem for contributors that do not have regional settings that are English (or any invariant-like setting), and even then it's an easy fix - just change your regional settings to "English (U.S.)"  and re-run the tests.

I assume that the test suite should not have a dependency on the regional settings of the computer it's running on.

Is it safe to say that all output from nunit should be English/invariant? Some of the test failures are likely the result of the code not being explicit about culture in calls to `.ToString()` and its culture-dependent brethren. I'd guess that that culture in most (all?) cases should be `CultureInfo.InvariantCulture`.

I'm happy to help, if you so wish.

**Comment by Lette** [comment]
A PR for this is already being discussed - #2185. This issue might be resolved by that PR.

**Comment by jnm2** [comment]
[http://www.moserware.com/2008/02/does-your-code-pass-turkey-test.html](Does Your Code Pass The Turkey Test?) 😆

**Comment by CharliePoole** [comment]
When I was at Microsoft we used to get tons of bugs from testers who ran in the Turkish culture. We hated them for it! 😄

**Comment by Lette** [comment]
I've made all tests pass under Swedish, Turkish and English (U.S.) cultures.

My code is, however, depending on #2179 being closed by merging #2185 into master, which will take care of the last (first?) seven failing tests.

I'll wait for your decision on that one, before I make a PR.

**Comment by rprouse** [comment]
This issue is marked as an idea but hasn't had contributions in years so I am closing. If anyone is interested in working on this idea, post your interest and the team will consider reopening.
