### ISSUE TITLE
nunitlite.tests.exe Win10 system command line console

### ISSUE THREAD

**Issue by noobwu** [nunit/nunit#2231]
nunitlite.tests.exe  version 3.7.1
nunitlite.tests.exe  --testlist=Tests.dll
runtime at NET 4.5
![qq 20170609001847](https://user-images.githubusercontent.com/4328356/26939534-2af2201a-4caa-11e7-8bf1-928dca5ac545.png)

**Comment by CharliePoole** [comment]
The `--testlist` option takes the name of a text file containing a list of tests to be run from the assembly or assemblies specified elsewhere on the command-line.

Please read the documentation: https://github.com/nunit/docs/wiki/Console-Command-Line

**Comment by jnm2** [comment]
@CharliePoole OP might be saying that he's having issues with the console encoding. I don't know enough about NUnitLite to know if setting [`Console.OutputEncoding`](https://msdn.microsoft.com/en-us/library/system.console.outputencoding.aspx) to `Encoding.Unicode` is in scope for it.

**Comment by jnm2** [comment]
@noobwu Please clarify what you are expecting and how it's different from what is actually happening.

**Comment by CharliePoole** [comment]
@jnm2 According to the display he used `--testlist=test.dll`. The console is reading `test.dll` a text file and listing all the "lines" it finds in it as "test" names.

**Comment by jnm2** [comment]
@CharliePoole I'll pay more attention.
