### ISSUE TITLE
NUnit Adapter 3.7.0.0 vs2017 引发类型为“System.OutOfMemoryException”的异常。

### ISSUE THREAD

**Issue by noobwu** [nunit/nunit#2232]
NUnit Adapter 3.7.0.0: Test discovery starting
Assembly contains no NUnit 3.0 tests: test.dll
Exception System.OutOfMemoryException, Exception converting Tests.BooleanTests.Can_store_and_read_bool_values
引发类型为“System.OutOfMemoryException”的异常。

**Comment by CharliePoole** [comment]
You will have to provide a great deal more information before we can treat this as an issue.

Does your `test.dll` contain any NUnit 3 tests? The message says not. It's not clear where the OOM exception is coming from.

**Comment by jnm2** [comment]
> It's not clear where the OOM exception is coming from.

I'm pretty sure it's [Mono.Cecil causes OutOfMemoryException with new .csproj PDBs](https://github.com/nunit/nunit3-vs-adapter/issues/296). If that's the case, [this](https://github.com/nunit/nunit3-vs-adapter/issues/296#issuecomment-285698000) is the workaround.

**Comment by noobwu** [comment]
test.dll contain NUnit 3 tests
nunit version  3.6.1.0 
NUnit Adapter 3.7.0.0: Test discovery starting
Assembly contains no NUnit 3.0 tests: Test.dll
Exception System.OutOfMemoryException, Exception converting 
Tests.Can_store_and_read_bool_values
引发类型为“System.OutOfMemoryException”的异常。
test code eg:
    [Test]
        public void Can_store_and_read_bool_values()
        {
            using (var db = OpenDbConnection())
            {
                db.DropAndCreateTable<Boolies>();

                var boolies = new List<Boolies> {
                  new Boolies { plainBool = true,  netBool = true },
                  new Boolies { plainBool = false, netBool = true },
                  new Boolies { plainBool = true,  netBool = false },
                  new Boolies { plainBool = false, netBool = false },
                };
                db.InsertAll(boolies);

                var target = db.Select<Boolies>();

                Assert.AreEqual(boolies.Count, target.Count);

                for (int i = 0; i < boolies.Count; i++)
                {
                    Assert.AreEqual(boolies[i].netBool, target.ElementAt(i).netBool);
                    Assert.AreEqual(boolies[i].plainBool, target.ElementAt(i).plainBool);
                }
            }
        }

**Comment by rprouse** [comment]
@noobwu as @jnm2 stated, the workaround for your issue is at https://github.com/nunit/nunit3-vs-adapter/issues/296#issuecomment-285698000

I think that if you run your tests with `nunit3-console.exe` your tests will work. It is a bug in the Visual Studio adapter.

**Comment by rprouse** [comment]
I am going to close this issue as a duplicate. Please feel free to continue to comment here, we will see your responses.
