### ISSUE TITLE
Provide a helper method similar to TestBuilder.RunTest

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2243]
I used to be able to do this so that I could debug the test every time I pressed F5:

```c#
public static class Program
{
    public static void Main() => new TheFixture().TheTest();
}

[TestFixture]
public sealed class TheFixture
{
    [Test]
    public void TheTest() => Assert.That(...);
}
```

Now that that is not possible, it would be great to be able to directly run tests like this:
```c#
    public static void Main() => NUnitTestRunner.Run<TheFixture>(_ => _.TheTest());
```

What I definitely don't want is to have to reference any assembly other than nunit.framework.dll just for this.

Rough draft of the new API:
```c#
public static void Run<TFixture>(Expression<Action<TFixture>> instanceTestMethod)
{
    if (instanceTestMethod == null) throw new ArgumentNullException(nameof(instanceTestMethod));
    if (!(instanceTestMethod.Body is MethodCallExpression call) ||
        call.Arguments.Count != 0 ||
        call.Object != instanceTestMethod.Parameters[0]) throw new ArgumentException(nameof(instanceTestMethod), "Test method expression must be a parameterless call to an instance method on the TFixture parameter.");

    var runner = new NUnitTestAssemblyRunner(new DefaultTestAssemblyBuilder());
    var fixtureType = typeof(TFixture);
    runner.Load(fixtureType.Assembly, new Dictionary<string, object>());

    var result = runner.Run(TestListener.NULL, TestFilter.FromXml(new TNode("filter")
    {
        ChildNodes =
        {
            new TNode("and")
            {
                ChildNodes =
                {
                    new TNode("class", string.IsNullOrEmpty(fixtureType.Namespace) ? fixtureType.Name : $"{fixtureType.Namespace}.{fixtureType.Name}"),
                    new TNode("method", call.Method.Name)
                }
            }
        }
    }));

    if (!result.HasChildren) throw new ArgumentException($"{call.Method.Name} is not an NUnit test method.", nameof(instanceTestMethod));
            
    if (result.ResultState.Status != TestStatus.Passed)
        throw new Exception(result.Message);
}
```

**Comment by CharliePoole** [comment]
Although we are reorganizing things, I think we should follow existing protocols for now and only change with notice to everyone when and if we decide differently.

So... marking something as an enhancement (usually coupled with adding it to the Backlog) has always given anybody - team or contributors - the right to self-assign it and implement it. If we did that here, then the only review would be in the PR and that's a bad time for someone to say "I don't think we should do this." 

So... I labeled this as an idea and put it under the Discussion swim lane.

Discussion from me... I don't think we should do this. We don't need any more APIs and this is precisely the kind of thing that could be maintained as a contribution. I've thought of doing that myself, perhaps as a gist, perhaps as some other form of source code that we provide.

Beyond that, isn't this related very closely to #2242? If the solution there is to give an error message, then of course, you would still want this. But we don't know what the solution will be yet.

Anyway that's my view and only mine. 😄 Others?

**Comment by rprouse** [comment]
In my opinion, we already have too many ways to run tests between the console runner, nunitlite, nunitlite.runner...

This just seems like an even lighter nunitlite.

**Comment by jnm2** [comment]
Yes. The motivation is that I really don't want is to have to reference any assembly other than nunit.framework.dll just for this. This is just for debugging.

**Comment by CharliePoole** [comment]
Now that we are able to once again run tests directly, should we close this issue?

**Comment by rprouse** [comment]
@jnm2 I am going to close this. Rant away if you feel strongly otherwise 😄

**Comment by jnm2** [comment]
Yes, the primary motivation is satisfied now without this helper. :D
