### ISSUE TITLE
Expose the formatter chain to formatters

### ISSUE THREAD

**Issue by appel1** [nunit/nunit#2246]
Currently I don't see any way to continue using the registered and built-in formatters in the TestContext.AddFormatter delegate. 

Right now I do the following but I'm guessing I'm not supposed to use the classes from the NUnit.Framework.Internal namespace. 

```csharp
TestContext.AddFormatter<KeyValuePair<string, List<object>>>(
  value =>
  {
    var keyValue = (KeyValuePair<string, List<object>>)value;
    return "<" + TestExecutionContext.CurrentContext.CurrentValueFormatter(keyValue.Key) + ", " + TestExecutionContext.CurrentContext.CurrentValueFormatter(keyValue.Value) + ">";
  });
```

**Comment by CharliePoole** [comment]
I see your point. I started to show you how to do it but then I realized you want the Value to be displayed using the formatters recursively. Let me give this a think!

**Comment by rprouse** [comment]
I am closing old Idea issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
