### ISSUE TITLE
Test cases skipped

### ISSUE THREAD

**Issue by cncharman** [nunit/nunit#2247]
We have two TFS servers which integrated with NUNIT to execute automatic unit test.
Every night the same unit test dynamic library will be loaded and executed, but with different results as below.

The two servers all are installed with WIN7.

**Server 1** 
... Total: 50, Passed: 25, Failed: 0, Other: 25 Click here for details

**Server 2**
... Total: 50, Passed: 50, Failed: 0, Other: 0 Click here for details

I checked the unit test result files, and found that the former 25 test cases in Server 1 are skipped.
Is there any system setting, environment variables or NUNIT setting wrong in Server 1?
Many thanks.

**Comment by CharliePoole** [comment]
Clearly something is different on Server 1. Take the NUnit console output from both of them, start at the top and see what is different in the listing. First thing to check is the version of the console. If nothing turns up there, do the same with the XML output. You can post any suspicious differences here.

**Comment by cncharman** [comment]
I found a difference in the output cleanupScript.log

Server 1
Local\VSEQT\QTAgent\4202f1a8-5846-4ad9-b67b-9e44741f2061\SHCT008\Deployment>set TotalAgents=2 

Server 2
AppData\Local\VSEQT\QTAgent\cafac896-a9be-451c-825e-83447929ac4f\SH296A\Deployment>set TotalAgents=1 

I need only one agent in server 1.
How can I set to unify the difference.

**Comment by CharliePoole** [comment]
TotalAgents is not an NUnit thing, although we have an --agents command-line option. I guess this is TFS.

**Comment by rprouse** [comment]
Are you using the NUnit Visual Studio adapter and the TFS Test task in your build, or are you integrating some other way? Is there anything special about your tests? For example, do they have Platform attributes or any Include/Excludes?

Are these two build agents running off the same TFS build definition?

@OsirisTerje can you help here?
