### ISSUE TITLE
OneTimeSetup runs multiple times if Test throws exception

### ISSUE THREAD

**Issue by evancam** [nunit/nunit#2248]
Using v3.6.1/3.7.1 from nuget.
NUnit Adapter 3.7.0.0

Nunit seems to re-run OneTimeSetup if a test fails due to an exception being thrown. If multiple tests throw exceptions, it will  It does not re-run OneTimeSetup if the test failed due to an assertion.

This behaviour can be seen through the following code by debugging, or observing the output of the setup below. One of the tests will fail, the other will pass and the 'Output' it prints will show that setup has run twice.

```
[TestFixture]
[TestFixtureSource(typeof(TestSource),"Test")]
public class TestClass
{
    static int run = 0;

    public TestClass(int source)
    {
        int test = source;
    }

    [OneTimeSetUp]
    public void oneTimeSetup()
    {
        TestSource.incrementSetup();
    }

    [Test Retry(4)]
    public void TestMethod()
    {
        if (run > 0)
        {
            TestSource.printSetup();
            Assert.Pass();
        }
        run++;
        throw new Exception();
    }
}
```

With the following TestSource fixture data:

```    
class TestSource
{
    private static int setup = 0;

    public static void incrementSetup()
    {
        setup++;
    }

    public static void printSetup()
    {
        Console.WriteLine($"Number of OneTimeSetups: {setup}.");
    }

    public static IEnumerable Test
    {
        get
        {
            yield return new TestFixtureData(1);
            yield return new TestFixtureData(2);
        }
    }
}
```
I realize that failing on Exceptions is different than an assertion failure, but I'm assuming the desired behaviour of OneTimeSetup is to only run once.

**Comment by CharliePoole** [comment]
The example you give creates two fixture instances. OneTimeSetUp in a fixture class is intended to use in initializing each instance. For that reason, your OneTimeSetUp will be run twice. This happens whether there is an exception or not, although you may not have noticed it without the exception.

I'll give you a chance to reply before closing this in case I have misunderstood the question.

**Comment by evancam** [comment]
Ah yes, I did not notice it initially with some changes I was making to the configuration. My mistake.
