### ISSUE TITLE
Randomizer.NextGuid()

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2251]
Creating a random GUID is not as straightforward as setting all 128 bits randomly. Ref: https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_.28random.29

https://github.com/nunit/nunit3-vs-adapter/issues/331 is an example of where someone needs random GUIDs using the repeatable randomness from `TestContext.CurrentContext.Random`.

**Comment by CharliePoole** [comment]
Doesn't seem like an easyfix to me! Requires knowledge of the different GUID types and how to generate them. (easyfix label is intended to attract new and inexperienced folks)

**Comment by jnm2** [comment]
Perhaps not. Ideally we'll copy whatever CoCreateGuid is doing (what Guid.NewGuid wraps).

**Comment by jnm2** [comment]
We can duplicate what `Guid.NewGuid` is doing by masking 128 random bits with `ffffffff-ffff-0fff-3fff-ffffffffffff`.

<details>
  <summary>Derivation</summary>

```c#
var randomnessMask = new byte[16];

fixed (byte* pRandomnessMask = randomnessMask)
{
    var pLow = (ulong*)pRandomnessMask;
    var pHigh = (ulong*)pRandomnessMask + 1;

    for (var i = 0; ; i++)
    {
        var left = Guid.NewGuid().ToByteArray();
        var right = Guid.NewGuid().ToByteArray();

        var didChange = false;

        fixed (byte* pLeft = left)
        fixed (byte* pRight = right)
        {
            var newLow = *pLow | *((ulong*)pLeft) ^ *((ulong*)pRight);
            if (newLow != *pLow)
            {
                didChange = true;
                *pLow = newLow;
            }
            var newHigh = *pHigh | *((ulong*)pLeft + 1) ^ *((ulong*)pRight + 1);
            if (newHigh != *pHigh)
            {
                didChange = true;
                *pHigh = newHigh;
            }
        }

        if (didChange) Console.WriteLine($"{i} iters: {new Guid(randomnessMask)}");
    }
}
```
</details>

**Comment by jnm2** [comment]
So, the entire implementation will look like this:

```c#
public Guid NextGuid()
{
    var bytes = new byte[16];
    NextBytes(bytes);
    bytes[7] &= 0x0f;
    bytes[8] &= 0x3f;
    return new Guid(bytes);
}
```

All that remains is writing tests.

**Comment by jnm2** [comment]
And code comments.

**Comment by CharliePoole** [comment]
@jnm2 Where does the code come form that you used and how is it licensed?

**Comment by jnm2** [comment]
@CharliePoole both written from scratch in VS by me as a contribution to NUnit under the repo licence. We

**Comment by jnm2** [comment]
But it needs comments.

**Comment by CharliePoole** [comment]
Sorry, you said something about "copying" so I thought you meant code. We can use other open source code but only if the license is compatible.

**Comment by jnm2** [comment]
Oh, that makes sense! I meant copy the _behavior_ of CoCreateGuid.

**Comment by MikeFH** [comment]
If no one is working on this, I'd like to give it a try.

**Comment by CharliePoole** [comment]
Since he posted code, I assumed @jnm2 was working on this, but I see he added up-for-grabs so you are welcome to take it!

**Comment by jnm2** [comment]
@MikeFH It's yours!

**Comment by jnm2** [comment]
Let us know if you need anything.
