### ISSUE TITLE
Parallel execution of test methods within a fixture is not thread safe

### ISSUE THREAD

**Issue by LirazShay** [nunit/nunit#2252]
As @CharliePoole mentioned here: https://github.com/nunit/nunit/issues/164#issuecomment-308157832
When running test methods within a fixture in parallel, all tests in a fixture use the same instance.
This makes this feature not usable in most cases for the following reasons:
1. My test class use shared resources, for example - fields that are declared in the class, now - 2 tests are running in parallel may change the same field and will cause to change the results
2. I use SetUp to create new instance and TearDown to dispose, but when I use Parallel Children - tests are failing sometimes because after Dispose because TearDown of first test then 2nd test called disposed object and so on, there can be many cases.
The solution is that when user run test methods within a fixture in parallel, create separate instance for each thread, it's so reasonable to do so. 
I'm attaching example code to reproduce it:
```cs
public class Calculator : IDisposable
    {

        public int Add(int first, int second)
        {
            if(isDisposed)
                throw new ObjectDisposedException("");
            return first + second;
        }

        private bool isDisposed;
        public void Dispose()
        {
            isDisposed = true;
        }
    }

    [Parallelizable(ParallelScope.Children)]
    [TestFixture]
    public class Tests
    {
        private Calculator _calculator;

        [SetUp]
        public void TestSetUp()
        {
            _calculator = new Calculator();
        }
        
        [TearDown]
        public void TestTearDown()
        {
            _calculator.Dispose();
            _calculator = null;
        }

        [Test]
        public void Test1()
        {
            System.Threading.Thread.Sleep(1000);
            var result = _calculator.Add(1,2);
            Assert.AreEqual(3,result);
        }

        [Test]
        public void Test2()
        {
            var result = _calculator.Add(1, 1);
            Assert.AreEqual(2, result);
        }
    }
}

```
**In the example above, Test 2 passed, Test 1 failed:**
**But when running the tests Not in parallel - both passed**
> at NUnitParallelFixture.Tests.Test1() in C:\NUnitParallelFixture\NUnitParallelFixture\Class1.cs:line 51
> --TearDown
>    at NUnitParallelFixture.Tests.TestTearDown() in C:\NUnitParallelFixture\NUnitParallelFixture\Class1.cs:line 43
> Result Message:	
> System.NullReferenceException : Object reference not set to an instance of an object.
> TearDown : System.NullReferenceException : Object reference not set to an instance of an object.

**Comment by ChrisMaddock** [comment]
There's an open issue discussing this as a proposition below. I suggest you add your thoughts there, I'll close this one as a duplicate. 🙂 

https://github.com/nunit/nunit/issues/2105

**Comment by rodolfoleal** [comment]
@ChrisMaddock  In the Issue [#2105](https://github.com/nunit/nunit/issues/2105) you refer this one?
 What was the proposed solution?

**Comment by jnm2** [comment]
Please see https://github.com/nunit/nunit/issues/2574 for a proposal to add an instance-per-test-case-feature.
