### ISSUE TITLE
EqualTo on ValueTuple with Nullable unexpected

### ISSUE THREAD

**Issue by Aurelianus** [nunit/nunit#2254]
I recently observed unexpected test failure when comparing ValueTuples with nullable types.

This works:
`(string name, int val) tuple = ("Hello", 3);`   
`Assert.That(tuple, Is.EqualTo(("Hello", 3)));`

Fails with msg: "Message:   Expected: (Hello, 3) (Int32])  But was:  (Hello, 3) (Int32]])"
`(string name, int? val) tuple = ("Hello", 3)`
`Assert.That(tuple, Is.EqualTo(("Hello", 3)));`

With correct type spec it works again:
`(string name, int? val) tuple = ("Hello", 3);`
`Assert.That(tuple, Is.EqualTo(("Hello", (int?)3)));`

I would expect one of this:

1. check succeeds

1. message shows type difference with Int32? or Nullable<Int32>

**Comment by jnm2** [comment]
@nunit/framework-team I'm strongly in favor of bringing this philosophy over to NUnit from our discussions at dotnet/rosyn and dotnet/csharplang:

 1. Tuples (the C# language feature) are intended to be as much as possible like an argument list.
    Operations on a tuple should be distributable as operations on each individual value.
    For example, `(a, b) == (c, d)` should be synonymous with `a == b && c == d` (coming in C# 7.1 I believe).
    
 2. Tuples (the language feature) are realized through the `ValueTuple` type as an implementation detail. 
    Unlike other types, the `ValueTuple` type has no significance except in how it accomplishes the philosophy
    of the tuple language feature. It's valid for the compiler to even optimize away usages of the ValueTuple
    type even though cannot know the implementation of `ValueTuple` at runtime.

I propose we follow the philosophy behind tuples by treating ValueTuples specially and comparing only the values, intentionally disregarding the generic type parameters on the ValueTuple.

This enables people to use tuples in assertions, thinking only in terms of the structure and the types of the values. People shouldn't have to additionally be considering the constructed type of the ValueTuple itself; that only detracts from the purpose of the test. In other words, @Aurelianus' first expectation.

NUnit does not use static typing for assertions; everything is cast or boxed to `object`. To treat a tuple as no more than individual ordered arguments, and to be consistent with NUnit's dynamic type inspection, each tuple value should also have the same treatment- only the value's actual type should matter, not the static type of the tuple field.

Thoughts?

**Comment by CharliePoole** [comment]
That makes sense to me so long as your intention is not to go crazy with conversions.... i.e. "5" != 5. (We are not PL/I).

However, before we code I'd like to understand why this isn't working. I assume that we are falling through all of our special cases and using the ValueTuple Equals override. If Tuples are intended to work in the way you describe, why doesn't its Equals do the job correctly? Why is it necessary to add special handling on our side? Also, what's with the expected/actual message? We should be using the output of ToString() for the tuple, but what I see doesn't make much sense.

**Comment by jnm2** [comment]
@CharliePoole
> If Tuples are intended to work in the way you describe, why doesn't its Equals do the job correctly?

At runtime, the static type information does not exist to implement the equivalent of `a == c && b == d` via  `(a, b) == (c, d)`. That has to be something the compiler does by circumventing the ValueTuple type. And that's why I stressed in point 2 that the `ValueTuple` type and its `Equals` method are not the way to go. `ValueTuple` only matters so long as it is able to support the tuple language feature- where they differ, `ValueTuple` is wrong, tuple semantics are correct. `ValueTuple` is a solution-space implementation detail but we want to keep people only thinking in problem-space.

Neil Gafter explained it well here: https://github.com/dotnet/corefx/pull/10417#issuecomment-239648257

**Comment by jnm2** [comment]
To make this more concrete, the intention of this code will never be to make sure the function's static return type is correct. It will always be to make sure the multiple returned values are correct:

```c#
(string, int?) Foo() => return ("Hello", 3);

Assert.That(Foo(), Is.EqualTo(("Hello", 3)));
```

**Comment by CharliePoole** [comment]
OK... when I commented on your idea of ignoring types, I didn't mean the type of the tuple, but the type of the items. It seems to me that we need to compare Item1 to Item1, Item2 to Item2, etc. using __NUnit__ equality rules, not C# rules. I don't want to have something like

```C#
Assert.That( 5.0, Is.EqualTo(5));
Assert.False( ( "Hello", 5.0), Is.EqualTo( ("Hello", 5) );
```

**Comment by jnm2** [comment]
@CharliePoole Ah, got it. Thanks for clarifying that. I agree that the value-to-value comparisons should be NUnit comparisons, and that doing it any other way would not be following the philosophy of tuples.

In other words I believe that whether this succeeds:
```c#
Assert.That(("Hello", 5.0), Is.EqualTo(("Hello", 5));
```
Should be exactly the same as whether this succeeds:
```c#
Assert.That("Hello", Is.EqualTo("Hello"));
Assert.That(5.0, Is.EqualTo(5));
```

For any values of `"Hello"` and `"5.0"` 😄

**Comment by jnm2** [comment]
Aka `Is.EqualTo` being distributive. We should also see if any other kind of constraint needs to be distributive with tuples.

**Comment by CharliePoole** [comment]
Separate issue, hopefully. 😉

**Comment by CharliePoole** [comment]
Please finish triaging this and then either take it or leave it for somebody else!

**Comment by jnm2** [comment]
@nunit/framework-team If you're comfortable with taking the design I proposed, I wonder what priority we should set for this? I'd be happy to take this one but I have my hands full and don't want to prevent someone else from doing it sooner.

**Comment by CharliePoole** [comment]
@jnm2 You're a team member and even a core team member. You can feel free to give stuff the priority you believe. That's what triaging involves. Hint: almost everything is normal, by definition, unless you have a reason to think it is low or high. Critical, means stop the presses, we need a new release tomorrow. Seriously... unless the project lead decides to change it, all committers have the authority to fully triage something. If someone disagrees, they will tell you, which is not a big deal either.

Also, I think we already did the design, aside from that level somebody does while coding.

**Comment by jnm2** [comment]
@CharliePoole Cool.

> Also, I think we already did the design, aside from that level somebody does while coding.

Okay. Is it usually fine to just make a proposal, hear from only one other framework team member, and go ahead and implement it or ask someone to take it on, and then rely on other team members being able to give their feedback on if and what we're doing during the PR in case the framework team doesn't end up with consensus?

**Comment by jnm2** [comment]
I'm going to put this in the backlog as up-for-grabs. That means PRs are welcome from @Aurelianus or anyone else who would like to see this get done sooner. Please comment if you'd like to contribute so we can assign you to avoid race conditions. :smile:

**Comment by CharliePoole** [comment]
Bearing in mind that our new approach to decentralization could mean that something changes in the future, here's how we have done it in the past.

A couple of committers will discuss how to do it and try to involve others to the extent that there seems to be a potential for controversy. That means we need to use judgement not only in how we want to implement it but also in realizing when an issue may have significant room for seeing things differently. So, we're free to use our judgement, which means we are also free to judge wrongly. If we are wrong, we find that out in the PR, which is inconvenient for us but at least doesn't break anything. 

In this case, once you and I got our terminology straight, we seemed to both see the same obvious solution. So, in your place, I would just put this up for self-assignment. Actually, I was about to do that for you, but I decided to prompt you to do it instead. 😄 

BTW... not the same issue, but this makes me wonder if we shouldn't be doing the same for structs.

**Comment by jnm2** [comment]
@CharliePoole Thanks. It wouldn't be fair to self-assign this because I'm not going to get to it for a while.

Re: doing the same for structs- unlike tuples, structs do have structure and coherence. We shouldn't be accessing inaccessible fields or assuming it's meaningful to treat multiple fields in isolation. I think `.Equals` is exactly the right thing to do for structs in general.

**Comment by CharliePoole** [comment]
I added to Backlog, which signals to us that we can self-assign and work on it. We're supposed to do a design next, before coding, according to the labels. I'm removing the design label so somebody can program on it. All this, of course, presumes that people know how we use labels and pipelines. New contributors may not. 😄

**Comment by jnm2** [comment]
I should have removed `design` after the conversation about waiting for the rest of the framework team. Things will go smoother when there isn't so much meta. 😆

**Comment by rprouse** [comment]
One question that may be already answered above and I missed it. The plan is to iterate through each value in the tuple and compare it to the value in the second tuple. Will we use .NET equality for each of those values, or will we recursively pass each value back into the `NUnitEqualityComparer`? I would assume the later since that is what we do for other "collections".

**Comment by jnm2** [comment]
@rprouse I believe we should recursively pass each value back into NUnitEqualityComparer. This is why: https://github.com/nunit/nunit/issues/2254#issuecomment-308754988

**Comment by rprouse** [comment]
@jnm2 I agree, I just wanted to make sure it was clear if anyone picks up this issue. If it is one of us that takes this issue, it might also be a good opportunity to refactor that class into separate classes with one that pulls them all together. It is getting to be a bit of a monster.

**Comment by mikkelbu** [comment]
I can try to supply a PR for this. 

@rprouse Wrt. the refactoring, would something like a new folder `Comparers` with one class/file per (major) comparer be appropriate? E.g. a `DirectoryInfo`-comparer, a `Arrays`-comparer etc.

**Comment by rprouse** [comment]
@mikkelbu yes, a sub-folder would be best, maybe under Internal. You can also make the classes internal so that users don't use them by mistake. internal will allow you to access them from the test project.
