### ISSUE TITLE
Console.WriteLine() does not write to console when running`dotnet test`

### ISSUE THREAD

**Issue by ayoung** [nunit/nunit#2257]
I'm running `dotnet test` targeting netcorapp1.1. Within the test I'm executing a console write but that text never makes it to the output on the screen.

**Comment by rprouse** [comment]
Are you using `dotnet-test-nunit` or the alpha of the adapter for your tests? In other words, `project.json` or `csproj`? This issue needs to be moved to the correct repository.

**Comment by ayoung** [comment]
i am using the alpha adapter. csproj.

**Comment by rprouse** [comment]
Thanks, I am going to move to that repository then. Please track it there.

**Comment by rprouse** [comment]
Issue moved to [nunit/nunit3-vs-adapter #343](https://github.com/nunit/nunit3-vs-adapter/issues/343) via [**ZenHub**](https://www.zenhub.com/)
