### ISSUE TITLE
Up-for-grabs.net tag updates

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2258]
Here's what I'm thinking of adding so that we're more visible at http://up-for-grabs.net:

```diff
+ NUnit
  .NET          
+ .NET Core     
+ cross-platform
  C#            
  testing       
+ unit testing  
  TDD           
+ OSS           
```

`NUnit`: Right now nothing happens if people search for 'nunit'. This will change that.
`.NET Core`, `cross-platform`: In case people are looking for such projects to contribute to
`unit testing`: It's a popular tag; we should be in the list
`OSS`: Seems redundant, but it's also a popular tag and it's applicable

Existing tags I skipped because I didn't think they were relevant enough:
`library`
`framework`
`integration testing`
`.NET Framework`

Thoughts?

**Comment by ChrisMaddock** [comment]
Looks good. :-)

**Comment by rprouse** [comment]
Maybe add the common alternatives dotnet and dotnetcore?

**Comment by jnm2** [comment]
@rprouse Sure, that makes sense. We'd be the first project to use those.

**Comment by jnm2** [comment]
@nunit/framework-team I'm about to submit a PR based on this and switching our tag from `easyfix` to `up-for-grabs`.

**Comment by jnm2** [comment]
See https://github.com/up-for-grabs/up-for-grabs.net/pull/654

**Comment by rprouse** [comment]
Related PR is merged. Closing.
