### ISSUE TITLE
Can't get Parallelism to work with NUnit 3.7.1

### ISSUE THREAD

**Issue by agray** [nunit/nunit#2260]
I have a very similar issue #2253.

I have also consulted the docs related to Parallelism but its not making sense to me yet.

I am consuming NUnit v3.7.1 from NuGet and using nunit-console v3.6.1.  I have two Test fixtures both inheriting from a couple of base classes that provide a [TestCaseSource(typeof(MyClazz))] enumeration.  See #1118 for more information on this structure.

While it continues to execute against SauceLabs it is only running in sequence.  I am unable to get anything  at all running in parallel.  Neither across Test Fixtures (of which I have 2) or within.  In total I have 14 test cases that unfortunately only execute one at a time.

I have the following Parallel related attributes:

**AssemblyInfo.cs**

    [assembly: Parallelizable(ParallelScope.Children)]
    [assembly: LevelOfParallelism(8)]

**MyRoot**

    [TestFixture(ParallelScope.Children)]  //If I remove this argument and add [Parallelizable] the whole application just hangs
    public abstract class MyRoot

    [SetUp]
    [Parallelizable]
    public void Setup() { ... }

Do I need to add [Parallelizable] to the Teardown as well?  I haven't at the moment as adding it also made the whole application hang.

As I said earlier this will execute but not in parallel.  I must be missing something really simple.

The command I run is:

    "C:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe" Saucery\NUnit\Version3\Saucery3Tester\bin\Release\Saucery3Tester.dll --result:junit-selenium-testsuite.xml;transform=nunit3-junit.xslt --trace=Verbose

and the output I get is:

    NUnit Console Runner 3.6.1 
    Copyright (C) 2017 Charlie Poole

    Runtime Environment
       OS Version: Microsoft Windows NT 10.0.14393.0
       CLR Version: 4.0.30319.42000

    Test Files
        MyApp\NUnit\Version3\MyAppTester\bin\Release\MyAppTester.dll

    Run Settings
    DisposeRunners: True
    InternalTraceLevel: Verbose
    WorkDirectory: C:\Jenkins\workspace\FullCircle\MyApp\MyAppNUnit
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.6.1
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    NumberOfTestWorkers: 8

    Test Run Summary
      Overall result: Passed
      Test Count: 14, Passed: 14, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
      Start time: 2017-06-16 02:32:34Z
      End time: 2017-06-16 02:39:15Z
      Duration: 400.722 seconds

    Results (user) saved as junit-selenium-testsuite.xml

I have also attached my TraceOutput files

[InternalTrace.3960.txt](https://github.com/nunit/nunit/files/1079624/InternalTrace.3960.txt)
[InternalTrace.10376.MyAppTester.dll.txt](https://github.com/nunit/nunit/files/1079625/InternalTrace.10376.Saucery3Tester.dll.txt)
[nunit-agent_10376.txt](https://github.com/nunit/nunit/files/1079626/nunit-agent_10376.txt)

**Comment by CharliePoole** [comment]
Best thing I can do is to read and interpret your code back to you.

The assembly level parallelizable attribute says that __everything__ can be run in parallel with everything else - setup fixtures, test fixtures, test cases, etc. You must have done a very solid job of removing dependencies to be able to do that.

You have a TestFixture that provides a ParallelScope argument. That doesn't make any sense from an NUnit perspective, unless it's being used for some purpose, get rid of it.

You have a ParallelizableAttribute on a SetUp method. There is nothing in NUnit or the docs to suggest doing that and NUnit isn't paying any attention to it.

Recommendation... if you are truly confident that all your test are capable of running in parallel, then just use the attributes at the assembly level and nowhere else. This implies that you have removed all modifiable state from any of your fixtures.

If you are made less confident by the preceding, use ParallelScope.Fixtures at the assembly level. You can then selectively add Parallelizable(ParallelScope.All) to those fixtures where you want to try running the cases in parallel.
