### ISSUE TITLE
Cannot inherit NUnit.Framework.Constraints.Constraint in vb.net

### ISSUE THREAD

**Issue by slarti-b** [nunit/nunit#2263]
I'm trying to write a custom constraint in vb.net  Simplest possible example:
```
Namespace MYConstraints
    Public Class MyConstraint
        Inherits NUnit.Framework.Constraints.Constraint

        Public Overrides Function ApplyTo(Of TActual)(actual As TActual) As NUnit.Framework.Constraints.ConstraintResult
            Throw New NotImplementedException()
        End Function
    End Class

End Namespace
```
The ApplyTo definition was added by Visual Studio automatically even, when I inherited the nunit Constraint class.  Problem is, it won't compile!

I get two errors:

>     BC30518 Overload resolution failed because no accessible 'That' can be called with these arguments:
> 
>     'Public Shared Overloads Sub That(Of TActual)(del As ActualValueDelegate(Of TActual), expr As IResolveConstraint)': Type parameter 'TActual' cannot be inferred.
> 
>     'Public Shared Overloads Sub That(Of TActual)(actual As TActual, expression As IResolveConstraint)': Type parameter 'TActual' cannot be inferred.

And  

> BC30935 Member 'Public MustOverride Overloads Function ApplyTo(Of TActual)(actual As TActual) As ConstraintResult' that matches this signature cannot be overridden because the class 'Constraint' contains multiple members with this same name and signature:
> 
>     'Public MustOverride Overloads Function ApplyTo(Of TActual)(actual As TActual) As ConstraintResult' 'Public Overridable Overloads Function ApplyTo(Of TActual)(ByRef actual As TActual) As ConstraintResult'

Looking at the nunit source for the Constain class I see that it defines two variants with (almost) the same signature:

```
/// <summary>
/// Applies the constraint to an actual value, returning a ConstraintResult.
/// </summary>
/// <param name="actual">The value to be tested</param>
/// <returns>A ConstraintResult</returns>
public abstract ConstraintResult ApplyTo<TActual>(TActual actual);

/// <summary>
/// Applies the constraint to an ActualValueDelegate that returns
/// the value to be tested. The default implementation simply evaluates
/// the delegate but derived classes may override it to provide for
/// delayed processing.
/// </summary>
/// <param name="del">An ActualValueDelegate</param>
/// <returns>A ConstraintResult</returns>
public virtual ConstraintResult ApplyTo<TActual>(ActualValueDelegate<TActual> del)
{
#if ASYNC
    if (AsyncInvocationRegion.IsAsyncOperation(del))
        using (var region = AsyncInvocationRegion.Create(del))
            return ApplyTo(region.WaitForPendingOperationsToComplete(del()));
#endif
    return ApplyTo(GetTestObject(del));
}
```

One is abstract with a pass-by-value TActual parameter and the other is virtual with a ActualValueDelegate<TActual> parameter which seems to be being treated as a reference parameter by vb? if so, it's not enough to distinguish when calling them

The tooltip error in Visual Studio (VS 2015 Professional if it makes a difference) is:
![image](https://user-images.githubusercontent.com/12972794/27215060-3f3b40a0-5278-11e7-806c-af220ee99b45.png)

So it looks like it's interpreting the ActualValueDelegate<TActual> as a ByRef TActual in vb.net

Is there an example of a custom constraint in vb.net anywhere?

Using: 

- nunit 3.7.1 (latest via nuget)
- Visual Studio 2015 professional
- The test prject targets .Net Frame 4.5.2

**Comment by CharliePoole** [comment]
Well, they aren't "almost" the same signature, as they use entirely different types. 😄 

What happens if you use ByVal in the definition of your override?

**Comment by jnm2** [comment]
VB.NET doesn't allow methods to overload by ref-ness like C# does. I just did a test and it prevents you from overriding too if the signatures are ambiguous.

VB.NET can't even *call* a method if it has an overload which differs only by ref-ness.

**Comment by jnm2** [comment]
Specifying `ByRef` and `ByVal` make no difference in the override. `ByVal` is redundant.

**Comment by CharliePoole** [comment]
@jnm2 In that case, it's pretty annoying that you don't get an error. The assembly is supposed to be CLSCompliant and not being able to call a method from VB seems pretty non-compliant to me!

It's still very odd that VB sees the two overloads as only differing by byref. That's confusing, since they are not `T` and `ref T` but `T` and `ActualValueDelegate<T>`. It even lists them correctly in the error message!

Any suggestions as to how we might make this usable for VB?

**Comment by slarti-b** [comment]
Yeah, they are different types - sorry, missed the other definitona dn thought that that was where the "byRef" variant in the VS message came from

Adding ByVal (or ByRef) doesn't help.  ByVal is anyway default if neither is given

I _can_ override the delegate variant by using
```
Public Overrides Function ApplyTo(Of TActual)(actual As NUnit.Framework.Constraints.ActualValueDelegate(Of TActual)) As NUnit.Framework.Constraints.ConstraintResult
    Throw New NotImplementedException()
End Function
```

But it still won't compile the tests project, complaining that:

> BC30935	Member 'Public MustOverride Overloads Function ApplyTo(Of TActual)(actual As TActual) As ConstraintResult' that matches this signature cannot be overridden because the class 'Constraint' contains multiple members with this same name and signature: 
>    'Public MustOverride Overloads Function ApplyTo(Of TActual)(actual As TActual) As ConstraintResult'
>    'Public Overridable Overloads Function ApplyTo(Of TActual)(ByRef actual As TActual) As ConstraintResult'

Having looked more at the source, I see that you do have both definitions:
```
        public abstract ConstraintResult ApplyTo<TActual>(TActual actual);
```
and
```
#pragma warning disable 3006
        /// <summary>
        /// Test whether the constraint is satisfied by a given reference.
        /// The default implementation simply dereferences the value but
        /// derived classes may override it to provide for delayed processing.
        /// </summary>
        /// <param name="actual">A reference to the value to be tested</param>
        /// <returns>A ConstraintResult</returns>
        public virtual ConstraintResult ApplyTo<TActual>(ref TActual actual)
        {
            return ApplyTo(actual);
        }
#pragma warning restore 3006
```

Apparently it is allowed in C# but not in vb.net?

If I take a much-simplified version of the code in the Constraint class:
```
public abstract class Constraint {
    public abstract ConstraintResult ApplyTo<TActual>(TActual actual);
    public virtual ConstraintResult ApplyTo<TActual>(ref TActual actual)
        {
            return ApplyTo(actual);
        }
}
```
And convert it to vb.net, I get the following:
```
 Public MustInherit Class Constraint
        Public MustOverride Function ApplyTo(Of TActual)(actual As TActual) As ConstraintResult
        Public Overridable Function ApplyTo(Of TActual)(ByRef actual As TActual) As ConstraintResult
            Return ApplyTo(actual)
        End Function
    End Class
```

Which also won't compile...

> BC30345	'Public MustOverride Function ApplyTo(Of TActual)(actual As TActual) As ConstraintResult' and 'Public Overridable Function ApplyTo(Of TActual)(ByRef actual As TActual) As ConstraintResult' cannot overload each other because they differ only by parameters declared 'ByRef' or 'ByVal'.
> 
> BC30521	Overload resolution failed because no accessible 'ApplyTo' is most specific for these arguments:
>     'Public MustOverride Function ApplyTo(Of TActual)(actual As TActual) As ConstraintResult': Not most specific.
>     'Public Overridable Function ApplyTo(Of TActual)(ByRef actual As TActual) As ConstraintResult': Not most specific.

**Comment by jnm2** [comment]
@CharliePoole Lol

```c#
#pragma warning disable 3006
```

https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs3006 "Overloaded method 'method' differing only in ref or out, or in array rank, is not CLS-compliant "

**Comment by jnm2** [comment]
@CharliePoole Git blame: https://github.com/nunit/nunit/commit/6f9ca59e736b841ce9eef798f50b16ee2240c320#diff-bda8af86776dd93e124714b9ef005e79

**Comment by CharliePoole** [comment]
Ouch! The proper fix would have been to add `[CLSCompliant(false)]` but that may have rippled to a lot of the framework. 

Key question would be whether writing custom constraints from VB is a goal. I'd say it is. In that case, we would have to figure out a new set of signatures - not a minor change.

**Comment by slarti-b** [comment]
Would it be an option to abstract the abstract stuff to a master class and have another which inherits it contain the virtual function and use that.  Why do you need both?

Would still be a non-trivial change of course

**Comment by CharliePoole** [comment]
Added to backlog as a design item, since it is central to the entire operation of asserts.

**Comment by CharliePoole** [comment]
We use the `ref TACTUAL` interface for DelayedConstraints. It's our only internal use but a fairly important one. Of course, users could create other constraints that use it.

**Comment by slarti-b** [comment]
Yeah, I was just thinking that any existing classes that inherit the Constraint class could continue to do so, unchanged, even if Constraint in it's turn inherits ConstraintBase (or whatever).  Then any VB custom constraints could inherit ConstraintBase directly.  But I was probably thinking "minimal change" rather than "cleanest solution"

**Comment by CharliePoole** [comment]
Constraint implements IConstraint, which is used by Assert to deal with all constraints uniformly. As it stands, it's impossible to implement the interface in VB. If we remove the method, then we have to remove one of the Assert.That overloads as well as drop a feature in DelayedConstraint.

**Comment by rprouse** [comment]
This issue is marked as an idea/design/discussion but hasn't had contributions in years so I am closing. If anyone is interested in working on this idea, post your interest and the team will consider reopening.
