### ISSUE TITLE
Intermittent test failures in Travic CI: TestContextTests

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#2276]
Failure is in new tests added in relation to attachments...
 * `FilePathOnlyDoesNotThrow`
 * `FilePathAndDescriptionDoesNotThrow`

See https://travis-ci.org/nunit/nunit/jobs/245882030

**Comment by ChrisMaddock** [comment]
These have been flakey on Mono/Travis before, and I've really no idea why. 😞 

They've never had a problem on Appveyor, and I can't work out any logic issues with parallelisation. 

The especially weird ones are the ones where file file exists for one test, but not for the next - the file should be created and disposed of in the OneTimeSetUp and OneTimeTearDown - so I'm really not sure what's going on there. :-/

**Comment by CharliePoole** [comment]
Parallelization is what it is. TestContextTests and TestAttachmentTests are creating and using the same file name. Best to use GetTempFileName().

**Comment by ChrisMaddock** [comment]
Ahhh - thanks! I'll PR at some point.
