### ISSUE TITLE
Better error message for EquivalentTo

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#228]
When this constraint fails, the message contains a list of the contents of both enumerations, one after the other, with commas separating each item. Possibly we could format this better to make it easier to read.

In general, it might be a good idea to hand off the formatting of errors to the engine or runner, passing back separate XML elements for the expected and actual values. This would be a pretty broad change, however.

**Comment by rprouse** [comment]
@CharliePoole do you think the various changes we made to allow overriding the messages, etc is enough to satisfy the needs of this issue?

**Comment by CharliePoole** [comment]
@rprouse The intent was to have a completely different expected/actual display, which is internal.

What's the new "review" label intended to mean?

**Comment by CharliePoole** [comment]
Making this a low-pri enhancement. If somebody wants to submit a PR that will get it done sooner.

**Comment by jnm2** [comment]
Closing as duplicate in favor of https://github.com/nunit/nunit/issues/1151 which contains more information.
