### ISSUE TITLE
CancelRun_WhenTestIsRunning_StopsTest sometimes never finish

### ISSUE THREAD

**Issue by appel1** [nunit/nunit#2282]
Does anyone know why _currentWorkItem is set to null in TestWorker.Cancel? _currentWorkItem is accessed without the lock used by Cancel in TestWorkerThreadProc and it looks like TestAssemblyRunnerTests.CancelRun_WhenTestIsRunning_StopsTest fails (never finishes) whenever TestWorkerThreadProc  throws a NullReferenceException. Looks like that is because then you end up with more Busy events getting raised than Idle. 

Locking on cancelLock inside the while loop would also fix it but then Cancel would have to wait for the current work item to complete before canceling.

**Comment by CharliePoole** [comment]
Our cancel run capability is very poorly exercised, since none of our runners use it. When the gui implements cancel, it will start getting more attention and I think more bugs will be generated.

WRT our own test failing (not finishing) could you specify the environment in which you run it, the framework version and the versions of whatever runner you use? It's not failing in our development environments or our CI builds.

**Comment by appel1** [comment]
Current nunit develop (.net 4.5 target) using Visual Studio 2017, latest R#, fully updated .NET 4.7. It also happens using the console runner (3.6.1). 

```
PS C:\GitHub\nunit\bin\Debug\net-4.5> nunit3-console nunit.framework.tests.dll --test NUnit.Framework.Api.TestAssemblyRunnerTests.CancelRun_WhenTestIsRunning_StopsTest -
-inprocess
NUnit Console Runner 3.6.1
Copyright (C) 2017 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.15063.0
  CLR Version: 4.0.30319.42000

Test Files
    nunit.framework.tests.dll

Test Filters
    Test: NUnit.Framework.Api.TestAssemblyRunnerTests.CancelRun_WhenTestIsRunning_StopsTest


Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at NUnit.Framework.Internal.Execution.TestWorker.TestWorkerThreadProc() in C:\GitHub\nunit\src\NUnitFramework\framework\Internal\Execution\TestWorker.cs:line 127
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by CharliePoole** [comment]
You're right... setting `_currentWorkItem` to null is not a good idea. We could remove that code and if something breaks we will know what problem that line was trying to solve.

**Comment by CharliePoole** [comment]
Obviously we should fix this!

**Comment by CharliePoole** [comment]
Obviously we should fix this! 

Beyond that, maybe we need to consider how to handle similar issues we have not yet found and fixed. If a test throws an exception, NUnit captures it and transforms it to a  result of some kind. Maybe the driver needs to capture any residual exception from the framework and transform it into something that goes back across the remoting boundaries in a way that makes it clear the engine has crashed so we don't try to reach it and cause another exception that hides the first one.

**Comment by CharliePoole** [comment]
One approach would be to imagine we are dealing with a framework we didn't write. Frameworks are not actually supposed to throw exceptions - or at least their driver should handle them. So if MysteryFramework throws an exception, what does the driver, runner and engine need to know in order to display clearly "Here's a problem that the framework caused."

**Comment by appel1** [comment]
Closed?

**Comment by CharliePoole** [comment]
Not intentionally.

**Comment by rprouse** [comment]
Nobody has picked this up and nobody else has asked for this so closing.
