### ISSUE TITLE
No way to specify app.config with console runner

### ISSUE THREAD

**Issue by cyanite** [nunit/nunit#2284]
Using nunit-console runner on individual dll's, there is no way to specify the app.config file to use. To do that you have to create an .nunit file and use configfile="app.config". There should be a command line option to do this.

We have a huge number of dll's which require assembly redirects and we don't have config files written for each of them, but only for our executables.

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit-console #246](https://github.com/nunit/nunit-console/issues/246) via [**ZenHub**](https://www.zenhub.com/)
