### ISSUE TITLE
[Meta] `closed:moved` tag

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2285]
I'd like to be able to filter this kind of issue out of lists. :-) None of the current `closed:` tags seems to fit.

Good/bad idea?

**Comment by ChrisMaddock** [comment]
No objections - although this seems to be getting a little OTT.

Do we need to label an issue as to why it was closed? Surely that should be evident from the last couple of comments.

**Comment by jnm2** [comment]
Only for filtering lists without having to click each item and remember what you saw.

But I am leery of going over the top with this, so you've made me question it.

**Comment by CharliePoole** [comment]
Two reasons for closed labels:
1. We use closed:done to track what gets into the release notes
2. It's nice to tell users why we rejected something. The labels we use have become "friendlier" with time. For example, we no longer say "Invalid" but rather "notabug".

Personally, I don't see why we need this new one. Except for doing releases, we have little need to look at closed issues.

**Comment by jnm2** [comment]
I'm content with that. Someone can reopen if they see a need.
