### ISSUE TITLE
Killing thread cancels test run

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#2288]
I've only seen this once, but it's pretty scary. In the following CI build, an entire test run is cancelled while we are testing ThreadUtility.Kill. I've never see this before.

https://ci.appveyor.com/project/CharliePoole/nunit/build/3.8.0-ci-04129-pr-2287

**Comment by rprouse** [comment]
Interesting, we had a timeout in those same tests and also in .NET 3.5 only in #2283 a few days ago.

**Comment by jnm2** [comment]
This is a test I wrote, so I'll take this one.

**Comment by jnm2** [comment]
I'll work on it tonight EST.

**Comment by jnm2** [comment]
Well, I have extra work so I'll have to put this off a day.

**Comment by jnm2** [comment]
Yikes. Worked 14 hours, slept 4.5, worked 11.5. Brain is cooked for today. But work deadline is over so I'll try to do this tomorrow at some point.

**Comment by jnm2** [comment]
The worst thing that's happening is a call to thread.Abort() on a thread I created, not the test thread, so I'm not sure how that got propagated back up to NUnit.

**Comment by jnm2** [comment]
I'm running stress tests via `build -t test35` and not getting a repro on my computer.

**Comment by CharliePoole** [comment]
It shouldn't... for exactly this reason. There is code that NUnit uses to cancel an Abort unless a particular flag is set in the TestExecutionContext that tells us "Yes, we really want to abort the entire run."

**Comment by jnm2** [comment]
Do we have a second example of this failure on AppVeyor? I haven't found one so far.

**Comment by jnm2** [comment]
AppVeyor needs a log search option.

**Comment by CharliePoole** [comment]
I saw it once before. Same stack trace as far as I remember. I wrote the bug on the second appearance of the problem.

**Comment by jnm2** [comment]
I can't think of any lines of attack. Can't think of any ways that a ThreadAbortException could be raised on a test thread via this test.

**Comment by CharliePoole** [comment]
I took a look at it. You have a TimeoutAttribute set, which will kill the test thread if it takes more than 1000ms. Maybe that interacts with the kill in your test in some unforseen way. You could try setting that timeout very short to see what happens.

**Comment by jnm2** [comment]
Now I feel silly. :D

**Comment by jnm2** [comment]
The problem with timeouts is that a busy server might not have the resources to complete the test in the desired time. We could try bumping this up to ten seconds. It's not expected to ever run that long; it's just a way to keep the test from running forever worst-case.

Though that would mean that the timeout message was not shown and IIRC that's a bug I have seen a while back. Would updating the version of the runner make a difference?

I can't think of any way that a thread abort exception could be raised except for Timeout, and that should guarantee the timeout message.

**Comment by jnm2** [comment]
Actually, here's a better fix: stop using the Timeout attribute and use `thread.Join(1000)` instead.

**Comment by jnm2** [comment]
@CharliePoole worth a try and then leave it unless we see this come back up?

**Comment by jnm2** [comment]
Weird that we don't have ThreadUtility on NETSTANDARD1_6... exploration for another day.

**Comment by CharliePoole** [comment]
Yeah... I wouldn't use Timeout there. We have often had to use low-level stuff in our tests to avoid depending on the very thing we are testing - or something close to it. My suggestion was that you __lower__ the timeout and see if you can make it fail, but if you'd rather not dig that deep I think `Join` is a good option. You can assert on the result and fail the test if the thread never ends.

**Comment by jnm2** [comment]
I tried lowering the timeout and it always gave the standard timeout message, never cancellation with a call stack. Happy to dig deep but I ran out of ideas. :-/

**Comment by ChrisMaddock** [comment]
> Weird that we don't have ThreadUtility on NETSTANDARD1_6... exploration for another day.

I thought .NET Standard doesn't have Thread.Join, which was why? I could be wrong...

**Comment by jnm2** [comment]
Ah, I didn't know that. True, but it looks like there is if you reference the System.Threading.Thread platform extensions package.
https://apisof.net/catalog/System.Threading.Thread.Join()

**Comment by jnm2** [comment]
But honestly we could work around it with a manual reset event, if we wanted timeout support for .NET Standard 1.6. If someone ever asks for it.

**Comment by ChrisMaddock** [comment]
We already reference System.Threading.Thread - but I think Thread.Join is only in .NET Standard 2.0?

Although the page you linked says it's in ".NET Standard + Platform Extensions" version 1.6, and I don't really know what that means! 😄

**Comment by jnm2** [comment]
Okay! You know more than I do. :-D

**Comment by ChrisMaddock** [comment]
One of the long term things on my list has been to implement a timeoutattribute on .NET Standard.

I'm pretty sure .NET Standard 2.0 will be released before I get round to it! 😄

**Comment by jnm2** [comment]
I'm seeing the same bug in an unrelated test:

https://travis-ci.org/nunit/nunit/jobs/269025127#L2923

Compare to https://ci.appveyor.com/project/CharliePoole/nunit/build/3.8.0-ci-04129-pr-2287#L1217 which Charlie linked above.

**Comment by jnm2** [comment]
(@rprouse this was `release-38-merge`– maybe the error was expected?)

**Comment by rprouse** [comment]
@jnm2 that was not expected in the merge. None of the changes in that PR were code, build or test related. It was just CHANGES.md version update and an extra file in packaging.
