### ISSUE TITLE
Use overridden Equals for IEnumerables, Collections, etc.

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#23]
When a user-defined class overrides Equals, we should use it even if the class implements IEnumerable, ICollection, etc.

See discussion at http://groups.google.com/group/nunit-discuss/browse_thread/thread/3ad31a263aaaba40?hl=en

From https://bugs.launchpad.net/nunit-3.0/+bug/646786

**Comment by jnm2** [comment]
We already have this with the `IEquatable<>` interface, but I'm not sure that it would be a good thing to detect if `object.Equals` has been overridden.  It is doable:

```c#
var objectEqualsMethod = typeof(object).GetMethod(nameof(object.Equals), BindingFlags.Public | BindingFlags.Instance);
var hasOverriddenEquals = typeof(EnumerableWithOverriddenEqualsSpy)
    .GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly)
    .Any(_ => _.GetBaseDefinition() == objectEqualsMethod);
```

but Liskov substitution and dependency inversion would not be happy with us. I'm afraid there would be too many inintended side effects. A BCL collection might start overriding equals for a reason irrelevant to the test.

We could consider treating `IComparable<>` the same as `IEquatable<>`, but other than that I vote to close this.

**Comment by ChrisMaddock** [comment]
I'd agree on the basis our equality testing is complicated enough, and this issue doesn't seem to have come up again since first raised in 2010!

**Comment by jnm2** [comment]
Two votes to close and no other responses.
