### ISSUE TITLE
Nested tests repeats base class tests

### ISSUE THREAD

**Issue by akamud** [nunit/nunit#2307]
I have this scenario:

```csharp
using NUnit.Framework;
using System;

namespace nUnitTest
{
    [TestFixture]
    public class BaseTestFixture
    {
        protected int value = 0;

        [SetUp]
        public void BaseSetup()
        {
            value = 30;
        }

        [Test]
        public void BaseTest()
        {
            Assert.AreEqual(30, value);
        }

        public class DerivedTestFixture : BaseTestFixture
        {
            [SetUp]
            public void DerivedSetup()
            {
                value = 100;
            }

            [Test]
            public void DerivedTest()
            {
                Assert.AreEqual(100, value);
            }
        }
    }
}
```

This shows up duplicated on VS and nUnit GUI, and the biggest problem is that the `BaseTest` showing up on the nested class fails because the test runs twice and this is the scenario:

1. BaseSetup runs
2. DerivedSetup runs
3. BaseTest runs // fails because `value` is now `100`

![image](https://user-images.githubusercontent.com/954102/27959111-89fb5e56-62fc-11e7-8b28-33eb9f737a7c.png)

Is this a supported scenario?
Should I "hide" all the tests from the base class so this doesn't happen? Like this:

```csharp
using NUnit.Framework;
using System;

namespace nUnitTest
{
    [TestFixture]
    public class BaseTestFixture
    {
        protected int valor = 0;

        [SetUp]
        public void BaseSetup()
        {
            valor = 30;
        }


        public class Test : BaseTestFixture
        {
            [Test]
            public void BaseTest()
            {
                Assert.AreEqual(30, valor);
            }

        }

        public class DerivedTestFixture : BaseTestFixture
        {
            [SetUp]
            public void DerivedSetup()
            {
                valor = 100;
            }

            [Test]
            public void DerivedTest()
            {
                Assert.AreEqual(100, valor);
            }
        }
    }
}

```

**Comment by CharliePoole** [comment]
Essentially, NUnit is doing what you told it to do. Both the base and derived classes are fixtures. The base qualifies because it has the attribute and also because it contains tests. The derived class also has the attribute - by inheritance - as well as tests.

The pattern you are trying to use is called Abstract Fixture and the solution is in its name. Make your base class abstract and either move the attribute to the derived class or eliminate it entirely.

**Comment by akamud** [comment]
Your suggestion still has a problem for my scenario:

```csharp
using NUnit.Framework;
using System;

namespace nUnitTest
{
    public abstract class BaseTestFixture
    {
        protected int valor = 0;

        [SetUp]
        public void BaseSetup()
        {
            valor = 30;
        }

        [Test]
        public void BaseTest()
        {
            Assert.AreEqual(30, valor);
        }

        public class DerivedTestFixture : BaseTestFixture
        {
            [SetUp]
            public void DerivedSetup()
            {
                valor = 100;
            }

            [Test]
            public void DerivedTest()
            {
                Assert.AreEqual(100, valor);
            }
        }
    }
}
```

Sure, the tests are not repeated anymore, but the base test still fails because it runs from the derived fixture. And that test is in the base class because I can have scenarios like this in my suite:

```
ConfirmCommand (3 tests)
ConfirmCommand.Offline (5 tests)
ConfirmCommand.Offline.WithLoggedUser (2 tests)
```

I see your point about nUnit doing what I told it to do, but my question is: is there a way to tell nUnit to not run base class tests *from the derived class*, but still allow for tests to be written in the base class, like in my first example? That would solve the problem. 

I guess what I'm trying to achieve is:
* Reuse `SetUps`, which was my main goal
* Well separated tests, declared in each class
* Avoid running the test more than once
* Avoid running base tests from the derived class because it can break due to a Derived `SetUp`

**Comment by CharliePoole** [comment]
Sorry, but I"m not getting it. IF you don't want to run the tests in the base class, then why are they there?

Fundamentally, an abstract fixture exists to contain all the things that are common to the derived classes. If those tests are not common, then perhaps you need yet another derived class to hold them.

WRT Setup, if both the base and derived classes contain SetUp methods, both are run before any tests are run. That's part of the specification of how setup works. Any tests that require `valor` to equal 30 would need to be in a derived class that doesn't change the value to anything else.

**Comment by akamud** [comment]
Actually I do want to run the tests in the base class, but I don't want it to start from the Derived classes.

Let me show you a more concrete example of what I mean, trying to keep it as simple as possible:

This is my code:
```csharp
public class VM
{
    User user;

    private async Task Confirm(User user)
    {
        // this is common
        _sessionControl.SetLoggedUser(user);

        // this varies depending on the user status
        if (!user.Status)
        {
            Username = string.Empty;
            Password = string.Empty;

            // show alert
        }
        else
        {
            // do something else with the enabled user
        }
    }
}
```

And these are my tests
```csharp
public class WhenLocalUserExists
{
    private User defaultUser;
    private VM vm;

    [SetUp]
    public void SetUpLocalUser()
    {
        defaultUser = UserBuilder.GetDefaultUser();
        DoSomethingForSetup(defaultUser);

        vm = new VM();
    }

    [Test]
    public void ShouldSetLoggedUser()
    {
        vm.Confirm();

        _mocker.Verify<ISessionControl>(x => x.SetLoggedUser(defaultUser));
    }

    public class AndUserIsDisabled : WhenLocalUserExists
    {
        [SetUp]
        public void DisableUser()
        {
            defaultUser.Status = false;
        }

        [Test]
        public void ShowsAlertIfUserIsDisabled()
        {
            vm.Confirm();

            _mocker.VerifyAlertIsShown(AppResources.Mensagem_Login_Inativo);
        }

        [Test]
        public void ClearsUsernameAndPasswordIfUserIsDisabled()
        {
            vm.Confirm();

            vm.Username.Should().BeEmpty();
            vm.Password.Should().BeEmpty();
        }
    }

    public class AndUserIsEnabled : WhenLocalUserExists
    {
        [SetUp]
        public void EnableUser()
        {
            defaultUser.Status = true;
        }

        [Test]
        public void OtherTest()
        {
            // Something other tests
        }
    }
}
```

As you can see, the `_sessionControl.SetLoggedUser` does not depend on the User status, so I write this test in my `WhenLocalUserExists` class, I need to run this test.
But now that I have two derived classes (`AndUserIsDisabled`, `AndUserIsEnabled`), the `ShouldSetLoggedUser` test is shown twice, and run twice.

Sure, the tests won't break becasue the inner setups does not affect it in any way, but do you agree it makes sense for that test to only exist in the Common scenario (`WhenLocalUserExists`)? Repeating this test and running it twice is not necessary and can be deceiving.

**Comment by CharliePoole** [comment]
What you are trying to accomplish makes perfect sense. But you have not modelled it that way in NUnit.

Everything in the base is duplicated in every derived class. Therefore, if there is something that you don't want duplicated, it can't be in a base class.

**Comment by akamud** [comment]
I understand that, but isn't this necessary because of the way Nesting Setups work on nUnit?

I mean, the only solution I came up with, was "hiding" the common scenario (`ShouldSetLoggedUser`) in a derived class. Like so:

```csharp
public class WhenLocalUserExists
{
    private User defaultUser;
    private VM vm;

    [SetUp]
    public void SetUpLocalUser()
    {
        defaultUser = UserBuilder.GetDefaultUser();
        DoSomethingForSetup(defaultUser);

        vm = new VM();
    }

    public class Common : WhenLocalUserExists
    {
        [Test]
        public void ShouldSetLoggedUser()
        {
            vm.Confirm();

            _mocker.Verify<ISessionControl>(x => x.SetLoggedUser(defaultUser));
        }
    }

    public class AndUserIsDisabled : WhenLocalUserExists
    {
        [SetUp]
        public void DisableUser()
        {
            defaultUser.Status = false;
        }

        [Test]
        public void ShowsAlertIfUserIsDisabled()
        {
            vm.Confirm();

            _mocker.VerifyAlertIsShown(AppResources.Mensagem_Login_Inativo);
        }

        [Test]
        public void ClearsUsernameAndPasswordIfUserIsDisabled()
        {
            vm.Confirm();

            vm.Username.Should().BeEmpty();
            vm.Password.Should().BeEmpty();
        }
    }

    public class AndUserIsEnabled : WhenLocalUserExists
    {
        [SetUp]
        public void EnableUser()
        {
            defaultUser.Status = true;
        }

        [Test]
        public void OtherTest()
        {
            // Something other tests
        }
    }
}
```

So essentially, all my base classes are becoming abstract classes.

What would be a better solution without the need of the `Common` subclass? I don't see how nUnit would allow me to do that.

**Comment by jnm2** [comment]
@akamud This is why we must run inherited methods. Otherwise this standard technique would stop working:

```c#
[TestFixture]
public abstract class ConsistencyTests
{
    protected abstract double PerformOperation(double left, double right);

    [TestCase(0, 1)]
    [TestCase(0, -1)]
    // etc
    public void Should_be_commutative(double left, double right)
    {
        Assert.That(PerformOperation(right, left),
            Is.EqualTo(PerformOperation(left, right));
    }

    [TestCase(0, 1)]
    [TestCase(0, -1)]
    // etc
    public void Should_be_associative(double first, double second, double third)
    {
        Assert.That(PerformBinaryOperation(first, PerformBinaryOperation(second, third)),
            Is.EqualTo(PerformBinaryOperation(PerformBinaryOperation(first, second), third));
    }
}

// Runs both tests
public sealed class AdditionTests : ConsistencyTests
{
    public override double PerformOperation(double left, double right) => left + right;
}

// Runs both tests
public sealed class MultiplicationTests : ConsistencyTests
{
    public override double PerformOperation(double left, double right) => left * right;
}
```

**Comment by jnm2** [comment]
Also suppose this happened:

```c#
[TestFixture]
public class BaseClass
{
    [Test]
    public virtual void SomeTest()
    {
        // ...
    }
}

public class OverridingClass : BaseClass
{
    [Test]
    public override void SomeTest()
    {
        // New implementation, may or may not call base.SomeTest()
    }
}

public class NonoverridingClass : BaseClass
{
    [Test]
    public void SomeTotallyDifferentTest()
    {
        // ...
    }
}
```

There is no way we should stop `NonoverridingClass.SomeTest` from running because doing so means that we also have to stop `OverridingClass.SomeTest` from running, *or* we hackishly disobey the OOP principles of liskov substitutability and dependency inversion, by using reflection to figure out _and act differently_ if `SomeTest` was overridden or not.

**Comment by akamud** [comment]
I see, so my scenario can only be achieved removing the tests from base classes, like I did with the `Common` class.

Thank you both for taking the time answering this.

**Comment by jnm2** [comment]
@akamud No problem. Hopefully the solution is serviceable for you. We try to adhere to .NET object model semantics as closely as possible. Many people (including me) consider it a likely code smell if you have a class that isn't marked either `abstract` or `sealed`, so to me your solution is actually cleaner from a semantic C# point of view. But YMMV. 😄

However, the other possibility is that we add a `[TestInThisClassOnly]` attribute. The test method would be invalid unless the method is sealed or non-virtual.

**Comment by akamud** [comment]
That attribute would work for me :)

**Comment by jnm2** [comment]
@nunit/framework-team Started discussion in a [new thread](https://github.com/nunit/nunit/issues/2309) for `[TestInThisClassOnly]`.

**Comment by jnm2** [comment]
We decided not to add this to the framework, but maintaining a custom attribute will still give you everything you'd want. See https://github.com/nunit/nunit/issues/2309#issuecomment-313936931.

**Comment by apiblueprint-heath** [comment]
> [@akamud](https://github.com/akamud) This is why we must run inherited methods. Otherwise this standard technique would stop working:
> 
> [TestFixture]
> public abstract class ConsistencyTests
> {
>     protected abstract double PerformOperation(double left, double right);
> 
>     [TestCase(0, 1)]
>     [TestCase(0, -1)]
>     // etc
>     public void Should_be_commutative(double left, double right)
>     {
>         Assert.That(PerformOperation(right, left),
>             Is.EqualTo(PerformOperation(left, right)));
>     }
> 
>     [TestCase(0, 1, 0.5)]
>     [TestCase(0, -1, 0.5)]
>     // etc
>     public void Should_be_associative(double first, double second, double third)
>     {
>         Assert.That(PerformBinaryOperation(first, PerformBinaryOperation(second, third)),
>             Is.EqualTo(PerformBinaryOperation(PerformBinaryOperation(first, second), third)));
>     }
> }
> 
> // Runs both tests
> public sealed class AdditionTests : ConsistencyTests
> {
>     public override double PerformOperation(double left, double right) => left + right;
> }
> 
> // Runs both tests
> public sealed class MultiplicationTests : ConsistencyTests
> {
>     public override double PerformOperation(double left, double right) => left * right;
> }





https://stackdev.space/questions/what-sets-apart-abstract-and-protected-in-my-specific-situation-in-c
