### ISSUE TITLE
[TestInThisClassOnly] for test methods

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2309]
Here is an example of a someone wanting to prevent base class test methods from being discovered and run for the derived class, with code: https://github.com/nunit/nunit/issues/2307#issuecomment-313754878

We must keep running base class test methods in derived classes by default (https://github.com/nunit/nunit/issues/2307#issuecomment-313857888), so this is the workaround: https://github.com/nunit/nunit/issues/2307#issuecomment-313765735

Many people consider it a likely code smell if you have a class that isn't marked either `abstract` or `sealed`, so to me the workaround is actually cleaner from a semantic C# point of view. But even more, I don't want to cramp people's style. I hadn't seen the `WhenX`, `AndY : WhenX` inheritance pattern before.

We could consider a `[TestInThisClassOnly]` attribute. The test method would be invalid unless the method is sealed or non-virtual, because otherwise we're working directly against .NET object semantics; https://github.com/nunit/nunit/issues/2307#issuecomment-313858259.

Seems something that could be `easyfix`, but I haven't looked.

Is this a good fit with the framework?

**Comment by CharliePoole** [comment]
It seems like an unnecessary substitute for people's learning how nunit works. Also, this has come up once in fifteen years!

It is curious however that a number of weird usages have suddenly started to pop up.

**Comment by jnm2** [comment]
I like to get the discussion though. For the sake of discussion, it sounds like you're saying that the `WhenX`, `AndY : WhenX` style is an unnecessary substitute for learning how NUnit works. That's not so if we decide we want NUnit to support that style.

**Comment by CharliePoole** [comment]
I was replying to TestThisClassOnly.

NUnit is designed to __support__ alternative syntactic styles but it probably makes more sense as an extension rather than expanding the framework itself.

**Comment by ChrisMaddock** [comment]
Personal opinion: I think this is going too far to solve a problem that should be handled by restructuring tests.

I think restructuring covers the vast majority. Should someone come across an edge case where they don't want to restructure, they could implement such an attribute as a custom attribute. I don't think this is a common enough case to add an attribute to the main library. 🙂

**Comment by oznetmaster** [comment]
I agree with @ChrisMaddock .

**Comment by jnm2** [comment]
Sounds good to me. Thanks for your opinions!

**Comment by jnm2** [comment]
Here is a tested implementation as a custom attribute:

```c#
[AttributeUsage(AttributeTargets.Method, Inherited = false)]
public sealed class TestInThisClassOnlyAttribute : TestAttribute, ISimpleTestBuilder
{
    public new TestMethod BuildFrom(IMethodInfo method, Test suite)
    {
        if (method.MethodInfo.DeclaringType != method.TypeInfo.Type) return null;

        var testMethod = base.BuildFrom(method, suite);

        if (method.MethodInfo.IsVirtual && !method.MethodInfo.IsFinal && !method.TypeInfo.Type.IsSealed)
            testMethod.MakeInvalid("TestInThisClassOnlyAttribute is not valid on unsealed virtual methods.");

        return testMethod;
    }
}
```

/cc @akamud

**Comment by jnm2** [comment]
Usage:

```c#
[TestFixture]
public class Tests
{
    [TestInThisClassOnly]
    public void Test()
    {
        Assert.That(this, Is.TypeOf<Tests>());
    }
}
    
public class DerivedTests : Tests
{
}
```

**Comment by akamud** [comment]
Thank you all for taking the time discussing this and for providing a workaround 👍

**Comment by Thaina** [comment]
@jnm2 Is it possible to do that on TestFixture too?

**Comment by jnm2** [comment]
So that all methods declared in the class are not discovered in derived classes? Yes, but it might be tricky having inherited from TestAttribute. I'll take a look when I'm back at a computer.

**Comment by jnm2** [comment]
@Thaina From what I can tell it is not possible to override at the fixture level. Since the `[TestFixture]` attribute itself is not needed, I can't create a custom one that changes the behavior when there are methods marked `[Test]`.

@nunit/framework-team Am I missing anything?

**Comment by jnm2** [comment]
Similarly, if you specify `[Test, TestInThisClassOnly]`, it's not possible for `[TestInThisClassOnly]` to have any effect because it can't interfere with the `[Test]` attribute’s decision to create a test in all derived classes.
