### ISSUE TITLE
Incorrect xmldoc on RetryAttribute

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#2313]
The xmldoc on RetryAttribute has been copy/pasted from RepeatAttribute. This should be corrected.

https://github.com/nunit/nunit/blob/7b87bdc7b48ee1b13023dd282efea449c2d66b81/src/NUnitFramework/framework/Attributes/RetryAttribute.cs

We already have some doc for RetryAttribute - so this could be a good issue for a first time contributor. 🙂 

https://github.com/nunit/docs/wiki/Retry-Attribute

**Comment by MhdTlb** [comment]
Can I work on this issue?

**Comment by mikkelbu** [comment]
Sure. I've assigned the issue to you.

**Comment by jnm2** [comment]
@mikkelbu Fyi, we remove the `up-for-grabs` when we assign people and try to add `up-for-grabs` (have to document first) whenever it's approved on the backlog and not assigned.
