### ISSUE TITLE
Add .editorconfig to set file encodings so that people don't have to think about it

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2319]
These days we want every file to be UTF-8 with no byte order mark. It's universally understood and compatible, unlike the ANSI encoding Visual Studio will use by default. This is a typical problem any time you copy and paste special characters from the clipboard into VS. It results in tests running fine locally and blowing up in Travis (see https://github.com/nunit/nunit/pull/2294#issuecomment-315223398).

Obviously, this is not something we want people to have to even think about if we can possibly avoid it. So many things have native `.editorconfig` support that it is worthwhile to start one just to override the charset of every file on save.

(EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs. http://editorconfig.org/)

**Comment by MhdTlb** [comment]
@jnm2  The idea is to add encoding type to `.editorconfig` file?

**Comment by jnm2** [comment]
Specifically I'm thinking something like

```ini
root = true

[*]
charset = utf-8
```

What are your thoughts?

**Comment by rprouse** [comment]
While we are at it, I would like to enforce our coding standards with the editorconfig extensions, http://kent-boogaart.com/blog/editorconfig-reference-for-c-developers

**Comment by jnm2** [comment]
@rprouse I was hoping someone would say that (besides me). I'm a huge fan of .editorconfig enforcement.

**Comment by jnm2** [comment]
I wonder how that list compares to the one I manually created from the Roslyn 2.0 release source code.
Also, full official documentation is coming with VS 17.3 =)
https://github.com/madskristensen/EditorConfigLanguage/issues/10#issuecomment-310139189

**Comment by jnm2** [comment]
Looks like they've added stuff since 2.2. I'll get busy!

**Comment by jnm2** [comment]
Oh hello, I didn't realize we had an .editorconfig already 😆

**Comment by MhdTlb** [comment]
Can I work on this?

**Comment by CharliePoole** [comment]
@jnm2 Maybe edit your issue description to tell those who read it what `.editorconfig` is and give a link?

**Comment by MhdTlb** [comment]
@jnm2  Take a look at this link https://developercommunity.visualstudio.com/content/problem/22922/editorconfig-support-interprets-charset-utf-8-as-u.html. I think `charset = utf-8` will add a BOM which is not desired

**Comment by jnm2** [comment]
@MhdTlb I'm sorry, I already went through the list! https://github.com/nunit/nunit/commits/editorconfig

I saw the BOM thing, taking a look. I haven't run into it yet other places.

**Comment by jnm2** [comment]
Better link https://github.com/nunit/nunit/compare/editorconfig?expand=1

**Comment by jnm2** [comment]
@MhdTlb I can't get VS to change the charset at all. I must be doing something wrong.

**Comment by jnm2** [comment]
Looks like my naming section causes it to ignore the file. I'll take that out for now.

**Comment by jnm2** [comment]
@MhdTlb You're right, that's no good! We'll have to wait on that till VS2017 isn't buggy.

**Comment by jnm2** [comment]
PR at https://github.com/nunit/nunit/pull/2320 for what @rprouse asked about, but as @MhdTlb points out, this issue is blocked on https://developercommunity.visualstudio.com/content/problem/22922/editorconfig-support-interprets-charset-utf-8-as-u.html.

**Comment by jnm2** [comment]
Now that VS 15.3 is out, how long should we wait before assuming that most people are off 15.0 through 15.2 which will still cause UTF8 BOM grief?

**Comment by rprouse** [comment]
> Now that VS 15.3 is out, how long should we wait before assuming that most people are off 15.0 through 15.2 which will still cause BOM grief?

Probably more than a week if the number of yellow update flags I see on my devs' computers is any indication 🙁

**Comment by jnm2** [comment]
@rprouse And it's been approximately two months and Update 4 is also out, so both the current update and the last update have the byte order mark fix. I'm not sure how to estimate how many people are still on 15.0–15.2. What do you think?

Worst case scenario if we go ahead too soon is that we'll get a PR with every first line of edited files showing delete of the line without BOM and addition of the line with BOM.

**Comment by ChrisMaddock** [comment]
> Worst case scenario if we go ahead too soon is that we'll get a PR with every first line of edited files showing delete of the line without BOM and addition of the line with BOM.

If this is worst case scenario - in my opinion, it's not worth worrying about! 🙂

**Comment by jnm2** [comment]
@rprouse I can squeeze that in #2320 or anyone else can update it later.

**Comment by rprouse** [comment]
Sure, put it in #2320. We can catch in code reviews, but hopefully contributors keep up to date if they are using 2017.

**Comment by jnm2** [comment]
Done and added `Fixes` keyword.
