### ISSUE TITLE
Cannot set or clear current TestExecutionContext from external runner code anymore

### ISSUE THREAD

**Issue by KrzysFR** [nunit/nunit#2321]
The `TestExecutionContext.ClearCurrentContext()` method has been removed in 3.7.x, and the `TestExecutionContext.CurrentContext` property cannot be set from external code (marked `internal set` in .NET Standard builds).

I have a very basic test runner that allows me to run my tests from an assembly's `void Main(..)`. It creates a fake `TestExecutionContext` for each test method that is being executed. I was using `EstablishExecutionEnvironment()` and `ClearCurrentContext()` in previous versions to install/remove this context.

Am I missing something, or is there another way to achieve the same result?

**Comment by jnm2** [comment]
@CharliePoole Do we want to consider making TestExecutionContext.Current settable or provide a setter method similar to SynchronizationContext? We recently [switched it from private to internal](https://github.com/nunit/nunit/pull/2279/files#diff-11a1802be2fa3b7e8bb8b478b2f00c99R180).

**Comment by KrzysFR** [comment]
In my case, I only need to clear the previous context, to make sure that no one is using the context after the test has completed/failed. I was afraid of some async task or timeout callback that would fire _after_ the test is supposed to be over.

If clearing the test context is not possible, maybe having a way to invalidate the current context so that any background thread attempting to access it would fail?

**Comment by jnm2** [comment]
@KrzysFR This is all it ever did: https://github.com/nunit/nunit/commit/76588be886cd2d65da836959f1a4efe13abba7a1#diff-11a1802be2fa3b7e8bb8b478b2f00c99L296

It always had the exact same effect as `TestExecutionContext.Current = null`.

**Comment by jnm2** [comment]
@KrzysFR This is all it ever did: https://github.com/nunit/nunit/commit/76588be886cd2d65da836959f1a4efe13abba7a1#diff-11a1802be2fa3b7e8bb8b478b2f00c99L296

It always had the exact same effect as `TestExecutionContext.Current = null` which I think we could expose for you.

**Comment by CharliePoole** [comment]
@jnm2 I'd first like to understand why he needs a context at all. We just fixed the problem of not being able to run tests outside s context by having NUnit create it's own fake context.

**Comment by CharliePoole** [comment]
I disagree that this is a bug. At the moment it's just a scenario we don't support. We need to decide if we want to support it.

**Comment by jnm2** [comment]
@KrzysFR What was gained when you used to null the `ClearCurrentContext` in the past? Now, if you null it, one will be created just in time as soon as a test needs it.

I was thinking the bug is that we deleted an API without providing a workaround like `CurrentContext = null`, which we still might need in the future. Possibly.

**Comment by jnm2** [comment]
We aren't supposed to do that on APIs that aren't in the Internal namespace, are we?

**Comment by KrzysFR** [comment]
I think I missed the fact that now you are automatically creating an Adhoc context if none is provided. In the past, the accessor to get the current context would return null - if run outside of an official test tunner - which would break a lot of things. I had to create and install a fake context, so that most of the test features would workd. And since there was an `EstablishExecutionEnvironment()` / `ClearCurrentContext()` pair of methods, I called them because I thought this was required (maybe it wasn't?)

Now I realize that most of this is probably not needed anymore.

The only thing I really want is to be able to setup the test current directory (which they use as a base for temporary files). If this can be achieved some other way, then I guess I can scrap all that code, and then clearing the test context would not be needed?

**Comment by jnm2** [comment]
> If this can be achieved some other way, then I guess I can scrap all that code, and then clearing the test context would not be needed?

That sounds right to me. Let's work on this assumption and if an x-y problem does arise, let's see if we can deal with it directly.

**Comment by CharliePoole** [comment]
@jnm2 TestExecutionContext is in the internal namespace to signal it's internal while still allowing extensions to be created. Note that extensions only work for a particular version so there is basically nothing to break.

@KrzysFR Hopefully that's the case. Let us know how it goes.

**Comment by jnm2** [comment]
😳 Oh, I'm sorry. I've been thinking it was in the public namespace all along.

**Comment by KrzysFR** [comment]
I just tried removing all of the previous fake context code, and here is what I find:

- Calling any of the `WorkerId`, `Random`, `Test` and `Result` properties on `TestContext.CurrentContext` throw a `NullReferenceException` (other properties do not throw). This makes a lot of test helper method fail.
- The test runner would try/catch the execution of the test method, and pass the exception to my fake `TestResult` class, which would then declare the test as failed. I'm not sure how I would be able to do the same thing now.
- I don't see a way to specify the test method name. It is used by my logger, and also to configure the output directory of some tests (they all produce artefacts under their own `${OUTPUT_PATH}/${TEST_NAME}/...` folder). The test helper would use the CurrentDirectory and Test name properties to construct this path.

Appart from the `NullReferenceException`s, the other items are optional (I can work around them).

**Comment by jnm2** [comment]
@KrzysFR Is what you're trying to do roughly the same as https://github.com/nunit/nunit/issues/2243? I.e, running tests without referencing NUnitLite?

**Comment by KrzysFR** [comment]
Mmmm yes you could say that, though my runner code is very basic (I don't run multiple tests, or have any test arguments, don't care about producing xml test results, etc...).

Basically, I need a quick way to execute a any test method from a void Main(), without any additional dependencies. The main motivation was to be able to run "benchmark-like" tests, using external tools such as a profiler or code analyzer (that does not know about NUnit runners).

I was able to hack something together for NUnit 2.x, and found a way to keep it working with NUnit 3.0. I guess it could be possible to use NUnitLite instead, but being able to quickly turn any dll into an exe, add a `void Main()` and be able to run any tests with a single line of code seems very easy in comparison.

**Comment by CharliePoole** [comment]
@jnm2 Maybe he needs to be using the latest development build from MyGet. I'm on my phone so can't easily check which fixes are in the release.

**Comment by KrzysFR** [comment]
There is no pressing issues, I was just trying out the latest version of NUnit in a test branch and found some breaking API changes. I'm currently using NUnit 3.5.1 without any issues, so I'm in no hurry to upgrade yet.

**Comment by jnm2** [comment]
@KrzysFR Alright, you and I are on the same page. Though if you are doing any kind of timing tests, I do recommend using BenchmarkDotNet for [reasons](https://github.com/dotnet/BenchmarkDotNet/blob/master/README.md).

**Comment by KrzysFR** [comment]
I'm a big fan of BenchmarkDotNet :) The test methods I want to run are more complex integration tests that run only once. I have another set of assemblies dedicated for BenchmarkDotNot, which do not require NUnit at all.

**Comment by jnm2** [comment]
@KrzysFR  Can you try the `NUnitTestRunner.Run<TheFixture>(_ => _.TheTest());` invocation from your main method, using the helper method from https://github.com/nunit/nunit/issues/2243, and see how well that suits or if it could be improved?

**Comment by KrzysFR** [comment]
Sure, but unfortunately it will have to wait until tomorrow, it's almost midnight for me :). Will keep you updated with the results.

**Comment by CharliePoole** [comment]
For me too, here in Paris. Good night guys.

**Comment by jnm2** [comment]
@KrzysFR At your convenience, of course, asynchronous processing for the win =) I can't say enough good things about sleep right now...

**Comment by KrzysFR** [comment]
@jnm2 I had some time to try your runner. I had to change things a bit because in NUnit 3.7.1 (from NuGet), the `Children` property of a `TNode` is get-only (you are probably working on a dev branch?). Anyway, I was able to construct the filter manually by doing the following (not pretty but it works)

```C#
var and = new TNode("and");
and.ChildNodes.Add(new TNode("class", string.IsNullOrEmpty(fixtureType.Name) ? fixtureType.Namespace : $"{fixtureType.Namespace}.{fixtureType.Name}"));
and.ChildNodes.Add(new TNode("method", method.Name));
var flt = new TNode("filter");
flt.ChildNodes.Add(and);
var filter = TestFilter.FromXml(flt);
```

This looks a lot more easier than what I was doing before, and I was able to make the test run properly. Also, huge benefit is I see that you can pass an 'options' dictionary to the runner, which is probably how I will be able to set the CurrentDirectory or other settings (cf #2322).

The only downsides I found:

- The `result` return by Run() is a bit difficult to consume with only a single test: I have to descend the hierarchy of the Children until I find the bottom node (which is the test method itself). I guess this API is intended to produce some XML that will parsed by other tools, while here I'm traversing the DOM somewhat blindly...

- Any output/log produced by the test or the various setup/teardown methods is dilluted accross multiple nodes. Currently I'm only dumping the output of the last result node, so I'm missing all the output from `[OneTimeSetUp]` and `[OneTimeTearDown]` methods

- I see in the `Output` property all the logs produces with `Console.Out`, but all the logs produced via `TestContext.Progress.WriteLine(...)` are missing. I worked around this with a global static that reroute all my logs to Console.Out instead in this mode.

- Previously, I was able to insert logs and callbacks in between the end of test `[Setup]` and test execution. This way I could insert for ex. a `Console.ReadKey()` right after the test initialization, giving me all the time in the world to attach a debugger and/or start profiling. This allows me to produce clean profile traces without all the setup and JITing gunk.

Appart from that, it looks like I can completly get rid of my fake TestContext/TestResult shims, which means that the current issue becomes a moot point...

**Comment by jnm2** [comment]
> I had to change things a bit because in NUnit 3.7.1 (from NuGet), the Children property of a TNode is get-only (you are probably working on a dev branch?). 

I was confused for a minute because my code snippet works using a NuGet reference to 3.7.1, but then I looked closer and saw that I'm not actually setting the ChildNodes property. I'm using a collection initializer syntax.

```c#
var x = new TNode("and")
{
    ChildNodes =
    {
        new TNode("class", string.IsNullOrEmpty(fixtureType.Namespace) ? fixtureType.Name : $"{fixtureType.Namespace}.{fixtureType.Name}"),
        new TNode("method", call.Method.Name)
    }
}
```

Is exactly the same as this:
```c#
var x = new TNode("and");
x.ChildNodes.Add(new TNode("class", string.IsNullOrEmpty(fixtureType.Namespace) ? fixtureType.Name : $"{fixtureType.Namespace}.{fixtureType.Name}"));
x.ChildNodes.Add(new TNode("method", call.Method.Name));
```

What would actual fail to compile is this, because ChildNodes.set is private:
```c#
var x = new TNode("and")
{
    ChildNodes = new NodeList
    {
        new TNode("class", string.IsNullOrEmpty(fixtureType.Namespace) ? fixtureType.Name : $"{fixtureType.Namespace}.{fixtureType.Name}"),
        new TNode("method", call.Method.Name)
    }
}
```

Note the `new Nodelist`.

**Comment by jnm2** [comment]
I'm curious what prompted you to change that part of the code, but if you hadn't changed it, it would have compiled.

**Comment by jnm2** [comment]
The XML is just the way the framework interfaces with tooling. You can also pass a TestListener where I have `TestListener.NULL` for realtime feedback. (@CharliePoole The name `NULL` goes against our coding standard.) Perhaps that will answer all your questions?

**Comment by KrzysFR** [comment]
> @jnm2 I'm curious what prompted you to change that part of the code, but if you hadn't changed it, it would have compiled.

I guess I must have written `ChildNodes = new TNode("and") { ... }` instead of `ChildNodes = { new TNode("and") { ... } }` for the root node `filter` while retyping the code. Copy-pasted from the original and it works fine. Oh well...

For `TestLitener.NULL`, if you are going after the same pattern as [Stream.Null](https://msdn.microsoft.com/en-us/library/system.io.stream.null(v=vs.110).aspx) or [StreamWriter.Null](https://msdn.microsoft.com/en-us/library/system.io.streamwriter.null(v=vs.110).aspx) then it should probably be renamed to `TestListener.Null`.

**Comment by jnm2** [comment]
Let me know if TestListener doesn't allow you to accomplish your points above.

**Comment by CharliePoole** [comment]
@jnm2 Regarding naming, TeatListener.NULL has a history from before our coding standard. I could have changed it from 2 to 3 but didn't. If it seemed important enough to change (I.e. were confusing) I'd add a synonym now and drop it in 4.0. IMO, it's not worth worrying about.

**Comment by KrzysFR** [comment]
@jnm2 I was able to do most of the things I want with a custom TestListener. To simplify things, I have created a generic listener that uses lambdas.

```C#
public sealed  class AnonymousTestListener : ITestListener
{

	public Action<ITest> TestStarted { get; set; } = (_) => { };

	public Action<ITestResult> TestFinished { get; set; } = (_) => { };

	public Action<TestOutput> TestOutput { get; set; } = (_) => { };

	void ITestListener.TestStarted(ITest test)
	{
		this.TestStarted?.Invoke(test);
	}

	void ITestListener.TestFinished(ITestResult result)
	{
		this.TestFinished?.Invoke(result);
	}

	void ITestListener.TestOutput(TestOutput output)
	{
		this.TestOutput?.Invoke(output);
	}

}
```

So to sum up: when using a `NUnitTestAssemblyRunner` and some elbow grease, it is possible to create a basic test runner without the need to fiddle with fake `TestContext`, which means that there is not much point in being able to set or reset it.

If you want to force people to go that route, then maybe I would suggest changing `TestContext.EstablishExecutionEnvironment()` to `internal` as well? That way it is in line with all the other context-related static helpers that are already marked `internal`. Unless there are other valid scenarios that requires this method, of course.

**Comment by CharliePoole** [comment]
Just guessing but it's usual to find things in nunit that are public for testing purposes. Back in the day, there was no such thing as InternalsVisibleTo and when it came out it was limited to .NET 2.0 +.

We are changing this rather slowly since features take priority.

**Comment by jnm2** [comment]
@KrzysFR Those delegate properties look like good candidates to be written as events. :D 

Anything remaining that you aren't able to accomplish?

**Comment by CharliePoole** [comment]
The framework avoids events in its external APIs because we don't know how the test results will be remoted or otherwise communicated to a runner. We viewed a simple interface as something that could be handled in pretty much any environment we could engine - think micro framework for example.

Nothing wrong with capturing interface call outside of the framework and changing it however - in fact the V2 GUI does that with it's test listener events.

**Comment by jnm2** [comment]
Yes, the interface itself is fine.

**Comment by KrzysFR** [comment]
> @jnm2 Anything remaining that you aren't able to accomplish?

As far as I'm concerned, I have a working solution that does not need to set or clear TestContext anymore, so I guess this issue can be closed, unless you think that there are other valid scenarios that require it?

**Comment by jnm2** [comment]
Not as far as I know. Glad everything is working for you!
