### ISSUE TITLE
Rename TestListener.NULL to Null

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2323]
`NULL` goes against our coding standard and I dislike it. It also doesn't match the .NET BCL or .NET design guidelines.

It's in the internal namespace so we should be good to up and rename it, right?

**Comment by CharliePoole** [comment]
This hardly seems worth our time to think about, but if we must, let's look at the corresponding code in the engine API. Having two different names could be confusing and that one is public.

**Comment by rprouse** [comment]
We haven't discussed this in months and it is very low priority, so I am closing as won't fix.
