### ISSUE TITLE
Does.Not.Throw

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2324]
I prefer `Does.Not.Throw` to `Throws.Nothing`. It also opens the door to `Does.Not.Throw.InstanceOf<>()`.

Impressions?

**Comment by ChrisMaddock** [comment]
NUnit historically has ended up with a number of different methods to assert the same thing - this can be confusing the new users. I wouldn't want to add to that any more without good justification.

`Does.Not.Throw.InstanceOf<>` implies that you have code which is fine to throw any type of exception, other than the type specified. I'd be intrigued to see the test that that would be useful for! 😄

**Comment by CharliePoole** [comment]
This reminds me a bit of a perennial request, which we have always rejected: "I might get several different kinds of exceptions, why do I have to specify one." The point is that not knowing what you expect in a test is a problem in itself.

**Comment by rprouse** [comment]
First impression 👎 

😄

**Comment by jnm2** [comment]
Quite fair =D
