### ISSUE TITLE
Retry attribute doesn't retry the test.

### ISSUE THREAD

**Issue by marcelopontipedra** [nunit/nunit#2325]
I've already used assert.true(), but it doesn't retry the test.

```c#
[Test, Order(2)]
[Retry(3)]
public void Login()
{
    step.BasicActions.LoginAndOpenPart15038(_driver);
    Assert.True(false == _driver.Url.Contains("login.html"));
}
```

**Comment by jnm2** [comment]
I can repro using:
```c#
private static int times = 0;

[Test, Retry(3)]
public void Login()
{
    times++;
    Assert.Fail(times + " times");
}
```

And looking at the message, or debugging.

**Comment by jnm2** [comment]
`Repeat` acts the same. Something weird is going on. I wonder if it's related to running via the VSTest adapter.

**Comment by jnm2** [comment]
I would have expected https://github.com/nunit/nunit/blob/master/src/NUnitFramework/tests/Attributes/RetryAttributeTests.cs to cover it.

**Comment by jnm2** [comment]
Nope, fails in NUnit Console run too.

**Comment by jnm2** [comment]
@CharliePoole Insight would be appreciated whenever you are available. I'm not missing anything obvious, am I?

**Comment by jnm2** [comment]
Retry is working under `TestBuilder.RunTestFixture` but not under direct run. I'm going to add a direct run test since this is the case.

**Comment by jnm2** [comment]
Doing a manual bisect. This problem didn't exist before the multiple asserts feature was introduced.

**Comment by jnm2** [comment]
Looks like 295fd187 is the commit that introduced this.

**Comment by jnm2** [comment]
https://github.com/nunit/nunit/pull/2085 is the culprit.

**Comment by jnm2** [comment]
Understanding why will be a challenge.

**Comment by jnm2** [comment]
Correction: Repeat is fine, I did the test wrong. It's just Retry.

**Comment by jnm2** [comment]
Added failing test: https://github.com/nunit/nunit/compare/fix_retry

**Comment by jnm2** [comment]
While the smell test is good, what I'm really hoping to see come out of this is a test that enforces an invariant behavior between direct runs and ``TestBuilder.RunTestFixture`, because it would be nice if ``TestBuilder.RunTestFixture` reflected reality.

**Comment by jnm2** [comment]
The exception caused by the Assert.Fail is getting [rethrown as an `NUnitException`](https://github.com/nunit/nunit/blob/1a3c728a34325f6068f0e128bce4df3c0ee95790/src/NUnitFramework/framework/Internal/Reflect.cs#L217). That exception is only caught higher up in the call stack which causes control to be taken away from RetryAttribute. ([No catch in `RetryAttribute`](https://github.com/nunit/nunit/blob/1a3c728a34325f6068f0e128bce4df3c0ee95790/src/NUnitFramework/framework/Attributes/RetryAttribute.cs#L94), [no catch in `TestMethodCommand.Execute`](https://github.com/nunit/nunit/blob/1a3c728a34325f6068f0e128bce4df3c0ee95790/src/NUnitFramework/framework/Internal/Commands/TestMethodCommand.cs#L64).)

**Comment by jnm2** [comment]
The catch is actually [one stack frame above `RetryAttribute`](https://github.com/nunit/nunit/blob/1a3c728a34325f6068f0e128bce4df3c0ee95790/src/NUnitFramework/framework/Internal/Execution/SimpleWorkItem.cs#L59).

**Comment by jnm2** [comment]
Prior to #2085, the actual catch was in [SetUpTearDownCommand.Execute](https://github.com/nunit/nunit/blob/64605da5d57e229dc29252f1895efe127e1cdf07/src/NUnitFramework/framework/Internal/Commands/SetUpTearDownCommand.cs#L66), one stack frame below RetryCommand.Execute, and there was no catch in [`SimpleWorkItem.PerformWork`](https://github.com/nunit/nunit/blob/64605da5d57e229dc29252f1895efe127e1cdf07/src/NUnitFramework/framework/Internal/Execution/SimpleWorkItem.cs#L59), one stack frame above.

**Comment by jnm2** [comment]
#2085 moved the catch from the stack frame below to the stack frame above.

**Comment by jnm2** [comment]
Two hard questions:

 1. Was the move intentional? Is it now `RetryCommand`'s and others' responsibility to catch exceptions?
 2. Why does this work fine with `TestBuilder.RunTestFixture`?

I'll be able to answer the second more easily.

**Comment by jnm2** [comment]
Aha! I don't think it's related to `TestBuilder.RunTestFixture` at all, which is good news. It's because the stack frame below `RetryCommand.Execute` is [`BeforeAndAfterTestCommand.Execute`](https://github.com/nunit/nunit/blob/1a3c728a34325f6068f0e128bce4df3c0ee95790/src/NUnitFramework/framework/Internal/Commands/BeforeAndAfterTestCommand.cs#L59) rather than [`TestMethodCommand.Execute`](https://github.com/nunit/nunit/blob/1a3c728a34325f6068f0e128bce4df3c0ee95790/src/NUnitFramework/framework/Internal/Commands/TestMethodCommand.cs#L64), which means that the test scenarios aren't comprehensive enough. I'll convert my direct test into an indirect test in its own fixture along with the others.

**Comment by jnm2** [comment]
Success: https://github.com/nunit/nunit/compare/fix_retry

So, `Retry` has not worked since #2085 in fixtures that don't have setup or teardown.

**Comment by jnm2** [comment]
So, there were a few apparent motions in #2085:

 1. `SetUpTearDownCommand.Execute` became `BeforeAndAfterTestCommand.Execute` and continued to catch exceptions
 2. `SimpleWorkItem.PerformWork` began catching exceptions. (@CharliePoole Why?)
 3. The inner command supplied to `RetryCommand` changed from `SetUpTearDownCommand` to `TestMethodCommand`.

Aside from point 2 the answer to which I can't ascertain on my own from scanning #2085, point 3 saeems to hint that we should be expecting `BeforeAndAfterTestCommand` to be supplied as the inner command for `RetryCommand`.

**Comment by jnm2** [comment]
@marcelopontipedra I'll waiot for the @nunit/framework-team to comment on which is the correct fix. In the meantime, the workaround is for you to put a dummy `[SetUp]` or `[TearDown]` method in the same fixture.

**Comment by marcelopontipedra** [comment]
Thanks @jnm2 . I also tried the assert.Fail() and it doesn't retry the test. I think this is because the Assert.Fail() breaks the line of code in the test, then it continue to the next test. I think the BeforeAndAfterTestCommand is better.

**Comment by jnm2** [comment]
Answer from @CharliePoole at https://github.com/nunit/nunit/issues/2328#issuecomment-318538546:

> Sorry I missed this thread last week. Changes in the command structure with #2085 made it necessary for every command to handle exceptions, in case there was no setup/teardown. I missed that because I was thinking we __always__ had a setup/teardown command, even if the user had no setup/teardown. That was once true, but isn't any longer.
> 
> Two ways to go here:
> 1. Retry should handle exceptions, as should any other command that cares about them.
> 2. We should ensure that we are catching exceptions and converting them to result somewhere else. That would mean two places actually: right when we execute the tests and after all the commands execute, in case the commands themselves cause exceptions.

**Comment by jnm2** [comment]
@nunit/framework-team This is small and shouldn't interact too much with https://github.com/nunit/nunit/pull/2380, so I'm doing this now.
