### ISSUE TITLE
Assert fails in my Test

### ISSUE THREAD

**Issue by jaindevassy** [nunit/nunit#2327]
Assert.AreEqual(text, getelement.getwebelementtext(element));   

'text' and 'getelement.getwebelementtext(element)' are same. But this step fails always. 

I am using NUnit - 3.7.1, NUnit3TestAdpater - 3.7.

**Comment by mikkelbu** [comment]
Hi @jaindevassy. Can you provide some more information about the types and values of `text` and `getelement.getwebelementtext(element)`. And what is the error message?

**Comment by jaindevassy** [comment]
Some times I find following error message:-
"Cannot obtain fields or call methods on the instance of type 'OpenQA.Selenium.IWebElement' because it is a proxy to a remote object."

**Comment by mikkelbu** [comment]
But what are the exact types of `text` and `getelement.getwebelementtext(element)` ? And what is the full error message from the assertio?

Also can you supply a full stacktrace from when the assertion fails. I suspect that this is more a Selenium problem than a NUnit problem.

**Comment by rprouse** [comment]
@jaindevassy this also sounds like a Selenium issue with a remoted object. Try splitting your code up into two parts,

```C#
string elementText = getelement.getwebelementtext(element);
Assert.AreEqual(text, elementText);
```

If the exception is happening on the first line, it is a Selenium issue, please report it there.

**Comment by jaindevassy** [comment]
Thanks for the feedback.
I too feel the same.

**Comment by mikkelbu** [comment]
@jaindevassy I'm going to close this issue, as it sounds like it is a Selenium issue. If you disagree, then please reopen it and provide some more information.

**Comment by jaindevassy** [comment]
Please close this. This was a Selenium issue.
Thanks
