### ISSUE TITLE
Update build script to use NUnitConsoleRunner v3.7.0

### ISSUE THREAD

**Issue by OmicronPersei** [nunit/nunit#2332]
As the title says.

**Comment by jnm2** [comment]
Sounds good- I'm getting consistent SocketExceptions and 3.7 fixes it for me and I saw it did the same for you.

Are you interested in submitting the PR for this?

**Comment by OmicronPersei** [comment]
Yes

**Comment by jnm2** [comment]
Thanks!

**Comment by ChrisMaddock** [comment]
Fixed by https://github.com/nunit/nunit/pull/2340#pullrequestreview-53435939
