### ISSUE TITLE
Insufficient error handling message in ProcessRunner -> RunTests method

### ISSUE THREAD

**Issue by Fernell** [nunit/nunit#2334]
log.Error("Failed to run remote tests {0}", e.Message); is insufficeint. It lacks details required to diagnose problem. Here is sample of my log:
> An exception occurred in the driver while loading tests.
> Server stack trace: 
>    at NUnit.Engine.Runners.DirectTestRunner.LoadDriver(IFrameworkDriver driver, String testFile, TestPackage subPackage)
>    at NUnit.Engine.Runners.DirectTestRunner.LoadPackage()
>    at NUnit.Engine.Runners.TestDomainRunner.LoadPackage()
>    at NUnit.Engine.Runners.DirectTestRunner.EnsurePackageIsLoaded()
>    at NUnit.Engine.Runners.DirectTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
>    at NUnit.Engine.Runners.AbstractTestRunner.Run(ITestEventListener listener, TestFilter filter)
>    at NUnit.Engine.Runners.AggregatingTestRunner.RunTestsSequentially(ITestEventListener listener, TestFilter filter, List`1 results, Boolean disposeRunners)
>    at NUnit.Engine.Runners.AggregatingTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
>    at NUnit.Engine.Runners.AbstractTestRunner.Run(ITestEventListener listener, TestFilter filter)
>    at NUnit.Engine.Agents.RemoteTestAgent.Run(ITestEventListener listener, TestFilter filter)
>    at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
>    at System.Runtime.Remoting.Messaging.StackBuilderSink.PrivateProcessMessage(RuntimeMethodHandle md, Object[] args, Object server, Object[]& outArgs)
>    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

I was unable to recognize error only by this stack trace. I was forced to download nunit3-console binaries and debug it myself. I found out that useful error message was in ex.InnerException which is not returned in error message at all. Please extend error message by adding ex.InnerException message.

**Comment by ChrisMaddock** [comment]
This is an nunit-console issue, I'll move it over to that repository.

@Fernell - we'd appreciate a Pull Request, if you were willing.

**Comment by ChrisMaddock** [comment]
Issue moved to [nunit/nunit-console #273](https://github.com/nunit/nunit-console/issues/273) via [**ZenHub**](https://www.zenhub.com/)
