### ISSUE TITLE
Remove deprecated Is.String* Constraints

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#2342]
https://github.com/nunit/nunit/pull/2338 removed the attributes obsoleted in v3.0.

I suggest we also remove the Is.String* constraints which were deprecated at the same time - and do this in the 3.8 release, so we only inconvenience users the once.

**Comment by CharliePoole** [comment]
I've never been happy with our syntax for the four string constraints, but the Is.String* items should definitely go.

**Comment by OmicronPersei** [comment]
While I wait for more info on #2226 I'll work on this 😛
