### ISSUE TITLE
No tests or proper test driver found when using nunit3-console 3.7.0 in CLI

### ISSUE THREAD

**Issue by alexandlazaris** [nunit/nunit#2343]
Am writing a test framework to run e2e tests. Running the tests from Test Explorer within VS works fine. Want to run the tests via CLI. Added Nunit packages. Tried ```.\nunit3-console ..\..\..\BDD\BDD.csproj``` from within .\NUnit.ConsoleRunner.3.7.0\tools and got this output:

```
Runtime Environment
   OS Version: Microsoft Windows NT 10.0.14393.0
  CLR Version: 4.0.30319.42000

Test Files
    ..\..\..\BDD\BDD.csproj

Errors, Failures and Warnings

1) Invalid : C:\nunit-page-objects\BDD\bin\Debug\BDD.dll
No suitable tests found in 'C:\nunit-page-objects\BDD\bin\Debug\BDD.dll'.
Either assembly contains no tests or proper test driver has not been found.

Test Run Summary
  Overall result: Failed
  Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2017-08-02 07:49:02Z
    End time: 2017-08-02 07:49:05Z
    Duration: 2.902 seconds
```

Repo: https://github.com/alexandlazaris/nunit-pageobjects
Packages:
```
  <package id="MSTest.TestAdapter" version="1.1.18" targetFramework="net452" />
  <package id="MSTest.TestFramework" version="1.1.18" targetFramework="net452" />
  <package id="Newtonsoft.Json" version="10.0.3" targetFramework="net452" />
  <package id="NUnit" version="3.7.1" targetFramework="net452" />
  <package id="NUnit.Console" version="3.7.0" targetFramework="net452" />
  <package id="NUnit.ConsoleRunner" version="3.7.0" targetFramework="net452" />
  <package id="NUnit.Extension.NUnitProjectLoader" version="3.6.0" targetFramework="net452" />
  <package id="NUnit.Extension.NUnitV2Driver" version="3.7.0" targetFramework="net452" />
  <package id="NUnit.Extension.NUnitV2ResultWriter" version="3.6.0" targetFramework="net452" />
  <package id="NUnit.Extension.TeamCityEventListener" version="1.0.2" targetFramework="net452" />
  <package id="NUnit.Extension.VSProjectLoader" version="3.6.0" targetFramework="net452" />
  <package id="Selenium.Firefox.WebDriver" version="0.18.0" targetFramework="net452" />
  <package id="Selenium.Support" version="3.4.0" targetFramework="net452" />
  <package id="Selenium.WebDriver" version="3.4.0" targetFramework="net452" />
  <package id="Selenium.WebDriver.ChromeDriver" version="2.31.0" targetFramework="net452" />
  <package id="Selenium.WebDriver.IEDriver" version="3.4.0" targetFramework="net452" />
  <package id="Selenium.WebDriver.MicrosoftDriver" version="15.15063.0" targetFramework="net452" />
```

**Comment by ChrisMaddock** [comment]
Are your tests found correctly if you pass the actual assembly into the nunit3-console, rather than the csproj?

**Comment by rprouse** [comment]
Also, why are you including the MSTest adapter and framework? Are your tests written as NUnit tests? You mention adding NUnit after running the tests in Visual Studio, so that makes me think you are using MSTest.

**Comment by alexandlazaris** [comment]
@ChrisMaddock - If you mean if I pass in my .dll file into the nunit3-console, then no it still fails. Same error.

@rprouse - Hmm good point. I am using MSTest to use ```[TestMethod]``` attributes and so on however I was under the impression I had to import the NunitConsoleRunner package to run those tests from CLI?

**Comment by rprouse** [comment]
If you are using the MSTest framework, then you need to use their command line runner. Nunit currently only runs tests that were written with the NUnit test framework. 

Normally you run tests using the runner for the framework you are using. NUnit has the ability to plug in runners for other frameworks, but none have been written yet.

**Comment by alexandlazaris** [comment]
Thanks for the assistance @rprouse , makes sense now. Successfully ran in MSText.exe 👯‍♂️ 👯

**Comment by rprouse** [comment]
@alexandlazaris glad you got it working. If MSTest doesn't meet your needs, remember NUnit is there for you 😄
