### ISSUE TITLE
Remove dependency on System.Web.UI.ICallbackEventHandler

### ISSUE THREAD

**Issue by estrizhok** [nunit/nunit#2344]
Due to the dependency on `System.Web.UI.ICallbackEventHandler`, the type from `System.Web,dll`, which does not exist in .netstandard, nunit.framework.dll compiled for .netstandard is incompatible with the nunit console runner. This is awkward since references to .netstandard libraries from projects targeting full .NET framework are completed valid.

**Comment by CharliePoole** [comment]
This "kind of" duplicates nunit/nunit-console#271 but we don't really have a console issue that deals completely and clearly with being able to run .NET standard under the console runner. We should convert the referenced issue, move this one or create a new one @nunit/engine-team 

@estrizhok This is not a framework issue because the framework supports other APIs besides the one that uses `System.Web.UI.ICallbackEventHandler`. It's just that our engine doesn't use any of them.

Leaving this for now so the @nunit/core-team can discuss whether to move or close.

**Comment by CharliePoole** [comment]
@estrizhok I'll add that there are other things besides that interface that keep it from working. Maybe if we create a proper issue, we'll make some progress on it.

**Comment by jnm2** [comment]
I believe we should get rid of the `System.Web.UI.ICallbackEventHandler` dependency and doing a sweep to remove any other non-.NET Standard 1.3 dependency. I'm in favor of moving this to the engine repo as-is and linking it to an epic or tracking issue like nunit/nunit-console#271.

**Comment by CharliePoole** [comment]
It appears to me that we have engine issues that deal with what we want to accomplish already. The framework is heavily involved here, so we also need a framework issue.

That said, I"m absolutely against breaking compatibility in the engine, which is supposed to be able to run tests written against __any__ version of our framework. The combination of frameworks plus drivers allows us to mix any number of different ways to call into the framework, without breaking anything.

**Comment by jnm2** [comment]
That's a hard one. We need a migration plan though, using a `System.Web.UI` type can't go on forever.

**Comment by CharliePoole** [comment]
@jnm2 Of course it can. It just can't go on at all in platforms that don't support it.

However, it doesn't have to go on forever. Assuming that the next major update is a big one like NUnit 3 was, we can change all the interfaces then. But till then, I think support for old ways of doing things has to stay in, especially one that's involved in two out of our three published APIs.

**Comment by CharliePoole** [comment]
@jnm2 I'll add... at a certain point, out of date stuff becomes an inconvenience for the developers. That's when a team shows what it's made of. Are we willing to inconvenience users (break their code) for our own convenience? In the past the answer has always been no, at least until the users affected by the change had pretty much disappeared.

There is a tendency for teams made up of highly motivated, talented and leading-edge developers to discount the needs of those users who are not equally on the leading edge. NUnit has always made it a point not to be that way. I sure hope that doesn't change.

**Comment by jnm2** [comment]
@CharliePoole 
> Of course it can. It just can't go on at all in platforms that don't support it.

That's exactly what I mean- we need to migrate to a new API that works in .NET Standard 1.3 or less, while leaving the legacy API in place.

**Comment by CharliePoole** [comment]
Perhaps the title of the issue was leading me astray.

**Comment by rprouse** [comment]
I am closing old uncategorized issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
