### ISSUE TITLE
Supported .Net Framework and Visual Studio versions 

### ISSUE THREAD

**Issue by asfihafeez** [nunit/nunit#2345]
I need to know what versions of Visual Studio and .Net Framework are supported by each, if not majority of the releases of NUnit. 

Any help is appreciated.

**Comment by CharliePoole** [comment]
If you are merely using NUnit, the version of VS you use is irrelevant. It may matter, however, if you are building it.

Every version of NUnit specifies what it supports. We can answer you here if you can narrow down the versions that interest you. There are on the order of 50 versions over the past 17 years, which you can check yourself in the docs, but it's a bit much for one of us to compose an answer without a bit more focus in the question.

**Comment by asfihafeez** [comment]
2.1
2.2
2.3
2.4
2.5
2.6

**&&&**

3.0 
3.2
3.4
3.5
3.6
3.7

**Comment by rprouse** [comment]
All versions of NUnit 3 and newer support .NET 2.0 and newer. If I remember right 2.6.4 also supports .NET 2.0 and newer.

Why do you need this information? It is a fair amount of work to compile and you could do it just as easily as us who are volunteers working in our spare time.

**Comment by asfihafeez** [comment]
I need the information for work related purposes, If you could provide me with the location this information is available at; I will gladly look myself.

**Comment by rprouse** [comment]
According to the release notes at http://nunit.org/docs/2.6.3/releaseNotes.html, support for .NET 1.0 was dropped with NUnit 2.6. Therefore NUnit 2.6 and newer support .NET 2.0 and newer. Older versions of NUnit support .NET 1.0 and newer. That said, support for specific .NET Features is very feature dependent. For example, support for async/await was not added until NUnit 2.6.3 I think? You will need to go through the release notes for those.
