### ISSUE TITLE
Missing reference to nunit.framework with NUnit NuGet package

### ISSUE THREAD

**Issue by qazwer1** [nunit/nunit#2346]
![image](https://user-images.githubusercontent.com/10104219/28907728-4f5afbbc-7828-11e7-8e0e-818e0b9113e6.png)

![image](https://user-images.githubusercontent.com/10104219/28907734-58e160ea-7828-11e7-973e-f38fea6ff61f.png)

**Comment by CharliePoole** [comment]
The only thing the images show is that your project has a reference to the NUnit framework, but the assembly is not present. To all appearances, you added the reference at one point but the files have been removed and it needs to be refreshed. There doesn't appear to be a bug here.

**Comment by rprouse** [comment]
@qazwer1 This can happen if your NuGet restore fails to happen or if you move your project to a different folder causing the reference to be broken. I suggest that you restart Visual Studio, then remove and re-add the package.

Everyone uses the NuGet package, so this isn't a general issue, but a problem with your setup. I am going to close this as a question. If you need more help, feel free to post here, we will see it.
