### ISSUE TITLE
Feature request for configuring tests to require Asserts - Explicit pass/fail/inconclusive

### ISSUE THREAD

**Issue by mcarriga** [nunit/nunit#2347]
I have testing framework built around NUnit that a large group of users writes their Selenium tests in. Need the ability to configure an explicit pass/fail in that if no assertions are present in a test then the default status is Inconclusive until an assert passes or fails the test. If 0 assertions were executed in a test then the final status would be inconclusive pending no other exceptions thrown. Alternatively, if that is not possible, then be able to access the Asserts count within NUnit API like TestContext.CurrentContext.Result.Asserts which would allow me to check the number of asserts in my TearDown() method and throw Assert.Inconclusive("No Assertions Executed"). I have seen when running from the console runner, that the XML output includes an "asserts" counter attribute on the <test-case> elements so all we would need is this counter accessible via the API.

**Comment by CharliePoole** [comment]
The only current option is to use theories, which default to Inconclusive rather than Passed. But theories are currently only applicable to parameterized tests.

The notion that a test passes if it does no asserts has been part of NUnit for many years, so we are not going to change the default. At what level would you like to be able to configure this.

**Comment by mcarriga** [comment]
@CharliePoole I agree on not making it a default; that makes total sense. If it were possible to configure this as part of the TestFixture attribute like [TestFixture(RequiresAssert: true)], that might be easiest way that I can think of. Otherwise, I am wondering if it would be possible to have a constraint that would be a constraint on the actual Test and could be configured in the SetUp - Not sure if that would make sense though. If it doesn't work out to include this ability as part of the framework, then just simply being able to access to asserts count from CurrentContext.Result would also be very helpful as mentioned above which would allow me in the TearDown to check the asserts count and throw an Assert.Inconclusive if the Asserts count is 0.

**Comment by mcarriga** [comment]
Would it be possible to have a console command line option to be able set requiring asserts?

**Comment by CharliePoole** [comment]
The option of exposing Asserts would not solve the problem at all. Many prefectly valid tests perform no asserts at all. The most common situation is when a mock is used and the mock framework's expectations replace assertions as the third A.

**Comment by CharliePoole** [comment]
I also wonder about the utility of the Inconclusive state. NUnit is designed so that inconclusive tests get almost no visibility. They neither add to nor subtract from the verification of the software. In this case, it seems that the OP wants to actually highlight tests that perform no asserts, so some kind of warning would probably be more appropriate.

**Comment by rprouse** [comment]
I am marking this as an idea and moving it to our discussion pipeline.

The problem with a command line option is that it will present different behavior depending on the runner you are using. If your developers are using ReSharper or the Visual Studio Adapter, they (and several other runners) would need to be updated to support the new option.

Personally, I would not be in favor of adding this, but I would be open to including the assert count in the TestContext's Results.

**Comment by CharliePoole** [comment]
I agree with @rprouse. If I were starting from scratch, I think that Inconclusive would be the best default value for a test. That would force any users who, for example, relied on the absence of unhandled exceptions to make a test pass to actually add an `Assert.Pass` at the end. However, we aren't starting from scratch.

I created #2353 to add assert count and some other info to `TestContext.CurrentContext.Result`.

**Comment by mcarriga** [comment]
I agree as well. Adding the assert count is the most feasible option and works for what I need. Thank you both!

**Comment by rprouse** [comment]
Since we have #2353 to track the count, I am going to close this as won't fix.
