### ISSUE TITLE
Obsolete CollectionContainsConstraint Constructors

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#2360]
At some point, https://github.com/nunit/nunit/pull/2239 is going to be merged and remove CollectionContainsConstraint. The only breaking change should be where anyone is explicitly using the code `new CollectionContainsConstraint()` - all the other methods will be changed internally to use a SomeItemsConstraint instead.

I think it would be good if we can obsolete the CollectionContainsConstraint constructor in v3.8, and then merge the actual constraint removal in v3.9. It should only be the constructor itself that is obsoleted - any other public methods which make use of the class will be refactored. The obsoletion message should state that `SomeItemsConstraint` is the appropriate replacement.

**Comment by ChrisMaddock** [comment]
D'oh - sorry @mikkelbu - I meant to tag you in this and ask if you wanted to do it!

**Comment by mikkelbu** [comment]
No problem 😄. I just needed a simple task after my vacation.

**Comment by mikkelbu** [comment]
@ChrisMaddock Just a question (I forgot about @CharliePoole's https://github.com/nunit/nunit/issues/1324#issuecomment-193552176). Adding the ObsoleteAttribute to the constructor gives the the following errors when compiling, so I'll need to do most of the same changes as in #2239 (except removing the class) in order to be able to compile the solution.
```
Has.cs(218,20): error CS0618: 'CollectionContainsConstraint.CollectionContainsConstraint(object)' is obsolete: 'Deprecated, use 'new SomeItemsConstraint(new EqualConstraint(expected))' or 'Has.Some.EqualTo(expected)' instead.' [C:\src\NUnit\nunit\src\NUnitFramework\framework\nunit.framework-4.5.csproj]
Does.cs(68,20): error CS0618: 'CollectionContainsConstraint.CollectionContainsConstraint(object)' is obsolete: 'Deprecated, use 'new SomeItemsConstraint(new EqualConstraint(expected))' or 'Has.Some.EqualTo(expected)' instead.' [C:\src\NUnit\nunit\src\NUnitFramework\framework\nunit.framework-4.5.csproj]
Contains.cs(44,20): error CS0618: 'CollectionContainsConstraint.CollectionContainsConstraint(object)' is obsolete: 'Deprecated, use 'new SomeItemsConstraint(new EqualConstraint(expected))' or 'Has.Some.EqualTo(expected)' instead.' [C:\src\NUnit\nunit\src\NUnitFramework\framework\nunit.framework-4.5.csproj]
Assert.cs(301,33): error CS0618: 'CollectionContainsConstraint.CollectionContainsConstraint(object)' is obsolete: 'Deprecated, use 'new SomeItemsConstraint(new EqualConstraint(expected))' or 'Has.Some.EqualTo(expected)' instead.' [C:\src\NUnit\nunit\src\NUnitFramework\framework\nunit.framework-4.5.csproj]
Assert.cs(311,33): error CS0618: 'CollectionContainsConstraint.CollectionContainsConstraint(object)' is obsolete: 'Deprecated, use 'new SomeItemsConstraint(new EqualConstraint(expected))' or 'Has.Some.EqualTo(expected)' instead.' [C:\src\NUnit\nunit\src\NUnitFramework\framework\nunit.framework-4.5.csproj]
Constraints\DictionaryContainsValueConstraint.cs(40,13): error CS0618: 'CollectionContainsConstraint.CollectionContainsConstraint(object)' is obsolete: 'Deprecated,use 'new SomeItemsConstraint(new EqualConstraint(expected))' or 'Has.Some.EqualTo(expected)' instead.' [C:\src\NUnit\nunit\src\NUnitFramework\framework\nunit.framework-4.5.csproj]
Constraints\DictionaryContainsKeyConstraint.cs(40,13): error CS0618: 'CollectionContainsConstraint.CollectionContainsConstraint(object)' is obsolete: 'Deprecated, use 'new SomeItemsConstraint(new EqualConstraint(expected))' or 'Has.Some.EqualTo(expected)' instead.' [C:\src\NUnit\nunit\src\NUnitFramework\framework\nunit.framework-4.5.csproj]
Constraints\ContainsConstraint.cs(84,35): error CS0618: 'CollectionContainsConstraint.CollectionContainsConstraint(object)' is obsolete: 'Deprecated, use 'new SomeItemsConstraint(new EqualConstraint(expected))' or 'Has.Some.EqualTo(expected)' instead.' [C:\src\NUnit\nunit\src\NUnitFramework\framework\nunit.framework-4.5.csproj]
Constraints\ConstraintExpression.cs(729,62): error CS0618: 'CollectionContainsConstraint.CollectionContainsConstraint(object)' is obsolete: 'Deprecated, use 'new SomeItemsConstraint(new EqualConstraint(expected))' or 'Has.Some.EqualTo(expected)' instead.' [C:\src\NUnit\nunit\src\NUnitFramework\framework\nunit.framework-4.5.csproj]
Constraints\ConstraintExpression.cs(742,62): error CS0618: 'CollectionContainsConstraint.CollectionContainsConstraint(object)' is obsolete: 'Deprecated, use 'new SomeItemsConstraint(new EqualConstraint(expected))' or 'Has.Some.EqualTo(expected)' instead.' [C:\src\NUnit\nunit\src\NUnitFramework\framework\nunit.framework-4.5.csproj]
An error occurred when executing task 'Build45'.
```

**Comment by ChrisMaddock** [comment]
Is it possible to disable the warnings with pragma's around the relevant lines?

**Comment by ChrisMaddock** [comment]
If not, maybe a solution is to merge #2239 - just without the classes removed, and them obsoleted there. Then in 3.9, it will just be a matter of deleting an unused class. 😄

**Comment by CharliePoole** [comment]
@ChrisMaddock Sounds like a plan.

**Comment by mikkelbu** [comment]
@ChrisMaddock I think that I will go for the second approach (reintroducing the classes in #2239 and mark the constructors as obsolete). Hopefully, I will have time for it this week.

**Comment by ChrisMaddock** [comment]
Great! 😀 3.8's come up quick - I need to carve some time out to sort the issues I was going to too! 😆

**Comment by rprouse** [comment]
@mikkelbu I am starting to prepare the 3.8 release. Should I expect a PR for this soon or should I move it out of the release milestone?

**Comment by rprouse** [comment]
This was done along with #2239. Sorry for not noticing earlier @mikkelbu. I am closing this as complete.

**Comment by mikkelbu** [comment]
No need to be sorry. I should have closed the issue myself (I was actually planning to do it tonight :)).
