### ISSUE TITLE
NUnit Parallelizable and OneTimeSetUp with no namespace results in single-threaded test execution

### ISSUE THREAD

**Issue by ivanakcheurov** [nunit/nunit#2361]
I set `[assembly: Parallelizable(ParallelScope.Fixtures)]`
I have the following OneTimeSetUp:
```
// no namespace so executed for all namespaces in this assembly
[SetUpFixture] //edit: added to this snippet because otherwise this class is ignored by NUnit
public class Config
{
    [OneTimeSetUp]
    public void SetUp()
    {
        XmlConfigurator.Configure();
    }

    //[TearDown]
    //public void TearDown()
    //{
    //}
}
```
_Expected:_ The tests should be executed **multi-threaded**.
_Actual:_ The tests are executed **single-threaded**.

_Additional observation:_
If I put the `OneTimeSetUp` class in a namespace (corresponding to one of the test suites), then tests are executed multi-threaded. However only that namespace is initialized with `SetUp()`. 
If I use this workaround then I have to specify `OneTimeSetUp` for every namespace in the assembly which is error-prone (have to keep it in sync manually). I have many sub-namespaces in the assembly because that's how SpecFlow generates them.

**Comment by CharliePoole** [comment]
What happens if you place the attribute on the SetUpFixture rather than at the assembly level?

**Comment by ivanakcheurov** [comment]
If I do it like this, then all tests run in parallel and the configuration is invoked
```
[SetUpFixture]
[Parallelizable(ParallelScope.Fixtures)]
// ReSharper disable once CheckNamespace
public class Config
{
    [OneTimeSetUp]
    public void SetUp()
    {
        XmlConfigurator.Configure();
    }

    //[TearDown]
    //public void TearDown()
    //{
    //}
}
```
This is a good workaround for the time being. Thank you!

**Comment by CharliePoole** [comment]
@ivanakcheurov Glad that works for you. It also shows very clearly where the error is, so I'll mark this confirmed.

**Comment by CharliePoole** [comment]
@rprouse This is somewhat serious, so I marked it for inclusion in 3.8. The PR is ready for review.

**Comment by rprouse** [comment]
@CharliePoole excellent, thanks. I was just about to post asking for people to assign PRs and issues that should be in the release to the milestone so I can track to a release next weekend. I will review your PR now.
