### ISSUE TITLE
Lazy TestCaseSourceAttribute

### ISSUE THREAD

**Issue by StefDotmailer** [nunit/nunit#2366]
I noticed that a if you decorate a test with the attribute in the title, the source method gets invoked for ANY test running in the entire project. So if I run TestFixtureX.Test and TestFixutureY.Test has the attribute, the test cases method will be executed also for TestFixtureX.Test.

This causes a significant overhead in big test projects with many sources; to run a single simple test, we have to wait a minute for all the test cases to be loaded.

Is this a bug or by design? Is there a way to avoid this or, even better, to make the test cases lazy and be evaluated only when the test requiring it is executed? If not, can you please consider adding this feature?

Thank you

**Comment by CharliePoole** [comment]
This duplicates an ancient issue: #3, which is part of the Epic #7! We should really do something about this.

**Comment by jnm2** [comment]
Wait a minute...
Some of my integration tests are about to get faster. 😆 

(Workaround is easy enough- cache in a static field, but I agree we should implement this!)
