### ISSUE TITLE
Combine existing testresult.xml file

### ISSUE THREAD

**Issue by georgooty** [nunit/nunit#2368]
Hi,

Have any option to combine the test results.xml with existing test results xml file.

Regards,
George

**Comment by CharliePoole** [comment]
No, but it's an interesting idea and the code to do it is already present in the engine.

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit-console #281](https://github.com/nunit/nunit-console/issues/281) via [**ZenHub**](https://www.zenhub.com/)
