### ISSUE TITLE
NuGet package does not install in Visual Studio 2012 or older

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#2369]
I received a report from a user, "I have Nuget 2.8.6 installed on my visual studio 2010. I am trying to download Nunit in one of my projects and it gives me an error 'NUnit' already has a dependency defined for 'NETStandard.Library'.. Any help on this will be appreciated."

Doing some research, I found this, https://stackoverflow.com/questions/38247961/nuget-package-manager-automapper-already-has-a-dependency-defined-for-micros which seems to indicate that NuGet 2.12 or newer is required for any NuGet packages that include .NET Standard packages. That also states that 2.12+ is only available for Visual Studio 2013 or newer.

**Workaround** use NUnit 3.5 or newer or upgrade Visual Studio.

**Possible fixes?** release a version of the nuget package without .NET Standard?

This isn't really our bug, what do people think we should do? I am also surprised we don't see it reported more often. Has everyone upgraded Visual Studio?

**Comment by ChrisMaddock** [comment]
This would have been an issue since January, and this is the first we've heard of it. This suggests to me that pre-VS 2012 users are a pretty small group.

I wouldn't be keen to introduce the overhead of a new package, to support an outdated IDE. Is it sufficient to suggest that users of VS 2010 should get the binary from the .zip package - which they could package on a NuGet feed, if the so wished?

I wonder what other packagers do? Most major packages now support some variety of .NET Standard.

**Comment by rprouse** [comment]
> I wonder what other packagers do? Most major packages now support some variety of .NET Standard.

I was wondering that too. I went out today and checked a number of popular packages. Very few are not supporting .NET Standard. My guess is that people that update NuGet packages in their solutions also update Visual Studio. People that are locked into older versions of Visual Studio are still using it because of legacy software that they can't update. Just my gut feeling though 😄

**Comment by ChrisMaddock** [comment]
@vikrantarora - for now, you can use any NUnit version up to 3.5.0. 🙂 That should work straight away from NuGet.

**Comment by vikrantarora** [comment]
Hey that was helpful mate. Cheers Chris and Rob

**Comment by ChrisMaddock** [comment]
I'd like to close this issue as something we won't fix. Any objections @nunit/framework-team?

**Comment by mikkelbu** [comment]
I don't mind (even though I have VS2010 and VS2012 installed on some of my computers ::)).

**Comment by rprouse** [comment]
Agreed

**Comment by CharliePoole** [comment]
Some explanation may be needed here - perhaps some documentation.

If I come upon this issue as a naive user, I read the title and see the won't fix, with the conclusion that we don't support VS2012. But that's not correct.

**Comment by rprouse** [comment]
I have updated the workarounds to include using the ZIP package, but we don't support VS2012 and NuGet, so isn't the title correct and not misleading?

**Comment by venusg987** [comment]
This issue is resolved for me after I update nuget.
