### ISSUE TITLE
Collect testresult.xml when executing restart/logout OS in test methods

### ISSUE THREAD

**Issue by georgooty** [nunit/nunit#2373]
Hi,

I have a requirement to execute the below test scenarios?. I tried it ,but the result.xml does not contains the full testsuite details due to the logout happening inside the testmethod.

1. do the one registry modification
2. logout the user

for the above purpose, I wrote a test method and include the above things. Then execute the nunit console, the testrsult doesnot contains the testsuite tags.

Have any suggestion to resolve it?

Regards,
George

**Comment by rprouse** [comment]
@georgooty this is outside the capabilities of NUnit. If you logout, the test processes will be shutdown. Ideally, you would mock out logging out the user so it doesn't hit the OS and you would just test that the logout method was called. Your `Logout` class should be an interface, something like `ILogout`, which is then injected into the code you are testing. In your tests, you would create a `MockLogout` class that just checks if the correct operations are performed.
