### ISSUE TITLE
Grouping fixtures for parallel running

### ISSUE THREAD

**Issue by andrei-ts** [nunit/nunit#2374]
Hi,
Is there a way to make some sort of configurable parallelization in the nunit according to the following example.

I have 8 test fixtures that are running in parallel using ParallelScope.Fixtures.
Also I have 2 fixtures that I want to run sequentially, but be parallel to those 8 fixtures.
Currently as I see if I use NonParallelizable attribute for these 2, they will start only after those 8 would finish. It is ok for me in general but influence total execution time.

In my particular case those tests in 2 fixtures I run sequentially modify several Windows registry settings, and as each test modify the settings for itself such work cannot be parallelized.

**Comment by CharliePoole** [comment]
If I understand you correctly, the two fixtures are not able to run together, although they can run with other fixtures. Grouping of fixtures that may run together in this way is definitely desirable, but not yet supported. See issue #165.

**Comment by andrei-ts** [comment]
Yep, you got it, thanks for pointing me to correct ticket
