### ISSUE TITLE
Prepare for 3.8 Release

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#2376]
@nunit/core-team and @nunit/framework-team I plan on releasing 3.8 this weekend or early next week depending on the backlog. If you feel any issues or PRs should be included in the release, please add the issues to the 3.8 milestone so we can track them. If PRs are not close to ready I will need reasons to justify delaying the release, so please update the PRs or issues accordingly. Thanks.

**Comment by OmicronPersei** [comment]
My guess is issues already merged into nunit/master will, by default, become a part of the 3.8 release?  Apologies for the probably newb question 😄

**Comment by rprouse** [comment]
@OmicronPersei, yes, everything that is in master will go into the release. At this point, we are just tracking open issues and PRs that **may** be in the release. At this point, we triage open issues and determine if any are serious enough to delay the release to get them fixed. We also track PRs for the same reason and try to get them resolved for the release, or delay merging until after the release.
