### ISSUE TITLE
Contains.Item() fails for collections in NUnit 3.8

### ISSUE THREAD

**Issue by RalfKoban** [nunit/nunit#2386]
Hi,

just updated from NUnit 3.7.1 to 3.8.0.
Now, a test starts to fail consistently which succeeded in the past.

Repro:

```

        [Test]
        public void Collection_regression_in_380() => Assert.That(new[] { "test", "test2", "test3" }, Contains.Item("test").And.Contains("test2").And.Contains("test3"));
```

Best regards,
Ralf Koban

**Comment by mikkelbu** [comment]
I think this is due to my solution of #1324

**Comment by rprouse** [comment]
@mikkelbu I am hoping to do a hotfix tonight or tomorrow morning. Are you investigating this issue?

**Comment by rprouse** [comment]
@mikkelbu I am starting to triage this issue. If you have ideas or want to work on it, let me know.

**Comment by rprouse** [comment]
PR is up for this. It was your change @mikkelbu, good catch, but it wasn't your fault, we didn't have any tests for this.

**Comment by jnm2** [comment]
Absolutely. Do not feel strange about making mistakes. It's par for the course. 😄

**Comment by jnm2** [comment]
Look what three of us missed: https://github.com/nunit/nunit-console/issues/285

**Comment by mikkelbu** [comment]
Great work guys 👍 . I was offline all last night (for once ;)), so I did not look into this, so no time wasted 😄 .

**Comment by AzP** [comment]
Has this been released yet?

**Comment by AzP** [comment]
We're still seeing this issue on 3.8.1. We updated directly from 3.6 to 3.8.1, so we've never had 3.8.0 installed.

**Comment by mikkelbu** [comment]
@AzP Are you seeing that the constraint fails (if so can you give an example)? Or that something like the following does not compile?
```
    [Test]
    public void ContainsItemUsing()
    {
      var collection1 = new List<int> { 1, 2, 3, 4, 5, 6, 7, 8 };
      // DOES NOT COMPILE: There is no Using on SomeItemsConstraint
      var constraint = Contains.Item(7).Using(myIntComparer);
      Assert.That(collection1, constraint);
    }
```
The problem about `Contains.Item(object).Using(...)` not compiling anymore can be found here #2412

**Comment by AzP** [comment]
The problem we're seeing is that tests that were previously passing are now failing because Has.Member() (or even Has.Member().And.Member()) are not recognizing objects within a list.
The check compiles and does not throw exceptions, it just doesn't recognize that the member is in the collection.

**Comment by mikkelbu** [comment]
Ok. Then the issue to watch is #2411 (but #2411 and #2412

**Comment by AzP** [comment]
It seems one of the issues might be caused by using CollectionAssert.Contains(PseudoEnum, string) where PseudoEnum has implicit comparison functions with strings.
