### ISSUE TITLE
Using bindingRedirect with codeBase when running in TeamCity

### ISSUE THREAD

**Issue by mortenbock** [nunit/nunit#2396]
Hi.

I have a unit test project, where I need to test that we are using the correct versions of Newtonsoft.Json in different parts of our code.

In order to do that, I need to include multiple version of Newtonsoft.Json.dll in the project. I do that with the following app.config:

    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
      <appSettings>
        <add key="mytest" value="itshere"/>
      </appSettings>
      <runtime>
        <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
          <dependentAssembly>
            <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30AD4FE6B2A6AEED" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
            <bindingRedirect oldVersion="7.0.0.0-10.0.0.0" newVersion="10.0.0.0" />
            <codeBase version="6.0.0.0" href="Newtonsoft.Json.6.0.8/Newtonsoft.Json.dll" />
            <codeBase version="10.0.0.0" href="Newtonsoft.Json.10.0.0.3/Newtonsoft.Json.dll" />
          </dependentAssembly>
        </assemblyBinding>
      </runtime>
    </configuration>

I have included the two dll's in my project, and set them to "Copy always", so they are placed in the `/bin/Debug/` folder.

I use the ConsoleRunner to execute the test, and if I do this they pass:

`packages\NUnit.ConsoleRunner.3.7.0\tools\nunit3-console.exe src\Website.Tests\bin\Debug\Website.Tests.dll`

However, TeamCity will run the tests as a nunit project file, so if I create a `test.nunit` project file like this:

    <NUnitProject>
        <Settings activeconfig="active" appbase="C:\Projects\MyProject"/>
        <Config name="active">
            <assembly path="src\Website.Tests\bin\Debug\Website.Tests.dll"/>
        </Config>
    </NUnitProject>

And run the tests with this command:

`packages\NUnit.ConsoleRunner.3.7.0\tools\nunit3-console.exe test.nunit`

The the tests fail, and I get the exception:

`System.IO.FileNotFoundException : Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.`

I assume that this is because the path to the dll's supplied in my app.config file no longer match the working directory of the process.

Is there a way to get this working?

Either by getting teamcity to not use a project for testing, or by setting the workingdirectory in a way so my assembly redirects will work?

As a note, I have confirmed that the app.config is available, by reading the "mytest" app setting, and that works.

**Comment by ChrisMaddock** [comment]
Can you just confirm what your `app.config` file is named?

You can specify it explicitly in an NUnit project file using the configfile attribute. Can you check if this works?

```
<NUnitProject>
    <Settings activeconfig="active" appbase="C:\Projects\MyProject" configfile=""/>
    <Config name="active" configfile="myapp.config">
        <assembly path="src\Website.Tests\bin\Debug\Website.Tests.dll"/>
    </Config>
</NUnitProject>
```

I'm afraid I don't use TeamCity, so don't know how to get TeamCity to build such an NUnit file. @NikolayPianikov may have some suggestions?

@nunit/engine-team Is there a potential enhancement to the nunit-project-loader here, that it should locate appropriately named config files automatically, in the same way as the console would?

**Comment by mortenbock** [comment]
@ChrisMaddock I have a passing test that looks like this:

        [Test]
        public void TestAppConfigUsed()
        {
            var appSetting = ConfigurationManager.AppSettings["mytest"];
            Assert.That(appSetting, Is.EqualTo("itshere"));
        }

So I have verified that the correct app.config is discovered automatically.
TeamCity will let you supply an app.config to use, but it will use the same app.config across all the dll's supplied (*.Test.dll) in the build step, which is not what I want, if I can avoid it.

I have created a custom commandline step that runs the tests with the `packages\NUnit.ConsoleRunner.3.7.0\tools\nunit3-console.exe src\Website.Tests\bin\Debug\Website.Tests.dll` command, and that works. in TeamCity, but also means I will have to add a new step for each new test assembly.

I guess I just do not understand why the relative `Newtonsoft.Json.10.0.0.3/Newtonsoft.Json.dll` path resolves differently when using the .nunit file.

**Comment by CharliePoole** [comment]
@ChrisMaddock The project loader has nothing to do with config files, other than passing them along if they are specified in the project. Essentially the "loader" really only translates an NUnit project file into a package. There is one issue that may apply here: relative paths in an NUnit project file are interpreted WRT the location of the project file when creating absolute paths from them.

The package that is created is passed back to the engine, which then proceeds to load it. So any work on this should start by verifying that the engine package is what we expect it to be.

@mortenbock Can you add a test to our project that verifies the application base is set the same whether you are using the project file or not?

**Comment by mortenbock** [comment]
@CharliePoole I would be happy to give it a shot, but I'm not quite sure where to put that test? 

Does it belong here in the NUnit project, or is there a console/runner project where it should be?

I could quite easily create a repo with a sample exhibiting the behavior, if that would be useful?

**Comment by CharliePoole** [comment]
@mortenbock I meant you should put it in your own tests, just as you did with the earlier test to verify you are getting the right config file.

**Comment by mortenbock** [comment]
@CharliePoole I've uploaded a repo that shows the issue: https://github.com/mortenbock/UnitTestSampleIssue

The `Run_DirectDllPath_Passes.bat` passes the tests, and the `Run_ProjectFile_Fails.bat` uses the `test.nunit` and fails 3 of the tests, but still passes the one that reads an appsetting from the app.config.

**Comment by NikolayPianikov** [comment]
@mortenbock try adding a build configuration parameter nunit_use_project_file to False, for example:
![7dj8g28voyw2vfjoi8qkmq](https://user-images.githubusercontent.com/11720017/29927801-1257979e-8e70-11e7-915b-e171507b14e3.png)
In this case TeamCity avoids using nunit config files

**Comment by mortenbock** [comment]
@NikolayPianikov That worked! :) 

Thank you very much.

**Comment by mikkelbu** [comment]
Hi @mortenbock. As far as I can tell this issue can be closed. Do you agree?

**Comment by mortenbock** [comment]
@mikkelbu I solved my particular use case in a different way, but I don't know if the underlying issue is an actual bug, or an unsupported scenario.

I have not received any feedback for the sample repo I created for reproducing the issue. 

I will leave it up to the team to decide if it's worth diving into :)
