### ISSUE TITLE
NUnit CI spurious failures, NUnit.Framework.Internal.ThreadUtilityTests.Kill

### ISSUE THREAD

**Issue by OmicronPersei** [nunit/nunit#2398]
Too frequently I see NUnit's CI fail due to the below failure:
>1) Failed : NUnit.Framework.Internal.ThreadUtilityTests.Kill
  Native message pump was not able to be interrupted to enable a managed thread abort.
  Expected: True
  But was:  False
   at NUnit.Framework.Internal.ThreadUtilityTests.AbortOrKillThreadWithMessagePump(Boolean kill)

as seen [here](https://ci.appveyor.com/project/CharliePoole/nunit/build/3.9.0-ci-04352-pr-2379#L1233).

**Comment by jnm2** [comment]
I was not aware of this. On it now, because I want to get to zero CI bugs.

**Comment by OmicronPersei** [comment]
I'll try to get better at reporting spurious CI bugs, I know I'm bad at it!  :(

**Comment by jnm2** [comment]
Me too. It would be cool if we had a tool that listed all error messages from the four CI integrations, sorted by frequency.

**Comment by jnm2** [comment]
Good news! I put stress tested this on my machine and successfully repro'd. Still diagnosing.

**Comment by jnm2** [comment]
Okay I *may* have finally decided to add a stress testing utility... https://github.com/nunit/nunit/compare/fix_spurious_kill_failure?expand=1#diff-59c720af8693dc67c7f2f461cc83adec

**Comment by jnm2** [comment]
It's never `Abort`, always `Kill`, that causes the problem.

**Comment by jnm2** [comment]
It's never [`Abort`](https://github.com/nunit/nunit/blob/f8ae1ff7b402d1b645b454164a77af9fcba42343/src/NUnitFramework/framework/Internal/ThreadUtility.cs#L80), always [`Kill`](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/ThreadUtility.cs#L109), that causes the problem.

This makes me quite happy because that seems to indicate that the bug is actually not in my code but my code did help uncover a case where `ThreadUtility.Kill` was already failing to work as intended! @CharliePoole you may find this interesting.

**Comment by CharliePoole** [comment]
@jnm2 Unless it relates to the native thread stuff you added. I'm afraid I never understood what you ddid there, which is my only reason for asking.

**Comment by jnm2** [comment]
Well, scratch that. `Abort` is doing it too. It seems much less likely to fail than `Kill`, but it does actually fail.

**Comment by jnm2** [comment]
@CharliePoole True. What I set up was a timer that checks every 100ms to see if the thread is still in ThreadState.AbortRequested, and if so, posts a meaningless thread message to the thread in case it's in a message loop in native code to make it come back to managed code. As soon as it sees that the thread aborted, it stops.

**Comment by jnm2** [comment]
Oh my, I should have started with this. Changing `thread.Join(1000)` to `-1` causes the stress test to pass every time. Seems it actually does take a second sometimes. But, changing it to `10000` causes it to fail again. Changing it to `86400000` (=milliseconds/day) also causes it to fail, even though the stress test completes in 25 seconds.

**Comment by jnm2** [comment]
Correction: it passes with `86400000`.

**Comment by jnm2** [comment]
Ha, sometimes Join doesn't get back right away even when ThreadState = Aborted. It doesn't take as long to wait if I use this tactic:

```c#
for (var tries = 0; thread.ThreadState == ThreadState.Aborted || thread.Join(1000); tries++)
{
    Assert.That(tries < 3, "Native message pump was not able to be interrupted to enable a managed thread abort.");
}
```

**Comment by jnm2** [comment]
Can't think of anything to address this except a sufficiently long timeout. When the CPU is under load, what else is there? We don't ever expect failures from this test, so how long can you tolerate waiting for results from CI? 30 seconds?

**Comment by jnm2** [comment]
So what I'm measuring is that when the CPU is under load, timers get around ten time slower to execute callbacks.

**Comment by jnm2** [comment]
So what I'm measuring is that when the CPU is under load, timers get around ten times slower to execute callbacks. I can't think of any mitigations for CPU load.

I say we make this a 15 second timeout and reopen if it comes back. Sound good?

**Comment by jnm2** [comment]
https://github.com/nunit/nunit/pull/2401
