### ISSUE TITLE
Investigate enabling any framework team member to restart the CI builds

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2399]
Right now I think only @CharliePoole and @rprouse can restart builds on these:

 - AppVeyor PR build
 - AppVeyor branch build

All of us can restart builds on these:

 - Travis PR build
 - Travis branch build

In an ideal world I'd say all @nunit/framework-team members and only @nunit/framework-team members should be able to restart each of these four. Do you agree? How close to that can we get?

@CharliePoole Also, AppVeyor lists our builds under your name. Does that have anything to do with it? Should we try a brand new AppVeyor setup?

**Comment by OmicronPersei** [comment]
@jnm2 Have you logged in to Travis using your GitHub credentials?  That's how I do it and it works fine for me.

**Comment by jnm2** [comment]
@OmicronPersei I have. Is there a restart button on this page for you? https://travis-ci.org/nunit/nunit/builds/269414184

**Comment by jnm2** [comment]
I was positive I was logged in on Travis but I wasn't! Okay, I got that now.

**Comment by jnm2** [comment]
I was positive I was logged in on Travis but I wasn't! That's embarrassing. Updated top post to keep it relevant. Thanks @OmicronPersei.

**Comment by ChrisMaddock** [comment]
I can restart any build -  there's a method to authenticate other users under Charlie's account to do that. I agree that should be possible for any team member. 🙂

**Comment by ChrisMaddock** [comment]
@CharliePoole - could you look into if it's possible to add all framework team members to Appveyor? https://github.com/nunit/nunit/pull/2425 is a good example where it's taken 3 team members to merge a simple typo. 😞

**Comment by CharliePoole** [comment]
I'll check but my impression is that everyone has it. You do have to log in via GitHub.

**Comment by jnm2** [comment]
> I'll check but my impression is that everyone has it. You do have to log in via GitHub.

Several of us have tried logging in. This is my logged-in screen:

![image](https://user-images.githubusercontent.com/8040367/30219206-5918fce4-9489-11e7-9f7f-fbfeae28a3c1.png)

**Comment by jnm2** [comment]
History screen:

![image](https://user-images.githubusercontent.com/8040367/30219251-7e78109c-9489-11e7-9d81-14f5c9dbba6e.png)

**Comment by jnm2** [comment]
I don't get any other nunit-related screens that I can find.

**Comment by CharliePoole** [comment]
Apparently only @ChrisMaddock was given access after the initial setup for @rprouse and myself. I added GitHub team access for framework and engine. @jnm2 Can you verify that this is now allowing you to do what you need and close this issue if so?

At some later point, I'd like to clean this up by giving the account a different name.

**Comment by jnm2** [comment]
Nothing has changed since my screenshots but I'll try again in a bit since AppVeyor may take time to update it.

**Comment by CharliePoole** [comment]
Sorry to be repetitious, but be sure you are logged in as a GitHub user. IIRC, it's possible to set up an AppVeyor account that has nothing to do with your GitHub account.

**Comment by jnm2** [comment]
Understandable. 😃 

![image](https://user-images.githubusercontent.com/8040367/30224245-fa366d5c-949b-11e7-98d0-387c6e62005e.png)

![image](https://user-images.githubusercontent.com/8040367/30224253-08accaa2-949c-11e7-8ff3-8e66dfa058ef.png)

**Comment by ChrisMaddock** [comment]
When I log in with my GitHub account, I then get forwarded to a second login page, where I have to select an account. (I choose 'CharliePoole' to do NUnit things!)

![image](https://user-images.githubusercontent.com/4837132/30227381-6d1f1866-94d1-11e7-8bd2-8380dd58f521.png)

@jnm2 - did you try logging out and back in again?

**Comment by CharliePoole** [comment]
@ChrisMaddock I wasn't aware you had to do that, since I'm always me. 😃 

Now that I added the teams of which you are a member, see if logging in as yourself works.

**Comment by jnm2** [comment]
Aha! Logging out and back in gave me

![image](https://user-images.githubusercontent.com/8040367/30227566-2a05b4d2-94a8-11e7-9200-af7da71de70b.png)

and the dropdown you showed. Weird model, good thing I don't have any personal projects on AppVeyor! Logging in and out would be a pain.

Now I'm in!

![image](https://user-images.githubusercontent.com/8040367/30227652-69d15f1c-94a8-11e7-95a6-29ad1ed90cc5.png)

**Comment by jnm2** [comment]
Oooh, settings... 😈

**Comment by CharliePoole** [comment]
Agreed... this is weird. It's the first I've heard about it as well.

**Comment by ChrisMaddock** [comment]
Yeah, I think it was a bit of an afterthought!

Sorted? Thanks Charlie - closing. 🙂

**Comment by jnm2** [comment]
Yes, thank you Charlie!
