### ISSUE TITLE
Assert on Dictionary Content

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#24]
Add constraints that test whether a dictionary contains a certain key and a certain value.

Based on request at https://bugs.launchpad.net/nunit-3.0/+bug/780607

**Comment by CharliePoole** [comment]
Testing for a key is complete for beta-1 release.

**Comment by constructor-igor** [comment]
Please, could you add expected Assert construction for the issue?

**Comment by CharliePoole** [comment]
Take a look at what was done in PR #483. We want this one to be symmetrical, so that would mean a DictionaryContainsValueConstraint and some syntax for Contains.Value. We'll need tests too, of course.

Assert.That(dictionary, Contains.Value("something")) should work.

**Comment by constructor-igor** [comment]
please, could you assign the issue to me?

**Comment by rprouse** [comment]
@constructor-igor, I wasn't able to assign this issue to you, so I set the status to started. Consider it yours.

**Comment by constructor-igor** [comment]
pull request #604

**Comment by CharliePoole** [comment]
If you make the reference in one direction (e.g. PR to issue) you can trust github to make it in the other direction. See above. :-)

**Comment by CharliePoole** [comment]
@constructor-igor Even though it's already closed, I have managed to assign this to you. :-)
