### ISSUE TITLE
OSX Job on Travis takes forever to start

### ISSUE THREAD

**Issue by OmicronPersei** [nunit/nunit#2403]
Notice after 41 minutes the job still hasn't started.

![alt](http://i.imgur.com/sxAOKwv.png)

Refers to [this](https://travis-ci.org/OmicronPersei/nunit/builds/270645243) build.

**Comment by CharliePoole** [comment]
We're kind of used to this, I'm afraid. Appears to be a resource problem with travis-ci.

**Comment by jnm2** [comment]
Well, at least this is documented. I didn't know this was an expected thing.

https://dotnetfoundation.org/about:

> AppVeyor - We have a Professional FOSS subscription with AppVeyor allowing projects access to the latest version of Visual Studio and the fastest category of build servers.

Too bad they don't mention Travis. That's the slow one.

**Comment by OmicronPersei** [comment]
Is there any reason we can't start doing all OS builds on Appveyor?

**Comment by jnm2** [comment]
@OmicronPersei I can't find any evidence that they provide anything but Windows environments (https://www.appveyor.com/docs/build-environment/). We should be executing tests in each OS if possible.

**Comment by OmicronPersei** [comment]
Oh I didn't know Appveyor was like that.  Yeah we definitely should test against every OS, I just falsely assumed each CI solution would offer _all_ the major OSs :)

**Comment by CharliePoole** [comment]
I thought AppVeyor was just Windows.

In any case, I think it's good to build and test under various CI systems and the Travis Linux jobs are often done before AppVeyor in my experience.

We previously reacted to Travis' slowness in starting OSX jobs by making them optional. Within the past few weeks, we decided to make them required. Then the slowness started happening again. 😞 

It's a bit annoying, but it doesn't usually slow us down. We generally go ahead and merge if that's the only problem.

**Comment by jnm2** [comment]
But if you find an alternate free-for-OSS build host (without limits that we might hit) that does OS X, any of us can test drive it.

**Comment by jnm2** [comment]
I imagine the slowness with OS X is that they are a more expensive resource and you're waiting in a queue.

**Comment by OmicronPersei** [comment]
Since we joined the .NET Foundation, are there any alternatives they can offer for OSX CI?  What about funds to purchase a VM/VPS to run an instance of Jenkins on? (provided we were able to buy a license of OSX)?

**Comment by OmicronPersei** [comment]
Since Travis is seemingly out of our control, I'll close this, unless someone disagrees.

**Comment by OmicronPersei** [comment]
Looking at the pricing, the only "free" version supports two "team members".  Speaking of which, does NUnit actually have funds, or are we poor? :(

**Comment by jnm2** [comment]
The Cake team may have gotten a deal through the .NET Foundation too.

**Comment by jnm2** [comment]
Travis is r_e_a_l_l_y bad recently and it always seems to be build job 3. Any clues why?

**Comment by OmicronPersei** [comment]
Well it is the OSX build, my guess is their resources are stretched so thin that spurious problems occur more often.  Although I haven't personally investigated it so...

**Comment by jnm2** [comment]
Oh, I didn't realize it was the only OS X build. Duh. 😄 
It can be irritating but on the bright side- having to wait almost an hour before merging isn't *all* bad.

**Comment by jnm2** [comment]
Unless you're Rob and you're getting out a hotfix I guess. 😄

**Comment by jnm2** [comment]
![image](https://user-images.githubusercontent.com/8040367/30221737-7a448740-9492-11e7-8bfb-c85bfa9cd25e.png)

o.O

On the other hand, this did feel a bit long...

**Comment by CharliePoole** [comment]
Requiring the IoS builds to pass was a recent decision. We used to run them but not require them for merge. So that's why you are noticing this all of a sudden. Ironically, the decision was motivated by the fact that the long-term resource issues seemed to have been solved by the Travis folks.

**Comment by jnm2** [comment]
![image](https://user-images.githubusercontent.com/8040367/30225065-22bed504-949f-11e7-8a59-62f4b12304e5.png)

Should I cancel and restart if it goes over an hour?

**Comment by CharliePoole** [comment]
What has started is the overall build, which consists of three jobs. Two of the three jobs have completed successfully. If you cancel the whole thing, all three jobs will be re-queued. You could just cancel the third job, but it has not even started running, so that would probably put you farther back in the queue. The only things to do are to either wait or override and merge anyway - assuming that's what you want to do.

**Comment by ChrisMaddock** [comment]
There seems to be another temporary issue with macOS. If you look down the page, there's be a couple this week.

https://www.traviscistatus.com/

**Comment by jnm2** [comment]
It finally kicked the bucket 😆 
![image](https://user-images.githubusercontent.com/8040367/30233395-5fbc1182-94c3-11e7-953d-3e147157cda6.png)
