### ISSUE TITLE
Enable constraints to return an inconclusive message

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2408]
I just ran into a scenario where it would be cool to do:

```cs
Assert.That(foo, IsIdenticalCopy.Of(bar))
```

and have it sometimes return a message and an inconclusive state.
Because that inconclusive part is really important, I'm probably going to have to forgo constraints:

```cs
IsIdenticalCopy.Assert(foo, bar);
```

If I had to guess, it doesn't seem like a complex type of thing to implement.
Does this sound interesting?

**Comment by jnm2** [comment]
(Before someone asks– `foo` is a `MethodInfo`, not a collection.)

**Comment by CharliePoole** [comment]
Constraints either succeed or fail. It's assertions and tests that give additional results. For example, if a constraint fails under the control of Assume.That, you get an inconclusive result.

**Comment by jnm2** [comment]
That is the current state of things, but is that a necessary state? Assume.That with an inconclusive or failing constraint result would give an inconclusive test result, Assert.That with an inconclusive constraint result would give an inconclusive test result, and Assert.That with a failing constraint result would give a failing test result.

In this case, sometimes there is not enough information for a constraint to succeed or fail and there is a message explaining why. Would you have it succeed with the message or fail with the message?

**Comment by CharliePoole** [comment]
It's not necessary, but it's the design of the assertion mechanism. All types of assertions give a passing result if they pass, but different Assert verbs indicate what should happen if the assertion fails.

Verb      | Result on Failing Assertion
-----------|----------------------------------
Assert    | Failure
Assume | Inconclusive
Warn     | Warning

This has been pretty fundamental to how NUnit works since the constraint-based assertions were added.

Can you give an example of calling a constraint that wouldn't have enough information to succeed or fail?

**Comment by jnm2** [comment]
Sure. In this case the constraint allows a nice fluent style in line with my other tests which use NUnit constraints which is why I picked it. This constraint reads the opcodes of two compiled methods and succeeds if they are semantically identical (even though token values are different). If not, it fails and shows where. If the method being tested is compiled with optimizations disabled, it should be inconclusive because the IL is not semantically identical. (Lots more locals are introduced and used.)

**Comment by CharliePoole** [comment]
I can see where that would be useful to you and how constraints might have worked that way, but it isn't how anything else works.

The more usual NUnit approach would be...

```C#
Assume.That(method1, Is.Unoptimized);
Assume.That(method2, Is.Unoptimized);

Assert.That(method1, Is.EquivalentTo(method2));
```

Additionally, you could consider it an error (throw an exception) if the EquivalentTo constraint is used on an optimized method, thereby allowing it's use by itself without the pre-condition check.
I like that approach because it makes it clear that the first tests are pre-conditions and the final one is the actual test.

**Comment by ChrisMaddock** [comment]
It sounds interesting, but I'm struggling to see a sufficiently wide-range of use-cases, to justify the extra complexity at the moment. That said - I don't use inconclusive anyway...

**Comment by jnm2** [comment]
@CharliePoole Okay, so require (in my case two) test lines rather than one. That seems like a good option since we don't have enough use cases to justify inconclusive contraints.

@ChrisMaddock Fair enough! 😁 This is usually what it looks like when I use them: https://github.com/Microsoft/ILMerge/blob/master/ILMerge.Tests/Integration/ConsoleTests.cs#L42

**Comment by jnm2** [comment]
@nunit/framework-team I tagged this issue `closed:wontfix` because even though the verb implies a bug rather than a feature, it's still the most representative of the decision made. Is this a good use of the tag or do we need to edit or create one?

**Comment by ChrisMaddock** [comment]
Maybe that's why I never use Inconclusive - we don't multi-target at all...

The tag seems close enough to me. :sligh

**Comment by CharliePoole** [comment]
@jnm2 Typically, I put assumptions in the SetUp method, it saves some code in the test. Some people prefer the extra line, however, for clarity.

The `closed:wontfix` label is perfect and doesn't imply a bug. I use it whenever we decide not to do something that has been asked for, even if it has reasonable points in its favor. ☹️

**Comment by jnm2** [comment]
> Typically, I put assumptions in the SetUp method, it saves some code in the test. Some people prefer the extra line, however, for clarity.

That's a good suggestion, so long as that doesn't require class fields (not parallel safe) to communicate values from the setup to the test, and so long as the assumption doesn't require access to a parameterized test's parameters. (Or do we parameterize SetUp?)

**Comment by CharliePoole** [comment]
Good point about parameters. That's a limitation of SetUp in a way. That is, you can only do those things that are common to all the tests, which excludes the value of the arguments. So... never mind. 😄

**Comment by jnm2** [comment]
@CharliePoole We could always expose them to SetUp and TearDown via a test context API, as I remember seeing requested here: https://github.com/nunit/nunit/issues/1395

**Comment by CharliePoole** [comment]
Yes... ironically, another use of `closed:wontfix` 😄 

Note that the same SetUp is used for all tests, which may have different numbers and types of arguments. That could lead to a pretty complicated SetUp method.

**Comment by jnm2** [comment]
To be honest, these days it's so rare for all these dimensions to align in a way that allows me to use `SetUp` and `TearDown` that it's easier to stick with my convention of never using them. 😆 

I wouldn't be in favor of implementing #1395. I think that using C# method parameters, `using` and `Assert.That(() => ..., Has.MaxTime())` is more idiomatic C# than using `SetUp` and `TearDown`.

**Comment by CharliePoole** [comment]
@jnm2 Can you post an example of what you mean? It may not get into NUnit, but I __am__ working on a new framework. 😄

**Comment by jnm2** [comment]
@CharliePoole The competition could bring some interesting developments... 😆 

If I was designing a new framework, it would recommend putting tests in static classes by default:

```cs
static class FooTests
{
    public static void Foo(int testCaseParameter, CancellationToken optionalInjectedTokenForCooperativeCancel)
    {
        using (var someSetupThing = CreateSetupThing())
        {
            Assert.Timeout(optionalTimeoutCancelToken =>
                new Foo(someSetupThing).Bar(optionalTimeoutCancelToken), 10_000);
            // or
            Assert.That(() => new Foo(someSetupThing).Bar(default),
                Has.MaxTime(someCriterion ? 1_000 : 10_000)));
        }
    }
}
```

**Comment by jnm2** [comment]
@ChrisMaddock All my tests at work which can be inconclusive are static-analysis-type tests which give up when simulating runtime behavior is too complex.

**Comment by jnm2** [comment]
For example, making sure every date edit control across the whole app has been configured a certain way, or making sure every list control has certain formatting styles so that common consistency issues are caught. Sometimes it's not possible to instantiate a `Control` descendant without loading context that is out of scope for the test, so it alerts you that it's inconclusive and that you need to keep an eye on it, while at the same time not failing the CI builds.
