### ISSUE TITLE
AbortOrKillThreadWithMessagePump fails on my PC

### ISSUE THREAD

**Issue by OmicronPersei** [nunit/nunit#2409]
>Test Name:	AbortOrKillThreadWithMessagePump_StressTest
Test FullName:	NUnit.Framework.Internal.ThreadUtilityTests.AbortOrKillThreadWithMessagePump_StressTest
Test Source:	C:\GitRepos\nunit\src\NUnitFramework\tests\Internal\ThreadUtilityTests.cs : line 75
Test Outcome:	Failed
Test Duration:	0:00:15.123

Running on my PC (Windows 10, intel core i7 dual core), executing using the NUnit test adapter in VS2017.

**Comment by jnm2** [comment]
It's expected that it will fail on every PC given enough stress unless you bump up the timeout on the test it's stress testing. That's why it's marked [Explicit]. It should never run unless you explicitly single it out.
See the explanation in https://github.com/nunit/nunit/pull/2401.

Do you have a suggestion of what you'd expect we should change?

**Comment by jnm2** [comment]
It's particularly sensitive to the CPU you have. I ran it on an i7-4790K.

**Comment by OmicronPersei** [comment]
Ah I missed that it's explicit.

I've been working on a PR in the namespace `NUnit.Framework.Internal` and it's been easy to just tell VS to run all of the testing within that namespace.  I guess that would mean it runs explicit tests in there, too.

**Comment by OmicronPersei** [comment]
(Recently rebased my feature branch, hence I'm just now seeing that test being executed and fail.)

**Comment by jnm2** [comment]
Perhaps https://github.com/nunit/nunit3-vs-adapter/issues/278 is relevant?

**Comment by CharliePoole** [comment]
Precisely. 😈

**Comment by jnm2** [comment]
I feel like running explicit tests came up in https://github.com/nunit/nunit3-vs-adapter/issues but I'm not finding the discussion.

**Comment by OmicronPersei** [comment]
Since it's explicit and expected to fail when ran, I will close this.

**Comment by CharliePoole** [comment]
@jnm2 Explicit tests can't work correctly under VS in any situation where the runner does the selection of tests. That's because VS has no concept of Explicit. We can resolve this in some situations, but not all.

nunit/nunit3-vs-adapter#47 deals with one situation where we could resolve it.
