### ISSUE TITLE
Specflow 2.1 and below attribute dependency

### ISSUE THREAD

**Issue by BlythMeister** [nunit/nunit#2414]
Specflow 2.1 and below are dependent on the TestFixtureSetUpAttribute and TestFixtureTeaeDownAttribute

Whilst these are marked as obsolete in 3.7 and specflow updated not to use them
An nunit 3.8 update forces a specflow update which is not always possible.

Proposal from #2410 was to create issue to re-adding these attributes to allow older specflow to work with newer nunit.

For information, specflow issue https://github.com/techtalk/SpecFlow/issues/612 updated their usage of attributes

**Comment by ChrisMaddock** [comment]
This also affected JustMock. https://github.com/telerik/JustMockLite/issues/29

I don't believe we fully considered the use of the attributes in third-party libraries as opposed to user code when we merged the PR. 😞 I think we should consider reverting the merge, and waiting until the next major version to remove the attributes instead - they're not doing much harm in the codebase, and removing them caused more problems that we expected.

**Comment by ChrisMaddock** [comment]
@rprouse - depending what we decide, this would be another candidate for a hotfix imo.

**Comment by rprouse** [comment]
Wow, it is annoying that several years in these 3rd Party frameworks are still ignoring the deprecation warnings. I guess they load them through reflection?

I am a bit torn on this one. Putting them back in will not encourage third party frameworks to update. My guess is that we will have the same issues reported against the eventual 4.0 release. They never read the breaking changes and deprecations for 3.0, so why would we expect them to do the same for 4.0?

It also sounds like it is fixed in newer versions of SpecFlow.  @BlythMeister why can you upgrade NUnit but not SpecFlow? This issue will be just as valid if we wait to NUnit 4 as we won't support older versions of frameworks.

Would it be better to to out to JustMockLite and submit a pull request?

I am open to changing my mind, but if we revert I think we will be in the same position later.

**Comment by BlythMeister** [comment]
if i upgrade nunit and not specflow the auto generated specflow code uses the old attributes.
They have fixed their stuff because of the obsolete...but also added other dependencies i can't cater for...

**Comment by jnm2** [comment]
@BlythMeister I think Rob is saying, why are you updating your NUnit dependency if you aren't willing to update your SpecFlow dependency?

**Comment by BlythMeister** [comment]
3.7 introduced a performance issue which was resolved in 3.8
I want the performance fix....but i don't want all the breaking changes and hell fire that comes with it.

**Comment by jnm2** [comment]
Just so I understand- you want the performance fix in NUnit 3.8, but also upgrading SpecFlow at the same time causes breaking changes and hellfire? (If not, then why not just upgrade your SpecFlow dependency?)

Your EDIT2 strikes me as reasonable.

**Comment by BlythMeister** [comment]
You are correct.
I want the bug/perf fix from 3.8.
To get 3.8 I also HAVE to upgrade specflow (due to removed attribute)
Upgrading specflow means I also have to upgrade newtonsoft Json, which I am currently unable to do.
Therefore specflow upgrade is also not currently possible.

So I'm stuck on 3.7 with the perf bug

If the perf bug fix was put as a 3.7.x hotfix, I would be happy to accept I can't get to 3.8 until I take the large upgrade pain, as long as I can still get the bug fixes.

**Comment by jnm2** [comment]
Thank you the details. They are very helpful and I can sympathize.

@rprouse What you you think of keeping the obsolete stuff removed and instead of doing that hotfix, do a 3.7.2 performance hotfix?

**Comment by BlythMeister** [comment]
The downside is, if I or someone else finds a bug with 3.7.2 at a later date say after 3.10 is released...what happens.

Normally, when a breaking major release happens, you might patch the old...since this is not a new major version, but has breaking changes...the "rule book" doesn't exist....

**Comment by jnm2** [comment]
@BlythMeister I'm used to working with frameworks which use the major version for branding and make breaking API changes in patches. I know that some tenets of semver have gone mainstream and I'm in favor of shunning source- and binary breaking changes but @CharliePoole brought up some good points in https://github.com/nunit/nunit/issues/2410#issuecomment-326776503 too and we're still having that discussion.

**Comment by jnm2** [comment]
At the end of the day your scenario would not be any different than if we went straight from 3.7.1 to 4.0.0. If you found a bug in 3.7.2, you'd still have to either go to 4.0.0 and put pressure upstream, or ask for 3.7.3. Same as now.

**Comment by BlythMeister** [comment]
I see where your coming from, and essentially my main issue is specflow adding Json as a dependency.
So have raised upstream too 👍
https://github.com/techtalk/SpecFlow/issues/930

**Comment by rprouse** [comment]
I am closing old Idea issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
