### ISSUE TITLE
Question: Using [Parallelizable] with single assembly

### ISSUE THREAD

**Issue by BeakerAU** [nunit/nunit#2416]
We are using SpecFlow, and have a single test assembly with approx 2000 tests defined. They currently take approx. 14hours to run, so I've been experimenting with running the tests in Parallel using the new [Parallelizable] attribute.

However, it seems that all the parallelization options (--workers, --agents, etc) all rely on a single process being responsible for a test assembly. If I need to run these in parallel, it seems like I am required to separate my test assembly.

Is this correct?

The only other option I can see, is to run nunit-console --explore to get the list of tests to run, then manually start n x nunit-console processes to run the tests.

**Comment by CharliePoole** [comment]
NUnit has two kinds of parallel execution Framework and Engine. They are each described in the docs:
 * https://github.com/nunit/docs/wiki/Framework-Parallel-Test-Execution
 * https://github.com/nunit/docs/wiki/Engine-Parallel-Test-Execution

The two types are completely independent. Framework parallelism relates to running tests and fixtures in parallel within a single assembly. The Parallelizable attribute pertains to this as does the --workers command-line option.

Engine parallelism is between different assemblies, each run in a separate process. The --agents option pertains to this.

There is nothing built into NUnit that allows for running the tests within a single assembly in more than one process. An assembly is always loaded into one process and worker threads are used to achieve parallelism within that process.
