### ISSUE TITLE
Support equality comparison delegate

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2418]
This is already possible today:

```cs
Is.EqualTo(...).Using<Foo>((x, y) => x.CompareTo(y)))
```

The delegate returns `int` which allows you to pick one: equal, greater than, or less than. It's a sorting comparison rather than an equality comparison.

I have a similar scenario with objects in a third party library that provide `IsEqual` but do not override `Equals` (:thinking:...). This should work:

```cs
Is.EqualTo(...).Using<Foo>((x, y) => x.IsEqual(y)))
```

But because it returns `bool` rather than `int`, it does not work. I am forced to arbitrarily convert equal/inequal to either 0/1 (equal/greater than) or 0/-1 (equal/less than). I don't like this because an ordering comparison does not make sense in this context, only a pure equality comparison.

```cs
Is.EqualTo(...).Using<Foo>((x, y) => x.IsEqual(y) ? 0 : 1))
```

In my opinion, I should be able to return a `bool` directly from any arbitrary delegate and NUnit should use it like it uses `bool IEqualityComparer<>.Equals` similar to the effect of this final workaround:

```cs
private sealed class FooEqualityComparer : IEqualityComparer<Foo>
{
    public static FooEqualityComparer Instance { get; } = new FooEqualityComparer();
    private FooEqualityComparer() { }

    public bool Equals(Foo x, Foo y) => x.IsEqual(y);

    // I don't even want to think about implementing the hash code on this property bag.
    public int GetHashCode(Foo obj) => 0;
}
```

**Comment by jnm2** [comment]
To implement, start by creating a new test helper called `GenericEqualityComparison`, imitating [`GenericComparison.cs`](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/tests/TestUtilities/Comparers/GenericComparison.cs). We need a delegate type with the signature `(T, T) => bool`. We should probably use `Func<T, T, bool>` since the BCL does not have an `EqualityComparison<T>` delegate type. Then make the `GenericEqualityComparison` version of this test:

https://github.com/nunit/nunit/blob/e7c7826da8b064cfcc518b1035e1c270588abc79/src/NUnitFramework/tests/Constraints/EqualConstraintTests.cs#L564-L570

And proceed to add the `Func<T, T, bool>` overloads to make the test pass. Along the way you'll need to create an `EqualityAdapter.For` overload which adapts `Func<T, T, bool>` to the `EqualityComparer` shape, just like this does for `IEqualityComparer<T>`:

https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Constraints/EqualityAdapter.cs#L187-L206

**Comment by david-proctor** [comment]
I'll take this issue if that's all right with everyone.

**Comment by jnm2** [comment]
@david-proctor Fantastic, thanks!

**Comment by david-proctor** [comment]
Submitted PR #2460.
