### ISSUE TITLE
Publishing symbols with releases

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2421]
We should provide debug symbols with every release so that people can step into the source code, set breakpoints, view variables, etc.

Can we start publishing PDBs with our NuGet package? We could make it part of our Cake script to index the PDBs with https://github.com/GitTools/GitLink so that the source code is pulled from GitHub when people step into the framework dll.

https://oren.codes/2015/09/23/enabling-source-code-debugging-for-your-nuget-packages-with-gitlink/

**Comment by jnm2** [comment]
@sharwell gave some pointers at https://gitter.im/nunit/nunit?at=59b1a2ce81cd9a5d7e9d8b45.

**Comment by jnm2** [comment]
I've tested this in the field quite a bit in unrelated projects using the new `/embed` C# compiler option. I'd like to finish this off.

This will affect the @nunit/framework-team's day jobs and side projects since it will be easy to drop into NUnit code any time you want to understand what's going on. It will also affect NUnit users who may return the courtesy by taking some initiative in diagnosing bugs they observe. Creating a repro is much easier when you aren't dealing with a black box!

Here are our options:

### 1. Ship [source-_embedded_](https://github.com/ctaggart/SourceLink#embedding-source-files) PDBs in the NuGet package

Integrates with csc.exe through MSBuild targets in a NuGet package.

**Pro**: No network connectivity to GitHub is needed for the debugger to pull the raw files for the right commit.

**Pro**: No headache making sure the PDB is linked to the right commit and verifying that the links and checksums work.

**Con**: No source is available in the debugger for NUnit consumers [prior to VS 2017 Update 5](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes#EmbeddedSource). No loss for them but no gain.

**Con**: Every NUnit source file which contains a method is compressed and embedded in the PDB which is then packed into the nupkg. (However, hard disk space is cheap, and "just working" is a terrific tradeoff.)

### 2. Ship [source-_linked_](https://github.com/ctaggart/SourceLink#sourcelink) PDBs in the NuGet package

Integrates with csc.exe through MSBuild targets in a NuGet package. A separate tool is needed to verify (see Con) which we would invoke from the Cake script.

Requires this Debug Options setting to be checked (it is on by default): 
![image](https://user-images.githubusercontent.com/8040367/34971070-52b6be86-fa46-11e7-93cb-8f73088a1d9e.png)

  **Con**: When you step into an library method, the debugger shows message box asking whether to allow downloading from github.com (there is an "always yes" option) and of course this requires network access

  **Con**: Every release should probably have some kind of [verification step](https://github.com/ctaggart/SourceLink#test) making sure the right commit is linked and publicly available on GitHub and all the hashes match in case something changed the local source files from the commit.

  **Con**: No source is available in the debugger for NUnit consumers [prior to VS 2017 RTW](https://github.com/dotnet/core/blob/master/Documentation/diagnostics/source_link.md#tooling). No loss for them but no gain.

### 3. Ship [source-_indexed_](https://github.com/GitTools/GitLink#gitlink) PDBs in the NuGet package

Does not integrate through MSBuild. We would add an additional Cake packaging step which would index and verify the PDBs using the GitLink support built in to Cake.

Requires this Debug Options setting to be checked (it is off by default):
![image](https://user-images.githubusercontent.com/8040367/34971276-7118da2a-fa47-11e7-8dc5-2d3440126097.png)

  **Pro**: Works all the way back to VS*2005*.

  **Con**: When you step into an library method, the debugger shows message box asking whether to allow **executing arbitrary code on your machine** out of the PDBs from the NuGet package (there is an "always yes" option) and of course this requires network access

  **Con**: Every release should probably have some kind of [verification step](https://github.com/ctaggart/SourceLink#test) making sure the right commit is linked and publicly available on GitHub and all the hashes match in case something changed the local source files from the commit.

### More

Knowing how each works from a technical standpoint, I don't know of any reason we couldn't combine two or all three approaches into the same PDBs. But I won't look into that unless we think that is desirable to get the best experience no matter which version of VS you're using.

I didn't explore shipping the PDBs in a separate .symbols.nupkg which is traditionally uploaded to a symbol server because that's a barrier to consumption– you have to find and paste a magic URL into your VS debugger symbol server settings– and everyone seems to be moving away from the practice. \<Repeat point about hard disk space here>
From personal experience, it's celestial to be able to turn off Just My Code<sup>1</sup> and immediately step into a library's source without knowing I was going to need to do that before I started debugging, and without breaking my train of thought and researching the symbol servers for the library.

<sup>1</sup> Even better [with an assigned keyboard shortcut](https://marketplace.visualstudio.com/items?itemName=SamHarwell.JustMyCodeToggle) (I kept bugging Sam 😄)

**Comment by ChrisMaddock** [comment]
I love it, and I would support enabling them for pre-vs-2017. 😊

**Comment by rprouse** [comment]
I like the idea assuming the PDB's don't get too large. The framework DLL is ~340 KB and the PDB is currently ~1.4 MB. That said, the Intellisense XML is nearly 1 MB. This is multiplied by the number of platforms we support, but I expect that would compress well with the duplication.

We would want to do the same with the engine so that users can seamlessly step through all layers. Most users will also likely be debugging their tests using the adapter in Visual Studio, so does this leak out there too? Personally, being able to debug the adapter might be useful sometimes 😄

**Comment by jnm2** [comment]
@rprouse 

> I like the idea assuming the PDB's don't get too large. The framework DLL is ~340 KB and the PDB is currently ~1.4 MB. That said, the Intellisense XML is nearly 1 MB. This is multiplied by the number of platforms we support, but I expect that would compress well with the duplication.

Along with the CSPROJ merge, we switched to the portable PDB format rather than the Windows format since it was custom-made with .NET in mind rather than shoe-horned into the native Windows PDB format. It is regularly ten times smaller. Right now the 3.10's framework PDB is over eight times smaller at 174 KB, half the size of the framework assembly.

However, supporting the debugger stepping into NUnit with versions of Visual Studio earlier than 2015.2 (and without dotPeek/ReSharper/JustDecompile/ILSpy/etc) means we should switch back to the legacy format. GitLink (the source-server tool we would be using) doesn't work with portable PDBs either last I checked. So we'd expect to ship the 1.4 MB PDBs in the NuGet packages.

It definitely makes sense for the console and agent and engine-related assemblies. I don't know how VS extensions are loaded, so we'd have to experiment to see if PDBs are autodiscovered.

How about adding it for NUnit Framework and NUnitLite (everything we ship in this repo) and take what we learn from that to open a new issue on the other repos?

Are we okay with the PDB size factor required by supporting versions of VS from 2005-2015.1? We could expect the packages to almost double in size with the Windows Format and maybe grow by a tenth with the portable format. I can get real numbers on this comparison if you're interested.

**Comment by ChrisMaddock** [comment]
I think large package size is an ok tradeoff for VS 2015 support - but I'm not overly attached to that idea of Rob disagrees.

**Comment by rprouse** [comment]
I would prefer to see real numbers before I make a final decision on this. I am not overly concerned about size on disk, more about download size of the `nupkg`. Is it easy enough to do a spike and get the numbers?

**Comment by jnm2** [comment]
@rprouse Sure. These results are:

- without GitLink. The only difference GitLink will make embeds an executable binary in each PDB for the debugger to invoke to download sources.
- assuming we pack a PDB for every exe and dll:
  - `nunit.framework.dll`
  - `nunitlite.dll`
  - `nunitlite-runner.exe` and `nunitlite-runner.dll`
  - not `NUnit.System.Linq.dll` because this repo does not build it)

|               |    NUnit | NUnitLite |      zip |
|---------------|---------:|----------:|---------:|
| Windows PDBs  | 3,658 KB |    592 KB | 5,632 KB |
| Portable PDBs | 1,935 KB |    329 KB | 3,650 KB |
| No PDBs       | 1,495 KB |    250 KB | 3,130 KB |

Taking the NUnit package, portable PDBs increase the size by 29% and Windows PDBs by 145%.
I'm not afraid of either number though. Disk space is a good thing to be able to trade off.

**Comment by jnm2** [comment]
@rprouse Sure. These results are assuming we pack a PDB for every exe and dll:
  - `nunit.framework.dll`
  - `nunitlite.dll`
  - `nunitlite-runner.exe` and `nunitlite-runner.dll`
  - not `NUnit.System.Linq.dll` because this repo does not build it

|                   |    NUnit | NUnitLite |      zip |
|-------------------|---------:|----------:|---------:|
| No PDBs           | 1,495 KB | 250KB     | 3,130 KB |
| Portable PDBs     | 1,935 KB |    329 KB | 3,650 KB |
| Windows PDBs      | 3,658 KB |    592 KB | 5,632 KB |
| PDBs with GitLink | 3,752 KB |    598 KB | 5,762 KB |

Taking the NUnit package, portable PDBs increase the size by 29% and Windows PDBs by 145%.
With GitLink, that's +151%. I don't have the SourceLink or embedded source numbers to compare that to though.

Personally I'm not afraid of the numbers. Disk space is a good thing to be able to trade off.

**Comment by jnm2** [comment]
@rprouse Sure. These results are assuming we pack a PDB for every exe and dll:
  - `nunit.framework.dll`
  - `nunitlite.dll`
  - `nunitlite-runner.exe` and `nunitlite-runner.dll`
  - not `NUnit.System.Linq.dll` because this repo does not build it

TODO: measure SourceLink.

| Options                      |    NUnit | NUnitLite |      zip |    × |
|------------------------------|---------:|----------:|---------:|-----:|
| No PDBs                      | 1,495 KB | 250 KB    | 3,130 KB | 1    |
| Portable PDBs (embed source) | 5,602 KB | 706 KB    | 7,692 KB | 3.75 |
| Windows PDBs (GitLink)       | 3,752 KB | 598 KB    | 5,762 KB | 2.51 |

| (for fun)                   |     NUnit | NUnitLite |       zip |    × |
|-----------------------------|----------:|----------:|----------:|-----:|
| Portable PDBs               | 1,935 KB  | 329 KB    | 3,650 KB  | 1.29 |
| Windows PDBs                | 3,658 KB  | 592 KB    | 5,632 KB  | 2.45 |
| Windows PDBs (embed source) | 10,923 KB | 1,328 KB  | 13,633 KB | 7.31 |

**Comment by jnm2** [comment]
@rprouse Here are the final numbers for each approach, assuming we pack a PDB for every exe and dll:
  - `nunit.framework.dll`
  - `nunitlite.dll`
  - `nunitlite-runner.exe` and `nunitlite-runner.dll`
  - not `NUnit.System.Linq.dll` because this repo does not build it

| Options                      | NUnit            | NUnitLite | zip      | Min VS |
|------------------------------|-----------------:|----------:|---------:|--------|
| No PDBs                      | 1,495 KB (1.00×) | 250 KB    | 3,130 KB |        |
| Portable PDBs + embed source | 5,602 KB (3.75×) | 706 KB    | 7,692 KB | 2017.5 |
| Portable PDBs + SourceLink   | 1,936 KB (1.29×) | 332 KB    | 3,652 KB | 2017   |
| Windows PDBs + GitLink       | 3,752 KB (2.51×) | 598 KB    | 5,762 KB | 2005   |

| (for fun)                   |             NUnit | NUnitLite |       zip | Min VS |
|-----------------------------|------------------:|----------:|----------:|--------|
| Portable PDBs               |  1,935 KB (1.29×) |    329 KB |  3,650 KB |        |
| Windows PDBs                |  3,658 KB (2.45×) |    592 KB |  5,632 KB |        |
| Windows PDBs + SourceLink   |  3,659 KB (2.45×) |    592 KB |  5,634 KB | 2017.3 |
| Windows PDBs + embed source | 10,923 KB (7.31×) |  1,328 KB | 13,633 KB | 2017.5 |

I was surprised to see how poorly the source code compresses. Even so I'm fine with any of the options, from 1.29× to 3.75× the original size. Just tell me which to finalize.

**Comment by rprouse** [comment]
Nice summary thanks. The size of the windows PDBs and embedded source code is starting to get a bit too big, especially since it only works on the latest version of VS.

With GitLink, does GitHub end up acting as the source server? In other words, is the source pulled from a commit on GitHub? Pretty cool if it does, but we will need to be careful with our release process to ensure that the commit matches the release. We will probably want to finish #2661 and include GitLink in that process.

I am leaning towards GitLink because of the wide support and reasonable size. It has the disadvantage of only working with Windows PDBs, but nothing before Visual Studio 2017 supports them either.

How are others leaning on this?

**Comment by jnm2** [comment]
> With GitLink, does GitHub end up acting as the source server? In other words, is the source pulled from a commit on GitHub? Pretty cool if it does, but we will need to be careful with our release process to ensure that the commit matches the release.

Yes, both the GitLink option (VS2005, windows PDBs only) and the SourceLink option (VS2017) download all source code on the fly from GitHub. I have this listed as a con because of the care you need to take with the release commit you push.

> We will probably want to finish #2661 and include GitLink in that process.

I am not aware of a tool that verifies GitLink v3 PDBs, as in, actually downloading the entire codebase URL by URL and making sure the commit hash is publicly accessibly and that line endings match, etc. It would also be a lengthy process. Without writing such a tool, here's all that there is to do: https://github.com/nunit/nunit/commit/7bb4f8ee5408538949ffd655c76b0df92000ca1c.

**Comment by rprouse** [comment]
Assuming that we only do builds and releases on build machines, we will know that the GitLink step is going against a valid checkin. It bothers me that we have such a great CI process but we are still releasing builds done on developer machines. That needs to change, thus #2661.

It looks like you are nearly ready to PR. Shall we go with GitLink?

**Comment by jnm2** [comment]
That makes sense.
I spotted a couple edits I didn't finish, but Chris and I are happy with GitLink so if you are, I'll PR.

**Comment by rprouse** [comment]
Sounds good, ship it!

![Ship It](https://media.giphy.com/media/d6WWh3Em7kWHu/giphy.gif)
