### ISSUE TITLE
Has.No.Items

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2437]
We can say `Has.Exactly(0).Items` but we can't say `Has.No.Items`.

We can say `Is.Empty`, but sometimes it's misleading grammar:

```cs
var cups = new List<Cup>();
Assert.That(cups, Is.Empty);
```

This is not contrived; `SomeType.IsEmpty` is a popular .NET idiom.
I would rather say:

```cs
var cups = new List<Cup>();
Assert.That(cups, Has.No.Items);
```

The implementation should be easy; rather than `ConstraintExpression`, just return ItemsConstraintExpression which `Exactly` is returning.

**Comment by jnm2** [comment]
Thinking ahead, we should think about providing `Has.One.Item`. It's an alternative to `Has.Exactly(1).Items` which solves the pluralization mismatch without adding `.Item` beside `.Items`.

Then, if we were to do that, would we want `Has.No.Items` or `Has.No.Item`?
`Has.No.Items.EqualTo` vs `Has.No.Item.EqualTo`?

Also, we could allow `Has.None` to be resolvable though personally I like `Has.No.Item/s` better.

**Comment by CharliePoole** [comment]
Seems to me we had a pretty extensive discussion about this stuff on some issue.

**Comment by mikkelbu** [comment]
@CharliePoole Perhaps you are thinking about #2004 and the accompanying PR #2283 which introduced `Has.One` as a "shorthand" for `Has.Exactly(1).Items`.

**Comment by CharliePoole** [comment]
That's the one!

**Comment by jnm2** [comment]
Ah, I thought I was missing something! I'm still on 3.7.1 at work because #2145 makes tests impossible for me with 3.8.0 and up.

So we do have `Has.One.Items` already. My suggestion would be to add a `.Item` property to `ItemsConstraintExpression` so that people can do whatever suits them. We would have `Has.Exactly(1).Item` and `Has.One.Item`, and then we would have `Has.No.Items` and `Has.No.Item`.

Any cons to that approach?

**Comment by CharliePoole** [comment]
So Item and Items would be synonyms? Has.Exactly(5).Item?

I'd prefer not to add a syntactic element just for grammatical concordance. This is supposed to be English-like, not English.

**Comment by jnm2** [comment]
@CharliePoole Yes, synonyms. But I can do without. I would like `Has.No.Items` then though.

**Comment by CharliePoole** [comment]
This is off the top of my head, but `Has.No.Items` strikes me as problematic. `Has.No` and `Has.Not` are synonyms and return a `ConstraintExpression` with a `NotOperator` on the operator stack. Whatever else you do after has to be defined on `ConstraintExpression` and will be negated.

**Comment by CharliePoole** [comment]
I've never been confused by `Is.Empty`

**Comment by ChrisMaddock** [comment]
This a complex bit of API already - I don't like the idea of adding _more_ ways to do the same thing. That's ok for advanced users, but leaves new users trying to work out the different functionality of all the different syntax.

IMO, things like this we should note down for a v4.0, where we could look at changing syntax we don't like.

**Comment by jnm2** [comment]
Sounds good. Mefore I close- can we have a `v4-review` tag?

**Comment by ChrisMaddock** [comment]
I replied to this twice, but looks like neither got through. 😞 Sorry!

We already have a v4 wiki page - maybe adding a bullet to that would be easier to review, when the time comes? 🙂

**Comment by rprouse** [comment]
>This a complex bit of API already - I don't like the idea of adding more ways to do the same thing. That's ok for advanced users, but leaves new users trying to work out the different functionality of all the different syntax.

I agree. Whenever we add additional syntax, users invariable mix it with other syntax in ways that we don't expect and causing headaches. It also confuses users when there are multiple ways to do the same thing. We already have too many of those.

**Comment by jnm2** [comment]
Wasn't a problem, Chris.

Done. https://github.com/nunit/docs/wiki/Notes-Toward-NUnit-4.0

**Comment by letaoana** [comment]
On current version the **RepeatAttribute** is only valid on method declarations. For future versions can we have it added at the level of a class?

**Comment by CharliePoole** [comment]
That would require a new feature request issue. On the surface, it's hard to see what the use would be so if you create an issue, you should give some use cases.

**Comment by julealgon** [comment]
Folks, has there ever been any discussion about separating the test runner from the assertion engine?

I know the folks behind the `Should` library propose this, and I have to agree with them. Why are we coupling the assertion mechanism to the runner? What prevents people from ignoring NUnit's Assertion classes completely and using something else?

It seems like a better design to me to have these decoupled into their own NuGet packages, and let consumers chose what they want.

**Comment by CharliePoole** [comment]
@julealgon Yes, there has. See #502.

I'm a fan of this, but it didn't get enough traction and was closed. I'm currently playing around with a design to do this from scratch in a new framework.

**Comment by julealgon** [comment]
> I'm a fan of this, but it didn't get enough traction and was closed. I'm currently playing around with a design to do this from scratch in a new framework.

Interesting. If this design is public, I'd really like to participate if possible @CharliePoole . I know I'm new to this repo (have been using mostly MSTest and just now faced with a project using NUnit), but I'd be willing to help in the discussions. Just let me know ;)

**Comment by CharliePoole** [comment]
I have a backlog, but I'll get to this eventually. 😄 If not, keep watching for notices on the discussion list.
