### ISSUE TITLE
Question about one of breaking change (TestCaseSource must be static) NUnit 3.X.

### ISSUE THREAD

**Issue by aytacasan** [nunit/nunit#2444]
Hi,

[https://stackoverflow.com/questions/45871241/migration-problems-when-migrate-from-nunit-2-x-to-nunit-3-x/45881240?noredirect=1#comment79447976_45881240](stackoverflow)

I have only one project (a little bit complex financial project) that using NUnit 2.X, it has 5K+ tests and when i try to migrate from 2.X to 3.X i faced many difficulties.

There is my question above link and there is "Update 2" part inside the question. And i asked one of your contributor that "Could you please tell me what are the technical reasons that run static test case methods before initialize/setup method? Is this because of NUnit or because of infrastructure of .Net Framework?"

Like i said in that question; I'm not fanatic about NUnit and/or TDD (i only used NUnit purpose of test framework but also i develop only one project with TDD). I don't have deep knowledge about these concepts but it does not make sense to me: run any method before setup method.

Thanks,
Aytac

**Comment by CharliePoole** [comment]
There are so many things discussed in the SO post, that I would ask you to re-post here only those parts about which you currently have concern. We don't need all the steps you went through to get there, just some idea of your current code, what you want to see happen and what is actually happening.

Regarding the question about static test case methods... they are __not__ run before the setup method. NUnit executes tests in the following order...

Load Tests
   Calls all your test case source and similar methods and generates the tests
Run Tests
   Run higher level OneTImeSetUp (SetUp fixture)
   for each test fixture
     Run test fixture OneTimeSetUp
     foreach test in fixture
       Run setup
       run the test
       run teardown
     Run test fixture OneTimeTearDown
   Run higher level OneTimeTearDown (SetUp fixture)

**Comment by rprouse** [comment]
@aytacasan it has been a long time since we made this decision and I can't find the issue where we discussed it, so I can't remember all of the reasons, but it boils down to the way NUnit discovers then runs tests. We first do a pass through the code and determine all of the tests to be run by checking for test attributes and expanding `TestCaseSource`'s. If the `TestCaseSource` was not static, we had to instantiate the class in order to run the `TestCaseSource` and get the data to construct the tests. To start with, this was inefficient, but it also led to a series of subtle issues where data was different between the discovery and test run phases.

I am going to close this issue as a question. If you would like to continue the discussion, just post a comment, we will see it even if it is closed.

**Comment by aytacasan** [comment]
@rprouse @CharliePoole - Thanks gentlemen for your clarifications. First of all i want to share my link again, because i think i can not share it correctly : [https://stackoverflow.com/questions/45871241/migration-problems-when-migrate-from-nunit-2-x-to-nunit-3-x](url)

Second is actually i solve all my problems about update my project's NUnit package from 2.X to 3.X already now. But i want to clarify something because maybe it'll help to development process of NUnit;

My project have Config.cs and it's using JSon syntax for read general runtime configurations from file. It's a static class and has static property "Settings" for get JObject which is containing all settings. Before upgrade NUnit, my getter method checking file (config.json) first, if exist then reading file and creating & returning the object. If not exist returning empty JObject. At that time when i debug my tests i see first higher level setup method working first then my config tests working, so static Settings property's getter method working after setup method too.

After upgrade NUnit package first of all i see test directory is not correct and so never finding the config file so returning Settings JObject always empty object. I added below code to my higher level OneTimeSetup method;

`            var assembly = Assembly.GetExecutingAssembly();
            var localPath = new Uri(assembly.CodeBase).LocalPath;
            var direcotyName = Path.GetDirectoryName(localPath);
            if (direcotyName != null)
            {
                Environment.CurrentDirectory = direcotyName;
            }`

After that i see some test still not passing and when i check it i see TestCaseSource methods must be static method. I change all TestCaseSource methods to static. After that i see my setup method calling after Settings property's getter method, because of that returning empty JObject and tests not passing again. Why?

Because NUnit first solving test methods and their TestCaseSource methods, This mean TestCaseSource methods calling before setup method and my config tests contain a TestCaseSource method which is creating TestData that creating some objects (check my link there is a Symbol objects) that accessing static Config classes's static property's getter method. As a result;

NUnit calling static TestCaseSource,
My static TestCaseSource creating some objects need to access static property getter,
At that point i never read config.json file because at that point setup method not called and so test directory not set and config.json file not accessible (Original config.json added to test project via linking).

I solve my problem like that; instead returning empty object when file not exist, i added hundreds of config lines to my object from config.json file. Is it ugly? (YES) Is it right way? (Don't not) But my problem is solved.

Again i'm not an expert about TDD and/or NUnit. This is only sentiment, setup must be run before everything (yes you said already it's calling first but because of static TestCaseSource rule it's not working like that for my project). Maybe i'm evaluate the situation wrong. Only want to share my experience with you. Decide to change or not that logic, it's up to you.

Regards,
Aytac

**Comment by rprouse** [comment]
Instead of getting the `ExecutingAssembly` to find the test directory, you should be able to switch to `TestContext.CurrentContext.TestDirectory`

**Comment by aytacasan** [comment]
@rprouse - I used like ExecutingAssembly because of this issue [https://github.com/nunit/nunit/issues/1072](url)

I think you mean instead use below code;

```
            var localPath = new Uri(assembly.CodeBase).LocalPath;
            var direcotyName = Path.GetDirectoryName(localPath);
            if (direcotyName != null)
            {
                Environment.CurrentDirectory = direcotyName;
            }
```

Use this;

`            Environment.CurrentDirectory = TestContext.CurrentContext.TestDirectory;`

**Comment by CharliePoole** [comment]
Yes. That's what @rprouse was suggesting - see also issue #1072 as well as the docs.

That said, if you can avoid setting the current directory, that's the best approach. Instead create a full path using `TestContext.CurrentContext.TestDirectory`. In general, changing the current directory is a very unfriendly action for a program to take. It will also break your tests if you run multiple tests in parallel and set it to different values.

**Comment by aytacasan** [comment]
@CharliePoole - Thanks for your answer. Yes i understand you and agree with you. For my current project i have to change current directory. But if i use NUnit with new project, absolutely i'll create a full path using TestContext.CurrentContext.TestDirectory.
