### ISSUE TITLE
CI failure in mono Warning tests

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#2446]
Just seen a new mono CI failure I haven't seen before - .NET 4.0 build only. It's flakey - it went away on a rebuild.

https://travis-ci.org/nunit/nunit/jobs/276500189

```
1) Failed : NUnit.Framework.Assertions.WarningTests.StackTracesAreFiltered("WarningAfterAwaitTaskDelay",3)
  Expected: less than or equal to 3
  But was:  5
  at NUnit.Framework.Assertions.WarningTests.StackTracesAreFiltered (System.String methodName, System.Int32 maxLineCount) [0x000ac] in <c07632bf29c04487b0d0b138c27780c6>:0 
```

@jnm2 - would you mind taking a look? I know you did some work here recently 🙂

**Comment by rprouse** [comment]
I've seen that once on Mono too. Rerunning the test fixed it, so it might be a timing issue.

**Comment by jnm2** [comment]
What do you guys favor- altering the test to show the whole call stack, which I'm curious to see, and leaving the limit of 3 so that we can note what the call stack was, or just bump the limit up to 5?

**Comment by mikkelbu** [comment]
I say the first option "show the whole call stack" and leaving the limit at 3. If we then get wiser from the full call stack then we can always bump the limit.

**Comment by ChrisMaddock** [comment]
I agree. Just changing the limit without knowing why doesn't seem the best solution - there's no rush to get it fixed!

**Comment by rprouse** [comment]
Also agreed 😄
