### ISSUE TITLE
API Proposal: MethodConstraint

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#2449]
I make a lot of use of the property constraint - it's great that I can get a more useful error message.

With the PropertyConstraint, I can do the following:

```
Assert.That(MyThing, Has.Property("IsValid").EqualTo(false));

Expected: property IsValid equal to False
But was:  True
```

What I currently can't do, is anything equivalent for methods. I'm currently limited to the following, uninformative error messages:

```
Assert.That(MyThing.MyMethod(1), Is.EqualTo(false));

Expected: False
But was:  True
```

My issue is the error message here gives me no information - and I have to go to the test code to discover what I've broken. 

---

What I'd like to be able to do, is something like this:

```
Assert.That(MyThing.MyMethod, Passed(1).EqualTo(false));

Expected: MyMethod(1) equal to False
But was:  True
```

I think it would be possible to do this without needing to pass a method name string, and instead retrieving that from the MethodGroup via reflection.

What do people think to the concept? Anyone suggest an improved API, over 'Passed'?

**Comment by ChrisMaddock** [comment]
My initial suggest wouldn't be refactor-safe of course. Maybe a better API would be something like this...

```
Assert.That(() => MyThing.MyMethod(1), Evaluates.EqualTo(false));

Expected: MyMethod(1) equal to False
But was:  True
```

I don't know if it's possible to get the method name out of such a lamda...I'd need to investigate that.

**Comment by jnm2** [comment]
Method constraints would have come in handy for me too several times.

If my memory serves, we'd want to take an `Expression<Func<T>>` and the method name would be accessible. Even more of the expression would also be accessible too, if you chained method calls and/or properties, though we wouldn't have to look any further than we want.

**Comment by jnm2** [comment]
We could get all Shouldly about it (https://stackoverflow.com/questions/39959272/how-does-the-shouldly-assertion-library-know-the-expression-the-assertion-was-ap) but that's quite the investment and Shouldly already exists. 😁
