### ISSUE TITLE
Debugging nunit tests in .net core using vs code

### ISSUE THREAD

**Issue by UnderNotic** [nunit/nunit#2458]
Is there any way to debug tests in vscode?

**Comment by rprouse** [comment]
It should just work by clicking on the CodeLens icons. See https://github.com/nunit/docs/wiki/.NET-Core-and-.NET-Standard to make sure you are referencing required packages. You also need the C# extension installed.

![image](https://user-images.githubusercontent.com/493828/30837507-5ac1831a-a233-11e7-9946-c9632bf26e45.png)

![image](https://user-images.githubusercontent.com/493828/30837519-7350b14e-a233-11e7-82e0-22c53340143f.png)
