### ISSUE TITLE
TestContext.CurrentContext NullReferenceException in Visual Studio 2015

### ISSUE THREAD

**Issue by m-finn** [nunit/nunit#2463]
Hi,

I'm experiencing a null reference exception on TestContext.CurrentContext {"Object reference not set to an instance of an object."} when running my tests in Debug in MS Visual Studio. They work fine when i use VS Test Explorer to run them. It looks like everything in  TestContext is null.

Do i need an adaptor of some sort to run debug. Sorry i couldnt find anything online.

.Net Framework 4.5.2 
NUnit Framework 3.7.0

**Comment by CharliePoole** [comment]
How do you run tests in VS without using Test Explorer?

Running under test explorer you need the NUnit adapter of course. The only other ways would involve some third party solution.

**Comment by m-finn** [comment]
Hi Charlie,

Thanks. Sorry yes I also have the Nunit3TestAdaptor nuget package 3.7.0 installed.

Can I not run the tests in Debug mode in VS (-> Start button)?

Sorry I'm not fluent in this, I'm eventually wanting to create a dll and run this from the nunit3-console.exe. I was going to try debug in VS first.

**Comment by CharliePoole** [comment]
You can only run from the debug button if you set up an executable runner as the start program, passing it the name of your test assembly as an agument. You can use nunit3-console for that purpose. For debugging individual tests, it's convenient to use the context menu for that item in test explorer.

Feel free to bring your how-to questions to our nunit-discuss google group. Filing an issue is best reserved for bugs and adding comments on closed bugs will only work if someone happens to notice it!

**Comment by m-finn** [comment]
thanks for clarifying, its appreciated (i thought this may have been a compatibility issue)

kind regards
