### ISSUE TITLE
Test execution hangs when using [SetUpFixture] with NUnit 3.8.x

### ISSUE THREAD

**Issue by jairbubbles** [nunit/nunit#2467]
It hangs with console runner (3.7) and also with  R# (2017.2).

Here are the log files when using `--labels:before`:
[nunit_3_8_1.txt](https://github.com/nunit/nunit/files/1348973/nunit_3_8_1.txt)
[nunit_3_7.txt](https://github.com/nunit/nunit/files/1348974/nunit_3_7.txt)

When running in R# we see that tests from other namespace never start:
![image](https://user-images.githubusercontent.com/15875066/31078940-53e98a3c-a784-11e7-9d16-59819e8e2e9f.png)

It seems related to `public class AssemblySetup` which has the attribute `[SetUpFixture]`.

**Comment by mikkelbu** [comment]
Hi @jairbubbles can you also provide the InternalTrace-files when you add verbose logging (i.e. `--trace=Verbose`).

**Comment by jairbubbles** [comment]
It seems highly related to my namespaces not being clean.

In `TeaBox.Macros.Test` assembly I have two main namespaces being tested:
- `TeaBox.Macros` in wich `AssemblySetup` is a `SetUpFixture` 
- `TeaBox.Scripting`

I I move tests from `TeaBox.Scripting` tests to `TeaBox.Macros.Scripting` it works correctly.

**Comment by jairbubbles** [comment]
(I'll try to make a simple repro case)

**Comment by jairbubbles** [comment]
Here we go:
[BugNUnit.zip](https://github.com/nunit/nunit/files/1349087/BugNUnit.zip)
It's pretty straight forward, run all tests and observe that the test in the exotic namespace will never run:
![image](https://user-images.githubusercontent.com/15875066/31080512-3198934c-a789-11e7-975b-80e7120c5697.png)


(You need VS2017).

**Comment by ChrisMaddock** [comment]
Great, nice example @jairbubbles. To save other's having to download - here's the repro. (I haven't tried it myself.)

There were some changes in this area for 3.8 which introduced a few problems we've been rooting out.  My guess is the particular specific things about your case we haven't seen before are a combination of:
1. A SetUpFixture for only _some_ of your tests.
2. No parallelization attributes at all.

```
using NUnit.Framework;

namespace BugNUnit
{
    [SetUpFixture]
    public class AssemblySetup
    {
        public AssemblySetup()
        {
        }
    }

    [TestFixture]
    public class TestInNamespace
    {
    }
}

namespace OtherNamespace
{
    [TestFixture]
    public class TestInAnotherNamespace
    {
    }
}
```

**Comment by jairbubbles** [comment]
I can confirm you that adding `[Parallelizable]` on of the test fixture does fix the issue too.

**Comment by CharliePoole** [comment]
Assigning this to myself for now so we don't duplicate one another. I'm adding this as a case to the suite of parallelization tests I'm working on.

**Comment by developer-edp** [comment]
I'm having the same issue with my integration tests and since they depend on the database I'm hesitant to run the tests in parallell. For others in my situation: my bandaid solution until proper fix is to rename the tests/namespaces so that the tests that isn't part of the SetupFixtures is run before anything else. Smelly I know, but a temporary solution that seems to be working.

**Comment by agray** [comment]
I think I might be suffering the same issue. My code base is now open sourced at https://github.com/Sauceforge/Saucery/tree/master/NUnit/Version3

**Comment by CharliePoole** [comment]
I added tests to demonstrate that this is not an NUnit framework problem. It may be that there is an adapter issue, of course, but I wanted to clear the issue here first.
