### ISSUE TITLE
Framework incorrectly identifies Win 10 in xml results

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#2475]
This is the second half of https://github.com/nunit/nunit/issues/2102

`Environment.OSVersion` is [deprecated](https://msdn.microsoft.com/en-us/library/system.environment.osversion(v=vs.110).aspx), and no longer reports the correct Windows version from Windows 10.

The framework uses this in two places - NUnit2XmlOutputWriter and FrameworkController - in both cases to write xml results. These should both be changed to report the correct platform.

The logic for all this is already in the OSPlatform class, it should just be an issue of making use of this correctly to write the correct value in the results.

**Comment by j4nw** [comment]
I'd like to do this!

**Comment by ChrisMaddock** [comment]
Great, thanks @j4nw - it's yours!
