### ISSUE TITLE
[Feature] Add a "Test" target to easily run tests from MsBuild

### ISSUE THREAD

**Issue by jairbubbles** [nunit/nunit#2480]
Now that MsBuild supports by default "restore" and "pack" (at least in the official documentation) I feel like it will be cool to support a "test" target.

Similar to `dotnet.exe test` we would run `msbuild.exe /t:test <path_to_the_csproj>` and the tests would be executed. The .csproj would only have to reference the good NUnit package and no .exe installed on the machine would ne needed.

`NUnit.ConsoleRunner` is a "tool" only package, we could have the "test" target in the "build" folder or we could have a new package `NUnit.MsBuildTask` we would depend on `NUnit.ConsoleRunner`. Please note that there's already a NUnit3 task over [here](https://github.com/loresoft/msbuildtasks/blob/master/Source/MSBuild.Community.Tasks/NUnit3.cs) but it only looks for `nunit3-console.exe` in Program Files. 

If you feel interested I'd happy to contribute as I'm interested in both MsBuild and NUnit.

**Comment by ChrisMaddock** [comment]
We use the NUnit 3 MSBuild Community Task you linked to at work. I don't know a lot about MSBuild though, so I have some naive questions.

1. Have you tried a contribution to the existing task, to instead first look for a local console, before checking for an installed console? Writing an entire new task just to check a different tool location seems overkill - am I missing something?

2. I'm confused by your packaging comments - why would we need to change the package structure? Can you link me to something that explains? 

My initial gut reaction is that this would be a great open source tool, but possibly lives outside the scope of the NUnit project. I'm not sure I fully understand the work that's needed here though - so I'll withhold judgement!

**Comment by jairbubbles** [comment]
Yes when you put a `.targets` file in  the `build` folder of your package it will be used automatically when building your project.

Manually add a new target in a project is pretty straight forward, just add these lines:
```xml
<Target Name="Tests">
   <NUnit3 Assemblies="$(OutputPath)/$(TargetFileName)" ToolPath="$(NuGetPackageRoot)\nunit.consolerunner\3.7.0\tools\" />
</Target>
```

And you can run the tests by running:
```
msbuild.exe /t:test <path_to_the_csproj>
```

It's not ideal as I also have to reference two packages:
```xml
<PackageReference Include="NUnit.ConsoleRunner" Version="3.7.0">
<PackageReference Include="MSBuildTasks" Version="1.5.0.235" />
```

Moreover if you run it on the solution it will fail on projects that don't have that target. I think I'll check on the MsBuild side what are their plans on the subject.

**Comment by stevewi1950** [comment]
Hi, just for info...
The NUnit3 task in the MSBuild.CommunityTasks does allow you to specify where the nunit3-console exe is via the ToolPath.

<NUnit3 Assemblies="@(TestAssemblies)" 
              ToolPath="$(MSBuildProjectDirectory)\lib\NUnit\console" 
              Process="Single" 
             OutputXmlFile="$(MSBuildProjectDirectory)\build\TestResults.xml"/>

Hope this clears things up.  I know the documentation in the project is not 100% clear but all of the tasks allow you to specify the path to the tool.

Regards.

**Comment by jairbubbles** [comment]
Yes that's what I do in my example!

The point of this is to be able to run NUnit tests from everywhere as simply as possible.

Now for running tests with Visual Studio we just need the "NUnit3TestAdapter" and it works like a charm. For command line it's more complex as we need to install NUnit on the machine.

**Comment by jnm2** [comment]
I understand the appeal of now requiring a machine-level installation of NUnit. One issue with putting nunit3-console.exe etc in the same package as the build target is that the build target isn't necessarily going to know the path to nunit3-console. You shouldn't assume people are going to be using the crippled `packages.config` where the packages are cached relative to the solution.

What I've done in writing similar a NuGet package with MSBuild targets (in my case ILMerge project integration) is to have the target create a `tools` folder like Cake does, download nuget.exe into it, and `nuget install NUnit.Console -ExcludeVersion -OutputDirectory tools` and invoke `nunit3-console.exe` from there. The `tools` path defaults to be solution-level and can be overridden; you can in fact share tools and nuget.exe with Cake. Through the magic of incremental build, this is only a first-time perf hit.

**Comment by jairbubbles** [comment]
> One issue with putting nunit3-console.exe etc in the same package as the build target is that the build target isn't necessarily going to know the path to nunit3-console.exe. 

If you put the .exe and the build .targets in the same package it is quite easy to find the path of the executable. You just need to use MsBuild properties like `MSBuildThisFileDirectory`. It will be something like `($MSBuildThisFileDirectory)\..\tools\nunit3-console.exe`

**Comment by jnm2** [comment]
Good, thanks for pointing that out. 

It's not like you'd ever have an existing project referencing NUnit.Console which would be messed up by the NUGet  package starting to add a Test target. I think this is a cool idea, definitely preferable to requiring global state (machine install) for the build script.

**Comment by jairbubbles** [comment]
Actually I think the change will be just to add a `build/NUnit.targets` file in the `NUnit.ConsoleRunner` package that contains:
```
<Target Name="Test">
   <NUnit3 Assemblies="$(OutputPath)/$(TargetFileName)" ToolPath="($MSBuildThisFileDirectory)..\tools\nunit3-console.exe" />
</Target>
```
It's a pretty simple change and I have the feeling that it will have no impact at all for people using this package as a "tool" package.

**Comment by rprouse** [comment]
@jairbubbles would adding the targets conflict with .NET Core based test projects that don't use the Console to run tests? Could we add platform specific targets in the package?

**Comment by kkm000** [comment]
@jairbubbles: Absolutely! The simplest test I can think of is ` '$(MSBuildRuntimeType)' == 'Core' `.

It is also worth noting that `dotnet test` runs the target named `VSTest`, not `Test`, at the least how I see it from the binlog on Windows. The whole things happens in [this file](https://github.com/Microsoft/vstest/blob/master/src/Microsoft.TestPlatform.Build/Microsoft.TestPlatform.targets). Perhaps it is even possible to leverage the task DLL.

**Comment by kkm000** [comment]
And apparently the whole thing also comes in packages: https://www.nuget.org/packages?q=Microsoft.TestPlatform

**Comment by aolszowka** [comment]
I know this is old FWIW we were looking to do something similar and created this https://github.com/aolszowka/NUnit.MSBuild still requires the console to be installed. I like the idea of getting the console runner burned into the package somehow.

**Comment by rprouse** [comment]
@aolszowka can't you just make the NUnit console package a dependency of your package to force it to install rather than "bake it in"?

**Comment by jnm2** [comment]
I think that would work. Here's an example of relying on a restored NuGet dependency: https://github.com/tunnelvisionlabs/ReferenceAssemblyAnnotator/blob/master/TunnelVisionLabs.ReferenceAssemblyAnnotator/TunnelVisionLabs.ReferenceAssemblyAnnotator.targets#L80

**Comment by jairbubbles** [comment]
I don't have this need anymore, so I'm closing that issue.
