### ISSUE TITLE
Message when asserting null with Is.EquivalentTo could be more helpful

### ISSUE THREAD

**Issue by appel1** [nunit/nunit#2486]
If `result.Things` is null in the following example the failure message is a little bit confusing. 

```csharp
Assert.That(result.Things, Is.EquivalentTo(new[] { "abc" }));
```

Message:
`System.ArgumentException : The actual value must be an IEnumerable`

Perhaps the null case could have a more specific message?

**Comment by ChrisMaddock** [comment]
I don't see any harm in someone implementing this. I think it may be slightly non-trivial, but I haven't looked in detail.

As I'm sure you're aware, if `result.Things` is possibly null, for now you could do:

    Assert.That(result.Things, Is.Not.Null.And.EquivalentTo(new[] { "abc" }));

**Comment by ChrisMaddock** [comment]
I'll label this up-for-grabs soon, but would like to give it 24 hours or so, and give anyone else the chance to disagree!

**Comment by mikkelbu** [comment]
I also think that this is a reasonable wish.

Note, that "the change" probably needs to be done in approx 10 places to be consistent, as we have similar checks for `IEnumerable` in most collection constraints.

**Comment by ChrisMaddock** [comment]
I was overthinking this.

It would be trivial to include a different _error_ message when actual is null. The current error message is meant for when a non-ienumerable is passed in, not when a 'null ienumerable' is passed in. It would be more involved to instead produce a custom failure message.

**Comment by jnm2** [comment]
I'm not opposed to changing it to a failure message like "Expected: IEnumerable But was: null`.

But if we keep it as an exception message, I've always thought it was the perfect message. It's a well-known C# fact that `null` is not `IEnumerable` (see `null is IEnumerable`).

**Comment by josteink** [comment]
I've submitted a PR for this issue. Consumer-wise and code-wise the result should be the same as before, but with another exception-message.
