### ISSUE TITLE
Different order of actual and expected in collection asserts

### ISSUE THREAD

**Issue by LazyPotato** [nunit/nunit#2487]
Hello,
we are using custom comparers in asserts and have discovered this insignificant though annoying problem. 

`Assert.That(actual, Is.EqualTo(expected).Using(comparer)` 
In overridden `Equals(T first, T second)` method of comparer **expected** comes as **first**, **actual** - as **second**.

`Assert.That(actualCollection, Does.Contain(expected).Using(comparer)` 
In this case, comparing the elements of collection with the expected element reveals inverted behavior: an element from the actual collection comes as **first** and **expected**" as **second**.
This is really confusing for the customization of fail message.

Looking through NUnit source code i've noticed next difference. 
In the EqualConstraint class arguments for the `NUnitEqualityComparer.AreEqual` method are passed in order (expected, actual).
However, arguments for the method `CollectionItemsEqualConstraint.ItemsEqual` (and then for AreEqual) are passed in the inverted order as in the CollectionContainsConstraint class for example.
`if (ItemsEqual(obj, Expected))
                    return true;`

Thats not really a big deal, but i suppose that behavior should be unified? Or maybe there is some reason for that i missed?
Thanks.

**Comment by jnm2** [comment]
The contract of .NET's equality comparer APIs is that they are symmetric. When your custom comparer code implements IEquatable or IComparable, you're making the promise that callers can switch the two parameters at random without any effect on the outcome.

I apologize that this issue has not been answered already!

**Comment by jnm2** [comment]
https://msdn.microsoft.com/library/bsc2ak47.aspx:

> The following statements must be true for all implementations of the Equals(Object) method. In the list, x, y, and z represent object references that are not **null**.
> 
> - `x.Equals(x)` returns **true**, except in cases that involve floating-point types. See ISO/IEC/IEEE 60559:2011, Information technology -- Microprocessor Systems -- Floating-Point arithmetic.
> 
> - `x.Equals(y)` returns the same value as `y.Equals(x)`.
> 
> - `x.Equals(y)` returns **true** if both x and y are **NaN**.
> 
> - If `(x.Equals(y) && y.Equals(z))` returns **true**, then `x.Equals(z)` returns **true**.
> 
> - Successive calls to `x.Equals(y)` return the same value as long as the objects referenced by x and y are not modified.
> 
> - `x.Equals(null)` returns **false**. 
> 
> Implementations of Equals must not throw exceptions; they should always return a value. For example, if _obj_ is **null**, the Equals method should return **false** instead of throwing an ArgumentNullException.
> 
> Follow these guidelines when overriding Equals(Object):
> 
> - Types that implement IComparable must override Equals(Object).
> 
> - Types that override Equals(Object) must also override GetHashCode; otherwise, hash tables might not work correctly.
> 
> - You should consider implementing the IEquatable<T> interface to support strongly typed tests for equality. Your IEquatable<T>.Equals implementation should return results that are consistent with Equals.
> 
> - If your programming language supports operator overloading and you overload the equality operator for a given type, you must also override the Equals(Object) method to return the same result as the equality operator. This helps ensure that class library code that uses Equals (such as ArrayList and Hashtable) behaves in a manner that is consistent with the way the equality operator is used by application code.

**Comment by jnm2** [comment]
> This is really confusing for the customization of fail message.

This sounds like there might be an X-Y situation going on here. We want to make sure you can do what you need to do without hacks like IEqualityComparers that craft messages. What is your ultimate goal?

**Comment by CharliePoole** [comment]
Adding to @jnm2's comment... NUnit equality, as represented by it's equality asserts, is symmetric with respect to the interpretation of what equality means, but non-symmetric WRT the creation of an error message and the application of certain types of tolerance.

When a comparer is provided through `Using`, it is only used to test equality and the order of its arguments should have no impact on the message. If you can provide an example where it does, that would be another matter. 😄 

The method `NUnitComparer.AreEqual` is applying NUnit's notion of equality, as it applies to tests. So the order of arguments is important there. Among other things, if there are two different Types involved, the `Equals` override on the expected value is used as a last resort.

**Comment by LazyPotato** [comment]
Thanks for the reply!
Actually, i can't recall the exact case we had a problem with. I suppose we have changed our message cutomization somehow.
Anyway,  this makes the implied Nunit code clear for me

> So the order of arguments is important there. Among other things, if there are two different Types involved, the Equals override on the expected value is used as a last resort.

Sorry for the inconvenience, i think i should close this issue for now.

**Comment by jnm2** [comment]
@LazyPotato It's no inconvenience, so don't feel bad. It's good for us to take opportunities to explain how NUnit works!
