### ISSUE TITLE
Improve performance of discovery/execution

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#2488]
@OsirisTerje commented on [Thu Sep 28 2017](https://github.com/nunit/nunit3-vs-adapter/issues/392)

It has been found that discovery of test cases are slowed down by the processing of traits.

**Comment by rprouse** [comment]
This is a copy of an issue in the adapter. We've found that some of our internal XML processing code is causing performance problems in larger test suites. Some fixes have been made in the adapter, but improvements can be made in the framework too. This needs investigation and performance testing to determine what can be done.

See https://github.com/nunit/nunit3-vs-adapter/issues/392

**Comment by ChrisMaddock** [comment]
This is related to the issue below that I wanted to look at a few days ago. 🙂 At least for the 'run individual test' workflow - not overall performance.

https://github.com/nunit/nunit/issues/3#issuecomment-334953472

**Comment by rprouse** [comment]
@navin22 will add some performance issues he has found to this issue.

**Comment by navin22** [comment]
I see the following as the top time consuming calls in the latest release of 3.9.0-dev-04564 version

Cross App Domain calls during the events NUnit.Framework.Internal.Execution.TestFinishedEvent.Send & NUnit.Framework.Internal.Execution.TestStartedEvent.Send.

![image](https://user-images.githubusercontent.com/19592945/31708479-b628b260-b40c-11e7-9845-5576d4ffb897.png)

I have uploaded the perfview traces for more analysis [here](https://1drv.ms/u/s!Ah2_fRsQIuFtgTk_uV4j0LPMvY6B).
