### ISSUE TITLE
Make it possible to specify a custom factory method for TestFixtures

### ISSUE THREAD

**Issue by erik-kallen** [nunit/nunit#2491]
It would be nice if it were possible to specify a custom factory method for tests. I propose this API:

```
[TestFixture, TestFixtureFactory(nameof(MyTests.CreateInstance))]
public class MyTests
{
    [Test]
    public void TestSomething()
    {
    }

    public object CreateInstance(Type actualType)
    {
        // actualType can be either MyTests or a class derived from it.
        return Activator.CreateInstance(actualType); // No, I won't do this :)
    }
}
```

What I am actually trying to achieve is to run all tests for a class in a separate AppDomain, and with this feature I could inherit my tests from `MarshalByRefObject` and create the object in a separate app domain and everything would (hopefully) just work

**Comment by jnm2** [comment]
If we did this, it seems like the first thing we should look at is enhancing the existing [TestFixtureSource](https://github.com/nunit/docs/wiki/TestFixtureSource-Attribute) capability to use a custom static method other than the constructor to instantiate the fixture.

**Comment by jnm2** [comment]
Also see https://github.com/nunit/nunit/issues/2280#issuecomment-335474469. Does this get you to your actual goal? If not, what are the specific shortcomings?

**Comment by CharliePoole** [comment]
We do already have a separate request for an attribute that would run tests in a separate AppDomain.

In addition, the proposed implementation doesn't leverage NUnit's normal way of building fixtures through an IFixtureBuilder attribute.

However, it doesn't seem like you really want a new kind of fixture, but to run the fixture in a different way. That would imply adding an attribute that collaborates in creating the commands to execute the test. 

I'd lean towards either rejecting this request as won't fix or as somewhat duplicating that other issue, which I can't find on my phone.

**Comment by erik-kallen** [comment]
@jnm2 If I understand that thread correctly, the solution with `IsolationUtils` would require me to use `IsolationUtils` inside every test, which is something I want to avoid.

@CharliePoole Is there a timeline for that feature? Thanks for the hint about IFixtureBuilder, I think that will solve my problem (although it will require users to use `[SeparateAppDomainTestFixture]` rather than the normal `[TestFixture]` for the tests), but I'm OK with that.

**Comment by erik-kallen** [comment]
This is the code I ended up with. Do you see any dangers?

```
    public class SeparateAppDomainTestFixtureAttribute : TestFixtureAttribute, IFixtureBuilder
    {
        private readonly NUnitTestFixtureBuilder _builder = new NUnitTestFixtureBuilder();
        private static readonly ConcurrentDictionary<Type, AppDomain> AppDomains = new ConcurrentDictionary<Type, AppDomain>();

        IEnumerable<TestSuite> IFixtureBuilder.BuildFrom(ITypeInfo typeInfo)
        {
			if (!typeof(SeparateAppDomainTestBase).IsAssignableFrom(typeInfo.Type))
			{
				throw new Exception($"The type {typeInfo.Type.FullName} must derive from {nameof(SeparateAppDomainTestBase)} in order to use the {nameof(SeparateAppDomainTestFixtureAttribute)}.");
			}

	        var domain = AppDomain.CreateDomain("TestAppDomain", null, AppDomain.CurrentDomain.SetupInformation);
            var suite = _builder.BuildFrom(typeInfo, this);
			suite.Fixture = domain.CreateInstanceAndUnwrap(typeInfo.Assembly.FullName, typeInfo.FullName);
            AppDomains.TryAdd(typeInfo.Type, domain);

            yield return suite;
        }

        internal static void TearDownDomain(Type type)
        {
            AppDomains.TryRemove(type, out var domain);
            AppDomain.Unload(domain);
        }
    }

    public abstract class SeparateAppDomainTestBase : MarshalByRefObject
    {
        protected SeparateAppDomainTestBase()
        {
            if (GetType().GetCustomAttributes().Any(a => a is TestFixtureAttribute && !(a is SeparateAppDomainTestFixtureAttribute)))
            {
                throw new Exception($"Use {nameof(SeparateAppDomainTestFixtureAttribute)} instead of {nameof(TestFixtureAttribute)} for types deriving from {nameof(SeparateAppDomainTestBase)}.");
            }
        }

        [OneTimeTearDown]
        public static void OneTimeTearDown()
        {
            SeparateAppDomainTestFixtureAttribute.TearDownDomain(TestExecutionContext.CurrentContext.TestObject.GetType());
        }
    }

    [SeparateAppDomainTestFixtureAttribute]
    public class Class1 : SeparateAppDomainTestBase
    {
        [Test]
        public void M1()
        {
        }
    }
```

**Comment by jnm2** [comment]
> If I understand that thread correctly, the solution with IsolationUtils would require me to use IsolationUtils inside every test, which is something I want to avoid.

Exactly and thanks for confirming that.

I see a race condition where the second AppDomain will not be torn down if NUnit happens to overlap two calls to `IFixtureBuilder.BuildFrom` withe the same argument. Why not get rid of the dictionary and make an internal `AppDomain` field inside `SeparateAppDomainTestBase`?

**Comment by CharliePoole** [comment]
I won't have time to give your code a real review till late in the day (PDT). A few quick comments...

NUnit attributes are not really designed for inheritance even though we don't seal them. You could run into problems, especially if you want to support parameterized fixtures.

Your fixture real __isa__ TestFixture. Tests are identified in the same way for example. You just want a minor change in how it is executed, ATL least minor from the TestFixture point of view. (Note that tests no longer execute themselves as they did in NUnit V2.)

It seems like you're making the user do a lot of work. From what you've explained about your goal, it seems as if an attribute should be able to do the job on its own.

More later...

**Comment by erik-kallen** [comment]
@jnm2 I do want to have the AppDomain as a member variable, but that requires a method of SeparateAppDomainTestFixtureAttribute to be called when the fixture is torn down. Is there such a method?
Is there a risk that NUnit will overlap calls to IFixtureBuilder.BuildFrom with the same argument? That was just the kind of questions I hoped to get answered, thanks.

**Comment by jnm2** [comment]
@erik-kallen This is what I meant:

<details>

```cs
public class SeparateAppDomainTestFixtureAttribute : TestFixtureAttribute, IFixtureBuilder
{
	private readonly NUnitTestFixtureBuilder _builder = new NUnitTestFixtureBuilder();

	IEnumerable<TestSuite> IFixtureBuilder.BuildFrom(ITypeInfo typeInfo)
	{
		if (!typeof(SeparateAppDomainTestBase).IsAssignableFrom(typeInfo.Type))
		{
			throw new Exception($"The type {typeInfo.Type.FullName} must derive from {nameof(SeparateAppDomainTestBase)} in order to use the {nameof(SeparateAppDomainTestFixtureAttribute)}.");
		}

		var domain = AppDomain.CreateDomain("TestAppDomain", null, AppDomain.CurrentDomain.SetupInformation);
		var suite = _builder.BuildFrom(typeInfo, this);
		suite.Fixture = domain.CreateInstanceAndUnwrap(typeInfo.Assembly.FullName, typeInfo.FullName);
		((SeparateAppDomainTestBase)suite.Fixture).AppDomain = domain;

		yield return suite;
	}
}

public abstract class SeparateAppDomainTestBase : MarshalByRefObject
{
	private AppDomain appDomain;	
	internal AppDomain AppDomain { set => appDomain = value; }
	
	protected SeparateAppDomainTestBase()
	{
		if (GetType().GetCustomAttributes().Any(a => a is TestFixtureAttribute && !(a is SeparateAppDomainTestFixtureAttribute)))
		{
			throw new Exception($"Use {nameof(SeparateAppDomainTestFixtureAttribute)} instead of {nameof(TestFixtureAttribute)} for types deriving from {nameof(SeparateAppDomainTestBase)}.");
		}
	}

	[OneTimeTearDown]
	public static void OneTimeTearDown()
	{
		AppDomain.Unload(appDomain);
	}
}

[SeparateAppDomainTestFixture]
public class Class1 : SeparateAppDomainTestBase
{
	[Test]
	public void M1()
	{
	}
}
```

</details>

**Comment by jnm2** [comment]
> Is there a risk that NUnit will overlap calls to IFixtureBuilder.BuildFrom with the same argument? 

I don't know of any guarantee that it won't. For example, there's a feature request that a new fixture instance is created per test case to make parallelism work with instance state. That would bring out the race condition rather dramatically. 😃 

It's additionally dependent on what the engine and runner do, not just the framework. If you use NUnitLite and decide to run two threads, or if Visual Studio via the adapter ever decides to parallelize its invocations of NUnit Framework within the same process, that's outside NUnit Framework's control.

**Comment by erik-kallen** [comment]
@jnm2 Thank you for the explanation.

Your idea to fix the race worked after a slight modification:

```
        [OneTimeTearDown]
        public static void OneTimeTearDown()
        {
            var test = (SeparateAppDomainTestBase)TestExecutionContext.CurrentContext.TestObject;
            AppDomain.Unload(test.appDomain);
        }
```

**Comment by jnm2** [comment]
Lol! Sorry for missing that. :+1:

**Comment by CharliePoole** [comment]
I made one of those mysterious disappearing comments this morning. Let's try again!

Going back to the original description...

You seem to be requiring the user to do all the work. Ideally, placing an attribute on the fixture class should be sufficient and the attribute should take care of it.

As to the type of attribute, I don't think it should be a fixture builder. Looking at what you are doing, the resulting TestFixture __isa__ NUnit TestFixture. It finds tests, for example in exactly the same way. You merely want a minor change in how the test is executed. Therefore, I think you want some type of attribute that modifies the command structure created for a fixture.

Unfortunately, we haven't defined an interface that does that for fixtures, but only for methods. 😞 We would have to create something equivalent to `ICommandWrapper` (used for methods) that applied to test fixtures. This is certainly possible and would be a general solution toward many problems of this kind.

**Comment by erik-kallen** [comment]
@CharliePoole The reason the user needs to derive from a custom class is that I need to unload the app domain when the test is run. I could not find a way for my attribute to get called after the test run is finished (although there might be a way)

**Comment by CharliePoole** [comment]
@erik-kallen Did you intend to close this? (People often click close by mistake.)

**Comment by erik-kallen** [comment]
Yes, I did. There was already a perfectly valid way to solve my problem.
