### ISSUE TITLE
EqualConstraint.Using(StringComparer.*) causes overload ambiguity error

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2492]
```cs
Assert.That("a", Is.EqualTo("a").Using(StringComparer.Ordinal));
```

fails to compile:

> CS0121 The call is ambiguous between the following methods or properties: `EqualConstraint.Using(IComparer)` and `EqualConstraint.Using<T>(IComparer<T>)`

In fact, `StringComparer` matches four of the overloads. 😆 

We could:

 1. Make the common string comparer selection case easier by adding a new overload to receive a `StringComparison` enum.

 2. Add a new `Using(StringComparer)` overload to disambiguate which forwards to any of the four other `Using` overloads.

 3. Add `Ordinal` and `OrdinalIgnoreCase` modifier properties to `EqualsConstraint` like we have with `IgnoreCase`.

 4. Leave things as they are and make this the minimum code you have to type:
    
    ```cs
    Assert.That("a", Is.EqualTo("a").Using((IComparer<string>)StringComparer.Ordinal));
    ```
    
    Or this, on the rare day that you have `using System.Collections;` already added:
    ```cs
    Assert.That("a", Is.EqualTo("a").Using((IComparer)StringComparer.Ordinal));
    ```

Opinions?

**Comment by ChrisMaddock** [comment]
Option 1 is ugly on our side, but the least obtuse to the user. That's my favourite. 👍

**Comment by jnm2** [comment]
.NET Core 2.0 added `StringComparer.FromComparison` (https://github.com/dotnet/corefx/issues/13800) but until that makes it into .NET Standard (and a version we target) we'll have to write a boring `switch`. 😁

**Comment by jnm2** [comment]
Wait! I just thought of another alternative: Add a `StringComparer` overload purely for disambiguation. What do you think of that one? I'll add it to the top.
