### ISSUE TITLE
Use ConstraintUtils.RequireActual through out the codebase

### ISSUE THREAD

**Issue by mikkelbu** [nunit/nunit#2497]
In #2489 we introduced a new helper method `ConstraintUtils.RequireActual` to verify that a given instance is a given type. The method was used in `CollectionConstraint` (https://github.com/nunit/nunit/pull/2489/files#diff-0bd8c864e13609fb56985f6d45dcd0d7R73) and `CollectionEquivalentConstraint` (https://github.com/nunit/nunit/pull/2489/files#diff-511119f00b739abcc41ccb36df45f89fR98), but we have other places were we could also use this method. At least we should use the method in the following places: 
* src/NUnitFramework/framework/Constraints/SomeItemsConstraint.cs
* src/NUnitFramework/framework/Constraints/NoItemConstraint.cs
* src/NUnitFramework/framework/Constraints/AllItemsConstraint.cs
* src/NUnitFramework/framework/Constraints/ExactCountConstraint.cs
* src/NUnitFramework/framework/Constraints/DictionaryContainsKeyConstraint.cs
* src/NUnitFramework/framework/Constraints/DictionaryContainsValueConstraint.cs

Please add tests if any of the places above is not covered by tests.

**Comment by Breemua** [comment]
I'll take this if possible

**Comment by jnm2** [comment]
Welcome! That was quick! 😄

**Comment by mikkelbu** [comment]
Fixed by #2503 
Thanks for the work  @Breemua 👍
