### ISSUE TITLE
Allow setting IgnoreAttribute on a namespace

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#2499]
Today, I wanted to ignore all tests under a certain namespace. IgnoreAttribute can currently only be applied to Methods, Classes and Assemblies - is there any reason to restrict that? As far as I can think, applying it to a namespace, if permitted, should just work?

**Comment by CharliePoole** [comment]
It's not possible to apply an attribute to a namespace. You can create a dummy `SetUpFixture` and apply certain attributes there. Whether the effect is what you want would depend on the attribute but I'm pretty sure Ignore will work.

**Comment by ChrisMaddock** [comment]
My bad - I mis-read the intellisense error message! Thanks. 😩
