### ISSUE TITLE
Honor nesting of classes when running tests

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#25]
Nested TestFixtures should be executed as sub-tests of the class that contains them.

This is based on and a necessary prerequisite for https://bugs.launchpad.net/nunit-3.0/+bug/782983

**Comment by rprouse** [comment]
This has been open for 4 years now marked as priority high, but nobody has commented. That makes me question the priority and even the validity of the feature. It makes sense from a correctness perspective, but if nobody cares?

**Comment by jnm2** [comment]
It seems too late to fix without messing people up wrt setup and teardown and test filters.
