### ISSUE TITLE
Can't handle async/await in delegate call

### ISSUE THREAD

**Issue by Heteroculturalism** [nunit/nunit#2500]
nunit 3.8.1

nunit3-console.exe NUnitBug.sln --config=Debug

The attached project has an example of not handling async/await calls within a delegate.  Execution does not resume when the asynchronous method call times out .  As such my unit test is erroneously failing.  Please advise.
[NUnitBug.zip](https://github.com/nunit/nunit/files/1392099/NUnitBug.zip)

**Comment by jnm2** [comment]
Your problem is that this method returns immediately:

```cs
      public void MethodUnderTest()
      {
         _queue.Enqueue(async () =>
         {
            try
            {
               var token = new CancellationTokenSource(500);

               await this.MethodThatNeverCompletesAsync(token.Token);
            }
            catch (Exception e)
            {
               _log.Log(e.Message);
            }
         });
      }
```

So your test fails because `sut.MethodUnderTest();` returns before waiting for the queue to do anything:

```cs
      [Test]
      [Timeout(100000)]
      public void Test1()
      {
         var q = A.Fake<IThreadQueue>();
         var log = A.Fake<ILog>();
         var sut = new ClassUnderTest(q, log);

         // Immediately execute any posted actions.
         A.CallTo(() => q.Enqueue(A<Action>.Ignored))
            .Invokes((Action action) => action());

         sut.MethodUnderTest();

         A.CallTo(() => log.Log(A<string>.Ignored))
            .MustHaveHappened();
      }
```

**Comment by jnm2** [comment]
`sut` needs to provide a way for `Test1` to wait for the queued action to complete.

(This isn't specific to NUnit; it's just doing things they way you told it to do them.)

**Comment by jnm2** [comment]
Your code is very generic so this might not be the right fix depending on the semantics of `ClassUnderTest.MethodUnderStart`, but it is a potential fix:

```cs
      public Task MethodUnderTest()
      {
         var source = new TaskCompletionSource<object>();

         _queue.Enqueue(async () =>
         {
            try
            {
               var token = new CancellationTokenSource(500);

               await this.MethodThatNeverCompletesAsync(token.Token);

               source.SetResult(null);
            }
            catch (Exception e)
            {
              source.SetException(e);
            }
         });

         return source.Task;
      }
```

And:

```cs
      [Test]
      [Timeout(100000)]
      public async Task Test1()
      {
         var q = A.Fake<IThreadQueue>();
         var log = A.Fake<ILog>();
         var sut = new ClassUnderTest(q, log);

         // Immediately execute any posted actions.
         A.CallTo(() => q.Enqueue(A<Action>.Ignored))
            .Invokes((Action action) => action());

         await sut.MethodUnderTest();

         A.CallTo(() => log.Log(A<string>.Ignored))
            .MustHaveHappened();
      }
```

**Comment by Heteroculturalism** [comment]
You're right, simply wasn't waiting long enough after invoking MethodUnderTest.  D'oh!

**Comment by jnm2** [comment]
No problem. I'd highly recommend using a TaskCompletionSource (or anything else that provides a ManualResetEventSlim) to wait for, versus waiting for a fixed about of time. If the CPU is under load, the thread can be preempted for arbitrarily large amounts of time and cause spurious failures due to incorrect testing. We see this kind of thing a lot in CI with timeouts.
