### ISSUE TITLE
Unable to use Custom Attribute in tests in another assembly

### ISSUE THREAD

**Issue by voltcode** [nunit/nunit#2502]
Scenario:

Assembly1 contains a Custom Attribute called "Blah"

Assembly2 contains a TestFixture with Test and "Blah" attributes. References are OK, meaning the code compiles correctly.

I run nunit3-console.exe on Assembly2, the test is not found.
If I remove the "Blah" attribute, the test is discovered by nunit3-console.exe

Is there a way to tell nunit to load attributes from another DLL? Should it work by design? If so, how can I dig further into this? If no, is there another extensibility mechanism that allows code reuse and the same functionality as a custom attribute?

The only custom attribute examples I found, show the Custom Attribute defined in the same assembly as tests. However this is not a desired scenario when you want to reuse code.

**Comment by voltcode** [comment]
Sorry my mistake, I didn't notice I had a nunit version mismatch between the attribute dll and the dll with tests.

**Comment by jnm2** [comment]
You may run/be running into https://github.com/nunit/nunit/issues/2230.
