### ISSUE TITLE
Include the expected result and actual result for each assertion in the test output

### ISSUE THREAD

**Issue by dynamatt** [nunit/nunit#2505]
NUnit currently only logs the expected and actual result in the test output .xml file if the test fails. It would be very helpful to have this information for each assertion, even when the test passes.

**Comment by jnm2** [comment]
@dynamatt Do you have any suggestions as to what the XML should look like? Right now you're just seeing the free text in the [`<failure>`](https://github.com/nunit/docs/wiki/Test-Result-XML-Format#failure) element, right?

**Comment by rprouse** [comment]
I am closing old Idea issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
