### ISSUE TITLE
Range attribute for decimal?

### ISSUE THREAD

**Issue by DianaKoenraadt** [nunit/nunit#2506]
Hi all, 

First off, NUnit is great, thanks for all your efforts :)
I noticed the RangeAttribute does not support decimal (from, to, step). Is there a specific reason for this? Is it by design, or open for extension?

Kind regards

**Comment by CharliePoole** [comment]
It's not possible to have a decimal attribute argument in C#. However, NUnit will accept int or double values and convert them for use with decimal parameters.

**Comment by DianaKoenraadt** [comment]
Oh, really? You live and learn. Thanks!
