### ISSUE TITLE
Retarget Solution to use the New CSPROJ Format

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#2515]
For most of the discussion and reasoning, see #2380. That PR has grown, so I am creating a separate issue to track the changes if we decide to move forward with it and release. A few key points from the PR.

This merges all of our targets into one project per assembly making maintenance easier.

![image](https://user-images.githubusercontent.com/493828/29592982-8b634f18-8775-11e7-9d54-884abb2d9477.png)

The intention is for the maximum number of potential contributors to NUnit to be able to pull our repository and build no matter what platform they are on. From my involvement in the community, the majority of non-Windows developers are using .NET Core, not Mono. The majority are also on Mac, not Linux so that is where my priorities are focused.

It is unfortunate, but the Mono project is making it very hard to support going forward as @ChrisMaddock found trying to download MonoDevelop for Mac or Windows where it points to Xamarin Studio which then in turn points to Visual Studio for Windows and for Mac. It seems like the Mono and MonoDevelop teams are only making token gestures of supporting Linux while actually concentrating on the Xamarin targets.

This aims to have a clean and easy to maintain solution that compiles out of the box on as many platforms as possible. The intention is to also switch from the old deprecated project.json format to the new csproj format. This will allow us to specify which combinations of IDE and SDKs are required clearly, where now we are working by trial and error because we are using unsupported and deprecated formats.

This will have both consequences and benefits,

- Requires Visual Studio 2017 15.3+ and .NET Core 2.0+ on Windows
- Requires Visual Studio for Mac and .NET Core 2.0+ on Mac.
- Visual Studio Code is an alternative on all platforms
- Only one project for each project. Files don't need to be added to 6 projects.
- Linux support will be limited to .NET Core until Mono catches up

I am pretty sure Linux users would have a clean development experience if we used some `$(OS)` conditionals in the project files and recommended a supported toolset. We will need to test those changes, there is a bug in Mono where OSX reports as Linux. I would prefer to do that as a separate issue and PR as the current PR is getting very large.

We will also likely want to create an issue to improve the development experience on OSX. I will delay creating those issues until the final decision is made to go forward with this issue.

**Comment by aaronfranke** [comment]
> Linux support will be limited to .NET Core until Mono catches up

Since I assume you have done research on this, would you happen to know when Mono is planning to catch up? Any links to discussions etc?

**Comment by mikkelbu** [comment]
@aaronfranke I don't know much about this area, but from https://github.com/mono/monodevelop/projects/1#card-7718175 it seems that they are working on it at the moment, but I cannot find any roadmap on their page.
