### ISSUE TITLE
When test writes something to the stdErr there is no guaranteed way to link a test-output event to a target test using ITestEventListener

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#2516]
@NikolayPianikov commented on [Thu Oct 26 2017](https://github.com/nunit/nunit-console/issues/305)

For example:

- Unit test `SuccessfulStdErrorTest` has code: `System.Console.Error.WriteLine("errorout");`

- ITestEventListener receives the following events:
```
<start-test id="0-1001" parentId="0-1000" name="SuccessfulStdErrorTest" fullname="Foo.Tests.UnitTests1.SuccessfulStdErrorTest" type="TestMethod" />

<test-output stream="Error" testname="Foo.Tests.UnitTests1.SuccessfulStdErrorTest"><![CDATA[errorout
]]></test-output>
```

`test-output` has no information id/parentId about a target test and there is no way to attach this error output. It is important to note that these events could be received from different tests simultaneously.

See this [sample](https://github.com/nunit/nunit-console/files/1418559/sample.zip)

**Comment by ChrisMaddock** [comment]
As far as I can see, @NikolayPianikov is correct - there's currently no way to associate test output with a particular test, when running in parallel, and test-names are not guaranteed to be unique.

This sounds a sensible feature for any GUI runners which wish to associate output with a particular test.

**Comment by CharliePoole** [comment]
I agree with testId. It's parentId that I have a problem with. NUnit's ids are unique within the run.

**Comment by MhdTlb** [comment]
I would like to work on this issue. But I need more explanation

**Comment by CharliePoole** [comment]
Find where we create `<test-output...>` elements in `TestOutput.ToXml()`. Add an `id` attribute along with the existing `stream` and `testname` attributes. Although order is not significant, you should probably use the same order as we use in our result XML to avoid confusion.

**Comment by ChrisMaddock** [comment]
@MhdTlb - Great! 😄  

Charlie's explanation is correct. The test ID lives on the the ITest interface, so can be retrieved and passed to the TestOutput object in the same way as the test name currently is. Then it will just want adding in the `ToXml()` method, and some unit tests adding.

Assigning this issue to myself to track progress - shout up if we can help any more. 👍

**Comment by MhdTlb** [comment]
Thanks @ChrisMaddock. It is been a while a did not pull from master but when I did to day and I tried to build the solution, I got a bunch of errors most of them are: **"*** provides a compile-time reference assembly for *** on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with ubuntu.14.04-x64."**
 
Am I missing a configuration to build the solution?
Note: I'm using Visual Studio 2017 on Windows 10 machine

**Comment by ChrisMaddock** [comment]
You may need to build in the command line, the first time around. After the initial package restore is done, I think working straight in VS will work. We’re working on fixing this.

Open a command prompt in your directory, and run ‘build’.

**Comment by MhdTlb** [comment]
I tried to use cmd and I get new error: 
**CommandLineTests.cs(137,90): error CS1061: 'IEnumerable<string>' does not contain a definition for 'ToArray' an
d no extension method 'ToArray' accepting a first argument of type 'IEnumerable<string>' could be found (are yo
u missing a using directive or an assembly reference?) [C:\Users\User\Documents\GitHub\nunit\src\NUnitFramework
\nunitlite.tests\nunitlite.tests-netstandard13.csproj]
An error occurred when executing task 'BuildNetStandard13'.**

Is there a document that could help to do proper build or set up a dev environment?

**Comment by CharliePoole** [comment]
BUILDING.md in the root of the project.

**Comment by ChrisMaddock** [comment]
@MhdTlb - can you clarify exactly what you've been doing to build on the command line? Are you using the build script in the repo?

It should be possible to run build.cmd and get a clean build - is that not the case? FYI - we're working on fixing this up properly here: https://github.com/nunit/nunit/pull/2380

**Comment by MhdTlb** [comment]
@ChrisMaddock I think there is problem with restoring Nuget packages. I tried to build the solution with Visual Studio 2015 but some assemblies were missing. I also tried to use command line to restore packages and to build but still getting same issue. Finally I installed Visual Studio 2017  which did the build for me.

**Comment by ChrisMaddock** [comment]
Glad you got up and running eventually @MhdTlb. We're working on fixing the build here: #2380
