### ISSUE TITLE
Assertion at sgen-scan-object.h:91 when running NUnit console runner on Linux on Mono

### ISSUE THREAD

**Issue by mkvonarx** [nunit/nunit#2522]
We're building our .NET 4.6.1 application on a Linux CentOS 7.4 VM with Jenkins and Mono 5.4.0.201, and run our unit tests with the NUnint 3.8.1 console runner.

Quite often (about 1-3 in every 10 execution), the NUnint console runner fails with an internal assertion. We don't see this assertions on Windows with Microsoft .NET 4.6.1 and the same NUnit 3.8.1 console runner.

The NUnit console runner fails with this output:
```
14:01:16 * Assertion: should not be reached at sgen-scan-object.h:91
14:01:16 
14:01:16 Stacktrace:
14:01:16 
14:01:16   at <unknown> <0xffffffff>
14:01:16   at (wrapper managed-to-native) object.__icall_wrapper_mono_gc_alloc_vector (intptr,intptr,intptr) <0x0005c>
14:01:16   at (wrapper alloc) object.AllocVector (intptr,intptr) <0x0014b>
14:01:16   at System.Linq.Set`1<TElement_REF>.Resize () [0x00012] in <6a639364726240738c9c88ff5596de8d>:0
14:01:16   at System.Linq.Set`1<TElement_REF>.Add (TElement_REF) [0x00079] in <6a639364726240738c9c88ff5596de8d>:0
14:01:16   at System.Linq.Enumerable/DistinctIterator`1<TSource_REF>.MoveNext () [0x00083] in <6a639364726240738c9c88ff5596de8d>:0
14:01:16   at Moq.Mock.SetupAllProperties (Moq.Mock,System.Collections.Generic.Stack`1<System.Type>) [0x001dd] in <6787c47d22cc4c12a909a9eeb39c5bc1>:0
14:01:16   at Moq.Mock/<>c__DisplayClass70_0.<SetupAllProperties>b__0 () [0x00006] in <6787c47d22cc4c12a909a9eeb39c5bc1>:0
14:01:16   at Moq.PexProtector.Invoke (System.Action) [0x00000] in <6787c47d22cc4c12a909a9eeb39c5bc1>:0
14:01:16   at Moq.Mock.SetupAllProperties (Moq.Mock) [0x0000d] in <6787c47d22cc4c12a909a9eeb39c5bc1>:0
14:01:16   at Moq.QueryableMockExtensions.FluentMock<T_REF, TResult_REF> (Moq.Mock`1<T_REF>,System.Linq.Expressions.Expression`1<System.Func`2<T_REF, TResult_REF>>) [0x000c2] in <6787c47d22cc4c12a909a9eeb39c5bc1>:0
14:01:16   at (wrapper dynamic-method) object.lambda_method (System.Runtime.CompilerServices.Closure) [0x00000] in <591e184b78744b7b966fda7f1323fb4f>:0
14:01:16   at Moq.Mock.GetInterceptor (System.Linq.Expressions.Expression,Moq.Mock) [0x0002a] in <6787c47d22cc4c12a909a9eeb39c5bc1>:0
14:01:16   at Moq.Mock/<>c__DisplayClass64_0`2<T_REF, TProperty_REF>.<SetupGet>b__0 () [0x00085] in <6787c47d22cc4c12a909a9eeb39c5bc1>:0
14:01:16   at Moq.PexProtector.Invoke<T_REF> (System.Func`1<T_REF>) [0x00000] in <6787c47d22cc4c12a909a9eeb39c5bc1>:0
14:01:16   at Moq.Mock.SetupGet<T_REF, TProperty_REF> (Moq.Mock`1<T_REF>,System.Linq.Expressions.Expression`1<System.Func`2<T_REF, TProperty_REF>>,Moq.Condition) [0x00027] in <6787c47d22cc4c12a909a9eeb39c5bc1>:0
14:01:16   at Moq.Mock/<>c__DisplayClass63_0`2<T_REF, TResult_REF>.<Setup>b__0 () [0x0000d] in <6787c47d22cc4c12a909a9eeb39c5bc1>:0
14:01:16   at Moq.PexProtector.Invoke<T_REF> (System.Func`1<T_REF>) [0x00000] in <6787c47d22cc4c12a909a9eeb39c5bc1>:0
14:01:16   at Moq.Mock.Setup<T_REF, TResult_REF> (Moq.Mock`1<T_REF>,System.Linq.Expressions.Expression`1<System.Func`2<T_REF, TResult_REF>>,Moq.Condition) [0x00027] in <6787c47d22cc4c12a909a9eeb39c5bc1>:0
14:01:16   at Moq.Mock`1<T_REF>.Setup<TResult_REF> (System.Linq.Expressions.Expression`1<System.Func`2<T_REF, TResult_REF>>) [0x00000] in <6787c47d22cc4c12a909a9eeb39c5bc1>:0
... <cut loads of output>
14:01:18 =================================================================
14:01:18 Got a SIGABRT while executing native code. This usually indicates
14:01:18 a fatal error in the mono runtime or one of the native libraries 
14:01:18 used by your application.
14:01:18 =================================================================
```

We call NUnint like this:
`/usr/bin/mono /path/to/nunit3-console.exe /path/to/solution.sln --nocolor --config=Release --where "cat == UnitTest" --agents=1 --workers=1 --result=/path/to/UnitTestsResult.xml;format=nunit2`

We tried different values for --agents and --workers (and leaving them completely out), but with no success.

Btw: we're having this issue since at least 6 months. So not a regression of the latest NUnit or Mono versions.

Any ideas?

**Comment by ChrisMaddock** [comment]
See my response on https://github.com/nunit/nunit/issues/2523.

**Comment by mkvonarx** [comment]
Hi Chris

We have seen much less errors (only one assert 6 days and no reflection error) since enabling `--trace=Debug`. Maybe a timing related issue?

Anyway: the only interesting (to me) data in the trace log files is the end of InternalTrace.log:
```
...
12:49:35.274 Debug [ 1] TestAgency: Returning new agent {95286059-d270-434d-b4e4-e3c00079b16b}
12:52:32.593 Error [ 1] ProcessRunner: Failed to run remote tests Tcp transport error.
12:52:32.615 Info  [ 1] ProcessRunner: Unloading MediaGateway.sln
12:52:32.658 Warning [ 1] ProcessRunner: Failed to unload the remote runner. Connection refused
12:52:32.658 Error [ 1] ProcessRunner: Connection refused
12:52:32.658 Debug [ 1] ProcessRunner: Stopping remote agent
12:52:32.659 Error [ 1] ProcessRunner: Failed to stop the remote agent. Connection refused
```

Does this help?

I could send you all log files if you can provide me a more private "channel" for the zip file than a GitHub issue.

**Comment by ChrisMaddock** [comment]
@mkvonarx You should have another log file for the agent. The end of that may be interesting - I think this is the main engine log, which just records that there was an issue shutting the agent down.

**Comment by mkvonarx** [comment]
@ChrisMaddock I'll attach all log files. I hope you find something.
[traces-75-failed.zip](https://github.com/nunit/nunit/files/1449571/traces-75-failed.zip)

**Comment by mikkelbu** [comment]
From the logs, in particular InternalTrace.6168.MediaGateway.ManagerGui.Backend.Tests.dll.log, it seems that the agent stops at the test `GetConfiguration_WithNotExistingDetailKey_NullReturned(Machines,"machine_which_does_not_exist")`

**Comment by jnm2** [comment]
Usually the approach I take is to try to remove as many parts as possible. Can you make a copy of the project and strip everything out of it except one or a few tests? Can you get Moq to do this in a non-NUnit console app?

**Comment by mkvonarx** [comment]
In the last 76 test runs, we had 7 failures with the assertion (#2522) and 3 with the reflected code (#2523). These 10 failures were caused by 7 different unit tests (from 745 total). So the actual unit test that causes the failures seems rather random.

Thanks @mikkelbu and @jnm2 for your suggestions! It's not so easy to remove tests and try again. We have currently 745 unit tests and the total execution time on the test VM is around 15 minutes. Also, it seems to be a different test that causes the failures each time. So removing one test does not really change much. Next time, a different one fails. And we only have the failures on the VM on CentOS with Mono, not on the developer machines.

At the moment, we tend to kind of ignore these failures. They happen rather regularly, but they don't hurt us too much. And as you mentioned above, it's hard to say if it's caused by NUnit, or by Moq, or by Mono, or by Linux, or by the combination of these.

It would still be good to fix the issue, as there is certainly a bug in one of those libraries/tools.

**Comment by rprouse** [comment]
@mkvonarx we have been seeing similar errors with some versions of Mono although our errors tend to be more regular. We see the exact same error with very different callstacks.

```
14:01:18 =================================================================
14:01:18 Got a SIGABRT while executing native code. This usually indicates
14:01:18 a fatal error in the mono runtime or one of the native libraries 
14:01:18 used by your application.
14:01:18 =================================================================
```

Switching even point releases of Mono often fixes the error. Sometimes it will persist for several versions and then go away. Based on the fact that the only difference is the mono version, I suspect mono is a bit less stable since they've gone to more frequent releases.

Have you tried different versions of Mono, or has this bug disappeared for you with a newer release of Mono?

**Comment by rprouse** [comment]
I am closing since we have not heard back from you. If you have more information, add it to this issue and we will reopen.
