### ISSUE TITLE
SerializationException in low trust floating point equality test

### ISSUE THREAD

**Issue by ggeurts** [nunit/nunit#2526]
The following test throws when run in low trust appdomain:

```
var quantity = Quantity.Create(10.5, "mg/l");
Assert.That(quantity, Is.Not.Null);
Assert.That(quantity.UnitSymbol, Is.EqualTo("mg/l"));
Assert.That(quantity.Magnitude, Is.EqualTo(10.5)); // throws SerializationException

```

System.Runtime.Serialization.SerializationException : Type 'NUnit.Framework.Constraints.Tolerance' in Assembly 'nunit.framework, Version=3.9.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb' is not marked as serializable.

**Comment by CharliePoole** [comment]
Ah, never mind, I see your test.

As you know, Tolerance is never passed across a remoting boundary by NUNit. I see no harm in making it serializable, but if many more things like that should pop up I think we might want to rethink the strategy.

**Comment by ChrisMaddock** [comment]
I'm a bit confused why Tolerance needs to be marked as Serializable, and nothing else. Does someone mind explaining what's going on here?

My thinking is I want to understand this to catch in future code reviews, but I'm not sure a) What's required to be marked as Serializable, and b) What NUnit supports running in low-trust.

**Comment by CharliePoole** [comment]
Actually @ggeurts pretty much added all this functionality, which I didn't know we had! I'm guessing that it's a matter of passing back the Constraint Result and it's contents.

**Comment by ggeurts** [comment]
I added the functionality (and the LowTrustFixture) to get some NUnit 2 tests running again that verify that code was able to run within partial trust environments. This was done by running the code to be tested and the assertions in a separate appdomain with a reduced permission set. In NUnit 3 the some constraint outcomes could  indeed not be serialized across AppDomain boundaries, causing tests to fail.
