### ISSUE TITLE
Matches<T>(Predicate<T>) throws ArgumentException or Fails when actual is null

### ISSUE THREAD

**Issue by kirtsis** [nunit/nunit#2533]
**Class:** `NUnit.Framework.Constraints.ConstraintExpression`
**Method:** `Constraint Matches<TActual>(Predicate<TActual> predicate)`

Hello,
I'm trying to use the Matches constraint that takes a predicate but I'm getting an ArgumentException:

> System.ArgumentException : The actual value is not of type String
> Parameter name: actual

or the test fails:

> Expected: <System.String> and value matching lambda expression
> But was:  null

I would expect the test to succeed/pass without an exception.

The same can be achieved with the Null.Or.Empty constraint, but I need to provide the predicate as parameter to the test method and the parameter cannot depend to the NUnit framework.

I'm assuming that the problem is at the [line 70 of the PredicateConstraint](https://github.com/nunit/nunit/blob/7b87bdc7b48ee1b13023dd282efea449c2d66b81/src/NUnitFramework/framework/Constraints/PredicateConstraint.cs#L70), but I can be wrong.
It checks if the actual passed to the ApplyTo method is of the type defined in the predicate. Since the actual passed is null, the check fails.

Thank you for your time.

## Test code:
```csharp
[TestFixture]
public class MatchesPredicateTests {

    [Test]
    public void HasAll_Matches_predicate_fails_When_actual_is_null_string() {
        var actuals = new[] {"", null};
        Predicate<String> predicate = o => (o == null) || (o == String.Empty);

        Assert.That(actuals, Has.All.Null.Or.Empty); // <-- Success
        Assert.That(actuals, Has.All.Matches(predicate)); // <-- Failure
    }

    [Test]
    public void Matches_predicate_fails_When_actual_is_null_string() {
        var actuals = new[] {"", null};
        Predicate<String> predicate = o => (o == null) || (o == String.Empty);

        foreach (String actual in actuals) {
            Assert.That(actual, Is.Null.Or.Empty); // <-- Success
            Assert.That(actual, Is.TypeOf<String>().And.Matches(predicate)); // <-- Failure
        }
    }

    [Test]
    public void HasAll_Matches_predicate_fails_When_actual_is_null_int() {
        var actuals = new Int32?[] {0, null};
        Predicate<Int32?> predicate = o => (o == null) || (o == 0);

        Assert.That(actuals, Has.All.Null.Or.Zero); // <-- Success
        Assert.That(actuals, Has.All.Matches(predicate)); // <-- Failure
    }

    [Test]
    public void Matches_predicate_fails_When_actual_is_null_int() {
        var actuals = new Int32?[] {0, null};
        Predicate<Int32?> predicate = o => (o == null) || (o == 0);

        foreach (Int32? actual in actuals) {
            Assert.That(actual, Is.Null.Or.Zero); // <-- Success
            Assert.That(actual, Is.TypeOf<Int32?>().And.Matches(predicate)); // <-- Failure
        }
    }

}
```

**Comment by jnm2** [comment]
You're right! Thanks for reporting this! We need to be doing:

`if (!(actual is T || (actual == null && default(T) == null)))`

And actually, I'd like use this method which we've started using instead:

https://github.com/nunit/nunit/blob/07d719b6851b8889934971152fb44e015b045961/src/NUnitFramework/framework/Internal/ConstraintUtils.cs#L42-L48

We would have to add an optional bool parameter to allow null, then add  this below the first line:
```cs
if (allowNull && actual == null && default(T) == null) return null;
```

And then use `ConstraintUtils.RequireActual<T>(actual, nameof(actual), allowNull: true)` here:

https://github.com/nunit/nunit/blob/7b87bdc7b48ee1b13023dd282efea449c2d66b81/src/NUnitFramework/framework/Constraints/PredicateConstraint.cs#L68-L74

And of course we need the predicate tests which you've so helpfully provided above.


@kirtsis Are you interested in doing the PR? If not, I'll also ping @josteink who added ConstraintUtils.
3.9 is going to be released in a few days and this is a tiny enough fix that I might jump in and do it if everyone else is busy.

**Comment by jnm2** [comment]
@rprouse I put it in 3.9 but feel free to pull it back out if you need to :D

**Comment by jnm2** [comment]
Okay, underway.

**Comment by jnm2** [comment]
Ready for review: https://github.com/nunit/nunit/pull/2546
