### ISSUE TITLE
Equality assert for Tuple instances does not work when items are arrays

### ISSUE THREAD

**Issue by svdHero** [nunit/nunit#2539]
I am using NUnit 3.6.0.0 via Resharper Test Runner in Visual Studio.
The following test A fails:
````C#
    [TestFixture]
    class MyTupleTests
    {
        [Test]
        public void TupleTest_A()
        {
            var t1 = new Tuple<float[], int[]>(new[] { 1f, 2f }, new[] { 1, 2 });
            var t2 = new Tuple<float[], int[]>(new[] { 1f, 2f }, new[] { 1, 2 });
            Assert.That(t1.Item1, Is.EqualTo(t2.Item1)); // succeeds
            Assert.That(t1.Item2, Is.EqualTo(t2.Item2)); // succeeds
            Assert.That(t1, Is.EqualTo(t2)); // fails
        }

        [Test]
        public void TupleTest_B()
        {
            var t1 = new Tuple<float, int>(1f, 2);
            var t2 = new Tuple<float, int>(1f, 2);
            Assert.That(t1, Is.EqualTo(t2));  // succeeds
        }
    }
````
Is there a way to make the last Assert statement in Test A succeed, too? Why does it fail? Test B succeeds without any problem.

I am passing Tuple instances to my test framework which internal just calls 'Assert.That(object1, Is.EqualTo(object2))`, so I cannot just check the Tuple's items individually for equality.

**Comment by mikkelbu** [comment]
Proper NUnit equality for tuples will first be available from 3.9 (see e.g. #893). So in NUnit 3.6.0.0 the comparison will just be done using the regular C# equality of tuples, and hence be comparing the two arrays using object references.

**Comment by svdHero** [comment]
Thanks for the quick answer. Sounds good. What is the release plan for NUnit 3.9? Will it become available anytime soon?

**Comment by jnm2** [comment]
Rob is releasing 3.9 this week if all goes well.

**Comment by mikkelbu** [comment]
@svdHero I've just tested your examples against the newest build from master and both tests succeed. I'm closing this issue, as I don't think that there is an easy way to special handle tuples (and also 3.9 will soon be released). Please reopen if you disagree.

**Comment by svdHero** [comment]
Thanks. I am in no rush and waiting another couple of days is totally okay. Thank you both for your help.
