### ISSUE TITLE
NUnit does not support parallelism on .NET Core 2.0

### ISSUE THREAD

**Issue by PYasonau** [nunit/nunit#2542]
It is known, but very critical issue for those, who use nunit as testframework for .net core 2.0 targer. In some cases it is not possible to use target framework different from .net core.  Parallelism is critical feature and test society need to know should they build they test system for .net core based on nunit or migrate to other test frameworks

**Comment by rprouse** [comment]
We hope to add a .NET Standard 2.0 version of the framework soon that will fully support Parallelism and re-enable many of the NUnit features that were disabled because of missing APIs in earlier versions of .NET Standard.

**Comment by SergiusZurawski** [comment]
Hello,  I have noticed that you have scheduled your next release 3.10 on February. Is there any chance that this issue will be solved by 3.10 release?

**Comment by jnm2** [comment]
@rprouse Once issue-2331 is merged I would be happy to get this done. What so you think?

**Comment by rprouse** [comment]
@jnm2 I agree, I would really love to go through what is missing from the .NET Standard 1.6 version, create issues and re-enable whatever we can.

**Comment by jnm2** [comment]
@rprouse Is this something you'd like to do or shall I take it? My plan would probably be to start from net45 rather than netstandard1.6 since I expect netstandard2.0 to have all the APIs we need.

**Comment by rprouse** [comment]
@jnm2 I am fine with you taking it. Are you planning on adding a .NET Standard 2.0 target and basing that on the .NET 4.5 target?

**Comment by jnm2** [comment]
@rprouse That's my plan, after finishing my work underway at https://github.com/nunit/nunit/tree/jnm2/reduce_platform_defines which will resolve my last two items at https://github.com/orgs/nunit/teams/framework-and-engine-team/discussions/3.

**Comment by jnm2** [comment]
Just waiting for https://github.com/nunit/nunit/pull/2586 to be merged, then I will start on this right away.

**Comment by potocnika** [comment]
Eagerly awaiting this. We switched from xunit to nunit some time ago because there were issues with xunit one time setup equivalent (fixtures) and parallelism and we never got parallelism to work on .net core 1.0 or 2.0. Really hoping this feature is available in nunit soon.

**Comment by jnm2** [comment]
While we're waiting for the @nunit/framework-team to find time to review https://github.com/nunit/nunit/pull/2607, it would be cool if you could download the NuGet package at https://ci.appveyor.com/project/CharliePoole/nunit/build/3.10.0-ci-04976-pr-2607/artifacts and see if it does everything you need. (It's not in a feed until it gets merged, so you'll have to put it in a local folder and add the folder path as an additional nuget.config package source.)

**Comment by jnm2** [comment]
.NET Standard 2.0 is now merged! 🎉 

You can try it now by merging this with your nuget.config and picking version 3.10.0-dev-05001 or later:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="NUnit MyGet" value="https://www.myget.org/F/nunit/api/v3/index.json" />
  </packageSources>
</configuration>
```

Early feedback is great! Otherwise you'll likely be waiting until 3.11 if we've missed anything critical to your scenario. 😃

**Comment by mitchellmaler** [comment]
I installed the dev version above and now when I run ```dotnet test``` I am getting this error.

```
Test run for [omitted].dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
NUnit Adapter 3.9.0.0: Test execution started
Running all tests in [omitted].dll
NUnit3TestExecutor converted 133 of 133 NUnit test cases

Exception System.PlatformNotSupportedException, Exception thrown executing tests in [omitted].dll
COM interop is not supported on this platform.
   at NUnit.Framework.Internal.Execution.TestWorker.Start()
   at NUnit.Framework.Internal.Execution.WorkShift.StartWorkers()
   at NUnit.Framework.Internal.Execution.WorkShift.Start()
   at NUnit.Framework.Api.NUnitTestAssemblyRunner.Run(ITestListener listener, ITestFilter filter)
   at NUnit.Framework.Api.FrameworkController.RunTests(Action`1 callback, String filter)

NUnit Adapter 3.9.0.0: Test execution complete
No test is available in [omitted].dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
```

**Comment by mitchellmaler** [comment]
Yea it seems to only work on Windows (I tested on win 10). I tried my MacOS and Arch Linux system and got the "COM interop is not supported on this platform." error when I ran ```dotnet test```.

**Comment by jnm2** [comment]
@mitchellmaler Sweet, thanks for finding that. We're getting successful NUnitLite runs on Ubuntu Trusty and OS X 10.12 but maybe we should stop using NUnitLite and run the test adapter instead. /cc @rprouse

**Comment by jnm2** [comment]
Based on your stack trace I'm thinking it's this line, since apartment state only makes sense in the context of COM:

https://github.com/nunit/nunit/blob/3c028034e717c79bf00661c5852b358f9097d2e1/src/NUnitFramework/framework/Internal/Execution/TestWorker.cs#L159

We will need to set up an integration test so we know when we've fixed this (and to confirm my guess.)

Prematurely, the fix I would suggest would be a new preprocessor constant `APARTMENT_STATE` to elide all apartment-related code until the team has time to discuss if and how we'd like to handle offering platform-dependent attributes like `ApartmentAttribute` in our platform-agnostic DLLs like .NET Standard.

**Comment by jnm2** [comment]
Oh dear, both netstandard tests are skipped on Travis. I needed an explanation for the above- there it is. 😳 This is important.

**Comment by jnm2** [comment]
Here's our repro: https://travis-ci.org/nunit/nunit/jobs/314194712#L3376

**Comment by jnm2** [comment]
Getting there! :D https://travis-ci.org/nunit/nunit/jobs/314204278#L3446

To be continued...

**Comment by jnm2** [comment]
The COM issue is taken care of in https://github.com/nunit/nunit/tree/jnm2/enable_tests_netstandard2.0.

Now that I've uncovered tests that weren't running on all platforms, we are blocked on these issues before we can ship a .NET Standard 2.0 build: https://github.com/nunit/nunit/issues/2555, https://github.com/nunit/nunit/issues/2608

**Comment by mitchellmaler** [comment]
Awesome! Thanks @jnm2 for all the work on this.

**Comment by mitchellmaler** [comment]
I just tested this on my mac and it ran this time and with parallelization!

**Comment by jnm2** [comment]
Sweet! Let us know if you find any issues!

**Comment by potocnika** [comment]
Just tested it with a sandbox project and it works nicely (Win 10 / .NET Core 2.0). It even works as expected with
`Parallelizable(ParallelScope.All)`

Another test was with [OneTimeSetUp] and [OneTimeTearDown] because someone flagged those as problems in earlier versions and it looks good.

Nice work guys!

Thanks @mitchellmaler for tests on a mac as we're expecting to run tests on Ubuntu TeamCity agents.
