### ISSUE TITLE
CI failure: NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_SendsExpectedEvents

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2544]
Only in `Test35`:

> 1) Failed : NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_SendsExpectedEvents
>   Expected: 24
>   But was:  15
>    at NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_SendsExpectedEvents()

https://ci.appveyor.com/project/CharliePoole/nunit/build/3.9.0-ci-04693-SetArgNames#L1247

/cc @CharliePoole

**Comment by rprouse** [comment]
I find it odd that we are having consistent .NET 3.5 problems on AppVeyor only. See also #2579

**Comment by mikkelbu** [comment]
Closing this as I haven't seen this error in a long time (and also we don't run .NET 3.5 anymore).
