### ISSUE TITLE
Internal.Execution.WorkItemQueueTests.StopQueue_WithWorkers fails about 10% of the time

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#2550]
Not sure what is going on here, but this test seems to fail about 10% of the time.

If I run just this test over and over, it exhibits this failure rate.

From looking at the code, I cannot see why it would fail sometimes.

@CharliePoole wrote this code, I think?  Perhaps you might have some insight?

Perhaps some can run this test repeatedly in another environment and see if this failure is unique to my two environments.

**Comment by oznetmaster** [comment]
It fails the assertion that a TestWorker has stopped.  Usually TestWorker 1.

**Comment by CharliePoole** [comment]
I think I have seen that fail intermittently in our CI. My guess is that we need to wait longer for the stop to occur. Another possibility is that it gets stopped but immedieately restarted by some other thread.... Just ideas, I haven't examined the code lately.

**Comment by rprouse** [comment]
I have seen this fail occasionally too. I thought we had an issue for it, but probably missed it.

**Comment by stevenaw** [comment]
Closing, I don't recall seeing this failing for a while.
