### ISSUE TITLE
Test won't start IIS Express

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#2557]
@martinRocks commented on [Fri Nov 10 2017](https://github.com/nunit/nunit3-vs-adapter/issues/415)

I'm using Visual Studio 2017 Professional 15.4.3 with resharper installed.  When I run the Selenium UI tests using the resharper's runner, IIS Express starts.  However, when I run the test with the VS Test Explorer, IIS Express doesn't start.  I have NUnit3TestAdapter 3.9 installed to make the NUnit show up in the test explorer.

I'm starting IIS as a new process in the base class.

I have created a small demo project of exactly what I'm doing.
NUnit: 3.8.1
NUnit3TestAdapter:3.9.0
.net platform 4.7
[NunitDemo.zip](https://github.com/nunit/nunit3-vs-adapter/files/1459529/NunitDemo.zip)

---

@CharliePoole commented on [Sat Nov 11 2017](https://github.com/nunit/nunit3-vs-adapter/issues/415#issuecomment-343689862)

Issue title confused me, making me think you were using the NUnit Explore API to examine tests, hence the title edit.

Two suggestions:
1. Debug your OneTimeSetUp method to make sure everything works as expected.
2. See if a brief wait for the process to actually start solves the problem.

---

@martinRocks commented on [Sat Nov 11 2017](https://github.com/nunit/nunit3-vs-adapter/issues/415#issuecomment-343692451)

Sorry about the confusion. 

I have used the StartIisExpress method in a number of different projects without any problems.  And when I run the test with resharper, IIS starts.  However, when I run it with Visual Studio's test explorer, the process doesn't start.  

I tried adding a Thread.Sleep(5000); before and after the _iisProcessExpress.Start(); without any luck.

Thank you for the suggestions.

---

@CharliePoole commented on [Sat Nov 11 2017](https://github.com/nunit/nunit3-vs-adapter/issues/415#issuecomment-343693663)

I'd be curious to know if it works when running under nunit3-console.exe. That would help narrow down the problem quite a bit: if it does work, it's an adapter problem, if not possibly an nunit problem. FYI, the fact that it runs with R# would give us more info, if we actually understood how R# runs NUnit. 😄 

---

@martinRocks commented on [Sat Nov 11 2017](https://github.com/nunit/nunit3-vs-adapter/issues/415#issuecomment-343696012)

I completely understand about R#.  It does a ton of things I wish I understand better :)

I just tried the console runner (NUnit.ConsoleRunner.3.7.0) and it acted just like VS's test explorer.  I.E. the IIS Express process didn't start.  

Also, I just upgraded NUnit to version 3.9.0

Does that mean that this is a problem with NUnit?

---

@CharliePoole commented on [Sat Nov 11 2017](https://github.com/nunit/nunit3-vs-adapter/issues/415#issuecomment-343697603)

Most likely it is. I'm moving this to the NUnit repo.

**Comment by jnm2** [comment]
Thanks for the repro project! That usually ensures a speedy diagnosis!

Found the problem. When it's working, this is the command line:
```
"C:\Program Files\IIS Express\iisexpress.exe" /path:"C:\Users\Joseph\Desktop\New folder\NunitDemo.Web" /port:62889
```

When it's not working:
```
"C:\Program Files\IIS Express\iisexpress.exe" /path:"C:\Users\Joseph\Desktop\New folder\NunitDemo.Test\NunitDemo.Web" /port:62889
```

Here's the source of the problem:

```cs
var solutionFolder = Path.GetDirectoryName(Path.GetDirectoryName(Path.GetDirectoryName(AppDomain.CurrentDomain.BaseDirectory)));
```

**Comment by jnm2** [comment]
I'm sorta curious why the AppDomain.CurrentDomain.BaseDirectory is getting set to an in

Using VSTest:
```
C:\Users\Joseph\Desktop\New folder\NunitDemo.Test\bin\Debug\
```

Using ReSharper:
```
C:\Users\Joseph\Desktop\New folder\NunitDemo.Test\bin\Debug
```

Guess you'll have to strip the slash first! 😂

**Comment by jnm2** [comment]
I'd do this; it works both ways:

```cs
var solutionFolder = Path.GetFullPath(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"..\..\.."));
```

**Comment by jnm2** [comment]
Excuse me a minute while I terminate two dozen chromedriver.exe processes. 😄

**Comment by martinRocks** [comment]
Thank you so very very much!!!  I can't believe it was something that small and simple.

**Comment by jnm2** [comment]
No problem. Sometimes simple problems can mislead the worst! Feel free to open a new issue if you run into anything else.
