### ISSUE TITLE
failing test due to whitespace

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#2559]
@LesediM commented on [Mon Nov 13 2017](https://github.com/nunit/docs/issues/239)

**Test Cases**

`[TestCase(0, "R 0.00")]`
          `[TestCase(1000, "R 1\u0020000.00")]`
           ` [TestCase(10000, "R 10 000.00")]`
`            public void GivenValueHasValue_ShouldReturnValueAsSouthAfricanCurrency(decimal amount, string expectedValue)`
`            {`
`                var result = PayfastTransactionCommon.FormatAsCurrency(amount);`
`                Assert.That(result, Is.EqualTo(expectedValue));`
`            }`

**Code being tested**
` public static string FormatAsCurrency(decimal? amount)`
        `{`
            `return amount.HasValue`
              `  ? $"R {amount:N}"`
              `  : string.Empty;`
      `  }`

First test case passes but the latter test cases fail. 
Am I missing something or doing something wrong?
Nunit version is 3.8.1.0

---

@CharliePoole commented on [Mon Nov 13 2017](https://github.com/nunit/docs/issues/239#issuecomment-343937928)

You filed this as an issue against our documentation. I'm moving it to the proper repository.

**Comment by LesediM** [comment]
@CharliePoole sorry about that

**Comment by CharliePoole** [comment]
I don't see anything in your method under test to force use of South African numeric display. AFAIK, interpolated values in strings work the same as if you provided `amount.ToString()`.

**Comment by LesediM** [comment]
thank you that worked

**Comment by jnm2** [comment]
Charlie is right. In this case, it's the same as `amount.ToString("N")`.
