### ISSUE TITLE
There is no `Does.All` for to migrate `Text.All`

### ISSUE THREAD

**Issue by wachulski** [nunit/nunit#2560]
I'm migrating framework v2 to v3. I read https://github.com/nunit/docs/wiki/Breaking-Changes to see:

> Assertions and Constraints
> Text.All | No longer supported. Use Does.All

In NUnit 3.9.0 there is no `Does.All` which I can use to migrate `Text.All` as I expected.

**Comment by wachulski** [comment]
BTW - I'm working on that migration tool we discussed a few months ago.
https://github.com/wachulski/nunit-migrator

**Comment by CharliePoole** [comment]
Corrected the docs. Use `Has.All` or `Is.All`
