### ISSUE TITLE
Help - Subscribe to event after TestResult.xml file is created

### ISSUE THREAD

**Issue by EtgarZ** [nunit/nunit#2570]
I am extending the nunit framework and need to subscribe to an event that is triggered after TestResult.xml file has already been written.
Is there such thing? How can I do it?

Thanks.

**Comment by ChrisMaddock** [comment]
Can you provide more details as to how you're extending the framework/what you're aiming to achieve?

'TestResult.xml' is a file written by the nunit.engine. It's content (most of it, anyway) are returned by the framework's ExecuteTests() call.

You might find nunit.xamarin an interesting example - see how this integrates [here](https://github.com/nunit/nunit.xamarin/blob/master/src/runner/nunit.runner/ViewModel/SummaryViewModel.cs#L136). I wouldn't recommend integrating directly with the framework unless you have a particular need to however - if you're just looking to build a test runner of sorts, integrating with the nunit engine via the nunit.engine.api assembly is the way to go.

**Comment by EtgarZ** [comment]
When saying "extension" I mean that I want to add a method that will be called after TestResult.xml is being written with all tests result in a TestFixture, so I wonder if there is an attribute like "TearDown" so I can put on a method and it will do the trick. 
I want to add manipulation on the TestResult.xml file.
Any idea?

**Comment by ChrisMaddock** [comment]
Ah ok. Sounds like ITestEventListener may be what you’re looking for? Although that possibly depends on the type of manipulation you’re planning!

https://github.com/nunit/docs/wiki/Event-Listeners

**Comment by ChrisMaddock** [comment]
Worth noting that this would be an engine extension, rather than extension to the framework.

**Comment by EtgarZ** [comment]
Thanks for replies!
I want to run the ReportUnit process with the TetsResult.xml to automatically generate the html type report within the end of the testFixture.

**Comment by ChrisMaddock** [comment]
Do you want to run ReportUnit at the end of every TestFixture, or once at the end of the entire run?

Does ReportUnit handle partial NUnit Test results?

**Comment by EtgarZ** [comment]
ReportUnit doesn't handle partial test results (it says format incorrect).
I have created a Base TestFixture and I want that every class that inherits it will run the ReportUnit process at the end of it (after TestResult.xml file is fully generated, so RepurtUnit will work).

**Comment by CharliePoole** [comment]
If all you want to do is automatically produce an output report of the entire run in some format, then create an output writer engine extension.   You will define some string representing your format, like "xxx". Then run with option --result:myresults.html;format=xxx.

You can either write code to create the report or run some existing program.

**Comment by EtgarZ** [comment]
Thanks a lot, but I don't want to create from scratch a custom format, the existing format is good for me. 
I only need to add execution of ReportUnit tool, after the TestResult.xml file has been written and contains all tests results.

**Comment by CharliePoole** [comment]
As @ChrisMaddock pointed out there is no way to do this in the framework, such as in your test TearDown, because the framework never writes any XML file. It simply returns XML to the engine.

The engine writes XML to a file in some format but only if a runner requests it. 

In a given console run, the XML may not be written, or may be written once or even several times. The format in which it is written can vary. So an event after the output is generated would not be helpful unless you knew the format in which it is written.

I don't know how ReportUnit works. Can it only read a file or can you pass it some XML directly? What format does it want the XML to be?

It sounds like an interesting challenge to connect the two directly.

**Comment by EtgarZ** [comment]
Thank you.
I don't know exactly how it is implemented, but I do know that it works when I pass it a TestResult.xml in format of nunit2. 
Anyhow, I have found a solution that works for me.
As suggested, I wrote a result writer extension that makes use of the nunit-v2-result-writer.dll and implemented those 3 methods of IResultWriter interface by calling the NUnit2XmlResultWriter object methods and added my desired functionality of running ReportUnit.
Thanks a lot.

**Comment by CharliePoole** [comment]
OK, I looked at their code. They Nerf a file to read, so you have to let nunit create one first. Be aware that only the console runner creates the default XML file and that it will not create it if you specify a  different name or format.

Basically, what you are asking would be an engine feature, adding a post-processing step. Currently, the simplest thing to do is to add a report step to your script.
