### ISSUE TITLE
No tests discovered in .NET Core project with NUnit >=3.8.1

### ISSUE THREAD

**Issue by Maritims** [nunit/nunit#2572]
Attempted to write a test today using NUnit 3.8.1 for a .NET Core project. No tests discovered when I built the solution and attempted to run all tests from the unit test explorer in VS2017. I updated to the latest versions of both NUnit and the NUnit3TestAdapter but did not experience any improvement. Still no tests discovered.

I made a minimal repo which reproduces the issue. It contains one fresh .NET Standard library project which references the latest versions of NUnit and the adapter, the single test in there is not discovered.

Link to repo: [https://github.com/Maritims/UnableToDiscoverTests](url)

Output from the Tests pane in VS2017 (diagnostic mode):

> [23.11.2017 14:46:00 Diagnostic] About to Enqueue operation 'RunAllOperation', hashcode:37660021 
> [23.11.2017 14:46:00 Diagnostic] Enqueue operation 'RunAllOperation', hashcode:37660021 
> [23.11.2017 14:46:00 Diagnostic] Operation left in the the queue: 1
> [23.11.2017 14:46:00 Diagnostic] 	'RunAllOperation', hashcode:37660021
> [23.11.2017 14:46:00 Diagnostic] 
> 
> [23.11.2017 14:46:00 Diagnostic] Processing Queue .....
> [23.11.2017 14:46:00 Diagnostic] Operation Dequeue : 'RunAllOperation'
> [23.11.2017 14:46:00 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=OperationSetStarted, operationInProgress=False
> [23.11.2017 14:46:00 Diagnostic] TestDiscoveryStats.OperationStateChanged State=OperationSetStarted, InProgress=False
> [23.11.2017 14:46:00 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=ChangeDetectionStarting, operationInProgress=True
> [23.11.2017 14:46:00 Diagnostic] TestDiscoveryStats.OperationStateChanged State=ChangeDetectionStarting, InProgress=False
> [23.11.2017 14:46:00 Diagnostic] We programmatically start the build in TestWindowHost.UpdateContainer... 
> [23.11.2017 14:46:01 Diagnostic] After we await the build that programmatically started in TestWindowHost.UpdateContainer... 
> [23.11.2017 14:46:01 Diagnostic] TestContainer update (build) complete : 380 ms
> [23.11.2017 14:46:01 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=OperationSetFinished, operationInProgress=False
> [23.11.2017 14:46:01 Diagnostic] TestDiscoveryStats.OperationStateChanged State=OperationSetFinished, InProgress=False
> [23.11.2017 14:46:01 Diagnostic] test container discoverer executor://vsprojectoutputcontainerdiscoverer/v1, discovered 1 containers
> [23.11.2017 14:46:01 Diagnostic] Containers from 'Microsoft.VisualStudio.TestWindow.VsAdapters.VsProjectOutputContainerDiscoverer' :
> [23.11.2017 14:46:01 Diagnostic] 	c:\users\martin\source\repos\UnableToDiscoverTests\UnableToDiscoverTests\bin\Debug\netstandard1.4\UnableToDiscoverTests.dll:executor://vsprojectoutputcontainerdiscoverer/v1
> [23.11.2017 14:46:01 Diagnostic] test container discoverer executor://testexplorerservicecontainerdiscoverer/v1, discovered 0 containers
> [23.11.2017 14:46:01 Diagnostic] No containers found from 'Microsoft.VisualStudio.TestWindow.Extensibility.TestExplorerServiceContainerDiscoverer' :
> [23.11.2017 14:46:01 Diagnostic] test container discoverer executor://cpsprojectoutputtestcontainerdiscoverer/v2, discovered 0 containers
> [23.11.2017 14:46:01 Diagnostic] No containers found from 'Microsoft.VisualStudio.TestWindow.Extensions.CPSTestContainerDiscoverer' :
> [23.11.2017 14:46:01 Diagnostic] test container discoverer executor://powershelltestexecutor/v1, discovered 0 containers
> [23.11.2017 14:46:01 Diagnostic] No containers found from 'PowerShellTools.TestAdapter.PowerShellTestContainerDiscoverer' :
> [23.11.2017 14:46:01 Diagnostic] test container discoverer executor://nodejstestexecutor/v1, discovered 0 containers
> [23.11.2017 14:46:01 Diagnostic] No containers found from 'Microsoft.NodejsTools.TestAdapter.TestContainerDiscoverer' :
> [23.11.2017 14:46:01 Diagnostic] test container discoverer executor://orderedtestadapter/v1, discovered 0 containers
> [23.11.2017 14:46:01 Diagnostic] No containers found from 'Microsoft.VisualStudio.MSTest.TestWindow.OrderedTestContainerDiscoverer' :
> [23.11.2017 14:46:01 Diagnostic] test container discoverer executor://generictestadapter/v1, discovered 0 containers
> [23.11.2017 14:46:01 Diagnostic] No containers found from 'Microsoft.VisualStudio.MSTest.TestWindow.GenericTestContainerDiscoverer' :
> [23.11.2017 14:46:01 Diagnostic] test container discoverer executor://webtestadapter/v1, discovered 0 containers
> [23.11.2017 14:46:01 Diagnostic] No containers found from 'Microsoft.VisualStudio.MSTest.TestWindow.WebTestContainerDiscoverer' :
> [23.11.2017 14:46:01 Diagnostic] DiscoveryOperation<RunAllOperation> FinishedChangedCotainers, changed container count is 0
> [23.11.2017 14:46:01 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=ChangeDetectionFinished, operationInProgress=False
> [23.11.2017 14:46:01 Diagnostic] TestDiscoveryStats.OperationStateChanged State=ChangeDetectionFinished, InProgress=False

**Comment by jnm2** [comment]
I see you've closed this issue. Were you able to resolve the problem?

Here's the documentation: https://github.com/nunit/docs/wiki/.NET-Core-and-.NET-Standard
