### ISSUE TITLE
Parameterized TestFixtureSource

### ISSUE THREAD

**Issue by okobets** [nunit/nunit#2590]
Hi,

I'm using NUnit 3.7 Console Runner to run Selenium UI tests from TeamCity.
What I want to do is support cross browser testing by passing a parameter from console command line (--params) to a SetUpFixture, set FixtureArgs static and data drive the tests based on that.

So, my code is roughly:

```
[SetUpFixture]
public class AssemblyInitializer
{
    [OneTimeSetUp]
    public void Setup()
    {
        var prms = TestContext.Parameters.Get("Browsers", string.Empty);
        FixtureInputParams.FixtureArgs = prms;
    }
}

in a different namespace...
[TestFixture]
public abstract class TestBase : IDisposable
{
    public void TestBase(string parameter)
    {
        // do something
    }
}

and tests themselves are in a different namespace
[Parallelizable]
[TestFixtureSource(typeof(FixtureInputParams), nameof(FixtureInputParams.FixtureArgs))]
public class MyTest : TestBase
{
    public MyTest(string param) : base(param)
    {
    }

    [Test]
    public void MyTestMethod()
    {
    }
}

```
The error I get is "No suitable constructor was found".

I know for a fact that OneTimeSetup is indeed being run and data is parsed and passed from command line parameter to FixtureArgs. What happens after that is something I was unable to debug, since it is within NUnit itself.

Is that scenario supported at all?
Any ideas?

Thanks.

**Comment by ChrisMaddock** [comment]
Afraid not, see https://github.com/nunit/nunit/issues/141.

Is there a reason you haven't put `TestContext.Parameters.Get("Browsers", string.Empty)` directly in the TestFixtureSource method? I'm not totally sure that will work, I don't know off the top of my head if Test Params are avaialable at that point in time or not.

**Comment by okobets** [comment]
Thanks, Chris.
That actually did the trick. 

I've created a static constructor inside my FixtureInputParams static class and TestContext was indeed available. Everything worked as expected after that.

**Comment by ChrisMaddock** [comment]
Great, glad you’re up and running!
