### ISSUE TITLE
NUnitEqualityComparer.Default should be replaced with new NUnitEqualityComparer()

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2591]
In https://github.com/nunit/nunit/pull/2290, we made the constructor internal ~~and introduced a Default static property which returns a new instance every time~~. I failed to notice this when reviewing that PR. 

Edit: Thanks for the correction @mikkelbu. The Default property has been in NUnitEqualityComparer since v2.5.1!

I believe that static properties should return the same instance every time or at least *semantically be able* to return the same instance every time. If the returned instance is immutable, it should be a static property. If it's mutable, it must create a new instance every time and therefore should be a method. Rather than having a static method delegate to the default constructor, I'd prefer re-exposing the default constructor.

I would like to propose the following:

```diff
namespace NUnit.Framework.Constraints
{
    public class NUnitEqualityComparer
    {
+       public NUnitEqualityComparer();

+       [Obsolete("Deprecated. Use the default constructor instead.", error: true)]
        public static NUnitEqualityComparer Default { get; }
    }
}
```

Should we make the obsoletion a warning or error? I prefer error because it helpfully points people to the necessary refactor while flushing out all uses but I could go either way.

**Comment by mikkelbu** [comment]
I have no problem in removing/deprecating the static property, but I did not introduce it 😄 . It was in the framework from the beginning on github, so there are probably a lot of people using it. See e.g. https://github.com/nunit/nunit/blob/de5b6e79ced6e831c14b55a43e841a69b3238931/src/NUnitFramework/framework/Constraints/NUnitEqualityComparer.cs#L72

**Comment by jnm2** [comment]
@mikkelbu Ahh, thanks for setting me straight! I thought the changes happened at the same time but I only looked up the one. Let me update.

**Comment by jnm2** [comment]
That property has been there since NUnit 2! :D Definitely shouldn't delete it.

**Comment by CharliePoole** [comment]
@jnm2 I agree with this and I would also agree with making the entire class internal. However, it __is__ a breaking change either way for any user who made use of the class.

This is in the category that I call "not part of our API" but which I believe you are calling part of the API because it's accessible. Maybe we should call it "accidentally exposed" instead. 😺

**Comment by CharliePoole** [comment]
However, since either change makes the property inaccessible to the user, we may as well delete the property and change our internal usage.

**Comment by jnm2** [comment]
It's not in an Internal namespace and it is currently an integral part of a real-world custom constraint. I'm not sure how I'd be able to implement the custom constraint without it. Unless I'm overlooking an API, NUnitEqualityComparer needs to be that public API we provide.

My proposal does not make the property inaccessible to the user. The problem with making it inaccessible or non-existent is that users either see a message saying they can't access it or a message saying it doesn't exist. What I'd prefer is for them to see the obsoletion message telling the how to fix. The lack of obsoletion message is exactly what sent me in circles when we made the constructor internal in #2290.

**Comment by jnm2** [comment]
We could also make the obsoletion a warning rather than an error if we don't want to force change on people.

**Comment by CharliePoole** [comment]
@jnm2 I didn't realize you are both the user reporting the problem and implementer here. I was hoping this might not have been used.

To clarify, can you indicate why you need to use the class? Frankly, we have too little info on how extenders are using our "internal" classes.

BTW I'm using "internal" in quotes to mean "stuff we didn't intend for users to access." I recognize that we may not be able to put the toothpaste back on the tube but I think it's still an important distinction.

**Comment by jnm2** [comment]
The custom constraint implements `HasEqualPropertyValues(expectedObj, "Property1", "Property2", ...)`. For each pair of properties I want to use NUnit's default equality comparison. I suppose could use `new EqualConstraint(expectedPropertyValue).ApplyTo(actualPropertyValue).IsSuccess` as an equality comparer though. It seems like moving parts that aren't 1:1 with the equality comparison semantics I need, but it would do the job.

Either way it's been around since 2.5.1, which is what made me think there's a good chance people use it.

It's getting confusing. We have things in the `internal` namespace that we do consider and want to consider part of our public API, and I just learned now that we have things outside that namespace that we want to consider to not be public API. Now I have much less confidence in using that term because it's a matter of interpretation.

**Comment by CharliePoole** [comment]
Well, I have to say __of course__ it's a matter of interpretation. 😸 Most things are! Historically, the team interpretation was known to the team as a whole. Of course, I'm the only one of that historical team left, which is why I'm trying to get it spelled out more clearly.

The particular class we're talking about got put into the constraint namespace because only constraints use it. Two of our own constraints use the Default property, while the rest use the default constructor. IIRC Default originally returned an immutable instant, until we made changes such that the comparer was no longer immutable. At that point we were forced to make it work just like `new`.

I think we need to spell out all these subtleties in order to deal with them. Historical fact 1: this class was not meant to be used by users or extenders. Fact 2: It is being used. One interpretation: it probably needs to be exposed __in some way__ because users want to be able to write code that says... do this comparison in the standard NUnit way.

I'd like to start a general discussion of this but I need to catch up my mail first!

**Comment by jnm2** [comment]
I want to get this in the next release. If don't have any other plan ready by then, I think we should restore the constructor.

For discussion:

Do we have any appetite for moving this class out of its current `NUnit.Framework.Constraints` namespace or changing its name, with or without leaving behind an obsoleted class pointing the way to the new location/name, before 3.10? I'm doubtful.

Do we have any appetite for changing the shape of the class's members before 3.10?

```cs
public class NUnitEqualityComparer
{
    public static NUnitEqualityComparer Default { get; }

    public bool CompareAsCollection { get; set; }

    public System.Collections.Generic.IList<EqualityAdapter> ExternalComparers { get; }

    public System.Collections.Generic.IList<NUnitEqualityComparer.FailurePoint> FailurePoints { get; }

    public bool IgnoreCase { get; set; }

    public bool WithSameOffset { get; set; }

    public bool AreEqual(object x, object y, ref Tolerance tolerance, bool topLevelComparison = true);

    public class FailurePoint
    {
        public bool ActualHasData;

        public object ActualValue;

        public bool ExpectedHasData;

        public object ExpectedValue;

        public long Position;

        public FailurePoint();
    }
}
```

Off the top of my head I'd like to obsolete `Default`, seal the classes, and try to make FailurePoint immutable and use properties and make the constructor internal. Perhaps try to make make `AreEqual` more intuitive? It's a moonshot, but I think comparers should be immutable and would try to make that happen too. Maybe `AreEqual` could return a complex type which encapsulates both the success/failure and the list of failure points.

Where do we want to draw the line, given the long history of the public `NUnit.Framework.Constraints.NUnitEqualityComparer`?

**Comment by CharliePoole** [comment]
Seems like a lot to bite off and it isn't even assigned to anyone.

**Comment by ChrisMaddock** [comment]
I agree with making `Default` a warning.

What's the motivation for moving the class? And why make the constructor internal - aren't we saying that we _want_ this to be available, or not?

**Comment by jnm2** [comment]
@CharliePoole 

> Seems like a lot to bite off and it isn't even assigned to anyone.

I agree, but I stated my thoughts because you asked for a design discussion before we went ahead and made the `NUnitEqualityComparer` constructor public and deprecated the `Default` property. Like I said, I don't actually expect we'll want to do much before 3.10 and in that case I'd rather do what I asked at the to.

@ChrisMaddock I have no motivation to move the class, but I was asking in case someone else has. My point being, if none of us is hoping to do anything drastic like renaming it over overhauling it, why not do what I suggested in the scope of my original proposal? =D

> And why make the constructor internal

Sorry– I should have said "the `FailurePoint` constructor." On the principle of leaving as many doors open for ourselves as possible and not committing to a public API until asked.

**Comment by CharliePoole** [comment]
Sorry, my comments are generally to the last thing you wrote and I don't always know if the original proposal is relevant because of the way these discussions develop.

I'm afraid this sounded to me as well as if you were proposing moving the class.

To the point, I think a major revision is needed here and someone should eventually take it on, creating a plan and a series of PRs to implement, each one standing on its own. At least that's how I'd be most comfortable with the scope of change needed.

**Comment by jnm2** [comment]
If no one is motivated to do the major revision before we release 3.10, can we proceed with the incremental improvement I proposed at the top?

**Comment by CharliePoole** [comment]
The original description was just obsoleting one property and re-exposing the constructor. Is that the incremental improvement you mean?

If so, my comment is as before: I prefer to just remove the property. I didn't feel adamant about it and don't feel that way now either.

I think this discussion has become much broader than it needs to be to deal with that original proposal, which is what was confusing me I suppose.

**Comment by jnm2** [comment]
@CharliePoole I did not want to go broader. That was my mistake. I misunderstood what you were [saying](https://github.com/nunit/nunit/issues/2591#issuecomment-349361495) in, "this class was not meant to be used by users or extenders. [...] it probably needs to be exposed **in some way**" and asking for a more general discussion of this.

So getting back on topic for the original proposal:

@CharliePoole prefers to delete `NUnitEqualityComparer.Default`. @mikkelbu is okay with either deleting or obsoleting. I want to be careful and leave an `[Obsolete("Upgrade instructions", error: true")]` behind, though I could be convinced that putting the upgrade instructions in the release notes is good enough.

@rprouse and @ChrisMaddock, which way do you lean?

**Comment by CharliePoole** [comment]
TO me , obsoleting implies coming back and deleting eventually. Is that your thought too @jnm2 ?

**Comment by ChrisMaddock** [comment]
I also prefer obsoletion. This has been public for a long time.

**Comment by jnm2** [comment]
@ChrisMaddock No problem. I see how I was less than clear! 😁

So we are all agreeable to the initial proposal, including the `error` parameter? Should we make the obsoletion a warning or error? I prefer error because it helpfully points people to the necessary refactor while flushing out all uses but I could go either way.

```diff
namespace NUnit.Framework.Constraints
{
    public class NUnitEqualityComparer
    {
+       public NUnitEqualityComparer();

+       [Obsolete("Deprecated. Use the default constructor instead.", error: true)]
        public static NUnitEqualityComparer Default { get; }
    }
}
```

**Comment by ChrisMaddock** [comment]
Warning imo. I don't think anything should prevent users code compiling full-stop, especially a case where we're **intending** to remove something cleanly. 🙂

**Comment by jnm2** [comment]
Good by me. So, are we all agreed on the warning-only version?

```diff
namespace NUnit.Framework.Constraints
{
    public class NUnitEqualityComparer
    {
+       public NUnitEqualityComparer();

+       [Obsolete("Deprecated. Use the default constructor instead.")]
        public static NUnitEqualityComparer Default { get; }
    }
}
```

**Comment by rprouse** [comment]
@jnm2 I have removed from the 3.10 milestone. Please make a case if it should remain.

**Comment by jnm2** [comment]
I can get a PR ready in fifteen minutes if that sounds like a good enough case to you. 😄

**Comment by jnm2** [comment]
@rprouse If you have time, https://github.com/nunit/nunit/pull/2744. If not, no worries.

**Comment by rprouse** [comment]
I am okay re-exposing it, but nobody from the community has commented on this issue or complained, so is it necessary, or is it just something you noticed in your API scanning? I am wondering if we should do anything.

**Comment by jnm2** [comment]
Compatibility aside, I want to change the API because static properties shouldn't return a new mutable instance every time they are called.
