### ISSUE TITLE
Test State

### ISSUE THREAD

**Issue by bondsbw** [nunit/nunit#260]
Feature request:  a dictionary of user state that is cleared after each test is finished.

A similar feature exists in SpecFlow, called ScenarioContext:  https://github.com/techtalk/SpecFlow/wiki/ScenarioContext.Current

This is useful for setting up mock data that should be reset per test, which is used by several different test fixtures in the same way.  Currently the only way I can accomplish this is to set up a static class containing the mock data, and telling it to reset in each fixture by creating a [SetUp] method.  Unfortunately this is easy to miss, and if we do, the test may be invalidated by using data defined in other test runs.

**Comment by rprouse** [comment]
Nobody is picking this issue up or voting for it. I propose we close.

**Comment by CharliePoole** [comment]
I agree
