### ISSUE TITLE
Constraint sequence Has.One.Member is accepted but not working as expected

### ISSUE THREAD

**Issue by Snaaio** [nunit/nunit#2604]
This issue started as a question on the following issue: https://github.com/nunit/nunit/issues/2411#issuecomment-348931250
@ChrisMaddock, @CharliePoole, @mikkelbu: Thanks for the help so far on the above issue!

I am currently using nunit.framework v3.9.0.0 and have problems when using a Has.One.Member(...) constraint:
`class TestElement { }`
```
var element = new TestElement();
Assert.That(new System.Collections.Generic.List<TestElement> { element }, Has.One.Member(element));
```
Test fails with the following error:
```
Message: System.ArgumentException : Expected: IEnumerable But was: TestElement
Parameter name: actual
```
I would expect that this sequence is either illegal, or when NUnit does allow it I would expect it to mean that the collection contains exactly 1 element and that element is equal to the provided object.

Side note: I encountered this while trying to write a constraint that in hindsight should probably be expressed as:
`Assert.That(new List<TestElement> { element }, Has.One.EqualTo(element));`
or as:
`Assert.That(new List<TestElement> { element, element2 }, Has.Member(element).And.Count.EqualTo(1));`

**Comment by CharliePoole** [comment]
Thanks for filing this!

**Comment by jnm2** [comment]
> I would expect it to mean that the collection contains exactly 1 element and that element is equal to the provided object.

I would expect it to mean `actual.Count(element => element == 1) == 1`.  That would allow for the count of elements to be arbitrarily large so long as the other elements do not satisfy `element == 1`.

**Comment by jnm2** [comment]
Wait a second, I messed that up.

`Has.One.Member(x)` is by definition a synonym to `Has.One.With.Member(x)`.

**Comment by jnm2** [comment]
In BCL parlance, I would read that as `actual.Count(element => element.Contains(x)) == 1`. It would only make sense in the context of nested collections.

**Comment by CharliePoole** [comment]
@jnm2 `Has.Member(X)` means that the enumeration contains an item equal to `X`. So `Has.One.Member(X)` should mean the same thing, with the further restriction that there can be only one of them.

**Comment by jnm2** [comment]
Maybe, but it would be a departure from the logic I think we've used thus far. `Has.Property` vs `Has.One.With.Property`; `Has.Member` vs `Has.One.With.member`. `With` is always a no-op.

**Comment by CharliePoole** [comment]
I don't think `With` enters into the discussion. As you say, its a no-op and we aren't using in this example anyway.

I guess you are saying that `Member` should work like `Property`, with all following constraints applying to the value of the property. I can see how one would think that but, in fact, `Member` has not worked that way in the past.

`Has.Member()` is something of a legacy construct. It used to involve object equality (sameness) but we stopped doing that a long time ago. Today `Has.Member(X)` is the same as `Has.Some.EqualTo(X)`, so I'd expect Has.One.Member(X)` to work like `Has.One.EqualTo(X)`.

That said, if it's possible to get into this much disagreement, I'd rather it be flagged as a compiler error in the first place!

**Comment by jnm2** [comment]
This is confusing; I'm not saying that constraints following `Member` should apply to the result but that constraints following `One` should apply to the `Exactly(1).Items` item result. Thus when `Member` follows `One` it is being applied to the result of `One`.

What if we deprecate `Member` since it's redundant when we have `EqualTo` and for me it's been confusing next to `Property` since I think of class members?

**Comment by CharliePoole** [comment]
AH! Now I understand. It makes sense when you look at it that way.

Knowing that `Has.Member` is synonymous with `Has.Some.EqualTo`,  I was surprised that we were allowing `Has.One.Member`, which would seem to match `Has.One.Some.EqualTo` and which makes no sense.

IOW, `Member` mixes together the comparison (equality) with what we apply it to (Some item) and that's not a style we tend to use any longer. I'd be in favor of deprecating it and making the combination with `One` impossible if we see an easy way to do it.

**Comment by Snaaio** [comment]
Thanks for looking into this so quickly guys. I can attest to this construct being confusing and for the record I am totally fine with disallowing it. I would say there are already plenty of alternatives that are equivalent and way more readable.
