### ISSUE TITLE
Enable .NET Standard 1.6 tests on non-Windows

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2611]
This will require installing two versions of the .NET Core SDK on Travis which may not be straightforward.
We need both the latest 1.1.x (because our tests target netcoreapp1.1) and the latest 2.0.x. I don't expect any 1.6 tests to fail once https://github.com/nunit/nunit/pull/2609 is merged, but since we use preprocessor and a whole different set of BCL libraries, there's always the chance.

The alternative would be to stop targeting netcoreapp1.1 in any test projects, but that would leave us without a way to test the netstandard1.6 NUnit DLL unless we added additional test csproj files which target netcoreapp2.0 and reference the netstandard1.6 framework DLL directly rather than referencing it via the framework project reference.

**Comment by jnm2** [comment]
@rprouse I remember you saying something about this. Maybe we should go down the alternative route? Should we go all the way and target our tests as `net47` (six csprojs to test every dll) and `netcoreapp2.0` (another two csprojs to test the .NET Standard dlls)?

**Comment by ChrisMaddock** [comment]
Sorry - I had no idea this issue existed when i commented on your PR! 😕

**Comment by jnm2** [comment]
Haha, no worries!
