### ISSUE TITLE
Assert.Multiple is not very useable from C++

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#2612]
We purport to support Managed C++ but Assert.Multiple doesn't work in C++ unless the user writes a bunch of shim code.

This is due to the fact that C# and C++ lambda expressions are not compatible, although it's possible to wrap a C++ lambda so it looks like a C# lambda.

I'm marking this issue for discussion and design. As part of the discussion phase, I'd like to here what our users who program in managed C++ do about this, if anything. Of course, it may turn out there are no such users or not many. 😄 

I'm thinking that one possible solution may be to create a header file that has the needed shims to make Assert.Multiple work with native C++ lambdas, but we should investigate whether there is actually a need first. If we go that way, it might be a separate project I would create myself or it could become an NUnit PR.

**Comment by jnm2** [comment]
If you use C++/CLI, you might also want to upvote https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/6703514-add-lambda-support-to-c-cli.

**Comment by rprouse** [comment]
We make heavy use of C++/CLI as a shim layer between legacy native code and newer managed code. Working in that layer is always painful and we avoid using any more advanced features like lambdas. We also almost always right our unit tests for those layers in C#. The fact that C++/CLI doesn't even support NuGet packages in this day and age causes us to avoid it as much as possible.

I don't think we should do much to support C++/CLI unless there are at least a few users asking for it. I like your idea of header files that support the shims.

I'm curious how you came across this @CharliePoole. Are you working with C++/CLI or did someone mention it to you?

**Comment by rprouse** [comment]
Just to make sure I wasn't lying about NuGet and C++/CLI, I Google/Bing'd it. Check out this super simple 11 step process for installing one package in one project, https://stackoverflow.com/questions/18694947/how-can-i-make-my-managed-nuget-package-support-c-cli-projects 😮 

Second class citizen?

**Comment by jnm2** [comment]
The last time I used C++/CLI was 2010 when I wrote a .NET QuickTime API. It seems almost no one remembers it exists.

**Comment by CharliePoole** [comment]
@rprouse As it happens, I'm working on a C++ version of the NUnit3TestDemo that's part of the NUnit 3 adapter repository. The idea is to use a language that doesn't use the Roslyn compiler so we can see how the test explorer operates in that case. Turns out quite a lot of NUnit's features can't be used from C++:  lambda arguments for assert.multiple and other things, async, .NET generics. Without some kind of shim it's not very powerful as a framework. Remains to be seen if there are actually any users.

**Comment by CharliePoole** [comment]
@rprouse I saw that recipe for using nuget packages with C++/CLI. As it turns out, I already have NUnit installed in the solution for C# and VB versions of the demo, so it was merely a matter of adding a reference to the C++.

**Comment by rprouse** [comment]
Adding reference to packages that are installed by a C# project is what we do, but it is a nightmare to maintain as packages get updated. No different than that work around I guess.

**Comment by rprouse** [comment]
I am closing old Idea issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
