### ISSUE TITLE
"Has no TestFixtures" message executing via nunit3-console.exe 

### ISSUE THREAD

**Issue by netmailgopi** [nunit/nunit#2613]
I have a simple class with a [TestFixture] and no [Test] methods inside it. I used to have the project reference NUnit 2.6.4 and run them with NUnit 2.6.4 runner. When I upgraded both to 3.7, I am getting this error. I don't want to change my code to get past this, is there a way around on this? Otherwise, I need to downgrade the project(s) to NUnit2 and run them, don't want to do that either 

```
Errors, Failures and Warnings
[14:34:27]
[14:34:27]1) Invalid : D:\BuildAgent\work\4d26b68a6ce28083\Projects\Tests\Services\Account\Services.Account.Daemons.User.Tests\bin\Staging\Services.Account.Daemons.User.Tests.dll
[14:34:27]Has no TestFixtures
[14:34:27]
[14:34:27]Run Settings
[14:34:27]    RuntimeFramework: net-4.0
[14:34:27]    DisposeRunners: True
[14:34:27]    ImageRuntimeVersion: 4.0.30319
[14:34:27]    ImageTargetFrameworkName: .NETFramework,Version=v4.5
[14:34:27]    ImageRequiresX86: False
[14:34:27]    ImageRequiresDefaultAppDomainAssemblyResolver: False
[14:34:27]    NumberOfTestWorkers: 2
```

Maybe related to https://github.com/nunit/nunit/issues/1118 but my use case is straightforward.

**Comment by CharliePoole** [comment]
I edited your example. For multi-line output, use a "fence" of three backticks before and after.

**Comment by CharliePoole** [comment]
Simply as an experiment, please add a test to the fixture.

Is there a reason you want to have an assembly with no tests in it?

**Comment by rprouse** [comment]
@netmailgopi we are waiting for a response from you in this issue. If we don't hear back, we will close the issue.

**Comment by netmailgopi** [comment]
Oops totally missed this. We have a bunch of old fixtures which are not
actually tests but categorized so. I excluded them from teamcity Nunit
step. I'm sure if we add tests they'll go through. Please close this
thread.

On Jan 15, 2018 5:58 PM, "Rob Prouse" <notifications@github.com> wrote:

@netmailgopi <https://github.com/netmailgopi> we are waiting for a response
from you in this issue. If we don't hear back, we will close the issue.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/nunit/nunit/issues/2613#issuecomment-357831519>, or mute
the thread

**Comment by jernelson7** [comment]
Hi, I'm having a similar issue and it's unclear to me what I'm supposed to do about it. I have an assembly with a test fixture marked with a category "LongRunning". When I run tests excluding that category, it throws an error that the assembly has no test fixtures. I want this to be silently ignored rather than an error. How can I do that?

Here's the edited relevant bits from the nunit.xml output:

> <command-line><![CDATA["C:\Users\Jeremy\Documents\dev\AccessibleEmail\Stage\Tools\nunit\nunit3-console.exe"  --x86  <MyTestAssembly>.dll  --out=<some path>\nunit.txt --process=Separate --where=" (cat != LongRunning) " --workers=1 --result=<some path>\nunit.xml --labels=All]]></command-line>

and later under that assembly
> <properties>
      <property name="_SKIPREASON" value="Has no TestFixtures" />
      <property name="_PID" value="7424" />
      <property name="_APPDOMAIN" value="domain-c7f214bf-<MyTestAssembly>.dll" />
    </properties>
    <failure>
      <message><![CDATA[Has no TestFixtures]]></message>
    </failure>
