### ISSUE TITLE
TestExecutionContext.CurrentContext is saved in Remoting CallContext between test runs

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#2614]
Discovered from https://github.com/nunit/nunit-console/issues/325.

TestExecutionContext.CurrentContext is currently saved in `Remoting.Messaging.CallContext` as below:

```
        private static readonly string CONTEXT_KEY = "NUnit.Framework.TestContext";

        public static TestExecutionContext CurrentContext
        {
            [SecuritySafeCritical]
            get
            {
                var context = CallContext.GetData(CONTEXT_KEY) as TestExecutionContext;

                if (context == null)
                {
                    context = new AdhocContext();
                    CallContext.SetData(CONTEXT_KEY, context);
                }

                return context;
            }

            [SecuritySafeCritical]
            private set
            {
                if (value == null)
                    CallContext.FreeNamedDataSlot(CONTEXT_KEY);
                else
                    CallContext.SetData(CONTEXT_KEY, value);
            }
        }
```

It appears that this CallContext is still accessible past the end of a single run, and across app domains. The result of this is that when the Console runs two tests assemblies sequentially (in the same process), the second test suite attempts to access the final TestExecutionContext of the previous assembly, and triggers an `AppDomainUnloadedException`.

I've tested this theory by including the below line at the end of `RunTestsAction` - i.e. as the last thing done by the framework in a test run. This appeared to clear the CallContext, and mean a new TestExecutionContext was created for the second assembly, as we'd want.

`CallContext.FreeNamedDataSlot("NUnit.Framework.TestContext");`

I know absolutely nothing about CallContext's, and the docs seem 'sparse'! From what I can see, `TestExecutionContext` implements `ILogicalThreadAffinative` - which is specifically to allow it to be accessed across AppDomains. What's the purpose of this, is it to permit user-created AppDomains? 

How should we handle this issue? I don't think the framework currently has any sort of 'clean-up' - is that the correct solution here?

**Comment by ChrisMaddock** [comment]
I suppose a second option would be to change the context key to be something unique to the current test assembly.

**Comment by CharliePoole** [comment]
The primary purpose of implementing `ILogicalThreadAffinative` is to allow the `TestExecutionContext` to flow across threads as they are created by the user or by the compiler in the case of async methods. A side effect is that it flows across `AppDomain` boundaries as well. This would definitely help in the case of user-created domains.

In the past, we always cleared the slot in the `CallContext` after the test run completed. We may have stopped doing that and simply not noticed because it's much rarer nowadays to run multiple assemblies in one process. I think we should go back to clearing it.

**Comment by ChrisMaddock** [comment]
> In the past, we always cleared the slot in the CallContext after the test run completed. 

In the framework I presume, rather than the engine? It feels like this cleanup should be the framework's responsibility.

**Comment by CharliePoole** [comment]
Yes, in the framework.

**Comment by ChrisMaddock** [comment]
Great - I'll take a look. Thanks!

**Comment by jnm2** [comment]
The other thing with `CallContext` is that it's .NET Framework-only. We replaced it with `AsyncLocal<>` in our .NET Standard builds.

**Comment by ChrisMaddock** [comment]
AsyncLocal is only .NET 4.6+ though, right? 😞 Or was your point that we should be clearing that as well?

**Comment by jnm2** [comment]
It is 4.6+, I keep forgetting! AppDomain is a .NET Framework-only construct as well, so the same problem can't exist on other platforms. Maybe make sure there is no similar problem?

**Comment by CharliePoole** [comment]
You can't have a problem with CallContext leakage on platforms that don't have / use CallContext. If there are other issues, then the key word is __other__.

TestExecutionContext had three different implementations in the past. Now it only has two.

**Comment by rprouse** [comment]
@ChrisMaddock how far out are you with the PR for this one? I don't mind waiting a few days for the release, but not if this is dangerous or will take awhile.

**Comment by ChrisMaddock** [comment]
I think the code that’s already written just needs moving to a different place, and I can hopefully do that tomorrow! 🙂

**Comment by ChrisMaddock** [comment]
@rprouse - Actually, looking at @CharliePoole's comments on the PR I feel like we might need a bit more time to work out the correct design for this. Suggest we leave it for after the release, it's not a 'new' problem.
