### ISSUE TITLE
NUnit is retaining the previous 'Failed' value in  TestContext.CurrentContext.Result.Outcome when working with Retry attribute

### ISSUE THREAD

**Issue by ammark1** [nunit/nunit#2619]
Hi @CharliePoole , I am facing a problem with Retry Attribute. NUnit is retaining the previous Failed value in
TestContext.CurrentContext.Result.Outcome and hence my Test Case is Failed even if it is actually Passed in the second attempt. Please see the below code snippet, my code goes inside the First if loop because currentContext.Result.Outcome value is "Failed" in the second attempt as well in the TearDown method(although my Test gets passed during the second attempt):

```cs
[TearDown]
public void TearDown()
{
    try
    {
        var currentContext = TestContext.CurrentContext;
        var message = TestContext.CurrentContext.Result.Message;
        var stackTrace = TestContext.CurrentContext.Result.StackTrace;
        if (currentContext.Result.Outcome != ResultState.Success)
        {
            var testName = currentContext.Test.Name;
            string rootPath = AppDomain.CurrentDomain.BaseDirectory;
            String filename = rootPath + "\Report\" + this.GetType().FullName + "." + testName + "_" + DateTime.Now.ToString("yyyy - MM - dd - HH - mm - ss") + ".png";
            Console.WriteLine("filename: " + filename);
            UtilityHelper.TakeScreenshot(_driver, filename);
            if (Global.tempCount <= 1)
                Global.test.Log(Status.Fail, stackTrace + message);
        }
        Log.Info("Teardown test");
        _driver.Quit();
    }
    catch { _driver.Dispose(); }
}
```

**Comment by CharliePoole** [comment]
@ammark1 Just to be sure we understand...

You have a test marked with `[Retry(n)]` where n is greater than or equal to 2. It fails on the first attempt and passes on the second. You are seeing results in teardown as follows:

```
First iteration: Failed
Second iteration: Failed
```

Is that correct?

**Comment by ammark1** [comment]
Yes that's correct. I have slightly modified the Retry Class though as per my needs. So Retry(n) is 3 in my code, and system runs 3 times, first time it's failed, and second and is Passed, but NUnit marks it Failed, and then it again runs(that is third time) and finally mark the Test Case as Failed.

The Execute method in the CustomRetry class looks like below:
public override TestResult Execute(TestExecutionContext context)
            {
                int count = _retryCount;

                while (count-- > 0)
                {
                    context.CurrentResult = innerCommand.Execute(context);
                    Global.tempCount = count;
                    var results = context.CurrentResult.ResultState;

                    if (results != ResultState.Error
                        && results != ResultState.Failure
                        && results != ResultState.SetUpError
                        && results != ResultState.SetUpFailure
                        && results != ResultState.TearDownError
                        && results != ResultState.ChildFailure)
                    {
                        break;
                    }
                }

                return context.CurrentResult;
            }
I followed below link to create the custom class:
https://testingrepository.com/retry-failed-tests-in-nunit/

Thanks for your response @CharliePoole  Please let me know if I am doing something wrong.

**Comment by jnm2** [comment]
@ammark1 Are you using NUnit 3.9.0?
(I formatted your code to make it easier to read.)

@CharliePoole Is including the Site component in this comparison coming to bite us?

https://github.com/nunit/nunit/blob/9b2159fccd35a0895ea937517170d3b4ecece815/src/NUnitFramework/framework/Attributes/RetryAttribute.cs#L96

**Comment by ammark1** [comment]
Hey @jnm2 I am using NUnit 3.8.1

**Comment by mitchellmaler** [comment]
I think it's because you are not clearing the result before looping again?

```
// Clear result for retry
if (count > 0)
    context.CurrentResult = context.CurrentTest.MakeTestResult();
```

**Comment by jnm2** [comment]
I have to think pretty hard when I look at that loop so I might be mistaken, but I think `count > 0` is what we want there. The last time through the loop is the only time `count == 0` and that's when we don't want to reset.

**Comment by CharliePoole** [comment]
@jnm2 I think he may be getting bitten by the reference comparison issue we fixed in the source but which is not yet release. I'll try this on the current master using our plain vanilla retry to be sure.

**Comment by ammark1** [comment]
Nailed it @mitchellmaler Updated the code as per your suggestion and it worked ! 
Below are the updated code snippets of Execute and TearDown methods:

public override TestResult Execute(TestExecutionContext context)
            {
                int count = _retryCount;

                while (count-- > 0)
                {
                    context.CurrentResult = innerCommand.Execute(context);
                    Global.tempCount = count;
                    var results = context.CurrentResult.ResultState;

                    if (results != ResultState.Error
                        && results != ResultState.Failure
                        && results != ResultState.SetUpError
                        && results != ResultState.SetUpFailure
                        && results != ResultState.TearDownError
                        && results != ResultState.ChildFailure)
                    {
                        break;
                    }
                    if (count > 0)
                    {
                        context.CurrentResult = TestExecutionContext.CurrentContext.CurrentTest.MakeTestResult();
                    }
                }

                return context.CurrentResult;
            }

public void TearDown()
        {
            try
            {
                //var currentContext = TestContext.CurrentContext;
                var currentContext = TestExecutionContext.CurrentContext;
                var message = TestContext.CurrentContext.Result.Message;
                var stackTrace = TestContext.CurrentContext.Result.StackTrace;
                //if (currentContext.Result.Outcome != ResultState.Success)
                if (currentContext.CurrentResult.ResultState != ResultState.Success)
                {
                    var testName = currentContext.CurrentTest.Name;
                    string rootPath = AppDomain.CurrentDomain.BaseDirectory;
                    String filename = rootPath+"\\Report\\" + this.GetType().FullName + "." + testName + "_" + DateTime.Now.ToString("yyyy-MM-dd-HH-mm-ss") + ".png";
                    Console.WriteLine("filename: " + filename);
                    UtilityHelper.TakeScreenshot(_driver, filename);
                    if (Global.tempCount <= 1)
                        Global.test.Log(Status.Fail, stackTrace + message);
                }
                Log.Info("Teardown test");
                _driver.Quit();
            }
            catch { _driver.Dispose(); }
        }

**Comment by jnm2** [comment]
Here's the test we'd add to NUnit:

```cs
public sealed class RetryAttributeTeardownFixture
{
    private bool isFirstRun = true;

    [Test]
    public void Test()
    {
        if (!isFirstRun) return;
        isFirstRun = false;
        Assert.Fail();
    }

    [TearDown]
    public void TeardownShouldSeeCorrectTestStatus()
    {
        Assert.That(TestContext.CurrentContext.Result.Outcome.Status, Is.EqualTo(isFirstRun ? TestStatus.Failed : TestStatus.Passed));
    }
}
```

Is this something we should fix? It seems so.

**Comment by jnm2** [comment]
Or perhaps

<details>

```cs
public abstract class RetryAttributeTeardownFixture
{
    private bool isFirstRun = true;

    public abstract ResultState GetCurrentResultState();

    [Test]
    public void Test()
    {
        if (!isFirstRun) return;
        isFirstRun = false;
        Assert.Fail();
    }

    [TearDown]
    public void TeardownShouldSeeCorrectTestStatus()
    {
        Assert.That(GetCurrentResultState(), Has.Property("Status").EqualTo(isFirstRun ? TestStatus.Failed : TestStatus.Passed));
    }

    public sealed class TestContextFixture : RetryAttributeTeardownFixture
    {
        public override ResultState GetCurrentResultState()
        {
            return TestContext.CurrentContext.Result.Outcome;
        }
    }

    public sealed class TestExecutionContextFixture : RetryAttributeTeardownFixture
    {
        public override ResultState GetCurrentResultState()
        {
            return TestExecutionContext.CurrentContext.CurrentResult.ResultState;
        }
    }
}
```

</details>

**Comment by jnm2** [comment]
Turns out I can't program tonight. 😂 Anyway, I can't find a repro for this on master. I'll try with 3.8.1.

**Comment by jnm2** [comment]
Oh duh... it took me this long to realize there was never a problem with NUnit's RetryAttribute. Only the custom class. 😂 Sorry everyone!

@ammark1 Is there anything outstanding after @mitchellmaler's help?

> I wonder why it was not resetting the current context by default :-(

What were you expecting to cause the reset? `innerCommand.Execute(context)`?

**Comment by CharliePoole** [comment]
@jnm2 As mentioned in another discussion, I already started a branch to add tests for this.

**Comment by CharliePoole** [comment]
@jnm2 Not sure how to label this... I used `closed:notabug` even though there is a commit so it wouldn't show up in the release notes.

**Comment by ammark1** [comment]
@jnm2 All good after @mitchellmaler help. Yes I thought that it would reset the results whenever the test is re-executed after `innerCommand.Execute(context)?`

**Comment by jnm2** [comment]
Thanks. I was just curious about your intuition with the API.
