### ISSUE TITLE
Breaking change in CollectionAssert.AllItemsAreUnique with NUnit 3.9

### ISSUE THREAD

**Issue by simarust** [nunit/nunit#2627]
After upgrading to NUnit Framework 3.9 we have a failing test that checks if all items of an object collection are unique. Example:
```
var collection = new Collection<object> {42, null, 42f};
Assert.That(
    () => CollectionAssert.AllItemsAreUnique(collection),
    Throws.TypeOf<AssertionException>());
```
A float value of `42f` now is considered to be different to an integer value `42`.
Is this intentional or an undesirable side effect of maybe #2551?

**Comment by jnm2** [comment]
We should probably add `|| memberType == typeof(object)`:

https://github.com/nunit/nunit/blob/e465d6966971cdcdd7859439902707e2c56414cb/src/NUnitFramework/framework/Constraints/UniqueItemsConstraint.cs#L79-L83

**Comment by jnm2** [comment]
@simarust Thanks for reporting this. Are you interested in contributing a fix? I think it would be as simple as adding the check I mentioned, plus adding the test you've written above.

**Comment by CharliePoole** [comment]
Why did it "work" before? Are we changing the semantics here?

**Comment by jnm2** [comment]
Yes. I think Mikkel spotted the semantic change we made. If `memberType == typeof(object)`, we go ahead with the fast hashtable code which does not use NUnit equality.

**Comment by jnm2** [comment]
We have the same problem with nonsealed classes and interfaces in general, so we could also be on the safe side and check that the type is nonvirtual or sealed.

**Comment by CharliePoole** [comment]
@jnm2 Actually, it's Numberic types that are handled specially, not object. We have a method (I'm not looking at the code right now, but it's called in NUnitEqualityComparer) that tests for our definition of numeric.

**Comment by jnm2** [comment]
@CharliePoole That is why I lean toward not putting the check in `IsHandledSpeciallyByNUnit` but rather against the `memberType` variable. It's the collection element type which is System.Object, not the type of the instances themselves.

**Comment by CharliePoole** [comment]
So you're basically saying that if the member type is object, it could be anything! That's right of course. Let's hope it doesn't happen often. :smile:

**Comment by jnm2** [comment]
`new IConvertible[] { 1, 1f }` leaves us in the same boat as `new object[] { 1, 1f }` too. What do you think about requiring the element type to be nonvirtual or sealed in order to take the fast path, then cautiously proceeding back from there if adjustments are needed? That way we're completely safe.

**Comment by CharliePoole** [comment]
That makes sense.

**Comment by jnm2** [comment]
Alright: I'm removing <kbd>good first issue</kbd> because I want to see comprehensive tests proving that NUnit equality is used when the element type is virtual and unsealed. @mikkelbu Would you like this one?

**Comment by mikkelbu** [comment]
Sure. I can take a look at it.

**Comment by rprouse** [comment]
@mikkelbu have you made any progress on this? It is in the 3.10 milestone and assigned to you. I would like to get 3.10 out soon, so I am triaging the issues remaining in the milestone.

**Comment by mikkelbu** [comment]
@rprouse Actually, I've not had time to look at this yet, but I think that I'll have time to do it this weekend.

**Comment by jnm2** [comment]
@mikkelbu I was thinking from a lexical C# standpoint in which struct, delegate types and enum types are don't have the C# `sealed` keyword. Your check is correct though because it's operating at the IL level which does use the IL `sealed` attribute for all those things. Also, your tests cover what we care about. 👍
