### ISSUE TITLE
Error during installing tools when running build script

### ISSUE THREAD

**Issue by OmicronPersei** [nunit/nunit#2628]
When I ran `.\build.ps1 -t test45`, I saw

> Error finding repository for 'https://ci.appveyor.com/nuget/nunit': An error occurred while retrieving package metadata for 'NUnit.ConsoleRunner.3.7.0' from source 'NUnit AppVeyor CI'.
  A task was canceled.

CC @jnm2

**Comment by OmicronPersei** [comment]
I should note the build and tests all performed otherwise fine.

**Comment by jnm2** [comment]
@rprouse Is this needed?

https://github.com/nunit/nunit/blob/e465d6966971cdcdd7859439902707e2c56414cb/NuGet.config#L4

**Comment by OmicronPersei** [comment]
Also noticed another one when doing `build.ps1 -t clean`:
> Error finding repository for 'https://www.myget.org/F/nunit/api/v2': An error occurred while retrieving package metadata for 'NUnit.ConsoleRunner.3.7.0' from source 'NUnit MyGet Feed'.
  A task was canceled.

**Comment by jnm2** [comment]
This might not be our bug:

 - https://github.com/cake-build/cake/issues/1937
 - https://github.com/cake-build/cake/issues/1877

**Comment by rprouse** [comment]
@jnm2 that line isn't needed for NUnit as far as I can think of. We've copied that `NuGet.config` file from repo to repo. We add in the various AppVeyor feeds so we can easily test builds in different repos, so we just include them all for convenience.

**Comment by jnm2** [comment]
If anyone would like to contribute this PR before I get to it, please go ahead.

**Comment by jnm2** [comment]
@rprouse– I took from that that we're okay with the nuget.configs diverging between repos and going ahead with removing the line. Let me make sure; is that what you meant?

**Comment by rprouse** [comment]
I am fine with them diverging. There is no reason to reference the NUnit CI packages from NUnit.

**Comment by pandualuvala** [comment]
Hello can i take this Task? Thanks

**Comment by jnm2** [comment]
Yes, it's yours! Let us know if you need anything.
