### ISSUE TITLE
New tests don't show up in TestResult.xml

### ISSUE THREAD

**Issue by OmicronPersei** [nunit/nunit#2629]
New tests added to the `nunit.framework.tests` project do not appear in the `TestResult.xml` file, when executed using the build Cake script.

When a test fails, the script output does catch them and report, they just don't seem to make their way into the output XML file.

However, using the NUnit Adapter 3.9.0.0 within VS2017 does appear to detect and run them.

**Comment by CharliePoole** [comment]
@OmicronPersei This can't be generally true, since we are adding tests all the time and they definitely show up. So if it's happening, it must be something particular about those tests. Can you provide an example of a particular test that doesn't show up?

**Comment by OmicronPersei** [comment]
Will confirm later, but at least one of the tests was as simple as `Assert.IsTrue(false);`

**Comment by OmicronPersei** [comment]
In a fresh clone, the following test does not appear in the TestResult.xml

```C#
namespace NUnit.Framework.Internal.Filters
{
    public class MiscTestClass
    {
        [Test]
        public void LotsOfFail2()
        {
            Assert.IsTrue(false);
        }
    }
}
```

**Comment by CharliePoole** [comment]
@OmicronPersei I hate to ask, but are you certain you are looking at the `TestResult.xml` that is newly created in your test run? My own setup has a bunch of TestResult files in various places and it's easy to be looking at the wrong one.

**Comment by OmicronPersei** [comment]
Assuming this is where I should be looking (the output of the build script):
>Results (nunit3) saved as C:\temp\nunit\bin\Release\net45\TestResult.xml
Finished executing task: Test45

Yes.

**Comment by CharliePoole** [comment]
Because we recently switched directory names, take a look at the timestamp on the file as well. I'll give it a try myself too.

**Comment by CharliePoole** [comment]
If Parallelism is in use, yes. The tests are all found and queued in the same order but the order in the TestResult.xml is the order in which they finish. 

Did the newly created file contain all tests? Is it possible that some error is occurring when the file comes to be overwritten and not being reported?

**Comment by OmicronPersei** [comment]
It's hard to tell because the 90% of the two test files are different, but they're very close to the same size.

**Comment by OmicronPersei** [comment]
Can I tell the build script not to use parallelism?

**Comment by CharliePoole** [comment]
You could temporarily modify it to use `--workers:0`.

Of course, even if the order of the file is different it should still
contain the record for every test and the reported counts should indicate
that new tests were added.

**Comment by jnm2** [comment]
@OmicronPersei This did not repro for me.

 - `git fetch upstream`
 - `git checkout upstream/master` (e465d6966971cdcdd7859439902707e2c56414cb )
 - `git clean -xdf`
 - Added `src/NUnitFramework/tests/Internal/Filters/Class1.cs` containing the exact `LotsOfFail2` example above
 - `.\build -t test45`
 - TestResult.xml (in the repo root, not in `bin\Release\net45`) contains `LotsOfFail2` as expected

**Comment by jnm2** [comment]
I wonder if what's confusing is that we're running two NUnit test process back to back; first NUnit tests, then NUnitLite tests, and they output files with the exact same name but to separate locations. The two together do look a bit like a single NUnit console run.

**Comment by CharliePoole** [comment]
@jnm2 I think you've nailed it. The test45 task runs two tests, first framework and then nunitlite. You would have to scroll up to see the message left by the framework tests.

**Comment by rprouse** [comment]
@OmicronPersei I readded the confirm, can you confirm that @jnm2 and @CharliePoole found your error?

**Comment by OmicronPersei** [comment]
Yep, looks like the TestResult.xml at the root of the repo was the one I was looking for!
