### ISSUE TITLE
Framework throws NullReferenceException if test parameter is marked with [Values(null)]

### ISSUE THREAD

**Issue by LeonidVasilyev** [nunit/nunit#2630]
I'm using NUnit 3.9.0, NUnit Console Runner 3.7.0 and NUnit 3 Test Adapter 3.9.0 for Visual Studio Community 2017. 

Exception is seems to be thrown by access to `Array.Length` property in [`ParamAttributeTypeConversions.GetData()`](https://github.com/nunit/nunit/blob/04c6b7b4984a01831be94baeab0744b1cc686980/src/NUnitFramework/framework/Internal/ParamAttributeTypeConversions.cs#L55). `Values(null)` is resolved to [`ValuesAttribute(params object[] args)`](https://github.com/nunit/nunit/blob/e91441571843b586edc94d4f822029fce3219f67/src/NUnitFramework/framework/Attributes/ValuesAttribute.cs#L93) call. Issue can be reproduced using following code snippet:
```csharp
class Foo
{
    [Test]
    public void Bar([Values(null)] int? param)
    {
        Assert.Pass();
    }
}
```
In Visual Studio test is not discovered during test project build, i.e. it doesn't appear in Test Explorer list of tests. No message is shown in Output window. NUnit Console Runner shows following error message:
> System.NullReferenceException: Object reference not set to an instance of an object. at NUnit.Framework.Internal.ParamAttributeTypeConversions.GetData(Object[] data, Type targetType) at NUnit.Framework.Internal.Builders.ParameterDataSourceProvider.GetDataFor(IParameterInfo parameter) at NUnit.Framework.CombiningStrategyAttribute.BuildFrom(IMethodInfo method, Test suite) at NUnit.Framework.Internal.Builders.DefaultTestCaseBuilder.BuildFrom(IMethodInfo method, Test parentSuite) at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.AddTestCasesToFixture(TestFixture fixture) at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildFrom(ITypeInfo typeInfo) at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom(ITypeInfo typeInfo)

You can check original use case in [How to pass NULL value to ValuesAttribute of the test method?](https://stackoverflow.com/questions/47732431/how-to-pass-null-value-to-valuesattribute-of-the-test-method/47872060#47872060) discussion on StackOverflow.

**Comment by jnm2** [comment]
You're right! Thanks for spotting that.

We should be doing the same thing we do for `TestCaseAttribute`:

https://github.com/nunit/nunit/blob/e91441571843b586edc94d4f822029fce3219f67/src/NUnitFramework/framework/Attributes/TestCaseAttribute.cs#L52-L55

And we should be doing the same test:

https://github.com/nunit/nunit/blob/e91441571843b586edc94d4f822029fce3219f67/src/NUnitFramework/tests/Attributes/TestCaseAttributeTests.cs#L509-L513

This is pretty straightforward. @LeonidVasilyev, are you interested in contributing the fix?

**Comment by CharliePoole** [comment]
@jnm2 There's a little more to it, I think, although not much. Introduction of ParamAttributeTypeConversions seems to have started it. The GetData method needs a Guard statement and the call should be conditional. I'm a bit surprised that the Parana argument is the one selected but there's no way we can change that.

**Comment by jnm2** [comment]
Thanks, yes. The implementer should add a `Guard.ArgumentNotNull` here to prevent the NRE:

https://github.com/nunit/nunit/blob/04c6b7b4984a01831be94baeab0744b1cc686980/src/NUnitFramework/framework/Internal/ParamAttributeTypeConversions.cs#L53-L55

@CharliePoole Which call should be conditional?

**Comment by jnm2** [comment]
Ah, this one, I think:

https://github.com/nunit/nunit/blob/04c6b7b4984a01831be94baeab0744b1cc686980/src/NUnitFramework/framework/Attributes/ValuesAttribute.cs#L101-L104

If `data` is null, what should it return or throw?

**Comment by CharliePoole** [comment]
I think that call points out the problem. The field `data` should __never__ be null, it's the args values being provided so it has to be an array. If it's seen to be null at that point, it is meant to be an array of length 1 with a null as it's single member, and there is nothing to be converted.

I'm doubting "good first issue"on this one. Maybe @mikkelbu wants to come back to it. 😸

**Comment by jnm2** [comment]
Do we even need a check? The only possible cause is if `ValueAttribute` has a badly implemented constructor, and we'll get the ArgumentNullException then due to the guard we're adding.

Yep, agree.

**Comment by CharliePoole** [comment]
If we fix the constructor, I agree we can avoid the check.

**Comment by jnm2** [comment]
Okay. To recap:

We should be doing the same thing in the ValuesAttribute params constructor that we do for `TestCaseAttribute`:

https://github.com/nunit/nunit/blob/e91441571843b586edc94d4f822029fce3219f67/src/NUnitFramework/framework/Attributes/TestCaseAttribute.cs#L52-L55

And we should be doing the same test:

https://github.com/nunit/nunit/blob/e91441571843b586edc94d4f822029fce3219f67/src/NUnitFramework/tests/Attributes/TestCaseAttributeTests.cs#L509-L513

We should add a `Guard.ArgumentNotNull` here to prevent the NRE:

https://github.com/nunit/nunit/blob/04c6b7b4984a01831be94baeab0744b1cc686980/src/NUnitFramework/framework/Internal/ParamAttributeTypeConversions.cs#L53-L55

And add a test to ParamAttributeTypeConversionTests to ensure this behavior.

@mikkelbu (or @LeonidVasilyev), are you interested in working on this one?

**Comment by mikkelbu** [comment]
@jnm2 Not particularly 😄, but if I have time then I could take a look at this.
Ps. I'm a bit unsure why my name came up. AFAICR I have not touched any of the files mentioned above.

**Comment by jnm2** [comment]
Oh, I think I mixed up the two issues. I'll do it if I have time.

**Comment by LeonidVasilyev** [comment]
@jnm2, thank you for asking. Unfortunately, I'm currently in lack of time needed to setup all environment and study the developer documentation. Maybe I will comeback to this issue if nobody will do this earlier.

**Comment by LeonidVasilyev** [comment]
> I'm a bit surprised that the params argument is the one selected but there's no way we can change that.

@CharliePoole, It appears to be that C# compiler treats constructor with params array as more specific than constructor with single object parameter because every `object[]` is `object` but not every `object` is `object[]`.

**Comment by ChrisMaddock** [comment]
I imagine this overlaps with @StanEgo's ongoing work on #2104. Maybe one to discuss, to avoid duplicating work. 🙂

**Comment by jnm2** [comment]
Good, thanks for pointing that out! I'll have to rewrite the one I am editing. 😊
