### ISSUE TITLE
Possible to have different category depending on combinatorial values?

### ISSUE THREAD

**Issue by jakkra** [nunit/nunit#2631]
For example (very simple example) below this is what I want to achive, but without writing every TestCase
```
        [TestCase(1, Category = "MY_CAT_1")]
        [TestCase(2, Category = "MY_CAT_2")]
        public void VerifyWorks(int mode)
```

Goal, but with different category depending on combinatorial mode.
```
        public void VerifyWorks([Values(1, 2)] int mode)
```

Is this possible? If not, what is the correct approach? Not using combinatorial is not an option, we have to many different cases.

**Comment by CharliePoole** [comment]
It's not possible to do this currently. Can you explain what you want to achieve with a mire complete example?

**Comment by jakkra** [comment]
We have hardware which support functionality X, Y with tests written for them. However now I have a new hardware with just functionality X. Since most of the tests are written with combinatorial:

     
```
public void VerifyWorks([Values(X, Y)] hardwareFunctionality)
{
if (X) {
    doSomethingMinor();
} 
    doSomethingMinor();
}

common code.
}
```

So for hardware X I just want to run VerifyWorks(X), since Y is not supported.
If course I can split it into two tests VerifyWorksX and VerifyWorksY and then call the common code. But this was an idea to avoid having to do that. Also all unsupported/known_erorr files need to be updated with the new test names.

**Comment by CharliePoole** [comment]
I wasn't looking for a business case, just what you would like to be able to type as a command and have happen as a result. The examples only have one argument, so it's pretty trivial to switch to using TestCase and specify the categories as you want to do. I'm assuming your real tests have multiple args, which are combined by NUnit into test cases.

I'm asking because I see the hint of a possible new feature in this issue, but the usage is still not entirely clear.

**Comment by jakkra** [comment]
Ah sorry I missunderstood!
Something like this is what we have. But what would be nice is if I can specify to only run LowEnergy tests.
```
public void BondingTest(
            [Values (Classic, LowEnergy)] Mode mode,
            [Values (DisplayYesNo, KeyboardOnly, SecurityOptX, SecurityOptY)] SecurityMode secMode,
            [Values(Initiator, Receiver)] Role role,
            [Values(115200, 912000, 1000000)] BaudRate rate)
        {
        }
```
I don't know what the best way to do it would be, the syntax is not straight forward for how to do it easiest/best. But just from the top of my head, one way to do it could be the ability to have combinatorials in [TestCase] like this:
```
[TestCase([Values (Classic)], [Values (1, 2, 3, 4)]), [Values(Initiator, Receiver)], [Values(115200, 912000, 1000000)], Category = "CLASSIC"]
[TestCase([Values (LowEnergy)], [Values (1, 2, 3, 4)]), [Values(Initiator, Receiver)], [Values(115200, 912000, 1000000)], Category = "LOW_ENERGY"]
public void BondingTest(Mode mode, SecurityMode secMode, Role role, BaudRate rate)
{
}
```

**Comment by jnm2** [comment]
C# would not like that, but this would be legal:

```cs
public void BondingTest(
    [Value(Classic, Category="Classic"), Value(LowEnergy, Category="LowEnergy")] Mode mode,
    [Values (DisplayYesNo, KeyboardOnly, SecurityOptX, SecurityOptY)] SecurityMode secMode,
    [Values(Initiator, Receiver)] Role role,
    [Values(115200, 912000, 1000000)] BaudRate rate)
{
}
```

**Comment by jnm2** [comment]
I suppose we could even allow multiple `Values` attributes on the same parameter and have each attribute specify a different category:

```cs
public void BondingTest(
    [Values(Classic, Category = "CLASSIC")]
    [Values(LowEnergy, LowEnergy2, Category = "LOW_ENERGY")] Mode mode,
    [Values(DisplayYesNo, KeyboardOnly, SecurityOptX, SecurityOptY)] SecurityMode secMode,
    [Values(Initiator, Receiver)] Role role,
    [Values(115200, 912000, 1000000)] BaudRate rate)
{
}
```

**Comment by jakkra** [comment]
Something like that would be awesome!

**Comment by CharliePoole** [comment]
@jnm2 Didn't we just change `ValuesAttribute` to allow multiple instances per parameter? If not, that's pretty trivial.

The proposed addition of a `Category` property would work syntactically (i.e. .Net would allow it) but it's a pretty major change to all the joining attributes that create test cases: `Combinatorial`, `Pairwise` and `Sequential`. They would have to track the categories associated with each value whereas now they simply work from multiple lists of values when creating test cases. I'd call it feasible but not an exercise for beginners. 😄 

I always like to ask "Why?" as many times as necessary to get to the root of an issue, so for the moment I'm sticking to trying to solve the OP's problem with what we already have, but I think this is a possible future enhancement if the right person is willing to put in the time to implement it.

**Comment by CharliePoole** [comment]
@jakkra So back to what you are trying to do... I like to use the "five whys" to try to understand what somebody is asking for. So far, I've learned that you want categories on parameter values is so they will be applied to the test case that contains those values so you can use those categories to just run the test cases that include the particular value.

So let's generalize that away from categories, which are after all just one of the ways to select the tests to be run. It's as if you would like to be able to type...

```
nunit3-console my.tests.dll --where "method==SomeMethod && <mode is Classic>
```

or, equivalently

```
nunit3-console my.tests.dll --where "method==SomeMethod && <first argument is Classic>
```

You can currently do that... sort of. Let's use your example...

```
public void BondingTest(
            [Values (Classic, LowEnergy)] Mode mode,
            [Values (DisplayYesNo, KeyboardOnly, SecurityOptX, SecurityOptY)] SecurityMode secMode,
            [Values(Initiator, Receiver)] Role role,
            [Values(115200, 912000, 1000000)] BaudRate rate)
        {
        }
```

From this, NUnit would create quite a lot of tests with the following names:

```
BondingTest(Classic, DisplayYesNo, Initiator, 11520)
BondingTest(Classic, DisplayYesNo, Initiator, 912000)
BondingTest(Classic, DisplayYesNo, Initiator, 1000000)
BondingTest(Classic, KeyboardOnly, Initiator, 11520)
BondingTest(Classic, KeyboardOnly, Initiator, 912000)
BondingTest(Classic, KeyboardOnly, Initiator, 1000000)
BondingTest(Classic, SecurityOptX, Initiator, 11520)
BondingTest(Classic, SecurityOptX, Initiator, 912000)
BondingTest(Classic, SecurityOptX, Initiator, 1000000)
BondingTest(Classic, SecurityOptY, Initiator, 11520)
BondingTest(Classic, SecurityOptY, Initiator, 912000)
BondingTest(Classic, SecurityOptY, Initiator, 1000000)
BondingTest(Classic, DisplayYesNo, Receiver, 11520)
BondingTest(Classic, DisplayYesNo, Receiver, 912000)
BondingTest(Classic, DisplayYesNo, Receiver, 1000000)
BondingTest(Classic, KeyboardOnly, Receiver, 11520)
BondingTest(Classic, KeyboardOnly, Receiver, 912000)
BondingTest(Classic, KeyboardOnly, Receiver, 1000000)
BondingTest(Classic, SecurityOptX, Receiver, 11520)
BondingTest(Classic, SecurityOptX, Receiver, 912000)
BondingTest(Classic, SecurityOptX, Receiver, 1000000)
BondingTest(Classic, SecurityOptY, Receiver, 11520)
BondingTest(Classic, SecurityOptY, Receiver, 912000)
BondingTest(Classic, SecurityOptY, Receiver, 1000000)
BondingTest(LowEnergy, DisplayYesNo, Initiator, 11520)
BondingTest(LowEnergy, DisplayYesNo, Initiator, 912000)
BondingTest(LowEnergy, DisplayYesNo, Initiator, 1000000)
BondingTest(LowEnergy, KeyboardOnly, Initiator, 11520)
BondingTest(LowEnergy, KeyboardOnly, Initiator, 912000)
BondingTest(LowEnergy, KeyboardOnly, Initiator, 1000000)
BondingTest(LowEnergy, SecurityOptX, Initiator, 11520)
BondingTest(LowEnergy, SecurityOptX, Initiator, 912000)
BondingTest(LowEnergy, SecurityOptX, Initiator, 1000000)
BondingTest(LowEnergy, SecurityOptY, Initiator, 11520)
BondingTest(LowEnergy, SecurityOptY, Initiator, 912000)
BondingTest(LowEnergy, SecurityOptY, Initiator, 1000000)
BondingTest(LowEnergy, DisplayYesNo, Receiver, 11520)
BondingTest(LowEnergy, DisplayYesNo, Receiver, 912000)
BondingTest(LowEnergy, DisplayYesNo, Receiver, 1000000)
BondingTest(LowEnergy, KeyboardOnly, Receiver, 11520)
BondingTest(LowEnergy, KeyboardOnly, Receiver, 912000)
BondingTest(LowEnergy, KeyboardOnly, Receiver, 1000000)
BondingTest(LowEnergy, SecurityOptX, Receiver, 11520)
BondingTest(LowEnergy, SecurityOptX, Receiver, 912000)
BondingTest(LowEnergy, SecurityOptX, Receiver, 1000000)
BondingTest(LowEnergy, SecurityOptY, Receiver, 11520)
BondingTest(LowEnergy, SecurityOptY, Receiver, 912000)
BondingTest(LowEnergy, SecurityOptY, Receiver, 1000000)
```

If I want to run all the low energy tests, I can use...

```
nunit3-console my.tests.dll --where "test=~BondingTest\(LowEnergy"
```

If I want to run the tests with SecurityOptX OR SecurityOptY using baud rate 912000, I can use

```
nunit3-console my.tests.dll --where "test=~BondingTest\(.*SecurityOpt.*912000"
```

And so forth. 

The above assumes that all your args are enums that display their names. For other args you would have to adjust the expression.

This isn't saying it wouldn't be nice to be able to type

```
nunit3-console my.tests.dll --where "method == BondingTest && arg1 == LowEnergy"
```

but that would take quite a bit of work and might not help many people beyond what can currently be done.

**Comment by jakkra** [comment]
Great, using --where will defenately work for me, thanks! As you say, since it require alot of work, and it's pretty specific, it's probably not worth implementing.

**Comment by CharliePoole** [comment]
@jnm2 Should we close this or do you want to keep it alive with the possibility of adding "mixin" categories in the way you outlined?

I did a quick review and I think we would have to...
* Add the property to all our parameter attributes.
* Change each attribute to return a parameter data class rather than just the argument value. The new class would be analagous to `TestParameters` and would need to have the argument value and any categories specified.
* Change each of the three combining strategies to make use of the new class when creating test cases, applying any categories found.
* Change `CombiningStrategyAttribute` to make use of the new class and pass it on to the strategy.

Personally, I don't think it gives enough benefit to warrant the work.

**Comment by jnm2** [comment]
Yes, let's close this. If someone is motivated to implement the above API, we can discuss at that time.
