### ISSUE TITLE
Description or AttributeUsage issue

### ISSUE THREAD

**Issue by awattar** [nunit/nunit#2636]
https://github.com/nunit/nunit/blob/4e6f838a767abf1e18b35fafe3a385817ac19efe/src/NUnitFramework/framework/Attributes/SetUpAttribute.cs#L42

Description states that "Attribute used to mark a class that contains one-time SetUp" but AttributeUsage has AttributeTargets.Method value.

**Comment by mikkelbu** [comment]
If you look at the current version of the code 
https://github.com/nunit/nunit/blob/e465d6966971cdcdd7859439902707e2c56414cb/src/NUnitFramework/framework/Attributes/SetUpAttribute.cs#L25-L35
The the comment has been changed to reflect the usage. This happened as part of #2178
