### ISSUE TITLE
ValuesAttribute causes ExpectedResult to have no effect

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2639]
As part of fixing #2630, I copied many tests from TestCaseAttributeTests to ValueAttributeTests and had to remove them again because they failed.

https://github.com/nunit/nunit/blob/c79e1c0a49c6c7fe1b2f895116ba02d93d0fe91e/src/NUnitFramework/tests/Attributes/TestCaseAttributeTests.cs#L400-L404

When translated to ValuesAttribute:

```cs
[Test(ExpectedResult = 4)]
public double? CanConvertIntToNullableDouble([Values(2)] double? x, [Values(2)] double? y)
{
    return x + y;
}
```

Gives:

> Method has non-void return value, but no result is expected

Looks like a bug to me. Does everyone agree?

**Comment by mikkelbu** [comment]
I agree. It looks like a bug.

**Comment by CharliePoole** [comment]
Here's the problem...

TestAttribute is ignored as far as building a test goes unless it's the only test-building attribute present. In this situation, NUnit adds an invisible CombinatorialAttribute to the method. The result is that a parameterized test using parameter attributes cannot have an expected result. This has always been the case.

**Comment by jnm2** [comment]
That makes sense. Should we give a more gelpful error message then, any time TestAttribute.ExpectedResult is used and there are child tests?

**Comment by CharliePoole** [comment]
I think it's stronger than that, now that I reflect on it. It a test method has a return value, it's an error to use data attributes on the parameters. So the error message was correct, but just not clear enough.

**Comment by jnm2** [comment]
Cool, and what about TestAttribute.ExpectedResult with multiple test cases?

**Comment by CharliePoole** [comment]
Of course, `TestAttribute` never generates multiple test cases. It either generates one test case or zero. When it's used with `TestCase`, `TestCaseSource`, `Values`, `Random`, etc. it doesn't generate any test cases.

Problem is, the user (like you) might expect the `ExpectedResult` to apply to every test case just as we do for `Description`, `Author`, etc. in `ApplyToTest`. I think what we should do is deal with `ExpectedResult` in `ApplyToTest` as well, marking the test as invalid if an `ExpectedResult` is provided for a test with parameters. That would allow us to give a very clear error message.

**Comment by jnm2** [comment]
I like it. To make the first error message stronger, whose responsibility should it be to determine whether an attribute is a data attribute?

**Comment by CharliePoole** [comment]
Attributes tell us that by implementing an interface. The test case builder simply calls all those that are data attributes. But the TestAttribute doesn't need to know if there are other attributes. It only needs to know whether the method has parameters. If so, it can't be used to create a test for that method (it's only a marker) and therefore any ExpectedResult is invalid.

THat's as I would do it, anyway. There's a more complicated way where you let the expected result be used when combined with TestCase or TestCaseSource but not with parameter values. I think that's both silly (What's the point of expecting the same result from every case) and potentially confusing to users. Saying "You can't use TestAttribute.ExpectedResult on a method parameters"is pretty clear and tells the user what to do.

**Comment by jnm2** [comment]
Oh, right! I was thinking that would block TestCaseAttribute.ExpectedResult, but of course it wouldn't.

**Comment by CharliePoole** [comment]
Interesting. We actually have a test that verifies the value of ExpectedResult is ignored in a similar circumstance to this issue...

https://github.com/nunit/nunit/blob/master/src/NUnitFramework/tests/Attributes/TestExpectedResult.cs#L53

**Comment by jnm2** [comment]
Can we make that test invalid instead of letting it pass with the test cases' expected results? Seems like a better guardrail.

**Comment by CharliePoole** [comment]
My point exactly.
