### ISSUE TITLE
3.9 Release is missing the framework dll build artifact

### ISSUE THREAD

**Issue by kaylanimis** [nunit/nunit#2646]
When attempting to get the latest version dlls from [the release page](https://github.com/nunit/nunit/releases/tag/3.9) I noticed that the only available downloads are the nupkg and source code. In [3.8.1](https://github.com/nunit/nunit/releases/tag/3.8.1) there's a separate zip available with the framework dlls already pre-packaged. I haven't been able to find any issues ([release issue](https://github.com/nunit/nunit/issues/2540)) or documentation saying that the project was discontinuing support for the non-nuget installation route as documented [here](https://github.com/nunit/docs/wiki/Installation). 

Please let me know if something has changed or it was just an oversight that affects the rare few of us who don't use nuget.

**Comment by rprouse** [comment]
It was definitely an oversight on my part, sorry. Unfortunately I don't have a copy of the ZIP to upload. As a workaround, download `NUnit.3.9.0.nupkg` and change the extension to `NUnit.3.9.0.zip`. The NuGet package is just a ZIP file and contains nearly everything that the ZIP would have although with a slightly different layout.

I am going to leave this open and assign to the 3.10 milestone to ensure it doesn't happen again. Interestingly though, you are the first to notice which is a testament to NuGet being the default for downloading libraries. How times have changed in a few short years!

**Comment by kaylanimis** [comment]
No problem, thanks for the quick response

**Comment by jnm2** [comment]
I noticed but I thought it was intentional. Sorry!

**Comment by jnm2** [comment]
@rprouse @MattGen [asked on Gitter](https://gitter.im/nunit/nunit?at=5a54d6eece68c3bc7498e03f) whether it was necessary to build from source to use NUnit in a Unity project. I don't think Unity provides any NuGet integration from the quick searching I did. I think the presence of the usual .zip download might have resolved the confusion.

I'm open to trying the release procedure for the first time, building 9b2159fccd35a0895ea937517170d3b4ecece815 and uploading the zip (and NUnitLite nupkg), unless you'd prefer to.

**Comment by rprouse** [comment]
When @OsirisTerje did the latest adapter release we discovered that GitHub releases no longer allow uploading NuGet packages, only ZIP files, so we will need to zip of rename to upload now.

**Comment by ChrisMaddock** [comment]
We should keep the zip - do we need to upload the NuGet packages here too, or could we just point to nuget.org?

There’s a site that tells you the number of downloads for each release atrifact somewhere isn’t there...would be interesting to see how often the nupkgs are downloaded directly from github.

**Comment by jnm2** [comment]
I've just uploaded a nupkg as a GitHub release binary: https://github.com/jnm2/nunit/releases/tag/uploadtest

**Comment by rprouse** [comment]
@jnm2 that is weird, maybe it is size related or bad network connection? @OsirisTerje kept getting errors.

@ChrisMaddock we like to have backup copies of files that we upload, but I agree that the NuGet packages don't necessarily need to be in the release. I keep a copy of everything backed up in OneDrive. It used to be in the website, but now the site is hosted by GitHub we can't, so I need to come up with a better solution.

**Comment by rprouse** [comment]
@ChrisMaddock looking at the downloads from the GitHub releases, the NuGet files get between 3,000 and 6,000 downloads and the ZIP files get 11,000 to 23,000. The ZIP is clearly well used but still pales in comparison to downloads from NuGet.org which are up to 1,674,949 for a single version. We could drop the copy of the NuGet packages from the release, but the ZIP is widely used enough that I would like to keep it.

**Comment by ChrisMaddock** [comment]
Wow! I was expecting it to be under 100!

Totally agree about keeping the zip - that's important for a number of situations. Sounds like there might not be an issue with continuing to upload the nupkg's anyway. 😄

**Comment by rprouse** [comment]
I will test when I do this release and keep uploading whatever I can. I should also go back to the GitHub blog and see what I can find. I think @OsirisTerje found a reference to it this week.

**Comment by rprouse** [comment]
Everything else is closed for the 3.10 release, so I am going to begin compiling it. It should be out in the next day or so. I will close this issue once I do the release as I see what I can upload and what restrictions there are. I will update the release notes as appropriate.

**Comment by rprouse** [comment]
The release is currently blocked on a decision on https://github.com/nunit/NUnit.StaticExpect/issues/5. @nunit/framework-team can you take a look and comment please?

**Comment by rprouse** [comment]
I had no trouble uploading the ZIP files or the NuGet packages. The errors we were seeing were probably transient network errors. Closing.
