### ISSUE TITLE
[Improvement] Missing short constraint for Throws.ArgumentOutOfRangeException 

### ISSUE THREAD

**Issue by TobiasSekan** [nunit/nunit#2650]
Hello,

it is possible to add a short constraint for **ArgumentOutOfRangeException**

```
Throws.ArgumentOutOfRangeException
```

so it can be used direct

```
Assert.That(delegate, Throws.ArgumentOutOfRangeException)
```

I use NUnit 3.9.0

**Comment by mikkelbu** [comment]
Hi @TobiasSekan. The shortest I can think of is `Assert.Throws<ArgumentOutOfRangeException>(delegate)`.

**Comment by TobiasSekan** [comment]
Yes I know, but it would be nice, when it is possible to write it with a short constraint

**Comment by mikkelbu** [comment]
Ok. I misunderstod what you meant by "short constraint" 😄 . I don't have any strong opinion about this except that I would mind if we had to support too many types of Exceptions like this.

**Comment by ChrisMaddock** [comment]
This is why c# needs extension _properties_. 😄 

There's also:
```
Assert.That(delegate, Throws.TypeOf<ArgumentOutOfRangeException>());
```
but I get that's not really what you're after. 

I agree with @mikkelbu - I'm not totally keen on adding more specific exceptions, as I'm just not sure where we'd stop! I can't see any clear selection criteria in what we currently have though...

**Comment by CharliePoole** [comment]
@ChrisMaddock Right... lots of people methods rather than properties in their fluent designs for exactly that reason. I didn't because I disliked seeing `()` everywhere.

What I've frequently done is to create my own class, inheriting from NUnit. Like...

```C#
public class Throws : NUnit.Framework.Throws
{
    public static ExactTypeConstraint ArgumentOutOfRangeException
    {
        get { return TypeOf<System.ArgumentOutOfRangeException>(); }
    }
}
```

Sometimes it takes a bit of fooling around with using statements to get it to work - depending on the namespace in which you define it.

**Comment by rprouse** [comment]
Like others on the team, I am reluctant to add too many specific exceptions. They syntax that is available is only a few more characters to type, even less with Intellisense, so I am going to close this one as won't fix. We appreciate the idea, but need to balance convenience with keeping the API footprint manageable. Adding this adds one more thing to the intellisense dropdown making the others harder to find. It is a slippery slope.
