### ISSUE TITLE
NuGet package links to outdated license

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2656]
https://github.com/nunit/nunit/blob/a8e36883aed269ce352328eb3e64d31ba7c7204a/nuget/framework/nunit.nuspec#L9

https://github.com/nunit/nunit/blob/a8e36883aed269ce352328eb3e64d31ba7c7204a/nuget/nunitlite/nunitlite.nuspec#L9

http://nunit.org/nuget/nunit3-license.txt:

> Copyright (c) 2015 Charlie Poole

Is this URL a good place to maintain the license into the future or should we use https://github.com/nunit/nunit/blob/master/LICENSE.txt?

**Comment by ChrisMaddock** [comment]
I agree project specific makes more sense, now different projects are copyrighted in different ways.

**Comment by jnm2** [comment]
I don't really know what the pros and cons are, but what do you think of linking the GUI version instead of the raw version? https://github.com/nunit/nunit/blob/master/LICENSE.txt

**Comment by rprouse** [comment]
Interesting question. The raw version is our license, whereas the GUI version is GitHub's interpretation of our license. Their interpretation is correct and I think it adds value, but does linking to that imply acceptance of GitHub's interpretation? Anyone have opinions or experience? The lawyer in me would say that we should link to the raw version, the dev to the GUI version. 

Please note, **I am not a lawyer**, I only play one in issue comments 😄

**Comment by ChrisMaddock** [comment]
>The lawyer in me would say that we should link to the raw version

I am also not a lawyer, and accordingly would keep a licence as simple as possible. 😄

**Comment by jnm2** [comment]
Good point. Raw sounds safest.

**Comment by ChrisMaddock** [comment]
This needs to be done in many projects. 😞 

Cloning it to just the console for now, so we can get it in the next release.
