### ISSUE TITLE
PR labels

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2658]
I think we've talked about adding some to keep track.

I have a PR which has been waiting for a review to unblock it for a full month. I think there are others as well. For the sake of awareness, keeping things from staying blocked, can we add and apply these labels?
(PRs left unlinked to avoid spamming.)

<kbd>needs:work</kbd>
Blocked until the contributor responds to team's request for changes.
(Currently: 2104, 2181, 2453, 2520, 2578)

<kbd>needs:review</kbd>
Blocked until an additional team member reviews.
(Currently: 2538)

<kbd>needs:help</kbd>
Blocked until a team member can answer an implementation question.
(Currently none)

<kbd>needs:discussion</kbd>
Blocked until the team comes to consensus on a design question.
(Currently: 2509, 2513, 2597, 2652, 2657)

Not sure how to categorize 2640 but since it's active, I'm not worried about categorizing it.

**Comment by ChrisMaddock** [comment]
Sounds good to me.

Suggestions: can we add waiting-on-ci, and merge the middle two into a more general 'needs-team-input'? I feel like there's four states - waiting-on-contributor, waiting-on-team, waiting-on-ci, and ~~wait-what-are-we-actually-doing-here~~ waiting-on-discussion.

**Comment by jnm2** [comment]
I like `waiting-on-` more than `needs:`. It's clearer.

I wish we didn't need a `waiting-on-ci` tag in the first place. :-( But until that's solved, the tag is a good idea.

**Comment by mikkelbu** [comment]
I agree with @ChrisMaddock, but do we really need a `waiting-on-ci` tag? Can't we just see the status from the PR overview page (I doubt that we soon will get more than 20-25 PR active at the same time. Of course we will not have the filtering, but I'm not sure we will need it).

**Comment by CharliePoole** [comment]
Who is the audience for these labels. I think what is needed may differ depending on whether you are aiming at NUnit users, devs or the project lead. For example, starting from the original problem articulated by @jnm2, who is supposed to notice this and do something about it?

Personally, I have two different mental models in this situation, depending on the structure of the project I'm working on: If it's fairly centralized, it's up to the lead to control all this stuff, in which case I'd let the lead decide what is needed to highlight it. OTOH, on a more decentralized project, I'd figure it's up to me as the developer to designate reviewers, nag them, etc. 

@jnm2 What I'm getting to here is that I doubt whether labels, by themselves, will cause anyone to review your PR. 😞 I wonder if there is really a "system" solution to this problem or if you don't simply have to deal with it case by case.

**Comment by ChrisMaddock** [comment]
@mikkelbu - good point!

I think labels will help keep tabs. On this repo, it’s common to have 15 or so open PRs, and now and then I’ll end up going through each one individually, and working out what needs to be done.

**Comment by rprouse** [comment]
I like the idea. I saw the same in the .NET Core docs repo which has a high volume of PRs, many of which are blocked waiting on feedback or changes. If they are properly used, it would make it much easier to scan the list of PRs and see what needs attention. It will only work if we update the labels though. An `awaiting:work` will only be useful if team members remove the tag when the work is complete. 

Rather than `needs` or `waiting-on`, how about `awaiting`?

Rather than `work`, maybe `response` which would cover awaiting any type of response from the submitter?

And instead of `help`, maybe `feedback`?

In the interest of being agile, let's try this on one repo (this one) and see how it works. We can revisit in a month or two and decide if we should continue using the labels, improve on the idea, or drop it.

**Comment by jnm2** [comment]
@CharliePoole I agree. It doesn't preclude the chance that I'll have to continue to try to entice another framework member to review. What I think labels might do is save our mental CPU cycles figuring out the status of each PR and lower the barrier to any team member dropping in and pushing things along. Looking at an untagged list of a dozen PRs is a bit opaque. If they were tagged, at least the status of each would make an impression and make it more likely that you might come back later and take action.

`awaiting:` seems good.  I think it should be `awaiting:contributor-response` because it's also possible to be awaiting a team response. Also: what if the contributor did respond via comment but hasn't started the work? In that case, it could be `awaiting:contributor`.

Attempting to merge all of our ideas:

<kbd>awaiting:contributor</kbd>
<kbd>awaiting:team</kbd>
<kbd>awaiting:discussion</kbd>

What do you think?

Keeping the PR labels up to date is not free of course, but I was thinking that the labels' information would be read by us many more times than it is updated by us.

Another side benefit to the  `awaiting:contributor` tag is that the contributor will see the tag and know that we haven't noticed their response and will ping us. [Instead of this happening.](https://github.com/nunit/nunit/pull/2493#pullrequestreview-88669009)

**Comment by ChrisMaddock** [comment]
These look good to me. I think this will also be clearer to our contributors of what we consider the status, which is a good thing.

**Comment by rprouse** [comment]
I have created the labels as per @jnm2's last comment plus `awaiting:review` and applied labels to all PRs except for one that is awaiting CI. Scanning the PR list does seem easier now, but the proof will be in the team being diligent updating the labels. Let's give this a month or two and re-evaluate how it is going. I am going to close this issue, any team member may bring it up again if they don't feel this is working.

**Comment by jnm2** [comment]
Question for discussion: since these new awaiting labels are at the top of the select list for all issues, people will try to use them when they think they are applicable. Should we embrace this? Either way, we should document it somewhere. I can document once we decide.

**Comment by rprouse** [comment]
I am okay with including on other issues where it is warranted. Maybe for confirm issues where we have asked for feedback? Right now I ask for feedback and if I don't get it, close in a few weeks, but it is tedious rescanning.

**Comment by jnm2** [comment]
How does this proposed addition to https://github.com/nunit/docs/wiki/Issue-Tracking look?

-----

#### PRs and issues that need attention

The goal with these is to keep team members from having to do tedious rescanning to figure out the state of each long-lived PR or issue in a list and also to increase awareness.

- **awaiting:contributor**
  Blocked until the contributor responds to team's request for changes.
- **awaiting:team**
  Blocked until the team comes to consensus on a design question.
- **awaiting:discussion**
  Blocked until an additional team member reviews.
- **awaiting:review**
  Blocked until a team member can answer an implementation question.

-----

**Comment by CharliePoole** [comment]
Are these the names we are trying out now? Two are of the form awaiting:SOMEBODY and two are awaiting:SOMETHING, which seems weird.

Also do we intend that awaiting:Discussion should mean waiting for a review and and awaiting:review should mean waiting for the answer to a question? Why don't we name them as what they mean in that case?

**Comment by ChrisMaddock** [comment]
@jnm2 I think you've got your lines in the wrong order - but if you mean the order I think you mean, they look good to me! 😄

**Comment by jnm2** [comment]
😂 I fixed the order! Sorry!

I [edited them a little](https://github.com/nunit/nunit/issues/2658#issuecomment-359141847) to differentiate them from each other, too.

@CharliePoole It's interesting that you point that out. I think it's okay.

**Comment by jnm2** [comment]
@CharliePoole It's interesting that you point that out. In all cases we are waiting for people, but `awaiting:discussion` and `awaiting:review` are more specific than `awaiting:team` (people + activity).

**Comment by CharliePoole** [comment]
It makes a bit more sense now that the definitions match up.

**Comment by rprouse** [comment]
Looks good. Ship it 😄

**Comment by jnm2** [comment]
Closed in https://github.com/nunit/docs/wiki/Issue-Tracking/9c5eb7681fe78472fde505d42e9ab0a90b1486bc.
