### ISSUE TITLE
NullReferenceException after parallel tests have finished executing

### ISSUE THREAD

**Issue by sanoursa** [nunit/nunit#2662]
Using NUnit 3.9.0, we have enabled `Parallelizable(ParallelScope.Fixtures)`, and while the tests all run correctly, about 30% of the time the test suite fails because NUnit's background thread throws a NullReferenceException with the following stack:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object. at 
NUnit.Framework.Internal.Execution.WorkItemQueue.get_IsEmpty() at 
NUnit.Framework.Internal.Execution.WorkShift.get_HasWork() at 
NUnit.Framework.Internal.Execution.ParallelWorkItemDispatcher.SelectNextShift() at 
NUnit.Framework.Internal.Execution.ParallelWorkItemDispatcher.OnEndOfShift(WorkShift endingShift) at 
NUnit.Framework.Internal.Execution.WorkShift.<StartWorkers>b__26_1(TestWorker s, WorkItem ea) at 
NUnit.Framework.Internal.Execution.TestWorker.TestWorkerThreadProc() at 
System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at 
System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at 
System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) at 
System.Threading.ThreadHelper.ThreadStart() 
```

Is this a known issue? Is there anything I can do to gather more information to help diagnose the problem?

**Comment by jnm2** [comment]
Huh, thought that stack trace was one of the two fixed in 3.9 by https://github.com/nunit/nunit/issues/2428.

**Comment by sanoursa** [comment]
@CharliePoole I tried the latest package from the dev feed, and still hit the same exception. Is there any extra logging that I can enable to help diagnose this?

Also I've noticed that I hit the exception very reliably on a machine with 4 cores, and very infrequently on a machine with 2 cores.

**Comment by CharliePoole** [comment]
It's tricky because we end up with a list of queues that includes null values. That causes an exception much later but I can't see how it happens.

**Comment by sanoursa** [comment]
I'm still trying to understand the code, but is it possible that there's a race between WorkItemQueue.Save() calling InitializeQueues(), and the background thread calling IsEmpty?

While InitializeQueues is in progress, _innerQueues is in a state where some its items can be null. If anything tries to access _innerQueues during that time, it could definitely hit this issue.

What if InitializeQueues is updated to create a new ConcurrentQueue in a local variable, and only assign it to _innerQueues once it's been fully initialized?

**Comment by sanoursa** [comment]
I'm testing out that theory now and I'll report back on the results. I have a very reliable repro, so if you have any other theories you'd like to test out, I'd be happy to try those too.

**Comment by sanoursa** [comment]
So far, so good. I've done several test runs on both 2 CPU and 4 CPU machines, with no hits on this exception so far. I've scheduled 10 more runs, so I'll check on the results in the morning and, if all goes well, I'll send you a PR with my fix.

**Comment by sanoursa** [comment]
Thanks for taking my PR! How soon do you think we will get this fix in an official release?

**Comment by jnm2** [comment]
Here's the milestone: https://github.com/nunit/nunit/milestone/34

 If you need an immediate workaround in a project, you can merge this with your project's nuget.config and upgrade NUnit to version [3.10.0-dev-05190](https://ci.appveyor.com/project/CharliePoole/nunit/build/3.10.0-dev-05190/artifacts) or later:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="NUnit MyGet" value="https://www.myget.org/F/nunit/api/v3/index.json" />
  </packageSources>
</configuration>
```

@rprouse Are you still thinking Feb 28?

**Comment by jnm2** [comment]
GitHub's not smart enough to recognize `Fixes issue #` like it does with `Fixes #`. 😄 Closed in https://github.com/nunit/nunit/commit/d355ad21f45b8b77afe28d7ac25c7a7de4b91e5a via https://github.com/nunit/nunit/pull/2668
