### ISSUE TITLE
Building NUnit .NET 4.5 in VS2017 fails

### ISSUE THREAD

**Issue by OmicronPersei** [nunit/nunit#2663]
>6>------ Build started: Project: nunit.framework.tests, Configuration: Debug Any CPU ------
6>nunit.framework.tests -> C:\GitRepos\nunit\bin\Debug\net45\nunit.framework.tests.dll
6>C:\Users\wheel\.nuget\packages\microsoft.bcl.build\1.0.21\build\Microsoft.Bcl.Build.targets(243,5): error : Could not locate C:\GitRepos\nunit\src\NUnitFramework\testdata\packages.config.  Ensure that this project has Microsoft.Bcl.Build installed and packages.config is located next to the project file.
6>Done building project "nunit.testdata.csproj".

However, the solution as a whole reports building having succeeded:
>========== Build: 6 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**Comment by jnm2** [comment]
Can reproduce with a fresh clone. It appears the error is cosmetic but I'd like to better understand it.

**Comment by jnm2** [comment]
I expect this is just naiveté on the part of the Microsoft.Bcl.Build package targets, attempting to be a useful diagnostic.

When building from the command line:

> Target "BclBuildValidateNugetPackageReferences" skipped, due to false condition; ('$(BclBuildRunningFullBuild)' != 'true' AND '$(SkipValidatePackageReferences)' != 'true' AND '$(BuildingInsideVisualStudio)' == 'true') was evaluated as ('true' != 'true' AND '' != 'true' AND '' == 'true').

**Comment by jnm2** [comment]
Yep, confirmed: https://github.com/NuGet/Home/issues/2913

**Comment by jnm2** [comment]
The source code is not available for the offending ValidatePackageReferences task in Microsoft.Bcl.Build.Tasks.dll. (https://blogs.msdn.microsoft.com/bclteam/p/bclbuild/)

I propose the same thing I see at https://github.com/NuGet/Home/issues/2913#issuecomment-239181431: skip the target by adding `<SkipValidatePackageReferences>true</SkipValidatePackageReferences>`.
