### ISSUE TITLE
Differentiate between test case Timeout and test Timeout

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#267]
There is significant inconsistency in the current Timeout attribute results.  Timeout is currently applied to the entire test case : SetUp+Test+TearDown.  However, if a timeout does occur, the results are unpredictable depending on where in the process it actually occurs.  Each of the three pieces (five if BeforeTest and AfterTest actions are included) can be run completely, partially, or not at all.

It seems like there need to be two different timeouts, with different result guarantees.

The first would be the current "test case" timeout (specified by the Timeout attribute, or from the command line -timeout), which would encompass all phases of the test case, but would guarantee no specific result.  When the timeout occurred, a failure would be reported, but there would be no attempt to complete any remaining phases of the test.

The second would be implemented similarly to the current Assert.Throws and Assert.That ... Throws constraints.  There would be an Assert.TimesOut (timeout, delegate) and an Assert.DoesNotTimeOut (timeout, delegate) assertion, and a TimesOut (timeout) and a DoesNotTimeout(timeout) constraint.

This would allow the exact timeout condition to be tested, and other assertions to be made before and after the timeout (including other Timeout), in the same fashion as currently happens with exceptions.  This would also allow a guarantee the all SetUp and TearDown actions would occur even if there is a timeout.

**Comment by CharliePoole** [comment]
Last discussion of this was in 2014.
