### ISSUE TITLE
NUnit puts in \r\n into Expected (expectedMessage)

### ISSUE THREAD

**Issue by sllewellyn13** [nunit/nunit#2676]
When I log my exceptions, as I always do, in my JSON results file, I see:  Expected: True\r\n  But was:  False\r\n"

Would this be an NUnit problem or a Newtonsoft JSON file?

**Comment by sllewellyn13** [comment]
Here is what the JSON looks like:
`{
  "results": "results"[
  {
    "ID": "9046",
    "Title": "Verify NGTS Server ESD1WBOLYNGTD01 responds to pings.",
    "_Result": "FAIL",
    "Tags": "NGTS,Dev1",
    "Subsystem": "NGTS",
    "Info": "Configuration system failed to initialize"
  },
  {
    "ID": "9046",
    "Title": "Verify NGTS Server ESD1WBOLYNGTD01 responds to pings.",
    "_Result": "FAIL",
    "Tags": "NGTS,Dev1",
    "Subsystem": "NGTS",
    "Info": "  Expected: True\r\n  But was:  False\r\n"
  }
]
}`

**Comment by sllewellyn13** [comment]
Here is the C# code that logs the exception. It is WriteResult that writes the JSON part.
`catch (Exception exc)
                {
                    string msg = exc.Message;  // bug in Exception: NUnit puts in Expected: true \r\n but was false \r\n
                    Log(msg);
                    Log(exc.StackTrace);
                    errorInfo = exc.Message;
                    trc.WriteResult(this as BaseTest, testCaseID, title, Resources.TestResultFail, tags, subsystem, errorInfo);
                    Assert.IsTrue(false);
                }`

**Comment by CharliePoole** [comment]
NUnit error messages often include newlines as defined on the platform. If you don't want them in your log, you would have to strip them.

**Comment by rprouse** [comment]
@sllewellyn13 Nunit will continue to include newlines in messages. They are most often consumed on the console or in a UI where the newlines are useful. We also do not produce JSON results, so you could change it when they are serialized to JSON. May I ask what you are using to produce the JSON results?

I am going to close this issue as won't fix. Feel free to add comments, we will see them.

**Comment by sllewellyn13** [comment]
That'll be fine. I found a way to handle it in my json result logger
