### ISSUE TITLE
A catch block with Exception does not cause test to fail.

### ISSUE THREAD

**Issue by sllewellyn13** [nunit/nunit#2677]
I put all my tests in a try/catch block. I have a situation where my tests are always ending in a try/catch block because of a problem with my System.Configuration. I have to add the line:
Assert.IsTrue(false); 
in the catch block in order to get NUnit to mark the test as failed.

**Comment by jnm2** [comment]
An example would help narrow down what we're talking about. It sounds like you're saying this doesn't work?

```cs
try
{
    // Do something unreliable that might cause a ConfigurationException
}
catch (ConfigurationException)
{
    Assert.IsTrue(false); // Or Assert.Fail();
}
```

I must be missing something about the issue you're having, because I'd replace that with this code:
```
// Do something unreliable that might cause a ConfigurationException
```

**Comment by CharliePoole** [comment]
IF you don't catch the exception, your test will give an Error result rather than a Failure result. Does the difference matter to you?

**Comment by mikkelbu** [comment]
I am closing this because it has been inactive for so long. If anyone has further info, we can reopen.
