### ISSUE TITLE
Deprecate the DebugWriter class

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2680]
Followup from https://github.com/nunit/nunit/issues/1944

> The class should probably be removed at some point as we don't use it.

I'd like to either do that or remove the Compact Framework comment.

https://github.com/nunit/nunit/blob/194f38ac43b8f129c2cc96d5d62ef964936f6f25/src/NUnitFramework/nunitlite/DebugWriter.cs#L30-L35

**Comment by CharliePoole** [comment]
I haven't used it for a long time! I used to do it in my nunitlite self-executing tests once in a while. Removing it of course risks breaking someone who has found it and used it.

**Comment by stevenaw** [comment]
Would deprecating this via the obsolete attribute be desired? If so, this could be a `good first issue`

**Comment by jnm2** [comment]
That sounds good to me.

**Comment by jnm2** [comment]
That sounds good to me. @nunit/framework-team?
