### ISSUE TITLE
Provide a Testing approach for reference equality types

### ISSUE THREAD

**Issue by pandualuvala** [nunit/nunit#2683]
We are constantly working on integration testing and had to test Images and Bitmaps. Since bitmap's have a reference equality we had to convert them into byte format and compare the underlying bits. But can we have  any other approach for testing reference equality types.

**Comment by jnm2** [comment]
There are multiple things that can be tested about bitmaps beyond their pixel data, such as EXIF tags or embedded color profiles. I'm not sure there is a single clear way to handle images in general. Besides System.Drawing, there are also images in libraries like SharpDX or SkiaSharp which NUnit wouldn't be able to help with.

What I've done for pixel data in my own projects is build my own `Constraint` class and use `Assert.That(actual, MyConstraints.HasSamePixelData(expected))`.

**Comment by pandualuvala** [comment]
Thank you for your response. Yes we are also testing the pixel data. But just wanted to know if we can have this pixeldata as an extension method for testing images in nunit. I don't know if that is possible i am just trying to understand more.

**Comment by jnm2** [comment]
I'm not opposed to adding something like `Has.SamePixelData`; we do have filesystem assertions. Usually the team decides that new things along these lines belong in a community additions library, but there is none. We also want to be careful that when you type `Has.`, you don't have to look through too many things. Perhaps another @nunit/framework-team member can give their thoughts.

**Comment by CharliePoole** [comment]
IMO, having domain-specific extensions is out of scope for NUnit. Our job should be to make it relatively simple for other people to create such things.

Currently, you could handle this in two ways: a custom constraint or a custom comparer. 

Custom comparers have the advantage that they may (depending on implementation) be independent of any particular nunit framework version, while custom constraints are not. OTOH, custom constraints provide a more integrated API.

**Comment by ChrisMaddock** [comment]
I agree - this sounds like a great use case for custom constraints.

**Comment by rprouse** [comment]
I also agree. This usage is fairly edge case for widespread use, but simple for you to write once for your team and reference in your test projects. I am going to close this and leave it to you write your own custom comparer or constraint. If you need any help, just ping us on the mailing list.
