### ISSUE TITLE
Remove Resharper .DotSettings and Rebracer file in favour of .editorconfig

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#2685]
We currently have three different files providing formatting guidelines - which I don't believe are all maintained.

The most recent work has been done in .editorconfig, I believe. Do we have any need to maintain all three files, or could we remove the Rebracer and ReSharper options?

I'd like to apply the same change to both the nunit and nunit-console repo's, if we can make a decision.

**Comment by rprouse** [comment]
Agreed. Rebracer isn't needed in VS 2017 which is now required to build so can be dropped. We also haven't updated Resharper in years other than your automatic changes.

**Comment by jnm2** [comment]
I was just looking at that. I think we should remove them but be open to adding *minimal* ReSharper settings back in to quiet down ReSharper's default complaints in our codebase for things that .editorconfig doesn't control yet.

**Comment by ChrisMaddock** [comment]
That sounds like a good idea to me. 😄

**Comment by zastrowm** [comment]
Note that ReSharper also has support for configuring it via .editorconfig: https://www.jetbrains.com/help/resharper/EditorConfig_Index.html

**Comment by ChrisMaddock** [comment]
Thanks @zastrowm!

Looks like we've made a decision. Should anyone new to contributing fancy picking this up, to clarify, the task is to remove the Rebracer.xml and NUnit.sln.DotSettings files from the repository. Pull Requests Welcome!

**Comment by pandualuvala** [comment]
Can i take this task please let me know. Thanks

**Comment by ChrisMaddock** [comment]
Yes please @pandualuvala! 😃 let us know if we need to clarify anything.

@nunit-team: I can’t remove the helpwanted label on my phone - would appreciate if someone else could now this issue is claimed.

**Comment by OsirisTerje** [comment]
@ChrisMaddock I think it is wise to keep the resharper file there, with "the minimal settings to quiet it down", as you mentioned above.  Otherwise anyone using resharper will very soon do refactorings based on those complaints to the code base, and you will have very intensive pull requests. 
(cc: @pandualuvala )

**Comment by ChrisMaddock** [comment]
My concern was that the resharper settings are probably out of sync with the editorconfig settings. If we think that we still need them, then I guess we should go through and work out what we can remove, and what’s being delegated to editorconfig.

@pand - ok, in that case, can you just remove Rebracer.xml for now? Looks like we’ll need to look at the ReSharper file in more detail. 🙂

**Comment by pandualuvala** [comment]
@ChrisMaddock @OsirisTerje Thanks will do that.

**Comment by pandualuvala** [comment]
can we close this issue?. The PR for this issue is already merged however we are still discussing about resharper settings. Please check Thanks.

**Comment by mikkelbu** [comment]
I agree with @pandualuvala. I've create #2693 for the comments from @ChrisMaddock about resharper settings.

**Comment by ChrisMaddock** [comment]
Thanks @mikkelbu and @pandualuvala! Sorry, I've missed a few notifications over the last few days!
