### ISSUE TITLE
Assert.Throws swallows console output

### ISSUE THREAD

**Issue by roman-turovskyy** [nunit/nunit#2688]
```
[TestFixture] // NUnit ver. 3.9
public class IssueTest
{
    [Test]
    public void AssertThrowsConsoleIssue()
    {
        Console.WriteLine(1);
        Assert.Throws<Exception>(() =>
        {
            Console.WriteLine(2);
            throw new Exception("test");
        });
        Console.WriteLine(3);
    }
}
```

I expect an output to be

```
1
2
3
```

But in reality it is

```
1
3
```

From my investigation `Assert.ThrowsAssync()` does not have described issue, only `Assert.Throws()` has.

Original question on stackoverflow: https://stackoverflow.com/questions/48453402/nunit-assert-throws-swallows-console-output

**Comment by CharliePoole** [comment]
@roman-turovskyy Thanks for filing this.

@nunit/framework-team I knew what this was immediately (see explanation in SO question) so I'll grab it and fix. I'll take a look to see if we are throwing anything else away at the same time.

**Comment by CharliePoole** [comment]
@roman-turovskyy Can you give us a real use case for wanting to preserve the output?

**Comment by roman-turovskyy** [comment]
@CharliePoole, in my use case I have an integration test on top of Entity Framework 6 with SQL statements logging to Console enabled. This is a negative test, and a final call to `dbContext.SaveChanges()` attempts to insert a duplicate value in a table. `Assert.Throws()` verifies this behavior. I was surprised not to see an SQL statement that caused an exception in console output. Actually it is not a big deal for me to see this output, I just was confused what was going on - exception is present but according to logs nothing special happened. It took me some time to figure out that `Assert.Throws()` prevents logs from outputting to Console. I didn't find this behavior documented and assumed that this might be a bug.

**Comment by CharliePoole** [comment]
Sounds like we should add some info to the documentation as it applies to other things like assert counts, warnings, etc. - things that are only present in test code.

However, I think we should fix this since it presents the least surprise and because it's more consistent. Without the fix, error and progress output continue to appear while standard output does not.
