### ISSUE TITLE
Ensure that resharper settings are consistent with the editorconfig configuration

### ISSUE THREAD

**Issue by mikkelbu** [nunit/nunit#2693]
In #2685 @ChrisMaddock wrote

> My concern was that the resharper settings are probably out of sync with the editorconfig settings. If we think that we still need them, then I guess we should go through and work out what we can remove, and what’s being delegated to editorconfig.

So this issue is about making sure that the resharper settings are up-2-date with respect to our editorconfig configuration.

**Comment by lasthero** [comment]
Just to clarify (sorry if I missed anything): is this issue just about removing NUnit.sln.DotSettings file?

**Comment by mikkelbu** [comment]
No. The issue is about making sure that the resharper settings are up-2-date with respect to our editorconfig configuration. For instance we have in the editorconfig `csharp_space_after_cast = false` which ma

**Comment by rprouse** [comment]
All yours @lasthero. Let us know if you need help.

**Comment by lasthero** [comment]
Sorry one more thing to clarify - from my research the editorconfig will override settings at DotSettings by default. If that's the case do we still need to sync them?

**Comment by jnm2** [comment]
IIRC that is recent, and people sometimes use older versions of ReSharper.

**Comment by lasthero** [comment]
@jnm2 Thanks for your reply and sorry for not replying sooner...
Is there resource out there that I can see the mappings between these 2 files?

**Comment by jnm2** [comment]
@lasthero Other than https://www.jetbrains.com/help/resharper/EditorConfig_Properties.html and https://www.jetbrains.com/help/resharper/Using_EditorConfig.html, I don't know.
