### ISSUE TITLE
TimeoutAttribute disabled for .net Core

### ISSUE THREAD

**Issue by y6nH** [nunit/nunit#2701]
In commit ea983b8, the Timeout attribute for tests and fixtures was removed for .net Core projects. I don't think this is documented anywhere but the commit message. Could you add a note to the wiki page, and give an indication of whether it's going to be reinstated?

**Comment by ChrisMaddock** [comment]
I think this is covered between https://github.com/nunit/nunit/issues/1638 and https://github.com/nunit/docs/issues/236. We'd welcome contributions and pull requests on both issues!

**Comment by ChrisMaddock** [comment]
I added a note to timeout attribute anyway - as one of the key features missing.

**Comment by y6nH** [comment]
Thanks for the quick response! We'll make do with MaxTime.

**Comment by abbotware** [comment]
https://github.com/abbotware/nunit-timeout  <- look a simple work around!

**Comment by abbotware** [comment]
Not at all.. I just extracted this from my personal code library (hence the boiler plate license)... I am going to change the license to 'open source' permissive one... might even make a nuget out of it ;-)

**Comment by CharliePoole** [comment]
Alternatively, contribute to NUnit via a PR. 😄
