### ISSUE TITLE
Combine "SetUp" and "TearDown" concepts

### ISSUE THREAD

**Issue by julealgon** [nunit/nunit#2705]
Folks, this one probably sounds a bit crazy already to you, so let me try to show you why this is something to at least consider :P
```
[TestFixture]
public class MyFixture
{
    private IStuff _disposableStuff;
    
    [SetUp]
    public SetUp()
    {
        _disposableStuff = new DisposableStuff();
    }
    
    [Test]
    public MyTest()
    {
        ...
        _disposableStuff.DoSomething();
        ...
    }
    
    [TearDown]
    public TearDown()
    {
        _disposableStuff.Dispose();
    }
}
```

In the sample above, notice how we have decoupled methods for creation and disposal of the `IDisposable` object, **which is really bad IMHO.** This basically goes against the intended, modern usage of `IDisposable` instances as it deals with disposal manually instead of using an `using` block. As you can imagine, it is impossible to use a proper `using` scope with methods separated like this.

I remember having nightmares with something very similar to this in unit tests before because of a few of the more strict FxCop warnings on disposables, as it correctly requests that every `IDisposable` be disposed. I always found this mechanism unnecessarily clunky to deal with those guys.

This sounds like a more natural "setup" to me (I've never seen something like this in any test framework):
```
[TestFixture]
public class MyFixture
{
    [SetUpTearDown]
    public SetUp(Action<IStuff> test)
    {
        using (var disposableStuff = new DisposableStuff())
            test(disposableStuff);
    }
    
    [Test]
    public MyTest(IStuff stuff)
    {
        ...
        stuff.DoSomething();
        ...
    }
}
```

Notice how we cleanly create and dispose with an `using` block here, while even removing the state from the class.

I know this is not a complete design proposal and that it would be a big endeavor to implement, but have you ever thought about doing something along these lines?

I'm also fully aware that the code above would clash with the current parameterized test approach using `TestCase`, so it's obviously not something final.

An alternative to this would be to abstract this even further and perform some type of class-level injection, where the `IStuff` would be injected in the fixture and used internally, but disposed outside by another entity that had the same look as the above.

Would love to hear some insights on this.

**Comment by CharliePoole** [comment]
Your idea is a very interesting one, but it seems to me to be one that would play better in the life-cycle of a test framework if it were designed in from the very start. Just my view, of course. but I'd rather apply such ideas in designing a new framework instead of retrofitting them to an existing one. Others may feel differently and you could certainly create a separate, detached fixture object in the way that xUnit does.

In the current design of NUnit, of course, it's the framework's job to ensure that your TearDown method gets called, no matter what happens. It's done in a `finally` block internally. Unfortunately, that's not known to static analyzers.

You do have a better way available if you want to create and dispose of resources at the class level. If your test class implements IDisposable, NUnit will simply call its `Dispose` method at the end.

**Comment by jnm2** [comment]
I never use SetUp or TearDown for the same reason and also because we don't have https://github.com/nunit/nunit/issues/2574. However, I'm okay with it. I think this is a more flexible pattern which encourages people to take more initiative:

```cs
public static class MyTests
{
    private sealed class MyFixture : IDisposable
    {
        public IStuff Stuff { get; }
        public IOtherStuff OtherStuff { get; }

        public MyFixture()
        {
            // Setup
        }

        public void Dispose()
        {
            // Teardown
        }
    }
    
    [Test]
    public static void MyTest()
    {
        using (var fixture = new MyFixture())
        {
            // ...
            fixture.Stuff.DoSomething();
            // ...
        }
    }
}
```

**Comment by CharliePoole** [comment]
Good pattern.

**Comment by rprouse** [comment]
I am closing old uncategorized issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
