### ISSUE TITLE
Properties defined on class on TestContext is not in property-bag.

### ISSUE THREAD

**Issue by antonpavlovname** [nunit/nunit#2709]
Hi dev,
I was trying to use properties of test as described in [https://github.com/nunit/docs/wiki/Property-Attribute](url), but my nint don't see properties, defined on class.
`  Expected: equivalent to < "P1", "P2" >
  But was:  < "P2" >
  Missing (1): < "P1" >
`
[NUnitProperties.zip](https://github.com/nunit/nunit/files/1720639/NUnitProperties.zip)
Example solution is attached, thanks.

**Comment by CharliePoole** [comment]
The test case is a "test" and the test fixture (class) is also a "test" They are two different tests, one contained inside the other. When the code for the test case is executing. It sees its own properties. When the code for the fixture (e.g. OneTimeSetUp) is executing, it will see its own properties. The code for the containing test (fixture) is not visible from the test method.

This has been talked about on many issues. See for example #1396, #2674, #1358, #796, #548. Issue #796 most exactly matches yours so I'm marking this as a duplicate.
