### ISSUE TITLE
NUnitLite --teamcity notifications are redirected to --out file specified.

### ISSUE THREAD

**Issue by hazzik** [nunit/nunit#2710]
If using NUnitLite in combination with `--teamcity` and `--out` options the TC control messages are redirected to the output file. TC listens for the console output, so I believe these messages should still be output to console regardless if we redirect the output to file or not, otherwise TC will never receive the messages.

It could also affect NUnit.Console runner, but I have never checked.

**Comment by jnm2** [comment]
Current code: https://github.com/nunit/nunit/blob/facc4c8ee5c99653accb64acd3026e07f214457a/src/NUnitFramework/nunitlite/TextRunner.cs#L176-L177

**Comment by rprouse** [comment]
Closing, we will be removing NUnitLite TeamCity support in #3759
