### ISSUE TITLE
Nunitlite dll reference issue

### ISSUE THREAD

**Issue by pp1609** [nunit/nunit#2715]
nunit nunit-3.0
I am trying to run the test written in a different dll file and referencing that dll in NUNITLITE test executer project using reflection:

asm = Assembly.LoadFrom(path);
  new AutoRun(asm).Execute(new String[] { "/test:" + ((MenuItem)items[0]).Title + ".StartTest" });
but i am getting TestFixture not found error.

If i am adding the refernce of that dll to the executing assmebly then nunitlite is able to run the test otherwise we are getting above error.

Kindly help .

Thanks.

**Comment by CharliePoole** [comment]
There's a small ambiguity in your explanation. Just to be sure, I understand that you have
1. Created an executable project that references nunitlite.dll
2. Created a separate dll with tests
3. Loaded the test assembly using reflection
4. Passed that loaded assembly reference to NUnitLite

Is that right?

If so, I believe the problem might be your use of `LoadFrom`. Try using `Load`.

**Comment by mikkelbu** [comment]
Closing this, due to the lack of activity.

Happy to reopen if anyone has more to add. 😄
