### ISSUE TITLE
Wrong version information of NUnit 3 in NUnit 2 export format

### ISSUE THREAD

**Issue by Pat781** [nunit/nunit#2721]
Hello,

I'm running NUnit console 3.8 and and NUnit framework 3.9 with the console parameter "format=nunit2".
In the result it prompts me: "environment nunit-version="3.6.0.0""
I feel the version information is misleading.

Regards,
Patrick

**Comment by CharliePoole** [comment]
Confirming this as a bug. The `nunit-v2-result-writer` extension uses its own version as the value of `nunit-version`. Instead, it should be looking at the `environment` element associated with the first assembly and using the value of the `framework-version` attribute.

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit-v2-result-writer #11](https://github.com/nunit/nunit-v2-result-writer/issues/11) via [**ZenHub**](https://www.zenhub.com/)
