### ISSUE TITLE
Nunit 3 multiple categories

### ISSUE THREAD

**Issue by heyitsmesuraj** [nunit/nunit#2722]
In transition from NUnit version 2 to 3, I have a problem to include/exclcude multiple categories. Since, there is an option in NUnit2, where  categories can be declared by comma separator but that cannot be achieved inNUnit3.

In NUnitV3, we have to mention 'cat' every time like
--where "cat != A && cat != B && cat != C  && cat != D && cat != E "

Can we achieve this by comma separator like --where "cat != A ,B,C ,D,E "

Thanks,
Suraj

**Comment by mikkelbu** [comment]
Moved to nunit/nunit-console#378
