### ISSUE TITLE
[Question] [Proposal] Constrain for Array StartWith, EndWith, ContainsArray

### ISSUE THREAD

**Issue by TobiasSekan** [nunit/nunit#2728]
Hello, is there a constrain to test if a array/list

Start with a sequence ?
`Assert.That(new int[0, 1, 2, 3, 4, 5, 7, 8, 9], Does.StartWith(new int[0, 1, 2])) == true`

End with a sequence ?
`Assert.That(new int[0, 1, 2, 3, 4, 5, 7, 8, 9], Does.EndWith(new int[7, 8, 9])) == true`

Contains a sequence (contains exact, not superset or subset or different order) ?
```
Assert.That(new int[0, 1, 2, 3, 4, 5, 7, 8, 9], Does.ContainsArray(new int[3, 4, 5])) == true

Assert.That(new int[0, 1, 2, 3, 4, 5, 7, 8, 9], Does.ContainsArray(new int[5, 4, 3])) == false
Assert.That(new int[0, 1, 2, 3, 4, 5, 7, 8, 9], Does.ContainsArray(new int[1, 5, 7])) == false
Assert.That(new int[0, 1, 2, 3, 4, 5, 7, 8, 9], Does.ContainsArray(new int[10, 5, 20])) == false
```

Best regards

**Comment by jnm2** [comment]
No, I don't think we have these. This is the first time I remember hearing a request for this.

Can you give us a feel for the type of data represented in the lists why you're checking StartsWith, EndsWith and Contains?

**Comment by CharliePoole** [comment]
Odd that I don't see my answer to the question, which I posted when I closed it. Probably because I used my phone... I'll check and re-create if necessary.

**Comment by CharliePoole** [comment]
Well... my comment is nowhere. I'm getting a bit annoyed at OctoDroid!

Anyway...

We have never had constraints or assertions that tread a collection as a sequence. I can well understand that it would be useful in some kinds of apps - in fact I worked on an app that manipulated time series where this would have been perfect.

That said, it feels like a bit of a niche requirement. My suggestion is that you work to develop a set of custom constraints. We can help, of course. That would put us in a position to either leave the feature outside of NUnit or later include it as a standard thing.

IF you do that, I suggest using `Sequence` in all the names - or some other key word that identifies how the collection is being viewed. `ContainsArray` could have several different meanings for anyone who saw it without thinking about sequences.

**Comment by rprouse** [comment]
I also think this is probably a bit too niche to include in NUnit, but that is why it is extensible. As a team, we need to balance how useful a feature is, how widely used it will be and the size of the API. When we add too many options it makes NUnit hard to use and hard to discover features. Thanks for the idea, but I am going to re-close this issue.

@CharliePoole I have stopped using OctoDroid and switched to FastHub for working on the phone. Give it a try.

**Comment by TobiasSekan** [comment]
Okay, thanks for the info
