### ISSUE TITLE
Proposal: Async test case sources

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2729]
For integration tests, it seems almost all of my test case sources would benefit from being allowed to use `await` syntax. I've been converting async code to `.GetAwaiter().GetResult()` every time I move it into a test case source.

These test case sources are following the principle of doing the absolute minimum amount of work needed to discover the correct number and correct display names of test cases before running any tests.
Many of the objects they use to determine the test-discovery data provide no synchronous API.

Since I'm familiar with the async execution parts of NUnit, I'm imagining this would be a few line change (besides the tests) and no maintenance overhead beyond what we're already doing today.

```cs
public static async Task<IEnumerable<TestCaseData>> AllGizmoConfigurations()
{
    var dataController = await base.LoadController();
    return from gizmo in await dataController.LoadGizmos()
           from configuration in gizmo.Configurations.AsIndexed()
           select new TestCaseData(gizmo, configuration.Value)
               .SetName("{m}(" + gizmo.Name + "[" + configuration.Index + "])")
}

[TestCaseSource(nameof(AllGizmoConfigurations))]
public static void Gizmo_configuration_is_valid(Gizmo gizmo, GizmoConfiguration configuration)
{
    // ...
}
```

**Comment by CharliePoole** [comment]
This seems reasonable to me. We should probably have more emphasis in the docs for `TestCaseSource` that people need to do as little as possible in the source method, but that's a separate matter.

Where do you see the design issue?

**Comment by jnm2** [comment]
Hmm, maybe Design was the wrong tag. I forget which to use for discussion now that I don't have ZenHub.

**Comment by CharliePoole** [comment]
Bearing in mind that they can be changed by the team leader and/or the team, here's how I originally set them up.

If you aren't sure whether we want to do something: `is:idea`. I'm pretty sure you're sure. 😄 

If we are sure we want to do it but there are questions to discuss about how to do it __ahead of time__: `design`. This is overloaded and covers UI design, API design and, where necessary, design of the implementation. Unless I'm missing something, you'd just like an async test case source method to work. Right?

I think there are lots of things to discuss if we get into how people ought to write their `TestCaseSource` methods, but none of them would make me want to turn down the feature. 

Your statement about having the source do as little as possible makes perfect sense and it's what we want users to understand as well.

**Comment by jnm2** [comment]
Right! I guess I don't need a label to fill the gap of the Discussion pipeline.

Well, cool! Should I assign myself to indicate that this issue has been accepted by the team, or use a priority label?

**Comment by rprouse** [comment]
I also think this would be a great enhancement. So much code is async these days. I am going to switch this since I don't see any objections.

**Comment by stevenaw** [comment]
I like this idea a lot myself and had a need for it recently.
Would it make sense to also make this work it for ValueSource and TestFixtureSource for consistency?

**Comment by manfred-brands** [comment]
I noticed that we have quite some inconsistencies between the three `...Source` attributes. It would be good to align them so that at least the discovery is only coded in one place.
