### ISSUE TITLE
Add License Header Manager to project

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#2730]
License Header Manager is a Visual Studio extension that allows you to easily insert our standard license header into files. Not everyone needs to use it, but if they do, it will make their lives easier. https://github.com/rubicon-oss/LicenseHeaderManager

This needs us to add a `.licenseheader` file to the solution. See https://github.com/rubicon-oss/LicenseHeaderManager/wiki/License-Header-Definitions

**Comment by jnm2** [comment]
I'm happy with this for the time being. I have been sitting on an analyzer that's almost finished that would do the same thing but since it's not a VS extension, it'll work in VS Code and any other C# IDE.

**Comment by rprouse** [comment]
@jnm2 maybe use `.licenseheader` for your analyzer so that projects can switch easily?

**Comment by mikkelbu** [comment]
@rprouse Is this still relevant with the recent changes and the addition of `file_header_template` to the .editorconfig

**Comment by rprouse** [comment]
No, thanks for pointing it out. Closing.
