### ISSUE TITLE
It's unclear how [NonParallelizable] and --process=Multiple work together

### ISSUE THREAD

**Issue by JPAhnen** [nunit/nunit#2731]
I upgraded to NUnit 3.9 and the latest Console Runner and noticed a huge increase in test time.
Before the upgrade it was NUnit 3.5 with Console 3.6.1.

I upgraded to use the `[NonParallelizable]` attribute, and now it seems the `--process=Multiple` is ignored.
We test around 33 assemblies, and before the update in took about 5 Minutes to complete.

I added the `[NonParallelizable]` to about 4 Fixtures only.

Now it takes 12 Minutes. The duration of each assembly is nearly identical as before.
If I sum up the duration of each assembly it's about 12 Minutes which seems that the assemblies aren't running in parallel anymore.

I'm note sure if this is a bug but maybe some issues with the tests?

Here is the reason why I upgraded in the first place:
We have tests that call a specific method which should not be called from multiple processes (which is only the case when testing) at the same time. These tests are in different assemblies, so I added the `[NonParallelizable]` attribute to the 4 fixtures containing these tests in the hope they would not get executed in parallel, but the other tests should as before.

**Comment by CharliePoole** [comment]
Attributes you use on tests have no relationship to how processes are run. If you have two methods in different processes that can't be run together then you simply can't run those processes at the same time.

If you want NUnit to control how two tests relate (parallel or not) then they have to be in the same test assembly.

Otherwise, you must control which processes run in parallel.

My guess is that you are running into a bug in the 3.8 console runner. What is your command-line?

**Comment by JPAhnen** [comment]
I call it from TeamCity with `--process=Multiple --skipnontestassemblies` which results in (from the BuildLog):

`Starting: "D:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe" "D:\Program Files (x86)\TeamCity\buildAgent\temp\buildTmp\FB8Fs08JpuxvwIEFm4hTQ318tqZprhDs.nunit" "--result=D:\Program Files (x86)\TeamCity\buildAgent\temp\buildTmp\FB8Fs08JpuxvwIEFm4hTQ318tqZprhDs.nunit.xml" --noheader --where cat!=ReviewTest --framework=net-4.0 --process=Multiple --skipnontestassemblies "--explore=D:\Program Files (x86)\TeamCity\buildAgent\temp\buildTmp\4BEbzyjJLJFYRXoc74A1lfmhxUYtgF93_all.tests"`

Befoer updating the console runner, I upgraded the project to NUnit 3.9 and the test duration was as before.

**Comment by CharliePoole** [comment]
Teamcity creates an NUnit project file. There is a known bug with the 3.8 console runner only running one process at a time when using an NUnit project.

I can't easily find the bug on my phone, but you can search in the nunit-console issues.

**Comment by mikkelbu** [comment]
nunit/nunit-console#382 is probably the issue that @CharliePoole is refering to.
