### ISSUE TITLE
TestCase Object Parameter

### ISSUE THREAD

**Issue by FabioMorcillo** [nunit/nunit#2732]
Hi,

How i can create TestCase with object parameter ?

Example:

        [Test]
        [TestCase(null)] <-- Work
        [TestCase(new User() {})] <-- I need this :)
        public void Valid_User(User user)
        {
            // Arrange

            // Act

            // Assert
        }

Thank you,

**Comment by jnm2** [comment]
@FabioMorcillo Since C# is very restrictive on what metadata can be encoded as an attribute value, we have [an alternative solution](https://github.com/nunit/docs/wiki/TestCaseData) where you use `TestCaseSource` attribute.

**Comment by rprouse** [comment]
I am closing as a question. If you need more help, post here, we will see it even though it is closed.
