### ISSUE TITLE
On an ignored test (using ignore attribute), [TearDown] isn't being called

### ISSUE THREAD

**Issue by ocmyhome** [nunit/nunit#2736]
On an ignored test (using Ignore attribute), [TearDown] isn't being called after the test run.  the [TearDown] method resides in a base class which is inherited by the [TestFixture] class.  Some insight would be helpful.

[Test]
[Ignore("TestRail ignore testing")]
public void TestRail_Ignore()
{
        Assert.IsTrue(true);
}

NUnit = 3.9.0
NUnit.ConsoleRunner = 3.8.0
NUnit3TestAdapter = 3.9.0

**Comment by CharliePoole** [comment]
If a test is ignored, it isn't run. That means none of its `SetUp` or `TearDown` methods are called. It wouldn't make sense to set up to run a test that is ignored... and even less to tear down that non-executed setup.

Is it possible you are doing something that belongs in a `[OneTimeSetUp]` or `[OneTimeTearDown]` method?

**Comment by ocmyhome** [comment]
Thanks @CharliePoole for the explanation.

We've integrated our test framework with TestRail.  Via TestRail's api, it lets us create test runs, test cases, and set results on tests.

We currently have the TestRail client being created in a constructor on the base class, then in the [TearDown] we implemented the logic to log the results of the test to TestRail, using the TestContext.  We'd want to submit this "Ignored" status to TestRail as well.

Any suggestions on how to accomplish this would be appreciated...

**Comment by rprouse** [comment]
I don't think any of the team has experience with TestRail. My first thought is that it would be better to import the `TestResult.xml` file which includes all information rather than log out each test result. You will need to talk to TestRail about how to do that.

**Comment by CharliePoole** [comment]
@ocmyhome It generally works best if tests are just tests and test management / reporting is done someplace else. In the case of NUnit 3, that someplace else is the test engine, which runs and reports on tests. The engine supports extensions and you could write one (specifically a TestListener extension) that captures every test result and sends it to the TestRail client. That would take all the code to manage the tests out of your test assembly itself. It would live in an extension that you would have to maintain separately.

**Comment by ocmyhome** [comment]
Thanks for the replies.  I'll see what I can figure out!
