### ISSUE TITLE
Any interest in a roslyn analyzer library?

### ISSUE THREAD

**Issue by JohanLarsson** [nunit/nunit#2738]
Check things like that parameters matches what is provided in `[TestCase]`, count & type.

**Comment by ChrisMaddock** [comment]
Very much so!

We have a start at https://github.com/nunit/nunit.analyzers. There's a lot of ideas and potential for this project, and lot's still to be written - contributions are very welcome! @mikkelbu's heading up the effort there. 

Personally, I'd love to see these packaged with the main library at some point - I think they could be a big game-changer.

**Comment by rprouse** [comment]
There is interest and work is underway, so I am going to close this issue. If you have specific ideas or want to contribute, head over to the analyzer repo. Thanks for showing interest, it helps us prioritize.
