### ISSUE TITLE
Set order for testcases

### ISSUE THREAD

**Issue by rutin31** [nunit/nunit#2747]
Hello,
I have the following configuration:
[Test]
[TestCase(a)]
[TestCase(b)]
[TestCase(c)]
public void Test1(int i)
{}

[Test]
[TestCase(a)]
[TestCase(b)]
[TestCase(c)]
public void Test2(int i)
{}

Is there a way to run the tests in order:
1.test1-testcase(a)
2.test2-testcase(a)
3.test1-testcase(b)
4.test2-testcase(b)
5.test1-testcase(c)
6.test2-testcase(c)

thank you

**Comment by jnm2** [comment]
As far as I know there is currently no way to make one test wait to start executing until a specific other test is finished. See https://github.com/nunit/nunit/issues/2521#issuecomment-370090334.

**Comment by rprouse** [comment]
The only thing I can think of is to switch to using a `TestFixuture` attribute and use the `Order` attribute for the tests. Something like this,

```C#
[TestFixture(1, 1)]
[TestFixture(2, 2)]
[TestFixture(3, 3)]
public class OrderedTests
{
    int _x1;
    int _x2;

    public OrderedTests(int x1, int x2)
    {
        _x1 = x1;
        _x2 = x2;
    }

    [Test]
    [Order(1)]
    public void TestOne()
    {
        // Use _x1 in tests
    }

    [Test]
    [Order(2)]
    public void TestTwo()
    {
        // Use _x2 in tests
    }
}
````

I am closing this as a question. Hope this helps.
