### ISSUE TITLE
When i try to run Specflow feature files i am getting "A Project with an Output Type of class library cannot be started directly " Error

### ISSUE THREAD

**Issue by Aboppudi21** [nunit/nunit#2750]
HI all,

I am getting "A Project with an Output Type of class library cannot be started directly " Error when i try to run speflow feature file or when i try to use start button in Visual studio 2017
I am using Specflow with Nunit  and to solve this i followed the details at "http://erraticdev.blogspot.co.uk/2012/01/running-or-debugging-nunit-tests-from.html" but i couldnt find nunit.exe file to specify the path at "start external program" but i found Nunit Console runner  , when i try to point the path of "nunit3-console.exe" and run my feature file then i am seeing outout message as below
The program '[14256] nunit3-console.exe: Program Trace' has exited with code 0 (0x0).
The program '[14256] nunit3-console.exe' has exited with code -4 (0xfffffffc).

so please give me the appropriate solution to solve this problem

thanks
Anusha

**Comment by rprouse** [comment]
Please redirect this question to SpecFlow at https://github.com/techtalk/SpecFlow. Most of the NUnit team does not use SpecFlow.
