### ISSUE TITLE
NuGet props causes MSBuild < 15 to fail

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2753]
MSBuild older than v15 will crash because we don't declare an XML namespace:

https://github.com/nunit/nunit/blob/36f193c13e86acab35f5c685f60a32f1ed71e8a5/nuget/framework/NUnit.props#L1

This is causing @marcelopontipedra these errors:

![image](https://user-images.githubusercontent.com/9210581/37318681-c94aa314-26a6-11e8-9fda-035a143426fd.png)
![image](https://user-images.githubusercontent.com/9210581/37318702-eeeb31c4-26a6-11e8-83ba-5df325be1236.png)

Change was made in https://github.com/nunit/nunit/pull/2594.

I wonder how hard it would be to set up an integration test against MSBuild 4.0.

**Comment by rprouse** [comment]
Please branch off the release branch, preferably the 3.10 tag and update the version to 3.10.1 if you can. If not, I will clean up and re-release as quickly as possible.

**Comment by jnm2** [comment]
@rprouse Already up: https://github.com/nunit/nunit/pull/2754

**Comment by jnm2** [comment]
Did you want to merge into `master` even though I based it on `release`?

**Comment by jnm2** [comment]
I don't want to get in your way now if you're working on it. It's based on release/v3.10, but maybe I misunderstood which branch you wanted to merge into? Easy to switch:

![image](https://user-images.githubusercontent.com/8040367/37319360-2d4f61ea-2645-11e8-94f0-69c9ee5d6200.png)

**Comment by rprouse** [comment]
Looks good, I want it to go into release for now. I will figure out getting it into master from there.

**Comment by marcelopontipedra** [comment]
Does the v3.10.1 release will be automatically available on the Nuget.org?

**Comment by jnm2** [comment]
@marcelopontipedra Yes, it will be up very soon.

**Comment by marcelopontipedra** [comment]
Thank you :)

**Comment by rprouse** [comment]
@marcelopontipedra I have uploaded 3.10.1. You should see it very soon. Can you give it a test and let us know if it works for you?

**Comment by marcelopontipedra** [comment]
It's now available. installing....

**Comment by marcelopontipedra** [comment]
I'm not sure on this, but I'm trying to make my Test adopter work. I'm building the test but no test available.. 
![image](https://user-images.githubusercontent.com/9210581/37321573-e4f6c6da-26b3-11e8-9e1f-f5fbb94f8748.png)

**Comment by marcelopontipedra** [comment]
I think it's already working. Thanks :)

**Comment by jnm2** [comment]
Thanks for letting us know!
