### ISSUE TITLE
How to send result file after all tests run

### ISSUE THREAD

**Issue by rutin31** [nunit/nunit#2769]
Hi,
Is there a way to send a mail with result file (I set this file in console command with option --result)
after running.
The result file was created after OneTimeTearDown function.
If sending an e-mail into OneTimeTearDown function - the result file comes incomplete

**Comment by CharliePoole** [comment]
The result file is only created by the console runner after the tests have run. To email it, you would need to add code in script that runs the console runner.

**Comment by ChrisMaddock** [comment]
Closing this, as I think the questions answered. Feel free to comment further if not, the team will still get the notifications. 🙂
