### ISSUE TITLE
Add FQN attribute to tests

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#2770]
Working with the Visual Studio Test team, the new source based discovery would be much more reliable if we could provide a standardized and predictable fully qualified name to the various test runners. We've met with the maintainers of the other .NET Test frameworks and agreed on a standard. We could recreate this information in the adapter, but we have all of the information required in the framework, so it would be much more efficient to create the FQN here and add it as an attribute to the test's XML node in `Test.PopulateTestNode`.

If @nunit/framework-team members would like to see or comment on the spec, contact @rprouse.

**Comment by jnm2** [comment]
I would like to see it (without slowing you down)—https://github.com/orgs/nunit/teams/framework-team discussions can be private to the @nunit/framework-team if desired...?

**Comment by CharliePoole** [comment]
This seems like a mistake to me. The FQN is a VS concept and only applies to VS. As documented, it's a simple combination of items already provided by NUnit, so it's reasonable to implement it in an adapter.

Let's imagine some other runner - not VS - that wants to be provided with some other field they need to identify tests. Options would then be (1) add that to NUnit as well, (2) tell them to conform to what VS does or (3) create an adapter (or have them create it) for their purpose. The third is what makes sense to me.

Anyway, the draft definition of FQN is only now out for review, so I would expect implementation to wait for that to be final.

**Comment by jnm2** [comment]
If FQN is a standard that more than one test running GUI (which can jump to source) would be interested in, implementing it in the framework makes sense. So long as FQN stays a VS-only concept, would we be open to pushing it into the VS adapter and just making sure that the framework provides any extra information the adapter needs to build the ideal FQN?

**Comment by jnm2** [comment]
It's plausible in my mind that a standardized FQN+test case ID is something we should be pushing for all runners and all test frameworks to use rather than relying on idiosyncratic knowledge of how to translate each test framework's results. Seems like NCrunch and ReSharper and any GUI that navigates to source would prefer this. Having some common exchange format for any kind of .NET test would make life easier, wouldn't it?

**Comment by CharliePoole** [comment]
Yes. And if we were to work cooperatively with other frameworks to establish that standard, I'd personally join the effort. That's not what's happening right now. MS is leading an effort to standardize to some extent how adapters work. I think it's great that they are doing that and I joined it for my TestCentric project.

But making it into a standard for __frameworks__ rather than adapters is a really big leap. It would be a bigger effort and would need different leadership and membership.

That's not to say a common adapter interface couldn't lead eventually to something more. It might. But that's only something that will happen over time.

**Comment by jnm2** [comment]
Yes. Besides framework maintainers we'd also need the maintainers of framework-agnostic runners to make sure the FQN format makes sense for them, right?

My initial thought was that we could optimistically push forward with FQN in the framework in hopes that more runners start using it. What I'm hearing is, until someone shows up to lead that conversation, you'd rather not do anything towards that end?

**Comment by CharliePoole** [comment]
Doing something in the hopes that others will follow you is using your market power to impose a standard. That's not in sync with my personal values, so I wouldn't favor doing it. As a framework developer, such an approach would make me want to stay away from it as well, so I assume that a good portion of other framework devs would react the same way.

Doing what you think is best and pressuring others to follow is the approach that got the adapter community into the pickle it's now in. You'll hear that from others than just me. So, no, it's not the path I'd __like__ to see the NUnit Project follow. That said, I'm not one of those who will be making the decision for you...

BTW, I suggested exactly the approach you are talking about - go ahead and try to develop something that others would take as a standard - about eight years ago. It's a natural thing to do if you believe you know the right way to go. I got talked down from that position by a third-party developer who pointed out that an NUnit standard was not one others would be likely to follow.

**Comment by CharliePoole** [comment]
@jnm2 FYI the MS effort involves __adapter__ developers, who in our case also happen to develop the framework. There are others who adapt frameworks they didn't write.

**Comment by ChrisMaddock** [comment]
Just got round to reading this spec.

One question - we already supply methodname and classname in the test-case xml. As far as I can see - the FQN is just sticking those together, and adding some extra formatting - so it seems it would be entirely duplicating existing information in the framework xml?

Based on that, building the FQN seems like much more natural fit in the adapter to me. If we were starting from scratch, I'd be open to adopting the FQN standard as our way of providing this information, but given we already have the methodname and classname attributes, and backwards-compatibility to think about, I'm less keen on the duplication.

>  **it would be much more efficient** to create the FQN here [...].

Objection! As someone who rarely uses the adapter, any work done solely for the adapter in the framework is an inefficiency for me. 😄 Am I missing a complexity here that makes this significantly more sensible to implement at the framework level?

**Comment by CharliePoole** [comment]
@ChrisMaddock I second that last (even if I'm repeating myself).

Also, consider that we __added__ the class and method names to the framework __in order to support__ the generation of FQN in the first place.

**Comment by rprouse** [comment]
My comment that it was more efficient to implement here was based on a previous spec for the FQN than the one that I sent you for which we did not have the information we needed in the adapter. If all of the information is available now, then it might belong in the adapter.

**Comment by CharliePoole** [comment]
@rprouse Let's imagine that the "recipe" for the FQN that Microsoft wants is some particular function of four atomic pieces of information, which are available in the framework. Let's further imagine that only two of them are currently available in the XML.

That would give us the choice of adding two more pieces of info to the XML and having the adapter calculate the FQN or calculating the FQN within the framework. In that (imaginary) scenario, I'd argue that the former is the better course of action.

Why...

1. By definition these are atomic pieces of information, independent of one another. If VS needs them, then somebody else is likely to. We should expose, just as we exposed class and method names, which were needed by VS but potentially useful to others as well.

2. If we publish the four atomic pieces of info, then the framework needs to know that this is info it should publish. If we publish the FQN, then the framework needs to know about the four pieces PLUS the rules for how they are combined to satisfy VS. Those rules are not general, but are particular to VS and the VS adapter. I think that the framework needing to know something that belongs to the adapter is a design smell.

**Comment by rprouse** [comment]
Agreed, closing this issue. Now that it is done in the adapter, there is no need for it here.
