### ISSUE TITLE
SynchronizationContexts and awaiting

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2774]
Going for a high-level view. I've been talking about finishing off the async PR for too long. I'm going to spend some time in airports/planes tomorrow and do a fresh spike. The PRs can be small and incremental, tackling a section at a time.

I'll be eager for any @nunit/framework-team comments on any part, though I know this is not most people's favorite thought experiment. 🙃 If you get a chance, please especially glance at the ❔s.

### Specially-recognized synchronization contexts

If `SynchronizationContext.Current` is an instance of `WindowsFormsSynchronizationContext` (Windows Forms control has been created) or `DispatcherSynchronizationContext` (WPF), NUnit should not call `.Wait()` on async methods or delegates or there will be a guaranteed deadlock. This is https://github.com/nunit/nunit/issues/2123. Sam ran into this a couple days ago. I've been making my test methods non-async and using [this workaround](https://gist.github.com/jnm2/4643df73fdda0efe1df3a03ad0188c46) for a long time.

### Default synchronization contexts

If `SynchronizationContext.Current` is null or an instance of `SynchronizationContext`, and the current apartment state is STA, we should install our own [`SingleThreadedSynchronizationContext`](https://github.com/nunit/nunit/issues/1200#issuecomment-312120851). Otherwise, awaits will continue on non-STA threads. This is https://github.com/nunit/nunit/issues/1200.

❔ Should we consider always installing a `SingleThreadedSynchronizationContext` so that all awaits in test methods and delegates keep continuing on the original thread, even if it isn't STA? If people don't like this, they can use `.ConfigureAwait(false)`. (You do have a habit of using that, right? 😉)

### Custom synchronization contexts

❔ Should we create a framework extension point so that people can override the waiting logic with custom code? Say, for example, some custom native message loop like certain DirectX libraries ship?
Probably not unless asked, but we would want to do this internally to some extent and make our four SynchronizationContext strategies pluggable.

### Fallthrough

In all other cases, we have no option but to block-wait. If continuations need to be pumped, there's no way NUnit can pump them and the tests will deadlock. If on the other hand they are scheduled on threadpool threads, they'll execute off-thread and finally complete the async task. This is what we currently do in all cases.

### Fallthrough—awaitable spec

This is https://github.com/nunit/nunit/issues/2286.

❕ Instead of `.Wait()`, we should be using `.GetAwaiter()`, checking `awaiter.IsCompleted`, then creating a ManualResetEventSlim, passing its Set method to `awaiter.UnsafeOnCompleted` if it implements ICriticalNotifyCompletion and `awaiter.OnCompleted` otherwise, and block-waiting on it. Finally, we call `awaiter.GetResult()`. (This is straight from the C# 5 spec and has not changed since.)

If the awaitable object's type is known to be `System.Threading.Tasks.Task`, we can use its internal shared ManualResetEventSlim by skipping the IsCompleted and OnCompleted parts of the protocol and going directly to `GetResult()`. This optimization is only valid on `System.Threading.Tasks.Task` since awaiters in general are not contractually obliged to block-wait in GetResult.

**Benefits:**

 - Exception and cancellation handling are higher-fidelity with the awaitable API than with the TPL API. For example, `Task.Wait()` unconditionally wraps the exception in AggregateException.
 - We light up support for `ValueTask` and any other awaitable type besides `Task`.

**Comment by sharwell** [comment]
The two default synchronization contexts (forms and dispatcher) should cover majority use cases. Single threaded should be limited to STA or you run a risk of deadlock in existing test suites. Extensibility shouldn't be actively blocked, but realistically it can come later if/when we have a better understanding of special needs.

**Comment by jnm2** [comment]
@sharwell Do you know of an example where a single-threaded synchronization context (using the implementation above) can produce deadlocks on non-STA threads? I've been using it in heavily multithreaded production console apps and should fix it if that is a possibility.

**Comment by ChrisMaddock** [comment]
>I'll be eager for any @nunit/framework-team comments on any part, though I know this is not most people's favorite thought experiment. 🙃 If you get a chance, please especially glance at the ❔s.

Afraid this is _way_ out of my field of knowledge, so afraid I have nothing useful to contribute! 😆

**Comment by jnm2** [comment]
😃 Not a problem, Chris!

**Comment by jnm2** [comment]
Note to self: next time, make sure VS doesn't require a check for an updated license token *before* leaving internet behind. I'm slower than I expected without Roslyn (VS code wouldn't boot it up).

**Comment by jnm2** [comment]
@sharwell I see [your comment](https://github.com/sharwell/gitextensions/commit/6ad3fab061aa37498b06e963dbb786a405bb7f4d#r28267301) about `JoinableTaskSynchronizationContext`. The current plan is that we'll block by calling `Task.GetAwaiter().GetResult()` (for non-Task awaitables, blocking on an MRES set with OnCompleted).

If blocking will cause you a deadlock, the only thing that occurs to me is adding the custom extension point I mentioned. You'd implement [`MessagePumpStrategy`](https://github.com/nunit/nunit/pull/2776/files#diff-308ac1319e4d291401e5ccd48a2b3651R38) and probably specify your implementation via an attribute. (Is 'message pump' appropriate terminology? I'm leaning more towards `AwaitStrategy`.)

**Comment by jnm2** [comment]
I might optimistically pipeline the next two PRs. :D

**Comment by sharwell** [comment]
> Do you know of an example where a single-threaded synchronization context (using the implementation above) can produce deadlocks on non-STA threads?

Sure, this is easy:

```csharp
[Test]
public void PleaseDoNotDeadlockMe()
{
  Func<Task> asyncPortion = async () => await Task.Yield();
  asyncPortion().GetAwaiter().GetResult();
}
```

**Comment by sharwell** [comment]
@jnm2 Since tests aren't reentrant, tests using vs-threading shouldn't cause any special problems aside from the ones you are already covering.

**Comment by sharwell** [comment]
> `GetResult()` always deadlocks with a single-threaded message pump

Yes, but there is no single-threaded message pump in an MTA test so it's fine there.

**Comment by jnm2** [comment]
Blocking a thread still seems to me like a code smell that people would avoid regardless of the thread apartment, but your conflicting expectation is enough evidence that it's safer to post continuations to a single thread only for STA.

**Comment by jnm2** [comment]
White rewriting tests today, I discovered that Application.Exit() appears to uninstall the WindowsFormsSynchronizationContext. I'll have to make sure it gets put back.
