### ISSUE TITLE
File type not supported (.nunit) when using --inprocess

### ISSUE THREAD

**Issue by tom-dudley** [nunit/nunit#2778]
### Environment
- `NUnit.ConsoleRunner 3.8.0`
- `NUnit.Extension.NUnitProjectLoader 3.5.0`
- Windows

Note: both packages are `nuget install`'d to the same directory
### Behaviour
* Running `nunit3-console.exe tests.nunit` starts all tests in the test assembly
* Running `nunit3-console.exe tests.nunit --inprocess` gives the error
```
1) Invalid : C:\Users\foo\tests.nunit
File type is not supported
```
* Running `--list-extensions` in both cases tells me (among other output)
```
Extension Point: /NUnit/Engine/TypeExtensions/IProjectLoader
  Extension: NUnit.Engine.Services.ProjectLoaders.NUnitProjectLoader
    FileExtension: .nunit
  Extension: NUnit.Engine.Services.ProjectLoaders.VisualStudioProjectLoader
    FileExtension: .sln .csproj .vbproj .vjsproj .vcproj .fsproj
```

### Expected Behaviour
Tests should run in both cases

### tests.nunit content
Here is the content of `tests.nunit`
```
<NUnitProject>
<Settings activeconfig="active" appbase="C:\dev\Bar\bin"/>
    <Config name="active">
        <assembly path="C:\dev\Bar\bin\Bar.dll"/>
    </Config>
</NUnitProject>
```

It seems as though the error message is a bit of a red herring given that in both cases the extension is apparently installed.

This might be purely a `nunit-console`\engine issue, in which case feel free to move it!

**Comment by tom-dudley** [comment]
Bah. Definitely should have search harder before submitting (especially to the right repo!)

This issue a duplicate (and independent confirmation of) https://github.com/nunit/nunit-console/issues/386.

**Comment by CharliePoole** [comment]
Thanks for confirming!
