### ISSUE TITLE
How to raise the tests execution performance (NUnit 3.9)?

### ISSUE THREAD

**Issue by victorklimkovich** [nunit/nunit#2782]
Hi there!

Until recently, we used in our project NUnit 2.6, and a couple of days ago we moved to the NUnit 3.9. However, despite the fact that now the unit tests are performed in parallel and not sequentially as before, we see almost no performance gain. All the builds are done on a separate build server using Teamcity 10. Different settings for agents and workers number don't affect the result. Perhaps we have missed something? Tell me please, what should we try to reduce tests execution time?

Thank you.

**Comment by ChrisMaddock** [comment]
Some starting questions: 😄 

- How many assemblies are you running, just one at a time?
- What have you done to parallelise your tests? Have you added a ParallelizableAttribute?
- What makes you sure they're running in parallel? Running with `--trace:Debug` will help with that - take a look at the produced log and see if your tests are running interleaved or not
- Is CPU power definitely your limiting factor? Not memory, or disk speed?

**Comment by victorklimkovich** [comment]
Thank you for responding to my post.
I will try my best to answer your questions..

_1. How many assemblies are you running, just one at a time?_
There are 17 test assemlies in our project. As I understand, by default they all running together using nunit3-console runner.

_2. What have you done to parallelise your tests? Have you added a ParallelizableAttribute?_
For each test assembly the [assembly: Parallelizable(ParallelScope.Fixtures)] attribute was set.

_3. What makes you sure they're running in parallel? Running with --trace:Debug will help with that - take a look at the produced log and see if your tests are running interleaved or not._
Certainly, the tests run simultaneously now, because we had to fix some errors caused by access to shared resources (initially, we did not take this into account, since the tests worked consistently).

_4. Is run-speed definitely your limiting factor? Not memory, or disk speed?_
As far as I know, our build server has about 10Gb of free physical memory and the SSD HDD with enough of free disk space, so it is very unlikely that the problem is related to the hardware.

**Comment by jnm2** [comment]
If you had 17 test assemblies which were already running in parallel, I wouldn't expect to see much benefit until the end where there are only one or two assemblies left running. So long as the console runner is running an assembly for each core, you're pretty much maxed out already.

**Comment by jnm2** [comment]
The biggest win for me with fixture- or especially test-case-level parallelization was when I would selectively run or debug tests; I wouldn't have to wait for each test case to run sequentially.With integration tests this can mean the difference between seconds and minutes of waiting for the development feedback.

**Comment by victorklimkovich** [comment]
**jnm2**, in other words, we should not expect a decrease of test execution time in comparison with the initial non-parallel version?

**ChrisMaddock**, maybe you have any thoughts on this matter or maybe you need some more information?

**Comment by ChrisMaddock** [comment]
It’s really totally dependent on your machine resources, and the contents of your test assemblies.

Take a look at machine resources while running the NUnit 2 tests. Is CPU already maxed out? Or does a particular assembly take up most of the run time? Is there a memory limitation instead, perhaps?

I think this is one you’ll need to dig into a little yourself to get some answers - I can’t think of much more we can help in terms of general advice, I’m afraid.

**Comment by jnm2** [comment]
@victorklimkovich Right. Knowing nothing else about your tests, I would expect either no difference or a slightly better average time as you indicated.

**Comment by ChrisMaddock** [comment]
Closing this, as there's not enough information to understand/reproduce the problem. 

Happy to reopen if anyone has more to add. 🙂
