### ISSUE TITLE
[SetUp] not being picked up

### ISSUE THREAD

**Issue by pedrokarsan91** [nunit/nunit#2784]
I have installed NUnit 2 Test Adapter on Visual Studio 2017 Community Edition
I have NUnit v2.6.3 installed in the class library

When I run tests it does not reach [SetUp]

I have another project that has the exact same thing but works just fine.

**Comment by ChrisMaddock** [comment]
Hi @pedrokarsan91 - the repository is for the NUnit 3 framework. I'll move your issue over to the NUnit 2 Test Adapter repo, for someone there to comment on.

**Comment by ChrisMaddock** [comment]
Issue moved to [nunit/nunit-vs-adapter #168](https://github.com/nunit/nunit-vs-adapter/issues/168) via [**ZenHub**](https://www.zenhub.com/)
