### ISSUE TITLE
Build fails (nunit 3.10.1)

### ISSUE THREAD

**Issue by mogikanin** [nunit/nunit#2787]
We've got an build error on our build server.

```
 (Rebuild target) (12) ->
(ImplicitlyExpandNETStandardFacades target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\Micro
soft.NET.Build.Extensions.NETFramework.targets(65,5): error MSB4062: The "NETBuildExtensionsError" task could not be lo
aded from the assembly C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\Microsoft.NET.B
uild.Extensions\\tools\net46\Microsoft.NET.Build.Extensions.Tasks.dll.  Confirm that the <UsingTask> declaration is cor
rect, that the assembly and all its dependencies are available, and that the task contains a public class that implemen
ts Microsoft.Build.Framework.ITask.
```

Nunit 3.9.0 worked fine. Also with 3.10.1 build works fine if we build project in Visual Studio, but doesn't work if we build it via cmd script.
The cmd script is quite simple:
```
%MsBuild% solutionfile.sln /t:Rebuild /p:Configuration=Release;TargetFramework=v4.6.1
```

**Comment by jnm2** [comment]
What does your project's `<TargetFramework>` or `<TargetFrameworks>` element contain, and what is the MSBuild version?

**Comment by mogikanin** [comment]
Ah, the error occurred when we updated Moq from 4.7.145 to latest 4.8.2.
We updated two libraries together, and I didn't notice it, With nunit everything is OK. I'll post the same bug to Moq repo.

**Comment by ChrisMaddock** [comment]
Thanks for feeding back @mogikanin
