### ISSUE TITLE
Removing ITypeInfo abstraction

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2790]
It appears that both NUnit's code and the ITypeInfo abstraction itself are tightly coupled to `System.Type`.
This does not appear to have the potential to be an area of volatility, so the abstraction appears to be pure overhead. That's definitely the feeling I get each time I've worked with it. It's not useful for cross-platform BCL differences since we use extension methods in namespaces for that.

How bad of a change would it be to remove TypeWrapper and ITypeInfo and run directly against the reflection API?

**Comment by ChrisMaddock** [comment]
Was this maybe originally added for the PCL build? 😕 @rprouse?

**Comment by rprouse** [comment]
Much of that code was to smooth over differences between NET Framework and PCL. I haven't looked since we dropped NET Standard 1.3 how much it is still needed. I guess you'll find out :wink:

**Comment by jnm2** [comment]
I'll take that as a go-ahead for a spike then. :D

**Comment by rprouse** [comment]
Spike away my friend :grin:

**Comment by jnm2** [comment]
All tests are passing!

**Comment by jnm2** [comment]
All tests are passing! Todo:

- [ ] Review my own code, check usings and update copyrights
- [ ] Split into smaller commits

https://github.com/nunit/nunit/compare/jnm2/remove_itypeinfo

**Comment by jnm2** [comment]
So I don't forget: this refactor made it more obvious that we have an issue where the exact same random sequence is used in every derived fixture for test parameters defined in the base fixture.

**Comment by jnm2** [comment]
Even though ReflectedType is deprecated and missing from netstandard1.6, in practice it looks like all the netstandard1.6-compatible platforms do track ReflectedType. Since we only test on platforms that support it, we can't write failing tests on behavior. I'm not so interested in doing anything about it unless that would become possible .
