### ISSUE TITLE
Running NUnit inside sandbox

### ISSUE THREAD

**Issue by andgein** [nunit/nunit#2792]
Hello, I'm trying to run NUnit tests with untrusted code inside sandbox.

Before NUnit v3.5 I used a portable version, which didn't require any special permissions. But there is no portable version now.

I tried to run NUnit 3.10 in the sandbox with following permissions set:
```
permSet.AddPermission(new FileIOPermission(FileIOPermissionAccess.Read, assemblyPath));
permSet.AddPermission(new FileIOPermission(FileIOPermissionAccess.PathDiscovery, assemblyPath));
		
/* Permissions for NUnit: see https://github.com/nunit/nunit/blob/master/src/NUnitFramework/tests/Assertions/LowTrustFixture.cs#L166 for details */
.AddPermission(new ReflectionPermission(ReflectionPermissionFlag.MemberAccess));            // Required to instantiate classes that contain test code and to get cross-appdomain communication to work.
.AddPermission(new SecurityPermission(
	SecurityPermissionFlag.Execution |   // Required to execute test code
	SecurityPermissionFlag.SerializationFormatter |   // Required to support cross-appdomain test result formatting by NUnit TestContext
	SecurityPermissionFlag.UnmanagedCode // Added by andgein. Required for NUnit 3.10's System.Console.SetOut() call
));  
```

Moreover I have to choose version for .NET standard 1.6. In other case some calls are marked with `[SecurityCritical]` which are not allowed inside sandbox. See https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Compatibility/LongLivedMarshalByRefObject.cs#L32 for example.

But giving `SecurityPermissionFlag.Execution` and `SecurityPermissionFlag.UnmanagedCode` for untrusted code is a bad idea, I think.

Is any appropriate way to run NUnit 3.10 inside sandbox? May be define some special constant for building sandbox-compatible version of NUnit? As `PORTABLE` which has been removed after v3.5?

**Comment by rprouse** [comment]
May I ask what .NET Framework you are targeting for your tests? As far as you know, is it only the `SecurityCritical` attributes that are causing you problems?

**Comment by andgein** [comment]
We want to target .NET Framework 4.5 or .NET Standard 2.0 for running tests.

No, not only `SecurityCritical`. We also don't want to give such SecurityPermissions as `Execution` or `UnmanagedCode`. They are needed for NUnit to call `Console.SetOut()` for example.

**Comment by jnm2** [comment]
(.NET tooling support is not there yet for targeting .NET Standard in unit test projects. II was just told it might be somewhere on the roadmap they are releasing next month. In the meantime, your options are `net45` or `net45;netcoreapp2.0`.)

**Comment by CharliePoole** [comment]
Historically (seems like I'm always saying that) NUnit was created by and for developers running code - often as admins - on their own machines. It predates most security measures we use today and there had never been a thorough analysis of what permissions it needs because the code it runs might do anything at all.

At some point I think we need such an analysis.

**Comment by andgein** [comment]
Thank you for quick responses.

I've tried to build NUnit version compatible with running on sandbox: https://github.com/andgein/nunit/commit/7692d5e1090293e171baf2ca08b76903d228fc8b (branch `sandbox-compatible`).

I am not sure that I found all places where high permissions needed, also I removed support of `TestAssembly`'s custom attributes, but now my tests works with following permission set:

```
permSet.AddPermission(new FileIOPermission(FileIOPermissionAccess.Read, assemblyPath));
permSet.AddPermission(new FileIOPermission(FileIOPermissionAccess.PathDiscovery, assemblyPath));
		
/* Permissions for NUnit: see https://github.com/nunit/nunit/blob/master/src/NUnitFramework/tests/Assertions/LowTrustFixture.cs#L166 and https://github.com/nunit/nunit/issues/2792 for details */
permSet.AddPermission(new FileIOPermission(FileIOPermissionAccess.PathDiscovery, Path.GetDirectoryName(typeof(Sandboxer).Assembly.Location)));
permSet.AddPermission(new ReflectionPermission(
	ReflectionPermissionFlag.MemberAccess));            // Required to instantiate classes that contain test code and to get cross-appdomain communication to work.
permSet.AddPermission(new SecurityPermission(
	SecurityPermissionFlag.Execution |                  // Required to execute test code
	SecurityPermissionFlag.SerializationFormatter       // Required to support cross-appdomain test result formatting by NUnit TestContext
));
```

**Comment by rprouse** [comment]
I am closing old uncategorized issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
