### ISSUE TITLE
Add Support for Windows Phone

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#28]
We need a Windows Phone 7 / .NET 3.7 build

From https://bugs.launchpad.net/nunit-3.0/+bug/996111

**Comment by rprouse** [comment]
Windows Phone 7 is pretty much done, support should be for Windows phone 8 or 8.1 or possibly soon for Windows 10 Universal. I am renaming this to just Windows Phone.

**Comment by CharliePoole** [comment]
Yeah, that and the issue # show it's been around for a while.

**Comment by rprouse** [comment]
This is part of the Xamarin runners. I think it is good enough unless someone requests otherwise. Closing.
