### ISSUE TITLE
Is NUnit2XmlOutput the right solution to backward compatibility?

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#280]
Rather then having to maintain NUnit2XmlOutput code in both nunitlite and nunit-console, perhaps it would be better to just write an xslt that converts the NUnit3XmlOutput format to the older format.

If there is a well defined xsd for each format, there are even tools which will generate the xslt for you.

Applying the xslt to the output xml file is usually a single .NET statement. It could either be applied in the runner if the older format is requested, or just provided to the user to apply if desired and remove the backward compatibility from both nunitlite and nunit-console.

If someone extends any aspect of the 3.0 output, then backward compatibility is simply a modification to the xslt.

**Comment by rprouse** [comment]
We've shipped several releases now without changing this, so I am going to close.
