### ISSUE TITLE
Testing for Exceptions fails for async methods using Constrains Model

### ISSUE THREAD

**Issue by IronSean** [nunit/nunit#2802]
When attempting to use Constrains model (`Assert.That`) to test for thrown exceptions in an `async` method, the test will fail with the exception supposed to be detected. A basic example is below. Nunit v3.10.1 

Method.cs
```csharp
public async Task MyMethod()
{
    throw new InvalidOperationException();
}
```

test.cs
```csharp
[Test]
public async MyTest()
{
    Assert.That(await MyMethod(), Throws.InvalidOperationException);
}
```

This code fails with the message: `Failed: InvalidOperationException` instead of passing as expected. I looked through the docs, but couldn't see a Constrains Model version of `ThrowsAsync` like in `Assert.ThrowsAsync()` or any special syntax I'm missing.

**Comment by IronSean** [comment]
It appears the correct syntax is `Assert.That(async () => await MyMethod(), Throws.InvalidOperationException);` So this might be safe to close.

**Comment by jnm2** [comment]
You're correct. No problem!

Here's another option:

```cs
[Test]
public async Task MyTest()
{
    Assert.That(MyMethod, Throws.InvalidOperationException);
}
```

**Comment by IronSean** [comment]
That syntax appears to fail with `Failed: System.ArgumentException : The actual value must be a TestDelegate or AsyncTestDelegate but was Task`1` then the method is called with parameters, or fail to compile without the invocation `()`.

**Comment by jnm2** [comment]
That's interesting! I ran it successfully against NUnit 3.10.1 before posting, and again just now:

```cs
[Test]
public async Task MyTest()
{
    Assert.That(MyMethod, Throws.InvalidOperationException);
}

public async Task MyMethod()
{
    throw new InvalidOperationException();
}
```

I wonder what's different between your project and mine?

**Comment by IronSean** [comment]
In my actual case it's
```csharp
public class MyClass
{
    public async Task<Otherclass> Load(int id)
    {
        throw new InvalidOperationException("My message");
    }
}
```
and 
```csharp
[Test]
public async Task MyTest()
{
    Assert.That(MyClass.Load(_testId), Throws.InvalidOperationException);
}
```
Throws the error that type Task is not a TestDelegate. 

And 
```csharp
[Test]
public async Task MyTest()
{
    Assert.That(MyClass.Load, Throws.InvalidOperationException);
}
```
Fails to compile with 

> CS1503	Argument 1: cannot convert from 'method group' to 'bool'

**Comment by jnm2** [comment]
Oh, well that's certainly to be expected! It looks like you edited your second post, so responding:

> But it's inconvenient to have to do this:
>
> ```cs
> Assert.That(async () => await MyMethod(-1), Throws.Exception);
> ```

There's a shorter syntax for that, too:
```cs
Assert.That(() => MyMethod(-1), Throws.Exception);
```

In general you should expect to write `() =>` when capturing exceptions. That's just the way C# is.
