### ISSUE TITLE
Vs2017 with nunit3 cannot be executed in parallel 

### ISSUE THREAD

**Issue by chenzongxi** [nunit/nunit#2809]
In vs2017, the nuint project is used for unit testing. The target framework of the nunit project is 4.6.1, and nunit.framework is 3.10.1.0
code show as below:
```
[TestFixture()]
Public class Class1Tests
{
  [Test]
  [Parallelizable]
  Public void test1Test()
  {
    While(true)
    {
      System.Diagnostics.Debug.WriteLine(2);
      Thread.Sleep(1000);
    }
  }
  [Test]
  [Parallelizable]
  Public void test2Test()
  {
    While(true)
    {
      System.Diagnostics.Debug.WriteLine(3);
      Thread.Sleep(1000);
    }
  }
}
```
The phenomenon is that the test1Test function has been executed and the output is always 2.
No parallel execution, why the test2Test function is not executed? Is VS2017 also need to configure where?

**Comment by chenzongxi** [comment]
how to use

**Comment by chenzongxi** [comment]
[ClassLibrary2.zip](https://github.com/nunit/nunit/files/1913633/ClassLibrary2.zip)

**Comment by chenzongxi** [comment]
![catch 04-16-08-57-33](https://user-images.githubusercontent.com/38370307/38786871-3c0f4b7c-415d-11e8-8116-678728ca70cc.jpg)
![qq 20180414131934](https://user-images.githubusercontent.com/38370307/38786872-3c5f8d9e-415d-11e8-9646-ef1d4e684d40.jpg)
![qq 20180414131858](https://user-images.githubusercontent.com/38370307/38786873-3cfffa54-415d-11e8-911b-cb353e0710da.jpg)
![k 5g_fq_lk 0sz t 04-16-08-57-33](https://user-images.githubusercontent.com/38370307/38786874-3e2056f4-415d-11e8-9399-9468b10646ae.png)

**Comment by chenzongxi** [comment]
I spent a few days to figure out how to use it.Still no progress.
I'm confused.

**Comment by rprouse** [comment]
I am closing old uncategorized issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
