### ISSUE TITLE
Infinite, non-terminating loop in WorkItemQueue.Dequeue

### ISSUE THREAD

**Issue by herebebeasties** [nunit/nunit#2810]
Our NUnit Agents are sometimes getting stuck chewing CPU. It seems that this happens due to this code in WorkItemQueue:
https://github.com/nunit/nunit/blob/42eba347d67ab441bc01903cedf1596c029c1e6b/src/NUnitFramework/framework/Internal/Execution/WorkItemQueue.cs#L295-L298

It seems that the code can get here when there are no items to dequeue and then unsurprisingly it just gets stuck, chewing 100% CPU while it's there.

In case it helps debugging this, in my thread dump I'm seeing:
```
26 threads running TestWorker
    1 of those in WorkShift.StartWorkers
        ParallelWorkItemDispatcher.OnEndOfShift
            ParallelWorkItemDispatcher.StartNextShift
                Shifts.get
   25 of those in WorkItemQueue.Dequeue
        20 of those in ManualResetEventSlim.Wait()
         4 of those calling TryDequeue here in a loop
```
I'm afraid I can't get an actual thread dump to you as it's quite hard to export things like this outside of our firm, but let me know if you'd like any more info.

(I think what you really want here is a `BlockingCollection` for which you could use its `ConsumingEnumerable`, rather than the current `ConcurrentQueue` usage - it would be much easier to manage it all. Suspect that's not compatible with your .NET 2.0 support, though.)

**Comment by jnm2** [comment]
>(I think what you really want here is a BlockingCollection

I happened to port BlockingCollection to net20 while working on something else. Decided to save the work after I didn't need it. https://github.com/jnm2/nunit/commit/e4e81a28937a6e974950774545e24682a2354d54.

**Comment by mikkelbu** [comment]
The content of this issue seems - more or less - to be the same as in #2417. @herebebeasties are you okay with me closing this as a duplicate?

**Comment by herebebeasties** [comment]
Well, that ticket is a "refactor because it's all a bit horrid" whereas this is a concrete bug that's happening sporadically for us.
My suggestion was to use a BlockingCollection, sure, but oerhaps

**Comment by rprouse** [comment]
I am closing old uncategorized issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
