### ISSUE TITLE
ITestEventListener

### ISSUE THREAD

**Issue by illumination7272** [nunit/nunit#2813]
If you please can update documentation regarding ITestEventListener , or make a short tutorial on how to create a custom addin with nunit 3 , because every try is met with failure, i require that to create a custom reporter.Thanks

**Comment by mikkelbu** [comment]
@illumination7272 Have you read https://github.com/nunit/docs/wiki/Writing-Engine-Extensions and https://github.com/nunit/docs/wiki/Event-Listeners ? 

Note also that (from https://stackoverflow.com/a/38749913)
> NUnit engine extensions get installed into the NUnit engine, so they need to be in a separate assembly. Once you have a separate assembly, you need to tell the engine where it is. Currently, you do this by creating a file of type .addins in the same directory as the engine. (You could modify the existing file, but that introduces maintenance problems in the future)

**Comment by illumination7272** [comment]
Yes i did , i created a separate assembly for the listener ,a basic listener that writes to a file ,  , and moved the dll into a new directory in packages (engine version 3.8) and updated the .addins file inside the engine .Note: "i used VS  to run the tests "

**Comment by CharliePoole** [comment]
The VS adapter uses its own copy of the engine. Did you find that copy and fix it to use your extension or did you install it in some other copy of the engine that was separately installed?

Normally using the VS adapter precludes use of extensions but it could possibly be made to work.

**Comment by rprouse** [comment]
I am closing old uncategorized issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
