### ISSUE TITLE
Save and restore the SynchronizationContext before and after each test case

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2821]
One of hundreds of tests is causing System.Windows.Forms.Control.CreateHandle() which installs a WindowsFormsSynchronizationContext. When the test worker runs the next and that test happens to be async, the test deadlocks due to the fix for https://github.com/nunit/nunit/issues/2123 not being released yet. The problem is, even with the deadlock fix in NUnit, I don't want the next test running with a WindowsFormsSynchronizationContext.

Rather than locating the misbehaving test(s) through trial and error I'd rather have a failure or at least a warning of executing the work item caused an overall change to the thread's SynchronizationContext.Current. That would cause a nice todo list to fall out of my tests.

Or would we prefer to save and restore `SynchronizationContext.Current` with the other global state we save and restore?

Either way, we'd have to make sure that we take the snapshot before any ITestActions and other setups start and only compare or restore after they all tear down.

**Comment by jnm2** [comment]
[`[assembly: DetectGlobalStateChanges]`](https://gist.github.com/jnm2/1c7c3d0502b6f2d175063631965e8d2f) was worth it. 381 of my tests are sloppy.

**Comment by jnm2** [comment]
Third party control's constructor is creating an internal control's handle. So how do I want to handle this: add boilerplate to a ton of tests, or have the ITestAction simply restore rather than warning?

This sort of makes me think NUnit should silently restore the SynchronizationContext by default.

**Comment by jnm2** [comment]
@sharwell Since you've worked in this area, I'd love to know what would your ideal would be in a test framework.

**Comment by sharwell** [comment]
> Or would we prefer to save and restore `SynchronizationContext.Current` with the other global state we save and restore?

⬆️ This

**Comment by jnm2** [comment]
@sharwell Thank you! 

@nunit/framework-team I'm thinking we should saving and restoring the SynchronizationContext ]in TestExecutionContext\(https://github.com/nunit/nunit/blob/63fbf8c0129e45c4b0ece3b640133dbe35ed35cb/src/NUnitFramework/framework/Internal/TestExecutionContext.cs#L138-L164). This fits our theme of working more smoothly with SynchronizationContexts. Any thoughts before I retitle and put this in for 3.11?

**Comment by jnm2** [comment]
Want to do this after https://github.com/nunit/nunit/pull/2818.

**Comment by jnm2** [comment]
Also have instances where TestCaseSource is creating objects which change the synchronization context. Need to make sure this is addressed, as well as any other discovery-time execution of user code.

**Comment by rprouse** [comment]
@jnm2 moving this out of the 3.11 milestone.

**Comment by jnm2** [comment]
@rprouse No pressure for 3.11, but I realized that this one should be simple. PR at #2966.
