### ISSUE TITLE
Regular "BusyExecIdle after 200 milliseconds delay" CI failures

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2831]
This is responsible for the last couple dozen times I read through the AppVeyor logs to figure out why a branch was failing to build. Always seems to be net35.

```
1) Failed : NUnit.Framework.Internal.Execution.TestWorkerTests.BusyExecuteIdleEventsCalledInSequence
  Expected: "BusyExecIdle" after 200 milliseconds delay
  But was:  <string.Empty>
   at NUnit.Framework.Internal.Execution.TestWorkerTests.BusyExecuteIdleEventsCalledInSequence() in C:\projects\nunit\src\NUnitFramework\tests\Internal\TestWorkerTests.cs:line 67
```

Can we change this to `10_000`? If it succeeds it's instantaneous. If it fails, all we care about is not hanging for minutes on end.

**Comment by rprouse** [comment]
Sure, go for it.
