### ISSUE TITLE
NUnitEngineException : Unable to acquire remote process agent

### ISSUE THREAD

**Issue by niwe** [nunit/nunit#2832]
I'm trying to start some tests with nunit3-console.exe (v3.8.0) on a virtual machine running Windows 10 (x64) but before any tests get executed NUnit stops. I get the following error messages:

```
Unhandled Exception: NUnit.Engine.NUnitEngineException: Failed to start remote test agent.
   at NUnit.Engine.Services.TestAgency.OnAgentExit(Object sender, EventArgs e)
   at System.Diagnostics.Process.OnExited()
   at System.Diagnostics.Process.RaiseOnExited()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(Object state, Boolean timedOut)
```

And after a few more seconds this is shown:

```
1) Error :
NUnit.Engine.NUnitEngineException : Unable to acquire remote process agent
--NUnitEngineException
   at NUnit.Engine.Runners.ProcessRunner.CreateAgentAndRunner()
   at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter)
```

I recently added the flag --_x86_ to NUnit and that's when this issue started. I added the flag because I also added an external file (_Microsoft Exression Encoder_) to my test project, and it seems to be x86 only. 
I read (on _Stackoverflow_ I think) that using --_inprocess_ works. I used to have that flag but it is not compatible with --_x86_. So I can't get it to work no matter how I try.

This is the command I use to run NUnit: `nunit3-console.exe C:\...\GUITests.dll --x86 --where "cat == .NIGHTLY" --result="C:\...\Logs\TestResult.xml;format=nunit2"`

**Comment by rprouse** [comment]
Are any of the other assemblies that your tests reference or that your code references x64?

How did you install NUnit Console and what version are you using?

I will likely move this issue to the NUnit.Console repository, but would like to confirm here first.

**Comment by niwe** [comment]
I'm not entirely sure how I can see if assemblies are x64 or not.

In my Visual Studio solution I have three projects. The project where NUnit is used (and Microsoft Expression Encoder) I only reference some standard .NET 4.5.2 assemblies (and one of the other projects). In the other two projects I reference WebDriver and Netwonsoft.Json.

On the machine (VM) where it's not working I installed NUnit with NUnit.Console.msi (3.8.0). On the machine where it's working (my workstation) I installed NUnit via NuGet, in Visual Studio, and I start the tests within Visual Studio using NUnit3TestAdapter.

I see now that I'm running NUnit 3.9.0 on my workstation. I will upgrade to 3.9.0 on the VM and see if this helps...

**Comment by niwe** [comment]
Hmm, I think I have mixed it up. I thought nunit-console and nunit was pretty much the same thing. Now I see that version 3.8.0 is the latest as far as nunit-console goes. So I am running the latest versions on both machines.

Any tips on how I can get this working?

**Comment by ChrisMaddock** [comment]
Try uninstalling the NUnit3Adapter NuGet package, and then running with the NUnit.Console msi on your VM.

I think there may be a discovery issue with the adapter and msi currently using different using different version of the NUnit engine.

**Comment by cmoonExpedia** [comment]
Could anyone explain why NUNIT needs to acquire the remote agent even though the tests in only local? What is under the hood?

Thanks.

**Comment by CharliePoole** [comment]
In this case "remote" merely means "in another process." NUnit console runs each assembly in a separate process by default. The process has to be started and then connected to in order to issue commands telling it to load and run the tests.

**Comment by WereDev** [comment]
I recently started getting this issue as well.  It happens with all solutions/assemblies.  I've tried uninstalling/reinstalling NUnit which didn't help, though don't much expect it to given that it's using the one pulled down from NuGet local to the solution.  Tried deleting those files to have them pulled down again, but that didn't help either.  Again, not really surprised as this suddenly affected all of my solutions at once.  I'm not sure what might have changed on my system to cause the issue.

**Comment by ChrisMaddock** [comment]
@WereDev do you have nunit installed via the msi, on anything nunit-y on you path vars- in addition to our nuget packages?

**Comment by niwe** [comment]
I finally found a solution to my issue. Hopefully someone can I explain why this is happening.

I ran my tests using (which gave an exception):
C:\PROGRA~1\NUnit.org\nunit-console\nunit3-console.exe C:\...\GUITests.dll

But running it this way works:
"C:\Program Files\NUnit.org\nunit-console\nunit3-console.exe" C:\...\GUITests.dll

Don't know it doesn't work the original way. No big deal for me, I found a workaround so I'm happy. Maybe it helps someone else running into the same problem.

FYI
The reason why I use "PROGRA~1" instead of "Program Files" is (I think... it was a long time ago :/) because I couldn't install NUnit, using the flag TARGETDIR, without using the old DOS 8.3 name. And then I reused that variable when starting NUnit.

**Comment by rprouse** [comment]
@niwe what version of the Console do you have installed?

**Comment by niwe** [comment]
@rprouse I installed NUnit using NUnit.Console-3.8.0.msi (from https://github.com/nunit/nunit-console/releases)

**Comment by Hu3bl** [comment]
We see the same issue on our CI server (Windows Server 2012R2). Occasionally, we get the error 

`
NUnit.Engine.NUnitEngineException : Unable to acquire remote process agent
--NUnitEngineException
   at NUnit.Engine.Runners.ProcessRunner.CreateAgentAndRunner()
   at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter)
`
for every test DLL in a larger project. While looking into it, we discovered that the nunit-agent.exe processes that get launched all crash before connecting to the runner and the Windows Event Log has the following to say about that:

`Application: nunit-agent.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.Diagnostics.Process.GetProcessById(Int32, System.String)
   at System.Diagnostics.Process.GetProcessById(Int32)
   at NUnit.Agent.NUnitTestAgent.Main(System.String[])`

We suspect that something is amiss with the command line that is passed to the agent process, but cannot yet prove it.

**Comment by ChrisMaddock** [comment]
@Hu3bl This is an interesting stack trace...but I'm unsure how this could occur! Are you able to share your full logs, including the agent log?

**Comment by Hu3bl** [comment]
Of course I'm allowed to share the logs with you, however, I had to remove all assembly names by xxx because I'm not allowed to publish them. 
I called nunit with 
`nunit3-console.exe build\xxx.sln --result:TestResult.xml;format=nunit3 --trace=Verbose`
The resulting files are attached as zip file.
[nunit.zip](https://github.com/nunit/nunit/files/2132058/nunit.zip)

**Comment by ChrisMaddock** [comment]
@Hu3bl Is this all the logs that were written? No `nunit-agent_6132.log`? 😞

**Comment by ChrisMaddock** [comment]
Never mind. Based on your stack trace, the agent will be crashing before it initialises the log.

But I'm still not sure why. 🤔

**Comment by ChrisMaddock** [comment]
@nunit/engine-team 

Nice self-contained issues here. How could `Process.GetProcessById()` be throwing an ArgumentException from some agents but not others, when the process it is looking up (appears to be) alive and well? It's only [documented](https://docs.microsoft.com/en-gb/dotnet/api/system.diagnostics.process.getprocessbyid?view=netframework-4.7.2#System_Diagnostics_Process_GetProcessById_System_Int32_) to throw this when the process is dead - I had a quick look in ReferenceSource, which seems to suggest the same...

**Comment by CharliePoole** [comment]
Is it possible that the argument   is not being parsed correctly in some cases?

**Comment by CharliePoole** [comment]
Locale? Grasping at straws here!

**Comment by ChrisMaddock** [comment]
I think we may need to add more logging!

**Comment by jnm2** [comment]
> and we could hold on to the ID instead, and then just look it up when we need to check if it's exited. (Which is already an 'error-case' in itself!)

Process IDs are recycled. If possible, you want to open the process handle (GetProcessById) ASAP in case the process closes and a new process starts with the same ID. 
If there isn't a reliable way to be sure the process is still running even when you call GetProcessById ASAP, the usual technique to uniquely identify a process over time is pid + start time.

**Comment by ChrisMaddock** [comment]
Good shout!

**Comment by ChrisMaddock** [comment]
@Hu3bl - this issue really should be in the nunit/nunit-console repo. I'm going to move it over now, and comment further over there. 🙂
