### ISSUE TITLE
Underscores for private fields?

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2845]
Do we like or dislike prefixing with underscores?

Only 376 of the 1106 private, non-compiler-generated fields declared in this repository begin with underscores. That is 34.0%. Our coding standard has been at odds with the majority of what you take in when you look through NUnit source and with the majority of C# code in general.
It's really hard to be consistent while writing and while reviewing. I just saw a field in one of my most recent PRs that is missing the underscore, added right under a field with an underscore, and no one (including me) noticed.

However, we recently decided to loosen the coding standard so that private and internal fields naming is totally up to the preferences of the team of each project. (https://github.com/nunit/nunit/issues/2822)  This project's team is led by Rob.

My second paragraph may have betrayed my bias, but really I'm happy to go either way and I don't particularly want to influence you. The reason I ask is that I have an .editorconfig and DotSettings ready which generate fields with underscores (without creating any new diagnostics). I could just as easily swap the order of preference around though, so I'd like to solicit your preferences.

<details>

I ran this script on all DLLs in [https://github.com/nunit/nunit/releases/download/v3.10.1/NUnit.Framework-3.10.1.zip](https://github.com/nunit/nunit/releases/download/v3.10.1/NUnit.Framework-3.10.1.zip)/bin/net45

```cs
var all = new List<FieldInfo>();
var underscore = new List<FieldInfo>();

foreach (var dll in Directory.GetFiles(@"C:\Users\Joseph\Desktop\net45", "*.dll"))
{
    var a = Assembly.LoadFile(dll);

    foreach (var type in a.DefinedTypes)
    {
        if (type.IsDefined(typeof(CompilerGeneratedAttribute))) continue;
        foreach (var field in type.GetFields(BindingFlags.NonPublic | BindingFlags.Static | BindingFlags.Instance))
        {
            if ((field.Attributes & FieldAttributes.FieldAccessMask) != FieldAttributes.Private) continue;
            if (field.IsDefined(typeof(CompilerGeneratedAttribute))) continue;
            all.Add(field);
            if (field.Name[0] == '_') underscore.Add(field);
        }
    }
}

Console.WriteLine($"{underscore.Count}/{all.Count} ({underscore.Count / (double)all.Count:p1})");
```
</details>

**Comment by oznetmaster** [comment]
I prefer prefixing private field names with underscores.  I find the visual cue provided by the underscore to be productive.

**Comment by mikkelbu** [comment]
I don't like the prefixing, but I value that the code is consistent mucher higher. So if most people prefer prefixing then I don't mind us using prefixes as long as we are consistent 😄.

**Comment by rprouse** [comment]
I prefer `_underscores` as a queue that the field is not a local variable. I would also prefer consistency, but the underscore standard was introduced in NUnit 3 and older code was only changed as we updated files, so much wasn't done.

**Comment by jnm2** [comment]
Thanks everyone! 😃
