### ISSUE TITLE
Assert.ThrowsAsync and friends do not catch AssertionException

### ISSUE THREAD

**Issue by hazzik** [nunit/nunit#2848]
Following code used to work in 3.9:

```csharp
Assert.ThrowsAsync<AssertionException>(async () =>Assert.AreEqual(1, 0));
```

```csharp
Assert.That(async () => Assert.AreEqual(1, 0), Throws.TypeOf<AssertionException>());
```
```csharp
Assert.CatchAsync<AssertionException>(async () => Assert.AreEqual(1, 0));
```
But in 3.10 all fail with the internal assertion:

```text
  Expected: 1
  But was:  0
```

The equivalent synchronous code works as expected.

**Comment by hazzik** [comment]
Related to #2758?

**Comment by hazzik** [comment]
Culprit in this commit: 86ef61e2a1c2ea1bd2ef4c2f06b76bca3f4f62b0. As I understand all catch-related methods where wrapped into the `using (new TestExecutionContext.IsolatedContext())`. But.... only the sync part.

**Comment by jnm2** [comment]
@hazzik I think this is covered by #2758. NUnit doesn't provide an official API for preventing `Assert` methods from failing your test. You can use this internal API:

```cs
Assert.That(async () =>
{
    using (new TestExecutionContext.IsolatedContext())
    {
        Assert.AreEqual(1, 0);
    }
}, Throws.TypeOf<AssertionException>());
```

We should probably consider what we want our public-facing API to be.

**Comment by hazzik** [comment]
@jnm2 I understand your point, however, I think that async and sync APIs should at least behave exactly the same: sync version does set up isolated context, but async does not. So, IMO they both should set up the isolation context, or both should not.

So here, for example, the `using (new TestExecutionContext.IsolatedContext())` should wrap whole `if` statement, and not only else part (or removed at all):
https://github.com/nunit/nunit/blob/662055f789a8528e851e63c6566822e9392a46d1/src/NUnitFramework/framework/Assert.Exceptions.cs#L44-L74

Anyway, we switched to `Warn.If` as suggested in #2758.

**Comment by jnm2** [comment]
My instinct is to agree with you, though one benefit of the inconsistency is that it brought you to us. 😁 It's a good suggestion.

@nunit/framework-team Should we make sure all exception asserts set up an isolated context, including the async onces?

**Comment by CharliePoole** [comment]
That's easy. The isolated context was added for backward compatibility so that people could keep calling tests directly in specific circumstances that didn't include sync methods.

**Comment by rprouse** [comment]
I am closing old uncategorized issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
