### ISSUE TITLE
Failure when unit testing code containing code dom compilation.

### ISSUE THREAD

**Issue by isyed2000** [nunit/nunit#2853]
Environment:  Nunit Framework version: 3.9, NUnit GUI: 0.6.0, VS 2017, .NET Framework 4.7.1 Full Version.

Scenario: As part of the logic, the system generates a dynamic assembly as follows.
```csharp
CompilerParameters cp = new CompilerParameters();

cp.GenerateExecutable = false;
cp.GenerateInMemory = true;

cp.TreatWarningsAsErrors = false;
cp.ReferencedAssemblies.Add("Employee.dll");
cp.ReferencedAssemblies.Add("Person.dll");

CompilerResults cr = provider.CompileAssemblyFromSource(cp, "someCode");
if (cr.Errors.Count > 0)
{..}
```

I open the Unit Test Assembly in NUnit-Gui-0.6.0 and test a method which ends up calling the above code as part of the business logic.

Issue: Above Error Count is greater than 0 and has the following messages:

`error CS0006: Metadata file 'Person.dll' could not be found
error CS0006: Metadata file 'Employee.dll' could not be found`

I have verified that these assemblies are present in the bin directory along with the Unit Test DLL. This code works in regular application workflow but not in NUnit 3.9.

Not sure if this is a bug in NUnit 3.* or an application issue.

Regards,

Iftikhar.

**Comment by isyed2000** [comment]
I get the same error when using nunit3.ConsoleRun.ner 3.8.0

**Comment by rprouse** [comment]
I am closing old uncategorized issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
