### ISSUE TITLE
Has.All.../Has.None... - show non-matching items in error message

### ISSUE THREAD

**Issue by Dreamescaper** [nunit/nunit#2854]
Currently NUnit only logs actual collection in error message. That's fine if we have 3 items, but not really great for 200, especially due to that only several first items are displayed.
Would be really great to log non-matching items as well, something like:
```
Expected: all items instance of <System.Char>
Actual: < 'a', \"b\", 'c' >
Non-Matching: < \"b\" > 
```

That would require to traverse through all collection though, even if the first checked item does not match, but I suppose that's OK, considering that it might happen only for failing test.

**Comment by CharliePoole** [comment]
Other errors often only show the first failure. For example, when comparing two arrays for equality, we show the index of the mismatch as well as the values. Seems as if that would work here as well and avoids re-examining the collection.

I do think we need to take a broad look at various error messages applied to collections.

**Comment by Dreamescaper** [comment]
Do you think that's important? 
As I mentioned, in order test to pass it will need to traverse the whole collection anyway.

The only case I can think of is to use NotConstraint with AllItemsConstraint, but it makes no sense considering that we have separate SomeItemConstraint.

If you still think we should break on the first non-mathcing item, what message would you suggest?
`Non-Matching: "b"` ?

**Comment by Dreamescaper** [comment]
Or something like `Non-Matching item at index [1]: "b"` ?

**Comment by Dreamescaper** [comment]
Decided to go with the last one so far, created PR for that.

**Comment by CharliePoole** [comment]
Have you looked at the output of comparing two arrays for equality? The location of the mismatch is handled in one line, followed by the precise failure. Maybe that's the general model to use.

**Comment by Dreamescaper** [comment]
Not sure I understand your suggestion. What should be on the following line (precise failure)?
In EqualConstraintResult it's simple expected-actual text, with special cases handling (like strings, enumerables etc.), as far as I can see.
Not sure that applies here.

a) actual result is same for all elements, therefore it will be simply duplicated:
```
Expected: all items instance of <System.Char>
Actual: < 'a', "b", 'c' >
Non-matching item at index [1]: 
	Expected: instance of <System.Char>
	Actual: "b"
```

b) in EqualConstraint we know that we need to check specifically for equality, but here it could be any condition, therefore I don't think we can handle any special cases. We could provide BaseConstraints message for that purpose, but see a) - that will simply duplicate first Expected line, won't it?

**Comment by jnm2** [comment]
I like this, especially because we may decide to trim the number of items printed:

```
Expected: all items instance of <System.Char>
Actual: < 'a', 'b', 'c', 'd', 'e', ...>
Non-matching item at index [25]: "z"
```
