### ISSUE TITLE
Is.Ordered - show item where order breaks in error message

### ISSUE THREAD

**Issue by Dreamescaper** [nunit/nunit#2855]
Currently NUnit only logs actual collection in error message. That's fine if we have 3 items, but not really great for 200, especially due to that only several first items are displayed.
Would be really great to show where order actually breaks somehow:

Something like this, maybe?
```
Expected: collection ordered
Actual: < "1", "2", "4", "3" >
Order breaks at index [2] with value "4" 
```

Besides, I would show collection with start index of `breakingIndex - 1` in actual, so that this item would always be displayed even for huge collections.

(Probably something trickier, like
```
int startIndex = breakingIndex > 8 ? breakingIndex - 1 : 0;
```
)

**Comment by jnm2** [comment]
I like this. @nunit/framework-team, what do you think?

@Dreamescaper If we use the term 'index', it should be zero-based. By convention, to get to item #1, you skip 0 items so the index is 0. To get to item 3, you skip 2 items so the index is 2. etc.

**Comment by Dreamescaper** [comment]
Sure, just a mistype!

**Comment by mikkelbu** [comment]
> I like this. I've had frustrations with this in the past. @nunit/framework-team, what do you think?

I don't mind the change, but I don't think that I have ever used `Is.Ordered`.

**Comment by jnm2** [comment]
@mikkelbu Me neither, but I think what I'm remembering is running into this with `Is.EqualTo` in collection mode.
