### ISSUE TITLE
NUnit documentation incorrect?

### ISSUE THREAD

**Issue by richardgavel** [nunit/nunit#2857]
Within the NUnit documentation at https://github.com/nunit/docs/wiki/Framework-Parallel-Test-Execution, is this paragraph in conflict with the closing of the issue at https://github.com/nunit/nunit/issues/2606 and https://github.com/nunit/nunit/issues/2542?

_Parallel execution is supported by the NUnit framework on desktop .NET runtimes. It is not supported in our Portable or .NET Standard builds at this time, although the attributes are recognized without error in order to allow use in projects that build against multiple targets._

**Comment by rprouse** [comment]
You are correct, the documentation was not updated. I have updated it to say,

*Parallel execution is supported by the NUnit framework on desktop .NET runtimes and .NET Standard 2.0. It is not supported in the .NET Standard 1.6 build, although the attributes are recognized without error in order to allow use in projects that build against multiple targets.*

**Comment by kumarbrandmuscle** [comment]
![default net snapshot](https://user-images.githubusercontent.com/40033740/41413087-abb93b24-6fff-11e8-9091-7607a698755b.png)
Hi rprouse,
If I select, as per snapshot attachment the parallel execution will run
Thanks,
Kumar.

**Comment by kumarbrandmuscle** [comment]
Hi rprouse,
I selected above dependencies,and I have getting N unit3Test Adapater not recognizing the library.
could please help me with this issue.

**Comment by ChrisMaddock** [comment]
@kumarbrandmuscle Your tests must target a specific platform, not netstandard itself. See the link below for an explanation:

https://github.com/nunit/docs/wiki/.NET-Core-and-.NET-Standard#why-cant-my-tests-target-net-standard

**Comment by kumarbrandmuscle** [comment]
Hi chris,
As the article says,that we have to select  class library (.net framework).
![image](https://user-images.githubusercontent.com/40033740/41417129-1b60ffac-700a-11e8-8f6e-4f53012d1a71.png).
Even though I selected the above one it was throwing me the same above error.
N unit test adapter not compatible.
could you please share the process ho to create ```https://github.com/nunit/docs/wiki/.NET-Core-and-.NET-Standard#why-cant-my-tests-target-net-standard```` with snapshots it would helpful to me.
Thanks.
kumar.
