### ISSUE TITLE
Cannot combine Throws.Something Constraints with And/Or Constraint

### ISSUE THREAD

**Issue by Dreamescaper** [nunit/nunit#2862]
The following code:
```C#
ActualValueDelegate<bool> actual = () => { throw new ArgumentNullException("Failure"); };

Assert.That(actual, Throws.ArgumentNullException | Throws.InvalidOperationException);
```

Fails with error:
`Message: System.ArgumentNullException : Value cannot be null.
Parameter name: Failure`

I suppose that's because And/Or Constraints don't have `ApplyTo<TActual>(ActualValueDelegate<TActual> del)` overriden.

We could provide overrides in And/Or constraints, but that would lead to delegate being executed twice - for each constraint.
Probably that's not very cool.

**Comment by Dreamescaper** [comment]
We could provide overrides in And/Or constraints, but that would lead to delegate being executed twice - for each constraint.
How do you think, how OK is that?

**Comment by rprouse** [comment]
Isn't it a bit of an anti-pattern to not know which exception the code you are testing is going to throw? Wouldn't you setup your test in such a way as to ensure that it throws the exception you intend?

**Comment by Dreamescaper** [comment]
That's just an example.
My use case was a bit different - I wanted to make DelayedConstraint to not fail on exceptions, so I tried to make it this way:
`(Throws.Nothing & Is.True).After(10,100)`

It failed anyway, so I tracked down why it wasn't working.

**Comment by rprouse** [comment]
I am closing old Idea issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
