### ISSUE TITLE
Unable to pass parameters (or GET parameters) based on test case to ValueSource functions

### ISSUE THREAD

**Issue by Cyrelc** [nunit/nunit#2864]
We would like to be able to write a single function which returns ValueSource IEnumerable data, but takes into account some information (such as a custom attribute) or else just takes a parameter from the test case. 

Example: We have a "valid login" test case, and an "invalid login" test case. Takes types of accounts, and grabs the credentials from an xml document, then tries to log in with username and password. Simple. However, the "valid" login function works with four accounts, and the "invalid" login works with different accounts. We would also like the ability to configure which accounts that tests get run against in the config file. 

So if validLoginTest runs against account types A, B, C, and D, the function would take (pseudocode):

```
public List<> ValueSourceFunctionName (List<accountTypes> accountTypes ) 
{
    List<> enabledAccountTypes;
    foreach(accountTypes as type)
        if(isEnabled(type))
            enabledAccountTypes.Add(type);
    return enabledAccountTypes;
}
```

Alternatively, the function could pull from a custom attribute above the test, or any other way you see fit for us to grab the variable. But we can not see a way to pass any variable or config setting to these functions on a per test basis. 

Thanks in advance for any guidance.

**Comment by CharliePoole** [comment]
Why not just have two data sources, one for valid, one for invalid?

**Comment by CharliePoole** [comment]
Makes sense but I think you need to say more because it sounds like two
functions, not hundreds

**Comment by Cyrelc** [comment]
Well yes, this is only one example. So sticking with accounts, we have various subscription levels, for example. So subscription level A and D might both be able to do one thing, while subscription level C and D might be able to do something entirely different. Making the tests valid for those accounts, but not for the others. 

Additionally, on a per test basis, we would like to enable a (config based enable/disablable) "random" function. So given four valid account types, run against only one of them. Currently the function would only allow us to run against the SAME one for every test. 

Example:
Test 1) Login (accounts A, B, C, D)
Test 2) Change Password (Accounts A, B, C, D)
Test 3) InvalidLogin (Accounts E, F, G)
Test 4) Purchase (Accounts H, I, J)

Accounts A, B, C, E, G, and I are "enabled" to have tests run against them. Each test passes the accounts applicable to it, and either returns ALL valid (random mode off) or only ONE valid (random mode on).

So that when running hundreds or thousands of tests, we will hit core functionality with each account type, rather than every account type. 

I should also mention this is black box integration testing, not unit testing.

**Comment by CharliePoole** [comment]
I'll outline my general approach to similar situations. Some of it may help you. I can't do much code-formatting on my phone but I'll try to make the choices clear.

There are three general approaches...

1. Multiple sources combined in various ways. This works well with two or three categories of account or other entity. You can use multiple TestCaseSource attributes to combine them. Sounds like that won't work for you.

2. Parameterized test case sources, as you asked for. This isn't available but I think there's an existing request for it.

3. Tests filter cases they need. This is the basis for NUnit theories but also works for straight tests. You give every test all the data and each test specified the data it wants using an Assume statement. Some people dislike this approach nut others, including me, find it very powerful. I think it might work for you.

**Comment by csrina** [comment]
Can you provide more details regarding option 3?

**Comment by rprouse** [comment]
@csrina, I think what @CharliePoole means by the third option is to use `Assume.That` as a guard clause at the beginning of your tests to check that the test should run based on the data that is passed in. `Assume` works like `Assert` except that a failure causes the rest of the test to not run because it hasn't met pre-conditions.

**Comment by CharliePoole** [comment]
@csrina Sorry I missed the question! What @rprouse writes is exactly what I meant.

**Comment by jnm2** [comment]
I'll often have TestCaseSource or ValueSource point to a public member which does nothing except pass parameters to a private static member which is shared by multiple TestCaseSources or ValueSources.
Worst-case that's a max of one source member per use of TestCaseSource or ValueSource, which isn't bad.

**Comment by rprouse** [comment]
I am closing old uncategorized issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
