### ISSUE TITLE
Visual Studio Test Explorer displays duplicate (and non-functional) test cases for parameterized tests in certain cases (see description)

### ISSUE THREAD

**Issue by vargonian** [nunit/nunit#2866]
I have discovered that, when using a TestCaseSource which returns a collection of arrays of type X, where X contains a ToString override which surrounds its contents (if any) with parentheses, the Visual Studio Test Explorer will display an extra, greyed out test without parameters specified which will not be runnable:
![broken_test_discovery](https://user-images.githubusercontent.com/226991/40353041-529233cc-5d65-11e8-9f44-c8beaceac7e9.png)

I've done my best to distill a repro case:

```
using NUnit.Framework;

namespace BrokenTestDiscoveryTests.Tests
{
    public class SomeDummyObject
    {
        public override string ToString()
        {
            return "(anything inside parentheses)";
        }
    }

    public class BrokenTestDiscoveryTests
    {
        private static SomeDummyObject[][] GetDummyParameters()
        {
            return new[]
            {
                new[] { new SomeDummyObject(), new SomeDummyObject() }
            };
        }

        [TestCaseSource(nameof(GetDummyParameters))]
        public void SomeDummyTest(SomeDummyObject obj1, SomeDummyObject obj2)
        {
            Assert.IsTrue(true);
        }
    }
}
```
Note that if the test method is changed to take a single parameter (with a 1D array TestCaseSource), the issue will not reproduce.  Note also that by removing either of the parentheses around the SomeDummyObject.ToString method, the issue will not reproduce.

This issue does not appear to manifest when using the console runner.

**Comment by rprouse** [comment]
Which version of VS are you running? VS now does it's own Roslyn source based discovery for tests instead of calling NUnit, xUnit, MSTest, etc to do discovery. This is to improve performance, but it means that the VS team has duplicated test discovery for each framework and there are bugs.

You will know that it is a VS issue, not an NUnit issue if you turn off "Discover Tests in real time" and it goes away.

![image](https://user-images.githubusercontent.com/493828/40370658-be0f8674-5dae-11e8-92b1-4c313d3f240a.png)

**Comment by vargonian** [comment]
I'm using Visual Studio 2017 Enterprise (15.7.1).

Interesting, when I disable that option, I'm not seeing the phantom tests anymore.  Thank you!

I do still see some oddness--for example, when using a parameterized test with "display-friendly" values), the test name is listed with its fully qualified namespace (A.B.TestMethod), whereas others have the namespace omitted (aside from the heading which groups them all):

![broken_test_discovery_fqn](https://user-images.githubusercontent.com/226991/40382184-9ae0c880-5db2-11e8-9561-dcba51bf799d.png)

(I imagine this is a separate issue.)

**Comment by rprouse** [comment]
Thanks for the update. We are working with the Visual Studio Test team to fix issues like this. There will be some back and forth as they provide fixes and extended APIs in newer VS releases for us to work with and as we extend the adapter to use those APIs. I am going to mark this issue as blocked, but leave it open to track for now.

**Comment by rprouse** [comment]
Sorry, I didn't notice that this issue is in the NUnit Repo. I am going to close this issue. We have many similar issues in the adapter repository for tracking this sort of thing. It is better there. Thanks.

**Comment by jnm2** [comment]
@rprouse Saw this yesterday 🎉 https://twitter.com/xunit/status/1000570656449224704

**Comment by rprouse** [comment]
@jnm2 that is the plan, I met with the VS test team today about it. It isn't coming soon though 🙁

**Comment by jnm2** [comment]
That's something though! :D
