### ISSUE TITLE
TestCaseSource breaks when using static classses, AppDomains, and Assemblies

### ISSUE THREAD

**Issue by bdonnahue** [nunit/nunit#2869]
I currently have a static class which hosts a method to dynamically loads assemblies into the current AppDomain. In these assemblies, there are implimentations of an interface which is defined in a seperate assembly which is referenced by the test project. I would like the TestCaseSource function to generate an Enumerator of objects which are defined in the dynamically loaded assemblies.

The problem is that when I load the assemblies, regardless of TestCaseData being returned by the enumerator ( eg. return yield TestCaseData(12)  ) the tests are not created and no errors are reported.

I think this is potentially a bug in the framework?

**Comment by jnm2** [comment]
This doesn't sound right. If you are returning TestCaseData instances, I can't think of a way for NUnit to be ignoring them no matter what parameters you specify.

Can you show a repro so I can be sure of what your'e describing?

**Comment by rprouse** [comment]
I am closing old uncategorized issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
