### ISSUE TITLE
Start-time and end-time attributes with default time cause TFS failure

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2871]
TFS build has a Publish Test Results task which understands the NUnit 3 result format. It fails with the message, “Failed to publish test results: The value for the StartedDate property is not within the permissible values for it.”
I found a similar-looking issue (https://developercommunity.visualstudio.com/content/problem/196633) and it appears as though TFS chokes on the `start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z"` for each skipped test. (Skipped, as intended, because the tests are marked `[Explicit]`.)

I just tried a quick-n-dirty XSL transform which removed all start-time or end-time attributes with the value `0001-01-01 00:00:00Z` and TFS's Publish Test Results worked beautifully!

```xslt
<stylesheet version="1.0" xmlns="http://www.w3.org/1999/XSL/Transform">
    <template match="@start-time[string()='0001-01-01 00:00:00Z']|@end-time[string()='0001-01-01 00:00:00Z']" />

    <template match="@*|node()">
        <copy>
            <apply-templates select="@*|node()"/>
        </copy>
    </template>
</stylesheet>
```

So while this is definitely something that could be improved in TFS build, I can't help but wonder how much sense it makes to be outputting `start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z"` in the first place. Could we change our XML-writing code so that if StartTime and EndTime are default, we do not emit the attributes?

Our [`ITestResult.StartTime` and `EndTime` properties](https://github.com/nunit/nunit/blob/ffcfba9bdd85792f6aa32dada77a4b044857b4bf/src/NUnitFramework/framework/Interfaces/ITestResult.cs#L67-L81) are not nullable, so they default to `0001-01-01 00:00:00Z`.

https://github.com/nunit/nunit/blob/ffcfba9bdd85792f6aa32dada77a4b044857b4bf/src/NUnitFramework/framework/Internal/Results/TestResult.cs#L376-L377

**Comment by ChrisMaddock** [comment]
I think this is a duplicate of: https://github.com/nunit/nunit/issues/2339? 🙂

**Comment by jnm2** [comment]
Yes! Thanks, Chris!
