### ISSUE TITLE
Questions about custom attributes and SetUp/TearDown

### ISSUE THREAD

**Issue by unickq** [nunit/nunit#2875]
I have the following code:
```csharp
    class Sample
    {
        [Test]
        [My]
        public void Test()
        {
            Console.WriteLine("!!! I'm just a test");
        }

        [SetUp]
        public void SetUp()
        {
            Console.WriteLine("I'm SetUp");
        }

        [TearDown]
        public void TearDown()
        {
            Console.WriteLine("I'm TearDown");
        }

        [OneTimeSetUp]
        public void OneTimeSetup()
        {
            Console.WriteLine("I'm OneTimeSetUp");
        }

        [OneTimeTearDown]
        public void OneTimeTearDown()
        {
            Console.WriteLine("I'm OneTimeTearDown");
        }
    }


    public class MyAttribute : Attribute, ITestAction
    {
        public void BeforeTest(ITest test)
        {
            Console.WriteLine("MyAttribute before test");
        }

        public void AfterTest(ITest test)
        {
            Console.WriteLine("MyAttribute after test");
            var method = (TestMethod) test;
            var fixture = (TestFixture) test.Parent;
            Console.WriteLine($"Setup count = {method.SetUpMethods.Length}\n" +
                              $"Teardown count = {method.TearDownMethods.Length}\n" +
                              $"OnetimeSetup count = {fixture.OneTimeSetUpMethods.Length}\n" +
                              $"OneTimeTearDown count = {fixture.OneTimeTearDownMethods.Length}");
        }

        public ActionTargets Targets => ActionTargets.Test;
    }
```

When I execute it I get:

> I'm OneTimeSetUp
> I'm SetUp
> MyAttribute before test
> !!! I'm just a test
> MyAttribute after test
> **Setup count = 0**
> **Teardown count = 0**
> **OnetimeSetup count = 1**
> **OneTimeTearDown count = 1**
> I'm TearDown
> I'm OneTimeTearDown

So the question are:

1. Why SetUpMethods and TearDownMethods count is equal to 0 now?
2. Is there a way to execute SetUp/TearDown in BeforeTest/AfterTest?

Thanks in advance,
Nick

**Comment by CharliePoole** [comment]
1. Take a look at fixture.SetUpMethods and fixture.TearDownMethods.

2. You could obviously invoke them via reflection, but then they would run twice, which doesn't seem like a good idea and might break things.

**Comment by CharliePoole** [comment]
The first arg in each case is the __instance__ of the fixture, not a TestMethod or TestFixture, which are both internal NUnit classes. .NET reflection knows nothing about those classes. If you are doing this in a test somewhere, you need to access the current instance (this). Otherwise, you need to create an instance.

**Comment by unickq** [comment]
I see

Thanks a lot, @CharliePoole
