### ISSUE TITLE
Copy/paste error in Assert.That documentation

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2885]
Every time an Assert.That overload has `A ThrowsConstraint used in the test`, it should be replaced with `A Constraint expression to be applied` to be more consistent with the other Assert.That overloads (and more truthful).

Also, the summary should be updated the same way.

https://github.com/nunit/nunit/blob/5cfc6da2abb22f444913da0e6359ca8ec5e8aa24/src/NUnitFramework/framework/Assert.That.cs#L175-L181

**Comment by CharliePoole** [comment]
Doesn't the expression in the above example have to resolve to a throwsconstraint? If it doesn't, then you end up applying a constraint to the result of calling the delegate, which is void.

**Comment by jnm2** [comment]
Oh, I see. We don't require a ThrowsConstraint through. You could pass a custom contraint. And the delegate doesn't have to throw an exception. Besides Throws.Nothing, we might also be measuring the time.

Do you think we can be more specific than the changes I suggested?

**Comment by CharliePoole** [comment]
Maybe a "constraint expression that resolves to a constraint that can handle a TestDelegate". This is one of those things that could be a compiler error if constraints were fully generic.

**Comment by jnm2** [comment]
@CharliePoole `TestDelegate` would also work with a plain Is.Null or Is.NotNull. I'm not coming up with a valid way to say more than `A Constraint expression to be applied`.

**Comment by CharliePoole** [comment]
Only in a very limited definition of "work", however. :smile 

I don't have any very strong opinion on this but it is interesting.

**Comment by MhdTlb** [comment]
@jnm2  I can take this one

**Comment by jnm2** [comment]
@MhdTlb Great, thank you!

**Comment by jnm2** [comment]
I just had a thought and realized that `Assume.That`, `Warn.Unless` and `AssertionHelper.Expect` all have the same thing. @MhdTlb, do you mind doing the exact same replacement for those as well?

**Comment by MhdTlb** [comment]
done. 

@jnm2  I noticed that there is inconsistency  even after using  new summary. there is `A Constraint to be applied` and `A Constraint **expression** to be applied`. I hope that would be fine.

**Comment by jnm2** [comment]
Yes, that's great! Thank you for going ahead and taking care of that.

**Comment by mikkelbu** [comment]
Close via #2946.
