### ISSUE TITLE
Test appears using function name when using test case data. 

### ISSUE THREAD

**Issue by bcjdude** [nunit/nunit#2886]
**Using** 
- NUnit 3.10.1
- NUnit3TestAdapter 3.10.0

**Issue**
When using TestCaseSource attribute and using TestCaseData.SetName the original function name still appears in Test Explorer and is not run able.

```
        [TestCaseSource(typeof(TestSimpleClassCaseData), nameof(TestSimpleClassCaseData.AddTestCases))]
        public void TestAdd(int a, int b, int expected)
        {
            SimpleClass simpleClass = new SimpleClass();
            var output = simpleClass.Add(a, b);

            Assert.That(output, Is.EqualTo(expected));
        }
```
```
    public static class TestSimpleClassCaseData
    {
        public static IEnumerable<TestCaseData> AddTestCases
        {
            get
            {
                yield return new TestCaseData(10, 20, 30).SetName("TestSimpleClass - Add - 10, 20");
                yield return new TestCaseData(20, 30, 50).SetName("TestSimpleClass - Add - 20, 30");
            }
        }
    }
```
This will appear in Test Explore as 
![image](https://user-images.githubusercontent.com/6519423/41263663-392e8442-6d9d-11e8-9001-3edf38a9c94e.png)

**Expected Behavior**

- Only tests that are in test case source appear.

**Supporting Files**

- Solution with Projects: [SimpleNUnit.zip](https://github.com/nunit/nunit/files/2092151/SimpleNUnit.zip)

**Comment by mikkelbu** [comment]
This is the same problem as in #2866. The problem can be resolved by turning off "Discover Tests in real time..." (see https://github.com/nunit/nunit/issues/2866#issuecomment-391021951 for more info) and restarting VS. Unfortunately, VS is trying to interpret which testcases there are, but the result is not 100% correct.

I am going to close this issue. We have many similar issues in the adapter repository for tracking this sort of thing.
