### ISSUE TITLE
Assert.AreEqual with IConvertible values

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#2891]
I am using Assert.AreEqual (1, TestValue) where TestValue is a UInt128 which fully implements IConvertible:
``` 
public struct UInt128 : IComparable<UInt128>, IComparable, IEquatable<UInt128>, IFormattable, IConvertible
```

as wells as IComparable between itself and int.

This assert always fails:
```
  Expected: 1 (Int32)
  But was:  1 (UInt128)
```

Shouldn't NUnit use either the IComparable interface or the IConvertible interface when comparing these two values for equality?

**Comment by CharliePoole** [comment]
NUnit has always used the Equals override for equality. Beginning 8 or 10 years ago it also uses IEqualityComparer, if implemented.

**Comment by CharliePoole** [comment]
I've thought of that in the past but never implemented it. It could be the last thing tried in NUnitEqualityComparer.

An alternative would be to figure out a way to register the type as "numeric". Then it could be handled with other numeric and even tolerance would be supported.

Someone else will have to decide whether to accept this as s request, however.

**Comment by oznetmaster** [comment]
It is interesting that apparently, Assert.AreEqual (bool, bool) is not supported either?

Perhaps any type that implements IConvertible should be considered a Numeric, since by definition it can be converted to any of the primitive numeric types that are already considered Numeric?

So:
```
        public static bool IsNumericType(Object obj)
        {
            return IsFloatingPointNumeric(obj) || IsFixedPointNumeric(obj);
        }
```

would become:
```
        public static bool IsNumericType(Object obj)
        {
            return IsFloatingPointNumeric(obj) || IsFixedPointNumeric(obj) || obj is IConvertible;
        }
```
and the rest of Numerics would be changed appropriately.

**Comment by CharliePoole** [comment]
The conversion methods are permitted to throw an exception if the particular conversion is not supported, so that's a bit tricky. Are you thinking of doing a PR?

**Comment by oznetmaster** [comment]
If I do this, it would be in my CF version.  Backporting has become difficult.  I can certainly post my code and let someone else do a PR, or I can do the PR, but not test it except as part of the PR.  I do not have an environment which will let me test it on my system in the full NUnit build.

**Comment by CharliePoole** [comment]
I've had to do PRs s few times where I couldn't test locally so just relied on the CI build. It's a bit awkward but doable.

**Comment by rprouse** [comment]
I am closing old uncategorized issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
