### ISSUE TITLE
Order when parallel and not parallel fixtures together works wrong

### ISSUE THREAD

**Issue by Noksa** [nunit/nunit#2892]
See this project (here is my BIG QUESTION AND TROUBLE):
https://github.com/Noksa/Nunit-test/tree/master/TestParallelismInDiffClasses
When run this solution with --workers=1 log will be:
> => TestParallelismInDiffClasses.Tests.TestFixture1.Test in TestFixture1
Thread "10" => starting test...
Thread "10" => stopping test...
=> TestParallelismInDiffClasses.Tests.TestFixture2.Test in TestFixture2
Thread "10" => starting test...
Thread "10" => stopping test...
=> TestParallelismInDiffClasses.Tests.TestFixture3.Test1 in TestFixture3
Thread "10" => starting test...
Thread "10" => stopping test...
=> TestParallelismInDiffClasses.Tests.TestFixture3.Test2 in TestFixture3
Thread "10" => starting test...
And other cases...

Why i have this order?

Why not all test-cases in TestFixture3 runs first??

TestFixture3 runs last! But have Order(1)...
Run this with  --workers=1 and you will see.

This also reproduces with  test-cases from [TestCaseSource]

Also see Project: https://github.com/Noksa/Nunit-test

I
After run tests with --workers=3 in this project i recieved this log:

> => JustForTest.TestFixtureFirstNotParallelism.1 not parallel
Thread "9" => test started.
Thread "9" => test ended.
=> JustForTest.TestFixtureFirstParallel.1 parallel
Thread "12" => test started.
=> JustForTest.TestFixtureThreeParallel.3 parallel
Thread "11" => test started.
=> JustForTest.TestFixtureSecondParallel.2 parallel
Thread "10" => test started.
Thread "10" => test ended.
=> JustForTest.TestFixtureFirstParallel.1 parallel
Thread "12" => test ended.
=> JustForTest.TestFixtureThreeParallel.3 parallel
Thread "11" => test ended.
=> JustForTest.TestFixtureSecondNotParallelism.2 not parallel
Thread "9" => test started.
Thread "9" => test ended.

Why the tests are running at this order?

Why TestFixtureFirstNotParallelism runs first, but TestFixtureSecondNotParallelism last?? 😕 

In project next order:
TestFixtureThreeParallel - 1
TestFixtureSecondParallel - 2
**TestFixtureFirstNotParallelism - 3**
TestFixtureFirstParallel - 4
**TestFixtureSecondNotParallelism - 5**

Run tests with this command: nunit3-console TestParallelismOrder.dll --workers=3

In my opinion, it should be like this:

First run in two threads TestFixtureThreeParallel and TestFixtureSecondParallel
Then the framework waits for their execution.
Then it starts up  TestFixtureFirstNotParallelism
Then the framework awaits execution.
After that, TestFixtureFirstParallel starts
Then the framework awaits execution.
After that, TestFixtureSecondNotParallelism starts.

It turns out that I can not combine test fixtures with [Parallelizable] and [NotParallelizable] attributes with order, but my general question now about first project - why all test-cases/testcasesource not run first in testfixture with order(1)

**Comment by Noksa** [comment]
Second option to reproduce, more shorter:

```
[Parallelizable(ParallelScope.Fixtures)]
    [Order(3)]
    public class TestFixtureFirstParallel : BeforeAfter
    {
        [TestCase(TestName = "1 parallel")]
        public void Test()
        {
            Thread.Sleep(3000);
        }
    }
    
    [Order(1)]
    public class TestFixtureFirstNotParallelism : BeforeAfter
    {
        [TestCase(TestName = "1 not parallel")]
        public void Test()
        {
            Thread.Sleep(3000);
        }
    }

    [Order(2)]
    public class TestFixtureSecondNotParallelism : BeforeAfter
    {
        [TestCase(TestName = "2 not parallel")]
        public void Test()
        {
            Thread.Sleep(3000);
        }
    }
```

If run with command: --workers=1
log will be:

> => JustForTest.TestFixtureFirstNotParallelism.1 not parallel
Thread "9" => test started.
Thread "9" => test ended.
=> JustForTest.TestFixtureFirstParallel.1 parallel
Thread "10" => test started.
Thread "10" => test ended.
=> JustForTest.TestFixtureSecondNotParallelism.2 not parallel
Thread "9" => test started.
Thread "9" => test ended.

Why order broken?

**Comment by Noksa** [comment]
Or see this project: https://github.com/Noksa/Nunit-test/tree/master/TestParallelismInDiffClasses

> => TestParallelismInDiffClasses.Tests.TestFixture1.Test in TestFixture1
Thread "10" => starting test...
Thread "10" => stopping test...
=> TestParallelismInDiffClasses.Tests.TestFixture2.Test in TestFixture2
Thread "10" => starting test...
Thread "10" => stopping test...
=> TestParallelismInDiffClasses.Tests.TestFixture3.Test1 in TestFixture3
Thread "10" => starting test...
Thread "10" => stopping test...
=> TestParallelismInDiffClasses.Tests.TestFixture3.Test2 in TestFixture3
Thread "10" => starting test...
^C


Why i have this order???

Why not all test-cases in TestFixture3 runs first??

TestFixture3 runs last! But have Order(1)...

**Comment by CharliePoole** [comment]
@Noksa I have always explained the `OrderAttribute` as being only a suggestion to NUnit of the order in which tests are to be started. If you are running in parallel, with four threads and have three tests with order 1, 2, 3, then all three of them will be started and they will run together.

The reason for this limitation is that we have long wanted to develop a Dependency attribute, which would constrain tests to only start __after some other test completed__. We implemented `OrderAttribute` as a workaround for the (non-existent) dependency attribute and it works quite well so long as only one thread is involved. So, I'm afraid you are expecting more of `OrderAttribute` than it was ever designed to give you. 😞 

OTOH, you have pointed out something particular here, which I think we should document. Once NUnit is running parallel tests, it will keep running them until there are no more and then switch to non-parallel tests. If it's running non-parallel tests, it will finish those first. That's intrinsic to the design and we explain it in the docs.

@nunit/framework-team I haven't marked this, but I believe it's a documentation issue.

**Comment by Noksa** [comment]
@CharliePoole 
Thanks for the quick response!
About the fact that all three tests will be launched simultaneously if the threads count are 3 or more is understandable.

But what about this case? Why in this case,  test-cases in TestFixture3 are not started at first? 
How many threads are not important.
If you specify only one thread, nunit will still run first not Order(1) Fixture.
See log please. I run all tests in single thread, but why order is not as expected?

> => **TestParallelismInDiffClasses.Tests.TestFixture1.Test in TestFixture1**
> Thread "10" => starting test...
> Thread "10" => stopping test...
> => **TestParallelismInDiffClasses.Tests.TestFixture2.Test in TestFixture2**
> Thread "10" => starting test...
> Thread "10" => stopping test...
> => **TestParallelismInDiffClasses.Tests.TestFixture3.Test1 in TestFixture3**
> Thread "10" => starting test...
> Thread "10" => stopping test...
> => **TestParallelismInDiffClasses.Tests.TestFixture3.Test2 in TestFixture3**
> Thread "10" => starting test...

I expect that at first all test-cases from method "Test" at TestFixture3 (because order = 1) will be run one by one , and after this - TestFixture1 and TestFixture2... 
But not. 
Real order is:
TestFixture1
TestFixture2
TestFixture3.

Expected order is:
Test-cases from TestFixture3
TestFixture1
TestFixture3.

Why?

Code:

```
using System.Threading;
using NUnit.Framework;

// ReSharper disable once CheckNamespace
namespace TestParallelismInDiffClasses.Tests
{
    [Parallelizable(ParallelScope.Fixtures)]
    [Order(2)]
    public class TestFixture1 : BeforeAfter
    {

        [TestCase(TestName = "Test in TestFixture1")]
        public void Test()
        {
            Thread.Sleep(3000);
        }
    }


[Parallelizable(ParallelScope.Fixtures)]
    public class TestFixture2 : BeforeAfter
    {
        [TestCase(TestName = "Test in TestFixture2")]
        public void Test()
        {
            Thread.Sleep(3000);
        }
    }

[Parallelizable(ParallelScope.Fixtures)]
    [Order(1)]
    public class TestFixture3 : BeforeAfter
    {

        [TestCase(TestName = "Test1 in TestFixture3")]
        [TestCase(TestName = "Test2 in TestFixture3")]
        [TestCase(TestName = "Test3 in TestFixture3")]
        [TestCase(TestName = "Test4 in TestFixture3")]
        [TestCase(TestName = "Test5 in TestFixture3")]
        [TestCase(TestName = "Test6 in TestFixture3")]
        [TestCase(TestName = "Test7 in TestFixture3")]
        [TestCase(TestName = "Test8 in TestFixture3")]
        [TestCase(TestName = "Test9 in TestFixture3")]
        [TestCase(TestName = "Test10 in TestFixture3")]
        [Parallelizable(ParallelScope.All)]
        public void Test()
        {
            Thread.Sleep(3000);
        }
    }
}
```

**Comment by Noksa** [comment]
@CharliePoole 
Also, about it:

> OTOH, you have pointed out something particular here, which I think we should document. Once NUnit is running parallel tests, it will keep running them until there are no more and then switch to non-parallel tests. If it's running non-parallel tests, it will finish those first. That's intrinsic to the design and we explain it in the docs.

As u can see at start post, I have next order when run test at multi threads:

> => JustForTest.TestFixtureFirstNotParallelism.1 not parallel
Thread "9" => test started.
Thread "9" => test ended.
=> JustForTest.TestFixtureFirstParallel.1 parallel
Thread "12" => test started.
=> JustForTest.TestFixtureThreeParallel.3 parallel
Thread "11" => test started.
=> JustForTest.TestFixtureSecondParallel.2 parallel
Thread "10" => test started.
Thread "10" => test ended.
=> JustForTest.TestFixtureFirstParallel.1 parallel
Thread "12" => test ended.
=> JustForTest.TestFixtureThreeParallel.3 parallel
Thread "11" => test ended.
=> JustForTest.TestFixtureSecondNotParallelism.2 not parallel
Thread "9" => test started.
Thread "9" => test ended.


So, here is order:
1) Nonparallel test 
2) Several parallel tests 
3) Another nonparallel test.

But how u saying, NUnit will run all nonparallel tests until they are no more and only after this switch to parallel. 
What you can say about it? Why it happening?

**Comment by CharliePoole** [comment]
@Noksa You should take the main answer to be "Order is not effective when used with parallel tests."

The details are interesting (to me as well) but once you accept not to use order with parallel tests __except in certain conditions__* I think life becomes easier. 😄 

Now... for the details of why your tests run in the exact order they do... If you specify `--trace=Info` on the command-line, we will get detailed information about how and why each test ran exactly when it did. I'd be interested in seeing that.

I'd also be interested to know if it changes anything to remove the scope args from your `ParallelizableAttributes`. In particular, the `ParallelScope.FIxture` argument is not normally placed on a fixture, but at the assembly level. That's because it means "run any child fixtures in parallel" and there are no child fixtures. I admit this too could be better documented!

**Comment by Noksa** [comment]
Thanks for answer.
I’ll will back after weekend with next information :)

**Comment by Noksa** [comment]
@CharliePoole 
Hello again! :)
I hope your weekend went through as well as mine.

1)
I added the --trace=Info argument, but nothing changed in the console log:

> C:\..\TestParallelismInDiffClasses\bin\Debug>nunit3-console TestParallelismInDiffClasses.dll --trace=Info --workers=1
NUnit Console Runner 3.8.0
Copyright (c) 2018 Charlie Poole, Rob Prouse
Runtime Environment
   OS Version: Microsoft Windows NT 10.0.16299.0
  CLR Version: 4.0.30319.42000
Test Files
    TestParallelismInDiffClasses.dll
=> TestParallelismInDiffClasses.Tests.TestFixture1.Test in TestFixture1
Thread "9" => starting test...
Thread "9" => stopping test...
=> TestParallelismInDiffClasses.Tests.TestFixture2.Test in TestFixture2
Thread "9" => starting test...
Thread "9" => stopping test...
=> TestParallelismInDiffClasses.Tests.TestFixture3.Test1 in TestFixture3
Thread "9" => starting test...
Thread "9" => stopping test...
=> TestParallelismInDiffClasses.Tests.TestFixture3.Test2 in TestFixture3
Thread "9" => starting test...
Thread "9" => stopping test...
=> TestParallelismInDiffClasses.Tests.TestFixture3.Test3 in TestFixture3
Thread "9" => starting test...
Thread "9" => stopping test...
=> TestParallelismInDiffClasses.Tests.TestFixture3.Test4 in TestFixture3
Thread "9" => starting test...
Thread "9" => stopping test...
=> TestParallelismInDiffClasses.Tests.TestFixture3.Test5 in TestFixture3
Thread "9" => starting test...
Thread "9" => stopping test...
=> TestParallelismInDiffClasses.Tests.TestFixture3.Test6 in TestFixture3
Thread "9" => starting test...
Thread "9" => stopping test...
=> TestParallelismInDiffClasses.Tests.TestFixture3.Test7 in TestFixture3
Thread "9" => starting test...
Thread "9" => stopping test...
=> TestParallelismInDiffClasses.Tests.TestFixture3.Test8 in TestFixture3
Thread "9" => starting test...
Thread "9" => stopping test...
=> TestParallelismInDiffClasses.Tests.TestFixture3.Test9 in TestFixture3
Thread "9" => starting test...
Thread "9" => stopping test...
=> TestParallelismInDiffClasses.Tests.TestFixture3.Test10 in TestFixture3
Thread "9" => starting test...
Thread "9" => stopping test...
Run Settings
    DisposeRunners: True
    InternalTraceLevel: Info
    WorkDirectory: C:\..\TestParallelismInDiffClasses\bin\Debug
    NumberOfTestWorkers: 1
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.7.1
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
Test Run Summary
  Overall result: Passed
  Test Count: 12, Passed: 12, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2018-06-18 05:06:01Z
    End time: 2018-06-18 05:06:37Z
    Duration: 36.591 seconds
Results (nunit3) saved as TestResult.xml


2) I deleted all Scope args from everywhere, and now the order has changed a little.

Code now looks like this:
```
using System.Threading;
using NUnit.Framework;

// ReSharper disable once CheckNamespace
namespace TestParallelismInDiffClasses.Tests
{
    [**Parallelizable**]
    [Order(2)]
    public class TestFixture1 : BeforeAfter
    {

        [TestCase(TestName = "Test in TestFixture1")]
        public void Test()
        {
            Thread.Sleep(3000);
        }
    }


    [**Parallelizable**]
    public class TestFixture2 : BeforeAfter
    {
        [TestCase(TestName = "Test in TestFixture2")]
        public void Test()
        {
            Thread.Sleep(3000);
        }
    }

    [**Parallelizable**]
    [Order(1)]
    public class TestFixture3 : BeforeAfter
    {

        [TestCase(TestName = "Test1 in TestFixture3")]
        [TestCase(TestName = "Test2 in TestFixture3")]
        [TestCase(TestName = "Test3 in TestFixture3")]
        [TestCase(TestName = "Test4 in TestFixture3")]
        [TestCase(TestName = "Test5 in TestFixture3")]
        [TestCase(TestName = "Test6 in TestFixture3")]
        [TestCase(TestName = "Test7 in TestFixture3")]
        [TestCase(TestName = "Test8 in TestFixture3")]
        [TestCase(TestName = "Test9 in TestFixture3")]
        [TestCase(TestName = "Test10 in TestFixture3")]
        [**Parallelizable**]
        public void Test()
        {
            Thread.Sleep(3000);
        }
    }
}
```

When running tests in two threads, the console log looks like this:

> C:\Users\a.danilin\source\repos\Nunit-test\TestParallelismInDiffClasses\TestParallelismInDiffClasses\bin\Debug>nunit3-console TestParallelismInDiffClasses.dll --trace=Info --workers=2

> => TestParallelismInDiffClasses.Tests.TestFixture1.Test in TestFixture1
Thread "10" => starting test...
=> TestParallelismInDiffClasses.Tests.TestFixture3.Test1 in TestFixture3
Thread "9" => starting test...
=> TestParallelismInDiffClasses.Tests.TestFixture1.Test in TestFixture1
Thread "10" => stopping test...
=> TestParallelismInDiffClasses.Tests.TestFixture3.Test1 in TestFixture3
Thread "9" => stopping test...
=> TestParallelismInDiffClasses.Tests.TestFixture3.Test2 in TestFixture3
Thread "9" => starting test...
=> TestParallelismInDiffClasses.Tests.TestFixture2.Test in TestFixture2
Thread "10" => starting test...
=> TestParallelismInDiffClasses.Tests.TestFixture3.Test2 in TestFixture3
Thread "9" => stopping test...
=> TestParallelismInDiffClasses.Tests.TestFixture3.Test3 in TestFixture3
Thread "9" => starting test...
=> TestParallelismInDiffClasses.Tests.TestFixture2.Test in TestFixture2
Thread "10" => stopping test...
=> TestParallelismInDiffClasses.Tests.TestFixture3.Test3 in TestFixture3
Thread "9" => stopping test...
=> TestParallelismInDiffClasses.Tests.TestFixture3.Test4 in TestFixture3
Thread "9" => starting test...
Thread "9" => stopping test...
=> TestParallelismInDiffClasses.Tests.TestFixture3.Test5 in TestFixture3
Thread "9" => starting test...
Thread "9" => stopping test...
=> TestParallelismInDiffClasses.Tests.TestFixture3.Test6 in TestFixture3
Thread "9" => starting test...
Thread "9" => stopping test...
=> TestParallelismInDiffClasses.Tests.TestFixture3.Test7 in TestFixture3
Thread "9" => starting test...
Thread "9" => stopping test...
=> TestParallelismInDiffClasses.Tests.TestFixture3.Test8 in TestFixture3
Thread "9" => starting test...
Thread "9" => stopping test...
=> TestParallelismInDiffClasses.Tests.TestFixture3.Test9 in TestFixture3
Thread "9" => starting test...
Thread "9" => stopping test...
=> TestParallelismInDiffClasses.Tests.TestFixture3.Test10 in TestFixture3
Thread "9" => starting test...
Thread "9" => stopping test...

As you can see, the launch order has changed.

But I still do not understand how to make it so that all the test cases from the test method "Test" from the TestFixture3 were run first, and then the rest?

If I specify Scope Arg == All in the test method, then the order will again look like the previous one - i.e. first started tests from TestFixture1 and 2.

**Comment by Noksa** [comment]
@CharliePoole 
This post about [this comment](https://github.com/nunit/nunit/issues/2892#issuecomment-397693489)

Here is trace log:

> InternalTrace: Initializing at level Info
08:33:55.058 Info  [ 5] DefaultTestAssemblyRunner: Running tests
08:33:55.064 Info  [ 5] Dispatcher: Initializing with 3 workers
08:33:55.081 Info  [ 5] WorkShift: NonParallel shift starting
08:33:55.082 Info  [ 5] TestWorker: NonParallelWorker starting on thread [8]
08:33:55.083 Info  [ 5] WorkItemQueue: NonParallelQueue.0 starting
08:33:55.084 Info  [ 8] TestWorker: NonParallelWorker executing TestParallelismOrder.dll
08:33:55.108 Info  [ 8] TestWorker: NonParallelWorker executing TestFixtureSecondNotParallelism
08:33:55.109 Info  [ 8] Dispatcher: Saving Queue State for TestFixtureSecondNotParallelism
08:33:55.110 Info  [ 8] WorkItemQueue: NonParallelQueue.1 starting
08:33:58.132 Info  [ 8] TestWorker: NonParallelWorker executing TestFixtureSecondNotParallelism OneTimeTearDown
08:33:58.133 Info  [ 8] WorkShift: NonParallel shift ending
08:33:58.134 Info  [ 8] Dispatcher: Restoring Queue State
08:33:58.135 Info  [ 8] WorkShift: Parallel shift starting
08:33:58.135 Info  [ 8] TestWorker: ParallelWorker#1 starting on thread [9]
08:33:58.139 Info  [ 8] TestWorker: ParallelWorker#2 starting on thread [10]
08:33:58.139 Info  [ 8] TestWorker: ParallelWorker#3 starting on thread [11]
08:33:58.139 Info  [ 8] TestWorker: ParallelSTAWorker starting on thread [12]
08:33:58.139 Info  [ 8] WorkItemQueue: ParallelQueue.0 starting
08:33:58.139 Info  [ 8] WorkItemQueue: ParallelSTAQueue.0 starting
08:33:58.139 Info  [ 9] TestWorker: ParallelWorker#1 executing TestFixtureFirstParallel
08:33:58.139 Info  [10] TestWorker: ParallelWorker#2 executing TestFixtureThreeParallel
08:33:58.139 Info  [11] TestWorker: ParallelWorker#3 executing TestFixtureSecondParallel
08:34:01.141 Info  [10] TestWorker: ParallelWorker#2 executing TestFixtureFirstParallel OneTimeTearDown
08:34:01.141 Info  [10] WorkShift: Parallel shift ending
08:34:01.141 Info  [10] WorkShift: NonParallel shift starting
08:34:01.141 Info  [10] WorkItemQueue: NonParallelQueue.0 starting
08:34:01.141 Info  [ 8] TestWorker: NonParallelWorker executing TestFixtureFirstNotParallelism
08:34:01.141 Info  [ 8] Dispatcher: Saving Queue State for TestFixtureFirstNotParallelism
08:34:01.141 Info  [ 8] WorkItemQueue: NonParallelQueue.1 starting
08:34:01.141 Info  [ 9] TestWorker: ParallelWorker#1 executing TestFixtureSecondParallel OneTimeTearDown
08:34:01.141 Info  [ 9] WorkShift: Parallel shift ending
08:34:01.141 Info  [11] TestWorker: ParallelWorker#3 executing TestFixtureThreeParallel OneTimeTearDown
08:34:04.142 Info  [ 9] WorkShift: NonParallel shift starting
08:34:04.142 Info  [ 9] WorkItemQueue: NonParallelQueue.1 starting
08:34:04.142 Info  [ 8] TestWorker: NonParallelWorker executing TestFixtureFirstNotParallelism OneTimeTearDown
08:34:04.142 Info  [11] WorkShift: Parallel shift ending
08:34:04.142 Info  [11] Dispatcher: Restoring Queue State
08:34:04.143 Info  [11] WorkItemQueue: ParallelQueue.0 stopping - 6 WorkItems processed
08:34:04.143 Info  [11] WorkItemQueue: ParallelSTAQueue.0 stopping - 0 WorkItems processed
08:34:04.143 Info  [ 9] TestWorker: ParallelWorker#1 stopping - 2 WorkItems processed.
08:34:04.143 Info  [11] WorkItemQueue: NonParallelQueue.0 stopping - 5 WorkItems processed
08:34:04.143 Info  [10] TestWorker: ParallelWorker#2 stopping - 2 WorkItems processed.
08:34:04.143 Info  [11] WorkItemQueue: NonParallelSTAQueue.0 stopping - 0 WorkItems processed
08:34:04.143 Info  [11] TestWorker: ParallelWorker#3 stopping - 2 WorkItems processed.
08:34:04.144 Info  [12] TestWorker: ParallelSTAWorker stopping - 0 WorkItems processed.
08:34:04.148 Info  [ 8] WorkShift: NonParallel shift ending
08:34:04.148 Info  [ 8] WorkItemQueue: ParallelQueue.0 stopping - 6 WorkItems processed
08:34:04.148 Info  [ 8] WorkItemQueue: ParallelSTAQueue.0 stopping - 0 WorkItems processed
08:34:04.148 Info  [ 8] WorkItemQueue: NonParallelQueue.0 stopping - 5 WorkItems processed
08:34:04.148 Info  [ 8] WorkItemQueue: NonParallelSTAQueue.0 stopping - 0 WorkItems processed
08:34:04.148 Info  [ 8] TestWorker: NonParallelWorker stopping - 5 WorkItems processed.

**Comment by Noksa** [comment]
A little more information.

I tried a lot of options.

At the moment, the only working option - provided that the test fixtures will not run in parallel (have `[NonParallelizable]` attribute or have `[Parallelizable(ParallelScope.Children)]` - in this case, you can build the order of parallel run tests within each test fixture.

If the fixtures are run in parallel, then the order becomes chaotic.

Why, when the fixtures is parallel, it does not at first start all the tests in parallel, which are in the fixture with the order 1 - this remains a mystery to me.

**Comment by CharliePoole** [comment]
@Noksa As already explained, it's not possible for NUnit to do what you want. When NUnit runs a fixture (either parallel or non-parallel) it does not yet know how the tests within that fixture may be run. A parallel fixture may contain non-parallel tests. A non-parallel fixture may contain parallel tests.

NUnit only discovers how the tests in a fixture are to be run after it has run the OneTimeSetUp for the fixture. At the time it does that, all the tests are added to the proper queue (P or nonP) so they can be run when a worker is available to run them.

IOW, Order on a fixture only controls when the fixture starts to run. Other factors contribute to when the tests within that fixture execute and those factors are out of your control.

For that reason, OrderAttribute on a fixture is not terribly useful when running tests in parallel. It becomes even less useful when some fixtures are parallel and some are not, as in your example.

**Comment by Noksa** [comment]
@CharliePoole 
Thanks for answer.
I will think about how to get around this problem without waiting Dependency attribute 😄

**Comment by Noksa** [comment]
@CharliePoole 
But the OrderAttribute inside the Test Fixture will still work, at the level of methods?

**Comment by CharliePoole** [comment]
The situation with methods is similar to that with fixtures. If all the methods in a fixture are either parallel or non-parallel, then they will start running in the order specified. But if there is a mixture of paralell and non-parallel methods, the order will appear random.

The key is that any test (fixture or method) is added to proper execution queue (P or nonP) in the order specified. But the order will not cause NUnit to switch queues.

**Comment by Noksa** [comment]
@CharliePoole 
Thank you, now I understand how everything works.
