### ISSUE TITLE
NUnitLite not reporting to TeamCity correctly

### ISSUE THREAD

**Issue by martin-frydl** [nunit/nunit#2902]
I'm using NUnitLite with --teamcity option to integrate with TeamCity. I have multiple tests in various namespaces in my test assembly. NUnit is reporting test suites and tests incorrectly resulting it completely useless results in TeamCity.

Let's have following three classes:
```
namespace A.B {
  [TestFixture]
  public class Test1 {
    [Test]
    public void T1() {}
  }
}

namespace A.B.C {
  [TestFixture]
  public class Test2 {
    [Test]
    public void T2() {}
  }
}

namespace A.B.D {
  [TestFixture]
  public class Test3 {
    [Test]
    public void T3() {}
  }
}
```

This means I have test classes A.B.Test1 with method T1, A.B.C.Test2 with method T2 and A.B.D.Test3 with method T3. Now when run with --teamcity option, NUnit begins to report:

```
##teamcity[testSuiteStarted name='TestLib.DLL']
##teamcity[testSuiteStarted name='A']
##teamcity[testSuiteStarted name='B']
##teamcity[testSuiteStarted name='C']
##teamcity[testSuiteStarted name='D']
##teamcity[testSuiteStarted name='Test1']
##teamcity[testStarted name='T1' captureStandardOutput='true']
##teamcity[testFinished name='T1' duration='19']
##teamcity[testSuiteFinished name='Test1']
...
```
The problem is that it first reports all namespaces in which there are some tests in assembly and then starts to report individual test classes and tests. But this time without namespace. TeamCity interprets this like test T1 in suite "TestLib.DLL: A: B: C: D: Test1", which is incorrect (and also strange). With old NUnit TeamCity reported Test1.T1 in suite "TestLib.DLL: A.B"

I've traced the problem inside NUnit and it looks like it walks through all the tests at the beginning and fires TestStartedEvent for each namespace component it finds, in parallel. Then it probably somehow serializes test execution because I have just one worker.

**Comment by botinko** [comment]
I have the same problem

**Comment by rprouse** [comment]
Closing, we will be removing NUnitLite TeamCity support in #3759
