### ISSUE TITLE
Any alternatives to Timeout Attribute for .NET core?

### ISSUE THREAD

**Issue by kuskmen** [nunit/nunit#2907]
Hi guys,

I saw in docs that Timeout attribute is not supported for .NET core, however I do need it, is there any alternative I can use while it is ported? Or maybe help me out on the reason of not being ported and I can see if I can prepare pull request :)

Regards,
kuskmen

**Comment by ChrisMaddock** [comment]
Take a look at https://github.com/nunit/nunit/issues/1638 - we're very much after help in porting this attribute!

The reason it's not been done already, is that we also support .NET 2.0 - and the `Thread.Abort()` API used for this functionality in .NET 2 isn't available in the netstandard builds. Writing a Task-based version of the functionality shouldn't be too hard though - it's something I've wanted to do myself for a while, but not got round to!

I'll close this issue in favour of the one linked above - but we'd love a pull request for this! Just add a comment on https://github.com/nunit/nunit/issues/1638 claiming it, if you're up for it. 😄

**Comment by abbotware** [comment]
https://github.com/abbotware/nunit-timeout  <- look a simple work around!
