### ISSUE TITLE
Obtain a list of tests (accounting for generated testcases)

### ISSUE THREAD

**Issue by masaeedu** [nunit/nunit#2914]
Is there a way to get a list of all testcases during `OneTimeSetup` (accounting for all possible mechanisms that can generate testcases such as `TestCaseSource`, `Combinatorial`, etc.)? I'm doing snapshot testing and need to prune the snapshot list when testcases are renamed or deleted.

Ideally I'd simply be able to get an `IEnumerable<TestContext>` to be able to read testcase names and argument objects.

**Comment by CharliePoole** [comment]
Test Contexts are created knot when the test runs and destroyed afterwards.

At the time one time setup is running, the tests exist but commands, work items and contexts do not.

I could tell you how to get a list of the names of the tests but (1) you would be relying on internal implementation details that may change and (2) you can't "prune" them at that point.

**Comment by masaeedu** [comment]
> At the time one time setup is running, the tests exist but commands, work items and contexts do not.

I only need an immutable representation of what tests exist, I don't need to do anything with them.

> you can't "prune" them at that point

I've run into this confusion in the gitter as well. What I'm pruning is a snapshot file (which nunit doesn't know or care about), not nunit's representation of what tests it's going to run.

**Comment by CharliePoole** [comment]
Look at NUnit.Framework.Internal.TestExecutionContext.CurrentContext.CurrentTest. As the namespace indicates, this is an internal class but we make it public for use by custom attributes and such. Good opportunity to break things if you were to change anything in it. 😄 

Property `Tests` is a list of child tests of the fixture. (I'm assuming you started in the one time setup of a test fixture, not a setup fixture). You can recursively examine those tests to find all test cases and get there names that way.

Marking this as an answered question, but feel free to ask followup questions here.

**Comment by masaeedu** [comment]
> I'm assuming you started in the one time setup of a test fixture, not a setup fixture

I need to do this once across the entire test assembly, not per-fixture; would this approach still work if I did this in a `[Setup]` fixture?

**Comment by CharliePoole** [comment]
Yes, an assembly-level SetUpFixture would have access to all the test cases. You'd just have a lot more recursion to do to find the test cases. Doing it once sounds much cleaner as well.

Note that the initial `CurrentTest` is a `Test`, while the child tests are all `ITests`. If you need some particular Type within NUnit, just cast.

**Comment by masaeedu** [comment]
Ah, ok. I think this should do it:

```c#
    [SetUpFixture]
    public class ApprovalSetup
    {
        public static IEnumerable<ITest> GetDescendants(ITest test)
            => test.Tests.Concat(test.Tests.SelectMany(GetDescendants));

        [OneTimeSetUp]
        public static void Setup()
        {
            var allTests = GetDescendants(TestExecutionContext.CurrentContext.CurrentTest).ToList();
            Console.WriteLine("durr");
        }
    }
```

**Comment by CharliePoole** [comment]
But you're getting suites as well as test cases contained within them. They're all tests in NUnit terminology but I understood you to actually want test cases.

**Comment by CharliePoole** [comment]
Clarifying: there's no guarantee that the leaf nodes in the tree of tests are test cases. They could be fixtures with no tests in them or invalid methods with no cases.

**Comment by masaeedu** [comment]
@CharliePoole Is there some subtype of `ITest` that I can filter for to get only "actual tests" (can't think of a better word for this, sorry).

**Comment by masaeedu** [comment]
If I do `GetDescendants(setupFixture).OfType<TestMethod>().ToList();`, it seems like I get the same number of tests as are discovered by `dotnet test -t`. Are there any circumstances where this might not be the case?

**Comment by CharliePoole** [comment]
It's because you don't have either of the two unusual situations I described. But NUnit is designed to run even if some of your tests are invalid.

Most likely, all you need to do is check the `IsSuite` property and ensure that you only end up with tests where it's false. Alternatively, use a more verbose version of GetDescendants that only tries to recurse when `IsSuite` is true.

**Comment by maettu-this** [comment]
For others who happen to get here, #3627 has some more input on the topic.
