### ISSUE TITLE
Missing Screenshot attachment in VSTS but see a path in .trx

### ISSUE THREAD

**Issue by charleshamel73** [nunit/nunit#2918]
Hello,
I am currently working with:
VSTestV2
VSTS 
Visual Studio 2017
NUnit 3.10.*

While using the `TestContext.AddTestAttachment(fullFilePath)` function, I see an attachment within the .trx file but that attachment isn't shown within test attachments page. I have tried to fix the path to be the test run settings but nothing is working. I have attached a screenshot of the Code and the Attachments Page without the attached screenshot
```csharp
 if (TestContext.CurrentContext.Result.Outcome != ResultState.Success)
 {
     String baseTestDir = TestContext.CurrentContext.WorkDirectory;
     if ( environment.HasEnvironmentValue("SYSTEM_DEFAULTWORKINGDIRECTORY"))
     {
         baseTestDir = String.Format("{0}\\TestResults",environment.GetEnvironmentValue("SYSTEM_DEFAULTWORKINGDIRECTORY"));
     }
     String fullFilePath = String.Format("{0}\\{1}.png", baseTestDir, TestContext.CurrentContext.Test.FullName);
     log.Info(String.Format("Test has failed. Taking Screenshot and writing it to '{0}'", fullFilePath));
     Screenshot screenshot = driver.GetScreenshot();
     screenshot.SaveAsFile(fullFilePath, ScreenshotImageFormat.Png);
     TestContext.AddTestAttachment(fullFilePath);
 }
```

Anyone have any idea what I might be missing?

**Comment by mikkelbu** [comment]
Hi @charleshamel73. I don't think I can help you, as I know very little about VSTestV2 and VSTS, but I just wanted you to tell you that I've edited the code blocks to make them read nicer (by using [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/)).

**Comment by CharliePoole** [comment]
@charleshamel73 This seems to be an issue for the NUnit 3 VS adapter, rather than the framework. We can move it there so the right people see it if you agree.

**Comment by charleshamel73** [comment]
Yes That would be great if you could. Even if this is just a problem on my end, i would like other users to at least be able to refer to this thread and be able to find a solution

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit3-vs-adapter #526](https://github.com/nunit/nunit3-vs-adapter/issues/526) via [**ZenHub**](https://www.zenhub.com/)
