### ISSUE TITLE
Improve error message on EmptyConstraint

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#2928]
When EmptyConstraint is used on the incorrect type, it throws the following exception:

```
throw new System.ArgumentException("The actual value must be a string or a non-null IEnumerable or DirectoryInfo", nameof(actual));
```

When chaining constraints, I sometimes hit this error message because of problems in my chaining, where I'm actually testing against a different type to the one I think I am. It would be useful if this error message included the type of `actual` which caused the exception - so the user can better debug where the problem in their chaining lies.

Ideally, whoever contributes this functionality would also add a corresponding unit test! There may already be something there - I haven't checked. 🙂

**Comment by nisha-kaushik** [comment]
Hey, I want to pick this up for contribution. Can you please explain it with some example.

**Comment by ChrisMaddock** [comment]
@nisha-kaushik Great! 

Take a look at this pull request below, where I made a very similar change to PropertyConstraint, to the one we want to make to EmptyConstraint. Do you want to have a go at a similar change to EmptyConstraint, and then put up a pull request, and we can work from there?

https://github.com/nunit/nunit/pull/2739

I've assigned this issue to myself to keep an eye on - let us know if you have any further questions, and we'll help where we can! 👍

**Comment by nisha-kaushik** [comment]
Thanks @ChrisMaddock I made some changes in pull request [2961](Improve error message on EmptyConstraint #2961).

Please Let me know in case of changes.
