### ISSUE TITLE
Using `Is.EqualTo(obj).Using(comparer)` does not test for equality and is misleading

### ISSUE THREAD

**Issue by fourpastmidnight** [nunit/nunit#2930]
I was looking at how to extend NUnit so that I could customize how the error messages are displayed when equality is determined for my object. What I would like to see is:

> Expected: Property 'MyProperty' to be 0
> But was: 1

instead of

> Expected: <Full.Namespace.Path.To.Type.MyCustomType>
> Actual: <Full.Namespace.Path.To.Type.MyCustomType>

which is less than useful because I have no clue in what ways these two objects are different from one another. And I didn't want to have a test method with a whole slew of separate `Assert.That(...)` calls, one for each property on the object. So that's what lead me to begin my trek through NUnit's code to best determine how I might most effectively achieve this goal.

While looking around NUnit's code to see how the existing equality constraint is written and how I might extend it (or if need be, create my own custom constraint), I came across the fact that the `EqualityConstraint` seems to delegate a lot of its responsibility to `EqualityAdapter`s and `EqualityComparer`s. It looked as though I may not need to write my own custom equality constraint, but may be able to add a derived `EqualityAdapter`. Alas, that is not the case. The collection of `EqualityAdapter`s are hidden away inside of the constraint and there is no extensibility mechanism other than your type implementing `IComparable`, `IComparable<T>`, or having an implementation of `IComparison` or `IComparison<T>` for your type in order to use something along the lines of:

```
Assert.That(myActualObject, Is.EqualTo(myExpectedObject).Using(MyObject.DefaultComparer))
```

However, this does not do what one would assume it does. Even though the assertion says `Assert.That(myObject, Is.EqualTo....)` that is _NOT_ what that code is doing. It is not testing for equality at all! Looking into the `EqualityConstraint.Using<T>(IComparison<T> comparer)` method overload, it adds  an instance of an `EqualityAdapter` to its private `ExternalComparers` collection (and, this should've been a clue that something was amiss--the name of the private backing field for the `ExternalAdapters` property is `equalityComparers`, not `equalityAdapters`...). Diving into the `EqualityAdapter.For<T>(IComparable<T> comparer)` method overload, it creates a new, _comparer_ adapter, _NOT_ an  _equality_ adapter. These are two very different things.

Looking further at the `EqualityAdapter` code, I saw the following implementation for the `ComparerAdapter<T>` class of the `AreEqual` method: `return comparer.Compare(xValue, yValue) == 0`. In my opinion, this is inappropriate to use for the determination of object equality. According to MSDN  for the `IComparable` interface:

> Defines a generalized type-specific comparison method that a value type or class implements to order or sort its instances.

Notice that this says nothing about testing for _value equality_ (or instance equality). The `IComparable` interface (and its generic counterpart) are only meant for determining ordering and sorting, _not equality_. Therefore, the `EqualityAdapter` is _not_ always an adapter testing for value/object equality. Furthermore, the _ComparableAdapter_ should not have an `AreEqual` method, but a `ComparesAsEqual` method (or `ComparesAsSame` so as to remove any notion of "equality")--since that is what it's _really_ determining. (And it should probably also have `ComparesAsLessThan` and `ComparesAsGreaterThan` methods, too.) I would not expect an _equality_ constraint to be using sort comparison semantics to determine instance value equality semantics.

And so this is my dilemma. My type implements `IEquatable<T>`; it does also implement `IComparable<T>` and has an `IComparison<T>` default comparer. But while instance equality checks that all properties are the same between two instances, for the purposes of comparison (for sorting), only a subset of the properties are used. The result is that while objects may "compare as equal", the instances are not in fact "equal" in terms of their value semantics--and so my tests are passing when they should, in fact, be failing.

It's fine if the `EqualityConstraint` has the ability to determine whether two types are "equal" according to their sort order. But this should be explicit in the name of the constraint (i.e. `Has.SameSortOrderAs`). You do have a `ComparerAdapter<T>` which is totally fine for this purpose. But what you are lacking is the ability to provide a _true_ `EqualityAdapter` to the list of adapters which would rely on the object implementing `IEquatable<T>` and a way to add such an adapter to the list of adapters to be used by the constraint (outside of providing an ugly `Is.EqualTo(obj).Using<T1, T2>(Func<T1, T2, bool> predicate)` type, which is long-winded and not so easy to read as simply `Is.EqualTo(obj).Using(someWayOfInjectingAnAdapter)`). The reason for providing an explicit way to add an adapter for objects implementing `IEquatable<T>` instead of just using the default implementation provided by NUnit is to be able to provide the custom messaging that I described when I started this issue.

If NUnit were to provide some mechanism for injecting an actual equality adapter into the framework to be used during constraint checking, it could eliminate the need to provide an entire custom constraint. Instead, the built-in NUnit `EqualityConstraint` can simply delegate that check to an appropriately provided adapter, and the user can reap the benefits of most of the NUnit framework while providing just the minimum amount of customization they require (in my case, providing appropriate messages when the equality test fails).

It seems like my only recourse, for now, is to implement a whole custom Constraint instead and all the boilerplate required just so I can have custom messaging.

**Comment by CharliePoole** [comment]
While you are quite right in the sense that "equality" in an `IComparer` is only intended to mean order equality, many people want to use an IComparer of their own design for equality comparisons. The overload is there for those people.

The `Using` modifier has seven overloads and it seems like one of them could serve for your purposes. If not, however, you could make a request for some other overload to be added. As for the names used, an equality adapter is a purely internal construct used to match various comparison approaches to the interface that NUnit uses internally.

I suggest you take a look at the `Using` overloads that take `Func(T, T, bool)`, `IEqualityComparer` or `IEQualityComparer<T>`.

**Comment by fourpastmidnight** [comment]
I did mention the `PredicateEqualityComparer` that is present (which is what the `Using` overload you referenced uses internally)--but also mentioned that it's long-winded (i.e. not easy to read) and it's not really feasible for providing the comprehensive messaging I'm looking for.

It just seems like there should be a way to add an actual _Equality_ adapter to the existing `EqualityConstraint` which can provide appropriate messaging to the existing `EqualityConstraintResult` instead of having to completely implement a custom `Constraint` and it's attendant `ConstraintResult`. The plumbing appears to be mostly there--it's just missing the actual hookup.

**Comment by fourpastmidnight** [comment]
I take that back--the hookup is missing because NUnit is conflating "sort equality" with "value equality", and so there's no easy path to providing an `Is.EqualTo(x).Using(y)` because how do you know some such call to `EqualTo` wants to do "equality" checking vs. "sort equality" checking? All-in-all, I feel like this design should change in the future to use appropriate semantics.

OR--could it be as simple as adding an `Is.EqualTo<T>(T expected)` method which would delegate to a new `EqualConstraint<T>` constraint that would provide a `Using<TEqualityAdapter>(TEquality adatper)` method where a user can inject in their custom equality adapter, leveraging the existing `EqualityConstraintResult` object?

**Comment by CharliePoole** [comment]
The user, in specifying an argument to `Using`, tells us what kind of comparison they want to have made. A given comparer (order or equality) makes its comparison in a particular way. If the user provides an `IComparer`, the implied intent is that we use the `0` return to indicate equality. That may be incorrect from a purist view, but it's what the user wants and it's not our job to tell them it's wrong. We could, of course document this better - like lots of things, I'm afraid.

`EqualityAdapter` is simply NUnit's way of making all ways of doing the comparison look the same internally. Let's say we made it public and you could specify an `EqualityAdapter` in a `Using` modifier. What would you do with it? How would it help? I'm trying to understand the need.

**Comment by jnm2** [comment]
> What I would like to see is:
> 
> > Expected: Property 'MyProperty' to be 0
> > But was: 1
> 
> instead of
> 
> > Expected: <Full.Namespace.Path.To.Type.MyCustomType>
> > Actual: <Full.Namespace.Path.To.Type.MyCustomType>

The first way I'd suggest achieving this is the idiomatic .NET solution of override ToString on custom types. If there's a reason not to do that, we also provide this API:

```cs
TestContext.AddFormatter<MyCustomType>(obj => ((MyCustomType)obj).X);
```

**Comment by CharliePoole** [comment]
Glad to help. You may want to consider doing a PR that changes the NUnit classes to enable what you want to do. In the architecture of the framework, it is the constraint that pulls together a predicate of some kind with the generation of an error message. In recent (< 5 I think) years we split out the constraint result as a separate class so we could specialize the message for some constraints, as we do for equality.

**Comment by fourpastmidnight** [comment]
@jnm2 Duh! Don't I feel dumb! I overrode `Equals`, `GetHashCode` and numerous other `System.Object` base class methods, but not the simple `ToString` method! I was too close to the problem to see the (very simple) solution!

Works perfectly. Thanks for chiming in.
