### ISSUE TITLE
Rename BUILIDING.md to BUILD.md

### ISSUE THREAD

**Issue by OmicronPersei** [nunit/nunit#2939]
Looks like our Team Practices wiki page makes a reference to refer to each repo's respective "BUILD.md" file, but it's currently called "BUILDING.md" in this repo.
> See BUILD.md in each repository.

We should rename this for consistency.

**Comment by OmicronPersei** [comment]
It's been a while since I've contributed to NUnit so could someone from @nunit/framework-team just double check that this is what we want?

**Comment by jnm2** [comment]
I think BUILDING is more common and I just messed up with the docs. Coming up with rationale on the spot, `build` seems like a command (script) while `building` sounds like a description (docs).

Would you be willing to make the reverse fix for consistency?

**Comment by OmicronPersei** [comment]
Sure!

**Comment by jnm2** [comment]
Thanks! 😃
