### ISSUE TITLE
Nunit_Test case suit failing

### ISSUE THREAD

**Issue by abdulkhameer** [nunit/nunit#2943]
Hi, I am new to Nunit , we are facing a big problem in our project. We have developed 500+ test methods based on requirement, now we are not able to run this regression test suite as our Test automation will be stopped if any one test case fails. Example: if test case no.50 fails , automation will be stoped, where other test cases are independent in nature,. I didnt find any attribute which allows automation to continue even any test case fails. i dont wana use Try catch. Is there any way for me to make my efforts usefull? please help me

**Comment by mikkelbu** [comment]
Hi @abdulkhameer 
How are you running the tests? The usual test-runners (in VS, NUnitConsole, the GUI) all continue even if a test fails in order to generate complete reports. NUnitConsole can - AFAIK - be configured to fail on the first failure or error by providing `--stoponerror`.

**Comment by oznetmaster** [comment]
I had never seen NUnitTestOrdering  before :(

It seems to address many of the issues I raised when NUnit first introduced test ordering.

Maybe it should become part of NUnit at some point in time?  Just a thought.

**Comment by abdulkhameer** [comment]
Well, I got this by just making "ContinousOnError" as true , Actually remarks was confusing me. Now we are so happy that all our test cases will execute rather no TC will be stopped if any preceding test case fails. 
Thanks

**Comment by mikkelbu** [comment]
Great, that you got it working. I must admit I also got confused about the remarks above `TestOrderingSpecification.ContinueOnError` which for me gives the opposite intuition of the name `ContinueOnError` 😄 (but perhaps I'm just tired).

Link: https://github.com/Sebazzz/NUnitTestOrdering/blob/b2cabbfb1df510b1ffe751ed89664d80b0f9c58a/src/NUnitTestOrdering/FixtureOrdering/TestOrderingSpecification.cs#L34-L48
