### ISSUE TITLE
Show errors when mismatch type

### ISSUE THREAD

**Issue by lorranpalmeira** [nunit/nunit#2945]
Maybe It´s interesting show a error when types are different

![image](https://user-images.githubusercontent.com/18705060/43344822-902bc9a6-91c1-11e8-91a1-5bfcfd615b74.png)

or show error when forget parameter

![image](https://user-images.githubusercontent.com/18705060/43345007-3eadda50-91c2-11e8-9004-5318fddf8462.png)

**Comment by CharliePoole** [comment]
All these show up as errors in NUnit and also in all the runners with which I'm familiar. Please tell us what version of the nunit framework and runners you are using and show what output you are getting from these tests.

**Comment by lorranpalmeira** [comment]
Yes, but not in output, but to see an errors in vscode just in time like a error method underscore redline.

**Comment by CharliePoole** [comment]
To get further help, you would need to answer the original questions... Here is more detail...
 * What version of the NUnit framework are you using?
 * What runtime does your test assembly target
 * How do you run the tests? E.g. are you using the NUnit 3 VS adapter?

If you are saying that you want vscode to show mismatches between the provided attributes and the method definitions even before running the tests, that would require some kind of addin, which doesn't currently exist as far as I know for VsCode. The nunit framework is not invoked until you use it to discover and run tests.

**Comment by mikkelbu** [comment]
@lorranpalmeira The [nunit-analyzers](https://github.com/nunit/nunit.analyzers) can do that, but currently VSCode does not support Roslyn analyzers, so this will only work in VS and Rider.

Your examples when using the analyzer
![image](https://user-images.githubusercontent.com/1007631/43360895-8907e9ec-92c1-11e8-9972-897bdceb705f.png)
and
![image](https://user-images.githubusercontent.com/1007631/43360898-a636af12-92c1-11e8-9fe2-e86f0dfc4b95.png)

**Comment by lorranpalmeira** [comment]
Thank you @mikkelbu, It´s exactaly Im talking about. Unfortunely doesnt work on vscode. 
Thank you @CharliePoole for helping me.

**Comment by ChrisMaddock** [comment]
Closing this issue - as I don't think there's anything else to discuss. 🙂 

The nunit-analyzers project is working on support for this in VS.
