### ISSUE TITLE
NUnit Framework freezes when we abort main thread

### ISSUE THREAD

**Issue by OsirisTerje** [nunit/nunit#2947]
@MichailQA commented on [Mon Jul 30 2018](https://github.com/nunit/nunit3-vs-adapter/issues/532)

Hi, 
I observed the following strange behavior:
NUnit Framework freezes when we abort main thread in OneTimeSetUp method.

When we abort main thread in test or in SetUp method - behavior is expected (test fails with message "Test cancelled by user"), but when it happens in OneTimeSetUp method - NUnit Framework freezes.

* NUnit (3.7.1) and NUnit3TestAdapter (3.10.0) versions 
* Visual Studio edition and full version number (see Help About) => 2017, Version 15.6.6
* A short repro, preferably attached or pointing to a git repo or gist

```cs
 [TestFixture]
    class Test1
    {
        [OneTimeSetUp]
        public void OneTimeSetUp()
        {
            Thread mainThread = Thread.CurrentThread;
            Task paralelThread = Task.Factory.StartNew(() =>
            {
                mainThread.Abort();
            });

            Thread.Sleep(2000);
        }

        [Test]
        public void Test_1() { }

        [Test]
        public void Test_2() { }

        [Test]
        public void Test_3() { }
    }
```

---

@MichailQA commented on [Mon Jul 30 2018](https://github.com/nunit/nunit3-vs-adapter/issues/532#issuecomment-408839350)

Also if we catch this type of exception (ThreadAbortException) in OneTimeSetUp its doesn't help, and NUnit freezes

---

@jnm2 commented on [Tue Jul 31 2018](https://github.com/nunit/nunit3-vs-adapter/issues/532#issuecomment-409201110)

(Edited your post to use [code fences](https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting).)

This seems like a framework (not an adapter) bug from an insider's perspective. Have you tried NUnit framework 3.10.1?

When someone has time, we should confirm this against the master branch. We made changes to OneTimeTearDown since 3.10.1, but as far as I know we haven't affected this scenario.

---

@OsirisTerje commented on [Tue Jul 31 2018](https://github.com/nunit/nunit3-vs-adapter/issues/532#issuecomment-409316645)

This also crashes in 3.10.1.

**Comment by OsirisTerje** [comment]
Moved to NUnit repo, closed it here.

**Comment by ChrisMaddock** [comment]
I agree...although I'd be interested to know the motivation to write tests like this. 🙂 

I'm not totally convinced yet that cancelling tests in this way is a supported scenario - if you intentionally kill the test runner mid-test, it feels like that should odd behaviour should be expected!

**Comment by CharliePoole** [comment]
NUnit creates the thread you are running on. You can't abort it without breaking something. What you have observed is that it breaks differently for a test method versus a OneTimeSetUp, but both are broken.

In the case of the test method, as you point out, NUnit falsely reports that the user cancelled the test.

**Comment by rprouse** [comment]
I'm closing this because it isn't how you should be using NUnit.
