### ISSUE TITLE
Problems when I activate Live Unit Testing using NUnit in a Visual Studio 2017 Test Project

### ISSUE THREAD

**Issue by licjapodaca** [nunit/nunit#2949]
I'm using Visual Studio 2017 Enterprise 15.7.6 and a Test Project with the following Nuget Packages:

![image](https://user-images.githubusercontent.com/828781/43696144-829ebcbc-98f1-11e8-91b6-eec4df2ce9ba.png)

The problem is that when I activate **Live Unit Testing (LUT)** in VS2017 and specify in a Test Method the attribute [TestCase] in some cases works the LUT but when I mke some change in source code other Test Methods are excluded from LUT as you can see in the next image:

![image](https://user-images.githubusercontent.com/828781/43696328-492125aa-98f2-11e8-897c-77b7fc149b23.png)

The source code that has the TestCase attribute is the following:

```csharp
[Test]
[TestCase(null), TestCase(""), TestCase(" ")]
public void Log_InvalidError_ThrowArgumentNullException(string error)
{
	var logger = new ErrorLogger();

	Assert.That(() => logger.Log(error), Throws.ArgumentNullException);
}
```

> NOTE: If I stop and start again LUT in VS2017 the Test Method mentioned at the beginning of this ISSUE is included correctly, but again if I refactor the source code, the LUT exclude the same Test Method again.

Is there a workaround for this problem?

Thanks for your help in advance.

**Comment by licjapodaca** [comment]
Anybody?

**Comment by CharliePoole** [comment]
Moving this to the nunit3 vs adapter repository, where it's likely to get more attention.

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit3-vs-adapter #536](https://github.com/nunit/nunit3-vs-adapter/issues/536) via [**ZenHub**](https://www.zenhub.com/)
