### ISSUE TITLE
Nunit on MacOS VS with Xamarin.Mac 2.0 not compatible?

### ISSUE THREAD

**Issue by victorylu** [nunit/nunit#2951]
Hi, I'm currently trying to get the Nunit framework installed on the MacOS version of Visual Studio, but I am getting the following message: "Could not install package. You are trying to install this package into a project that targets 'Xamarin.Mac,Version=v2.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author." Is there more information regarding this topic or is it not supported at this time?

**Comment by rprouse** [comment]
Sorry, we don't currently have a runner for Xamarin.Mac although I thought our .NET Standard 2.0 target would work. I usually test projects like that by making my shared code .NET Standard and then consuming it from a .NET Core test project. I can test most of the Xamarin code, just not the platform specific code. I often have to implement mock platform interfaces, but that isn't too much work.

**Comment by victorylu** [comment]
Oh okay. Thanks for letting me know!
