### ISSUE TITLE
Potential threading issue in IsolatedContext

### ISSUE THREAD

**Issue by roederja2** [nunit/nunit#2955]
I'm occasionally seeing this exception when running my tests:

```
System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: chunkLength

 Stack Trace

   at System.Text.StringBuilder.ToString()
   at NUnit.Framework.Internal.TestExecutionContext.IsolatedContext.Dispose()
   at NUnit.Framework.Assert.Throws(IResolveConstraint expression, TestDelegate code, String message, Object[] args)
   at NUnit.Framework.Assert.Throws[TActual](TestDelegate code, String message, Object[] args)
   at MyNamespace.TransactionalJobInnerThrowsOuterCommits(Boolean distributed, Boolean withFunction)
```

It seems to be some sort of threading issue, but I'm not sure how this is being triggered. My test code looks like this:

```
Exception ex = Assert.Throws<SomeException>(() =>
{
       CallMethod();        
});
```

**Comment by CharliePoole** [comment]
The exception is being thrown when the IsolatedContext, on disposal, attempts to preserve any text output from the test by writing the saved output to a StringBuilder. Can you provide a test that replicates this behavior?

**Comment by roederja2** [comment]
That's a bit difficult because I only see it on our build server and only some of the time. It's definitely threading related. But I don't think I'm checking assertions in different threads. And even if I was it shouldn't crash like this.

**Comment by roederja2** [comment]
Yes, my delegate is creating a thread or rather threads. Some googling of the chunkSize Exception indicates that the most plausible way to get this is because of multi threaded access. Naively I would assume the StringWriter/Builder needs to be protected with a lock.

**Comment by CharliePoole** [comment]
Here's the code that's throwing the exception...

```C#
public void Dispose()
{
    _originalContext.OutWriter.Write(CurrentContext.CurrentResult.Output);
    CurrentContext = _originalContext;
}
```

Reference to the `Output` property of the result causes `TestResult._output.ToString()` to be called, where `_output` is the StringBuilder causing the problem.

TestResult has a ReaderWriterLock to avoid conflicts between threads that affect the result but The `Output` property is not using it. Should be changed to work like the `Message` property, for example.

**Comment by roederja2** [comment]
Thanks Charlie,
I had a look at the code and it seems to me it's not as easy as just using the existing `RwLock`. The `OutWriter` has its own synchronisation via `TextWriter.Synchronized`, however when reading the `_output` StringBuilder is accessed directly. I don't see how the monitor from inside `TextWriter.Synchronized` can be used to protect read access to `_output`

**Comment by CharliePoole** [comment]
IIRC, `TextWriter.Synchronized` was used early on and the ReaderWriterLock was added later. We may want to use the ReaderWriterLock when writing to the _output stringwriter as well as when accessing it.

BTW, my comments are intended as advice for whomever fixes this, not as an indication that I"m taking it on myself. :-)

**Comment by roederja2** [comment]
I gave it a go: https://github.com/nunit/nunit/pull/2957

So far it seems to fix my issue

**Comment by roederja2** [comment]
PR has been merged and my problem is solved by it. Closing.
