### ISSUE TITLE
Ordering integration test with Nunit for Test Automation

### ISSUE THREAD

**Issue by AutomationSifu** [nunit/nunit#2956]
Hi Team,

I'm writing a test automation framework using the below technologies:

Selenium Web Driver
NUnit v3.10.1
cSharp
Visual Studio

In Java, I can use the testng.xml file to group tests together (test suites) and have them run in the order they are listed.

Right now with csharp/Nunit I'm using the order attribute at the test fixture level, and grouping tests using test categories. This was working fine until test # 5 needs to be run in a different order with another test suite.

Please note these tests are being run from Visual Studio as we're not using NUnit Console (Continuous Integration not in place yet).

Could someone point me in the right direction?

Thanks!

**Comment by mikkelbu** [comment]
If I understand your situation correctly, then this cannot be specified using the OrderAttribute. Perhaps it will be possible using the more advanced features in  https://github.com/Sebazzz/NUnitTestOrdering from @Sebazzz, but I've not used this yet.

**Comment by AutomationSifu** [comment]
Hi Mikkelblu,

Thanks for your feedback!  The link seems like what I'm looking for.  The only thing I'm unsure of is if a test fixture can be referenced with a different order to be re-used in more than one test suite.  At the moment when I use the order attribute at the testfixture level,  I'm only able to use the order attribute once, which makes sense there's not a clear way to know which order attribute to use at the time of test execution.

**Comment by Sebazzz** [comment]
> Thanks for your feedback! The link seems like what I'm looking for. The only thing I'm unsure of is if a test fixture can be referenced with a different order to be re-used in more than one test suite.

That is possible.

**Comment by AutomationSifu** [comment]
Thank you, that is very encouraging!  I tried to download the package in visual studio using the Package Manager Console but it appears I can only use Nunit versions 3.7 to 3.10.0.  I'm currently on version 3.10.1, which is considered the latest stable version of Nunit.

**Comment by AutomationSifu** [comment]
Hi Sebazzz,

I've created a small project in Visual Studio so I can do a test run of your library.  In setting up the library I do have a few questions,  What is the proper place to place those questions.  Thanks!

**Comment by Sebazzz** [comment]
Please use the bugtracker of the project itself.

Met vriendelijke groet,
Sebastiaan Dammann

________________________________
Van: AutomationSifu <notifications@github.com>
Verzonden: donderdag, augustus 23, 2018 6:17 PM
Aan: nunit/nunit
CC: Sebastiaan Dammann; Mention
Onderwerp: Re: [nunit/nunit] Ordering integration test with Nunit for Test Automation (#2956)


Hi Sebazzz,

I've created a small project in Visual Studio so I can do a test run of your library. In setting up the library I do have a few questions, What is the proper place to place those questions. Thanks!

**Comment by AutomationSifu** [comment]
This library was exactly what I was looking for.  I'm able to create test suites that can run in a custom order.
