### ISSUE TITLE
Planning for 3.11 Release

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#2960]
We are past due for a 3.11 release. I went through the issues and cleaned up. We only have 33 completed issues so far for 3.11, so I don't think there is a huge rush, so I was thinking mid to late September for a release. @nunit/framework-team if there is anything you are working on or planning on working on that you would like to see in 3.11, please add to the milestone. I removed a couple of long running issues/PRs from the milestone. If work is ongoing and you'd like to get them in, feel free to re-add.

**Comment by rprouse** [comment]
@agray I'm still planning on getting the release out by the end of the month if not a bit earlier. I've been doing some cleanup and other admin duties now that I've got the console release out. Are their particular issues that you are waiting for? If so, those are the sort of thing I would like to highlight in the release notes.

**Comment by agray** [comment]
Parallel test execution in the same assembly like JUnit.

**Comment by CharliePoole** [comment]
Could you clarify? We already do parallel execution on assembly. What features are implied by "like JUnit"?

**Comment by jnm2** [comment]
@agray I think NUnit 3 has had that for quite a while?

**Comment by agray** [comment]
When I have a data driven test fixture tests won't run in parallel.
Implemention is at github.com/sauceforge/saucery3.

**Comment by CharliePoole** [comment]
@agray Is this related to #2481? It doesn't appear that anyone has worked on that or even confirmed it to this point.

**Comment by agray** [comment]
It doesn't hang on my machine. It would be good if someone else could
confirm it.

Getting NUnit 3 to behave like JUnit 4 wrt parallelism has been the goal of
Saucery3 all along.

**Comment by agray** [comment]
Charlie informed me that the parallism in NUnit 3 was across different
assemblies not in the same assembly.

In JUnit 4 parallism works great in a single data driven test fixture. For
an implementation of this see github.com/sauceforge/SauceryJ

I'm yet to be able to get NUnit 3 to work the same way.  As soon as I try
to add parallelism attribute to the TestFixture it hangs.

Regards,

Andrew

**Comment by rprouse** [comment]
@agray there may be some fixes and improvements in the upcoming release of NUnit, but no major changes to parallelism or capabilities. I would confirm your requirements and expectations using the NUnit Console, then if you are not seeing the same behaviour in Saucery, we can help you figure out what you are doing differently.

**Comment by CharliePoole** [comment]
@jnm2 A small clarification: both fixture level and test-case level parallelism are opt-in. That is, if you don't use `ParallelizableAttribute` somewhere in the assembly, then nothing runs in parallel. I think that's what you most likely meant, but others could be confused.

**Comment by CharliePoole** [comment]
@agray I'm pretty sure I didn't tell you there was no parallelism within the assembly in NUnit. What I may have said is that there is no parallelism __by default__ within the test assembly but there is default parallelism across multiple assemblies.

The reason for the distinction is that different test assemblies tend to test entirely different things and so can usually run in parallel. OTOH, the tests within an assembly are typically about the same target assemblies and can often interfere with one another so we don't want to introduce problems by running them in parallel without the user having asked for it.

**Comment by jnm2** [comment]
(Thanks Charlie, I reworded!)

**Comment by rprouse** [comment]
FYI, I have started the release process. It won't be completed today, but it underway...

**Comment by jnm2** [comment]
No problem! I'm more entertaining in the evenings than the morning, too... 

(sorry 😁)
