### ISSUE TITLE
NUnit cannot find tests after upgrading to Visual Studio 15.8

### ISSUE THREAD

**Issue by fcin** [nunit/nunit#2962]
Hi,

I updated Visual studio Enterprise 2017 to version 15.8.0 and it fails to discover all tests inside Unit Test project (.NET Framework 4.6.1). It discovers tests for .NET Standard 2.0, but fails for .NET Framework 4.6.1. I can see all tests in Test Explorer, but when I try to run them I get this output:

```
[2018-08-16 11:58:45 Informational] ------ Run test started ------
[2018-08-16 11:58:46 Warning] No test matches the given testcase filter `FullyQualifiedName=WebFormsApplication.Tests.UnitTest1.TestMethod1` in myPath\WebFormsApplication.Tests\bin\Debug\WebFormsApplication.Tests.dll
[2018-08-16 11:58:46 Informational] ========== Run test finished: 0 run (0:00:01,0001) ==========
```

Replication steps:

1. Create WebForms application targeting .NET Framework 4.6.1.
2. Create Unit Test project targeting .NET Framework 4.6.1
3. Install NUnit 3.10.1 nuget package in Unit Test Project
4. Create test inside Unit Test project:
```
    [TestFixture]
    public class UnitTest1
    {
        [Test]
        public void TestMethod1()
        {
            Assert.Pass();
        }
    }
```
5. Rebuild 

This test will be discovered in Test Explorer but trying to run this will result in above output.

I'm using NUnit 3 Test Adapter 3.10.0.0 and NUnit 3.10.1 nuget package

**Comment by fcin** [comment]
Issue is solved by removing references to 

Microsoft.VisualStudio.TestPlatform.TestFramework
Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions

**Comment by rprouse** [comment]
Thanks for letting us know @fcin.

@OsirisTerje take a look at this issue and the solution. You may run into the same thing in the adapter project.

**Comment by miroslav-peterka** [comment]
I have the same situation in project with Selenium.

**Comment by mikkelbu** [comment]
Hi @miroslav-peterka 
You'll need to provide some more information for us to help you.
* What type of project (.NET Standard 2.0, .NET Framework 4.6.1, ...)?
* Which versions of NUnit and NUnit 3 Test Adapter do you use?
* Are you using Live Unit Testing in VS?
* Can you run the tests using the commandline and nunit-console?
* Are test discovered, but not run, like the problem in this issue, or is the problem - a bit - different?

Ps. Did you see this comment - https://github.com/nunit/nunit/issues/2962#issuecomment-413507120

**Comment by miroslav-peterka** [comment]
- I'm using NUnit3TestAdapter 3.10.0 and NUnit 3.10.1 nuget package
- project .Net Framework 4.6.1

but I found I can solve this by downgrading NUnit to version 3.10.0

**Comment by mikkelbu** [comment]
Strange. Was that the only change, because the only difference between 3.10.1 and 3.10.0 is https://github.com/nunit/nunit/compare/v3.10...release and I have not heard from anybody else that this had the effect of hiding tests. What if you upgrade to 3.10.1 again and rebuild does the problem reappear?

**Comment by miroslav-peterka** [comment]
yes

**Comment by bobrinch** [comment]
Same here.

Was using NUnit3TestAdapter 3.10.0 and NUnit 3.11.0, and got the "No test matches the given testcase filter" error message. After downgrading to NUnit 3.10.0 I can run unit tests again.

**Comment by rprouse** [comment]
Please go to the output window and switch the dropdown to test after compiling your solution and copy/paste the text in that window here.

**Comment by rprouse** [comment]
The only change from 3.10.0 to 3.10.1 is the update to the first line of `nunit.props` in the NuGet file to `<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">`. That change is still in 3.11, so it is odd that it would cause failures.

**Comment by Dispersia** [comment]
I am getting this as well. I think something changed with the visual studio test runner, it is auto discovering nunit tests even before I build, even if I clean everything my tests still show up. I can't downgrade to any version to seem to get it to work. 

 Was on nunit 3.9.0, nunit3testadapter 3.10, ran tests this morning and everything was good, upgraded both to latest as of today, now no matter what I downgrade either package to, I can no longer get any test to run. They are all discovered correctly (and as stated before, instantly, even without the nunit3testadapter installed), but I get the:
`[10/16/2018 10:05:27 AM Warning] No test matches the given testcase filter`

**Comment by kevinheyvaert** [comment]
@Dispersia does still works? I have now also the issue for a couple of days and not sure how to fix it. I use NUnit 3.10.1 and the Nunit3testadapter 3.10.

**Comment by mikkelbu** [comment]
Can you see if VS have changed the Default Processor Architecture like in this issue (see the last comments) https://developercommunity.visualstudio.com/content/problem/311537/unit-testing-cannot-findexecute-test-cases-anymore.html

**Comment by Dispersia** [comment]
@kevinheyvaert yes, it's still working for me. I think the thing that really worked for me was moving it out of my build directory. I put it on my desktop, and it works, putting the build back to bin\debug makes it stop discovering properly. It's like updating made the cache for that directory wrong - but i cleaned everything and have no idea where else it could be looking for that directory.

**Comment by pjdiii** [comment]
> Issue is solved by removing references to
> 
> Microsoft.VisualStudio.TestPlatform.TestFramework
> Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions

Had to add reference to Microsoft.VisualStudio.QualityTools.UnitTestFramework afterwards

**Comment by mikkelbu** [comment]
@panuoksala
Can you also provide the logs when running with 3.10 (just so we can compare)?

Ps. and when you are talking about downgrading 3.10 version from 3.11, then you are talking about the NUnit version and not the adapter version?

**Comment by panuoksala** [comment]
> @panuoksala
> Can you also provide the logs when running with 3.10 (just so we can compare)?
> 
> Ps. and when you are talking about downgrading 3.10 version from 3.11, then you are talking about the NUnit version and not the adapter version?

I actually downgraded both.
This is logs after downgrade:

[7.11.2018 12.23.04 Informational] ------ Run test started ------
[7.11.2018 12.23.04 Informational] NUnit Adapter 3.11.0.0: Test execution started
[7.11.2018 12.23.04 Informational] Running selected tests in C:\src\Common.Tests\Common.Tests.dll
[7.11.2018 12.23.05 Informational]    NUnit3TestExecutor converted 48 of 48 NUnit test cases
[7.11.2018 12.23.05 Warning] SetUp failed for test fixture Auto.Common.Tests.Initializer
[7.11.2018 12.23.05 Warning] SetUpAttribute attribute not allowed in a SetUpFixture
[7.11.2018 12.23.05 Informational] NUnit Adapter 3.11.0.0: Test execution complete
[7.11.2018 12.23.05 Informational] ========== Run test finished: 1 run (0:00:01,1892639) ==========
