### ISSUE TITLE
NuGet Package : Add `repository` metadata. 

### ISSUE THREAD

**Issue by MaximRouiller** [nunit/nunit#2965]
Basically, we can now add a repository metadata on a nuspec file to allow the repository to be surfaced on NuGet. 

I've talked about it [on Twitter](https://twitter.com/MaximRouiller/status/1030468873945075712) but the most basic things to know is here:

[NuSpec Reference](https://docs.microsoft.com/en-us/nuget/reference/nuspec?WT.mc_id=social-github-marouill#repository)

Reference Implementation in Json .NET
![image](https://user-images.githubusercontent.com/209384/44277447-b1c20f00-a218-11e8-9406-4f1f05879d47.png)

**Comment by rprouse** [comment]
Sounds like a great idea. Thanks for entering it.

**Comment by rprouse** [comment]
We should probably duplicate this issue in our other repos if we are going to go ahead with it.

**Comment by MaximRouiller** [comment]
If you do, can you link back to this issue? Worst case, I'm ready to do PRs.

**Comment by jnm2** [comment]
Yes, I was coming here to file the same issue! @MaximRouiller, we would seriously take you up on the offer of PRs for our repositories. We use .nuspec files in most of them.

**Comment by jnm2** [comment]
@rprouse I was thinking this would be great to get in 3.11 since it'll be a while before 3.12.

**Comment by MaximRouiller** [comment]
Damn... I've just looked at the number of repos and Nuspec that you guys have... and it's a lot.

If you could list me those that are active, I'd greatly appreciate it.

**Comment by MaximRouiller** [comment]
Child issues:

- https://github.com/nunit/nunit-console/issues/456
- https://github.com/nunit/nunit3-vs-adapter/issues/538

**Comment by CharliePoole** [comment]
If you are asking whether it's active, then yes. Any specific question about the package should be asked in its repo, so the right people see it.

**Comment by MaximRouiller** [comment]
Adding a reference to this issue. 

https://github.com/nunit/nunit-vs-adapter/issues/175

**Comment by jnm2** [comment]
I think these are the repos actively shipping packages:

- [ ] https://github.com/nunit/nunit
- [ ] https://github.com/nunit/nunit-console
- [ ] https://github.com/nunit/nunit-v2-framework-driver
- [ ] https://github.com/nunit/nunit-vs-adapter
- [ ] https://github.com/nunit/nunit.analyzers
- [ ] https://github.com/nunit/nunit.xamarin (csproj SDK rather than nuspec)
- [ ] https://github.com/nunit/nunit3-tdnet-adapter
- [ ] https://github.com/nunit/nunit3-vs-adapter
- [ ] https://github.com/nunit/teamcity-event-listener
- [ ] https://github.com/nunit/vs-project-loader

@MaximRouiller We are grateful for any of these that you have the time and willingness to do! Otherwise one of us will get around to it eventually!

**Comment by MaximRouiller** [comment]
https://github.com/nunit/nunit/pull/2968
https://github.com/nunit/nunit-console/pull/457
https://github.com/nunit/nunit-v2-framework-driver/pull/25
https://github.com/nunit/nunit-vs-adapter/pull/176
https://github.com/nunit/nunit.analyzers/pull/72
https://github.com/nunit/nunit.xamarin/pull/113
https://github.com/nunit/nunit3-tdnet-adapter/pull/11
https://github.com/nunit/nunit3-vs-adapter/pull/539
https://github.com/nunit/teamcity-event-listener/pull/55
https://github.com/nunit/vs-project-loader/pull/32

**Comment by MaximRouiller** [comment]
There's 2 in there that I had to modify the csproj file. These will need to have their output double checked.

It's pretty obvious when you're using a Nuspec that the data is going to get grabbed but if other means are used to package these projects with a csproj, it may need that data to be updated. For those? I'll leave the team to do the basic work. 

Shouldn't be too hard.

**Comment by CharliePoole** [comment]
FYI this that embed the metadata in a cake script are easy enough since cake is just C#.

**Comment by MaximRouiller** [comment]
Had to update `cake` to `0.29.0` but it fixed the issue for this one:

https://github.com/nunit/nunit-v2-framework-driver/pull/26

**Comment by MaximRouiller** [comment]
And for the `vs-project-loader`. This one already download the latest version of cake.

https://github.com/nunit/vs-project-loader/pull/33

**Comment by MaximRouiller** [comment]
With everything approved... there's a few that remains to be merged but I think that concludes the transition to the Source Code link. 

Sadly, we can't tag previous packages so only the latest version of the packages will have the URL. 

I'm going to be writing a blog post very shortly describing the type of work that was done here and provide help for other Package Authors to have this included as well in 3 ways. Nuspec, MSBuild and with cake.

Thanks a lot for your patience with a new contributor. 😁

**Comment by ChrisMaddock** [comment]
That's awesome - thanks for doing all these @MaximRouiller!

**Comment by ChrisMaddock** [comment]
As far as I can see, everything's merged, apart from those in the adapter repositories which @OsirisTerje looks after - and I'm sure he'll be along within a few days to do so. I'll close this issue - thanks for doing this across all our project though @MaximRouiller! Would love to see the blog, if you'll add a link back when it's done!
