### ISSUE TITLE
Missing constraint for testing object is in collection?

### ISSUE THREAD

**Issue by richard-fine** [nunit/nunit#2969]
I want to write an assert like this:

`Assert.That(item, Is.ContainedIn(collection));`

You're probably thinking: Why not just write 

`Assert.That(collection, Has.Member(item));`

instead? Simple - because that reverse the roles of the 'actual' and 'expected' entities. My collection is a static thing, and my item is the 'potentially wrong' thing that is actually under test. So I want to write it the former way, partly for code clarity and partly to give the best possible failure messages.

I know that I can write this constraint myself, but I wanted to bring it up because a) maybe it exists under some other name and I'm just missing it, and b) I think it's worth considering for inclusion in the framework itself.

**Comment by ChrisMaddock** [comment]
You're after the newly added `Is.AnyOf()` I believe, newly added in 3.10 by @Dreamescaper!

https://github.com/nunit/nunit/pull/2703

I'm afraid it's so new, it's not yet in our docs. (But we'd love a contribution to fix that, if you'd be interested!?)

**Comment by ChrisMaddock** [comment]
Moving this issue over to the docs repo. 🙂

**Comment by ChrisMaddock** [comment]
Issue moved to [nunit/docs #281](https://github.com/nunit/docs/issues/281) via [**ZenHub**](https://www.zenhub.com/)
