### ISSUE TITLE
3.0 Xml Output additions

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#297]
The current 3.0 Xml output includes the environment element which details the information about the version of the os and the verison of nunit used for the test.

It does not include any information about the test assembly/assemblies used for the tests.

It would seem very useful if the output included the full name of the tested assembly (which includes its version), and the created/modified date/time information.  Perhaps the load path for the assembly as well?

**Comment by yetibrain** [comment]
@CharliePoole  (commented on Oct 24, 2014)
Yes, why not. But NUnit will parse the command line arguments anyway, so i'd prefer to have them as separate parameters instead of one large string. But if we do so, we should embed it into a CDATA section because it could contain special characters.

**Comment by CharliePoole** [comment]
@yetibrain Not sure if that will work, but I'll keep it in mind. The top level XML element is added by the master test runner, which is part of the engine. Whatever program ran the tests will have it's own syntax for the command-line, and that's not known to the engine. However, the engine is passed certain parameters, drawn from the command-line in the case of the console runner, from various gui settings in the case of the gui, and so forth... I think if we show these parameters, which are name / value pairs, you'll be able to figure out how the test was run.

**Comment by CharliePoole** [comment]
I have started issue #713 to handle the @yetibrain 's request regarding command-line paramters.

I'm closing this issue as the original problem was fixed some time ago.
