### ISSUE TITLE
Broken NUnit Repo

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#2974]
Every time I  attempt to sync with the nunit repo using github for windows, I get the error:

Failed to sync to this branch [master]
You might need to open a shell and debug the state of the repo.

Can someone please either do something about this, or tell me what to do.

**Comment by ChrisMaddock** [comment]
I think that's a very generic error message unfortunately - but looks like it's normally related to your local repo? Open up cmd, and see if `git status` gives any clues?

See https://stackoverflow.com/questions/15387640/github-windows-failed-to-sync-this-branch

FWIW, I just tried cloning a fresh repo, and had no issues.

**Comment by oznetmaster** [comment]
I used the newer github for windows, and it says:

A lock file already exists in the repository, which blocks the operation from completing.

Any idea how to fix this?

**Comment by mikkelbu** [comment]
@oznetmaster This sounds similar to the problems described in desktop/desktop#4938 (I'm unsure if this repository is "the newer github for windows").

**Comment by rprouse** [comment]
@oznetmaster rather than spelunking around trying to fix, might it be easier to clone a new clean copy?

**Comment by oznetmaster** [comment]
I tried deleting the lock file in the local copy of the repo, and it seemed to fix the problem!

**Comment by ChrisMaddock** [comment]
Closing this, as it looks like the problem may lie outside of NUnit.

Happy to reopen if anyone has more to add. 🙂
