### ISSUE TITLE
ComparisonConstraints are allocating string on construction

### ISSUE THREAD

**Issue by lahma** [nunit/nunit#2975]
While investigating our test suite's memory usage, NUnit also came up from some paths where a lot of parsed data was processed through loop that checked against LessThanOrEqualConstraint. If you look how all ComparisonConstraint inheritors are implemented, they all allocate Description when constructed even though I would presume it's not needed unless assertion fails?

https://github.com/nunit/nunit/blob/6f806c61eb84f1fed0b47f9b90f1d1e21ec72e14/src/NUnitFramework/framework/Constraints/GreaterThanOrEqualConstraint.cs#L35-L38

I would suggest that these would be either lazy evaluated or evaluated every time the getter is called, like for example in EqualConstraint:

https://github.com/nunit/nunit/blob/6f806c61eb84f1fed0b47f9b90f1d1e21ec72e14/src/NUnitFramework/framework/Constraints/EqualConstraint.cs#L399-L421

**Comment by rprouse** [comment]
Looks like a good idea and an easy fix. Thanks for the examples.

**Comment by madetara** [comment]
Hello. I'd like to work on this issue. Need some time to go through all the contributing guidelines though.

**Comment by mikkelbu** [comment]
Hi @madetara
The issue is yours. I've assigned the issue to myself just to mark it as "taken", as we cannot assign issues to non-members. Here are the [contributing guidelines](https://github.com/nunit/nunit/blob/master/CONTRIBUTING.md) and how to [build build and run the tests](https://github.com/nunit/nunit/blob/master/BUILDING.md) (I personally prefer just to run `build.ps1 -t Test`).

**Comment by madetara** [comment]
It seems I came up with good solution, but having troubles running tests, getting following error: 
`More than one build script specified.`
Both via `build.sh -t Test` and `build-mono-docker.ps1 -t Test`

OS: Manjaro 17.1.12
Bash: 4.4.23
Docker: 18.06.1-ce
Mono: 5.14.0

P.S. Projects builds via Rider with no problems, even though it's said that mono should crush

**Comment by madetara** [comment]
Yep, that works, thanks for the asnwer.

I'm now having another problem though, NuGetRestore fails with the following error:
 `error NU1603: nunitlite depends on NETStandard.Library (>= 2.0.2-servicing-26420-0) but NETStandard.Library 2.0.2-servicing-26420-0 was not found. An approximate best match of NETStandard.Library 2.0.2 was resolved.`

**Comment by mikkelbu** [comment]
Hi @madetara 
I'm not sure if I can help you with this. This sounds like the same problem as in https://bugs.archlinux.org/task/59274, so a "problem" with Arch Linux?
Do you get more (relevant) information if you run with `Verbosity` set to `Diagnostic` ?. Perhaps @CharliePoole can help you (as far as I can remember he shifted til Linux only development recently, but I guess that the "dotnet tooling" is different from Linux variant to Linux variant.

**Comment by madetara** [comment]
I finally had time to figure out the SDK versioning. 
Running build with v2.1.300 SDK fixed the problem, thanks for the help.
Will probably open the PR soon

**Comment by madetara** [comment]
Also, the Arch distribution of dotnet-sdk-1.1 is no longer maintained, so I was not able to run corresponding tests

**Comment by mikkelbu** [comment]
Merged. Thanks for the contribution @madetara. It is much appreciated 👍.
