### ISSUE TITLE
Is there any to run a single test case multiple times as parallel

### ISSUE THREAD

**Issue by kumarbrandmuscle** [nunit/nunit#2977]
Hi,
I am using Repeat attribute to run test cases multiple times.
But the test cases are not running parallely.
Is there any to run single time multiple times in parallel way.
Usage classlevel:
 [TestFixture]
    [Parallelizable(ParallelScope.Fixtures)]
Method level:
[Test, Repeat(3)]

**Comment by ChrisMaddock** [comment]
Not with how RepeatAttribute is currently implemented, no.

There's actually a relevant comment on RepeatAttribute itself:

https://github.com/nunit/nunit/blob/cefc0c3a86c065daa4130aa255b1384db51b2b08/src/NUnitFramework/framework/Attributes/RepeatAttribute.cs#L24-L30

This requirement would possibly tie into point 2 - which is a non-trivial piece of work to implement. See https://github.com/nunit/nunit/issues/7 for more info there.

I'm going to close this particular issue - as I think it's a very specific part which can only really be covered by the much larger piece of work in #7. The issue will of course still be attached to #7 now, if/where someone looks at that. If anyone on nunit/framework-team disagrees with me or thinks I've missed something, please feel free to re-open!
