### ISSUE TITLE
Update AppVeyor version last so that links to running builds do not break

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2985]
When we submit a PR or branch build and follow the GitHub integration link to AppVeyor, we often see this:

![image](https://user-images.githubusercontent.com/8040367/44633616-b34baf80-a95b-11e8-8f82-bf6f0ddcb0b8.png)

Early this year I discovered that this is due to setting the AppVeyor build number in our Cake script. Sequence of events:

- GitHub notifies AppVeyor that a branch is updated

- AppVeyor queues a build and posts the link back to GitHub, e.g. https://ci.appveyor.com/project/CharliePoole/nunit3-vs-adapter/build/3.11.898.

- AppVeyor starts the build and a few seconds later the Cake script changes AppVeyor's number for that build:
  
  https://github.com/nunit/nunit/blob/31f62cc2d49b02bd7074483af5e80761fbea9b55/build.cake#L108

- The new link is https://ci.appveyor.com/project/CharliePoole/nunit3-vs-adapter/build/3.11.0-ci-00898-pr-541, but AppVeyor doesn't notify GitHub that the link has changed until the build completes. So we get the 404 as long as the build is still running.

We can minimize this by making the AppVeyor version update the last thing the Cake script does.

**Comment by ChrisMaddock** [comment]
Nice find - I'd always wondered what caused that! 😄

**Comment by jnm2** [comment]
Possibly superseded by https://github.com/nunit/nunit/issues/3012.

**Comment by stevenaw** [comment]
Appveyor is primarily used now for publishing to myget. The recent myget outage is complicating our use of this.
@OsirisTerje I'm closing this as I think the talk about moving to github packages in https://github.com/nunit/nunit/issues/4440 shows we probably don't want to continue maintaining the appveyor build
