### ISSUE TITLE
Adding delay to the Threads of scripts executed in parallel execution form

### ISSUE THREAD

**Issue by Sameerchit** [nunit/nunit#2988]
I have a bunch of scripts that I am executing in parallel using Nunit console.
Wherein NUnit launches multiple browsers at the same time and distributes test cases.

Here I face issue, as my application expects at least 3-5 seconds delay within two application launches, or in fact login doesn't work if there are more than one login attempts within a period of 3 seconds.

Is there any way, I can instruct NUnit to have a delay of say 4 Seconds within multiple threads.

**Comment by ChrisMaddock** [comment]
I think you'll need to explain how you've implemented this more specifically, for anyone to be able to provide any advice.

How are you "executing your scripts using NUnit console"? Are you calling them within your test code? Or is the console itself executed as part of your scripts? 

What part of your code manages the login? Is that within an NUnit called method, e.g. a SetupFixture?

As a gut feeling - it sounds like the most reliable solution for you would be to detect the failure and then retry, but without more information, I'm only guessing. 🙂
