### ISSUE TITLE
Error in .NET Standard 1.4 DictionaryContainsKeyConstraint MetadataToken compatibility methods

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#2994]
@oznetmaster identified issues with the two `Matched()` methods added by https://github.com/nunit/nunit/pull/2967 - where `return true` looks like it should be `return false`. See https://github.com/nunit/nunit/commit/feb226fe9180b07b6c348bcb30f6e745ec5850da#r30332971

This initially looks like a mistake - it would be good to verify that, and also work out why the tests passed on CI, and on my local machine, but not for @oznetmaster. (And of course, if we can write a test to fill whatever the gap is!)

**Comment by ChrisMaddock** [comment]
cc @DaiMichael - appreciate this has been a long running issue, however you're help in figuring this one out would be appreciated! 😄

**Comment by oznetmaster** [comment]
From the commit:

Not any more. I corrected the errors, and all of the DictionaryContainsKeyConstraintTests now pass.

With the errors, many of the DictionaryContainsKeyConstraintTests test failed.

I was debugging that failures and saw these routines fail in the debugger.

This is why I am very confused as to how the tests pass for everyone else.

Unless, in the regular .NET environment, those two routines are never being called? Remember, I am running the tests in the CF environment. Not sure why it would be different.

Can someone see if they are ever actually called in regular .NET?

Remember that generics are handled totally differently in CF then they are in regular .NET.

**Comment by oznetmaster** [comment]
It is not the return that is the error.  It is the comparison.  The returns are correct if the comparison is corrected.

**Comment by DaiMichael** [comment]
@ChrisMaddock @oznetmaster I'll take a look, I'll be honest neither myself nor @jnm2 were 100% happy with this solution but it "worked" or so it seemed.... I'll revisit.

**Comment by ChrisMaddock** [comment]
Great - thanks @DaiMichael. 🙂

**Comment by DaiMichael** [comment]
@ChrisMaddock @oznetmaster 

I'm going with a PR on this so you guys can take a peek. I've got it working, this is purely for `.Net Standard 1.4`, which I'm growing to err... finding lack of features hard work.... 😞 

My tests all work and I now understand why they all work 😆, I won't pretend it is the best thing in the world but I have spent quite a bit of time on this and this is the only solution I got working with no side effects and passes all the tests.

I'll add a comment in the PR about the method...
