### ISSUE TITLE
Assembly Resolving HowTo

### ISSUE THREAD

**Issue by HaegerPilz** [nunit/nunit#2995]
Hi,

Our software product is big system (more then 300 DLLs). We are using Nunit 3.* to test this system. 
We have nunit tests which start the whole system and then do a lot of tests. The whole system is then loaded inside of the Nunit.exe. Tests are initializing the product and so on ...
The product is compiled into the System\bin  folder. 

The complex tests must be also compiled into the System\bin folder because they must find the product dlls at runtime . My job is to move the test DLLs out of the System\bin folder to another folder. 
The test DLL references the product dlls. Compile of the tests into another folder is working fine. The problem is when the tests starts. 

The tests using - at startup - an AssemblyResolver  which will find the needed product Dlls in the System\bin.
Code looks like this:
```
 public class Test
{
       //start the Assembly ressolver
       private ResolverClassLocatedByTheTest AssemblyResolver = AssemblyRessolver();
        [Test]
        public void TestIt()
        {
             CallTestMethod()
        }
        private CallTestMethod()
       {
             TypeOfAProductDLL myObject = new TypeOfAProductDLL()
             Assert.NotNull(myObject)
      }
```
When CallTestMethod() is called the AssemblyRessolver is able to find the type _TypeOfAProductDLL_ and load the needed DLL which contains the type in the System\bin folder.

But there are tests which will not work 
I think the problem is that the TypeOfAProductDLL cannot be loaded because Nunit BL comes first.
Here is an example:
```
 public class Test
{
       private ResolverClassLocatedByTheTest AssemblyResolver = AssemblyRessolver();
      //Using this productType as Member will not work
       TypeOfAProductDLL MemberVarMyObject = new TypeOfAProductDLL()
        [Test]
        public void TestIt()
        {
             //using productType direct in the test method will not work
             TypeOfAProductDLL localVarMyObject = new TypeOfAProductDLL()
        
             Assert.NotNull(localVarMyObject)
        }
```

In the code example above the  TypeOfAProductDLL cannot be loaded when they are used as a member variable or direct in the test method. I think it comes from the point when Nunit Runner begins to analyse and tries to find the unkown types. The AssemblyResolver  is not startet at this point.
Is there a way to solve this? Can I start the AssemblyResolver  at DLL load time?

I have seen that there is the newer NunitLite with that I would be able to activate Assembly Ressolver into the main method. 
But then I must use an Console.Exe. A lot of developers are using Resharper and I haven' t found a way to run tests in resharper with the new Nunit Lite concept which is using a Console.exe.

Can someone give me some hints how to handle this problem without patching the Nunit Dll?
The best  would be to start the AssemblyRessolver before Nunit BL starts but using it as a test dll that it is still runable in resharper.

regards

HaegerPilz

**Comment by rprouse** [comment]
Can you instantiate one `AsemblyResolver` for your entire test run using the `SetUpFixture` attribute?

See https://github.com/nunit/docs/wiki/SetUpFixture-Attribute

**Comment by HaegerPilz** [comment]
Hi,
the solution with the SetUpFixture is not working.
The problem is always the same - the .net call for _GetTypes_().
In the nunit Framework there is the base method _GetCandidateFixtureTypes_ that creates a collection all types of the test assembly. This list will be used for analyses to find the different fixtures.
Calling _GetTypes_() leads to a crash (assembly not found) for scenarios decribed above.
 
The only possible idea I  see is to expand Nunit.framework by another preparation call like _BaseSetUpFixture_. This must be inside of a base preparation DLL. Nunit.framework get knowledge about this dll by a config file (app.config). If this _BaseSetUpFixture_ is configured then the Framework is calling this _BaseSetUpFixture_ before loading the test assembly.
In _BaseSetUpFixture_ some global preparations like starting the assembly ressolver could be done.

Would It possible to have such a feature in the near future`?

regards

Haeger

**Comment by CharliePoole** [comment]
Do you have code in the test assembly that generates data for tests? Does that code require loading the product? If so, nothing you do at test __execution__ time, including Setup, can resolve the problem. Additionally, nothing that resides in your test assembly can resolve the problem if the test assembly cannot be loaded due to missing references.

Not a solution, I realize, but knowing what can't work may be useful.

**Comment by mikkelbu** [comment]
I'm not sure this will work, but what if you used assembly bindings instead of the `AssemblyResolver`? I.e. adding app.configs to the test dll's and the place information about where to find the production code dlls that the tests use.

It is somewhat difficult to get working - at least for me - and require some understanding of how .NET loads dll's. See e.g. https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/codebase-element and use [fuslogvw](https://docs.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer) to see how .NET tries to find the dll's at run time.

**Comment by HaegerPilz** [comment]
Hi together, 

@CharliePoole: Yes I agree - nothing inside of the test.dll can solve the problem. The only chance I see is, that the Nunit Runner is calling a preparation DLL (configured by the User) which starts the AssRes before the regular Test dll is analysed. I don't think that Nunit is offering such a possibility?

@mikkelbu: I already read about the .net assembly ressolving.  
> If the assembly has a strong name, the codebase setting can be anywhere on the local intranet or the Internet. If the assembly is a private assembly, the codebase setting must be a path relative to the application's directory. 

I cannot ressolve the needed DLLs because they are not strong named and they are at three different locations  below programm folders under c:\.


regards

Haeger

**Comment by rprouse** [comment]
I am closing old uncategorized issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
