### ISSUE TITLE
PlatformAttribute for .NET Core

### ISSUE THREAD

**Issue by dos-ise** [nunit/nunit#2997]
Are there any reasons why the PlatformAttribute is not available on .NET Core/.NET standard? Is it planned to be ported?

Using Environment.OSVersion.Platform it would be possible to port.

Would be super useful to me :)

**Comment by ChrisMaddock** [comment]
Nope - simply not implemented yet! We'd love a Pull Request, if you'd be interested in contributing this?

This is covered in more detail here: https://github.com/nunit/nunit/issues/2432 I'm going to close this issue as a duplicate - but if you'd be interested in contributing this - please leave a comment on the other issue, and claim it for yourself!
