### ISSUE TITLE
TestCategory Attribute is ignored when running test via dotnet cli when placed on class

### ISSUE THREAD

**Issue by dos-ise** [nunit/nunit#2998]
I am having an issue when running my dotnet core test on an linux machine. 
The category only works when the testCategoryAttribute is placed on an individual test.
When the testCategoryAttribute  is placed on the testclass the tests are executed although they should be execluted via the filter.

Is this a known problem or am I doing something wrong?

**Comment by ChrisMaddock** [comment]
Can you share details of exactly which filter your passing to dotnet test?

**Comment by ChrisMaddock** [comment]
Issue moved to [nunit/nunit3-vs-adapter #542](https://github.com/nunit/nunit3-vs-adapter/issues/542) via [**ZenHub**](https://www.zenhub.com/)
