### ISSUE TITLE
Assert.That with Throws should allow asserting on lambda property

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#30]
To assert a property name, one can use the following

``` C#
Assert.That (testDelegate, 
    Throws.ArgumentException.With.Property("ParamName").EqualTo ("name"));
```

or this one, as a refactor-friendly way

``` C#
Assert.That (testDelegate, 
    Throws.ArgumentException.And.Matches<ArgumentException> (x => x.ParamName == "name"));
```

It works but the error text reported when the assert is not satisfied is rather generic:

```
Expected: <System.ArgumentException> and value matching lambda expression
```

There should be an easier way to express the intent and have a better error message, something like:

``` C#
Assert.That (testDelegate, 
    Throws.ArgumentException.And.Property(ex => ex.ParamName).EqualTo ("name"));
```

with the error reporting:

```
Expected: Property lambda ex.ParamName with value "name"
but got
Property lambda ex.ParamName with value "myParam"
```

TestCaseData migh also benefit from this if it implemented the lambda property functionality.

As discussed here: https://groups.google.com/forum/#!topic/nunit-discuss/Fg0oFzR8owE

From https://bugs.launchpad.net/nunit-3.0/+bug/1099517

**Comment by CharliePoole** [comment]
@aschlapsi Any progress for the alpha-5 release or should this be postponed?

**Comment by aschlapsi** [comment]
We should postpone it for the next alpha release.

**Comment by CharliePoole** [comment]
@aschlapsi What's the status of this one?

**Comment by rprouse** [comment]
@aschlapsi, I assume you haven't made any progress on this. Let me know or I am going to remove you as the assignee to give someone else a chance to work on it. Thanks.

**Comment by aschlapsi** [comment]
I haven't made any progress on this. I remove myself as the assignee.

**Comment by elbaloo** [comment]
Any ideas on how to implement this?

>There should be an easier way to express the intent and have a better error message, something like:


>>```csharp
Assert.That (testDelegate, Throws.ArgumentException.And.Property(ex => ex.ParamName).EqualTo ("name"));
>>```

Is the expectation with the above syntax to be able to provide Property method a reference to the actual Property member?

For this syntax to work, or be closer to work we would need something more like:
```csharp
Assert.That (testDelegate, Throws.ArgumentException.And.Property<ArgumentException>(ex => ex.ParamName).EqualTo ("name"));
```
Which assumes Property would be defined something like:
```csharp
public ReturnType Property<T>(Func<T, object> del) { ... }
```
But then how would ``` Func<T, object> del``` within Property get a reference to the actual exception thrown, in this case? Not sure if making sense here, am I way too lost?

**Comment by CharliePoole** [comment]
Yes, I think you've come quickly to see why this is challenging. :-)

**Comment by CharliePoole** [comment]
We have not worked on this, it's challenging and we need to get out the RC. Postponing.

**Comment by rprouse** [comment]
Nobody has picked this up and nobody else has asked for this so closing.
