### ISSUE TITLE
Create an NUnit Visual Studio Template

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#300]
From the discussion in nunit/nunit-vs-adapter#51

See that issue for the discussion on including the service tag the Visual Studio automatically adds to NUnit projects.

```xml 
<ItemGroup>
    <Service Include="{82A7F48D-3B50-4B1E-B82E-3ADA8210C358}" />
</ItemGroup>
```

If we did a template, I would probably publish it as a Visual Studio extension and install it with the regular NUnit install. I've done a few templates for work including a test template. They aren't too hard, just a bit fiddly.

Installing is easy, you just need to copy the Zip file into every supported version of Visual Studio at,

C:\Users\{user}\Documents\Visual Studio {version}\Templates\ProjectTemplates\Visual C#

If we put the template into a subdirectory like NUnit or Test, it will appear under that node in the New Project dialog.

**Comment by rprouse** [comment]
This issue was moved to ideas, not sure if it should be there. It is started and actually nearly ready for release. See https://github.com/nunit/nunit.templates

**Comment by CharliePoole** [comment]
I did all my initial moves purely mechanically. That is is:idea => Ideas milestone.

This one progressed form idea to actually doing it but nothing ever got reflected in the labels.

**Comment by CharliePoole** [comment]
Marked this as a feature, even though it's a separate project. We can close it when we release.

**Comment by rprouse** [comment]
The templates have been [released on GitHub](https://github.com/nunit/nunit.templates/releases/tag/v1.0) and on the [Visual Studio Gallery](https://visualstudiogallery.msdn.microsoft.com/6cd55f79-4936-49e7-b81d-c40fcd81abc7)
