### ISSUE TITLE
Wrong error message for CollectionAssert.IsSubsetOf() method

### ISSUE THREAD

**Issue by Reineke4** [nunit/nunit#3002]
![2018-09-03_151033](https://user-images.githubusercontent.com/12124057/44986632-1c02df80-af8d-11e8-9fca-0a1e3508820e.jpg)

I think, that expected and actual result are shown in contrary in error message

**Comment by CharliePoole** [comment]
The wording of the message indicates that `<4>` is not a subset of <1,2,3>. Because of the standard "Expected... but was" phrasing, it doesn't read as naturally as it might but it's correct.

**Comment by Reineke4** [comment]
Thank you for your answer! 
Now I agree that actual message is correct. But I still feel a misunderstanding of the message.
Off course, it’s only my opinion, and I can't describe why. But it much more naturally to read something like: 
Expected: superset for <4>
But was: < 1, 2, 3>

It looks like as error message for CollectionAssert.Contains() method.
