### ISSUE TITLE
Is there any assertion method which checks given parameter has default value?

### ISSUE THREAD

**Issue by mstrYoda** [nunit/nunit#3006]
Would not be a good feature to have assertion for default value control?

What in my mind is looks like below :

```c#
Assert.IsDefault(someVariable);
```

I made some research about it but I could not find any feature like above.

I don't want to check given values manually by asserting as something like below:

```c#
Assert.Equals (someVariable, default(TypeOfVariable));
```

If it useful to you I wish to make a contribution to add that functionality.

**Comment by CharliePoole** [comment]
There is not. If you would like to contribute it, it will be useful to provide a more complete use case. That is, why do you want to be able to do this in a test?

**Comment by mstrYoda** [comment]
@CharliePoole Well sometimes we came across situations like we need to check an object is just initialized or properties has values. As far as I know, checking a value or property has default value, is the only way to check if a variable initialized.

So I think it would be useful to have that functionality.

**Comment by CharliePoole** [comment]
It's tricky, however, since some default values may also be set expressly. For example, an int may be set to zero. If I really wanted to be sure that a setter had been used, I'd use a mock to verify it.

OTOH, it's easy enough to implement.

**Comment by mstrYoda** [comment]
Well, you saying that it is a useless feature? Then I think issue should close.

**Comment by CharliePoole** [comment]
I said what I would do. I'm just one person. We find out whether features are likely to be useful by kicking them around in discussion. And, in the positive vein, I said it's easy to implement. 😄 

I suggest waiting (patiently or impatiently) for comments.

**Comment by mstrYoda** [comment]
@CharliePoole what you think about this issue? Could you add others to discuss about it?

**Comment by CharliePoole** [comment]
@mstrYoda The issue is visible, but as a reminder: @nunit/framework-team can folks let him know what, if anything, will happen with this?

**Comment by jnm2** [comment]
Can someone remind me whether or not we would still expanding the Assert class instead of adding the syntax `Assert.That(value, Is.Default);`?

Also, this method absolutely must be generic. If it's not generic, it won't be able to tell the difference between these two cases:

```c#
object x = 0;
Assert.That(x, Is.Default); // Should fail

int y = 0;
Assert.That(x, Is.Default); // Should succeed
```

**Comment by jnm2** [comment]
Yes. @mstrYoda Here are the alternatives right now:

```c#
// For reference types:
Assert(expr, Is.Null); // Recommended
Assert.IsNull(expr);

// For value types:
Assert(expr, Is.EqualTo(default(TheValueType)); // Recommended
Assert.AreEqual(default(TheValueType), expr);
```

What value would `Is.Default` bring to the table?

**Comment by mstrYoda** [comment]
@jnm2 I came this sitiuation with some use-case, I need to check a variables of an object has initialized. I want to avoid writing if conditions and type checkings in my code.

But I convinced that I should go with provided examples. Actually, I was write the code like that in the beginning.

Issue should be closed, thank you guys for helping.
