### ISSUE TITLE
ParrallelScope has one additional undocumented value

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#3010]
There is a ParallelScope.All value which is the same as ParallelScope.Self + ParallelScope.Children.

It is visible in Intellisense, but is not documented.

**Comment by ChrisMaddock** [comment]
Looks that way to me - moving this issue to docs. 🙂

**Comment by ChrisMaddock** [comment]
Issue moved to [nunit/docs #284](https://github.com/nunit/docs/issues/284) via [**ZenHub**](https://www.zenhub.com/)
