### ISSUE TITLE
Upgrade nunit-vs-adapter to 3.10 for nUnit 3.11

### ISSUE THREAD

**Issue by DaiMichael** [nunit/nunit#3020]
Should we upgrade nunit-vs-adapter to latest version 3.10. I have been having issues with running tests for .Net Core and using this fixes my issues for this reason :

https://github.com/nunit/nunit3-vs-adapter/issues/325

I'm happy to fix and PR if agreed.

**Comment by jnm2** [comment]
Please do, thank you!
