### ISSUE TITLE
Unable to add `.IgnoreCase` modifier to an `AnyOf` constraint in collection constraints

### ISSUE THREAD

**Issue by BrianDiggs** [nunit/nunit#3024]
# Summary

Unable to add `.IgnoreCase` modifier to an `AnyOf` constraint in collection constraints.

# Reproducible example

## Goal

I was creating an assertion that all the (string) elements of a collection were one of a
set of possibilities, with a case insensitive comparison

## Code

    Assert.That(new string[] { "red", "red", "red", "green" }, 
        Is.All.AnyOf(new string[] { "RED", "BLUE", "GREEN" }).IgnoreCase);

## Expected result

Assertion passed

## Acutal result

Compilation error:

> 'Constraint' does not contain a definition for 'IgnoreCase' and no
> extension method 'IgnoreCase' accepting a first argument of
> type 'Constraint' could be found (are you missing a using directive or an
> assembly reference?)

# Variations/workarounds

A simpler version for a single value instead of all the elements of a collection works:

    Assert.That("red", Is.AnyOf(new string[] { "RED", "BLUE" }).IgnoreCase);

A suggested variation from Charlie also works

    Assert.That(new string[] { "red", "red", "red", "green" }, 
      new AllItemsConstraint(
        Is.AnyOf(new string[] { "RED", "BLUE", "GREEN" }).IgnoreCase));

# Hypothesis of problem

The returned type of the `AnyOf` method are different in the two cases. `Is.AnyOf` returns type `AnyOfConstraint`. For `Is.All.AnyOf`, `Is.All` returns a `ConstraintExpression` and `ConstraintExpression.AnyOf` returns a `Constraint`. Were the return type `AnyOfConstraint`, then `AnyOfConstraint.IgnoreCase` could be invoked. I'm not sure if there are other implications to changing the return type.

# References

I asked [a question on StackOverflow about this](https://stackoverflow.com/q/52322519/892313) which is where Charlie provided a workaround.

**Comment by CharliePoole** [comment]
I think we should provide this and I see two approaches:

1. Simply add the modifier to `AnyOfConstraint` just like `EqualConstraint`
2. Add it to `Constraint` and remove from `EqualConstraint` as well as any others that have it.

The side effect of option 2 is that you will be able to use `.IgnoreCase` in situations where it will be ignored, which could be confusing to users. Up to now, we have tried to keep that from happening.

**Comment by CharliePoole** [comment]
You're right! I looked at  this on SO and saw that, but it slipped my mind just now. So, scratch 1.

Option 2 is probably all there is left to do about this. We already allow modifiers to be used even though they don't end up getting used. Best example is IgnoreCase itself. You can add it to an equality constraint even though that constraint has nothing to do with strings.

As a further refinement of 2, we may want to add more runtime error checking, if the modifier is used in some case where it should not be used. Alternatively, use inheritance to partition constraints into those that can use this modifier and those that can't.

**Comment by BrianDiggs** [comment]
It seems that changing the signature of `ConstraintExpression.AnyOf` would be a narrower change.

`ConstraintExpression.AnyOf()` returns `Constraint` (according to its signature)
`Is.AnyOf()` returns `AnyOfConstraint` (according to its signature)

Both return an instance of an `AnyOfConstraint`. Since `AnyOfConstraint` inherits from `Constraint`, that's valid. 

Is there any reason that the signature of `ConstraintExpression.AnyOf()` can't be changed to say it returns an `AnyOfConstraint` rather than just a `Constraint`? If it was changed, `Is.All.AnyOf().IgnoreCase` would be valid just like `Is.AnyOf().IgnoreCase` is.

**Comment by CharliePoole** [comment]
I could be overthinking this! I was thinking it was some issue of precedence between `All` and `AnyOf`, but if it's merely the signature of `ConstraintExpression.AnyOf`, that would be way easier. We should try that idea first. It will either work or we'll discover the reason for the use of `Constraint` in the signature.

Are you interested in doing a PR?

**Comment by mikkelbu** [comment]
Closed by #3025
