### ISSUE TITLE
Remoting exception when getting the TestContext.CurrentContext.Test.FullName value in OneTimeSetup

### ISSUE THREAD

**Issue by AutomationSifu** [nunit/nunit#3026]
**Description**:

When trying to access the TestContext.CurrentContext.Test.FullName value in a OneTimeSetup method I receive a Remoting Exception in the NUnit Gui (TestCentric)

**Current Setup**:

I'm trying to pass in the TestContext.CurrentContext.Test.FullName value to a TestFixture as a param.  The The TestFixture class inherits a BaseTest class where a OneTimeSetup method gets the TestContext.CurrentContext.Test.FullName value.

I've done some research and it appears that I I'm possibly trying to get the TestContext.CurrentContext.Test.FullName value before it's available, but I'm not 100% sure.  I'm currently running the tests using the new NUnit Gui (TestCentric), so I'm not sure if that is part of the issue or not.  As long as I'm getting the TestContext.CurrentContext.Test.FullName value in a OneTimeSetup method, shouldn't it be able to access the value during that time?

**Tools/Version numbers:**

NUnit - 3.9.0
NUnit Gui (TestCentric) - pre-release
NUniteTestOrdering - 1.0.0-beta1

**Error Message**:

`'System.Runtime.Remoting.RemotingException : This remoting proxy has no channel sink which means either the server has no registered server channels that are listening, or this application has no suitable client channel to talk to the server.' />
   <property name='_PROVIDERSTACKTRACE' value='   at System.Runtime.Remoting.Proxies.RemotingProxy.InternalInvoke(IMethodCallMessage reqMcmMsg, Boolean useDispatchMessage, Int32 callType)   
at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData&amp; msgData, Int32 type)   
at NUnit.Framework.Internal.TestExecutionContext.get_CurrentTest()   
at NUnit.Framework.TestContext.get_Test()   
at Tests.BaseTest.&lt;get_FixtureParamsData&gt;d__52.MoveNext() in C:\Users\[username]\Source\Workspaces\QA -Test Automation Repository\Project\Automation - ...\BaseTest.cs:line 452   
at NUnit.Framework.TestFixtureSourceAttribute.GetParametersFor(Type sourceType)' />`

**Comment by mikkelbu** [comment]
Hi @AutomationSifu 

Can you provide a small example of what you are trying to do? When I run the following in either VS or using the console, I get two test failures (as expected). Ps. using NUnit 3.10.1.
```
1) Failed : TestNameInOneTimeSetup.Class1.Test1
  Expected string length 3 but was 29. Strings differ at index 0.
  Expected: "One"
  But was:  "TestNameInOneTimeSetup.Class1"
  -----------^
   at TestNameInOneTimeSetup.Class1.Test1() in C:\Users\Mikkel\Source\Repos\TestNameInOneTimeSetup\TestNameInOneTimeSetup\Class1.cs:line 23

2) Failed : TestNameInOneTimeSetup.Class1.Test2
  Expected string length 3 but was 29. Strings differ at index 1.
  Expected: "Two"
  But was:  "TestNameInOneTimeSetup.Class1"
  ------------^
....
```

```c#
    [TestFixture]
    public class Class1
    {
        string testName = null;
        [OneTimeSetUp]
        public void SetUp()
        {
            testName = TestContext.CurrentContext.Test.FullName;
        }

        [Test]
        public void Test1()
        {
            Assert.That(testName, Is.EqualTo("One"));
        }

        [Test]
        public void Test2()
        {
            Assert.That(testName, Is.EqualTo("Two"));
        }
    }
```

**Comment by AutomationSifu** [comment]
Hi @ mikkelbu

No problem my pleasure.  I created a solution with the files below, let me know if that helps.  I've tried to keep the files as small as possible to recreate the issue.  I was able to recreate the issue with the files listed below.

Please note:  I was able to recreate the issue without the EnableTestOrdering.cs file

**Libraries/Version Numbers:**

.Net Framework - 4.61
NUnit - 3.9.0
NUnitTestOrdering - 1.0.0-beta1
NUnit Gui (TestCentric) - pre-release


**EnableTestOrdering.cs**

`using System;
using NUnitTestOrdering.FixtureOrdering;
using TestFixtureTestContextExample;

[assembly:EnableTestOrdering]

[OrderedTestFixture]

public sealed class EnableTestOrdering : TestOrderingSpecification
{

    protected override void DefineTestOrdering()
    {

        OrderedTestSpecification<TestFixture1>();

    }

    protected override bool ContinueOnError => true;

    }

public sealed class TestFixture1 : TestOrderingSpecification
{

    protected override void DefineTestOrdering()
    {

        TestFixture<UnitTest1>();

    }

    protected override bool ContinueOnError => true;

}`

**BaseTest.cs**

`using NUnit.Framework;
using System.Collections;

namespace TestFixtureTestContextExample
{
    public class BaseTest
    {

        [OneTimeSetUp]

        public void firstTest()
        {
            GetFixtureParamsData();

        }

        public static IEnumerable GetFixtureParamsData()
        {
            string testName = TestContext.CurrentContext.Test.FullName;

            yield return new TestFixtureData(testName);


        }

        public static IEnumerable FixtureParamsData
        {

            get
            {
                return GetFixtureParamsData();
            }
        }
    }
}`

**UnitTest1.cs**

`using System;
using NUnit.Framework;

namespace TestFixtureTestContextExample
{
    [TestFixture]
    [TestFixtureSource(typeof(BaseTest), "FixtureParamsData")]
    public class UnitTest1:BaseTest
    {

        public string tc_name;

            public UnitTest1(string tc_name)
        {
            this.tc_name = tc_name;

        }


        [Test]
        public void TestMethod1()
        {

            Console.WriteLine("Test Case Name: " + tc_name);

        }
    }
}`

**Error Message**

`System.Runtime.Remoting.RemotingException : This remoting proxy has no channel sink which means either the server has no registered server channels that are listening, 
or this application has no suitable client channel to talk to the server.' />
   <property name='_PROVIDERSTACKTRACE' value='   
at System.Runtime.Remoting.Proxies.RemotingProxy.InternalInvoke(IMethodCallMessage reqMcmMsg, Boolean useDispatchMessage, Int32 callType)   
at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData&amp; msgData, Int32 type)   
at NUnit.Framework.Internal.TestExecutionContext.get_CurrentTest()   
at NUnit.Framework.TestContext.get_Test()   
at TestFixtureTestContextExample.BaseTest.&lt;GetFixtureParamsData&gt;d__1.MoveNext() in 
c:\users\[username]\documents\visual studio 2015\Projects\TestFixtureTestContextExample\TestFixtureTestContextExample\BaseTest.cs:line 19   
at NUnit.Framework.TestFixtureSourceAttribute.GetParametersFor(Type sourceType)' />`

**Comment by AutomationSifu** [comment]
Thanks @CharliePoole 

I had an idea that was the issue.
Is there any documentation that could give more details on the order of execution in NUnit?

Not a problem I'll retry with the NUnit Console.

**Comment by CharliePoole** [comment]
There used to be such a page, but I can't seem to locate it. @nunit/framework-team Does anyone have a link?

An adhoc test context is automatically created when you call for a test execution context when none exists. This was done to avoid NREs, but I'm afraid it may have the side effect of masking actual errors from the user. :-(

**Comment by AutomationSifu** [comment]
I took a look at TestCentric and noticed something interesting.  In the screenshot below the Full Name value is populated.  This is before running a test and I still have the remoting exception.

Is the Full Name value the same test Full Name value NUnit is picking up or another Full Name value only used in TestCentric?

![image](https://user-images.githubusercontent.com/42382190/45834026-297dd080-bcd4-11e8-843a-9c9cb6c23d95.png)

**Comment by CharliePoole** [comment]
I see that you are using the experimental GUI, which has had no development for quite a while. I imagine that you have simply uncovered a bug in it.

The experimental GUI is at a very early pre-alpha stage (hence "experimental") and is quite definitely not recommended for your production work.

The actual TestCentric Gui is in alpha release and while not yet production would be more suitable for your use right now. See https://github.com/TestCentric/testcentric-gui

**Comment by AutomationSifu** [comment]
Thanks for the clarification, I thought I didn't know there was another project for TestCentric.  

I read the documentation and was looking for a pre-release build for TestCentric Runner for NUnit - Version 0.1.  I'm very new to GitHub so if you could point me in the right direction I would really appreciate it.

Thanks!

**Comment by AutomationSifu** [comment]
Awesome thanks!

**Comment by AutomationSifu** [comment]
I was able to download and use the alpha release of the Test Centric Gui.
  -  I no longer get the RemotingException error but an error message that's more clear.

I think I have an idea now what I should be looking for.  Let me know if I'm on the right track.

I should be looking to access the Full Name of the test by using one of the Load-Time Interfaces?

  -  It appears that should be a way to pull this data in with TestFixtureAttribute.GetCustomAttribute... ?

I'm still trying to figure how to use this class and hopefully this works.

**Comment by rprouse** [comment]
I am closing old uncategorized issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
