### ISSUE TITLE
ShouldPassAfter2RepeatsAndTimeoutIsResetEachTime timeout is too short for CI

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#3031]
I've seen this fail the net35 macOS build half a dozen times recently:

> 1) Failed : NUnit.Framework.Attributes.RepeatableTestsWithTimeoutAttributesTests.ShouldPassAfter2RepeatsAndTimeoutIsResetEachTime
> Test exceeded Timeout value of 85ms

Our timing tests should strive for a very fast success path but a very forgiving failure path since timing is at the mercy of shared computing resources.

**Comment by CharliePoole** [comment]
Agree in general, but that's not possible here. As noted in the original discussion, I don't think this should be a timing test. Trying to verify that timing is reset for each retry by means of a timing test forces the timing to become very unforgiving. A different way to test it is needed.

**Comment by MatthewBeardmore** [comment]
I think this should be fixed by #3014.

**Comment by mikkelbu** [comment]
You are right @MatthewBeardmore. This is closed by #3062.
