### ISSUE TITLE
APIs to restore before 3.11

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#3032]
Diffed 3.10.1 and master. These APIs had breaking changes to revert from https://github.com/nunit/nunit/pull/2796 before 3.11 is released:

- [x] IFixtureBuilder.BuildFrom (keep new IFixtureBuilder2 consistent)
- [x] IFixtureBuilder2.BuildFrom
- [x] IMethodInfo (undelete)
- [x] IParameterDataProvider.GetData
- [x] IParameterDataSource.GetData
- [x] IParameterInfo (undelete)
- [x] IReflectionInfo (undelete)
- [x] ISuiteBuilder.BuildFrom (2)
- [x] ISuiteBuilder.CanBuildFrom
- [x] ITest.Method
- [x] ITest.TypeInfo (incl rename)
- [x] ITestBuilder.BuildFrom
- [x] ITestCaseBuilder.BuildFrom
- [x] ITestCaseBuilder.CanBuildFrom
- [x] ITypeInfo (undelete)

Should be covered by the above:

- [x] RandomAttribute.GetData
- [x] RangeAttribute.GetData
- [x] SetUpFixtureAttribute.BuildFrom
- [x] TestAttribute.BuildFrom
- [x] TestCaseAttribute.BuildFrom
- [x] TestCaseSourceAttribute.BuildFrom
- [x] TestFixtureAttribute.BuildFrom (2)
- [x] TestFixtureSourceAttribute.BuildFrom (2)
- [x] ValueSourceAttribute.GetData
- [x] ValuesAttribute.GetData
- [x] Test.Method (undelete)
- [x] Test.TypeInfo (incl rename)

Do not restore:

- [x] Test.DeclaringTypeInfo (mutable protected field in Internal namespace)

**Comment by jnm2** [comment]
@CharliePoole Would you want to take this opportunity to change the IPrefilter.IsMatch overloads from `Type type` and `Type type, Methodinfo method` to `ITypeInfo typeInfo` and `ITypeInfo typeInfo, IMethodInfo method`?

**Comment by CharliePoole** [comment]
Do you see an advantage to that? As currently defined users make use of well-known .NET Types and it's up to us to implement it.

**Comment by jnm2** [comment]
@CharliePoole Consistency with the other interfaces is the only reason I can think of, but we don't expect users to implement IMethodInfo and therefore I can't think of any inherent reason that it would be better.
