### ISSUE TITLE
RequiresThreadAttribute allows ApartmentState.Unknown, unlike ApartmentAttribute

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#3042]
Does it make sense to allow `[RequiresThread(ApartmentState.Unknown)]`?

**Comment by ChrisMaddock** [comment]
I guess it makes sense if https://github.com/nunit/nunit/issues/3041 is differentiating between MTA and 'UnInitialized' - and in which case is should be 'Uninitialized' instead?

These are hierachical, right? Presumably I would want this if I wanted to make an entire assembly as STA, and then certain fixtures as 'not-STA'?

Is there a cost to permitting it? Other than the face I don't like the "Unknown" name? 😄

**Comment by CharliePoole** [comment]
Note that in older versions of .NET ApartmentState.Unknown meant "not yet set." If you did nothing, the apartment used was MTA.

**Comment by jnm2** [comment]
I left out part of the question, sorry. Given that `[RequiresThread]` is always allowed, should `[RequiresThread(ApartmentState.Unknown)]` be allowed? If so, should we allow `[Apartment(ApartmentState.Unknown)]`?

We can't change Unknown to Uninitialized unless we declare our own enum. :D

@CharliePoole I can't think of any use cases for running tests that care about the apartment state and need it to be uninitialized. The only reason it's worth differentiating between leaving COM uninitialized and setting it to MTA is just so we can error in one case and not the other on platforms other than Windows.

**Comment by ChrisMaddock** [comment]
I understand, sorry. Yes - I agree these two attributes should be consistent.

This is a good issue for first-time contributors! To anyone interested:

- Take a look at the existing check in ApartmentAttribute: 
https://github.com/nunit/nunit/blob/5163de63d94174f2857ac197248b1306164ee5d8/src/NUnitFramework/framework/Attributes/ApartmentAttribute.cs#L44

To close this issue, we should introduce a similar check in RequiresThreadAttribute. And of course, a unit test to support the behaviour!

**Comment by petmat** [comment]
I'll take a look at this if it's ok!

**Comment by jnm2** [comment]
Great, let us know if you need anything!

**Comment by mikkelbu** [comment]
Closed by #3058

**Comment by oznetmaster** [comment]
Not sure why this was necessary at all?  In fact, I think it is incorrect to change it.

"Note: This attribute, used with or without an ApartmentState argument will always result in creation of a new thread. To create a thread only if the current ApartmentState is not appropriate, use the ApartmentAttribute."

If no ApartmentState is specified, or ApartmentState.Unknown is specified, a new thread of the same ApartmentState as the current thread is used to run the test.  ApartmentState.Unknown only documents that it is whatever ApartmentState is current.

**Comment by CharliePoole** [comment]
I see your point. However, `ApartmentState.Unknown` in .NET means the state has not been initialized yet. We were using it to mean "don't care", which seems a bit confusing. 

The default constructor should still work - if it doesn't that's a bug - and users with ApartmentState.Unknown should be told to use that constructor instead.

**Comment by oznetmaster** [comment]
I would be ok with that.

If ApartmentState.Unknown is passed as the argument, then make it work the same as the default constructor, but issue a warning (like for an obsolete attribute).

**Comment by ChrisMaddock** [comment]
Is there specifically a strong motivation to allow `ApartmentState.Unknown`?

The key motivation of this change (for me!) was to make `RequiresThreadAttribute` consistent with `ApartmentAttribute`. I don't have any particularly strong opinions on which way that should have gone, other than specifying ApartmentState.Unknown feels slightly ambiguous, and would be unnecessary.

Given the work to make things consistent has already been done, if we have a clear reason to allow `ApartmentState.Unknown`, then lets update both attributes. If not, I'd be happy to leave this as is.

**Comment by ChrisMaddock** [comment]
Sounds reasonable - I have no strong opinions here. Will leave this to see what others think.

**Comment by CharliePoole** [comment]
It seems clearer to me if the two uses of ApartmentState work the same way. Either ApartmentState.Unknown is allowed or not. Even though the two attributes do two different things, the argument does the same thing in both cases. It specifies what ApartmentState should be used on any thread that is created.

The way to decide this sort of thing IMO is to imagine writing the documentation or answering user questions in either case. Pick the one that requires less explanation.

**Comment by oznetmaster** [comment]
Not really.  In the case of the ApartmentAttribute, the argument indicates the desired ApartmentState for the test to be run under.  If that is already the current ApartmentState, then the attribute is effectively a noop.  So if ApartmentState.Unknown were to be specified for the ApartmentState attribute, it is an obvious error, because it does not impart the required information.  Alterntively, it could just be a noop as well.  In the case of RequiresThreadAttribute, the argument indicates what kind of thread to create.  Allowing ApartmentState.Unknown actually specifically indicates the new thread does not know, or care, what its ApartmentState is, just as if the default constructor had been used.

**Comment by rprouse** [comment]
@oznetmaster do you actually use the `ApartmentState.Unknown` instead of the default constructor? To be honest, even though I also don't have strong opinions, like others, I think both usages should be consistent and I think using `ApartmentState.Unknown` instead of the default constructor might be okay, but it is confusing. I am going to close this one again.
