### ISSUE TITLE
Add .idea folder to .gitignore

### ISSUE THREAD

**Issue by madetara** [nunit/nunit#3048]
The title is self-explanatory.
It seems that people are switching to Rider as their IDE of choice for C# development on a higher rate.
It might be a good idea to add the .idea folder to .gitignore to avoid possible bad commits.

You can read about that folder [here](https://rider-support.jetbrains.com/hc/en-us/articles/207097529-What-is-the-idea-folder-).
tl;dr Rider specific settings and local history

**Comment by rprouse** [comment]
Good idea, feel free to submit a PR.
