### ISSUE TITLE
Conversion from TestCase string parameter to DateTimeOffset

### ISSUE THREAD

**Issue by Thorarin** [nunit/nunit#3053]
`TestCaseAttribute` includes behavior to perform conversion of some parameter types to the desired target type. Amongst others, conversion from `String` to `DateTime` and from `String` to `TimeSpan` are supported. This is useful, because no constants of these target types can be defined in the `TestCaseAttribute`.

It would be nice if `DateTimeOffset` could be added could be added to the list of supported conversions.

For example:

```C#
[TestCase("2018-10-09 15:15:00+02:00")]
public void MyTest(DateTimeOffset foo)
{
}
```

`Convert.ChangeType` does not appear to work for `DateTimeOffset`, so the code would be similar to the code for `TimeSpan`.

I wouldn't mind creating a PR for this if that helps; it seems fairly straightforward to add.

NUnit version: latest master

**Comment by jnm2** [comment]
I like this. If I understand correctly, `Convert` was a legacy class to help folks migrate to .NET from older VB. Type converters were the modern (.NET Framework 1.0) answer. If we simply get the default type converter for the parameter type and attempted to convert the string that way, would it behave the way you'd like?

@nunit/framework-team What do you think about TypeConverter? Needs `https://www.nuget.org/packages/System.ComponentModel.TypeConverter/` for the .NET Standard 1.4 build, and the .NET team really intends us to use packages like that and report issues if any still exist.

**Comment by oznetmaster** [comment]
Convert is used for anything that implement sthe IConvertible interface.

TypeConverter is for anything else.

I think we should fully support both.

**Comment by jnm2** [comment]
Good. Yes, I'm not proposing to stop using `Convert`. That would almost surely break someone.

**Comment by stevenaw** [comment]
@Thorarin Were you still working on this, or do you mind if give it a try?

**Comment by jnm2** [comment]
@stevenaw I do believe this item is free to work on, since we haven't put it up for grabs yet. All the feedback so far is positive, so let's go ahead.

@rprouse Does it seem fair to go ahead and assign @stevenaw?
