### ISSUE TITLE
TextFixture [Order] reverses order - Potentially a Bug?

### ISSUE THREAD

**Issue by Aarskin** [nunit/nunit#3055]
According to the documentation: https://github.com/nunit/docs/wiki/Order-Attribute

> The OrderAttribute may be placed on a test method **or fixture** to specify the order in which tests are run. 

Consider an intuitive example

    [TestFixture("A", false)]
    [TestFixture("B", false)]
    [TestFixture("A", true)]
    [TestFixture("B", true)]
    public class SampleFixture1
	{
		public SampleFixture1(string a, bool flag)
		{
			Trace.WriteLine("Fixture start.");
		}

		[Test]
		public void DummyTest() { }
	}

On debugging, this hits the constructor in the following order

    A, False
    A, True
    B, False
    B, True

Makes sense. Now consider this change (fixture itself is the same)

    [TestFixture("A", false), Order(0)]
    [TestFixture("B", false)]
    [TestFixture("A", true)]
    [TestFixture("B", true)]

On debugging, this hits the constructor in the following order

    B, True
    B, False
    A, True
    A, False

What's going on here - **is this expected somehow?** 

The fixtures run in this order independent of which `[TestFixture]` gets the `Order` attribute. 
It is also independent of if I change `Order(0)` to use a `1` or `2`

**Comment by CharliePoole** [comment]
This sequence of attributes...

```c#
[TestFixture("A", false), Order(0)]
[TestFixture("B", false)]
[TestFixture("A", true)]
[TestFixture("B", true)]
```
is equialent to

```c#
[TestFixture("A", false)]
[Order(0)]
[TestFixture("B", false)]
[TestFixture("A", true)]
[TestFixture("B", true)]
```

or even to

```c#
[TestFixture("A", false)]
[TestFixture("B", false)]
[TestFixture("A", true)]
[TestFixture("B", true)]
[Order(0)]
```

In fact, any randomized ordering of these five attributes does the same thing. It makes the fixture class, which follows it, run before any other fixture classes. That's obviously not what you want.

To cause one of the four instances of the fixture to run ahead of the others, we would need to add an `Order` property to `TestFixture`, in which case you could put `Order=0` inside the parentheses. However, we don't have such a property for `TestFixture` at this time.

**Comment by CharliePoole** [comment]
@Aarskin That's true for the current implementation, provided __no other data source__ is used on the same fixture. If the fixture had multiple data sources (i.e. `TestFixture` with args or `TestFixtureDataSource`) then the order is only deterministic within a given `TestFixtureDataSource`.

**Comment by rprouse** [comment]
I am closing old uncategorized issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
