### ISSUE TITLE
How can we pass parameters to [OneTimeSetUp] method?

### ISSUE THREAD

**Issue by alphonsajacob** [nunit/nunit#3057]
How can we pass parameters to [OneTimeSetUp] method?
In case of TestNG, we can use @Parameters along with @BeforeClass. Is there anyway to pass parameter to [OneTimeSetUp] in NUnit?

**Comment by sanojqa** [comment]
> How can we pass parameters to [OneTimeSetUp] method?
> In case of TestNG, we can use @parameters along with @BeforeClass. Is there anyway to pass parameter to [OneTimeSetUp] in NUnit?

**Comment by kkm000** [comment]
Probable duplicate: #3004.

**Comment by NicoAtTangelo** [comment]
I have the exact same question.
I'm using a pageObject model with:
- OneTimeSetup method in BaseTest class
- and my test

When I launch my test, the OneTimeSetup  method is ran.
How can I pass an argument to this OneTimeSetup method ??

If I get it well, I would need the TestFixture above my class, but which one ? BaseTest class containing my OnetimeSetup method ? Or my class containing my test ?

Would appreciate any help
Thanks

**Comment by CharliePoole** [comment]
@nunit/framework-team Should this not be closed as answered already?

**Comment by stevenaw** [comment]
Thanks @CharliePoole I agree this should be closed as answered.
@NicoAtTangelo If you are still facing this issue, can you please see if Charlie's suggestion above works for you?

> You can usually achieve the same behavior with a TestFixture constructor argument. Save the value of the argument in a member field and use it in your OneTimeSetUp.
