### ISSUE TITLE
Complete RunAsyncAction tests in FrameworkControllerTests

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#3075]
There are currently three tests with all assertions commented out. We should either make them work, or remove them.

https://github.com/nunit/nunit/blob/cefc0c3a86c065daa4130aa255b1384db51b2b08/src/NUnitFramework/tests/Api/FrameworkControllerTests.cs#L520-L584

Here's where they were added, looks like the tests were never completed: https://github.com/nunit/nunit/pull/173#discussion-diff-16001892

**Comment by CharliePoole** [comment]
I commented that I was going to remove them in 2014 but never did! I believe they are simplly copies of the equivalent synchronous tests that were never fixed to work with RunAsync.

**Comment by yarhamjohn** [comment]
I can raise a PR to remove these tests
