### ISSUE TITLE
Regression from 3.10 to 3.11: Range in bytes

### ISSUE THREAD

**Issue by MartinZec** [nunit/nunit#3079]
Hello,

I have tests which define a Range in bytes. After the update from NUnit 3.10 to 3.11 those tests were not executable any more. I changed the data type form byte to int and the tests were executable again.

If the Range was defined in bytes, I got the attached error.
Example: public void test([Range(0x00, 0x0F)] byte value)
[git3.11.log](https://github.com/nunit/nunit/files/2525229/git3.11.log)

Best regards,
Martin

**Comment by jnm2** [comment]
@MartinZec Thank you for the repro! This would have been caused by my https://github.com/nunit/nunit/pull/2805. I will take a look as soon as I have a chance.

**Comment by jnm2** [comment]
This code does not repro the problem:

```cs

        [Test]
        public static void Test([Range(0x00, 0x0F)] byte test)
        {
        }
```

**Comment by MartinZec** [comment]
The issue was observed with testcentric 1.0 alpha.
Tests with Range in bytes are marked red and the exception is shown at the properties dialog of the test.

**Comment by jnm2** [comment]
If you switch the min and the max, the problem reproduces:

```cs
     [Test]
        public static void Test([Range(0x00, 0x0F)] byte test)
        {
        }
```

Negative steps are supposed to work in exactly this scenario, so I think we have our repro now.

(Workaround: specify the lower bound first.)

**Comment by MartinZec** [comment]
Just to be mentioned, in the example from @mikkelbu another small issue can be seen:
For the value "0" the test shoes "byte.MinValue" and not "0".

**Comment by mikkelbu** [comment]
@jnm2 But the example you have fails with "The step must strictly **decrease**." in line 87, but the error message in the first comment fails with "The step must strictly **increase**." in line 81, so it seems that the problems are related, but "opposite", so don't we still need a repo for the first example?

Ps. I've attached a debugger and the problem is that when we are decreasing from 15 down to 0 and then the next value is 255 which is more than 0, but I don't think I've time to look more at this tonight.

**Comment by jnm2** [comment]
@mikkelbu Ah, that's it! It's when it ends on a boundary. Here's the actual repro to fail on increase:

```c#
[Test]
public static void Test([Range(0xFE, 0xFF)] byte test)
{
}
```

To fail on decrease:

```c#
[Test]
public static void Test([Range(1, 0)] byte test)
{
}
```

It shouldn't be failing in either case.

**Comment by CharliePoole** [comment]
Cool! Nice catch. Looks like the last commit in #2805 is the culprit.

**Comment by jnm2** [comment]
Ah, I see it, thanks. So that the differences between the ints and the floats don't leak through to the common generic code, we should probably have a `step.TryApply` instead which handles the OVerflowException in the case of floats and handles rollover in the case of ints.
