### ISSUE TITLE
Reflect.cs not found

### ISSUE THREAD

**Issue by pandualuvala** [nunit/nunit#3080]
When debugging a test the test assembly breaks and gives the following stack trace information. Don't understand why the path says to look under "C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\" Instead of the current referenced folder. 

This is the stack trace : 

Locating source for 'C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Reflect.cs'. Checksum: SHA1 {db ae 17 40 7a 46 56 f6 79 ee 5a 25 c7 7 94 f1 97 c1 a5 de}
The file 'C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Reflect.cs' exists.
Determining whether the checksum matches for the following locations:
1: C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Reflect.cs Checksum: SHA1 {e5 6a a 57 84 6c 87 ed a6 10 f 3d 4e 53 a1 d4 de e6 c6 c8} Checksum doesn't match.
Looking in script documents for 'C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Reflect.cs'...
Looking in the Edit-and-Continue directory 'C:\Users\xxxx\Documents\GitHub\unity\MasterProject\enc_temp_folder\'...
The file with the matching checksum was not found in the Edit-and-Continue directory.
Looking in the projects for 'C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Reflect.cs'.
The file was not found in a project.
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\cvt\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\msclr\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\sys\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\thr\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\crt\src\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\crt\src\x64\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\crt\src\arm\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\crt\src\concrt\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\crt\src\i386\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\crt\src\linkopts\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\crt\src\stl\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\crt\src\vccorlib\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\crt\src\vcruntime\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\atlmfc\src\mfc\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\atlmfc\src\atl\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\atlmfc\include\'...
Searching for documents embedded in the symbol file.
An embedded document was not found.
The debug source files settings for the active solution indicate that the debugger will not ask the user to find the file: C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Reflect.cs.
The debugger could not locate the source file 'C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Reflect.cs'.    Any work around please let me know. Thanks.

**Comment by jnm2** [comment]
@pandualuvala Did you intend to turn off Just My Code and step into third-party code? (https://github.com/nunit/docs/wiki/Debugger-Source-Stepping)

**Comment by pandualuvala** [comment]
@jnm2 no i don't but it was throwing exception for it. Anyways i will enable Just My Code and Run the test and see .

**Comment by rajeshpvasudev** [comment]
Do you have any update on this ? I am getting the same error

**Comment by mikkelbu** [comment]
I just tried to recreate the issue and it also failed for me.

Some googling suggested (https://developercommunity.visualstudio.com/content/problem/62612/source-server-support-no-longer-work-with-assembly.html) to check ".NET Framework source stepping" (this as as sideeffect creates a symbol cache location). After this I'm possible to debug the code (and I can also remove the checkmark in ".NET Framework source stepping"). 

So apparently the symbol cache location is necessary in order to make this work. @pandualuvala and @rajeshpvasudev  can you see if this also solves the problem for you? (then I'll add a note of this on the wiki)

**Comment by pandualuvala** [comment]
So if you turn ON Just My Code then it will not throw the error but it breaks the assembly that is executing. Possibly cause of it is due to null reference exception happening some where in the code. But still the weird part for me is the the folder location where it is trying to look for the Reflect.cs. It should be the local installation referenced folder right?. Correct me if i am wrong on this.

**Comment by mikkelbu** [comment]
Closing this as answered and I have added some text about the problem in https://github.com/nunit/docs/wiki/Debugger-Source-Stepping.
