### ISSUE TITLE
XML Test-Suite Assembly does not contain DLL path anymore

### ISSUE THREAD

**Issue by TheJoKlLa** [nunit/nunit#3085]
In XML Result the attribute fullname of test-suite with the type "Assembly", does not contain an absolute filepath of the dll anymore.
NUnit-Framework 3.10.1:
```
<test-suite type='Assembly' id='0-1063' name='cgw_kammer.dll' fullname='C:\Users\thejoklla\source\repos\cgw_kammer\cgw_kammer\bin\Debug\cgw_kammer.dll' 
```
NUnit-Framework 3.11.0:
```
<test-suite type="Assembly" id="0-1063" name="cgw_kammer.dll" fullname="cgw_kammer.dll"
```
Tested with NUnit.Engine.Api 3.9.0

**Comment by dmitryserbin** [comment]
We're having the same issue here - test-suite fullname does not contain full assembly file path.

**Comment by bagavan44** [comment]
I am also facing the same issue with 3.11.0 version, if degrade it to 3.10.1 it was fine.

**Comment by mikkelbu** [comment]
@nunit/framework-team I just a quick look at this, and I think that #2913 introduced the problem in `DefaultTestAssemblyBuilder.cs` (more precisely in https://github.com/nunit/nunit/pull/2913/files#diff-1284be2d36700bc4ef1d6532a6242e25R83). The change was made on purpose, but it seems that we did not think about the effect on the result XMLs.
