### ISSUE TITLE
Rerunning tests in Resharper without rebuilding gives Inconclusive

### ISSUE THREAD

**Issue by jwg4** [nunit/nunit#3086]
Hi,
I have just upgraded our NUnit version from 3.5 -> 3.11. This led to a problem where when tests are re-run, but there haven't been any code changes, and so the project hasn't been rebuilt, the tests are not run, or running them fails, and the status comes back as Inconclusive. This happens every time the tests are run again. However, if I make a code change and then re-run, the code rebuilds, and the tests are run correctly.

I downgraded to 3.10.1 and everything works fine again.

This appears to be the same problem reported by 
@asendimitrov at https://github.com/nunit/nunit/issues/3008#issuecomment-430589028 - however this comment was made in what seems to be an unrelated issue, so I thought it was better to add a new issue

**Comment by Haukinger** [comment]
Same here

**Comment by rprouse** [comment]
@NikolayPianikov another related issue, can you help or know someone who can?

**Comment by NikolayPianikov** [comment]
@rprouse I asked for comments

**Comment by fbuyvolkot** [comment]
@jwg4 Could you please update to the latest release [ReSharper 2018.2.3](https://www.jetbrains.com/resharper/download/) (or try the most recent [ReSharper 2018.3 EAP](https://www.jetbrains.com/resharper/eap/) build) and check if you are able to repro the problem there as well?

**Comment by Ratcha9** [comment]
@fbuyvolkot I can reproduce with Ultimate 2018.2.3

**Comment by bjharo** [comment]
I recently updated to 3.11 and am seeing this too on Resharper 2016.1

**Comment by asendimitrov** [comment]
Hey guys, have we got any update on that one?

**Comment by papademos** [comment]
I had the same problem, and could solve it by either
1. Downgrade to nunit 3.10.1, or
2. Upgrade to the latest R# (atm 2018.3.3).

**Comment by mikkelbu** [comment]
At some point I would like to know how R# test execution is implemented, at least the high-level architecture.

**Comment by rprouse** [comment]
I am closing old uncategorized issues that have not had comments or made progress. If anyone comes back with a compelling argument for these issues, we can reopen.
