### ISSUE TITLE
When calling process.start, on occasions will stop the tests.

### ISSUE THREAD

**Issue by sbhanderi** [nunit/nunit#3092]
Hi 
I am using
nunit.framework 3.11.0.0
NUnit Console Runner 3.9.0

Please not I am using nunit as a system test tool.
When I have a call:
this.lyncGuiProcess = Process.Start("lync.exe");

Within  either tests or test fixture setup, on occasions it locks there. Further prints are not seen.
Is this the correct way to start another external executable ?

ps
I am running the tests within Jenkins slave via command line nunit console runner.

**Comment by mikkelbu** [comment]
Hi @sbhanderi 
Given the information I don't think we can help you much. I think `Process.Start` is a fine method to start another executable, but I don't think one should do this in tests.

If the process is stuck then you need to figure out why it is stuck. To this end you can use the tools from https://docs.microsoft.com/en-us/sysinternals/ or e.g. take a dump of lync.exe when it is stuck, but it will require some knowledge about debugging.

When it hangs can you then manually start lync.exe on the same machine?

**Comment by sbhanderi** [comment]
I will try to run manually once process has got stuck.

**Comment by sbhanderi** [comment]
Hi 
Confused a bit.
When running tests, if I call
this.lyncGuiProcess = Process.Start("lync.exe");

Even if lync.exe crashes out, it should not stop nunit tests from running the next line.

As a further test,
I wrapped this process.start within a new thread.
so
        public static void StartWithinNewThread()
               .......
                var theThread = new Thread(() => LyncUi.StartNewProcess("lync.exe"));
                theThread.Start();
                ...............

and
          public static void StartNewProcess(string applicationName)
                .....
                LyncUi.lyncGuiProcess = Process.Start(applicationName);
                ......


So if lync.exe does not start, crashes, stops, burns etc, it should not stop nunit tests from running.

2 out of 20 times I see that Process.Start had been calls, but nunit console trace stops. So I pursume nunit thread has been blocked.
I cannot see how this can happen.
I did not see this happen on much old versions of nunit.

**Comment by sbhanderi** [comment]
ps the other thing to note is tcp connections are made within this app, so I don't know if there is some associations with this.

**Comment by mikkelbu** [comment]
@sbhanderi Try the following:
* Run the console with the option `--inprocess` and `--trace=Verbose` and see if it changes anything or if there is anything of interest in the tracefiles that it generates.
* E.g. `--labels=All` to see where the console stops

When/if the program stops then try to create a memory dump and inspect it, or perhaps attach a debugger to the process to see where it is stuck.

**Comment by sbhanderi** [comment]
The command line I am using to run the tests is as follows ( via Jenkins ), Note it has ncover wrapper, but I did check by removing ncover too and it did not make a difference:
"%cover%" -target:"%nunit3%" -targetargs:"--x86 --labels=All --timeout=300000 --trace=Verbose --agents=1 Genesyslab.Lync.Test.dll --testlist=%testlist% --result=%WORKSPACE%\\nunit-result-%testGroup%.xml;format=nunit3" -filter:"+[Genesyslab*]* -[Genesyslab.Lync.Test]*" -coverbytest:*.dll -targetdir:%testRoot%\\IWS\\ -register:Path32 -hideskipped:Filter -output:%WORKSPACE%\\%testGroup%-Coverage.xml

So what was missing was the option "--inprocess".
I will add this and try again.
If you think other options are missing or incorrect, then let me know - thanks.

**Comment by sbhanderi** [comment]
"--inprocess" and "--x86" cannot work together. Don't really know why. I will remove "--x86".
I thought that was only to force the tests to run in 32 bit mode.

**Comment by CharliePoole** [comment]
Since the console process is not running in 32-bit mode, telling NUnit to (a) run in process and (b) run in 32-bit mode is contradictory.

Note that we are not saying it's correct or better to run in process, merely that you might see a more useful error message if you try it once. The option --process=Single is synonymous with --inprocess.

So, that debugging option isn't really open to you, unfortunately.

**Comment by sbhanderi** [comment]
Not quite sure what to do now, as this problem occurs infrequently. 2 out 20 times.

**Comment by mikkelbu** [comment]
@sbhanderi And the trace files did not contain anything of interest. The files should follow the naming convention `InternalTrace.YYYY.Genesyslab.Lync.Test.dll.log` and `InternalTrace.UUUU.log` where `YYYY` and `UUUU` are four digits.

**Comment by sbhanderi** [comment]
@mikkelbu I am still investigating. Thanks for the information about the log files.

**Comment by sbhanderi** [comment]
Hi all and @mikkelbu 

I have attached the output logs of the tests run, but does not contain anything I can see why the tests were stuck.
The last bit of the console output trace was as follows:
10:20:52 [2856-9]:[10:20:52.696]:Sleep:1000
10:20:53 StartInteractionWorkspace - 01
10:20:53 [2856-9]:[10:20:53.697]:CheckOrLaunchWorkspaceWithAgent-Launching:TestAgent.
10:20:53 fileName:C:\MSLync\IWS\InteractionWorkspace.exe.
10:20:53 arguments:-url tcp://localhost:4042/WDE -u TestAgent -place 182_01_u4.
10:20:53 
10:20:53 [2856-9]:[10:20:53.699]:- ShowWdeAndLyncProcesses - 
10:20:53 [2856-9]:[10:20:53.699]:CheckOrLaunchWorkspaceWithAgent-ShowOtherProcesses:- ShowWdeAndLyncProcesses - 
Then stuck.
The line it tries to run is process.start("some application"), then never comes out from that call. 

[InternalTrace.2856.Genesyslab.Lync.Test.dll.log](https://github.com/nunit/nunit/files/2629665/InternalTrace.2856.Genesyslab.Lync.Test.dll.log)
[InternalTrace.5716.log](https://github.com/nunit/nunit/files/2629666/InternalTrace.5716.log)
[nunit-agent_2856.log](https://github.com/nunit/nunit/files/2629667/nunit-agent_2856.log)
