### ISSUE TITLE
Move our tests from netcoreapp2.0 to netcoreapp2.1

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#3099]
.NET Core 2.0 is no longer supported as of October 1st. Supported versions remain:

- .NET Core 1.0 and 1.1 (Until June 27, 2019)
- .NET Core 2.1 (Until August 21, 2021 at the earliest)

https://www.microsoft.com/net/platform/support-policy/dotnet-core

This does not mean that NUnit will not support folks who use NUnit with .NET Core 2.0. Our .NET Standard 2.0 or .NET Standard 1.4 builds run fine on all versions of .NET Core since 1.0. This only means that our own tests should probably be targeting what everyone else is targeting (netcoreapp2.1).

**Comment by mikkelbu** [comment]
@jnm2 Should we also change the target in `nunitlite-runner.csproj`?

**Comment by jnm2** [comment]
@mikkelbu That doesn't affect the bits we ship, right? If not, then I'd say yes just like all our other tests.

**Comment by mikkelbu** [comment]
@jnm2 It seems that this was closed in #3383, so I'm closing this issue. Please reopen it, if I'm wrong.

**Comment by jnm2** [comment]
Thanks!
