### ISSUE TITLE
[2.6.3] Target framework not specified on the AppDomain when running against .Net 4.5

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#310]
This issue was originally written against the nunit-console project:

It seems that the target framework is not specified on the AppDomain when running tests against *.Net 4.5*. This causes some code to revert back to the old *4.0* behaviour.

For example
 `Uri.IsWellFormedUriString("http://www.example.com/düsseldorf", UriKind.RelativeOrAbsolute)`
returns 
 - `False` in *4.0* 
 - `True` in *4.5* with TargetFramework *4.5*
 - `False` in *4.5* with no TargetFramework specified

The only way I found to work around this issue is to compile the *agent* using the *4.5* framework.

**Comment by CharliePoole** [comment]
Comments from the original issue:

@CharliePoole - 

Please provide info on how to reproduce this issue. In particular...

How is the test code compiled?
What command line is used to run tests?

@jmartinpeterson -

There's an issue in the Jetbrains issue tracker that seems just as relevant for NUnit: http://youtrack.jetbrains.com/issue/RSRP-412080 

The linked MSDN blog explains some of the quirking that is done when the .NET 4.5 runtime doesn't find TargetFramework set to 4.5. It basically means that code run by NUnit can behave differently than in a 4.5 targeted product, which kind of defeats the purpose of running the tests.

@serialseb -

Real problem, hit it too.

Fix is to have a specific 4.5 compiled agent for target 4.5 (as the current nunit mode is not 4.5 but quirks mode 4.5). Alternatively (see reference source), one can set the TargetFrameworkName in the default appdomain, and if that fails one can set the attribute on the entry assembly using a 4.5 version.

**Comment by CharliePoole** [comment]
@rprouse Should this issue be closed now as a result of #244?

**Comment by rprouse** [comment]
Yes, I am going to close as won't fix in 2.6 and fixed in a later release.
