### ISSUE TITLE
Declare class in Program.cs provided with NUnitLite Nuget package static

### ISSUE THREAD

**Issue by ahoisl** [nunit/nunit#3107]
The default Program class provided with the NUnitLite Nuget package 3.11.0 is not static.
This causes warnings/errors on some static code analysis like SonarQube (classes only containing static members should be declared static).

As the file is always replaced/recreated when installing the Nuget package, you cannot simple fix the problem.

BTW, the documentation in the Wiki is correctly creating a static class:
https://github.com/nunit/docs/wiki/NUnitLite-Runner

**Comment by CharliePoole** [comment]
I agree with the request but I'm wondering about "the file is always replaced/recreated." Can't we avoid that in some way? If you have edited the file yourself, you don't want to replace it.

**Comment by ahoisl** [comment]
True, but this is part of a separate issue (#1428) which is not so pressing for me, actually.

**Comment by CharliePoole** [comment]
Fixing just what you need is definitely the way to get things done!
