### ISSUE TITLE
nunit-console.exe throws exception

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#311]
This was originally an nunit-console issue...

nunit-console.exe throws the following error while i tried to execute from Mapped Network Drive

Unhandled Exception: System.TypeInitializationException: The type initializer for 'NUnit.ConsoleRunner.Runner' threw an exception. ---> System.Security.SecurityException: That assembly does not allow partially trusted callers. at NUnit.ConsoleRunner.Runner..cctor() The action that failed was: LinkDemand The assembly or AppDomain that failed was: nunit-console-runner, Version=2.6.3.13283, Culture=neutral, PublicKeyToken=96d09a1eb7f44a77 The method that caused the failure was: NUnit.Core.Logger GetLogger(System.Type) The Zone of the assembly that failed was: Internet The Url of the assembly that failed was: file:///Z:/jenkinsworkspace/workspace/FlashUpload/tools/NUnit/lib/nunit-console-runner.DLL --- End of inner exception stack trace --- at NUnit.ConsoleRunner.Runner.Main(String[] args) at NUnit.ConsoleRunner.Class1.Main(String[] args)

i tried the following methods to fix.

added loadFromRemoteSources enabled="true" in nunit-console.exe.config
But the change did not solve the problem.

**Comment by CharliePoole** [comment]
This has been a long-standing situation with NUnit. The only way to run NUnit from a mapped drive is to specifically enable full trust on your machine.

**Comment by ChrisMaddock** [comment]
I believe this just came up here: https://stackoverflow.com/questions/48402851/nunit-console-incorrect-parameter

Moving this issue to the console repo. I'm not sure if it's something we will deal with any time soon - but we should keep it tracked.

**Comment by ChrisMaddock** [comment]
Issue moved to [nunit/nunit-console #358](https://github.com/nunit/nunit-console/issues/358) via [**ZenHub**](https://www.zenhub.com/)
