### ISSUE TITLE
Prevent single TestCase from running

### ISSUE THREAD

**Issue by naukacsp** [nunit/nunit#3110]
Hi, I have a bit of a problem. I have a test with a few test cases and I would like to turn off(not Ignore) one test case (simple way like below). Turn off completely = to not run it (don’t get ANY result). It should not be displayed in test results at all.
Example:

```csharp
public class Class1
{
    [Test]
    public void AnotherTest()
    {
        string a = "a";
        Assert.AreSame("a", a);
    }
 
    [TestCase("1")]
    [TestCase("2")]
    [TestCase("3"), Ignore("bb")]
    public void SimpleTest(string passedArgument)
    {
        Assert.AreEqual("1", passedArgument);
    }
}
```
 
On the above picture, I would like to turn off TestCase(”3”), but still running other test cases and other tests in class.
The hard part is to run other test cases, but this. Ignore is not the solution I am looking for (IgnoreAttribute that is) as it turns off the whole test, but not a single test case.

**Comment by mikkelbu** [comment]
Hi @naukacsp 
Instead of writing `[TestCase("3"), Ignore("bb")]` you should write `[TestCase("3", Ignore = "Ignore me")]`.

Writing `[TestCase("3"), Ignore("bb")]` is equivalent to writing
```csharp
[TestCase("3")]
[Ignore("bb")]
```

**Comment by naukacsp** [comment]
I don't want to run the particular test case at all. That is why I specified that I am not looking for Ignore. ;)

**Comment by CharliePoole** [comment]
When you use ignore, the test is not run. It's reported as ignored, with the reason you gave. Are you saying you want to silently ignore the test?

One way to do that is to just comment out the attribute. Another is to mark it explicit. NUnit is intentionally designed so it's hard to ignore a test without getting a report on it.

**Comment by naukacsp** [comment]
I don't want to get results ex. Build: 7 succeeded, 0 failed, 0 up-to-date, **2 skipped**
I would like to get Build: 7 succeeded, 0 failed, 0 up-to-date, 0 skipped

So I guess yes, I would love to get silent ignore.

Right now the solution with the attribute that is working, but for a whole test(I need for test case).

public class IgnoredTestsAttribute : CategoryAttribute, ITestAction
    {
        private readonly string _reason;

        public IgnoredTestsAttribute(string reason)
        {
            _reason = reason;
            Targets = ActionTargets.Default;
        }

        public ActionTargets Targets { get; }

        public void AfterTest(ITest test)
        {
            //test is ignored due to _reason
        }

        public void BeforeTest(ITest test)
        {
            Log.Info(this, $"Ignoring {test.Name} due to {_reason}.");

            Assert.Ignore();
        }
    }

**Comment by CharliePoole** [comment]
Historically, we have always treated tests that are skipped or ignored silently as a bug and fixed it so they are reported. The rationale for that is that tests are supposed to be run. This can be very important when tests are subject to FDA review, as an example.

In order to get a test neither run nor reported you have to select tests to run and not include that test.
For example if you gave test3 the category XYZ and ran the console using `--where cat != XYZ` you would then see the result you are after.

THe logic of the precding is that you __told__ NUnit to run only certain tests. That fact is recorded in the test result file so no test has been suppressed silently.

**Comment by naukacsp** [comment]
@CharliePoole I need it as a default behavior(both in IDE and running from command line). Not configured each time.
That is why I wanted to write a custom test case attribute that is making it behave the way I wanted. For test it was achievable, for test case I have a hard time figuring it out. I would love the same solution as I presented for test above but working for a single test case.
To the solution above it is done this way:
``` dotnet test --filter "TestCategory!=IgnoredTests" ```

**Comment by ChrisMaddock** [comment]
I agree with @CharliePoole on this one - NUnit is designed to ensure all tests are reported accurately.

Hiding the real state is not something I would want to add to the core framework. If it's achievable through custom extensibility, that's where it should live, in my mind.

**Comment by rprouse** [comment]
I am going to close this as an answered question. If you want to continue the discussion, feel free to continue to post here.
