### ISSUE TITLE
TestContext.Parameters not filled

### ISSUE THREAD

**Issue by kaanmijo** [nunit/nunit#3111]
Hi,

I'm trying to use a .runsettings file with my nunit tests. However, every time I try to run the tests the parameters don't seem to get filled. Is this a bug or am I doing something wrong here? I've already checked out [https://github.com/nunit/nunit3-vs-adapter/issues/251](this issue), but to no avail. I'm using **VS 2017**, **nunit 3.11.0** and **SpecFlow 2.4.0** .

settings.runsettings:
```
<?xml version="1.0" encoding="utf-8" ?>
<RunSettings>
  <!-- Parameters used by tests at runtime -->
  <TestRunParameters>
    <Parameter name ="webAppUrl" value="value1" />
  </TestRunParameters>
</RunSettings>
```

My test:
```
[Given(@"I am on the page with authorizations so i can add one")]
public static void GivenIAmOnThePageWithAuthorizationsSoICanAddOne () {
     string url= TestContext.Parameters["webAppUrl"];
     driver = LoginHelper.GetDriverLoginAndGoToPage(url);
}
```

![image](https://user-images.githubusercontent.com/4430874/49802627-afe30500-fd4d-11e8-87c8-95da5c5c220b.png)

**Comment by CharliePoole** [comment]
You haven't said, but you seem to be using a BDD framework which either generates NUnit code or layers on top of NUnit. You should add info about what you are using. If the actual NUnit test code is generated by the framework you are using, it would heop if you included the generated code.

It would also be helpful to know how you are running your tests, i.e. with what test runner software.

**Comment by kaanmijo** [comment]
> You haven't said, but you seem to be using a BDD framework which either generates NUnit code or layers on top of NUnit. You should add info about what you are using. If the actual NUnit test code is generated by the framework you are using, it would heop if you included the generated code.
> 
> It would also be helpful to know how you are running your tests, i.e. with what test runner software.

I'm using SpecFlow 2.4.0 for BDD. I'm running the tests using the build-in Test Explorer in Visual Studio 2017. I've uploaded my code here: https://github.com/kaanmijo/TestProject. I'm not really sure what else I should add, since this is my first time trying NUnit in combination with SpecFlow.

**Comment by CharliePoole** [comment]
The uploaded project doesn't have any reference to `TestContext.Parameters`

**Comment by kaanmijo** [comment]
It does for me (?) https://github.com/kaanmijo/TestProject/blob/master/UnitTestProject1/ContactPageSteps.cs. Line 15

**Comment by CharliePoole** [comment]
Sorry, I missed that. 

Maybe (well actually definitely) I don't understand how SpecFlow works. in line 15, you assign `TestContext.Parameters["webAppUrl"]` to the temporary field `context`. You don't do anything with that field, so it's hard to see how it would have any effect on the test.

**Comment by kaanmijo** [comment]
In line 15, I indeed assign it to the field `context`. On line 17, I now use a static string:
`driver.Navigate().GoToUrl("http://www.testspecialist.nl/contact");`

Whenever I put the temporary field `context` on that line this:
`driver.Navigate().GoToUrl(context);`

The test fails because the value of context is `null`. This makes sense, because as you can see in the screenshot I posted in the original post, the parameters of the `TestContext` are completely empty.

**Comment by rprouse** [comment]
I am closing old uncategorized issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
