### ISSUE TITLE
Allow to ignore exceptions in DelayedConstraint

### ISSUE THREAD

**Issue by Dreamescaper** [nunit/nunit#3114]
Sometimes for integration tests I need to poll in assertions, where DelayedConstraint is handy, but I also need it not to fail on exception during that polling (e.g. some resource is created with delay, and API client throws NotFoundException if I try to access it until it is created).

I suggest to add ability to ignore occurring exceptions during polling.

Suggested changes - add two methods to DelayedConstraint:
`public DelayedConstraint IgnoreExceptions()` - ignore all exceptions
`public DelayedConstraint IgnoreExceptions(params Type[] exceptionType)` - ignore only exceptions of specified types

**Comment by ChrisMaddock** [comment]
Maybe I'm wrong..I thought this was current behaviour? 

Could you throw together a single tests I can run to demonstrate the problem?

**Comment by CharliePoole** [comment]
I'm not sure about current behavior, but the original behavior of `DelayedConstraint` was to ignore __failures__ only. That would mean an `AssertionException` but not a `NotFoundException`.

**Comment by Dreamescaper** [comment]
I see that try-catch is present in DelayedConstraint, so I might be wrong. Will re-check a bit later

**Comment by Dreamescaper** [comment]
Okay, so there _is_ try-catch in DelayedConstraint, but it does not handle delegate invoking itself:
https://github.com/nunit/nunit/blob/cefc0c3a86c065daa4130aa255b1384db51b2b08/src/NUnitFramework/framework/Constraints/DelayedConstraint.cs#L290

So any exception in delegate will make it fail immediately

**Comment by rprouse** [comment]
No progress since 2019, closing.
