### ISSUE TITLE
TestCaseData array arguments complex

### ISSUE THREAD

**Issue by dodoni** [nunit/nunit#3115]
Hi, 
hoping this is the right place for my problem:
 
I have the following situation concerning unit tests with some complex numbers which was working under NUnit 2.x but does not work under NUnit 3.0 any more:

```csharp
[TestCaseSource(nameof(TestData)]
public void SimpleTest(int a, Complex[] b) {
 // do some test, i.e. Assert.That(,....
}
```

```csharp
public static IEnumerable TestData {
   get { yield return new TestCaseData(2,  new Complex[]{ 1.0, 2.0 + Complex.ImaginaryOne});
...} 
}
```

The test will not be shown correctly in the test explorer (VS2017, NUnit3TestAdapter 3.11.2, NUnit 3.11), i.e. it seems that the test cases are not recognized. The problem is the array argument. The only solution I found was to use object[] arguments in the signature of the test function and change the 'TestData' property in the following way:

```csharp
[TestCaseSource(nameof(TestData)]
public void SimpleTest(int a, object[] bAsObject) {
 Complex[] b = bAsObject[0] as Complex[];
 // do some test, i.e. Assert.That(,....
}
```

```csharp
public static IEnumerable TestData {
   get { yield return new TestCaseData(2, new[] {new Complex[]{ 1.0, 2.0 + Complex.ImaginaryOne})};
...} 
}
```

With NUnit 2.x it works. Is there any reason for this behaviour in NUnit 3? This workaround is quite uncomfortable in my eyes.

Thanks.
Best wishes
Markus Wendt

**Comment by mikkelbu** [comment]
Hi @dodoni 
This sounds somewhat related to #1792 (and I think that there are other issues of a similar character). Can you run the tests using the console runner and see if it provides some feedback we can use to determine the problem. 
Perhaps it is also possible to get this feedback from VS by examine the test output in the Output window.

Ps. I've added some [fences](https://help.github.com/articles/creating-and-highlighting-code-blocks/) in your message to enable highlighting of the code.

**Comment by CharliePoole** [comment]
What happens if you make the second test parameter a `params` array and specify the complex values as separate args?

**Comment by dodoni** [comment]
> What happens if you make the second test parameter a `params` array and specify the complex values as separate args?

Something like this?

```C#
 [TestCaseSource(nameof(TestData))]
        public void SimpleTest(int a, params Complex[] b)
        {
            // do some test   
        }

        public static System.Collections.IEnumerable TestData
        {
            get
            {
                yield return new TestCaseData(2, new Complex(1.0, 0), 2.0 + Complex.ImaginaryOne);
            }
        }
```
Good idea, but I'v got the same problem as before.

**Comment by dodoni** [comment]
> Hi @dodoni
> This sounds somewhat related to #1792 (and I think that there are other issues of a similar character). 

Yes, it looks somehow similar, but in my case (i) the test case will not be detected at all (ii) I use TestCaseData instances instead of a  `IEnumerable<string>`  etc.



>Can you run the tests using the console runner and see if it provides some feedback we can use to determine the problem.
> Perhaps it is also possible to get this feedback from VS by examine the test output in the Output window.

Well I have not install the console runner yet. The following output is taken from VS output windows, but it does not contain deeper information:


_[14.12.2018 10:50:13 Informational] ------ Run test started ------
[14.12.2018 10:50:14 Informational] NUnit Adapter 3.11.2.0: Test execution started
[14.12.2018 10:50:14 Informational] Running all tests in C:\Users\gimmick\Source\wc\Dodoni.net_Project\Dodoni.net\BasicMathLibrary.Tests.Unit\bin\Debug\netcoreapp2.1\Dodoni.BasicMathLibrary.Tests.Unit.dll
[14.12.2018 10:50:15 Informational]    NUnit3TestExecutor converted 768 of 768 NUnit test cases
[14.12.2018 10:50:15 Informational]    Skipping assembly - no matching test cases found
[14.12.2018 10:50:15 Informational] NUnit Adapter 3.11.2.0: Test execution complete
[14.12.2018 10:50:15 Warning] Kein Test entspricht dem angegebenen Testfallfilter "FullyQualifiedName=Dodoni.MathLibrary.Miscellaneous.EigenvaluePolynomialRootFinderTests.SimpleTest" in "C:\Users\gimmick\Source\wc\Dodoni.net_Project\Dodoni.net\BasicMathLibrary.Tests.Unit\bin\Debug\netcoreapp2.1\Dodoni.BasicMathLibrary.Tests.Unit.dll".
[14.12.2018 10:50:15 Informational] ========== Run test finished: 0 run (0:00:01,6831988) ==========_



> Ps. I've added some [fences](https://help.github.com/articles/creating-and-highlighting-code-blocks/) in your message to enable highlighting of the code.

Thanks! Now it looks quite nice.

**Comment by mikkelbu** [comment]
This [Tips-And-Tricks page](https://github.com/nunit/docs/wiki/Tips-And-Tricks) contains some information about how to get more output from the adapter. 

Perhaps turning up the verbosity to 5 and setting DumpXmlTestDiscovery to true in a .runsettings would give some more information (this [post](https://github.com/nunit/nunit3-vs-adapter/issues/251#issuecomment-315453322) has some info about how to refer to the .runsettings file from VS).

**Comment by CharliePoole** [comment]
@dodoni My suspicion is that your tests __are__ being detected but are being merged together with other test cases of the same name having the same argument pattern. Look for existing tests that show more than one result when the test is selected.

For example, I would expect to see all tests of the same method with `(2, Complex[])` as args to be conflated in the Test Explorer.

**Comment by dodoni** [comment]
> @dodoni My suspicion is that your tests **are** being detected but are being merged together with other test cases of the same name having the same argument pattern. Look for existing tests that show more than one result when the test is selected.
> 
> For example, I would expect to see all tests of the same method with `(2, Complex[])` as args to be conflated in the Test Explorer.

Well, in the test explorer the special test is listed twice (not sure why, I expected one entry only - there is no other unit test with the same name). Therefore the test is somehow detected, but I did not found it merged together with other test cases.

![image](https://user-images.githubusercontent.com/25553148/50033327-5fdb9b00-fff8-11e8-93f8-ec8f24cb9642.png)

**Comment by CharliePoole** [comment]
@dodoni My comment was in reply to your telling us that the test is not detected at all. It seems that it is.

**Comment by aolszowka** [comment]
I think we might be encountering the same issue; I have added some discussion here https://github.com/nunit/nunit3-vs-adapter/issues/585
