### ISSUE TITLE
TestCaseAttribute,TestName

### ISSUE THREAD

**Issue by dodoni** [nunit/nunit#3117]
The following tests are not working under VS2017 (nunit 3.11.0, NUnitAdapter 3.11.2), 

```C#
[TestCase(1,TestName="{c}.{m} Flag 1, i.e. H=(h11 & 1 \\ -1 & h22")]
[TestCase(-2, TestName="{c}.{m} Flag -2, i.e. H=(1 & 0 \\ 0 & 1)")]
public void drotm_TestCaseData_ResultOfManuallyBechmark(int flag) 
{//...
}
```

[14.12.2018 13:54:43 Informational] ------ Run test started ------
[14.12.2018 13:54:44 Informational] NUnit Adapter 3.11.2.0: Test execution started
[14.12.2018 13:54:44 Error] Ausnahme beim Aufrufen von Executor "executor://nunit3testexecutor/": Ungültiges Format für TestCaseFilter Fehler: Ungültige Bedingung "FullyQualifiedName=Dodoni.MathLibrary.Basics.LowLevel.BuildIn.BuildInLevel1BLASTests.TEST Flag 1, i.e. H=".. Geben Sie das richtige Format an, und versuchen Sie es erneut. Beachten Sie, dass das falsche Format dazu führen kann, dass kein Test ausgeführt wird.
[14.12.2018 13:54:44 Informational] ========== Run test finished: 0 run (0:00:01,0146485) ==========

Well the dot (.) and equal sign (=) seems to be the problem, i.e. if I remove the dot between {c} and {m} as well as between i and e (of i.e.) and =, the tests are running. The templates {c} and {m} are not recognized, i.e. the test are shown in the test explorer as "{c}{m}Flag 1, ie H(h11 & 1 \\ -1 & h22)".

First at all https://github.com/nunit/docs/wiki/Template-Based-Test-Naming does not contain information about such restrictions in the naming. Moreover the templates {c} and {m} are not recognized. As a workaround I will give a meaningful name directly in the attribute (without '.' inside).

**Comment by mikkelbu** [comment]
I think that this is an issue in the Adapter (or in vstest) as if I run tests using the console I get
```xml
...
    <test-suite type="TestSuite" id="0-1005" name="TestNames" fullname="TestNames" runstate="Runnable" testcasecount="2" result="Passed" start-time="2018-12-14 13:50:15Z" end-time="2018-12-14 13:50:15Z" duration="0.043170" total="2" passed="2" failed="0" inconclusive="0" skipped="0" asserts="2">
      <test-suite type="TestFixture" id="0-1000" name="MyClass" fullname="TestNames.MyClass" classname="TestNames.MyClass" runstate="Runnable" testcasecount="2" result="Passed" start-time="2018-12-14 13:50:15Z" end-time="2018-12-14 13:50:15Z" duration="0.037612" total="2" passed="2" failed="0" inconclusive="0" skipped="0" asserts="2">
        <test-suite type="ParameterizedMethod" id="0-1003" name="drotm_TestCaseData_ResultOfManuallyBechmark" fullname="TestNames.MyClass.drotm_TestCaseData_ResultOfManuallyBechmark" classname="TestNames.MyClass" runstate="Runnable" testcasecount="2" result="Passed" start-time="2018-12-14 13:50:15Z" end-time="2018-12-14 13:50:15Z" duration="0.032171" total="2" passed="2" failed="0" inconclusive="0" skipped="0" asserts="2">
          <test-case id="0-1001" name="MyClass.drotm_TestCaseData_ResultOfManuallyBechmark Flag 1, i.e. H=(h11 &amp; 1 \ -1 &amp; h22" fullname="TestNames.MyClass.MyClass.drotm_TestCaseData_ResultOfManuallyBechmark Flag 1, i.e. H=(h11 &amp; 1 \ -1 &amp; h22" methodname="drotm_TestCaseData_ResultOfManuallyBechmark" classname="TestNames.MyClass" runstate="Runnable" seed="233838475" result="Passed" start-time="2018-12-14 13:50:15Z" end-time="2018-12-14 13:50:15Z" duration="0.016471" asserts="1" />
          <test-case id="0-1002" name="MyClass.drotm_TestCaseData_ResultOfManuallyBechmark Flag -2, i.e. H=(1 &amp; 0 \ 0 &amp; 1)" fullname="TestNames.MyClass.MyClass.drotm_TestCaseData_ResultOfManuallyBechmark Flag -2, i.e. H=(1 &amp; 0 \ 0 &amp; 1)" methodname="drotm_TestCaseData_ResultOfManuallyBechmark" classname="TestNames.MyClass" runstate="Runnable" seed="718355746" result="Passed" start-time="2018-12-14 13:50:15Z" end-time="2018-12-14 13:50:15Z" duration="0.000063" asserts="1" />
        </test-suite>
      </test-suite>
    </test-suite>
....
```
But you are right that something like this should be mentioned on the wiki

**Comment by CharliePoole** [comment]
Problem is that the documentation page is for __NUnit__ (i.e. the framework) and describes correctly what NUnit does. Naturally, it doesn't describe what the adapter does __with__ those tests once they are run. Not sure what would be the best way to organize info about things that do not work in the adapter.

We do know that VS does not allow the same freedom in naming tests that NUnit allows.

@OsirisTerje What do you think? Where should this be documented?

**Comment by OsirisTerje** [comment]
I think 1) a seperate page for the adapter documenting this 2) A link in the main nunit page to this new page , where it warns about the differences and link to 1.

**Comment by CharliePoole** [comment]
That's namespace sense. The warning should also state that some third-party runners may not be able to handle arbitrary names.

**Comment by OsirisTerje** [comment]
Works now in adapter 4.5.0 and nunit 4.0.0-beta.1.  

See test Issue3117 in repro https://github.com/nunit/nunit.issues/tree/main/Issue4549

**Comment by stevenaw** [comment]
I can confirm that this works in the latest stable version of the framework, version 4.0.1
