### ISSUE TITLE
What is the official stance on the NUnit.Framework.Internal namespace with respect to backwards compatibility?

### ISSUE THREAD

**Issue by madelson** [nunit/nunit#3118]
Hello,

I'm working on a company-internal library of testing utility methods, helpers, and infrastructure that is all built on top of NUnit 3 (3.11 currently).

I'm finding myself wanting to use a class in the `NUnit.Framework.Internal` namespace, but the name made me hesitate. In particular, what I want is the ability to add a test property from various points in code, using:
```
TestExecutionContext.CurrentContext.CurrentTest.Properties.Add("NAME", "VALUE");
``` 
There are a few smaller cases of this as well.

Because this code is going into an internal NuGet package that will be installed into ~100 different projects, I want to be sensitive to backwards compatibility. For example, if someone were to upgrade to NUnit 3.12 (when it exists), is there any chance that this API would be changed/removed?

I've looked at several issues/threads related to this (e. g. #2156) and I'm not sure I know what the project's official stance is.

Thanks!

**Comment by ChrisMaddock** [comment]
Hi @madelson - good question.

For historic reasons, there's lots of code within the `Internal` namespace which is `public` but not intended as a supported API - if we were starting from scratch today, those classes would be internal. There is however other parts of  `Internal` which are meant to be part of the public API, and should maybe be in a different namespace. You can see some of the issues them team are having with this ourselves e.g. at https://github.com/nunit/nunit/issues/1426 and https://github.com/nunit/nunit/issues/2413.

Fortunately, your specific issue has come up before. Adding a property to a test _during_ the test was never intended to be exposed functionality, and was actually 'removed' in a sense in https://github.com/nunit/nunit/pull/2692. Advice from https://github.com/nunit/nunit/issues/2793#issuecomment-391135774 would be to implement your own container, instead.

Hope that helps, sorry it's not a simple clear-cut answer. It's something we're hoping to improve over time.

**Comment by madelson** [comment]
@ChrisMaddock thanks for answering! 

First, one clarifying question: Would the NUnit maintainers remove any of these APIs without a major version bump on the NuGet package?

It sounds like there is still debate about what to do with the APIs in that namespace, but hopefully there is at least an answer on whether breaking changes there would be permitted within an NUnit 3.x version.

Second, I just wanted to call out our use-case for adding properties mid-test. Basically, we are using properties as a way for tests to attach additional metadata as they run which then gets picked up and logged with the test result. As an example, we have integration tests that connect to databases at runtime; these tests want to specify the database server and name that they used so that this is visible in our test reports.

**Comment by CharliePoole** [comment]
I'll repeat some earlier comments to suggest that such properties might better be considered properties of the result rather than the test. In theory, they might vary at each execution. This could be implemented as a new feature, without worrying about backward compatibility.

**Comment by ChrisMaddock** [comment]
> First, one clarifying question: Would the NUnit maintainers remove any of these APIs without a major version bump on the NuGet package?

Yes, potentially. NUnit doesn't currently strictly follow SemVer.

> I'll repeat some earlier comments to suggest that such properties might better be considered properties of the result rather than the test. In theory, they might vary at each execution. This could be implemented as a new feature, without worrying about backward compatibility.

This sounds sensible to me. @madelson - if this is a feature you'd be interested in contributing, I suggest you make start a new issue along those lines. I would propose what this would look like in terms of API and xml first, and get that agreed among the team. 🙂

**Comment by madelson** [comment]
Thanks @CharliePoole / @ChrisMaddock  !

I've filed an issue for the "result properties" idea here: https://github.com/nunit/nunit/issues/3136

**One other question regarding properties**: another approach we'd considered was to add properties using an `ITestAction` attribute and adding properties via `ITest.Properties.Add`. Presumably this is equally non-kosher?

> Yes, potentially. NUnit doesn't currently strictly follow SemVer.

Is there any interest in formally adopting SemVer? Following SemVer is super helpful to consumers like myself. :-)
