### ISSUE TITLE
Parallel execution using Selenium Grid.

### ISSUE THREAD

**Issue by anfasansary** [nunit/nunit#3120]
How can run my test in different browsers in different machines using specflow, nunit and selenium grid.

My environment is like,
Node1 and Node2 are registered using selenium grid. Now i want to execute my test in parallel:

1. using Chrome browser in node1
2. using Firefox browser in node2

Is it possible and if so how ?. Please help me to find a solution. 
Hope you understand the test environment.

**Comment by CharliePoole** [comment]
NUnit can run assemblies or fixtures in parallel on __one__ machine. NUnit does not have the capability built in to kick off tests on a separate machine. Therefore, if you want to run tests on two separate machines, you have to arrange for the parallel execution outside of NUnit.

Maybe Selenium does this... it's outside of my area of expertise.

You could certainly create a script that fired off NUnit on two different machines, passing in a command-line parameter to indicate which browsr should be used. Your tests would have to be written to use the command-line parameter to select the correct browser.

**Comment by CharliePoole** [comment]
Tell us the shape of your tests...
 * All in one assembly, or separated?
 * Separate fixtures for Chrome and Firefox or one fixture with two arguments?
 * How do you use Parallelizable attribute

Also, how do you execute your tests... console runner, Test explorer, other?

**Comment by CharliePoole** [comment]
You still have not said how you actually run your tests. This is crucial to reproducing any problem.

For example, if you use the console runner... provide the exact command-line, including options.

**Comment by anfasansary** [comment]
Sorry. I am using test explorer now for running the tests.

![image](https://user-images.githubusercontent.com/42206887/50335773-5be8d500-0532-11e9-8315-68187a367026.png)

**Comment by CharliePoole** [comment]
Good to know. One of the things we are trying to figure out is if this should be reported as an adapter problem rather than an NUnit problem. I'll look through the code you attached.

**Comment by anfasansary** [comment]
Thanks Charlie. Looking forward to hearing.

**Comment by anfasansary** [comment]
> Good to know. One of the things we are trying to figure out is if this should be reported as an adapter problem rather than an NUnit problem. I'll look through the code you attached.

@CharliePoole Happy New Year...
Hope you gone through the code. Please let me know if any changes needed for parallel execution.

**Comment by Alex2357** [comment]
The answer here https://github.com/nunit/nunit/issues/3197#issuecomment-475951179 may help you as I have had similar problem with Grid
