### ISSUE TITLE
Parallelizable(ParallelScope.) doesn't work on a SetUpFixture

### ISSUE THREAD

**Issue by AndreyChizhikov** [nunit/nunit#3126]
Hello.
Please, advice.
I want to run  TestFirstGroup and  TestSecondGroup in parallel but they are executed 
consistently.

I have next autotests structure:

**Class for Authorization:**
```
namespace TestAutomation
{
  public class Authorization
    {
        [OneTimeSetUp]
        public void CreateUser()
        {
        }

        [OneTimeTearDown]
        public void DeleteUser()
        {
        }
}
```

**First namespace with autotests:**
```
namespace TestAutomation.TestsGUI.TestFirstGroup
{
 [SetUpFixture, Parallelizable]
    public class TestGroupOneSetupFixture
    {
        [OneTimeSetUp]
        public void RunBeforeAnyTests()
        {
        }
        [OneTimeTearDown]
        public void RunAfterAnyTests()
        {
        }
    }

[TestFixture]
 BaseTestFirstGroup : Authorization
{
   [OneTimeSetUp]
        public void RunBeforeTests()
        {
        }

        [OneTimeTearDown]
        public void RunAfterTests()
        {
        }

}

  public class FirstGroupTestFixtureOne :  BaseTestFirstGroup
{
        [Test]
        public void TestOne(){}
        [Test]
        public void TestTwo(){}
}

  public class FirstGroupTestFixtureTwo : BaseTestFirstGroup
{
        [Test]
        public void TestOne(){}
        [Test]
        public void TestTwo(){}
}
}

```
**Second namespace with autotests:**

```
namespace TestAutomation.TestsGUI.TestSecondGroup
{
 [SetUpFixture, Parallelizable]
    public class TestGroupSecondSetupFixture
    {
        [OneTimeSetUp]
        public void RunBeforeAnyTests()
        {
        }
        [OneTimeTearDown]
        public void RunAfterAnyTests()
        {
        }
    }

[TestFixture]
BaseTestSecondGroup : Authorization
{
   [OneTimeSetUp]
        public void RunBeforeTests()
        {
        }

        [OneTimeTearDown]
        public void RunAfterTests()
        {
        }

}

  public class SecondGroupTestFixtureOne : BaseTestSecondGroup
{
        [Test]
        public void TestOne(){}
        [Test]
        public void TestTwo(){}
}

  public class SecondGroupTestFixtureTwo : BaseTestSecondGroup
{
        [Test]
        public void TestOne(){}
        [Test]
        public void TestTwo(){}
}
}

```
 **and other autotests.**

NUnit version: 3.10.1
NUnit.ConsoleRunner version: 3.8.0
NUnit3TestAdapter version :3.10.0

**Comment by CharliePoole** [comment]
Can you please add a description that tells us what you want to work, how you want it to work and what is happening instead?

**Comment by AndreyChizhikov** [comment]
And sorry for the empty issue)

**Comment by CharliePoole** [comment]
What you want is intended to work. :smile:

**Comment by agray** [comment]
Didn't say right at the top?

"I want to run TestFirstGroup and TestSecondGroup in parallel but they are executed
consistently [in sequence]"

**Comment by CharliePoole** [comment]
It does __now__!

**Comment by AndreyChizhikov** [comment]
@CharliePoole @agray  I'm trying using this [solution](https://stackoverflow.com/questions/46343533/nunit-can-i-group-tests-by-a-key-and-run-tests-in-each-group-in-parallel-but) from StackOverflow, but it does not work for me. Autotests are still run in series.
What am I doing wrong? 
Please, advise.

**Comment by CharliePoole** [comment]
That's why I marked it confirm. I'm pretty sure it used to work. One of the other team members will hopefully give it a shot. I can't do it on my phone. :smile:

**Comment by mikkelbu** [comment]
@CharliePoole I don't know much about the parallel feature - and https://github.com/nunit/docs/wiki/Parallelizable-Attribute does not explain much - but will `[Parallelizable]` (meaning `[Parallelizable(ParallelScope.Self]`) also make the individual tests (`TestOne` and `TestTwo`) in run in parallel? I thought that `[Parallelizable(ParallelScope.Self]` meant that the test would run in parallel with other tests at the **same level**.

If `[Parallelizable(ParallelScope.Self]` also affects the "children" then why do we also have `ParallelScope.All`?

**Comment by CharliePoole** [comment]
@mikkelbu No it won't - or shouldn't anyway. Not sure why you ask, however. The issue seems to be that he isn't seeing any parallelism.

Because we don't have the best tests for complex structures of tests like this, I can easily imagine it breaking.

**Comment by agray** [comment]
Tests in the same fixture running in parallel?  This was the reason I created Saucery3 to drive NUnit to behave the same way as JUnit 4. Tests in the same fixture running in parallel when the TestFixtureSetUp is in a subclass of the [Test] definitions.

I have been hoping to see this behaviour realised but have NEVER seen it.

I have been updating with every released version of NUnit abd NUnit Console.

**Comment by agray** [comment]
Can we please remove the confirm label and get this feature implemented?

**Comment by AndreyChizhikov** [comment]
@agray In my case, I have several tests groups which I cannot parallelizable intra-group and I try running tests in parallel on groups level.
I created tests group by using [SetUpFixture] but this solution does not work.

**Comment by CharliePoole** [comment]
@agray This issue is 20 hours old. In that time @AndreyChizhikov created a working example and I marked it confirm so somebody would get to work on it. Give us a break!

Note that without the confirm label, it would revert to being an unexamined issue and we would start all over again.

**Comment by mikkelbu** [comment]
> @mikkelbu No it won't - or shouldn't anyway. Not sure why you ask, however. The issue seems to be that he isn't seeing any parallelism.

The reason I asked was because I read the question as a how to run the two different test groups in parallel. But with only `[Parallelizable]` on the two `SetUpFixtures` then it will only be the setup and the teardown in those classes that is executed in parallel and not the tests (and I found that wish strange, but perhaps I misunderstod the wish?)

If I look at the log for the example above (running the console with `--trace=Debug`), then I get that the setup and the teardown is executed by the parallel worker (
[full log from console - InternalTrace.3932.ParallelTests.dll.log](https://github.com/nunit/nunit/files/2713020/InternalTrace.3932.ParallelTests.dll.log))
```
18:46:44.744 Debug [ 5] WorkShift: Parallel shift assigned worker ParallelWorker#1
18:46:44.744 Debug [ 5] WorkShift: Parallel shift assigned worker ParallelWorker#2
18:46:44.744 Debug [ 5] WorkShift: Parallel shift assigned worker ParallelWorker#3
18:46:44.744 Debug [ 5] WorkShift: Parallel shift assigned worker ParallelWorker#4
...
18:46:44.792 Info  [ 8] TestWorker: ParallelWorker#1 starting on thread [9]
18:46:44.792 Info  [ 8] TestWorker: ParallelWorker#2 starting on thread [10]
18:46:44.792 Info  [ 8] TestWorker: ParallelWorker#3 starting on thread [11]
18:46:44.792 Info  [ 8] TestWorker: ParallelWorker#4 starting on thread [12]
...
18:46:44.792 Info  [ 9] TestWorker: ParallelWorker#1 executing TestFirstGroup
18:46:44.792 Info  [11] TestWorker: ParallelWorker#3 executing TestSecondGroup
...
18:46:44.825 Info  [12] TestWorker: ParallelWorker#4 executing TestFirstGroup OneTimeTearDown
...
18:46:44.828 Info  [ 9] TestWorker: ParallelWorker#1 executing TestSecondGroup OneTimeTearDown
...
18:46:44.847 Info  [12] TestWorker: ParallelWorker#4 stopping - 1 WorkItems processed.
18:46:44.847 Info  [10] TestWorker: ParallelWorker#2 stopping - 0 WorkItems processed.
18:46:44.847 Info  [11] TestWorker: ParallelWorker#3 stopping - 1 WorkItems processed.
...
18:46:44.847 Info  [ 9] TestWorker: ParallelWorker#1 stopping - 2 WorkItems processed.
...
```

**Comment by CharliePoole** [comment]
@mikkelbu I see that in the log. The tests themselves are all run using the non-parallel strategy. I thought they should run using the Direct Strategy, that is on the same thread as the parent. That would effectively cause everything to run in parallel.

I could be wrong, but I believe this was once working. We need to figure out why the lower-level tests are being dispatched using the NonParallel strategy. I think that's the key to the problem.

**Comment by AndreyChizhikov** [comment]
Hello @CharliePoole 
Maybe is there another way for parallelizable on namespace level?
Please, advice.

**Comment by AndreyChizhikov** [comment]
@mikkelbu, @CharliePoole
This problem was solved when I added  [SingleThreaded] annotation for SetUpFixture classes.
Excuse for troubling.
