### ISSUE TITLE
TestCaseAttribute special type conversions don't work with param array

### ISSUE THREAD

**Issue by stevenaw** [nunit/nunit#3135]
I noticed this while working on #3053

It looks like in the `TestCaseAttribute`, while we support passing primitives to a primitives param array and the passing of strings as values to single `DateTime`/`TimeSpan` values, we don't support the passing of strings to a param array of `DateTime`s or `TimeSpan`s.

So while these work:

```csharp
[TestCase(1, 2, 3)]
        public void CanConvertStringToDateTimeAsParamArray(int a, int b, int c) {}

[TestCase(1, 2, 3)]
        public void CanConvertStringToDateTimeAsParamArray(params int[] values) {}

[TestCase("1942-10-12", "1942-10-12")]
        public void CanConvertStringToDateTimeAsParamArray(DateTime a, DateTime b) {}
```

This does not:
```csharp
[TestCase("1942-10-12", "1942-10-12")]
        public void CanConvertStringToDateTimeAsParamArray(params DateTime[] dt) {}
```

**Comment by CharliePoole** [comment]
Correct, that would be a new feature. Personally, I wouldn't be keen on seeing it added since it seems only a limited convenience.

**Comment by ChrisMaddock** [comment]
Personally, I like the consistency of having it in. I wouldn't say it's a high priority, but if @stevenaw's done the work to make if happen, that sounds great to me! 😄

**Comment by CharliePoole** [comment]
My concern was for two things:

1. Even if the code is done, we have to keep supporting it.

2. What are the ramifications? If we make this work, are there other things that users might reasonably expect to work? I'm thinking of feature creep here.

@stevenaw do your changes apply __all__ the existing conversions to params arrays?

Do we want to convert non-params arrays? I should think not, since the arguments are not separated and the user can easily specify the type of the array.

**Comment by stevenaw** [comment]
Thanks @CharliePoole @ChrisMaddock (and for calling out what I've done so far on this), I agree just because it's coded doesn't mean it should be added.

@CharliePoole the work I've done so far would apply all existing type conversions to params arrays. It basically just applies the existing type conversion helper to the existing param array processing.
As for converting non-param arrays, that is a good question. I haven't been able to find existing support for nunit to perform any sort of type conversions in that case. The work I've done so far doesn't apply special conversions in this case, as there's no explicit handling of it by the framework.

I suppose my ultimate response to "why should this be added" is "I don't know". I noticed the (apparent) need for this by noticing in code that we only apply special conversions in some cases. It struck me as a possible API inconsistency that could be addressed. However, it also makes sense that if special conversions are applied to array processing, it should be for all cases.

So I guess that's the real question: Should type conversions be applied to arrays in addition to individual values?

I like the consistency this would bring, but I understand the overhead now in making this happen, as NUnit would have to add explicit handling of conversion of arrays (something I don't think is currently supported).

**Comment by stevenaw** [comment]
My last comment was a little verbose, but having thought about this a bit more, I'm almost against my original suggestion. Other cans-of-worms this could open include "do we convert multi-dimensional arrays"?

**Comment by rprouse** [comment]
I'm with @CharliePoole on this. It is feature creep and adds serious complexity for limited functionality. I am going to close this one.
