### ISSUE TITLE
Add "result properties"

### ISSUE THREAD

**Issue by madelson** [nunit/nunit#3136]
**Overview**

Today, NUnit supports the notion of test properties which can be used to associate static metadata with a test.

Similarly, it would be beneficial to be able to associate potentially-dynamic metadata with a test result for the purpose of providing additional diagnostic information after-the-fact. Examples of this include:
* If the test uses an external resource (e. g. a database), recording which instance of the resource was used
* Associating additional diagnostic information (e. g. a test which uses the Selenium API to automate a browser might wish to capture screenshots on failure and associate those files with the test result).
* Logging performance information

This was suggested in #3118.

**Potential API**

Ultimately, the API would look like adding to a dictionary, something like:

```
???.ResultProperties.Add("key", "value");
```

??? indicates that there are many places where this could be exposed, such as `TestContext.CurrentContext`, `TestContext.CurrentContext.Result`, etc.

The `ResultProperties` object itself could be `IPropertyBag` but I would prefer if it were a simple collections-like interface/abstract class:

```
abstract class ResultPropertyBag : IReadOnlyDictionary<string, string>
{
     public void Add(KeyValuePair<string, string> keyValuePair);
     public string this[string key] { get; set; }
}
```

**XML representation**

This would result in a test result XML collection similar to test properties:

```
<test-case id="0-1058" name="TestName" fullname="A.B.TestName" methodname="TheMethodName" classname="TheClassName" runstate="Runnable" seed="791217020" result="Passed" start-time="2019-01-02 17:54:36Z" end-time="2019-01-02 17:54:36Z" duration="0.000516" asserts="0">
   <properties>
      <property name="test property" value="its value" />
   </properties>
   <resultProperties>
       <resultProperty name="key", value="value" />
       ...
   </resultProperties>
</test-case>
```

**Current workarounds**

Today, this can be simulated by using test properties; you can add test properties at runtime via `TestExecutionContext.CurrentContext.CurrentTest.Properties.Add` or (less conviently) by implementing `ITestAction` and modifying `ITest.Properties` in `AfterTest`. However, according to #3118, this functionality is not intentional and may be removed in the future.

**Comment by CharliePoole** [comment]
A given test can only have one TestResult, which is the result were talking about here.

Test properties are set at the time the test is created (discovered) and cannot be changed subsequently. They express information about the test and exist whether you run the test or not.

Result properties would be added at execution time by user test code and possibly also by NUnit itself. They express something about a particular __execution__ of the test.

No particular implementation is implied. There might be a separate dictionary for result properties or individual properties might carry an indication of what type they are. The XML representation might call for a new element or the two might share the same representation. That's where some design is needed.

Constraint or assertion results might also be implemented as properties but that would seem to be a separate issue from this one.

**Comment by rprouse** [comment]
I am closing old uncategorized issues that have not had comments or made progress in some time. If anyone comes back with a compelling argument for these issues, we can reopen.
