### ISSUE TITLE
Default timeouts for uap10.0 tests

### ISSUE THREAD

**Issue by cclauson** [nunit/nunit#3146]
Hi,

My organization has a requirement that we run tests on uap10.0, we are currently doing this using NUnitLite.

We'd like to set default timeouts on tests so that if one hangs, it will fail.  It looks like this is supported if the nunitlite.dll that's being used was built with the #PARALLEL constant defined:
![image](https://user-images.githubusercontent.com/16675794/51864414-90516d00-22f8-11e9-8509-0c8a31d89ba5.png)

I'm seeing that in older versions of the nunitlite nuget package (3.6.1), uap10.0 would link against a portable class library that did have this defined, however in the newer version (3.11.0), it links against .NET Standard 1.4, which doesn't.  I believe we're stuck using the newer 3.11.0 version, which poses a problem for getting test timeouts.

Ideas/suggestions/advice?  Thanks so much!

**Comment by CharliePoole** [comment]
Seems like an odd choice to base TimeOut support on whether parallel execution is supported even though they both rely on the underlying threading capability. The decision of where to support parallelization and where to suppport timeout are logically separate.

**Comment by mikkelbu** [comment]
It was change from `!NETSTANDARD1_6` to `PARALLEL` in this PR https://github.com/nunit/nunit/commit/3dfb4fca636e6b4b22b508f4679e214bd88dca45#diff-ef55251d4911b7abfb43ccce01976965L381, but the tests are using `!NETCOREAPP1_1`:
https://github.com/nunit/nunit/blob/d438cf5f22515b9469cee705c8182366930a70e9/src/NUnitFramework/nunitlite.tests/MakeRunSettingsTests.cs#L34-L36
and
https://github.com/nunit/nunit/blob/d09def3521dca9be6fbd84fc483c555c4955afe3/src/NUnitFramework/nunitlite.tests/CommandLineTests.cs#L334-L336
And the implementation is using `THREAD_ABORT` (I think)
https://github.com/nunit/nunit/blob/cbeffad907943d4219a2f0cdcea55830d267225e/src/NUnitFramework/framework/Internal/Execution/SimpleWorkItem.cs#L144-L154
But `THREAD_ABORT` is also not available on .NET Standard 1.4, but will be when nunit/nunit#3027 is merged.

**Comment by rprouse** [comment]
I am closing old uncategorized issues that have not had comments or made progress. If anyone comes back with a compelling argument for these issues, we can reopen.
