### ISSUE TITLE
Unable to pass multiple assemblies to nunit console-3.8 in gitlab pipeline

### ISSUE THREAD

**Issue by ghost** [nunit/nunit#3151]
When I try to execute following command from from project root folder ` "C:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe" "path-to-assembly1 path-to assembly2"` in gitlab runner , I get the below error 

> The system cannot find the path specified
@CharliePoole  Could you suggest

**Comment by rprouse** [comment]
Try putting each assembly in quotes instead of both in one set of quotes? Also test on the command line on your developer machine. If it works on your machine but not on GitLab, you will need to contact them because there is probably something different about their runner.

**Comment by rprouse** [comment]
I am closing since we have not heard back from you. If you have more information, add it to this issue and we will reopen.
