### ISSUE TITLE
Custom test grouping and naming

### ISSUE THREAD

**Issue by withkittens** [nunit/nunit#3152]
Sorry, I didn't find relevant information about this. Suppose I have a test like follows:

```csharp
[TestCaseSource("Mul_TestCases")]
public void Mul(double expected, double a, double b) {
    Assert.AreEqual(expected, a * b);
}

public IEnumerable Mul_TestCases {
    get {
        yield return new TestCaseData(4, 2, 2);
        yield return new TestCaseDate(6, 2, 3);
    }
}
```

By default, NUnit generates a test group (_a test suite_?) name from a method, and test names - by combining a method name and arguments. So I get the following test structure:

```text
Tests
└ Mul
  ├ Mul(4,2,2)
  └ Mul(6,2,3)
```

**My question is**, is it possible to override the names of both the test group and test cases and still retain the structure? I.e. what I'd like to get:

```text
Tests
└ 🌈 Multiplication 🌈
  ├  2 × 2 is 4
  └  2 × 3 is 6
```

**Comment by withkittens** [comment]
Thanks for the reply!

> You can rename your test cases via the ‘setName()’ method on TestCaseData.

In this case the test cases stop being grouped under their "method" test, the suite is lost so to say:

```text
Tests
├ Name set with SetName()
└ Name set with SetName() [2]
```

> In terms of renaming the suite - can you not just give the method the name you want?

Yes, as long as the name I want obeys the rules for C# identifiers.

---

I tried to override the suite's name with an attribute:

```csharp
[AttributeUsage(AttributeTargets.Method)]
public class OverrideTestNameAttribute : Attribute, IApplyToTest
{
    public void ApplyToTest(Test test)
    {
        test.Name = "🌈 Multiplication 🌈";
    }
}

[OverrideTestName, TestCaseSource("Mul_TestCases")]
public void Mul(double expected, double a, double b) {
    Assert.AreEqual(expected, a * b);
}
```

But this doesn't work for some reason. Am I missing something? 🤔

**Comment by CharliePoole** [comment]
@withkittens I don't think you've told us how you are running the tests, i.e. what program is displaying the hierarchy. The reason this matters is that the nunit framework only creates the names, while the runner decides how to display them.

**Comment by withkittens** [comment]
Good point! I check both Visual Studio's Test Explorer and Jet Brains' Unit Test Explorer. They display the tests identically, i.e. if a test suite is discovered, it is displayed as a group in both tools.

**Comment by ChrisMaddock** [comment]
> Yes, as long as the name I want obeys the rules for C# identifiers.

Ahhh...I understand the problem! 😄 So no, I don't think your current solution will work - as the `TestCaseSource` attribute is currently responsible for building the Test Suite, and the two attributes I don't _think_ will work in combination. I don't think there's a work around with our current extensibility...@CharliePoole might know better!

It may be a possible feature addition, with adding a `TestSuiteName` property to the TestCaseSourceAttribute, which would work in a similar way to the `TestName` property on TestCaseAttrivute. That could then be passed in with the TestCaseParams, I think, from a quick glance at the code here.

https://github.com/nunit/nunit/blob/b5c1d549938476ff06f118557b29778b36593549/src/NUnitFramework/framework/Attributes/TestCaseSourceAttribute.cs#L146-L148

>_You can rename your test cases via the ‘setName()’ method on TestCaseData._
> In this case the test cases stop being grouped under their "method" test. The suite is lost so to say:

Ah - this is possibly an issue in the Microsoft test runner and JetBrains runner - neither of which are within full control of the NUnit team. 😞 Renaming a test doesn't affect the test structure, as output by the test framework! 

I'd suggest trying with

**Comment by withkittens** [comment]
I've got a repro project: https://github.com/withkittens/Issue3152.

1\. **I run tests once** through the JB's Unit Test Explorer. In the case of **.NET Core**, if I name `TestCaseData`s, their parent test suite is lost. **.NET462** starts display overriden test suite names but doesn't run them and doesn't display the test cases.

   ![image](https://user-images.githubusercontent.com/5273891/52170491-6070f200-275c-11e9-96c4-96cc6b6e92da.png)

2\. **I rerun the tests.** Nothing changes for **.NET Core**, but **.NET462** finally displays what I expect:

   ![image](https://user-images.githubusercontent.com/5273891/52170517-f016a080-275c-11e9-99d8-460f7b2e7e8a.png)

As you have much more experience than me in how the Visual Studio's test platform works, do you maybe have any clues or ideas what's working differently here?

**Comment by ChrisMaddock** [comment]
I think you have a problem with Resharper here - which is out of NUnit's control. Just to check, I loaded up your .NET462 assembly in the TestCentric GUI, where the tests display correctly, first time.

![image](https://user-images.githubusercontent.com/4837132/52178258-00ae3180-27c4-11e9-8bee-f3e6de9a1da5.png)

Regarding the Visual Studio runner, I would _guess_ that this is also out of our control, but @OsirisTerje might know better.

I'm going to close this issue, as I think you're problems lie outside NUnit - but feel free to comment further if I've missed something - we'll still get the notifications!

**Comment by ChrisMaddock** [comment]
Also, TIL that you _can_ in fact name your test suites with emoji! Thanks for that - what a time to be alive! 😄
