### ISSUE TITLE
NUnitLite TextUI Runner

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#316]
Currently, the TextUI runner loads the alternative assembly specified on the command line by calling Assembly.Load (assemblyName).  This requires that the specified assembly be either in the same directory as the executable, or on the probing path.

It would seem useful to allow the alternative assembly to be located anywhere.  The Assembly.LoadFrom (assemblyFile) allows the assembly to be located anywhere, since assemblyFile is "The name or path of the file that contains the manifest of the assembly".

I have found this to be very useful in my CF implementation, allowing me to put the assemblies containing tests in their own subdirectory.  I check the provided name for a directory separator character or an extension, and call the LoadFrom method if name has either.  Otherwise, I call the normal Load method. 

This is definitely a non-necessary enhancement.  Just a convenience.

**Comment by CharliePoole** [comment]
This was actually resolved several months ago in this commit: https://github.com/nunit/nunit/commit/9a0eb35aa7dd1b26aa28ff01c3ec46ed7e0633c8

I'm marking it as part of beta 2 so it will be included in the release notes.
