### ISSUE TITLE
https url repo

### ISSUE THREAD

**Issue by 304NotModified** [nunit/nunit#3161]
Please change the url of the repo to https :)

![image](https://user-images.githubusercontent.com/5808377/52527777-5e63e180-2cce-11e9-8c75-3d9c2cbb6703.png)

**Comment by jnm2** [comment]
@rprouse, @CharliePoole, you are the only two with access to the repo Settings tab?

**Comment by CharliePoole** [comment]
I changed it and got a security error, so I put it back.

1. http://nunit.org and http://www.nunit.org give a non-secure connection

2. https://nunit.org gives a secure connection

3. https://www.nunit.org gives me an error message indicating that the site is misconfigured. I'm using Firefox.

So there's more to be done here than just changing the links. I'll leave it for somebody who can take the time to figure it out.

**Comment by ChrisMaddock** [comment]
@rprouse has an open issue looking at this stuff at https://github.com/nunit/nunit.github.io/issues/21. @CharliePoole - do you think it would be good to change it to option 2, so we're sorted for now? 🙂

**Comment by CharliePoole** [comment]
That would make sense to me. I can make the change in the title but I think some of @jnm2 's changes use the form that doesn't work.

**Comment by CharliePoole** [comment]
Done in the repo heading.

**Comment by ChrisMaddock** [comment]
Just double checked - there's only one nunit.org change in Joseph's PR, and it looks to be the right form to me. 🙂 

This issue's specifically for the header, so I think I'll close this now as fixed. Thanks Charlie, and thanks @304NotModified for raising this! 

(One other thing while we're here - mind changing it to "NUnit 3 Framework" rather than "NUnit 3.0 Framework"? Been a good while since 3.0 now! 😄)

**Comment by jnm2** [comment]
@CharliePoole there was one link with a `www.` form, but I switched it to the form we usually use without even realizing that it was necessary. I think the HTTP form redirects `www.nunit.org` to `nunit.org`.

**Comment by CharliePoole** [comment]
@ChrisMaddock I changed the description as well.

@jnm2 I couldn't remember what you had used. I never cite with "www" anyway. It gets confusing because different browsers handle it differently, sometimes doing their own "redirecting."

**Comment by ChrisMaddock** [comment]
Thanks Charlie!
