### ISSUE TITLE
https url organization 

### ISSUE THREAD

**Issue by 304NotModified** [nunit/nunit#3163]
Here another one ;)

Please change the organization url to https (on https://github.com/nunit)

![image](https://user-images.githubusercontent.com/5808377/52540000-105de500-2d85-11e9-8b0f-71ab320278a5.png)

related #3161

PS, did you know you could also verify the domein? 

For example:

![image](https://user-images.githubusercontent.com/5808377/52540009-3a170c00-2d85-11e9-9f12-e7ede415f535.png)

You can do that here: 

![image](https://user-images.githubusercontent.com/5808377/52540032-5dda5200-2d85-11e9-9820-6392d5927e5f.png)

(deeplink: https://github.com/organizations/nunit/settings/domains)

**Comment by 304NotModified** [comment]
bump @ChrisMaddock

**Comment by CharliePoole** [comment]
I thought @rprouse was handling this although I can no longer find the issue. IIRC, we didn't want to link using https: until we were sure it worked correctly. I believe only @rprouse and I have the authority to change this in GitHub.

**Comment by rprouse** [comment]
Thanks, fixed. I am setting the milestone as closed without action so it doesn't get picked up in the changes.md for the next release.
