### ISSUE TITLE
Allow static SetUpFixture classes

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#3166]
As long as the setup and teardown methods are static, no instance should be created and therefore `static` and `abstract` classes and classes without constructors should work, just like OneTimeTearDown with a non-[SetUpFixture] class.

```cs
[SetUpFixture]
public static class AcceptanceTestsTeardownFixture
{
    [OneTimeTearDown]
    public static void OneTimeTearDown()
    {
        AcceptanceTests.OnGlobalTeardown();
    }
}
```

It currently fails all tests with:

> OneTimeSetUp: NUnit.VisualStudio.TestAdapter.Tests.Acceptance.AcceptanceTestsTeardownFixture is an abstract class

**Comment by stevenaw** [comment]
I'd be happy to take this on.

**Comment by CharliePoole** [comment]
Hadn't noticed this. You'll find that static classes look like abstract classes if you test for them in the wrong order.

**Comment by jnm2** [comment]
Thanks @stevenaw!

@CharliePoole It's not in the title but I wanted abstract classes and classes without constructors to work too. So like test fixtures, it shouldn't be necessary to be able to instantiate the class so long as all the methods NUnit needs are static methods.

**Comment by CharliePoole** [comment]
Making abstract classes work is inconsistent with test fixtures. It could work now but bite you later when done other features get added to setup fixtures. If the user wants to avoid instantiation, they tell us that by making the class static.

**Comment by jnm2** [comment]
I see, I was wrong about test fixtures. Thanks!

(@stevenaw Just static classes then.)

**Comment by stevenaw** [comment]
Sounds good. Thanks for the clarification @CharliePoole @jnm2
