### ISSUE TITLE
Assert-like Helper Methods that return useful data

### ISSUE THREAD

**Issue by abbotware** [nunit/nunit#3167]
While I am sure it is 'by design' I notice that all Assert methods are **void** (except for Throw / Catch)  

Would you consider helper methods that combine operations that would typically go together in series?

Consider the following:

```
    Assert.IsInstanceOf<OkObjectResult>(result.Result);
    var ok = result.Result as OkObjectResult;
    ... more asserts

```

After the first Assert, I almost always want to cast .. and then do more asserts.  This could be eliminated with a helper method like the following:

```
        public static TExpected InstanceOf<TExpected>(object expected)
        {
            Assert.IsInstanceOf<TExpected>(expected);
            return (TExpected)expected;
        }

```
the original now becomes:

```
     var ok = AssertHelper.IsInstanceOf<OkObjectResult>(result.Result);
    ... more asserts

```

**Comment by rprouse** [comment]
This issue is marked as an idea but hasn't had contributions in years so I am closing. If anyone is interested in working on this idea, post your interest and the team will consider reopening.
