### ISSUE TITLE
WARNING: All test reports are empty

### ISSUE THREAD

**Issue by slavkof** [nunit/nunit#3174]
Hello,

We are running tests in Unity3d.Unit tests (ran in test mode in unity) are displaying test results properly, but when we do the same for ui tests in play more, we get WARNING: All test reports are empty. Attaching the test output.

https://pastebin.com/BfhaJj0M

Any ideas? Thanks a lot!

**Comment by CharliePoole** [comment]
My vague understanding, based on comments elsewhere on the internet, is that Unity uses a modified version of NUnit. The test result XML you posted would seem to indicate that, since the second level test-suite element is not something NUnit would produce.

I know that's not very helpful, but maybe somebody else can add something. :smile:

**Comment by slavkof** [comment]
Perhaps, but the test that we run as editor tests produce this "same" output and that gets parsed properly by the xunit/nunit3 plugin on jenkins.

**Comment by CharliePoole** [comment]
My point was that if it's not actually vanilla NUnit producing the output and it's not NUnit writing the report, this may not be the best place to ask.

@nunit/framework-team Does anybody know about Unity and how its tests differ from straight NUnit?

**Comment by jnm2** [comment]
I haven't used Unity, sorry. That message doesn't exist in our codebase. Asking this question at https://unity3d.com/community is probably the quickest way to figure out why you're getting the message.

**Comment by slavkof** [comment]
Ok, thanks, will explore elsewhere.

**Comment by mikkelbu** [comment]
@slavkof No that this helps much, but if I google for »All test reports are empty« (without the quotes) then most hits are about the Jenkins plugin.
