### ISSUE TITLE
SetUpAttribute attribute not allowed in a SetUpFixture

### ISSUE THREAD

**Issue by BermudaLamb** [nunit/nunit#3178]
OneTimeSetUp: SetUpAttribute attribute not allowed in a SetUpFixture
Exception doesn't have a stacktrace
My code looks like this:

```cs
           [SetUpFixture]
            public class CCIOneTimeSetup : GMSignoffTestBase
            {
                internal static Dictionary<eOpportunityType, Configuration> Configurations { get; set; }
                internal static Dictionary<eOpportunityType, int> OpportunityCount { get; set; }
                internal static Dictionary<eOpportunityType, bool> HasOpportunities { get; set; }
        
                [OneTimeSetUp]
                public void Init()
                {
                       // Do some stuff here
                      // Populate the Configuations dictionary
                }
           }
```

I use ReSharper Ultimate 2018.2 to run my unit tests
I use NUnit 3.11, NUnit.ConsoleRunner 3.7, and NUnit3TestAdapter 3.12
My work is built in Visual Studio Professional 2017 v15.9.6 with .NET Framework 4.7.03190

**Comment by CharliePoole** [comment]
Do you have some TestFixture that mistakenly inherits from the SetUpFixture?

**Comment by BermudaLamb** [comment]
No, but I do have classes that reference the 3 static Dictionary items in there.

**Comment by CharliePoole** [comment]
The code you show has no SetUpAttribute, so the message is a mystery. Are you showing all of the code for the class?

**Comment by BermudaLamb** [comment]
The only method in the class is the init method. The base class only adds a getter for a GUID value.
The error message says:
`OneTimeSetUp: SetUpAttribute attribute not allowed in a SetUpFixture`

It is identifying the OneTimeSetUp attribute as the issue

**Comment by BermudaLamb** [comment]
Ah ha,, there is a an abstract base class that is a TestFixture, and has a void method with a OneTimeSetup attribute on it. Is that what the issue is?

**Comment by CharliePoole** [comment]
The message prefix, "OneTimeSetUp:", isn't referring to the attribute, although I can see how you would think that. In this case, "OneTimeSetUp" is the name of an internal stage of test execution in which the fixture class is examined and instantiated. It indicates that this is when the message was issued.

You can see the code that issues the message here: https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Attributes/SetUpFixtureAttribute.cs#L87

As you see, it's only triggered by SetUpAttribute or TearDownAttribute.

**Comment by CharliePoole** [comment]
If the base class has a SetUpAttribute as well, that would cause the problem.

However, you should never mix TestFixtures and SetUpFixtures in the same inheritance hierarchy.If the two of them need common code, then use the same base class - without any attributes - for both of them.

**Comment by rprouse** [comment]
@BermudaLamb I believe your problem has been solved so I am going to close this issue. Please comment if that is a mistake.
