### ISSUE TITLE
TestActionAttribute: Retrieving the TestFixture

### ISSUE THREAD

**Issue by stffabi** [nunit/nunit#318]
In NUnit 2.6.3 it was possible to access the TestFixture in a TestActionAttribute through TestDetails.Fixture.

The new ITest interface, which is used e.g. in the BeforeTest Method, seems not the have the possibility to retrieve the TestFixture. Is there some way to achieve this?

**Comment by CharliePoole** [comment]
Basically, someone needs to step through this and see what's happening so we can decide how to fix it.

**Comment by rprouse** [comment]
I have confirmed this. The Fixture attribute is never set for tests, fixtures or suites except in a couple of tests. It is accessed once in `OneTimeSetupCommand`, but that will always fail, so it will use the `Reflect.Construct(_fixtureType, _arguments)` call instead.

**Comment by CharliePoole** [comment]
I see the problem. We used to use the Fixture object in a TestMethod in order to invoke test methods, so it was always set. We changed to use TestExecutionContext.TestObject for invoking methods. We should probably copy that object to the Fixture property of a test when we begin executing the work item. For ActionAttributes, it will have to be done before the TestActionCommand is invoked.

**Comment by CharliePoole** [comment]
For suites or fixtures, I would have thought it was already set, but the same approach would likely apply if it isn't.

**Comment by shanabus** [comment]
If this is done, should the documentation be updated?  http://nunit.org/index.php?p=actionAttributes&r=3.0

It still shows TestDetails as a class to be passed into Before/After methods and it uses the Fixture property.

**Comment by CharliePoole** [comment]
That's not the current documentation, which is here: 
    https://github.com/nunit/nunit/wiki/Action-Attributes

I think the page you  found is an undeleted orphan page, but if you linked to it from somewhere, please let me know where.

**Comment by shanabus** [comment]
Ok, thank you.  It just came up with these search terms: "nunit 3 beforetest" - top result.

**Comment by CharliePoole** [comment]
I guess I should delete it then.
