### ISSUE TITLE
Test Parameters generate Common Language Runtime detected an invalid program.

### ISSUE THREAD

**Issue by natiki** [nunit/nunit#3191]
Hi,

I am getting the following error when NUnit runs via TeamCity (TC) on Windows Server 2012 R2:

```
======= Failed test run #1 ==========
System.InvalidProgramException : Common Language Runtime detected an invalid program.
   at NUnit.Framework.Internal.TestParameters..ctor(ITestData data)
   at NUnit.Framework.Internal.TestCaseParameters..ctor(ITestCaseData data) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\TestCaseParameters.cs:line 68
   at NUnit.Framework.TestCaseAttribute.GetParametersForTestCase(IMethodInfo method) in C:\src\nunit\nunit\src\NUnitFramework\framework\Attributes\TestCaseAttribute.cs:line 267
======= Failed test run #2 ==========
System.InvalidProgramException : Common Language Runtime detected an invalid program.
   at NUnit.Framework.Internal.TestParameters..ctor(ITestData data)
   at NUnit.Framework.Internal.TestCaseParameters..ctor(ITestCaseData data) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\TestCaseParameters.cs:line 68
   at NUnit.Framework.TestCaseAttribute.GetParametersForTestCase(IMethodInfo method) in C:\src\nunit\nunit\src\NUnitFramework\framework\Attributes\TestCaseAttribute.cs:line 267
```

TeamCity is configured as:

![image](https://user-images.githubusercontent.com/4738140/54485587-906cf280-48cf-11e9-89f5-2dcdf9e00843.png)

(I have also tried with the 3.9.0 console runner and it produces the same results)

The **Splyce.Standard.Messaging.Tests** has the following packages installed:

![image](https://user-images.githubusercontent.com/4738140/54485700-674d6180-48d1-11e9-8b70-ff0f514d80fc.png)

The **Splyce.Standard.Messaging.Tests** is a class library for .NET 4.61 and SpYtMessageBuilder is contained in a .NET Standard 2.0 class library. Other tests in the same **Splyce.Standard.Messaging.Tests** assembly **without parameters** run just fine. 

![image](https://user-images.githubusercontent.com/4738140/54485724-e17de600-48d1-11e9-982c-3e3240740e19.png)

It appears that it is only when I add the TestCase() attribute to provide parameters to my tests that the tests fail with the afore mentioned error. Any suggestions for a fix here?

PS. On my Windows 10 Professional 1803 machine all tests initiated using R# test runner all run just fine, both parameterless and those with parameters.

**Comment by rprouse** [comment]
@NikolayPianikov do you have any suggestions for this TeamCity error?

**Comment by mgoodfellow** [comment]
Hi @natiki ,

I just ran into this error myself while performing an upgrade from NUnit 2.x to NUnit 3.x

I solved this issue temporarily by turning off CodeCoverage in the TC NUnit configuration.

I'm using NUnit Console Runner 3.8.0

![image](https://user-images.githubusercontent.com/6501186/56419232-738e5b00-6291-11e9-8ac6-ef1eb63a8c4d.png)

I previously had the JetBrains dotCover selected.

Hope this helps!

**Comment by NikolayPianikov** [comment]
@natiki sorry, I missed this issue. Is it possible to create a minimal solution to reproduce the issue?

**Comment by natiki** [comment]
> @natiki sorry, I missed this issue. Is it possible to create a minimal solution to reproduce the issue?
@NikolayPianikov All good... What would you need? Just my test DLL?

**Comment by NikolayPianikov** [comment]
@natiki, yes, it would be great to have testing assemblies to reproduce and a build log file to get additional information about tools, versions and etc.

As for the suggestion from @mgoodfellow: if turning off the dotCover helped you, try updating it to the newest version and turn on again

**Comment by mgoodfellow** [comment]
@NikolayPianikov I updated from dotCover 2018.1.4 to 2018.3.4 and the build now passes successfully as before. Thanks!

One point of note is that the build is much slower (takes 12mins versus 5mins), but I'm still investigating this behaviour.

**Comment by NikolayPianikov** [comment]
@mgoodfellow try adding "include" (+:) filter for profiling assemblies only

**Comment by natiki** [comment]
@NikolayPianikov I also upgraded dotCover as suggested by @mgoodfellow  so I think this case can be closed (and am doing so) and a new one opened for @mgoodfellow performance issue if it is still in evidence.
