### ISSUE TITLE
Drop or at least make Travis not required?

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#3195]
We now have Azure DevOps Pipelines builds for NUnit, the NUnit Console/Engine and the Adapter running on all supported platforms. Our Travis builds have always been really slow and somewhat flaky. Based on that, I propose;

- Make our Azure DevOps Pipelines Required for PRs
- Make our Travis builds optional
- Possibly drop our Travis builds?

I'm entering the issue in this project, but I am thinking of doing this in the console/engine and adapter too, so I'd like it if the @nunit/core-team could comment. Based on our decision, I can create issues in the other projects.

**Comment by rprouse** [comment]
I forgot that the console/engine project doesn't have Azure DevOps pipelines builds yet. I will enter an issue to get them setup.

**Comment by rprouse** [comment]
Sorry, jumping around too much today. @jnm2 has the PR for the Azure DevOps pipeline builds in the console project.

**Comment by jnm2** [comment]
I'm in favor of dropping Travis even if it wasn't slow since it is redundant.

**Comment by CharliePoole** [comment]
Redundancy can be good. :smile:

**Comment by rprouse** [comment]
I agree that redundancy is good and I'd advocate for keeping Travis if it wasn't for the number of Travis builds that fail for unrelated reasons. It has been more stable recently, but I don't have much faith in their future stability. I've heard they were acquired and that a large number of their developers were let go.

**Comment by mikkelbu** [comment]
Personally, I prefer doing it in steps: first make our Travis builds optional, and then after some time drop them if they provide more pain than value.

**Comment by rprouse** [comment]
That is an excellent way of thinking about it @mikkelbu, let's go with that.

**Comment by rprouse** [comment]
I've made Azure DevOps required and dropped Travis as required on this repo and in NUnit Console.
