### ISSUE TITLE
IApplyToTest save user data to TestContext & dispose once test execution completed

### ISSUE THREAD

**Issue by Alex2357** [nunit/nunit#3197]
Hi,

I have found IApplyToTest interface which can be used to create a custom attribute for a test.
In that interface implementation I'm gonna wait once a resource(s) from the pool is(are) available
then I need to put it into a Context, so that test can use those resources indirectly.
Then I need to dispose that resource(s) once test execution completed. 

Questions:

- Is it a good option to use IApplyToTest to wait for a resource(s) available from pool of resources?
- Where do I store resource(I did not find anything in Context to store user data)?
- How do I add my implementation to dispose resource(s) once test executed?

**Comment by CharliePoole** [comment]
The `IApplyToTest` interface is implemented by attributes that do one particular thing: modify the test object itself, immediately after it is created. It's good for doing things like changing the status, adding properties, etc. but it has no direct part in how a test is executed.

Other interfaces exist for other purposes. Waiting for a resource is an action that would have to take place before the test could be launched. Amont other things, that would probably involve an attribute that participated in creating the commands used to execute a test by implementing one of the derivatives of `ICommandWrapper`.

That said, I'm not sure if you can effectively do this as an extension anyway. It sees to me that having a test that is ready to run but waiting for a resource requires an additional state to be added to NUnit's own test execution logic. Right now, tests that are enqueued are ready to start running. Use of a command wrapper would mean that the running test somehow got suspended until the resource became available. However, without getting into the internals of the framework, that test would continue to take up one of the worker threads and having sufficient tests in that state would hang your entire test run.

I think a true implementation would need to go beyond what it's possible for a custom attribute to do. See issue #165.

**Comment by Alex2357** [comment]
> ICommandWrapper

CharlierPoole many thanks for your answer. ICommandWrapper seems exactly what I need.
My use case is that the tests are using a limited number of WebDriver instances from the Selenium Grid.
Generally speaking a test uses one instance, but some test may require 2 instances. As result, I need to manage of those instances.
