### ISSUE TITLE
Tracking progress of OneTimeSetUp/OneTimeTearDown and SetUp/TearDown methods.

### ISSUE THREAD

**Issue by OlegYanushkevich** [nunit/nunit#3198]
By realisation ITestEventListener we can get information about starting and ending assemblies/fixture/tests, capture test output and test messages, but why we can't get information about starting and ending OneTimeSetUp/OneTimeTearDown and SetUp/TearDown methods?

**Comment by CharliePoole** [comment]
In NUnit a test is an abstraction. The ITestEventListener gives info about tests.  The internal implementation of s test

**Comment by OlegYanushkevich** [comment]
Thanks @CharliePoole  for detailed response. So, I'm trying to improve [nunit agent for reportportal](https://github.com/reportportal/agent-net-nunit) that builds a report based on what is sent to him nunit through ITestEventListener. Out of the box it supports concepts like OneTimeSetUp/OneTimeTearDown and SetUp/TearDown methods from nunit and fact that there is no possibility to track progress of the described methods, report will not contain full launch information.

**Comment by CharliePoole** [comment]
Let's see what other @nunit-framework-team members have to suggest.

**Comment by OlegYanushkevich** [comment]
@CharliePoole thanks for your attention.
