### ISSUE TITLE
NUnit System.Reflection.TargetException When using Run All on two different TestFixtures

### ISSUE THREAD

**Issue by ShenbagaPriya22** [nunit/nunit#3207]
I have created an IOS project with two classes, namely A and B using 'MonoTouch NUnitLite' version 1.0.0.0
A contains 3 tests and B contains 2 tests.
Selected  'Run All' test cases and noticed all 5 test passed.
Selected 'Run All' from 'A' and all 3 test passed.
Selected 'Run All' from 'B' and all 2 test failed.

Error:

System.Reflection.TargetException : Object of type 'B.test' doesn't match target type "A.test".

Same vice-versa, if I run B first and then A.

**Comment by mikkelbu** [comment]
@ShenbagaPriya22 Sorry for not noticing this issue, but this repository is not the source of "MonoTouch NUnitLite". I googled this and it seems to be https://github.com/spouliot/Touch.Unit. For this reason I'm closing this issue, but note that we can still see additional comments.
