### ISSUE TITLE
Can't read my Property Attribute

### ISSUE THREAD

**Issue by InkUisitor** [nunit/nunit#3208]
Hello !
I faced a problem about the Property attribute. I want to use it in a particular way but I can't retrieve the value I set.
The only way I can do it is when I 

```
[TestFixture(toto)]
[TestFixture(tata)]
MyClass
[Test, Property("myProperty", "myValue")]
MyFunction

```
I use TestContext.CurrentContext.Test.Properties["myProperty"] to get the value I set.

But my problem is that I want to make multiple execution with different values on myProperty

I tried :
```
[TestFixture(toto), Property("myProperty", "myValue1")]
[TestFixture(toto), Property("myProperty", "myValue2")]
[TestFixture(tata)]
MyClass
[Test]
MyFunction
```

But when I tried to get my values, my TestContext.CurrentContext.Test.Properties is empty.

I tried this too :
```
[TestFixture(toto)]
[TestFixture(tata)]
MyClass
[TestCase, Property("myProperty", "myValue1")]
[TestCase, Property("myProperty", "myvalue2")]
MyFunction
```

But for this one too, my TestContext.CurrentContext.Test.Properties is empty...

Can someone explain me how I can solve my problem with the property attribute ? I can cheat with the Description of my TestFixture, but this solution disgust me ...
Thanks

**Comment by InkUisitor** [comment]
OK, I solved the problem with the TestCase attribute.

I used this to solve my problem :
```
[TestFixture(toto)]
[TestFixture(tata)]
MyClass
[TestCase("myValue1")]
[TestCase("myValue2")]
MyFunction(MyValue)
```

It's perfect for what I wanted. But the question remains, why can't we access this Property when it's used in specific conditions ?

**Comment by mikkelbu** [comment]
Hi @InkUisitor. Variants of this have been asked before, see e.g. #1396 or #3067, as people think that properties, categories ... are derived from testfixtures to tests, or from parameterized tests to the individual tests. Charlie has a good explanation in https://github.com/nunit/nunit/issues/3067#issuecomment-430410684.

In your first example, you are placing the properties directly on the test, hence it is accessible from the test. In the second example, you are placing the properties on the fixture, hence they will only be accessible from the fixture. Also note that 
```csharp
[TestFixture(toto), Property("myProperty", "myValue1")]
[TestFixture(toto), Property("myProperty", "myValue2")]
[TestFixture(tata)]
MyClass
```
is the same as
```csharp
[TestFixture(toto)]
[Property("myProperty", "myValue1")]
[TestFixture(toto)]
[Property("myProperty", "myValue2")]
[TestFixture(tata)]
MyClass
```
in C#.  Similar in the the third example, the properties are not connected to the TestCase, even though it look to be case. The following 
```csharp
[TestCase, Property("myProperty", "myValue1")]
[TestCase, Property("myProperty", "myvalue2")]
MyFunction
```
is the same as 
```csharp
[TestCase]
[Property("myProperty", "myValue1")]
[TestCase]
[Property("myProperty", "myvalue2")]
MyFunction
```
So the properties are connected to the parameterized test and not the individual testcases. In the last case you are not using properties, but passing the values as parameters to the parameterized test. An alternative approach could be to have a source that supplies the TestCaseData for the test and then call `SetProperty` (see e.g. https://github.com/nunit/docs/wiki/TestCaseData).

I'm closing this issue, as I think it is covered by the existing issues, but we will still see the communication in this issue, so please write if you have more input.
