### ISSUE TITLE
Provide a way to distinguish between test discovery and test execution in `ITestBuilder.BuildFrom()` or similar.

### ISSUE THREAD

**Issue by dammejed** [nunit/nunit#3210]
Hello,

I'm writing to request or brainstorm if it's possible to enhance the `ITestBuilder.BuildFrom()` method to expose information around in what context the method is being built. For my case specifically, I care if the method is being built during discovery or during execution (e.g., in visual studio's test runner).

My usecase is that I have many many tests that are using [Autofixture](https://github.com/Autofixture/Autofixture) to provide automated data to various tests.

Unfortunately, building some of this data can take quite a long time, for essentially nothing. During discovery, the only use (to my knowledge, anyway) of building the test method is to arrive at the test method's name. In this case, it's essentially useless to build up object graphs for each parameter.

If there was a way to examine if the test method was being built for discovery, I could skip all of that construction, and simply return dummy parameter values, since they're not (again, to my knowledge) ultimately going to be used.

In the past, I could examine the test runner process to determine what mode the test method was being built in. (e.g. testdiscovery.exe vs testexecution.exe, I forget the exact names). In VS 2017 and later, however, both of these steps take place within `testhost.x86`, so that hack no longer works. The hack drastically improved test discovery time. from several minutes today (for ~18k tests) to tens of seconds. It's really a drag.

I'd love to discuss (or contribute!) along making this possible, but I'm afraid I don't have a full picture of the constraints. Any help in discussing feasibility or guiding implementation would be very much appreciated.

**Comment by frblondin** [comment]
Great idea. @rprouse do you agree with this idea so we could submit a PR?

**Comment by rprouse** [comment]
I am not against the idea although I would be interested in @mikkelbu and @jnm2's opinions too. I would worry in the use-case given that you will not return parameters in the same way as NUnit causing difficult to diagnose issues, but I guess it is your rope to hang yourself with 😄 

We must ensure that we don't break/change the existing interfaces. Quite a few people create builder attributes and we can't be breaking them. How do you propose to make the change with that in mind?

**Comment by frblondin** [comment]
Not sure about the best way to provide this information. @dammejed was requesting guiding implementation if have any idea.

For this, relying on a simple static field/property declared in `nunit.dll` or some ambient context somewhere would be enough. 

Once we have clearer ideas we'd need to agree as of how we could send this information to the remove AppDomain/process without breaking interfaces. I guess the existing `IFrameworkDriver.Load(...)` method could receive this information in the existing `IDictionary<string, object> settings` parameter? The implementation would the simply need to store this information somewhere (field/property/...).

**Comment by dammejed** [comment]
I agree. An ambient context for the discovery/running stage would be least impactful for existing implementors-- but I don't know if adding ambient context information anywhere jives with the design goals of NUnit.

**Comment by CharliePoole** [comment]
Bear in mind that the set of test names returned to TestExplorer in execution must match exactly those returned in discovery. This is not an NUnit limitation but a constraint imposed by VS. It's not an unreasonable one since the discovered tests are what the user sees.

**Comment by dammejed** [comment]
Indeed. That constraint is already considered by the default test method builder for Autofixture:

https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixture.NUnit3/FixedNameTestMethodBuilder.cs

It relies on the fact that `OriginalArguments` is used to build the method name, so that auto-created objects have a stable name (e.g. auto<T>).

**Comment by CharliePoole** [comment]
My concern is less about how you (and autofixture) will use it and more about what the as-yet-to-be-defined Api permits users to do in general.

As another matter, let's remember that this is __always__ discovery as nunit sees it. NUnit does discovery during TestExplorer's discovery phase and repeats it during the execution phase. We've always treated that as a hack - a necessary evil. Maybe we should revisit the need to do that.

If this is entirely about how we run in TestExplorer, we need @OsirisTerje in the loop and maybe this is really an adapter issue.

**Comment by dammejed** [comment]
If I take a step back, I think the problem isn't necessarily that I want to distinguish between discovery and execution, it's that I want to be able to defer creation of arguments _until needed_ at execution.
Similarly, I would want that the full name of a `TestMethod` can be build without needing to eagerly evaluate these arguments. It's been my assumption that it's not possible with NUnit facilities today, but maybe that's a false assumption.

**Comment by CharliePoole** [comment]
Yes. I think a full solution to that general problem will probably have to wait for a new framework or at least a new major version. Up to now we have advised __users__ to deal with it by deferring object construction to the test code itself, but that's not always convenient.

However, I can imagine dealing  in some way with the extreme case of execution under Test explorer, where discovery is performed twice.

**Comment by rprouse** [comment]
This issue is marked as an idea but hasn't had contributions in years so I am closing. If anyone is interested in working on this idea, post your interest and the team will consider reopening.
