### ISSUE TITLE
TestCaseSource is building for every test case on test runs

### ISSUE THREAD

**Issue by vanderkyl** [nunit/nunit#3213]
We currently have a test project that contains about 370 tests. All of these tests use TestCaseSource in order to retrieve test data. No matter how many test cases are run from the project, every single TestCaseSource is built and all data collected.

This has become a problem for us since we are using an AWS database (Dynamo DB) and the read operations on the tables within are causing exceptions since so many tests are grabbing data. Also it is taking around 20 seconds longer to start any test cases.

This is the theory anyway. One way to test this would be to turn off building every single test no matter which test is ran. It would be ideal to only build and retrieve data for the tests that are being requested to run. This may not be possible, but this the place to ask that question.

Any feedback is welcome. Thanks!

**Comment by mikkelbu** [comment]
This is currently only possible if you run the tests using NUnitLite, e.g. not via the console or via VS. Charlie has a god explanation of the problem in https://github.com/nunit/nunit/issues/2877#issuecomment-393110302 and has implemented filtering for NUnitLite in #2876.

See e.g. #2867 for more info. I'm closing this as answered, but we will still comments in this thread.

**Comment by CharliePoole** [comment]
To clarify our slightly conflicting answers... NUnitlite has code that __mitigates__ the effect of any problem but you're still not advised to do anything resource-intensive in your test case source code.

**Comment by vanderkyl** [comment]
Ok thank you, I'll take a look at filtering. 

One more question, if I were to add the [Explicit] tag to all of my test cases, will this fix the problem? Will the test cases be ignored during build time when not requested explicitly, or does this only affect if a test runs?

**Comment by CharliePoole** [comment]
No difference with Explicit. First we need a test case, then we can check if it's explicit.

Until discovery runs, there are no tests to select display, select, etc.
