### ISSUE TITLE
[Question] AppartmentAttribute on .NET Core

### ISSUE THREAD

**Issue by PKarasinski-Configit** [nunit/nunit#3227]
Hi. Is `AppartmentAttribute` not available on .NET Core? I can't use it and don't see it in Object Browser.

Thanks in advance.

**Comment by mikkelbu** [comment]
Hi @PKarasinski-Configit. It will be available for .NET Standard 2.0 from the next release of NUnit 3.12 (hopefully released within a week or two). I'm closing this as answered/duplicated by #3035. But we will still additional questions in this issue.
