### ISSUE TITLE
Framework 4.7 vs Framework 4.5

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#3254]
I am actually going to need to build a version of NUnitLite which runs on Mono, which currently supports .NET Framework 4.7.

Looking at the various build option, it looks like we only currently support up to .NET 4.5?

I am confused, since we use/test features which are not available in 4.5, such as ValueTuple, which was not introduced until 4.7.

Along this same line, how do I build a version of NUnitLite (framework and runner) which targets just .NET 4.7 and will run on mono?  Preferably in VS2019.

**Comment by CharliePoole** [comment]
The idea is that NUnit itself doesn't need any features > 4.5 but can run tests written against 4.7. I believe others do this. However, I don't know if Mono is a special case. Can you create a small test file targetting 4.7 but referencing the NUnit 4.5 build to see what happens?

**Comment by oznetmaster** [comment]
It is still confusing, because, for instance, ValueTupleEqualityTests.cs is conditioned on !NET35, which makes no sense, since it uses ValueTuple specifically, and cannot be compiled or run on anything less then .NET 4.7.

Yet, there is not ability to build a .NET 4.7 set of tests, that I can see.

**Comment by jnm2** [comment]
@oznetmaster The test project is referencing the System.ValueTuple NuGet package which works on earlier versions of .NET Framework.

**Comment by rprouse** [comment]
> Along this same line, how do I build a version of NUnitLite (framework and runner) which targets just .NET 4.7 and will run on mono? Preferably in VS2019.

Have you tried creating a test project console app that targets .NET 4.7 in Visual Studio? You should just have to add the NuGet package for NUnitLite, write your tests and compile. It should then just run in Mono.

**Comment by jnm2** [comment]
@oznetmaster Not sure, have we answered your questions?

**Comment by rprouse** [comment]
@oznetmaster I am going to close this as an answered question. Please revive it if you need more help.
