### ISSUE TITLE
I doubled my tests somehow

### ISSUE THREAD

**Issue by EnyarIsMe** [nunit/nunit#3255]
I somehow doubled my tests and don't know how to fix it back, When i rolled back the solution i becomes normal again, but i don't realy want to redo a lot of things, so how do i do it normal again?

**Comment by EnyarIsMe** [comment]
Foundout myself, needed to uncheck mshelper in resharper, 
Tools->Unit Testing->MsTest

**Comment by mikkelbu** [comment]
Great that you solved it @EnyarIsMe. I'm closing this issue.
