### ISSUE TITLE
The type of an Array isn't inferred from properly

### ISSUE THREAD

**Issue by KoziLord** [nunit/nunit#3259]
Using arrays of any dimension does not work in this example and ends up in the TestFixture failing to Set-up: ([System.IndexOutOfRangeException trace](https://gist.github.com/KoziLord/f781cb7ee748a69c2e40b0c480650ffd))
```CS
static object[] populateTestCases = new object[]
        {
            new object[] { new int[40], 10}
        };

        [Test, TestCaseSource(nameof(populateTestCases))]
        public void PopulateTest<T>(T[] array, T value)
        {
            foreach (var item in array)
                Assert.AreEqual(item, value);
        }
```

However using a List\<T> works fine: (The test compiles and behaves properly)
```CS
static object[] populateTestCases = new object[]
        {
            new object[] { new List<int>(40), 10}
        };

        [Test, TestCaseSource(nameof(populateTestCases))]
        public void PopulateTest<T>(List<T> array, T value)
        {
            foreach (var item in array)
                Assert.AreEqual(item, value);
        }
```

**Comment by CharliePoole** [comment]
Looks like a bug (if confirmed) in the logic whereby NUnit deduces what type to use for a generic test method. It would probably give us some useful info if you tried reversing the order of the arguments.

**Comment by KoziLord** [comment]
Reversing the order doesn't help.

**Comment by CharliePoole** [comment]
Ah well, it was a thought and the result gives us more information.

**Comment by mikkelbu** [comment]
I just debugged the problem. When we enter `GenericMethodHelper.TryGetTypeArguments` we have that `argList` contain two elements: an int `10` and an integer array consisting of 40 zeroes. When we call `TryApplyArgType` for the array then we call with `parmType` is an `T[]` and `argType` is an `Int32[]`.

But the code below fails as `parmType.GetTypeInfo().ContainsGenericParameters` returns true, but `parmType.GetGenericArguments()` returns an empty array, so for arrays we should probably use `parmType.GetElementType()` to get `T`.

https://github.com/nunit/nunit/blob/1a34eac63d3041697245ffcb573f756fe2bf2f7e/src/NUnitFramework/framework/Internal/GenericMethodHelper.cs#L110-L117
