### ISSUE TITLE
F#'s unit type should be treated the same way as void

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#3267]
[`unit`](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/unit-type) is F#'s closest idiomatic equivalent of C#'s [`void`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/void).

Where you'd use `void` in C#, you'd return `()` (return type [`unit`](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/unit-type) in F#. Where you'd use `Task` in C#, you'd use [`Async<unit>`](https://msdn.microsoft.com/visualfsharpdocs/conceptual/control.async-class-%5bfsharp%5d) in F#.

NUnit marks such methods as not runnable:

> Method has non-void return value, but no result is expected

This is blocking my work on https://github.com/nunit/nunit/issues/34.

~~@nunit/framework-team Unless there's a workaround which I've been unable to find, does this mean that no one has ever used F# with NUnit? I'm looking at https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-fsharp-with-nunit#creating-the-first-test and I can't see how this would work since NUnit would fail it for having the return type `unit`.~~

**Comment by CharliePoole** [comment]
People have been using F# with nunit for years. See our F# samples project.

It's not idiomatic F#. I based it on what people were doing at the time to fit nunit into F#.

IIRC many people were using an adapter framework that made the tests seem more idiomatic.

**Comment by jnm2** [comment]
Ah, the missing piece for me was that the F# compiler uses the IL return type `void` when it returns `unit`! The reason I'm getting `Method has non-void return value, but no result is expected` was not because of the `unit` return type which I saw in the F# tooltip but rather `Async<unit>` not being recognized as an async type.

Alright, I think I can go ahead and make the same changes as part of the async work:

https://github.com/nunit/nunit/blob/78627a97ae1cdeac31f9c016697b18c6c1d96e1f/src/NUnitFramework/framework/Internal/Tests/TestSuite.cs#L320-L325

https://github.com/nunit/nunit/blob/78627a97ae1cdeac31f9c016697b18c6c1d96e1f/src/NUnitFramework/framework/Internal/Builders/NUnitTestCaseBuilder.cs#L187-L195

**Comment by ehouarn-perret** [comment]
Any way to interpret `Task<unit>` as Task`
