### ISSUE TITLE
Failed assertion in TearDown will stop executing the rest

### ISSUE THREAD

**Issue by richja** [nunit/nunit#3269]
Noticed one behavior and not sure if this is a bug or feature.
When assertion is done inside TearDown method and that assertion will fail, the rest of the method is not executed.

Example:
```    
        [TearDown]
        public void Finish()
        {
            Assert.That(false);           
            driver.Quit(); //this method will not get executed when assert will fail
        }
```

Is there some more elegant way to run assert at the end of every single test?
Thank you

**Comment by CharliePoole** [comment]
As you indicate, a failed assertion ends the test immediately by throwing an exception.

In the original (i.e. cerca 2000) design of NUnit, Assertions inTearDown that fail were treated as an error. We have continued to follow that strategy throughout the various versions of NUnit.

The reason for this is that the TearDown is guaranteed to run, even if your code throws an unhandled exception. So, in some cases, you end up running as part of an exception handler. Essentially, that means you should really not use assertions in a TearDown, but if you do you have to make sure to do it after all necessary cleanup is done.

In an old issue (#49) I talked about a `PostTestAttribute` that would run after the test method but before teardown. We never did anything with that however.

I'll leave this open for now in case there are more comments or ideas for you.

**Comment by mikkelbu** [comment]
I'm closing this issue as answered. Please note that we will still see additional comments on this issue.
