### ISSUE TITLE
Does Nunit have a distributed testing system?  If not are there any plans to do so?

### ISSUE THREAD

**Issue by John-Albers** [nunit/nunit#3278]
I've been trying to use Nunit and Selenium to run distributed tests using the Grid system, but for any complex operations grid has to send all of the page html across the network and this adds unfortunate delays to the tests.  I was wondering if Nunit has a similar system but one that would send each test to a separate Nunit tester to run on a remote system.

**Comment by mikkelbu** [comment]
@John-Albers This sounds similar to nunit/nunit-console#167, but nothing of the kind exists at the moment as far as I know, and I think it will be a very big task, so I don't think that this will be done anytime soon.

@CharliePoole and @rprouse can probably provide more info, as nunit/nunit-console#167 is before I got involved in NUnit.

**Comment by rprouse** [comment]
This is similar to nunit/nunit-console#167. Nobody has ever started work on that issue even though I do think it is a good idea. @John-Albers, I am going to close this issue as a question, but feel free to comment on or add suggestions to nunit/nunit-console#167. The more interest there is in a feature, the more likely someone will work on it 😉
