### ISSUE TITLE
TimeoutAttribute makes all Assertions count as failure

### ISSUE THREAD

**Issue by fbrosseau** [nunit/nunit#3282]
Hello

TimeoutAttribute(via TimeoutCommand) wraps the tests in a Task.Wait call under netcore (because Thread.Abort is no longer supported API), here: https://github.com/nunit/nunit/blob/d8490ecd6171538fa0ba9cb5d38948bde5ebd61e/src/NUnitFramework/framework/Internal/Commands/TimeoutCommand.cs#L102

Using any of the 'flow-control' assertions like Assert.Ignore will throw their respective special-case Exception (here IgnoreException), which Task.Wait will wrap in an AggregateException, which is not handled by ValidateAndUnwrap here
https://github.com/nunit/nunit/blob/c3caee3dcbc4704cd9a2c4ae426789869d5d092c/src/NUnitFramework/framework/Internal/Results/TestResult.cs#L564

This will result in the test counting as full-blown failure due to unhandled exception.

This simple test will do it:
```        
[Test, Timeout(1234)]
public void TimeoutBug()
{
    Assert.Ignore("a");
}
```

I believe it should be safe to change ValidateAndUnwrap to handle AggregateExceptions the same way it does for TargetInvocationExceptions. It may also be beneficial to dive into the exception recursively instead of only once.

**Comment by airbreather** [comment]
Another option:

1. `originalTask` = the `Task.Run` we do now
1. `delayTask` = a `Task.Delay(_timeout)`
1. `Task.WhenAny(originalTask, timeoutTask).GetAwaiter().GetResult()` gives you the first `Task` to complete.
    - if it's `delayTask`, then we hit the timeout block
    - otherwise, call `.GetAwaiter().GetResult()` on it, which should do the right thing

**Comment by provegard** [comment]
Came here to report this exact issue. We want to use an assembly-wide `Timeout` attribute, but tests that use `Assert.Ignore` start to fail. Any workaround except not using `Assert.Ignore`?

**Comment by roji** [comment]
Ran into this too.
