### ISSUE TITLE
'Good first issue' or 'help wanted' issue count badge

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#3290]
What do you think of the idea of adding one of these badges to our readme?

[![GitHub issues by-label](https://img.shields.io/github/issues/nunit/nunit/help%20wanted.svg)](https://github.com/nunit/nunit/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22)

Or

[![GitHub issues by-label](https://img.shields.io/github/issues/nunit/nunit/good%20first%20issue.svg)](https://github.com/nunit/nunit/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)

**Comment by mikkelbu** [comment]
I think it is an good idea, and also an easy task for a new contributor, so I say yes.

**Comment by CharliePoole** [comment]
Nice! I plan to steal the idea.
