### ISSUE TITLE
Assert().Fail() generates exception framestack with incorrect index of line

### ISSUE THREAD

**Issue by nvborisenko** [nunit/nunit#3299]
```csharp
[Test]
        public void Test3FailedWithoutMessage()
        {
            Assert.Fail();
        }
```

In the report I see that test failed at the 39th line number. But expected line should be `38`.

![image](https://user-images.githubusercontent.com/22616990/60541868-2dd32180-9d1b-11e9-9001-6d119d248eae.png)

**Comment by nvborisenko** [comment]
Cannot reproduce it with provided simple example. I will return back to here if meet it again.

**Comment by mikkelbu** [comment]
@nvborisenko Is this compiled in debug og release (or more precisely, compiled with optimizations enabled), as this can sometimes affect the line numbers in stack traces. But usually optimizations "removes" lines from the original code whereas this is the opposite problem.

**Comment by nvborisenko** [comment]
I am able to reproduce it again. I prepared solution for playing: [git repo](https://github.com/reportportal/example-net-nunit/tree/nunit-issue-3299) (branch is `nunit-issue-3299`).

If we open this solution and execute tests via Test Explorer (formally using NUnit3TestAdapter), the stacktrace is correct.

But if we execute tests via `nunit3.console.exe`, we meet incorrect stacktrace line number.

It doesn't depend on Debug/Release mode.

**Comment by nvborisenko** [comment]
I added new test into the same class, which throws exception as `throw new Exception()`, and stacktrace is correct for this case. So, I can say, that nunit modifies stacktrace somehow.

**Comment by nvborisenko** [comment]
@mikkelbu thank you, you are right. We can blame code optimization during project building which is set by default for Release configuration. If I disable `Optimize code` checkbox in project settings, stacktrace is correct.
