### ISSUE TITLE
Incorrect formatting of failure message if test fails with Assert.Multiple

### ISSUE THREAD

**Issue by nvborisenko** [nunit/nunit#3302]
```csharp
Assert.Multiple(() =>
            {
                Assert.AreEqual(2, 3, "The first failed assert");
                Assert.AreEqual(4, 5, "The second failed assert");
                throw new Exception("And exception and the end.");
            });
```

XML report contains failure message with missing whitespace:
![image](https://user-images.githubusercontent.com/22616990/60539941-9ff53780-9d16-11e9-87a2-05217b230b90.png)

**Comment by ChrisMaddock** [comment]
I've moved this issue over to the framework repo, where the fix will need to be. 🙂 

I agree the simpler fix is fine. This is a legacy message - if someone wants to take the time to make the formatting equivalent, I'd happily merge the work - but it's not necessary in my eyes.
