### ISSUE TITLE
Sporadic GetResultIsNotCalledUntilContinued failure

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#3307]
I've seen this a few times in CI builds:

```
1) Failed : NUnit.Framework.AwaitableReturnTypeTests("ReturnsCustomTask").GetResultIsNotCalledUntilContinued
GetResult was not called after the continuation passed to OnCompleted was invoked.
   at NUnit.Framework.AwaitableReturnTypeTests.GetResultIsNotCalledUntilContinued() in C:\projects\nunit\src\NUnitFramework\tests\AwaitableReturnTypeTests.cs:line 83
```

**Comment by CharliePoole** [comment]
Me too. Hope you can get rid of it.

**Comment by jnm2** [comment]
Who writes this stuff lol

https://github.com/nunit/nunit/blob/a56e6859f3609128128ef87b0226472eb63ea5d4/src/NUnitFramework/tests/AwaitableReturnTypeTests.cs#L77

(me)

**Comment by jnm2** [comment]
I'm still trying to repro, but in the meantime I'd like to get rid of the spin waits: https://github.com/nunit/nunit/pull/3310

**Comment by jnm2** [comment]
Ah, I bet it was as simple as the 1000 timeout being too short for CI. Added a commit in #3310 to increase to the standard 10_000.
