### ISSUE TITLE
Test hangs "Test run in prog."

### ISSUE THREAD

**Issue by AKCen** [nunit/nunit#3319]
Hi, I'm running my tests by running "dotnet test".
On most of the test suites I have Parallelizable(ParallelScope.All)
References: nunit 3.11.0

It stucks on some test showing "Test run in prog.". May I setup a test execution timeout so that if the test is not completed in 2 minutes I get failed test?

**Comment by jnm2** [comment]
Yes. You can do `[Timeout(10_000)]` on any test method or fixture or `[assembly: Timeout(10_000)]` to set a default. (https://github.com/nunit/docs/wiki/Timeout-Attribute) If you're using .NET Core, our latest release (3.12) enables timeout support.

Good luck with the hanging test! Does this answer your question for now?

**Comment by AKCen** [comment]
Many thanks for a quick response. Sorry for the delay with my answer I had to verify on other machine.
I believe your answer is correct, the only a problem it did not help me. I was running test in VirtualBox on MAC Book Pro. Because it is slightly heavy CPU load then MACOS to prevent overheating is just doesn't let to work VirtualBox and VirtualBox doesn't do anything and it looks like a test stuck, where in fact the VM stuck.
