### ISSUE TITLE
New targets to replace EOL platforms

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#3320]
Microsoft stopped supporting .NET Core 2.0 on October 1, 2018 and .NET Core 1.0 and 1.1 on June 27, 2019. (https://dotnet.microsoft.com/platform/support/policy/dotnet-core)

Any version of .NET Standard lower than 2.0 is not needed because the only difference moving to 2.0 makes is that you have to move from UWP 10.0 to UWP 10.0.16299. (https://docs.microsoft.com/en-us/dotnet/standard/net-standard) There should be no reason _not_ to move to UWP 10.0.16299 at this point because it targets every version of Windows 10 that Microsoft supports.
@jrjrguo You asked for UWP 10.0 support about a year ago and we shipped it pretty soon after that. I remember from your GitHub profile that you work for Microsoft, so I'm assuming you have no need to support versions of Windows 10 released more than two years ago and therefore no need to target the old UWP 10.0. What are your thoughts?

### Things I would like to do

@nunit/framework-team What is your input on this?

1. [**Done**] Stop running our tests using netcoreapp1.1 and start using netcoreapp2.1, netcoreapp2.2, and netcoreapp3.0 (preview 7 is go-live and should be out next week)

2. [**Done**] Remove the NUnit framework netstandard1.4 target which simplifies our test matrix

3. Add a new netcoreapp2.1 target to NUnit framework so that TimeoutAttribute can actually use threads instead of tasks on .NET Core
  Now that I think of it, this would open the door to using AsyncLocal and other things not present in net45.

Whatever we decide here will affect https://github.com/nunit/nunit/issues/3223 where I want to begin testing every assembly we ship on every runtime we support.

**Comment by jnm2** [comment]
I don't personally like the idea of requiring contributors to have preview bits on their machines in order to run tests, so until we autodetect and skip that (#3223) let's just add up to netcoreapp2.2.

**Comment by rprouse** [comment]
I am fine with all of this, the only question is, if we want to add a `netcoreapp2.1` target and bring in support for `AsyncLocal`, should we also add a .NET 4.6+ target for the same thing on the full framework? Are there other constructs in 4.6+ that we should be supporting but aren't?

**Comment by jnm2** [comment]
@rprouse Perhaps yes? I'm not sure yet. AsyncLocal is just something we use internally in our .NET Standard builds IIRC, but it can't hurt to have more uniform behavior by adding a `net46` target.

Since Windows 7 is out of support in a few months, nearly everyone is on Windows 10 which doesn't allow you to get more than a year out of date. That means, functionally, everyone using a supported version of Windows will soon have .NET Framework 4.7.2 on their machine by default, and 4.8 soon after that.

I'll get started on moving things because it makes other work easier.

**Comment by stevenaw** [comment]
I'm closing this as the runtimes discussed here have already been dropped and `Timeout` has been marked `Obsolete` on .NET as aborting threads is not considered a safe thing to do.
