### ISSUE TITLE
NUnit Agent holding memory

### ISSUE THREAD

**Issue by mcgary-andrew** [nunit/nunit#3323]
Running NUnit agent on a virtual machine through Octopus Deploy is spiking the memory:

![image](https://user-images.githubusercontent.com/10423637/61488166-c8ab3d00-a964-11e9-9976-3e4a633490bd.png)

I am not sure what the issue could be. When I am running the same thing on my machine, I do not see it taking that much memory. I have tried adding "--agents=1" and "--dispose-runners" to the executing script but neither of them change how much memory it eventually takes (usually takes about 15 min for it to get up to 11-12gb).

**Comment by mikkelbu** [comment]
@mcgary-andrew Can you dump the process or attach a debugger to see what is holding the memory? (Otherwise, we don't have much to work with)

**Comment by ocmyhome** [comment]
@mcgary-andrew and I both tested against NUnit 3.11 and 3.12.  Same issue with memory.  Here's a link to the dumped NUnit agent process:  https://drive.google.com/open?id=1qqzywSr3xpdCfiZmKBZSvigr17Ce7gpz

In the mean time i'm going to downgrade to 3.10 and see what happens...

**Comment by rprouse** [comment]
Can you add the command-line options to the Task Manager and get the options that are being passed in to the agent? Ideally, we'd also like to see the options being passed in to the console runner.

You say that it is taking 15 minutes to get up to that memory usage. Do your tests usually take that long to run?

Lastly, can you reproduce on the virtual machine running NUnit console with the same command line options to take Octopus out of the picture?

**Comment by ocmyhome** [comment]
@rprouse I'll try and get that command-line information if/when I have some time.

Our tests typically take up to an hour or more.  We have a lot of tests and have built it retry logic.

I can't run on a virtual machine unfortunately.  We could attempt to run it on our own dev machines, which perhaps should help.

We've decided to rework some code on our end, which shouldn't increase the memory going fwd, which may make this issue go away for us...

**Comment by nvborisenko** [comment]
I may image a lot of tests generates a lot of console output.

**Comment by rprouse** [comment]
I am closing since we have not heard back from you. If you have more information, add it to this issue and we will reopen.
