### ISSUE TITLE
Broken link in CHANGES.md

### ISSUE THREAD

**Issue by dlebansais** [nunit/nunit#3324]
The file ./CHANGES.md contains "https://github.com/nunit/dev/wiki/Core-Engine", and this link triggers my broken link detector when I install.

**Comment by mikkelbu** [comment]
As far as I can tell the "core-engine" was removed based on this issue #793, but I cannot find any trace of the old documentation (as far as I can tell it was in a repository that no longer exists and was not migrated to the "docs"-repository, as the functionality was removed before this repository was created). 

I'm happy to delete the following sentence from CHANGES.md (to reduce confusion and remove broken links)
> See https://github.com/nunit/dev/wiki/Core-Engine for more information.

even though it is a bit stange to update old release notes. What do you think @nunit/framework-and-engine-team ?

**Comment by ChrisMaddock** [comment]
Sounds sensible to me. 🙂

**Comment by jnm2** [comment]
Sure.

**Comment by rprouse** [comment]
The core engine has been merged with the engine, so I think it makes sense to just clean up.
