### ISSUE TITLE
NUnitLite does not work with Microsoft.NET.Test.Sdk greater than 15.7.0

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#3327]
From https://github.com/nunit/nunit/pull/3321#discussion_r303218862.

All packages later than 15.7.0 cause our NUnitLite tests to fail on netcoreapp2.0 due to what I think is a VSTest bug, but I haven't had the time to dig in and confirm it.

**Comment by rprouse** [comment]
No progress since 2019, closing.
