### ISSUE TITLE
Workers parameter for .NetCore

### ISSUE THREAD

**Issue by unickq** [nunit/nunit#3332]
Hi all,

Is there a way to pass workers parameters to `dotnet test` when NUnit is used?

Here are my references.
![image](https://user-images.githubusercontent.com/6696821/62143571-e7141f80-b2f8-11e9-9c7f-b68bf40518b9.png)

The case is the following:
1) Root dir with sln and the main core project
2) Several test projects that refer to the main one. 
Each has `[assembly: NUnit.Framework.LevelOfParallelism(2)]`

 - When I run `dotnet test root/projectDir/project.csproj` everything runs fine in 2 threads as expected.
 - But when `dotnet test root/solution.sln` - all projects start run parallelly.

So what I want is smth like `dotnet test --workers=2`

This might be related to dotnet cli, but I think it's better to ask here first :)

**Comment by olegbaslak** [comment]
Use [.runsettings](https://github.com/nunit/docs/wiki/Tips-And-Tricks) options. These options can be passed using .runsettings file or as parameters in cmd.
For command line it can be used like `dotnet test -- NUnit.NumberOfTestWorkers=5`

**Comment by mikkelbu** [comment]
Hi @unickq 
I'm closing this issue as answered, but we will still get notifications about additional comments in the issue.
