### ISSUE TITLE
@Deni35 Which version of Visual Studio are you using? I have VS 16.2.0 Preview 1.0 and it looks like this

### ISSUE THREAD

**Issue by Deni35** [nunit/nunit#3342]
@Deni35 Which version of Visual Studio are you using? I have VS 16.2.0 Preview 1.0 and it looks like this
<img src="https://user-images.githubusercontent.com/1007631/62652096-d3049980-b95a-11e9-8038-971854db717f.png" width="50%" height="50%">

_Originally posted by @mikkelbu in https://github.com/nunit/nunit/issues/3340#issuecomment-519239261_

**Comment by Deni35** [comment]
How to delete it?

**Comment by Deni35** [comment]
Sorry!

**Comment by mikkelbu** [comment]
No problem :)
