### ISSUE TITLE
Test does not create a result after cancellation token stops infinite loop (works fine debugging)

### ISSUE THREAD

**Issue by SirMartin** [nunit/nunit#3343]
Hi,

I have some unit tests in a project, calling to a method that could be stuck on an infinite loop, I call this method inside a task, and cancel it after some time (enough for normal processing), and set an _assert_ if the task is not completed (I can understand as the method is stuck inside the loop)

If I run the test in debug mode in Visual Studio, works fine, the cancellation token works, and the test stops in the _assert_ and show the error and test failed. If I just run normally, it takes a longer time, and the test explorer shows the previous results greyed out.

I tried the same test running with Microsoft Test Framework, and worked fine, so I think there is an issue with NUnit that make it doesn't work.

I found that the test fails and print this message in the output, but test is not failed.
> The active test run was aborted. Reason: Process is terminating due to StackOverflowException.

I am using:
- .Net Core 2.1.7, 
- NUnit (3.12)
- NUnit3TestAdapter (3.14.0)

Can anyone help me? Any ideas?

``` chsarp
// Arrange
var obj = new MyObject();

// Act
var cts = new CancellationTokenSource();
cts.CancelAfter(250); // Cancel the task after 250 ms.

var taskResult = Task
   .Run(() => obj.DoSomething(cts.Token))
   .Wait(1000);

// Assert
Assert.AreEqual(true, taskResult, "The task not be completed until timeout, check if the loop is not stuck.");
```

**Comment by mikkelbu** [comment]
Hi @SirMartin 
Can you try to execute the tests using the nunit-console (perhaps with the `--inprocess`). Just so that it is easier to determine if the error is in NUnit, the adapter, VS, or a combination thereof.

**Comment by SirMartin** [comment]
I cannot find the way to run the tests with the console, I found some old information about was not possible to run .net core tests via console runner.

I am getting this error

```
NUnit.Engine.NUnitEngineException : An exception occurred in the driver while loading tests.
  ----> System.IO.FileNotFoundException : Could not load file or assembly 'nunit.framework, Version=3.12.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb' or one of its dependencies. The system cannot find the file specified.
--NUnitEngineException
An exception occurred in the driver while loading tests.
```

**Comment by SirMartin** [comment]
Anyone can help me? Thanks.

**Comment by rprouse** [comment]
Nobody was able to help and @SirMartin hasn't added any feedback, so closing.
