### ISSUE TITLE
Standardize TeamCity processing between Console runner and NUnitLite

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#3355]
I'm writing this after reviewing issue #2902, with an eye toward the more general problem underlying that issue. Which IMO is...

I originally wrote the code for TeamCity event handling, for both environments. At one point, we used the same (copy-pasted) source code in both projects. NUnitLite used it directly, while the engine accessed it through an extension.

That was a long time ago. @NikolayPianikov took over maintenance of the extension and has been fixing bugs and adding features for years now. Meanwhile, the part of NUnitLite that handles the `--teamcity` option has had relatively few changes.

If the @nunit/framework-and-engine-team agrees, I think this should be standardized in some way that doesn't require double maintenance. Some ideas...

1. Stop supporting `--teamcity` in NUnitLite. I put this here primarily for completeness because it's one obvious way to ensure that we don't have two different implementations! I don't think we can do it for NUnit 3, but maybe it should be considered for NUnit 4, if we plan to keep NUnitLite for that major upgrade.

2. Use shared source. That may be a bit difficult because the extension is implemented in multiple files and we would need to select those files that contain the basic implementation as opposed to the files that make it work as an extension. I think @NikolayPianikov would probably have to be the one to do this.

3. Use the extension package as a part of NUnitLite. We would bypass the extensibility stuff and use the internal implementation directly through the `ITestEventListener` interface. There are two options for how to use it.

 * Statically, using a normal assembly reference
 * Dynamically, loading the assembly only if the option is specified.

4. Make a separate NUnitLiteForTeamCity package, which uses option 3 while using option 1 for the existing NUnitLite package. The latter is, of course, a breaking change.

5. Actually implement a minimal version of extensibility for NUnitLite. This would be a somewhat bigger deal than any of the others, to say the least!

Personally, I lean toward either option 3 with dynamic loading or option 4. I'd be willing to pair up with @NikolayPianikov to make one of them happen. I think the decision needs to be taken by the teams involved and particularly the leads, taking into account where we want to be going WRT NUnitLite in the future.

**Comment by ChrisMaddock** [comment]
I would chose option 1, although yes, probably for v4. 

We have a continual battle in keeping the NUnitLite command line in sync with the console. Unpopular a consideration as it may be, the console has vastly more users than NUnitLite, and I don't like that the 'requirement' to make changes to both codebases impacts changes and developments to the console.

In previous threads, we discussed stopping trying to keep these command lines in sync. My view is that for v4, the NUnitLite command line should be stripped of all complex options where implementations may diverge, (e.g. teamcity, labels, NUnit2 results) and users should instead use the console if they require this functionality. In fact, I'd be quite happy if NUnitLite didn't support _any_ options, and just allowed the simple running of tests to default parameters.

I'd also like to see it merged into the framework itself, and no longer exist as a separate package...but that's a different thread! 😄

**Comment by ChrisMaddock** [comment]
Out of interest, what 'gap' do you see NUnitLite as filling, Charlie?

We use it frequently at work for all our 'simple' test libraries, so they can self-execute on CI, and we don't have to install any tooling to run tests. I'm aware others use a derivative for platforms the main project doesn't support, however all the supported platforms I believe we're also now planning to make available through the engine. Perhaps there's other usecases I'm missing.

**Comment by CharliePoole** [comment]
Good question. 

The original NUnitLite (now legacy at version 1.0) fulfilled two user needs and one personal need.

1. The need for a simple drop-in framework, all in one assembly to run simple tests in a single test-assembly as an executable.

2. The need to run tests on devices, which were assumed to be running a simplified operating system and often to require headless execution.

3. My own personal need to get away from complexity and work on a simple framework.

Out of __that__ NUnitLite, came a few things that persist today...

1. The Constraint model of test assertions, which I ported to NUnit in version 2.4.

2. The Xamarin versions of NUnitLite that run on IOS and Android.

3. The current "NUnitLite", which is part of NUnit. Of course it is no longer a test framework but only an addon that allows running a test. The original NUnitLite was both the framework and the runner.

But you are asking about the current NUnitLite! I'd say it serves the original first need and could possibly be used for the second one. However, I don't think you guys have been planning to stage tests on devices from the desktop, have you?

**Comment by NikolayPianikov** [comment]
2. I am ready to make code shared between several projects for instance by publishing nuget package with source code and all other required changes for all dependent projects
3,4,5 - good options
