### ISSUE TITLE
SetUpFixture not run

### ISSUE THREAD

**Issue by provegard** [nunit/nunit#3356]
## Description

I'm trying to migrate a test project from .NET Classic 4.7.2 to .NET Core 2.2. I have a class marked with `SetUpFixture` and inside it a `OneTimeSetUp` method. It is not run at all.

## Versions

NUnit version: 3.12.0
NUnit3TestAdapter version: 3.15.0
Visual Studio: 2017 Professional, 15.9.15
.NET platform: Core 2.2

## Repro

```
using NUnit.Framework;

namespace Tests
{
    public class Tests
    {
        [Test]
        public void Test1()
        {
            Assert.True(SUF.HasRun);
        }
    }
}

[SetUpFixture]
public class SUF
{
    public static bool HasRun;

    [OneTimeSetUp]
    public void BeforeEverything()
    {
        HasRun = true;
    }
}
```

**Comment by OsirisTerje** [comment]
@mikkelbu If I run All Tests from test explorer, that is the prefilter should not be in use, and I use 3.15, then it works for .net fw 4.7, and it doesnt for .net core.

**Comment by mikkelbu** [comment]
@OsirisTerje I can still make it fail also on .NET Framework 4.7 (sometimes I had to do a clean build, or to use git clean, to get consistent results when switching between FW and Core and between different versions of nuget packages).

![image](https://user-images.githubusercontent.com/1007631/63656623-87455300-c796-11e9-9aae-c128e469a8ff.png)

I've inserted some extra logging in the framework code, and in discovery there is no prefilter, but when I run All tests a filter is used. I'll try to see what kind of prefilter, but I'll probably first have time to do it Tuesday night.

**Comment by mikkelbu** [comment]
@OsirisTerje Which version of VS are you using. On VS 2019 (version 16.2.3) it fails on .NET Framework 4.7.2, but the same project passes on 15.9.15, so perhaps VS has change how they call the adapter for "All tests" in VS 2019?

**Comment by OsirisTerje** [comment]
@mikkelbu I am on travel now, so only got my laptop.  On my work machine I tested it on VS 2019 16.2.x (dont remember the rev no), and it worked on 4.7 and not on .net core.   Got to check with the PG if there has been any changes in the way they call the adapter.  
I've looked through the changes on 3.15, and I can't see any assembly changes that are really off.

**Comment by ohenriksson** [comment]
I have the exact same symptoms in a .Net 4.7.1 project.
All tests are in the same namespace.
[SetUp] is executed but not [OneTimeSetup]
VS 2019(16.2.3)

I've reverted back to the 3.14 adapter.

**Comment by OsirisTerje** [comment]
@ohenriksson @provegard Version 3.15.1 should now work for you.  The prefilter which caused this is turned off by default.

**Comment by ohenriksson** [comment]
> @ohenriksson @provegard Version 3.15.1 should now work for you. The prefilter which caused this is turned off by default.

Thank you! I've upgraded without problems

**Comment by provegard** [comment]
@OsirisTerje apologies for the late reply. I have ugpraded as well and everything works.
