### ISSUE TITLE
Tests with warnings are not added to console TestResult.xml's total count 

### ISSUE THREAD

**Issue by ashishdawale20** [nunit/nunit#3368]
Consider below tests and run it with the NUnit console runner 3.10.0.
The test-suite node of TestResult.xml file has total as 1 only. It should be 2 as I run all the tests using "nunit3-console.exe unittests.dll" command. 
 
 ```
[TestFixture]
    public class Class1
    {
        [Test]
        public void PassingTest()
        {
            Assert.IsTrue(true);
        }

        [Test]
        public void WarningTest()
        {
            Assert.Warn("Test");
        }
    }
```
Below it the test suite node of TestResult.xml, see the total attribute.

`<test-suite type="TestSuite" id="0-1004" name="UnitTest" fullname="UnitTest" runstate="Runnable" testcasecount="2" result="Warning" site="Child" start-time="2019-09-04 12:05:21Z" end-time="2019-09-04 12:05:21Z" duration="0.137385" total="1" passed="1" failed="0" warnings="1" inconclusive="0" skipped="0" asserts="1">`

**Comment by mikkelbu** [comment]
Good find. It looks like a bug, and it exists both in NUnitLite https://github.com/nunit/nunit/blob/cefc0c3a86c065daa4130aa255b1384db51b2b08/src/NUnitFramework/nunitlite/OutputWriters/NUnit3XmlOutputWriter.cs#L115 and in the regular output https://github.com/nunit/nunit/blob/a56e6859f3609128128ef87b0226472eb63ea5d4/src/NUnitFramework/framework/Internal/Results/TestResult.cs#L393.

Note that NUnitLite also lacks an attribute with the Warning-count.

**Comment by CharliePoole** [comment]
@mikkelbu The nunitlite code only replies to the `test-run` element, which it produces. The `test-suite` elements are created by the framework. The engine, of course, also creates `test-run` elements.

**Comment by ashishdawale20** [comment]
I am working on this fix. I will submit PR along with some tests.

**Comment by mikkelbu** [comment]
@CharliePoole I'm not sure I understand what you are saying. Should we leave the NUnitLite as it is, or perhaps just update the `total`, but not add a new `Warning` attribute (I'm guessing the latter, but I'm not sure).

**Comment by CharliePoole** [comment]
Only that you should fix NUnitLite and the framework itself consistently. The test-run record is not part of what the framework returns. It's added by the execution engine, i.e. nunitlite or nunit.engine.

**Comment by wvetrone** [comment]
Our team could use this fix.  @CharliePoole  -- what is the review process to get this into our code?  In the meantime do you have a work around for us?  We relay on that value

**Comment by CharliePoole** [comment]
Creating a PR __is__ the process. It has had some review and @ashishdawale20 made some further commits. He'll tell us when it's ready to be reviewed again and we'll go on from there.

**Comment by CharliePoole** [comment]
Sorry, I thought there was already a PR!!! So creating one is the next step.

**Comment by ashishdawale20** [comment]
@CharliePoole  the PR https://github.com/nunit/nunit/pull/3370 is ready to be reviewed.

**Comment by CharliePoole** [comment]
I added a notation to the PR description so it would correctly link with and (eventually) close this issue. FYI, not having that was why I didn't see that a PR existed.

**Comment by hmrjpatil** [comment]
@CharliePoole 
I too encountered same issue. When can this be fixed?

**Comment by CharliePoole** [comment]
@hmrjpatil I approved the PR but it is still waiting for a second team member to review it.
