### ISSUE TITLE
Could not write to file CucumberMessageQueue/messages. Stream could not be opened

### ISSUE THREAD

**Issue by cosminPintea** [nunit/nunit#3384]
My environment:
- Windows 10 , VS 2017, Specflow, Nunit3 , c# , .NET Core 2.1, Selenium
I am trying to run some UI specflow scenarios programmatically. I am trying to start the test execution using AWS lambda function (VS project AWS lambda project) . I get a "XmlNode" test fail response(see attachment). 
[XmlNodeResponsFromLambda.txt](https://github.com/nunit/nunit/files/3674988/XmlNodeResponsFromLambda.txt)

The same code run just fine in a console application run on a Windows machine.
Here is the code:
```c#

using Amazon.Lambda.Core;
using NUnit.Engine;
using System.Xml;

                using (ITestEngine engine = TestEngineActivator.CreateInstance())
                {
                    ITestFilterService _filterService = engine.Services.GetService<ITestFilterService>();
                    TestPackage package = new TestPackage("SpecflowTests.dll");
                    ITestFilterBuilder builder = _filterService.GetTestFilterBuilder();
                    builder.SelectWhere("cat == 18");
                    NUnit.Engine.TestFilter filter = builder.GetFilter();
                    ITestRunner runner = engine.GetRunner(package);

                    exploreResult = runner.Explore(filter);
                    result = runner.Run(null, filter);
                }

```
The error is : 
"OneTimeSetUp: System.InvalidOperationException : Could not write to file CucumberMessageQueue/messages. Stream could not be opened
trace:
at TechTalk.SpecFlow.CucumberMessages.Sinks.ProtobufFileSink.SendMessage(Envelope message)\n   at TechTalk.SpecFlow.CucumberMessages.CucumberMessageSender.SendTestRunStarted()\n   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnTestRunStart()\n   at TechTalk.SpecFlow.TestRunnerManager.FireTestRunStart()\n   at TechTalk.SpecFlow.TestRunnerManager.OnTestRunStart(Assembly testAssembly, IContainerBuilder containerBuilder)\n   at NUnitAssemblyHooks.AssemblyInitialize() in C:\\Users\\V3\\.nuget\\packages\\specflow.nunit\\3.1.32-beta\\build\\NUnit.AssemblyHooks.cs:line 13"

I notice that the trace has some references to windows folders. This code basically run in a Linux environment.  Could be something regarding right access for some files, or missing references? If something is missing i can add the file to the package that is deployed on the Lambda run environment.

**Comment by CharliePoole** [comment]
I reformatted your code and error blocks for legibility using code fences. See https://help.github.com/en/articles/creating-and-highlighting-code-blocks

**Comment by mikkelbu** [comment]
I don't think that this has anything to do with NUnit. The path in the stacktrace is just from the compilation and not something that is used at runtime. 

Same issue in the SpecFlow repository: techtalk/SpecFlow#1742

**Comment by cosminPintea** [comment]
Yes, look like it is an write access issue generated from specflow. The cause could be the write access in lambda function run-environment. The discussion is still open on AWS and specflow side.

**Comment by SabotageAndi** [comment]
This is an issue in SpecFlow. It has nothing todo with NUnit. It can be closed here.

**Comment by mikkelbu** [comment]
@cosminPintea I'm closing this issue, but we still see the new comments.
