### ISSUE TITLE
Use of Thread.CurrentPrincipal in Blazor/WASM

### ISSUE THREAD

**Issue by DzonnyDZ** [nunit/nunit#3392]
As commented on #2922 an issues seems to be introduced in NUnit 3.10 that prevents the tests running on Blazor/WASM.
I see the problem is in `SandboxedThreadState.Capture` where `Thread.CurrentPrincipal` is being red on netstandard2.0 and throws the exception (see below) that the Operation is not supported.

Code like this

     public class TestRunner : TestFilter, ITestListener
     {
        public IJSRuntime JS { get; }

        public TestRunner(IJSRuntime js) => JS = js ?? throw new ArgumentNullException(nameof(js));

        public void Run()
        {
            Console.WriteLine("Starting tests");
            Console.WriteLine();
            var builder = new DefaultTestAssemblyBuilder();
            var runner = new NUnitTestAssemblyRunner(builder);
            runner.Load(typeof(TestRunner).Assembly, new Dictionary<string, object>()
            {
                //https://github.com/nunit/nunit/issues/2922
                [FrameworkPackageSettings.NumberOfTestWorkers] = 0,
                [FrameworkPackageSettings.SynchronousEvents] = true,
                // [FrameworkPackageSettings.RunOnMainThread] = true
            });
            runner.Run(this, this);
            Console.WriteLine();
            Console.WriteLine("Test run finished");
        }
        #region ITestListener
        public void TestStarted(ITest test) => Console.WriteLine("Running " + test.FullName);
        public void TestFinished(ITestResult result)
        {
            var symbol = result.FailCount > 0 ? "✖" : (result.PassCount > 0 ? "✔" : "❓");
            Console.WriteLine($"\t{symbol}{result.PassCount} passed, {result.FailCount} failed, {result.SkipCount} skipped");
        }
        public void TestOutput(TestOutput output) => Console.WriteLine("\t🖶" + output.Text);
        //public void SendMessage(TestMessage message) => Console.WriteLine("\t🛈" + message.Message);
        #endregion

        #region TestFilter 
        //See NUnit.Framework.Internal.TestFilter+EmptyFilter
        public override bool Match(ITest test) => true;
        public override TNode AddToXml(TNode parentNode, bool recursive) => parentNode.AddElement("filter");
        public override bool Pass(ITest test) => true;
        public override bool IsExplicitMatch(ITest test) => false;
        #endregion
     }

Fails like this:

```
WASM: System.AggregateException: One or more errors occurred. (Operation is not supported on this platform.) ---> System.PlatformNotSupportedException: Operation is not supported on this platform. blazor.webassembly.js:1:35073
WASM:   at System.Threading.Thread.get_CurrentPrincipal () <0x20559e8 + 0x00008> in <c2e6bcfe48324efd8e0e56b33265ed38>:0 blazor.webassembly.js:1:35073
WASM:   at NUnit.Framework.Internal.SandboxedThreadState.Capture () <0x20556a0 + 0x00008> in <d392db2fb3d64f4fa564a7b744fc7801>:0 blazor.webassembly.js:1:35073
WASM:   at NUnit.Framework.Internal.TestExecutionContext.UpdateContextFromEnvironment () <0x20554b8 + 0x00004> in <d392db2fb3d64f4fa564a7b744fc7801>:0 blazor.webassembly.js:1:35073
WASM:   at NUnit.Framework.Internal.TestExecutionContext..ctor () <0x2054f40 + 0x0006c> in <d392db2fb3d64f4fa564a7b744fc7801>:0 blazor.webassembly.js:1:35073
WASM:   at NUnit.Framework.Api.NUnitTestAssemblyRunner.CreateTestExecutionContext (NUnit.Framework.Interfaces.ITestListener listener) <0x2054338 + 0x00006> in <d392db2fb3d64f4fa564a7b744fc7801>:0 blazor.webassembly.js:1:35073
WASM:   at NUnit.Framework.Api.NUnitTestAssemblyRunner.RunAsync (NUnit.Framework.Interfaces.ITestListener listener, NUnit.Framework.Interfaces.ITestFilter filter) <0x204df28 + 0x0007e> in <d392db2fb3d64f4fa564a7b744fc7801>:0 blazor.webassembly.js:1:35073
WASM:   at NUnit.Framework.Api.NUnitTestAssemblyRunner.Run (NUnit.Framework.Interfaces.ITestListener listener, NUnit.Framework.Interfaces.ITestFilter filter) <0x204d840 + 0x0000c> in <d392db2fb3d64f4fa564a7b744fc7801>:0 blazor.webassembly.js:1:35073
WASM:   at Doers.HtmlDom.Tests.InBrowser.TestRunner.Run () <0x1f93920 + 0x00098> in <5e269b296ac844bb952f344e9d495791>:0 blazor.webassembly.js:1:35073
WASM:   at Doers.HtmlDom.Tests.InBrowser.Startup.Configure (Microsoft.AspNetCore.Components.Builder.IComponentsApplicationBuilder app) <0x1f93060 + 0x00028> in <5e269b296ac844bb952f344e9d495791>:0 blazor.webassembly.js:1:35073
WASM:   at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&) blazor.webassembly.js:1:35073
WASM:   at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x1e846c0 + 0x000d2> in <c2e6bcfe48324efd8e0e56b33265ed38>:0 blazor.webassembly.js:1:35073
WASM: --- End of stack trace from previous location where exception was thrown --- blazor.webassembly.js:1:35073
WASM: blazor.webassembly.js:1:35073
WASM:   at Microsoft.AspNetCore.Blazor.Hosting.ConventionBasedStartup.Configure (Microsoft.AspNetCore.Components.Builder.IComponentsApplicationBuilder app, System.IServiceProvider services) <0x1f8b100 + 0x000fa> in <28660ebc37c240c28a4ee41c6477f236>:0 blazor.webassembly.js:1:35073
WASM:   at Microsoft.AspNetCore.Blazor.Hosting.WebAssemblyHost.StartAsyncAwaited () <0x1f8a258 + 0x001e8> in <28660ebc37c240c28a4ee41c6477f236>:0 blazor.webassembly.js:1:35073
WASM:    --- End of inner exception stack trace --- blazor.webassembly.js:1:35073
WASM: ---> (Inner Exception #0) System.PlatformNotSupportedException: Operation is not supported on this platform. blazor.webassembly.js:1:35073
WASM:   at System.Threading.Thread.get_CurrentPrincipal () <0x20559e8 + 0x00008> in <c2e6bcfe48324efd8e0e56b33265ed38>:0 blazor.webassembly.js:1:35073
WASM:   at NUnit.Framework.Internal.SandboxedThreadState.Capture () <0x20556a0 + 0x00008> in <d392db2fb3d64f4fa564a7b744fc7801>:0 blazor.webassembly.js:1:35073
WASM:   at NUnit.Framework.Internal.TestExecutionContext.UpdateContextFromEnvironment () <0x20554b8 + 0x00004> in <d392db2fb3d64f4fa564a7b744fc7801>:0 blazor.webassembly.js:1:35073
WASM:   at NUnit.Framework.Internal.TestExecutionContext..ctor () <0x2054f40 + 0x0006c> in <d392db2fb3d64f4fa564a7b744fc7801>:0 blazor.webassembly.js:1:35073
WASM:   at NUnit.Framework.Api.NUnitTestAssemblyRunner.CreateTestExecutionContext (NUnit.Framework.Interfaces.ITestListener listener) <0x2054338 + 0x00006> in <d392db2fb3d64f4fa564a7b744fc7801>:0 blazor.webassembly.js:1:35073
WASM:   at NUnit.Framework.Api.NUnitTestAssemblyRunner.RunAsync (NUnit.Framework.Interfaces.ITestListener listener, NUnit.Framework.Interfaces.ITestFilter filter) <0x204df28 + 0x0007e> in <d392db2fb3d64f4fa564a7b744fc7801>:0 blazor.webassembly.js:1:35073
WASM:   at NUnit.Framework.Api.NUnitTestAssemblyRunner.Run (NUnit.Framework.Interfaces.ITestListener listener, NUnit.Framework.Interfaces.ITestFilter filter) <0x204d840 + 0x0000c> in <d392db2fb3d64f4fa564a7b744fc7801>:0 blazor.webassembly.js:1:35073
WASM:   at Doers.HtmlDom.Tests.InBrowser.TestRunner.Run () <0x1f93920 + 0x00098> in <5e269b296ac844bb952f344e9d495791>:0 blazor.webassembly.js:1:35073
WASM:   at Doers.HtmlDom.Tests.InBrowser.Startup.Configure (Microsoft.AspNetCore.Components.Builder.IComponentsApplicationBuilder app) <0x1f93060 + 0x00028> in <5e269b296ac844bb952f344e9d495791>:0 blazor.webassembly.js:1:35073
WASM:   at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&) blazor.webassembly.js:1:35073
WASM:   at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x1e846c0 + 0x000d2> in <c2e6bcfe48324efd8e0e56b33265ed38>:0 blazor.webassembly.js:1:35073
WASM: --- End of stack trace from previous location where exception was thrown --- blazor.webassembly.js:1:35073
WASM: blazor.webassembly.js:1:35073
WASM:   at Microsoft.AspNetCore.Blazor.Hosting.ConventionBasedStartup.Configure (Microsoft.AspNetCore.Components.Builder.IComponentsApplicationBuilder app, System.IServiceProvider services) <0x1f8b100 + 0x000fa> in <28660ebc37c240c28a4ee41c6477f236>:0 blazor.webassembly.js:1:35073
WASM:   at Microsoft.AspNetCore.Blazor.Hosting.WebAssemblyHost.StartAsyncAwaited () <0x1f8a258 + 0x001e8> in <28660ebc37c240c28a4ee41c6477f236>:0 <--- blazor.webassembly.js:1:35073
WASM: blazor.webassembly.js:1:35073
```

**Comment by jnm2** [comment]
@DzonnyDZ I don't know of a reason not to take a fix for this. Are you able to let us know if this is the only thing blocking you? My method of checking would be to clone NUnit, comment out the Blazor project's package reference to NUnit and reference nunit.framework.csproj directly instead, and then comment out the CurrentPrincipal getting and setting in NUnit code and run?

@nunit/framework-team What do you think? We are not set up to do Blazor tests right now.

**Comment by DzonnyDZ** [comment]
@jnm2 This is the only think blocking me. Actually I'm able to successfully run tests in browser with code similar to what I posted and NUnit 3.9. I will try direct reference to NUnit to confirm this as You suggest.

**Comment by DzonnyDZ** [comment]
Hello, I can confirm that commenting-out line 60 in SandboxedThreadState.cs so the code looks like 
        public static SandboxedThreadState Capture()
        {
            return new SandboxedThreadState(
                CultureInfo.CurrentCulture,
                CultureInfo.CurrentUICulture,
                null,
                SynchronizationContext.Current);
        }
Solves the "Operation is not supported on this platform." exception.
However I'm still unable to run unit  tests inside of browser with the latest NUnit from master branch. The command `NUnitTestAssemblyRunner.Run` simply does nothing and never returns. As mentioned earlier NUnit 3.9.0 works perfectly. I suspect the issue is related to some threading as I can see there were some changes in threading and Mono.WASM (Blazor) does not support multithreading (yet).
But if I may, let's keep this bug focused on `Thread.CurrentPrincipal` and I'll try to figure out what is the other problem.

Also, I'm not sure how to currently fix the issue with `Thread.CurrentPrincipal` as I don't see Mono.Wasm as target framework in Visual Studio so this piece of code can be `#if`-ed. However I can get following information from `RuntimeInformation` and `RuntimeEnvironment` `System.Runtime.Interop` classes, so maybe normal `if`.

    ﻿RuntimeInformation:
        FrameworkDescription: Mono 6.7.0 (explicit/612e0644b6a)
        OSDescription: web
        OSArchitecture: X86
        ProcessArchitecture: X86
    RuntimeEnvironment:
        GetSystemVersion: v4.0.30319

**Comment by DzonnyDZ** [comment]
Further experimenting I can see that similar problem is indeed in `SandboxedThreadState.Restore` on line 80 where there is

**Comment by jnm2** [comment]
> Also, I'm not sure how to currently fix the issue with Thread.CurrentPrincipal as I don't see Mono.Wasm as target framework in Visual Studio so this piece of code can be #if-ed. However I can get following information from RuntimeInformation and RuntimeEnvironment System.Runtime.Interop classes, so maybe normal if.

I think the recommendation is to do feature testing rather than version/platform testing. What that looks like is to catch and ignore `PlatformNotSupportedException`.

**Comment by ChrisMaddock** [comment]
> We are not set up to do Blazor tests right now.

Medium-term, I'd be interested to look at creating a Blazor test agent for the console. Possibly though some sort of extensibility interface for adding platform-specific agents. 😊

**Comment by DzonnyDZ** [comment]
It would be great to provide some kind of one-click experience in Visual Studio. That some test adapter will run the tests in browser (of choice) and I can see the test execution progress and results in Visual Studio (and also debug the tests - but even Blazor itself is not that far yet). 
For now I was writing a code that using NUnit API runs the tests inside of browser on page load and display results in JS Console.
