### ISSUE TITLE
Async testing with F#

### ISSUE THREAD

**Issue by haf** [nunit/nunit#34]
I have been trying to find on how to test asynchronous code from F# without having to manually unwrap the async value, but rather having the test framework do that for you.

Since it seems 3.0 will bring with it improvements to async as well as the ability to parallelise tests, it would be great if there was some guidance on how to use the project with F#.

My question is simpler than this however; how do I create tests with F# that are async without wrapping them in TPL?

**Comment by nosami** [comment]
I just discovered a pattern that works for F#

```fs
open System.Threading.Tasks
open System.Runtime.CompilerServices

let toTask computation : Task = Async.StartAsTask computation :> _

[<Test>]
[<AsyncStateMachine(typeof<Task>)>]
member x.``Test``() = toTask <| async {
    let! x = doAsyncStuff()
}
```

**Comment by nosami** [comment]
Would be much nicer if NUnit supported F# async natively though

**Comment by rprouse** [comment]
@nosami, yes it would. Contributions from the F# community are welcome, or even just some help for us functional neophytes :smile:

**Comment by yreynhout** [comment]
I just discovered another pattern that works for F#

```fsharp
open System.Threading.Tasks
open NUnit.Framework

let toAsyncTestDelegate computation = new AsyncTestDelegate(fun () -> Async.StartAsTask computation :> Task)

[<Test>]
member x.``Test``() = 
    Assert.ThrowsAsync<InvalidOperationException>(asyncStuff 123 |> toAsyncTestDelegate) |> ignore
```

**Comment by nosami** [comment]
[This](https://github.com/xunit/xunit/commit/a2aa665f1b9633e8ec00f549c5df73a0c784a742) is how @bradwilson implemented it for xunit

**Comment by jnm2** [comment]
@rprouse Should I add an .fsproj to the solution (`nunit.testdata.fsharp`) for the IDE experience, or should I compile F# test fixtures on the fly using by referencing the FSharp.Compiler.Service nupkg from `nunit.framework.tests`?

The .fsproj would require all NUnit contributors to have the desktop F# SDK and the .NET Core F# SDK installed which may or may not be default. I could check.

**Comment by mikkelbu** [comment]
I prefer the second option, but I'm also a little biased as I already have F# installed 😄.

**Comment by rprouse** [comment]
I would prefer an F# project because it is easiest and I have it installed too, but it isn't a default workload in VS. How hard is it to use the FSharp.Compiler.Service?

**Comment by bradwilson** [comment]
In @xunit, we don't take any direct F# references (in the production code), but rather rely on reflection to discover the things that might be around and usable. Notably: https://github.com/xunit/xunit/blob/215dcb1a37f0eef0277e5ece002cc7dc030fe2a2/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs#L152-L180

**Comment by jnm2** [comment]
@bradwilson Awesome, nice to know I'm on the right track!

**Comment by jnm2** [comment]
@rprouse I haven't tried to use it yet, but it can't be fundamentally different than Roslyn and I've used that in tests before. Would you like to see what it would look like?

**Comment by rprouse** [comment]
@jnm2 I'd be fine with Roslyn as long as it isn't too much work for you.

**Comment by jnm2** [comment]
@rprouse Okay, I'll try out `FSharp.Compiler.Service` (the Roslyn-like option) then! I'm honestly on the fence, so I'm equally happy either way.

**Comment by ehouarn-perret** [comment]
Btw I am also having that with the task builder when it returns: `Task<unit>`: 
> Async test method must return an awaitable with a void result when no result is expected

Which makes the whole thing not that convenient and force an upcast to `Task`, for instance:

```fsharp
task {
    do! blahblahAsync()
} :> Task
```

**Comment by jnm2** [comment]
@ehouarn-perret This is taken care of in my PR which is just about done: https://github.com/nunit/nunit/pull/3268
