### ISSUE TITLE
Consider deprecating NUnitEqualityComparer.AreEqual optional bool parameter

### ISSUE THREAD

**Issue by stevenaw** [nunit/nunit#3410]
The NUnitEqualityComparer contains an optional parameter in the public API to specify if the comparison is top-level or not.
https://github.com/nunit/nunit/blob/8de9af1d695d42d2d85604a100ff9f6c00e5728f/src/NUnitFramework/framework/Constraints/NUnitEqualityComparer.cs#L157

This has been converted to separate overloads in a subsequent PR. https://github.com/nunit/nunit/pull/3406

That PR also gets the code to the point where the boolean parameter _could_ be calculated (but doing so could break consumers who explicitly pass false).

We can't just remove it outright, since it's a part of the public API and could be used by consumers (ex: a custom wrapper over the comparer), but I think we should consider marking the overload with the bool as obsolete, to be removed in a later version.

**Comment by mikkelbu** [comment]
I think it is fine to mark it obsolete in the 3.13.x branch and then correct it on master.

**Comment by seanpoulter** [comment]
It appears to me that #3410 can now we be closed. What do you think? We've had two PRs merged in October that marked AsEqual as obsolete then removed it.

**Comment by mikkelbu** [comment]
@seanpoulter Thanks for the heads up. You are right. This should be closed by the two PRs.
