### ISSUE TITLE
Update nuspec file to mention support for NET Standard 2.0+

### ISSUE THREAD

**Issue by stevenaw** [nunit/nunit#3411]
I think the nuspec file for nunit.dll needs to have the description updated to reflect current supported platforms. It mentions `.NET Standard 1.4+` but I think the actual support is `.NET Standard 2.0+`.
https://github.com/nunit/nunit/blob/master/nuget/framework/nunit.nuspec#L21

**Comment by jnm2** [comment]
Oh, that's important. Would you be able to take care of it?

**Comment by stevenaw** [comment]
Sure thing, I should be able to do this tonight

**Comment by jnm2** [comment]
Awesome. I didn't mean to rush you or anything. Only needs to be done before 3.13 ships.

**Comment by stevenaw** [comment]
Not a problem, it's a pretty quick change. PR is open for review.
I left a comment in there about keeping (or not) the mention of .NET Core in the description
