### ISSUE TITLE
ParallelScope.All hangs for almost 5 mins before starting the threads

### ISSUE THREAD

**Issue by anandbabu787** [nunit/nunit#3424]
My setup is like below,

nunit 3.12
nunit Test adapter 3.15.1

I have only one assembly and in assembly I have just mentioned the level of parallelism as **[assembly: LevelOfParallelism(10)]**

And in the test class I have removed all the dependencies between tests and set Parallelscope to all.

When I just run with 1 thread the tests are running as expected, but when I run it in multiple threads the threads wait for a long time before starting the execution, if I reduce the no of threads the wait time reduces.

I also tried it in the console runner in verbose mode to see the logs and the logs are below.

![image](https://user-images.githubusercontent.com/52974467/68679951-6d5e1580-0526-11ea-845e-0df125cf99ec.png)

Also these are not UI tests and all are just API tests.

I do have a setupFixture attribute with a onetime teardown which updates all the test results to TFS. I only have 30 tests as of now and they run less than 2 mins if I run in single threaded, if i enable parallelism it takes more than 5 mins to complete. Please assist.

**Comment by CharliePoole** [comment]
In general, although not always, performance problems come from allocating too many threads for the particular set of tests. To diagnose what's happening, we would need to see the __complete__ log. The portion you have attached appears to show various TestFixtures executing their one-time teardowns followed eventually by what I assume is your SetUpFixture. Is that correct? The portion shown takes almost two minutes in itself.

Other info needed:
 * What code is being executed in your various one-time teardowns.
 * How many cores do you have available for the 10 threads?
 * What performance do you see with fewer threads?
 * What performance do you see with `ParallelScope.Fixture` rather than `All`?

Bear in mind that there is an optimal number of threads for a given group of tests on a given machine, beyond which performance will always drop.

**Comment by anandbabu787** [comment]
Thanks for the quick response @CharliePoole 

I have a teardown at a test level for custom reporting and TFS execution status capturing and there are not multiple fixtures i have only one test fixture i mean all the tests are residing under only one class.

        [TearDown]
        public void CleanUp()
        {
            UpdateTestCaseIdsToTextFile();
            UpdateTestResultsInExtent();
            //CleanUpDriver();
        }

Please find the complete log below,


InternalTrace: Initializing at level Debug
23:33:07.640 Debug [ 5] DefaultTestAssemblyBuilder: Loading C:\Workspace\HR.DraftingPlanning.Automation\HR.DraftingPlanningTests\bin\QSB\HR.DraftingPlanning.Tests.dll in AppDomain domain-9d1059dc-HR.DraftingPlanning.Tests.dll
23:33:07.649 Debug [ 5] DefaultTestAssemblyBuilder: Examining assembly for test fixtures
23:33:07.652 Debug [ 5] DefaultTestAssemblyBuilder: Found 13 classes to examine
23:33:07.715 Debug [ 5] DefaultTestAssemblyBuilder: Found 5 fixtures with 36 test cases
23:33:07.797 Info  [ 5] DefaultTestAssemblyRunner: Running tests
23:33:07.803 Info  [ 5] Dispatcher: Initializing with 10 workers
23:33:07.807 Debug [ 5] WorkShift: Parallel shift adding queue ParallelQueue
23:33:07.807 Debug [ 5] WorkShift: Parallel shift adding queue ParallelSTAQueue
23:33:07.807 Debug [ 5] WorkShift: NonParallel shift adding queue NonParallelQueue
23:33:07.807 Debug [ 5] WorkShift: NonParallelSTA shift adding queue NonParallelSTAQueue
23:33:07.808 Debug [ 5] WorkShift: Parallel shift assigned worker ParallelWorker#1
23:33:07.808 Debug [ 5] WorkShift: Parallel shift assigned worker ParallelWorker#2
23:33:07.808 Debug [ 5] WorkShift: Parallel shift assigned worker ParallelWorker#3
23:33:07.808 Debug [ 5] WorkShift: Parallel shift assigned worker ParallelWorker#4
23:33:07.808 Debug [ 5] WorkShift: Parallel shift assigned worker ParallelWorker#5
23:33:07.808 Debug [ 5] WorkShift: Parallel shift assigned worker ParallelWorker#6
23:33:07.808 Debug [ 5] WorkShift: Parallel shift assigned worker ParallelWorker#7
23:33:07.808 Debug [ 5] WorkShift: Parallel shift assigned worker ParallelWorker#8
23:33:07.808 Debug [ 5] WorkShift: Parallel shift assigned worker ParallelWorker#9
23:33:07.808 Debug [ 5] WorkShift: Parallel shift assigned worker ParallelWorker#10
23:33:07.808 Debug [ 5] WorkShift: Parallel shift assigned worker ParallelSTAWorker
23:33:07.808 Debug [ 5] WorkShift: NonParallel shift assigned worker NonParallelWorker
23:33:07.808 Debug [ 5] WorkShift: NonParallelSTA shift assigned worker NonParallelSTAWorker
23:33:07.819 Debug [ 5] Dispatcher: Using NonParallel strategy for HR.DraftingPlanning.Tests.dll
23:33:07.821 Info  [ 5] WorkShift: NonParallel shift starting
23:33:07.822 Info  [ 5] TestWorker: NonParallelWorker starting on thread [8]
23:33:07.823 Info  [ 5] WorkItemQueue: NonParallelQueue.0 starting
23:33:07.824 Info  [ 8] TestWorker: NonParallelWorker executing HR.DraftingPlanning.Tests.dll
23:33:07.845 Debug [ 8] Dispatcher: Using Direct strategy for HR
23:33:07.845 Debug [ 8] Dispatcher: Using Direct strategy for DraftingPlanning
23:33:07.845 Debug [ 8] Dispatcher: Using NonParallel strategy for Tests
23:33:07.846 Info  [ 8] TestWorker: NonParallelWorker executing Tests
23:33:07.846 Info  [ 8] Dispatcher: Saving Queue State for Tests
23:33:07.848 Debug [ 8] WorkItemQueue: NonParallelQueue.0 pausing
23:33:07.848 Info  [ 8] WorkItemQueue: NonParallelQueue.1 starting
23:33:08.116 Debug [ 8] Dispatcher: Using Parallel strategy for DraftingPlanningAPITests
23:33:08.117 Info  [ 8] WorkShift: NonParallel shift ending
23:33:08.117 Debug [ 8] WorkItemQueue: NonParallelQueue.1 pausing
23:33:08.117 Info  [ 8] WorkShift: Parallel shift starting
23:33:08.118 Info  [ 8] TestWorker: ParallelWorker#1 starting on thread [9]
23:33:08.118 Info  [ 8] TestWorker: ParallelWorker#2 starting on thread [10]
23:33:08.118 Info  [ 8] TestWorker: ParallelWorker#3 starting on thread [11]
23:33:08.118 Info  [ 8] TestWorker: ParallelWorker#4 starting on thread [12]
23:33:08.119 Info  [ 8] TestWorker: ParallelWorker#5 starting on thread [13]
23:33:08.119 Info  [ 8] TestWorker: ParallelWorker#6 starting on thread [14]
23:33:08.119 Info  [ 8] TestWorker: ParallelWorker#7 starting on thread [15]
23:33:08.119 Info  [ 8] TestWorker: ParallelWorker#8 starting on thread [16]
23:33:08.120 Info  [ 8] TestWorker: ParallelWorker#9 starting on thread [17]
23:33:08.120 Info  [ 8] TestWorker: ParallelWorker#10 starting on thread [18]
23:33:08.120 Info  [ 8] TestWorker: ParallelSTAWorker starting on thread [19]
23:33:08.120 Info  [ 8] WorkItemQueue: ParallelQueue.1 starting
23:33:08.120 Info  [ 8] WorkItemQueue: ParallelSTAQueue.1 starting
23:33:08.120 Info  [11] TestWorker: ParallelWorker#3 executing DraftingPlanningAPITests
23:33:08.126 Debug [11] Dispatcher: Using Direct strategy for CloseDraftingPlan
23:33:08.126 Debug [11] Dispatcher: Using Parallel strategy for CloseDraftingPlan("DRAFT_ADMIN",[1057739, 1057740, 1057742])
23:33:08.126 Debug [11] Dispatcher: Using Direct strategy for CloseDraftingPlan401
23:33:08.126 Info  [13] TestWorker: ParallelWorker#5 executing CloseDraftingPlan("DRAFT_ADMIN",[1057739, 1057740, 1057742])
23:33:08.126 Debug [11] Dispatcher: Using Parallel strategy for CloseDraftingPlan401("NON_DRAFT_USER",[1057741, 1057743])
23:33:08.127 Debug [11] Dispatcher: Using Direct strategy for CreateDraftingPlan
23:33:08.127 Info  [15] TestWorker: ParallelWorker#7 executing CloseDraftingPlan401("NON_DRAFT_USER",[1057741, 1057743])
23:33:08.127 Debug [11] Dispatcher: Using Parallel strategy for CreateDraftingPlan("DRAFT_ADMIN",[1029094])
23:33:08.127 Debug [11] Dispatcher: Using Direct strategy for CreateDraftingPlan400
23:33:08.127 Info  [16] TestWorker: ParallelWorker#8 executing CreateDraftingPlan("DRAFT_ADMIN",[1029094])
23:33:08.127 Debug [11] Dispatcher: Using Parallel strategy for CreateDraftingPlan400("DRAFT_ADMIN",[1054392])
23:33:08.127 Debug [11] Dispatcher: Using Direct strategy for CreateDraftingPlan401
23:33:08.127 Info  [12] TestWorker: ParallelWorker#4 executing CreateDraftingPlan400("DRAFT_ADMIN",[1054392])
23:33:08.127 Debug [11] Dispatcher: Using Parallel strategy for CreateDraftingPlan401("NON_DRAFT_USER",[1029118])
23:33:08.127 Info  [18] TestWorker: ParallelWorker#10 executing CreateDraftingPlan401("NON_DRAFT_USER",[1029118])
23:33:08.127 Debug [11] Dispatcher: Using Direct strategy for GetClientUserMetadata
23:33:08.127 Debug [11] Dispatcher: Using Parallel strategy for GetClientUserMetadata("DRAFT_ADMIN",[1029083])
23:33:08.128 Info  [14] TestWorker: ParallelWorker#6 executing GetClientUserMetadata("DRAFT_ADMIN",[1029083])
23:33:08.128 Debug [11] Dispatcher: Using Direct strategy for GetClientUserMetadata401
23:33:08.129 Debug [11] Dispatcher: Using Parallel strategy for GetClientUserMetadata401("NON_DRAFT_USER",[1052366])
23:33:08.129 Info  [10] TestWorker: ParallelWorker#2 executing GetClientUserMetadata401("NON_DRAFT_USER",[1052366])
23:33:08.129 Debug [11] Dispatcher: Using Direct strategy for GetDraftingPlanById
23:33:08.136 Debug [11] Dispatcher: Using Parallel strategy for GetDraftingPlanById("DRAFT_ADMIN",[1029015])
23:33:08.136 Debug [11] Dispatcher: Using Direct strategy for GetDraftingPlanById401
23:33:08.136 Info  [ 9] TestWorker: ParallelWorker#1 executing GetDraftingPlanById("DRAFT_ADMIN",[1029015])
23:33:08.149 Debug [11] Dispatcher: Using Parallel strategy for GetDraftingPlanById401("NON_DRAFT_USER",[1029015])
23:33:08.150 Info  [17] TestWorker: ParallelWorker#9 executing GetDraftingPlanById401("NON_DRAFT_USER",[1029015])
23:33:08.150 Debug [11] Dispatcher: Using Direct strategy for GetDraftingPlanEmployees
23:33:08.153 Debug [11] Dispatcher: Using Parallel strategy for GetDraftingPlanEmployees("DRAFT_ADMIN",[1022088])
23:33:08.153 Debug [11] Dispatcher: Using Direct strategy for GetDraftingPlanEmployees401
23:33:08.153 Debug [11] Dispatcher: Using Parallel strategy for GetDraftingPlanEmployees401("NON_DRAFT_USER",[1022104])
23:33:08.153 Debug [11] Dispatcher: Using Direct strategy for GetDraftingPlans
23:33:08.154 Debug [11] Dispatcher: Using Parallel strategy for GetDraftingPlans("DRAFT_ADMIN",[1028985])
23:33:08.154 Debug [11] Dispatcher: Using Direct strategy for GetDraftingPlans401
23:33:08.154 Debug [11] Dispatcher: Using Parallel strategy for GetDraftingPlans401("NON_DRAFT_USER",[1052390])
23:33:08.154 Debug [11] Dispatcher: Using Direct strategy for GetEmployeesForBoss
23:33:08.154 Debug [11] Dispatcher: Using Parallel strategy for GetEmployeesForBoss("DRAFT_MANAGER",[1054330])
23:33:08.154 Debug [11] Dispatcher: Using Direct strategy for GetEmployeesForBoss400
23:33:08.154 Debug [11] Dispatcher: Using Parallel strategy for GetEmployeesForBoss400("DRAFT_ADMIN",[1054415])
23:33:08.154 Debug [11] Dispatcher: Using Direct strategy for GetEmployeesForBoss401
23:33:08.154 Debug [11] Dispatcher: Using Parallel strategy for GetEmployeesForBoss401("NON_DRAFT_USER",[1054539])
23:33:08.154 Debug [11] Dispatcher: Using Direct strategy for GetEmployeesForBossByPlanUid
23:33:08.154 Debug [11] Dispatcher: Using Parallel strategy for GetEmployeesForBossByPlanUid("DRAFT_ADMIN",[1054459])
23:33:08.154 Debug [11] Dispatcher: Using Direct strategy for GetEmployeesForBossByPlanUid401
23:33:08.154 Debug [11] Dispatcher: Using Parallel strategy for GetEmployeesForBossByPlanUid401("NON_DRAFT_USER",[1054480])
23:33:08.154 Debug [11] Dispatcher: Using Direct strategy for GetEmployeesForBossByPlanUid403
23:33:08.155 Debug [11] Dispatcher: Using Parallel strategy for GetEmployeesForBossByPlanUid403("DRAFT_MANAGER",[1054466])
23:33:08.155 Debug [11] Dispatcher: Using Direct strategy for GetJobsWithPayRanges
23:33:08.155 Debug [11] Dispatcher: Using Parallel strategy for GetJobsWithPayRanges("DRAFT_ADMIN",[1021747])
23:33:08.155 Debug [11] Dispatcher: Using Direct strategy for GetBoss
23:33:08.155 Debug [11] Dispatcher: Using Parallel strategy for GetBoss("DRAFT_ADMIN",[1054428])
23:33:08.155 Debug [11] Dispatcher: Using Direct strategy for GetBoss400
23:33:08.155 Debug [11] Dispatcher: Using Parallel strategy for GetBoss400("DRAFT_ADMIN",[1054448])
23:33:08.155 Debug [11] Dispatcher: Using Direct strategy for GetBoss401
23:33:08.155 Debug [11] Dispatcher: Using Parallel strategy for GetBoss401("NON_DRAFT_USER",[1054430])
23:33:08.155 Debug [11] Dispatcher: Using Direct strategy for QueueDraftingEvent
23:33:08.155 Debug [11] Dispatcher: Using Parallel strategy for QueueDraftingEvent("DRAFT_ADMIN",[1057744])
23:33:08.155 Debug [11] Dispatcher: Using Direct strategy for QueueDraftingEvent401
23:33:08.155 Debug [11] Dispatcher: Using Parallel strategy for QueueDraftingEvent401("NON_DRAFT_USER",[1057745])
23:33:08.156 Debug [11] Dispatcher: Using Direct strategy for UpdateBossEmployees
23:33:08.156 Debug [11] Dispatcher: Using Parallel strategy for UpdateBossEmployees("DRAFT_MANAGER",[1054469])
23:33:08.156 Debug [11] Dispatcher: Using Direct strategy for UpdateBossEmployees500
23:33:08.156 Debug [11] Dispatcher: Using Parallel strategy for UpdateBossEmployees500("DRAFT_MANAGER",[1054473])
23:33:08.156 Info  [11] TestWorker: ParallelWorker#3 executing GetDraftingPlanEmployees("DRAFT_ADMIN",[1022088])
23:38:50.949 Debug [17] Dispatcher: Using Direct strategy for GetDraftingPlanById401 OneTimeTearDown
23:38:50.953 Info  [17] TestWorker: ParallelWorker#9 executing GetDraftingPlanEmployees401("NON_DRAFT_USER",[1022104])
23:38:54.950 Debug [13] Dispatcher: Using Direct strategy for CloseDraftingPlan OneTimeTearDown
23:38:54.950 Info  [13] TestWorker: ParallelWorker#5 executing GetDraftingPlans("DRAFT_ADMIN",[1028985])
23:38:59.018 Debug [16] Dispatcher: Using Direct strategy for CreateDraftingPlan OneTimeTearDown
23:38:59.018 Info  [16] TestWorker: ParallelWorker#8 executing GetDraftingPlans401("NON_DRAFT_USER",[1052390])
23:39:07.287 Debug [10] Dispatcher: Using Direct strategy for GetClientUserMetadata401 OneTimeTearDown
23:39:07.287 Info  [10] TestWorker: ParallelWorker#2 executing GetEmployeesForBoss("DRAFT_MANAGER",[1054330])
23:39:11.265 Debug [ 9] Dispatcher: Using Direct strategy for GetDraftingPlanById OneTimeTearDown
23:39:11.265 Info  [ 9] TestWorker: ParallelWorker#1 executing GetEmployeesForBoss400("DRAFT_ADMIN",[1054415])
23:39:19.391 Debug [18] Dispatcher: Using Direct strategy for CreateDraftingPlan401 OneTimeTearDown
23:39:19.391 Info  [18] TestWorker: ParallelWorker#10 executing GetEmployeesForBoss401("NON_DRAFT_USER",[1054539])
23:39:26.206 Debug [14] Dispatcher: Using Direct strategy for GetClientUserMetadata OneTimeTearDown
23:39:26.208 Info  [14] TestWorker: ParallelWorker#6 executing GetEmployeesForBossByPlanUid("DRAFT_ADMIN",[1054459])
23:39:32.157 Debug [15] Dispatcher: Using Direct strategy for CloseDraftingPlan401 OneTimeTearDown
23:39:32.157 Info  [15] TestWorker: ParallelWorker#7 executing GetEmployeesForBossByPlanUid401("NON_DRAFT_USER",[1054480])
23:39:37.245 Debug [12] Dispatcher: Using Direct strategy for CreateDraftingPlan400 OneTimeTearDown
23:39:37.245 Info  [12] TestWorker: ParallelWorker#4 executing GetEmployeesForBossByPlanUid403("DRAFT_MANAGER",[1054466])
23:39:42.170 Debug [11] Dispatcher: Using Direct strategy for GetDraftingPlanEmployees OneTimeTearDown
23:39:42.170 Info  [11] TestWorker: ParallelWorker#3 executing GetJobsWithPayRanges("DRAFT_ADMIN",[1021747])
23:40:26.819 Debug [ 9] Dispatcher: Using Direct strategy for GetEmployeesForBoss400 OneTimeTearDown
23:40:26.819 Info  [ 9] TestWorker: ParallelWorker#1 executing GetBoss("DRAFT_ADMIN",[1054428])
23:40:32.964 Debug [16] Dispatcher: Using Direct strategy for GetDraftingPlans401 OneTimeTearDown
23:40:32.964 Info  [16] TestWorker: ParallelWorker#8 executing GetBoss400("DRAFT_ADMIN",[1054448])
23:40:38.537 Debug [12] Dispatcher: Using Direct strategy for GetEmployeesForBossByPlanUid403 OneTimeTearDown
23:40:38.539 Info  [12] TestWorker: ParallelWorker#4 executing GetBoss401("NON_DRAFT_USER",[1054430])
23:40:49.746 Debug [14] Dispatcher: Using Direct strategy for GetEmployeesForBossByPlanUid OneTimeTearDown
23:40:49.746 Info  [14] TestWorker: ParallelWorker#6 executing QueueDraftingEvent("DRAFT_ADMIN",[1057744])
23:41:00.657 Debug [13] Dispatcher: Using Direct strategy for GetDraftingPlans OneTimeTearDown
23:41:00.657 Info  [13] TestWorker: ParallelWorker#5 executing QueueDraftingEvent401("NON_DRAFT_USER",[1057745])
23:41:11.731 Debug [18] Dispatcher: Using Direct strategy for GetEmployeesForBoss401 OneTimeTearDown
23:41:11.731 Info  [18] TestWorker: ParallelWorker#10 executing UpdateBossEmployees("DRAFT_MANAGER",[1054469])
23:41:17.306 Debug [15] Dispatcher: Using Direct strategy for GetEmployeesForBossByPlanUid401 OneTimeTearDown
23:41:17.306 Info  [15] TestWorker: ParallelWorker#7 executing UpdateBossEmployees500("DRAFT_MANAGER",[1054473])
23:41:22.983 Debug [10] Dispatcher: Using Direct strategy for GetEmployeesForBoss OneTimeTearDown
23:41:34.026 Debug [17] Dispatcher: Using Direct strategy for GetDraftingPlanEmployees401 OneTimeTearDown
23:41:40.252 Debug [11] Dispatcher: Using Direct strategy for GetJobsWithPayRanges OneTimeTearDown
23:41:58.492 Debug [16] Dispatcher: Using Direct strategy for GetBoss400 OneTimeTearDown
23:42:20.952 Debug [ 9] Dispatcher: Using Direct strategy for GetBoss OneTimeTearDown
23:42:32.179 Debug [12] Dispatcher: Using Direct strategy for GetBoss401 OneTimeTearDown
23:42:37.877 Debug [14] Dispatcher: Using Direct strategy for QueueDraftingEvent OneTimeTearDown
23:42:43.722 Debug [13] Dispatcher: Using Direct strategy for QueueDraftingEvent401 OneTimeTearDown
23:42:49.457 Debug [18] Dispatcher: Using Direct strategy for UpdateBossEmployees OneTimeTearDown
23:43:02.937 Debug [15] Dispatcher: Using Direct strategy for UpdateBossEmployees500 OneTimeTearDown
23:43:02.938 Debug [15] Dispatcher: Using Parallel strategy for DraftingPlanningAPITests OneTimeTearDown
23:43:02.938 Info  [18] TestWorker: ParallelWorker#10 executing DraftingPlanningAPITests OneTimeTearDown
23:43:02.938 Info  [15] WorkShift: Parallel shift ending
23:43:02.938 Debug [18] Dispatcher: Using NonParallel strategy for Tests OneTimeTearDown
23:43:02.938 Debug [15] WorkItemQueue: ParallelQueue.1 pausing
23:43:02.938 Debug [15] WorkItemQueue: ParallelSTAQueue.1 pausing
23:43:02.938 Info  [15] WorkShift: NonParallel shift starting
23:43:02.938 Info  [15] WorkItemQueue: NonParallelQueue.1 starting
23:43:02.938 Info  [ 8] TestWorker: NonParallelWorker executing Tests OneTimeTearDown
23:43:02.938 Info  [18] WorkShift: Parallel shift ending
23:43:02.938 Debug [18] WorkItemQueue: ParallelQueue.1 pausing
23:43:02.938 Debug [18] WorkItemQueue: ParallelSTAQueue.1 pausing
23:43:04.180 Debug [ 8] Dispatcher: Using Direct strategy for DraftingPlanning OneTimeTearDown
23:43:04.180 Debug [ 8] Dispatcher: Using Direct strategy for HR OneTimeTearDown
23:43:04.180 Debug [ 8] Dispatcher: Using Direct strategy for HR.DraftingPlanning.Tests.dll OneTimeTearDown
23:43:04.181 Info  [18] Dispatcher: Restoring Queue State
23:43:04.182 Info  [18] WorkItemQueue: ParallelQueue.0 stopping - 29 WorkItems processed
23:43:04.182 Info  [18] WorkItemQueue: ParallelSTAQueue.0 stopping - 0 WorkItems processed
23:43:04.182 Info  [12] TestWorker: ParallelWorker#4 stopping - 3 WorkItems processed.
23:43:04.182 Info  [14] TestWorker: ParallelWorker#6 stopping - 3 WorkItems processed.
23:43:04.183 Info  [19] TestWorker: ParallelSTAWorker stopping - 0 WorkItems processed.
23:43:04.183 Info  [ 9] TestWorker: ParallelWorker#1 stopping - 3 WorkItems processed.
23:43:04.182 Info  [15] TestWorker: ParallelWorker#7 stopping - 3 WorkItems processed.
23:43:04.183 Info  [10] TestWorker: ParallelWorker#2 stopping - 2 WorkItems processed.
23:43:04.183 Info  [16] TestWorker: ParallelWorker#8 stopping - 3 WorkItems processed.
23:43:04.182 Info  [18] WorkItemQueue: NonParallelQueue.0 stopping - 3 WorkItems processed
23:43:04.186 Info  [18] WorkItemQueue: NonParallelSTAQueue.0 stopping - 0 WorkItems processed
23:43:04.186 Info  [18] TestWorker: ParallelWorker#10 stopping - 4 WorkItems processed.
23:43:04.184 Info  [17] TestWorker: ParallelWorker#9 stopping - 2 WorkItems processed.
23:43:04.182 Info  [13] TestWorker: ParallelWorker#5 stopping - 3 WorkItems processed.
23:43:04.182 Info  [11] TestWorker: ParallelWorker#3 stopping - 3 WorkItems processed.
23:43:04.194 Info  [ 8] WorkShift: NonParallel shift ending
23:43:04.194 Debug [ 8] WorkItemQueue: NonParallelQueue.0 pausing
23:43:04.194 Info  [ 8] WorkItemQueue: ParallelQueue.0 stopping - 29 WorkItems processed
23:43:04.194 Info  [ 8] WorkItemQueue: ParallelSTAQueue.0 stopping - 0 WorkItems processed
23:43:04.194 Info  [ 8] WorkItemQueue: NonParallelQueue.0 stopping - 3 WorkItems processed
23:43:04.194 Info  [ 8] WorkItemQueue: NonParallelSTAQueue.0 stopping - 0 WorkItems processed
23:43:04.194 Info  [ 8] TestWorker: NonParallelWorker stopping - 3 WorkItems processed.

**Comment by CharliePoole** [comment]
The log messsages regarding test discovery indicate that 13 classes were examined and 5 test fixtures were found among them. (See messages at start of log)

Later, we see OneTimeSetUp and OneTimeTearDown being executed for 5 different test fixtures. If you have only one class, then it seems to be a parameterized fixture, which creates 5 different instances. The OneTime tearDown executes for each instance.

Is it possible that the code you are invoking in onetime teardown is forced to wait for availability of a shared resource, such as an output file?

Timing when you run the fixture instances sequentially but the cases in parallel might be instructive.

**Comment by anandbabu787** [comment]
@CharliePoole  you are right. I had to move the initialization of the custom reporting we do to onetimesetup currently it was in setup and being called in parallel for all threads.

After I moved it out, it resolved the issue. Once again thanks for your assistance.
