### ISSUE TITLE
Assert.That is blocking and might lead to deadlock when used with WCF.

### ISSUE THREAD

**Issue by MikiKaufhold** [nunit/nunit#3432]
### Problem 1)
Suppose you are asserting an asynchronous WCF service call - for the sake of simple example just its completion (for complete implementation see [NUnitUsingWCFClientDeadlockReproducer.cs.txt](https://github.com/nunit/nunit/files/3873451/NUnitUsingWCFClientDeadlockReproducer.cs.txt))

```
Assert.That(async () =>
{
  await AsyncCall();
  return true;
}, Is.True);
```
In certain cases this lead to deadlock…

### Analysis 1)
There is a [great article where Alois explains a case of similar WCF deadlock](https://aloiskraus.wordpress.com/2018/07)

> The problem is that WCF runs asynchronous method completions on the WCF channel dispatcher which seems to be single threaded just like a UI application with a message pump.
> …
>  A sync/async mixture of remoted methods will likely cause deadlocks

Interestingly, our WCF service has only Async methods…
However, `Assert.That` ends up with a blocking `Task.Wait()` call and (likely) causes the deadlock.

### Solution 1)
To resolve this we have introduced an async variant for `Assert.That` using `DelayedConstraint` that looks like this:
`public static Task DelayedAsync<T>(Func<Task<T>> actualValueDelegate,
													IResolveConstraint expression,
													int delayInMilliseconds)`
 (for complete implementation see [DelayedAsync.cs.txt](https://github.com/nunit/nunit/files/3873527/DelayedAsync.cs.txt))

### Problem 2) - Considering upgrade of NUnit from 2.6.6 -> 3.11
We are running into the issue generally known as "Catching AssertionException fails tests" #2758 but also mentioned in #2043, #2040, #2007.

### Analysis 2)
As suggested in those threads,
`using (new NUnit.Framework.Internal.TestExecutionContext.IsolatedContext())` in the most inner DelayedAsync call resolves the issue.

However, since catching AssertionExceptions is not recommended practise and  TestExecutionContext is Internal, I am hesitant to adopt this as a final solution.

Instead I would wish for a native awaitable Assert.That that would implement [**async all the way** pattern as recommended by Stephen Cleary](https://docs.microsoft.com/en-us/archive/msdn-magazine/2013/march/async-await-best-practices-in-asynchronous-programming).

Looking forward to your feedback and suggestions.

**Comment by jnm2** [comment]
We mitigate deadlocks for known synchronization contexts, currently just Windows Forms and WPF message loops. https://github.com/nunit/nunit/issues/2917 tracks making this extensible.

Does WCF have a synchronization context and a MessageLoop.Run() and MessageLoop.Exit() equivalent? We might be able to detect it and do everything in the box.

> Instead I would wish for a native awaitable Assert.That that would implement async all the way pattern as recommended by Stephen Cleary.

I'm with you 110%. https://github.com/nunit/nunit/issues/2843 tracks this.

**Comment by OsirisTerje** [comment]
@uecasm @MikiKaufhold Can you guys confirm https://www.myget.org/feed/nunit/package/nuget/NUnit/4.0.0-dev-07733 is working for you?

**Comment by siprbaum** [comment]
Cc @z002Holpp, who I know was also affected by this.

**Comment by OsirisTerje** [comment]
This has not been confirmed by any of the reporters, so I'll close this issue with the assumption it works. The PR has been merged.
