### ISSUE TITLE
[Question] How to set property value of [Test] to a variable?

### ISSUE THREAD

**Issue by tindecken** [nunit/nunit#3439]
Hi all,
Please take a look and help me on this case

I have a Class with field RunId, I would like to set this field as a property

![image](https://user-images.githubusercontent.com/4727197/70228097-5954af00-1786-11ea-9cf6-df930add7af5.png)

I need to transfer this RunId to every [SetUp] of each [Test]

Many thanks.

**Comment by CharliePoole** [comment]
Not clear why you want it to be a property of each test case. The static RunId is available in every test (including SetUp) simply by referring to it.

**Comment by tindecken** [comment]
Hi @CharliePoole,
Thank you for the response, sorry that my question is not clearly yet
For the future, the `Class1.cs` will be generated automatically. So I don't want to access this class to get RunId value.

I do a work around with the `TestExecutionContext.CurrentContext.CurrentTest.Properties.Add("RunId", RunId);`
then, in `SetupAndTearDown.cs`, i can take it with `string RunId = TestExecutionContext.CurrentContext.CurrentTest.Parent.Properties.Get("RunId").ToString();`

![image](https://user-images.githubusercontent.com/4727197/70289331-fd7e3a80-1806-11ea-941c-8ef90a7f057a.png)

![image](https://user-images.githubusercontent.com/4727197/70289367-171f8200-1807-11ea-85e4-266eeca8ca68.png)

I'm not sure it's the best way, but currently, it works.
Thanks.

**Comment by CharliePoole** [comment]
Only thing, your generated class is under your control but internal NUnit details are not. Properties of test are presented to you as read-only in the TesrContext. Your code is taking advantage of an undocumented implementation detail to write a property.

**Comment by tindecken** [comment]
Hi @CharliePoole , after few days of trying some approaches, I've checked that Nunit has custom attributes and it's very useful, match with my needing.

![image](https://user-images.githubusercontent.com/4727197/71009267-84db8000-211c-11ea-9120-261d9fb00ee1.png)

![image](https://user-images.githubusercontent.com/4727197/71009284-8a38ca80-211c-11ea-9838-0b92d29b5fbd.png)

Thank you very much for the support, I thinks I should close this item.
