### ISSUE TITLE
Is there a way to not include some scenarios in parallel scope when using NUnit + SpecFlow?

### ISSUE THREAD

**Issue by vyakaa** [nunit/nunit#3440]
I am using NUnit + SpecFlow.
Parallel tests execution is implemented via AssemblyInfo using 
```
[assembly: Parallelizable(ParallelScope.Fixtures)]
[assembly: LevelOfParallelism(5)]
```
and everything is perfect, EXCEPT
I need some tests to be excluded from parallel scope.
In pure NUnit it was like
```
[TestFixture]
[Parallelizable(ParallelScope.None)]
public class SomeTestClass
```
Is there some option to tag scenarios in .feature files so that 
`[NUnit.Framework.Parallelizable(NUnit.Framework.ParallelScope.None)]`
is added to .feature.cs file after build solution?

**Comment by CharliePoole** [comment]
If I understand correctly (I haven't used SpecFlow myself), each `.feature` file generates a test fixture.

So the question boils down to "How can I make SpecFlow include a `Parallelizable` attribute on a particular fixture. That seems to be more of a SpecFlow than an NUnit question.

That said, we'd love to know the answer, because it's a question that gets asked of us a lot. If you are able to get an answer elsewhere, I hope you'll post it here as well!

**Comment by vyakaa** [comment]
Yes exactly, it`s about converting SpecFlow tags to test fixture to include NUnit attributes. Didn`t find an answer yet, Gherkin documentation on tags doesn`t give any idea. I will comment here how I solved this issue because in current project changing tool is not my responsibility.

**Comment by CharliePoole** [comment]
FWIW, some commercial projects cooperate well with open source teams, others, not so much. :frowning_woman:

**Comment by Dreamescaper** [comment]
Haven't worked with with SpecFlow for quite a while, so might be wrong, but as far as I remember it generates partial class definition. If that's the case, you can add another partial definition in separate file, and define attribute there.

Still, I agree that this issue should go to SpecFlow repository, not here.

**Comment by vyakaa** [comment]
Thank you @Dreamescaper for idea! 
Really, with `partial` classes generated by SpecFlow (`.feature.cs` per each feature file) it gives you possibility to add another attribute for test fixture in separate file with `partial` classes for fixtures you need to exclude from parallel scope defined in `AssemblyInfo`.
This is how I made it:

```
namespace Tests
{
    [NUnit.Framework.Parallelizable(NUnit.Framework.ParallelScope.None)]
    public partial class FeatureOne
    { }

    [NUnit.Framework.Parallelizable(NUnit.Framework.ParallelScope.None)]
    public partial class FeatureTwo
    { }
}
```
