### ISSUE TITLE
Additional Assertion is added by NUnit in case of reflection is being used inside the test

### ISSUE THREAD

**Issue by ashishdawale20** [nunit/nunit#3445]
**Case 1: Without reflection**

In this case, even if we are throwing the exception in catch the NUnit only show's that there was one assert.

```
[Test]
public void Test1()
{
   try
   {
     Method()
   }
   catch(Exception ex)
   { 
     throw;
   }
}
public void Method()
{
Assert.Fail("Assertion Test");
}
[TearDown]
public void TearDown() {}
```

 
**Result:** 

 Error : Assertion Test:
at NunitTests.Class1.KuchNai() in C:\Users\**\Documents\Visual Studio 2015\Projects\SameMessageTest\NunitTests\Class1.cs:line 28
at NunitTests.Class1.Test1() in C:\Users\**\Documents\Visual Studio 2015\Projects\SameMessageTest\NunitTests\Class1.cs:line 18

 

**Case 2: With Reflection**

In this case, we are using reflection inside the test, if there is failure/Assert inside the method getting called using reflection, Nunit shows that there were two assertions as shown in the result below.

```
[Test]
public void Test1()
{
   try
   {
 //Calling the method using reflection
 Type magicType = Type.GetType("NunitTests.Class1");
 ConstructorInfo magicConstructor = magicType.GetConstructor(Type.EmptyTypes);
 object magicClassObject = magicConstructor.Invoke(new object[] { });
 MethodInfo magicMethod = magicType.GetMethod("Method");
 object magicValue = magicMethod.Invoke(magicClassObject, new object[] { });
   }
   catch(Exception ex)
   { 
     throw;
   }
}
public void Method()
{
Assert.Fail("Assertion Test");
}
[TearDown]
public void TearDown() {}
```

 **Result**

1-1) Error : NunitTests.Class1.Test1
Error Assert
at NunitTests.Class1.KuchNai() in C:\Users\***\Documents\Visual Studio 2015\Projects\**\**\Class1.cs:line 38

1-2) Error : NunitTests.Class1.Test1
System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
----> NUnit.Framework.AssertionException : Error Assert
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
at NunitTests.Class1.Test1() in C:\Users\***\Documents\Visual Studio 2015\Projects\**\**\Class1.cs:line 32

**Comment by mikkelbu** [comment]
Thanks for a nice repo @ashishdawale20. The code can be simplified a little as we have the same behaviour without the catch
```csharp
using NUnit.Framework;
using System;
using System.Reflection;

namespace AssertsAndReflection
{
    public class WithoutReflection
    {
        [Test]
        public void Test1()
        {
            Method();
        }

        public void Method()
        {
            Assert.Fail("Assertion Test");
        }
    }

    public class WithReflection
    {
        [Test]
        public void Test1()
        {
            //Calling the method using reflection
            Type magicType = Type.GetType("AssertsAndReflection.WithReflection");
            ConstructorInfo magicConstructor = magicType.GetConstructor(Type.EmptyTypes);
            object magicClassObject = magicConstructor.Invoke(new object[] { });
            MethodInfo magicMethod = magicType.GetMethod("Method");
            object magicValue = magicMethod.Invoke(magicClassObject, new object[] { });
        }

        public void Method()
        {
            Assert.Fail("Assertion Test");
        }
    }
}
```
The one without reflection is presented as a Failure - reported by the console
`1) Failed : AssertsAndReflection.WithoutReflection.Test1`
whereas the two reports by the reflection are presented as Errors - reported by the console
`2-1) Error : AssertsAndReflection.WithReflection.Test1` and
`2-2) Error : AssertsAndReflection.WithReflection.Test1`.

I don't know much about this area of NUnit, but I'm guessing that the code responsible for reporting the failures/errors (and also unwrapping the exceptions) might contain a bug in this regard.

**Comment by ashishdawale20** [comment]
@mikkelbu Please assign this to me. I will work on fixing this issue.

**Comment by mikkelbu** [comment]
@ashishdawale2 I've assigned the issue to you. Please ask if you have any questions.

**Comment by ashishdawale20** [comment]
@mikkelbu - Reflection code throws TargetInvocationException which has an "inner exception" which is the actual exception. 
Nunit also uses a reflection to call the unit tests that's why it handles the TargetInvocationException by throwing the ex.innerexception. 

But in this case, we have TargetInvocationException inside TargetInvocationException and inner exception of which has the actual exception.

I can fix this issue with below change in the TestResult.cs file
![image](https://user-images.githubusercontent.com/43884208/71667522-72ec1500-2d8b-11ea-817e-9d9a00a7e407.png)

This fix works just fine. But with this, we will need to change the Assert.That, Assert.Throws behaviors also.

Like when I wanted to write the unit tests for this by using Assert.Throws - This is still throwing the TargetInvocationException instead of AssertException.

Please suggest how to proceed with this fix. Should we change code for Assert.That and Assert.Throws and any other code that might affect by this change.

**Comment by CharliePoole** [comment]
I'm not sure this is really a bug... or at least not the bug we think it is. Since your test code is throwing a `TargetInvocationException`, we __should__ report that. Ignoring it seems like an error because there may be some cases where that would allow a silent failure.

I __would__ prefer to see just one error, but it would be best if it included both exceptions. However, showing the two of them separately is quite easy to understand... at least if you are using Reflection, you should expect to see a `TargetInvocationException` sometimes.

**Comment by ashishdawale20** [comment]
I agree. We can close this ticket.

**Comment by mikkelbu** [comment]
Ok. I'm closing this issue. Thanks for reporting the issue and also looking into it @ashishdawale20 👍
