### ISSUE TITLE
Is.EqualTo(...).Using(StructuralComparisons.StructuralEqualityComparer or StructuralComparer) not working

### ISSUE THREAD

**Issue by marklam** [nunit/nunit#3447]
[`System.Collections.Immutable.ImmutableArray`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutablearray-1?view=netcore-3.1) implements both reference equality and structural equality via [`IStructuralEquatable`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.istructuralequatable?view=netcore-3.1).

I want to be able to check two arrays for structural equality, but only some of the overloads of [`EqualConstraint.Using`](https://github.com/nunit/nunit/blob/cefc0c3a86c065daa4130aa255b1384db51b2b08/src/NUnitFramework/framework/Constraints/EqualConstraint.cs#L308) work as expected.

The two overloads that take `IEqualityComparer` or `IComparer` don't use the correct comparison, whereas the versions that take delegates do.

The attached code (which was built with packages **NUnit 3.12.0** and **System.Collections.Immutable 1.7.0** fails the last two tests.

```C#
using System;
using System.Collections;
using System.Collections.Immutable;
using NUnit.Framework;

namespace NUnitStructural
{
    [TestFixture]
    public class Test
    {
        [Test]
        public void ImmutableArrayNotReferenceEquality()
        {
            var x = ImmutableArray.Create(1, 2, 3);
            var y = ImmutableArray.Create(1, 2, 3);

            Assert.That(x != y);
        }

        [Test]
        public void ImmutableArrayWithStructuralEqualityComparison()
        {
            var x = ImmutableArray.Create(1, 2, 3);
            var y = ImmutableArray.Create(1, 2, 3);

            Comparison<ImmutableArray<int>> comparison = (a, b) => StructuralComparisons.StructuralComparer.Compare(a, b);
            Assert.That(x, Is.EqualTo(y).Using(comparison));
        }

        [Test]
        public void ImmutableArrayWithStructuralEqualityComparerEquals()
        {
            var x = ImmutableArray.Create(1, 2, 3);
            var y = ImmutableArray.Create(1, 2, 3);

            var del = new Func<ImmutableArray<int>, ImmutableArray<int>, bool>((a, b) => StructuralComparisons.StructuralEqualityComparer.Equals(a, b));
            Assert.That(x, Is.EqualTo(y).Using<ImmutableArray<int>>(del));
        }

        [Test]
        public void ImmutableArrayWithStructuralComparerEquals()
        {
            var x = ImmutableArray.Create(1, 2, 3);
            var y = ImmutableArray.Create(1, 2, 3);

            var del = new Func<ImmutableArray<int>, ImmutableArray<int>, bool>((a, b) => StructuralComparisons.StructuralComparer.Compare(a, b) == 0);
            Assert.That(x, Is.EqualTo(y).Using<ImmutableArray<int>>(del));
        }

        [Test]
        public void ImmutableArrayWithStructuralEqualityComparer()
        {
            var x = ImmutableArray.Create(1, 2, 3);
            var y = ImmutableArray.Create(1, 2, 3);

            Assert.That(x, Is.EqualTo(y).Using(StructuralComparisons.StructuralEqualityComparer));
        }

        [Test]
        public void ImmutableArrayWithStructuralComparer()
        {
            var x = ImmutableArray.Create(1, 2, 3);
            var y = ImmutableArray.Create(1, 2, 3);

            Assert.That(x, Is.EqualTo(y).Using(StructuralComparisons.StructuralComparer));
        }
    }
}

```

**Comment by mikkelbu** [comment]
I can confirm the issue. Looking at the code I guess that the problem is that `EqualityAdapter` only handles strings and the derived classes `EqualityComparerAdapter` and `ComparerAdapter` used in the last two cases does not override `CanCompare`, so the code does not think that the supplied method can be used.
https://github.com/nunit/nunit/blob/15810166a4bc9ee9c481c1f1237668812042a845/src/NUnitFramework/framework/Constraints/EqualityAdapter.cs#L50-L59

**Comment by CharliePoole** [comment]
It handles all classes __except__ `IEnumerable`s, unless the `IEnumerable` is a string. That's because the intent is to pass the equality test down to each item returned by the `IEnumerable`.

**Comment by stevenaw** [comment]
I just ran into this myself. I'm wondering if it's related specifically to `ImmutableArray` when using a non-predicate comparer. In the following example, the test fails for `ImmutableArray` but passes `ImmutableList` (`ImmutableStack` and `ImmutableQueue` also pass):

```csharp
        // Fails
        [Test]
        public void ImmutableArrayEquals()
        {
            var x = ImmutableArray.Create(1, 2, 3);
            var y = ImmutableArray.Create(1, 2, 3);

            Assert.That(x, Is.EqualTo(y));
        }

        // Passes
        [Test]
        public void ImmutableListEquals()
        {
            var x = ImmutableList.Create(1, 2, 3);
            var y = ImmutableList.Create(1, 2, 3);

            Assert.That(x, Is.EqualTo(y));
        }
```
