### ISSUE TITLE
Pre-Filtering in NUnitLite has problems

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#3454]
There appears to be an issue with the pre-filtering in NunitLite.

If there is a a namespace a.b which contains a SetupFixture, and a namespace a.b.c which has a test method a.b.c.TestMethod, and only the test a.b.c.TestMethod is specified, the setup fixture's OneTimeSetup and OneTimeTearDown methods are never run. 

Apparently, the pre-filtering excludes the a.b namespace from consideration.

It would seem that pre-filtering should examine all parent namespaces for a SetupFixture, even if tests in those namespaces are excluded by the pre-filtering.

Maybe there needs to be a simple way to turn pre-filtering off entirely?

**Comment by CharliePoole** [comment]
This sounds familiar. Has it come up before?

**Comment by CharliePoole** [comment]
Ah! It's #3356, but that was fixed and closed by changing the VS adapter - eliminating pre-filtering as a default. So the issue was never dealt with in nunitlite.

As a workaround, pass in a pre-filter that always succeeds, rather than taking the default.

**Comment by oznetmaster** [comment]
However #3356 really did not fix the problem, only eliminated the trigger.

Could this be solved by simply searching the entire test assembly for classes with the SetupFixture attribute, and automatically adding them to the pre-filter?

**Comment by oznetmaster** [comment]
I fixed this problem in my CF version as above.

In DefaultTestAssemblyBuilder.

```
		private void AddSetupFixturesToPreFilter (Assembly assembly)
			{
			foreach (Type type in assembly.GetTypes ())
				{
				if (type.IsClass && type.HasAttribute<SetUpFixtureAttribute> (false))
					_filter.Add (type.FullName);
				}
			}
```

and

```
				AddSetupFixturesToPreFilter (assembly);
```
just before
```
				var fixtures = GetFixtures (assembly);
```

I am not setup to modify the release code, so someone else will have to do this if it is desired.

**Comment by CharliePoole** [comment]
I think that will run all setup fixtures in the discovery phase, not just those that relate to the selected tests.

**Comment by mikkelbu** [comment]
This issue is also related to #3399

**Comment by NN---** [comment]
Still an issue with latest NUnitLite.

**Comment by rprouse** [comment]
Resolved by @3679
