### ISSUE TITLE
Add DefaultConstraint

### ISSUE THREAD

**Issue by Dreamescaper** [nunit/nunit#3457]
Sometimes it is needed to verify value type against default value. 
Common use case - verify that value in rest response is not empty, e.g. Guid (not empty) or enums (not Undefined value).

Current alternative - using EqualConstraint (e.g. `Is.Not.EqualTo(Guid.Empty)`, `Is.Not.EqualTo(default(MyEnumTypeName))`), which is not always convenient.

Details:
1. If actual is non-nullable value type - should pass if `actual == default`.

2. If actual is nullable value type - should pass if `actual` is equal to default value of underlying type, so the following code could be possible:
```
MyValueType? actual = ...;
Assert.That(actual, Is.Not.Null & Is.Not.Default);
```

Open question - what the expected behavior if nullable `actual` is null? Technically it is default value for nullable value type, but I think would make sense to fail it in this case, i.e. only account for underlying type default value.

3. Not sure about the behavior for reference types. Not sure it should be allowed at all. Another option - allow (passing when null), and provide roslyn analyzer with warning if used against reference type.

**Comment by rprouse** [comment]
I think this is a decent idea. @nunit/framework-team thoughts?

> Not sure about the behavior for reference types. Not sure it should be allowed at all.

Since the default value for a reference type is `null`, would could just treat it the same as the null constraint.

**Comment by stevenaw** [comment]
I really like this idea.

As far as expected behaviour, if I came across an this API without documentation I'd probably think of this as syntactic sugar for a comparison to `default(T)`. Based on that, I agree with @rprouse on point 3 about reference types being null, since `default(T) == null` where T is a reference type.

For point 2, I'd probably be surprised if `Nullable<int>` was treated as equal to 0, since `default(Nullable<int>)` evaluates to null. I think an uninitialized variable of type `Nullable<int>` also evaluates to null, so to have a 0 value would it to be explicitly set. I can see special casing a comparison of the underlying type being convenient for some cases, but I could see it causing false negatives in others.

**Comment by jnm2** [comment]
It's not possible to pass an instance of type `Nullable<T>` because the NUnit API only takes `object` instances. When you convert `Nullable<T>` to `object`, what you get is either `(object)null` or a boxed `T` value.

**Comment by jnm2** [comment]
Oops, I'm sorry. I was thinking of `Is.EqualTo(object)`, but `Assert.That` is generic and does not box to `object`.

I agree that I'd expect `Assert.That<T>(x, Is.Default)` to evaluate `x.Equals(default(T))` the way C# would, whether `T` is `int` or `int?`.

**Comment by stevenaw** [comment]
Given the edge cases around `ImmutableArray<T>` in #3772 I'd like to ask if there's any further thoughts on this.
`default(ImmutableArray<T>)` is unfortunately neither null (it's a struct) nor empty (it's uninitialized and throws when enumerated against)

**Comment by jnm2** [comment]
I think it would be a useful constraint to add. It is synonymous with (or an extrapolation of) `Is.Zero` since 'default' in .NET means zeroed memory, but I would prefer to use the syntax `Is.Default` for anything non-numeric.

**Comment by jnm2** [comment]
I would implement it using `System.Runtime.CompilerServices.RuntimeHelpers.Equals(actual, default(T));` to bypass any custom equality implementation on the struct which might legitimately throw for a default instance and which would also not as accurately answer the question "is this default memory."

**Comment by Dreamescaper** [comment]
I'll work on this one (unless someone else is planning to).

**Comment by Dreamescaper** [comment]
I'm wondering, what should be the behavior for boxed values?
```csharp
object a = 0;
Assert.That(a, Is.Default);
```

What is the expected behavior for that code, should it pass (since 0 is `default(int)`) or fail (since 0 is not `default(object)`).

I'm leaning towards the first option, but nullable value types will require special handling.

What do you think?

**Comment by jnm2** [comment]
I think it should fail too.

**Comment by Melandel** [comment]
Hello,

I would be interested in using the `Is.Default` but have noticed it was not available in version `3.13.3`, looking at my compiler's feedback and the package's source code [Asset](https://github.com/nunit/nunit/archive/refs/tags/v3.13.3.zip).

Seeing the issue being `closed`, I suspect I am lacking knowledge about what gets or doesn't get released.

Is the absence of the constraint `Is.Default` expected in the release `3.13.3` ?

**Comment by mikkelbu** [comment]
@Melandel You can use the milestone to determine the release. This issue was targeting the version 4.0 release, so you cannot use it in 3.13.X.

**Comment by Melandel** [comment]
Oh, right!

Thanks for the information :)
