### ISSUE TITLE
Is.GreaterThanOrEqualTo is incorrect for hyphenated strings.

### ISSUE THREAD

**Issue by jbosse** [nunit/nunit#3459]
The following assertions fail when they should pass:
```
Assert.That("ALL-STAR", Is.LessThanOrEqualTo("ALLSTAR"));
Assert.That("ALLSTAR", Is.GreaterThanOrEqualTo("ALL-STAR"));
```

**Comment by Dreamescaper** [comment]
Why do you expect it to pass?

**Comment by jbosse** [comment]
I would expect it because that's how I expect it alphabetically, and how it works in other languages. But yes I agree that since `.CompareTo` is returning 1 then the problem is not with NUnit.

**Comment by jbosse** [comment]
@Dreamescaper maybe its me but I would expected these to all be -1
https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYDMACA3gWAChsTsN08jTrsAiAWloDoBhAewFsAHAQzAFMAKmwAUtAMq0AlEwCSUAM5d+AY2AipAbio0StAIIAZQ9nGD9AJWbtufIaIPGzl6XMXK1G7cV10jh+mcrVk5eAWExfyDXeSVVdS0dEgBfImSgA=

**Comment by jbosse** [comment]
I have been away from C# for a hot minute. Re-entry has been difficult.
