### ISSUE TITLE
How to customize NUnit TimeOut message : 'Test exceeded Timeout value of.....' (in C#)

### ISSUE THREAD

**Issue by HP83DS** [nunit/nunit#3460]
On Timeout we get message like "Test exceeded Timeout value of....."
There is a lot of value knowing at which point Time Out happened.
Makes it easier to get to the origin of the failure.
Please let me know if there is a way to do this.
----------------------------------------------------
**I am looking for a way where either N Unit does this or allows me to customize this message**

**Comment by mikkelbu** [comment]
If you search for "Test exceeded Timeout" in this repository then the first hit 
https://github.com/nunit/nunit/search?q=%22Test+exceeded+Timeout%22&unscoped_q=%22Test+exceeded+Timeout%22 is where the logic is implemented. Currently, it is not possible to customize the message, but it should be associated with a test, so you should know the failing test (I've not tested this, so this is from memory).

So if you need to extend or change the message, then the only solution now is to make your own implementation of a `TimeoutAttribute` (you can probably reuse most of the existing code).

**Comment by rprouse** [comment]
Closing as a question.
