### ISSUE TITLE
Test passes despite exception when passed assertion is recorded in teardown

### ISSUE THREAD

**Issue by grzesiek-galezowski** [nunit/nunit#3463]
From the two tests below, `Test` passes and `Test2` fails. I would expect both tests to fail as both end with exception.

```csharp
[Test]
public void Test1()
{
    throw new Exception();
}

[Test]
public void Test2()
{
    Assert.Fail();
}

[TearDown]
public void TearDown()
{
    TestExecutionContext.CurrentContext.CurrentResult.RecordAssertion(AssertionStatus.Passed, "A");
}
```

**Comment by CharliePoole** [comment]
Can you explain why you want to do what you are doing?

I ask because otherwise your question translates (to me) as "If I mess with the internal workings of NUnit, something breaks!" :smiley:

If we understand what you want to accomplish, perhaps we can figure out a way to do it that avoids the `Internal` namespace.

**Comment by grzesiek-galezowski** [comment]
Thank you, I was not aware that this was the internal stuff. Should have looked better at the namespaces.

The report has more to do with what I wanted to avoid. Typically, I use FluentAssertions together with NUnit and these assertions throw exceptions when failing. For a reason I cannot explain, someone in my team put the `TestExecutionContext.CurrentContext.CurrentResult.RecordAssertion(AssertionStatus.Passed, ...);` call in a method that was called from a TearDown, instantly turning all my tests in a class into false positives. Tracking down the issue took me some time, especially that the same call put at the end of test seemed to work fine and I was like "how would reporting a passed assertion make the whole test pass?".

Still, given your remark that this namespace is clearly marked as internal, I understand if you decide to not address this and reject the issue.

**Comment by CharliePoole** [comment]
I don't understand the specific error either. Recording a passed assertion should have no impact on the test overall result. That is, if other assertions failed, then it should continue to fail. However, in the normal course of NUnit execution, I don't think passed assertions are ever recorded, so this code is doing something that doesn't normally happen and isn't tested.

I'll leave it to more active team members to decide what they want to do with the issue as a whole.

**Comment by rprouse** [comment]
As this is not intended for public use, I am going to close this as a won't fix.
