### ISSUE TITLE
EquatablesComparer can return true when default Equals method returns false

### ISSUE THREAD

**Issue by tombogle** [nunit/nunit#3469]
In switching some of our assemblies to use Nunit 3.12. I have a few new test failures that are the result of changes in the way Nunit implements AreEqual/AreNotEqual. In the underlying implementation, it goes through a long list of comparers, one of which is EquatablesComparer. We have some objects that implement IEquatable<IPalasoDataObjectProperty>. We have an abstract class
`public abstract class CloneableTests<T, TClone> where T : ICloneable<TClone>`
For the concrete case of
`ClonableTests<IPalasoDataObjectProperty, IPalasoDataObjectProperty>`
one of the text cases has Assert.AreNotEqual(a, b), where a and b are both of type IPalasoDataObjectProperty.
Stepping through the implementation of AreNotEqual, I see that eventually it gets to the list of comparers and when it asks the EquatablesComparar if the two objects are equal, it returns true. This is because it explicitly invokes an implementation of Equals based on the two objects being IEquatable<IPalasoDataObjectProperty>. However, IPalasoDataObjectProperty implements Equals in such a way that it returns false for these two objects.
I can't tell if this is a bug in NUnit or a deficiency in our code. In one sense, it seems it could be argued that any version of Equals that can validly apply to two objects should return the same result. On the other hand, it also seems fair to say NUnit should use the same version of Equals that would normally be applied to two objects, rather than using reflection to select a different version of Equals.
For now, I have worked around this by changing the test to
`Assert.IsFalse(a.Equals(b));`
If you think the current behavior of NUnit is correct, I will kick this issue back to the developers who know these classes better on our end to see if they can improve them so that the Equals implementation based on the IEquatable interface can see the distinction that our Equals method detects. Otherwise, if you think this may be a deficiency in NUnit, I can try to boil things down to a concrete example.

**Comment by CharliePoole** [comment]
Just a side comment here... I don't know whether this is a bug in NUnit or not...

"...NUnit should use the same version of Equals that would normally be applied to two objects, rather than using reflection to select a different version of Equals."

Unfortunately, NUnit could only do that by using __even more reflection__ to figure out what version would _normally_ be used. By the time we are down in that level of code, we are dealing with two objects and nothing happens without our making it happen. :cry: 

One day I want to rewrite all this to be type-based and type-safe!

**Comment by rprouse** [comment]
> One day I want to rewrite all this to be type-based and type-safe!

I'll second that and have tried to do that by introducing generic overrides, but it ended up being a huge rabbit hole trying to maintain backwards compatibility. 🙄

**Comment by rprouse** [comment]
@tombogle I am going to close this issue. You have a workaround and there are arguments that it should work both ways depending on your point of view.
