### ISSUE TITLE
Our XML comments are using <code> (block element) instead of <c> (inline element)

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#3475]
Example:

https://github.com/nunit/nunit/blob/30df2d13c0f67eeb6b3dc7f56eebd7c5cfb5c7de/src/NUnitFramework/framework/Assert.Conditions.cs#L218-L222

Visual Studio has recently begun taking the XML comment formatting tags seriously, so it may make a difference.

I would recommend that we add the design-time tool https://www.nuget.org/packages/DotNetAnalyzers.DocumentationAnalyzers to our Directory.Build.props and follow all its prompts. It's been awesome in every project where I've seen it. I know it catches this particular case.

**Comment by Parshudar** [comment]
@jnm2  Hi. I would like to start working on this and was wondering if it could be assigned to me. This would be my first contribution and I can't wait to get started.

**Comment by jnm2** [comment]
@Parshudar Welcome, thanks for offering! I assigned you. Let us know if we can help!

**Comment by jnm2** [comment]
@Parshudar If you could use a hand, just let us know!

**Comment by IrisClasson** [comment]
@Parshudar are you working on this? I'd love to help or take ownership of the issue if you are buys!

**Comment by jnm2** [comment]
@IrisClasson We haven't heard from @Parshudar since February, so I think it's safe to give you ownership. Is that alright with you?

**Comment by rprouse** [comment]
I've reassigned to you @IrisClasson

**Comment by IrisClasson** [comment]
Thank you @rprouse I'll get it done today!
