### ISSUE TITLE
Running tests in parallel

### ISSUE THREAD

**Issue by asafweiss** [nunit/nunit#3478]
I couldn't find anywhere a detailed explanation regarding the different scopes of parallel test execution.

If I mark a test class as **Parallelizable** on the **children level**, what does it mean exactly?
Do the tests run in a different process or just on different threads?
Will the **'oneTimeSetup'** methods run once, and when it's over the execution will commence?
Do the tests run on different instances of the class?

I need to understand all of these in order to plan my project's parallel execution.

Regards,

Asaf.

**Comment by CharliePoole** [comment]
Have you read the docs? If not, start with these pages:

https://github.com/nunit/docs/wiki/Framework-Parallel-Test-Execution
https://github.com/nunit/docs/wiki/Engine-Parallel-Test-Execution

Framework parallel execution uses threads and applies within a single assembly. Based on your question, it's probably what you want. `OneTimeSetUp` methods run once per test run and the individual tests begin (possibly in parallel) after it completes as you would expect. (Note that `SetUp` is considered part of the individual test) In NUnit (parallel or not) all tests use the same instance of the class to which they belong.

Engine parallel execution uses processes to run tests in different assemblies. You can limit the number of active processes if you like.

**Comment by rprouse** [comment]
Closing as a question
