### ISSUE TITLE
how to attain TestResults.XML file when running tests via NUnit.Engine c# project?

### ISSUE THREAD

**Issue by JoeConroy93** [nunit/nunit#3480]
Hi, 

I have a C# API project and have some GET/POST methods utilising the NUnit.Engine to Explore and Run my Nunit tests, the code is working fine however i am struggling to attain the results output in the format that the GUI or Console provides? i am using;

```
"XmlNode result = runner.Run(null, Myfilter);"
```

i also tried;

```
TestEngineResult Result = new TestEngineResult(xmlText).Aggregate("test-run", "ID", "Payments Regression.dll", PaymentsDLL);
```
but the content of these output cannot be parsed into Living Reports through PicklesCommandLine like i am able to do when the test is executed via Console or GUI.

sorry if i have incorrectly placed this query, its my first time here. 

any help greatly appreciated.

thanks & Regards

**Comment by rprouse** [comment]
This belongs more in the Console/Engine project. See the lines starting here, https://github.com/nunit/nunit-console/blob/8b2eda8b421a0b52bde682a67912ee3974e8cf50/src/NUnitConsole/nunit3-console/ConsoleRunner.cs#L227

I am going to close this as a question. If this doesn't help, let us know.
