### ISSUE TITLE
Support explicit generic type arguments for Tests/Fixtures

### ISSUE THREAD

**Issue by damageboy** [nunit/nunit#3504]
When looking into how NUnit supports generic in tests there is something left to be desired.

Namely, what I think is missing the most, is the ability to specific generic type arguments explicitly at the fixture or the individual test level.

Here is a sample of how this is done in BenchmarkDotNet:
https://benchmarkdotnet.org/articles/samples/IntroGenericTypeArguments.html:

```csharp
using System;
using BenchmarkDotNet.Attributes;

namespace BenchmarkDotNet.Samples
{
    [GenericTypeArguments(typeof(int))]
    [GenericTypeArguments(typeof(char))]
    public class IntroGenericTypeArguments<T>
    {
        [Benchmark] public T Create() => Activator.CreateInstance<T>();
    }
}
```

I think that the ability to provide type arguments in the way is invaluable, and intorduces a clean way the enables developers to write simpler code when testing for generic classes

I think that providing a direct type argument like this for NUnit is desirable.

**Comment by mikkelbu** [comment]
This look much like the existing functionality for generic Testfixtures - https://github.com/nunit/docs/wiki/TestFixture-Attribute#example-2. Can you give an example on what you want to do that the existing functionality does not support.

**Comment by damageboy** [comment]
Thanks!
This was exactly what I needed.
I have no idea how I did find this while googling for generic type arguments for tests...

**Comment by mikkelbu** [comment]
No problem. Just glad that you could use the functionality 😄.
