### ISSUE TITLE
No result xml found even if I set --results-directory value

### ISSUE THREAD

**Issue by madhusameena** [nunit/nunit#3511]
I am using .Net core and NUnit console runner with version "3.11.1"

I set --results-directory value -> I see directory is generated
But I dont see any xml files in it.

**Comment by mikkelbu** [comment]
@madhusameena You'll need to provide some more information. The NUnit console runner does not support .NET Core yet, so how are you calling the console and which output does it provide (to the screen and e.g. to the logs - you can set `--trace=Verbose` for debugging output in trace-files).

**Comment by madhusameena** [comment]
I am using dotnet test command to run nunit tests for .net Core
link - https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test

Please find the command I used
"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test C:\MySample\MySample.UnitTest.csproj --configuration Release --no-build --no-restore --output C:\MySample\bin\AnyCPU\Release --results-directory C:\MySample\TestResult.UnitTest.AnyCPU.Release" -targetdir:C:\MySample\bin\AnyCPU\Release -excludebyattribute:System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute;System.Runtime.CompilerServices.CompilerGeneratedAttribute;System.CodeDom.Compiler.GeneratedCodeAttribute -filter:"+[UploadData.Service]* +[UploadData.Api]* +[ManageJobsStatus]*" -oldStyle -output:C:\MySample\Coverage.MySample.UnitTestAnyCPU.Release.xml -threshold:100 -register:Path64 -returntargetcode:0

I am using --results-directory to get results - But I dont see any result files

Don't know is this issue with NUnit - Looking forward to get some update.

**Comment by mikkelbu** [comment]
This is not an issue with NUnit. Either it is in the adapter or more probably in vstest aka `dotnet test`. I Googled for "results-directory" and one of the first hits was https://stackoverflow.com/questions/49390416/dotnet-test-not-creating-test-results-folder
> To output the test results using the `dotnet test` option `--results-directory` you have to also set `--logger`.

And as far as I can tell you are not setting `--logger`

**Comment by madhusameena** [comment]
> 
> 
> This is not an issue with NUnit. Either it is in the adapter or more probably in vstest aka `dotnet test`. I Googled for "results-directory" and one of the first hits was https://stackoverflow.com/questions/49390416/dotnet-test-not-creating-test-results-folder
> 
> > To output the test results using the `dotnet test` option `--results-directory` you have to also set `--logger`.
> 
> And as far as I can tell you are not setting `--logger`

Thank you for the link

I can able to generate files - But they are not recognized by sonar - That is different story anyway 
I will check that
Thanks
