### ISSUE TITLE
Specify upper limit with Assert.Multiple

### ISSUE THREAD

**Issue by chm-tm** [nunit/nunit#3512]
When using Assert.Multiple with a loop, I want to limit the maximum number of failed assertions. This limits the time lost in doing the assertions and yields a manageable number of failures.
```C#
Assert.Multiple(() =>
{
    int matches = 0;
    for (int i = 0; i < BigConstant; i++)
    {
        if (matches < i - 10)
        {
            matches = -1;
            break;
        }
        Assert.That(Test(i));
        matches++;
    }
    if (matches == -1)
    {
        Assert.Fail("Maximum failure count reached.");
    }
});
```
There is certainly a more elegant approach out of the box, but...
If I could pass an upper limit to `Assert.Multiple`, the same code could be simplified to this:
```C#
Assert.Multiple(() =>
{
    for (int i = 0; i < BigConstant; i++)
    {
        Assert.That(Test(i));
    }
}, limitFailuresTo: 10);
```
Please consider introducing such an API.

**Comment by CharliePoole** [comment]
@chm-tm IMO this would have a better chance of being considered if you provided a motivating example. What you give as an example is abstract - i.e. "I have a lot of assertions to run under MultipleAssert." Can you indicate a situation where extremely large numbers of assertions are actually needed to be run without failing on any of them individually?

Reason for asking: This is not the kind of usage we had in mind for MultipleAssert. OTOH maybe you have a good usage that we didn't think of!

BTW: I believe that this is a simpler way to do your workaround...

```c#
Assert.Multiple(() =>
{
    for (int i = 0; i < BigConstant; i++)
    {
        Assert.That(Test(i));

        if (TestContext.CurrentContext.Result.Assertions.Count() >= 10)
            break;
    }
});
```

**Comment by chm-tm** [comment]
I'm asserting the contents of each cell of a quite a big RAM I can access using a `Read` method. I want to see actual and expected values in case of failed assertions, but not in an overwhelming fashion. How am I supposed to accomplish this?

Thanks for your suggestion using the `TextContext`. I think, the `FailCount` property would perfectly match my needs.

**Comment by rprouse** [comment]
I think this is an edge use case that I'd prefer not to include in the framework, plus you have an alternative, so I am going to close as won't implement. Thanks for your idea though.
