### ISSUE TITLE
TryValidateModel throws System.NullReferenceException: 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by alinabrinza95** [nunit/nunit#3514]
I am trying to validate a model in a controller method, using TryValidateModel method from ControllerBase class. When I am manually testing the controller method using Swagger, it works and the model is validated. When I'm trying to unit test it tho, it fails at TryValidateModel(myModel) with the following exception: System.NullReferenceException: 'Object reference not set to an instance of an object.'

The object I am passing to TryValidateModel has the same values as the one I am passing via Swagger, and the model makes use of DataAnnotations to ensure that two properties are required, this being the reason why I am using the TryValidateModel method.
I am using NUnit (3.12.0), NSubstitute (4.2.1).

Can you please check if this is a framework related issue?
Thank you.

**Comment by mikkelbu** [comment]
I don't think this is a framework related issue, but it is difficult to tell given the information. First and foremost, do you have the stacktrace, so we can see where the exception is thrown.

When you are testing via swagger, then you have started the process that implements the controller. How do you do this in the test, or are you just calling the endpoint method directly?

**Comment by ivan-shaporov** [comment]
Here is a stacktrace:
  Message: 
    System.AggregateException : One or more errors occurred. (Object reference not set to an instance of an object.)
    ---- System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace: 
    Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
    Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
    Task.Wait()
    SomeUnitTest() 
    --- End of stack trace from previous location where exception was thrown ---
    ----- Inner Stack Trace -----
    ControllerBase.TryValidateModel(Object model, String prefix)
    ControllerBase.TryValidateModel(Object model)
    SomeController.Post(SomeRequestType request) line 72

**Comment by mikkelbu** [comment]
I'm closing this issue as it seem to be an issue with the asp.net framework - needing to mock the ObjectValidator - and not with NUnit. Please note that we will still see additional comments in this issue.
