### ISSUE TITLE
How to create an attribute to run logic BEFORE each test is run and AFTER each test is run

### ISSUE THREAD

**Issue by TraGicCode** [nunit/nunit#3518]
Hello,

What is the recommended way to be able to mark tests with an Attribute to run code BEFORE the test starts and AFTER the test finishes?  For Example, I'm wanting to do something like this

```
[Test]
[Profiler]
void MyTest()
{
// Before test starts i want to enable the profiler for this test
// AAA is here
// Before test finishes i want to Write profiler output somewhere
}
```

Some like this
```
public class ProfilerAttribute
{

void BeforeTest()
{
  StartProfiler
}

void AfterTest()
{
print out profiler output
}

}
```

**Comment by Dreamescaper** [comment]
You can do that by inheriting from `TestActionAttribute`, see details here:
https://github.com/nunit/docs/wiki/Action-Attributes

**Comment by TraGicCode** [comment]
Hey @Dreamescaper ,

I actually did this BUT I was unsure if there was a recommended alternative since the ITestAction interface in the NUnit3 documentation mentions it will most likely go away soon.

> Note: Action Attributes are a feature of NUnit V2, designed to better enable composability of test logic. They are carried over to NUnit 3, but are not the recommended approach for most new work. Instead, for most problems of extensibility, NUnit 3 Custom Attributes are a better approach and are more likely to be supported in future releases.However, at this time, Action Attributes provide the only approach that allows placing an attribute on a higher-level element and having it affect the behavior of lower-level elements. The rest of this page describes Action Attribute usage in NUnit 3.

**Comment by Dreamescaper** [comment]
Well, you can achieve same by implementing `IWrapTestMethod` in your attribute - put code that you need before and after running `command`.
https://github.com/nunit/docs/wiki/ICommandWrapper-Interface

As far as I remember, there's limitation that you cannot apply it on the whole assembly though, don't know whether you need that.

I don't think there are any plans to remove Action Attributes anytime soon though.

**Comment by CharliePoole** [comment]
I wrote the warning out if an excess of caution. I'd like to see a better replacement but I'm not with this project any longer so others should tell you what they plan. In any case we can be sure it won't go away in NUnit 3, since that would be a breaking change.

That said, if you aren't trying to use it at a higher level, like on the assembly, implementing the interface is pretty easy.

**Comment by TraGicCode** [comment]
Thanks everyone!
