### ISSUE TITLE
Test with infinite loop in TearDown cannot be aborted

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#352]
Pursuant to a discussion on issue #326 I added some tests in order to see the behavior of tests that caused a timeout because of a hung SetUp or a hung TearDown. An infinite loop in the SetUp is handled the same as one in the test but a loop in TearDown causes the entire run to hang.

The cause of this phenomenon is that we run TearDown out of a finally clause. Code in a finally clause is not interupted by a ThreadAbortException.

The same behavior occurs in NUnit V2. See https://github.com/nunit/nunitv2/issues/26

It appears that there are three options:
1. Don't run TearDown in a finally clause.
2. Don't use Thread.Abort to cancel a test that times out.
3. Have NUnit host the CLR and thereby gain the ability to escalate aborts.

All of these are fairly big deals, so some design work is needed.

**Comment by CharliePoole** [comment]
I'm moving this to Beta2 since it's low priority. That said, we should give it a bit of focus after beta 1 to decide whether it's feasible to fix it or if we should just document it. As commented above, fixing it means calling teardowns in some other way than in a finally clause. It seems like there should be a way to do this and that it would improve the design if we did so. Finally clauses should be for _our_ cleanup, not for the users'.

**Comment by rprouse** [comment]
As part of #867, I am commenting out the ignored test `TimeoutTests.TearDownTimesOutAndNoFurtherTearDownIsRun` which fails because of this issue. When this issue is fixed, that test should be uncommented.

**Comment by jnm2** [comment]
This seems like low-hanging fruit. I'd be happy to move this out of the `finally`:

https://github.com/nunit/nunit/blob/13b47765b9951ae5edc3253e4f9116db5f7d542d/src/NUnitFramework/framework/Internal/Commands/BeforeAndAfterTestCommand.cs#L69-L73

It would require replacing the `finally` with `catch (Exception ex)` and rethrowing the exception (if any) after executing the finally block.

**Comment by jnm2** [comment]
Or we could just do `AfterTestCommand` and assume there will be no exception lol:

like https://github.com/nunit/nunit/blob/dd73ab001cbbdc8f911d457b976a7f982b3c11b0/src/NUnitFramework/framework/Internal/Commands/AfterTestCommand.cs#L48-L50

**Comment by CharliePoole** [comment]
@jnm2 Except... I think it's being fixed with #2920, using the simplest of the approaches I suggested.

**Comment by jnm2** [comment]
Oh good!

**Comment by jnm2** [comment]
@rprouse 

> As part of #867, I am commenting out the ignored test `TimeoutTests.TearDownTimesOutAndNoFurtherTearDownIsRun` which fails because of this issue. When this issue is fixed, that test should be uncommented.

@dukearena already did the implementation, and https://github.com/nunit/nunit/pull/2921 addresses this part.
