### ISSUE TITLE
Package 'NUnit.ConsoleRunner.3.11.1' is not found on source

### ISSUE THREAD

**Issue by smiske** [nunit/nunit#3520]
We use a build server to build our applications and we are getting the following error; "Package 'NUnit.ConsoleRunner.3.11.1' is not found on source"

We have verified that the directory it is looking for is present. we also added it to the 3.10.0 directory structure.
so in our repository of nuget packages where it is looking we have
NUnit.ConsoleRunner.3.11.1
and
nunit.consolerunner
     3.10.0
     3.11.1

I would have expected the the first to work, but we get the error, and the second one is not woking either.  3.10.0 does compile with no errors.
can the 3.10 and 3.11 be together?  I could remove 3.10, but I hate to remove it until I know how to get 3.11.1 to work.

**Comment by CharliePoole** [comment]
It seems as if you have managed to add the same package (3.11.1) twice using different casings. Were they added to your source in different ways? (Assuming you are refering to a local NuGet source, btw, similar to nuget.org)

**Comment by smiske** [comment]
We are using nuget and its nuget that is failing.  Our server cannot download from the web, so we place what it needs in a nuget location.  The NUnit.ConsoleRunner.3.11.1 is in the location, but says it can't find it.
C:\Users\xyz\.nuget\packages
in this directory  we have
nunit
--3.12.0
nunit.consolerunner
--3.10.0
--3.11.1  => I put this here as the other was not found
NUnit.ConsoleRunner.3.11.1  => being said it's not found
nunit3testadapter
--3.13.0

that's everything for nunit I see, 3.10.0 does compile
I hope this helps

**Comment by CharliePoole** [comment]
Can you verify that 3.11.1 is actually a good package and that it's actually the version it should be? You can open a package as a zip file (for some software you may need to rename the file) and examine the contents. Check the contained nuspec for the actual version. If anything looks suspicious, download a fresh copy to replace it.

I would NOT keep two copies of the same package version in the source however. Nothing good can come of that. :smile:

**Comment by rprouse** [comment]
@smiske If your server is not allowed to connect to external NuGet servers, you should add a `NuGet.config` file to the root of your solution. In that file, add a new `packageSource` that points to a directory on your server where you copy the full NuGet packages, not the unzipped copies of them. 

For example, you would just drop `NUnit.ConsoleRunner.3.11.1.nupkg` into that folder, not the `NUnit.ConsoleRunner\3.11.1\*.*` like it seems that you are doing.

This is the recommended practice for adding local package sources to NuGet. See https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file

I'm going to close this issue as a question since you are not using NUnit or NuGet in the recommended way.

**Comment by smiske** [comment]
I'm not sure what you mean by non-standard as I have 262 packages that work including 3.10.0.  we are using a config and it has
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="MSTest.TestAdapter" version="1.3.2" targetFramework="net48" />
  <package id="MSTest.TestFramework" version="1.3.2" targetFramework="net48" />
  <package id="NUnit.ConsoleRunner" version="3.11.1" targetFramework="net48" />
</packages>

**Comment by smiske** [comment]
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="MSTest.TestAdapter" version="1.3.2" targetFramework="net48" />
  <package id="MSTest.TestFramework" version="1.3.2" targetFramework="net48" />
  <package id="NUnit.ConsoleRunner" version="3.11.1" targetFramework="net48" />
</packages>

**Comment by CharliePoole** [comment]
@rprouse Structure of the local source is nuget version-dependent. In 3.3+ it can be hierarchical. See https://docs.microsoft.com/en-us/nuget/hosting-packages/local-feeds.

@smiske states that only this one is not working. Based on what he shows us it appears that he is mixing the flat file structure with the hierarchical structure and I'm sure that can't be good! That would happen in two ways that I know of:

1. Mixing manually copying the files with use of nuget add (Don't)
2. Using nuget add with different versions (pre 3.3 and post) of nuget (Don't)

I think a large local source repo like this has to be managed very carefully.

**Comment by smiske** [comment]
[cid:image001.png@01D60C20.93D69A10]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by CharliePoole** [comment]
@smiske You seem to be trying to post an image, but only the name of the png file is showing up.

**Comment by smiske** [comment]
It basically shows that the .nuspec file is there

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by jnm2** [comment]
I'd recommend starting over and using `nuget init` to set up the correct folder structure and .nuspec extraction.

**Comment by CharliePoole** [comment]
Right, but you would have to verify that the file is correct, not just that it is there! It may be simpler for you to just remove and re-add that release, ensuring that it is done correctly.
