### ISSUE TITLE
Not able to acheive parallel execution in Nunit while having all the initialization methods and excel methods are there in another project library

### ISSUE THREAD

**Issue by gnaneswarreddy** [nunit/nunit#3525]
Do we have any sample project with this reference where the initialization methods and excel, launching browsers are in different project and tests are in different project? Any help would be appreciated Thanks

**Comment by mikkelbu** [comment]
I'm unsure what you mean by
> where the initialization methods and excel, launching browsers are in different project and tests are in different project

But as far as I know we don't have any samples that involve neither Excel nor web-browsers.

**Comment by gnaneswarreddy** [comment]
I have two projects Project A and Project B where i have the tests in Project A with NUnit fixtures and Project B contains the NUnit.Framework.TestContext sent using setup method of Project A and this testcontext is used to get test case name and test case execution details and where it reads the excel data of that test case method. So when using this way i am able to run the single tests but parallel execution is failing when running two tests at same time.  Do i need to implement anything on the methods to support this?

**Comment by CharliePoole** [comment]
It's not clear what you mean by "Project B contains the NUnit.Framework.TestContext sent using setup method of Project A." In terms of NUnit, the TestContext isn't designed to be "sent" anywhere but is used inside your tests.

Can you provide a simplified code example of what you are trying to do?

**Comment by rprouse** [comment]
@gnaneswarreddy we haven't heard back from you, so I am closing this issue. If you have sample code to explain what you are asking, please open a new issue.
