### ISSUE TITLE
Constraints syntax with nullability

### ISSUE THREAD

**Issue by maxkatz6** [nunit/nunit#3529]
Hello!
Right now it isn't possible to use constraints syntax with enabled C#8 nullable feature.

Let's image some auth Service, which doesn't allow null arguments
```csharp
#nullable enable
public void Auth(string userName, string password) {  }
```
And we have test for it, where we read secrets from some source (const or config, doesn't matter) and Assert, that they will not be null or empty.
```csharp
#nullable enable
[Test]
public void ServiceAuthTest()
{
    Assert.That(Secrets.Test.UserName, Is.Not.Null & Is.Not.Empty, "Test UserName is missed");
    Assert.That(Secrets.Test.Password, Is.Not.Null & Is.Not.Empty, "Test Password is missed");

    var testedService = new Service();
    // Compiler Warning CS8604 Possible null reference argument for parameter 'userName'
    testedService.Auth(Secrets.Test.UserName, Secrets.Test.Password);

    // ...
}
```
We can understand, that UserName and Password will never be null, but compiler doesn't.

Workarounds:
1. Use '!' operator to ignore warning
2. Ignore CS8604 warning in source with "pragma warning disable"

It isn't critical, but it would be nice to have working code without workarounds.
Also it seems like problem is in Roslyn and there no way to fix it at least right now.

With Assert.IsNotNull(nullable) it should be possible though with [NotNullAttribute] on nullable argument.

**Comment by maxkatz6** [comment]
I don't have any experience with Roslyn analyzers, but it seems like NUnit.Analyzers can implement DiagnosticSuppressor for that specific case:
https://github.com/dotnet/roslyn/issues/30172
https://gist.github.com/mavasani/fcac17a9581b5c54cef8a689eeec954a

**Comment by Dreamescaper** [comment]
Related:
https://github.com/nunit/nunit.analyzers/issues/157

**Comment by maxkatz6** [comment]
@Dreamescaper thanks. I haven't seen that issue in another repo.
Probably I should close this one as duplicate.
