### ISSUE TITLE
Selenium C# / NUnit 3.12.0 is not running tests in parallel

### ISSUE THREAD

**Issue by Aznariy** [nunit/nunit#3534]
I am executing my tests in Visual Studio Enterprise 2019 version 16.3.9 / Test Explorer window. My architecture is Intel(R) Core(TM) i7-7600 CPU @ 2.80Ghz (4 CPUs), ~2.9Ghz  
Here is my pseudo Selenium C# code below:

    [TestFixture]
    internal class TestClass{
    
        [OneTimeSetUp]
        public void OneTimeSetUp()
        {
           initializeExtentReport()
        }
    
        [SetUp]
        public void Setup()
        {
           initializeChromebBrowser();
        }
    
        [Test]
        public void NavigatoToGmail()
        {
            bool isGmailAccessible = GoToUrl("https://www.google.com/");
            Assert.True(isGmailAccessible);
        }
    
        [Test]
        public void NavigatoToMicrosoft()
        {
            bool isMicrosoftAccessible = GoToUrl("https://www.microsoft.com/");
            Assert.True(isMicrosoftAccessible);
        }
    
    
        [Test]
        public void NavigatoToYahoo()
        {
            bool isYahooAccessible = GoToUrl("https://www.yahoo.com/");
            Assert.True(isYahooAccessible);
        }
    
        [TearDown]
        public void TearDOwn()
        {
            CloseBrowser();
        }
    
        [OneTimeTearDown]
        public void OneTimeTearDown()
        {
            FinishExtentReport();
        }

So here is what I tried already and it didn't work

1. Adding `[Parallelizable(ParallelScope.Children)]` to the class and `[Parallelizable(ParallelScope.Self)]` attributes to every test method. The result - 3 browser instances open with no other actions. No URL navigating, nothing.

2. Adding `[Parallelizable(ParallelScope.All)]` to class and `[Parallelizable(ParallelScope.Self)]` to every test method. The result - 3 browser instances open. Only the last test (NavigatoToYahoo) is executed and provides the result. The first 2 - no other action happens and the browser windows are not closed, meaning TearDown() method is not executed. 

3. Just adding `[Parallelizable(ParallelScope.Self)]` to every test method. The result - 3 browser instances open with no other actions. No URL navigating, nothing.

4. Adding `[Parallelizable(ParallelScope.Self)]` to the class and `[Parallelizable(ParallelScope.Self)]` attributes to every test method. The result - 3 browser instances open. The second test (NavigateToMicrosoft) gets executed, the rest 2 - no other action, no URL navigating, nothing.

5. Adding `[Parallelizable(ParallelScope.Self)]` to the class and `[Parallelizable(ParallelScope.All)]` attributes to every test method. The result - getting error message `May not specify ParallelScope.Children on a non-parameterized test method` - honestly have no idea why

I have gone through the documentation here https://github.com/nunit/docs/wiki/Parallelizable-Attribute but I feel like there is no actual way to execute unit tests in parallel using NUnit framework. 

I simply want to run those 3 tests (in my actual scenario there are about 100 of them) in parallel independent of each other.

**Comment by mikkelbu** [comment]
Hi @Aznariy. When you run the tests methods in parallel, then it still only creates one instance of your testfixture object, and runs all tests on that object. That's the same behaviour as when you run your tests in non-parallel.

So I guessing that the methods you call:
* initializeExtentReport
* initializeChromebBrowser
* GoToUrl
* CloseBrowser
* FinishExtentReport
manipulates some shared state, but this state is shared by all the methods, so this is probably the reason for why it is not working. We have several issues about this and a PR for enabling "Instance-per-test-case feature" #2574, but we have not been able to close it yet.

**Comment by mikkelbu** [comment]
I'm closing this issue, as we have not heard anything from the reporter. Please note that we will still see additional comments on this issue.
