### ISSUE TITLE
ApplyTo<TActual> behavior for Is.Not.Null constraint

### ISSUE THREAD

**Issue by elv1s42** [nunit/nunit#3546]
Hello.
Not sure if it's a bug or a question.

Please consider the following code example (looks like it's working as expected):
`Assert.That<string>((string)null, Is.Not.Null)`

![image](https://user-images.githubusercontent.com/6689884/81811579-870c0400-952d-11ea-8a73-65b87184651a.png)

The question is about the next code example:
`NUnit.Framework.Is.Not.Null.ApplyTo<string>((string)null)`

![image](https://user-images.githubusercontent.com/6689884/81811702-b884cf80-952d-11ea-9448-5466041eeaf3.png)

Why the second code example returns `Success` ConstraintStatus?

Thank you

**Comment by elv1s42** [comment]
Some more details about package versions: 
The `NUnit` version is `3.12.0`
![image](https://user-images.githubusercontent.com/6689884/81816395-f127a780-9533-11ea-830d-3e9635e6e1b9.png)

**Comment by Dreamescaper** [comment]
All pending operators are applied only after Resolve called.
So it should be 
`NUnit.Framework.Is.Not.Null.Resolve().ApplyTo<string>((string)null)`
or
`new NotConstraint(new NullConstraint()).ApplyTo<string>((string)null)`

**Comment by elv1s42** [comment]
Hi @Dreamescaper, 
Thank you for the quick response.
Looks like the `Resolve` method is not available for me:

![image](https://user-images.githubusercontent.com/6689884/81829240-5d5dd780-9543-11ea-8cb0-ebe4981d6437.png)

Should it be public as long as the `ApplyTo<>` method is public?

![image](https://user-images.githubusercontent.com/6689884/81829089-356e7400-9543-11ea-89d4-7aa631f6ed20.png)

**Comment by Dreamescaper** [comment]
Yeah, sorry, it's explicit implementation.
`((IResolveConstraint)Is.Not.Null).Resolve().ApplyTo((string)null)`

**Comment by elv1s42** [comment]
Thank you, casting to `IResolveConstraint` did the trick!
Closing the issue.
