### ISSUE TITLE
String Comparisons are not culture-safe

### ISSUE THREAD

**Issue by stevenaw** [nunit/nunit#3549]
The following comparison should probably pass, but doesn't currently

```csharp
[Test, SetCulture("de-DE")]
        public void CultureAware()
        {
            string x = "ss";
            string y = "ß";

            Assert.IsTrue(string.Equals(x, y, StringComparison.CurrentCulture));  // passes
            Assert.AreEqual(x, y);   // fails
        }
```

There's also issues with case-insensitive comparisons (the following should pass):

```csharp
[Test, SetCulture("de-DE")]
        public void CultureAwareStringEquals([Values]bool ignoreCase)
        {
            Assert.That("ss", Is.EqualTo("ß"));

            if (ignoreCase)
                Assert.That("SS", Is.EqualTo("ß").IgnoreCase);
        }
```

This is because, in many places, NUnit uses the following rules for string comparisons:
- Case-insensitive comparisons are `Ordinal` ("s1".Equal("s2"))
- Case-sensitive comparisons invoke `ToLower()` and then perform an ordinal comparison

Most comparisons are done via `StringComparer`, but some constraints duplicate the logic (ex: UniqueItemsConstraint) so changes may be a little more widespread.

**Comment by stevenaw** [comment]
NOTE: This _could_ be considered a breaking change for any consumers who expect ordinal comparisons. For example, the following test from NUnit 2.5.1 relies on ordinal comparison
https://github.com/nunit/nunit/blob/ad943eb94fe280e661fc6c690043fe8eb0a11e40/src/NUnitFramework/tests/Assertions/StringAssertTests.cs#L154-L162

**Comment by appel1** [comment]
I think string comparisons are ordinal by default to behave the same way as the Equals method and == operator for string. I would be very surprised if NUnit suddenly started doing comparisons culture aware by default.

Using culture aware comparisons is a bit cumbersome due to a overload collision. Maybe there's some better way?

```csharp
[Test, SetCulture("de-DE")]
public void CompareString()
{
    Assert.That("ss", Is.EqualTo("ß").Using((IEqualityComparer<string>)StringComparer.CurrentCulture));
}
```

**Comment by stevenaw** [comment]
Huh. I must admit I've never had to use that overload of `Using()`. It's almost as if what I suggested in the initial description... already exists. Thanks 😄
