### ISSUE TITLE
MessagePumpStrategy does not work for WPF on netcoreapp3.0 and upwards

### ISSUE THREAD

**Issue by batzen** [nunit/nunit#3552]
I am trying port our applications to netcoreapp3.1.
During this i also tried to run our unit tests for that target framework.
To my surprise the tests deadlocked as soon as they use async or things like `Assert.CatchAsync`.
The issue boils down to `MessagePumpStrategy` which had special cases for windows forms and WPF on net framework 4.

Is there a reason why there are no special cases for netcoreapp3.0 and upwards or was it just an oversight and those should be there?

**Comment by jnm2** [comment]
This was just an oversight. Thanks!

**Comment by batzen** [comment]
Good to hear that. ;-)

I know i shouldn't ask this question, but do you have any estimate for a fixed release?
Don't feel pressured, but i can't finish porting till this issue is resolved.
If there is anything i can do to help you here just tell me so.

**Comment by jnm2** [comment]
@batzen I believe we're on the cusp as we speak.
