### ISSUE TITLE
WinUI 3 support

### ISSUE THREAD

**Issue by Xarlot** [nunit/nunit#3556]
As you may know, Microsoft just releases WinUI 3 Preview 1 https://github.com/microsoft/microsoft-ui-xaml/issues/2472

Do you have any plans to support it? If so, letting us know timeframe will be very helpful.

**Comment by SimonCropp** [comment]
@Xarlot in what way does nunit not support winui?

**Comment by OsirisTerje** [comment]
@Xarlot You need to have the Test Sdk at version 16.6, to support .netcoreapp5.0.  That given, you can test WinUI 3
