### ISSUE TITLE
[Question] Is it possible to use --inprocess parameter with dotnet test command ?

### ISSUE THREAD

**Issue by goblinmaks** [nunit/nunit#3558]
In previous time when we used NUnit console we used --inprocess parameter. Is it possible to use it with dotnet test ?

**Comment by ChrisMaddock** [comment]
dotnet test runs in process by default, at least from an NUnit point of view. I'm not sure what the Microsoft side does, @OsirisTerje might know?

We were actually considering removing this option in future versions however. Can I ask why you need to use it?

**Comment by CharliePoole** [comment]
@ChrisMaddock When it comes to the test adapter, it's the host who sets up the process in which it runs. So it would be redundant to create another process from that one.

**Comment by mikkelbu** [comment]
Closing this issue as answered.
