### ISSUE TITLE
[Question] Is it possible to create TestFixtureSource with generic?? (Like At Picture)

### ISSUE THREAD

**Issue by 50N** [nunit/nunit#3560]
![Capture1](https://user-images.githubusercontent.com/25611208/82584913-5d9f4800-9bbf-11ea-917a-94dfcccb7b85.PNG)

**Comment by CharliePoole** [comment]
It's possible. :smile: 

Whether or not it works depends on the actual data and tests, which you have not shown. :disappointed: 

In short, it will work IFF the compiler is able to deduce the type of `T` from the arguments you supply.

I assume that both the `RandomizeUITestData` class and the `RandomizeData()` method are non-generic.

**Comment by mikkelbu** [comment]
If I Google for "TestFixtureSource generic" (without the quotes) then the first hit is #1346 which is linked to a PR - #2439 - with the following code which works (so it is possible)
```csharp
public interface IValidEntity { }
public class EntityOne : IValidEntity { }
public class EntityTwo { }
public class EntityThree : IValidEntity { }

[TestFixtureSource(typeof(RegistryType), nameof(RegistryType.Source))]
public class TestUsingTypeSource<TEntity>
{
	[Test]
	public void TestMethod()
	{
		Assert.That(typeof(IValidEntity).IsAssignableFrom(typeof(TEntity)));
	}
}

public class RegistryType
{
	public static readonly Type[] Source = new[]
	{
		typeof(EntityOne),
		typeof(EntityTwo),
		typeof(EntityThree)
	};
}
```

**Comment by 50N** [comment]
thank you

>

**Comment by mikkelbu** [comment]
I'm closing this issue as answered. Please note that we will still see if new comments arise on this issue.
