### ISSUE TITLE
Set TestName to inherited class

### ISSUE THREAD

**Issue by mwhelan** [nunit/nunit#3572]
I am doing BDD-style tests with a test per class where each test inherits from a base class. Conveniently, I only have to put the Test attribute on the base class and all the tests run for the inheriting classes.

```csharp
using NUnit.Framework;
using TestStack.BDDfy;

namespace NUnitTestName
{
    public class Domain{}

    [TestFixture]
    public abstract class ScenarioFor<TSut> where TSut : class
    {
        [Test]
        public void RunTest()
        {
            this.BDDfy();
        }
    }

    public class DomainScenario : ScenarioFor<Domain>
    {
        public void Given(){}
        public void When() { }
        public void Then() { }
    }
}
```

The only issue is that the TestName is set to "RunTest," which is the name of the test method on the base class. I would like it to be set to the name of the test class - "DomainScenario."

I tried using the TestCase attribute instead, with the class template pattern but this just set the TestName to the name of the base class ScenarioFor`1:

```csharp
[TestCase(TestName = "{c}")]
```

Can anyone think of any way that I might achieve this? I have tried a number of other things too and am really open to any suggestion at this stage, no matter how custom.

I am using  NUnit 3.12.0 and NUnit3TestAdapter 3.16.1. The issue occurs in Visual Studio (with ReSharper and Test Explorer) and on Azure DevOps.

**Comment by mwhelan** [comment]
Hi, it's been 10 days and I haven't had a response. I would really appreciate it if someone could please suggest some options for setting the TestName for an inheriting class? Or perhaps just suggest the best place to implement this kind of behaviour?

Some ideas I've seen mentioned elsewhere:
- Create a custom attribute using something like StackFrame?
- Create a custom test name template?
- Given the static nature of attributes, I wonder if it is even possible to set the test name programmatically at runtime or might I need a solution that runs at build time?
- Replacing the TestName in the .trx file after the tests have run?

It would be really useful if TestContext.CurrentContext.Test.Name was settable.

Thanks, really appreciate any suggestions.

**Comment by mikkelbu** [comment]
Currently, most of the answers, investigations, reviews etc. in all the NUnit repositories are done by approximately a handful of people in their spare time, so often the feedback be slow.

That being said of the alternatives that you list above then we don't support custom test name template as far as I know, replacing the TestName in the .trx file sounds hacky, so I would go for a custom attribute. Despite developing on this project for a couple of years I've never done that before, but looking into the documentation I came up with the following which gives the following structure in the Test Explorer.

![image](https://user-images.githubusercontent.com/1007631/84542086-03466280-acf9-11ea-8d1d-5adba3271132.png)

```csharp
using NUnit.Framework;
using NUnit.Framework.Interfaces;
using NUnit.Framework.Internal;
using NUnit.Framework.Internal.Builders;
using System;

namespace NUnitTestName
{
    public class Domain { }

    [TestFixture]
    public abstract class ScenarioFor<TSut> where TSut : class
    {
        [DerivedClassName]
        public void RunTest()
        {
            Assert.Pass();
        }
    }

    public class DomainScenario : ScenarioFor<Domain>
    {
        public void Given() { }
        public void When() { }
        public void Then() { }
    }

    public class AnotherDomainScenario : ScenarioFor<Domain>
    {
        public void Given() { }
        public void When() { }
        public void Then() { }
    }

    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = true)]
    public class DerivedClassNameAttribute : NUnitAttribute, ISimpleTestBuilder
    {
        public TestMethod BuildFrom(IMethodInfo method, Test suite)
        {
            var builder = new NUnitTestCaseBuilder();
            var testMethod = builder.BuildTestMethod(method, suite, null);
            testMethod.Name = method.TypeInfo.Name;
            return testMethod;
        }
    }
}
```

**Comment by CharliePoole** [comment]
Just a quick comment to supplement @mikkelbu as to why certain things don't work...

The test name is part of the test identity, which also includes the fullname and an id. All of those are set before the test starts to run and are tracked by NUnit. Once the test begins, they can't be changed. Nothing you do within the code of the test - including SetUp and TearDown - is allowed to actually change the test itself. That's why `TestContext.CurrentContext.Test` is a readonly view of the test data.

**Comment by mwhelan** [comment]
@CharliePoole thanks for that extra context. It's helpful to know.

@mikkelbu apologies if I sounded like I was complaining. I really appreciate people giving up their time to help with open source. Your solution is exactly what I was looking for, thanks. I had tried using a custom attribute without getting it to work, but wasn't aware of NUnitTestCaseBuilder. Thanks!

**Comment by mikkelbu** [comment]
@mwhelan No problem :). I'm closing this issue as answered.
