### ISSUE TITLE
Nunit don't handle custom attribute

### ISSUE THREAD

**Issue by CimaCha** [nunit/nunit#3582]
I've created a custom attribute to process retry if an exception was caught. This attribute is a copy of retry attribute except one "if" statement:

```
public override TestResult Execute(TestExecutionContext context)
            {
                var count = _tryCount;

                while (count-- > 0)
                {
                    try
                    {
                        context.CurrentResult = innerCommand.Execute(context);
                    }
                    // Commands are supposed to catch exceptions, but some don't
                    // and we want to look at restructuring the API in the future.
                    catch (NoSuchElementException ex)
                    {
                        if (context.CurrentResult == null) context.CurrentResult = context.CurrentTest.MakeTestResult();
                        context.CurrentResult.RecordException(ex);
                    }

                    **if (context.CurrentResult.ResultState == ResultState.Error)
                    {
                        break;
                    }**

                    // Clear result for retry
                    if (count <= 0) continue;
                    context.CurrentResult = context.CurrentTest.MakeTestResult();
                    context.CurrentRepeatCount++;
                    // increment Retry count for next iteration. will only happen if we are guaranteed another iteration
                }

                return context.CurrentResult;
            }
```

And I use it in test like this:

`[Test, RetryOnException(2), Category("SmokeTests")]`

In debug mode, I can see that attribute is created, but the "Execute" method isn't called by Nunit

**Comment by CharliePoole** [comment]
Did you copy the attribute code from the current GitHub master or from the source code of the nunit release you are using? The latter would be the best way to go to match your version of NUnit but either one should work.

If you are sure that the `Execute` method is not being called, then its content is not relevant to the problem. Check if your `Wrap` method is being called.

If not, it means you are probably not using the same `IRepeatTest` interface that NUnit is using. Where is the custom attribute? That is, is it in a separate assembly, your test assembly, etc? How is it referencing nunit?

**Comment by CimaCha** [comment]
I copied code from the source code of the NUnit release: 
```
<package id="NUnit" version="3.12.0" targetFramework="net461" />
  <package id="NUnit.ConsoleRunner" version="3.11.1" targetFramework="net472" />
  <package id="NUnit3TestAdapter" version="3.16.1" targetFramework="net472" developmentDependency="true" />
```
On Windows 10

"Wrap" method isn't called too

**Comment by CharliePoole** [comment]
If Wrap is never called, then of course nothing can happen. Wrap will only be called if your custom attribute is referencing the same copy of the framework as the tests. The easy way to do this is to define the attribute right in the test assembly.

**Comment by CimaCha** [comment]
What do you mean by "define the attribute right in the test assembly."?? File with attribute created in the same project with tests.

**Comment by CharliePoole** [comment]
Exactly. Is that what you did?

All this info is necessary in order to try to replicate and confirm the problem.

**Comment by CimaCha** [comment]
The issue is resolved by restarting the computer. Rebuild project didn't help
