### ISSUE TITLE
Failed tests are displayed as Error in NUnit Console Runner

### ISSUE THREAD

**Issue by OlafVolafka** [nunit/nunit#3584]
I have a test that correctly evaluate a failure but has a result displayed as Error (not Failed as expected). Is it possible there could be some error occured in TearDown method that is causing test result being stated as Error not Failed?

**Comment by CharliePoole** [comment]
That's possible. The stacktrace

**Comment by OlafVolafka** [comment]
@CharliePoole Thanks for the answer.
