### ISSUE TITLE
Audit string equality comparisons and consider changes for v4

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#3588]
Many of .NET's System.String APIs default to CurrentCulture comparisons. Unintentional linguistic comparisons cause correctness and performance problems. @jskeet has found a couple of significant speed issues caused by NUnit using EndsWith without specifying StringComparison.Ordinal: https://github.com/nunit/nunit/pull/3583, https://github.com/nunit/nunit/issues/1555.

~~If you think it's a good idea, I would like to reference https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers. I would silence all rules using .editorconfig which we aren't prepared to fix and would specifically leave on these rules:~~

**Update:** In the current .NET SDK, we would instead do `<AnalysisLevel>6.0-minimal</AnalysisLevel>` or similar and turn *on* these rules.

https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1310 (Specify StringComparison for correctness)
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1309 (Use ordinal StringComparison)

For each case where we can't fix the CA warning due to backwards compatibility concerns, I'd prefer to use `#pragma warning disable` with a comment noting why. For v4 we could consider removing these exceptions.

**Comment by stevenaw** [comment]
I did a cursory check for `EndsWith` a week or two ago, and I think most usages of that check for a constant string of symbols all in the ASCII range (similar to the `EndsWith("[]")` case covered in #3583  ). It's possible that most of these could be updated in a non-breaking way.

**Comment by OsirisTerje** [comment]
Seems most have been done here, or are there more left?  
@stevenaw

**Comment by stevenaw** [comment]
Good catch @OsirisTerje !
I think this was an issue we'd originally thought there to be more follow-up to do but I think that it can be closed. There may be a bit of release notes cleanup needed here too. I can try and tackle this in the next few days
