### ISSUE TITLE
Add classname and methodname to the start-test event

### ISSUE THREAD

**Issue by OsirisTerje** [nunit/nunit#3592]
The test case finished event includes the classname and methodname.  The start-test event needs the same.  The lack of this is the reason the NUnit3TestAdapter cannot skip the discovery phase.

**Comment by cjconrad2** [comment]
This seems easy to implement given those properties already exist on ITest, but based on the discussion in https://github.com/nunit/nunit/pull/2099 (the last time this event was updated), @CharliePoole seemed opposed to adding additional information to the start-test event.

**Comment by CharliePoole** [comment]
Saw my name here. :smile: 

My objection to adding the __particular__ info requested in #2099 was that the requestor gave no explanation of why it was needed. In this case, @OsirisTerje has stated why it's needed.

That said, I'm no longer a part of this project, so I'll leave it for others to act.

**Comment by siburny** [comment]
Based on the code, it seems that `start-test` event already has the following fields:
> Id
> parentId
> Name
> FullName
> TestType

https://github.com/nunit/nunit/blob/26ddebb17caad79054367ab571dd2483166ad977/src/NUnitFramework/framework/Internal/TestProgressReporter.cs#L58

**Comment by CharliePoole** [comment]
@siburny Correct. @OsirisTerje was asking for two additional fields, which aren't there but are available in the framework.
