### ISSUE TITLE
Assert that Directory does not exist?

### ISSUE THREAD

**Issue by Thypari** [nunit/nunit#3605]
What's the recommended way to do this?

```
Assert.AreEqual(false, Directory.Exists(path))

Assert.IsFalse(Directory.Exists(path))

Assert.That(new DirectoryInfo(path), Does.Not.Exist);
```

For a long time I've used the first approach. But it suddenly fails with "Expected: false, Was: false"....
NUnit3: 3.12.0
NUnit3TestAdapter: 3.14.0
Visual Studio 2019 Pro 16.6.5

**Comment by mikkelbu** [comment]
@Thypari Can you provide some more information about why the first approach suddenly fails.

Using the constraint based syntax I would go with
```csharp
Assert.That(path, Does.Not.Exist); // path can just be a string
```

If you prefer the classical syntax you can use
```csharp
DirectoryAssert.DoesNotExist(DirectoryInfo actual);
```
or
```csharp
DirectoryAssert.DoesNotExist(string actual);
```

All of the above give better failure messages, e.g.
```      
Expected: not directory exists
But was:  "C:\Temp"
```
compared to the boolean comparisons that just states if something is true or false
```csharp
Assert.AreEqual(false, Directory.Exists(path))
Assert.IsFalse(Directory.Exists(path))
```


Failure messages like

**Comment by Thypari** [comment]
I have no idea why the Assert is failing. It just says _"expected: false but was: false"_

**Comment by Dreamescaper** [comment]
@Thypari 
`Assert.AreEqual(false, Directory.Exists("/test/test"));`
This line passes for me.
Would it be possible for you to provide example project demonstrating the issue?

**Comment by Thypari** [comment]
The issue only occurs on a co-worker's machine. The same project works on other machines.
We will look into it and report back if we are able to find out what's the difference.

**Comment by rprouse** [comment]
If you find more information, please post. For now, I'm closing as a question.
