### ISSUE TITLE
enum == but not the same

### ISSUE THREAD

**Issue by sunux** [nunit/nunit#3614]
nUnit 3.12.0

test a function like
```
public SvnStatus GetStatus(x);
```
where SvnStatus is a enmu whose values can be Add, Modified, Ignore etc.

test case is
```
public void Normal(List<SvnStatus> x, SvnStatus result)
        {
            Assert.AreSame(result, GetStatus(x));    // fail
            // Assert.That(result == GetStatus(statuses));    // pass
           // Assert.Equals(result, GetStatus(x));    // pass
        }
```

As 'AreSame' check reference, why assert '==' pass but asser 'same' fails. 
Does C# 's enum value share the same instance, doesn't it ?

**Comment by sunux** [comment]
fail info is like

```
  Expected: same as Conflicted
  But was:  Conflicted
```
I am not the same as myself ?

**Comment by jnm2** [comment]
@sunux `AreSame` asks the question, "Are these two object references the same object instance?" Value types like enum values are not object references, so AreSame doesn't make sense to use on them. What is happening here is that the AreSame parameters are of type `object`, so C# is implicitly casting the enum values to `object` which boxes them and creates a new object reference each time.

```cs
// This is like doing SvnStatus.Conflicted == SvnStatus.Conflicted (always true)
Assert.Equals(SvnStatus.Conflicted, SvnStatus.Conflicted);

// This is like doing (object)SvnStatus.Conflicted == (object)SvnStatus.Conflicted (always false)
Assert.AreSame(SvnStatus.Conflicted, SvnStatus.Conflicted);
// The above, but making the implicit casts explicit:
Assert.AreSame((object)SvnStatus.Conflicted, (object)SvnStatus.Conflicted);
```

**Comment by jnm2** [comment]
One thing we could have done about this in the past was to define AreSame this way so that it would be a compiler error to use AreSame with value types such as enums:

```c#
public static void AreSame<T>(T expected, T actual) where T : class?
```

Because we care about ABI compatibility, this would have to wait for NUnit v4. In the meantime, we can achieve the same effect by adding a rule to https://www.nuget.org/packages/NUnit.Analyzers. I highly recommend you add the analyzer package to your test projects even before we add this rule.

**Comment by sunux** [comment]
@jnm2 Many thanks for your replay. It makes things more clear. I will follow your advice.

**Comment by CharliePoole** [comment]
@jnm2 FYI I took your advice in my TCLite framework and used the class constraint. Works a charm.

**Comment by jnm2** [comment]
@sunux Cool, thanks for following up.
