### ISSUE TITLE
Listening to Socket in SetUp

### ISSUE THREAD

**Issue by teremyx** [nunit/nunit#3615]
Hi, I want to write Tests for my MasterServer. 
I have two testing methods, that don't do anything as of yet. 
I have a Setup-method with "SetUp"-attribute, in which I start the MasterServer => listening on a specific port. 
When I run the TestFixture, the second test always fails, because I am already listening on that port. 
I thought SetUp is for any logic, that is run before any test, but I didn't know that consecutive calls of my Setup-method will have impact on each other (variables already being initialized etc.). 
I can run every test in isolation without any problem and I thought that's what unit tests are all about, that's why I was surprised by this behaviour. Will implementing a TearDown-method, that stops listening on the socket (basically unitialize the MasterServer), help? Is this the right thing to do in terms of architecture or are there any alternatives?

**Comment by CharliePoole** [comment]
@teremyx Please allow me to turn your question upside down. :smiley:

SetUp and TearDown is part of __each__ test case. Therefore, if you want something to happen once and once only, then why would you use SetUp or TearDown?

If you implemented a TearDown, that would allow you to repeat the action of listening for each test. That's OK if it's what you want to do but it will prevent you from ever running your tests in parallel.

OTOH you have OneTimeSetUp and OneTimeTearDown available, which are for the situation in which you want something to happen only once in the lifetime of the fixture. Although I don't know all the details of what you are doing, it sounds as if that's what you want.

**Comment by teremyx** [comment]
@CharliePoole 
Thank you! This solved my problem and helped me understand :-).
