### ISSUE TITLE
Extend Is.Empty to work for Guid.Empty

### ISSUE THREAD

**Issue by yaakov-h** [nunit/nunit#3616]
If I have a `Guid` that I want to assert is empty, I currently have to use:

```csharp
Assert.That(myId, Is.EqualTo(Guid.Empty));
```

I think it would be simpler and read easier to be able to say:

```csharp
Assert.That(myId, Is.Empty);
```

Unfortunately this currently throws an error stating that NUnit expected `myId` to be an `IEnumerable`.

**Comment by TimothyDJewell** [comment]
Are you open to a PR to add this?

**Comment by mikkelbu** [comment]
@TimothyDJewell Sure 😄. I'll assign the issue to you.
