### ISSUE TITLE
Visual Studio - test didn't run when using TestCaseSource

### ISSUE THREAD

**Issue by brunomartinspro** [nunit/nunit#3617]
When using the TestCaseSource, visual studio shows a not run test.

```
using NUnit.Framework;
using System.Collections;

namespace NUnitTestProject1
{
    public class UseTestCased
    {
        [Test, TestCaseSource(nameof(GetData))]
        public void Test2()
        {
            Assert.Pass();
        }

        private static IEnumerable GetData()
        {
            yield return new TestCaseData().SetName("Random1_IsOk");
            yield return new TestCaseData().SetName("Random2_IsOk");
        }
    }
}
```

Output:

![image](https://user-images.githubusercontent.com/7645736/89886201-263fa680-dbc4-11ea-9edb-415df5c2bc9a.png)

**Comment by brunomartinspro** [comment]
Removing the SetName from GetData() solved the issue

**Comment by mikkelbu** [comment]
@brunomartinspro I just tried your example and it works on my machine, but I've also disabled the Real Time Test Discovery in VS (under Tools => Options => Test General). The difference could also depend on the version of the NUnit adapter - https://github.com/nunit/nunit3-vs-adapter - you are using (I used version 4 alpha in the test project).
