### ISSUE TITLE
Test suite

### ISSUE THREAD

**Issue by santhosh-James** [nunit/nunit#3625]
I have to create an object before all tests start execute and then after all test execute the data on this object will be inserted to a database. The test fixtures are expecting  parallel. What is the best approach in NUnit to get the suite level control?

Is there a way I can use reflection to get the Suite level access?

**Comment by rprouse** [comment]
I believe what you are looking for is the [SetupFixture](https://docs.nunit.org/articles/nunit/writing-tests/attributes/setupfixture.html) attribute. Add it to a class in your top level namespace, then add `OneTimeSetUp` and `OneTimeTearDown` methods to that class. It will be called before and after all of your tests.
