### ISSUE TITLE
TestCase: An explicit test case makes all test cases explicit

### ISSUE THREAD

**Issue by hhaldn** [nunit/nunit#3628]
If you create a test method with a number of test cases and mark one of them as Explicit, all the test cases are skipped unless explicitly selected. It seems that marking a single test cases as explicit affects all the test cases.

This is not what I would expect from the documentation of [TestCase](https://docs.nunit.org/articles/nunit/writing-tests/attributes/testcase.html), where it says:

"Explicit is set to true in order to make the individual test case Explicit. Use Reason to explain why."

I have attached a simple C#-project with an example and a screen dump of running the tests from this project in the console runner.
![TestCaseExplicit](https://user-images.githubusercontent.com/55240341/92239685-b61efa80-eebb-11ea-9c8a-e9f177b8e7ac.PNG)
[TestCaseExplicit.zip](https://github.com/nunit/nunit/files/5174803/TestCaseExplicit.zip)

NUnit: version 3.12
NUnit-Console: Version 3.11.1

**Comment by mikkelbu** [comment]
This is not a problem with NUnit, but you are misunderstand how attributes work. When you write - as in your example
```csharp
            [TestCase(1)]
            [TestCase(2), Explicit]
            public void IntegerComparison(int i)
            {
                Assert.Greater(i, 0);
            }
```
then it is the same as 
```csharp
            [TestCase(1)]
            [TestCase(2)]
            [Explicit]
            public void IntegerComparison(int i)
            {
                Assert.Greater(i, 0);
            }
```
or even 
```csharp
            [TestCase(1), TestCase(2), Explicit]
            public void IntegerComparison(int i)
            {
                Assert.Greater(i, 0);
            }
```
as the first is just a short hand to specify several attributes using a single `[...]`. The correct way to do it would be 
```csharp
            [TestCase(1)]
            [TestCase(2, Explicit = true)]
            public void IntegerComparison2(int i)
            {
                Assert.Greater(i, 0);
            }
```

We have an analyzer issue - nunit/nunit.analyzers#231 - to help users notice these kinds of problems.

I'm closing this issue as answered, but we will still see new comments in this issue
