### ISSUE TITLE
NUnitLite filtering fails if space in test name before (

### ISSUE THREAD

**Issue by crinksdr** [nunit/nunit#3636]
If I create a test using a testcase source with a name "{m} (unique attribute)" and pass that test in through -testlist argument the test will not be discovered. If there is no space "{m}(unique attribute)" this works fine. The problem is in the TextRunner.MakeRunSetting when its building the prefilter list from the test list it is not trimming the sub string so the parent of the tests are not being discovered.

Work around is to build my own prefilter list with the trim and pass it in using the undocumented --prefilter argument

**Comment by rprouse** [comment]
Sounds like an easy-fix, care to submit a PR?

**Comment by crinksdr** [comment]
Ya I can do that shortly

**Comment by marty-shields** [comment]
Is this still being looked at? I'm more than happy to take a look into it if not

**Comment by crinksdr** [comment]
Go for it I got tied up with other things.

**Comment by marty-shields** [comment]
Ok, bit busy tonight but will take a look tomorrow

**Comment by marty-shields** [comment]
Looks like someone beat me to it. Thanks for the PR.
