### ISSUE TITLE
How to close async calls in teardown

### ISSUE THREAD

**Issue by rojaadi** [nunit/nunit#3637]
Hello 

I have few unit tests , in which dispatcher.yield() is called as production code had used await Task.Run(() => xyzServiceFunction());
there are many expectations were set using rhinomocks on  xyzservice.

so whenever tests are run for each run different unit test is failing saying it is not recieved expected expectation.

can you help me understanding what is the issue happening 

Thanks in advance

**Comment by rprouse** [comment]
Can you provide us a simple repro so that we can see what you are talking about? Your descriptions doesn't provide us enough information to help you unless we've run into very similar issues in the past which we haven't.

**Comment by rojaadi** [comment]
Below is the method and unit test which I am executing, there are many tests in the solution and facing issues of expecattion  exception at different unit tests for each test run. Individually each test is passing , not able to derive root cause or way to fix it , Kindly help me to analyze it. 
Method to test:-
Public class AttachableAttributes
{
Public AttachableAttributes(){}
 public void StartPolling(object sender, EventArgs e)
        {
            try
            {
                if (!Common.Registry.GetService<IService>().IsServiceBusy())
                {
                    //if the service is not busy stop the timer
                    DisableDispatcherTimer(ServiceBusyStatusTimer);
                    IndicateServiceFree();                    
                    SetAttachableAttributesAsync();
                    UpdateAttachableValuesAsync();
                }
            }
            catch (Exception ex)
            {
                //remove the status for service busy indication
                Status.Clear();
                IsBuysStatusBarIndeterminate = false;
                DisableDispatcherTimer(ServiceBusyStatusTimer);
            }
        }
private async Task SetAttachableGridStatusAttributesAsync()
        {
            try
            {
                if (!(Common.Registry.GetService<IService>().IsServiceBusy()))
                {
                    IndicateDetectorFree();
                    IsAsyncCallRunning = true;
                    var values = await Task.Run(() => GetAttachableStatusAttributesFromService());
                    IsAsyncCallRunning = false;
                    if (values == null)
                    {
                        throw new InvalidOperationException("The array of Attachable  status attributes obtained from service is null");
                    }
                    else
                    {
                        SetAttachableStatusAttributes(values);
                    }
                }
                else
                {
                    IndicateServiceBusy(false);                   
                }
            }
            catch (Exception ex)
            {
                IsAsyncCallRunning = false;
            }
        }
private async Task UpdateAttachableStatusValuesAsync()
        {
            int taskDelayInMilliSecs = 2000;
            try
            {
                while (attachableStatusFlag)
                {
                    if (!(Common.Registry.GetService<IService>().IsServiceBusy()))
                    {                        
                        IndicateDetectorFree();
                        IsAsyncCallRunning = true;
                        var values = await Task.Run(() => GetAttachableStatusValuesFromService());
                        IsAsyncCallRunning = false;
                        if (values != null)
                        {
                            SetAttachableStatusValues(values);
                        }
                    }
                    else
                    {
                        IndicateServiceBusy(false);
                    }
                    await Task.Delay(taskDelayInMilliSecs);
               }
            }
            catch (Exception ex)
            {
                IsAsyncCallRunning = false;
            }
        }       
 private void DisableDispatcherTimer(DispatcherTimer timer)
        {
            if (timer != null)
            {
                //if the timer is not null, stop it first and set it to null
                if (timer.IsEnabled)
                {
                    timer.Tick -= StartPollingWhenServiceIsFree;
                    timer.Stop();
                }
                timer = null;
            }
        }
  private void IndicateServiceFree()
        {
            IsBusyIndicatorProgressBarVisible = false;
            IsBuysStatusBarIndeterminate = false;
            Status.Clear();
        }
 public bool IsAsyncCallRunning
        {
            get; set;
        }
}

Unit test:-
 private IService serviceMockObj;
private AttachableAttributes commandObj;
private string[] stringData = { "Test1", "Test2" };
 private string[] strArrayDataWithMoreValues = { "Test1", "Test2", "Test3" };
[Setup]
Public void Setup()
{
 serviceMockObj = MockRepository.GenerateStrictMock<IService>();
            Common.Registry.RegisterService<IService>(serviceMockObj);
            commandObj = new AttachableAttributes();
}
[Test]
 public void TimerTickWhenServiceBecomesFree()
        {
            serviceMockObj.Expect(d => d.IsServiceBusy()).Return(false).Repeat.Any();
            serviceMockObj.Expect(d => d.GetAttachableAttributes(
                ServiceConstants.FreeServiceIndex)).Return(stringData).Repeat.Any();
            serviceMockObj.Expect(d => d.GetAttachableValues(
                ServiceConstants.FreeServiceIndex)).Return(stringData).Repeat.Any();
            commandObj.StartPollingWhenDetectorIsFree(null, null);
            DispatcherYieldHelper();
            serviceMockObj.VerifyAllExpectations();
        }
        
        [Test]
        public void TimerTickWhenServiceIsBusy()
        {
          serviceMockObj.Expect(d => d.IsServiceBusy()).Return(true).Repeat.Any();
            serviceMockObj.Expect(d => d.GetAttachableAttributes(
                ServiceConstants.FreeServiceIndex)).Return(stringData).Repeat.Any();
            serviceMockObj.Expect(d => d.GetAttachableValues(
                ServiceConstants.FreeServiceIndex)).Return(stringData).Repeat.Any();
            commandObj.StartPollingWhenDetectorIsFree(null, null);
            DispatcherYieldHelper();
            serviceMockObj.VerifyAllExpectations();
        }
private void DispatcherYieldHelper()
        {
            while (commandObj.IsAsyncCallRunning)
            {
                Dispatcher.Yield();
            }
        }

**Comment by jnm2** [comment]
@rojaadi The first step I'd take is to stop sharing any state between the tests. It's very difficult to reason about how any test will perform when it's reusing long-lived objects from other tests.

**Comment by rojaadi** [comment]
Hello ,
The issue suddenly stopped appearing and executed without any errors.
But after few months it emerged again and we found that it was happening due to  multithreading. Identified unit test cases which actually calling multithreading methods and make unit test case to wait and not to run next unit test until child thread not completed its task and should not interfere the mock object of next unit test flow.

Thank you so much for giving your suggestions.
