### ISSUE TITLE
NUnit equivalent to MSTest Assert.AreEqual<T>?

### ISSUE THREAD

**Issue by jez9999** [nunit/nunit#3644]
MSTest has the following method: `public static void AreEqual<T>(T expected, T actual);`

This is a very useful method, and we're using it extensively to test the values of `JToken`s against `string`s without having to add the `JToken.Value<T>()` cruft each time, because there's an implicit `JToken` -> `string` converter defined by Newtonsoft.Json.

Does NUnit provide anything equivalent to this?  I can't see a similar generic method.  If not, I think it should be added.

**Comment by siburny** [comment]
Can you provide a simple unit test script? It would valuable to see your use case.

Documentation for `Assert.AreEqual<T>(T, T)` states:
> Tests whether the specified values are equal and throws an exception if the two values are not equal. **Different numeric types are treated as unequal even if the logical values are equal. 42L is not equal to 42.**

**Comment by siburny** [comment]
Looking the code I see that `StringsComparer` checks the types of both arguments before comparing the values:

https://github.com/nunit/nunit/blob/6a2619e4e5471a9ae515eb8d2803aa69eb902f68/src/NUnitFramework/framework/Constraints/Comparers/StringsComparer.cs#L40-L54

**Comment by NN---** [comment]
@siburny The topic is about compile time check in AreEqual.
Currently NUnit receives object in both parameters.

If you had it generic this would not compile AreEqual(1, “1”)

**Comment by jnm2** [comment]
The NUnit `Assert.AreEqual` method is considered legacy and the team's default position is that we should not add new Assert APIs.

What I would do in this case and in the much larger bucket of cases where there is too much repetitive noise in tests is to extract a helper method. Sometimes to obtain the value to assert against, sometimes to do the assert itself.

**Comment by jez9999** [comment]
@jnm2 If it's legacy, what is meant to be used instead?

**Comment by jnm2** [comment]
@jez9999 The constraint model assertions: `Assert.That(actual, Is.EqualTo(expected));`
(https://docs.nunit.org/articles/nunit/writing-tests/assertions/assertion-models/constraint.html)

Or if you're like me, you use a separate assertion library along with NUnit because you like a third style better than these two.
