### ISSUE TITLE
NUnit Version 2 - Retry of failed tests

### ISSUE THREAD

**Issue by NadeemBader** [nunit/nunit#3648]
Hi
Is that possible to perform retry of failed tests using Nunit version 2?
If yes, can you please assist?
Best Regards,
Nadeem Bader

**Comment by siburny** [comment]
There is no built-in Retry attribute in v2 as I can see

**Comment by mikkelbu** [comment]
I'm closing this issue as answered. The closest thing I could find for NUnit 2 was https://www.nuget.org/packages/NUnit-retry/, but looking at the code and the issues, I don't think that it works (at least not without changes).

**Comment by NadeemBader** [comment]
Thank you very much
