### ISSUE TITLE
Nunit 3 - NunitAddin & IAddin

### ISSUE THREAD

**Issue by NadeemBader** [nunit/nunit#3649]
Hi
I'm wonder why I don't find the attribute NUnitAddin and the interface IAddin in NUnit 3, while they are available in NUnit 2.
Can you please assist?
Best Regards,
Nadeem Bader

**Comment by NadeemBader** [comment]
Answer could be found here: [http://docs.nunit.org/articles/nunit/technical-notes/nunit-internals/specs/Engine-Addins-Spec.html](url)

**Comment by mikkelbu** [comment]
The attributes no longer exists in NUnit 3, and the addin concepts have changed as lot between NUnit 2 and 3 - see e.g. https://github.com/nunit/nunit/issues/2206#issuecomment-304976197, so if you need to migrate an NUnit 2 addin to NUnit 3, then I think we best can help you if you describe what the addin does.

**Comment by ChrisMaddock** [comment]
Closing this, as I think the questions answered. Feel free to comment further if not, the team will still get the notifications. 🙂
