### ISSUE TITLE
I am not able to get total iteration from textcontext..how to run the test case multiple times by getting the test iteration value from excel? 

### ISSUE THREAD

**Issue by gnaneswarreddy** [nunit/nunit#3652]

**Comment by siburny** [comment]
[This blog post](https://jeremybytes.blogspot.com/2015/10/getting-nunit-test-parameters-from-file.html) contains good examples on how to load test case data from a text file.

**Comment by gnaneswarreddy** [comment]
This is not getting the data from text or excel but i have to run the test multiple times after getting the test data from excel, IN MStest we can do that using "textcontext.datarow.table.rows.count" where i get multiple times my test method has been there but Nunit i dont have anything like that.

**Comment by siburny** [comment]
I don't think there is a built-in way. See @CharliePoole answer here: https://stackoverflow.com/questions/51015369/iteration-number-when-using-testcasesource

> Two approaches are possible:
> * Include iteration number as an argument to the method.
> * Use TestCaseData instances rather than object[] for each argument set. TestCaseData allows you to specify a name for the test that can include your interation number if you like.

**Comment by rprouse** [comment]
I'm going to close this as a question. Feel free to post with more info.
