### ISSUE TITLE
Test explorer of Visual Studio integration

### ISSUE THREAD

**Issue by YVEF** [nunit/nunit#3656]
Hi,
It's just a question.
How Visual Studio find tests with [Test] attribute and display it in the test explorer? 
I didn't find any points, that NUnit implement for that in this repository. 
Is it hardcoded in a source code of the Visual Studio?
Thanks.

**Comment by OsirisTerje** [comment]
If you think about the Real Time Discovery, the answer is yes, Visual Studio know about the NUnit attributes.    

When executing however, you need the NUnit3TestAdapter which bridges down to the framework and returns the result to populate the window.

**Comment by YVEF** [comment]
Thank you for the answer. Yes, I'm about real time discovering.
Is there any way to extend such behavior? I mean, I need to discover not only Test attribute by NUnit, but also my custom attributes.

**Comment by OsirisTerje** [comment]
@YVEF If you extend based on the NUnit attributes it *should* work also for the RTD, but since you're asking, I'm assuming it doesn't.  Can you show some code snippets of what you're after ?
