### ISSUE TITLE
Replace multiple project files with a single one

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#366]
It would seem that it would be much easier to maintain things if all the different project files were replaced with a single one, with multiple build configurations for the different platforms.

Currently, the CF build would not be able to be included, but once CF 3.9 was added, it would as well.

**Comment by rprouse** [comment]
The new, but soon to be deprecated `xproj` format allows for this very nicely and all targets are compiled. They said that they wouldn't drop functionality when they update the `csproj` format for .NET Core, so we should revisit this then.

**Comment by CharliePoole** [comment]
This was originally proposed in the context of CF but we more recently talked about it in terms of shared projects. I think we can revise how we build any time in the future but this particular issue has reached the end of it's usefulness and should be closed.

**Comment by ChrisMaddock** [comment]
Agree with Rob that we should definitely happen with the new csproj. Seems like having an issue to track that would be sensible - I'm ambivalent as to whether that's this one, or we create a new one!

**Comment by rprouse** [comment]
I agree that we can close this issue. When I do the .NET Standard port, I will keep this issue in mind, but I don't want to do it the way that was originally proposed with multiple build configurations.
