### ISSUE TITLE
NUnit 3 - XmlResultWriter

### ISSUE THREAD

**Issue by NadeemBader** [nunit/nunit#3660]
Hi
By upgrading the nunit version to v3, I see that XmlResultWriter is missing.
Any suggestions?
Best Regards,
Nadeem Bader

**Comment by ChrisMaddock** [comment]
Hi @NadeemBader,

Not too sure what you're doing with the XmlResultWriter, but, if you're not using the NUnit Engine you probably want to be looking at `IResultService` instead.

You can see how the NUnit Console interacts with it in the source file below, as an example:

https://github.com/nunit/nunit-console/blob/master/src/NUnitConsole/nunit3-console/ConsoleRunner.cs

Hope that helps. I'll close this issue, but let us know if you hit any problems - the team will still get the notifications.
