### ISSUE TITLE
TestContext.CurrentContext.CurrentRepeatCount only contains retry count not the repeat count

### ISSUE THREAD

**Issue by DrHardReset** [nunit/nunit#3662]
While implementing a test which uses Retry and Repeat attributes, I noticed that the property "TestContext.CurrentContext.CurrentRepeatCount" does only count retries but not repeats.

As the name of the property leads to the assumption that repeats will be counted, I open this is issue as an improvement.

**Comment by Antash** [comment]
Addressed by #3696
