### ISSUE TITLE
Instance injection for test class from custom attribute with implementing IApplyToContext

### ISSUE THREAD

**Issue by mcichonqa** [nunit/nunit#3664]
Hello. When I used custom attributes, I encountered two problems and I'm not entirely sure, if it is a lack of my knowledge or if it can not be done as I expected.

1.I created an attribute called "ExtendedAttribute" to include logic in it, e.g. to execute database queries. My custom attribute looks like this: 

```
[AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public class ExternalAttribute : Attribute, IApplyToContext {

public void ApplyToContext(TestExecutionContext context)
        {
            Type testObject = context.TestObject.GetType();  <-- TestObject is null
            FieldInfo[] fields = testObject.GetFields(BindingFlags.NonPublic | BindingFlags.Instance);

            FieldInfo field = fields.First(x => x.IsDefined(typeof(ExtendedParameterAttribute)));

            object instance = Activator.CreateInstance(field.FieldType);
            ExtendedTestParameters parameters = (ExtendedTestParameters)instance;

            field.SetValue(context.TestObject, parameters);
        }
}
```

In ApplyToContext method I implemented my logic, but in addition to performing certain operations, I'd like to inject an instance into a test class like - obj.SetValue(context.TestObject, param).

The problem is "AttributeTargets.Class" for my custom attribute, because this makes it impossible get TestObject from TestExecutionContext instance because its null. 
**Is it possible to add an attribute that will be annotated as AttributeTargets.Class and which will allow instance injection into the test class?**

2. I tried to create a custom attribute for the fields, but the ApplyToContext method does not call. For example:

```
[TestFixture]
public class TestExampleSuite {
[ExtendedFieldAttribute]
public ReferenceRandomType type;

[Test]
public void test () {...}
}
```

The attribute looks like this:
```
[AttributeUsage (AttributeTargets.Field, AllowMultiple = false, Inherited = false)]
public ExtendedFieldAttribute : Attribute, IApplyToContext {...}
```

**Is it possible to annotate fields and thus call the ApplyToContext method?**

Thanks

**Comment by rprouse** [comment]
It sounds to me like you are trying to inject data into your test classes at runtime. If that is the case, you could use the [TestFixtureSource](https://docs.nunit.org/articles/nunit/writing-tests/attributes/testfixturesource.html) attribute on your test classes and inject the data you want into the test class's constructor.

A simple example;

```csharp
[TestFixtureSource(typeof(TestDataProvider), nameof(TestDataProvider.InjectionData))]
public class TestFixtureDataTests
{
    string _injected;

    public TestFixtureDataTests(string injected)
    {
        _injected = injected;
    }

    [Test]
    public void TestInjected()
    {
        Assert.That(_injected, Is.Not.Null.Or.Empty);
    }
}

public static class TestDataProvider
{
    public static IEnumerable<TestFixtureData> InjectionData =>
        new[]
        {
            new TestFixtureData("One"),
            new TestFixtureData("Two"),
        };
}
```

Obviously your `TestDataProvider` would have do more and may only return one item, but it can be used on multiple test classes.

Does this help?

**Comment by mcichonqa** [comment]
Hi, thank you for your answer.

I understand that you can inject variables through the constructor, but I was more concerned with doing it through reflection like field.SetValue(context.TestObject, parameters);

I wanted to achieve something similar to the global extensions in SpockFramework, but this requires "interceptors".
I just want my "type" variable in the test class to have an attribute, something like this:

```
[TestFixture]
public class TestSuiteExample {

[HttpControllerAttribute(port = 447)]
public ReferenceRandomType type;

[Test]
public void test () {...}
}
```

Then the "port" parameter would be passed to the constructor in the HttpControllerAttribute class and then initialize the ReferenceRandomType variable on the appropriate port before performing any test. Is it possible to do something like that?
