### ISSUE TITLE
Nunit console runner not picking up ms tests 

### ISSUE THREAD

**Issue by HyderNBK117** [nunit/nunit#3665]
Hello, I’m creating a cake build script for a CI pipeline. I have multiple solutions that contain Nunit 3, 2 and Microsoft tests. 

How do I configure the console runner to run all these test types in one run? I was able to do this with the vs test console exe, but I want to switch to Nunit3 console runner and OpenCover.

**Comment by rprouse** [comment]
Sorry, we don't have a plugin for NUnit Console to run MSTest or xUnit tests. It currently only runs NUnit 2 and 3 tests.
