### ISSUE TITLE
Filter from runsettings?

### ISSUE THREAD

**Issue by ffMathy** [nunit/nunit#3673]
Is there a way to filter settings from a file (like runsettings) instead of the --filter argument?

**Comment by OsirisTerje** [comment]
Can this https://docs.nunit.org/articles/vs-test-adapter/Tips-And-Tricks.html#where help you?

**Comment by mikkelbu** [comment]
@ffMathy Should I interpret the "thumbs up" as the question has been answered (and thus this issue could be closed)?

**Comment by ffMathy** [comment]
Yes 🙏👍👌
