### ISSUE TITLE
is there any way to make test run last in a test project ?

### ISSUE THREAD

**Issue by amitbarkai** [nunit/nunit#3675]
Hi 

from what i could find till now , i am not sure it is possible , but maybe there is something that I'm missing.
like in any test project we have lots of tests classes ( in our case these are E2E tests that runs on an live system)
when in some tests we need to run a script as a prerequisite that triggers iisreset .
which affect other tests ..
so what we want achieve is running these tests ( tests that triggers iisrest one by one ) after all other tests where executed.

just to be sure my question is clear , currently all tests run in parallel 

thanks

**Comment by rprouse** [comment]
Sorry, no one has suggestions. Closing.
