### ISSUE TITLE
Getting TestMethodCommand.cs not found while debugging Nunit related projects.

### ISSUE THREAD

**Issue by Laxmijha92** [nunit/nunit#3680]
Getting TestMethodCommand.cs not found while debugging Nunit related projects.
Getting many other such issues like Reflect.cs not found.

![image](https://user-images.githubusercontent.com/62870155/100718809-c4f54a80-33e1-11eb-9305-8063193177c1.png)

Getting TestMethodCommand.cs not found

You need to find TestMethodCommand.cs to view the source for the current call stack frame

Locating source for 'D:\a\1\s\src\NUnitFramework\framework\Internal\Commands\TestMethodCommand.cs'. Checksum: SHA1 {ff 16 88 7a d0 2a 97 ca dc 34 58 50 bf e9 f bf 97 cf ba aa}
The file 'D:\a\1\s\src\NUnitFramework\framework\Internal\Commands\TestMethodCommand.cs' does not exist.
Looking in script documents for 'D:\a\1\s\src\NUnitFramework\framework\Internal\Commands\TestMethodCommand.cs'...
Looking in the projects for 'D:\a\1\s\src\NUnitFramework\framework\Internal\Commands\TestMethodCommand.cs'.
The file was not found in a project.
Looking in directory 'C:\'...
Searching for documents embedded in the symbol file.
An embedded document was not found.
The debug source files settings for the active solution indicate that the debugger will not ask the user to find the file: D:\a\1\s\src\NUnitFramework\framework\Internal\Commands\TestMethodCommand.cs.
The debugger could not locate the source file 'D:\a\1\s\src\NUnitFramework\framework\Internal\Commands\TestMethodCommand.cs'.

**Comment by mikkelbu** [comment]
@Laxmijha92 You'll need to provide some more information for us to help you.
* Which version of NUnit are you using
* Are you debugger your own tests and then stepping into NUnit code or are you debugging NUnit directly
* Do you have `Just My Code` disabled in VS, see e.g. https://github.com/nunit/nunit/blob/e3db502f121a9d9bdbf0dca70b2ba55f27365571/CONTRIBUTING.md#confirming-issues

**Comment by rprouse** [comment]
@Laxmijha92 we haven't heard back from you, so I am closing. Please comment if you want this reopened.
