### ISSUE TITLE
#3655 is incorrect

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#3683]
I noted this in #3655, but it appears that a comment on a merged issue is no longer disseminated?

The merged code appears incorrect.

I noted the incorrect code in #3655.

**Comment by stevenaw** [comment]
Thanks @oznetmaster 
I was on the PR and did receive an email notification about your comment, but I hadn't had the chance to respond yet.

As the implementer, can you help me understand a bit about why it's incorrect, or what edge cases wouldn't be covered under the current version?

**Comment by oznetmaster** [comment]
TargetMethods returns all methods defined for the target type, while InterfaceMethods returns only the methods defined on the interface, in this case only Equals.

**Comment by jnm2** [comment]
Isn't the method defined for the target type the one that was wanted there? That's what the original code did.

**Comment by oznetmaster** [comment]
The interface methods are a subset of the target methods.  That are all based on the target type.  Think target type cast to interface and then get methods.

**Comment by oznetmaster** [comment]
Look closely at description of InterfaceMap

**Comment by jnm2** [comment]
> ~~That's what the original code did.~~

Sorry, what I thought was original code was just a previous commit in the same PR.

@oznetmaster I understand what InterfaceMap does. The target method is the implementation method, not the interface method. Could you explain why it is a bad thing for our `EquatableMethodImpl` class to be holding the implementation method instead of the interface method?

**Comment by jnm2** [comment]
> TargetMethods returns all methods defined for the target type, while InterfaceMethods returns only the methods defined on the interface, in this case only Equals.

This doesn't make sense to me. TargetMethods is designed to correlate 1:1 by index with InterfaceMethods. I've long used this member this way.

https://docs.microsoft.com/en-us/dotnet/api/system.reflection.interfacemapping.targetmethods#remarks:

> The elements returned in the InterfaceMethods array match their counterpart elements returned from the TargetMethods array. That is, the elements are in the same array indexing order.

**Comment by oznetmaster** [comment]
It appears that the problem is in the third part implementation of InterfaceMap I was using.

You may remember that all of my work is on WindowsCE and the Compact Framework.

Since the Compact Framework does not support InterfaceMap, I had to use a third party implementation of it.

Apparently, that implementation is faulty.

I am writing my own implementation, which should solve my problem.

Sorry for the noise here.

**Comment by jnm2** [comment]
The noise doesn't bother me. Comments like "Look closely at description of InterfaceMap" do bother me a bit. Those comments say to Steve and me that we don't know what we're talking about when we do. Even if we didn't know what we were talking about, it would be a lot nicer conversing without overtones like that. Does that make sense?

**Comment by stevenaw** [comment]
Thanks @jnm2 for investigating and digging into it.
Thanks @oznetmaster for calling this out too as a concern, though I'm glad in the end we determined there were no bugs introduced in the PR
