### ISSUE TITLE
Inherited tests not using derived class in full name

### ISSUE THREAD

**Issue by hamjo** [nunit/nunit#3684]
I have an issue with test names that is similar to #3671 

When using the pattern {M} as DefaultTestNamePattern in runsettings, the test name does not contain the name of the derived class being run for inherited tests.

Reproduction steps here : https://github.com/hamjo/github-issues/tree/master/nunit/inherited-test-name

**Comment by stevenaw** [comment]
Closing this as I believe it to be a duplicate of https://github.com/nunit/nunit/issues/4446
