### ISSUE TITLE
Clarifying the status of the classic model assertions

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#3688]
Do we document anywhere that we consider the classic model to be legacy? We bring it up in GitHub issues, but people seem to be surprised to learn it, e.g. https://github.com/nunit/nunit/issues/3644#issuecomment-739532642.

https://docs.nunit.org/articles/nunit/writing-tests/assertions/assertions.html hints but doesn't come right out and say it.

1. Is "legacy" the word we want to use?
2. Do we want more folks to know about this designation?
3. Which pages would be good places to get folks' attention?

**Comment by mikkelbu** [comment]
1. I think legacy has a negative sound, so in the analyzers we also use "constraint model" vs "classic model" (and I prefer this to legacy). A comment on nunit/nunit.analyzers#9 states that they where called legacy asserts at some time
> There was a time, about 7 years ago, when I wanted to get rid of Classic asserts. In fact, I was calling them legacy asserts back then. User feedback strongly favored keeping them and so I dropped the goal of dropping them. :-)

2. We can make it more clear, but I can understand why some use the classical model for simple asserts like `Assert.IsTrue(expression)` or `Assert.IsNull(expression)` rather than the longer constraint variant.

3. I think the page that you already link to and perhaps a new page under "Assertion Models" so that one does not end up on "classical models" when expanding the item.

Ps. It also seems like we have much more documentation (at least in the index) for the classical model compared to the constraint model, so I think we should add all the constraint pages, like https://docs.nunit.org/articles/nunit/writing-tests/constraints/AnyOfConstraint.html, to an item under "Constraint model"
![image](https://user-images.githubusercontent.com/1007631/101342144-71bc4580-3882-11eb-9025-bb66cad311b6.png)

**Comment by OsirisTerje** [comment]
About the documentation we have:  I notice that many of the examples we show use the legacy/classic model.  It might be helpful to change those to use the constraint model.

**Comment by stevenaw** [comment]
This came up at work yesterday. Another thing which could be helpful to document when we do this is to describe the reasons why the constraint model is recommended.

**Comment by stevenaw** [comment]
This came up in a recent PR again. @CharliePoole gave the helpful context in the originating issue that the `CollectionAssert` class was at one point considered for removal. Given the maturity of the analyzers and fixers, I'm wondering if this is something we should now consider. Perhaps just marking it as `Obsolete` could also communicate long-term intent.

I'm also wondering if an additional note in the [class documentation](https://docs.nunit.org/articles/nunit/writing-tests/assertions/classic-assertions/Collection-Assert.html) could help too

**Comment by manfred-brands** [comment]
Although I agree that these should be phased out, at my work (and lots of others users) have a considerable set of nunit test that were written for nunit2 using the classic model. Every time we touch the code, we run the nunit.analyzer and convert all classic asserts over to the new model, but some code (whole classes/projects) is simply not touched and the business doesn't budget changing perfectly working test for no reason. Marking them as obsolete prevents us upgrading to the new nunit version for the whole solution as we can only reference a single nuget package for a solution.

**Comment by stevenaw** [comment]
True. I suspect outright removing them could be disruptive. Marking them as obsolete but leaving them in could be less disruptive, but potentially still unpleasant for anyone with a build configured to treat warnings as errors.

I suppose a third option could be inline xmldoc comments on the class so that they show up in Intellisense. I think most devs use Intellisense as a primary way of discoverability for an API and having "something" in the code at class level may also help guide contributors about long-term intent.

**Comment by CharliePoole** [comment]
I imagine that the level of disruption differs for various legacy asserts...

* Classic Asserts like Assert.AreEqual or Assert.Null - even I still use some of these. :-)
* CollectionAsserts - originally aimed at users of MSTest who tended to prefer that syntax
* FileAsserts
* TypeAsserts
* StringAsserts

**Comment by manfred-brands** [comment]
We can put [Editorbrowsable](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.editorbrowsableattribute?view=net-7.0) attributes on any methods we want to phase out. That we they don't show up in Intellisense but compile fine on existing code.

@CharliePoole I think there is less of any issue marking the ...Assets classes as Obsol5

**Comment by stevenaw** [comment]
Good idea about EditorBrowsable.

@manfred-brands  Just to be sure I understand what you are thinking, are you suggesting we mark `CollectionAsserts`, `FileAsserts`, `TypeAsserts`, and `StringAsserts` as obsolete in `4.x` or `3.x`? Were you thinking to add the `EditorBrowsable` at the same time as the `Obsolete` or later?

If we were to wait until `4.x`, what are your thoughts on also doing an unobtrusive xmldoc update in 3.x to start to nudge people away for those that happen to see it, or perhaps clearer language on https://docs.nunit.org/ about these APIs being frozen?

In general my guess would be that the codebases with the highest usage of the "specialized classic asserts" (for lack of a better or more formal term) are also likely older and less frequently updated. My thinking is that a more nuanced or multi-pronged approach could be helpful for them. For example, NUnit 3 first launched over 7 years ago though there are still occasional requests for upgrade support here for those making the move from NUnit 2.

**Comment by OsirisTerje** [comment]
@stevenaw @manfred-brands I like the slowly nudging approach,  hinting to people first to change, so that at least some get the notion it will be deprecated, so all for doing this with the 3.X.  
And agree we should separate them out in the docs, is that something for you @SeanKilleen?

**Comment by CharliePoole** [comment]
@OsirisTerje Something to think about however... If you deprecate in the 4.0 release and remove in the 5.0 release, and if NUnit you continue with the existing pace of major releases (so far 3 in 23 years) then you will be supporting all of these for a long time. That was one reason why we have broken so much in the 4.0 engine branch... to remove stuff we didn't want to support as quickly as possible... :-) 

That's also why I don't think deprecating something should be treated as a breaking change, even though it does affect some users who treat warnings as errors. It's an easy fix to ignore those suppress those warnings if they want to.

**Comment by stevenaw** [comment]
I'm ok with actually marking them as obsolete in `3.x` too, I think this is something we've already done with a few other APIs. I just would advocate for an additional communication medium in this particular case to benefit those who update infrequently.

Which, as I am typing that out, I would suggest that adding something to the docs on https://docs.nunit.org could be ideal as it would live outside the code and could be immediately visible to those who tend to go long periods before updating their dependencies.

**Comment by manfred-brands** [comment]
@OsirisTerje  
> not making the obsolete attributes, but leave that to the analyzer
That would only work if everybody would run the analyzer.
I thought we could put the nunit.framework.dll in a new nunit.framework nuget package and then have the existing nunit package to include both nunit.framework and nunit.analyzers and probably also nunit3testadapter as those are all needed simultaneously. The downside is those packages are updating at different rates. We can update the nunit package when either of the 3 child packages updates, but then we need to figure out version numbering.

I don't know if you saw the discussion about the `Assert.NotNull` needing a `[NotNull]` attribute. The solution we have for them is to use the nunit.analyzer. The person in question hated it as he got 100s of warnings about the classic asserts he was using.
Yes with a few "Quick fix" actions he would have cleaned and modernized his code, but he was very clearly not going to do that.

I think I would be in favour of dropping them completely in 4.x and create a nunit.classicasserts nuget package that will be marked EOL with no future updates.
That way we have a way for people to still compile their old code and we don't have to maintain the old interface.
We can skip the EditorBrowsable attribute step in that case.

**Comment by mikkelbu** [comment]
@manfred-brands suggestion sounds good to me. Also note that EditorBrowsable has been broken for some time - see dotnet/roslyn#4434 - and still are as far as I know

**Comment by stevenaw** [comment]
I had forgotten about the classic asserts, that sounds ideal.

I've been trying to think about if there's any way to use typeforwards for this in the 3.x branch to make the migration path easier for those that need it, but everything I can think of would require all consumers taking the transitive dependency on classicasserts. Which we likely want to avoid.
