### ISSUE TITLE
Drop .NET 4.0 Build Target

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#3708]
.NET 4.0 has been EOL for around five years, so I'd like to drop support for it. This would allow us to clean up our async code.

**Comment by stevenaw** [comment]
I like this idea and am all for simplifying the code base.

One question: Would this be considered a breaking change (or can it be released in NUnit 3.x  ?). Five years EOL is quite a while, I can't imagine many people are still targeting Framework 4.0
