### ISSUE TITLE
Description of --where=EXPRESSION missing from Notes section

### ISSUE THREAD

**Issue by biocoder-frodo** [nunit/nunit#3713]
Last week I used NUnitLite for the first time and after some searching I found the correct syntax for the --where option. I just saw the commit in https://github.com/nunit/docs/pull/540  , which would have been helpful one week ago ;).

Having entered wrong commandline options for nunitlite a few times, I noticed that the DisplayHelp method shows the option description for the --where clause in /src/NUnitFramework/nunitlite/CommandLineOptions.cs, which points to the notes section in /src/NUnitFramework/nunitlite/TextUI.cs, but the actual description is missing from said notes?

For me it would be OK, if the text pointed you towards docs.nunit.org.

**Comment by mikkelbu** [comment]
I think the text output should be extended then it will also make sense if we change the URL at some point.

The problem is that the `--where` option is described as 
```
      --where=EXPRESSION     Test selection EXPRESSION indicating what tests
                               will be run. See description below.
```
but there is no description below which explains this.

**Comment by OsirisTerje** [comment]
@mikkelbu  Pointing to the docs would be helpful, right?  
I believe the correct link would be https://docs.nunit.org/articles/nunit/running-tests/Test-Selection-Language.html

About changing url's, I believe @SeanKilleen is handling these by rerouting when we do it.
