### ISSUE TITLE
TestFilter implementations are all internal

### ISSUE THREAD

**Issue by richard-fine** [nunit/nunit#3714]
The TestFilter implementations in https://github.com/nunit/nunit/tree/master/src/NUnitFramework/framework/Internal/Filters are all `internal` currently.

The filter types in there could be very helpful for people using the execution API - it includes basic logical operators (AndFilter/OrFilter/NotFilter) as well as ValueMatchFilter subclasses for the most common test properties. It's not difficult for users using the execution API to create equivalent filter classes themselves, but it seems like a shame to not let them take advantage of the classes that already exist.

So,
1) Is there any reason why these classes should not, at some point, be made `public`?
2) Assuming that they could be made public, what needs to be done to get them to that point? API review/changes? Tests? Documentation?

**Comment by richard-fine** [comment]
I guess one thing that might need looking at is the use of `TestFilter` vs `ITestFilter`. Classes such as `AndFilter` are using `TestFilter` rather than `ITestFilter`, which would make plugging in other custom ITestFilter implementations impossible. It's not a trivial change because `TestFilter` exposes an overload of `Pass()` that takes a second parameter, and that's not present in `ITestFilter`.

**Comment by mikkelbu** [comment]
The filters were public until approx. 3 years ago, but were made internal. See #2684 and #2931 for the discussions about the filters.

**Comment by richard-fine** [comment]
Thanks. Closing this issue, will open a new one if I have something significant to add to the existing discussions.
