### ISSUE TITLE
Assert.Throws now returns a nullable exception

### ISSUE THREAD

**Issue by yarhamjohn** [nunit/nunit#3717]
We just tried to upgrade from v3.12.0 to v3.13.0 and found that our project stopped building due to warnings about `Deference of a possibly null reference` wherever we used `var ex = Assert.Throws<Exception>(); ex.Message...`.

It seems a bit strange that `Assert.Throws` should return a nullable exception - is there any situation where it would actually return null? If not it would be good for us if it wasn't nullable since we have to add the `!` operator everywhere otherwise which is a bit messy.

**Comment by rprouse** [comment]
@jnm2 can you review this issue and provide your thoughts?

**Comment by manfred-brands** [comment]
`Assert.Throws` returns `null` if there is no exception thrown. Normally nunit would stop further execution, except when run inside an `Assert.Multiple`. There violations are collected until the end. Which means you need to check for `null` in that case. This cannot be solved using declarations, but I can add this to `nunit.analyzer` as a suppression. If the `Assert.Throws` is not run inside an `Assert.Multiple` then the return value is never `null`. The `nunit.analyzer` will tell the compiler that despite the nullable declaration the return value is not `null` and you will therefore not get an error.

**Comment by manfred-brands** [comment]
Note that if you want to check the Message, you can use the constraint variant:

```
Assert.That(() => YOUR.ACTION(), Throws.Exception.With.Message.EqualTo("Expected"));
Assert.That(() => YOUR.ACTION(), Throws.InstanceOf<YOUR.EXCEPTION>().With.Message.Contains("Expected"));
```

**Comment by jnm2** [comment]
@manfred-brands' explanation is exactly what I would have said. `Assert.Throws` is annotated to possibly return null because sometimes it does return null.

**Comment by mikkelbu** [comment]
Note that @manfred-brands have contributed suppression of the "nullability" (if that is a word) of the exception type returned from `Assert.Throws` which is part of the 3.0.0 release of the NUnit Analyzers - https://www.nuget.org/packages/NUnit.Analyzers/3.0.0. 

The release also contains the initial work on suppression of errors due to nullable reference types (suppressed by a check via `Assert.NotNull`, `Assert.IsNotNull` or `Assert.That`)

**Comment by jnm2** [comment]
That's impressive!

Closing since the answer we had previously is "use NUnit.Analyzers or suppress the warning manually," but we can reopen if we start wanting to consider a different path.
