### ISSUE TITLE
Nunit v3 - OneTimeSetup & OneTimeTearDown

### ISSUE THREAD

**Issue by NadeemBader** [nunit/nunit#3721]
Hi

I have the below classes and I need to run the category "CustomCategory1" by executing the code of "PreRun" only once for all 3 tests that belongs to this category (Before all tests starts) and to execute the method "PostRun"only once after running all tests.

By running the following command, I noticed that the PreRun and PostRun called twice (Since we have 2 TestFixture classes):

`C:\Program Files (x86)\NUnit.org\nunit-console>nunit3-console.exe D:\Code\Tests.dll --configfile=D:\Code\App.config --where="cat == CustomCategory1" --labels=All --work=TestResults --out=C:\Logs\TestResult.txt --result=C:\Logs\TestResult.xml`

Can you please assist without changing the name of namespaces?

```
namespace Infra.NUnit
{
    public class TestContextBase
    {
       
        [OneTimeSetUp]
        public virtual void PreRun()
        {
            
        }

        [OneTimeTearDown]
        public virtual void PostRun()
        {
            
        }

        [SetUp]
        public virtual void PreTest()
        {
          
        }

        [TearDown]
        public virtual void PostTest()
        {
           
        }
   }
}
```

```
namespace Tests
{
    public abstract class AbstractTestCase : TestContextBase
    {
        
        /// <summary>
        /// Constructor
        /// </summary>
        public AbstractTestCase() : base()
        { }       

        /// <summary>
        /// Pre Test
        /// </summary>
        [SetUp]
        public override void PreTest()
        {
            base.PreTest();
            Before();
        }

        /// <summary>
        /// Post Test
        /// </summary>
        [TearDown]
        public override void PostTest()
        {
            After();
            base.PostTest();
        }
    }
}

```

```
namespace CTests_Point1
{    
    [TestFixture]
    public class TestV1 : AbstractTestCase
    {
        public TestV1() : base()
        { }
        
        [Test]
        [CustomCategory("CustomCategory1")]      
        public void CData2()
        {

        }        

        [TearDown]
        public void AfterTest()
        {
          //Some functionality
        }

        [SetUp]
        public void BeforeTest()
        {
            //Some functionality
        }
    }
}
```

```
namespace CTests_Point2
{    
    [TestFixture]
    public class TestV2 : AbstractTestCase
    {
        public TestV2() : base()
        { }
        
        [Test]
        [CustomCategory("CustomCategory1")]      
        public void CData3()
        {

        }    

        [Test]
        [CustomCategory("CustomCategory1")]      
        public void CData5()
        {

        }       

        [TearDown]
        public void AfterTest()
        {
          //Some functionality
        }

        [SetUp]
        public void BeforeTest()
        {
            //Some functionality
        }
    }
}
```

Best Regards,
Nadeem Bader

**Comment by antonBrits** [comment]
Have a look at SetupFixture https://docs.nunit.org/articles/nunit/writing-tests/attributes/setupfixture.html 
You can add a class like this:
`namespace Something
{
	[SetUpFixture]
    public class BaseSetupFixture
    {
        /// <summary>
        /// OneTimeSetUp method will run once before any test suites.
        /// </summary>
        /// <returns></returns>
        [OneTimeSetUp]
        public void  OneTimeSetupBeforeAllFixtures()
        {
            
        }

        /// <summary>
        /// OneTimeTearDown method will run once after all test suites.
        /// </summary>
        /// <returns></returns>
        [OneTimeTearDown]
        public void  OneTimeTearDownAfterAllFixtures()
        {
            
        }
	}
}`

**Comment by mikkelbu** [comment]
I'm closing this issue as answered.
