### ISSUE TITLE
SetUpFixture and OneTimeSetUp don't work with .net5

### ISSUE THREAD

**Issue by nkastratovic** [nunit/nunit#3723]
SetUpFixture and OneTimeSetUp doesnt work with .net5

I have class ImportInit marked as SetUpFixture and method Initialize() marked as OneTimeSetUp,
using it to trigger method Init(). 

When run tests it couldn't trigger the Init() method. 
When run in debugging mode the breakpoint in line with TestInit.Init(); is never reached.

This code works properly with .net framework 4.8 but not with .net 5

```
using NUnit.Framework;

namespace IntegrationTest.B_Import
{
	[SetUpFixture]
	public class ImportInit
	{
		[OneTimeSetUp]
		public static void Initialize()
		{
                TestInit.Init();
                }
	}
}
```

**Comment by mikkelbu** [comment]
I could not confirm this, so I think we need some more information. 
* Which version of NUnit (and is it the same version that works with .NET framework 4.8 but not with .NET 5)?
* How are the tests executed (using the nunit-console, VS, or `dotnet test`)
* Are the executed tests in the same namespace as `ImportInit`?

At least when I run the test `MyTest` below in VS (targeting net5.0 and using the NUnit3TestAdapter v. 3.17.0 and NUnit 3.13.0) then the test pass (and I'm also able to stop at a breakpoint inside `Initialize`)

```csharp
using NUnit.Framework;

namespace IntegrationTest.B_Import
{
    public static class Data
    {
        public static int SomeData = 0;
    }

    [SetUpFixture]
    public class ImportInit
    {
        [OneTimeSetUp]
        public static void Initialize()
        {
            Data.SomeData++;
        }
    }

    public class Test
    {
        [Test]
        public void MyTest()
        {
            Assert.That(Data.SomeData, Is.EqualTo(1));
        }
    }
}
```

**Comment by nkastratovic** [comment]
@mikkelbu Thanks a lot, now it works for me, the issue can be closed.
