### ISSUE TITLE
Test start and end time should end with Z

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#3724]
The test start and end time are UTC and should be formatted as such so that they are parsed as UTC by the engine and runners. This causes problems in the Adapter with Explicit tests that are set to `DateTime.MinTime`. They are getting parsed as local which makes the date negative throwing an exception. 

See nunit/nunit3-vs-adapter#811

```
<NUnitTestEvent>
<test-case id='0-1001' name='ExplicitTest' fullname='NUnit3VSIssue811.Explicit.ExplicitTest' methodname='ExplicitTest' classname='NUnit3VSIssue811.Explicit' runstate='Runnable' seed='1980958818' result='Skipped' label='Explicit' site='Parent' start-time='0001-01-01T00:00:00.0000000' end-time='0001-01-01T00:00:00.0000000' duration='0.000000' asserts='0' parentId='0-1000'>
   <reason>
      <message><![CDATA[OneTimeSetUp: https://github.com/nunit/nunit3-vs-adapter/issues/811]]></message>
   </reason>
</test-case>
</NUnitTestEvent>
```

**Comment by mikkelbu** [comment]
We can probably specify that the kind is UTC using `DateTime.SpecifyKind(orgDataTime, DateTimeKind.Utc)`. As far as I can tell all of our "real datetime values" (e.g. values besides `DateTime.MinValue`) are in UTC, so we only need to change the `DateTime.MinValue`s to have the kind `DateTimeKind.Utc` and then we can keep the serialization as it is.

**Comment by KalleOlaviNiemitalo** [comment]
@rprouse, did you close this by mistake? I don't see how <https://github.com/nunit/nunit/pull/3734> relates to the DateTime format.

**Comment by rprouse** [comment]
Yes, thank you. I linked the wrong issue to a PR.
