### ISSUE TITLE
Is it possible to NOT parallelize a single TestCase, in a cluster of TestCases?

### ISSUE THREAD

**Issue by ocmyhome** [nunit/nunit#3725]
Scenario:  I have a test which has several parameterized TestCase attributes associated to it.  I currently have the whole test repo running 5 tests at a time in parallel.  If I run this test, all 4 unique test params/scenarios run in parallel.  Great!  However, is there a way to have one of the parameterized TestCases NOT run in parallel?

Here's what it looks like:

![image](https://user-images.githubusercontent.com/24324485/104649599-3297c600-5672-11eb-9bb2-0ca39dee908e.png)

I want the InternetExplorer TestCase to not run in parallel (it causes problems).  Is there something I can do to target that specific TestCase, to not run in parallel?

**Comment by mikkelbu** [comment]
@ocmyhome I don't know that much about this area, but I would say "no".

The best you can do is to have two separate test methods that call the same (helper) method (which contain the entire test) and then decorate the first test method with the three TestCases and the other test method with the InternetExplorer TestCase and also mark it with `[NonParallelizable]`.

**Comment by ocmyhome** [comment]
Yea, that's what it seems I may have to do.  Appreciate the input.

**Comment by rprouse** [comment]
AFAIK, @mikkelbu's suggestion is the best workaround. I'm going to close this as answered.
