### ISSUE TITLE
Assert EqualTo().Within().Seconds does not work with DateTimes in NUnit 3.13

### ISSUE THREAD

**Issue by smkanadl** [nunit/nunit#3726]
I have several `Asserts` in the following style comparing `DateTime`s to be equal within small amount of time. This worked well in NUnit 3.12.
```Assert.That(DateTime.UtcNow - TimeSpan.FromSeconds(5), Is.EqualTo(DateTime.UtcNow).Within(1).Seconds);```
```
Message: 
      Expected: 2021-01-15 11:44:01.8274509 +/- 00:00:01
      But was:  2021-01-15 11:43:56.8274456
```

Updating to 3.13 is OK when the test passes, but if the test breaks (for whatever reason), I get the following message.
```
Message: 
    System.ArgumentException : Both arguments must be numeric
```
Obviously, NUnit struggles to create the actual message.

Stacktrace:
```
Numerics.Difference(Object expected, Object actual, Boolean isAbsolute) line 447
Numerics.Difference(Object expected, Object actual, ToleranceMode toleranceMode) line 436
TextMessageWriter.WriteDifferenceLine(Object expected, Object actual, Tolerance tolerance) line 330
TextMessageWriter.DisplayDifferences(Object expected, Object actual, Tolerance tolerance) line 181
EqualConstraintResult.DisplayDifferences(MessageWriter writer, Object expected, Object actual, Int32 depth) line 96
EqualConstraintResult.WriteMessageTo(MessageWriter writer) line 82
Assert.ReportFailure(ConstraintResult result, String message, Object[] args) line 381
Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args) line 229
Assert.That[TActual](TActual actual, IResolveConstraint expression) line 210
```

**Comment by mikkelbu** [comment]
I think this is an unfortunate side-effect of #3697. I've placed this report in the milestone that we aim to release in a couple of weeks.

**Comment by smkanadl** [comment]
Many thanks for taking care!

**Comment by Antash** [comment]
@mikkelbu that's a shame :|
Will fix shortly

**Comment by mikkelbu** [comment]
Thanks @Antash 👍. I'll assign the issue to you, please write if you have any questions.

**Comment by Antash** [comment]
@mikkelbu fixed. I'm lucky to face CI issues again though :)

**Comment by manfred-brands** [comment]
I'm facing the same issue, but not with datetime, but with a custom type. Is there a beta feed for nuget I can test before release?

**Comment by mikkelbu** [comment]
@manfred-brands The prerelease feed is here - https://www.myget.org/feed/nunit/package/nuget/NUnit. But looking at the PR I don't think it will help you, as it extends the handling, so that we also handle DateTimes as well as numerics.

Either we should not fail for "unknown" cases or we should handle then generically. Can you provide a small example that reproduces the problem (probably in a new issue).

**Comment by mikkelbu** [comment]
@manfred-brands regarding
> Should we add a rule to nunit.analyzer to complain that .Within is not used and should be removed for non-numeric comparisons?

I think we can create an issue for this. As far as I can tell from the documentation `WithIn` should work with both numerics and DateTimes.
