### ISSUE TITLE
Test project does not reference any .NET NuGet adapter.

### ISSUE THREAD

**Issue by Irvinaby** [nunit/nunit#3727]
I am having a problem running my NUnit test fixtures via VS test runner as well as ReSharper test runner.
Tests end up not running in VS test runner and Incomplete in ReSharper runner after encountering JetBrains.Util.LoggerException.

I am only able to debug my tests using ReSharper test runner. Debugging in VS test runner also fails.

I am having this error as my VS test output:

 Test project a.Test does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
It's recommended to reference NuGet test adapters in each test project in the solution.
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process exited with error: . Please check the diagnostic logs for more information.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.ThrowOnTestHostExited(Boolean testHostExited)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)

I have:

- VS 2019 16.8.4
- NUnit (v3.12.0 via NuGet) 
- NUnit3TestAdapter (v3.16.1 via NuGet)
- ReSharper(2020.3.2)

I have tried:

- Installing Microsoft.NET.Test.Sdk (v16.8.3)
- Installing NUnit.ConsoleRunner
- Updating NUnit and NUnit3TestAdapter to latest stable (v3.13.0 and v3.17.0 respectively)
- Setting processor architecture for AnyCPU Projects to Auto and x64 respectively
- It looks like a duplicate of https://github.com/nunit/nunit/issues/3334 however I wasn't able to confirm any of the fixes there

**Comment by mikkelbu** [comment]
This is probably the wrong repository, as this is related to VS (and thus the adapter). Can you provide the csproj of the test project? Ps. You don't need the `NUnit.ConsoleRunner` to run tests in VS. Also, I think that Resharper has its own adapter and runner, so it should probably only need `NUnit` installed.

Try to create a minimal project that fails.

**Comment by OsirisTerje** [comment]
@mikkelbu @Irvinaby You will need the adapter with Resharper too.   Please upload a small repro project, test file (.cs) and the csproj file.

**Comment by Irvinaby** [comment]
I found out the problem is related is irrelevant to NUnit adapter but due to the fact that VS was not run on admin mode. Thank you for your assistance!
