### ISSUE TITLE
AppVeyor builds failing

### ISSUE THREAD

**Issue by mikkelbu** [nunit/nunit#3729]
The AppVeyor builds have starting failing again, so the solution in #3698 was only a temporary solution, as the failure is similar to the last failures (that netcoreapp3.1 builds fail with `error NETSDK1127: The targeting pack Microsoft.NETCore.App is not installed. Please restore and try again.` / `error NETSDK1127: The targeting pack Microsoft.WindowsDesktop.App is not installed. Please restore and try again.`).

I can see that a new AppVeyor image has been released yesterday - https://www.appveyor.com/updates/2021/01/16/ - which among other contains Visual Studio 2019 version 16.8.4 (see appveyor/ci#3603) which includes `.NET SDK 5.0.102`. So I think the problem is that our install scripts install an old version `5.0.101` on top of a newer version. At least https://github.com/dotnet/runtime/issues/45755#issuecomment-760929942 indicates that there could be issues in this area (but why we are the only one experiencing it I don't know
> @marcpopMSFT @vitek-karas @dsplaisted have we heard of such issues in the past where installing previous shipped SDKs change the behavior of the latest one installed and causes the discussed restore issues?

I'll see if removing the manual installation of `5.0.101` solves the problem (at least it should already be installed in the images we use).

**Comment by rprouse** [comment]
@mikkelbu I was working on NUnit tonight, so I submitted a PR to see if removing the manual install fixes this.

**Comment by mikkelbu** [comment]
@rprouse  I think we also need to do it for Windows in the Azure pipeline, otherwise it will fail when they update their image.

**Comment by rprouse** [comment]
Good idea. I can do that.

**Comment by rprouse** [comment]
Fixed by #3734
