### ISSUE TITLE
C# 9.0 covariant return types break the engine, aboring running the entire test class that contains such code

### ISSUE THREAD

**Issue by AlFasGD** [nunit/nunit#3732]
I was trying to run tests for one class in my library, and it suddenly threw that issue in a class:

```
OneTimeSetUp: System.TypeLoadException : Return type in method '<type>.<function>()' on type '<type>' from assembly <assembly> is not compatible with base type method '<baseType>.<function>()'.
```

I was using NUnit 3.12.0, updated to 3.13.0, and now the tests will not even show a result; I'm assuming the issue silently occurs.

Basically, this issue applies to code of the following pattern:
```csharp
class BaseClass
{
    virtual BaseClass Function();
}
class InheritingClass
{
    override InheritingClass Function();
}
```

For the specific case that I encountered, look at [this commit's](https://github.com/AlFasGD/Garyon/commit/22473fd77375fb1fe4284d6ce1cbc4eb2862d417) description.

**Comment by mikkelbu** [comment]
@AlFasGD It sounds similar to dotnet/runtime#45344 (and related issues). Can you provide a small test samples that reproduces the problem?

**Comment by AlFasGD** [comment]
Yes indeed this is a .NET 5.0 issue; current issue is dotnet/runtime#47007. Closing here.
