### ISSUE TITLE
Nunit 3 - ITestRunner and AppDomain

### ISSUE THREAD

**Issue by NadeemBader** [nunit/nunit#3738]
Hi
In NUnit v2, I was able to create an instance of RemoteTestRunner by assigning the App Domain instance. As shown here:

```
var domain = AppDomain.CreateDomain("Runner Domain");
categoriesRunnerDomain.SetData("APP_CONFIG_FILE", path\to\app.config);
var remoteTestRunner = RemoteTestRunner.CreateInstance(domain, 0);
remoteTestRunner.Load(testPackage);
TestResult testResult = remoteTestRunner.Run(new NullListener(), filter, false, LoggingThreshold.All);
```

But by moving to NUnit v3, I'm not able to create an instance with AppDomain. How can I do it? 
I'm using the code which is shown in the following link: https://stackoverflow.com/questions/48893789/using-nunit-testrunner-with-xml-filter

I need to work with App domain - It is important
Any suggestions?

Best Regards,
Nadeem Bader

**Comment by rprouse** [comment]
Sorry, no one has suggestions. Closing.
