### ISSUE TITLE
c# tests skipped due to "OneTimeSetUp:   Expected: not null   But was:  null" on Mac machines.

### ISSUE THREAD

**Issue by LimingRenPA** [nunit/nunit#3739]
NUnit Adapter 3.17.0.0
NUnit 3.13.0 
DotNet 5.0

Our Visual Studio C# simple NUnit test project does not have OneTimeSetUp anywhere.  

But all the tests are skipped due to errors like below:

```xml
      <Output>
        <StdOut>OneTimeSetUp:   Expected: not null
  But was:  null</StdOut>
        <ErrorInfo>
          <Message>OneTimeSetUp:   Expected: not null
  But was:  null
</Message>
```

We run our tests by "dotnet test" in the root dir. The project builds with no errors or warnings.

Thanks,

**Comment by mikkelbu** [comment]
@LimingRenPA Do you get any stacktraces to make the problem easier to diagnose? And can you provide a minimal project that fails.

Also try to turn up the verbosity (https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test), and/or use a runsettings file (see previous link) to increase 
`InternalTraceLevel` (https://docs.nunit.org/articles/vs-test-adapter/Tips-And-Tricks.html) and perhaps also `DumpXmlTestDiscovery` and `DumpXmlTestResults`.

**Comment by LimingRenPA** [comment]
Thanks for the quick reply. Let me get a  minimal project and more trace info.

**Comment by LimingRenPA** [comment]
It is a bug in our code (test constructor).  Thanks
