### ISSUE TITLE
New syntax for selecting tests to be run

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#374]
Currently, we are still using NUnit 2.x category expressions. We need to define a syntax for selection, possibly similar to what is used for selecting tests in the TestExplorer window. It should be possible to specify tests by

  * name (full or wild-card)
  * arguments
  * categories
  * properties
  * logical combinations of any of these

The syntax should replace the use of category expressions in the console runner command-line using a new option to distinguish it from the --include and --exclude options previously used.

This issue needs to be resolved in two phases:

1. Design the syntax and have it reviewed.
2. Implement it.

**Comment by CharliePoole** [comment]
A number of other issues really depend on this in the sense that we would either not do them or do them differently depending on the outcome of this issue. I'm upping the priority and clarifying that it's in the design stage at this point.

**Comment by CharliePoole** [comment]
Proposed External Syntax for selecting tests. This would be used, for example, in a gui text box or as a command line argument.

A simple filter consists of a key word, an operator and a value or set of values. For example:
    id=123
    name%test
    category=Urgent
    Priority=High

**Key words** are case-insensitive and include id, name, test, fullname, class, method, category and any property names defined on the test. The key word 'test' is a synonym for fullname used for compatibility with the console runner --test option. All values are strings.

Three operators are defined initially:

= tests for equality
!= tests for inequality
% tests for string containment and may be read as 'like'

simple filters may be combined in expressions using &, | and parentheses.
A parenthesized expression may be preceded by unary ! (not)

While we could implement operator - to mean "and not" as in the NUnit 2.x syntax for included and excluded categories, this would make it impossible to use '-' as a part of the name of a catgory.

The general idea here is that an expression formed by the above rules could be used with a --select option on the command line, replacing and extending the current --test, --include and --exclude options. Depending on the host operating system, it might be necessary to put the expression in parentheses when it contains certain characters.

**Comment by CharliePoole** [comment]
The syntax has changed as I have worked on it. In this comment I'm documenting the current state of the parser.This makes earlier comments describing the syntax obsolete, although I'm not deleting them in order to retain a bit of history. I'll update this comment as changes are made until as a basis for the documentation page.

Tests are selected using a --where option (previously called --select) followed by a where clause. Here is the syntax in BNF form...

```
   <where-clause> ::= <filter-expression>

 <filter-expression ::= <filter-term> | <filter-expression> '||' <filter-term>
                                                      | <filter-expression> '|' <filter-term> 

        <filter-term> ::= <filter-element> | <filter-term> '&&' <filter-element>
                                                           | <filter-term> '&' <filter-element>

  <filter-element> ::= <equality> | <inequality> | <match> | <nomatch>

          <equality> ::= <lhs> '==' <rhs> |  <lhs> '=' <rhs>

       <inequality> ::= <lhs> '!=' <rhs>

            <match> ::= <lhs> '=~' <rhs>

          <nomatch ::= <lhs> '!~' <rhs>

                 <lhs> ::= 'cat' | 'category' | 'name' | 'fullname' | 'test' | 'method' | 'class' | 'id'
                             | 'prop:'<prop> | <prop>

               <prop> ::= The name of a property. Use with 'prop:' prefix if it matches a key word.
  
                 <rhs> ::= <word> | <string>

                <string> ::= A character sequence in single or double quotes or between slashes.

                <word> ::= A sequence of letters, digits, underscore, hyphen and dot.

Notes:

1. Synonyms: cat == category, test == fullname, the operators &, | and = may be single or double.

2. Strings are surrounded by single or double quotes or slashes. A string may contain its own terminator if escaped by a backslash.

**Comment by CharliePoole** [comment]
Based on comments on the initial implementation, particularly those from @rprouse , I'm going to make the following changes to the syntax and semantics of the selection language:

1. The **test** keyword, when used for a simple match (equal and not equal) will check both the test name and the full name. It will succeed if either one matches. The regular expression operators =~ and !~ will do the same thing if the expression is anchored at the start. If it is unanchored, then there is no need to check anything except the full test name.

2. The **name** keyword will be eliminated, since the preceding item makes it unnecessary.

3. The **class** and **method** keywords will work just like the **test** keyword, matching either the name or the full name of the class and method respectively.

**Comment by CharliePoole** [comment]
Well, it (previous comment) sounded like a good idea. Rob had suggested that it was quite annoying to have to use the full name of a test. We could try with the full name and then - if nothing was found - try with just the name.

This would work well at the command-line level, triggered when a particular filter found no tests at all. Based on some experiments I have run, it turns out to be rather inconvenient when applied at the lower level. That's because each filter application to a test is separate from every other application. If each filter tries it's hardest to succeed by loosening the restraints, then we may end up with more tests selected than intended.

I think this has to be a separate, future issue. Either the console or the engine would need to recognize that the filter found nothing and then retry, replacing more strict filters by looser ones. In the case where many filters were combined, it might be tricky to decide which ones to loosen.

I've created #884 to remind us to look at this in the future.

Meanwhile, I'm retaining both **test** and **name**.

**Comment by CharliePoole** [comment]
Closed with PR #877

**Comment by oznetmaster** [comment]
I was looking over the code on my iPad, as best I can.

I am confused by the TextRunner.CreateTestFilter method.

Perhaps I misunderstand.  And I cannot run any code.

If there is more than one filter, they are combined with an AndFilter.

Doesn't an AndFilter require that all of its component filters pass to be executed?

If the filters are all FullNameFilters (just a bunch of --test:<name> options), shouldn't they be combined with an OrFilter?  You want a test to run if it matches any of the FullNameFilters, not all of them (which it never will).

I may be way off base, since I am limited in what I can see/do :(

**Comment by oznetmaster** [comment]
It would seem that it should be something like:

```
		/// <summary>
		/// Create the test filter for this run - public for testing
		/// </summary>
		/// <param name="options"></param>
		/// <returns></returns>
		public static TestFilter CreateTestFilter (NUnitLiteOptions options)
			{
			var filters = new List<TestFilter> ();

			foreach (var test in options.TestList)
				filters.Add (new FullNameFilter (test));

			if (filters.Count > 1)
				{
				var orFilter = new OrFilter (filters.ToArray ());
				filters.Clear ();
				filters.Add (orFilter);
				}

			if (options.WhereClauseSpecified)
				{
				string xmlText = new TestSelectionParser ().Parse (options.WhereClause);
				filters.Add (TestFilter.FromXml (TNode.FromXml (xmlText)));
				}

			switch (filters.Count)
				{
				case 0:
					return TestFilter.Empty;
				case 1:
					return filters[0];
				default:
					return new AndFilter (filters.ToArray ());
				}
			}
```

and that the various tests should be  changed accordingly.

**Comment by CharliePoole** [comment]
In fact, I think the code was something like that until I "simplified" it. Apparently, there isn't a test for this combination - or if there is it must be expecting the wrong thing.

**Comment by CharliePoole** [comment]
As you suggest, the tests are wrong as well as the code. Good catch!

**Comment by oznetmaster** [comment]
I am also confused as to where test selection criteria are prioritized.

If there is a Test T1, which has a Category of C1, what happens if the command line is:

--test:T1 --where:category!=C1

**Comment by oznetmaster** [comment]
If you have a lot of items of the same type (e.g. category) it is really tedious to have to use cat=<category>||...  over and over.

Is there any possibility of allowing a comma separated list as the <rhs>, which would be parsed as an implicit OrFilter?

**Comment by CharliePoole** [comment]
It will not be run. This is the same as using test plus exclude. Or as
saying test == T1 && cat != C1. We have to document it, of course.

**Comment by oznetmaster** [comment]
As in the case of the --test options, where lots of tests cause the command line to exceed its maximum size, and hence the --testlist option, the --where option has the same problem.

It seems there is a need for a --wherefile option, which allows the entire where option to be specified in a file.  It could work the same as the --testfile, with the --wherefile option being converted to a --where option in CommandLineOptions.ConfigureOptions method.  File would be read, newlines removed, and then the contents would be set as a --where option value.

**Comment by CharliePoole** [comment]
I'd prefer to introduce a more general way of storing options in a file.

**Comment by oznetmaster** [comment]
See #890

**Comment by oznetmaster** [comment]
--include and --exclude did allow a comma separated list.  That was lost in the new --where syntax

**Comment by CharliePoole** [comment]
Not precisely "lost" - the original implementation included but after a
little discussion, I simplified.

I'm imagining that very few people would use more than two or three
categories in a run, but perhaps there is a use case I'm not thinking of.

We retained --testlist because of it's special use: people generate lists
of tests using external software. And we kept --test simply because it is
so similar to --testlist.

**Comment by oznetmaster** [comment]
I was working on a legacy test suite with 150 categories :(  Tests were always run by a set of categories, sometimes as many as 100 of them at a time.

I did not write it, but someone apparently thought is was a useful way to divide up the tests.

**Comment by CharliePoole** [comment]
In the  first implementation, it was possible to write cat == C1,C2,C3,etc.

I removed that since it's not too difficult to specify cat == C1 || cat ==
C2... for a reasonable number of categories!

Maybe we should just put back the include option. At least it's hard to
imagine anyone wanting to exclude such a large number.

Whatever we do will probably be post-beta-5 however.

**Comment by oznetmaster** [comment]
I think that a comma delimited list should be allowed after the == wherever it makes sense, for consistency.  cat, test, class, method seem to be the ones.

Certainly, if a comma delimited list is allowed after --test:, it would seem consistent to allow it after the test== in the --where option

**Comment by oznetmaster** [comment]
The BNF does not define the syntax for a wildcard.  Are wildcards allowed anywhere, or just in the match/no match operations?

**Comment by CharliePoole** [comment]
I thought about allowing wildcards (* and ?) with == and != but decided to
stick to regular expressions only, triggered by the =~ and !~ operators.
Using the wildcards would be tricky, since they can appear in some of the
fields we want to match against. It would be very confusing to tell users
that the feature is available for some comparisons but not others.

**Comment by CharliePoole** [comment]
Since the and/or confusion is fixed, I'd like to merge this and then deal with the "comma" question separately. Is that OK with you @oznetmaster ?

**Comment by oznetmaster** [comment]
Seems ok to me.  I have not tested it since I am still in Texas.

---Sent from Boxer | http://getboxer.com

On October 15, 2015 at 2:10:44 PM CDT, CharliePoole <notifications@github.com> wrote:Since the and/or confusion is fixed, I'd like to merge this and then deal with the "comma" question separately. Is that OK with you @oznetmaster ?  —Reply to this email directly or view it on GitHub.

**Comment by CharliePoole** [comment]
I have run tests for all platforms, CF included, so I'll go ahead. When you
get a moment, would you mind filing an issue about wanting commas for (at
least) categories?

Charlie
