### ISSUE TITLE
Using IFixtureBuilder, docs or sample?

### ISSUE THREAD

**Issue by lukos** [nunit/nunit#3746]
I am trying to provide dependency injection into a TestFixture class and I understood it was possible to do custom creation of a test fixture with IFeatureBuilder by overridding `BuildFrom()`.

However, I can't find any samples that contain `IFeatureBuilder` (in C#) and the documentation doesn't explain where to use the interface.

I tried creating an attribute that inherited TestFixture to override BuildFrom but BuildFrom is not virtual so that doesn't look correct. I also tried removing the TestFixture attribute and adding the interface directly to my test fixture class but BuildFrom is not called and the output in Visual Studio says that the test host crashed! Same if I add the attribute and the interface directly onto my test fixture.

Can someone point me in the right direction?

**Comment by mikkelbu** [comment]
I've not done this before, but I took a look at the implementation of TestFixtureAttribute - https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Attributes/TestFixtureAttribute.cs - and of NUnitTestFixtureBuilder - https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/Builders/NUnitTestFixtureBuilder.cs - to which it delegates most of the work.

I ended up with the following (note that you probably will need more code from NUnitTestFixtureBuilder, e.g. the delegation to  DefaultTestCaseBuilder, if you want to reuse other parts of NUnit, my implementation is just an example).

When I run this my attribute will pass in `"MyInformation"` in the constructor and it will all mark all public, instance methods as test methods. When I run the tests one will fail - `DoSomethingTest` - and one will pass - `DoAnotherThingTest`.

## MyCustomAttribute.cs
```csharp
using NUnit.Framework;
using NUnit.Framework.Interfaces;
using NUnit.Framework.Internal;
using System;
using System.Collections.Generic;
using System.Reflection;

namespace CustomAttribute
{
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public class MyCustomAttribute : NUnitAttribute, IFixtureBuilder
    {
        public IEnumerable<TestSuite> BuildFrom(ITypeInfo typeInfo)
        {
            var testSuite = new TestSuite(typeInfo, new[] { "MyInformation" });
            foreach (var method in typeInfo.GetMethods(BindingFlags.Public | BindingFlags.Instance))
            {
                if (method.Name.EndsWith("Test"))
                {
                    testSuite.Add(new TestMethod(method));
                }
            }

            yield return testSuite;
        }
    }
}
````

## MyTests.cs
```csharp
using NUnit.Framework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CustomAttribute
{
    [MyCustom]
    public class MyTests
    {
        private readonly string _data;
        public MyTests(string data)
        {
            _data = data;
        }

        public void DoSomethingTest()
        {
            Assert.That(_data, Is.Null);
        }

        public void SomeMethod()
        {
            Assert.Pass();
        }

        public void DoAnotherThingTest()
        {
            Assert.That(_data, Is.EqualTo("MyInformation"));
        }
    }
}
```

**Comment by rprouse** [comment]
Closing as question.
