### ISSUE TITLE
[FeatureRequest] Add a new dictionary constraint

### ISSUE THREAD

**Issue by DamienCassou** [nunit/nunit#3747]
The [Constrains documentation](https://docs.nunit.org/articles/nunit/writing-tests/constraints/Constraints.html#constraints-by-category) discusses 2 dictionary-related constraints:

- [DictionaryContainsKeyConstraint](https://docs.nunit.org/articles/nunit/writing-tests/constraints/DictionaryContainsKeyConstraint.html), e.g., `Assert.That(dictionary, Contains.Key(key));`
- [DictionaryContainsValueConstraint](https://docs.nunit.org/articles/nunit/writing-tests/constraints/DictionaryContainsValueConstraint.html), e.g., `Assert.That(dictionary, Contains.Value(4));`

Usually, what I want to test is that a dictionary contains the right value at the right key, e.g.,

```csharp
Assert.That(dictionary[key], Is.EqualTo(value));
```

I thought nunit could provide something better than the above 2 constraints.E.g.,

```csharp
Assert.That(dictionary, Has.Key(key).MappingToValue(value));
// or
Assert.That(dictionary, Maps.Key(key).ToValue(value));
```

What do you think?

I can have a look at an implementation if you tell me what you want exactly.

**Comment by siprbaum** [comment]
This feature was IMHO discussed in #3470 which lead to PR #3486, implementing 
```
var dictionary = new Dictionary<string, string> { { "Hello", "World" }, { "Hola", "Mundo" } };
Assert.That(dictionary, Does.ContainKey("Hola").WithValue("Mundo"));
```

**Comment by siprbaum** [comment]
Perhaps it is just not documented? Searching for 'KeyValue' on https://docs.nunit.org/articles/nunit/writing-tests/attributes.html came up empty.

**Comment by rprouse** [comment]
I created https://github.com/nunit/docs/issues/548 to document this.
