### ISSUE TITLE
The 'And' filter doesn't work properly

### ISSUE THREAD

**Issue by NadeemBader** [nunit/nunit#3755]
Hi
I'm using nunit3-console.exe tool as shown below;

case 1:

`nunit3-console.exe Tests.dll --configfile=app.config --where="cat==Test1Name and cat==Test2Name" --labels=All --work=TestResults --out=C:\TestResult.txt --result=C:\TestResult.xml
`
case 2:

`nunit3-console.exe Tests.dll --configfile=app.config --where="test==Test1Name and test==Test2Name" --labels=All --work=TestResults --out=C:\TestResult.txt --result=C:\TestResult.xml`

In both cases, the tests doesn't even started, but by changing "**and**" to "**or**" in the **where** clause then the tests run as expected.
Why is that? 

Best Regards,
Nadeem Bader

**Comment by manfred-brands** [comment]
'and' means both, so only a test which is both in category Test1Name and in category Test2Name would run.
'or' means either, so test in category Test1Name and tests in category Test2Name will run.

**Comment by rprouse** [comment]
You haven't responded @NadeemBader so I am assuming your issue has been addressed and am closing this issue.

**Comment by NadeemBader** [comment]
Thank you very much
