### ISSUE TITLE
Feature Request: Some Bag collection in TestContext.

### ISSUE THREAD

**Issue by alex-kulakov** [nunit/nunit#3756]
Is there any interest of having some collection, probably a key-value collection, within ```TestContext```? Let's call it ```Bag```

So the purpose of the bag is to hold something during test method execution (a method marked by ```[TestAttribute]```) and disappear after it automatically. This reminds me of ```Bag``` concept in ASP.Net MVC as a way to pass some data to a view rendering.

I see use case as something like:
```
[SetUp]
public void BeforeTest()
{
  // do some init;
  TestContext.CurrentContext.Bag["uniqueName"] = <some value>;
}

[Test]
public void TheTestItself()
{
  var valueFromSetUp = TestContext.CurrentContext.Bag["uniqueName"];
  // do whatever with the value;
}
```

Now I need to create some fields within class and perform access synchronization for them, which is not good especially for parallel tests execution (I assume each test method execution, sequential or parallel, has access to unique instance of ```TestContext```)

If there was an interest I could contribute it after polishing the concept with repo owners.

**Comment by rprouse** [comment]
As you say, you can easily add a `Dictionary<string, object>` or other collection to your test class and handle that. If you need a unique instance in Parallel tests, then just add `[FixtureLifecycle(LifeCycle.InstancePerTestCase)]` to your test class and a new copy of the dictionary would be created per test.

You state that you would expect a new instance of a `Bag` for each test. We have other features with implicit behaviour like that and even though it is documented, many users expect it to work differently and report issues or file feature requests. Those extra issue reports make it tough for our team of volunteers to keep up. Until I got to the end of your issue, I expected the `Bag` to share data between tests and I expect many users would want that behaviour.

Thanks for the suggestions, but this is an edge case with a fairly easy workaround, so I am going to close.
