### ISSUE TITLE
Re-Add WinForms and WPF based tests

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#3757]
The change to 4.0 and running tests in the NUnitLite test runner removed the test targets that referenced WinForms and WCF. They should be reinstated.

See #3753

**Comment by OsirisTerje** [comment]
@nunit/framework-team Anyone know what needs to be done here?  

I can't see any ignored tests, so have they been deleted over the years, or is this something else?

Will close if no one knows.

**Comment by stevenaw** [comment]
I think this involves getting the test suite running against specifics TFMs.
I recall there being some runtime-specific things like the message pumps which then I am guessing may need the Windows-specific TFM to light up. I'm not 100% certain though

**Comment by OsirisTerje** [comment]
Ok, can it be because, as said in the description, there was a move from something else runner to NunitLite runner, and the NUnitLite runner was not able to run the current test suite so some targets have been removed ?

Have we done anything that could have rectified this?   Seems like this issue just have to wait.

**Comment by stevenaw** [comment]
That makes sense to me on all counts @OsirisTerje 
I think it also then makes sense to change the milestone here if that's what you're suggesting.

**Comment by manfred-brands** [comment]
I found the commit @rprouse is talking about: `Switch to running tests with the NUnitlite runner` (3727fce5f031acb0179c591f455b65703747a9d4)

There is a `UseWindowsFormsAndWPF` conditional which is now no longer set.
Under this conditional are `SynchronizationContext` tests using specific `Windows` versions.

In NUnit4 we DO have an `windows-tests` project which has a `TargetFramework` with the `-windows` suffix.
I will add/move these Windows specific tests to that assembly.
