### ISSUE TITLE
Drop .NET 3.5 Build Targets

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#3758]
Drop the .NET 3.5 build targets for the 4.0 release. Users can remain on 3.13.x releases with bugfixes or target their tests to 4.5+ if they want to upgrade.

**Comment by oznetmaster** [comment]
I fully understand the reasons for this.

It will make it harder, if not impossible, to keep the .NET CF version that I maintain functionally identical to the full .NET version, as is currently the case.

I will have to see if it makes any sense to try to add any 4.0 features to my version.

I will, of course, provide my users with an 3.13.x hotfixes that are released.
