### ISSUE TITLE
nunit3-console.exe - Get tests list based of the specified 'where' clause

### ISSUE THREAD

**Issue by NadeemBader** [nunit/nunit#3763]
Hi
I have the following command line:

nunit3-console.exe Tests.dll --configfile=app.config --where="cat==Test1Name and cat==Test2Name" --labels=All --work=TestResults --out=C:\TestResult.txt --result=C:\TestResult.xml

Is there any option which enable me get the list of tests that will be executed based of the specified "where" clause?

Best Regards,
Nadeem Bader

**Comment by mikkelbu** [comment]
If you just want the tests as a list of test names you can use the following
```
.\nunit3-console.exe --explore:"output.txt;format=cases" Tests.dll --where="cat==Test1Name and cat==Test2Name" ....
```
explore will "Display or save test info rather than running assemblies and projects specified."

**Comment by NadeemBader** [comment]
Great - thank you
But is that possible to get the tests list (As you mentioned) and run that tests within the same command line?

**Comment by mikkelbu** [comment]
You can probably pipe the output into a new call to nunit3-console using the `--testlist` option. But why do you want to do this rather that just run the tests directly?

**Comment by NadeemBader** [comment]
I'm just wonder if that is possible or not.
Again, thank you very much for your help

**Comment by NadeemBader** [comment]
Before closing this issue... I faced 1 issue with the output file.
It contains 2 records for the same same test, and each record contains c# related code:

```
Main_Tests.Tests.Flow._Level1_Flow(System.Collections.Generic.Dictionary`2[System.String,System.String])
Main_Tests.Tests.Flow._Level1_Flow(System.Collections.Generic.Dictionary`2[System.String,System.String])
```

Any idea why?

**Comment by mikkelbu** [comment]
You have a parametric tests that accept a `Dictionary<string, string>` as input. For some types we have some pretty-printing of them when they are used as parameters to tests (e.g. simple types, tuples, arrays ...), but we don't have any special-handling of dictionaries, so for that we just use `ToString()` (and the default implementation of `ToString()` just returns the fully qualified name of the type).

For instance if you have the following
```csharp
...
        [TestCaseSource(nameof(GetData))]
        public void _Level1_Flow(Dictionary<string, string> input)
        {
            Assert.That(input, Is.Not.Null);
        }

        public static IEnumerable<Dictionary<string, string>> GetData()
        {
            yield return new Dictionary<string, string> { { "Key1", "Value1" } };
            yield return new Dictionary<string, string> { { "Key2", "Value2" } };
        }
...
```
then you will get the following as output from `--explore`.
```
ParametricTest.Program._Level1_Flow(System.Collections.Generic.Dictionary`2[System.String,System.String])
ParametricTest.Program._Level1_Flow(System.Collections.Generic.Dictionary`2[System.String,System.String])
```

**Comment by rprouse** [comment]
I am closing since we have not heard back from you. If you have more information, add it to this issue and we will reopen.
