### ISSUE TITLE
nunit3-console.exe - Update Results.xml after each test

### ISSUE THREAD

**Issue by NadeemBader** [nunit/nunit#3768]
Hi

When running the below nunit3-console.exe command, the Results.xml file get updated at the end of the execution. Even its content is not available during the "OneTimeTearDown" method (The method which runs once after all tests). The problem is that I need to read the Results.xml file in the OneTimeTearDown method, but it is not ready, but it is become ready after the OneTimeTearDown method completes.

The command line:

`nunit3-console.exe Tests.dll --configfile=app.config --where="cat==Test1Name and cat==Test2Name" --labels=All --work=TestResults --out=C:\Result.txt --result=C:\Result.xml`

Is that possible to make content of Results.xml updated after each test? So I can access them during the run?

Best Regards,
Nadeem Bader

**Comment by mikkelbu** [comment]
Hi @NadeemBader 
It is not possible at the moment, and is complicated due to the nested structure of the XML and parallel test execution, see e.g. #2549 or #1514.

Why do you need to access the Results.xml file in the "OneTimeTearDown" method?

**Comment by rprouse** [comment]
I am closing since we have not heard back from you. If you have more information, add it to this issue and we will reopen.
