### ISSUE TITLE
Remove code marked "Obsolete"

### ISSUE THREAD

**Issue by stevenaw** [nunit/nunit#3769]
Given the main branch is now targeting 4.0, there is an opportunity to clean up and remove deprecated code. We should remove any types of members marked with the "Obsolete" attribute.

**Comment by rprouse** [comment]
I agree, but I'd like to come up with a list and evaluate each. I'd like to make sure that we made the right decision deprecating everything.

We're probably good and don't need to discuss everything, but some things might still be widely used.

**Comment by stevenaw** [comment]
Good point. I've put together a list below of what's currently decorated with "Obsolete".

### Types

[AssertionHelper Type](https://github.com/nunit/nunit/blob/ad49f27294bd0f2677d8699756c6ccb10df600f8/src/NUnitFramework/framework/AssertionHelper.cs#L36)

[FileExistsConstraint type](https://github.com/nunit/nunit/blob/ad49f27294bd0f2677d8699756c6ccb10df600f8/src/NUnitFramework/framework/Constraints/FileExistsConstraint.cs#L33)

[DebugWriter type](https://github.com/nunit/nunit/blob/f94e9e15d408443bc9f7b36c90eb0d2053f5f721/src/NUnitFramework/nunitlite/DebugWriter.cs)

[DataAttribute type](https://github.com/nunit/nunit/blob/ad49f27294bd0f2677d8699756c6ccb10df600f8/src/NUnitFramework/framework/Attributes/DataAttribute.cs#L35)

[List type](https://github.com/nunit/nunit/blob/ad49f27294bd0f2677d8699756c6ccb10df600f8/src/NUnitFramework/framework/List.cs#L35)

[ListMapper type](https://github.com/nunit/nunit/blob/ad49f27294bd0f2677d8699756c6ccb10df600f8/src/NUnitFramework/framework/ListMapper.cs)
- [And some references](https://github.com/nunit/nunit/blob/ad49f27294bd0f2677d8699756c6ccb10df600f8/src/NUnitFramework/framework/AssertionHelper.cs#L145)

### Members

DictionaryContainsKeyConstraint
- [IgnoreCase](https://github.com/nunit/nunit/blob/ad49f27294bd0f2677d8699756c6ccb10df600f8/src/NUnitFramework/framework/Constraints/DictionaryContainsKeyConstraint.cs#L101)
- [Using Predicate overloads](https://github.com/nunit/nunit/blob/ad49f27294bd0f2677d8699756c6ccb10df600f8/src/NUnitFramework/framework/Constraints/DictionaryContainsKeyConstraint.cs#L146-L230)

String Starting/Containing/Ending/Matching functions (replaced by StartsWith/Contains/EndsWith/Matches overloads)
- [AssertionHelper StringContaining](https://github.com/nunit/nunit/blob/ad49f27294bd0f2677d8699756c6ccb10df600f8/src/NUnitFramework/framework/AssertionHelper.cs#L724-L746)
- [ConstraintExpression StringContaining](https://github.com/nunit/nunit/blob/71422c08dd541dd3757d3d83fb8df1db823b7bde/src/NUnitFramework/framework/Constraints/ConstraintExpression.cs#L805-L827)
- [ConstraintExpression StringStarting](https://github.com/nunit/nunit/blob/71422c08dd541dd3757d3d83fb8df1db823b7bde/src/NUnitFramework/framework/Constraints/ConstraintExpression.cs#L854-L857)
- [ConstraintExpression StringEnding](https://github.com/nunit/nunit/blob/71422c08dd541dd3757d3d83fb8df1db823b7bde/src/NUnitFramework/framework/Constraints/ConstraintExpression.cs#L885-L889)
- [ConstraintExpression StringMatching](https://github.com/nunit/nunit/blob/71422c08dd541dd3757d3d83fb8df1db823b7bde/src/NUnitFramework/framework/Constraints/ConstraintExpression.cs#L936-L940)

RuntimeType
- ["Net" value](https://github.com/nunit/nunit/blob/ad49f27294bd0f2677d8699756c6ccb10df600f8/src/NUnitFramework/framework/Internal/RuntimeType.cs#L39-L40)

CollectionContainsConstraint 
- [Constructor](https://github.com/nunit/nunit/blob/ad49f27294bd0f2677d8699756c6ccb10df600f8/src/NUnitFramework/framework/Constraints/CollectionContainsConstraint.cs#L41)

Timeout Command
- [Constructor](https://github.com/nunit/nunit/blob/ad49f27294bd0f2677d8699756c6ccb10df600f8/src/NUnitFramework/framework/Internal/Commands/TimeoutCommand.cs#L54)

WorkItemBuilder
- [CreateWorkItem overload](https://github.com/nunit/nunit/blob/ad49f27294bd0f2677d8699756c6ccb10df600f8/src/NUnitFramework/framework/Internal/Execution/WorkItemBuilder.cs#L47)

SimpleWorkItem
- [Constructor](https://github.com/nunit/nunit/blob/c7afecbd7ce0c5176bae672d684ceb96fb22fd30/src/NUnitFramework/framework/Internal/Execution/SimpleWorkItem.cs#L50)

NUnitEqualityComparer
- [Default](https://github.com/nunit/nunit/blob/34e3cd9779819385a9f5b96405b7203982ecf8bc/src/NUnitFramework/framework/Constraints/NUnitEqualityComparer.cs#L98)

NUnitLite OptionSet
- [GetOptionForName](https://github.com/nunit/nunit/blob/ad49f27294bd0f2677d8699756c6ccb10df600f8/src/NUnitFramework/nunitlite/Options.cs#L527)

**Comment by stevenaw** [comment]
@nunit/framework-team can I ask your thoughts on what of the above code should be removed (if any)
