### ISSUE TITLE
IsEquivalent on default ImmutableArray throws exception.

### ISSUE THREAD

**Issue by manfred-brands** [nunit/nunit#3772]
NUnit version 3.13.0

An ImmutableArray is a structure, but can contained a null array.
The following test fails with an InvalidOperationException: _This operation cannot be performed on a default instance of ImmutableArray<T>_

```
ImmutableArray<string> expected = ImmutableArray.Create("Test");
ImmutableArray<string> actual = default(ImmutableArray<string>);

Assert.That(actual, Is.EquivalentTo(expected));
```

Same for `Assert.That(actual, Is.Not.Empty);`

It is a pity that Microsoft doesn't treat this the same as `ImmutableArray<string>.Empty`.

**Comment by mikkelbu** [comment]
It is a bit unfortunate that we need to have special cases for all these structures, but I think we should also handle this.

**Comment by stevenaw** [comment]
Agreed, this is unfortunate.
Should `default(ImmutableArray<T>)` be treated as semantically equivalent to `Empty` or to `null`? NUnit makes a distinction between these for reference-type collections:

```csharp
string[] expected = Array.Empty<string>();
string[] actual = null;
Assert.That(actual, Is.Not.EqualTo(expected));
```

Though I would also find it unusual for the following test to pass:

```csharp
Assert.That(default(ImmutableArray<string>), Is.Null);
```

I wonder if this is case solved via a DefaultConstraint (https://github.com/nunit/nunit/issues/3457) ?

**Comment by manfred-brands** [comment]
It looks like `Assert.That(default(ICollection), Is.Empty)` throws an `ArgumentException`. _The actual value must be a string, ..._
and `Assert.That(default(ICollection), Is.EquivalentTo(Array.Empty<string()))` throws with mesage _Expected IEnumerable But was: null_

So it looks like in all cases, one would need to check for `null` (or Default) first, so maybe this does not need changing in NUnit.
In my case that would mean inserting an `Assert.That(actualValue.IsDefault, Is.False)` or use the new DefaultConstraint when available.

**Comment by jnm2** [comment]
I don't think NUnit should treat `default(ImmutableArray<T>)` as though it was `ImmutableArray<T>.Empty`. This will hide problems in my code.

**Comment by stevenaw** [comment]
I'm unsure if there's still interest in this getting fixed, but I noticed that we solved a similar case in the `EqualConstraint` for `ArraySegment` in the past in #477

**Comment by stevenaw** [comment]
I haven't checked the scenarios described in https://github.com/nunit/nunit/issues/477#issuecomment-73454620 for `ImmutableArray` but if they _don't hold_ here then I'm wondering if this should be closed given the presence of `Is.Default` and @jnm2 's points above

**Comment by jnm2** [comment]
This type of error is an occupational hazard of using default structs which themselves through these exceptions when you call through IEnumerable interfaces on them, not unique to NUnit. We could always provide hints added onto assertion messages if we detect a misunderstanding though.

**Comment by manfred-brands** [comment]
Note that the [`IsEmpty`](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray_1.Minimal.cs#L157) property on `ImmutableArray` will throw a `NullReferenceException`: 
```csharp
get { return this.array!.Length == 0; }
```

There is even a comment on the [`Length`](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray_1.Minimal.cs#L169) property: `We intentionally do not check this.array != null, and throw NullReferenceException if this is called while uninitialized.`

**Comment by stevenaw** [comment]
I agree that NUnit special casing "empty" doesn't make sense here. I'm a little less sure about the "Equivalent" case.

Perhaps it's just me, but I've always thought of NUnit collection equivalence as a looser form form of collection equality in that all the same rules apply _except_ ordering doesn't matter with equivalence. From that perspective, I would expect that any test which passes for `Is.EqualTo()` to also pass for `Is.EquivalentTo()`. However it seems neither `ArraySegment<>` or `ImmutableArray<>` follow this.

In other words, the below tests apply what I would consider increasingly looser equality definitions and so I would not expect the second or third assertion to ever fail if the first passes. An interesting note here is that not only does the third fail in both, they also do not output the custom message that I would expect.

```csharp
[Explicit, Test]
public void TestImmutableArray()
{
    var a = default(ImmutableArray<int>);
    var b = default(ImmutableArray<int>);

    Assert.That(a.Equals(b), "Not equals");
    Assert.That(a, Is.EqualTo(b), "Not NUnit equals");
    Assert.That(a, Is.EquivalentTo(b), "Not NUnit equivalent");
}

[Explicit, Test]
public void TestArraySegment()
{
    var a = default(ArraySegment<int>);
    var b = default(ArraySegment<int>);

    Assert.That(a.Equals(b), "Not equals");
    Assert.That(a, Is.EqualTo(b), "Not NUnit equals");
    Assert.That(a, Is.EquivalentTo(b), "Not NUnit equivalent");
}
```

**Comment by jnm2** [comment]
Perhaps Is.EquivalentTo could first check EqualityComparer<T>.Default.Equals and return true if that returns true?

**Comment by stevenaw** [comment]
I think that's a nice easy win for the happy path here, for all types :)

If we're in agreement on approach here for the equivalent scenario, I'd like to suggest this again as a `good first issue`.

**Comment by mr-sergito** [comment]
Hey guys, I'd like to try to work this one out 😊

In order to have `Is.EquivalentTo` to first check `EqualityComparer<T>.Default.Equals` we'd need to add this check at [`CollectionEquivalentConstraint.Matches`](https://github.com/nunit/nunit/blob/af7b9413f9cb7b5780753db6edd1ec7ef0a4ffe1/src/NUnitFramework/framework/Constraints/CollectionEquivalentConstraint.cs#L42) before the Tally initialization right? Which is what fails when trying to apply the [`CollectionTally.ToList`](https://github.com/nunit/nunit/blob/af7b9413f9cb7b5780753db6edd1ec7ef0a4ffe1/src/NUnitFramework/framework/Constraints/CollectionTally.cs#L73) to the uninitialized IEnumerable. Should we try to prevent this method from failing with such argument?

**Comment by stevenaw** [comment]
Thanks @mr-sergito ! We'd definitely welcome your contribution here.
That's right :) Effectively we'd be adding a "fast path" here where, if `EqualityComparer<T>.Default.Equals()` returns true would then allow us to skip the relatively more expensive `CollectionTally` operations altogether - which in the process should also then fix the issue when trying to compare equivalency of two `default(ImmutableArray)`s.

**Comment by mr-sergito** [comment]
So adding the following [commit](https://github.com/nunit/nunit/commit/70984b0abc13821a55bbc0afc9bfd463cfd4d7b5) would solve the scenarios mentioned [here](https://github.com/nunit/nunit/issues/3772#issuecomment-2325159917). 

However, it'd still fail [here](https://github.com/nunit/nunit/blob/af7b9413f9cb7b5780753db6edd1ec7ef0a4ffe1/src/NUnitFramework/framework/Constraints/CollectionTally.cs#L132) whenever either of the collections is default and the other isn't. 
Should we handle these cases somehow?

**Comment by jnm2** [comment]
My leaning is still to let it crash, since this not an issue specific to NUnit but is just how the ImmutableArray type implements the collection interfaces. You'll see the same issue everywhere, including with LINQ methods.

**Comment by stevenaw** [comment]
I'm in favor of that too. I suspect most usages here seek happy path "is equivalent" behavior which this now permits. 
An equivalency test receiving a default + non-default ImmutableArray or a "not equivalent" test with the same data would likely be much rarer and, as @jnm2 points out, also liable to exceptions within parts of the BCL

**Comment by manfred-brands** [comment]
I also think we shouldn't deal with uninitialized ImmutableArray as it would be hiding potential errors in real scenarios.
