### ISSUE TITLE
TestCaseSource

### ISSUE THREAD

**Issue by PierreLemmel** [nunit/nunit#3776]
In a .Net5 / WPF project I have the following test:

  ```
[Test]
[TestCaseSource(nameof(DeconstructTestCaseData))]
public void Deconstruct_Deconstruct_Tuples_Into_Separated_Arrays2((string, int)[] input, string[] expectedArray1, int[] expectedArray2)
{
    (string[] array1, int[] array2) = input.Deconstruct();

    Check.That(array1).IsEquivalentTo(expectedArray1);
    Check.That(array2).IsEquivalentTo(expectedArray2);
}

public static IEnumerable<object[]> DeconstructTestCaseData => new object[][]
{
    new object[]
    {
        new (string, int)[]
        {
            ("Hello", 1),
            ("World", 2),
            ("!!!!", 4),
            ("olleH", 8),
            ("dlroW", 666),
        },
        new string[]
        {
            "Hello",
            "World",
            "!!!!",
            "olleH",
            "dlroW",
        },
        new int[]
        {
            1,
            2,
            4,
            8,
            666,
        }
    },
};
```

I expect this test source to provide only one test case. But the discoverer discovers two tests :
![discoverer](https://user-images.githubusercontent.com/6038760/109009696-21999600-76af-11eb-9902-3731a0853d41.PNG)

The second test runs ok, but the first one gives the follwing error (in french, sorry for that):
Une exception s'est produite durant l'appel de l'exécuteur 'executor://nunit3testexecutor/' : Format incorrect pour le TestCaseFilter Erreur : condition non valide 'FullyQualifiedName=PewPew.Tests.Helpers.TuplesShould.Deconstruct_Deconstruct_Tuples_Into_Separated_Arrays2,,,,],["Hello", "World", "!!!!", "olleH", "dlroW"],[1, 2, 4, 8, 666]'. Spécifiez le format approprié, puis réessayez. Notez que si le format est incorrect, aucun test n'est exécuté.

This error prevents me from executing all the tests.

Since I only have one test-case, I hard-coded my inputs in my test, so it's not a problem anymore, but it is still a strange behaviour :-)

**Comment by mikkelbu** [comment]
@PierreLemmel Which version of NUnit and which version of the NUnit Adapter? I just tried it locally - and on my machine it works (I guess that you are running the tests using the Test Explorer in VS?)

**Comment by PierreLemmel** [comment]
@mikkelbu your guess is right, I use Test Explorer in VS :-)

My project uses nunit 3.12.0 with adapter 3.15.1

I upgraded packages to 3.13.1 and 3.17.0 and still have the same problem

**Comment by mikkelbu** [comment]
@PierreLemmel I think the problem is that you have enabled "Test Discovery" (can be found under "Tools => Options... => Test => General). If I enabled this, then I get the same behaviour as you.

See https://github.com/nunit/nunit3-vs-adapter/projects/1#card-37570678 for more problems related to "Test Discovery".

@OsirisTerje Should we transfer this issue to the NUnit Adapter project, or is this issue duplicating one of the existing issues.

**Comment by PierreLemmel** [comment]
@mikkelbu indeed it solved the issue, thanks :-)
