### ISSUE TITLE
How to expect unhandled exception in a non-test thread?

### ISSUE THREAD

**Issue by IgorBuchelnikov** [nunit/nunit#3783]
My test starts a thread. That thread should stop with an unhandled exception.  I test that case is properly processed. 
Thus stopping the thread with an unhandled exception is expected. Problem is that my test always fails with the unhandled exception in the started non-test thread. I run the test using `dotnet test` in the Linux environment.

**Comment by rprouse** [comment]
To me, you are trying to do too much in your test. Ideally, each unit test should test as little as possible. In this case, you are testing running code on a background thread and you are testing errors on that background thread. Ideally, you would split that up into a test that ensures a thread is created and another that tests the error on the test thread.

I don't know your code though and there may be reasons that you need to test this way. If that is the case, then how are errors on your background thread handled in production? If they are throwing unhandled exceptions in this error case, aren't they also failing on production and crashing your app or putting it in a bad state? Shouldn't you be catching those exceptions and reporting them back to the thread that created them?

**Comment by IgorBuchelnikov** [comment]
My fail. My code will only work properly with
```
  <runtime>
    <legacyUnhandledExceptionPolicy enabled="1"/>
  </runtime>
```
