### ISSUE TITLE
NUnit with dotnet test results in O(n^2) filtering complexity

### ISSUE THREAD

**Issue by pakrym** [nunit/nunit#3786]
The usual pattern for `dotnet test` when invoking test is to pass an Or filter with a FullNameFilter for every test it wants to run.

To check if the Or filter matches the test we need to iterate over every child filter and do it for every test in the project that results in O(n^2) time complexity. It's not noticeable on small projects but is very noticeable on large ones (9000+ tests). 

One solution is to reduce the OrFilter that only has FullNameFilter to a HashSet-based filter that would reduce overall complexity to O(N). I prototyped it in https://github.com/nunit/nunit/pull/3787 

For real-world data, the https://github.com/azure/azure-sdk-for-net/blob/1814567d1f6cfb4905539e71d54377ab46ed6737/sdk/storage/Azure.Storage.Blobs takes 80 sec to run but only 40 with the fix from the https://github.com/nunit/nunit/pull/3787.

Considering tests themselves take ~ 25-30 sec to run it's a 5X filter time improvement.

**Comment by mikkelbu** [comment]
Hi @pakrym 

I thought that your issue sounded like something I had seen somewhere, and after some digging I found nunit/nunit3-vs-adapter#660. Close to the end of this issue it is mentioned that version 4 of the adapter solves this issue (or at least to some degree). Would it be possible for you try out the prerelease of the adapter to see how it affects the performance?

That being said I think your contribution still provides value. @nunit/framework-team do you agree?

**Comment by pakrym** [comment]
I'm happy to try the 4.0.0.

On the other hand, this might improve the performance enough that AssemblySelectLimit can be increased to a much higher number without a performance impact.

**Comment by pakrym** [comment]
Ping @jnm2 @rprouse, happy to implement the optimization if you can comment with the way you'd like to see it.

**Comment by rprouse** [comment]
@pakrym sorry for the delay. I would appreciate the help with this. I will try and take a closer look today or tomorrow.

**Comment by rprouse** [comment]
@pakrym I've looked at your code so far and I'm fine with the approach you are taking. Thanks for the help.

**Comment by kasobol-msft** [comment]
@rprouse My team suffers from this problem. I.e. we have large test suite that takes long time to spin. Could this be prioritized? What's the timeline to release nunit with this fix?

**Comment by rprouse** [comment]
@kasobol-msft PR is in for this and should be merged soon. I need to take a look at what is outstanding for a 3.13 release, but it should be out soon. If needed, you can use a CI/CD build from MyGet once the RP is merged.

**Comment by rprouse** [comment]
Closing, PR has been merged. I will also forward port to master.

**Comment by pakrym** [comment]
@rprouse, is the https://www.myget.org/feed/nunit/package/nuget/NUnit the feed you are referring to? It doesn't seem to have new builds from the 3.13.x branch.

**Comment by rprouse** [comment]
@pakrym yes that is the feed. Sorry, we haven't setup the 3.13 branch to deploy there, didn't think about that. I will add an issue to do so. Meanwhile, you can take the latest from master once the other PR is merged. There are no substantive changes on master that you should worry about. I'm also planning on doing a 3.13 release within a week or so.

**Comment by rprouse** [comment]
Cherry-pick to master has been merged. Once it is built and deployed to MyGet, you can test if you like.

**Comment by pakrym** [comment]
Hm, when using the older
```
    <PackageReference Update="NUnit" Version="4.0.0-dev-07093" />
    <PackageReference Update="NUnit3TestAdapter" Version="4.0.0-dev-01695" />
```

or the latest
```
    <PackageReference Update="NUnit" Version="4.0.0-dev-07101" />
    <PackageReference Update="NUnit3TestAdapter" Version="4.0.0-dev-01695" />
```

Many of our test assemblies don't get their tests discovered.

**Comment by dmitry-lipetsk** [comment]
v3.13-dev now works fine (29155 tests). Thanks.

**Comment by rprouse** [comment]
If anyone needs to use the MyGet feed, 3.13.x is now deploying there, https://www.myget.org/feed/nunit/package/nuget/NUnit/3.13.2-ci-07105-v3-13-dev

I am also planning on doing a 3.13.2 release very soon.

@pakrym can you test with the 3.13 MyGet build and with a more stable release of the adapter? I want to rule out the adapter as the issue you are having.

**Comment by pakrym** [comment]
Can't restore with the version set to `3.13.2-ci-07105-v3-13-dev` and your link requires auth.

**Comment by rprouse** [comment]
Sorry about that @pakrym. I'm looking into the 3.13 feed issue, but I don't see anything yet.

**Comment by rprouse** [comment]
The MyGet feed is fixed. I confirmed using an In-private window 😸 

https://www.myget.org/feed/nunit/package/nuget/NUnit/3.13.2-dev-07107

**Comment by pakrym** [comment]
@rprouse thank you. This time it worked, all tests were discovered.

**Comment by rprouse** [comment]
@kasobol-msft the fix for this has been released, https://github.com/nunit/nunit/releases/tag/v3.13.2
