### ISSUE TITLE
Best way to perform actions per-test-fixture before loading test assembly?

### ISSUE THREAD

**Issue by svengeance** [nunit/nunit#3793]
Hey all -

I'm looking at dockerizing my test execution. What I want to do is -

**For Each Test Fixture**
\> Build Docker Container
\> Copy Test Assembly Into Container
\> Execute Test Assembly
\> Report Execution
\> Tear Down Container

This is proving a little difficult. I tried messing with writing an `IFrameworkDriver` extension, but that's an on assembly-wide basis, and I'm only looking at grouping tests by TestFixture. I'd had a thought of trying to filter tests by Fixture and then calling `NUnitNetCore31Driver` on each group of fixtures, but that likely won't play nice with reporting to the Test Explorer UI.

I also wouldn't mind doing this in a base TextFixture, but I think that's likely to get a little hairy because by the time I get to a fixture, _my test is already running_.

I'd like to have this work nicely with `dotnet VsTest`, `dotnet test`, and the Test Runner inside of Visual Studio if possible.

Any advice on where I can go?

Thank you!

**Comment by svengeance** [comment]
Something cute I noticed I can do is **limit** what the driver runs, and that does seem to work actually. So if the filter is `<or><test1><test2></or>` and I artificially limit it down to `<test1>`, `<test2>` is never ran or reported.  
The problem is that I don't know how to grab the Fixture from these test names. I suppose I have access to the `TestAssemblyPath` and I could load the assembly, find the class that matches the FQN of the method `<test1>` and then load all methods underneath it?

A lot of this is manual and I feel like I'm going about it the hard way.

**Comment by rprouse** [comment]
Personally, I think you are trying to do this at the wrong level. The way you are trying to do it, your tests are already running on the host machine, you will then copy the test assembly into the container and run them again. I would move the functionality you are trying to write out a layer to the test adapter.

If you want to run tests using vstest, dotnet test and Visual Studio, then to me, you should be creating a test adapter like the NUnit3 Test Adapter. The adapter would be responsible for setting up your docker container, copying your tests into it, running them and collecting the results to generate reports. If you do this, it would work with any NUnit tests, you would just need to add a refeerence to your adapter instead of ours.

**Comment by svengeance** [comment]
Heh, I was afraid I'd have to dive a little deeper than some NUnit extension points. Oh well, I tried.

> If you do this, it would work with any NUnit tests, you would just need to add a refeerence to your adapter instead of ours.

What do you mean by this? I'm not _too_ familiar with the topology of the VS Testing ecosystem (I'm just trying to figure out the Path of Least Pain here), could I essentially copy-paste a majority of NUnit's adapter, modify it for my needs, and then have it go about its normal functionality?

**Comment by svengeance** [comment]
If you think that is largely unnecessary (to repeat most of NUnit Adapter's code), _by chance_ do you have any recommended reading in this area that I could use as a basis? Quite a few of the blogs/github topics I've read lament about the poor documentation when it comes to interoperability with the VS Testing Ecosystem 😭

**Comment by svengeance** [comment]
@rprouse I was able to get this working with the following code: https://github.com/svengeance/nunit3-vs-adapter/commit/0b3dddfe719726f58c9886b6ef0e5bb819b67679

Husky is a pet project of mine that isn't yet public, but part of the e2e testing relies on being able to execute code in a throwaway environment per-fixture.

Thanks for the advice, and thanks @jnm2 who kindly helped me a bit as well. I will do my best to give back where I can with the adapter now that I have a decent understanding of the codebase.

Cheers!
