### ISSUE TITLE
TestCaseSource targeting based on testmethodname or specific testcaseid

### ISSUE THREAD

**Issue by gnaneswarreddy** [nunit/nunit#3796]
In Excel i have the below data

TestmethodName | Param1 | Param2 | Param3
Test1 | User | Password | //['Login']
Test2 | User2 | Password2| //['Login']
Test3| null | null | null
I am using the below test method
[TestCaseSource(nameof(ExcelData))] //This has excel details
public void Test1(string Test1, string param1, string param2, string param3) //This is returning all the rows but i need the data for just Test1 only
{
}

[TestCaseSource(nameof(ExcelData))] //This has excel details
public void Test2(string Test1) //This is returning all the rows but i need the data for just Test2 only
{
}

How can we return only required set of data based on test method name? I am also getting Test3 with "" values and when i run the Test its failing as those values are null but i dont require those values as part of my test

**Comment by mikkelbu** [comment]
It is possible to do this (by supplying the test name as a parameter to the souce), but it seem a little backwards. On one hand you want to use the same source, but on the other hand you want the same source to return different results depending on the receiving method. I've shown how you can do it below, but I think a much simpler approach would be to have separate sources.

See e.g. https://docs.nunit.org/articles/nunit/writing-tests/attributes/testcasesource.html#form-1---testcasesourcestring-sourcename for more documentation of the `TestCaseSourceAttribute`.

```csharp
    [TestCaseSource(nameof(TestStrings), new object[] { nameof(LongNameWithEvenNumberOfCharacters) })]
    public void LongNameWithEvenNumberOfCharacters(string name)
    {
        Assert.That(name, Does.StartWith("Data"));
    }

    [TestCaseSource(nameof(TestStrings), new object[] { nameof(ShortName) })]
    public void ShortName(string name)
    {
        Assert.That(name, Does.StartWith("ShortData"));
    }

    static IEnumerable<string> TestStrings(string testName)
    {
        // Just some random test data that could have been read from Excel or some other source
        var allTestCases = new List<(string key, string testData)>
        {
            ("LongNameWithEvenNumberOfCharacters", "Data1"),
            ("ShortName", "ShortData1"),
            ("LongNameWithEvenNumberOfCharacters", "Data2"),
            ("ShortName", "ShortData2")
        };

        // Only return the data when the name matches
        return allTestCases.Where(t => t.key == testName).Select(d => d.testData);
    }
```

**Comment by gnaneswarreddy** [comment]
@mikkelbu This would help my condition but till now i was using testcasedata but with this approach i need to create the ReadExcel and get that in to the list. I have tried using that and able to get the datatable in Framework project class but not sure how to get that datatable and use it in the above code ?

**Comment by gnaneswarreddy** [comment]
Closing this issue
