### ISSUE TITLE
MQRC_KEY REpository_error

### ISSUE THREAD

**Issue by roopaeyes** [nunit/nunit#3797]
I am facing an isssue while migrating from nunit 2.5 to nunit 3.9 with respect to ibmmq . its working fine in nunit 2.5 but in nunit 3.9 i am getting mqrc_key_repository_error.
The following is the code.

[Test]
public void TestMq()
{
MQQueueManager _queueManager;
var properties = new Hashtable();
properties.Add(MQC.HOST_NAME_PROPERTY, "wmqdevap008.xx.xxxx.xxxxxx");
properties.Add(MQC.PORT_PROPERTY, 11426);
properties.Add(MQC.CHANNEL_PROPERTY, "xxxxxx.xx.xx");
properties.Add(MQC.TRANSPORT_PROPERTY, MQC.TRANSPORT_MQSERIES_CLIENT);
properties.Add(MQC.SSL_CERT_STORE_PROPERTY, sslKeyRepository);
properties.Add(MQC.SSL_CIPHER_SPEC_PROPERTY, "TLS_RSA_WITH_AES_128_CBC_SHA256");
properties.Add(MQC.SSL_CIPHER_SUITE_PROPERTY, "SSL_RSA_WITH_AES_128_CBC_SHA");
properties.Add(MQC.SSL_FIPS_REQUIRED_PROPERTY, 0);
properties.Add(MQC.SSL_PEER_NAME_PROPERTY, sslPeerName);

_queueManager = new MQQueueManager("xxxxxxx", properties);
}

The same code when executed in a console application or windows application  works fine without any exception only when i try to run in nunit3 am getting exception

Console >> nunit3-console.exe Class1Library1.dll

Kindly help. Let me know if you need any information.

Regards,
Roopa

**Comment by mikkelbu** [comment]
Hi @roopaeyes 

I don't think anyone here can help you unless they know about IBM MQ. The only difference I can think of could difference in app domains. Does running the console with `--inprocess` make any difference?

**Comment by roopaeyes** [comment]
Hi mikkelbu, 
Thanks for the reply. Unfortunately --inprocess also did not work. Any suggestions?

**Comment by mikkelbu** [comment]
What is the full exception and stacktrace?

**Comment by rprouse** [comment]
@roopaeyes if we don't hear back from you with more information, we will close this issue.

**Comment by mikkelbu** [comment]
Closing this issues, as we have not heard back (and I guess it is more a problem with IMB MQ - perhaps due to appdomains - rather than NUnit)
