### ISSUE TITLE
Timeout Attribute don't work for SetUpFixture

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#38]
setting Timeout Attribute for SetUpFixture has no effect.

We have a class which handle some preconditions for all tests, so timeout might be possible attribute too.

From https://bugs.launchpad.net/nunit-3.0/+bug/614228

**Comment by rprouse** [comment]
Another enhancement that has been open for a long time without interest. Close as low value?

**Comment by jnm2** [comment]
Yes.
