### ISSUE TITLE
Add Compact Framework 3.9 Build

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#380]
CF 3.9 is source-compatible with 3.5 and can be part of our VS2012+ solution. At some point, this will allow us to drop CF 3.5 and it's VS2008 solution.

**Comment by oznetmaster** [comment]
This is actually not difficult to do, just difficult to test.

Has anyone found an appropriate testing platform (emulator)?

When we last looked, there was not one readily available.

**Comment by CharliePoole** [comment]
I haven't been able to find anything. It's frustrating.

**Comment by CharliePoole** [comment]
@rprouse @oznetmaster It doesn't look like we are doing this. Should we drop it or move it to ideas?

**Comment by oznetmaster** [comment]
If we can find a hardware platform to test with, we can/should do it.  I am surprised that there appears to be no hardware platform/emulator available for 3.9 development.  Are we missing something?

**Comment by CharliePoole** [comment]
It seems odd to have a task to support a platform that nobody has ever asked for, that's all.

**Comment by rprouse** [comment]
I am going to close. AFAIK, there are no emulators and as @CharliePoole says, nobody has ever asked. If someone does, then we can reopen this issue.
