### ISSUE TITLE
DictionaryContainsKeyConstraint doesn't perform parameter type conversion on Invoke

### ISSUE THREAD

**Issue by Jevonius** [nunit/nunit#3807]
Hi,

We have upgraded NUnit recently, from 3.10.1 to 3.13.1. We're noticing an issue with `DictionaryContainsKeyConstraint` in a couple of our tests caused by the changes in PR #2881, specifically that the invocation of `ContainsKey` doesn't convert the `key`

 parameter to the correct type before calling (see [this SO page](https://stackoverflow.com/questions/6639219/how-to-do-automatic-type-conversion-for-parameters-when-invoking-a-method-using) for a bit more info).

I've attached a LinqPad query demonstrating the issue; the call to `actual.ContainsKey` succeeds, but the constraint version fails with an ArgumentException `Object of type 'System.Guid' cannot be converted to type 'UserQuery+FooGuid'.`

Happy to have a go at creating a PR to fix this, but not sure of the best way to implement it - would a variant of [this SO answer](https://stackoverflow.com/a/6647579) be acceptable?

Cheers!

[DictionaryContainsKeyConstraint bug.linq.txt](https://github.com/nunit/nunit/files/6244445/DictionaryContainsKeyConstraint.bug.linq.txt)

**Comment by stevenaw** [comment]
I can confirm that the test passes on NUnit 3.10.1 and fails on 3.13.3. It seems like we accidentally brought the DictionaryContainsKeyConstraint out of sync with the native ,NET behaviour in this regard as the repro correctly shows that the built-in `Dictionary<TKey, TValue>.ContainsKey()` method does take `IEquatable<TKey>` into consideration.

I've uploaded the repro here: https://github.com/nunit/nunit.issues/tree/main/Issue3807

**Comment by stevenaw** [comment]
This looks unrelated to the behaviour of ContainsKey and more related to the implicit conversion operator which is handled at compile-time by the compiler injecting an `op_Implicit` call to convert the param from `Guid` to `FooGuid` before calling `ContainsKey`. This is no longer happening after the switch to reflection within the constraint here.

```
// bool flag = dictionary.ContainsKey(Guid);
	IL_0052: ldloc.0
	IL_0053: ldloc.1
	IL_0054: call valuetype Issue3807.UnitTest1/FooGuid Issue3807.UnitTest1/FooGuid::op_Implicit(valuetype [System.Runtime]System.Guid)
	IL_0059: callvirt instance bool class [System.Collections]System.Collections.Generic.Dictionary`2<valuetype Issue3807.UnitTest1/FooGuid, valuetype [System.Runtime]System.Guid>::ContainsKey(!0)
	IL_005e: stloc.2
```

```
// bool flag2 = dictionary.ContainsKey(FooGuid);
	IL_006a: ldloc.0
	IL_006b: ldloc.3
	IL_006c: callvirt instance bool class [System.Collections]System.Collections.Generic.Dictionary`2<valuetype Issue3807.UnitTest1/FooGuid, valuetype [System.Runtime]System.Guid>::ContainsKey(!0)
	IL_0071: stloc.s 4
```

A potential workaround is to cast the value to the target type. For example:
```csharp
Assert.That(actual, Does.ContainKey((FooGuid)expectedGuid));
```

**Comment by manfred-brands** [comment]
Can we change the code in `DictionaryContainsKeyConstraint.Match` to:

```csharp
var method = GetContainsKeyMethod(actual);
if (method != null)
{
    object expectedAsType = Convert.ChangeType(Expected, method.GetParameters()[0].ParameterType);
    return (bool)method.Invoke(actual, new[] { expectedAsType })!;
}
```

**Comment by manfred-brands** [comment]
Unfortunately not: ` System.InvalidCastException : Object must implement IConvertible.`

**Comment by stevenaw** [comment]
I'm in favour of closing this.

The .NET dictionary itself doesn't perform this conversion and I suspect the issue described above will go away if we were to strongly type `ContainsKey` as it would then allow the compiler enough info to inject the implicit conversion operator prior to passing the value into the constraint.

The work around to cast the value prior to passing it in seems ok in the short term to me.

@nunit/framework-team objections?

**Comment by mikkelbu** [comment]
No objections from me (disclaimer: I cannot remember much about how the code was changed)
