### ISSUE TITLE
Incorrect summary comments on Warn.If overloads

### ISSUE THREAD

**Issue by rouacke** [nunit/nunit#3811]
I believe a couple `Warn.If` overloads have incorrect summary comments.

https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Warn.cs#L335

https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Warn.cs#L335

The summary comments on those overloads read:

> Asserts that a condition is true. If the condition is false, a warning is issued.

However, the method bodies read:

```
Warn.If(condition, Is.True, ...);
```

They log a warning if the condition is true.

The summary comment seems to be correct on other overloads:

> Asserts that a condition is false. If the condition is true a warning is issued.

**Comment by rprouse** [comment]
Good catch. That code has been there forever. It is surprising no one has noticed before you!
