### ISSUE TITLE
NUnit - Using Abstracted Test Classes, with Abstracted TestCaseSource.

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [nunit/nunit#3813]
Brief rundown-

I have a web api project, which communicates with a business layer, which communicates with a data access layer. My business layer has most common functionality abstracted, such as, Get All, Get One, Get One By Name, Delete, Update, Create.

As such, this allows me to also apply abstraction to my unit tests. Since, all common functionality is implemented in a pretty standardized way, with enough flexibility in the abstractions, The unit tests can all be written in the same fashion.

So, this leads me to an abstract base class for my unit tests.

The issue I am running into TestCaseSource, ValueSource, etc, all depend on a static member to provide data. 

To give an example-

Lets say, we have a abstract class from which the tests inherit.
```csharp
public abstract class TestClass_R<TBL, TEntity, TDTO, TOptions>
        : TestClass<TBL>
        where TBL : IBuisnessLogic_Read_All<TDTO, TOptions>
            , IBuisnessLogic_Read_ByID<TDTO_Detail, TOptions>
        where TEntity : Interfaces.INameIDRecord
        where TDTO : DataTransfer.Interfaces.INamedDTO
        
        public abstract IEnumerable<TEntity> BaseData();
        public abstract IEnumerable<TOptions_WithName> TestOptions();
        
        [Test]
        public void ReadALL()
        {
              ...
        }
```        

Now, let's build an implementation of said class.
        
```csharp
    public class UserTestsNew : TestClass_R<UserLogic, User, UserDTO, GetUserOptions>
    {
        public override IEnumerable<User> BaseData() => TestData.Users();

        public override IEnumerable<GetUserOptions> TestOptions()
        {
            yield return new GetUserOptions { Include_Manager = true };
            yield return new GetUserOptions { Include_Manager = false };
        }   

        protected override void AssertDetailDTOMatchesEntity(User Expected, UserDTO Actual)
        {
            Assert.IsNotNull(Expected);
            Assert.IsNotNull(Actual);


            Assert.AreEqual(Expected.ID, Actual.ID);
            Assert.AreEqual(Expected.Name, Actual.Name);
            Assert.AreEqual(Expected.Email, Actual.Email);
        }

        protected override void AssertSummaryDTOMatchesEntity(User Expected, UserDTO Actual) => AssertDetailDTOMatchesEntity(Expected, Actual);

        protected override UserLogic CreateT(ILogger<UserLogic> log) => new UserLogic(db, log);

    }
```

From this point- I can execute the same basic tests on all provided entities, to test all of the common functionality of a typical business layer interface.

HOWEVER, the issue lies- I cannot utilize TestCaseSource, or ValueSource to pull a list of TestData or parameters, because both methods require a STATIC data source.

For my case, I do have a work around in the sense, I can do something like this:
```csharp
        private IEnumerable<(TEntity, TOptions_WithName)> GetCombinations()
        {
            foreach (var Data in BaseData())
                foreach (var Options in TestOptions())
                    yield return (Data, Options);
        }
        
   [Test]
        public void ReadByID()
        {
            foreach ((var Data, var Options) in GetCombinations())
            {
                var resultTask = bl.GetBy_ID(Data.ID, Options, token);

                var Result = resultTask.AssertAndReturnValue();

                AssertNameIDMatches(Data, Result);
                AssertDetailDTOMatchesEntity(Data, Result);
            }
        }
```

And, this will have the same overall outcome as using a ValueSource. However- instance of each "TestCase" being represented as an individual test, Everything would be lumped together into a single pass/fail result.     

So- My question is-

1. Is there any supported method for obtaining TestCaseSource or ValueSource from a non-static member.... OR
2. Is there a method on the NUnit test context which can be invoked to "Split" the test into multiple sets of results.

Justification for attempting to do testing in this way-

1. You have a proper CRUD/Rest API. The expectation is Create, Read, Update, and Delete works in a consistent manner across all of your types of entities. This lends itself very well to abstraction to reduce the amount of repeated logic, and to enforce consistency.
2. This calls your business layer. Within reason, your business layer will interpret the C.R.U.D requests, in a somewhat consistent manner. This also lends itself very well to abstraction to reduce the amount of repeated logic, and to enforce consistency. 
3. Your BL layer, calls your Data Access Layer. Since, you enforce consistency, You have a pretty standard set of interfaces to enforce a similar model for all of your entities. 

4. Finally- since every tier of your CRUD api is now abstracted, and everything works in a very consistent manner- This means you can also abstract your unit tests, to perform testing on your entity and BL layers, in a consistent mannor.

**Comment by Dreamescaper** [comment]
You're right that TestCaseSource requires a static member, it doesn't have to be defined in the same class where it is referenced.
You can define your test method in abstract class with some [TestCaseSouce("TestData")] attribute, but declare static TestData property in descendant classes instead (a separate property for each descendant class).

You can take a look how it is done in NUnit tests.
ConstraintTestBase (abstract class):
https://github.com/nunit/nunit/blob/0296dad2f7a28928b9c4721402ac8747f59afac9/src/NUnitFramework/tests/Constraints/ConstraintTestBase.cs#L41

SameAsTest (descendant class):
https://github.com/nunit/nunit/blob/0296dad2f7a28928b9c4721402ac8747f59afac9/src/NUnitFramework/tests/Constraints/SameAsTest.cs#L19

**Comment by XtremeOwnageDotCom** [comment]
@Dreamescaper, I was about 40 lines into a detailed reply, when what you are saying, finally clicked.

```csharp
public abstract class testbaseclass
{
    [Test, TestCaseSource("FailureData")] 
    public void dotest(object testdata)
    {
        ...
    }

}


public class TestClass : testbaseclass
{
    public static object FailureData => ...


}
```

I will go down the route of testing this solution- as this would resolve my issues.

However, it would be really nice if c# had... oh, static abstract, or static members on interfaces.... etc... to ensure the compiler enforced proper using of the base test class.

**Comment by Dreamescaper** [comment]
We have an analyzer in https://github.com/nunit/nunit.analyzers, which validates that TestCaseSource target exists.
I'm not really sure if it handles such abstract cases though...

**Comment by XtremeOwnageDotCom** [comment]
I'll be....

Your method actually works. I hate that there is no good way to enforce proper usage by the compiler / language, however, it does work as expected.

I suppose, for the time being, I can live with this.

However- there are a few upcoming proposals for c#10, which would greatly benefit this specific use case.
https://github.com/dotnet/csharplang/issues/4436


*shrugs

Thanks for your assistance and solution, much appreciated.

**Comment by mikkelbu** [comment]
At my old company we made a similar solution to the problem when we (partly) migrated from NUnit 2 to 3.

> We have an analyzer in https://github.com/nunit/nunit.analyzers, which validates that TestCaseSource target exists.
> I'm not really sure if it handles such abstract cases though...

I'm quite sure that the analyzer as it is will does not support this. The easiest solution would be not to perform this kind of check (and other checks in abstract classes). I'll create a an issue for this, although it is of lesser priority.

**Comment by XtremeOwnageDotCom** [comment]
A... band aid, if anybody else chases down this rabbit hole:

```csharp
        [OneTimeSetUp]
        public void EnsureStaticMembers()
        {
            var Entities = this.GetType().GetMethod("Entities", System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.Public);
            Assume.That(Entities is not null, "Expected static member is not implemented on derrived test class");

            Assume.That(Entities.ReturnType == typeof(IEnumerable<TEntity>), $"Expected return type of Entities() does not match expected IEnumerable<{typeof(TEntity).Name}>");
        }
```
