### ISSUE TITLE
static AsyncLocal not initialized

### ISSUE THREAD

**Issue by Frudy** [nunit/nunit#3830]
Given this code

`	public static class ClassA
	{
		public static readonly AsyncLocal<MyAmbientContextClass> MyAmbientContext = new AsyncLocal<MyAmbientContextClass>();
`

In NUnit 3.12.0
ClassA.MyAmbientContext.Value is initialized

In NUnit 3.13.1
ClassA.MyAmbientContext.Value is NULL / uninitialized

**Comment by rprouse** [comment]
Can you give us a bit more context here? It looks like you are expecting the async context to be the same for static initialization of your class as it is for test execution. If so, we don't guarantee that. Can you give us more information.

**Comment by Frudy** [comment]
This was no fault of NUnit. NUnit changed behaviour in this area going from 3.12.0 to 3.13.1, probably to the better. This resulted in failing tests on our side, exposing bad test setup. 
Thus no fault due to NUnit.

**Comment by jnm2** [comment]
Awesome! This was probably https://github.com/nunit/nunit/issues/3283 which was fixed in 3.13.0.
