### ISSUE TITLE
'Explicit' and 'Category' TestCase parameters behavior

### ISSUE THREAD

**Issue by eduherminio** [nunit/nunit#3846]
Given: 

```csharp
[TestCase("1")]
[TestCase("2", Explicit = true, Category = "LongRunning")]
[TestCase("3", Category = "LongRunning")]
[TestCase("4", Explicit = true)]
public void MyTest(string str)
{
     Assert.Pass();
}
```

I would like:
* Explicit behavior so that cases 2 and 4 aren't executed by default from VS or when running `dotnet test`.
* A way of executing cases 2 and 3 (categorized test cases, most likely explicit, but not necessarily).

After reading [the examples of use section](https://docs.nunit.org/articles/nunit/writing-tests/attributes/explicit.html#examples-of-use) of `Explicit` attribute, I was expecting a similar behavior when using the `Explicit` parameter of `TestCase` combined with a `Category`.

However, when running
```bash
dotnet test -c Release --filter "TestCategory=LongRunning"
```

in the provided scenario, only case 3 is executed, being the explicit one ignored.

----

Is the current behavior the desired one, or can this be some kind of bug/enhancement?

If it is the desired one, any suggestions about how to run (by category) `TestCase`s with both `Category` and `Explicit` parameters?

**Comment by rprouse** [comment]
I am adding the confirm label because we've had issues with explicit and the adapter. This issue might belong in that repo.

**Comment by eduherminio** [comment]
I can confirm that upgrading `NUnit3TestAdapter` to `4.0.0-beta.2` fixes this bug (as suggested by @OsirisTerje for [this other (related?) issue](https://github.com/nunit/nunit3-vs-adapter/issues/851#issuecomment-830862750)).
Thanks folks!
