### ISSUE TITLE
It seems that assertion of exception message doesn't work

### ISSUE THREAD

**Issue by GibbOne** [nunit/nunit#3847]
I can't test correct exception message.

To reproduce:
- csproj
``` c#
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.9.4" />
    <PackageReference Include="NUnit" Version="3.13.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.17.0" />
  </ItemGroup>
</Project>
```

- code:
``` c#
using NUnit.Framework;
using System;

namespace NUnitExceptionMessageAssertion
{
    public static class ClassToTest
    {
        public static void FaultyMethod() => 
            throw new Exception("Error message!");
    }

    public class Tests
    {
        [Test]
        public void Test()
        {
            Assert.Throws<Exception>(
                () => ClassToTest.FaultyMethod(), 
                "Wrong Error Message!");
        }
    }
}
```

The test should fail. But it doesn't.

Am I miss something?

**Comment by manfred-brands** [comment]
Why would it fail? You assert that `Exception` is thrown and that is what your method throws.
You are not asserting a message.

**Comment by GibbOne** [comment]
I guessed that second argument of the `Throws` method (message) would check the message of the exception.

But I understoond that I was wrong.

The argument is just the message in case of test failure.

Thx.

P.S. maybe method online documentation could be improved?

**Comment by mikkelbu** [comment]
> P.S. maybe method online documentation could be improved?

The documentation can always be improved :). https://docs.nunit.org/articles/nunit/writing-tests/assertions/classic-assertions/Assert.Throws.html already contains some examples on validating the message. I can see that it could be confusing to see the overloads in the beginning of the page with `string message`, but all other assert pages have a similar flow (and argument), but perhaps we could add a sentence explaining the `string message` argument on this page, as it is probably only on this page (and the async variant) where the reader can be confused.

Or did you have something else in mind?

**Comment by rprouse** [comment]
@GibbOne the second parameter is the message that is output if the test fails. You want something like,

```csharp
Assert.That(ClassToTest.FaultyMethod, Throws.Exception.With.Message.EqualTo("Wrong Error Message!"));
```

**Comment by GibbOne** [comment]
@mikkelbu 

For sure your documenation is good.
I was just thinking to add the word 'test' in the argument description.

 Instead of 

`The message that will be displayed on failure`

`The message that will be displayed on test failure`

@rprouse 

Thx to all.

**Comment by rprouse** [comment]
I'm going to close this as an answered question.
