### ISSUE TITLE
Nunit is throwing a BadImageFormatException when trying to load tests for win-arm64 dll

### ISSUE THREAD

**Issue by hichem001** [nunit/nunit#3850]
Hello,

When trying to excute tests from my .net5 dll, I'm getting "BadImageFormatException: Could not load file or assembly" error.
Checking my dll info, I verified that it has ARM64 arch:

![image](https://user-images.githubusercontent.com/669027/117447265-8e49d000-af3d-11eb-94e1-22f1cb0fb612.png)

Following are my project file (it's a basic project):
![image](https://user-images.githubusercontent.com/669027/117447596-01534680-af3e-11eb-96f5-9c28baba7b8c.png)

Following the error I'm having when executing test using the console (I'm running test on a Surface Pro X ARM64 based):

> C:\hichem\to_be_removed\net5.0-windows>"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow\\vstest.console.exe" NUnitTestProject1.dll
> Microsoft (R) Test Execution Command Line Tool Version 16.8.0
> Copyright (c) Microsoft Corporation. All rights reserved.
> 
> Starting test execution, please wait...
> A total of 1 test files matched the specified pattern.
> NUnit Adapter 3.16.1.0: Test execution started
> Running all tests in C:\hichem\to_be_removed\net5.0-windows\NUnitTestProject1.dll
> Assembly not supported: C:\hichem\to_be_removed\net5.0-windows\NUnitTestProject1.dll
> Exception NUnit.Engine.NUnitEngineException, Exception thrown executing tests
> An exception occurred in the driver while loading tests.
> at NUnit.Engine.Runners.DirectTestRunner.LoadDriver(IFrameworkDriver driver, String testFile, TestPackage subPackage)
> at NUnit.Engine.Runners.DirectTestRunner.LoadPackage()
> at NUnit.Engine.Runners.DirectTestRunner.EnsurePackageIsLoaded()
> at NUnit.Engine.Runners.DirectTestRunner.Explore(TestFilter filter)
> at NUnit.Engine.Runners.MasterTestRunner.Explore(TestFilter filter)
> at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(String assemblyPath, IGrouping`2 testCases, TestFilter filter) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 236
> at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 104
> Innerexception: System.BadImageFormatException: Could not load file or assembly 'NUnitTestProject1, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.
> File name: 'NUnitTestProject1, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
> at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
> at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
> at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
> at NUnit.Engine.Drivers.NUnitNetStandardDriver.Load(String testAssembly, IDictionary`2 settings)
> at NUnit.Engine.Runners.DirectTestRunner.LoadDriver(IFrameworkDriver driver, String testFile, TestPackage subPackage)
> NUnit Adapter 3.16.1.0: Test execution complete
> No test is available in C:\hichem\to_be_removed\net5.0-windows\NUnitTestProject1.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
> 
> Additionally, path to test adapters can be specified using /TestAdapterPath command. Example /TestAdapterPath:<pathToCustomAdapters>.
> 

Am I doing something wrong? Did I miss something?

Thanks!

**Comment by rprouse** [comment]
Are you running the tests from Visual Studio or using `dotnet test` on the command line? We often see this error when the tests are being run x86 from Visual Studio. In Visual Studio, look under the Test | Processor Architecture menu and make sure it is correct. If you are using `dotnet test`, what options are you passing?

**Comment by hichem001** [comment]
I'm using the vstest.console like the following:

> "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" NUnitTestProject1.dll

is that the correct way?

**Comment by hichem001** [comment]
I found the root cause of the failure, I was inluding a bad framework:
<FrameworkReference Include="Microsoft.WindowsDesktop.App.WindowsForms" />

seems that this one is not supported by ARM64 architecture. I had to replace it by: "System.Drawing.Common" (actually my app need this fw to be selected as reference) and it works fine
