### ISSUE TITLE
'NUnit.Engine.TestEngine with a version greater than or equal to 3.0 not found'

### ISSUE THREAD

**Issue by AhlamJelti** [nunit/nunit#3852]
i use NUnit.Engine.APi to run Test From other assembly .. but i had this error "'NUnit.Engine.TestEngine with a version greater than or equal to 3.0 not found'" when i install package Nunit.Engine i don't have this error but still the code coudn't Load teh assembly that i specified by path and the tests d

            ITestEngine engine = TestEngineActivator.CreateInstance();
            TestPackage package = new TestPackage(@"PaTH\TestScenariotSpecflow.dll");
            ITestRunner runner = engine.GetRunner(package);

            // Run all the tests in the assembly
            XmlNode testResult = runner.Run(listener: null, TestFilter.Empty);

 - the program is  excuted but i couldn't run the tests also if i use incorrect path i don't have any message error .
PS : i wanna run some scenario created in gherkin i used specflow + NUnit

**Comment by mikkelbu** [comment]
Closing this, as an issue was also created in the nunit-console repo - nunit/nunit-console#945 - which is also the correct place for this question.
