### ISSUE TITLE
SerializationException NUnit.Framework.Internal.TestExecutionContext is not marked as serializable

### ISSUE THREAD

**Issue by bjakobitz** [nunit/nunit#3853]
Message: System.Runtime.Serialization.SerializationException : Type 'NUnit.Framework.Internal.TestExecutionContext' in Assembly 'nunit.framework, Version=3.12.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb' is not marked as serializable.

This is an extension of [v2 bug](https://bugs.launchpad.net/nunitv2/+bug/1084181) but in NUnit 3.  This is the exact same project mentioned in the v2 bug.  We are trying to upgrade to NUnit 3.  The work around CallContext.FreeNamedDataSlot("NUnit.Framework.TestContext"); no longer works.  I suspect it's because the library name has changes but I've tried both "NUnit.Framework.Internal.TestExecutionContext" and "NUnit.Framework.Internal.TestContext" with no luck.  It looks like this was fixed in 2.6.3 preview.  Is this something that can me ported to 3.12?  Is there a different class name I can use in the work around?

Thanks,
Brad

**Comment by bjakobitz** [comment]
After pulling down the source code we were able to find CallContext.FreeNamedDataSlot("NUnit.Framework.TestExecutionContext"); works.  I would still ask that if the fix in 2.6.3 works can it be ported to 3.12?

**Comment by stevenaw** [comment]
I'm closing this as won't fix. A review of the original bug report indicates this was originally added to support remoting, which has been removed from .NET 6+ (https://learn.microsoft.com/en-us/dotnet/core/porting/net-framework-tech-unavailable)
