### ISSUE TITLE
 IEnumerable<strings> Is.Null  Expected: null       But was:  < null >

### ISSUE THREAD

**Issue by bloodgang94** [nunit/nunit#3855]
Hey! I am returning a collection of IEnumerable strings. There are times when it is null
This is where the problem arose:

![image](https://user-images.githubusercontent.com/63465285/118090744-963cc080-b3d2-11eb-876b-8845e9a6bda8.png)

![image](https://user-images.githubusercontent.com/63465285/118090299-157dc480-b3d2-11eb-9571-436f19331b8e.png)

Why is this behavior?

**Comment by bloodgang94** [comment]
Update: Has.All.Null works

**Comment by Dreamescaper** [comment]
It looks like it is an IEnumerable with single null element.
IEnumerable itself is not null though.

**Comment by mikkelbu** [comment]
Closing this as answered. As @Dreamescaper writes, `Assert.That(elements, Is.Null)` checks whether `elements` is `null` which is not as it an `IEnumerable` containing one element which is `null`. The constraint `Has.All.Null` on the other hand checks whether all elements in the collection are `null`.
