### ISSUE TITLE
Parallel executing for parameterized method in .NET Framework/.NET Core 3.1

### ISSUE THREAD

**Issue by mcichonqa** [nunit/nunit#3860]
Hi, is it possible to run tests in parallel with ParallelScope.Children for parameterized method with parameters 	`<NumberOfTestWorkers>2</NumberOfTestWorkers>` in .runsettings? My parameterized test method creates 8 tests and while executing I have 8 threads, but I set NumberOfTestWorkers = 2. My class containing parameterized test method has attribute [Parallelizable(ParallelScope.Children)]. In .NET Framework this works the same. 
Is it possible to control threads when ParallelScope.Children?
I tested this from VisualStudio.

Im using .NET Core 3.1, NUnit 3.13.1, NUnit3TestAdapter 3.17.0, VS 16.8.6
Please help.

**Comment by mcichonqa** [comment]
Sorry, I had problems with my .runsettings file...

**Comment by mikkelbu** [comment]
No problem. Glad you figured it out.
