### ISSUE TITLE
nunit Framework tests do not run with "dotnet test" nor inside VS2019 (Windows)

### ISSUE THREAD

**Issue by FrankRay78** [nunit/nunit#3867]
**Expected:** as per the NUnit documentation [here](https://docs.nunit.org/articles/nunit/getting-started/dotnet-core-and-dotnet-standard.html), I should be able to run the unit tests from the command line using `dotnet test`

![image](https://user-images.githubusercontent.com/52075808/120346968-c7ceea80-c2f3-11eb-9f50-e3fdfad338a1.png)

**Actual:** No tests are ever found

#

**Environment**
Dell XPS 15, 32BG ram
Running `clrver` outputs

```
Versions installed on the machine:
v2.0.50727
v4.0.30319
```
.Net 5.0 SDK has been installed manually

#

**Steps to reproduce**

1. Open VS2019 and clone the nunit repo into a clean directory
2. Open windows PowerShell and navigate to the directory
3. Run `build --target=Test --configuration=Release`
4. NuGet packages restored, all dlls are built, all unit tests pass (for all framework targets)

![image](https://user-images.githubusercontent.com/52075808/120344050-2181e580-c2f1-11eb-8445-4cfe9f85ff8a.png)

5. Navigate to the bin\Release\net5.0 directory
6. Run `dotnet test nunit.framework.tests.dll --framework:net5.0`

![image](https://user-images.githubusercontent.com/52075808/120344475-863d4000-c2f1-11eb-994f-5027e1d2c85a.png)

7. Open the solution in VS2019 and set the test target architecture to x64

![image](https://user-images.githubusercontent.com/52075808/120344833-dcaa7e80-c2f1-11eb-99d8-8637fca13212.png)

8. Save all and close VS2019
9. Repeat steps 3, 5 and 6 above

![image](https://user-images.githubusercontent.com/52075808/120345359-50e52200-c2f2-11eb-9ff4-4b668cf3a96b.png)

10. Specify the path to the TestAdapters located here:

![image](https://user-images.githubusercontent.com/52075808/120345554-7bcf7600-c2f2-11eb-9c1d-67640496ef64.png)

11. Run the following command `dotnet test nunit.framework.tests.dll /TestAdapterPath:C:\Users\frank\Documents\Professional\Source\nunit-VS2019-2\bin\Release\net5.0 --framework:net5.0`

![image](https://user-images.githubusercontent.com/52075808/120345751-aa4d5100-c2f2-11eb-95ee-cac2af7ac0a0.png)

12. Open the solution in VS2019 and upgrade to the latest TestAdapter:

![image](https://user-images.githubusercontent.com/52075808/120346258-1def5e00-c2f3-11eb-817b-2abb3f8b86f4.png)

13. Repeat build step 3 above. 
14. Check the output has the updated TestAdapter

![image](https://user-images.githubusercontent.com/52075808/120346595-6b6bcb00-c2f3-11eb-99ce-de930489c161.png)

15. Run the following command `dotnet test nunit.framework.tests.dll /TestAdapterPath:C:\Users\frank\Documents\Professional\Source\nunit-VS2019-2\bin\Release\net5.0 --framework:net5.0`

![image](https://user-images.githubusercontent.com/52075808/120346712-88080300-c2f3-11eb-9917-32d0a1c93d5a.png)

nb. I've tried the above steps for the net4.5 build output to the same effect

#

**Commentary**
I believe the inability to find / execute the tests using `dotnet test` may explain why I cannot get unit tests to execute within Visual Studio 2019 (with or without Resharper) on Windows and also JetBrains Rider (on either Windows 10 and Debian Linux) - see attached log output
[VS2019 test output log.txt](https://github.com/nunit/nunit/files/6577318/VS2019.test.output.log.txt)

Related Issues
#3008 
#2973 

Related Discussions
#3861 

#

**Additional Information**

I ran the following command from the **bin\Release\net5.0** directory, `dotnet test nunit.framework.tests.dll --list-tests --framework:net5.0 --diag dotnet_test_log.txt --logger "console;verbosity=detailed"`

The following logs were generated: 
[dotnet_test_log.host.21-06-01_20-09-24_22867_6.txt](https://github.com/nunit/nunit/files/6580094/dotnet_test_log.host.21-06-01_20-09-24_22867_6.txt) and [dotnet_test_log.txt](https://github.com/nunit/nunit/files/6580095/dotnet_test_log.txt)

**Comment by manfred-brands** [comment]
I found some time to look into this today.
The tests are all skipped because the adapter doesn't find a supported nunit.framework.

The NUnit3DriverFactory.IsSupportedTestFramework explicitly tests on version 3 of the framework:
```
return NUNIT_FRAMEWORK.Equals(reference.Name, StringComparison.OrdinalIgnoreCase) && reference.Version.Major == 3;
```

Note that this [class](https://github.com/nunit/nunit-console/blob/master/src/NUnitEngine/nunit.engine.core/Drivers/NUnit3DriverFactory.cs) is in the nunit-console repository.

The current master branch has version 4.

Locally if have tried a version with the one-token change (`>= 3`) and it now does find tests, both with `dotnet test` and inside Visual Studio`.

Note that this involves changes in 3 repositories:
* nunit-console (change == 3 into >= 3),
* nunit-vs-adapter (reference newer version of nunit.engine)
* nunit (reference newer version of nunit3testadapter)

But they not all pass!
Only 2 errors in `net45`, but 70 in `net5.0`.
There are several errors like the below:
```
  Failed LoadWithPreFilter("NUnit.Tests.Assemblies","NUnit.Tests.Singletons","NUnit.Tests.FixtureWithTestCases") [2 ms]
  Error Message:
     Exception has been thrown by the target of an invocation.
  ----> Delegates must be of the same type.
  Expected: Runnable
  But was:  NotRunnable
```
That failure is in when calling `AssemblyLoadContext.LoadFromAssemblyPath`.

Note that the above failures also occur in the `v3.13-dev` branch with the existing code (no changes).
So there is clearly a difference between the `nunitlite` runner part of `nunit` and the `nunit.engine` part of `nunit-console`.

Are they supposed to be compatible?

**Comment by OsirisTerje** [comment]
@manfred-brands 

> The NUnit3DriverFactory.IsSupportedTestFramework explicitly tests on version 3 of the framework:

>   return NUNIT_FRAMEWORK.Equals(reference.Name, StringComparison.OrdinalIgnoreCase) && reference.Version.Major == 3;

I am fixing this now for the embedded engine in the adapter, which is based off the 3.15.X branches.   I will release a 4.5 alpha release of the adapter on nuget so it can be tested in the nunit framework repo.

**Comment by OsirisTerje** [comment]
@manfred-brands @stevenaw @rprouse 
I have release version 4.5.0-alpha.3 on nuget which accepts NUnit 4, ref @manfred-brands comment above.
Trying that version on the framework repo, doesn't help much, as the same errors are still there, missing testhost.runtimeconfig.json, a file I don't think should be there at all.  
![image](https://user-images.githubusercontent.com/203432/226173641-1b012da5-e350-470b-ba9b-fa90a86c7b83.png)

Further, as can be seen in the image above, the net462 is not displayed, and there is a warning about that, 
![image](https://user-images.githubusercontent.com/203432/226173672-f3cec684-feb3-409f-ac49-2684ad157057.png)
So it seems the net462 is not building properly, but no compiler warning or error about that.
![image](https://user-images.githubusercontent.com/203432/226173714-442a01e6-457e-4333-9d93-81149bd6f88b.png)
And there is only one place where the adapter is added, and that is the framework.test project.

This [Issue 3937](https://github.com/microsoft/vstest/issues/3937) in the vstest repo is the only place I have found that refers to the same error messages, and the gist of it is that it looks like mixing framework DLLs in the same bin folder can cause this.  Not sure which these can be, but I do see that all projects build to the same bin folder.  It should be per framework, but that would not apply for dependencies.

**Comment by stevenaw** [comment]
Thanks for taking a look at this @OsirisTerje and experimenting with an alpha release of the adapter. I'll also try to take a second look at this when I am able. From my recollection this issue appears to only affect the `main` branch of the repo, but they've started to diverge enough such that there are now far more differences than simply the v3 / v4 assemblyinfo.

**Comment by OsirisTerje** [comment]
Do you know if the binary outputs have been changed?

**Comment by OsirisTerje** [comment]
1. Adding the https://www.nuget.org/packages/NUnit3TestAdapter/4.5.0-alpha.3 makes the tests reappear, and they run.
![image](https://user-images.githubusercontent.com/203432/226208137-8eb34253-8630-4d2c-af1f-5088f22c3dd4.png)

70 tests out of 5600 tests fails.  
However, the source code links from the tests in the test explorer to the source code doesn't work, it doesn't find the source code links.
![image](https://user-images.githubusercontent.com/203432/226208293-d1587bc0-7fa5-48c7-bc1f-6d3952426091.png)

2.  Changing the outputpath from a common bin output, in Directory.Build.props to individual project bin outputs, restores the source links.  
![image](https://user-images.githubusercontent.com/203432/226208323-ec419ba6-c186-4337-abeb-9a277317cd32.png)

**Comment by OsirisTerje** [comment]
Exception details:
![image](https://user-images.githubusercontent.com/203432/226211297-f8bfaa53-c564-4bbe-9e3c-1d65d92702f5.png)
![image](https://user-images.githubusercontent.com/203432/226211306-0164e7f9-a517-4edc-8727-8db56d539894.png)

**Comment by stevenaw** [comment]
Thanks @OsirisTerje !
I'm not at a computer at the moment, but the main change I can recall between the branches aside from the version bump is that some older TFMs were dropped in main. There were some build changes to minimize the number of places we define the target frameworks by putting them in a Directory.build.props file, but I didn't _think_ the build output directory itself changed

**Comment by OsirisTerje** [comment]
@stevenaw No, the build output directory have been like that since 2017.  But I seem to remember that the last time I worked with the framework (a few months back though), these things did work.  Not sure though.

**Comment by OsirisTerje** [comment]
@jnm2 Any idea why the loading of the assemblies using dynamic loading of the AssemblyLoadContext would fail?

**Comment by OsirisTerje** [comment]
Added System.RunTime.Loader nuget package to get hold of the AssemblyLoadContext, and it works.  See latest in the PR.

**Comment by gordon-dynamic-import** [comment]
> [@manfred-brands](https://github.com/manfred-brands)
> 
> > The NUnit3DriverFactory.IsSupportedTestFramework explicitly tests on version 3 of the framework:
> 
> > return NUNIT_FRAMEWORK.Equals(reference.Name, StringComparison.OrdinalIgnoreCase) && reference.Version.Major == 3;
> 
> I am fixing this now for the embedded engine in the adapter, which is based off the 3.15.X branches. I will release a 4.5 alpha release of the adapter on nuget so it can be tested in the nunit framework repo.





https://lnkr.fun/1795cf6
