### ISSUE TITLE
Order attribute skips classes with multiple test fixtures

### ISSUE THREAD

**Issue by mozhirin** [nunit/nunit#3868]
I'm ordering some simple test classes by applying `Order` attribute.

```
namespace TestProject1
{
    [Order(2)]
    public class Class1
    {
       [Test]
        public void A()
        {
            Console.WriteLine("A");
        }
    }
    
    [Order(1)]
    public class Class2
    {
        [Test]
        public void B()
        {
            Console.WriteLine("B");
        }
    }
    
    [Order(0)]
    public class Class3
    {
        [Test]
        public void C()
        {
            Console.WriteLine("C");
        }
    }
}
```
And getting expected output:
```
C
B
A
```
Then I'm adding `TestFixture` attribute to one of the classes:
```
[TestFixture("1")]
[Order(1)]
public class Class2
{
    private string s;
    public Class2(string s)
    {
        this.s = s;
    }

    [Test]
    public void B()
    {
        Console.WriteLine("B");
    }
}
```
And still getting expected output:
```
C
B
A
```
But when I'm adding second TestFixture
```
[TestFixture("1")]
[TestFixture("2")]
[Order(1)]
public class Class2
{
    private string s;
    public Class2(string s)
    {
        this.s = s;
    }

    [Test]
    public void B()
    {
        Console.WriteLine("B");
    }
}
```
And I'm getting
```
C
A
B
B
```
instead of
```
C
B
B
A
```

Is this expected behavior and I'm missing something or a bug?

**Comment by michaeluskov** [comment]
Ran into the same case

**Comment by mozhirin** [comment]
Linking [discussion at stackoverflow](https://stackoverflow.com/questions/67988558/order-attribute-skips-classes-with-multiple-test-fixtures)

**Comment by mikkelbu** [comment]
I think Charlies suggestion sounds like a good solution.

> You can't currently do it because NUnit interprets the OrderAttribute as applying to each individual fixture. But that serves no useful purpose, since each one gets the same ordering value, and it makes it impossible to effectively order fixtures when any of them use parameters. NUnit could just as easily apply the OrderAttribute to the invisible wrapping suite when multiple parameterized fixtures are involved.

**Comment by mozhirin** [comment]
Can you tell me when approximately it's gonna be fixed?

**Comment by rprouse** [comment]
> Can you tell me when approximately it's gonna be fixed?

As far as I know, nobody is working on this yet and it isn't high priority so it won't be hotfixed. If it is important to you, we accept PRs.
