### ISSUE TITLE
Copyright notices for third-party code

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [nunit/nunit#3869]
The NUnit v3.13.2 source tree includes some third-party code that is built into "lib/net35/nunit.framework.dll" in the "NUnit" NuGet package, or into "lib/netstandard2.0/nunitlite.dll" in the "NUnitLite" NuGet package. Maybe those copyright notices should be added to [NOTICES.txt](https://github.com/nunit/nunit/blob/5631b49d1cf3f50beba6c595ddfbdac05b73d37b/NOTICES.txt), which is likewise distributed in the NuGet packages.

<https://github.com/nunit/nunit/blob/5631b49d1cf3f50beba6c595ddfbdac05b73d37b/src/NUnitFramework/framework/Compatibility/System.Collections.Concurrent/ConcurrentQueue.cs#L9>
<https://github.com/nunit/nunit/blob/5631b49d1cf3f50beba6c595ddfbdac05b73d37b/src/NUnitFramework/framework/Compatibility/System.Collections.Concurrent/IProducerConsumerCollection.cs#L4>
<https://github.com/nunit/nunit/blob/5631b49d1cf3f50beba6c595ddfbdac05b73d37b/src/NUnitFramework/framework/Compatibility/System.Collections/CollectionDebuggerView.cs#L10>
<https://github.com/nunit/nunit/blob/5631b49d1cf3f50beba6c595ddfbdac05b73d37b/src/NUnitFramework/framework/Compatibility/System.Diagnostics.CodeAnalysis/NullableAttributes.cs#L5>
<https://github.com/nunit/nunit/blob/5631b49d1cf3f50beba6c595ddfbdac05b73d37b/src/NUnitFramework/framework/Compatibility/System.Threading/LazyThreadSafetyMode.cs#L7>
<https://github.com/nunit/nunit/blob/5631b49d1cf3f50beba6c595ddfbdac05b73d37b/src/NUnitFramework/framework/Compatibility/System.Threading/SpinWait.cs#L4>
<https://github.com/nunit/nunit/blob/5631b49d1cf3f50beba6c595ddfbdac05b73d37b/src/NUnitFramework/framework/Compatibility/System/Lazy.cs#L11>
<https://github.com/nunit/nunit/blob/5631b49d1cf3f50beba6c595ddfbdac05b73d37b/src/NUnitFramework/nunitlite/Options.cs#L7>

**Comment by mikkelbu** [comment]
I'm no expert in copyright, but I don't see a problem with this. Note that all the "Compatibility" files above are removed in the master branch as NUnit 4 will not support net35.

**Comment by KalleOlaviNiemitalo** [comment]
I was thinking about this paragraph of the license terms:

```
// The above copyright notice and this permission notice shall be
// included in all copies or substantial portions of the Software.
```

It seems to me that the NuGet packages include a copy of the licensed code, in binary form, but do not include the copyright notice to which the paragraph refers.

**Comment by mikkelbu** [comment]
I'm sorry. I just reread my comment, and I can see that it is _very_ ambiguous. With 

> I'm no expert in copyright, but I don't see a problem with this.

I meant that I see no problem in adding this to NOTICES.txt. So I don't see a problem in doing this.

**Comment by rprouse** [comment]
I'm also fine with adding it to NOTICES.txt and including it in the NuGet file.

**Comment by somashekharshekhar** [comment]
Hi team, am new to Nunit our project is starting with C# Microservices project, am looking for the framework to test Microservices TDD, can you help me with the framework , post me the git link  i will clone and develop it. thanks in advance

**Comment by OsirisTerje** [comment]
@lennartb- Yes, the ones that apply.  As @mikkelbu points out, the *compatibility* ones are not applicable anymore for the next 4.X version.  

The current notice (in notice.txt) points to the original writers of the NUnit code that the current code is based on, with no pointers to specific code sections.  For other copyright notices that should be noted.

Separate each section so that it is clear what it belongs to.
Use a format like this:
```
Copyright (c) [Year] [Author's Name]

The following code [specific file(s) or portion(s), with link] is used under [license name/version].

[Optionally additional details, such as license terms or any other relevant information.]
```
If the license is embedded in the source code, like with Options.cs, just state that.

After a quick search, that file is the only one I find with a copyright notice though.

**Comment by OsirisTerje** [comment]
@KalleOlaviNiemitalo Feel free :-)   It's just part of the same but by all means.  I assumed you or @lennartb- wanted to raise a PR on this.
