### ISSUE TITLE
Debugging F# NUnit tests in VSCode

### ISSUE THREAD

**Issue by atlemann** [nunit/nunit#3870]
For C# projects you get the code lens above each test (https://github.com/nunit/nunit/issues/2458), but this doesn't seem to work for F# projects.

![image](https://user-images.githubusercontent.com/16226914/120757075-5fa92000-c510-11eb-928f-55b78cde0a16.png)

Is there a way to make this work or is there some other way?

**Comment by mikkelbu** [comment]
I'm closing this as answered, as I don't think we (NUnit) can do anything about this, as this is functionality that needs to be implemented as an extension to vsCode.

It seem like you have to pay to make it work for F# projects (It can be that there exists free alternatives, but I rarely use F#, so I don't know)

See https://github.com/ionide/ionide-vscode-fsharp/issues/609 and https://gumroad.com/l/NeptunePlugin

**Comment by atlemann** [comment]
Ok, thanks for answering. Unfortunately, the Neptune plugin was killed a long time ago.

**Comment by mikkelbu** [comment]
Sorry about that. I don't know if there are other extensions, but so far I've not found any.
