### ISSUE TITLE
Running Nunit console runner 

### ISSUE THREAD

**Issue by csanghavi** [nunit/nunit#3880]
I am trying to use nunit3-console for running a test method which also has testcase attribute with two parameters. 

The issue I am facing is that any values passed from parameters while using console runner are not used. Is this expected behavior ? Or there is something else that I need to do to use in command line so that it ignores the values passed in TestCase attributes.
Here is code snippet: 

```csharp
using NUnit.Framework;
namespace My_Tests
{
    public class Foo 
    {
      [OneTimeSetup]
      public void Initialize() {}
      {OneTimeTearDown]
      public void Teaddown() {}

        [TestCase("dbType", "SubFolder")]
        public void TestMethod(string databaseType, string testDataFolder)
        {
           ....
           bool result = .. some operations
           Assert.IsTrue(result);
        }
   }
}
```
From VS I can successfully run this test which takes testcase attribute values as shown above.

From command line also, the same test runs fine (Note that different values for databaseType and testDataFolder)

```
>nunit3-console --test="My_tests.Foo.TestMethod" 
                            --testparam:databaseType="SomeDbNotSameAsDbType" --testparam:testDataFolder="AnotherSubFolder"
                            "C:\MyFolder\MyProject\bin\debug\My_Tests.dll"
```

 This test runs fine (ignore any typing errors) and I see the output showing two parameters as passed above. 
 The issue I see is that this method takes "dbType" and "SubFolder". 
 
Not sure whether there is a way to let nUnit framework take the values passed from command through console runner and  ignore the existing values defined in TestCase attribute.

Thanks
Chandresh

**Comment by mikkelbu** [comment]
Hi Chandresh

You are mixing different concepts. The `TestCaseAttribute` is a way to write a parametric test and then run the test with different hardcoded inputs each hardcoded input given by `TestCaseAttribute` - see e.g. https://docs.nunit.org/articles/nunit/writing-tests/attributes/testcase.html for examples.

Test parameters as passed in via `--testparam` in the console can be accessed in the test-run using via `TestContext.Parameters`. 

You can obtain what you want by using a `TestCaseSourceAttribute` and then return the hardcoded data, if no parameter has been supplied. So something like the following

```csharp
using NUnit.Framework;

namespace My_Tests
{
    public class Foo
    {
        public static object[] TestData()
        {
            var databaseType = TestContext.Parameters.Get("databaseType") ?? "dbType";
            var testDataFolder = TestContext.Parameters.Get("testDataFolder") ?? "SubFolder";

            return new[]
            {
                new object[] { databaseType, testDataFolder }
            };
        }

        [TestCaseSource(nameof(TestData))]
        public void TestMethod(string databaseType, string testDataFolder)
        {
            // some test
        }
    }
}
```

But since we only create one test (using either the hard-coded value or the provided value) we could just as well move this to the concrete test (the only downside is that you cannot see from the test name - in the test output - whether the test was run using the hardcoded values or some data from the test parameters).

```csharp
    public class Foo
    {
        [Test]
        public void TestMethod()
        {
            string databaseType = TestContext.Parameters.Get("databaseType") ?? "dbType";
            var testDataFolder = TestContext.Parameters.Get("testDataFolder") ?? "SubFolder";

            // some test
        }
    }
```

**Comment by csanghavi** [comment]
Hi Mikkel,

Thanks for quick response. I know I have been using two different ways to test and mixing two different ways (TestCase attribute and --testparam using Console Runner) of testing, but I feel using both are necessary sometimes. 1) We already had quite a few test cases created using TestCase attribute and tested out well in advance.. Now the requirement is to test out all test cases with various values without touching the code. So, I was running console runner and expecting some flag or something which can find TestContext parameters exists and use it as long as it is run thru console runner and --testparam  are used. 2) Using VS debug environment with TestCase sounds like always the first preferred way to test the method (I do not want to debug the test running thru console runner.. ).. 3) The console runner still uses parameters passed thru testcase attributes even if the they are not passed thru --testparam using console runner.. this is already a case of mixing parameters and console runner always going with data defined thru TestCases.

For now, I will use the code to switch between testparam and testcase (because I do not want to throw the testcases defined in the code). But, I still think/hope there needs to be a way to override/ignore testcase parameters and use --testcaseparam (if passed with console runner command , or throw up error message in console that user must pass testparam and testcase params will be ignored).. because this is quite possible that other users may end up first using the testcase parameters and then switch to using console runner.
