### ISSUE TITLE
Is not possible to use `netstandard2.0` assembly in place of `net45`

### ISSUE THREAD

**Issue by GibbOne** [nunit/nunit#3896]
I created a simple test project on `net472` framework.

[TestDotNetStandard.zip](https://github.com/nunit/nunit/files/6823701/TestDotNetStandard.zip)

that works correctly.

![image](https://user-images.githubusercontent.com/12271500/125803028-26f22501-cfe4-48fa-bf55-3df589536b7c.png)

In the output directory I find `nunit.framework.dll` copied from `nunit 3.13.2\lib\net45` of the packages folder.

If I replace `nunit.framework.dll` file contained in the output directory with the version contained in `nunit 3.13.2\lib\netstandard2.0` folder of the package, I receive the following error.

![image](https://user-images.githubusercontent.com/12271500/125803966-c2ff7da9-0d07-40bf-b921-e157bb4f22f1.png)

```
System.InvalidCastException: Unable to cast transparent proxy to type 'System.Web.UI.ICallbackEventHandler'.
```

Why are not compatible? It should not have additional dependencies.

Am I wrong?

Thanks

**Comment by rprouse** [comment]
I think you are running into a mistake that was made a long time ago when NUnit used the `System.Web` interface `ICallbackEventHandler`. It isn't available in .NET Standard, so we handle callback using `Action` if I remember right.

Like you said, it should work but it doesn't. That is one reason why we maintain the .NET 4.5 targets.

**Comment by rprouse** [comment]
I'm going to close this as a question. You were overriding the way we package and distribute the framework so this isn't something we are going to fix even if it is an interesting edge case.
