### ISSUE TITLE
NUnit 3.13.2 : LessThanOrEqualTo fails on a case which should succeed

### ISSUE THREAD

**Issue by ydubernet** [nunit/nunit#3898]
On latest 3.13.2 version, I have this unexpected behaviour : 
![image](https://user-images.githubusercontent.com/10231598/126669441-dc574aff-f868-4876-bb1b-0c0c734e3c5d.png)

I expect the output number to be less than or equal to the initial number, it is the case, and yet the test execution context throws an AssertionException.

Here is a code example :
```
[Test, Repeat(1000)]
public void Test()
{
    var floor1 = 95217168582.206969750145956m;
    var floor2 = 95217168582.20696975014595521m;
    Assert.That(floor2, Is.LessThanOrEqualTo(floor1));
}
```

For your interest, I have tried to reproduce it in version 3.13.1 and it does not fail.
Hence it looks linked to a bug in between 3.13.1 and 3.13.2.

Best regards

**Comment by stevenaw** [comment]
Thanks for reporting this @ydubernet 
I can confirm this is still present on the `v3.13-dev` branch
