### ISSUE TITLE
Allow randomizing 'Guid' test arguments with [Random]

### ISSUE THREAD

**Issue by julealgon** [nunit/nunit#3899]
`[Random]` currently supports several primitive types (mostly numeric ones), but it does not work with `Guid`. To provide different values to a `Guid` argument, one has to manually provide them either via `[TestCaseSource]` or via `[ValueSource]`.

In my experience, being able to easily provide different `Guid` values to a test is fairly useful. Currently, I'm doing this by using a `ValueSource`, which caused a [different problem](https://github.com/nunit/nunit/issues/3894), forcing me to resort to hardcoded `Guid`s instead of using `Guid.NewGuid`.

I'm aware that `Guid` randomization is different than the standard one using the `Random` class, so I'm not sure if it would be possible to have the same "seed" in discovery and execution phases to build the unique test names with the built-in values (probably not).

**Comment by julealgon** [comment]
The last part of my post is probably not true as per [this comment from @jnm2](https://github.com/nunit/nunit/issues/3894#issuecomment-881877904) :
> In the meantime, that suggests the workaround you could use. Instead of Guid.NewGuid(), use `TestContext.CurrentContext.Random.NextGuid()`.

I guess you could then easily leverage this for generating the random `Guid` values in a consistent manner like any other random values are created today.

**Comment by mikkelbu** [comment]
Closed by #3951
