### ISSUE TITLE
Category inclusion/exclusion is ignored when it comes to SetUpFixtures

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#39]
In my DLL there are a few TestFixtures, divided to various categories with the Category attribute.
There's also one SetUpFixture that has a global SetUp method, and it's marked with Category("OneCategory").

When I run nunit (either console or GUI) with "/include=OneCategory", the global SetUp method runs, followed by all tests from OneCategory. This is great. However, when I run nunit with "/include=OtherCategory", the same global SetUp method still runs - followed by all tests from OtherCategory. Adding an explicit "/exclude=OneCategory" doesn't seem to help either.

I'd expect that category inclusion and exclusion would also affect the SetUpFixtures that run, not only TestFixtures that run.

See comment at https://bugs.launchpad.net/nunit-3.0/+bug/616226

**Comment by rprouse** [comment]
Nobody has picked this up and nobody else has asked for this so closing.
