### ISSUE TITLE
.Net Core Project Assemblies in Parallel

### ISSUE THREAD

**Issue by Icaroto** [nunit/nunit#3905]
Hi, this is more a question than an issue (I think):

I have a .Net Core project where I use SlowCheetah to have multiple configurations generated. To run my tests, I use :
`dotnet test "assembly.dll" "assembly2.dll"`

I noticed the tests from the assemblies do not run in parallel, but one after the other. Is that the expected behaviour? If so, is there a way to make those 2 assemblies run at the same time? 

I used to use  nunit3-console to run them in parallel, but for some reason, it doesnt find my configuration file so I'm trying other options!

Thanks!

**Comment by rprouse** [comment]
As far as I know we have no control over how `dotnet test` runs your assemblies, we don't get called until it loads our test adapter.

**Comment by rprouse** [comment]
Closing as a dormant/answered question.
