### ISSUE TITLE
I'd like to test excuted on the UI Thread.. but it is impossible on the latest NUnit :(

### ISSUE THREAD

**Issue by junimnjw** [nunit/nunit#3908]
Hello. I am a user of Nunit. 
I have recently update NUnit version from 3.8.1 to 3.12.1. 
after Updated, there is one issue that our TCs are excuted on not UI thread.. 
Our TCs are based on UI Framework API..so it should be excuted on UI Thread...
Could you please add any feature or attribute to test TCs on UI Thread in the next version?

**Comment by jnm2** [comment]
I wonder if it could have been fixing https://github.com/nunit/nunit/issues/2821 that caused this change.

You can already run tests on a UI thread, but it may require a little extra setup. It depends on which UI framework you use. For Windows Forms, you can put `SynchronizationContext.SetSynchronizationContext(new WindowsFormsSynchronizationContext());` in a `[SetUp]` method, for instance, and `[ApartmentState(ApartmentState.STA)]` on the test class.

**Comment by junimnjw** [comment]
I AM NOT USing windows form. I AM USING TINZEN'S OWN UIFW...

2021년 8월 10일 (화) 오후 10:22, Joseph Musser ***@***.***>님이 작성:

**Comment by jnm2** [comment]
I'm not familiar with that. Is that Tizen? Is there a micro sample you could share demonstrating the tests working using NUnit 3.8.1?

The change that I'm expecting to have affected you is #2821, and in that case, a small modification to the sample you provide will probably get it working with NUnit 3.12.1. I'm just guessing until I see it though. It would amount to setting the UI synchronization context in the setup of each test.

**Comment by mikkelbu** [comment]
I'm closing this as we have not heard back from the reporter in years
