### ISSUE TITLE
String comparison without whitespace

### ISSUE THREAD

**Issue by Crown0815** [nunit/nunit#3918]
In some situations a string comparison without taking whitespace into account is desirable.

A use-case would be JSON string comparison, which should be whitespace agnostic but requires perfect whitespace matching when using the `EqualConstraint`.

# Current solution to the issue

To avoid this issue I have to write

```csharp
Assert.That(resultingJsonString.WithoutWhitespace(), Is.EqualTo(expectedJsonString.WithoutWhitespace()));
```

where `WithoutWhitespace()` is an extension method removing all whitespace characters.

# Prefered syntax

It would be more fluent to write

```csharp
Assert.That(resultingJsonString, Is.EqualTo(expectedJsonString).IgnoreWhitespace));
```

`IgnoreWhitespace` was inspired by the existing `IgnoreCase` configuration.

**Comment by Dreamescaper** [comment]
You can create extension method similar to something like this:
```csharp
        private static readonly Regex _whitespaceRegex = new Regex(@"\w+");

        private static string ReplaceSpaces(string s) => _whitespaceRegex.Replace(s, " ");

        public static EqualConstraint IgnoreWhitespace(this EqualConstraint constraint)
        {
            return constraint.Using<string>((actual, expected) => ReplaceSpaces(actual) == ReplaceSpaces(expected));
        }
```

So you'd be able to write something like:
`Assert.That(resultingJsonString, Is.EqualTo(expectedJsonString).IgnoreWhitespace()));`

**Comment by ivan-gurin** [comment]
Some other expression types would also benefit of similar option, say `Is.Null.Or.Empty.IgnoreWhitespace` (unless this is already implemented somehow)
