### ISSUE TITLE
Question: Given a generic test fixture, is there a way to pass generic `TestCaseSource`s

### ISSUE THREAD

**Issue by EugeneKrapivin** [nunit/nunit#3923]
Hello,
I'm probably lacking some understanding in the framework :)

**Just to be on the safe side**: the example is not what I'm really doing, only the notion was carried from my real code.

here goes:

Given I have multiple classes:
```csharp
public class Adder : IOperator {}
public class Subtractor : IOperator {}
public class Multiplier : IOperator {}
public class Divider : IOperator {}
```

I want to be able to test some basic assumptions about all those classes in a single `TestFixture` that will have allow me to write a test only once and test it for all classes given I have a way to pass the correct `TestCaseSource`

```csharp
public abstract class GenericConverterTests<T, TSource>
  where T : IOperator, new()
  where TSource : new()
{
    
    [TestCaseSource(typeof(TSource), "Positive")]
    public void Test1(IOperand left, IOperand right, Result expected)
    {
        var operator= new T();

        operator.Bind(left);
        operator.Bind(right);

        var result = operator.Execute();
        //... assertions.
    }

    [TestCaseSource(typeof(TSource), "Negative")]
    public void Test2(IOperand left, IOperand right)
    {
        var operator= new T();

        operator.Bind(left);
        operator.Bind(right);

        Assert.That(() => operator.Execute(), Throws.Exception);
    }
```

Currently I'm failing due to a language limitation, it figures that C# doesn't allow to use generics in an Attribute constructor because Attributes are compile-time generated while generics could be runtime generated.

Is there a pattern I'm missing with NUnit to allow me to achieve this feat?

Thanks.

**Comment by stevenaw** [comment]
Hi @EugeneKrapivin 

Is the reason the containing class in your example is abstract only to be able to provide the type arguments? If so, would it work for you to use a `[TestFixture]` or perhaps `[TestFixtureSource]` to specify the closing generic type at class-level? Something like this (untested):

```csharp
[TestFixture(typeof(Adder), typeof(int))]
public class GenericConverterTests<T, TSource>
  where T : IOperator, new()
  where TSource : new()
{
    
    [TestCaseSource("Positive")]
    public void Test1(IOperand left, IOperand right, Result expected)
    {
    }
}
```

**Comment by EugeneKrapivin** [comment]
@stevenaw hey! That's the thing, I need different inputs for the test case source dependant on the operator I'm testing. All operators have the same basic assumptions, hence should have the same test flows.

Think multiplication and addition, both are operators over numbers and both have the commutative property. Both will have as input (2,3) but addition will have 5 as output while multiplication will have 6.

Now let's say I have N operators with M common properties, how do I write test fixtures such that the same fixture will be correct for all operators with the same M properties?

[My solution](https://github.com/EugeneKrapivin/JsonTranslate.NET/tree/main/tests/JsonTranslate.NET.Transformer.UnitTests/TypeConverters) was to create an abstract class with tests and I've inherited and overridden those tests, each override providing a relevant test case source.
