### ISSUE TITLE
Nuget package naming policies for third party packages.

### ISSUE THREAD

**Issue by vpenades** [nunit/nunit#3927]
I want to publish some packages on nuget.org to add some features to NUnit.

I would like to know which are the recomended naming policies for such packages.

I am tempted to go with "NUnit.*" as I've seen several third party packages published this way at nuget.org, but not sure if this policy is welcomed here.

My alternate naming policies would be:
- NUnit.ThirdParty.*
- *.NUnit

The packages I am considering are related to WPF and Numerics.Vectors

**Comment by rprouse** [comment]
@vpenades, there are a few legacy 3rd party packages with the `NUnit.*` prefix but we discourage that. We've found that the community sees those as official packages and come to us for support. We've reserved that prefix on NuGet.org, so hopefully no new packages can be added.

We'd previously discussed `NUnit.Contrib.*` for third party packages but I have not tested if NuGet will allow it and their admin inteface doesn't say. Other packages are using the `*.NUnit` style which I am fine with.

I'd also ask that you don't use our icon without modification to prevent confusion.

**Comment by vpenades** [comment]
Understood.

What about the namespaces inside the libraries? it's allowed to go with NUnit.* ? or it's also discouraged?

I'm writing a small library for testing images.... so I was thinking in using something like NUnit.Media or NUnit.Extras or something on that line.

The thing is, whenever I use nunit plus some other helper classes, the using * header is a pain to track and clean.

**Comment by vpenades** [comment]
Okey... I went with "NUnitForImages" ...  [repo here](https://github.com/OfCourseMyHorse/NUnit.Utilities) if you want to take a look.

**Comment by jnm2** [comment]
> The thing is, whenever I use nunit plus some other helper classes, the using * header is a pain to track and clean.

In C# 10, you can add this to your csproj to address this pain:

```cs
  <ItemGroup>
    <Import Include="SomeNamespace"/>
  </ItemGroup>
```

This is the equivalent of writing `global using SomeNamespace;` in any file (https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-10#global-using-directives) which itself is the equivalent of inserting `using SomeNamespace;` at the top of every file in the compilation.
