### ISSUE TITLE
The new features of C#9.0 cannot pass the test coverage

### ISSUE THREAD

**Issue by hdefucom** [nunit/nunit#3933]
If I use a new version of syntax.This line of code cannot be included in the test coverage.
```
if (c is (>= 'a' and <= 'z') or (>= 'A' and <= 'Z') or (>= '0' and <= '9'))
```
However, using the old version can pass the test coverage.
```
if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9'))
```

xUnit also has this problem

**Comment by mikkelbu** [comment]
NUnit don't handle the code coverage, so I'm quite sure the problem is not here. Do you use coverlet or a similar tool to create the coverage?
