### ISSUE TITLE
Assert.That overloads fails after upgrading to c# 10

### ISSUE THREAD

**Issue by ovebastiansen** [nunit/nunit#3940]
After upgrading to latest vs2022 some parts of the test code does not compile anymore.
1>C:\source\repos\nunit\csharp10issue\Tests\UnitTest1.cs(14,20,14,24): error CS0121: The call is ambiguous between the following methods or properties: 'Assert.That(TestDelegate, IResolveConstraint)' and 'Assert.That<TActual>(TActual, IResolveConstraint)'

Simple repro his here, just change langversion to 9.0 to see that the test project compiles
https://github.com/ovebastiansen/csharp10issue

**Comment by OsirisTerje** [comment]
@rprouse @jnm2

**Comment by Dreamescaper** [comment]
That was a roslyn bug, which is fixed now.
Probably will ship in next VS preview.
Don't think there's anything we can do here.

https://github.com/dotnet/roslyn/issues/56167

**Comment by ovebastiansen** [comment]
thanks, just found it and wanted to make sure it got the right attention. Wasn't sure if this needed to be fixed here, but it was only the test code that got this error ;)

**Comment by jnm2** [comment]
Also, here's the language design notes (including lines to issues) in response to a lot of feedback that the C# 10 previews broke things: https://github.com/dotnet/csharplang/blob/main/meetings/2021/LDM-2021-09-20.md#lambda-breaking-changes
