### ISSUE TITLE
Installing nunit packages from meta-package does not work

### ISSUE THREAD

**Issue by sungam3r** [nunit/nunit#3944]
Consider meta-package `Sdk.Build` with such section in props (or targets, it doesn't matter): 
```xml
 <ItemGroup Condition="'$(IsTestProject)' == 'true'">
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.11.0" />
    <PackageReference Include="NUnit" Version="3.13.2">
      <PrivateAssets>none</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NUnit3TestAdapter" Version="4.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Shouldly" Version="4.0.3" />
    <PackageReference Include="PublicApiGenerator" Version="10.2.0" />
  </ItemGroup>
```

When installed into target package
```xml
 <ItemGroup>
    <PackageReference Include="Sdk.Build" Version="1.0.0" PrivateAssets="all" />
 </ItemGroup>
```
all PackageReferences from Sdk.Build package are visible in solution explorer but the code doesn't compile - compiler doesn't see any class from NUnit package. Note that classes/methods from Shouldly or PublicApiGenerator are visible.

**Comment by sungam3r** [comment]
Nevermind, `PrivateAssets/IncludeAssets` was the cause of problem.
This config works well:
```xml
 <ItemGroup Condition="'$(IsTestProject)' == 'true'">
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.11.0" />
    <PackageReference Include="NUnit" Version="3.13.2">
      <PrivateAssets>none</PrivateAssets>
    </PackageReference>
    <PackageReference Include="NUnit3TestAdapter" Version="4.0.0">
      <PrivateAssets>none</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Shouldly" Version="4.0.3" />
    <PackageReference Include="PublicApiGenerator" Version="10.2.0" />
  </ItemGroup>
```

**Comment by sungam3r** [comment]
@mikkelbu Sorry, I was wrong, there is still an error. Small repro:
[sdk.build.zip](https://github.com/nunit/nunit/files/7265493/sdk.build.zip)
[Solution1.zip](https://github.com/nunit/nunit/files/7265495/Solution1.zip)

**Comment by sungam3r** [comment]
It turns out that the situation is even more strange.

1. Build sdk project and get nupkg from it.
2. Add local folder with nupkg from step 1 as nuget feed into VS.
3. Open solution1 in VS and build it. You will see
![изображение](https://user-images.githubusercontent.com/21261007/135592594-16adf17b-c3c9-4bc5-812f-cfecf1a58f0e.png)
4. Open poweshell or cmd from solution1 sln folder and run `dotnet build`. And...
![изображение](https://user-images.githubusercontent.com/21261007/135592932-ac6286ef-8a2a-4e1a-aa2a-ecf83a454a9e.png)
5. Now rebuild solution from VS and you will see the first picture again.

NOTE: if you comment `using NUnit;` and `[Test]` after that step and build again then you will see
```
Rebuild started...
Restored C:\Solution1\ClassLibrary1\ClassLibrary1.Tests.csproj (in 178 ms).
1>------ Rebuild All started: Project: ClassLibrary1.Tests, Configuration: Debug Any CPU ------
1>ClassLibrary1.Tests -> C:\Solution1\ClassLibrary1\bin\Debug\net5.0\ClassLibrary1.Tests.dll
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
``` 
😕 

ENV:

Microsoft Visual Studio Community 2019
Version 16.11.3

dotnet --info:
 Version:   5.0.401
 Commit:    4bef5f3dbf

(as well on machines with 5.0.301 SDK)

**Comment by mikkelbu** [comment]
I finally had time to take a closer look at this, and I got the same result as you, but it seems that the solution is to change the `using` from `NUnit` to `NUnit.Framework`, then I can compile the project and run the test.
![image](https://user-images.githubusercontent.com/1007631/139498178-8b33a3c2-7839-41b6-865d-b837eb3416eb.png)

**Comment by sungam3r** [comment]
> then I can compile the project and run the test.

Are you sure? I see the same errors for `using NUnit.Framework`. Are you using `dotnet build` to verify result?

**Comment by mikkelbu** [comment]
I cannot use `dotnet build` it fails with 
```
Microsoft (R) Build Engine version 16.10.1+2fd48ab73 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored ........Solution1\ClassLibrary1\ClassLibrary1.Tests.csproj (in 150 ms).
........Solution1\ClassLibrary1\Class1.cs(2,7): error CS0246: The type or namespace name 'NUnit' could not be found (are you missing a using directive or an assembly reference?) [........Solution1\ClassLibrary1\ClassLibrary1.Tests.csproj]
........Solution1\ClassLibrary1\Class1.cs(8,10): error CS0246: The type or namespace name 'TestAttribute' could not be found (are you missing a using directive or an assembly reference?) [........Solution1\ClassLibrary1\ClassLibrary1.Tests.csproj]
........Solution1\ClassLibrary1\Class1.cs(8,10): error CS0246: The type or namespace name 'Test' could not be found (are you missing a using directive or an assembly reference?) [........Solution1\ClassLibrary1\ClassLibrary1.Tests.csproj]

Build FAILED.

........Solution1\ClassLibrary1\Class1.cs(2,7): error CS0246: The type or namespace name 'NUnit' could not be found (are you missing a using directive or an assembly reference?) [........Solution1\ClassLibrary1\ClassLibrary1.Tests.csproj]
........Solution1\ClassLibrary1\Class1.cs(8,10): error CS0246: The type or namespace name 'TestAttribute' could not be found (are you missing a using directive or an assembly reference?) [........Solution1\ClassLibrary1\ClassLibrary1.Tests.csproj]
........Solution1\ClassLibrary1\Class1.cs(8,10): error CS0246: The type or namespace name 'Test' could not be found (are you missing a using directive or an assembly reference?) [........Solution1\ClassLibrary1\ClassLibrary1.Tests.csproj]
    0 Warning(s)
    3 Error(s)

Time Elapsed 00:00:01.24
```
and it "resets" the package dependencies
![image](https://user-images.githubusercontent.com/1007631/139508794-dcaa625d-28bf-43a0-923f-006ddc193a69.png)

But I can build in VS and when the build is done, then the package dependencies are back 
![image](https://user-images.githubusercontent.com/1007631/139509014-c7a5ef5a-e50e-4f38-b648-8353930d5762.png)

But the `dotnet build` makes VS crash when I examine the dependencies.

**Comment by sungam3r** [comment]
That's what I'm talking about - works from vs, but does not work from cli. It should work in both cases. Now it crashes on build server.

**Comment by rprouse** [comment]
Does it work if you do a `dotnet restore` first? All of my build scripts use that step before the build, so I haven't seen this.

**Comment by rprouse** [comment]
This sounds like a `dotnet` issue, not an NUnit one. Can you confirm that other meta packages work?

**Comment by sungam3r** [comment]
> Does it work if you do a `dotnet restore` first?

My CI script does `dotnet restore` first, yes. In fact, I noticed this error at first on CI. Next I tried to reproduce it locally. And you see that I could achieve this.

I have other meta packages  with `PackageReferences` inside `ItemGroup`s. They work.

I suspect that the case is in `IsTestProject` and some related stuff, maybe the order of MSBuild targets or property evaluation. I don't know.

**Comment by sungam3r** [comment]
Restore works OK
```
dotnet restore \
    -s http://someaddr/repository/local-nuget-release \
    -s http://someaddr/repository/nuget-remote \
    -s http://someaddr/repository/local-nuget-snapshot \
    --verbosity %build_Verbosity%
```
Then Build failed:
```
dotnet build \
  --nologo \
  --no-restore \
  --configuration %build_Configuration% \
  --verbosity %build_Verbosity% \
  -p:CI_Build=true \
  -p:UseAnalyzers=%build_UseAnalyzers% \
  -p:VersionSuffix=dev-%build.counter%
```

error CS0246: The type or namespace name 'NUnit' could not be found (are you missing a using directive or an assembly reference?)

**Comment by sungam3r** [comment]
> This sounds like a dotnet issue, not an NUnit one.

I don't know. I have such error only for NUnit. It may be shared responsibility.

**Comment by manfred-brands** [comment]
According to [NuGet](https://github.com/NuGet/Home/issues/9132#issuecomment-581740452) this is not supposed to work. The fact that it works in VS they call a bug.

`dotnet restore` adds the sdk.props to the `ClassLibrary1.Tests.csproj.nuget.g.props` file.

This file however adds new package references, but restore had already run and hence those will not be restored.
You say that the `Shouldy` parts works, but it doesn't. Comment out the `using NUnit` and the `[Test]` results in an error about `Shouldly`.

`dotnet restore` adds a nuget package and all nuget package's nuget reference to your project.
I can make your package work by adding the PackageReference to the sdk.build.csproj file.

Now the 'restore' knows it might need those packages.
Your .props file is still used to references the conditionally.

**Comment by sungam3r** [comment]
Wow! Thanks.

**Comment by sungam3r** [comment]
I want to note that the behavior seems inconsistent because I have long been using `PackageReference`s from SDK meta-packages to distribute analyzer packages. A lot of them, really. So `PackageReference` with analyzer works fine but `PackageReference` with "normal" package does not. 🤔

**Comment by mikkelbu** [comment]
Closing this as answered - please note that we will still see additional comments on this issue.
