### ISSUE TITLE
Dispose is not called on test fixtures with LifeCycle.InstancePerTestCase without TearDown method

### ISSUE THREAD

**Issue by Crown0815** [nunit/nunit#3953]
# Issue

If I run the following test fixture, the `test_that_dispose_was_called` passes because the  `Dispose` method is called as expected.

```csharp
[FixtureLifeCycle(LifeCycle.InstancePerTestCase)]
public class Test_fixture : IDisposable
{
    private static bool _disposeWasCalled;

    [Test, Order(0)]
    public void test_running_first() => Assert.Pass("Some test running before");

    [Test, Order(1)]
    public void test_that_dispose_was_called() => Assert.That(_disposeWasCalled);

    [TearDown]
    public static void TearDown(){}

    public void Dispose() => _disposeWasCalled = true;
}
```
![image](https://user-images.githubusercontent.com/36126706/135986903-3116ebee-6beb-4502-8d02-c3b6fbed76ba.png)

However, if I remove the `TearDown` method, the `Dispose` method is no longer called and `_wasDisposed` remains false.

```csharp
[FixtureLifeCycle(LifeCycle.InstancePerTestCase)]
public class Test_fixture : IDisposable
{
    private static bool _disposeWasCalled;

    [Test, Order(0)]
    public void test_running_first() => Assert.Pass("Some test running before");

    [Test, Order(1)]
    public void test_that_dispose_was_called() => Assert.That(_disposeWasCalled);

    public void Dispose() => _disposeWasCalled = true;
}
```
![image](https://user-images.githubusercontent.com/36126706/135986857-e6ba0ff5-df9c-40b4-af2f-78a9977f466c.png)

# Expected

I would have expected `Dispose` to be called after every test if the fixture has the attribute `FixtureLifeCycle(LifeCycle.InstancePerTestCase)` set on it, independent of the presence of a `TearDown` method. This is expectation is based on [the documentation of the FixtureLifeCycleAttribute](https://docs.nunit.org/articles/nunit/writing-tests/attributes/fixturelifecycle.html), which states that `IDisposable` fixtures are disposed after each test.

**Comment by Crown0815** [comment]
It appears to be linked to exceptions being thrown from the `test_running_first`. If `test_running_first` throws no exception (`Assert.Pass(...)` also throws an exception) the `Dispose` method is called as expected.

```
[FixtureLifeCycle(LifeCycle.InstancePerTestCase)]
public class Test_fixture : IDisposable
{
    private static bool _disposeWasCalled;

    [Test, Order(0)]
    public void test_running_first() {}

    [Test, Order(1)]
    public void test_that_dispose_was_called() => Assert.That(_disposeWasCalled);

    public void Dispose() => _disposeWasCalled = true;
}
```
![image](https://user-images.githubusercontent.com/36126706/135992443-2e261d31-a0c7-4ec9-aa76-19646c2beb8e.png)

**Comment by stevenaw** [comment]
Thanks for reporting this @Crown0815 !
I think there's been a few bugs fixed in this area in recent releases. Can you please confirm which version of the NUnit framework you are seeing this on?

**Comment by stevenaw** [comment]
Thanks for confirming @Crown0815

**Comment by mikkelbu** [comment]
I can confirm it on the 3.13-dev branch

**Comment by mikkelbu** [comment]
@rprouse Shouldn't this be in the 3.13.3 milestone? (I guess that 3.13.3 will be released before 4)

**Comment by rprouse** [comment]
If I remember right, the pr for this went to master. There was another pr that cherry picked it, so I marked that with the 3 milestone

**Comment by mikkelbu** [comment]
You are right. #3962 is marked with the 3 milestone
