### ISSUE TITLE
DictionaryContainsKeyValuePairConstraint doesn't work with `IDictionary<TKey, TValue>`

### ISSUE THREAD

**Issue by pantosha** [nunit/nunit#3964]
`DictionaryContainsKeyValuePairConstraint` fails when actual object implements only `IDictionary<TKey, TValue>`, but not `IDictionary`:

```csharp
[Test]
void Test()
{
    var dictionary = new TestDictionary();
    Assert.That(dictionary, new DictionaryContainsKeyValuePairConstraint(1, "hello"));
}

class TestDictionary : IDictionary<int, string>
{
    // Dictionary implementation
}

// Test fails with next error:
// 1) Error : NUnit.Framework.Constraints.DictionaryContainsKeyValuePairConstraintTests.ShouldCallContainsKeysMethodOnDictionary
// System.ArgumentException : Expected: IDictionary But was: TestDictionary (Parameter 'actual')
```

**NUnit version:** 3.13.2
**Runner:** NUnit3TestAdapter

It looks like the bug is here: https://github.com/nunit/nunit/blob/2c21bff1d8891c2df3cad1f5ed34551e1c4edb9e/src/NUnitFramework/framework/Constraints/DictionaryContainsKeyValuePairConstraint.cs#L43

**Comment by rprouse** [comment]
Too much of this code was first written way too long ago before generics, so I expect this isn't the only case of this. Good find.

**Comment by louis-z** [comment]
I'd be interested in taking a stab at it, if no one else is looking into it.

**Comment by mikkelbu** [comment]
@louis-z You are most welcome. I've assigned the issue to you, please write if you have questions or problems.

**Comment by louis-z** [comment]
> @louis-z You are most welcome. I've assigned the issue to you, please write if you have questions or problems.

Though I'm not familiar with the codebase much, I just submitted an initial fix. Let me know whether the PR complies with this project's standards. Thanks @mikkelbu.

**Comment by ColonelPanic-42** [comment]
Is there any chance of backporting this fix to the current release?

**Comment by stevenaw** [comment]
The change seems fairly low-risk at a glance. @mikkelbu do you have any concerns?

**Comment by mikkelbu** [comment]
@stevenaw No. I think this should be quite safe.

**Comment by stevenaw** [comment]
Ok thanks for your confirmation! If no one else objects, I can tackle this next when when I return from travels
