### ISSUE TITLE
2question, driver inheritance, classes tests which each of them inherit driver

### ISSUE THREAD

**Issue by iamgithb** [nunit/nunit#3967]
When i have a lot of classes with tests which each of them inherit my base driver and support classes without test which also inherit my base driver.
And if i init class with test for use test in other class, i have driver null err (NullReferenceException).
This is to be expected.

If anybody have best practices, about this. _Example, will be below_

**Comment by mikkelbu** [comment]
Closing this issue as we have not heard back from the reporter.
