### ISSUE TITLE
3question, i dont know, issue this or other something 

### ISSUE THREAD

**Issue by iamgithb** [nunit/nunit#3968]
Some external method: 
```
public void verify() => Assert.Multiple(() => {
 Assert.That(() => driver.FindElement(By.XPath("//a")),
            Throws.TypeOf<NoSuchElementException>());
//..
});
```
External run:
```
[Test]
some name
Assert.That(() => verify(),
 Throws.Nothing);
```
show exception NoSuchElementException or MultipleAssertException may be without MultipleAssertException 

If i use without Assert.Multiple, `Assert.That(() => driver.FindElement(By.XPath("//a")),
            Throws.TypeOf<NoSuchElementException>());` works good

**Comment by iamgithb** [comment]
> Why do you need to wrap Assert.Multiple inside other Assert statement?...

I dont know, Iam tester. 
Sometime work is Ok, sometime Exception thorw to [test] 
Expected: <OpenQA.Selenium.NoSuchElementException>

**Comment by Dreamescaper** [comment]
I don't know what you're trying to achieve.

But probably you don't need that, just use Assert.Multiple directly, without wrapping it into other Assert.

**Comment by iamgithb** [comment]
via debug, Throws.TypeOf<NoSuchElementException>() completed successful
via autorun Run test. Test crushed with
`Expected: <OpenQA.Selenium.NoSuchElementException> But was: no exception thrown` 
funny not funny if i have not brain

**Comment by rprouse** [comment]
Closing as a dormant/answered question.
