### ISSUE TITLE
Nunit Retry not working for the below scenario

### ISSUE THREAD

**Issue by gnaneswarreddy** [nunit/nunit#3977]
I tried the below code for Nunit(3.13.2) retry on the test method for which the test got failed and it displayed Exepcted: No Exception to be thrown and But was ERROR here and then it is not retrying the test again. here is my sample test method

[Test, Retry(2), Category("Test")] [Description("Verifies the URL ")] [TestCaseSource(typeof(ExcelStatic), "Method Name", new object[] { "TestData\SampleTests2.xlsx", "sampletesttab"})] 

public void Test2_URL( string url, string application) {

        Assert.That(() => UtilitiesPage.URL(driver, appUrl), Throws.Nothing); //This method is present in the other libraries

    )

**Comment by mikkelbu** [comment]
How do you know it has not tried the test again? Given the following

```csharp
    public class Class4
    {
        public static int k = 0;

        public static IEnumerable<int> GetData => new[] { 1, 2 };

        [Retry(3)]
        [TestCaseSource(nameof(GetData))]
        public void TestThrowsNothing(int i)
        {
            TestContext.Error.WriteLine($"Called with i: '{i}' and k: '{k}'");
            Assert.That(() => SomeMethod(), Throws.Nothing);
        }

        public void SomeMethod()
        {
            k++;
            if (k < 3)
                throw new Exception("HELLO");
        }
    }
```
Then I get the following logged for `TestThrowsNothing(1)`
```
  Standard Error: 
    Called with i: '1' and k: '0'
    Called with i: '1' and k: '1'
    Called with i: '1' and k: '2'
```
and for `TestThrowsNothing(2)`
```
  Standard Error: 
    Called with i: '2' and k: '3'
```
so it seems like retry is working with `Throws.Nothing` and `TestCaseSource`.

If I change `if (k < 3)` into `if (k < 4)` then the first test fails with
```
      Expected: No Exception to be thrown
      But was:  <System.Exception: HELLO
...
```
as the method will fail the first three times it is invoked (and the first testcase only invoke it three times).

Can you provide a minimal reproducible example than illustrates the problem, i.e. containing a complete example, so we can examine it. It is always hard to diagnose partial code snippets, and puts the burden of work on us.

**Comment by mikkelbu** [comment]
I'm closing this issue as answered. Please note that we will still see additional comments.
