### ISSUE TITLE
Can Assert.Throws<TException> return null?

### ISSUE THREAD

**Issue by gps7** [nunit/nunit#3982]
Hi,
We have quit Unit tests expecting exceptions by fallowing template:

```
var error = Assert.Throws<Exception>(() => { .... throw Exception() });
Assert.That(error.Message, Is.EquilTo("....."));
```

However, combining the third party tool like Resharper this shows possible NullReference exception on Assert suggestion to add new validation:

```
var error = Assert.Throws<Exception>(() => { .... throw Exception() });
Assert.That(error, Is.Not.Null);
Assert.That(error.Message, Is.EquilTo("....."));
```

We find this is as noise since error never returned as null since would defeat the purpose to validate exception. I know that there are different syntaxes on validation and I found different one to see if the null is possible:

`Assert.Throws((Type)null, () => { });`

But this simple code execution fails with weird exception:

_Expected: null
But was: null_

So I wonder, if there are possibilities really to get null exception result for [Assert.Throws<T>](https://github.com/nunit/nunit/blob/d8e06e82210733f887b9afb9056ef18b7258b9cf/src/NUnitFramework/framework/Assert.Exceptions.cs#L104)? If this is not possible then I would raise code documentation bug which does not say that returns not nullable object of type exception. This would eliminate the warning of possible null as well as won't suggest to add a check.

**Comment by Dreamescaper** [comment]
It can return null if the assertion is wrapped in Assert.Multiple block.

**Comment by mikkelbu** [comment]
The documentation of `Assert.Throws` should say `Verifies that a delegate throws a particular exception when called. The returned exception may be <see langword="null"/> when inside a multiple assert block.` - see e.g. https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Assert.Exceptions.cs

Closing this as a duplicate of #3717 - @manfred-brands has a good explanation in https://github.com/nunit/nunit/issues/3717#issuecomment-758583151 and also proposes to use the NUnit.Analyzers to suppress these warnings.
