### ISSUE TITLE
NUnit failed to load

### ISSUE THREAD

**Issue by warinthornS** [nunit/nunit#3987]
I don't know how to fix it.

![image](https://user-images.githubusercontent.com/18109120/141419040-69ec0ebd-e044-4b44-a8e8-b527cc200d25.png)

![image](https://user-images.githubusercontent.com/18109120/141436803-b050b341-8acc-48ff-9a7d-51d8ec446bff.png)

![image](https://user-images.githubusercontent.com/18109120/141419257-5201da23-1542-45c8-b9c4-f9757ce08741.png)

**Comment by rprouse** [comment]
Do you also have a dependency on `Microsoft.NET.Test.Sdk`? It is required.

**Comment by warinthornS** [comment]
> Do you also have a dependency on `Microsoft.NET.Test.Sdk`? It is required.

Yes, I have

![image](https://user-images.githubusercontent.com/18109120/141712069-a2fb3aae-6d4f-41f4-83d4-cd2033307c28.png)

**Comment by mikkelbu** [comment]
I'm a bit surprised that the id is `0-1003`. I would have expected it to be `0-1000`. @warinthornS can you attach a complete example to this issue, so we can check it locally. My best guess is that there is either something odd in the project file or you have some problematic dlls in the output

**Comment by warinthornS** [comment]
> I'm a bit surprised that the id is `0-1003`. I would have expected it to be `0-1000`. @warinthornS can you attach a complete example to this issue, so we can check it locally. My best guess is that there is either something odd in the project file or you have some problematic dlls in the output


มันแปลกที่เมื่อฉันนำโปรเจคไปทดสอบบนคอมพิวเตอร์เครื่องอื่นกลับไม่มีปัญหานี้
