### ISSUE TITLE
Revisit build documentation relating to IDEs

### ISSUE THREAD

**Issue by stevenaw** [nunit/nunit#3989]
I don't have experience with MonoDevelop myself, but I noticed it is explicitly listed in the [build documentation](https://github.com/nunit/nunit/blob/master/BUILDING.md) as not able to build nunit due to lack of multi-targeting support since .NET3.5. The main branch of nunit no longer targets .NET 3.5. NUnit's build docs mention the kanban board on MonoDevelop's github repo hasn't been updated since 2019. The repo itself is in an "archived" readonly state.

Visual Studio and VSCode are listed as cross-platform IDEs known to work. Should MonoDevelop be removed from the build docs?

**Comment by rprouse** [comment]
Yes we should. Since Microsoft bought Xamarin and developed VS for Mac there haven't been any updates. When we first noticed it wasn't being updated we'd hoped that it would change, but that seems unlikely now.

**Comment by stevenaw** [comment]
I've updated the title slightly to broaden the scope of this to revisit the docs suggesting IDEs in general. Now that NUnit build targets net60, I think the mention of `Visual Studio 2019 16.8 or newer` mentioned in [BUILDING.md](https://github.com/nunit/nunit/blob/master/BUILDING.md) will need to be revised since building net60 is not supported on Visual Studio 2019.

I'm unsure whether it's best to simply increase it to mention Visual Studio 2022 or perhaps make it more generic like "latest stable Visual Studio". Should an explicit IDE be mentioned at all, or would it be enough to say a ".NET 6-capable IDE" and then call out Visual Studio + Visual Studio Code by name as examples?
