### ISSUE TITLE
C#10 Call is ambiguous

### ISSUE THREAD

**Issue by manfred-brands** [nunit/nunit#3993]
With C#10 new delegate/lambda resolving, I get ambiguous errors on `Assert.That(TestDelegate, ...)`

```
[Test]
public void Test()
{
    static void Method() => throw new NotImplementedException();

    Assert.That(() => Method(), Throws.TypeOf<NotImplementedException>(), "Wrong Magic");
}
```

![image](https://user-images.githubusercontent.com/8655218/142378300-20bd0e1a-bc18-42df-9728-6d9d32b7d116.png)

The only way to resolve it seems to cast the first parameter to `TestDelegate`:
```
    Assert.That((TestDelegate)(() => Method()), Throws.TypeOf<NotImplementedException>(), "Wrong Magic");
```

**Comment by appel1** [comment]
https://developercommunity.visualstudio.com/t/CS0121-ambiguous-call-for-generic-method/1534736

**Comment by jnm2** [comment]
This is a bug that was introduced in RC1 and fixed in RC2 and the general release. I no longer repro this.

I believe this issue is a duplicate of https://github.com/nunit/nunit/issues/3940.

**Comment by jnm2** [comment]
Oops, I do repro and this is not a duplicate. My repro solution was overriding langversion so my test was invalid.

**Comment by manfred-brands** [comment]
The reference issues says fixed in October, but I'm running .NET6 release and it didn't make it to the release.

**Comment by jnm2** [comment]
So https://github.com/dotnet/csharplang/blob/main/proposals/csharp-10.0/lambda-improvements.md caused some intentional breaks. Some were fixed in RC2, others were intentionally left under (if I remember right) the theory that libraries will be able to add overloads to resolve ambiguities. I'm not sure if that's possible here though.

**Comment by jnm2** [comment]
What's weird is that removing the `params` argument makes it start compiling.

**Comment by jnm2** [comment]
This seems like a possible compiler bug. These are the two overloads the compiler calls ambiguous, right? If I place them by themselves, there's no error:

```cs
using NUnit.Framework;
using NUnit.Framework.Constraints;
using System;

#nullable enable

class C
{
    public void Test()
    {
        static void Method() => throw new NotImplementedException();

        That(() => Method(), Throws.TypeOf<NotImplementedException>(), "test");
    }

    public void That(TestDelegate code, IResolveConstraint constraint, string? message, params object?[]? args) { }
    public static void That<TActual>(ActualValueDelegate<TActual> del, IResolveConstraint expr, string? message, params object?[]? args) { }
}
```

**Comment by jnm2** [comment]
If I remove each `params` parameter, the error goes away:

```cs
using NUnit.Framework;
using NUnit.Framework.Constraints;
using System;

#nullable enable

class C
{
    public void Test()
    {
        static void Method() => throw new NotImplementedException();

        // ❌ CS011  The call is ambiguous between the following methods or properties:
        // 'C.That(TestDelegate, IResolveConstraint, string?, params object?[]?)' and
        // 'C.That<TActual>(TActual, IResolveConstraint, string?, params object?[]?)'
        That(() => Method(), Throws.TypeOf<NotImplementedException>(), "test");
    }

    public static void That(TestDelegate code, IResolveConstraint constraint) { }
    public static void That(TestDelegate code, IResolveConstraint constraint, string? message, params object?[]? args) { }
    public static void That<TActual>(TActual actual, IResolveConstraint expression) { }
    public static void That<TActual>(TActual actual, IResolveConstraint expression, string? message, params object?[]? args) { }
}
```

**Comment by jnm2** [comment]
> 
> 
> https://developercommunity.visualstudio.com/t/CS0121-ambiguous-call-for-generic-method/1534736

@appel1 This one actually is different and was fixed in RC2 after feedback from RC1. (Same as https://github.com/nunit/nunit/issues/3940). What @manfred-brands found seems to only involve overloads with `params`.

**Comment by jnm2** [comment]
Looks like this is the exact same use case (NUnit with these `params` overloads) and it was a compiler bug: https://github.com/dotnet/roslyn/issues/57627

It's fixed for VS2022 Update 1 RC2 and they are considering servicing existing versions.

**Comment by manfred-brands** [comment]
The issue is fixed in [.NET 6.0.1](https://github.com/dotnet/roslyn/releases/tag/v4.0.1) released today.
