### ISSUE TITLE
Option to temporarily pause the run from the test code

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#40]
Add a method to Assert or TestContext to allow the user to cause the run to be paused while external action is taken. This is a general facility and will make it easier to do a number of things, including:
- Taking a dump
- Attaching a debugger
- Checking the status of external devices

See discussion at https://bugs.launchpad.net/nunit-3.0/+bug/730891

**Comment by rprouse** [comment]
Another enhancement that has been open for a long time without interest. Close as low value? Workaround is to temporarily add a `Thread.Sleep` or `Task.Delay`.

**Comment by jnm2** [comment]
Yes.
