### ISSUE TITLE
OverflowException comparing large double values

### ISSUE THREAD

**Issue by manfred-brands** [nunit/nunit#4000]
@stevenaw This fails on 3.13-dev, but succeeds on 3.13.2, it was introduced with #3898 

```
[Test]
public void DecimalRange()
{
    const double Maximum = 1e30;
    const double Value = 0.0099999999999988987;

    Assert.That(Value, Is.LessThan(Maximum));
}
```

It fails with:
```
  Message: 
System.OverflowException : Value was either too large or too small for a Decimal.

  Stack Trace: 
Decimal.ctor(Double value)
IConvertible.ToDecimal(IFormatProvider provider)
Convert.ToDecimal(Object value)
Numerics.Compare(Object expected, Object actual)
NUnitComparer.Compare(Object x, Object y)
```

The last change for testing range only test range if either of the parameters is `decimal`.
If both are `double` no range checking is done and we get this error.

I will raise a PR for this shortly.

**Comment by rprouse** [comment]
@manfred-brands can you cherry pick to 4.0?

**Comment by manfred-brands** [comment]
Done see #4003

**Comment by stevenaw** [comment]
Thanks for catching + fixing this @manfred-brands !
The original issue was surprisingly tricky, I'm not surprised to have missed this case

**Comment by mikkelbu** [comment]
Reopening this issue, so it can be closed by a PR
