### ISSUE TITLE
Test project Models does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project. It's recommended to reference NuGet test adapters in each test project in the solution.

### ISSUE THREAD

**Issue by GaneshMarkad11** [nunit/nunit#4011]
I' getting error after upgrading Nuget packages.
Error = "Test project Models does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
It's recommended to reference NuGet test adapters in each test project in the solution."

Visual Studio 2019
.Net Framework 4.7.2
MSTest.TestAdapter 2.2.8
Magenic.Maqs 6.4.1

I tried couple of solutions however not able to resolve this error.

**Comment by OsirisTerje** [comment]
Are you using NUnit?

**Comment by mikkelbu** [comment]
This is the NUnit project. Since you are using the MSTest adapter, then the question should be asked in https://github.com/microsoft/testfx

**Comment by GaneshMarkad11** [comment]
> Are you using NUnit?

No. I'm using MSTest.

**Comment by mikkelbu** [comment]
Closing this issue, as microsoft/testfx#1015 have been created.
