### ISSUE TITLE
Attaching debugger to NUnit runner

### ISSUE THREAD

**Issue by serezlan** [nunit/nunit#4015]
Hi,

I'm using emacs (dap+netcoredbg) to debug my application in linux. So far I've not been able to debug my unit test.
Is there a way for me to attach my debugger to NUnit runner? If not, what is the alternative?

AFAIK, NUnit console runner does not provide means to do this.

**Comment by mikkelbu** [comment]
@serezlan I don't have any experience in running the tests on Linux. Are you using the NUnit console runner on Linux? One possibility could be to use NUnitLite - see https://docs.nunit.org/articles/nunit/running-tests/NUnitLite-Runner.html.

**Comment by rprouse** [comment]
As Mikkelbu said, one option is to pull in NUnitLite and make your tests a self-executing EXE. You can then debug as you would any other program.

The console runner also has a `--debug` option to attach a debugger, but I haven't used it with .NET Core. I haven't used the console much lately myself.

**Comment by mikkelbu** [comment]
I don't think the `--debug` works on .NET Core at least the code for adding the option looks like this
```
            this.AddNetFxOnlyOption("debug", "Launch debugger to debug tests.",
                NetFxOnlyOption("debug", v => DebugTests = v != null));
```
So this probably only works on .NET framework

**Comment by rprouse** [comment]
I am closing this as answered.
