### ISSUE TITLE
Async test mystery

### ISSUE THREAD

**Issue by drieseng** [nunit/nunit#4016]
To be honest, I'm pretty sure I'm doing something dumb here (async newbie) but let me explain anyway:

I have an async test in Quartz.NET where I use a stopwatch to time how long a specific [call](https://github.com/drieseng/quartznet/blob/ed93e09be2c94987ac40276d6e3da3f4403d7107/src/Quartz/Core/QuartzScheduler.cs#L469-L563) to an async [method](https://github.com/drieseng/quartznet/blob/ed93e09be2c94987ac40276d6e3da3f4403d7107/src/Quartz/Core/QuartzScheduler.cs#L469-L563) takes:

```cs
var stopwatch = Stopwatch.StartNew();

var result = await scheduler.Shutdown(false);

stopwatch.Stop();
```

This test fails regularly when I run the tests in GitHub actions, but never fails locally. This is why I instrumented the method that we call to time each individual call to other methods and return a string containing these recorded timings.

Problem is that, even if the stopwatch indicates that the call to `scheduler.Shutdown(false)` took 200 ms to complete, the "recordings"  from that method indicate that it completed instantaneously (like it should). Could the async machinery really take 200 ms?

If you're sure this has nothing to do with NUnit, you can of course immediately close this issue.

**Comment by rprouse** [comment]
Is your test method `async Task`?

```c#
public async Task TestSomethingAsync()
{
}
```

**Comment by drieseng** [comment]
Yes, you can see the code [here](https://github.com/drieseng/quartznet/blob/ed93e09be2c94987ac40276d6e3da3f4403d7107/src/Quartz.Tests.Unit/SchedulerTest.cs#L325-L364).

**Comment by drieseng** [comment]
@rprouse No problem, I'm also an OSS hacker with only 24 hours in a few. I solved it by changing the test method to sync.
I'd love to have a fix, but more out of curiosity of what the cause is than out of necessity.

**Comment by rprouse** [comment]
Thanks, we aren't going to be able to dig in further, so I'm going to close this.
