### ISSUE TITLE
Assert.AreAnglesEqual(expected, actual, delta)

### ISSUE THREAD

**Issue by se5a** [nunit/nunit#4017]
Would it be too much to ask for something to handle testing angles as simple doubles along the lines of: `Assert.AreAnglesEqual(expected, actual, delta)`?

i.e. if I'm expecting something close to 0, but getting something close to 2pi and within the delta, it should still pass.

**Comment by manfred-brands** [comment]
This might be too specific to add to a general framework.
It is easy to do yourselves.

You can wrapped you angles, like in:

```
Assert.That(Wrapped(actual), Is.EqualTo(Wrapped(expected)).Within(0.1));

static double Wrapped(double angle) => Math.IEEERemainder(angle, Math.PI * 2);
```

**Comment by se5a** [comment]
isn't that going to break if actual or wrapped is 0? or 2.. or 4

**Comment by manfred-brands** [comment]
It breaks on comparing numbers on either side of the 2PI border. It becomes therefore a bit more complex:

```
        public void AssertAnglesRadians(double actual, double expected, double tolerance = 0.0)
        {
            Assert.That(Wrapped(actual, expected), Is.EqualTo(expected).Within(tolerance));

            static double Wrapped(double actual, double expected)
            {
                double delta = actual - expected;
                return delta < -Math.PI ? actual + (Math.PI * 2) : delta > Math.PI ? actual - (Math.PI * 2) : actual;
            }
        }
```

**Comment by mikkelbu** [comment]
I also think that this is outside the scope of NUnit. This could be handled in user code or as a separate assertion package.

**Comment by se5a** [comment]
Yeah, however it feels like there's enough edge cases when trying to write something to test something like this...

**Comment by se5a** [comment]
I ended up with:

`
    public static void AreAngleEqual(double expected, double actual, double delta)
    {
        double value = Math.PI - Math.Abs(Math.Abs(expected - actual) % Math.Tau - Math.PI);
        Assert.IsTrue(value <= delta);
    }
    public static void AreAngleNotEqual(double expected, double actual, double delta)
    {
        double value = Math.PI - Math.Abs(Math.Abs(expected - actual) % Math.Tau - Math.PI);
        Assert.IsFalse(value <= delta);

    }
`

**Comment by manfred-brands** [comment]
Although yours works, the error messages of mine are much clearer:

Mine:
```
Message: 
  Expected: 3.1415926535897931d +/- 0.0d
  But was:  3.041592653589793d
  Off by:   0.10000000000000009d
```

Yours:
```
Message: 
  Expected: True
  But was:  False
```
> does nunit treat delta as inclusive or exclusive?

Inclusive.

I didn't know about `Math.Tau`, but I see it was added in `net5.0`

**Comment by Dreamescaper** [comment]
You can also achieve that via custom comparer and extension methods, smth like that:
```csharp
    public static class EqualConstraintExtensions
    {
        public static EqualConstraint AsAngles(this EqualConstraint constraint)
        {
            return constraint.Using<object>((actual, expected) =>
            {
                var delta = constraint.Tolerance.IsUnsetOrDefault ? 0 : (double)constraint.Tolerance.Amount;
                double value = Math.PI - Math.Abs(Math.Abs(Convert.ToDouble(expected) - Convert.ToDouble(actual)) % Math.Tau - Math.PI);
                return value <= delta;
            });
        }
    }

    ....
    Assert.That(0, Is.EqualTo(2 * Math.PI).Within(0.01).AsAngles());
    Assert.That(Math.PI, Is.Not.EqualTo(2 * Math.PI).Within(0.01).AsAngles());
```

**Comment by stevenaw** [comment]
There hasn't been any activity on this issue in a few months, so I'm going to close it as "answered".
Please note that we will continue to see any follow-up discussion here
