### ISSUE TITLE
Nunit 3 - The test Outcome in Inconclusive at the end of the test

### ISSUE THREAD

**Issue by NadeemBader** [nunit/nunit#4027]
HI
I'm using the nunit3, and seems that it works as expected, bu lately I faced a strange behavior.
The test Outcome at the end of the test was Inconclusive even that all steps are passed. 
Seems that this a known issue when searching in the web, but I was not able to find a solution.
Any suggestions?
Best Regards,
Nadeem Bader

**Comment by mikkelbu** [comment]
Closed due to inactivity
