### ISSUE TITLE
[Feature Request] Support for simple Boundary Values generation using attributes

### ISSUE THREAD

**Issue by lsolano** [nunit/nunit#4029]
### Rationale
As usually errors are found near boundaries it will be good to have values generating attributes to express those more declarative. In a first stage this could be only for numeric ranges, but can be extended to other comparable types as well (like `DateTime` and related types).

Let's say that we have to capture some numerical data, like age, and the specification says that the valid values are positive integers between 18 and 150. Three partitions of values here: 

- Invalid Partition a: below 18
- Valid Partition: from 18 to 150 inclusive
- Invalid Partition b: above 150

The BVA technique recommends to pick boundary values from this partitions, and values just above and below those. We should test with:

- Invalid Values: `17` and `151`
- Valid Values: `18`, `19`, `149`, and `150`

Example taken from ["What is Boundary Value Analysis"](https://www.toolsqa.com/software-testing/istqb/boundary-value-analysis/)

### Proposal 
Create two new attributes `[ValuesWithinBoundaries(min, max)]` and `[ValuesOutsideBoundaries(min, max)]`.

#### Usage
```
// Produces: { 1, 2, 9, 10 }
[Test]
public void SomeTest([ValuesWithinBoundaries(1, 10)] int someInt)
  => Assert.That(() => testSubject.DoSomethingWith(someInt), Throws.Nothing);

// Produces: { 0, 11 }
[Test]
public void SomeTest([ValuesOutsideBoundaries(1, 10)] int someInt)
  => Assert.That(() => testSubject.DoSomethingWith(someInt), Throws.ArgumentException);
```

### Next steps
Wait for discussion / confirmation or rejection before submitting a PR with attributes implementation.

**Comment by Dreamescaper** [comment]
Is there any significant value over simply setting those values manually via [Values] ?..

**Comment by manfred-brands** [comment]
Like this, seems to be not much different from the requested and maybe even clearer.

```
[Test]
public void SomeTest([Values(1, 2, 9, 10)] int someInt)
  => Assert.That(() => testSubject.DoSomethingWith(someInt), Throws.Nothing);

[Test]
public void SomeTest([Values(0, 11)] int someInt)
  => Assert.That(() => testSubject.DoSomethingWith(someInt), Throws.ArgumentException);
```

**Comment by rprouse** [comment]
I agree with @manfred-brands that explicit passing and failing test names are even more explicit than attributes. For attributes to add value, all of the test runners would need to expose them.

**Comment by rprouse** [comment]
Thanks for the request. It is a good idea, but I don't think it is of wide enough value to add.

**Comment by lsolano** [comment]
@rprouse  @manfred-brands @Dreamescaper Thanks for your feedback.
