### ISSUE TITLE
Tests won't run with an abstract base class that has a TestCaseFixtureSource

### ISSUE THREAD

**Issue by thomhurst** [nunit/nunit#4032]
When reporting a bug, please provide the following information to speed up triage:

* NUnit and NUnit3TestAdapter versions
NUnit 3.12.2 NUnit3TestAdapter 4.2.0

* A short repro, preferably attached or pointing to a git repo or gist
[Repo Here](https://github.com/thomhurst/FailingAbstractTestCaseFixtureSourceNUnitTestProject) - Can't run tests when inheriting from an abstract base class that has a TestCaseFixtureSource

* What .net platform and version is being targeted
.NET 6

![image](https://user-images.githubusercontent.com/30480171/150138183-23efb515-72ef-41bf-80a9-f33b20c4c682.png)

**Comment by stevenaw** [comment]
@manfred-brands thanks for tackling this! The fix has been merged into the v3.13 branch. Would you be willing to cherry-pick the changes into main on a new PR so that they can be included in v4?
