### ISSUE TITLE
Drop net45 build target in nunit4

### ISSUE THREAD

**Issue by stevenaw** [nunit/nunit#4036]
The framework library is currently built for net45 + netstandard2.0, but net45 has hit EOL. Within a few months time, by April 26, 2022, net462 will be the minimum supported runtime by Microsoft (excluding 3.5 SP1) https://devblogs.microsoft.com/dotnet/net-framework-4-5-2-4-6-4-6-1-will-reach-end-of-support-on-april-26-2022/

I'm finding I'm having a hard time installing the required dependencies on Windows 11 to build the net45 version of the framework. It may be worth considering targeting minimum net462 in the next semver-major release 

@nunit/framework-team thoughts?

**Comment by stevenaw** [comment]
Actually, given net462 implements netstandard20 (which is already targeted) perhaps this is a time to consider dropping a netfx-specific build target altogether.

Adding @nunit/core-team as well for thoughts

**Comment by manfred-brands** [comment]
The one difference is that for a framework target we enable THREAD_ABORT:
```
  <PropertyGroup>
    <DefineConstants Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'">$(DefineConstants);THREAD_ABORT</DefineConstants>
  </PropertyGroup>
```

Unfortunately, despite the `Thread.Abort` method being in the net standard, all but the framework runtime throws a `NotSupportedException`.  The current solution for non-framework targets is just to leave it running in the background. See #4021.
If we do away with `Thread.Abort` in nunit 4, then we could have a single Library version. We still need all the runtime versions to test on the platforms.
```
    <NUnitLibraryFrameworks>net45;netstandard2.0</NUnitLibraryFrameworks>
    <NUnitRuntimeFrameworks>net45;netcoreapp3.1;net5.0;net6.0</NUnitRuntimeFrameworks>
```

**Comment by stevenaw** [comment]
Hmm, thanks, I'd forgotten about that. That's a really good point. We will still need to account for the differences in cancellation models between the runtimes.

**Comment by appel1** [comment]
Perhaps not a huge problem for test projects, but consuming a netstandard dll from a .NET Framework project puts a lot of unnecessary netstandard dlls in the bin output directory in addition to the dependency on netstandard.dll. It's only about 2.5MB but would still be nice if it could be avoided by providing a real .NET Framework 4.6.2 target.

**Comment by jnm2** [comment]
I'm happy to drop it. I thought in some thread @rprouse had floated the idea of making 4.8 the single supported .NET Framework target, but I might be mixing things up.

**Comment by stevenaw** [comment]
Oh, right you are @jnm2 thanks! I think I found the discussion in the overarching "NUnit 4 Planning" issue: https://github.com/nunit/nunit/issues/3325#issuecomment-513868269

It looks like net472 or net48 were suggested as ideas for targeting long-term support

**Comment by stevenaw** [comment]
I don't see a firm decision in #3325 around which netfx runtimes we want to build the framework for. However, I think it would be nice to be able to build v4 of the framework using the latest version of Visual Studio without requiring additional SDK installs beyond what's included in that. VS2022 only supports net462+

 @nunit/core-team @nunit/framework-team  would it make sense to:
1. Change the net45 build target to instead target net462 within the framework _on main only_
2. Create a follow-up issue for discussion on long-term runtimes to build against (and potentially a superset to test against)
3. Create a follow-up issue to use `Array.Empty<T>` in v4 instead of the helper defined in #4041

**Comment by CharliePoole** [comment]
Once upon a time, we had a build script that allowed building only those targets, which were actually installed on the build machine. That was way back when we were using a completely different build technology.

Should we consider reviving this? I've been thinking of doing that for the engine, so as to allow contributors to easily work on their machines with the CI build catching any problems in runtimes they did not have installed.

**Comment by manfred-brands** [comment]
To build locally, for any framework is now relatively simply due to the fact that `TargetFrameworks` are now only listed in `Directory.Build.props`:

```
    <NUnitLibraryFrameworks>net45;netstandard2.0</NUnitLibraryFrameworks>
    <NUnitRuntimeFrameworks>net45;netcoreapp3.1;net5.0;net6.0</NUnitRuntimeFrameworks>
```

There are two issues, `dotnet test` doesn't work (#3867) and `build.cake` has the targets hard-coded.
Maybe we can upgrade `build.cake` to check for installs and let it pass arguments to msbuild to override the settings in `Directory.Build.props`.

**Comment by rprouse** [comment]
Visual Studio currently installs the 4.5.2 targeting pack but, "Support for .NET Framework 4.5.2, 4.6, and 4.6.1 will end on April 26, 2022. Customers and developers must have completed the in-place update to .NET Framework 4.6.2 or later by April 26, 2022 to continue receiving technical support and security updates."

NUnit 4.0 is still a bit out and my policy has been to keep up to date with the LTS versions of the framework, so I'm okay with a new minimum of 4.6.2 for NUnit 4.0. Personally, I don't like forcing our contributors or team to install unsupported versions of the framework. I'm also of the opinion that we shouldn't be supporting targeting versions of the framework that aren't receiving security patches. In this day and age, it is irresponsible to do so.

**Comment by stevenaw** [comment]
@rprouse How should we approach this point above?

> Change the net45 build target to instead target net462 within the framework on main only

I agree with you about not requiring the installation of unsupported software. Would this mean also updating v3.13 branch to no longer build the framework against net45 (and if so, should we also be targeting net462 there within the framework lib itself) ?

**Comment by manfred-brands** [comment]
It is gone in VS 2022 Professional 17.2.0:
![image](https://user-images.githubusercontent.com/8655218/156301361-bfb40e6d-ebf1-40ec-91f8-7cd3ebd18f8e.png)

But they kept NET core 2.1?
Better install 4.6.2 then.

**Comment by stevenaw** [comment]
Since it sounds like we have general agreement on updating v4 to use net462, I'm going to drop the `awaiting:discussion` label here

**Comment by jnm2** [comment]
After they are out of support by Microsoft, then sure. Until then I don't know.
