### ISSUE TITLE
Assembly SetUpFixture with OneTimeSetup doesn't seem to work with .NET 6.0

### ISSUE THREAD

**Issue by appel1** [nunit/nunit#4038]
According to https://docs.nunit.org/articles/nunit/writing-tests/attributes/setupfixture.html you can have a SetUpFixture outside of any namespace and its OneTimeSetup is called before any tests are run in the whole assembly. Using NUnit 3.13.2 and the VS test runner with NUnit3TestAdapter 4.1.0 I cannot get this to work if the test assembly targets .NET 6.0. It works fine with .NET Framework. 

```
[SetUpFixture]
public class AssemblySetUp
{
    [OneTimeSetUp]
    public void SetUp()
    {
// I never get here with .NET 6.0.
    }
}
```

**Comment by sicil1ano** [comment]
I can confirm I'm unable to reproduce your issue with a test assembly targeting .NET 6, using  NUnit 3.13.2, NUnit3TestAdapter 4.1.0 and VS 2022 v17.0.6.

The SetUp method in AssemblySetUp class gets correctly hit in a debug session.

This is how my test project file looks like: 
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.11.0" />
    <PackageReference Include="NUnit" Version="3.13.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.1.0" />
  </ItemGroup>

</Project>
```

and my test class:

```
public class Tests
{
    [SetUp]
    public void Setup()
    {
    }

    [Test]
    public void Test1()
    {
        Assert.Pass();
    }
}
```

**Comment by appel1** [comment]
I'm using latest VS 2022. 

I'll see if I can reproduce this in a smaller sample project.

**Comment by appel1** [comment]
Sorry, my bad. I had added the setup class to the wrong test project. So I wasn't testing the same thing when targeting .NET 6 vs .NET Framework.😭
