### ISSUE TITLE
Minimze empty array allocations via centralized helper for pre-net46

### ISSUE THREAD

**Issue by stevenaw** [nunit/nunit#4041]
net462 + netstandard2 define a static `Array.Empty<T>()` helper which returns a cached empty array. There's a few places in the code where we `#ifdef` this in where it's easy but there's other places where this approach would be cumbersome. It might help to both cleanup the code + give a minor perf boost (via reduced allocations) by creating a helper to handle this.

This would be most useful for v3.13.x but could also have a place in v4 if we continue to target net45 there (https://github.com/nunit/nunit/issues/4036). If net45 support _is_ dropped in v4, then we should instead update all callsites to just call `Array.Empty<T>` directly instead

**Comment by mikkelbu** [comment]
@stevenaw It looks like #4042 didn't close this issue - even though it had a `Fixes #4041` ??? - (also they are not linked by GH). 

I've linked this PR now and will close this issue. Please reopen if you disagree.

**Comment by mikkelbu** [comment]
Closed by #4042

**Comment by stevenaw** [comment]
Hmm thanks for catching this @mikkelbu ! I wonder if the auto closing function only works for merging to main
