### ISSUE TITLE
Stop testing the framework against netcoreapp21 in v3.13 branch

### ISSUE THREAD

**Issue by stevenaw** [nunit/nunit#4043]
We currently run our framework tests against a variety of runtimes, including netcoreapp21. .NET Core 2.1 hit EOL on August 21, 2021. It's now about 6 months later and it looks like our CI builds are failing due to netcoreapp21 not being installed. I'd like to suggest we drop netcoreapp21 from our test targets as a solution to fixing the CI.

**Comment by stevenaw** [comment]
This change should be made in v3.13 + v4 branches so that both can continue to build

**Comment by manfred-brands** [comment]
It was dropped for nunit4 a while back when .net6 was added #3986

**Comment by stevenaw** [comment]
Ah thanks @manfred-brands ! I suppose this would be v3.13-specific then
