### ISSUE TITLE
Backport .NET6 test infra + build improvements from #3984 onto v3.13 branch

### ISSUE THREAD

**Issue by stevenaw** [nunit/nunit#4046]
As noted by @manfred-brands (https://github.com/nunit/nunit/issues/4036#issuecomment-1054919618)
We added .NET6 to our testing matrix on main in #3984 along with some nice build improvements to reduce duplication of specified runtime/library build targets. I think this could be a good candidate to backport to v3.13 as well as it will help keep the testing and tooling between the two consistent

**Comment by manfred-brands** [comment]
@stevenaw As those were my changed, would you like me to create a PR for this or do we need to wait for consensus?

**Comment by stevenaw** [comment]
You are very welcome to take this on if you have time @manfred-brands , thanks! You would definitely be most familiar with what's needed.
I think this should be a fairly safe thing to commit to on 3.13 given we know there's going to be a future release and this would allow us to test against the latest LTS, but lets see if at least a second person from @nunit/framework-team or @nunit/core-team is in favour.

**Comment by rprouse** [comment]
@manfred-brands I'd like to get a release out before the end of the month. Do you think you can get this in? I'd be cool to merge post release though.

**Comment by manfred-brands** [comment]
Sorry @rprouse I was waiting for someone to second the request as asked by @stevenaw. I missed you adding the milestone. Not sure if github creates notifications for that.
