### ISSUE TITLE
Simplify property retrieval in DefaultTestAssemblyBuilder.Build()

### ISSUE THREAD

**Issue by stevenaw** [nunit/nunit#4049]
[`DefaultTestAssemblyBuilder.Build()`](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Api/DefaultTestAssemblyBuilder.cs#L96) contains code which maps values in an `IDictionary<string, object>` to statically defined properties. The current code uses the following pattern:

```csharp
if (options.ContainsKey(name))
{
    var value = options[name] as {Type};
    if (value != null)
    {
      // Sets the property here
    }
}
```

I think this code predated the addition of `TryGetValue()` in the .net framework. We should consider updating it to use `TryGetValue` along with any other modernizations like pattern matching.

**Comment by manfred-brands** [comment]
There are other places doing similar:

`NamespaceTreeBuilder.GetNamespaceSuite`

```csharp
if (_namespaceIndex.ContainsKey(ns))
    return _namespaceIndex[ns];
```
`WorkItemBuilder.Compare`

```csharp
if (x.Test.Properties.ContainsKey(PropertyNames.Order))
    xKey = (int)x.Test.Properties[PropertyNames.Order][0];

if (y.Test.Properties.ContainsKey(PropertyNames.Order))
    yKey = (int)y.Test.Properties[PropertyNames.Order][0];
```

`NUnit2XmlOutputWriter`:

```csharp
if (test.Properties.ContainsKey(PropertyNames.Description))
{
    string description = (string)test.Properties.Get(PropertyNames.Description);
    ...
```

**Comment by Phyrik** [comment]
I'd like to work on this issue if that's ok

**Comment by stevenaw** [comment]
Welcome @Phyrik and thanks! You are very welcome to help on this.
Please let us know if you have any questions or run into any issues. Our build documentation is in need of a refresh, but you will likely need a .NET6-compatible IDE such as VS2022 in order to build nunit.

**Comment by Phyrik** [comment]
Thanks! I should have a PR today (GMT) for you

**Comment by Phyrik** [comment]
I've created a PR for this issue which you can find here: #4054
