### ISSUE TITLE
Stack Filtering Improvement needed for (at least) CF

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#405]
The stack traces displayed under the compact framework are extremely long and contain entries all the way down to the start of application execution. This is not helpful when the trace is displayed as part of the results of a test.

BACKGROUND

NUnit intercepts exceptions generated by tests and makes the stack trace a part of the test result. We handle two types of exceptions: (1) those that NUnit uses to report test results (e.g.: AssertionException) and (2) unexpected exceptions generated by the user code. Each is handled slightly differently.

Result exceptions like AssertionException are filtered from the top of the stack down, with any entries generated by the NUnit infrastructure removed. This leaves the point at which an assertion failed at the top of the displayed stack.

Exceptions that escape the user code are currently not filtered at all, since we want to see the exact point at which the exception was thrown.

In the past (.NET 1.x days) NUnit also filtered all exceptions from the bottom up so that the bottom of the stack represented the first point at which the NUnit passed control to user code. With the advent of .NET 2.0, this became unnecessary. That's because all calls to user code are done by reflection. When an exception is thrown, it is wrapped in a TargetInvocationException and modern versions of .NET already limit the bottom of the stack to the point where the reflection started.

The compact framework seems to be different. The InnerException of a TargetInvocationException includes the entire stack trace, which is much more than the user wants to see. For CF we need to re-instate the practice of pruning the bottom of the stack as well.

This will be trickier than it might seem at first, for two reasons:

1) The user code itself might call some method by reflection, so we have to locate the point where NUnit first gave control to user code.

2) If we look for NUnit namespaces in the stack, we have to allow for the fact that NUnit has its own tests, which should be treated as "user" code.

I'll look to see if I can find how we did this in old versions of NUnit and post a comment here.

If anyone knows of other platforms that suffer from the same issue, please post here.

**Comment by rprouse** [comment]
We no longer support CF and nobody is asking for this. Closing.
