### ISSUE TITLE
Simplify how to work with IPropertyBag

### ISSUE THREAD

**Issue by stevenaw** [nunit/nunit#4052]
Doing a search of `IPropertyBag.Keys` within the framework shows that, with one exception (size check), it's used almost exclusively to iterate over the contents of one bag in order to add it to another. Most "bulk copy" operations like this take the form of:

```csharp
foreach key in a.Keys
  foreach val in a[key]
    b.Properties.Add(key, val)
```

A few options which could help here could be:
- Allow `IPropertyBag` to implement `IEnumerable` or `IEnumerable<T>`
- Add a "bulk add" method to the interface, such as `IPropertyBag.AddRange(IPropertyBag)`
- Both/Other?

**Comment by stevenaw** [comment]
An open question for anyone who may know is if this class is useful to expose outside the framework. It's in the `NUnit.Framework.Internal` namespace but has public visibility. I know that historically some classes were given public visibility in that namespace, but I'm curious if it should stay public or not. Do runners commonly use this?

**Comment by stevenaw** [comment]
Based on some findings in https://github.com/nunit/nunit/issues/4049 it sounds like a `TryGetValue()` function could help too. Perhaps implementing `IDictionary<T1, T2>` could help

**Comment by stevenaw** [comment]
Alrighty, I've done a bit of digging and I think I've come up with what I consider to be a minimal API to add to IPropertyBag based on how it is used within the framework. I'd like to suggest the following additions to IPropertyBag:

```csharp
public interface IPropertyBag
{
  bool TryGetValue(string key, out IList<object> value);
  void AddRange(string key, IList<object> values);
}
```

AddRange could be implemented in a meaningful and optimized way on the framework's `PropertyBag` class if the  internal dictionary were changed from `Dictionary<string, IList>` to `Dictionary<string, List<object>>` to make use of `List<T>`'s `AddRange()` function. https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/PropertyBag.cs#L21

The following could then also be added as helpers based on some specific things we do within the framework itself. They could be added to the `IPropertyBag` interface itself but I am hesitant to suggest we add more to there than absolutely necessary, so another option could be as internal extension methods on the `IPropertyBag`:

```csharp
internal static class IPropertyBagExtension
{
   internal static bool TryGetSingleValue(this IPropertyBag instance, string key, [MaybeNullWhen(false)] out object value);
   internal static bool TryGetSingleValue<T>(this IPropertyBag instance, string key, [MaybeNullWhen(false)] out T value);
   internal static void CopyTo(this IPropertyBag instance, IPropertyBag other);
}
```

@nunit/framework-team @nunit/core-team  Thoughts? As this would involve adding methods to a public interface, this proposal would naturally break anyone who has defined a custom `IPropertyBag`, but I suspect it could make this type a bit easier to work with

**Comment by CharliePoole** [comment]
@rprouse Is this intended to be a public interface in NUnit 4?

**Comment by rprouse** [comment]
Let's hold off on any changes to the interface for NUnit 4. As for should it be public, I think I've seen it used occasionally in custom Attributes, but I might be mistaken. We'll need to make sure that it isn't exposed in any of our current public interfaces.

**Comment by CharliePoole** [comment]
The key interfaces using IPropertyBag appear to be ITest and ITestData., both of which are publicly exposed (ITest only for extensions).

In looking at the question of "what should be public" for nunit-console 4.0 I've been finding that the decisions need to be made from the outside inward, which is probably also the case here. That is, if either ITest or ITestData remain public and continue exposing IPropertyBag, then IPropertyBag itself needs to be public.

In the case of the console, I've been feeling the need to plan the API in advance, even though I normally like to work incrementally. Maybe that's true for the framework as well.

**Comment by stevenaw** [comment]
Should this be closed as `closed:wontfix` ?

**Comment by stevenaw** [comment]
Closing this. I don't think it'll be possible to do this purely via extension methods as most framework code calls against the interface but the optimized approach here will require access to private members of the concrete PropertyBag.

I'd hoped to take a usage-based approach here, but as Charlie mentioned we may need to look beyond the framework to find the truly valuable use cases. Those should probably be dealt with in dedicated future tickets as they are identified
