### ISSUE TITLE
[nunit v3.13.2] TestContext.CurrentContext.Test.Properties.Add has been taken out.

### ISSUE THREAD

**Issue by quldude** [nunit/nunit#4059]
In a previous nunit version , I used `TestContext.CurrentContext.Test.Properties.Add` to add extra properties for a test during test execution so that my TestEventListener could read those properties from the xml. But in the latest version the Add method is not supported. What is the best way to pass data to the event listener for a test? I dont want to output the data as its sensitive.

**Comment by stevenaw** [comment]
Sorry you have hit this @quldude 
I think this was a consequence of #1578 which was in the 3.10 release. Can you please confirm if you were updating from a version earlier than that one?

If so, there was a bit of discussion in that ticket around the rationale behind the change, and how disruptive it may be and to who. One suggestion for those who depended on the functionality of the old API, geared towards extension authors, is to use `TestExecutionContext.CurrentContext.CurrentTest.Properties` instead, however that accesses NUnit's _internal_ representation which itself may be subject to subtle changes in the future. 

Another option which may help is that NUnit 3.7 introduced the ability to associate and link a test attachment to the XML output. Would it work to write the sensitive values to a different file and to use the [`AddTestAttachment`](https://docs.nunit.org/articles/nunit/writing-tests/TestContext.html#addtestattachment-37) function to record the path in the XML for later consumption?:

**Comment by quldude** [comment]
thank you for the quick response @stevenaw ! Yes I was using an older version - 3.6.1. I'll take a look at both options and see which suits me better, although, I'm leaning towards more on AddTestAttachment function as you mentioned the other option might put me in this same situation.

**Comment by quldude** [comment]
@stevenaw with the latest version of testadapter I'm not seeing my ITestEventListener implementation being initialized when I run a test from visual studio test adapter. I've placed my addins file in `packages\NUnit3TestAdapter.4.2.1\build\net35`. In 3.6.1 I did the same with a previous version of testadapter and it worked. Do you know what I'm missing?

**Comment by quldude** [comment]
Used AddTestAttachment function to resolve this.
