### ISSUE TITLE
Warning-level Assertions

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#406]
Sometimes, you just want a warning! Please review the spec at https://github.com/nunit/docs/wiki/Warning-Level-Assert-Spec and comment here.

**Comment by CharliePoole** [comment]
I'd like to come back to discussion of this issue. I just updated the spec at  https://github.com/nunit/docs/wiki/Warning-Level-Assert-Spec

Let's try to resolve whether we want to do this (I favor it) and if so pick a syntax and put it onto our backlog again.

**Comment by ig-sinicyn** [comment]
@CharliePoole 
I'd expect warning assertions to be added into classic model API some day, so I vote for 'Expect.*' option.
This way `Expect.AreEqual()`, `Expect.Throws()` or `Expect.Contains()` will look fine.

In case we need more choices: `Assume.AreEqual()`, `Suspect.NotNull()` and `Guess.Greater()` to the rescue:)

**Comment by CharliePoole** [comment]
@ig-sinicyn I particularly liked Expect myself, so I'm sorry to say it's already a synonym for Assert in the AssertionHelper class. In case you didn't know, Assume already exists with its own special meaning.

How about `Hope.That` or `Pray.That`. 😆

**Comment by rprouse** [comment]
I like the idea of the feature, but I worry about how it will surface in the Visual Studio adapter or various CI servers. We have control over the CI adapter, so would we treat them something like ignored tests?

For the syntax, how about `IThink.That`? 😋 

`Warn.That` does not read well to me at all, I would use the alternative `Warn.If`. I would be okay with `Warn.Unless` too. I prefer the `Warn` keyword since its behaviour is explicit in its name. The other could be interpreted as synonyms for `Assert`.

**Comment by CharliePoole** [comment]
@rprouse I think I agree with you that `Warn` is the right keyword. In fact, nothing prevents us from going all perl-like and supporting both `Warn.If` and `Warn.Unless`!

**Comment by CharliePoole** [comment]
I updated the spec and I think we are ready to move take this out of design and add it to the backlog. Please check it over again @rprouse.

**Comment by rprouse** [comment]
Looks good to me. On the runner side, I am assuming we will count warnings and display them in the summary block at the end of the run and that they will be displayed like ignores. I also assume they will be summarized at each level of the test result XML. Something like `passed="58" failed="0" warnings="12"`.

**Comment by CharliePoole** [comment]
Good points. I'll add them to the spec.

**Comment by CharliePoole** [comment]
Updated the spec.

**Comment by CharliePoole** [comment]
@nunit/contributors The spec for warnings has been updated and I'm working on the code. I wanted to ask you to please be quite sure that you agree with it all, in particular the point about treating ignored tests more clearly as warnings. Redefining `ResultState.Ignored` as a warning status means it will be counted as a warning and listed with other errors, failures and warnings. They will no longer simply be "not run" in other words.

NUnit has always considered "Ignored" as a "Bad Thing" hence the yellow bar it causes. In my mind, this change simply makes it clearer for users but I'd like to be sure we all agree before anybody gets surprised by it. :-)

**Comment by ChrisMaddock** [comment]
Makes sense for ignored tests. In terms of precedence - I'm assuming that only a test which would otherwise be `Passed` could be `Warning`? And `Failure` and `Inconclusive` would still take priority over `warning`?

**Comment by CharliePoole** [comment]
@ChrisMaddock Yes, we'll need to treat warnings similarly to how we treat failures in a multiple assert block. I'm assuming I'll merge multiple asserts into this before long, which will introduce the need to distinguish between tests that have a failure or error and those that only have warnings. Essentially, this pushes down into the test itself the same logic we currently use for merging test results into a suite result.

WRT suites, they will be get a warning status if the worst result they contain is a warning, just as they now are treated as failing if any of their results is a failure.

**Comment by CharliePoole** [comment]
Blocked by #1912

**Comment by CharliePoole** [comment]
All issues under this Epic are complete.
