### ISSUE TITLE
TestEventListener not being called when running a test from VS test adapter.

### ISSUE THREAD

**Issue by quldude** [nunit/nunit#4063]
With the latest version of testadapter and nunit I'm not seeing my ITestEventListener implementation being initialized when I run a test from visual studio test adapter. I've placed my addins file in `{Solution folder}\packages\NUnit3TestAdapter.4.2.1\build\net35\my.nunit.addins`. In nunit v3.6.1 I did the same with a previous version of testadapter (v3.9) and it worked. If I use the console runner v3.15, then it works fine. Do you know what I'm missing for the test adapter piece?

**Comment by stevenaw** [comment]
@OsirisTerje Should this be transferred to the adapter repo for visibility?
