### ISSUE TITLE
Release of 3.13.3

### ISSUE THREAD

**Issue by manfred-brands** [nunit/nunit#4064]
Hello @rprouse 

When do you think of releasing 3.13.3?
At my work we use a copy of binaries downloaded from the build system for a specific build.
Unfortunately there are no 3.13.x nuget packages on myget.org.

**Comment by rprouse** [comment]
I was just thinking the exact same thing, possibly this weekend? 

Is there anything outstanding that you would like to ensure gets into the release @manfred-brands?

**Comment by stevenaw** [comment]
@rprouse I would appreciate if this could make it in: https://github.com/nunit/nunit/pull/4007

It fixes some tail-chasing from a previous yet-to-be-released bugfix in that area as well as sets up the detection of of a type is sortable for future memoization/caching.

**Comment by manfred-brands** [comment]
Thanks @rprouse There isn't anything not yet in the dev branch we explicitly wait on.

**Comment by rprouse** [comment]
I am going to move the two remaining issues in the 3.13.3 milestone to 3.13.4 and do the release today. #4007 is merged and will be included.

**Comment by stevenaw** [comment]
Thanks @rprouse 🎉

**Comment by rprouse** [comment]
Release is out, just waiting on NuGet verification.
