### ISSUE TITLE
Create generic versions for Attribute operator + constraints

### ISSUE THREAD

**Issue by stevenaw** [nunit/nunit#4067]
`Has.Attribute()` and `ConstraintExpression.Attribute()` have generic and non-generic overloads. Internally the generic overload just calls the non-generic overload. We should reverse this and build out the internal plumbing to allow the following to have generic versions:

1. AttributeOperator
2. AttributeConstraint
3. AttributeEqualsConstraint

NOTE: This is intended to provide generic classes for working with attributes, not classes to work with generic attributes.

**Comment by stevenaw** [comment]
Unassigning myself from this to open it up for others. I'm having a hard time doing it in a way I'm happy with and I suspect I'll have considerably less time to continue with this over the next few weeks.

**Comment by manfred-brands** [comment]
I don't see a need for doing this. No matter how far we take it deeper, eventually we will have to do `typeof(T)`.
The generic version here is pure for readability, not for functionality or to prevent boxing.

**Comment by stevenaw** [comment]
Yep, exactly. I had made this since it was the first constraint alphabetically, but the value isn't really there.
I had hoped that carrying the generic typing down into AttributeHelper, which is only used by the above-listed classes, that something could be gained but alas the type check + conversion to ICustomAttributeProvider there is still required for assembly attributes.

Happy to close this
