### ISSUE TITLE
AssertExcption has mutiple failures message which includes the previous exceptions message, I just want the last one.

### ISSUE THREAD

**Issue by JanetY-as** [nunit/nunit#4080]
As shown in the screenshot.
For the second AssertExcetion, why it has mutiple failures info. I just only want this one"Expected: not <empty> But was:<string.Empty>". 
Similarly, the message of third AssertException will has three failures info, and so on. How to resolve it?
![图片](https://user-images.githubusercontent.com/102147869/159451021-e5292ab3-3b90-4819-8268-2a8a2f735355.png)

**Comment by mikkelbu** [comment]
@JanetY-as you shouldn't catch assertion exceptions. If you really want to do it you can use TestExecutionContext.IsolatedContext in a using block -  see https://github.com/nunit/nunit/issues/2758#issuecomment-385498560 for inspiration and discussion about catching assertion exceptions.

Ps. If you know that the first part always throws, then you can also use Assert.Throws to capture the exception.

**Comment by mikkelbu** [comment]
I'm closing this question as answered. Please note that we will still see additional comments in this issue.
