### ISSUE TITLE
How to get the total number of testcases started in a test execution in Nunit 3.0?

### ISSUE THREAD

**Issue by gnaneswarreddy** [nunit/nunit#4081]
I am using Nunit 3.0 i want to know the total number of test cases i have started in a test exeuction as i am getting the final number of test cases completed and passed in to my customized html report.

**Comment by stevenaw** [comment]
Hi @gnaneswarreddy Sorry, can you explain a bit more about what you're trying to do?
The test result file should contain a `<test-run>` root element with most of the information you should need including `testcasecount` and `total`. Is there additional info you're trying to report on?

For more info on the XML Format:
- Docs: https://docs.nunit.org/articles/nunit/technical-notes/usage/Test-Result-XML-Format.html
- Sample run: https://nunit.org/files/testresult_30.txt

**Comment by stevenaw** [comment]
I'm going to close this due to inactivity. If you're still having troubles and can provide us with more info, please let us know.
