### ISSUE TITLE
nunit v3.13.2 is not displaying the test full name when outputting text in console.

### ISSUE THREAD

**Issue by quldude** [nunit/nunit#4082]
In this version of nunit and nunit console runner (3.15.0), I'm not seeing the test full name being outputted when displaying text to the console when I use ` TestContext.Progress.WriteLine(string);`

Eg: In previous nunit version I saw this:
```
=> <namespace>.<class name>.<test name>
  <custom output text>
```

Now I'm seeing this:
```
  <custom output text>
```

Any idea?

**Comment by stevenaw** [comment]
Hi @quldude 
Thanks for reporting this. What version were you upgrading from? Also, do you see the same on the newly released v3.13.3 version of the framework?

**Comment by quldude** [comment]
I was upgrading from nunit 3.6.1. I upgraded to v3.13.3 and see the same issue.

**Comment by stevenaw** [comment]
Hi @lnsandnkth welcome! I noticed you're interested in contributing a fix for this issue, would you like me to assign it to you? That'll help with coordination in the project and ensure no one else picks it up 🙂

**Comment by stevenaw** [comment]
I've tried reproducing this across a few different versions of the framework including 3.6.1 + 3.11.0, and using both the console runner and dotnet test, and for both net8.0 and net462. I haven't been able to reproduce the originally described output.

@quldude I'm going to close this for now. If you're still hitting this and are able to upload a sample repo which can run "as-is" to [our issue samples repo](https://github.com/nunit/nunit.issues) then we can take another look.
