### ISSUE TITLE
בפרסום מודעה חדשה ניתן לרשום 4 תווים בשדה מספר רישוי ללא הודעת שגיאה

### ISSUE THREAD

**Issue by eladginot** [nunit/nunit#4084]
לחצתי על כפתור פרסום מודעה חדשה ולאחר מכן מילאתי את כל השדות הנדרשים. רשמתי 4 ספרות בשדה מספר רישוי ולא קיבלתי הודעת שגיאה למרות שלוחית רישוי מינימלית מכילה 5 ספרות

**Comment by mikkelbu** [comment]
Hi @eladginot 

I'm closing this issue as we - or at least I - cannot read Hebrew. From the google translate it does not sound this is related to NUnit.

Note that we will still see additional comments on this, and if it is an NUnit problem, then we can reopen the issue.
