### ISSUE TITLE
Command line switches

### ISSUE THREAD

**Issue by circa1741** [nunit/nunit#409]
Background:
In our shop, we have a custom runner with the following switches:

- retry - since there are tests that sometimes fail and sometimes pass, we are able to set the runner to "retry" all failing tests.

- category - instead of using the CategoryAttribute, we have our custom attributes HighAttribute, MediumAttribute and LowAttribute so we can use -c High

- team - we tag our TestFixture/Test with our custom attribute TeamAttribute so we can use -t "SomeTeam"

Requests:
1. It would be nice to be able to request the runner to retry the failed tests and possible indicate the number of retry. For example: `-retry 3`
2. It would be nice to have a switch to allow selecting tests via attribute.
For example, given the custom attributes above:
-attribute Medium,Low (or any other custom attribute)
-attribute Team("SomeTeam") - (am not sure if switches can be used this way)

Also, I have read somewhere that there might be a built-in IssueAttribute. It would be nice to be able to run a particular Issue:
For example:
-attribute Issue("Jira 888")

**Comment by CharliePoole** [comment]
Since this request is actually covered by issue #374 I'm closing it.
