### ISSUE TITLE
nunit v3.13.3: custom test attribute is not taken into account

### ISSUE THREAD

**Issue by DimoYa** [nunit/nunit#4091]
used version:

nunit v3.13.3
.NET 6

I have the following custom attribute

```csharp
    [AttributeUsage(AttributeTargets.Method)]
    public class SkipIfOtherFailsAttribute : Attribute
    {
        public SkipIfOtherFailsAttribute(string dependentTestNames)
        {
            this.DependentTestNames =
                new HashSet<string>(dependentTestNames.Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries));
            this.CheckForDependency();
        }

        public ICollection<string> DependentTestNames { get; }

        private void CheckForDependency()
        {
            foreach (var dependentTestName in this.DependentTestNames)
            {
                var checkMainTestStatus = Helpers.GetTestContex()
                    .Where(x => x.Test.Name == dependentTestName)
                    .Select(x => x.Result.Outcome.Status)
                    .FirstOrDefault()
                    .ToString();

                if (TestContext.CurrentContext.Result.Outcome.Status.ToString() != TestCaseStatus.Skipped.ToString() &&
                checkMainTestStatus == TestCaseStatus.Failed.ToString())
                {
                    Assert.Ignore();
                }
            }
        }
    }
 ```

The usage is like this:

```csharp
        [Test]
        public void ThisTest_ShouldFail()
        {
            Assert.Fail();
        }
-------------------------------------------------------------------------

        [Test]
        [SkipIfOtherFails("ThisTest_ShouldFail")]
        public void ThisTest_ShoulBeSkipIfOtherFails()
        {
            Assert.Pass();
        }
```

With the previous v3.13.2, the second test is marked with "Skipped" if the first failed, with v3.13.2 I am not able to enter the custom attribute at all, and the status is "Passed"

Thanks in advanced

**Comment by DimoYa** [comment]
i haven't described the whole logic. The first test has [Order(1)]. Each test case is also added in a HashSet<TestContext> so i can check in the custom attribute if the test tagged as dependent. It is tested with several tests and was working for some time. Please check the changes you have made

**Comment by manfred-brands** [comment]
Trying this out, with 3.13.2 the attribute constructor is called twice, with 3.13.3 once. 
But this is more likely an optimization.
Checking the change, it was part of #4034 where method information is cached.

I don't think your logic ever was meant to work.
You could put your logic in a method attributed with [SetUp]
It allows you access to TestContext.CurrentContext.Test.MethodName which you yourself can check etc.
