### ISSUE TITLE
check for zeroes in assert messages

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#41]
It happened to us that somehow there was a zero in an assertion message. This zero within the message, even embedded into a cdata-section within the resultfile caused a crash to all applications that tried to create a DOM, .NET XmlDocument class and eben XmlSpy application crashed. Of course a zero is not allowed in a xml file but this zero came from the assertion message and so went into the NUnit resultfile. NUnit should check if messages are really valid strings and if there is a disallowed zero, escape it or convert it to its string representation.

From https://bugs.launchpad.net/nunit-3.0/+bug/1223271

**Comment by rprouse** [comment]
PR #127 might have fixed this. We should make sure there is a unit test and close if it is fixed.

**Comment by rprouse** [comment]
PR #127 does fix this, closing.
