### ISSUE TITLE
Custom Runner

### ISSUE THREAD

**Issue by circa1741** [nunit/nunit#410]
It would be nice to provide a sample starter boilerplate project that demonstrates how to create a custom runner using NUnit 3.

**Comment by rprouse** [comment]
I am moving this issue out to 3.0 extras milestone so that it isn't blocking the release. There is no reason this can't be done out of band.

**Comment by ChrisMaddock** [comment]
I think this is now pretty covered by @CharliePoole's new docs below:

https://github.com/nunit/docs/wiki/NUnit-Internals

**Comment by CharliePoole** [comment]
Not that new. 😄
