### ISSUE TITLE
Expose ExpectedResult to the TestContext

### ISSUE THREAD

**Issue by garyhuntddn** [nunit/nunit#4101]
We have a scenario where we have extensive test cases which use the ```ExpectedResult``` argument of the ```TestCase``` attribute.

Within those test we have a new need to be able to assess the ```ExpectedResult```.

Rather than convert the tests so that the ```ExpectedResult``` is passed in as an argument and an assert performed we would like to be able to examine the ```ExpectedResult``` in the same we can see the ```MethodName``` and the ```Arguments```.

We've been able to hack together a solution using reflection against the _test field and the internal ```ExpectedResult``` property of the ```TestMethod``` class but it would be nicer if we didn't have to do this.

See https://github.com/nunit/nunit/pull/4100 for a simple PR that exposes this property.

**Comment by manfred-brands** [comment]
Can you explain your scenario a bit more?
Knowing the ExpectedResult in a test either is cheating or doing Nunit's job to compare the actual result with the expected.

**Comment by stevenaw** [comment]
This was closed via #4100
