### ISSUE TITLE
PropertyAttribute should work when applied to a parameterized test method

### ISSUE THREAD

**Issue by MJB222398** [nunit/nunit#4105]
I use a attribute that derives from PropertyAttribute to decorate most of my non-parameterized test methods. For the tests that are parameterized I am having to use TestCaseData.SetProperty  (as properties applied on the test method itself aren't recognized). When using this call I can only specify the key value pair, it would be nice to be able to specify an instance of the derived property that I use for my other tests.

**Comment by stevenaw** [comment]
@MJB222398 

Can you give a code example of how you would use this? While I haven't tested this myself, I suspect NUnit's internal instantiation and handling of these attribute may limit how widely this could be used.
In the absence of this having been added to the framework, would an extension method helper in your project also serve the same purpose for you to avoid duplicate code on your side?

**Comment by stevenaw** [comment]
> as properties applied on the test method itself aren't recognized

This may be something we'd want to fix. It may also be more intuitive than adding an API which expects an instance of an attribute to be passed in. 

I'm adding the `confirm` label here so that I can verify the current behavior first

**Comment by stevenaw** [comment]
Oh. It appears we already have that represented by #1194
I'm that case I'm going to close this issue based on that I think it could be a more intuitive fix here.

**Comment by OsirisTerje** [comment]
@stevenaw #1194 have not been touched in 6 years or so.  Do you think it ever will?

**Comment by stevenaw** [comment]
I agree with closing that one. I want to do a bit more research into historical issues first, however.

I found a few comments from Charlie across various issues around 2018 that indicate that the described behavior there is actually by-design... at least as far as the original design went. I thought summarizing that could be helpful additional context to include when closing it.

**Comment by stevenaw** [comment]
Looking closer, it seems that #1194 evolved to cover a very specific case dealing with `ExpectedResult`.

#3067 on the other hand seems to describe the behavior also described in this issue. Charlie has gone on to leave a detailed comment there suggesting that the current behavior is by-design.
