### ISSUE TITLE
[Bug] Test host process crashed on the code that works well in console project

### ISSUE THREAD

**Issue by AsakusaRinne** [nunit/nunit#4108]
### Environment
Ubuntu 20.04LTS
64bit
dotnet 6.0.201

### Description

I wrote the following code with nunit but it cannot run successfully. 

```
using NUnit.Framework;

namespace TensorOpTest;

public class EyeTest
{
    [SetUp]
    public void Setup()
    {
    }

    [Test]
    public void Test1()
    {
        var t = Tensor.FromArray<int>(
            new int[] { 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 }, new TensorShape(4, 5));
        var p = Tensor.Eye<int>(4, 5, 2);  // Here!
        Assert.IsTrue(TensorUtils.IsValueEqual(t, p));
    }
}
```

The code above could run successfully in dotnet console project. However, when I ran it in nunit, it shown the error message below.

```
The active test run was aborted. Reason: Test host process crashed

Test Run Aborted with error System.Exception: One or more errors occurred.
 ---> System.Exception: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action`1 errorHandler, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---.
```

After some try, I located the problem in the line that I comments in the code. Since the code was from a framework I wrote myself and has interop with c++, it may takes sometimes for me to abstract it. I will update the info if it is necessary for solving this BUG.

I will appreciate it if you are willing to help me!

**Comment by manfred-brands** [comment]
If you add `System.Diagnostics.Debugger.Launch()` just before the failing line, then run the test, does the debugger show any exception thrown?
It looks like an exception is not caught or cannot be caught which then brings the test process down.

**Comment by mikkelbu** [comment]
@AsakusaRinne It sounds like it is similar to microsoft/vstest#2952. Can you test if you get the same problem running the test in XUnit? I'm quite sure that the problem resides outside of NUnit as I cannot see it in the stacktrace

**Comment by KundM** [comment]
Same issue here with xUnit on Unix using `dotnet test`. On windows it is working Also tried Microsoft.NET.Test.Sdk version 17.2.0-preview-20220401-08 and xunit version 2.4.2-pre.12 but getting the same error.

**Comment by stevenaw** [comment]
Thanks for confirming that @KundM . 
I'm going to close this as the bug is not within nunit itself. Please note that we will continue to see additional comments.
