### ISSUE TITLE
`Is.Empty` constraint on complex collections might hide bugs

### ISSUE THREAD

**Issue by Crown0815** [nunit/nunit#4111]
With the recent update to NUnit 3.13.3, one of our unit tests started failing. The test failed because of a "mistake" in one of our collections. We build a *soft deleting* collection with a restore functionality. You can imagine the collection looking like this:

```csharp
public class SoftDeletingCollection<T> : IEnumerable<T>
{
    private readonly List<Deletable<T>> _inner = new();

    public void Add(T item)
    {
        _inner.Add(new Deletable<T>(item, false));
    }

    // Remove only soft deletes items so that they can be restored later
    public void Remove(T item)
    {
        var deletable = _inner.Single(x => x.Represents(item));
        deletable.IsDeleted = true;
    }

    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
    public IEnumerator<T> GetEnumerator() => new SoftDeletingEnumerator<T>(_inner.GetEnumerator());
}
```
(the real remove logic is more complex, but the shown one is sufficient for my point)

The `Deletable<T>` class is simply a container holding the value and `IsDeleted` flag:

```csharp
private class Deletable<T>
{
    public Deletable(T Value, bool IsDeleted)
    {
        this.Value = Value;
        this.IsDeleted = IsDeleted;
    }

    public T Value { get; }
    public bool IsDeleted { get; set; }

    public bool Represents(T value) => EqualityComparer<T>.Default.Equals(Value, value);
}
```

The `SoftDeletingEnumerator<T>` is crucial since it is responsible for hiding deleted members during enumeration:

```csharp
private class SoftDeletingEnumerator<T> : IEnumerator<T>
{
    private readonly IEnumerator<Deletable<T>> _inner;
    public SoftDeletingEnumerator(IEnumerator<Deletable<T>> inner) => _inner = inner;

    public bool MoveNext()
    {
        // This while loop skips deleted items during enumeration
        while (_inner.MoveNext())
            if (!_inner.Current.IsDeleted) return true;
        return false;
    }

    public T Current => _inner.Current.Value;
    object IEnumerator.Current => Current;
    public void Reset() => _inner.Reset();
    public void Dispose() { }
}
```

Now I test that the `SoftDeletingCollection<T>` `Is.Empty` after I remove the last item:

```
[Test]
public void Test_without_count_property()
{
    var instance = new SoftDeletingCollection<int> { 1 };
    instance.Remove(1);
    Assert.That(instance, Is.Empty);    // Passes
}
```

However, if we now introduce a `Count` property to the collection (e.g., to implement `IReadOnlyCollection<T>` instead of `IEnumerable<T>`)  and make a small mistake such as forgetting to deduce *deleted* items

```csharp
public class SoftDeletingCollection<T> : IEnumerable<T>
{
    ...
    public int Count => _inner.Count; // this ingores the soft deletion
    ...
}
```

the test fails with the message

```
Expected: <empty>
  But was:  <empty>
```

which is **very confusing**.

In our particular case, we had a collection such as `SoftDeletingCollection` and the test was passing until NUnit `3.13.3`, so to figure out what was the problem was quite a journey.

But the worst part about this is that we could make the test pass and still have a bug in our collection by **fixing** the `Count` implementation (i.e., `... Count => _inner.Where(x => !x.IsDeleted).Count();`) but breaking the `SoftDeletingEnumerator`

```csharp
private class SoftDeletingEnumerator<T> : IEnumerator<T>
{
    ...
    public bool MoveNext()
    {
        return _inner.MoveNext();    // this will enumerate deleted items as well
    }
    ...
}
```

---

I think that `Is.Empty` should rather check the enumeration than the `Count` property. To evaluate the `Count` the `Has.Count` expression is far more explicit. In the case described above, the new behavior of `Is.Empty` will lead to false positive test results and bugs in production code.

It might be valuable to *include* a check of the `Count` in the `Is.Empty` constraint, but I am not convinced that `Count` should be the deciding property for emptiness.

**Comment by manfred-brands** [comment]
Thanks for the detailed report.
NUnit checks the `Count` property in preference to enumeration as it is more efficient. But even though it is assumed that `Count` and enumeration are in sync for a class that implements `ICollection` it is NUnit job to allow you to test this. If `Has.Count.EqualTo(0)` and `Is.Empty` test the same thing you cannot. 
There is a similar discussion that `Is.EqualTo(null)` doesn't actually call the class' `Equals` method at all.

If you want to test your implementation you must call your methods directly and don't assume what NUnit calls.
What NUnit does is what a consumer of your class also assumes. If the class behaves the two `Count` and enumeration are in-sync.

**Comment by stevenaw** [comment]
I agree with @manfred-brands here, it's unusual to have a `Count` on an `Enumerable` which represents something which can't be enumerated. Some places in .NET itself - like Linq's `Any()` method - also use this optimization via the `ICollection` interface in order to check for empty/non-empty efficiently. In your code example, I think your going down a codepath where we check for non-`ICollection` types which still define a `Count` prop in order to support .NET 6's  `PriorityQueue`.

Is there a property on your class which represents the number of non-deleted items which you could assert against directly instead?

**Comment by Crown0815** [comment]
@manfred-brands I agree that it makes sense to check `Count` on classes implementing `ICollection`, since this interface implies a contract between the enumeration and the `Count`. Especially with the behavior of LINQ's `Any()`, it makes perfect sense.

Where I disagree is that the existence of a `Count` property itself, without any associated interface, is a reasonable argument to forego the enumeration. This is also where LINQ's `Any()` (`.NET5` and `.NET6`) behaves differently.

For the scenario where `ICollection` is not implemented, `Count` returns `0`, and the enumeration returns elements, the following test fails

```csharp
[Test]
public void Test_without_count_property()
{
    var instance = new SoftDeletingCollection<int> { 1 };
    instance.Remove(1);
    Assert.That(instance, Has.Count.EqualTo(0));          // Passes
    Assert.That(instance, Is.Empty);                      // Passes
    Assert.That(instance.Any(), Is.False);                // Fails
}
```

Intuitively, I would expect LINQ`s `Any()` to return the same result as `Is.Not.Empty` when applied to an `IEnumerable`.

@stevenaw, according to the documentation, `PriorityQueue` does not implement `IEnumerable`, so a one could still handle it by swapping the checks for `IEnumerable` and `HasCountProperty` in the `EmptyContraint`. Currently, the code looks like this

```csharp
...
else if (CountZeroConstraint.HasCountProperty(actualType))  // For Collections that have Count but are not ICollection
    realConstraint = new CountZeroConstraint();
else if (actual is System.Collections.IEnumerable)          // Enumerates whole collection
    realConstraint = new EmptyCollectionConstraint();
...
```

**Comment by Crown0815** [comment]
@stevenaw 
> As suggested, is there a property on your class which represents the number of non-deleted items which you could assert against directly instead?

We are not interested in the *non-deleted* items. We are just interested in the correctness of our collection, meaning, we want that if we delete the only (or last) item from the `SoftDeletingCollection` the collection is *empty*. By *empty*, we mean that enumerating it will yield no items.

**Comment by manfred-brands** [comment]
@Crown0815 Yes, swapping those two conditions is a possibility, especially as we already have a case testing on `ICollection` before that so the number of times we would enumerate would only if a class has both a `Count` property and an enumerable, but is not an `ICollection`. However, I would augment the test to include `IReadOnlyCollection` to catch Immutable collections.

It would still mean however that if you implement `ICollection` then `Is.Empty` would still not iterate over your enumeration, just like `Any()` will not. So to find the bug where these behave wrongly you still would to iterate explicitly in your test. I would even go so far as to not rely on Linq `ToArray` in case that will be optimized in the future to return `Array.Empty()` when the class implements `ICollection` and has a `Count` of `0`.

**Comment by stevenaw** [comment]
I'd be ok with swapping those checks as it would defer the potentially slower reflection check until after the enumeration check, though I'd like to hear more thoughts from the team, especially on if this is something to backport to the 3.13 branch. I wouldn't consider the existing implementation in nunit a "bug" per se.

@Crown0815 if you're only interested in checking the enumeration, one option could be to assert against the enumerator itself
```
[Test]
public void Test_without_count_property()
{
    var instance = new SoftDeletingCollection<int> { 1 };
    instance.Remove(1);

    Assert.That(instance.GetEnumerator().MoveNext(), Is.False);
}
```

**Comment by stevenaw** [comment]
I've been thinking about this a bit and I can't think of how the proposed change to swap those lines could break an existing consumer. I'd be ok with adding it to 3.13 if others were

**Comment by Crown0815** [comment]
@stevenaw Yes, I could assert against the enumerator, but this would leave me with an `expected false but was true` message in case of failure. Not the end of the world, but a little unsatisfying.

The main reason, why I could see this being a "bug", is the output produced by the assertion: 

```
Expected: <empty>
  But was:  <empty>
```

This is some odd output, that felt like a bug to me when I encountered it. At the very least, the output should say:

```
Expected: <empty>
  But was:  Count > 0
```

**Comment by Crown0815** [comment]
I just submitted a pull request to resolve the issue.

In the context of my changes, I went through the `EmptyConstraintTest.cs` file and came across these lines:

```csharp
...
[TestCase(null)]
[TestCase(5)]
public void InvalidDataThrowsArgumentException(object data)
{
    Assert.Throws<ArgumentException>(() => TheConstraint.ApplyTo(data));
}

public void InvalidDataThrowsArgumentException()
{
    Assert.Throws<ArgumentException>(() => TheConstraint.ApplyTo(default(SingleElementCollection<int>)));
    Assert.Throws<ArgumentException>(() => TheConstraint.ApplyTo(new NotReallyACollection()));
}

[Test]
public void NullStringGivesFailureResult()
{
    string actual = null;
...
``` 

Does anyone know why `InvalidDataThrowsArgumentException` is not marked as test? Running this method as a test actually fails on the first `Assert...`. I am not certain why, but suspect it is the presence of a `Count` on the type.

**Comment by stevenaw** [comment]
Thanks for noticing that @Crown0815 !

I'm also not sure. It looks like it was added when we added support for `PriorityQueue` which like both `SingleElementCollection<T>` and `NotReallyACollection` define a `Count` on a non-`IEnumerable`. My guess is that it was added early on during that fix to establish a baseline before making the change and got missed during cleanup or later refactoring. The missing `[Test]` certainly got missed when I was involved in the review :)

It looks like both `SingleElementCollection<T>` and `NotReallyACollection` are also represented in the `SuccessData` and `FailureData` test cases as well in the final version of the PR so it's possible that the `InvalidDataThrowsArgumentException` method could now just be removed.

**Comment by manfred-brands** [comment]
Looks like time to references the [NUnit.Analyzers](https://github.com/nunit/nunit.analyzers) so we do what we tell others to do. Rule [NUnit1028](https://github.com/nunit/nunit.analyzers/blob/master/documentation/NUnit1028.md) would have told me that I had forgotten the `[Test]`.
