### ISSUE TITLE
Missing output with failed test stack traces for Assert.Multiple

### ISSUE THREAD

**Issue by gps7** [nunit/nunit#4129]
Hi,
I am missing test output with stack traces for failed tests. For running example test fails but output not showing any information about failures nor even mention that test has failed:

```
[Test]
public void AssertMultiple()
{
	Assert.Multiple(() =>
	{
		ValidateInteger();
		Assert.That("a", Is.EqualTo("b"), "String");
		ValidateInteger();
	});
}

private void ValidateInteger() => Assert.That(1, Is.EqualTo(2), "Integer");
```
Running Nunit console with fallowing command line provides empty TEST_OUTPUT.log file:
"nunit3-console.exe" MyTests.dll --test=MyTests.TestClass.AssertMultiple --out=TEST_OUTPUT.log

I've tried to run v3.15.0. I assume this also affects the Test Centric since it shows failing test but output is always empty. I've expect to see not only failures but also 3 stack traces for 3 failures.

I am using Framework 4.8.

**Comment by stevenaw** [comment]
Hi @gps7 

I suspect this may be done for compatibility with some runners which only output a single message 
https://docs.nunit.org/articles/nunit/writing-tests/assertions/multiple-asserts.html#compatibility

> Older runners generally display a single failure message and stack trace for each test. For compatibility purposes, the framework creates a single message that lists all the failures. The stack trace in such a case will indicate the end of the assert multiple block.

Just to confirm, do you see no stack trace at all, or just a single line in the stack trace, like this from within Visual Studio using the `NUnitTestAdapter@4.0.0`

![image](https://user-images.githubusercontent.com/439844/175824288-7387a863-06bd-41c9-966f-d418b51f49f8.png)

**Comment by gps7** [comment]
Hi @stevenaw ,
Running TestCentric version 2.0.0-alpha4 I get exactly this output with single stack trace to the test (as your shown output):
![TC_AssertMultiple_Errors](https://user-images.githubusercontent.com/21167960/176107084-f1899f00-4591-469d-9b53-c12273a8bbf2.PNG)

The output of TC is totally empty:
![TC_AssertMultiple_Output](https://user-images.githubusercontent.com/21167960/176107118-6260ef35-df9b-4121-8205-a9d223b900ca.PNG)

However, running same tests with Resharper extension in VS2022 all information is shown as expected:
![TC_AssertMultiple_Resharper_Output](https://user-images.githubusercontent.com/21167960/176107483-14965315-556e-4132-9b27-bd9140956716.PNG)

I am not sure if ReSharper has own Nunit adapter or how else it manages to get all stack trace information. Our test solutions are using Nunit3TestAdapter NuGet package v4.2.1 and output is same on build servers: no stack traces or any information at all in output files but only failing information in the pipeline test information with single stack trace to the test itself.

@mikkelbu, we don't use XML output since we produce a lot of log additional information by using mainly log4net appenders (occasionally we use also Console.Write) due long running complex tests and our output files can exceed 200Mb file size for just 800 tests.

**Comment by gps7** [comment]
@mikkelbu How to determine then faulty side Engine/Console or adapter so I can rise new issue? Does the console using adapter when executing from command line?

**Comment by OsirisTerje** [comment]
The NUnit Console is not using the adapter,  The Adapter however uses the NUnit.Engine, and the NUnit Console is also using the NUNit.Engine

**Comment by gps7** [comment]
Issue moved to Nunit-console support.
