### ISSUE TITLE
TestContext.CurrentContext.Result.Assertions just gives failed assertions.

### ISSUE THREAD

**Issue by kaanakdeniz** [nunit/nunit#4146]
I use ExtentReports in my tests and i want to show all assertions with their explanations like
```
   var assertions = TestContext.CurrentContext.Result.Assertions;
            foreach (var assertion in assertions)
            {
                var message = assertion.Message;
                test.Log(ReportUtils.AssertionStatusMap[assertion.Status], $"<b>{assertion.Status}</b>: {message}");
            }
```

But TestContext.CurrentContext.Result.Assertions just gives failed assertions, doesn't give success assertions, i want to see all assertions.

My test code like
```
    [Test]
        public void Play()
        {
            Assert.Multiple(() =>
            {
                Assert.AreEqual(5, 5, "Equal");
                Assert.AreEqual(5, 4, "Not Equal");
                Assert.Null(5, "Null");
            });
        }
```

In TestContext->Assertions gives last two of them but assertioncount is 3.

**Comment by OsirisTerje** [comment]
It is only when a  test fails that a lot of information is added to the result tree.  If that should happen also for success tests, which normally would be in large majority, the output result tree would become very large and thus also be much slower.

With NUnit 4, you will see the exact Assert statement in the test results, but again, only for failed tests. 
See https://docs.nunit.org/articles/nunit/Towards-NUnit4.html#improved-assert-result-messages
