### ISSUE TITLE
Running tests in AWS Lambda causes "Access to the path "/home/sbx_user1051" is denied" Error

### ISSUE THREAD

**Issue by Daedra22** [nunit/nunit#4147]
Hi guys,
I was trying to run my compiled tests in an ubuntu image using aws lambda via the command:
`mono nunit-console.exe -nologo -noresult test.dll`

Unfortunatelly the following error is thrown:
> Access to the path "/home/sbx_user1051" is denied

In aws lambda I have only write access to the /tmp/ folder and nested folders in it.

Is it possible to run the nunit tests via nunit-console.exe  without the need to access "/home/sbx_user1051" or could the path for this user be moved to tmp?

Thanks and kind regards.

**Comment by mikkelbu** [comment]
Can you provide some more context? Is there a stacktrace or similar, so we can determine what is trying to access "/home/sbx_user1051".

Does it help if you try the `--work=PATH` option to set folder for output files. And what about `--out=PATH` for the text output

**Comment by stevenaw** [comment]
I'm going to close this due to inactivity, but @Daedra22 please let us know if mikkelbu's answer didn't help, and any additional context you could provide which could further help us
