### ISSUE TITLE
Distribute optimized framework builds with easy debugging

### ISSUE THREAD

**Issue by stevenaw** [nunit/nunit#4149]
As noted in https://github.com/nunit/nunit/pull/4035#issuecomment-1200160651
In https://github.com/nunit/nunit/pull/3464 we stopped using sourcelink in favour of distributing a debug build of the framework with embedded symbols + source, however it seems this can make some operations noticeably slower in larger suites. I'm wondering what thoughts or options there are to distribute an optimized build while still allow a good debugging experience.

@nunit/framework-team @nunit/core-team Thoughts?

**Comment by jnm2** [comment]
I'm happy to go back as soon as there is evidence we can share to back this up. When @sharwell switched us to publishing debug builds, we simply didn't have that evidence yet.

**Comment by stevenaw** [comment]
@lahma are you able to share any of the numbers you saw in #4035 ?

**Comment by lahma** [comment]
@stevenaw I'll put this on my TODO list, need to dig up my test suites for benchmarking test discovery etc...

**Comment by lahma** [comment]
OK here are the results. Note I can offer a PR if you want basic benchmark project setup. This relies on having esprima-dotnet's large test suite built and ready as DLL. This is the runner code I extracted by debugging what Rider IDE was doing and sending.

The only change in running the tests is that I flip the value of `nunit.framework.csproj` attribute `<Optimize>false</Optimize>` value between true and false.

Testing done in `v13.3-dev` branch, under NET 6 runtime.

## Benchmark

* __CountTestsEmptyFilter__: 60737 matches
* __CountTestsWithCategoryFilter__: 2307 matches
* __CountTestsWithOrFilterAll__: 60737 matches (the IDE scenario where IDE runner sends all ids which was optimized with OrFilter)
* __LoadTests__: 341 results

```csharp
using System.Collections;
using BenchmarkDotNet.Attributes;
using NUnit.Framework.Api;
using NUnit.Framework.Interfaces;
using NUnit.Framework.Internal;
using NUnit.Framework.Internal.Filters;

namespace NUnit.Framework;

[InProcess] // need to use so that we get correct test loading
[MemoryDiagnoser]
public class FrameworkControllerBenchmark
{
    private FrameworkController _controller;
    private List<string> _testIds;
    private string _orFilter;

    [GlobalSetup]
    public void GlobalSetup()
    {
        const string workDirectory = "C:\\Work\\jint\\Jint.Tests.Test262\\bin\\Release\\net6.0";
        var settings = new Hashtable
        {
            { "ProcessModel", "InProcess" },
            { "DomainUsage", "None" },
            { "ShadowCopyFiles", false },
            { "TestParametersDictionary", "" },
            { "NumberOfTestWorkers", 0 },
            { "SynchronousEvents", "false" },
            { "RandomSeed", 878248866 },
            { "LOAD", new List<string> { "Jint.Tests.Test262.BuiltInsTests", "Jint.Tests.Test262.LanguageTests", "Jint.Tests.Test262.AnnexBTests", "Jint.Tests.Test262.Intl402Tests", "Boostrap" } },
            //{ "LOAD", new List<string>() { "NUnit.Framework" } },
            { "WorkDirectory", workDirectory },
        };
        _controller = new FrameworkController($"{workDirectory}\\Jint.Tests.Test262.dll", "0-", settings);
        _controller.LoadTests();

        _testIds = new List<string>();
        var exploreTests = _controller.Runner.ExploreTests(TestFilter.Empty);
        GatherTestIds(exploreTests.Tests, _testIds);

        _orFilter = "<filter>" + new OrFilter(_testIds.Select(x => (TestFilter) new IdFilter(x)).ToArray()).ToXml(true).OuterXml + "</filter>";
    }

    [Benchmark]
    public int CountTestsEmptyFilter()
    {
        var count = _controller.CountTests("<filter/>");
        return count;
    }

    [Benchmark]
    public int CountTestsWithCategoryFilter()
    {
        var count = _controller.CountTests("<filter><cat>BigInt</cat></filter>");
        return count;
    }

    [Benchmark]
    public int CountTestsWithOrFilterAll()
    {
        var count = _controller.CountTests(_orFilter);
        return count;
    }

    [Benchmark]
    public string LoadTests()
    {
        return _controller.LoadTests();
    }

    private static void GatherTestIds(IList<ITest> tests, List<string> collector)
    {
        foreach (var child in tests)
        {
            collector.Add(child.Id);
            GatherTestIds(child.Tests, collector);
        }
    }

}
```

## Results

``` ini
BenchmarkDotNet=v0.13.1, OS=Windows 10.0.22621
AMD Ryzen 9 5950X, 1 CPU, 32 logical and 16 physical cores
.NET SDK=6.0.106
  [Host] : .NET 6.0.7 (6.0.722.32202), X64 RyuJIT

Job=InProcess  Toolchain=InProcessEmitToolchain  
```

### Optimize: false

|                       Method |       Mean |     Error |    StdDev |      Gen 0 |     Gen 1 |  Allocated |
|----------------------------- |-----------:|----------:|----------:|-----------:|----------:|-----------:|
|        CountTestsEmptyFilter |   1.508 ms | 0.0037 ms | 0.0035 ms |     1.9531 |         - |      45 KB |
| CountTestsWithCategoryFilter |  35.117 ms | 0.6331 ms | 0.6218 ms |   928.5714 |         - |  16,084 KB |
|    CountTestsWithOrFilterAll |  64.162 ms | 0.2979 ms | 0.2786 ms |  1625.0000 |  750.0000 |  34,145 KB |
|                    LoadTests | 368.248 ms | 3.4929 ms | 3.2672 ms | 12000.0000 | 5000.0000 | 200,290 KB |

### Optimize: true

|                       Method |         Mean |       Error |      StdDev |      Gen 0 |     Gen 1 |    Gen 2 |  Allocated |
|----------------------------- |-------------:|------------:|------------:|-----------:|----------:|---------:|-----------:|
|        CountTestsEmptyFilter |     926.4 μs (-40%) |     4.28 μs |     3.79 μs |     1.9531 |         - |        - |      45 KB |
| CountTestsWithCategoryFilter |  24,758.2 us (-30%) |   188.70 us |   176.51 us |   968.7500 |         - |        - |  16,084 KB |
|    CountTestsWithOrFilterAll |  66,369.0 μs (+3%) |   561.85 μs |   525.56 μs |  1777.7778 | 1000.0000 | 111.1111 |  34,145 KB |
|                    LoadTests | 320,899.6 μs (-13%) | 4,175.30 μs | 3,905.57 μs | 12500.0000 | 5500.0000 | 500.0000 | 198,883 KB |

**Comment by stevenaw** [comment]
Thanks very much for the numbers @lahma !
I think there's still some discussion to be had about if we actually go ahead with optimizing the release build, but I at least think they show there can be a measurable difference for many scenarios.

You are very welcome to put up a PR for benchmarking too if you like, however before you go too far I am curious to see if other @nunit/framework-team members would find it useful. Even if not merged it could still, of course, be used to help others run further benchmarks for this issue.

**Comment by lahma** [comment]
One thing I'd like to highlight is all this performance reflects to UI responsiveness as IDEs heavily rely on the discovery and filtering. In UI interaction milliseconds matter as IDE feels unresponsive when there's "think-time".

**Comment by rprouse** [comment]
I think there is merit in looking into optimizing the release builds. Thanks for the numbers. I also looked at the benchmark PR, very interesting. I think it has merit.

**Comment by Daniel-Svensson** [comment]
As a nunit consumer, the current approach with debug builds does not give a good experience.

The approach does not work with "just my code" 
- when trying to debug our own code there are lots of nunit call stacks.
- stepping through code enters nunit code 
- the debugger breaks inside nunit code when exceptions are thrown 

It would provide a much better experience if nunit was distributed in release mode (with sourcelink) so that I can opt into debugging nunit code when i want.

Is there any chance you have had the time to discuss this and can switch back to release huilds?

**Comment by stevenaw** [comment]
It sounds like there could be a general consensus that this is a good idea. @nunit/framework-team @nunit/core-team  is anyone opposed to us moving forward with this?

**Comment by stevenaw** [comment]
It sounds like there's been generally positive feedback about this idea so I'm going to upgrade it to an enhancement.
