### ISSUE TITLE
When value for attribute date is TIMEOUT OR BROKEN other attributes are empty

### ISSUE THREAD

**Issue by yetibrain** [nunit/nunit#4155]
We have a test result file that has a failure message : 'Test suite did not execute correctly.'
The date attribute has the value 'TIMEOUT OR BROKEN' so obviously something went wrong with one or more tests.

However we would like to know on what machine this occurred, but sadly the machine-name attribute contains no value.
As long as nunit is running and can create an output result file, shouldn't the machine-name, nunit-version, os-version etc. be known?
Can't NUnit set the values for these attributes, even when the date value is unknown and so set to 'TIMEOUT OR BROKEN'?

Here's what we've got:

`<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-results name="Test assembly might be missing, test might be broken or killed by timeout supervision. Please inspect logfiles." total="1" errors="0" failures="0" not-run="1" inconclusive="0" ignored="0" skipped="0" invalid="0" date="TIMEOUT OR BROKEN" time="0.0" >
    <environment nunit-version="No Run" clr-version="No Run" os-version="No Run" platform="No Run" cwd="" machine-name="" user="" user-domain="" />
    <test-suite type="Assembly" name="" executed="True" result="Failure" success="False" time="0.001" asserts="0">
        <results>
            <test-case type="Namespace" name="Hints on test failure:" executed="True" result="Failure" success="False" time="0.0" asserts="0">
                <failure>
                    <message>Test suite did not execute correctly.</message>
                </failure>
            </test-case>
        </results>
    </test-suite>
</test-results>`

![TestResult_TIMEOUT_OR_BROKEN](https://user-images.githubusercontent.com/6065728/183965563-1e2e4565-b394-4d53-b689-95d42f091500.png)

**Comment by yetibrain** [comment]
> @yetibrain How are you running the tests and which version of NUnit are you using?
> 
> I've never seen "TIMEOUT OR BROKEN" before and cannot find it in the codebase (the same is the case for "Test assembly might be missing" and many of the other strings mentioned in the XML).

@mikkelbu Thanks for your reply. I will ask my developers regarding your questions.

**Comment by stevenaw** [comment]
I haven't been able to find the phrase "TIMEOUT OR BROKEN" anywhere on Github in a way that could be relevant here either.
I'm going to close this issue due to inactivity. 
@yetibrain Please feel free to add more context if you have it and are still facing this issue and we can look into it.
