### ISSUE TITLE
SetupFixture should have an `AttributeUsage` of `Inherited = false`

### ISSUE THREAD

**Issue by stevenaw** [nunit/nunit#4158]
Based on the conversation in https://github.com/nunit/nunit/issues/3937, `SetupFixture` isn't intended to be used in a base class, however there is nothing stopping it from being added to a base class or even an abstract base class. One source of confusion here could be that the attribute is explicitly marked with `Inherited = true` prop in the `AttributeUsage`. It might help avoid confusion to make this explicitly false.

**Comment by x789** [comment]
I can take care of it.

Shall I also make this change in the v3 branch?
Normally, I would say that setting `Inherited` to `false` is a breaking change. But if I understood the discussion in #3937 correctly, the attribute does not work with derived classes, therefore it should be okay in this context.

**Comment by stevenaw** [comment]
Thanks once again for tackling this!
