### ISSUE TITLE
NUnit ConsoleRunner 3.15.2 hangs

### ISSUE THREAD

**Issue by alisari41** [nunit/nunit#4159]
![image](https://user-images.githubusercontent.com/81421228/185875803-c883ea70-2578-4e38-a21b-6094ed404462.png)
Project hangs after completing tests between test classes. It doesn't turn off. Can you talk about the reasons that may cause the error? I ask for your help, I wish you good work. (Proje test sınıfları arasında testleri tamamladıktan sonra asılı kalıyor. Kapanmıyor. Hataya neden olabilecek sebeplerden bahsedebilir misiniz. Yardımınızı rica ederim, iyi çalışmalar dilerim.)

**Comment by alisari41** [comment]
Problem solved. I overlooked using driver.Quit() instead of driver.close() in the code.

**Comment by alisari41** [comment]
a

**Comment by stevenaw** [comment]
Thanks for following up @alisari41 , glad to hear it's working for you. 🙂
