### ISSUE TITLE
Tests under a given `Category` are ignored due to `Non-Explicit run`

### ISSUE THREAD

**Issue by eduherminio** [nunit/nunit#4160]
In [my project](https://github.com/lynx-chess/Lynx) I have a list of category names:

```csharp
public static class Categories
{
    // ....
    public const string LongRunning = "LongRunning";
    // ....
}
```

I have tests referencing them like this:
```csharp
    [Explicit]
    [TestCaseSource(typeof(MatePositions), nameof(MatePositions.Mates_in_4), Category = Categories.LongRunning)]
    public void Mate_in_4(string fen, string[]? allowedUCIMoveString, string description)
    {
        // ....
    }
```

and I attempt to run tests that belong to those categories like this:
`dotnet test -c Release --filter "TestCategory=LongRunning" --logger "console;verbosity=normal"`.

What I get when I execute them is the following:

```bash
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
NUnit Adapter 4.2.0.0: Test execution started
Running selected tests in C:\dev\personal\Lynx\tests\Lynx.Test\bin\Release\net6.0\Lynx.Test.dll
   NUnit3TestExecutor discovered 4 of 57 NUnit test cases using Current Discovery mode, Non-Explicit run
  // ....
  Skipped Mate_in_4("5k2/R7/8/5K2/8/8/8/8 w - - 0 1       ",["f5e6"],"") [7 ms]
  Skipped Mate_in_4("6k1/1R6/5K2/3p1N2/1P3n2/8/8/3r4 w - -",["f5h6"],"https://gameknot.com/chess-puzzle.pl?pz=260253") [7 ms]
  // ....
```

They are skipped, I guess due to the `Non-Explicit run`? 

**But... why non-explicit run? Is this expected? If so, why and how can I run the tests from that category using `dotnet test`?**

---------
Extra information:

In [this branch](https://github.com/lynx-chess/Lynx/compare/nunit-issue?expand=1) I added a sample test:
```csharp
    [Test]
    [Explicit]
    [Category("LongRunning")]
    public void __________________________SampleTest() { Assert.True(true); }
```

The behavior is the same (fair enough?):
```bash
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
NUnit Adapter 4.2.0.0: Test execution started
Running selected tests in C:\dev\personal\Lynx\tests\Lynx.Test\bin\Release\net6.0\Lynx.Test.dll
   NUnit3TestExecutor discovered 4 of 57 NUnit test cases using Current Discovery mode, Non-Explicit run
  // ....
  Skipped Mate_in_4("5k2/R7/8/5K2/8/8/8/8 w - - 0 1       ",["f5e6"],"") [7 ms]
  Skipped Mate_in_4("6k1/1R6/5K2/3p1N2/1P3n2/8/8/3r4 w - -",["f5h6"],"https://gameknot.com/chess-puzzle.pl?pz=260253") [7 ms]
  Skipped __________________________SampleTest [2 ms]
  // ....
```

However, weirdly, when I rename the category to something else:
```csharp
public static class Categories
{
    // ....
    public const string LongRunning = "LongRunningg";
    // ....
}
```

I do get an `Explicit run` and my SampleTest is executed:
```bash
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
NUnit Adapter 4.2.0.0: Test execution started
Running selected tests in C:\dev\personal\Lynx\tests\Lynx.Test\bin\Release\net6.0\Lynx.Test.dll
   NUnit3TestExecutor discovered 1 of 1 NUnit test cases using Current Discovery mode, Explicit run
NUnit Adapter 4.2.0.0: Test execution complete
  Passed __________________________SampleTest [4 ms]

Test Run Successful.
Total tests: 1
     Passed: 1
 Total time: 1.3188 Seconds
```

----

I'm clearly missing something here, hopefully someone can shed some light on it.
Apologies for not being able to reproduce it within a simpler setup.

**Comment by OsirisTerje** [comment]
The Non-explicit statement is just the result of the evaluation, not a setting.
The adapter is for some reason not able to deduct that the tests are Explicit, so this looks to be related to the adapter.  It might be lower though, since the adapter use the information it receives from the framework.

**Comment by eduherminio** [comment]
I also failed yesterday, but thankfully I've been luckier today and managed to get something with a similar quirky behavior which I understand shares the root cause with my real life case:
https://github.com/nunit/nunit3-vs-adapter.issues/pull/5

It's ready to be visited commit by commit

**Comment by eduherminio** [comment]
I added another pair of commits to reproduce a similar and probably related issue: when adding `[Ignore]` to one of the tests, the run stops being `Explicit`.

**Comment by stevenaw** [comment]
@OsirisTerje I did some digging and it sounds like this and https://github.com/nunit/nunit/issues/3979 could be duplicates of each other. Each has a decent amount of context in the history and, while this issue has a repro, #3979 has the context of having been in the adapter project but moved here to confirm if it's a framework or engine issue.

Would you mind if I closed this one and linked the repro to the other issue instead?

**Comment by OsirisTerje** [comment]
@stevenaw Please do :-)
