### ISSUE TITLE
Allow more option to configure LevelOfParallelism

### ISSUE THREAD

**Issue by Socolin** [nunit/nunit#4166]
Hello,

Would it be possible to configure LevelOfParallelism with a % of the number of the core to use?
My use case is the following: I have lots of test projects (mainly unit tests and integration) and 2 functional/e2e test projects that take longer to run. 

To speed up things, I run all tests assembly in parallel, and I also run the tests inside the e2e/functional tests in parallel. 

The Unit tests are complete within 10 seconds, the integration tests in 30-45 seconds and the 2 last (e2e / functional) are complete in 2-3 minutes. But currently, I have lots of test failing because CPU is a bit too busy and I would like to configure those both tests to use half the CPU cores available like `[LevelOfParallelism("50%")]` 

Like in jest: https://jestjs.io/docs/configuration#maxworkers-number--string

**Comment by stevenaw** [comment]
This is an interesting idea, though you may be able to do it today too. How are you running the tests, is it via the console runner?

While the framework does allow for a constant-level of parallelization via the `LevelOfParallelism` assembly attribute, this can also be passed into the framework from some runners. The nunit console, for example, can pass in `--workers=NUMBER` to control the level of parallelism. Depending on your setup, you could choose to pass in a static value here or potentially calculate it from a bootstrapper script like powershell
https://docs.nunit.org/articles/nunit/running-tests/Console-Command-Line.html

Another option which may help you is something like a runsettings file (though again that may need to be defined statically) where you can define a `NumberOfTestWorkers` to control the parallelization
https://docs.nunit.org/articles/vs-test-adapter/Tips-And-Tricks.html#numberoftestworkers

**Comment by stevenaw** [comment]
I don't have access to a rider install myself, but it looks like they should also support `.runsettings`. One option available to you with this approach could be to have each person configure theirs to their preferences and `.gitignore` it to prevent it from accidentally being committed.
https://www.jetbrains.com/help/rider/Reference__Options__Tools__Unit_Testing__NUnit.html#nunit-3

As far as the proposed change, I've tried to think about it a few different ways. I'm only one person on the team (and I welcome other points of view on this) but I personally have concerns around hidden ambiguity. 

You probably know how you'd interpret a value like "50%" to work, but others may interpret it differently. For example, is that "50% of physical core", "50% of logical cores", "50% of the default", or possibly something else still. It also wouldn't be clear to me how a percentage that calculates out to a fractional level of parallelism should be treated. 25% of cores on a 4-core machine is clear, but on a 2-core machine would that 0.5 round up or down? Separately, there's also a bit of a slippery slope with passing expressions as strings they may lead to suggestions for supporting increasingly complex expressions. Passing the value in other forms, like a floating point value, obviates the slippery slope but potentially introduces other ambiguities (ex: would 50% be `0.5` or `50.0`).

As I said, I'm just one person on the team. If, however, the team doesn't buy in you also still have the option to make your own custom attribute. NUnit has a lot of extension points and if you wanted you could extend `PropertyAttribute` with your desired behaviour in your codebase. The important thing to do with this approach would be to ensure you set it as a property of type `int` and named `LevelOfParallelism`. For example (untested pseudocode, based on the existing [LevelOfParallelismAttribute](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Attributes/LevelOfParallelismAttribute.cs)):

```csharp
[AttributeUsage( AttributeTargets.Assembly, AllowMultiple=false, Inherited=false)]
public class CustomLevelOfParallelismAttribute : PropertyAttribute
{
  public CustomLevelOfParallelismAttribute (string percentage) : base("LevelOfParallelism", Parse(percentage))
  {}

  private static int Parse(string percentage) {
    // your logic to convert "percentage" into an appropriate int for the level of parallelism to run the tests under
  }
}
```

**Comment by Socolin** [comment]
I did not know we could create a custom attribute for that, it worked :)

I agree with your comment, it would need more discussions about this.

In the meantime I think it would be nice to document this workaround in the documentation, like "If you want some custom logic, you can implement this attribute"
https://docs.nunit.org/articles/nunit/writing-tests/attributes/levelofparallelism.html

**Comment by stevenaw** [comment]
Glad to hear it worked for you! :)

My suggestion to inherit from `PropertyAttribute` was a minimal-code solution specific to your use case, but there is also some general documentation around custom attributes here: https://docs.nunit.org/articles/nunit/extending-nunit/Custom-Attributes.html
Rather than looking for specific attributes to work, NUnit actually looks for the interfaces defined there instead. For example, `PropertyAttribute` implements the `IApplyToTest` interface. So in theory a `CustomLevelOfParallelization` attribute would only need to implement this interface and not inherit from anything - though of course it would then need to do some additional work itself like the setting the test's property directly.

**Comment by stevenaw** [comment]
I'm going to close this issue, however we'll still be able to respond to any questions
