### ISSUE TITLE
Disposing AutoCAD Transaction will hang the Nunit and Nunitlite setup

### ISSUE THREAD

**Issue by WindingWinter** [nunit/nunit#4167]
Let me be clear that I can't tell whether this is a problem of NUnit 3.13.3, or[ NUnitlite Runner](https://docs.nunit.org/articles/nunit/running-tests/NUnitLite-Runner.html) 3.13.3, or AutoCAD/Civil 3D 2023.1 version. 

I've posted [the complete problem description](https://forums.autodesk.com/t5/net/why-commiting-transaction-is-a-must-even-for-read-only-operation/td-p/11389366) at AutoCAD forum ( finger crossed for a useful reply). To summarize the issue, it seems that if I use AutoCAD transaction as designed ( no need to Commit a transaction during a readonly operation), then under the test setup described, the code will hang at when I'm disposing the Transaction.

Note that if I don't comment out the tr.Transaction, then the code will run well. 

I've no idea how to further investigate in order to narrow down the problem, any pointers? If something thinks that this is a NUnitlite problem, feel free to move it to NUnitlite Runner forum.

**Comment by mikkelbu** [comment]
Can you attach a debugger to the test execution and then break into the debugger when the code hangs to see where it is blocked?

Can you provide more information about the environment? Is .NET framework, .NET Core, Mono ... How do you exactly execute the code. The more information the better :)

**Comment by WindingWinter** [comment]
Here's the parallel stack information:
![Hang thread](https://user-images.githubusercontent.com/13161574/187816149-54b2d607-340c-4e32-a013-b582434eb54d.png)

I'm running on .Net framework 4.8. So it's windows all the way down.

**Comment by WindingWinter** [comment]
OK, it stems from how AutoCAD API wasn't used properly. 

See the update [here](https://forums.autodesk.com/t5/net/why-commiting-transaction-is-a-must-even-for-read-only-operation/m-p/11417318/highlight/true#M74043)
