### ISSUE TITLE
How to make Nunit not break when reaching the NUnit Assert stage?

### ISSUE THREAD

**Issue by WindingWinter** [nunit/nunit#4171]
I'm using NUnit and NUnit lite Runner in my code, I found that the behavior when running with VS debugger attached is that, whenever the execution reaches the NUnit Assert stage ( like, even ` Assert.Pass("hehe")`), the program will break because `NUnit.Framework.AssertException` is thrown.

This is so very different from my experience in running NUnit without the lite Runner.

It doesn't matter whether the test passes or fails, since the `AssertException` is thrown, the program will break. It also doesn't matter if instruct the VS to not break for any thrown exception, the program will still break.

This is very annoying because I want to leave the tests running unattended ( this is the spirit of unit test, right?), but this behavior disrupts my plan.

Any idea how to solve this?

**Comment by manfred-brands** [comment]
The documentation of [Assert.Pass](https://docs.nunit.org/articles/nunit/writing-tests/assertions/classic-assertions/Assert.Pass.html) states that it ends the test.
If you want progress information, check out [TraceListener](https://docs.nunit.org/articles/vs-test-adapter/Trace-and-Debug.html)

**Comment by WindingWinter** [comment]
@manfred-brands , I'm not too sure how your comment is related to my question. I'm less concerned about printing the progress information, more about ensuring the VS debugger doesn't break when `NUnit.Framework.AssertException` is thrown.

**Comment by manfred-brands** [comment]
@WindingWinter What version of NUnit and VS are you using? NUnit 3.13/VS 2022 doesn't stop on those exceptions when debugging.

**Comment by WindingWinter** [comment]
I'm using NUnit 3.13, and VS 2022 Community version.

I can reproduce the problem very simply. Here's the code.

**Comment by WindingWinter** [comment]
And here's a screenshot

![passbreak](https://user-images.githubusercontent.com/13161574/188543567-c2396be3-d7b8-4d39-9e90-dce16fdf4777.png)

**Comment by manfred-brands** [comment]
The NUnit exceptions are not in the known list of VS "Common Language Runtime Exceptions", so that tick box doesn't do anything. You need to add them manually to the list. 
![image](https://user-images.githubusercontent.com/8655218/188544194-4a7676da-606f-44eb-9c20-748ce6e3266f.png)

Or simpler, remove the tick on "Break when this exception type is user-unhandled". Your code doesn't handle the exception, NUnit is.

**Comment by WindingWinter** [comment]
@manfred-brands , thank you! It solves the issue for me.
