### ISSUE TITLE
Limit test execution parallelism by set of resources

### ISSUE THREAD

**Issue by nzbart** [nunit/nunit#4184]
Is is possible to restrict parallel execution of tests by a given resource, such as a database, file, machine setting, or other shared resource that may be used by more than one test across an assembly or assemblies? While I know that unit tests should be completely independent, and ideally system tests as well, some real-world tests, or tests against legacy code, will run against resources that are difficult or expensive to replicate for multiple test cases.

NCrunch accomplishes this in a flexible way using the following attributes:
* [InclusivelyUsesAttribute](https://www.ncrunch.net/documentation/reference_runtime-framework_inclusively-uses-attribute)
* [ExclusivelyUsesAttribute](https://www.ncrunch.net/documentation/reference_runtime-framework_exclusively-uses-attribute)

It would be great if we could use a similar approach in NUnit via `dotnet test`.

**Comment by ondraco** [comment]
This would also help me a lot! For me the shared resources are the HW I am testing. It would be nice if I could have X of them and then be able to run X tests in parallel.

**Comment by stevenaw** [comment]
This is an  idea which seems to have gotten traction in the past. @nzbart I'm not closely familiar with how NCrunch does this, but I'm wondering if #165 describes what you're hoping for here

**Comment by nzbart** [comment]
@stevenaw you could be right. Maybe I couldn't find that issue because it doesn't really have a fleshed out design proposal, although @jnm2 has linked his ideas in https://github.com/nunit/nunit/issues/2389. I like the naming approach NCrunch takes, which is presumably based on the standard locking concepts of "exclusive" and "shared" locks.

I'll close this issue.
