### ISSUE TITLE
RetryAttribute doesn't reset TestContext.Properties

### ISSUE THREAD

**Issue by arnonax-tr** [nunit/nunit#4210]
When I set properties inside `TestContext.Properties` in the first retry, then if the test fail, and a second retry is invoked, the values from the first retry remain. I was expecting them to be reset, as between tests.
Is there a hidden reason behind this or is it a bug?

**Comment by arnonax-tr** [comment]
I also just noticed that I don't have a way to clear the existing properties by myself, which makes it much more annoying... :(

**Comment by stevenaw** [comment]
Thanks for raising this @arnonax-tr 

I'm unclear if this is by design or not as I lack the design history of this feature but I could see it going either way (by-design or a bug). It's certainly confusing for those who think of the testcontext as "per test execution", but for those who view it as "per test" then the current behaviour could be considered "correct".

I'm hoping someone from the @nunit/framework-team  with a bit more insight here can help weigh in here

**Comment by manfred-brands** [comment]
@arnonax-tr What properties are you setting?
I don't see a `TestContext.Properties` and `TestContext.CurrentContext.Test.Properties` is read-only. Its values come from `PropertyAttribute` set on tests.
There is a `TestContext.Parameters` which is also read-only.

Neither of these are as far as I know to be used for temporary user variables.
If you instead use a `Dictionary<string, object>` field that is set (or cleared) in a `SetUp` method then each run of your test will get a fresh dictionary as the `SetUp` method is called for each run.

**Comment by arnonax-tr** [comment]
Sorry about the confusion. I meant `TestExecutionContext.CurrentContext.CurrentTest.Properties`. While this property itself is read-only, the collection object (which implements `IPropertyBag`) is a mutable collection.

I'm using this collection from a library project, and therefore I don't have access to the test's `[SetUp]` method nor the test class itself. I didn't find any other way to attach state to the test's execution other than that. If you have a better idea, I'd be happy to hear.

**Comment by stevenaw** [comment]
Can you explain a bit more @arnonax-tr , perhaps with a code sample? If your code is in a library then it would be most helpful to understand the integration point with the test. For example, is it a base class, custom attribute, a helper method, or something else entirely? It would also help to know the versions of NUnit in use.

While it's tough to know without a code sample, I'm starting to wonder if you are trying to set properties as part of the test's execution itself, which if so, is unfortunately not something that was intended to be supported. If that's the case, there's a bit more of a description here: https://github.com/nunit/nunit/issues/3118#issuecomment-449568209

Though that's just a guess as to what you may be trying to do. Are you able to give us more info?

**Comment by arnonax-tr** [comment]
The description in https://github.com/nunit/nunit/issues/3118#issuecomment-449568209 looks very relevant, and also the feature request https://github.com/nunit/nunit/issues/3136 (which was unfortunately closed due to inactivity...)

Anyway, I'll try to describe the library and the use of the property:

The library provides logging functionality through Extent Reports. The final outcome is a single HTML file that contains the logs of all of the tests. Extent Reports has `ExtentReports` class that represents that entire report, and an `ExtentTest` that represents the log of a specific test, to which log entries should be added at runtime. However, we want to expose a simple `Log` method and hide all the details inside our library. But because tests can run in parallel, we need to be able to access the instance of the `ExtentTest` that is associated with the current test. The test author (the client of the library) is only expected to call a method called `StartTest` of our library on her `[SetUp]` method and `EndTest` on `[TearDown]`, and use `Log(...)` from anywhere to add log entries to the current test.
The real code is more complicated, but in essence, `StartTest` calls `TestExecutionContext.CurrentContext.CurrentTest.Properties.Set(_testLoggerTestContextProperty, new ExtentTest(...));` and `Log` calls `TestContext.CurrentContext.Test.Properties.Get(_testLoggerTestContextProperty) as ExtentTest`.

Note: I'm not very happy with using these test properties, as they are essentially global variables which the test author may access and manipulate, which breaks the encapsulation of my library, but I didn't find a better way. If you have a better idea for how to accomplish the same goal, without complicating things for the test author, I'll be happy to know.

**Comment by manfred-brands** [comment]
Inside your library you could have a dictionary with key Test and value ExtentTest.
In StartTest you as a new entry and in Log you lookup that entry from the Test context.Currentcontext.Test.
In EndTest you can cleanup.

**Comment by stevenaw** [comment]
@arnonax-tr Just following up on this. Did @manfred-brands 's answer work for you?

**Comment by arnonax-tr** [comment]
Pretty much. For some reason this doesn't look to me like the most elegant solution either, but currently I can't explain to myself why or what would I want to have differently, so I guess @manfred-brands's is a fine answer.

**Comment by stevenaw** [comment]
Great to hear it worked 😄
I'm also not sure the best way to approach this, but if more use cases come up in the future it could help shape a solution
