### ISSUE TITLE
Remove the word "failed" from test result summary lines or offer a configurable format string

### ISSUE THREAD

**Issue by SwissMaWi** [nunit/nunit#4234]
Nunit closes test runs with "========== Clean: 11 succeeded, 0 **failed**, 0 skipped =========="
In large log files from Devops Server it is really hard to find true failures.
IMHO the word **failed** should not occur in any test output if nothing has failed.

Potential solutions
1. do not write "0 failed" if nothing has failed. Simply omit that part.
2. make this like configurable by a .Net format string

**Comment by jnm2** [comment]
This is an MSBuild/.NET SDK message. NUnit doesn't write "Clean" or these `=====` lines to a log
