### ISSUE TITLE
Where can I get the functionalities of nunit.core in Nunit 3?

### ISSUE THREAD

**Issue by WindingWinter** [nunit/nunit#4245]
I understand that [nunit.core and nunit.util assemblies are not part of NUnit 3](https://stackoverflow.com/a/39420125/3834), only it NUnit 2.x.

But because I need some of the classes and functionalities in them, such as RemoteTestRunner, TestPackage in order to write my own test runner that runs all the tests in the main thread. Is there anyway that I can obtain related classes and services from any of the Nunit 3 dlls?

More specifically, I want to do [the equivalent](https://github.com/arup-group/RvtUnit/blob/master/rvtUnit/Controls/MainWindowViewModel.cs#L251) in NUnit 3.

         TestPackage theTestPackage = new TestPackage("All Dlls", assemblies);
         theTestPackage.Settings.Add("UseThreadedRunner", false);
         theTestPackage.Settings.Add("DomainUsage", DomainUsage.None);
         RemoteTestRunner testRunner = new RemoteTestRunner();
         testRunner.Load(theTestPackage);
         TestResult testResult = testRunner.Run(NullListener.NULL, testfilter, false, LoggingThreshold.Off);

From my testing, the above code will enable my tests to run in the main thread in Nunit 2, I gather that the NUnit 3 equivalent should also perserve the same behavior. 

I need to do this because I need to run [AutoCAD tests](https://forums.autodesk.com/t5/civil-3d-customization/tinsurface-rebuild-crashes-the-whole-civil-3d-application-when/m-p/11435428/highlight/true#M22212) in main thread, see also #4188 .

**Comment by stevenaw** [comment]
Sorry for the lack of activity in this issue @WindingWinter 
It sounds like the functionality you're looking for is just the ability to run tests on the main thread, which I believe is already tracked in https://github.com/nunit/nunit/issues/4240
I'm going to close this as a duplicate but please note that we'll continue to see and respond to any discussion
