### ISSUE TITLE
VS 2022 fails to run test or tests in a class with a test with the Range attribute  (Range doesn't convert [int] to same as parameter [uint])

### ISSUE THREAD

**Issue by Aaron-Corp00** [nunit/nunit#4261]
Hello NUnit Developers,
It appears that Test Explorer will not run any test that contains the [Range](https://docs.nunit.org/articles/nunit/writing-tests/attributes/range.html) attribute, nor will it run any test that is contained in a class that contains a test using the range attribute. For example:

```csharp
[Test]
public void Test([Range(0, 100)] uint value) {
    Assert.IsTrue(value < 101);
}
```

Original seen with the following software:
.Net 6.0
VS 17.2.? (I'm not quite sure of the version number).
Microsoft.Net.Test.Sdk 16.11.0
NUnit 3.13.2
NUnit Test Adapater 4.0.0

An attempt with updated software also failed:
.Net 6.0
VS 17.4.0
Microsoft.Net.Test.Sdk 17.4.0
NUnit 3.13.3
NUnit Test Adapater 4.3.0

The test also does not run with `dotnet test` with the updated software. I didn't try it with the original software.

Microsoft Visual Studio Professional 2022
Version 17.4.0
VisualStudio.17.Release/17.4.0+33103.184
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

Visual C++ 2022   00476-80000-00000-AA199
Microsoft Visual C++ 2022

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.4.326.54890
ASP.NET and Web Tools

AvaloniaPackage Extension   1.0
AvaloniaPackage Visual Studio Extension Detailed Info

Azure App Service Tools v3.0.0   17.4.326.54890
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.4.0-3.22518.13+7856a68c109b22de70e07580018fec601e944f46
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   17.0.22263.6
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Python - Profiling support   17.0.22263.6
Profiling support for Python projects.

Python with Pylance   17.0.22263.6
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

SQL Server Data Tools   17.0.62207.28050
Microsoft SQL Server Data Tools

SQLite & SQL Server Compact Toolbox   4.8
SQLite & SQL Server Compact Toolbox adds scripting, import, export, rename, query execution and much more to SQL Server Compact & SQLite Data Connections.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.10921.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.4.0-3.22518.13+7856a68c109b22de70e07580018fec601e944f46
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.4.0-beta.22512.4+525d5109e389341bb90b144c24e2ad1ceec91e7b
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

Regards,
Aaron

**Comment by stevenaw** [comment]
Interesting! I can also confirm this is happening on the following:

> .Net 6.0
VS 17.4.0
Microsoft.Net.Test.Sdk 17.4.0
NUnit 3.13.3
NUnit Test Adapater 4.3.1

It looks to be related to the passing of `int`s in the range attribute which are then received as a `uint`. Either of the below will work:

```csharp
[Test]
public void Test([Range(0, 100)] int value)
{
    Assert.IsTrue(value < 101);
}

[Test]
public void Test([Range(0u, 100u)] uint value)
{
    Assert.IsTrue(value < 101);
}
```

This sounds vaguely familiar. I'm not able to check if a previous filing exists for it. I'm wondering if this type mismatching is something we want to consider checking for as an analyzer too. 80% of the time I work with unsigned numbers I forget to add the suffix until the compiler tells me to

**Comment by stevenaw** [comment]
https://github.com/nunit/nunit/issues/2783 is what I had been thinking of.
The initial example there passes ints into the `TestCaseAttribute` in hex format instead of decimal but I believe the underlying issue is the same.

I'm going to close this as a duplicate and include a note there that it is also present in the `Range` attribute
