### ISSUE TITLE
Is there anyway to run only the tests that are under "Debug\AnyCPU" in NUnit3 Console?

### ISSUE THREAD

**Issue by WindingWinter** [nunit/nunit#4263]
I can run all of my test cases in a solution file ( in DEBUG mode) by using the following command:

`nunit3-console.exe "%SlnFile%" /config:Debug --skipnontestassemblies --result="%TestResult.xml%"`

But this command will run for all tests under different platforms, x86, x64 and AnyCPU that are defined in the csprojects. 

Is there anyway to restrict it, so that nunit3-console only runs for DEBUG|AnyCPU?

**Comment by stevenaw** [comment]
This question may be better suited for the audience in the console runner repo (https://github.com/nunit/nunit-console), but it should be possible to point the console runner at a DLL. Are you able to structure your build output in a way that you can point the console runner at a DLL output from the desired build target?

**Comment by rprouse** [comment]
We haven't heard back, so closing. Please comment if you want this re-opened.
