### ISSUE TITLE
No nUnit tags past 3.13, causing broken package deployment

### ISSUE THREAD

**Issue by LeftofZen** [nunit/nunit#4269]
nUnit hasn't had a tag since 3.13 despite claiming 3.15.2 is out: https://docs.nunit.org/articles/nunit-engine/release-notes.html

As a result, package deployment has also ceased - Nuget only has 3.13 as does nUnit's own downloads page: https://nunit.org/download/.

This means that nUnit consumers like myself are having issues with .NET 6 unit tests not working but are unable to update past 3.13 to rectify those issues.

What is the reason for ceasing tagging and package deployment of nUnit?

**Comment by manfred-brands** [comment]
There is a difference between the nunit console/engine and the nunit framework. The latest version of the latter is 3.13. What problems do you have with .Net 6?

**Comment by manfred-brands** [comment]
I can reproduce your issue, but can you explain that offending member?
You have a generic `struct Range<T>`, with a fully qualified member `Range<TimeOnly>`? I'm sure you created this for the reproduction, but what is the real case where a generic type has a specific member?
Note that every T has its own copy of that member, so `Range<TA>.NineToFive` is a different instance from `Range<TB>.NineToFive`

Note that if you change the code to `class Range<T>`, NUnit can load the test just fine.

Note that the inability to load has nothing to do with NUnit.
I added a console program Show with a Program.cs containing:
```csharp
using Lib;

Range<DateOnly> year = new(new DateOnly(2022, 1, 1), new DateOnly(2022, 12, 31));

Console.WriteLine(year.Start);
Console.WriteLine(year.End);
```

Running this program gives the same `TypeLoadException` as NUnit:
```
$ ./Show.exe
Unhandled exception. System.TypeLoadException: Could not load type 'Lib.Range`1' from assembly 'Lib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Program.<Main>$(String[] args)
```

So it looks like .NET allows us to compile code it cannot load.

**Comment by LeftofZen** [comment]
The purpose of the static member was just to provide a constant for the fully-qualified type, and as you rightly point out this design is shit because it means each T has its own copy of it when it really only applies to a single T. This wasn't an effect of making the SSCCE, I just originally coded it up like that. I've moved this static property to its own class specifically for constants of T type, ie just a simple

```
public static class TimeRangeConstants
{
	public static readonly TemporalRange<TimeOnly>NineToFive = (new TimeOnly(9, 0, 0), new TimeOnly(17, 0, 0));
}
```
and this is how I should have done it in the first place.

In my case struct better represents what I'm doing with the type so I won't change it to class.

Nice find that this isn't an nUnit problem, I'm happy for you to therefore close this issue here. Ignoring my shitty original design, this sounds like an issue with .NET itself and I should file a bug report there?

**Comment by manfred-brands** [comment]
> Ignoring my shitty original design, this sounds like an issue with .NET itself and I should file a bug report there?

Maybe .NET tries to help you to prevent shitty designs

**Comment by LeftofZen** [comment]
> Maybe .NET tries to help you to prevent shitty designs

Or maybe not. In this case this is a problem with .NET.
