### ISSUE TITLE
Unclear documentation for Assert.Greater(arg1, arg2)

### ISSUE THREAD

**Issue by WindingWinter** [nunit/nunit#4271]
For `Assert.Greater(arg1, arg2)`, to make the test passes, which argument should be greater, arg1 or arg2?

It would be great to rename the argument to something like:

`Assert.Greater(greater, lesser)`

This would improve the clarity

**Comment by stevenaw** [comment]
Thanks @WindingWinter 
I agree, this is something that we shouldn't change in code, with the primary concern being that it could be a breaking change for anyone passing values to this API as named parameters. We took a similar approach in #4185
