### ISSUE TITLE
Clean up inactive contributors

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#4273]
I am removing inactive contributors from the @nunit/framework-team for security.

@OmicronPersei, @oznetmaster and @Dreamescaper, if you would like to continue working with us, let me know and I will re-add you. Thanks for your many past contributions and help.

**Comment by oznetmaster** [comment]
I am still supporting the .NET Compact Framework version for Crestron.

 

I would like to remain a contributor.

 

From: Rob Prouse ***@***.***> 
Sent: Monday, January 9, 2023 6:26 AM
To: nunit/nunit ***@***.***>
Cc: Neil Colvin ***@***.***>; Mention ***@***.***>
Subject: [nunit/nunit] Clean up inactive contributors (Issue #4273)

 

I am removing inactive contributors from the @nunit/framework-team <https://github.com/orgs/nunit/teams/framework-team>  for security.

@OmicronPersei <https://github.com/OmicronPersei> , @oznetmaster <https://github.com/oznetmaster>  and @Dreamescaper <https://github.com/Dreamescaper> , if you would like to continue working with us, let me know and I will re-add you. Thanks for your many past contributions and help.
