### ISSUE TITLE
App.Config settings values are null while running the tests using nunit3-console.exe

### ISSUE THREAD

**Issue by NadeemBader** [nunit/nunit#4274]
Hi
I have a tests c# (.Net 6.0) project with nunit tests.

Versions:
* Nunit: 3.13.3
* NUnit3TestAdapter: 4.1.0

This project contains app.config file which contains different appSettings keys.
By running the test from Visual Studio (V. 2022), the tests runs as expected.
But by running the tests using nunit3-console.exe (V. 3.16.1), the tests fails since the values are not retrieved from the App.Config file (Always null).

I'm reading the settings as shown here:
var value = ConfigurationManager.AppSettings["Url"];

I mean, in my case the "value" is always "null"

Here is the command line:
```
nunit3-console.exe D:\Output\CMR.Automation.UI.TestLayer.dll --configfile=D:\Output\CMR.Automation.UI.TestLayer.config --where="cat == Level1" --work=TestResults --out=C:\Automation\Logs\Xml\TestResult.txt --result=C:\Automation\Logs\Xml\TestResult.xml
```
Can you please assist?

Best Regards,
Nadeem Bader

**Comment by NadeemBader** [comment]
HI
Hope to get help
Best Regards,
Nadeem Bader

**Comment by nbader1** [comment]
Kindly reminder

**Comment by nbader1** [comment]
Hi

Thank you for your reply
I tried all suggested ways. But none of them helped me.
It is important to indicate that by running the test from Visual Studio itself, I'm able to run all data from the App.Config file. But when run using the nunit3-console.exe, I'm facing the described issue.

Any suggestions?

Best Regards,
Nadeem Bader

**Comment by stevenaw** [comment]
If those links don't help then we may need more information. Are you able to provide a minimal repro of what you are trying, something in a format which would be easy for a team member to run to replicate your issue? Common ways in the past for this to have been given is in the form of a ZIP file of a small solution or a github repo with a sample project source in it.
