### ISSUE TITLE
Adding a NuGet reference to NUnit.Engie 3.16.x causes Microsoft.Data.SqlClient to throw a PlatformNotSupportedException

### ISSUE THREAD

**Issue by toniarnold** [nunit/nunit#4279]
Steps to reproduce:

1. Create a vanilla .NET Core TestProject1 from the "NUnit Test Project" template in VS 2022 (.NET 6)
2. Run the test. Green.
3. Add the "System.Data.SqlClient" NuGet package (currently Version="4.8.5")
4. Replace Assert.Pass(); with this line in Test1():
   var c = new SqlConnection();
5. Run the test. Green.
6. Add just a reference to the "NUnit.Engine" NuGet package (currently Version="3.16.2") (without even using it).
7. Run the test. Red with:
   System.PlatformNotSupportedException : System.Data.SqlClient is not supported on this platform.
8. Downgrade NUnit.Engine to Version="3.15.2"
9. Run the test. Green again.
10. Re-upgrade to 3.16.0
11. Side-observation: The tests remain blue and are not run. This was fixed in NUnit.Engine 3.16.1
12. NUnit.Engine 3.16.1 also yields the PlatformNotSupportedException (same as 3.16.2)
13. Side-observation: Just delete nunit.engine*.dll in the bin dir and run 
    dotnet test --no-build. 
	Yellow with "No test found."

The PlatformNotSupportedException problem vanishes on .NET Core 2.1 to 3.0, only later versions are affected. 

Upgrading the TestProject1 to all all current NuGet packages yields (problem persists):
```
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.4.1" />
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit.Engine" Version="3.16.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.3.1" />
    <PackageReference Include="NUnit.Analyzers" Version="3.5.0">
    <PackageReference Include="coverlet.collector" Version="3.2.0">
    <PackageReference Include="System.Data.SqlClient" Version="4.8.5" />
```
Expected behaviour:

Adding just an (also indirect) NuGet reference to NUnit.Engine to an NUnit test project should not affect System.Data.SqlClient DLL resolution.

**Comment by SeanKilleen** [comment]
Out of curiosity, does this have the same issue when using the `Microsoft.Data.SqlServer` package rather than System.Data.SqlClient?

**Comment by toniarnold** [comment]
Thank you for the hint - using the legacy `System.Data.SqlClient` is a forgotten left-over in the [project](https://github.com/toniarnold/aspnettest/blob/master/src/asplib.core/Model/Db/IDeleteNewRows.cs) where I've encountered the problem. Replacing it with the current `Microsoft.Data.SqlClient` makes no difference, and I've updated the bug title accordingly. The problem is the same, also when the tests are run from the Visual Studio 2022 Developer Power Shell with `dotnet test`:
```
  Fehler Test1 [47 ms]
  Fehlermeldung:
   System.PlatformNotSupportedException : Microsoft.Data.SqlClient is not supported on this platform.
  Stapelverfolgung:
     at Microsoft.Data.SqlClient.SqlConnection..ctor()
   at TestProject1.Tests.Test1() in C:\Users\tarnold\Documents\AspNetTest\Parts\NUnit.Engine\TestProject1\UnitTest1.cs:line 15


Fehler!      : Fehler:     1, erfolgreich:     0, übersprungen:     0, gesamt:     1, Dauer: 47 ms - TestProject1.dll (net6.0)
```
The OS is Windows 10 Pro/22H2/19045.2486 and I'm trying to connect to a Microsoft SQL Server Developer (64-bit) 15.0.4236.7.

**Comment by SeanKilleen** [comment]
I created a reproduction repository here: https://github.com/SeanKilleen/nunit-4279-repro

Verified this is indeed the case and I'm also confused (though I'm new to look into these things, so I suspect I'll learn something here).

Dropping a quick table of publishing targets from Nuget here for reference. 

| Version | .NET Framework 2.0 | .NET Core 3.1 | .NET Standard 2.0 | .NET Framework 4.6.2 |
| -------- | -------------------- | -------------- | ------------------ | --- |
| NUnit.Engine 3.14.x |  ✅ | ✅ | ✅ |  ❌ |
| NUnit.Engine 3.15.x | ✅ | ❌  | ✅ | ❌ |
| NUnit.Engine 3.16.x |  ❌ | ✅   |  ✅  | ✅  |
| Microsoft.Data.SqlClient | ❌ | ❌ | ✅ | ✅  |

**Comment by stevenaw** [comment]
I haven't looked in depth into this myself, but it reminds me a bit of https://github.com/nunit/nunit-console/issues/1282
which itself could be related to this: https://github.com/nunit/nunit-console/issues/1269

Though I'm not sure yet how the addition of the Engine package here is causing any issues for the runner. I'll likely also learn a thing or two from this.

**Comment by OsirisTerje** [comment]
This is [probably] not related to the SqlClient package.  Adding a reference to the engine when at the same time using the adapter will cause issues (probably crashing).  
The adapter has the Nunit.Engine package embedded, and that is fixed to a certain version.

**Using adapter 4.3.1 the embedded engine is version 3.15.2.**  

(Also be aware of this list of compatible frameworks:   https://docs.nunit.org/articles/vs-test-adapter/Supported-Frameworks.html  )

PS:  The NUnit.Analyzer should be extended to warn if the versions do not match up. Tha adapter can probably not do this, since it might fail before it manages to output anything, we can try though.....

**Comment by mikkelbu** [comment]
Regarding the analyzer, then I'm unsure whether it is possible or not, but I've created nunit/nunit.analyzers#515.

**Comment by OsirisTerje** [comment]
@stevenaw @mikkelbu Can't this issue be closed now?

**Comment by stevenaw** [comment]
Thanks @OsirisTerje ! Yep, I agree this can be closed. Thanks for the docs and filing the analyzer-side ticket
