### ISSUE TITLE
Add ExpectedExceptionAttribute to C# samples

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#428]
As discussed in the mailing list, upgrading projects from 2.6.x to 3.0 can be tedious if `ExpectedException` was used extensively. Instead of adding it back in, we decided to provide a limited version of the attribute as an example of extensibility in 3.0.

**Comment by CharliePoole** [comment]
I posted questions on nunit-discuss regarding removal of the attribute. Let's wait to see what the response is.
