### ISSUE TITLE
Using Range Attribute to create millions of test cases does not work

### ISSUE THREAD

**Issue by elksson** [nunit/nunit#4288]
Are there any limitations on the number of test cases that can be created using RangeAttribute? 
The following test case seems to not be able to run using the VS test adapter, not sure if it runs using other methods or not.
`[Test]
public void Test1([Range(0,0x7FF)] int one, [Range(0, 0x7FF)] int two, [Range(0, 0x7FF)] int three, [Range(0, 0x7FF)] int four, [Range(0, 0x7FF)] int five)
{
    Assert.Pass();
}`

**Comment by OsirisTerje** [comment]
Perhaps time?  

Running 2000 (~0x7FF) tests takes (on my machine) approx 0.5s.  (200000 tests take around 43 s) 
2000*2000 => 1000 secs => 17 min
2000*2000*2000 => 34000 min => 570 hours => 24 days
... 4 of these  => 130 years
... 5 of these...  => 260.000 years...  time enough to create a new humankind I would guess :-)  

So 2000^5 might be slightly too much, but it should work if you keep within the millions range.  
There are no built-in limits, so operating system, x32/x64, memory space and.... TIME,  that should be your constraints.

**Comment by elksson** [comment]
Yes the problem here is that not all these test cases are actually valid so I was planning to use a theory to filter out the invalid cases cause it would be a huge task to calculate by hand the valid test cases. I tried using testcasesource as well but calculating the test cases also seems to take a significant amount of time. Also generating the test cases seems to cause a memory exception on x86. and maybe x64 not sure. Our next attempt is to pre-compute the test steps into a json file and load them during run time. It would be nice to have a built in method in nunit that could automatically handle this for large test sets.

**Comment by stevenaw** [comment]
There's some unreleased test discovery performance improvements which should ship in the next release that may help here, but "millions" is still quite a high, somewhat unbounded number to know for sure if it will solve it. In either case the data set is likely large enough that pre-computing may be best as you say. https://github.com/nunit/nunit/issues/706 is an old feature request here which I think, if implemented, could satisfy your need here:

> It would be nice to have a built in method in nunit that could automatically handle this for large test sets.
