### ISSUE TITLE
.NET5 Test Suite is failing on Azure DevOps for Windows

### ISSUE THREAD

**Issue by stevenaw** [nunit/nunit#4293]
It looks like the test suite is having issues targeting .NET5 for Window on Azure DevOps. Multiple recent PRs have failed on the .NET5 build with the following ([example link](https://nunit.visualstudio.com/NUnit/_build/results?buildId=5961&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=abae1f68-3c73-5bff-491f-f2b908580ce6&l=1701))

> ========================================
TestNetStandard20 on net5.0
========================================
##[error]Unable to process command '##vso[results.publish type=NUnit;mergeResults=true;config=Release;runTitle='net5.0/Windows';publishRunAttachments=true;]' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)

The build output indicates that .NET5 isn't installed by default, and the image documentation supports this (https://github.com/actions/runner-images/blob/main/images/win/Windows2019-Readme.md#net-core-tools)

The Linux and MacOS builds appear fine since it seems we install the runtime  as part of the build. While normally we may consider manually installing it on the Windows image too, .NET5 has been out of support by Microsoft for about 9 months, since May 10, 2022 (https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core). We should consider if we should explicitly target it on the Windows build or, perhaps, to instead remove it as a test suite target.

Any change here would need to be included in both main + v3.13 branches

**Comment by manfred-brands** [comment]
For this reason, I prefer GitHub actions where we are in control what SDKs are installed, instead of perfectly fine builds failing because MS no longer has older frameworks installed.

The support decision is up to @nunit/framework-team

**Comment by rprouse** [comment]
Should we drop the Azure DevOps build in favor of the Github Actions? I'd prefer to only maintain and check one build.

I'm also good with getting the tests to a supported version of the framework. I was going to look at that last night but ran out of time after the console release.

**Comment by stevenaw** [comment]
Does Azure DevOps provide any benefits over Github Actions? I'd be ok to drop it if there's no added value from it, and fewer build configs to maintain is always a good thing too.

**Comment by rprouse** [comment]
@stevenaw I don't see huge value in building on multiple build systems. We set up Azure DevOps because it had Windows, Linux and Mac build agents. Previously we were using multiple build systems to test each platform. Now that GitHub actions is available, I think it is a much more integrated and seamless experience, so I am good to make it our primary build system and drop support for others.

**Comment by rprouse** [comment]
I've disabled Azure DevOps as a required check and I am working on a PR to remove it and to enable the GitHub actions as a required check.

**Comment by rprouse** [comment]
My two PRs have enabled the GitHub Actions as required checks so they have been added as required for all PRs in all branch protection rules.
