### ISSUE TITLE
Is it possible to redirect/split content of TestContext.Out?

### ISSUE THREAD

**Issue by BADF00D** [nunit/nunit#4294]
We have a rather special situation. We use NUnit to run integration tests that check if a real device behaves correctly. In cases a test fails, its part of the TearDown method to collect log files from the device and its environment. These get stored in a special folder and finally uploaded to Azure. So far all good.
The tests itself write lots of status messages to the methods of TestContext.Out and TestContext.Progress. This get also uploaded Azure while publishing the trx files. 

My problem is, I want to download all logs at once, but the StdOut log is stored in a separate location. I searched for a possibility to replaces the TextWriter used by the TestContext, but I was not able to find public setter. 
is there a possibility to redirect the output of the TextWriters? I was not able to find any public setter to do so.

**Comment by stevenaw** [comment]
It is possible, but the suggestion may vary depending on your environment. Can you explain a bit more about how you are running the tests (`dotnet test`, `nunit-console.exe`, `nunitlite`, etc)?

In theory nunit itself and nunitlite both write to `Console.Out` by wrapping it. In theory if you were to make your own custom writer you could then use .NET's `Console.SetOut()` function to set where stdout goes and you could then split or redirect as needed. The same could be applied to `Console.SetError` for "immediate" progress messages I believe. Note though that this carries it's own maintenance overhead around management and disposal of these streams which would then need to be handled by your own code. There is a recently-submitted PR to detect and handle that particular issue of disposal within the framework, but it hasn't been reviewed yet.

However, other simpler options may be available. Most runners include the ability to configure where stdout is written too which may save you the effort of handling that yourself.
