### ISSUE TITLE
TextRunner accidentally disposes System.Out

### ISSUE THREAD

**Issue by jeroenvervaeke** [nunit/nunit#4319]
It is possible to replace `System.Out` with your own implementation of `TextWriter`.
One reason why you would want to do that is if you want to both capture all output to a stream and write it to console.

I was using this approach and I stumbled upon an issue when using `TextRunner`.
When using `TextRunner`, and not providing a file, `TextRunner` defaults to `System.Out`.
When `TextRunner` is done running it disposes the underlying stream that it was writing to. This is correct behaviour when using files, but not desired behaviour when using `System.Out`.
See: [source code
](https://github.com/nunit/nunit/blob/92180f13381621e308b01f0abd1a397cc1350c12/src/NUnitFramework/nunitlite/TextRunner.cs#L104)

I modified `ConsoleColorWriter` so `Dispose` is a NOP. (The base class disposes the writer provided by `ConsoleColorWriter` = `System.Out`).

I've also added a unit test to verify that the fix works. If you want a code example of what crashes, check the unit test.

**Comment by mr-russ** [comment]
How does PR #4317 and your pull request?  I've not looked in detail as I don't understand the implications of each.  They appear on the surface to do similar things.  Can you provide some comments about how they work together, if they are the same or completely different?

**Comment by jeroenvervaeke** [comment]
Apparently my colleague and I both created a PR in our spare time for the same issue without telling each other about it. We can close my PR in favor of the PR that @normj created

**Comment by normj** [comment]
Whoops sorry about the miscommunication @jeroenvervaeke and @mr-russ

**Comment by stevenaw** [comment]
Not a problem! It's always welcome to have bugs filed, and having two PRs submitted to fix it is never a bad thing either.

PS: I enjoyed your recent Lambda GC article @normj , great read.

**Comment by stevenaw** [comment]
Oops, I just noticed that this was the only open issue for this. I'm going to reopen it to track the PR fix

**Comment by OsirisTerje** [comment]
The current PR #4317 to main should go there, and it would be nice if @normj would add another PR to merge to the 3.13 branch.

**Comment by normj** [comment]
I update the PR with a test and I can create a PR for 3.13 once I know I did this PR correctly.

@stevenaw Great to hear you like the blog post!
