### ISSUE TITLE
test fixture public methods not accessible from attribute implementing `ITestAction`

### ISSUE THREAD

**Issue by awa5114** [nunit/nunit#4349]
I'm trying to call a public method in my `TestFixture` before every test using a custom attribute that implements the `ITestAction` interface.

Here's what I tried:

```
   [AttributeUsage(AttributeTargets.Method)]
   internal class CreateIdoAttribute : Attribute, ITestAction
   {
      public CreateIdoAttribute()
      {

      }
      public void BeforeTest(ITest test)
      {
         
         //test.Fixture.MyPublicMethod();
         return;
      }

      public void AfterTest(ITest test)
      {
         return;
      }

      public ActionTargets Targets => ActionTargets.Test;
   }
```

The type of `test.Fixture` is actually my test class, and I can see all its private fields in the debugger. Strangely enough I am unable to call the public method, and if I uncomment the call in `BeforeTest` and compile, the test fails.

Can I get to the public methods or properties of my test fixture through `ITestAction`? If not what is the appropriate interface to use here?

**Comment by manfred-brands** [comment]
The compiler doesn't know the type, you have to cast the `test.Fixture` first.
You can use:
```
MyTestClass fixture = (MyTestClass)test.Fixture;
```
That will limit your attribute to only that particular class. But as you want to call a method on it, that is probably your intention.
Alternatively you can cast to an interface or base class that has that method you want to call.

**Comment by manfred-brands** [comment]
@amine-aboufirass That is a different kind of attribute, you will have to implement an [ITestBuilder](https://docs.nunit.org/articles/nunit/extending-nunit/ITestBuilder-Interface.html)
