### ISSUE TITLE
Allow Is.AnyOf to be called with arrays or other collections

### ISSUE THREAD

**Issue by manfred-brands** [nunit/nunit#4355]
Follow-up to a great docs observation on https://github.com/nunit/docs/pull/750 and https://github.com/nunit/nunit.analyzers/issues/533

The `Is.AnyOf` only works if the members are specified as individual values, not if passed as an array or list.

Example Gotcha:

```csharp
[Test]
public void CanBeUsedWithParameters()
{
    Assert.That(42, Is.AnyOf(0, -1, 42, 100)); // Passes
}

[Test]
public void CantBeUsedWithAnArray()
{
    var array = new[] { 0, -1, 42, 100 };
    Assert.That(42, Is.AnyOf(array)); // Fails
}

[Test]
public void CantBeUsedWithAList()
{
    var list = new List<int>() { 0, -1, 42, 100 };
    Assert.That(42, Is.AnyOf(list)); // Fails
}
```

It was suggested to make an Analyzer to warn about this, but it seems more prudent to fix it in the framework, so that these expected cases work.

**Comment by stevenaw** [comment]
I'm not positive, but I feel like this may have been by-design to account for an edge case with strings being an innumerable<char> but I could be mistaken.

I'd have to refresh myself on some of the design discussions in https://github.com/nunit/nunit/issues/2704

**Comment by manfred-brands** [comment]
@stevenaw Yes, that issue was discussed in #2704, with a remark _We could add the params now and do IEnumerable on demand later_.

I added a nunit test that proofs that the below work.
```
            Assert.That('A', Is.AnyOf('A', 'B', 'C'));
            Assert.That("Hello", Is.AnyOf("Hi", "Hello", "G'day"));

            string[] greetings = { "Hi", "Hello", "G'day" };
            Assert.That("Hello", Is.AnyOf(greetings));
```

The one not working is: 
```
            Assert.That('A', Is.AnyOf("ABC"));
```
But that one doesn't work in the master branch either, so isn't something broken. I would that to be written as:
```
            Assert.That("ABC", Does.Contain('A'));
```

This brings me to the point that `Is.AnyOf` is the reverse of `Does.Contain` and if we have an array, we should write:
```
            string[] greetings = { "Hi", "Hello", "G'day" };
            Assert.That(greetings, Does.Contain("Hallo"));
```
Which actually started the whole `Is.AnyOf` discussion as the error message was confusing.
It is now:
```
  Expected: some item equal to "Hallo"
  But was:  < "Hi", "Hello", "G'day" >
```

So this PR has not broken anything, but added something we might or might not want.

**Comment by stevenaw** [comment]
Thanks @manfred-brands !
I had a feeling this scenario had been discussed, I just couldn't remember the outcome

**Comment by ivan-gurin** [comment]
Hey how about
https://github.com/nunit/nunit/blob/097a1be976fb6bfff6a2a3a9d8b24dd5010fbcdb/src/NUnitFramework/framework/Constraints/ConstraintExpression.cs#L870 ?
I want Has.All.AnyOf() :)

**Comment by OsirisTerje** [comment]
This issue is closed.
