### ISSUE TITLE
How to enable One test method depends on another Test method using Nunit 3.13.3 version

### ISSUE THREAD

**Issue by lakshminagandla** [nunit/nunit#4359]
As per the Nunit documentation, we could see below Attribute we can use to enable the dependency, but it is not working

[Dependencies (<dependency-specification> [, <dependency-specification> [, ...]])]

where <dependency-specification> is:

Before="TestA, TestB"
After="TestC, TestD"
AfterAnySuccess="TestE, TestF"
AfterAnyFailure="TestG, TestH"
AfterAllSuccess="TestE, TestF"
AfterAllFailure="TestG, TestH"
BeforeAll
AfterAll
AfterAllSuccess
This attribute would apply to Test's within a single TestFixture, or to TextFixture's within a single test assembly.

Though I have used [Dependencies] attribute, it is unable to identify it. Hence can you please help with this.

**Comment by OsirisTerje** [comment]
Where do you seethis attribute?

**Comment by stevenaw** [comment]
@lakshminagandla Are you referring to https://docs.nunit.org/articles/nunit/technical-notes/nunit-internals/specs/Test-Dependency-Attribute-Spec.html ?

It looks like that is a draft spec for an attribute that was never implemented. I think there was a bit of discussion around trying to implement a dependency feature like that early on in the planning for NUnit 3, but as far as I can tell a simpler `Order` attribute was chosen instead. The original discussion can mostly be found in https://github.com/nunit/nunit/issues/51, but apparently it's an even longer-standing request going back to 2011 in https://bugs.launchpad.net/nunit-3.0/+bug/740539

From what I can tell, that draft spec could still be relevant to #51 if it were to be implemented in the future, though unfortunately no such attribute exists as of yet.

**Comment by stevenaw** [comment]
You can find some documentation about the simplified "`Order`" attribute here: https://docs.nunit.org/articles/nunit/writing-tests/attributes/order.html

I hope that one can also meet your use case
