### ISSUE TITLE
Add NUnit.Analyzer to our test projects

### ISSUE THREAD

**Issue by manfred-brands** [nunit/nunit#4364]
Mainly as it is needed for #3376 we should add the NUnit.Analyzers to our test projects.

**Comment by manfred-brands** [comment]
Adding this resulted in a lot (1k+) analyzer errors/warnings, meaning we have a mismatch between the two. 
Some are because the tests are explicitly for those cases, such as calling `Assert` with mismatched types, calling `Assert` with constants.

Some are limitations in the analyzer:

* (`TypeParameterUsedWithTestMethod<T>)` and equivalents. The analyzer would have to deduce the type from the `TestFixture` attribute. Not sure how often this is used in real life if it warrants the work needed in the analyzer.
* `ConstraintTestBase` references a property in a `TestCaseSource` which is not defined in the class, but assumes that a derived class would have one. As the member must be `static` we cannot specify this as an abstract property. The derived classes get standard .net analyzer warnings about unused fields. Not sure how to fix that nicely.

**Comment by jnm2** [comment]
I'd usually use pragmas with explanations in a comment on the pragma line.

This doesn't help earlier than .NET 7, but interfaces can declare static abstract members and I wonder if implementing such an interface would cause the compiler to stop calling then fields unused.

**Comment by manfred-brands** [comment]
@jnm2 Unfortunately the interface approach doesn't help with a derived class hierarchy.
If we put the interface on the base class we need to implement it them in the base class and we can't implement static members as abstract there.
