### ISSUE TITLE
Timeout does not properly abort unit test and run longer than the threshold

### ISSUE THREAD

**Issue by fl0l-gouze** [nunit/nunit#4371]
Hello,

We are facing the issue, where, despite a timeout set to 1 mins, unit test can run during 1hours or more.
While i've not yet identified the "why" on the code, here is the behavior observed : 

Test PublicNunitIssue is running with a timeout on 1 mins.
While below threshold limit, unit test will either call an external service or query something on database that will last for hours (longer that it should).
The test wait for the query to be finished to evaluate the time spent, and will fail the test with below errors : 
PublicNunitIssue [6 mins 3s] Failed: Test Exceeded Timeout value of 60 000ms.

Here is the smallest non compiling example i could find (non compiling on your end but working on my workstation targeting oracle db) : 
```
        [Timeout(60000)] //1min timeout
        [Test]
        public void SmallestVisibleIssueTest()
        {
            using(var dbCom = Context.CreateCommand())
            {
                dbCom.CommandText = "BEGIN dbms_session.sleep(360); END;"; //6 mins sleep
                dbCom.Commandtype = CommandType.Text;
                Console.WriteLine("Will go there");
                dbCom.ExecuteReader();
                Console.WriteLine("Will never go there");

            }
        }
```
**When run locally, the test will run for more than 6 mins, then once the dbCom finish is query, the timeout seem to be evaluated and only then the test throw.
My expectation were to have the timeout throwing an failure during the ExecuteReader();**

The timeout seems to work fine when using task / sleep, Meaning the test will stop at 1mins on the dot, not waiting for newTask.Wait to complete.
```
        [Timeout(60000)] //1 min timeout
        [Test]
        public void TaskWorkingWithTimeout()
        {
            var newTask = Task.Run(() => Thread.Sleep(6 * 1000 * 60)); //6 mins sleep
            newTask.Wait();
        }
```

I believe regardless of the underlying code, we should never breach the Timeout, otherwise it would be a duplicate between maxTime and Timeout.
Is this an expected behavior ?

I will put in comment an example of working code regardless you have an oracle db or a connexion setup

**Comment by fl0l-gouze** [comment]
Here is the code that can reproduce (but with more verbose and less intent) without having any oracle db or connexion setup : 
``` 
       [Timeout(10000)] //10s timeout
        [Test]
        public void PublicNunitTimeoutSqlCommandTest()
        {

            //any bad connection strin that respect format of System.Data.OracleClient.OracleConnection
            var badConnectionString = "DataSource=(DESCRIPTION =" +
                "(ADDRESS = (PROTOCOL=TCP)(HOST=urHost)(PORT=urPort)) " +
                "(CONNECT_DATA=(SID=urOracleSID)));" +
                "User Id=urUsername;Password=urPassword;  ";

            using (var connection = new System.Data.OracleClient.OracleConnection(badConnectionString))
            {
                connection.Open(); //Will take 1 mins as default timeout
                Console.WriteLine("Will never reach here");
            }
        }
```

While using (Depreciated) OracleConnection from  System.Data.OracleClient Version 4.0, Targeting .NetFramework 4.8 & Nunit3testdapater/4.4.2

While this is an example, i'm almost certains we had the same issue when querying external api so issue may not be restricted to OracleClient

**Comment by OsirisTerje** [comment]
I think I need you to fix the repro,  I made one based on what your wrote above, but it doesn't work:
![image](https://user-images.githubusercontent.com/203432/235228292-28822860-c7a0-41c7-b19e-50fa0492a42f.png)

The repro is here:  https://github.com/nunit/nunit.issues/tree/main/Issue4371

Please correct it so that it works.  I am no Oracle specialist, so have probably chosen the wrong package.

**Comment by manfred-brands** [comment]
@fl0l-gouze I presume you are using .net (core) and not .net framework.
The `TimeOut` attribute doesn't stop your code as there is no way to do so in later versions of .net. 
See #4021 for more information.

**Comment by fl0l-gouze** [comment]
We are using .net framework 4.8

I'm currently with ilimted acces to a workstation but I (or one of my collegue) will try to provide a full .sln soon

**Comment by OsirisTerje** [comment]
@fl0l-gouze Still an issue or can we close it?
