### ISSUE TITLE
Add support for Test Cancellation

### ISSUE THREAD

**Issue by manfred-brands** [nunit/nunit#4385]
This is to augment the existing TimeoutAttribute
The latter which has problems on .NET Core version of NUnit #4021

**Comment by goblinmaks** [comment]
@manfred-brands Have chance it to be merged as soonest time ?

**Comment by manfred-brands** [comment]
@goblinmaks I have managed to fix the issues I had under Linux/MacOS (using Mono) and marked the PR as ready for review.
