### ISSUE TITLE
how to set Custome ITestListener

### ISSUE THREAD

**Issue by ShaoHans** [nunit/nunit#4393]
I used NUnit 3.13.3，and implementation the ITestListener interface that can listen cancel event, how can i inject my custome TestListener ? The TestExecutionContext.CurrentContext cannot get Listener object , because it was internal type

**Comment by OsirisTerje** [comment]
This is an engine extension point, described here:  https://docs.nunit.org/articles/nunit-engine/extensions/creating-extensions/Event-Listeners.html   
You have to install that extension as an .addins file.
