### ISSUE TITLE
Explicit test fixture not found by dotnet test --filter

### ISSUE THREAD

**Issue by mrafnadeem-apimatic** [nunit/nunit#4403]
I have a test fixture that is marked as `[Explicit]` in NUnit 3, which means it won't be run unless specified. The test runs fine if I specify it using the `nunit-console` application but when I use `dotnet test --filter`, it can't find the test at all.

For example, if I have a test fixture like this:
```csharp
using NUnit.Framework;

namespace MyTests
{
    [TestFixture, Explicit]
    public class ExplicitTests
    {
        [Test]
        public void TestSomething()
        {
        // some code
        }
    }
}
```
And I run `nunit-console MyTests.dll --test=MyTests.ExplicitTests`, it works as expected. But if I run `dotnet test MyTests.csproj --filter MyTests`, it says `No test matches the given testcase filter`. I get the same behaviour regardless of whether I use TestCategory or Name or a FullyQualifiedName.

[According to the NUnit documentation](https://docs.nunit.org/articles/nunit/writing-tests/attributes/explicit.html), an explicit test or fixture will be run if it is selected by name or if it is included by use of a filter. A not filter, which excludes certain tests, is not treated as an explicit selection and never causes an explicit test to be run. All other filters are considered to explicitly select the tests that they match.

Is this a bug or am I missing something? How can I run an explicit test fixture using `dotnet test --filter`?

**Comment by OsirisTerje** [comment]
If you go to https://github.com/nunit/nunit3-vs-adapter.issues/tree/master/Issue912 and run that with 
`dotnet test  --filter Test1`
you should get the following response  (it is a failing test)
![image](https://github.com/nunit/nunit/assets/203432/23c13e1a-d856-4c49-8851-fd5c52c96dc2)

The different commands for dotnet test using NUnit are also described here:  https://learn.microsoft.com/en-us/dotnet/core/testing/selective-unit-tests?pivots=nunit

Ensure you have the latest NUnit adapter, at time of writing that is version 4.5.0.  

Also, you can filter on class or method, but on namespace. 

I hope this helps :-) 

PS:  If it still doesn't work, please upload a sample repro project.
