### ISSUE TITLE
upgrade from nunit 2.7.1 to nunit 3

### ISSUE THREAD

**Issue by MohammadNsr** [nunit/nunit#4405]
i'am upgrading my test project form nunit 2.7.1 to the actual version of nunit 3.
i have some question to the best practices of testrunner.
in the old project with nunit 2.7.1 i created the testrunner then chose the test class in the test package as follows:

    //////some code before that
    string testClass = "myTest";
    TestPackage package;
    ProcessModel processModel = ProcessModel.Default;
    RuntimeFramework framework = RuntimeFramework.CurrentFramework;
    string packageName = Assembly.GetExecutingAssembly().Location;
    package = new TestPackage(packageName);
    // here i assigned the test to be done
    package.TestName = testClass;
           
    NUnit.Core.TestRunner testRunner = new 
    InProcessTestRunnerFactory().MakeTestRunner(package);
    testRunner.Load(package);
    try{
       if (testRunner.Test == null)
        {
          testRunner.Unload();
          Console.Error.WriteLine("Unable to locate fixture {0}", testClass);
          return null;
        }

       MyEventListener collector = new MyEventListener();
       TestResult result = null;
       string savedDirectory = Environment.CurrentDirectory;
       try
       {
          result = testRunner.Run(collector, TestFilter.Empty, true, LoggingThreshold.Info);
       }

now in the nuunit 3: according to the documentation i can create testrunner like the following:

    // Get an interface to the engine
    ITestEngine engine = TestEngineActivator.CreateInstance();
    // Create a simple test package - one assembly, no special settings
    TestPackage package = new TestPackage("my.test.assembly.dll");
    // Get a runner for the test package
    ITestRunner runner = engine.GetRunner(package);
    // Run all the tests in the assembly
    XmlNode testResult = runner.Run(listener: null, TestFilter.Empty);
how can i assign the "testclass" to the testrunner in nunit 3? only with a filter like follows?

    XmlNode RunTest(string testClass)
    {
          string packageName = Assembly.GetExecutingAssembly().Location;
          TestPackage package = new TestPackage(packageName);
          ITestEngine engine = TestEngineActivator.CreateInstance();
          ITestRunner testRunner = engine.GetRunner(package);
          
          ITestFilterService filterService = engine.Services.GetService<ITestFilterService>();
          ITestFilterBuilder builder = filterService.GetTestFilterBuilder();
          builder.AddTest(testClass);
          NUnit.Engine.TestFilter testFilter = builder.GetFilter();
           try
          { 
	      MyEventListener collector =  new MyEventListener();
              XmlNode result = null;
              result = testRunner.Run(collector, testFilter);
              return result;
          }
          finally
          {
              testRunner.Unload();
          }
    }

i want the testrunner only to run one testclass each time.

the second question is:
how to convert the testReuslt (from type XmlNode) to suitable datatype like the TestResult which is in the namespace NUnit.Framework.Internal?

**Comment by OsirisTerje** [comment]
None from the team have responded to this.  @MohammadNsr Did you figure it out from the source code?

Unsure why you need to create your own runner, instead of using standard `dotnet test`.

**Comment by MohammadNsr** [comment]
> Unsure why you need to create your own runner, instead of using standard `dotnet test`.
it is an old project, where we create a test binary and execute on several machines. so i need to upgrade it and use the same approach as the existing one now.

**Comment by OsirisTerje** [comment]
Then you could consider using NUnitLite as your runner.

There are a lot of changes between 2.7 and 3, and trying to upgrade without changing the runner you use may be futile.  
The best approach if you go that route is to look through the source code, and also compare it with the 2.7, so that you see where the breaks are.  
You could also look at the NUnit3TestAdapter code, in the NUnitEngineAdapter folder, where you can see how it is done there.

**Comment by MohammadNsr** [comment]
i would leave the tag awaiting:contributer. cause there must be others like me who write their own runner and this will be helpful for them, if the developers of nunit have other ideas.

**Comment by OsirisTerje** [comment]
We use the tags for organizing the task lists :-), so not so good to leave it "open".   
You can edit the title, and add e.g. something like "custom runner implementation: " +++ what there is now. That should pinpoint others to what this is about.

And, btw, did you get it working with the adapter solution code ?

**Comment by MohammadNsr** [comment]
>And, btw, did you get it working with the adapter solution code ?
>You could also look at the NUnit3TestAdapter code, in the NUnitEngineAdapter folder, where you can see how it is done there.

Do you mean this here:
https://github.com/nunit/nunit3-vs-adapter/tree/master/src/NUnitTestAdapter
i took a look at it and its complexity is more than what i need in my old project
