### ISSUE TITLE
Why does NUnit lose its SynchronizationContext after await?

### ISSUE THREAD

**Issue by awaescher** [nunit/nunit#4407]
I have written an unit test which goes like this and I wonder why the test loses its `SynchronizationContext` after the first async method is awaited.

```
[Test]
public async Task Test_Keeps_SynchronizationContext()
{
    SynchronizationContext.Current.Should().NotBeNull(); // OK
    await Task.Delay(1).ConfigureAwait(true);
    SynchronizationContext.Current.Should().NotBeNull(); // FAIL
}
```

Tested with NUnit 3.13.3 on .NET 7.0

**Comment by awaescher** [comment]
I just found out that this works as expected if I use a STA apartment.
Feel free to close this issue if this is expected.

**Comment by jnm2** [comment]
Yes, this is expected. The behavior is not different from how an async method works in a console app.
