### ISSUE TITLE
nunit console is slower than resharper test explorer

### ISSUE THREAD

**Issue by WindingWinter** [nunit/nunit#4408]
I've something that is similar to #480. 

On exactly the same assembly and same test method, nunit can take twice as much time as the resharper test explorer quite consistently. And I've already ensured that the time is taken to measure the time spent **in the actual test,** like this

```
        [Test]
        [Category("Flaky")]
        public void RunLongOperation()
        {
            var stopWatch = new Stopwatch();
            stopWatch.Start();
            SimulateLongOperationAsync();

            stopWatch.Stop();
            TestContext.WriteLine($"{nameof(RunLongOperation)}, {stopWatch.ElapsedMilliseconds / 1000.0}");
        }
```

And I'll compare the output.

This is how I call the nunit console:

`call  "%NunitConsole%\nunit3-console.exe" "%slnFile%" /config:Debug --skipnontestassemblies --result="%testresultxml%"  --where "cat=Flaky"  --timeout=300000 > "%testresulttxt%"`

I'm aware that the setup or tear down time can contribute to the variance, that's why I use StopWatch only on the "meat" operation. So this case can't be due to the setup or teardown, I must conclude that nunit console affects the actual application running (?).

Any ideas?

**Comment by mikkelbu** [comment]
It is hard to tell from the given information :). Some questions:
* Which version of the NUnit Console (and how was it installed) and which version of Resharper?
* When you say "twice as much time" which granularity are we taking about. Is it 100ms vs 200ms or is it more 10 seconds vs 20 seconds?
* When tests are run in Resharper are they also running in Debug like the call above?
* Can you profile the test runs to see what takes more time in `SimulateLongOperationAsync` when run via NUnit Console compared against Resharper?
