### ISSUE TITLE
Move classic asserts into its own project 

### ISSUE THREAD

**Issue by OsirisTerje** [nunit/nunit#4416]
It should subsequentially be released as its own package, but we keep it in the framework repo and solution until it is worked out.

See details of the discussion here https://github.com/nunit/nunit/issues/3325#issuecomment-1629414362  and the following comments after that.

**Comment by OsirisTerje** [comment]
Started moving classic asserts over into its own project,  see #4417

**Comment by OsirisTerje** [comment]
@jnm2 @stevenaw @manfred-brands @mikkelbu 

Are the Assert.Throws part of the classic asserts?   They are used all over the nunit space, and just a few places where I see the new Assert.That(xxx,Does.Throw  syntax.  They also contain their own code, so not just redirecting to the constraint model. 
Also, there is no Analyzer trigger on the use if it (@mikkelbu @manfred-brands ), is that because it is not regarded as classic/legacy or just because the analyzer haven't got to it yet?

**Comment by manfred-brands** [comment]
@OsirisTerje Good question.

The analyzer is virtually impossible to make for the difficult cases where the return value of `Assert.Throws` is used. It might just be checking the Message which could be converted if we can detect it. It could check way more and in those cases there is no new equivalent I know of. Something like: `Assert.That(..., Throws.InstanceOf<SomeException>().Where(ex => ex.NonStandardProperty == ...))`. If we add that generic case, an analyzer rule could possible be created.
