### ISSUE TITLE
[OneTimeSetUp] is invoked multiple times on derived classes

### ISSUE THREAD

**Issue by RenderMichael** [nunit/nunit#4418]
Repro:
``` csharp
public class Base
{
    protected static int invokedCount = 0;
    [OneTimeSetUp]
    public void Setup()
    {
        invokedCount++;
    }

    [Test]
    public void Test1()
    {
        TestContext.Out.WriteLine("Base test. Set up: " + invokedCount);
    }
}

public class Derived1 : Base
{
    [Test]
    public void Derived1Test()
    {
        TestContext.Out.WriteLine("Derived1 test. Set up: " + invokedCount);
    }
}

public class Derived2 : Base
{
    [Test]
    public void Derived2Test()
    {
        TestContext.Out.WriteLine("Derived2 test. Set up: " + invokedCount);
    }
}
```
output:
```
Base test. Set up: 1

Derived1 test. Set up: 2

Base test. Set up: 2

Derived2 test. Set up: 3

Base test. Set up: 3
```

Maybe there can be some attribute to control this? Maybe `[OneTimeSetUp(ApplyToDerived = true)]`?

**Comment by OsirisTerje** [comment]
It is actually correct, you have 3 test instances that starts up, and you get the OneTimeSetup invoked 3 times:
<img width="232" alt="image" src="https://github.com/nunit/nunit/assets/203432/5d52d123-4af9-4d12-bf6c-32571ec56632">
The class Base is also a concrete class, and will also be invoked. 

However, if you don't want that, you can just make it abstract, and then it will only be invoked twice, once for each of the derived classes.

If you want to have something that is only invoked once for all instances, then you can use a SetupFixture.
