### ISSUE TITLE
Add --stoponerror option back to NUnit-console

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#442]
The NUnit 2.6 --stoponerror option should be added to NUnit 3.0. There may be some commented-out code in the console runner for implementing this. If not, check NUnit 2.6.4 source.

**Comment by oznetmaster** [comment]
It would seem this should be in nunitlite.runner as well?

**Comment by CharliePoole** [comment]
Given that it's easy to do, I would say yes.

**Comment by CharliePoole** [comment]
Implementation notes:

1. The nunit-console and nunitlite command-lines both support the option.
2. NUnitLite does not pack this option into the settings it passes to the framework.
3. The console runner places the appropriate setting into the package.
4. The engine driver passes the package settings to the framework.
5. The framework uses the settings to set a flag in the TestExecutionContext
6. The TestExecutionContext setting is currently ignored when tests are run.
7. The nunit-console report displays a message when the test is stopped due to a single error.

We need to fix item 6 for nunit-console to work. For nunitlite, both 2 and 6 must be fixed and a message should be added to the report output.
