### ISSUE TITLE
Fix null message in internal static string? ExtendedMessage(string methodName, string? message, string actualExpression, string constraintExpression)

### ISSUE THREAD

**Issue by OsirisTerje** [nunit/nunit#4432]
Ref comment in PR #4430 

> The message comes from the _getExceptionMessageoverloads which are declared asFunc<string?>. Also there are some NUnit tests (e.g. LifeCycleAttributeTest) that pass in result.Messagewhich is also declaredstring?`.
If we want to change all that, I would do that in a separate PR.

**Comment by manfred-brands** [comment]
@OsirisTerje I started in this.

**Comment by OsirisTerje** [comment]
@manfred-brands Awesome!
