### ISSUE TITLE
No tests found in large test assembly on linux, ~2500 found on windows.

### ISSUE THREAD

**Issue by mjkkirschner** [nunit/nunit#4439]
please see this issue, the vstest folks suggested that the underlying issue was with nunit.
https://github.com/microsoft/vstest/issues/4330

I have recently tried with simpler test assemblies, as we have now migrated those to .net6 and those work under linux as well, so I assume it's something to do with this large test assembly.

Any hints at tracing this issue would be appreciated.

I have removed `dotnet test` from the issue and tested by directly calling `dotnet nunit.console.dll DynamoCoreTests.dll`

**Comment by OsirisTerje** [comment]
Looking at the logs there are exceptions about failed loading of several MS assemblies.  I assume those errors are the same on windows and linux?

Can you add a .runsettings file, and enable verbosity = 5 and also enable the dumps for both discovery and execution?

**Comment by mikkelbu** [comment]
Closing this as we have not heard back from the reporter for quite a while. If new information is supplied, then we can reopen the issue.

**Comment by avidit** [comment]
Hi @OsirisTerje We still have this issue. I am attaching .runsettings and diag file if that helps

[test.runsettings.xml](https://github.com/user-attachments/files/22910334/test.runsettings.xml)
[test.log](https://github.com/user-attachments/files/22910333/test.log)
[test.host.25-10-14_13-55-21_47352_6.log](https://github.com/user-attachments/files/22910332/test.host.25-10-14_13-55-21_47352_6.log)

**Comment by OsirisTerje** [comment]
The log says:

> Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

There are a lot of these.  It may be that the Linux server doesnt have this, but the Windows do (just guessing).  But anyway, if you add a packagereference to this in your test project, does it then work better ?

There are also:

> TpTrace Information: 0 : 38476, 1, 2025/10/14, 13:55:19.542, 2161899608763077, vstest.console.dll, Failed to load assembly Microsoft.VisualStudio.TestPlatform.Fakes, Version=17.0.0.0, Culture=neutral. Reason:System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.Fakes, Version=17.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

> File name: 'Microsoft.VisualStudio.TestPlatform.Fakes, Version=17.0.0.0, Culture=neutral, PublicKeyToken=null'

   

> at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)

  

>  at System.Reflection.Assembly.Load(AssemblyName assemblyRef)

   

> at Microsoft.VisualStudio.TestPlatform.Common.Utilities.FakesUtilities.LoadTestPlatformAssembly() in /__w/1/s/src/vstest/src/Microsoft.TestPlatform.Common/Utilities/FakesUtilities.cs:line 273

You can use the same trick, but not sure if this is used at all in NUnit.  

I also see a lof of warnings about Verbosity in the runsettings file there.

**Comment by avidit** [comment]
Hi @OsirisTerje I did add the missing references, but no luck
```xml
<PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="9.0.10" />
<PackageReference Include="Microsoft.QualityTools.Testing.Fakes" Version="18.1.1" />
```

**Comment by OsirisTerje** [comment]
@avidit Did you get the same errors ?

**Comment by avidit** [comment]
I get the same errors. But I saw that I get the same missing assembly errors while running the test on windows as well.

**Comment by OsirisTerje** [comment]
None of these are used by NUnit.  So I don't get where the requests for those come from.  Have you searched your codebase completely ?  Looked at the dependency tree  (xxxx.deps.json) ?
