### ISSUE TITLE
NUnit 3.14 Release 

### ISSUE THREAD

**Issue by stevenaw** [nunit/nunit#4447]
Momentum is building on v4 changes so we should probably consider getting a final v3.14 out before too long. There's a handful of unreleased bugfixes and a feature or two there. There's also been a few community requests for a release in some of the unreleased issues over the past months.

@nunit/framework-team Is there anything else we should aim to include that's not yet done?

@rprouse @OsirisTerje I'm a little unclear who normally drives these releases. Would it make the most sense to be done by either of you, or is it something anyone of the framework team could do once we decide it's time?

**Comment by rprouse** [comment]
I could do a release if everything is ready. Is there anything that I should wait for?

**Comment by stevenaw** [comment]
Thanks @rprouse 
Nothing pending on my end. I don't see any open issues in the milestone and no open bugs jump out of importance to me.
There are a few pending documentation updates for new features, but nothing that should block a framework release.
- https://github.com/nunit/docs/issues/778
- https://github.com/nunit/docs/issues/756

@manfred-brands FYI that I see one open PR of yours pointing to the `v3.13-dev` branch (https://github.com/nunit/nunit/pull/4025). Is that or anything else something you want in a 3.x release?

**Comment by manfred-brands** [comment]
@stevenaw That PR is for a feature that should wait for NUnit 4.0

**Comment by OsirisTerje** [comment]
@rprouse Awesome if you could get 3.14 out.  We need to do the release notes.  I started on the 4.0 some months ago, took me a couple of evenings.  Should be less for the 3.14 but still.  I can start that now, but the release can go out without it being completely ready.

**Comment by OsirisTerje** [comment]
About who does the release, as long as we agree it is due time, I don't think it matters.  Anyone on the team could do it.  There are always some stuff to be done wrt to releases, actually I don't know if there is a checklist for the framework (@rob ?).  If not, we should make one, so that it's easier for anyone later to do a release.

**Comment by rprouse** [comment]
This is still somewhat up to date, https://docs.nunit.org/articles/developer-info/Packaging-the-Framework.html

**Comment by OsirisTerje** [comment]
Perhaps time now to do a 3.14 release ?

**Comment by OsirisTerje** [comment]
Then version 3.14. is released today, Nov 3rd. in the year 2023.
