### ISSUE TITLE
Test build are extremely slow

### ISSUE THREAD

**Issue by RapGeneral** [nunit/nunit#4449]
I am experiencing extremely slow test builds (50-60 seconds) when I stop debugging of a test.
The flow is as:
I start debugging a test.
I press the stop debug button or just proceed with the test.
The next build takes from 10 to 60 seconds seconds.
Also the sole act of stopping the debugging seems to make visual studio lag, as I cant navigate trough the code, for example, for a solid minute as well.
The processor usage goes up to 30% when starting the test, but during the stop is down to 2-3%.
I have enough ram (32GB) and AMD Ryzen 7 3800X, so its not a hardware issue.

So far, I have tried:
Updating visual studio to latest version.
Uninstall and install visual studio.

I have two accounts on my PC, and it happens for both of them.
Versions are:
NUnit - 3.13.3
NUnit3TestAdapter - 4.3.1

**Comment by stevenaw** [comment]
Thanks @RapGeneral  There could be a lot of things at play here. 

Do you have any extensions installed on Visual Studio which could be interfering with the run? Have you tried running your tests from the command line using `dotnet test` to rule out any other Visual Studio-related factors such as extensions, etc? Both `dotnet test` and Visual Studio itself would make use of the same NUnit and NUnit3TestAdapter packages referenced by your test project.

**Comment by stevenaw** [comment]
Oh, also, are you able to share a simple code repro of the test suite where you see this behaviour?

**Comment by OsirisTerje** [comment]
This seems to be a Visual Studio issue. 
Would suggest you raise this on the VS dev support.

**Comment by RapGeneral** [comment]
Although the issue is closed, thanks you both for your input.
@stevenaw no extensions, nothing. Literally every project with integration tests is affected, only on this PC. The same project I run in another computer (lets say my work laptop) is absolutely fine.
Visual studio is clean, no extensions.
The same tests run in github actions absolutely fine, no problems there.
I didnt think of running `dotnet test`, and now that I did, it runs without any problems.
I was suspecting the runner, but it seems thats not the case.
Will raise this with Visual Studio as @OsirisTerje suggested.

**Comment by manfred-brands** [comment]
As it runs fine on your work laptop, is your PC underspec'd? How much memory do you have and how much is free.

**Comment by RapGeneral** [comment]
@manfred-brands  Answering a bit late as I come across this now. No, my PC is not underspec'd. I mentioned this in the original post.
Comparing it with the laptop, the PC is ~2 times faster.
