### ISSUE TITLE
Add missing [DoesNotReturn] annotations for Assert.Fail

### ISSUE THREAD

**Issue by KL-Sven** [nunit/nunit#4451]
Like Assert.Pass, Ignore and Inconclusive from #3958, Assert.Fail does never return and should be annotated.

**Comment by manfred-brands** [comment]
According to the [XML documentation](https://github.com/nunit/nunit/blob/3e514156aa0631f9f1aeb183d2b7a19961b81561/src/NUnitFramework/framework/Assert.cs#L115-L116) it can return if used inside an `Assert.Multiple`.

**Comment by KL-Sven** [comment]
Thank you for your example. The 2nd statement is executed and I was alread aware of this. My point is, `Assert.Fail` has no knowledge of `Assert.Multiple`. There is no special behaviour of `Assert.Fail` when inside `Assert.Multiple`. You can always write your own try/catch around `Assert.Fail`. That doesn't make `[DoesNotReturn]` attribute wrong.

The motivation here is that the flow analysis for nullable reference types fails without this annotation. Consider this code:

```
public class MyResponse
{
    public MyResponse(string data)
    {
        Success = true;
        Data = data;
    }

    public MyResponse()
    {
        Success = false;
    }

    [MemberNotNullWhen(true, nameof(Data))]
    public bool Success { get; }

    public string? Data { get; }

}
```
```
var response = new MyResponse("Successful response");
if(response.Success == false)
{
    Assert.Fail();
}

var data = response.Data // <- code is unreachable, but code analysis is warning here.
```

**Comment by manfred-brands** [comment]
You are right that `Assert.Fail` doesn't know about `Assert.Multiple`, but my point is that if your code is run inside such, the code IS reachable.

Having said that, we had similar discussions around the `Assert.NotNull` and its equivalents. I managed to suppress the compiler warnings for using variables tested for null with a `DiagnosticSuppressor` in the nunit.analyzers. Maybe this is another candidate. However flow control analysis through conditional statements is likely beyond what the analyzer can do and is duplicating what the compiler does.

`Analyzer.Multiple` might have been a good idea to get multiple independent test to run, instead of failing on the first, but for these kind of things it is more of a limitation.

Maybe `Assert.Fail` should behave like the others and never continue.

**Comment by manfred-brands** [comment]
Offtopic
We used to be a R# house, but dropped it. Besides it really slowing down VS, with the new nullability and roslyn analyzer most of what it gave us now came for free with dotnet. We are still slowly removing JetBrains.Annotations everywhere.
/Offtopic

**Comment by OsirisTerje** [comment]
I can't see any good reason for the Assert.Fail to be used in a Multiple.  It explicitly tells that you want the test to Fail, and there should not be any ifs or buts around that.

**Comment by manfred-brands** [comment]
@OsirisTerje Do we need to check with developers who originally made that distinction or can we change it for Version 4?

**Comment by OsirisTerje** [comment]
I believe we can change it for v4.  It may crash for some people who have used Multiple over more complex test code.  But that is not how a Multiple should be used.  So I think we're fine with that.  They would have to replace that with an exception instead.

**Comment by jnm2** [comment]
> I think the documentation is misleading. `Assert.Fail` does always throw an exception. `Assert.Multiple` catches all exceptions. But this is independent to the assert inside.

> My point is, `Assert.Fail` has no knowledge of `Assert.Multiple`. There is no special behaviour of `Assert.Fail` when inside `Assert.Multiple`.

These are both incorrect. `Assert.Fail` changes behavior when it runs inside a callback executed by `Assert.Multiple` so that it does not throw. `Assert.Fail` delegates to this method:

https://github.com/nunit/nunit/blob/3e514156aa0631f9f1aeb183d2b7a19961b81561/src/NUnitFramework/framework/Assert.cs#L321-L323

**Comment by OsirisTerje** [comment]
@jnm2 Disregarding how it works.  Do you agree that it doesn't make sense semantically?  

I can't see any reason for doing an Assert.Fail inside a Multiple block.   I am then disregarding code that have a conditional first, and based on that result do an Assert.Fail. Those are really asserts on that conditional.   
Even our own example in the documentation:
`public void AssertStringContains(string expected, string actual, string message)
{
    if (actual.IndexOf(expected) < 0)
        Assert.Fail(message);
}`
could just be rewritten as
`public void AssertStringContains(string expected, string actual, string message)
{
    Assert.That(actual.IndexOf(expected), Is.GreaterThanOrEqualTo(0),message);
}`
The latter could obviously be used in a Multiple, so if we say that the example with the Fail is ok, then it also has to be able to run in a Multiple.    
However, if we say that Assert.Fail is reserved for those rare cases that you actually need to fail something, then it is an absolute statement, and would have no meaning in a Multiple.

**Comment by jnm2** [comment]
@OsirisTerje I've refactored away from `Assert.That` to `if` + `Assert.Fail` intentionally for clarity, and there could also be situations where it's harder to get away from `if`. Imagine it's one of three `switch` cases, or imagine if you have Assert.Fail wired up in an event handler for the object under test (or wired up to a mocked interface call).

If we would change Assert.Fail, it would break people's existing multiple-assert tests if anyone used it.

**Comment by OsirisTerje** [comment]
Good points.  Then we can't add any DoesNotReturn. 

PS: As I said, I'm "opiniated" the other way, but I see your point, so we then should leave it as is.

**Comment by stevenaw** [comment]
FWIW I agree with leaving the existing behaviour in place.

Occasionally there are misunderstandings with `Assert.Multiple()` and I suspect it could complicate that further to allow some assertions to exit early and others to not. I agree it's likely that a common scenario for `Assert.Fail()` to appear within an `Assert.Multiple()` is if it were within a conditional, in which case if someone did desire "return early" semantics, they could do just that by adding a `return` after the `Assert.Fail()` call. In other words, in the case of `Assert.Fail()` within an `Assert.Multiple()`, I would suspect it's easier to opt into early exit when it's not the default behaviour than it would be to opt out of it if it were the default. I could see the current behaviour being helpful if one wanted to accumulate a list of failures to report at-once at the end, which is a use case for Assert.Multiple().


After a bit of digging I found the issue where much of this behaviour was originally defined (https://github.com/nunit/nunit/issues/1907, PR https://github.com/nunit/nunit/pull/1909). The link to the Multiple Assert spec doesn't appear to work anymore but it seems `Assert.Fail()` was special cased at the time to not exit early - contrasting with `Assert.Pass()` which was instead disallowed entirely from Assert.Multiple. Without seeing the rationale, I could imagine it may've been done that way at the time to allow easy failure accumulation for the "if + assert.fail" pattern @jnm2 described.

**Comment by manfred-brands** [comment]
@stevenaw The mentioned issue is about an early exit out of `Assert.Multiple`, but the PR then basically makes it impossible.
Even thought the spec might have changed, the PR didn't supply a solution.

The wiki was moved to [docs.nunit.org](https://docs.nunit.org/articles/nunit/writing-tests/assertions/multiple-asserts.html)
Although that is not listed under [Specifications](https://docs.nunit.org/articles/nunit/technical-notes/nunit-internals/specs/Specifications.html), it does mention `Assert.Fail()` behavior.

The only way to exit an `Assert.Multiple` seems to be throwing an exception, but the documentation considers that an error in the code. Maybe we need and `Assert.MultipleExit()` method to make it part of the API.

**Comment by stevenaw** [comment]
Oh thanks @manfred-brands ! Perhaps in this case the spec _became_ the documentation. I mostly dug up the issue in the hope of trying to voice the developers who originally made the distinction, but the exact rationale doesn't seem to have been explicitly stated. My understanding from the original issue was that `Assert.Pass()`, etc early exit in that subsequent assertions aren't evaluated, though it does this by failing fast and reporting an error.

On the note of manually exiting early, a more limited option would be an explicit `return` statement, though it is understandably limited to being directly in the `Assert.Multiple` and not further down the stack in a called helper function.

```csharp
Assert.Multiple(() =>
{
    if (true)
    {
        Assert.Fail("Now you see me");
        return;
    }

    Assert.Fail("Now you don't");
});
```

Like you, this issue has also made me curious about allowing a way to better control this "early out" behaviour if it were desired. 😄 .  I hadn't considered a new assert and thought instead potentially adding a parameter to `Assert.Multiple()` to specify a `maxFailureCount` before the `Assert.Multiple` exits. I think each idea could have its merits.

```csharp
Assert.Multiple(() => {
  Assert.Fail("Now you see me");
  Assert.Fail("Now you see me");
  Assert.Fail("Now you don't");
}, maxFailureCount: 2);
```

**Comment by manfred-brands** [comment]
Personally, I don't like _maxFailureCount_. Just when you think you fixed all failures, you get another. It is the same when not using `Assert.Multiple`. Developers only fix the first error to then find out that the next `Assert` also fails.

On the other hand, if `Asserts` were called in a loop, we don't want hundreds of the same errors either.
So it could be beneficial there.

**Comment by OsirisTerje** [comment]
I also don't like the *maxFailureCount*, it seems like a technical solution and not a declarative one.  It would prefer something like @manfred-brands suggested with a  *Assert.MultipleExit* or Assert.FailInMultiple* or something like that.

**Comment by stevenaw** [comment]
Good points! I could also see a complex multiple block potentially hitting such a limit at different times.
I like the idea of parameterizing an existing API myself if it makes sense, but if that's just a preference. It _would_ be trickier to ensure the parameter also doesn't add confusion if used outside of a multiple block.

Another option for a new API if we go that route could be a `Assert.FailFast()` method, which parallels the naming of [`Environment.FailFast()`](https://learn.microsoft.com/en-us/dotnet/api/system.environment.failfast?view=net-7.0). Outside of a multiple, such a method would act like `Assert.Fail()` but inside it would exit the block immediately

**Comment by OsirisTerje** [comment]
That makes sense!  Good name too!

But none of this solves the issue of Assert.Fail and the DoesNotReturn, so I guess we have to decline this, but we should create a new issue for FailFast

**Comment by stevenaw** [comment]
I've made https://github.com/nunit/nunit/issues/4461
I realized while writing it up that `FailFast()` is nifty but would make sense to cause the multiple block to fail... unlike what I suspect @manfred-brands had in mind with `Assert.MultipleExit()` so I've tried to keep the discussion open
