### ISSUE TITLE
NUnitTestAssemblyRunner: Setting WorkDirectory seems not to be working 

### ISSUE THREAD

**Issue by i-m-luke** [nunit/nunit#4454]
I'm runnig tests from a custom test runner. During the tests I expect the working directory to match the directory of the current test assembly. According to the summary of the WorkDirectory constant (FrameworkPackageSettings class) this option should specify "_full path of the directory to be **used for work** and result files_". 

I use the Load method to load a test assembly and pass the settings options with the specified work directory to it. Here is the code I use:
```
            ITestAssemblyRunner runner = new NUnitTestAssemblyRunner(new DefaultTestAssemblyBuilder());

            string testAssemblyDirPath = @"TestAssembly\Dir\Path";
            Dictionary<string, object> settings = new Dictionary<string, object>()
            {                
                { FrameworkPackageSettings.WorkDirectory, testAssemblyDirPath }
            };
            runner.Load(Path.Combine(testAssemblyDirPath, "TestAssembly.dll"), settings);

            runner.Run(TestListener.NULL, TestFilter.Empty);  
```

When I run the test, I encounter errors caused by the working directory not matching the one specified in the settings.

I examined the NUnitTestAssemblyRunner class and discovered that there is no handling for the FrameworkPackageSettings.WorkDirectory option. The option is only used in the case of FrameworkController, but only for setting the path for a log file (InternalTrace) and not for work. Perhaps I don't fully comprehend the meaning "work" used in the description, but I assumed it referes to the working directory of a running test.

**Comment by OsirisTerje** [comment]
The WorkDirectory is documented here: https://docs.nunit.org/articles/vs-test-adapter/Tips-And-Tricks.html#workdirectory
It is the directory where outputfiles is to be stored, not the directory/ies where the running assemblies are.

**Comment by i-m-luke** [comment]
Thanks, now it's clear to me how/when to use the WorkDirectry option.
