### ISSUE TITLE
TaskCreationOptions.LongRunning and TimeoutAttribute

### ISSUE THREAD

**Issue by emphasis87** [nunit/nunit#4463]
I have trouble getting this code to work. I would expect the code to run indefinitely without [Timeout], but that does not work. The long running task is immediately returned when awaited. Moreover [Timeout] is completely ignored and the test runs for 20s. Can someone explain to me what I am doing wrong?

```csharp
using NUnit.Framework;
using System.Diagnostics;

public class TestFixture
{
    [Timeout(3000)]
    [Test]
    public async Task Test()
    {
        var task = Task.Factory.StartNew(
            Work,
            CancellationToken.None,
            TaskCreationOptions.LongRunning | TaskCreationOptions.AttachedToParent,
            TaskScheduler.Default);

        await Task.Delay(10000);

        await task;

        await Task.Delay(10000);
    }

    public static async Task Work()
    {
        var time = Stopwatch.GetTimestamp();
        while (true)
        {
            await Task.Delay(1000);
            Console.WriteLine($"{Stopwatch.GetElapsedTime(time)}");
        }
    }
}
```

**Comment by OsirisTerje** [comment]
First, see this comment https://github.com/nunit/nunit/issues/4371#issuecomment-1528649053  and issue #4021
> The TimeOut attribute doesn't stop your code as there is no way to do so in later versions of .net.

About using StartNew, see https://stackoverflow.com/questions/41788529/why-task-factory-startnew-returns-immediately-while-task-run-does-not 
Also see https://blog.stephencleary.com/2013/08/startnew-is-dangerous.html 

You should use Task.Run instead
