### ISSUE TITLE
Update cake version in build scripts

### ISSUE THREAD

**Issue by stevenaw** [nunit/nunit#4465]
There's a few draft PRs in progress right now that have had to upgrade cake in the build scripts as part of other changes. It might be nice to upgrade cake separately as part of this issue to make those and other future updates simpler

**Comment by OsirisTerje** [comment]
Do you mean update the version number seperately from the cake script? 
We could move over to use Gitversion.  It is used in the console repo.

**Comment by stevenaw** [comment]
Oh that's a good idea too, but different from what I'd been thinking. We currently use `dotnet-cake@1.1` in the framework build scripts but I think it's now on at least version 3.

https://github.com/nunit/nunit/blob/master/.config/dotnet-tools.json#L6

**Comment by manfred-brands** [comment]
I tried to update cake in order to get access to branch/pr information but to not much success. In the pr for GitHub NuGet packages I resorted to using git tags and git describe to make up a version number.

**Comment by stevenaw** [comment]
Appreciate it @manfred-brands !
Your PR had been part of why I thought it may be good to formally identify this in an issue. I suspected your upgrade may've been for those reasons and I figured that by calling out this need and addressing it (whether in existing PRs or a new dedicated one) could help us or others avoid the need for that debugging step when making future functional changes to the build.
