### ISSUE TITLE
Is there a way to create a nesting/Hierarcy of the tests created via TextCaseSource?

### ISSUE THREAD

**Issue by dcook-net** [nunit/nunit#4470]
Hi.

Not a feature request, just a question:

I've created a TestCaseSource that iterates over a file structure, which results in a nesting of tests like this in the test runner:
```

namespace
|_classname
   |_TestName
       |_TestCaseDataName-Car-scenario1    
       |_TestCaseDataName-Car-scenario2   
       |_TestCaseDataName-Car-scenario3
       |_TestCaseDataName-Van-scenario1    
       |_TestCaseDataName-Van-scenario2   
       |_TestCaseDataName-Van-scenario3
       |_ ...


```
I was wondering if there was a way that I could force the output of the testcases to look like this (or similar):
```

namespace
|_classname
   |_TestName
       |_Car
          |_scenario1    
          |_scenario2    
          |_scenario3
       |_Van    
          |_scenario1    
          |_scenario2    
          |_scenario3
       |_ ...

```
I was looking at [this page](https://docs.nunit.org/articles/nunit/running-tests/Template-Based-Test-Naming.html), but I'm not sure I understand what this is telling me.

**Comment by dcook-net** [comment]
Hmmm, interesting @manfred-brands what versions of which nunit packages are you using to get these results?
I've copied your example and give a very different output.
 
<img width="973" alt="Screenshot 2023-09-15 at 22 32 36" src="https://github.com/nunit/nunit/assets/4937727/3fef80f3-cfb0-4b45-994f-673bf8adda49">

**Comment by manfred-brands** [comment]
I use:
```xml
  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="Nunit3TestAdapter" Version="4.5.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.7.2" />
  </ItemGroup>
```

However, I downgraded all 3 versions and it made no difference.
I'm using VS 2022 version 17.7.4. and in TestExplorer there is a `Group By` button:
![image](https://github.com/nunit/nunit/assets/8655218/a8793617-3bba-4fdb-9c87-0c17b61cb6e4)
Mine is set to group as:
![image](https://github.com/nunit/nunit/assets/8655218/009ccdbb-6af5-4aff-a180-daf3e0e1f6e1)

If I untick `Class`, I no longer get the `Car` and `Van` nodes:
![image](https://github.com/nunit/nunit/assets/8655218/e9127f9e-3ffa-4f06-8849-f3e3f1500c86)

Note that if I change the capital `{M}` into `{m}` in the `SetName` calls, it looks even better:
![image](https://github.com/nunit/nunit/assets/8655218/72dc8b7d-460d-4fbe-a63e-99d6ac1bef7b)

You can drop the `{m}` completely, which result in:
![image](https://github.com/nunit/nunit/assets/8655218/414920e8-98a5-41d3-873c-27a88dad8fab)
Note that the actual method name is no longer shown.

**Comment by dcook-net** [comment]
Thanks @manfred-brands I've got this working now using Group By Category.
Using Rider, but it works the same way 👍🏻
