### ISSUE TITLE
Tests that infinite loop never display output

### ISSUE THREAD

**Issue by jamespicone** [nunit/nunit#4471]
If you run a test that enters an infinite loop (perhaps because of a bug) from the Visual Studio test explorer, any output from that test never shows up anywhere. This is extremely confusing, and it's difficult to even realise that that's what's happening; from the point of view of a user it just looks like test explorer is hung or something.

**Comment by stevenaw** [comment]
Thanks for the bug report @jamespicone 

Part of this is by-design as the NUnit framework currently buffers contents for the current test in memory. There's been a few discussions to change that in (https://github.com/nunit/nunit/issues/3336). Unfortunately, it would be a very involved and difficult fix which no one has picked up yet.

As far as the current state, while it wouldn't be possible for NUnit to actually _detect_ an infinite loop, there are a few options that could help:

- Support for a "progress" stream as well as an "error" stream writing out immediately was added here: https://github.com/nunit/nunit/pull/1536 meaning that `TestContext.Progress` and `TestContext.Error` could help here.
- If your tests are on .NET Framework, the `[Timeout]` attribute could also provide an upper bound for how long the test may run before forcibly stopping it.
- If your tests are on modern .NET then there are also plans to add support to cancel the test after a certain amount of time via a new `CancelAfter` attribute in an upcoming v4 release, though it may still be a ways in the future until it comes out. The PR tracking that particular feature is https://github.com/nunit/nunit/issues/4385

For the first option, it would also be up to the Visual Studio runner to display it. I've just tested it now and it while it looks like it doesn't _immediately_ display, it does queue it up for the runner to read from when it's ready. Which may help for your case if a runner list Visual Studio only polls periodically

**Comment by jamespicone** [comment]
Thanks for the reply Steven.

In my specific use-case I've been able to switch over to TestContext.Progress for the logging. The specific use-case is a mod for a Unity-based card game; the tests that have been most problematic play a random game just to try and find crashes or exceptions that other tests don't catch. It's a bit more of a nuisance if the random tests fail with no obvious indication what they were doing; they're currently not seeded (which is probably something I need to look into).

I realise detection isn't really possible; part of the reason I put this issue up is because I found it difficult to find information about what was even going on when the issue showed up. Seems useful for you to have an issue explicitly tracking the problem that buffering of test output causes for naively-written tests. I do realise it's to support parallel tests.

Is there any way for nunit to detect that tests aren't being run in parallel and not buffer console output in that case? Naive testers aren't likely to be running in parallel (I know I hadn't looked into the possibility).

**Comment by stevenaw** [comment]
Glad you found something that worked @jamespicone 🙂

Sorry it's a few days between replies for me right now. I've done a bit of digging. The `ParallelibleAttribute` works by [setting some flags on `TestExecutionContext.ParallelScope`](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Attributes/ParallelizableAttribute.cs#L77) for the framework to work with internally.  While `TestExecutionContext` is in the internal namespace, it should be alright for your purposes to code against it as it is exposed through the `IApplyToContext` interface which is itself defined as a [framework extensibility point](https://docs.nunit.org/articles/nunit/extending-nunit/IApplyToContext-Interface.html). This is also the interface which the `ParallelizableAttribute` implements internally to flip the flag.

So I'm wondering if perhaps you were to define a helper method like this for your case?

```csharp
// Extension method definition
public static bool IsRunningInParallel(this TestExecutionContext context) {
  return context.ParallelScope != ParallelScope.None;
}

// usage
if (TestContext.CurrentContext.IsRunningInParallel()) {
  // Parallel-specific behaviour
}
```
