### ISSUE TITLE
NUnit 4 - alpha/beta release

### ISSUE THREAD

**Issue by OsirisTerje** [nunit/nunit#4477]
We should now get out a NUnit 4 version.  I have been running a dev version in a development project for some time now, with no issues at all, with more than 1,000 tests of different types.    

In order to get it out, we need to do a few things:

- [x] Update release notes.  There is a start for an alpha version, stopping at issue #4149. Anything after that for milestone 4.0 and closed, should be added to the release notes.  
- [x] Also check the current list for any missing lower-numbered issues that are now set to 4.0, e.g. #4021 
- [x] There are some breaking changes, particularly the Legacy asserts. The documentation should be updated and organized to reflect that.
- [x] Some issues have milestone 3.14. Some of these may be backports, and should be in the release notes. We need to identify those. Others are fixed for 3.14, but should be up-ported to 4.0.

**Comment by agray** [comment]
Yes please. We need parallel tests fixed :)

**Comment by OsirisTerje** [comment]
NUnit 4.0.0-beta.1 is out.  Release notes https://docs.nunit.org/articles/nunit/release-notes/framework.html    Nuget package: https://www.nuget.org/packages/NUnit/4.0.0-beta.1

**Comment by agray** [comment]
Thanks Terje et al.

How many pre-releases are you planning on doing before it is a final
release?

Regards, Andrew

**Comment by OsirisTerje** [comment]
We need to see a significant number of downloads, and then hopefully not too many issues coming up.  
Significant:   >2000   , up to 10000 would be nice to see.  After 5 days now there are 650 downloads.

Since we do have some significant breaking changes, it would be nice to see some comments on them too, ref https://github.com/nunit/nunit/discussions/4485  , none so far.  It may be good, or it may be bad... ;-)

**Comment by agray** [comment]
Thanks Terje, I think a lot of people want it but they want the final
release rather than a pre-release.

Cheers,

Andrew

**Comment by OsirisTerje** [comment]
Absolutely, understand that.  But we're trying to avoid hotfixes for burning issues, and up to 10000 downloads is not much.  
If we have to fix multiple issues now, we will have another beta, if the number is low, we will go to the final release.  Don't expect more than a very few beta's,  would be nice if we could do with this one. 
Do you have any comments on the two breaking changes?  Will those be ok as is ?

**Comment by OsirisTerje** [comment]
Just to give you an idea, these are the alpha- and beta download numbers for the NUnit3TestAdapter, and I believe we could reach the goal number within a couple of weeks.  
![image](https://github.com/nunit/nunit/assets/203432/c4e9c920-81bd-4e51-b1e1-a41815e60158)

**Comment by agray** [comment]
I'll have to download and integrate and see how it effects my code base.

Probably be able to do that tomorrow.

If not tomorrow some time in the next week.
