### ISSUE TITLE
`Does.ContainKey()` throws an unintuitive exception for a null key

### ISSUE THREAD

**Issue by RenderMichael** [nunit/nunit#4481]
```csharp
Assert.That(new Dictionary<string, string>(), Does.ContainKey(null));
```
This throws the following exception
```
 System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.ArgumentNullException : Value cannot be null. (Parameter 'key')
```

It would be nice to unwrap this exception in here:
https://github.com/nunit/nunit/blob/32b83e7ca8b9f96bab09d319fbc0a3a0da166601/src/NUnitFramework/framework/Constraints/DictionaryContainsKeyConstraint.cs#L85-L88

to 
```csharp
if (method is not null)
{
    try
    {
        return (bool)method.Invoke(actual, new[] { Expected })!;
    }
    catch (TargetInvocationException ex)
    {
        ExceptionDispatchInfo.Throw(ex.InnerException!);
    }
}
```

**Comment by manfred-brands** [comment]
Thanks @RenderMichael for reporting.

There is already a wrapper method `Reflect.Invoke` that does this.
We need to find all places where `MethodInfo.Invoke` is called directly and change those.
One first glance I found about 14 places.

**Comment by RenderMichael** [comment]
@manfred-brands I tried that method out but the output I got was

```csharp
 Assert.That(caughtException, expression)
  Expected: <System.ArgumentNullException>
  But was:  <NUnit.Framework.Internal.NUnitException: Rethrown
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'key')
... rest of the stack trace
```

**Comment by manfred-brands** [comment]
@RenderMichael probably not. 

This method existed way before I joined the team.
There is also an `InvokeWithTransparentExceptions` which re-throws the `InnerException`, but that method doesn't expect parameters.
There are several places that catch `NUnitException` / `TargetInvocationException` and then get the `InnerException`.

Debugging it,  `Does.ContainKey` is indirectly called by `Reflect.InvokeMethod` already, but as it calls the `ContainsKey` also through reflection, the `InnerException` is actually another `TargetInvocationException`.
If I add a loop to unwrap the `InnerException` until it is no longer is an `TargetInvocationException`, I get the wanted error message:
![image](https://github.com/nunit/nunit/assets/8655218/0114fc26-634d-44e4-b1cb-bc602750b561)

However, when I write the test as:
```csharp
Assert.That(() => Assert.That(new Dictionary<string, string>(), Does.ContainKey(null!)),
            Throws.ArgumentNullException);
```

It fails as this is a place that doesn't unwrap the `TargetInvocationException` all the way.

I need to write it as:
```csharp
Assert.That(() => Assert.That(new Dictionary<string, string>(), Does.ContainKey(null!)),
            Throws.TargetInvocationException.With.InnerException.InstanceOf<ArgumentNullException>());
```

@nunit/framework-team Should we update all code expecting an `TargetInvocationExpression` to unwrap it as far as possible?
Or should we find `.Invoke` calls in specific Constraints and unwrap at that location?

@RenderMichael Note that is you have [nullable reference types enabled](https://learn.microsoft.com/en-us/dotnet/csharp/nullable-references), your code example raises CS8625 as `null` is not a valid key parameter:
![image](https://github.com/nunit/nunit/assets/8655218/0f8afad3-8755-4f5c-b75f-613a503237b1)

**Comment by stevenaw** [comment]
I like the idea of unwrapping it. I think it should be easy for calling code to understand why something fails, and differentiating from a generic wrapped reflection exception will likely be a big help.

It's also nice not to expose an implementation detail like this in case it ever changes. Nunit is heavily reflection-based but technically source generators could be an alternate implementation in a hypothetical future version of the framework
