### ISSUE TITLE
String not-regex constraint succeeds non-`string` actual value

### ISSUE THREAD

**Issue by RenderMichael** [nunit/nunit#4484]
The following code passes
```csharp
[Test]
public void StringMatchesRegex()
{
    // lang=regex
    string regex = "[0-9]";
    string? actual = null;
    Assert.That(actual, Does.Not.Match(regex));
}
```

Should the `RegexConstraint` throw an `ArgumentException` for non-string values (like `null`)?

If so, that a 2-line change (plus tests) and I can spin up the PR myself.

**Comment by OsirisTerje** [comment]
Well,....  null does not match any regex, so the statement there is true.   

You could try:

```cs
Assert.That(actual, Is.Not.Null.And.Does.Not.Match(regex));
```

**Comment by RenderMichael** [comment]
> null does not match any regex

That's a philosophical statement, and I see the point.

On the other hand, .NET's built-in regex throws when calling `Matches(null)`.

Additionally, the constraint calls `actual is string actualStr && Regex.Matches(actualStr)` (pseudocode since I don't have the code in front of me).

So the following also passes, although it's flagged by NUnit.Analyzers
```csharp
[Test]
public void StringMatchesRegex()
{
    // lang=regex
    string regex = "[0-9]";
    int actual = 1;
    Assert.That(actual, Does.Not.Match(regex));
}
```

**Comment by OsirisTerje** [comment]
> On the other hand, .NET's built-in regex throws when calling Matches(null)

If .Net does so, we should probably do the same.

**Comment by RenderMichael** [comment]
Would love to be assigned this PBI, I can spin up a PR for it

**Comment by OsirisTerje** [comment]
There you are :-)  Have fun!
