### ISSUE TITLE
TearDown : Microsoft.Playwright.PlaywrightException : Process exited - C# Nunit playwright package

### ISSUE THREAD

**Issue by aaron-volosin-tfs** [nunit/nunit#4487]
I wrote a set of tests the using the Nunit framework for Playwright and the tests themselves work fine until I add code into [TearDown] that stops my service I am running against.   I can run the tests. They complete without any errors and then when the code specifically hits the myService.Stop(); in [TearDown] then the test fails with "TearDown : Microsoft.Playwright.PlaywrightException : Process exited"  I can watch the browser close at this step.  Here is the full stack trace.

  Message: 
TearDown : Microsoft.Playwright.PlaywrightException : Process exited
TearDown : Microsoft.Playwright.PlaywrightException : Process exited

  Stack Trace: 
--TearDown
Connection.InnerSendMessageToServerAsync[T](String guid, String method, Dictionary`2 dictionary, Boolean keepNulls) line 214
Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) line 521
BrowserContext.CloseAsync() line 276
BrowserTest.BrowserTearDown() line 57
GenericAdapter`1.GetResult()
AsyncToSyncAdapter.Await(Func`1 invoke)
SetUpTearDownItem.RunSetUpOrTearDownMethod(TestExecutionContext context, IMethodInfo method)
SetUpTearDownItem.RunTearDown(TestExecutionContext context)
--TearDown
Connection.InnerSendMessageToServerAsync[T](String guid, String method, Dictionary`2 dictionary, Boolean keepNulls) line 214
Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) line 515
Browser.CloseAsync() line 79
WorkerAwareTest.WorkerTeardown() line 90
GenericAdapter`1.GetResult()
AsyncToSyncAdapter.Await(Func`1 invoke)
SetUpTearDownItem.RunSetUpOrTearDownMethod(TestExecutionContext context, IMethodInfo method)
SetUpTearDownItem.RunTearDown(TestExecutionContext context)

I would really like to use Setup and TearDown to stop and start my service to make sure all sessions are cleared for the next test.  Any Ideas?

**Comment by OsirisTerje** [comment]
This looks very Playwright-specific, and we have little knowledge about Playwright, unfortunately.

1. Have you tried ask some Playwright people about this?
2. Is this exception "normal", then catch it and go on, in the TearDown method. (I have no clue if this will work or not, just a suggestion).

**Comment by OsirisTerje** [comment]
As this doesn't seem to be a NUnit issue, I'm closing for now.

If you're sure it is NUnit, please reopen and add a repro we can investigate.
