### ISSUE TITLE
Use buffer pooling when calculating partition filters

### ISSUE THREAD

**Issue by stevenaw** [nunit/nunit#4489]
The partition filter currently generates a new byte array for each method name. Given partitioning is most likely to be helpful (and thus most likely to be used) when splitting up a large suite, there's the potential for this to allocate quite a few times.

https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/Filters/PartitionFilter.cs#L110

It might be worth looking into using `ArrayPool<byte>` or a single large buffer at instance level here instead of making a new one each time. The one-shot hashing helpers and stackalloc could be helpful here too on the .NET6 build.

I think this should be possible for all library targets but may require taking a dependency on System.Buffers on the net462 build if ArrayPool is used.

@nunit/framework-team thoughts or objections (particularly about the dependency this would add)?

**Comment by stevenaw** [comment]
Perhaps stackalloc is overly ambitious on the net462 side. We could add the System.Memory package too to get Span<> support, but there's not really any APIs to target for it.

**Comment by manfred-brands** [comment]
@stevenaw I'm not sure, but I think that filters are only called from a single thread as part of building the test suite.
If that is correct, we can allocate a large buffer as well as an instance of the `SHA256` class in the constructor.

**Comment by lahma** [comment]
As an exception from hashing should be quite unlikely, you could save some CPU cycles from not having a try-catch.

**Comment by stevenaw** [comment]
Thanks @lahma ! Indeed, some of your past contributions and the size of suites you've helped optimize Nunit for is partly what inspired me to look for optimizations here too

**Comment by manfred-brands** [comment]
@lhama `encoding.GetMaxByteCount(name.Length)` returns just `name.Length * 3` where 3 is *MaxUtf8BytesPerChar*
We know there is a practical upper limit of names, e.g. 1k, so you could use a 4k buffer.

**Comment by manfred-brands** [comment]
@stevenaw Never change two parameters at once.
As there is no difference in netfx, is all your performance improvement in net6 run from the static Hash?
If so it means that the ArrayPool didn't give you any benefit, just made the code more complex.

**Comment by stevenaw** [comment]
Very true @manfred-brands 
Up until now it's been very experimental to see if it was worth more investigation so I put a few low-hanging fruit together to try to understand what bottlenecks there are and what approach to take to multi-targeting.
The more rigorous iterative "change something and measure" is still to come.

**Comment by stevenaw** [comment]
As an aside, how important would thread safety be in this and other filters?

While filters are currently applied sequentially, there's always the possibility a higher-level optimization could change that. For example, within this filter each test's partition is calculated independently meaning a parallel divide and conquer approach could also theoretically apply here for very large suites. There would, of course, be ways we could work around any lack of thread safety but it still may be something worth considering too

**Comment by manfred-brands** [comment]
Indeed a future TestSuiteBuilder could build fixtures/tests in parallel.

For the .net core build, I suggest to use stackalloc and the static hash method.
For the .net framework build, you could try [ThreadLocal](https://learn.microsoft.com/en-us/dotnet/api/system.threading.threadlocal-1?view=net-7.0) for both the global buffer and the hasher. Even in case of a single thread we would be re-using these and in case of multiple threads we would you a few more.
