### ISSUE TITLE
Add Delta overload for `DateTime` assertions

### ISSUE THREAD

**Issue by CollinAlpert** [nunit/nunit#4493]
The `Assert.AreEqual` API allows a delta argument for `double` and `decimal` values. This would also come in handy for `DateTime` assertions in terms of a `TimeSpan` delta, for example [when precision loss occurs](https://github.com/npgsql/npgsql/issues/2646).

I would be happy to provide a PR in case this feature gets approved.

**Comment by manfred-brands** [comment]
Hello @CollinAlpert The `Assert.AreEqual` falls under the *legacy classic* category. In the next version of NUnit these will be renamed and move to separate nunit.legacy nuget package.
We will not accepting any PR for the legacy asserts.

The replacement, for a long time now, is using `Assert.That(actual, Is.EqualTo(expected).Within(1).Milliseconds`
There are several units supported for `TimeSpan`
```csharp
                DateTime expected = new DateTime(2007, 4, 1, 13, 0, 0);
                DateTime actual = new DateTime(2007, 4, 1, 16, 0, 0);
               Assert.That(actual, Is.EqualTo(expected).Within(5).Hours);
```

If you add the [NUnit.Analyzers](https://www.nuget.org/packages/NUnit.Analyzers) nuget package, then you will have "code fixes" to convert the classic assert to the new modern one. You can do that one by one or a whole document/project/solution at once.
