### ISSUE TITLE
NUnit 4.0 LevelOfParallelism doesn't seem to limit number of parallels

### ISSUE THREAD

**Issue by agray** [nunit/nunit#4501]
22 failed tests 
https://github.com/Sauceforge/Saucery/actions/runs/6520846311/job/17708830970

![image](https://github.com/nunit/nunit/assets/118102/5ba42d3e-d069-4cc5-9a78-b26141f6777d)

that all pass reliably with NUnit 3
https://github.com/Sauceforge/Saucery/actions/runs/6520519641

![image](https://github.com/nunit/nunit/assets/118102/6bba7b68-604e-41d5-a678-de83c868e8cb)

OpenQA.Selenium.NoSuchElementException : no such element: Unable to locate element: {"method":"css selector","selector":"#comments"}

rolled back to nunit 3.13:
https://github.com/Sauceforge/Saucery/actions/runs/6521785485

**Comment by manfred-brands** [comment]
All errors seem to be related to timeouts of your server:
```
   OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL http://ondemand.saucelabs.com/wd/hub/session/9251fa8232304ff68c5a86c9d21df70e/element/32e7f528-9ed9-4b1d-9dab-d1b9cb6e3bfe/value timed out after 500 seconds.
```

Your build drop back to nunit 3.13.3 also seem to fail:
https://github.com/Sauceforge/Saucery/actions/runs/6521570628

**Comment by agray** [comment]
Thank mate,
See https://github.com/Sauceforge/Saucery/actions/runs/6521785485

**Comment by manfred-brands** [comment]
@agray Is that an NUnit 4 build?

**Comment by agray** [comment]
> @agray Is that an NUnit 4 build?

The one that failed was the alpha release. Terje ask us on another thread to test it.

**Comment by OsirisTerje** [comment]
4.0.0-beta.1 :-)   From https://www.nuget.org/packages/NUnit/4.0.0-beta.1

**Comment by OsirisTerje** [comment]
@agray Still an issue?

**Comment by agray** [comment]
Yes.  It doesn't work.

**Comment by OsirisTerje** [comment]
I do see some timeout issues, but also a bunch of actual errors where things are not equal. 
I dont see any NUnit in the stacktrace, so it might be that your testproject take a dependency on something that NUnit 3 provides, but not NUnit 4.  
Can you debug this locally for one of the failing tests ?

**Comment by OsirisTerje** [comment]
@agray Are you able to debug this?  
If not I can have a look at your referred code next week.

**Comment by agray** [comment]
Hi Terje,

My Open Sauce account that SauceLabs granted me allows for 5 parallel VMs.

It seems when we try to limit the parallelism it is being ignored and
floods SauceLabs with tests which will lead to the timeouts. It would be
good to be able to control the number of tests if possible.

Saucery relies on and utilises the parameterised test fixture feature of
NUnit.

I've built Saucery in 2014 and have been maintaining it ever since.

If you happen to find any other bugs please let me know.

Thanks

Andrew

**Comment by OsirisTerje** [comment]
@agray 
I cloned the repo and it built, but there are a lot of failing tests.
There are possibly some configurations and also some dependencies that are not described anywhere [I can find], nor does the repo itself handle them.
![image](https://github.com/nunit/nunit/assets/203432/23a401bb-2e9d-47d0-ab42-240c33424d3f)

Not sure how to proceed with this.

**Comment by agray** [comment]
You need a SauceLabs account to run the integration tests.

**Comment by OsirisTerje** [comment]
@agray Not sure what more we can do here.  We can't run it.  It would be great if you could debug down to where this fails, and then see if this is caused by NUnit or Saucelabs code.

**Comment by agray** [comment]
NUnit 3.x without parallelism works fine.

Upgrading to NUnit 4.0 and adding Parallelism causes it to start failing.

The site being hit is SauceLabs guinea pig page.

A free SauceLabs Trial account is all you need to be able to execute the
integration tests.

**Comment by stevenaw** [comment]
@agray I think I saw a reference to this above, but have you tried NUnit 4 without parallelism or NUnit 3 with parallelism to see if either fails?

**Comment by OsirisTerje** [comment]
@agray  As @stevenaw  indicates, this looks like it has something to do with your code not being able to run parallel tests.  From what we can see it doesn't have anything to do with NUnit.  We unfortunately don't have the resources to dive into unknown code.
You do know your code better than us, so if you see anything that could indicate a NUnit bug here, could you please just create a small repro for it.

**Comment by agray** [comment]
Yes...got it from NuGet...

**Comment by agray** [comment]
Please reopen.

Here's you repo:

```
[assembly: LevelOfParallelism(3)]

namespace MyAwesomeNamespace;

[TestFixtureSource(typeof(RequestedPlatformData))]
[Parallelizable(ParallelScope.All)]
public class MyTestClass(BrowserVersion browserVersion) : BaseClassWithSetupAndTeardown(browserVersion)
{
    [Test]
    [TestCase(4)]
    public void DataDrivenTest(int data)
    {
        //test code
    }

    [Test]
    public void AnotherTest()
    {
        //test code
    }
}
```

My SauceLabs account has 5 parallel tests allowed, Despite setting level of LevelOfParallelism to 3 I see with NUnit 4.0.0 I witnessed 7 tests running in parallel (total tests run = 100).

I seems to me that LevelOfParallelism is being ignored somehow.

**Comment by SeanKilleen** [comment]
Re-opening because the original poster followed up.
