### ISSUE TITLE
Add the ability to stop a run in NUnitLite

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#451]
NUnitTestAssemblyRunner has the ability to stop a run currently in progress.  However, that ability is not invokable in NUnitLite.  Currently, only the FrameworkController calls the Runner.StopRun method.

The ability to cleanly stop a run in progress should be added to the NUnitLite runner.

This may mean running the NUnitLite runner on another thread so that additional console input can be given while the tests are running.

This is what my current Crestron CF build in fact does.

**Comment by CharliePoole** [comment]
How would we trigger a cancel? Right now we simply cancel the process running the tests.

**Comment by rprouse** [comment]
It seems to me that you are trying to make NUnitLite the equivalent of nunit-console for CF. There is nothing wrong with wanting a fully capable test runner for CF, but AFAIK, NUnitLite was intended to be a light, simple, single threaded, in-process test runner. Personally, I don't want to see us bringing too much in to the core of NUnitLite, I want to keep it light.

Do you think it would be possible to fork off a platform specific runner for CF like I am doing for other platforms like Android and iOS? I realize there will be code duplication, but it may also reduce complexity. For Android which doesn't have a console, it was actually quite nice to gut all the unneeded code and simplify.

Just a thought :smile:

**Comment by CharliePoole** [comment]
In fact, we do have an issue about that - maybe several. As far as I'm concerned that's separate from NUnitLite, which is entirely about self-executing test assemblies. There are clearly some pieces of NUnitLite that can go into such a platform-specific runner, but I agree it's a different thing.

However, this issue is about cancelling an NUnitLite run. I'd like to know how Neil is envisioning that the user would cause a cancel. Do we need to take control when that happens or is just cancelling the process sufficient. The answer would presumably apply to any text-based console-style runner that we produce, including nunit-console.

As for me, I'm not seeing the need but I'd like to know if I'm missing something.

**Comment by oznetmaster** [comment]
NUnitTestAssemblyRunner has a StopRun method which stops the current run without having to abort the process.

 

In my builds, the console runs asynchronously from NUnitLite, so the console is always available.  I just enter a –stop command, and it (eventually) calls StopRun.

 

This then allows a different set of tests, or even a different test assembly (my AutoRun replacement removes the inhibition to having test assembly names on the command line), to be run.  It also allows the results of any tests run to be obtained.

 

However, StopRun is currently only partially implemented, so my build fixes it to work properly, at least in my environment.

**Comment by CharliePoole** [comment]
@oznetmaster So, how would you propose we expose the stop/cancel capability in NUnitLite? In the absence of any console like yours, how will we test it?

**Comment by oznetmaster** [comment]
It seems that this should happen after the “console” is added back to NUnitLite, which you indicated would be before Beta 2.

 

This could be done one of two ways.

 

It could be done like I do, which is make the console runner optionally get its command line from the console input, rather than from the command line.  This would mean that it would stay available to have other commands (like –stop) issued while a test suite is running.  In this mode it would need to run the console and the test suite asynchronously from each other, but that is pretty easy.

 

Alternatively, NUnitLite could be made to run as a singleton.  If it is already running, and another copy of it is started (with a new command line), then that new command line would be passed to the existing (running) copy for processing, and the second copy would then exit.

**Comment by CharliePoole** [comment]
As written, this issue asks for a general NUnitLite capability to cancel the run. Such a capability is already in existence in the framework.

NUnitLite runners that expose a user interface while the test is running are already able to stop the run, provide that the UI is active while the test runs. Other runners, such as those that are based on a console display that runs the tests synchronously, don't have that capability. Any ability to stop the run has to be dependent on the individual runner implementation making use of the framework to cancel it. No further work is needed to make this available for runners that want to use it.
