### ISSUE TITLE
Randomizer has inconsistent max value exclusive/inclusive in the range

### ISSUE THREAD

**Issue by vgriph** [nunit/nunit#4531]
The NUnit randomizer has inconsistent handling of the max value for ranges.
`NextUInt`, `NextLong` and `NextULong` have inclusive logic for the max value
`NextShort`, `NextByte`, `NextSByte`, `NextDouble` and `NextFloat`  have exclusive logic for the max value (since the use Random.Next / Random.NextDouble which has exclusive logic)
`NextDecimal` has exclusive logic (even excludes to the floor of the passed max value if the passed value is not an integer)

**Comment by OsirisTerje** [comment]
@vgriph Can you provide some repro code to showcase this?

**Comment by vgriph** [comment]
Actually. I did some tests, and it does stay in range. I was tricked by the modulo bias prevention code. However, I think that there is a minor problem with that code that would make it not completely eliminate the bias.

The problem is that the `RawUInt64()` can return a value from 0 to `ulong.MaxValue` inclusive. But the loop in `Randomizer.NextULong(min, max)` is only looping while the `raw > limit`, so if the range is [0..ulong.MaxValue), the raw value could be 0 or ulong.MaxValue with equal probability. And then on the final return where modulo is used but 0 and ulong.MaxValue would be mapped to 0.

To completely avoid bias, `limit % range` would need to be equal to `range - 1`.

To actually see this statistically you would need large sample.
