### ISSUE TITLE
Binary backward compatibility for Assert.That

### ISSUE THREAD

**Issue by manfred-brands** [nunit/nunit#4536]
Because the parameters for `Assert.That` have changed from _format_ + `params` to `FormattableString` we now get:

```
System.MissingMethodException : Method not found: 'Void NUnit.Framework.Assert.That(!!0, NUnit.Framework.Constraints.IResolveConstraint, System.String, System.Object[])'.
```

If any NUnit libraries are used.

Is there any way to keep the old signature in a non-source code way?
Maybe by marking the method internal.

**Comment by OsirisTerje** [comment]
@manfred-brands Can you explain a bit more what you see here.  This is one of the breaking changes, so if we add internal methods, it will still not compile, and the error message would then be wrong.   
Or, is it something with what other NUnit libraries that's in use - which ones could these be?
Do you have some example code?

**Comment by manfred-brands** [comment]
What I want to try is to see if we can add a hidden method that won't be used in any compilation but will resolve at runtime.

**Comment by manfred-brands** [comment]
> I see that Shouldly does not depend on NUnit.

My bad, I thought it was just a wrapper around NUnit asserts. I now saw that it is self contained.

**Comment by manfred-brands** [comment]
Adding some of the old methods and declaring them `internal` changes the exception to a `MethodAccessException`
This means we can only add `public` versions with `Obsolete` and `EditBrowsable(Never)` attributes.

But adding some overloads gives us problems:

NUnit 3 has an `Assert.That<TActual>(TActual actual, IResolveContraint)`.

Whilst NUnit4 has `Assert.That<TActual>(TActual actual, IResolveContraint, ... message = default, string actualExpression = "", string constraintExpression = "")`

Even though that is binary a completely different signature, compile time it is the same and the compiler will favor the one with no-optional parameters. As the first one is marked obsolete users can't compile.

I haven't found a way to hide a method from compilation, but not from runtime calling.

Not sure if possible, but changing that at runtime when the assembly us loaded sounds a bit too far fetched for me.

**Comment by OsirisTerje** [comment]
@gwolbrecht Update your code. 
See https://docs.nunit.org/articles/nunit/release-notes/Nunit4.0-MigrationGuide.html#assertthat-with-format-specification-and-params-overload-conversion

Step by step: 

1. Before upgrade to 4.
2. Upgrade ONLY the NUnit.Analyzer to latest version
3. Use the analyzers update for NUnit2050
4. The upgrade to NUnit 4.
