### ISSUE TITLE
Poor error message when DictionaryContainsKeyValuePairConstraint fails

### ISSUE THREAD

**Issue by ssrmm** [nunit/nunit#4548]
When using `Does.ContainKey(...).WithValue(...)` NUnit currently produces a poor error message that does not include much information about the expected value (s. example below). I've found that this was already reported in #3718 and supposed to be fixed with #3778. The merge-commit of that PR indicates in the list of included tags that this change should be present in the 3.14.0 release. However, this either is not the case or the problem still persists for other reasons. I can still reproduce this with 3.14.0.

```csharp
[Test]
public void Test()
{
    var dictionary = new Dictionary<int, string>
    {
        { 1, "foo" },
        { 2, "bar" },
    };

    Assert.That(dictionary, Does.ContainKey(1).WithValue("bar"));
}
```
```
Expected: dictionary containing entry System.Collections.DictionaryEntry
  But was:  < [1, "foo"], [2, "bar"] >
```

My expectation would be the same as the one of the person who initially posted this issue, a message that includes expected key and value, similar to how it happens if you assert only key or only value.
```
Expected: dictionary containing entry [1, "bar"]
  But was:  < [1, "foo"], [2, "bar"] >
```

For Comparison:
```csharp
Assert.Multiple(() =>
{
    Assert.That(dictionary, Does.ContainKey(1).WithValue("bar"));
    Assert.That(dictionary, Does.ContainKey(3));
    Assert.That(dictionary, Does.ContainValue("baz"));
});
```
This proudces:
```
Multiple failures or warnings in test:
  1)   Expected: dictionary containing entry System.Collections.DictionaryEntry
  But was:  < [1, "foo"], [2, "bar"] >
  2)   Expected: dictionary containing key 3
  But was:  < [1, "foo"], [2, "bar"] >
  3)   Expected: dictionary containing value "baz"
  But was:  < [1, "foo"], [2, "bar"] >
```

**Comment by manfred-brands** [comment]
@ssrmm The milestone for that ticket is 4.0.
Have you tried this with 4.0.0-beta1?

**Comment by ssrmm** [comment]
Not before opening the ticket, but I've tried now. With v4 it is indeed working as expected.

Milestones are usually set manually and I've found across various projects that they tend to be wrong from time to time. Therefore I've been looking at the tag information on the [merge-commit](https://github.com/nunit/nunit/commit/79cf178df1a1d7299892d14fa8286f5a9cb69b46), which should be correct because it is derived from the Git history.
![image](https://github.com/nunit/nunit/assets/22149188/13755663-807d-4a6d-b99e-056ecbb78f6c)

Any idea, why that information is incorrect then?

**Comment by manfred-brands** [comment]
> Any idea, why that information is incorrect then?

Yes, the v3.14.0 tag was created accidentally on the `master` branch instead of on the `v3` branch.
This has been corrected:

![image](https://github.com/nunit/nunit/assets/8655218/1cb28178-86d0-4a08-88ea-7329bd02cf22)

**Comment by ssrmm** [comment]
I guess the original question is answered at this point.

Though, it still looks very much like the there is something wrong with the tag then. If you click on the three dots that are shows in your screenshot, the `v3.14.0` tag shows up. And when I view the code under the `v3.14.0` tag, the fix is also seemingly included: https://github.com/nunit/nunit/blob/v3.14.0/src/NUnitFramework/framework/Constraints/MsgUtils.cs#L86

**Comment by OsirisTerje** [comment]
The tag has been fixed, thanks for notice !
