### ISSUE TITLE
Make ConstraintExpression.AnyOf() accept IEnumerable

### ISSUE THREAD

**Issue by ivan-gurin** [nunit/nunit#4551]
That could probably be a part of https://github.com/nunit/nunit/issues/4355 but didn't happen. That issue was dealing with `Is.AnyOf()`, but exactly same problem exists with `ConstraintExpression.AnyOf()`. Can it be fixed there as well please?
The use case would be like 
```
List<Product> products = await productService.GetProductsAsync();
List<ProductType> types = ProductTypeGroups.AvailableToPurchase;
Assert.That(products.Select(p => p.Type), Has.All.AnyOf(types));
```

**Comment by OsirisTerje** [comment]
@manfred-brands Seems we have some code duplication going on here.

**Comment by manfred-brands** [comment]
@OsirisTerje NUnit has multiple ways to do the same or sometimes similar things. It isn't always clear if similar was intended or accidental.

The linked PR fixed the `AnyOfConstraint` and `Has.All.AnyOf` calls that one.
I'll have a look why that doesn't work as @ivan-gurin expects.

**Comment by ivan-gurin** [comment]
It doesn't work because here you only have an overload with `params object[]`:
https://github.com/nunit/nunit/blob/097a1be976fb6bfff6a2a3a9d8b24dd5010fbcdb/src/NUnitFramework/framework/Constraints/ConstraintExpression.cs#L870
You need something like 
 `public AnyOfConstraint AnyOf(IEnumerable expected) `
 by its side

**Comment by OsirisTerje** [comment]
I had a look at the code for these:

This is the code for  `Is.AnyOf` 

![image](https://github.com/nunit/nunit/assets/203432/1964f56d-f3bc-4389-9eba-2a6d8b2b2be2)

And this is the code the ConstraintExpression.AnyOf

![image](https://github.com/nunit/nunit/assets/203432/5b7becfa-0acb-4edb-b5d5-54ab98686779)

So it looks like the green marked box for the Is.AnyOf should also be in the ConstraintExpression.

**Comment by ivan-gurin** [comment]
So in my example,
`Assert.That(products.Select(p => p.Type), Has.All.AnyOf(types.Cast<object>.ToArray()));`
works as it resolves to unexpanded form of AnyOf(params object?[]? expected), but for other collections expanded form is used, which is not what I would want there.
What you said above is 100% correct.

**Comment by manfred-brands** [comment]
Yes, I agree. I''m not behind a PC, if either of you want to create a PR is fine by me, otherwise I can do so tomorrow.

**Comment by OsirisTerje** [comment]
@ivan-gurin Want to raise a PR for this change?
