### ISSUE TITLE
Wrong binaries for release 3.14

### ISSUE THREAD

**Issue by ivan-gurin** [nunit/nunit#4553]
Seems that the binaries here https://github.com/nunit/nunit/releases/tag/v3.14.0 (and in NuGet) are not built from the sources from the archive on that page. For example, the changes introduced in https://github.com/nunit/nunit/pull/4356 are present in source files, but not in binaries.
I guess that the binaries were build out of https://github.com/nunit/nunit/commit/d784a33dab3da9cd44870d65c74162cad55d3bdc (v3).

**Comment by OsirisTerje** [comment]
Your observation is correct.  The binaries were uploaded there, but the tag and thus the source code is wrong.
It seems that the tag, and thus the code in the release archive there is wrong, it is commit #8c51c41c6 which is on the master branch and thus v4. 
The #4356 belongs to the V4, not V3.  
We don't have any backports for this issue.

**Comment by ivan-gurin** [comment]
Ok I see. Will wait for v4 then, thanks.

**Comment by OsirisTerje** [comment]
v4 should be out within a few days now.
