### ISSUE TITLE
Tests not discovered for .NET Windows-specific TFM without Windows build number

### ISSUE THREAD

**Issue by oatkins** [nunit/nunit#4564]
When reporting a bug, please provide the following information to speed up triage:

* NUnit and NUnit3TestAdapter versions
  * NUnit 4.0
  * NUnit3TestAdapter 4.5
* Visual Studio edition and full version number (see Help About)
  * 17.9.0 Preview 1.0

After updating to NUnit 4.0, and version 4.5 of the test adapter, tests are no longer recognised for a test project targeting **net6.0-windows**. Changing the target to **net6.0-windows10.0.19041.0** works around the problem.

See the attached repro project: [NUnitRunnerWindows.zip](https://github.com/nunit/nunit3-vs-adapter/files/13477774/NUnitRunnerWindows.zip)

Thanks!

**Comment by stevenaw** [comment]
@OsirisTerje 
I haven't been able to sit down to debug yet but this feels like it could be related to some of the refactoring of the Platform attribute and some of the internal helpers. This is likely the same issue @SimonCropp is hitting here: https://github.com/nunit/nunit/issues/4565

The error message mentioned there, "OneTimeSetUp: Only supported on Windows7" is likely from here
https://github.com/nunit/nunit/blob/d91b4cfd94432d8b493a1437be7cc85d7610317f/src/NUnitFramework/framework/Internal/PlatformHelper.cs#L101

**Comment by stevenaw** [comment]
This may be related to where we added support for `SupportedOSPlatformAttribute` https://github.com/nunit/nunit/pull/3926
@OsirisTerje @manfred-brands Should we be ignoring this attribute if found at assembly-level? It seems like it may be added to the assembly when building using a TFM such as `net8.0-windows`

**Comment by SimonCropp** [comment]
from what i have seen, TargetPlatform and SupportedOSPlatform do not produce useful (and possibly incorrect) values. 

so probably best to ignore them

eg `net8.0-windows` produces `Windows7.0`. and net8 doesnt even support windows 7 https://learn.microsoft.com/en-us/dotnet/core/install/windows?tabs=net80#supported-releases

**Comment by manfred-brands** [comment]
I have investigated this a bit further.
The atttribute `[assembly: SupportedOSPlatform("Windows7.0")]` is translated into `[Platform(Include = "Windows7")]`
Which then gets to `PlatformHelper.IsPlatformSupported`:
```csharp
                case "WINDOWS7":
                    isSupported = _os.IsWindows7;
                    break;
```

`_os.IsWindows7` returns `false` on my PC (I'm on Windows 10) and therefore no tests are executed.

Should `[Platform(Include = "Windows7")]` mean `Windows7` and greater, then this implementation is wrong.

I checked the differences between NUnit 3.14.0 and NUnit 4.0.0, but I don't notice specific differences.
When I add `[Platform("Windows7")]` to the test in the given sample repository, I also get no tests runnable, but the message is different:
```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Skipped SomeTest [3 ms]

None     - Failed:     0, Passed:     0, Skipped:     0, Total:     0, Duration: 3 ms - NUnitRunnerWindows.dll (net6.0)
```

With NUnit 4 I get:
```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
No test is available in D:\Development\3rd\NUnit\nunit.issues\Issue4564\NUnitRunnerWindows\bin\Debug\net6.0-windows\NUnitRunnerWindows.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

Additionally, path to test adapters can be specified using /TestAdapterPath command. Example  /TestAdapterPath:<pathToCustomAdapters>.
```
@OsirisTerje Where does this difference come from as I cannot find that text in NUnit.

Summarizing, NUnit thinks that the test _only_ runs on `Windows7` and none of us do.
I suggest to change the code in `PlatformHelper` such that `Windows7` means `>= Windows7`.
Note that the same issue exists in NUnit 3.14.0.
The difference is that the compiler generated `SupportedOSPlatform` attribute is now also applied.

**Comment by manfred-brands** [comment]
Note, a workaround is to add:
```
[assembly: System.Runtime.Versioning.SupportedOSPlatform("Windows10")]
```

**Comment by stevenaw** [comment]
> I suggest to change the code in PlatformHelper such that Windows7 means >= Windows7.

I like the idea of treating "-windows" as all windows versions in NUnit as I think that's how `PlatformAttribute` works already.

What do you think about applying that change at the `OSPlatformTranslator` level instead? `PlatformHelper` is used by both `OSPlatformTranslator` and `PlatformAttribute` to handle both attributes. My thinking is it may minimize chance of changing how existing users may be using `PlatformAttribute`, in particular if someone had added something like this to their codebase in the past and was counting on it only running on Windows 7 (ie: relying on it not running)

```csharp
[Platform("Windows7")]
public void TestThatShouldOnlyRunOnWindows7() {

}
```

**Comment by manfred-brands** [comment]
@stevenaw The documentation of [SupportedOSPlatform](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.versioning.supportedosplatformattribute?view=net-8.0) explicitly states:

> If a version is specified, the API cannot be called from an earlier version

The documentation of [Platform](https://docs.nunit.org/articles/nunit/writing-tests/attributes/platform.html?q=Platform) does not specify this.

> The Platform attribute is used to specify platforms for which a test or fixture should be run

I agree with your suggestion to update `OSPlatformTranslator`.

**Comment by OsirisTerje** [comment]
@manfred-brands @stevenaw  Does this warrant a hotfix version, or should it wait for 4.1?  I've added it now to milestone 4.1, but we could do a hotfix too.  It doesn't block e.g. ILSpy.  And the fix is on myget now.  What do you think?   

@christophwille @oatkins Comments?

**Comment by christophwille** [comment]
For us (ILSpy) a MyGet version would be ok (we recently switched to central package management with source locking). Maybe others would like a more official place, like a 4.0.1 on NuGet.

**Comment by manfred-brands** [comment]
@OsirisTerje I don't know how many projects target just windows. We have both a workaround and a MyGet version. Maybe wait to see if there are more bugs found.

**Comment by OsirisTerje** [comment]
@manfred-brands I missed the workaround, what was that?

**Comment by manfred-brands** [comment]
> @manfred-brands I missed the workaround, what was that?

https://github.com/nunit/nunit/issues/4564#issuecomment-1829047785

**Comment by SimonCropp** [comment]
the workaround didnt work for me

**Comment by manfred-brands** [comment]
> the workaround didnt work for me

Are you on Windows 11 by any chance, then you need to adjust the number.

**Comment by OsirisTerje** [comment]
@oatkins We have no control over the source code discovery unfortunately, and it doesn't find all test cases, so more will pop up during the execution discovery phase.  Until we get this under our own control, there is little we can do with that confusing behavior.  
Tests that are filtered out for some reason, not matching the runtime requirement as you state, they are often not even "found", so we can't mark them skipped either.  The idea is good, and if we could add more "skipped" variants, would be even better, but as it is now, we're kind of a bit blind with respect to this.

**Comment by tannergooding** [comment]
Just noting that I logged a bug against the SDK (https://github.com/dotnet/sdk/issues/37220) around what it is emitting here.

As best as I can tell (and I'm imaging a Win7 machine to confirm now), it should be emitting `windows6.1` for "windows 7" support.

**Comment by SimonCropp** [comment]
@OsirisTerje awesome work on the fix. is there an eta for nuget?

**Comment by OsirisTerje** [comment]
Seems it will be for 4.1.  Would be cool to have it out before end of year.  We need to gather up some more fixes though.

**Comment by SimonCropp** [comment]
is it possible to push a 4.0.1 with just this fix?

**Comment by stevenaw** [comment]
@manfred-brands If it helps,I'm happy to take on organizing the backports of these while you focus on the v4 fixes

**Comment by bhaeussermann** [comment]
> Note, a workaround is to add:
> 
> ```
> [assembly: System.Runtime.Versioning.SupportedOSPlatform("Windows10")]
> ```

I had to add set the platform name string to `"Windows10.0"` like so (in _AssemblyInfo.cs_):

```
[assembly: System.Runtime.Versioning.SupportedOSPlatform("Windows10.0")]
```

**Comment by BenjaminNitschke** [comment]
Test discovery works in VS Test Runner, with NCrunch and manually running them. However with ReSharper no tests are discovered at all and nothing can be run, ReSharper comes bundled with some old NUnit 3.13 version, but it can't be changed as it requires a NUnit.Engine.dll, but only NUnit.Framework.dll is at version 4.0.1. Instead of hacking around on hundereds of projects using some random SupportedOSPlatform, we switched back to NUnit 3.14.0, which works fine with ReSharper (and any other tool). We have a lot of projects with .net8-windows, but also quite a lot with just .net8, zero tests are found by ReSharper .. haven't dug much deeper into it yet ..

**Comment by OsirisTerje** [comment]
You are correct.  The support for NUnit 4 comes in Rider/Resharper version 2023.3, which is at EAP now.

**Comment by lahma** [comment]
Rumor is that 2023.3 will be probably released this week so the wait should not be long.

**Comment by SimonCropp** [comment]
yeah, currently in Release Candidate. so should drop shortly
