### ISSUE TITLE
Version 4.0 - Tests dont get discovered in Rider

### ISSUE THREAD

**Issue by hexxone** [nunit/nunit#4567]
Hi there,

I am not sure if this is the right place for this or if it is related to the NUnit3TestAdapter or something else.

But when I just tried to upgrade to the new 4.0 version, suddenly all the tests stopped being detected in JetBrains Rider for my .NET 6 ASP Core project.

In Visual Studio they are still detected and work as usual.
If I downgrade back to 3.14.0 and refresh, they also show up again in Rider.

I have also tried looking for a "NUnitTest4Adapter" or similar, but assume it has yet to be released, or should be backward-compatible?

My installed packages are:
- `NUnit` - 4.0.0
- `NUnit.Analyzers` - 3.10.0
- `NUnit3TestAdapter` - 4.5.0

Thanks in advance :)

**Comment by OsirisTerje** [comment]
That is correct indeed.  Jetbrains Rider has this fixed now, coming in version 2023.3

See https://youtrack.jetbrains.com/issue/RSRP-494310

**Comment by hexxone** [comment]
Ah, tyvm for the quick and precise reply :) Looking forward to it then!

**Comment by OsirisTerje** [comment]
It should be in their 2023.3 EAP versions now.

**Comment by lahma** [comment]
[Rider 2023.3 is now available](https://www.jetbrains.com/rider/download).
