### ISSUE TITLE
NUnit 4 - Tests cannot be found

### ISSUE THREAD

**Issue by MHofmann-rossmanith** [nunit/nunit#4570]
When executing the tests of a .NET 4.8. DLL with the NUnit.ConsoleRunner in the cmd, no tests are found.
![grafik](https://github.com/nunit/nunit/assets/56957131/dcdb9092-8cf7-4dc7-bb96-b4c3cd304ce9)

Installed packages
- NUnit 4.0.0
- NUnit3TestAdapter 4.5.0
- NUnit.ConsoleRunner 3.16.3

Test project: [NUnit4ExploreTest.zip](https://github.com/nunit/nunit/files/13497183/NUnit4ExploreTest.zip)

**Comment by manfred-brands** [comment]
The `NUnit.ConsoleRunner` 3.16 is not working. When I use version `3.15.5` it works for me.
Note that you don't need the `NUnit3TestAdapter` 
That is only if you use `dotnet test`
