### ISSUE TITLE
NUnit 4: dotnet test behaving differently locally vs on GH Actions (failing)

### ISSUE THREAD

**Issue by christophwille** [nunit/nunit#4571]
Started in #4569 - all those variations work fine in Windows 11 in addition to VS 17.8 + 17.9p1 with the NUnit 4 4.1.0-adev.1 package from MyGet:

```
PS D:\GitWorkspace\ILSpy\ILSpy.Tests> dotnet test
PS D:\GitWorkspace\ILSpy\ILSpy.Tests\bin\Debug\net8.0-windows> dotnet test ilspy.tests.dll
PS D:\GitWorkspace\ILSpy\ILSpy.Tests\bin\Debug\net8.0-windows> dotnet test --logger "junit;LogFileName=Debug.xml" --results-directory test-results ilspy.tests.dll
```

However, as part of GH Actions run (see PR https://github.com/icsharpcode/ILSpy/pull/3132), it fails to find tests

```
Run dotnet test --logger "junit;LogFileName=Debug.xml" --results-directory test-results $env:Tests1 $env:Tests2 $env:Tests3
Microsoft (R) Test Execution Command Line Tool Version [17](https://github.com/icsharpcode/ILSpy/actions/runs/7030026378/job/19128743036#step:10:18).8.0 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 3 test files matched the specified pattern.
No test is available in D:\a\ILSpy\ILSpy\ICSharpCode.Decompiler.Tests\bin\Debug\net8.0-windows\win-x64\ICSharpCode.Decompiler.Tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
No test is available in D:\a\ILSpy\ILSpy\ILSpy.Tests\bin\Debug\net8.0-windows\ILSpy.Tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
No test is available in D:\a\ILSpy\ILSpy\ILSpy.BamlDecompiler.Tests\bin\Debug\net8.0-windows\win-x64\ILSpy.BamlDecompiler.Tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
Results File: D:\a\ILSpy\ILSpy\test-results\Debug.xml
```

dotnet test --diag output file for such a run attached:  [dotnettestdiag-Debug.txt](https://github.com/nunit/nunit/files/13499509/dotnettestdiag-Debug.txt)

What could be the difference of local Windows vs GH Windows runner? (and how to pinpoint)

**Comment by christophwille** [comment]
Just a wild and stupid guess after having an Espresso - could it be that server OSes are not covered by #4569? After all, we are using a 2022 server image on GH.

**Comment by OsirisTerje** [comment]
Can you try to add a new workflow, focusing just on the ILSpy.Tests and the dependencies of that of course, nothing else, and just an out-of-the-box action template, and a standard windows-10/11.

**Comment by christophwille** [comment]
![image](https://github.com/nunit/nunit/assets/344208/bc6f6696-3bd4-457e-85b2-9444c4b10609)
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

That's not happening I guess.

**Comment by rgroenewoudt** [comment]
I just encountered a bug that finding tests doesn't work if TargetFramework contains windows: https://github.com/nunit/nunit3-vs-adapter/issues/1141

This is perhaps the same issue.

**Comment by christophwille** [comment]
> I just encountered a bug that finding tests doesn't work if TargetFramework contains windows: [nunit/nunit3-vs-adapter#1141](https://github.com/nunit/nunit3-vs-adapter/issues/1141)
> 
> This is perhaps the same issue.

That's #4564 - this is using the fix already, but with GH still not working.

**Comment by manfred-brands** [comment]
Ok, the Windows runner reports as Windows 10 Server.
There was already a WindowsServer10 definition in NUnit Platform.
I have updated the OSPlatformTranslator to also add this Platform when appropriate.

**Comment by christophwille** [comment]
Thanks; once merged & MyGet'd I can test it with our PR.

**Comment by OsirisTerje** [comment]
@christophwille The -adev.2 was out yesterday on Myget.  Can you verify it works?

**Comment by christophwille** [comment]
Yes it worked.

**Comment by OsirisTerje** [comment]
Thanks!   Awesome.    Then I'll try to get 4.0.1 out during the weekend.

**Comment by OsirisTerje** [comment]
Version 4.0.1 is out on nuget,  https://docs.nunit.org/articles/nunit/release-notes/framework.html#nunit-401---december-2-2023
