### ISSUE TITLE
Make new PropertiesComparer optional

### ISSUE THREAD

**Issue by Mazzelfassel** [nunit/nunit#4572]
I updated NUnit to bersion 4.0 and run my tests like usual. After doing the required migrations some tests that I didn't even touched start to fail. After some investigation I discovered that this is related to the new PopertiesComparer added by #4394.

The affected tests compare classes via `Is.EqualTo()` and before they were compared by reference. But due to some objects having the exact same properties the new comparer now consideres them equal, failing my tests.

The new comparer is used by default and it looks like it cannot be disabled in the current version. 

Example of  a Test that worked before but fails in version 4:
```
private class TestClass 
{
    public int Prop { get; set; } = 0;
}

[Test]
public void CompareObjects()
{
    TestClass a = new() { Prop = 2 };
    TestClass b = new() { Prop = 2 };

    Assert.That(b, Is.Not.EqualTo(a));
}
```

**Comment by manfred-brands** [comment]
In the example, I would say a and b are considered equal.

If you want reference comparison, you should use `Is.SameAs` instead.

Unfortunately the definition of `Equals` in .NET is not defined as being value or reference. One has to use `ReferenceEquals` to quantify.

If your classes were either `struct` or implemented `IEquality` the behaviour of `Is.EqualTo` changes

I see the behaviour is breaking, but is that because the wrong test was used?

**Comment by OsirisTerje** [comment]
@manfred-brands We should perhaps clarify in the docs for EqualTo that it is intended to do Value equality, and if you need reference equality they should turn to SameAs.  It is not explicitly stated in the docs there, and that could be helpful to do.

**Comment by Mazzelfassel** [comment]
That solution should work. I checked the documentation and it states that `Does.Contain` is a shortcut for what you just described. I probalby was unaware of that fact similar to the `Is.SameAs` situation.

That just leaves the issue with the exception when testing a class with an indexer.

**Comment by manfred-brands** [comment]
Does.Contains is equivalent to Has.Some.EqualTo

> That just leaves the issue with the exception when testing a class with an indexer.

Yes, I will see if I can get a fix for that soon.

**Comment by batzen** [comment]
For anyone interested in a quick fix:
```
[SetUpFixture]
public class TestAssemblySetup
{
    [OneTimeSetUp]
    public void RunBeforeAnyTests()
    {
        // Workaround for https://github.com/nunit/nunit/issues/4572
        {
            var comparersFieldInfo = typeof(NUnitEqualityComparer).GetField("Comparers", BindingFlags.NonPublic | BindingFlags.Static);

            if (comparersFieldInfo?.GetValue(null) is Array comparers)
            {
                object equalsComparerDelegate = null;
                for (var i = 0; i < comparers.Length; i++)
                {
                    var comparer = comparers.GetValue(i);

                    switch (comparer)
                    {
                        case Delegate { Method: { DeclaringType: { Name: "EqualsComparer" } } }:
                            equalsComparerDelegate = comparer;
                            break;
                        case Delegate { Method: { DeclaringType: { Name: "PropertiesComparer" } } } when equalsComparerDelegate is not null:
                            comparers.SetValue(equalsComparerDelegate, i);
                            break;
                    }
                }
            }
        }
    }
}
```

**Comment by stevenaw** [comment]
Thanks for sharing your work around @batzen !

@OsirisTerje @manfred-brands What do you think about us adding an opt out mechanism here, and if so what could one look like?

Alternately, would it make sense to only use the property comparer internally for value types and let reference types use the default "Equals" function? Is there a use case where we'd want to enforce requiring only value equality over reference types?

**Comment by manfred-brands** [comment]
I'm ok with an opt-in or opt-out, but don't want it to restrict to value types. 

I had `PropertiesComparer` intended for DTO classes to test equality without the need to implement `IEquatable<T>` or a special comparer or write an Assert method asserting every property one selves.

However I get the impression that @batzen wants reference comparison for which we have the different constraints. As @OsirisTerje said we need to better document that EqualTo is for value comparison and SameAs for reference comparison.

But historically most users will have used EqualTo for everything.

**Comment by batzen** [comment]
@manfred-brands I don't always want reference comparison when using EqualTo.
What i absolutely don't want is every property getter being called automatically, with no way of preventing that behavior.

The PropertiesComparer only kicks in when the types are exactly equal and everything else failed to check for equality.
Why not remove it from EqualTo and add a new `Has.PropertyValuesEqualTo`?
That way the assert could also assert when different types are passed.

> I had PropertiesComparer intended for DTO classes to test equality without the need to implement IEquatable<T> or a special comparer or write an Assert method asserting every property one selves.

That's totally fine as a convenience method, but it should be explicit instead of implicit.

**Comment by OsirisTerje** [comment]
@manfred-brands @stevenaw @batzen 

EqualTo is meant to be value equality.  The problem with value equality is always how deep you should go. So including the properties makes sense to me.  

However, if I use fields instead it actually doesn't  say that the objects are value equal - but they are, so we have a glitch there.

I looked up how XUnit resolves this, and they have an new assertion Equivalent , which does value equality.  
From their docs:

> Assert.Equivalent differs from Assert.Equal is the “level of equality” that is expected from the two values. For example, Assert.Equal requires that both values are the same (or a compatible) type, whereas Assert.Equivalent will simply compare all the public fields and properties of the two values to ensure they contain the same values, even if they aren’t the same type. Equivalence comes with a “strictness” switch which allows the developer to say whether the expected value contains the complete set of values that the actual value should contain (‘strict’) vs. only a subset of values (‘not strict’). When strict comparisons are done, an “extra” properties on the actual object vs. the expected object cause failure, whereas they are ignored for non-strict comparisons.

We might need to rethink equality.  I have always thought of EqualTo as full value equality, but I can understand that it actually is not.  It is something in between. It compares by value until it is nearly finished, then sort of continues by comparing by reference (It doesnt, but the effect is the same).    So I like the PropertyComparer, but it is a breaking change (which is fine as it is 4.0), but it should then also have done fields the same way.  

So, perhaps we should do something like what XUnit has done with the Equivalent ?
Or should we have a modifier to control this for the EqualTo ?

**Comment by stevenaw** [comment]
> I have always thought of EqualTo as full value equality,

@OsirisTerje Interesting!

I've actually historically had a bit of a different mental model with `EqualTo()`. I think I've thought of it similar to how @Mazzelfassel [describes it here](https://github.com/nunit/nunit/issues/4572#issuecomment-1833964092), which is that it is analogous to default dotnet equality but with  a bunch of convenience conversions on top to handle things like collections, tolerance, etc.

If we do decide to explicitly define equality as by-value for compound reference types such as custom classes, then I suspect the adjustment for those who think of `EqualTo` in a different way may be to allow a modifier on the `EqualConstraint` to allow the asserts to work in a way compatible with that way of thinking. For example, since we already have `Using()` to describe modifying equality rules, value equality by default may pair well with a `UsingReferenceEquality()` modifier.

**Comment by OsirisTerje** [comment]
Modifiers:  Good thought.  The XUnit Equivalent comes with an adjustable  "strictness" setting, perhaps we could have a similar Using , but we then also have to figure out the defaults.  Should it be like it was before?  And then have opt-in for more strictness, like UsingFullValueEquality  ?   The pre-4.0 EqualTo missed the properties, now we have the properties, but we're missing the fields.  And, we dont go below the class itself, so if a class has another class as a composite child, should that be included?  Should the depth be another parameter?   

Or, should we leave it up to the user, and just have the possibility to add your own ?  A more relaxed model.

**Comment by stevenaw** [comment]
Quick thought (as I'm not at a computer anymore) but we may need to expose a modifier over a few different constraints. I believe Superset, Subset, Contains (as pertains to collections rather than strings) and EquivalentTo are a few of the collection-based constraints which apply equality rules when comparing individual items in the collection

**Comment by stevenaw** [comment]
Changing this from question to enhancement as it sounds like something the team wants to explore

**Comment by manfred-brands** [comment]
> However, if I use fields instead it actually doesn't say that the objects are value equal - but they are, so we have a glitch there.

Yes. Initially, before settling on properties, I was thinking of using fields iso properties, as even auto-properties are backed by hidden fields. I guess I made the wrong decision there. But that was based on my companies use case.

Value comparing classes only makes sense for data classes and in theory those should have public properties, not fields. When following [CA1051](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1051) field are internal implementation details. However [CA2211](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2211) only raises for mutable fields. So immutable data classes using read-only fields should be fine.

`EqualTo` does other things which might be not expected for user that expect standard .net Equals behaviour.
We iterate enumerables, dictionaries and even read whole streams, so properties/fields fits in that paradigm.

One option would be to rename `EqualTo` into `ValueEquals` along the `SameAs` to clearly specify the intend.
It is too late for NUnit4 but we could already add a `ValueEquals` for people to make the transition.

But as @stevenaw says, there are many constraints that implicit use an `EqualConstraint`: 
* Has.Member
* Does.Contain
* Contains.Item
* Contains
* Member
* EqualTo

There also the separate constraints uses `NUnitEqualityComparer` themselves:
* CollectionItemsEqualConstraint which again is used by several other mainly Dictionary constraints.
* AnyOfConstraint, is documented with `value is equal`. I don't think there is a reference equivalent.
* CollectionTally as used by Equivalent, Subset, Superset.

Not all have an `SameAs` equivalent, nor the same options to specify an additional comparer.

When adding the `PropertiesComparer`, I initially thought of using it as an extra comparer users can specify, but that only would test a top level class, not nested and also would not have the benefit of calling into the NUnitEqualityComparer recursively to get the benefits of the other comparers (including tolerance) for each property.

We need to see if we can come up with or have to add to a set of all constraints that use either Value or Reference comparison.
* `Is.EqualTo` vs `Is.SameAs`
* `Has.Member` == `Has.Some.EqualTo` vs `Has.Some.SameAs`
* `Is.EquivalentTo` has no equivalent for reference comparison only, but could use `.Using<object, object>((x, y) => object.ReferenceEquals(x, y))` which is quite long.
* etc.
Once we have that list and added any missing constraints we need to add that to the documentation.
But I think all the above needs to have it own issue.

An alternative is to have a "comparison mode" where users specify `value` or `reference` behaviour.
Again this means changing API.

For the immediate case I can change `PropertiesComparer` into a `FieldComparer`, but I would like to compare both public and private fields (to catch backing fields of properties). This will work around properties that are not value properties and will fix the indexer throwing.

I give another thought on making it optional with a `Using`. I couldn't do what I wanted with a class outside NUnit, but it might work with one defined there. 

Sorry that this got a bit long.

**Comment by batzen** [comment]
@manfred-brands I think comparing fields would be even worse than comparing properties. Comparing something private should be way out of scope for a test framework.

All i am asking for is to be able, without using reflection, to globally turn off the `PropertiesComparer`.

I still think that blindly calling into every property is generally a bad idea as no one knows which cost and side effects that might have.

**Comment by appel1** [comment]
Ran into a problem because of this when comparing not yet completed tasks. PropertiesComparer called Task<T>.Result which caused a deadlock. 

The fix here is not to use EqualsTo but instead use SameAs. But thought I should mention it. 

```csharp
var tcs1 = new TaskCompletionSource<int>();
var tcs2 = new TaskCompletionSource<int>();

// Do things here that results in two tasks that took the completion source tasks as input. 

var task1 = tcs1.Task;
var task2 = tcs2.Task;

Assert.That(task2, Is.Not.EqualTo(task1)); <- Causes hang

tcs1.SetResult(0);
Assert.That(task1.IsCompleted, Is.True);
Assert.That(task2.IsCompleted, Is.False);
```

**Comment by rauhs** [comment]
Could this added to the breaking changes for v4? This behavior change just cost us a bit of time.

**Comment by manfred-brands** [comment]
I created a PR to go back to 3.14 behaviour for `Is.EqualTo` and add an `UsingPropertiesComparer()` method to enable it.
This would cause no breaking changes, but allows the functionality to be used when needed.

**Comment by OsirisTerje** [comment]
@Mazzelfassel @batzen Can you please check this package https://www.myget.org/feed/nunit/package/nuget/NUnit/4.1.0-alpha.0.1

**Comment by Mazzelfassel** [comment]
Tested it on my code and it seems to work fine so far. The tests that were broken before are working as expected now.

**Comment by OsirisTerje** [comment]
@manfred-brands We need to document the UsingPropertiesComparer.  From what I can see it is added to four constraints.  I'm adding it to the Modifiers list for those four.

We probably don't need to do anything more right now, but we could add some more description of it later, how it works (like single level, not deep), and when to use it. 

I'm also considering mentioning it as a **possible** breaking change since in 4.0 it is included, whereas in 4.1. it is optional.  However, in earlier versions it did not exist, so.  What do you think?

**Comment by manfred-brands** [comment]
@OsirisTerje I initially tried to create a `class PropertiesComparer : IComparer` however that means NUnit only calls into that comparer. What I needed was an integration where only if all other known comparers were exhausted, NUnit will call into the properties comparer. The properties comparer also calls into NUnit comparer for all individual properties which in turn only as a means of last resort call properties comparer again.
This was the reason it was initially 'always on'.
I thought of calling the method `EnablePropertiesComparer`, but choose the `Using` prefix to align with the others that select a different compare mode.

**Comment by manfred-brands** [comment]
@OsirisTerje I'll make time to work on https://github.com/nunit/docs/issues/812
