### ISSUE TITLE
Add "NUnit.Annotations.InternalApiAttribute" or similar?

### ISSUE THREAD

**Issue by SeanKilleen** [nunit/nunit#4578]
A follow-up to https://github.com/nunit/docs/pull/843.

Now that we have the API reference published, there might be certain areas of the code where we want to clearly mark them with our intention to keep them internal -- keeping them out of the docs, etc.

Akka .NET does something similar -- docfx then allows them to exclude anything marked with their attribute:

https://github.com/akkadotnet/akka.net/blob/dev/docs/filterConfig.yml

Is there any interest in me adding this? If so, are there any good candidates where there's widespread agreement this attribute should be used?

Thanks!

**Comment by SeanKilleen** [comment]
@manfred-brands good call; I should be able to filter out the internal namespace from the docs at least for starters. I don't think that'll require anything here to do. I'll get on that ASAP.

So this would be for anything outside of that namespace that we still don't want in the docs for any reason.

**Comment by jnm2** [comment]
v4 being so new is a really good opportunity to make them internal. That said, I've definitely used them for workarounds and things that can't be done via the public API, and that would block me from using v4 until an equivalent public API was provided.

**Comment by manfred-brands** [comment]
> If we do changes we should create a branch v5 to hold those until we decide to release v5

I agree it is too late for v4, but having a long running branch just for this is not worth the hassle. We could have some issue with a v5 milestone to change the visibility at that time.

> On the other hand, is there something we could do to the documentation process to improve this?

I think @SeanKilleen said there are lots of filters, so maybe a namespace filter

> I don't mind that there are some internal methods documented in the API docs.

Some is fine, even all if separated, but currently it overshadows the things end users look for. They get lost.

**Comment by stevenaw** [comment]
We may want to review the discussion in #1426 
It may not be as straightforward as treating everything in the namespace as internal to the framework. It looks like the last comment there started the process of identifying exactly which of the subnamespaces may be needed for different use cases

**Comment by jnm2** [comment]
> Can you elaborate what you needed that wasn't part of the API. In that case we can move those classes out of the `Internal`  and document them.

It seemed a bit here and there. I remember it included using TestExecutionContext for various things, but it's been a while and I forget. I definitely would file issues as needed.

I do like the concept that the framework would be generally open for customization that doesn't require the NUnit team to design every use case individually. I like fully trusting users as programmers.

**Comment by jnm2** [comment]
I do agree that removing access to internals is a large enough item that we likely shouldn't frame it as a bugfix but rather as an API change, requiring v5.

**Comment by SeanKilleen** [comment]
I think at this point it seems like we have consensus that:

* Marking things actually internal would be a v5 breaking change (which should be created in an issue with a v5 milestone)
* We are OK with removing the `NUnit.Framework.Internal.*` items from the docs (which I've now done).

Given that, I think I can close this. 👍 Thanks all1
