### ISSUE TITLE
Updating Nunit package to v4.0.1 cause compilation error in Assert.IsTrue and other Assert

### ISSUE THREAD

**Issue by moh-hassan** [nunit/nunit#4580]
When updating package NUnit  Test projects in net472 and net6  from v3.14.0 to v4.0.1 (also 4.0.0) a compilation error is raised:
```
Error	CS0117	'Assert' does not contain a definition for 'AreEqual'	
Error	CS0117	'Assert' does not contain a definition for 'IsTrue'	
Error	CS0117	'Assert' does not contain a definition for 'IsFalse'	
Error	CS0117	'Assert' does not contain a definition for 'IsEmpty'	
```
I had to re use v3.14.0.
Is Assert.xxx is removed in v4.0.1

**Comment by OsirisTerje** [comment]
No, it is not removed, it has just moved to another class and namespace, so use ClassicAssert.XXXX instead.  
The information about it is at the [Migration Guide](https://docs.nunit.org/articles/nunit/release-notes/Nunit4.0-MigrationGuide.html) and in the [NUnit 4 plans](https://docs.nunit.org/articles/nunit/Towards-NUnit4.html#classiclegacy-asserts).

**Comment by mikkelbu** [comment]
@moh-hassan Note that you can use the NUnit.Analyzers to help with the migration. See https://docs.nunit.org/articles/nunit/release-notes/Nunit4.0-MigrationGuide.html#convert-classic-assert-to-constraint-model for more information

**Comment by moh-hassan** [comment]
Thanks  @mikkelbu  for suggestion
I tried the NUnit.Analyzers and find it suggest me to Consider using the constraint model, `Assert.That..`. that lead to modification of the parameters of Assert.
I think for quick fix Find/Replace `Assert` with `ClassicAssert`.
Is there a better way for auto conversion of Assert?

**Comment by OsirisTerje** [comment]
> that lead to modification of the parameters of Assert.

Even if the parameters are changed, it should do the same.  Under the hood, the ClassicAsserts call the constraint model, so all you do by transforming them, is to surface that internal change.

If all your asserts are of the ClassicAssert types, then a Find/Replace would do fine.

**Comment by moh-hassan** [comment]
Based on the Migration Guidance document
  [Use global using aliases](https://docs.nunit.org/articles/nunit/release-notes/Nunit4.0-MigrationGuide.html#use-global-using-aliases)

I migrated Assert.xxx to v4 ClassicAssert.xxx in all test projects
using **ONLY ONE** line of code I dropped in the file  GlobalUsings.cs instead of Find/Replace:

```
global using Assert = NUnit.Framework.Legacy.ClassicAssert;
```

Just Clean migration.
So easy, so simple :)

**Comment by OsirisTerje** [comment]
@moh-hassan Thanks for that suggestion.  We should drop that into the Migration guide !
