### ISSUE TITLE
Nunit 4.0.x Test case selection is incorrect with certain test data

### ISSUE THREAD

**Issue by johnjaylward** [nunit/nunit#4584]
We have certain test cases that are using test data and expected results.

When the tests run in Microsoft Visual Studio 2022 (64-bit) Version 17.8.2, the tests get ignored.

I've created a sample project that recreates the issue: https://github.com/johnjaylward/Nunit4_TestcaseSelectionIssue

I managed to find a work around that does let the tests run by adding another Test with the same name, but does not use parameters.

In the test project the `SelectionFail` tests show the bug while the `SelectionSuccess` test shows the workaround.

![image](https://github.com/nunit/nunit/assets/383703/c626766e-5f5f-47d7-8e02-dd966d21b758)

**Comment by OsirisTerje** [comment]
I tried your code, and I do see the same in Visual Studio.  
When I add a runsettings file, and dump the content from the framework/engine, I also see that no tests from SelectionFail appears. They are sent down from the explorer/adapter, but doesnt come back. 

It is something with the naming here, if I do a SetName on each data to a "normal" name, then it works.  

![image](https://github.com/nunit/nunit/assets/203432/3b1fdc1a-f5fe-4349-846d-59bd66eca37c)

I also see that it works from the command line.
Looking at the dump files, the dotnet test doesn't use any filter, as expected, in this case

```xml
<TestFilter>
   <filter/>
</TestFilter>
```

Using Test Explorer, it does send all down as a list of testcases, so we then get a rather ugly filter:
(just start of shown)

```xml
  <filter><or><test>Nunit4_TestcaseSelectionIssue.SelectionFail.TestFailure([
  1,
  2,
  3,
  4,
  5,
  6
],4)</test><test>Nunit4_TestcaseSelectionIssue.SelectionFail.TestFailure([
  1,
  2,
  3,
  4,
  5,
  6
],2)</test><test>Nunit4_TestcaseSelectionIssue.SelectionFail.TestFailure([
  1,
```

There is then something in the framework/engine that doesn't like these test names.  Why an extra test should make them appear again beats me right now.

As a workaround:  You can force it to not use any filter if you add `<AssemblySelectLimit>2</AssemblySelectLimit>` (with any number less than the number of tests you have) to your .runsettings file.  Then it will always run all tests.

**Comment by johnjaylward** [comment]
ok, instead of using the default `.runsettings` as provided by MS, I used the one in this repo, and I got similar results to what you showed:

![image](https://github.com/nunit/nunit/assets/383703/db88b873-6cf1-49ff-ab1d-f9c3101d4d04)

**Comment by OsirisTerje** [comment]
It doesn't affect anything but the filtering of test cases sent to the framework.  That setting is meant to fix the issue that Test Explorer was changed at some time to not send us Test All anymore, but just a list of testcases.   If you have a lot of test cases, say >2000, it would slow down the test simply because of the parsing of that long list of tests.  So when the number of tests are above this limit, we just clean the filter and let all tests run.  If you define a category filter, it will still honor that filter.

**Comment by stevenaw** [comment]
@OsirisTerje sorry, I had missed that you had pinged for thoughts here. I'm not at a computer for a few days, but will try to look soon. Definitely need to step through it to understand it.

Initial thoughts: I can't recall any changes in how we'd enumerate something like a jsonarray to generate test cases but I think the biggest change in that area this release was async enumeration. I'm unsure if jsonarray could be taking the async path there?

**Comment by stevenaw** [comment]
Oh, reading further I see that perhaps this is on the filtering side, as you mention.

**Comment by mikkelbu** [comment]
I cannot think  of any changes that should affect this, so I'll have to try it out to come with a better answer

**Comment by stevenaw** [comment]
I've been able to experiment a bit with the repro.

It seemed as though commenting out the ignore didn't change anything, though the presence of another test did seem to be required to get the parameterized "success"case to run.

**Comment by stevenaw** [comment]
I'm beginning to wonder if this is a line endings issue within the test name.

I see `\r\n` here in `DefaultTestCaseBuilder.BuildFrom`
![image](https://github.com/nunit/nunit/assets/439844/f6ddab16-072b-4189-9328-c308fc18915e)

And `\n` here in the passed in filter in `NUnitTestAssemblyRunner.Run()`
![image](https://github.com/nunit/nunit/assets/439844/408a7c84-2bd2-4aae-870e-567fb7f6294d)

The filter itself is coming in as `\r\n`. It seems that the parsing of the `<test>` element yields a `TNode.Value` with `\n` while `TNode.OuterXml` itself instead shows `\r\n`. 

At a glance there were some changes to `OrFilter` and `FullNameFilter` as well as `InFilter.TryOptimize`. It _does_ look like it's trying to use optimize the filter into an `InFilter`. I'm wondering if the hash-based checking of the `InFilter` is what's conflicting with potentially mixed line endings.

I have to stop investigation for the night but hopefully these intermediate findings may spark a team member's memory.

**Comment by stevenaw** [comment]
This doesn't appear related to the in filter optimization as commenting it out doesn't seem to change anything.

**Comment by OsirisTerje** [comment]
@stevenaw Are you close to a solution to this?

**Comment by stevenaw** [comment]
I've been able to make a test over this which seems to reproduce the issue but I wouldn't say I'm "close". I'll push a branch in a few hours to show what I've got so far.

**Comment by stevenaw** [comment]
@OsirisTerje 
I've found that the XML generated for the test method above doesn't roundtrip when calling `TNode.ToXML` and `TNode.FromXml` again. I suspect this to be the underlying issue here. We've had a few different changes to XML escaping or parsing logic between 3.14 and 4 so my focus right now is trying to narrow down the change. I'll keep on it :)

In my opinion, if we're open to doing a 4.2.1, then I would say don't hold up a release on account of this ticket if everything else is ready to go. There's other completed bugfixes which would be valuable to get out soon.

My branch so far: https://github.com/stevenaw/nunit/tree/4584-selection-issue

**Comment by OsirisTerje** [comment]
Yes, we have 28 fixed issues now, so that is good. 
But this is a bugfix, so belongs in a 4.3 then.    But we can do a 4.3 within the next quarter or so.

**Comment by stevenaw** [comment]
I'd welcome help if we want to make a concerted push to get this done sooner. Next two weeks will likely be a challenge for myself to make any progress

**Comment by OsirisTerje** [comment]
Sure, can see if I can help out.  Perhaps @manfred-brands also has some timeslots.

> doesn't roundtrip when calling TNode.ToXML and TNode.FromXml

What exactly do you mean with "roundtrip" here?

**Comment by manfred-brands** [comment]
@stevenaw The roundtrip is a red herring.

The _allXml_ uses `<testcase ... />` whilst the _allReparsed_ uses `<testcase ...></testcase>`

If I change your code to adjust for that, the test passes.
```csharp
var allReparsed = reparsed.OuterXml.Replace("></test-case>", " />");
```

**Comment by stevenaw** [comment]
Thanks @manfred-brands ! Yes, I was a few minutes too slow to clarify. 🙂

Looking up to an earlier investigation here, I _think_ I also saw some line endings changing when occurring in a test name (https://github.com/nunit/nunit/issues/4584#issuecomment-1937404469). I don't think I quite narrowed down where though

**Comment by manfred-brands** [comment]
We cannot run the individual `TestSuccess` tests either. I don't know how to filtering in VS TestExplorer works, but maybe if running all tests, the filter only contains `TestSuccess` only the prefix is used as a filter? Renaming the `TestSuccess` without parameters into `TestAlsoSuccess` also causes the other `TestSuccess` tests to not run.

As @stevenaw said in https://github.com/nunit/nunit/issues/4584#issuecomment-1937404469 there is something with new lines. The translation from `\n` to `\r\n` and back is done by various libraries in .NET. In this case `Utf8JsonWriter.WriteLine`. `JsonArray.ToString` is hard-coded to use _pretty_ Json formatting.
The idea was you can say `Console.Write("Hello\nWorld\n")` and on Unix it would output `\n` and on Windows `\r\n`.
Same for the reverse.

I don't know where this is happening as I don't know who passed the filter with only `\n` in it.

Personally, I don't really like embedded line separators in a name.
I updated the test supplied by @johnjaylward to replace `JsonArray` with `MyJsonArray` which is a wrapper class which only replaces `.ToString()` to remove the `\r\n`. This fixes the issue (note that the test names look better imho):

![image](https://github.com/user-attachments/assets/f263e724-3e80-4603-8e39-5a2f5716d3e1)

We can update `DisplayName.GetValueString` to:
* remove `\r' and `\n' so names don't contain these characters. Potentially expand this for all non-printable characters.
* replace them with `\\r\\n`. Potentially expand this for all non-printable characters.

**Comment by manfred-brands** [comment]
Accepting the output of `.ToString()` for unknown types could result in weird character or very long names.
Maybe we should treat the result of that in a similar way as we treat strings. Limit its length and control characters are escaped.

Extending this, we should also escape any strings passed to `SetName` and `SetArgDisplayNames`.

**Comment by manfred-brands** [comment]
One problem with escaping `\r` is that the names will be different between unix and windows.
Potentially we could first  replace `\r\n` with `\n` and then escape the `\n` into `\\n`

Or alternatively only remove `\r` from names as it seems that `TestExplorer` only sends `\n`.

**Comment by manfred-brands** [comment]
@stevenaw @OsirisTerje What would you like me to do:

1. Strip `\r` from `Name` as that will be lost in `TextReader`?
2. Strip all control characters from `Name` as that will affect readability.
3. Escape all control characters from `Name` as to match source, but will affect readability.

**Comment by stevenaw** [comment]
@manfred-brands I'm unsure. 

It sounds like my own investigation here stopped before I could identify exactly where and what changed to strip these characters. I recall testing this on both 3.x and 4.x and I think the issue was only present on 4.x so I think I was assuming something on our end rather than in the BCL was the cause. I can try and take another look tonight if you saw something different. 

To that end, while I agree line breaks in test name are unusual, I'm hesitant to say we accept this change without first understanding it. I'll report any findings I may have here in a bit

**Comment by stevenaw** [comment]
Ok, I can reconfirm that the example repro works on nunit 3.14 and fails in 4.x: https://github.com/nunit/nunit.issues/tree/main/Issue4584

And I can confirm I think something @manfred-brands was saying earlier. The `\r` gets stripped out when `XmlReader` is trying to read the content of the `<test>` node here: https://github.com/nunit/nunit/blob/main/src/NUnitFramework/framework/Interfaces/TNode.cs#L176

For given the xml passed to the framework:
```xml
"<filter><or><test>NUnit.Framework.Tests.Issue4584+SelectionFail.TestFailure([\r\n  1,\r\n  2,\r\n  3,\r\n  4,\r\n  5,\r\n  6\r\n],4)</test><test>NUnit.Framework.Tests.Issue4584+SelectionFail.TestFailure([\r\n  1,\r\n  2,\r\n  3,\r\n  4,\r\n  5,\r\n  6\r\n],2)</test><test>NUnit.Framework.Tests.Issue4584+SelectionFail.TestFailure([\r\n  1,\r\n  2,\r\n  3,\r\n  4,\r\n  5,\r\n  6\r\n],1)</test><test>NUnit.Framework.Tests.Issue4584+SelectionFail.TestFailure([\r\n  1,\r\n  2,\r\n  3,\r\n  4,\r\n  5,\r\n  6\r\n],7)</test></or></filter>"
```

The value returned from `reader.Value` there is:
```
NUnit.Framework.Tests.Issue4584+SelectionFail.TestFailure([\n  1,\n  2,\n  3,\n  4,\n  5,\n  6\n],2)
```

It looks like it's the `XmlReader` doing this. Switching from passing `StringReader` into `XmlReader.Create()` to instead using `MemoryStream` doesn't seem to have any effect. `XmlReader` appears to buffer the passed in stream/reader internally so we also can't inspect the current stream position to "fake" consuming the `\r`

**Comment by stevenaw** [comment]
@OsirisTerje It looks like the test filter XML is getting passed in from the adapter already escaped. Is there any chance the adapter is escaping this?

**Comment by manfred-brands** [comment]
@stevenaw The tests get selected when running 3.14 with the same adapter, so I don't think the adapter makes the difference. Maybe the `\r` gets ignored somewhere in the match on 3.14, but I haven't found it.

**Comment by OsirisTerje** [comment]
@stevenaw I am on travel now, but the TestFilter class parses the incoming filter and transforms it into a NUnit filter.  I don't think there are any escaping there on line ends.  

Socolins PR covers color stuff, and is on the return events, not the ingoing filtering.

As @manfred-brands says, if the same adapter is used, it should not be the adapter.  

The tokenizer (used in TestFilterParser) will skip all `\r ` and ` \n` as they are considered whitespace. So a test filter should not consist of any of these characters.

**Comment by stevenaw** [comment]
Thanks @OsirisTerje @manfred-brands 
I may've missed that it worked on 3.14 while keeping the adapter the same. Definitely framework-related

**Comment by stevenaw** [comment]
Digging into this a bit more, it looks like the current behaviour of normalizing line endings is "to spec" as the XML parsing standards appear to say [line endings should be normalized](https://www.w3.org/TR/REC-xml/#sec-line-ends) to `\n`.

I haven't find a _public_ way to adjust this but there is an _internal_ prop named `Normalize` which controls this. Changing it from `true` to false in the debugger or via reflection both seem to work.
https://github.com/dotnet/runtime/blob/280f2a0c60ce0378b8db49adc0eecc463d00fe5d/src/libraries/System.Private.Xml/src/System/Xml/Core/XmlTextReaderImpl.cs#L2004

So we may have a few options here:
1. Stick with the standards and say carriage returns are unsupported in test names - and recommending against newlines in general. Suggested work arounds could be to manually override the test name or to change or remove the line endings.
2. Use the reflection-based approach. This would give the most flexibility but with the minor risk that a change in naming of this internal prop could break us. I consider this risk quite low but not zero.
3. A mix of the above. We still recommend against newlines in general and say carriage return support is undefined. We do a best-effort to normalize this by setting the property, but we do so in a way that if the property name changes that the framework doesn't throw an exception.

I like option 3 a bit myself. I've put an initial PR up with what I have so far.
 @manfred-brands @OsirisTerje @nunit/framework-team  thoughts on how we proceed?

**Comment by stevenaw** [comment]
Ok, scratch that remark about reflection - the property can be set if I just initialize the `XmlTextReader` directly. Looks like we can restore the behaviour here. I'll wrap up the linked PR tomorrow. Do we want to still have any recommendations on test naming we should document? @manfred-brands had made a good point that newlines will make portability of test files an issue for users.

**Comment by manfred-brands** [comment]
Thanks @stevenaw I can confirm that your change works for me, in my tests.

None of this explains why it works on 3.14 :-(
However the `TNode.FromXml(string)` method has a completely different implementation between v3 and v4.
v3 use `XMLDocument.Load` and v4 uses an `XmlReader`. I didn't delve to deep to see why the first keeps `\r`.

I actually added a test to ensure the filter works. Without your change, it fails in v4:

```csharp
[Test]
public void DiscoverAndExecution()
{
    var fixtureType = typeof(TestCaseSourceAttributeFixture.SelectionFail);
    var methodName = nameof(TestCaseSourceAttributeFixture.SelectionFail.Test);
    var fixture = TestBuilder.MakeTestFromMethod(fixtureType, methodName);

    foreach (var test in fixture.Tests)
    {
        TestContext.Out.WriteLine($"Test: {DisplayName.EscapeControlChars(test.Name)}");

        var filter = TestFilter.FromXml(
            $"<filter><name>{test.Name}</name></filter>");
        WorkItem? workItem = WorkItemBuilder.CreateWorkItem(fixture, filter, recursive: true);

        Assert.That(workItem, Is.Not.Null);
        Assert.That(workItem, Is.InstanceOf<CompositeWorkItem>());

        var compositeWorkItem = (CompositeWorkItem)workItem;
        Assert.That(compositeWorkItem.Children, Has.Count.EqualTo(1));
    }
}
```

I used a slightly different `SelectionFail` test so I didn't have to add a dependency on `System.Text.Json` and how it formats text.

```csharp
#region Multiline selection failure
[TestFixture(Description = "https://github.com/nunit/nunit/issues/4584")]
public class SelectionFail
{
    [TestCaseSource(nameof(Data))]
    public static void Test(int actual, int expected)
    {
        Assert.That(actual, Is.EqualTo(expected));
    }

    public static IEnumerable<TestCaseData> Data
    {
        get
        {
            yield return new TestCaseData(42, 42);
            yield return new TestCaseData(42, 42).SetName("42 == 42");
            yield return new TestCaseData(42, 42).SetName("42\r\n42");
            yield return new TestCaseData(42, 42).SetArgDisplayNames("42\n", "42\r\n");
        }
    }
}
#endregion
```

@stevenaw  I wanted to put-up a PR with the above tests, but accidentally pushed it to your branch. Sorry.

I still prefer stripping `\r` from Names. As these are only added if running on Windows, not on Unix.
Leaving them in would use different Names depending on OS.

**Comment by stevenaw** [comment]
Thanks @manfred-brands Happy to have your commits in my branch, appreciate the cleanup.

> None of this explains why it works on 3.14 :-(
> However the TNode.FromXml(string) method has a completely different implementation between v3 and v4.
> v3 use XMLDocument.Load and v4 uses an XmlReader. I didn't delve to deep to see why the first keeps \r.

Agreed. My suspicion now that we've found the switch which controls this is that perhaps `XmlDocument` internally defaults this to false in certain cases, perhaps if no DTD is present on the document. Like you, I also didn't dig too far on that side. I _had_ tried restoring the old `XmlDocument.Load()` behaviour earlier in my investigation and hadn't seen it "fix" the issue at the time, but perhaps something had cached.

On new lines in test names, there's certainly a few different ways to approach it. My ending thought here would just be that I don't know how often test file XML would be copied between OS's. My earlier suggestion had been coming from the idea that we could make a best effort, but that it might be kinder to fail noisily if someone is trying to do something OS-specific across multiple OS.
