### ISSUE TITLE
Feature request: Assert.Multiple() could return an IDisposable, avoiding passing an Action around.

### ISSUE THREAD

**Issue by andrewimcclement** [nunit/nunit#4587]
Would it be possible to be able to write code like:
```
// Act
var result = GetResult();

// Assert
using (Assert.Multiple())
{
    Assert.That(result.A, Is.EqualTo("A"));
    Assert.That(result.B, Is.EqualTo("B"));
}
```

This would hopefully avoid capturing unnecessary context into the Action (because it wouldn't exist).  Async code becomes slightly simpler (no need to specify `async` again) also.

It might also make things like #4242 easier to get right.

Considerations:
- As written, this would not conflict, but we would certainly want to drive users towards this as a preferred option over the existing `Assert.Multiple(() => { ... });` option.  So we could consider using a different name to avoid ambiguity.

**Comment by OsirisTerje** [comment]
This would be a syntax like FluentAssertions `AssertionScope`.  

@andrewimcclement Can you elaborate on what the concern is about capturing context in the Action?

If implemented, it has to be a another method, could use the same word `AssertionScope`, so that we don't introduce a breaking change.

For me, I find the existing syntax easy, and this more confusing.  Further, will these not trigger the IDE0063 (Simplify using statement).  If it does, and the user inadvertency accept it, it will cover all asserts to the end of the test.  Not exactly what one would normally want.

@jnm2 You're on the team - and upvoted this.  Can you comment on your thoughts about it?

**Comment by manfred-brands** [comment]
Although I like the idea, there will be people that would call this statement without a `using` at all. That would mean the `multiple` is not reset. Unless nunit does that at the end of each test.
The current syntax has no such issue.

**Comment by OsirisTerje** [comment]
@manfred-brands I absolutely do agree.  

But something like:
```cs
using (new AssertionsScope())
{
.....
}
```

would solve that I think.

But again:  Why do you feel this is a better syntax?  (Curious)

**Comment by jnm2** [comment]
> If implemented, it has to be a another method, could use the same word AssertionScope, so that we don't introduce a breaking change.

I don't see why it has to be another method, since we could have `void Multiple(Action)` and `IDisposable Multiple()` overloads, but I agree that the word `Scope` should be included so that the API is less confusing.

> Although I like the idea, there will be people that would call this statement without a using at all. That would mean the multiple is not reset. 

NUnit analyzers can help.

> But again: Why do you feel this is a better syntax? (Curious)

- It's automatically async-friendly.
- Tools can analyze variable usage better between the inside and outside of the block. Things like definite assignment of variables will work, and nullability flow analysis.
- It's a familiar style of API for me, and it's the choice I go with any time I have the choice (versus taking a delegate).
- (least important by far to me) It's lighter-weight from a performance perspective, versus a lambda capturing class.

**Comment by OsirisTerje** [comment]
Ok, got it.  

So, should it be `Assert.MultipleScope`,  which would probably be the same as "new MultipleScope()`, 
or should it be something along `AssertionScope` ?

Or something else?   Suggestions @nunit/framework-team ?  @andrewimcclement

**Comment by andrewimcclement** [comment]
Disabling IDE0063 via NUnit.Analyzers would likely be a good complement to this feature.
I don't mind about the terminology, though I think MultipleScope isn't necessarily ideal - it doesn't convey that it is related to assertions.  AssertionScope seems fine.  If we wanted a method on Assert that wasn't `Assert.Multiple()`, maybe `Assert.Scope()` would work?

**Comment by jnm2** [comment]
.NET 9 is adding a new API, System.Threading.Lock, with a method called EnterLockScope. What do you think about `Assert.EnterScope()` or `Assert.EnterMultipleScope()`?

**Comment by manfred-brands** [comment]
I don't even think IDE0063 will come up as no variable is assigned, unless we think we need to return a Test multiple context or so. In that case we can indeed look at the analyzer to suppress it.

I do like `EnterMultipleScope` as it indicates better. `EnterScope` only raises questions about what kind of scope.

**Comment by stevenaw** [comment]
While I like the idea of naming an "AssertionScope" without the "multiple" identifier to encourage more arbitrary use but I don't have a strong preference. Someone may indeed want to use it for multiple asserts, or someone may instead want to use it for some isolated or _scoped_ setup of a single assert in a larger method.

I do think that, whatever the name, semantically it should behave as a multiple assert block - which I suppose then speaks to @manfred-brands point about their preference to include `Multiple` in the name.

I suppose a third middle-ground here could be something like below. Debatably then, `RunAll` may or may not be the default.

```
public static IDisposable EnterScope(ScopeBehaviour behaviour);

public enum ScopeBehaviour {
  RunAll,
  StopOnFirstFailure
}
```

**Comment by stevenaw** [comment]
> > Although I like the idea, there will be people that would call this statement without a using at all. That would mean the multiple is not reset.
>
> NUnit analyzers can help.

Agreed re: analyzers.

Should the framework still track these internally to dispose of at the end of a test? If so, I think we should ensure we can handle nested scopes and define if they must be disposed in order and what should happen if a parent is disposed before it's child by a user. Would such a case automatically dispose the child or throw an error?

**Comment by stevenaw** [comment]
@nunit/framework-team It sound like this could help in scenarios where a multiple assertion has separate subgroupings which each must fail-fast (https://github.com/nunit/nunit/issues/4720). I'm promoting this from an `idea` to something we think we want to happen in the framework, but please feel free to chime in if you disagree

**Comment by manfred-brands** [comment]
I think the situation described in #4720 is trying to shoe horn multiple tests into one.
Instead of one `Assert.Multiple` with nested standard behaviour, these could all be separate `Test`. 
NUnit executes all tests and each test has a _StopOnFirstFailure_ behaviour.
Common initialization can be done in a `OneTimeSetUp`.
To me it seem like looking for a problem to a solution instead of the other way around.
It makes NUnit more complex for no added benefit.

**Comment by stevenaw** [comment]
That's a fair point, I hadn't considered that. I'd be fine with leaving the `ScopeBehavior` part out of the initial public API of this Disposable proposal, at least until we hear more in #4720 

How do you feel about the rest of it? It seemed like the team generally got behind this idea but that discussion stalled out a bit during design

**Comment by manfred-brands** [comment]
I'm happy with an `IDisposable` pattern.
Just not sure if we should expose the actual class/implementation.
I rather have it more integrated into the `Assert` class.

```csharp
internal sealed class AssertionScope : IDisposable
{
}

public class Assert
{
  public static IDisposable EnterMultipleScope() => new AssertionScope();
}

public class MyTest
{
    [Test]
    public void TestProperties()
    {
        var instance = ObtainAnInstance();
        Assert.That(instance, Is.Not.Null);
        using (Assert.EnterMultipleScope())
        {
            Assert.That(instance.PropertyA, Is.EqualTo(ExpectedValueOfPropertyA));
            Assert.That(instance.PropertyB, Is.EqualTo(ExpectedValueOfPropertyB));
            Assert.That(instance.PropertyC, Is.EqualTo(ExpectedValueOfPropertyC));
        }
    }
}
```

Note that this still allows extending by end-users using aggregation instead of inheritance.

```csharp
internal sealed class MyUserScope : IDisposable
{
    private IDisposable _NUnitScope = Assert.EnterMultipleScope();

    public MyUserScope ()
    {
        // Do what ever the user needs to setup in its scope
    }

    public void Dispose() 
    {
        // Cleanup user scope
        _NUnitScope.Dispose();
     }
}

public class MyTest
{
    [Test]
    public void TestProperties()
    {
        var instance = ObtainAnInstance();
        Assert.That(instance, Is.Not.Null);
        using (new MyUserScope())
        {
            Assert.That(instance.PropertyA, Is.EqualTo(ExpectedValueOfPropertyA));
            Assert.That(instance.PropertyB, Is.EqualTo(ExpectedValueOfPropertyB));
            Assert.That(instance.PropertyC, Is.EqualTo(ExpectedValueOfPropertyC));
        }
    }
}
```

**Comment by andrewimcclement** [comment]
Favouring composition over inheritance makes sense to me - we can keep it internal until we find a killer use case that requires it to be public.

**Comment by stevenaw** [comment]
@manfred-brands Would `public sealed` also work for you? @OsirisTerje how strongly do you feel about being able to instantiate the class directly like in your strawman code sample here: https://github.com/nunit/nunit/issues/4587#issuecomment-1854302483

I like the composition over inheritance approach, but I'm not sure if making this `public sealed` could also improve discoverability - if that is a pattern we also want to enable. I think the most common way to discover things in NUnit is on the `Assert` class via Intellisense which would be served either way here

**Comment by manfred-brands** [comment]
@stevenaw If it is `public` it allows users to use `new AssertionScope()`. If it is not `public` they are guided into the `Assert.EnterMultipleScope()`.

There is already too much public in NUnit which means we can't make any breaking changes even though we don't change how it is supposed to be used.

**Comment by stevenaw** [comment]
@OsirisTerje do you feel strongly about being able to instantiate the scope directly like this?

```csharp
using (new AssertionsScope()) {

}
```

as opposed to requiring initialization like:

```csharp
using (Assert.EnterMultipleScope()) {

}
```

I don't have a strong opinion either way, I'm mostly just trying to establish a consensus on the design.

**Comment by OsirisTerje** [comment]
Me neither:  From reading back, it seems majority points to the second option there.

**Comment by stevenaw** [comment]
Great, thanks! Sounds like we have a design.

**Comment by manfred-brands** [comment]
I created a draft PR for discussion. Especially for async methods using the `EnterMultipleScope` is much nicer.

However there is one difference between the old and the new method in case an exception is thrown _after_ a failing assert.

In the original code, the `Assert.Multiple` has a `finally` which only decrements the `MultipleAssertLevel`.
The exception is then re-thrown and we never get to the code that throws the `MultipleAssertException`.
The original exception is then caught higher up (as if there was no `Assert.Multiple`).

In the new code, the `Dispose` does both actions, throws the `MultipleAssertException` and the original exception is lost.

> C# 4 Language Specification § 8.9.5: If the finally block throws another exception, processing of the current exception is terminated.

There is a similar scenario on stackoverflow:
* [how-can-i-check-if-any-exception-has-already-been-thrown](https://stackoverflow.com/questions/17866511/how-can-i-check-if-any-exception-has-already-been-thrown) 
* [determine-if-executing-in-finally-block-due-to-exception-being-thrown](https://stackoverflow.com/questions/3301507/determine-if-executing-in-finally-block-due-to-exception-being-thrown)

The two solutions are either:
1. Call an `scope.Complete()` method. If an exception is thrown that will not be set. This however relies on user to add it.
2. Use the equivalent of the existing `Assert.Multiple` with an `Action`.

If we cannot detect a pending exception is this something we can live with? 

The earlier assertion failures could be the cause of the exception in the first place (e.g. Is.Not.Null)
If not and the failures are fixed, the exception re-surfaces.

If we cannot live with this for existing behaviour, then I can update the PR to restore the original `Assert.Multiple` code.

**Comment by stevenaw** [comment]
Good catch, I hadn't thought about that. I don't have other ideas for immediate solutions.

Another, separate edge case: The callback based approach of `Assert.Multiple` enforces that an inner block will always end before an outer one. An `IDisposable` option opens the possibility that the scopes may be disposed out of order - or even passed around or stored in a class variable. These would all be misuses of the API, of course, but should we guard against or alert about them?

**Comment by stevenaw** [comment]
An idea: Would making `AssertionScope` a `ref struct` help here? It wouldn't be able to implement the `IDisposable` interface, but it could still participate in `using` statements if it were shaped properly and guaranteed by the compiler not to outlive the test method (though I'm not at a computer to verify if it would also get flagged by the compiler if not explicitly disposed)

**Comment by manfred-brands** [comment]
> Another, separate edge case: The callback based approach of `Assert.Multiple` enforces that an inner block will always end before an outer one. An `IDisposable` option opens the possibility that the scopes may be disposed out of order - or even passed around or stored in a class variable. These would all be misuses of the API, of course, but should we guard against or alert about them?

Good questions.

People can forget to Dispose it completely. We should probably detect that after any test.
Out of order can be detected by the `AssertionScope`, if the level in the dispose is not the same as the one set in the constructor.

I will update the PR with the above.

The Microsoft CA2000 analyzer should fire if the return value is not disposed. Unfortunately it is not enabled by default.
The NUnit.Analyzer could maybe do some detections, but it also is not used by default.

**Comment by stevenaw** [comment]
Thanks @manfred-brands !

Digging more into the "assertion scope lifetime" comment above (https://github.com/nunit/nunit/issues/4587#issuecomment-2226769908) it would appear that the upcoming .NET 9 Lock Scope feature mentioned further up by @jnm2 has chosen to use `ref struct` for their own scope class (https://learn.microsoft.com/en-us/dotnet/api/system.threading.lock.scope?view=net-9.0)

**Comment by andrewimcclement** [comment]
Thanks for putting the draft PR together @manfred-brands , it looks very nice to use.

**Comment by manfred-brands** [comment]
@stevenaw I tried to convert the `AssertionScope` into a `ref struct`, but that makes `async` methods impossible:

![image](https://github.com/user-attachments/assets/90ab0c8d-a08f-4c48-aa71-b3a3e2e8fa21)

Even when compiling with SDK 9.0-preview6, I still get an error:

```
Assert.cs(244,20): error CS4007: Instance of type 'NUnit.Framework.Assert.Scope' cannot be preserved across 'await' or 'yield' boundary.
```

Even if it worked, we would then requires user to use C#13 which is not yet released and in a non-LTS SDK.

So I reverted back to the class.

**Comment by manfred-brands** [comment]
I added a commit to guard against non or out of order disposal.

**Comment by stevenaw** [comment]
> I tried to convert the AssertionScope into a ref struct, but that makes async methods impossible:

@manfred-brands 
Right, of course, that makes perfect sense. Thanks for trying! Agreed `ref struct` is not right there
