### ISSUE TITLE
Remove the Mixed Platforms build configuration

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#459]
The solution keeps adding either a Mixed Platforms platform or an Any CPU platform when we add projects because of the projects that target x86/x64. To fix,

-  Move the C++ test projects out to their own solution. We can build and test with them when needed.
- Remove the nunit.agent.x86 project from the solution.
- Build nunit.agent.x86.exe from the nunit.agent.exe project using MSBuild in NUnit.proj. We do this in NUnit 2.6.4.

**Comment by CharliePoole** [comment]
@rprouse I think you intended to do this, right?

**Comment by rprouse** [comment]
Yes
