### ISSUE TITLE
VS 2022 Test Explorer shows tests multiple times

### ISSUE THREAD

**Issue by preblelaw** [nunit/nunit#4593]
Until recently, Test Explorer would group by 'standard' traits like Category, but not by custom PropertyAttributes. Now custom PropertyAttributes are treated like standard traits, and tests are being listed multiple times. The tree marked with red/orange began appearing in the last few weeks. Test Explorer used to only show the tree marked with green.
![image](https://github.com/nunit/nunit/assets/155109668/79241f86-85c0-4266-bbaa-0be7c0a5a86a)

AssociatedTestCase is the custom property:

**Definition**
```
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    public class AssociatedTestCaseAttribute : PropertyAttribute
    {
        public AssociatedTestCaseAttribute(string url) : base(url) { }
    }
```

**Usage**
```
        [TestCaseSource(typeof(TestCaseSources), "IsModelContract")]
        [Parallelizable(ParallelScope.None)]
        [Category("Code Links")]
        [AssociatedTestCase("Core Test: Outpatient Code Links")]
       // [AssociatedTestCase("Core Test: Contract Loading: By MS-DRG and By CPT Classifiers")]
        public void CPRO_EC_OPByCPT_ImportCodeLinks_CPTToAge(bool IsModelContract)
```

Here you can see the standard Category "Code Links" and the custom attribute AssociatedTestCase "Core Test: Outpatient Code Links".

**Comment by OsirisTerje** [comment]
Can you please upload a repro project?

You can a) Add it as a PR to https://github.com/nunit/nunit3-vs-adapter.issues, add it as a separate folder named IssueXXX where the XXX is the issue number, or b) Add it as a zipped attachment here , or c) Add it to your own repo and just post the link. 

Make it as small as you can, it should compile "as is".
