### ISSUE TITLE
AssemblyVersion needed

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#46]
A nice feature would be a Version as a Attribute. When the assembly version is at least the value, the test is active. If the assembly version is to low, the test will be ignored.
The version could be the version of the assembly which contains the test or delivered by a public static class from a special property (as it is in testcasesource).

Testcase and Testfixture and so on must also have this feature.

See discussion at https://bugs.launchpad.net/nunit-3.0/+bug/628884

**Comment by rprouse** [comment]
Another enhancement that has been open for a long time without interest. Close as low value?

**Comment by jnm2** [comment]
I agree.
