### ISSUE TITLE
Add `DateTime`/`TimeSpan` support for inequality tolerance

### ISSUE THREAD

**Issue by RenderMichael** [nunit/nunit#4600]
It would be nice if the following code worked:

``` csharp
public static DateTime LastDateAccessed { get; set; } // simulate a remote value

[Test]
public void TestMe()
{
    DateTime beforeUpdate = DateTime.UtcNow;

    // Do operation
    LastDateAccessed = DateTime.UtcNow.AddMilliseconds(-50); // some kind of timing imperfection on the server

    // This fails because of the timing issue
    Assert.That(LastDateAccessed, Is.GreaterThan(beforeUpdate));

    // It would be nice to do this
    Assert.That(LastDateAccessed, Is.GreaterThan(beforeUpdate).Within(TimeSpan.FromSeconds(1)));
}
```

For consistency, this should probably be done on all constraints that extend [`ComparisonConstraint`](https://github.com/search?q=repo%3Anunit%2Fnunit+%22%3A+ComparisonConstraint%22&type=code).

I am willing to take up the task. I just want to make sure this is kind of change would be accepted.

**Comment by RenderMichael** [comment]
My workaround, using the above example:

``` csharp
Assert.That(LastDateAccessed, Is.InRange(beforeUpdate - TimeSpan.FromSeconds(1), beforeUpdate + TimeSpan.FromSeconds(1)));
```

But it's less elegant or intuitive.

**Comment by RenderMichael** [comment]
Opened PR #4618

**Comment by OsirisTerje** [comment]
@RenderMichael Can you please check this package https://www.myget.org/feed/nunit/package/nuget/NUnit/4.1.0-alpha.0.1

**Comment by RenderMichael** [comment]
Works flawlessly 👍 
![image](https://github.com/nunit/nunit/assets/12619902/e364cfb5-f952-488a-8368-fe5858108cde)

**Comment by RenderMichael** [comment]
@OsirisTerje opened https://github.com/nunit/docs/pull/907, let me know if there's something else you had in mind as I've never contributed docs before.
