### ISSUE TITLE
WpfMessagePumpStrategy - change from Dispatcher.Run to Dispatcher.PushFrame 

### ISSUE THREAD

**Issue by soerendd** [nunit/nunit#4602]
Currently when awaiting an awaitable test nunit post to the context and calls Dispatcher.Run. In the Post a continuation is scheduled which calls ExitAllFrames on the dispatcher. This leads to some problems if there is already a frame running. 

My idea (and I have a working version) is to create a DispatcherFrame and call PushFrame on the Dispatcher. If the posted action is completed just set frame.Continue to false. This will cause the PushFrame to return and will not disturb a previously pushed frame. Would you guys be interested in a PR for this?

**Comment by jnm2** [comment]
Yes, this sounds perfect! Thank you!

**Comment by OsirisTerje** [comment]
@soerendd Can you please check this package https://www.myget.org/feed/nunit/package/nuget/NUnit/4.1.0-alpha.0.1

**Comment by soerendd** [comment]
@OsirisTerje In my local tests everything works fine...
