### ISSUE TITLE
GitHub Actions fail on `master` for Windows and Linux builds

### ISSUE THREAD

**Issue by mikkelbu** [nunit/nunit#4606]
The builds are failing on `master` as our `global.json` expects version "8.0.100" for the SDK and the build agents - for Windows and Linux - now install 8.0.101. I guess we would like to update the `global.json` at some point, but I'm unsure if we can expect all contributors to be updating immediately when a new version comes out, so perhaps we should initially just supply a more specific version than `8.0.x` in `setup-dotnet` and then bump the `global.json` and the CI agents later ?

![image](https://github.com/nunit/nunit/assets/1007631/a560859e-7ed0-4a9a-86d1-c4aa19727255)

**Comment by SeanKilleen** [comment]
@mikkelbu can we use rollForward in the global.json?.https://learn.microsoft.com/en-us/dotnet/core/tools/global-json

**Comment by manfred-brands** [comment]
We could use rollForward to latest patch only and change the .net install to 8.0.1xx. That way we use bugfixes but not new possibly incompatible features.

**Comment by OsirisTerje** [comment]
I agree ,  Roll forward for patches should do it.

**Comment by OsirisTerje** [comment]
@mikkelbu  The [global.json](https://github.com/nunit/nunit/blob/master/global.json) still points to 8.0.100, and I see the latest builds are all green https://github.com/nunit/nunit/actions/runs/7616486979   
Where do you see they're red ?

**Comment by manfred-brands** [comment]
@OsirisTerje You merged the PR that uses global.json to download that particular version, so the issue is sort of addressed with my caveat that we now assume github pre-installs .NET 6.0
