### ISSUE TITLE
EqualTo() gives wrong result

### ISSUE THREAD

**Issue by waacton** [nunit/nunit#4609]
After upgrading from 3.13.3 to 4.0.1 I have an unexpected test failure.

**Reproduction**
```c#
public enum Enumeration
{
    First,
    Second
}

public class Thing
{
    public double Number { get; }
    public readonly Enumeration Enumeration;
    
    public Thing(Enumeration enumeration)
    {
        Enumeration = enumeration;
    }
}

public class Test
{
    [Test]
    public void TwoThingsNotEqual()
    {
        var thing1 = new Thing(Enumeration.First);
        var thing2 = new Thing(Enumeration.Second);
        Assert.That(thing1, Is.Not.EqualTo(thing2)); // test fails
    }
}
```

NUnit thinks those two `Thing` objects are equal.

If I change `public double Number { get; }` to `public double Number;`, or remove the property entirely, the two objects are treated as not equal and the test passes.

**Comment by manfred-brands** [comment]
NUnit 3 only used reference comparison and regardless of the parameter passed to the Thing constructor, even if both are the same, the instances would compare as not equal.

Version 4 introduced a Property comparer which compares the values of properties. in your case Number, which in all cases is the same and the two instances are considered equal as the values of all properties are the same 

You have both a property and a public field, if you change the latter to a property, the test will succeed.

Although we could compare fields, one issue already mentions that those should not be compared as the might be implementation details. Maybe we could only compare public (read-only) fields. However MS actively promotes to use properties for value classes.

**Comment by manfred-brands** [comment]
Yes it only tests public properties as internal ones could be implementation details.
Look at it like this, a user of your class has only access to the public ones, if the comparison says, instances are different, it has no idea why as all properties the user can see are the same. 

Before NUnit4, users had to test each property separately to see if any of them was different. They cannot do that if those properties are not public.

If you want complete control over what is considered Equal and what not, you must implement `IEquality<T>` on your class.
