### ISSUE TITLE
Support for the new test runner

### ISSUE THREAD

**Issue by RenderMichael** [nunit/nunit#4612]
With the announcement of the new [MSTest Runner](https://devblogs.microsoft.com/dotnet/introducing-ms-test-runner)

As well as this enticing issue about NUnit support: https://github.com/microsoft/testfx/issues/2164

Is the NUnit team interested in pursuing support for this new runner? Maybe the MSTest team will implement that support themselves if enough 👍s are raised.

Thanks

**Comment by OsirisTerje** [comment]
Yes, we will pursue support for this runner.  Stay tuned :-)

**Comment by OsirisTerje** [comment]
@RenderMichael I assume you are aware, but for others, the NUnitLite runner is very similar (and predates) to this new Microsoft runner.  See https://docs.nunit.org/articles/nunit/running-tests/NUnitLite-Runner.html and https://www.nuget.org/packages/NUnitLite
