### ISSUE TITLE
Implement API for composable and reusable test setups

### ISSUE THREAD

**Issue by fakefeik** [nunit/nunit#4623]
## The problem

I use NUnit for all my tests, be it unit, functional or end-to-end using browser. For many of these tests I have to write some complex setup/teardown logic. In NUnit, setup/teardown logic is usually written in [SetUp]/[TearDown]-annotated methods, for reusability these methods are extracted to base class.

Now imagine I need a container, and a browser for my tests, what do I do? Write test bases!

```csharp
class MyTest : BrowserTestBase { /* our tests live here */ }
class BrowserTestBase : ContainerTestBase { /* we set up and dispose of browser here */ }
class ContainerTestBase { /* setup and dispose of container */ }
```

But what if I now need an organization/user for many of my test fixtures? should I write `class OrganizationTestBase : BrowserTestBase`? what if I need an organization, but don't need browser? should it be `BrowserTestBase` inherits `OrganizationTestBase` inherits `ContainerTestBase`? With inheritance approach our test bases could quickly become unmaintainable as our test complexity increases.

## The solution

We can use composition of setups instead of inheritance, like this:

```csharp
class MyTest
{
  // we can invent some attribute like [TestConfiguration],
  // or just search for Configure method with reflection, like ASP.NET Core does with its Startup.cs
  public void Configure(ISetupBuilder fixture, ISetupBuilder test)
  {
    fixture
      .UseSimpleContainer()
      .UsePlaywright();
    
    test
      .UseSetup<BrowserPerTestSetup>();
  }
}
```

we can now easily add/modify our test's behaviour without need to modify base classes:

```diff
...
    fixture
-     .UseSimpleContainer();
+     .UseSimpleContainer(ConfigureContainer)
      .UsePlaywright();
    
    test
+     .UseOrganizations(c => c.AddOrganization("seller", OrgType.Seller))    
      .UseSetup<BrowserPerTestSetup>();
...

+  private void ConfigureContainer(ContainerConfigurator builder) { ... }

...
```

This model is heavily inspired by ASP.NET Core's middlewares and has some additional advantages:
- code of our setups is now reusable, we can put our `UseSimpleContainer` higher into suite setup changing just one line of code
- like in ASP.NET Core, our setup code can be moved out of our tests into some nuget packages for better reusability (for example, `NUnit.Extensions.DependencyInjection`, `NUnit.Extensions.Logging`, `NUnit.Extensions.Playwright` and so on)

## The code

I've made a quick attempt at writing such a library, the result lives [here](https://github.com/skbkontur/nunit-middlewares), I believe the result is a simple yet powerful library that opens up a lot of opportunities to write better and more reusable code in tests.

The API itself is not stable, but I think the main idea of this sort of extensibility point for NUnit is something worth looking into.

## The question

The main question I have is: does something like this have a place inside NUnit project itself, inside [NUnit](https://www.nuget.org/packages/NUnit) package? Or in some `NUnit.Extensions` package governed by NUnit team?

Another question is: can this paradigm replace the original `[SetUp]`/`[TearDown]`-based tests configuration where we actually setup test's *lifecycle methods* rather than setting up *behaviours* that test needs. It has quite a few problems that new approach seems to solve:
- SetUps/TearDowns nudge developers to use deep inheritance chains like in the example above
- SetUps/TearDowns are responsible for setting up many separate *behaviours*, for example, my BrowserTestBase can be responsible for setting up playwright, browser context, page, authorization, collecting traces/screenshots on test failure, etc. This quickly becomes hard to maintain and extend and violates single responsibility principle
- It is not easy to reuse code in SetUps/TearDowns, if I have `BrowserTestBase` inherits `ContainerTestBase`, but my tests do not need container for some reason, the options I have are either use `BrowserTestBase` anyway or Ctrl+C SetUps/TearDowns from `BrowserTestBase` into new TestBase class
- It is not easy to parallelize tests when they set up some private fields in test classes

New pattern also looks like something that has already been done in in another (not test-related) frameworks, like [middlewares](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/middleware) in `ASP.NET Core` or [hooks](https://react.dev/reference/react/hooks) in `React`. In both examples new approach allowed for better composibility and reuse of code. In both examples, code written with new approach is easier to maintain and reuse. Maybe it's time we bring the same approach to the test world?

**Comment by OsirisTerje** [comment]
Thanks for your suggestion.  NUnit has a policy of trying to avoid taking dependencies of external libraries.  Bringing the code into the NUnit project would also be too much for the special cases you line up.  Although the idea may be good in certain cases, it is probably best to keep this outside the NUnit project.

**Comment by fakefeik** [comment]
but the code in question has zero dependencies on external libraries

perhaps I didn't word it correctly, but the library I linked to is an example of what could be implemented to make extending NUnit simpler, I did not suggest making a dependency in NUnit package to some external `NUnit.Middlewares` package

your position is clear tho, thank you for response
