### ISSUE TITLE
Generic TestCase and TestCaseParameter support 

### ISSUE THREAD

**Issue by stevenaw** [nunit/nunit#4632]
As a follow-up to https://github.com/nunit/nunit/issues/1215
Where we allowed the passing of `Type` objects in a `TypeArgs` property to allow consumers greater control over the type arguments used in generic test methods.

This would allow the creation of generically-typed TestCase attribute. We may want to provide a few overloads here to account for up to n different strongly typed args.

This would be on modern (NET 6+) frameworks. See a sample snippet here: https://github.com/nunit/nunit/pull/4620#discussion_r1493936280

**Comment by OsirisTerje** [comment]
@stevenaw @manfred-brands Where are we with this now?   

From the https://github.com/nunit/nunit/pull/4620#discussion_r1493936280 it looks like it works, except for .net framework, which is ok.  Are am I missing something here ?

**Comment by manfred-brands** [comment]
It would be a matter of adding the new attributes and tests under a conditional compilation.
@stevenaw would you like me to take this?

**Comment by stevenaw** [comment]
Feel free @manfred-brands thanks!

**Comment by stevenaw** [comment]
We might've missed a PR link here.
@manfred-brands was this one fixed by #4755 ?

**Comment by manfred-brands** [comment]
@stevenaw Yes, indeed. I added the link.

**Comment by stevenaw** [comment]
Thanks!

**Comment by OsirisTerje** [comment]
We don't have this in the ordinary documentation, do we ?
