### ISSUE TITLE
NUnit publish plugin for Jenkins doesn't create attachments file

### ISSUE THREAD

**Issue by mcichonqa** [nunit/nunit#4633]
Hi, Im struggling with NUnit plugin for publish test results in Jenkins and Im able to publish test results, but without test attachments(files created during test execution). My question is, does this plugin is ready for create attachments? In my test result xml file, attachments were added like this:

```
<attachments>
                <attachment>
                  <filePath>C:\FileTasks\Test.txt</filePath>
                </attachment>
</attachments>
```

I found one thread about that in stackoverflow, but it is very old topic https://stackoverflow.com/questions/45954480/nunit-test-report-does-not-publish-attachments
Could you explain please how can I achieve attachments in jenkins or it is not achievable?

Thanks in advance.

**Comment by OsirisTerje** [comment]
Seems the Jenkins guys have not fixed the issue.  Have you checked with them?

**Comment by mcichonqa** [comment]
@OsirisTerje Thanks, I have reported that here https://github.com/jenkinsci/nunit-plugin/issues/96

**Comment by stevenaw** [comment]
@mcichonqa 
Terje is right that this is an issue on the Jenkins plugin side. One option you could consider in the absence of a fix there is to ensure all attachments for a run are in a common directory, and then use the separate `archiveArtifacts` step in Jenkins.

For example:
https://www.jenkins.io/doc/pipeline/tour/tests-and-artifacts/
