### ISSUE TITLE
nunit.engine project is not built before projects that have dependency

### ISSUE THREAD

**Issue by boltomli** [nunit/nunit#465]
Repro steps:
1. Open solution in VS2013
2. Clean build
3. Build
Build errors are seen.

**Comment by boltomli** [comment]
Tried build NUnitEngine manually after clean, then rebuild can succeed.
https://github.com/boltomli/nunit/commit/3451d99cf0546e70f892dd6b3b7902ea5daf17c0 is committed as an attempt to avoid the build error,

Thanks,
Song

**Comment by rprouse** [comment]
Could you submit a pull request for your change?

**Comment by CharliePoole** [comment]
The order of building is based on dependencies. If there's a problem that's fixed by changing the order of the projects in the solution file, that's an accidental fix, and probably not a permanent one.

What is the error you see initially? It would be best to document the problem first, so we can see it and then see it fixed.

Also, please tell us what source you are using.

**Comment by rprouse** [comment]
@boltomli is using a fork of this repository. I have tried building a clean solution for both the Mixed Platforms and Any CPU configurations and do not get any errors.

@boltomli, a few questions before we close this issue,

- Is your copy of the repository up to date?
- Can you copy the build output with the errors?
- Are you building in a VPC with one virtual CPU?
- Are you building Release or Debug? 
- Are you building Any CPU or Mixed Platforms? The second will be gone soon and the first has been fixed up.
- Are you doing a rebuild, building after a fresh get, a clean then build or what?

If we don't hear back, we will close this issue. If we do and you get back with errors we can reproduce, we can always re-open the issue.

**Comment by boltomli** [comment]
Thank you for the guidance. Sorry for I didn't have stable time during the week thus the slow response.

I'm fine to close the issue and will be happy to provide any new input if I have in the future.

1. I tried another clean build with VS2012, and didn't reproduce the error.
2. I now suspect it's related to a rather old config mixed here, but can't really figure out since the environment might be rather rare so few will trigger it. Plus, we now know it's OK with a totally brand-new  fresh clone.

Answer the questions you need below. (sorry again for I'm not familiar with MD yet)
    Is your copy of the repository up to date? - Yes, just synchronized.
    Can you copy the build output with the errors? - Sorry I lost the environment and didn't retrieve the errors back.
    Are you building in a VPC with one virtual CPU? - No.
    Are you building Release or Debug? - Debug.
    Are you building Any CPU or Mixed Platforms? The second will be gone soon and the first has been fixed up. - Mixed. Glad to know we'll have a pure Any CPU build.
    Are you doing a rebuild, building after a fresh get, a clean then build or what? - Fresh get resolved the issue.

**Comment by rprouse** [comment]
Thanks for getting back to us. I am going to close this issue for now. Let us know if you have problems in the future.
