### ISSUE TITLE
Switch back to using macos-latest after latest becomes MacOS 14

### ISSUE THREAD

**Issue by stevenaw** [nunit/nunit#4650]
Follow-up to https://github.com/nunit/nunit/issues/4649
GitHub Actions currently has `macos-latest` targeting 12 so we've bumped up to explicitly targeting `macos-14`: https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

Once 14 is "latest" we can go back to "latest". This is currently planned to happen sometime in Q2 2024 (Apr-Jun 2024).

This will ensure we can get "latest" once latest goes past macos14 (in case we forget!)

**Comment by stevenaw** [comment]
@nunit/framework-team Curious for thoughts here. MacOS 16 is probably a ways out. Do we feel we need to do this or are we fine to leave it on `macos-14` for the foreseeable future?

**Comment by mikkelbu** [comment]
I can live with either option - as I see it in both cases we need to remember to revisit this at some point - or points - so perhaps it is easiest to leave it on `macos-14`.

**Comment by stevenaw** [comment]
Thanks! I like that idea
