### ISSUE TITLE
TestCaseSource that contains Exception with InnerException - not running tests

### ISSUE THREAD

**Issue by konrad-gora** [nunit/nunit#4659]
After updating NUnit 3 to NUnit 4 (4.1.0) my test cases with InnerException are not run. I'm using TestAdapter 4.5.0
```
[FixtureLifeCycle(LifeCycle.InstancePerTestCase)]
public class Tests1
{
    [TestCaseSource(nameof(GetSomeExceptionCases))]
    public void NoMethod_GivenException_ShouldPassTest(Exception testCase) => testCase.Should().NotBeOfType<string>();

    public static TestCaseData[] GetSomeExceptionCases() =>
    [
        new TestCaseData(new ArgumentNullException()),
        new TestCaseData(new ArgumentNullException("message", new Exception())),
    ];
}
```
![image](https://github.com/nunit/nunit/assets/6730064/ed95e072-7ba6-4f41-9f3b-a8991da45956)

When I downgrade NUnit to 3.14.0, both tests are passing.
![image](https://github.com/nunit/nunit/assets/6730064/63e0a513-e10e-46d4-a4de-225aff5f938f)

**Comment by stevenaw** [comment]
@konrad-gora thanks for the report.
We've noticed some EOL issues in test case display names. Does the name of the passing test case remain on one line?

**Comment by stevenaw** [comment]
This could be related to #4584

**Comment by manfred-brands** [comment]
@konrad-gora What is the package that implements your `Should` method? Is it calling into NUnit `Assert`. In that case you likely need a new version that is NUnit 4 compatible.

**Comment by konrad-gora** [comment]
> @konrad-gora thanks for the report. We've noticed some EOL issues in test case display names. Does the name of the passing test case remain on one line?

Yes, passing test have one line name.

**Comment by konrad-gora** [comment]
> @konrad-gora What is the package that implements your `Should` method? Is it calling into NUnit `Assert`. In that case you likely need a new version that is NUnit 4 compatible.
> 
> Can you replace your test with:
> 
> `public void NoMethod_GivenException_ShouldPassTest(Exception testCase) => Assert.That(testCase, Is.Not.InstanceOf<string>());`
> 
> Then switch NUnit versions.

Should() is from FluentAssertion. I changed the test like you suggested and it works in the same way (on both, NUnit 3 and NUnit 4). This assertion is just to have something inside.
When I was trying to debug it on NUnit 4, I put a breakpoint at the start of the test method and I wasn't hit.

**Comment by manfred-brands** [comment]
Thanks @konrad-gora. We can exclude this then.

**Comment by manfred-brands** [comment]
> To see if it is related to the name, can you set the `Name` property on the `TestCaseData` to something simple.

This seems to work:
```
new TestCaseData(new ArgumentNullException()).SetName("First"),
new TestCaseData(new ArgumentNullException("message", new Exception())).SetName("Second"),
```

**Comment by manfred-brands** [comment]
@stevenaw DisplayName.GetValueString calls (indirectly) Exception.ToString() which result in a stack trace, including a \r\n:

> System.ArgumentNullException: message ---> System.Exception: Some Exception Message\r\n   --- End of inner exception stack trace ---

Adding a case for `Exception` and formatting this like: `"ArgumentNullException: message, Exception: Some Exception Message"` works.

This still depends on the user not passing "\r\n" as part of the exception message.

**Comment by konrad-gora** [comment]
> > To see if it is related to the name, can you set the `Name` property on the `TestCaseData` to something simple.
> 
> This seems to work:
> 
> ```
> new TestCaseData(new ArgumentNullException()).SetName("First"),
> new TestCaseData(new ArgumentNullException("message", new Exception())).SetName("Second"),
> ```

Yeah, I tested it with providing names and tests passed.
