### ISSUE TITLE
`.ContainKey().WithValue()` and `.Or`/`.And` interact incorrectly

### ISSUE THREAD

**Issue by ssrmm** [nunit/nunit#4670]
Combining `Or`/`And` with the `DictionaryContainsKeyValuePairConstraint` produces incorrect results, see examples below.

The error messages in the failure cases imply that the expression is parsed in a weird/unintended way.

```csharp
[Test]
public void BugReport()
{
    var dictionary = new Dictionary<string, int>
    {
        { "a", 123 },
        { "b", 456 }
    };

    Assert.Multiple(() =>
    {
        Assert.That(dictionary, Does.ContainKey("a").WithValue(456).Or.ContainKey("b").WithValue(123), "Passes but should fail");
        Assert.That(dictionary, Does.ContainKey("a").WithValue(456).And.ContainKey("b").WithValue(456), "Passes but should fail");

        // Expected: dictionary containing key "c" or dictionary containing entry ["c", 456]
        // But was:  < ["a", 123], ["b", 456] >
        Assert.That(dictionary, Does.ContainKey("a").WithValue(123).Or.ContainKey("c").WithValue(456), "Fails but should pass");

        // Expected: dictionary containing key "c" and dictionary containing entry ["c", 456]
        // But was:  < ["a", 123], ["b", 456] >
        Assert.That(dictionary, Does.ContainKey("a").WithValue(123).And.ContainKey("c").WithValue(456), "Fails but for the wrong reason");
    });
}
```

**Comment by OsirisTerje** [comment]
Repro code here:   https://github.com/nunit/nunit.issues/tree/main/Issue4670

**Comment by OsirisTerje** [comment]
@Falco20019 @rprouse @mikkelbu  
This PR #3486 introduced the WithValue which seems to trigger a bug when using Or/And constraint expressions,  It might be because the or/and only looks at the immediate left and right constraints, and assumes they have been fully resolved - which they doesn't seem to be.  Or, it might be by design, ref docs on the or/and stating they resolve left->right.  I am not exactly sure how that is to be interpreted.  
The constraint stack also seems to contain two constraints on each side, both a DictionaryContainsKey and a DictionaryContainsKeyValue. If the WithValue had been a modifier, it should work, but now it seems to chain in a new constraint.  I am not sure if we have other places where this is being done.

**Comment by OsirisTerje** [comment]
Just to indicate how weird this is:
The given statement above,  
```csharp
 Assert.That(dictionary, Does.ContainKey("a").WithValue(123).Or.ContainKey("c").WithValue(456))
```
results in an Or constraint with Left and Right equal to 'c' and  ['c',456] respectively.  Failing of course, but should have passed

Note that the 'c' is wrong

However

```csharp
Assert.That(dictionary, Does.ContainKey("a").WithValue(123).Or.ContainKey("b").WithValue(789));
 ```
This pass, the right side value is false, but the key is does exist.

**Comment by Falco20019** [comment]
I can confirm that the issue is, that we have two constraines not linked properly. Technically, it should work to use the `And` (which would compare contains key AND contains key with value) on building. I will prepare tests and correct it.

**Comment by OsirisTerje** [comment]
I wonder if it would be better to have only one constraint, and using the WithValue as a modifier to that constraint.  We could still have the two Does.ContainKey and Does.ContainValue, but let both modify a single constraint.

**Comment by Falco20019** [comment]
Having only one would have also made it easier. But I didn't want to break public API and therefore added it as new one. Also, it would have made the match-check more complex. The PR is currently replacing the existing one added by `ContainsKey` with the combined one that matches the entry (checking for key + value pair).

In my opinion, `Does.ContainKey` and `Does.ContainValue` are still valid and have a different meaning then checking for a key-value-pair. So I would not mark them obsolete as they fullfil different use-cases. I'm also not sure if having one constraint that allows checking for key-only, value-only or key-value-pair would increase maintainability.

**Comment by OsirisTerje** [comment]
Fair point

**Comment by OsirisTerje** [comment]
@ssrmm Please verify that this work:  https://www.myget.org/feed/nunit/package/nuget/NUnit/4.2.0-alpha.0.10

**Comment by ssrmm** [comment]
Looks good. Thank you.
