### ISSUE TITLE
Reason for removing `TestCaseData.Categories`?

### ISSUE THREAD

**Issue by maettu-this** [nunit/nunit#4678]
When migrating from NUnit 2.6.4 to 3.14.0 I ran into a breaking change neither documented at https://docs.nunit.org/articles/nunit/release-notes/breaking-changes.html nor any other resource I am consulting:

**`TestCaseData.Categories` got removed**.

Workarounds I found was to use `myTestCaseData.Properties["Category"]` or `myTestCaseData.Properties[NUnit.Framework.Internal.PropertyNames.Category]` instead. While this seems to work, I find it quite inconvenient (the property string is only available internally in `NUnit.Framework.Internal`) and a bit non-orthogonal (obvious `SetCategory` but inexistent `Categories` nor `GetCategories`).

Background for having to retrieve `Categories`:

I am generating test cases based on the available physical test environment. A first stage generates a generic set of `TestCaseData` that describes the physical test environment, a second stage enriches `TestCaseData` with the effective tests. In order to achieve this, a helper merges the `Categories` of the first stage with those of the second stage.

**Comment by stevenaw** [comment]
I can't say exactly why it was removed but based on the commit message it looks to have been part of a refactoring to simplify the code and API and move towards the current property-based approach: https://github.com/nunit/nunit/commit/cce6b303e68e2fc8bf10a035fed4e3a89930da28 and    https://github.com/nunit/nunit/commit/119f504ea97be52a3c53171806828708c32e4f95

You're right that this should probably be added to the list of breaking changes.

**Comment by stevenaw** [comment]
@maettu-this I've put in a PR to update the documentation, thanks for catching this.

In case this change has caused you lots of updates across lots of places, one option which you may've already considered in your own migration to Nunit 3.14 is to add an extension method over `TestCaseData` to make a `GetCategories()` method to encapsulate this change on your end.

**Comment by maettu-this** [comment]
@stevenaw thanks for the hint, my code already implements a `TestCaseData` that encapsulates this, only needed to adjust two locations.

However, I still think the API now is non-orthogonal, as `SetCategory` as well as `SetProperty` are "public" while `PropertyNames.Category` is only available in `NUnit.Framework.Internal`. Making `PropertyNames` "public" would fix this.

**Comment by stevenaw** [comment]
Thanks @maettu-this 
FWIW, I agree with you on this:

> Making PropertyNames "public"

It's already publicly visible but moving this out of the internal namespace would be consistent with moving towards a public PropertyBag-based approach. These property names are already debatably part of a "public" API as well as they are output to XML where Nunit itself and other tooling may consume it.
