### ISSUE TITLE
add reason to archive https://github.com/nunit/dotnet-new-nunit

### ISSUE THREAD

**Issue by kasperk81** [nunit/nunit#4680]
in https://github.com/nunit/dotnet-new-nunit?tab=readme-ov-file#nunit-3-test-project-template-for-dotnet-new-cli, please add a reason why that repository was archived.

**Comment by OsirisTerje** [comment]
It is stated in the repo under the About section:
![image](https://github.com/nunit/nunit/assets/203432/c5de9fda-e255-46b0-81f7-c2a6b61ae50c)

When you write `dotnet new nunit` it is the same as this, except for the changes done last year.   They took over early 2003.   
You find the same code here:  https://github.com/dotnet/test-templates/tree/main/template_feed/Microsoft.DotNet.Test.ProjectTemplates.9.0/content
