### ISSUE TITLE
Consider deprecation of TestFixture's "leading args" generic type specification

### ISSUE THREAD

**Issue by stevenaw** [nunit/nunit#4682]
NUnit, or rather the dotnet runtime, will generally infer the type args passed into a generic type or method by NUnit attributes based on the values passed in. TestFixture has historically also supported more explicit user control for this in two ways:
- Explicitly specifying the `Type`s as  leading arguments, prior to any other arguments
- Explicitly specifying the `Type`s via the `TypeArgs` property

In https://github.com/nunit/nunit/issues/1215 we added the this functionality to  `TestCase` and `TestCaseSource` attributes, the latter via `TestCaseData`. A decision was made to only do this via `TypeArgs` property as the "leading types" form was found to be confusing (https://github.com/nunit/nunit/issues/1215#issuecomment-207003920). That comment also suggests considering phasing out the leading args form on `TestCaseSource`.

**Comment by manfred-brands** [comment]
@stevenaw Should we not first implement the generic attributes we previously discussed so developers can specify types more naturally as: `TestFixture<string>` etc.?

**Comment by stevenaw** [comment]
I thought about including that in here too. 🙂
Perhaps it's just me, but I'd thought then separate but complementary things.

For example, one caveat to the generic attribute discussion we'd want to consider there is that most `*Source` attributes could support passing of types for two purposes - generic method/class args, or potentially the "owning" type of the source data if different from the fixture itself.

**Comment by OsirisTerje** [comment]
@stevenaw I am not sure I understand what you mean by "leading types" form, du you mean explicitly adding typeinfo arguments?    I tried to understand the discussion there, but gave up.  Can you add some simple code examples of how this would look

The comment in #1215 , and the issue itself, is 8 years old now.   I would assume most devs today are used to generic type arguments (like @manfred-brands example above.  And also that they are used to the inference of generic type arguments when none are explicitly given.  To me that would look more modern than having to add typearguments in any other form.

Or, did I misunderstand what you're discussing :-)

**Comment by stevenaw** [comment]
Oh sorry @OsirisTerje . I think I mean this:

> do you mean explicitly adding typeinfo arguments?

Though I'm only thinking about the _last_ of the three below-listed forms

```csharp
[TestFixture(42, 100.0)]                                                    // Inference based
[TestFixture(42, 100.0, TypeArgs = new[] { typeof(int), typeof(double) })]  // Explicit, based on TypeArgs param
[TestFixture(typeof(int), typeof(double), 42, 100.0)]                       // Explicit based on providing the types as additional leading args
public class SpecifyArgs<T1, T2> {}
```

The example is untested, but all three of these should generate a closed generic of type `SpecifyArgs<int, double>`. The last two  allow explicit control of the closed generic types. The very last form is specific to `TestFixture` and is not supported on any other attribute, and was the form the comment suggested has caused confusion in the past. https://docs.nunit.org/articles/nunit/writing-tests/attributes/testfixture.html#generic-test-fixtures-with-parameters

I agree that generic attributes will provide a more natural way on modern runtimes, but as they're unsupported on .NET Framework I think we'd still need another way to support explicit typing there. I think it also makes sense to have the form we keep for .NET Framework _also_ supported on .NET Core for consistency as I don't think we want entirely different ways of doing the same thing on different runtimes. While true that the originating comment is 8 years old, it resonated a bit with me as even today we have an inconsistency with how our attributes support explicit typing.

I'm proposing that we can consider phasing out the `[TestFixture(typeof(int), typeof(double), 42, 100.0)]` form in favour of `[TestFixture(42, 100.0, TypeArgs = new[] { typeof(int), typeof(double) })]`. I think it would simplify the API and nicely compliment the addition of any truly generic `TestFixture<T>` attributes we may add in the future for .NET Core runtimes.

If we did choose to phase this out, it would obviously be considered a breaking change and require a major release.

**Comment by OsirisTerje** [comment]
I am fully agree with the syntax, the inference based and the explicit with TypeArgs.   They should be able to coexist.  And for net framework, we can just not support the inference there.  Ifdef's have been used before!  

To make this into a breaking change, do we really need to do that?  If we can keep the old syntax too, we would annoy less people.  We can add analyzer rules to push upgrades, or even add Obsolete to them, although some people gets annoyed by that too.  
Or, will it be impossible to cover it all due to the params?

**Comment by stevenaw** [comment]
Guidance/migration path would be tricky, and a big part of why I hadn't filed this earlier. I think we'd _have_ to use analyzers here as it's not really a particular API we'd be deprecating, just a way of using it. 

This _could_ be detected at runtime, but I'm not sure how we'd report it unobtrusively. As you say, annoyance is something we'd want to avoid.

Perhaps, if we did choose to explicitly direct away from this form, it works only be possible to do in documentation. Open to thoughts.

**Comment by stevenaw** [comment]
I'd also suggest that the absence of a clear, easy, and reliable way to guide away from this form would itself indicate we won't be able to remove it

**Comment by OsirisTerje** [comment]
I'm not sure if inference will work though.  It seems it has to be specified for attributes.  But that is also ok.

**Comment by stevenaw** [comment]
Even just from this short conversation I am starting to think that any deprecation of this form:

```csharp
[TestFixture(typeof(int), typeof(double), 42, 100.0)]
public class SpecifyArgs<T1, T2> {
  public SpecifyArgs(T1, T2) {}
}
```

May only be possible at the documentation level, _maybe_ also augmented by analyzers. That alone doesn't feel like enough warnings for us to eventually remove it but perhaps we could at least get the nudges in place. Though an analyzer telling consumers to change this without a path on our side to remove the underlying functionality could be asking effort of them with no value.

@OsirisTerje @manfred-brands If we were to nudge away from this (without actually committing to removal itself), should we only do it as a documentation-only update? @mikkelbu curious your thoughts here too given your experience on the analyzers side

**Comment by stevenaw** [comment]
I'm going to close this issue for now. While the issue has only been open a short time, the idea hasn't gained much traction with the team and the discussion so far is that it would be very difficult to properly and effectively communicate about this change as there isn't a particular API to mark `[Obsolete]`.
