### ISSUE TITLE
Either enable partial TestCaseSource combinatorial with Values, or document this is a limitation of TestCaseSource

### ISSUE THREAD

**Issue by maettu-this** [nunit/nunit#4691]
When parametrizing tests, there may be different kinds of parameters. In my case, a set of parameters relates to the capabilites of the physical test environment, the rest relates to the test itself.

For the first part I use `TestCaseSource`. For the rest I would like to use e.g. `Values`. However, currently this is not supported, loading results in e.g. "Not enough arguments provided, provide at least 2 arguments."

Here's a condensed sample:
```
using System.Collections;

using NUnit.Framework;

namespace TestCaseSourceCombinatorial
{
    public static class TestCaseSourceBase
    {
        public static IEnumerable SomeVariationOfTheTestEnvironment
        {
            get
            {
                yield return ("VariationA");
                yield return ("VariationB");
            }
        }
    }

    public class Test
    {
        [Test, TestCaseSource(typeof(TestCaseSourceBase), nameof(TestCaseSourceBase.SomeVariationOfTheTestEnvironment)), Combinatorial]
        public void Run(string someVariationOfTheTestEnvironment, [Values] bool someVariationForTheTest)
        {
        ////Do whatever is needed...
        ////Assert whatever is needed...
        }
    }
}
```
I would like to have NUnit detect that `TestCaseSource` only provides the first argument, but the second argument is already given by `Values`, so all is defined.

I understand if the NUnit teams decides to not support this, for whatever reason or poential conflict with something else. But in that case, I ask you to state this limitation or impact in the [documentation of TestCaseSource](https://docs.nunit.org/articles/nunit/writing-tests/attributes/testcasesource.html).

**Comment by stevenaw** [comment]
This is a good idea @maettu-this .
This was also raised recently in different issue (https://github.com/nunit/nunit/issues/4453) so I will close this one as a duplicate, but I will also chime in on the other issue that you also found this to be a helpful future addition.
