### ISSUE TITLE
Constraint helper classes modification request

### ISSUE THREAD

**Issue by kuskmen** [nunit/nunit#4694]
Hello, I was writing some custom constrains and I was wondering why not make all the constraint helper classes (Is, Has, Warn, Throws etc.) be partial so clients of NUnit can also add their custom extensions in the existing API?

**Comment by manfred-brands** [comment]
Unfortunately partial classes must be in the same dll. See restrictions in the [documentation](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/partial-classes-and-methods):

> All partial-type definitions meant to be parts of the same type must be defined in the same assembly and the same module (.exe or .dll file). Partial definitions can't span multiple modules.

**Comment by kuskmen** [comment]
Ah, my mistake, oh well sucks then :/

**Comment by stevenaw** [comment]
@kuskmen 
The `Is`, `Does` and `Has` classes are all abstract so that they may be inherited to add a "hook" for custom constraints. A great example can be found here: 

https://hermit.no/how-to-extend-the-nunit-constraints/
