### ISSUE TITLE
State that the scope of a `SetUpFixture` is limited to an assembly

### ISSUE THREAD

**Issue by maettu-this** [nunit/nunit#4695]
Currently, [SetUpFixture](https://docs.nunit.org/articles/nunit/writing-tests/attributes/setupfixture.html) states "all the test fixtures in a given namespace including nested namespaces below". However, if a root namespace spans accross multiple test assemblies this statement is wrong. Consider an assembly structure like:
```
Assembly MyScope.MySubscope1.Test
Assembly MyScope.MySubscope2.Test
...
```
Even if the `SetUpFixture` is placed into the `MyScope` root namespace, adding it only to the first assembly won't fulfill the "all the test fixtures in a given namespace" statement.

Proposing to more clearly state that a [SetUpFixture](https://docs.nunit.org/articles/nunit/writing-tests/attributes/setupfixture.html) is...

1. ...limited to the assembly it is contained in
2. ...only then "all the test fixtures in a given namespace including nested namespaces below"

Note that "Notes" currently include "A SetUpFixture outside of any namespace provides SetUp and TearDown for the entire assembly." which implies `SetUpFixture` is limited to an assembly, but only implicitly. One approach is to rearrange the notes like:

- A SetUpFixture is limited to an assembly.
- A SetUpFixture in a namespace will apply to all tests in that namespace and all contained namespaces of the assembly.
- A SetUpFixture outside of any namespace provides SetUp and TearDown for the entire assembly.

Another approach is to already state this in the very first sentence.
Or a combination of both.

Related to #4686 which requires to place a `SetUpFixture` into each required assembly. Somewhat related to #4106.

**Comment by OsirisTerje** [comment]
I thought we already had that pretty well documented here:  https://docs.nunit.org/articles/nunit/writing-tests/attributes/setupfixture.html#notes

But if you believe it will be more clear with your suggestions, feel free to raise a PR for this in the docs repo :-) 
Improvements are always welcome!

**Comment by maettu-this** [comment]
Fixed in docs, closing this issue.
