### ISSUE TITLE
Unexpected GreaterThan(NaN) behavior

### ISSUE THREAD

**Issue by shimat** [nunit/nunit#4711]
Hi,

even though `0.1 > double.NaN` returns False, `ClassicAssert.GreaterThan(0.1, double.NaN)` passes. Of course, the behavior is similar for any value other than 0.1. Is this the intended behavior?

NUnit 4.1.0 / .NET 8

```c#
public class Tests
{
    // Fail
    [Test]
    public void DirectGreaterThan() => ClassicAssert.IsTrue(0.1 > double.NaN);

    // Fail
    [Test]
    public void DirectLessThan() => ClassicAssert.IsTrue(0.1 < double.NaN);

    // Pass (???)
    [Test]
    public void NUnitGreaterThan()
    {
        ClassicAssert.Greater(0.1, double.NaN);
        Assert.That(0.1, Is.GreaterThan(double.NaN));
    }

    // Fail
    [Test]
    public void NUnitLessThanTest() => ClassicAssert.LessOrEqual(0.1, double.NaN);
}
```

**Comment by manfred-brands** [comment]
@shimat I can confirm this issue, but what is correct is not that straight forward:

NUnit will use [Double.CompareTo](https://learn.microsoft.com/en-us/dotnet/api/system.double.compareto?view=net-8.0&redirectedfrom=MSDN#System_Double_CompareTo_System_Object_)

This contains the following table:
![image](https://github.com/nunit/nunit/assets/8655218/9f6413ea-77bc-47a4-b712-972e76c1d73a)

```csharp
[Test]
public void CompareWithNaN()
{
    const double actual = 0.1;

    Assert.Multiple(() =>
    {
        Assert.That(actual.CompareTo(double.NaN), Is.Positive);
        Assert.That(double.NaN.CompareTo(actual), Is.Negative);
        Assert.That(double.NaN.CompareTo(double.NaN), Is.Zero);

        Assert.That(actual > double.NaN, Is.False);
        Assert.That(actual < double.NaN, Is.False);

        Assert.That(actual, Is.GreaterThan(double.NaN));
        Assert.That(actual, Is.Not.LessThan(double.NaN));
    });
}
```

Which matches the current NUnit behaviour, but not the C# expression.

**Comment by shimat** [comment]
Thank you, I understand. 
I still think GreaterThan when NaN is in the argument is misleading behavior, but I understand the reason and this issue can be closed.
