### ISSUE TITLE
Remove reference to the mailing list from CONTRIBUTING.md

### ISSUE THREAD

**Issue by stevenaw** [nunit/nunit#4730]
We mention "helping people on the mailing list" quite high up in https://github.com/nunit/nunit/blob/master/CONTRIBUTING.md

The mailing list was closed. We should consider removing the link as no new content or questions to answer will be posted.

**Comment by mikkelbu** [comment]
Perhaps we should replace the mailing list with a link to the Slack channel (although I'm rarely there 😄)

**Comment by stevenaw** [comment]
Great point about directing people to Slack instead!
