### ISSUE TITLE
QoL suggestion: fail fast in Assert.Multiple under debugger

### ISSUE THREAD

**Issue by MaceWindu** [nunit/nunit#4738]
While `Assert.Multiple` is nice for failure reporting on test runs, it is quite bad when you try to debug test compared to regular assert.

- with simple assert you get exception on assertion failure and could debug it
- with `Assert.Multiple` you get exception at the end where you probably lost all related test context already and need to put manual breakpoints inside of delegate to be able to debug first failure (or comment `Assert.Multiple` wrap)

I propose to throw assert exception on first failure if process is under debug (`Debugger.IsAttached == true`) with some kind of switch for backward compatibility. E.g. for those who use tests with debbugger for any reason or just enjoy having troubles during debugging.

**Comment by OsirisTerje** [comment]
Nice idea!  Could be enabled using a setting.  Would you like to do a PR for this ?

**Comment by MaceWindu** [comment]
Sure https://github.com/nunit/nunit/pull/4739

Need some help with:

- what else is missing?
- default value true or false? I assume it should be false for backward compat.

**Comment by OsirisTerje** [comment]
> default value true or false? I assume it should be false for backward compat.
Yes :-)

Can't think of anything else missing right now.

**Comment by OsirisTerje** [comment]
Need to raise a separate documentation issue for this.

**Comment by RenderMichael** [comment]
I am also interested in this.

Thanks to first-change exceptions, the debugger stops whenever anything throws, even if it is caught (unless Just My Code is enabled).

Therefore you could have something like

```csharp
if (DummyThrowForDebugger)
{
    try
    {
        throw new Exception();
    }
    catch (Exception)
    {
    }
}
```

And the debugger will still break here.

Alternatively, you could just call `System.Diagnostics.Debugger.Break();` directly.

This will enable debugger stopping without breaking `Assert.Multiple` functionality.

**Comment by OsirisTerje** [comment]
@RenderMichael But does the PR, which is now merged,solve this for you?

**Comment by RenderMichael** [comment]
It solves it in the same way commenting out `Assert.Multiple` would. We’d lose the second, third, etc. error message, and in order to debug through those, the first assertion needs to be commented out or resolved.

**Comment by MaceWindu** [comment]
Such behavior also could be useful. @OsirisTerje any objections to convert new boolean option to enumeration like that:

```cs
enum MultipleAssertBehaviorUnderDebugger
{
    Default,
    ThrowOnFirstFailure,
    ThrowOnEachFailure
}
```

**Comment by MaceWindu** [comment]
Actually I think we just need to follow @RenderMichael proposal and change behavior to throw first-change exceptions. Having two throw modes doesn't add any value

**Comment by MaceWindu** [comment]
Submited PR #4749

**Comment by MaceWindu** [comment]
Also submitted adapter PR [#1188](https://github.com/nunit/nunit3-vs-adapter/pull/1188)
