### ISSUE TITLE
TypeHelperTests.cs is orphaned

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#474]
PR #434 Created a new test file TypeHelperTests.cs but never added it to any of the projects.

**Comment by CharliePoole** [comment]
Looks like the tests were left out deliberately because they are not complete. Postponing.

**Comment by mikkelbu** [comment]
@CharliePoole The file was added in 7eda103d2d4500386203518ecba5de2772359d2c (also tests were added).
