### ISSUE TITLE
Allow fixture-level `Retry` attribute.

### ISSUE THREAD

**Issue by RenderMichael** [nunit/nunit#4747]
Hello,

I have instability in one of my features, requiring the use of the `RetryAttribute`.  In fact, my entire test fixture is related to the flaky feature, and I would like to add `[Retry(2)]` to the entire class.

However, the `RetryAttribute` is only allowed on test methods.

Is it possible to allow fixture-wide try logic?

**Comment by stevenaw** [comment]
Thanks for raising this @RenderMichael 
This has been a common request over the years

There's a bit of discussion in #2452 about it and a surprising number of edge case behaviors. At the time the team felt there that it would be tough to define a single way this retry should work for everyone. Sticking points included defining interaction with other fixture-level attributes and `OneTimeSetup`.

One thing that did come out of the discussion was https://github.com/nunit/nunit/issues/3719#issuecomment-1350272879 which describes a desire to have a generalized built-in way for the framework to allow users to apply an attribute at fixture or assembly level which would normally be applied method-level. It unfortunately has stalled out in design process. Would you be interested in helping out with that and lending your thoughts?

**Comment by stevenaw** [comment]
There's a few user-contributed custom attributes that have been shared in #2452 over the years which may also be of more immediate benefit to you too 🙂

**Comment by RenderMichael** [comment]
Chalk this issue up to me failing to search through the open issues before opening my own 😁 

Thanks for linking those issues, it's certainly something I'd love to help implement!

**Comment by stevenaw** [comment]
Not a problem @RenderMichael there's a quite a few open issues.

We'd absolutely welcome your help on it, both in implementation and on any outstanding design points if you had ideas  🙂
