### ISSUE TITLE
Multiple TestFixtureAttributes on Base class are not run

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#476]
The following was submitted in error to the defunct nunit-console project by @britianoates:

When we compile and run the following from nunit console, we only see the double version of the test.  We have seen both types run in Visual Studio.  We have rechecked our expectations against the documentation at http://www.nunit.org/index.php?p=testFixture&r=2.6.3.

    public class ExampleInheritenceProblem<T> : ExampleInheritenceProblemBase<T>
    {
        [Test]
        public void MyTest()
        {
            Assert.Pass(_type.ToString());
        }
    }

    [TestFixture(typeof(int))]
    [TestFixture(typeof(double))]
    public abstract class ExampleInheritenceProblemBase<T>
    {
        public Type _type;

        protected ExampleInheritenceProblemBase()
        {
            _type = typeof (T);
        }
    }

Expected:  2 tests to be ran
Actual:   1 tests is ran

**Comment by CharliePoole** [comment]
I would normally recommend putting the attributes on the derived class. Nevertheless, this looks as if it should work and the docs seem to say it will. One or the other needs to be fixed.

**Comment by britianoates** [comment]
Sorry about posting in the defunct repo.  I was linked there by the nunit.org contact us page.

Workaround: Giving 0 as a argument value somehow causes all TestFixtures to be found and executed.

public class ExampleInheritenceProblem<T> : ExampleInheritenceProblemBase<T>
{
    [Test]
    public void MyTest()
    {
        Assert.Pass(_type.ToString());
    }
}

[TestFixture(0, TypeArgs = new []{typeof (int)})]
[TestFixture(0, TypeArgs = new []{typeof (double)})]
public abstract class ExampleInheritenceProblemBase<T>
{
    public Type _type;

    protected ExampleInheritenceProblemBase()
    {
        _type = typeof (T);
    }
}

**Comment by britianoates** [comment]
Putting the attributes on the derived class did not fix the problem.  Once inheritance was added we lost all but one TestFixtureAttribute behavior.

**Comment by CharliePoole** [comment]
Thanks for pointing out the problem with the contact page. That explains a lot! It's now fixed.

**Comment by CharliePoole** [comment]
Odd... we'll check it out.

**Comment by constructor-igor** [comment]
I checked the scenario in 3.0Beta4 and cannot reproduce reported issue (see details below).
Probably, could you help me actual problem?

Details:
```c#
    public class ExampleInheritanceProblem<T> : ExampleInheritanceProblemBase<T>
    {
        [Test]
        public void MyTest()
        {
            Assert.Pass(_type.ToString());
        }
    }
    [TestFixture(typeof(int))]
    [TestFixture(typeof(double))]
    public abstract class ExampleInheritanceProblemBase<T>
    {
        protected Type _type;

        protected ExampleInheritanceProblemBase()
        {
            _type = typeof(T);
        }
    }
```
and can inform that NUnit3 Test Adapter executes 2 tests:

![image](https://cloud.githubusercontent.com/assets/1849690/9628841/fa79286e-5176-11e5-9b4d-d0ae8ea676a5.png)

Also nunit command line executes the 2 tests:
```xml
      <test-suite type="GenericFixture" id="0-1015" name="ExampleInheritanceProblem&lt;T&gt;" fullname="AssertSamples.ExampleInheritanceProblem&lt;T&gt;" runstate="Runnable" testcasecount="2" result="Passed" start-time="2015-09-02 10:33:05Z" end-time="2015-09-02 10:33:05Z" duration="0.215039" total="2" passed="2" failed="0" inconclusive="0" skipped="0" asserts="0">
        <test-suite type="TestFixture" id="0-1011" name="ExampleInheritanceProblem&lt;Double&gt;" fullname="AssertSamples.ExampleInheritanceProblem&lt;Double&gt;" classname="AssertSamples.ExampleInheritanceProblem`1" runstate="Runnable" testcasecount="1" result="Passed" start-time="2015-09-02 10:33:05Z" end-time="2015-09-02 10:33:05Z" duration="0.001603" total="1" passed="1" failed="0" inconclusive="0" skipped="0" asserts="0">
          <test-case id="0-1012" name="MyTest" fullname="AssertSamples.ExampleInheritanceProblem&lt;Double&gt;.MyTest" methodname="MyTest" classname="AssertSamples.ExampleInheritanceProblem`1" runstate="Runnable" seed="1687410536" result="Passed" start-time="2015-09-02 10:33:05Z" end-time="2015-09-02 10:33:05Z" duration="0.001170" asserts="0">
            <reason>
              <message>System.Double</message>
            </reason>
          </test-case>
        </test-suite>
        <test-suite type="TestFixture" id="0-1013" name="ExampleInheritanceProblem&lt;Int32&gt;" fullname="AssertSamples.ExampleInheritanceProblem&lt;Int32&gt;" classname="AssertSamples.ExampleInheritanceProblem`1" runstate="Runnable" testcasecount="1" result="Passed" start-time="2015-09-02 10:33:05Z" end-time="2015-09-02 10:33:05Z" duration="0.000806" total="1" passed="1" failed="0" inconclusive="0" skipped="0" asserts="0">
          <test-case id="0-1014" name="MyTest" fullname="AssertSamples.ExampleInheritanceProblem&lt;Int32&gt;.MyTest" methodname="MyTest" classname="AssertSamples.ExampleInheritanceProblem`1" runstate="Runnable" seed="1152481947" result="Passed" start-time="2015-09-02 10:33:05Z" end-time="2015-09-02 10:33:05Z" duration="0.000407" asserts="0">
            <reason>
              <message>System.Int32</message>
            </reason>
          </test-case>
        </test-suite>
      </test-suite>
```

**Comment by CharliePoole** [comment]
In that case, I think you have eliminated one bug! :-)
