### ISSUE TITLE
`MultipleAssertException` should derive from `AssertionException`, or both should derive from a common e.g. `AssertionExceptionBase`

### ISSUE THREAD

**Issue by maettu-this** [nunit/nunit#4761]
https://github.com/nunit/nunit/issues/4701#issuecomment-2231695472 shows an issue with the current design, `MultipleAssertException` and `AssertionException` are currently not directly related to each other. From an OO point of view, `MultipleAssertException` is a specialization of `AssertionException`, I therefore expected to be able to catch both at once using `AssertionException`, but this is not the case.

Also, the naming seems somewhat inconsistent, I would have expected `MultipleAssertionException` rather than `MultipleAssertException`, or `AssertException` rather than `AssertionException`. Whatever way around, either both `Assertion` or `Assert`.

Potential designs:

- `AssertionExceptionBase` as base class. `AssertionException` and `MultipleAssertException` as derived classes. This would be non-breaking for sure.
- Change `AssertionException` to become the base class. `SingleAssertException` and `MultipleAssertException` as derived classes. In the majority of cases this should also be non-breaking. And this would resolve the naming inconsistency.
- `AssertionException` as base class. `MultipleAssertionException` as derived class. The latter renaming is breaking but could be made backward compatible with an `MultipleAssertException` alias.

Please consider refining.

**Comment by OsirisTerje** [comment]
They both derive from `ResultStateException`.
The full hierarchy looks like this:
<img width="752" alt="image" src="https://github.com/user-attachments/assets/b3aa9c4f-fa65-41e8-bcd6-3ac754ab021d">

Making this hierarchy deeper is not something I believe will be an improvement, rather the opposite.

We can not easily change the names either, that would be a breaking change for many users, with very little benefit.  

In a code base like this we can't always go for what is currently regarded as optimal, but have to live with decisions made way back. 

In order to handle the issue of catching both, you can catch the ResultStateException and then filter on the two others.
```csharp
 catch (ResultStateException e) when (e is AssertionException or MultipleAssertException)
```

**Comment by maettu-this** [comment]
@OsirisTerje, I understand the necessity of keeping compatibility, especially with long running projects. At the same time, long running projects also need to evolve where there is need.

Therefore, I am challenging the...

> change the names either, that would be a breaking change for many users

...with two experimental PRs for which I ask you to approve the workflows for. The two PRs contain minimal change and I think will pass verification. Reasoning:

- Not much changes for `MultipleAssertException`, it just derives from `AssertionException`, making it clearer this is a specialization of such.
- While introducing `SingleAssertException` looks like a big change, verification based on `AssertionException` should still work and users currently catching `AssertionException` will still catch that.
- Nothing changes for legacy assertions, they may continue to throw the common `AssertionException` base.

**Comment by OsirisTerje** [comment]
1. MultipleAssertException is not a specialization of AssertionException.
2. Adding more exceptions representing the same thing is not the way we need to go.

I don't see any need for implementing what you're suggesting here.
Exceptions are used internally, and should not be used externally.
See @CharliePoole comment here:  https://github.com/nunit/nunit/issues/4701#issuecomment-2231895900

**Comment by maettu-this** [comment]
I understand @CharliePoole's reasoning. On the other hand, me as well as @RenderMichael and likely several others do rely on catching these exceptions. For me, catching such exception seems the natural approach for handling exceptional cases like e.g. those described at #4701. Of course the...

> `Assert.That(ACTUAL, Is.SomeConstraint, On.Failure(ACTION));`

...proposed @CharliePoole would provide even more power. But to me, refining the design of the exceptions seems to be a low hanging fruit for enabling e.g. the described uses cases and seems to keep things "simple and stupid". But of course this is object to personal perspective.

**Comment by OsirisTerje** [comment]
You can still do that (catching the exceptions) using the code line above, no need to change anything.

**Comment by stevenaw** [comment]
@maettu-this Thanks for raising this. I understand the desire on your end for the naming consistency between `Assert` and `Assertion` in these exception types :)

One added complication I could offer here for your suggestion that hasn't been raised yet is that changes to exception hierarchy are particularly brittle based on the rules the CLR uses to resolve multiple catch handlers. Consider the following code:

```csharp
public class CustomExceptionA : Exception {}
public class CustomExceptionB : Exception {}

try {
  throw new CustomExceptionB();
} catch (CustomExceptionA) {
  Console.WriteLine("a");
} catch (CustomExceptionB) {
  Console.WriteLine("b");
}
```

Based on the code above, throwing exception b in the try/catch will output `b` and throwing exception a will output `a`. However if the following change were made:

```diff
-public class CustomExceptionB : Exception {}
+public class CustomExceptionB : CustomExceptionA {}
```

Then I believe it would instead output `a` as the `catch` statements are resolved top-down and it would change to resolving to `catch CustomExceptionA` as it would now become a base class of the thrown exception. I think it's unlikely we'd had a test for this in our own codebase as catching exceptions is something we've recommended against, but it's still a pattern we'd have to be conscious of in general from any NUnit users.

For that reason, the dotnet team suggests that [one of the only non-breaking changes](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/breaking-change-rules.md#exceptions) which can be made to an exception hierarchy is the introduction of an entirely new exception type to throw. However in NUnit's case this would then mean adding another layer to the exception hierarchy which I'd then agree with @OsirisTerje is not worth the complexity it would bring

**Comment by CharliePoole** [comment]
Another bit of history, in case it helps...

Once we decided, after a lot of discussion, that use of exceptions was an internal detail, the main "audience" for the exceptions we use became the developers of NUnit itself. AssertionException and and MultipleAssertException were used for entirely different things and were handled by different code, so it made sense to keep them separate. A further step, which I considered, would have been to make them both internal. But I figured that people who wanted to catch would still catch "Exception" and look at the actual type name in order to handle it. That would be even worse than catching the exceptions themselves.

FWIW... AssertionException is used to report the errror and, secondarily, to terminate execution. I had hopes of finding a way to terminate execution differently, but everything I thought of seemed inordinately complicated.

MultipleAssertException's main purpose is to terminate execution conditionally, depending on what happened within its scope.

**Comment by maettu-this** [comment]
@stevenaw thanks for the input regarding exception hierarchies. Taking this into account indeed makes the design a bit more complicated:

- `AssertException` as common base.
- `MultipleAssertException` deriving from `AssertException`.
- `SingleAssertException` deriving from existing `AssertionException` which is now also deriving from `AssertException`.

Problems solved:

- Common base `AssertException` for all assertions, i.e. the initial intention of this issue.
- Existing `AssertionException` still strictly tied to `SingleAssertException`.
- Existing `AssertionException` still usable for legacy assertions.
- Exception types consistently named, except for the existing `AssertionException` which is left unchanged.

However, experiments revealed a severe issue:

The wrapping of the legacy assertions into "modern" assertions results in the legacy assertions also throwing the new `SingleAssertException`. While existing code catching `AssertionException` would still work fine, code relying on `Assert.Throws<AssertionException>()` or the `Throws.InstanceOf<AssertionException>()` constraint would break.

Too bad... At least I have tried :-) And this outcome is visible to others who run into the same issue.
