### ISSUE TITLE
Document ThrowOnEachFailurUnderDebugger

### ISSUE THREAD

**Issue by OsirisTerje** [nunit/nunit#4765]
This needs to be documented both for the framework and for the adapter.  See Issue #4738 
The docs can refer to each other so no need for duplication.  Also mention it will apply to NUnit 4.2 and above.

For the adapter it should be here:  https://docs.nunit.org/articles/vs-test-adapter/Tips-And-Tricks.html    Upcoming PR will add it there, so it can just be filled out with a link to the NUnit doc

For NUnit it should be under Technical notes

Repo:  https://github.com/nunit/docs

@MaceWindu Can you do this?

**Comment by OsirisTerje** [comment]
@MaceWindu If it works now, as is, then that change would be an implementation detail.  And can be done in the next version.

Alternatively, we should postpone the issue to next version.  If it works now, I can't see why we should do that. 
The plan is to get the 4.2 out end of July or at latest early August.

**Comment by MaceWindu** [comment]
Got it. Will work on docs then
