### ISSUE TITLE
Assert failure in a Task is not considered for overall Nunit test suite result

### ISSUE THREAD

**Issue by yogi5292** [nunit/nunit#4766]
Hi, I'm currently using NUnit version 3.8.1.2 and observed that when an Assert condition fails within a System.Threading.Tasks.Task block it is not consider as part of the overall Nunit test suite execution result. Could you let me know if it is an issue with Nunit or how I've written the block of Task? 

Task.Run(() =>
            {
                callReturned = false;
                var result = mySessionControlUnderTest.Shutdown(false);
                **Assert.IsFalse(result, "Shutdown is passed");**
                callReturned = true;
            });

The above Assert condition fails and also the TaskStatus is faulted, since I expected that if the Assert fails in the Task it would fail the test suite result I did not assert for TaskStatus. After I started asserting the TaskStatus the test suite started failing.

**Comment by manfred-brands** [comment]
The `Task` runs in the background. If you don't wait for the result, the actual `Test` method might be finished before the `Task` gets to the `Assert.IsFalse`.
This error will be recorded to whatever the current `TestExecutionContext` is, which might be an unrelated test.
The exception thrown will cause an `UnobservedTaskException` which gets either lost or brings down the current run completely.

You should never start an unobserved `Task` in an nunit test.

**Comment by yogi5292** [comment]
OK but the test method is not finished before the task execution. Also, like I mentioned "After I started asserting the TaskStatus the test suite started failing." this is the behaviour which I observed but the expected behaviour is that Assert failure in Task is considered for TestExecutionContext, which is not the case.

**Comment by stevenaw** [comment]
@yogi5292 It might help us if you could provide us with a bit more. Ideally a repro that runs as-is without the need for modification. Are you able to expand on your code snippet here or perhaps open a PR into our "issues" repo with something that we can run to see your issue?

https://github.com/nunit/nunit.issues

It would also help if we could understand if this code that isn't behaving as you expect is a net-new test you are trying to write or if it's an existing test which has started to fail for you as a result of a recent upgrade. It would also help to understand if you've tried upgrading to a later version of NUnit 3 to see if your issue has already been fixed there :)

**Comment by stevenaw** [comment]
I would agree about the wisdom to await the `Task` too, if you are not already doing that

**Comment by manfred-brands** [comment]
This test does recognize failures in the `Task`:

```csharp
[Test]
public async Task AssertInTaskAsync([Values] bool check)
{
    var task = Task.Run(() =>
    {
        Assert.That(check, Is.True);
    });

    await task;
}
```

![image](https://github.com/user-attachments/assets/4a7c3134-1667-4d81-8182-fb789e70385d)

If you don't wait, then the test completes before the failure is recorded.
