### ISSUE TITLE
Support tuples in inline data

### ISSUE THREAD

**Issue by MaxKot** [nunit/nunit#4771]
*Feature request*

Add support to passing tuples in inline parameter values. This would simplify passing complex values while using combinatorial and pairwise test cases generation.

Example usage:

```csharp
[Test]
public void Test
(
    [Values(new object[] {"a", 1}, new object[] {"b", 2})]
    (string, int) a,
    [Values(1, 2, 3)]
    int b
)
```

Currently it can be achieved with `ValueSource`. Note that this feature will also need an update to `NUnit1031` diagnostic.

**Comment by manfred-brands** [comment]
It is a pity `[Values(("a", 1), ("b", 2))]` doesn't compile and is something that had been [requested](https://github.com/dotnet/roslyn/issues/22459) but denied.

But I can't say that the `new object[] {"a", 1}` is very readable.
The road with a `ValueSource` seems nicer to me:

```csharp
        private static readonly (string, int)[] ValueTuples = [("a", 1), ("b", 2)];

        [Test]
        public void TupleTest(
            [ValueSource(nameof(ValueTuples))] (string, int) a,
            [Values(1, 2, 3)] int b)
        {
        }
```

**Comment by MaxKot** [comment]
I find using `ValueSource` more cumbersome when there are similar tests that require different input values as you need to make up different field names for each test. Sometimes it results with long names like `XDoesYWhenZInput1Values`, `XDoesMWhenNInput1Values` etc so I thought that just specifying values inline would be a better way.

**Comment by stevenaw** [comment]
I also wish that the language support here were better, but have to agree with @manfred-brands here.

I think NUnit has historically taken the philosophy that inline `TestCase` or `Values` attributes must use compile-time primitive types [compatible with attribute parameter types](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/attributes#2224-attribute-parameter-types) and that the "Source" attributes like `TestCaseSource` and `ValueSource` then allow for other more complex scenarios such as non-primitives or reuse of data across multiple tests. Some convenience conversions between these types have existed for historical reasons to support things like the .NET Compact Framework but I believe in general we've tried to continue to follow this philosophy.

I understand you are looking to keep with your chosen test naming convention here but that you are finding the test source names becoming verbose and that you desire simplification. In lieu of changing names of your data sources, is there any test reorganization which could aid in associating a non-reusable test source to it's test? Without knowing your codebase I am wondering if something like nested classes could provide a natural hierarchical way to tightly group these in your case.

Ex:

```csharp
public class ClassAMethodXTests {
  public class DoesY {
    [Test]
    public void WhenZ([ValueSource(nameof(Input1))] inputs) {
    }

    [Test]
    public void WhenZ([ValueSource(nameof(Input2))] inputs) {
    }

    public static IEnumerable Input1() {}
    public static IEnumerable Input2() {}
  }
}

```

**Comment by MaxKot** [comment]
@stevenaw Thanks for the suggestion, I'll look into ways to organize tests so that there's no naming collisions.

What's the final verdict on tuple conversions? I could make a PR for the analyzers repository, but this feature is not desired, I'll close the issue and the PR here.

**Comment by stevenaw** [comment]
Thanks for asking @MaxKot 
Seems we may have some differing opinions between team members. @jnm2 @OsirisTerje what are your thoughts on this being included in the framework?

**Comment by OsirisTerje** [comment]
I prefer to have readable code, so I lean towards @manfred-brands suggestion above, and also how @stevenaw organize it.   Also NUnit1031 is good advice.  The problem with tuples is (as @manfred-brands states) is that they are not constant expressions which can be used for attributes.  So then you're forced to write the hack with the arrays.  I don't think that is a good way to do it.  Using a valuesource is a way more nice way to do it. 

That said. I am all for freedom of expression - and for the developers freedom to write terrible code - , so if it could be introduced without compromising anything, I'm fine with that.  But NUnit1031 should stand, and any user should then suppress that warning if they choose to go down that route.  

Looking at the suggested code, I am not sure,  it complicates a method that is already more than complex. It needs more tests, and it should not impact performance (meaning becnhmarks are needed).

**Comment by jnm2** [comment]
> But I can't say that the `new object[] {"a", 1}` is very readable.

In C# 12, it should be possible to write `["a", 1]` instead.

**Comment by MaxKot** [comment]
I extracted and split tuples-related code to several methods, hope it's less complicated now.

Should I add benchmarks to nunit.framework.benchmarks or make a separate benchmark outside of the repository?

I see two possible ways to improve readability. One is to pass "flattened" tuples to `ValuesAttribute` constructor. Knowing the size of the target tuple and the number of constructor arguments, arguments can then be grouped to construct tuple values. Some additional separator e.g. three spaces instead of one may be used to separate tuples. This should look something like this:

```
[Test]
public void Test
(
    [Values("a", 1,   "b", 2)]
    (string, int) a,
    [Values(1, 2, 3)]
    int b
)
```

I don't like how it's pretty error-prone to use but it looks cleaner than sub-array instantiations.

Another way is to add an attribute providing exactly one argument value instead of all arguments and allow multiple arguments on a single parameter:

```
[Test]
public void Test
(
    [Value("a", 1)]
    [Value("b", 2)]
    (string, int) a,
    [Values(1, 2, 3)]
    int b
)
```

Handling tuples can be kept within the new attribute thus removing any performance and complexity impact on `ParamAttributeTypeConversions`. I'm not sure whether it should be included in the framework or it can be left to be implemented in the client code though.

And finally a way to provide custom conversions may be added. It's already possible with client-controller types via `TypeConverterAttribute` so why not allow client code to provide a `TypeConverter` for any type in a way like custom formatters are added? Tuples could be handled outside of the framework then.

**Comment by OsirisTerje** [comment]
> Should I add benchmarks to nunit.framework.benchmarks or make a separate benchmark outside of the repository?

To nunit.framework.benchmarks please.

I seem to remember (but cant find it now) a discussion about creating a NUnit.Extensions package, which could contain any kind of user contributed framework extensions.  A kind of pay-as-you-go libray (in the meaning, on your own risk) .  This would then not have to be as rigorously treated as we have to do with NUnit itself.

**Comment by OsirisTerje** [comment]
1. Using spaces for separation will probably be hard to enforce.  

2. Your idea of a separate attribute (if I understand you correctly) , and allowing for a TypeConverter.  Can you elaborate on that?  Also on the impact on the framework please.

**Comment by MaxKot** [comment]
Here are my results of benchmarks.

```

BenchmarkDotNet v0.13.12, Windows 11 (10.0.22631.4037/23H2/2023Update/SunValley3)
11th Gen Intel Core i5-11400H 2.70GHz, 1 CPU, 12 logical and 6 physical cores
.NET SDK 8.0.303
  [Host]     : .NET 6.0.32 (6.0.3224.31407), X64 RyuJIT AVX2
  DefaultJob : .NET 6.0.32 (6.0.3224.31407), X64 RyuJIT AVX2


```
| Method     | Input                | Mean       | Error     | StdDev    | Median     | Ratio | RatioSD | Gen0   | Allocated | Alloc Ratio |
|----------- |--------------------- |-----------:|----------:|----------:|-----------:|------:|--------:|-------:|----------:|------------:|
| **Original**   | **(null) to String**     |  **22.523 ns** | **0.4667 ns** | **0.9103 ns** |  **22.912 ns** |  **1.00** |    **0.00** |      **-** |         **-** |          **NA** |
| WithTuples | (null) to String     |  23.331 ns | 0.0786 ns | 0.0735 ns |  23.363 ns |  1.03 |    0.05 |      - |         - |          NA |
|            |                      |            |           |           |            |       |         |        |           |             |
| **Original**   | **12,3 to Decimal**      |  **47.804 ns** | **0.3456 ns** | **0.3064 ns** |  **47.765 ns** |  **1.00** |    **0.00** | **0.0051** |      **32 B** |        **1.00** |
| WithTuples | 12,3 to Decimal      |  47.776 ns | 0.3598 ns | 0.3366 ns |  47.903 ns |  1.00 |    0.01 | 0.0051 |      32 B |        1.00 |
|            |                      |            |           |           |            |       |         |        |           |             |
| **Original**   | **12,3 to Decimal?**     | **146.733 ns** | **2.8854 ns** | **4.8209 ns** | **149.255 ns** |  **1.00** |    **0.00** | **0.0100** |      **64 B** |        **1.00** |
| WithTuples | 12,3 to Decimal?     | 137.584 ns | 1.3065 ns | 1.1582 ns | 137.897 ns |  0.97 |    0.03 | 0.0100 |      64 B |        1.00 |
|            |                      |            |           |           |            |       |         |        |           |             |
| **Original**   | **123 to SByte**         |  **32.875 ns** | **0.0825 ns** | **0.1156 ns** |  **32.905 ns** |  **1.00** |    **0.00** | **0.0038** |      **24 B** |        **1.00** |
| WithTuples | 123 to SByte         |  33.130 ns | 0.6815 ns | 0.5321 ns |  32.959 ns |  1.01 |    0.02 | 0.0038 |      24 B |        1.00 |
|            |                      |            |           |           |            |       |         |        |           |             |
| **Original**   | **123 to SByte?**        | **120.753 ns** | **2.1449 ns** | **2.5533 ns** | **119.675 ns** |  **1.00** |    **0.00** | **0.0088** |      **56 B** |        **1.00** |
| WithTuples | 123 to SByte?        | 117.952 ns | 1.0684 ns | 0.8341 ns | 118.362 ns |  0.98 |    0.03 | 0.0088 |      56 B |        1.00 |
|            |                      |            |           |           |            |       |         |        |           |             |
| **Original**   | **2024-(...)eTime [36]** | **258.196 ns** | **1.4074 ns** | **1.0988 ns** | **257.767 ns** |  **1.00** |    **0.00** | **0.0038** |      **24 B** |        **1.00** |
| WithTuples | 2024-(...)eTime [36] | 259.808 ns | 0.7508 ns | 0.6656 ns | 259.646 ns |  1.01 |    0.00 | 0.0038 |      24 B |        1.00 |
|            |                      |            |           |           |            |       |         |        |           |             |
| **Original**   | **2024-(...)Time? [37]** | **375.124 ns** | **2.7395 ns** | **2.2876 ns** | **375.449 ns** |  **1.00** |    **0.00** | **0.0086** |      **56 B** |        **1.00** |
| WithTuples | 2024-(...)Time? [37] | 369.453 ns | 0.5281 ns | 0.4410 ns | 369.334 ns |  0.98 |    0.01 | 0.0086 |      56 B |        1.00 |
|            |                      |            |           |           |            |       |         |        |           |             |
| **Original**   | **DBNull to String**     |  **36.583 ns** | **0.2144 ns** | **0.2005 ns** |  **36.656 ns** |  **1.00** |    **0.00** |      **-** |         **-** |          **NA** |
| WithTuples | DBNull to String     |  36.683 ns | 0.1428 ns | 0.1193 ns |  36.672 ns |  1.00 |    0.01 |      - |         - |          NA |
|            |                      |            |           |           |            |       |         |        |           |             |
| **Original**   | **strin(...)erter [26]** | **103.018 ns** | **2.0857 ns** | **3.2471 ns** | **101.290 ns** |  **1.00** |    **0.00** | **0.0101** |      **64 B** |        **1.00** |
| WithTuples | strin(...)erter [26] | 102.698 ns | 0.5378 ns | 0.4768 ns | 102.701 ns |  0.98 |    0.04 | 0.0101 |      64 B |        1.00 |
|            |                      |            |           |           |            |       |         |        |           |             |
| **Original**   | **string to String**     |   **6.334 ns** | **0.0286 ns** | **0.0223 ns** |   **6.322 ns** |  **1.00** |    **0.00** |      **-** |         **-** |          **NA** |
| WithTuples | string to String     |   6.559 ns | 0.0032 ns | 0.0027 ns |   6.558 ns |  1.04 |    0.00 |      - |         - |          NA |
|            |                      |            |           |           |            |       |         |        |           |             |
| **Original**   | **strin(...)tible [23]** |  **98.732 ns** | **0.3222 ns** | **0.3014 ns** |  **98.825 ns** |  **1.00** |    **0.00** | **0.0063** |      **40 B** |        **1.00** |
| WithTuples | strin(...)tible [23] | 101.020 ns | 2.0064 ns | 2.7463 ns | 102.471 ns |  1.01 |    0.03 | 0.0063 |      40 B |        1.00 |

**Comment by MaxKot** [comment]
Sorry my wording was misleading. A new attribute to provide a single parameter value is my second suggestion at improving readability of tuple values.

Allowing for custom `TypeConverter` is a separate suggestion. It would allow framework users to handle tuples (or any other types) any way they see fit thus removing the need to handle tuples in the framework itself. Perhaps I should create a new feature request for this?

**Comment by manfred-brands** [comment]
> > But I can't say that the `new object[] {"a", 1}` is very readable.
> 
> In C# 12, it should be possible to write `["a", 1]` instead.

That syntax only works if the target type is an array and not just object.

In this case `[Values(new object[] {"a", 1}, new object[] {"b", 2})]`
We can not write: `[["a", 1], ["b", 2]]` as the compiler doesn't allow array syntax for `object`.

**Comment by jnm2** [comment]
Ah, and `object[][]` is not valid. Gotcha. This is a scenario we hope to make smoother when we get to designing natural types for collection expressions. (Maybe C# 14?)

**Comment by stevenaw** [comment]
FWIW I like the explicit groupings that multilevel arrays offer here, independent of any syntax improvements (though they certainly make it nicer).
 I think it defines some ambiguities out of existence.

For example, if passing a flat list of values to be inferred into one or more tuples, how would it behave if the test method were to contain optional arguments or, in the future, params (https://github.com/nunit/nunit/issues/1281)

**Comment by manfred-brands** [comment]
@stevenaw Nobody suggested a flat list. I only stated that we cannot use collection initializers to make it readable.

**Comment by stevenaw** [comment]
Yep thanks @manfred-brands ! I'm glad you had raised the connection initializers point. 

Sorry about the confusion here. I'd been late to respond but my comment was more in relation to one above from @MaxKot

**Comment by stevenaw** [comment]
Thanks for providing your use case @MaxKot . The desire to combine district value sets based in part by NUnit's auto-enumeration of enum values is something that would be a little bit more code to do in a testcasesource.

@jnm2 @OsirisTerje @manfred-brands I'm still on the fence myself about if it's worth the added complexity to support this in TestCase vs just using a TestCaseSource. I see a discussion about syntax above but I'm unclear how we feel about the feature proposal itself

**Comment by manfred-brands** [comment]
@stevenaw I'm not in favour, but I can live with @OsirisTerje statement:

> That said. I am all for freedom of expression - and for the developers freedom to write terrible code - , so if it could be introduced without compromising anything, I'm fine with that

**Comment by stevenaw** [comment]
Ah! Thanks @manfred-brands I may've missed that when rereading the issue today to refresh myself on the discussion
@MaxKot thanks for your patience while awaiting PR review. I aim to soon
