### ISSUE TITLE
Publicly expose `IgnoreAttribute.Reason`

### ISSUE THREAD

**Issue by RenderMichael** [nunit/nunit#4777]
I'm doing some internal analytics about the ignored tests in my test suites, and it would be useful if the `reason` from the constructor could be publicly exposed on `IgnoreAttribute`.

I'm happy to contribute this myself.

### API Proposal

```diff
namespace NUnit.Framework;

public class IgnoreAttribute
{
+    public string Reason { get; }
}
```

**Comment by OsirisTerje** [comment]
Sounds good to me :-)

**Comment by RenderMichael** [comment]
Opened #4781 for this
