### ISSUE TITLE
Multiple mains when running nunitlite to test an executable

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#4780]
I encountered this converting the tests for the console runner to use NUnitLite. In a situation where...

1. The SUT is an executable
2. The test is an executable using NUnitLite

The compiler finds two mains when compiling the test executable. In my case, I resolved this by adding a `<StartupObject>` element to the test project.

I suggest that this should be noted in the docs.

**Comment by OsirisTerje** [comment]
@charlie See preview link here:  https://66bcf72ca9b1db0c93f962da--resilient-maamoul-8b1e0d.netlify.app/

**Comment by CharliePoole** [comment]
Looks good! Funny that I ran into this only now after so many years.
