### ISSUE TITLE
NUnit 4.2.0 is missing System.Buffers on .NET Framework

### ISSUE THREAD

**Issue by ghelyar** [nunit/nunit#4795]
Upgrading from NUnit 4.1.0 to 4.2.0 in a .NET Framework project causes a `System.IO.FileNotFoundException` of `System.Buffers` at runtime, when asserting equality on any type after the `StreamsComparer` in [the list](https://github.com/nunit/nunit/blob/3f1eb0454234205c99419918115bbedeb33bcd4d/src/NUnitFramework/framework/Constraints/NUnitEqualityComparer.cs#L41), including enums, chars, etc.

It looks like it's because while it goes through the comparers it's trying to use a `StreamsComparer`, which was changed to use `System.Buffers` [here](https://github.com/nunit/nunit/commit/67a13691d04bdaf09c4e2a36a8872f28005cecba), but this probably needs a package reference for .NET Framework.

In fact at the time that had
```csharp
#if !NETFRAMEWORK
using System.Buffers;
#endif
```

but that got removed [here](https://github.com/nunit/nunit/commit/bab626e217ecdd8210b3582d2059b4bd93066e4d#diff-57f5421e71da296e02ec0d48cfee1a9e89e53de267929ee779797c9d24448fbc).

Error:
```
System.IO.FileNotFoundException : Could not load file or assembly 'System.Buffers, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
   at NUnit.Framework.Constraints.Comparers.StreamsComparer.Equal(Object x, Object y, Tolerance& tolerance, ComparisonState state, NUnitEqualityComparer equalityComparer)
   at NUnit.Framework.Constraints.NUnitEqualityComparer.AreEqual(Object x, Object y, Tolerance& tolerance, ComparisonState state)
   at NUnit.Framework.Constraints.NUnitEqualityComparer.AreEqual(Object x, Object y, Tolerance& tolerance)
   at NUnit.Framework.Constraints.EqualConstraint.ApplyTo[TActual](TActual actual)
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, NUnitString message, String actualExpression, String constraintExpression)
   at nurepro.Repro.Test()
```

Repro:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.0" />
    <PackageReference Include="NUnit" Version="4.2.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```

```csharp
using NUnit.Framework;

namespace nurepro
{
    public class Repro
    {
        [Test]
        public void TestEnum()
        {
            Assert.That(Foo.Bar, Is.EqualTo(Foo.Bar));
        }
        
        [Test]
        public void TestChar()
        {        
            Assert.That('x', Is.EqualTo('x'));
        }
    }

    public enum Foo
    {
        Bar = 1,
    }
}
```

**Comment by OsirisTerje** [comment]
Thanks!   
Same as #4794 

We're working on a  fix, by adding in `System.Memory` as a dependency in the package nuspec.  `System.Memory` depends on `System.Buffers`, so that should solve it.

Adding your code to the repro at https://github.com/nunit/nunit.issues/tree/main/Issue4794

**Comment by OsirisTerje** [comment]
@ghelyar Can you verify that the enclosed package works for you: 
[NUnit.4.2.1.zip](https://github.com/user-attachments/files/16727917/NUnit.4.2.1.zip)

**Comment by OsirisTerje** [comment]
Version 4.2.1 is released on Github and on Nuget.

**Comment by ghelyar** [comment]
4.2.1 fixes the issue.

**Comment by OsirisTerje** [comment]
Thanks @ghelyar !
