### ISSUE TITLE
Add a test to ensure direct framework dependencies in csproj are reflected in nuspec

### ISSUE THREAD

**Issue by stevenaw** [nunit/nunit#4798]
We currently have to manually ensure framework dependencies in the csproj are also reflected in nuspec. We should consider adding some sort of test coverage to validate this to give us a safety net for future changes.

**Comment by stevenaw** [comment]
@OsirisTerje @manfred-brands 
Time zones being as they are, thank you for getting the 4.2.1 out so quickly while it was nighttime on my end. 

I've added this to help give us some coverage here. I'm unsure the best way to do this, but perhaps the simplest is a basic parse and compare of the csproj and nuspec XML directly.

**Comment by manfred-brands** [comment]
As we had this situation twice now, I agree that an automated check in the build or pack script is the way to go.

**Comment by OsirisTerje** [comment]
I added the System.Memory package ONLY to the NetFramework nuspec.  The repro worked for .net 8.  Should that package perhaps be under the .Net Framework condition?  What is it that includes it in .net 8 ?

**Comment by manfred-brands** [comment]
The nuget package for .NET Core 2.1 and higher is empty (only contains the `_._` file. 
The corresponding classes must be part of the Core libraries.

**Comment by OsirisTerje** [comment]
The check like suggested can be added to the CakeScript project, and then called from the Cake build. We have a test project there for verifying it works.

**Comment by OsirisTerje** [comment]
> The corresponding classes must be part of the Core libraries.

So we could just place that under the .Net Framework condition block then.

**Comment by manfred-brands** [comment]
> > The corresponding classes must be part of the Core libraries.
> 
> So we could just place that under the .Net Framework condition block then.

Yes indeed
