### ISSUE TITLE
Explicit seems to conflict with Ignore

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#48]
I have a test fixture marked with:
[TestFixture]
[Explicit, Category("SomeCategory")]

Tests in this fixture are run when the console runner specifies "SomeCategory".
The tests in this fixture CONTINUE to be run when I add [Ignore] to the class. They only stop being run when I remove the [Explicit] attribute.

From https://bugs.launchpad.net/nunit-3.0/+bug/1046259

**Comment by constructor-igor** [comment]
Tests:
```c#
    [TestFixture]
//    [Ignore("ignore")]
//    [Explicit, Category("SomeCategory")]
    public class ExplicitTests
    {
        [Test]
        public void Test1()
        {            
        }
        [Test]
        public void Test2()
        {
        }
    }
```
nunit v3 console (without category specification)
```
      <test-suite type="TestFixture" id="1000" name="ExplicitTests" fullname="NUnit_v3_samples.ExplicitTests" classname="NUnit_v3_samples.ExplicitTests" runstate="Runnable" testcasecount="2" result="Passed" start-time="2015-04-19 08:06:04Z" end-time="2015-04-19 08:06:04Z" duration="0.022000" total="2" passed="2" failed="0" inconclusive="0" skipped="0" asserts="0">
        <test-case id="1001" name="Test1" fullname="NUnit_v3_samples.ExplicitTests.Test1" methodname="Test1" classname="NUnit_v3_samples.ExplicitTests" runstate="Runnable" seed="1998102471" result="Passed" start-time="2015-04-19 08:06:04Z" end-time="2015-04-19 08:06:04Z" duration="0.009000" asserts="0" />
        <test-case id="1002" name="Test2" fullname="NUnit_v3_samples.ExplicitTests.Test2" methodname="Test2" classname="NUnit_v3_samples.ExplicitTests" runstate="Runnable" seed="1801850340" result="Passed" start-time="2015-04-19 08:06:04Z" end-time="2015-04-19 08:06:04Z" duration="0.000000" asserts="0" />
      </test-suite>
```

nunit v3 console (with **--include=SomeCategory**): no tests

```c#
    [TestFixture]
//    [Ignore("ignore")]
    [Explicit, Category("SomeCategory")]
    public class ExplicitTests
    {
        [Test]
        public void Test1()
        {            
        }
        [Test]
        public void Test2()
        {
        }
    }
```
nunit v3 console (without category specification): **not found any information about the tests**
nunit v3 console (with **--include=SomeCategory**):
```
      <test-suite type="TestFixture" id="1000" name="ExplicitTests" fullname="NUnit_v3_samples.ExplicitTests" classname="NUnit_v3_samples.ExplicitTests" runstate="Explicit" testcasecount="2" result="Passed" start-time="2015-04-19 08:14:53Z" end-time="2015-04-19 08:14:53Z" duration="0.023000" total="2" passed="2" failed="0" inconclusive="0" skipped="0" asserts="0">
        <properties>
          <property name="_SKIPREASON" value="" />
          <property name="Category" value="SomeCategory" />
        </properties>
        <test-case id="1001" name="Test1" fullname="NUnit_v3_samples.ExplicitTests.Test1" methodname="Test1" classname="NUnit_v3_samples.ExplicitTests" runstate="Runnable" seed="1998102471" result="Passed" start-time="2015-04-19 08:14:53Z" end-time="2015-04-19 08:14:53Z" duration="0.008000" asserts="0">
          <properties />
        </test-case>
        <test-case id="1002" name="Test2" fullname="NUnit_v3_samples.ExplicitTests.Test2" methodname="Test2" classname="NUnit_v3_samples.ExplicitTests" runstate="Runnable" seed="1801850340" result="Passed" start-time="2015-04-19 08:14:53Z" end-time="2015-04-19 08:14:53Z" duration="0.000000" asserts="0">
          <properties />
        </test-case>
      </test-suite>
```

```c#
    [TestFixture]
    [Ignore("ignore")]
    [Explicit, Category("SomeCategory")]
    public class ExplicitTests
    {
        [Test]
        public void Test1()
        {            
        }
        [Test]
        public void Test2()
        {
        }
    }
```
nunit v3 console (without category specification): **not found any information about the tests**
nunit v3 console (with **--include=SomeCategory**):
```
      <test-suite type="TestFixture" id="1000" name="ExplicitTests" fullname="NUnit_v3_samples.ExplicitTests" classname="NUnit_v3_samples.ExplicitTests" runstate="Explicit" testcasecount="2" result="Passed" start-time="2015-04-19 08:16:52Z" end-time="2015-04-19 08:16:52Z" duration="0.023000" total="2" passed="2" failed="0" inconclusive="0" skipped="0" asserts="0">
        <properties>
          <property name="Category" value="SomeCategory" />
          <property name="_SKIPREASON" value="" />
        </properties>
        <test-case id="1001" name="Test1" fullname="NUnit_v3_samples.ExplicitTests.Test1" methodname="Test1" classname="NUnit_v3_samples.ExplicitTests" runstate="Runnable" seed="1998102471" result="Passed" start-time="2015-04-19 08:16:52Z" end-time="2015-04-19 08:16:52Z" duration="0.009000" asserts="0">
          <properties />
        </test-case>
        <test-case id="1002" name="Test2" fullname="NUnit_v3_samples.ExplicitTests.Test2" methodname="Test2" classname="NUnit_v3_samples.ExplicitTests" runstate="Runnable" seed="1801850340" result="Passed" start-time="2015-04-19 08:16:52Z" end-time="2015-04-19 08:16:52Z" duration="0.000000" asserts="0">
          <properties />
        </test-case>
      </test-suite>
```

```c#
    [TestFixture]
    [Ignore("ignore")]
    [Category("SomeCategory")]
    public class ExplicitTests
    {
        [Test]
        public void Test1()
        {            
        }
        [Test]
        public void Test2()
        {
        }
    }
```

nunit v3 console (with **--include=SomeCategory**):
```
      <test-suite type="TestFixture" id="1000" name="ExplicitTests" fullname="NUnit_v3_samples.ExplicitTests" classname="NUnit_v3_samples.ExplicitTests" runstate="Ignored" testcasecount="2" result="Skipped" label="Ignored" site="SetUp" start-time="2015-04-19 08:18:57Z" end-time="2015-04-19 08:18:57Z" duration="0.122000" total="2" passed="0" failed="0" inconclusive="0" skipped="2" asserts="0">
        <properties>
          <property name="_SKIPREASON" value="ignore" />
          <property name="Category" value="SomeCategory" />
        </properties>
        <reason>
          <message>ignore</message>
        </reason>
        <test-case id="1001" name="Test1" fullname="NUnit_v3_samples.ExplicitTests.Test1" methodname="Test1" classname="NUnit_v3_samples.ExplicitTests" runstate="Runnable" seed="1998102471" result="Skipped" label="Ignored" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
          <properties />
          <reason>
            <message>OneTimeSetUp: ignore</message>
          </reason>
        </test-case>
        <test-case id="1002" name="Test2" fullname="NUnit_v3_samples.ExplicitTests.Test2" methodname="Test2" classname="NUnit_v3_samples.ExplicitTests" runstate="Runnable" seed="1801850340" result="Skipped" label="Ignored" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
          <properties />
          <reason>
            <message>OneTimeSetUp: ignore</message>
          </reason>
        </test-case>
      </test-suite>
```

**Comment by constructor-igor** [comment]
nunit v3 console (**--include=SomeCategory**): 

Test | Result
------------ | -------------
Ignore, Explicit, Category | 2 executed tests
Ignore, Category | 2 skipped tests
Category | 2 executed tests
Explicit, Category | 2 executed tests

**Comment by constructor-igor** [comment]
nunit v2.6.3 UI 
![image](https://cloud.githubusercontent.com/assets/1849690/7218756/8d5ec7e8-e687-11e4-9c41-46f5b23784ea.png)

**Comment by constructor-igor** [comment]
NUnit v3 Test Adaptor:
![image](https://cloud.githubusercontent.com/assets/1849690/7219414/3e04c470-e6a7-11e4-9607-e425a2720299.png)

```c#
    [TestFixture]
    [Ignore("ignore")]
    [Explicit, Category("SomeCategory")]
    public class ExplicitTests
    {
        [Test]
        public void Test1()
        {            
        }
        [Test]
        public void Test2()
        {
        }
    }
```

**Comment by CharliePoole** [comment]
So, looking at your summary...

Test | Result | Comment
------------ | ------------- | -------------
Ignore, Explicit, Category | 2 executed tests | This is an **error** - should be ignored
Ignore, Category | 2 skipped tests | This is OK
Category | 2 executed tests | This is OK
Explicit, Category | 2 executed tests | This is OK

That seems to confirm the bug: --include is overriding ignore for explicit tests. Right?

**Comment by constructor-igor** [comment]
Right. Bug confirmed.
Strangely enough, UI test adaptor works properly, but "command line" not.
If you want, I'll try to investigate the issue in debugger.

**Comment by CharliePoole** [comment]
That would be great. It would be helpful to add a failing test first. Looking in ApplyToTestTests.cs, I see that we test ExplicitAttribute and IgnoreAttribute separately, but not in combination. We need a test that applies EA followed by IA and another that reverses the order. In both cases, the RunState should end up ignored.

I think the issue here is that ExplicitAttribute is overriding RunState.Ignored when it should not. There may be issues in other attributes that set RunState as well.

**Comment by constructor-igor** [comment]
How better to provide the tests: enough publish it here or send change request?

![image](https://cloud.githubusercontent.com/assets/1849690/7233262/f408dbe4-e788-11e4-9532-807ad2676368.png)

Suggested test:
```c#
        [Test]
        public void IgnoreAttributeWithExplicitIgnoresTest()
        {
            new IgnoreAttribute("BECAUSE").ApplyToTest(test);
            new ExplicitAttribute().ApplyToTest(test);
            Assert.That(test.RunState, Is.EqualTo(RunState.Ignored));
        }
```
Resharper report:

![image](https://cloud.githubusercontent.com/assets/1849690/7233230/ce420548-e788-11e4-8705-a97037207ad8.png)

**Comment by CharliePoole** [comment]
Would you like to work on the issue and supply a fix? In that case, a pull request is the best way. We'll review, comment, etc. and finally merge. If not, then posting the test here is enough.

You could fix this specific combination or - if you like - you could expand to check all combinations of Ignore with other attributes that impact the RunState, which include PlatformAttribute and CultureAttribute.

If you want to work on it, I'll assign it to myself to keep others off it. GitHub seems not to permit assignment to people who are not committers yet.

**Comment by constructor-igor** [comment]
Ok. I am going to work on the issue ("specific combination") and pull request.
Assign the issue to me, if it's possible.

**Comment by CharliePoole** [comment]
Not possible, but I can do this: 

Assigned to @constructor-igor

**Comment by rprouse** [comment]
Igor,

Adding the tests for an issue within the issue is fine. Creating pull
requests won't work because they would introduce failing tests which we
will not merge without the fix.

I would like to point out that you shouldn't be using the Resharper test
runner for NUnit 3.0 tests. Resharper has not been updated to work with
3.0, so the test results are not reliable. Tests may appear to pass, but
actually be failing or visa-versa.

If you want to test in Visual Studio, I would suggest installing the NUnit
3.0 Visual Studio Test Adapter from
https://visualstudiogallery.msdn.microsoft.com/0da0f6bd-9bb6-4ae3-87a8-537788622f2d

Rob

On 20 April 2015 at 11:14, Igor <notifications@github.com> wrote:

> How better to provide the tests: enough publish it here or send change
> request?
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1849690/7233262/f408dbe4-e788-11e4-9532-807ad2676368.png>
>
> Suggested test:
>
>         [Test]
>         public void IgnoreAttributeWithExplicitIgnoresTest()
>         {
>             new IgnoreAttribute("BECAUSE").ApplyToTest(test);
>             new ExplicitAttribute().ApplyToTest(test);
>             Assert.That(test.RunState, Is.EqualTo(RunState.Ignored));
>         }
>
> Resharper report:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1849690/7233230/ce420548-e788-11e4-8705-a97037207ad8.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nunit/nunit/issues/48#issuecomment-94480623>.
>



-- 

Rob Prouse



I welcome VSRE emails. Learn more at http://vsre.info/

**Comment by CharliePoole** [comment]
@rprouse In fact, however, testing this bug under the adapter isn't a good idea at all. VS actually selects the tests to run, which may mask the problem. In fact, anyone working on NUnit should be using nunitlite or nunit-console (or both) to run the tests unless they are verifying a problem that only occurs with the adapter.

**Comment by constructor-igor** [comment]
pull request #601
