### ISSUE TITLE
System.NotSupportedException when using AsyncEnumerable test cases for `TestCaseSourceAttribute`

### ISSUE THREAD

**Issue by vjred** [nunit/nunit#4802]
## Example test case
```csharp
  public static async IAsyncEnumerable<TestCaseData> AsyncEnumerableTestCases()
  {
      await Task.Delay(100); // Simulate an asynchronous operation
      yield return new TestCaseData(42, 42);
      await Task.Delay(100); // Simulate another asynchronous operation
      yield return new TestCaseData(51, 51);
  }
  
  [TestCaseSource(nameof(AsyncEnumerableTestCases))]
  public async Task TestAsyncEnumerable(int expected, int actual)
  {
      await Task.Delay(100); // Simulate an asynchronous operation
      actual.Should().Be(expected);
  }
```

## Error
```
System.NotSupportedException : Specified method is not supported.
.AsyncEnumerableTestCases()+System.IAsyncDisposable.DisposeAsync()
   at NUnit.Framework.Internal.AsyncEnumerableAdapter.AsyncEnumeratorWrapper.<Dispose>b__4_0()
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await[TResult](Func`1 invoke)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.AsyncEnumerableAdapter.AsyncEnumeratorWrapper.Dispose()
   at NUnit.Framework.TestCaseSourceAttribute.GetTestCasesFor(IMethodInfo method)
```

Notes:
1. On debugging, its failing on [this line](https://github.com/nunit/nunit/blob/main/src/NUnitFramework/framework/Attributes/TestCaseSourceAttribute.cs#L152).
2. This snippet used to work before `nUnit 4.2.0` , and looks like the feature added in #4538 regressed.

**Comment by manfred-brands** [comment]
@vjred what is your target framework? .net framework or .net 6+?

The code tried to call your `IAsyncEnumerable.DisposeAsync` which then seems to throw `NotSupportedException`.

**Comment by vjred** [comment]
Target Framework is .net 8

**Comment by OsirisTerje** [comment]
I've added a repro here:  https://github.com/nunit/nunit.issues/tree/main/Issue4802   using .net 8.

**Comment by stevenaw** [comment]
Thanks adding the repro there @OsirisTerje 
Interesting we are seeing this, I didn't recall any changes in this area between the releases.

**Comment by OsirisTerje** [comment]
I managed to single step through the code in the AsyncToAsyncAdapter and the AsyncEnumerableAdapter, and when doing it slowly it did not crash at the place above, and I actually could return out of it, but with no results coming out.

**Comment by OsirisTerje** [comment]
> This snippet used to work before nUnit 4.2.0 , and looks like the feature added in https://github.com/nunit/nunit/pull/4538 regressed.

This code is from Nov 23, so it is also in 4.1 which does work.

**Comment by OsirisTerje** [comment]
Single stepping through I also got this crash,  it points to the ValueTaskAwaitAdapter, which was touched between 4.1 and 4.2:

```txt
   at Issue4802.Tests.<AsyncEnumerableTestCases>d__0.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at NUnit.Framework.Internal.ValueTaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted() in D:\repos\NUnit\nunit\src\NUnitFramework\framework\Internal\ValueTaskAwaitAdapter.cs:line 67
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter) in D:\repos\NUnit\nunit\src\NUnitFramework\framework\Internal\MessagePumpStrategy.cs:line 35
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await[TResult](Func`1 invoke) in D:\repos\NUnit\nunit\src\NUnitFramework\framework\Internal\AsyncToSyncAdapter.cs:line 38
   at NUnit.Framework.Internal.AsyncEnumerableAdapter.AsyncEnumeratorWrapper.MoveNext() in D:\repos\NUnit\nunit\src\NUnitFramework\framework\Internal\AsyncEnumerableAdapter.NetCore.cs:line 61
   at NUnit.Framework.TestCaseSourceAttribute.GetTestCasesFor(IMethodInfo method) in D:\repos\NUnit\nunit\src\NUnitFramework\framework\Attributes\TestCaseSourceAttribute.cs:line 152
```

**Comment by stevenaw** [comment]
Oh yes, you're right, it looks like we did touch that. 

From what search engines have told me, this exception may occur if a disposeasync or movenextasync operation is attempted before a previous movenextasync operation has completed. MoveNextAsync return `ValueTask<>` and the comments in the PR indicate previously we had previously been falling back to the CSharpPatternAwaitAdapter for those

**Comment by stevenaw** [comment]
Perhaps we're missing `AsyncToSyncAdapter.Await()` similar to https://github.com/nunit/nunit/blob/main/src/NUnitFramework/framework/Internal/AsyncEnumerableAdapter.NetFramework.cs#L101 ?

I don't know if I'll have time to look at this in front of a computer tonight, but I'll push a PR if I'm able

**Comment by stevenaw** [comment]
@OsirisTerje should we consider a 4.2.2 for this?

**Comment by OsirisTerje** [comment]
@stevenaw Not quite sure.  

Is this something that is often or rarely used you think?  If the former, we should mark this Critical and do a 4.2.2, otherwise wait for 4.3, or go along something else that is critical, if that appears.......

1. When we do a hotfix/patch release, I have started unlisting the previous versions.
2. If this is to be a hotfix release, we need to branch the fix off the 4.2.1 tag, so that we don't release other stuff that we might not want to release yet.  (Or we could just release that too, but if any of those are enhancements, we're up for a minor release and not a hotfix).

**Comment by OsirisTerje** [comment]
@stevenaw TEsted your branch now with the repro and it works :-) 
Very tempting to release a 4.2.2

**Comment by vjred** [comment]
It would be great to have it in 4.2.2, as we wont be able to use 4.2.1 till then. Alternatively what timelines are we expecting 4.3?

**Comment by OsirisTerje** [comment]
@stevenaw Thinking that since this is actually a regression bug, we should do a 4.2.2.  Agree?

**Comment by OsirisTerje** [comment]
@vjred It has been a bit over 6 months since the 4.1.  Would be nice to keep it 4 times a year.  So somewhere between 3 to 6 months.

**Comment by stevenaw** [comment]
I like the idea of a 4.2.2 myself.

Broader, improved async and asyncenumerable support has been a recurring theme the last few releases and it could be a challenge for those looking to upgrade to have it broken in the latest stable release. This particular fix also feels fairly focused and the risk of unexpected issues from it should be extremely low

**Comment by OsirisTerje** [comment]
I'll get it out during the weekend

**Comment by stevenaw** [comment]
Thanks @OsirisTerje !

**Comment by stevenaw** [comment]
I've created the milestone and added this issue

**Comment by OsirisTerje** [comment]
Version 4.2.2 published on nuget.  

@vjred  Can you verify it works for you?

**Comment by vjred** [comment]
I just checked 4.2.2 and it works perfectly. Thank you @OsirisTerje, @stevenaw and @manfred-brands. Extremely happy that this was resolved quickly!

**Comment by OsirisTerje** [comment]
@vjred Thanks for confirming.  

And thanks for reporting this, and also providing a repro we could work with :-)
