### ISSUE TITLE
Remove ImmutableArray as a dependency of the tests

### ISSUE THREAD

**Issue by stevenaw** [nunit/nunit#4803]
We added this as a dependency of the tests when we added support for IStructuralEquatable comparisons in https://github.com/nunit/nunit/pull/3646

It's proven a bit difficult to upgrade, and also introduces dependencies into our tests which aren't in the framework. 

We may want to consider dropping the dependency and rewriting the related tests to instead use a custom implementation of the interface. Our implementation should try to mirror ImmutableArray a bit, in that it should likely also implement IEnumerable<> and IEquatable<> to ensure it validates the same prioritization of interfaces by the comparer chain.

**Comment by manfred-brands** [comment]
@stevenaw What is the problem? If the dependency is only in the tests, we can do any upgrade without affecting the framework.

**Comment by stevenaw** [comment]
This was inspired in part by your comment here https://github.com/nunit/nunit/pull/4773#discussion_r1701173622

And by some of the nuspec dependency issues we had in 4.2.0. I know we fixed the nuspec issue and added a safeguard, but I thought this might be a good thing to discuss still. 

I've also had issues upgrading this particular dependency and have left it on 6.0.0, but not sure if that's just me.

**Comment by stevenaw** [comment]
I had been thinking this could be a `good first issue` if we did decide to pursue this

**Comment by jnm2** [comment]
It's fairly common for a test project to have dependencies not in the library that it tests. What would be the gain in thinking of library dependencies and test project dependencies in a coupled way?

**Comment by stevenaw** [comment]
This was mostly just inspired as an idea based on some recent comments and issues to have come up.

Happy to leave this in too. I think it helpful to have our tests run against a variety of commonly used BCL data structures.
