### ISSUE TITLE
Benchmarks fail to run

### ISSUE THREAD

**Issue by MaxKot** [nunit/nunit#4806]
*Bug*

Steps to reproduce:

1. Run nunit.framework.benchmarks in Release configuration.
2. Select ByteAllocationBenchmark, CompositeWorkItemBenchmark or StreamsComparerBenchmark

*Expected result*

Benchmarks running

*Actual result*

Benchmark error `CSC : error CS7027: Error signing output with public key from file '..\..\nunit.snk' -- File not found.`

*Additional steps*

3. Set `AssemblyOriginatorKeyFile` value relative to `$(MSBuildThisFileDirectory)` in src\NUnitFramework\Directory.Build.props and src\NUnitFramework\benchmarks\nunit.framework.benchmarks\nunit.framework.benchmarks.csproj

*Result after additional steps*

Benchmark error `\src\NUnitFramework\Directory.Build.props(72,5): error : Missing AssemblyConfiguration for net6.0`

*Addtional notes*

It appears that `TargetFramework` is empty when BenchmarkDotNet builds boilerplate code. Setting hard-coded `AssemblyConfiguration` value allows benchmarks to run without issue.

**Comment by stevenaw** [comment]
Thanks for the diagnosis and report here @MaxKot !

**Comment by stevenaw** [comment]
@OsirisTerje 
 We have a defined `4.4` milestone however I realize we may want a `4.3.1`. I'll make that now and assign this to it.
