### ISSUE TITLE
Is.EqualTo with empty ValueTuple throws System.NotSupportedException "Specified Tolerance not supported for instances of type 'System.ValueTuple' and 'System.ValueTuple'" after updating to NUnit 4.2.2

### ISSUE THREAD

**Issue by KrzysFR** [nunit/nunit#4807]
After updating from NUnit 4.1 to 4.2.2, I have the following error when comparing the value of a ValueTuple (empty tuple) with `Is.EqualTo` constraint:

```
System.NotSupportedException : Specified Tolerance not supported for instances of type 'System.ValueTuple' and 'System.ValueTuple'
```

The issue does NOT happen when comparing to a non-empty tuple, or with the `Is.Not.EqualTo` constraint.

Sample code:
```csharp
[TestFixture]
public class ReproTest
{
	[Test]
	public void Test_ValueTuple_Equality()
	{
		Assert.Multiple(() =>
		{
			// 4.1: PASS, 4.2.2: **FAIL**
			Assert.That(ValueTuple.Create(), Is.EqualTo(ValueTuple.Create()), "() == ()"); // => throws NotSupportedException !

			// 4.1: PASS, 4.2.2: PASS
			Assert.That(ValueTuple.Create(123), Is.EqualTo(ValueTuple.Create(123)), "(123,) == (123,)");

			// 4.1: PASS, 4.2.2: PASS
			Assert.That(ValueTuple.Create(123), Is.Not.EqualTo(ValueTuple.Create()), "(123,) != ()");

			// 4.1: PASS, 4.2.2: PASS
			Assert.That(ValueTuple.Create(), Is.Not.EqualTo(ValueTuple.Create(123)), "() != (123,)");
		});
	}
}
```

Observed error in 4.2.2:
```
System.NotSupportedException : Specified Tolerance not supported for instances of type 'System.ValueTuple' and 'System.ValueTuple'
   at NUnit.Framework.Constraints.NUnitEqualityComparer.AreEqual(Object x, Object y, Tolerance& tolerance)
   at NUnit.Framework.Constraints.EqualConstraint.ApplyTo[TActual](TActual actual)
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, NUnitString message, String actualExpression, String constraintExpression)
   at ReproTest.Test_ValueTuple_Equality()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by KrzysFR** [comment]
Looking at the code, I think this can be caused by this test: https://github.com/nunit/nunit/blob/116802d7be7619746537ae1d8ff30c19d644d823/src/NUnitFramework/framework/Constraints/Comparers/TupleComparerBase.cs#L42-L43

Here, both `redoWithoutTolerance` and `numberOfGenericArgs` should be equal to 0 for `ValueTuple`, and `(1U << numberOfGenericArgs) - 1` will return 0.

**Comment by stevenaw** [comment]
Thanks for the report @KrzysFR ! I'm not at a computer myself to confirm the behavior you're seeing, but your diagnosis there looks sound. Would you be interested in contributing a fix?

**Comment by manfred-brands** [comment]
I didn't think of Tuples without any arguments.

**Comment by KrzysFR** [comment]
I've had the same issue multiple times, since `ValueTuple` is not the same as `ValueTuple<...>` (same issue with `Task`/`Task<T>`) !

I don't have an easy way to rebuild/test the NUnit project right now, but I think the fix could be as adding the following line, but I'm not sure if this should be done before or after the call to `state.PushComparison`

```csharp
 if (numberOfGenericArgs == 0) 
     return EqualMethodResult.ComparedEqual;
```

**Comment by manfred-brands** [comment]
Ok, I'll fix it.

**Comment by manfred-brands** [comment]
The API is a bit unexpected and inconsistent.
To me a (Value)Tuple with 1 argument doesn't make any sense, let alone a ValueTuple with no arguments.
Note that there is no Tuple.Create with no arguments, but ValueTuple has one.

**Comment by KrzysFR** [comment]
Tuples with 0 or 1 argument are more likely to be seen when dealing with tuples that behave like vectors, for example via the [`System.Runtime.CompilerServices.ITuple`](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.ituple?view=net-8.0) interface, where a tuple can have any length (0, 1, 2, etc...), and support operations such as Append, Concat, Tail, Slice, ...

The empty tuple would be used as the initial value (similar to en empty list), or as the marker of "no more items" when popping values from a vector until it is "done".
