### ISSUE TITLE
API integrationtest logging is lost  when using WebApplicationFactory (nunit 3.9)

### ISSUE THREAD

**Issue by HuiSou** [nunit/nunit#4808]
in my api integration test, I setup webapplicationfactory and use Serilog under Microsoft.Extension.Logging to log the application behavior on Console

but, it seems that nunit only dump log 

I've try to fix by adding this into  terdown but it still give me no luck

```c#
[TearDown]
public void TestTearDown()
{
Debug.Flush();
Trace.Flush();
Serilog.Log.CloseAndFlush();
}
```

however, once I migrate to xunit, it seems that I got all application log properly

can you help with the fix? and/or suggest me a  setup that will helpe me overcome this challange.

**Comment by OsirisTerje** [comment]
Have you read this:  https://docs.nunit.org/articles/vs-test-adapter/Trace-and-Debug.html  and the implementation here: https://docs.nunit.org/articles/nunit/technical-notes/usage/Trace-and-Debug-Output.html
