### ISSUE TITLE
Assert.ThatAsync does not support polling

### ISSUE THREAD

**Issue by Dreamescaper** [nunit/nunit#4811]
```csharp
        var i = 0;
        async Task<string> GetResult()
        {
            return new string('1', i++);
        }

        await Assert.ThatAsync(GetResult, Is.Not.Empty.After(1000, 10));
```

Expected Result:
GetResult function returns non-empty result on second execution. So assertion should pass, since it has polling interval.

Actual Result:
Nunit invokes GetResult only once, therefore it fails.
```
Assert.That(GetResult, Is.Not.Empty.After(1000, 10))
  Expected: not <empty> after 1000 milliseconds delay
  But was:  <string.Empty>
```

**Comment by Shadi201711** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by manfred-brands** [comment]
Looking at the code, it indeed will not and isn't likely to change unless all the underlying code changes and we introduce `async` versions of `Constraint.Apply`

At the moment `ThatAsync` is a small wrapper on which does:

```csharp
var result = await code();
Assert.That(() => result, constraint, message, actualExpression, constraintExpression);
```

The existing `Assert.That` works with your code but will use the `AsyncToSyncAdapter`
```csharp
Assert.That(GetResult, Is.Not.Empty.After(1000, 10));
Assert.That(i, Is.EqualTo(2));
```

For now we could add an issue to `nunit.analyzers` to warn users that `ThatAsync` doesn't work with `DelayedConstraint`.

**Comment by Dreamescaper** [comment]
> unless all the underlying code changes and we introduce async versions of Constraint.Apply

That seems like a correct thing to do.
That would simplify other constraints as well, like ThrowsConstraint. Currently there is a wokraround with try-catch inside of ThatAsync.
