### ISSUE TITLE
Remove `StringUtil.Compare()` and update references in the tests

### ISSUE THREAD

**Issue by stevenaw** [nunit/nunit#4819]
The [`StringUtil.Compare()`](https://github.com/nunit/nunit/blob/main/src/NUnitFramework/framework/Internal/StringUtil.cs#L20) function is public but lives in the "Internal" namespace. It isn't actually used in any constraints, but there are three references in the tests still to it. A comment on the class indicates that 

> Provides methods to support legacy string comparison methods.

I'd like to propose we begin the process of removing this. I think we can convert the test usage already but I'd like to suggest we mark the method itself as obsolete rather than outright removal even though it's in the internal namespace to maximize others' chance to move away from it.

@nunit/framework-team I think this could be a `good first issue` if we can agree on if we should obsolete or remove outright

**Comment by OsirisTerje** [comment]
Supports just removing it.

**Comment by manfred-brands** [comment]
I'm also in favour of removing it. It is just not worth it to doing it in phases. Technically it is a breaking change, but practically nobody should have used it.

**Comment by stevenaw** [comment]
Ok that works for me too.

Interestingly, I looked through the history and these made their way _into_ the tests as a result of being used in a bug repro. Which means at least one person at one time has relied on these. I can not find it documented in our docs however, so I agree the number impacted will be extremely small.

**Comment by mr-sergito** [comment]
Hey, I'd love to take a shot on this one 😊

**Comment by OsirisTerje** [comment]
@mr-sergito Feel free :-)

**Comment by mr-sergito** [comment]
Been reading through the contributing guidelines. 

If I'm understanding things correctly, removing method [`StringUtil.Compare()`](https://github.com/nunit/nunit/blob/main/src/NUnitFramework/framework/Internal/StringUtil.cs#L20) involves removing its class [`StringUtil`](https://github.com/nunit/nunit/blob/bf2d0f25ab9ccf2b2c6b11f3ec01bd8898fc93e6/src/NUnitFramework/framework/Internal/StringUtil.cs#L10) right?

Regarding the tests that reference both methods in the class, should I just replace them with `System.StringComparison`?

**Comment by stevenaw** [comment]
@mr-sergito That's right! Part of removing this would involve updating the callsites in the tests to use that built-in enum.
I'd recommend trying to find the affected tests, make sure you can run them and they pass, then make the change to update just that `Compare` method call 🙂

Removing the entire `StringUtil` class itself could then be a good next step if the team agrees. On my end, I think it makes sense that if we are ok with deleting one reference then we are ok with deleting the one method then we are ok with deleting the other too. From what I can recall the remaining `Equals()` method may be called from 2 or 3 places in the framework itself in some path-related constraints.

@nunit/framework-team objections or agreement to remove the whole class?

**Comment by stevenaw** [comment]
As an aside, as an "internal" method if concerns _were_ present, I'd suggest that marking something with the obsolete attribute could then be candidate for removable in a future minor version release rather than waiting for the next major release. Depending on usages or visibility, of course
