### ISSUE TITLE
[SetupFixture] methods not executing in expected order

### ISSUE THREAD

**Issue by millenial94** [nunit/nunit#4828]
### **Description:**
The [SetupFixture] class methods [OneTimeSetup] and [OneTimeTearDown] are not executing as expected. Instead of running once before and after all tests in the namespace, they appear to be skipped entirely or executed in the wrong order.

### **Background Scenario:**
I am developing an Automation Test Project where I aim to use [SetupFixture] class methods [OneTimeSetup] and [OneTimeTearDown] to initialize and flush Extent Reports at global level. The goal is to cover multiple [TestFixture] classes within a single report in a test > node format. To understand how these annotations operate, I created this sample setup to test the behaviour of these attributes.

Additionally, I am looking for a way to execute a method before every [TestFixture] starts, similar to how [Setup] works for [Test] methods, but at the fixture level. I haven't added the logic for that in the code, but if someone can suggest a way for it would be really great.

### **Code Example:**
**ExtentReportManager.cs**
```
namespace SamplePractice.TestCases
{
    [SetUpFixture]
    public class ExtentReportManager
    {

        public ExtentReportManager() { }

        [OneTimeSetUp]
        public void OneTimeSetUp()
        {
            Console.WriteLine("Global One Time SetUp executing");
        }

        [OneTimeTearDown]
        public void OneTimeTearDown()
        {
            Console.WriteLine("Global One Time Tear Down executing");
        }
    }
}
```

**BaseClass.cs**
```
namespace SamplePractice.TestBase
{
    public class BaseClass
    {
        [SetUp]
        public void Init()
        {
            Console.WriteLine("Setup Executing");
        }

        [TearDown]
        public void Cleanup()
        {
            Console.WriteLine("Tear Down Executing");
        }
    }
}
```

**Testcases:**
```
using SamplePractice.TestBase;

namespace SamplePractice.TestCases
{
    [TestFixture, Order(1)]
    public class Class1 : BaseClass
    {
        [Test, Order(1)]
        public void Class1Test1()
        {
            Console.WriteLine("Class1 Test 1 executing");
        }

        [Test, Order(2)]
        public void Class1Test2()
        {
            Console.WriteLine("Class1 Test 2 executing");
        }
    }
}

using SamplePractice.TestBase;

namespace SamplePractice.TestCases
{
    [TestFixture, Order(2)]
    public class Class2 : BaseClass
    {
        [Test, Order(1)]
        public void Class2Test1()
        {
            Console.WriteLine("Class 2 Test 1 executing");
        }

        [Test, Order(2)]
        public void Class2Test2()
        {
            Console.WriteLine("Class 2 Test 2 executing");
        }
    }
}
```

### **Steps I tried:**
1. Ensured ExtentReportManager is a public class with a default constructor.
2. Placed ExtentReportManager in the assembly namespace to target the entire assembly
3. Verifies NUnit version (3.14.0) for runner configuration.
4. Ran tests using both Visual Studio test runner and NUnit Console (nunit3-console).

### **Output from Visual Studio Test Runner:**
```
Setup Executing
Class1 Test 1 executing
Tear Down Executing

Setup Executing
Class1 Test 2 executing
Tear Down Executing

Setup Executing
Class 2 Test 1 executing
Tear Down Executing

Setup Executing
Class 2 Test 2 executing
Tear Down Executing
```

### **Output from NUnit Console:**
```
Setup Executing
Class1 Test 1 executing
Tear Down Executing
Setup Executing
Class1 Test 2 executing
Tear Down Executing
Setup Executing
Class 2 Test 1 executing
Tear Down Executing
Setup Executing
Class 2 Test 2 executing
Tear Down Executing
Global One Time SetUp executing
Global One Time Tear Down executing
```

### **Expected Output:**
```
Global One Time SetUp executing
Setup Executing
Class1 Test 1 executing
Tear Down Executing
Setup Executing
Class1 Test 2 executing
Tear Down Executing
Setup Executing
Class 2 Test 1 executing
Tear Down Executing
Setup Executing
Class 2 Test 2 executing
Tear Down Executing
Global One Time Tear Down executing
```

### **Questions:**
1. Why is there a difference in the output between the Visual Studio test runner and the NUnit Console? Why are [OneTimeSetup] and [OneTimeTearDown] methods in [SetUpFixture] not executing as expected?
2. How can I execute a method before every [TestFixture] starts, similar to [SetUp] for [Test] methods, but at the fixture level.

**Comment by manfred-brands** [comment]
Test output in VS is per test. One-time setup/teardown don't fit in there.
Are you sure the tests are not executed as expected. I suspect the output capture to affect the result.
You could try `Console.Error.WriteLine` instead.
Or create a static `Trace` class with a static `WriteLine` class. Inside there increase a static Counter class and increment and then prefix that number in each WriteLine call. That will show you the real execution order.

You can add a `OneTimeSetup` to your `BaseClass` to run once before every `TestFixture`

**Comment by manfred-brands** [comment]
Glad to hear that the code executed in the correct order.

Output during a test is captured so that it can be logged  with the results and passed to runners like in VS who then shows the output in the test result window.
As said before output of `OneTime` methods is not associated with a particular test and I don't recall if that is redirected at all.

Note that tests ideally should not output anything. If tests succeed, nobody will look at it and if tests fail it is almost impossible to find the actual failing test amongst all the output especially if tests are running on parallel.
