### ISSUE TITLE
Unable to attach ExtentReportManager as ITestListener in NUnit Test Runner

### ISSUE THREAD

**Issue by millenial94** [nunit/nunit#4829]
### **Description:**
I'm working on integrating Extent Reports with NUnit for my automation framework, aiming to capture detailed test execution logs and screenshots. The idea is to create a structured Extent Report that shows each [Test] method under its [TestFixture] class as child nodes.

The primary reason is to capture the test lifecycle events, such as when a test starts and finishes, so that these can be logged into the Extent Report. Without attaching ExtentReportManager as a listener, it's unable to hook into these events, meaning it can't log the necessary details or screenshots to the report. This attachment is essential for building a dynamic and detailed report that reflects the actual test execution.

However, I'm running into a roadblock while trying to attach my ExtentReportManager class as an ITestListener. It seems that neither TestExecutionContext.CurrentContext.Listener nor AddListener() methods are working for this purpose. I'm not sure if I'm missing something or if there's a different approach I should take with NUnit.

### **Steps Taken:**

1.  Created an ExtentReportManager class that implements the ITestListener interface to capture test lifecycle events.
```
public class ExtentReportManager : ITestListener
{
    private readonly BaseClass baseInstance;

    public ExtentReportManager(BaseClass baseInstance)
    {
        this.baseInstance = baseInstance;
    }

    public void TestStarted(ITest test)
    {
        // Logic to create a child node in Extent Report
        var testName = test.Name;
        baseInstance.CaptureScreen(testName); // Capture screenshot
        // Create and log to Extent Report
    }

    public void TestFinished(ITestResult result)
    {
        // Logic to finalize the test node in Extent Report
    }
    
    // Other ITestListener methods...
}
```

2. Tried attaching ExtentReportManager in the [SetUpFixture] class using TestExecutionContext.CurrentContext.Listener and AddListener() methods as advised by ChatGPT:
```
[SetUpFixture]
public class ExtentReportSetUp
{
    [OneTimeSetUp]
    public void GlobalSetup()
    {
        // Attempt 1: Direct assignment (does not work)
        // var extentReportManager = new ExtentReportManager(new BaseClass());
        // TestExecutionContext.CurrentContext.Listener = extentReportManager;

        // Attempt 2: AddListener (does not work)
        // TestExecutionContext.AddListener(extentReportManager);
    }

    [OneTimeTearDown]
    public void GlobalTeardown()
    {
        // Flush the Extent Report
    }
}
```

3. **Error Encountered:**
- Attempting to use TestExecutionContext.CurrentContext.Listener results in the error: 'TestExecutionContext' does not contain a definition for 'Listener'.

- Attempting to use TestExecutionContext.AddListener() results in a similar error indicating AddListener is not defined.

### **Expected Behavior:**
I expected that by attaching ExtentReportManager as a listener, it would capture and log all the test lifecycle events into the Extent Report, making the report more informative and useful.

### **Actual Behaviour:**
The tests run, but ExtentReportManager isn't logging anything into the Extent Report since it's not attached as a listener.

### **Environments:**

- NUnit Version: 3.14.0
- NUnit3TestAdapter Version: 4.5.0
- Running Tests Using: NUnit Test Runner in Visual Studio
- Programming Language: C#
- Framework: Selenium WebDriver, Extent Reports

### **Code Structure:**
- ExtentReportManager class is designed to implement ITestListener.
- BaseClass contains methods like CaptureScreen, WebDriver initialization and tear down.
- [SetUpFixture] is used for global test setup and teardown.

### **Request for guidance:**

- How can I correctly attach ExtentReportManager to the NUnit test execution so that it listens to test events?
- Is there an alternative way to register ITestListener for tests running in the NUnit Test Runner within Visual Studio?
- Any suggestions on achieving this integration seamlessly within the current NUnit framework?

**Comment by manfred-brands** [comment]
Looking at the [docs](https://docs.nunit.org/articles/nunit-engine/extensions/creating-extensions/Event-Listeners.html?q=Itestlistener) you seem to have to put an [ExtensionAttribute](https://docs.nunit.org/articles/nunit-engine/extensions/creating-extensions/Writing-Engine-Extensions.html?q=Extensionattribute) on it.

I have not done this myself. Read up and see if it works.
