### ISSUE TITLE
Setting thread names to make debugging easier

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#4832]
Right now it's not easily distinguishable which threads are NUnit's, and specifically which are part of its MTA queues or STA queues.

![image](https://github.com/user-attachments/assets/694f5b15-3d14-4f16-9ba3-cc956cd7d3f4)

**Comment by OsirisTerje** [comment]
Makes good sense. 
We should prefix all threads we create with "NUnit." and probably also add which component is creating the thread, framework, engine, console or adapter.  The name could be a bit long though, so perhaps use a short name for the component.

I also see the thread named "EventPumpThread".  A bit surprised it is not named "StandardEventPumpThread", as that should be the name, according to the code.   https://github.com/nunit/nunit/blob/af7b9413f9cb7b5780753db6edd1ec7ef0a4ffe1/src/NUnitFramework/framework/Internal/Execution/EventPump.cs#L137  and https://github.com/nunit/nunit/blob/af7b9413f9cb7b5780753db6edd1ec7ef0a4ffe1/src/NUnitFramework/framework/Internal/Execution/EventPump.cs#L93, and only one usage which doesn't change it.

**Comment by stevenaw** [comment]
I like this idea. Improved observability and debugging experience is always a good thing

**Comment by manfred-brands** [comment]
I agree for threads we create.
However isn't is that in fully async code the thread running a test can change between awaits.

**Comment by OsirisTerje** [comment]
Yes, it can only be for our own threads.  
Async/await may change threads, so thread names and tests are not strongly connected.  But I would assume it would in any case look better than the screen shot @jnm2 has above.

**Comment by OsirisTerje** [comment]
Just for a simple test, I got this:
<img width="940" alt="image" src="https://github.com/user-attachments/assets/a1c0443a-1615-4470-aa42-f016e156f9a8">
