### ISSUE TITLE
Allow to use collection expressions with collection constraints

### ISSUE THREAD

**Issue by Dreamescaper** [nunit/nunit#4839]
Currently the following code is not possible:
```csharp
var actual = new[] { 3, 2, 1 };
Assert.That(actual, Is.EquivalentTo([1, 2, 3]));
// CS9174	Cannot initialize type 'IEnumerable' with a collection expression because the type is not constructible.
```

I suggest to add `IEnumerable<T>` overloads for all constraint methods, which currently accept non-generic `IEnumerable`:

```csharp
        public static CollectionEquivalentConstraint EquivalentTo<T>(IEnumerable<T> expected)
        {
            return new CollectionEquivalentConstraint(expected);
        }

        public static CollectionSubsetConstraint SubsetOf<T>(IEnumerable<T> expected)
        {
            return new CollectionSubsetConstraint(expected);
        }

        // etc
```

Note: it is partially related to https://github.com/nunit/nunit/issues/53, but tackles a very specific issue of using collection expressions.

**Comment by Dreamescaper** [comment]
Is it possible that such overloads would cause any issues due to overload resolution? Or any other breaking changes?
Per my understanding - no, but maybe I'm missing something.

**Comment by manfred-brands** [comment]
I would say add them and see if any of our unit tests give compile time errors.

**Comment by stevenaw** [comment]
I agree with @manfred-brands 
We want to move towards a more strongly-typed public constraints API but have realized it will likely have to happen in pieces. I think this could be a great piece, and it sounds like this is a good use case to require it too

**Comment by Dreamescaper** [comment]
@stevenaw 
Well, in the scope of this item I thought only about adding new overloads, leaving existing ones in place, to avoid having any braking changes.

**Comment by stevenaw** [comment]
@Dreamescaper Sorry, my last comment was rushed, but I'd been thinking the same. 🙂 Adding generic overloads as you suggest will be a great help towards later improvements in the area.

**Comment by stevenaw** [comment]
Overloads to receive a generic IEnumerable that is.
