### ISSUE TITLE
Missing file in NUnit.Console nuget package

### ISSUE THREAD

**Issue by xplicit** [nunit/nunit#484]
install NUnit.Console 3.0.0-alpha-5 from nuget

`nuget install NUnit.Console -pre`

then run `nunit-console test.exe` where test.exe is non-existing file

You'll get the error message (could not find Mono.Addins):

    NUnit Console Runner 3.0.5509
    Copyright (C) 2014 Charlie Poole

    Не удалось загрузить файл или сборку "Mono.Addins, Version=1.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756" либо одну из их зависимостей. Не удается найти указанный файл.

Expected result: error message that `test.exe` could not be found.
OS: Windows 7

Comments: Looks like there is a missing dependency to Mono.Addins in nunit-console 3a5. I copied Mono.Addins to `tools` folder and the error has gone.

**Comment by CharliePoole** [comment]
Fixed the package and re-uploaded it on both nuget.org and github.
