### ISSUE TITLE
MacOS test failure

### ISSUE THREAD

**Issue by manfred-brands** [nunit/nunit#4841]
We recently have build failures for the MacOS build on:

```
 Failed : NUnit.Framework.Tests.Constraints.DelayedConstraintTests.AssertionExpectingAnExceptionWithRetrySucceeds
  Assert.That(ThrowsAfterRetry, Throws.InvalidOperationException.After(AFTER, POLLING))
  Expected: <System.InvalidOperationException> after 500 milliseconds delay
  But was:  no exception thrown
   at NUnit.Framework.Tests.Constraints.DelayedConstraintTests.AssertionExpectingAnExceptionWithRetrySucceeds() in /_/src/NUnitFramework/tests/Constraints/DelayedConstraintTests.cs:line 256
```

Even though the async version was changed recently, this one was not.
Is there any one with a MacOS to see what this could be?
All I can think of is that the 50ms interval on MacOS is soo large that it doesn't do 4 iterations in 500ms.

**Comment by Dreamescaper** [comment]
There are multiple tests in that class, ignored for MacOS:
Platform(Exclude = "MACOSX", Reason = "Doesn't seem to work correctly with timing, something to ponder later")]

**Comment by manfred-brands** [comment]
There is one ;-)
But as none of use seem to have any (virtual) MacOS, the pondering is likely not happening.
It might also have nothing to do with MacOS, but the github runner might be the culprit.
We are not the only ones: https://github.com/actions/runner-images/issues/1336
It also seems that the macos runners are arm64: https://github.com/actions/runner-images/issues/9741

It also seems to run in half the memory:
From: https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners

![image](https://github.com/user-attachments/assets/eee6732e-d329-4f97-899f-bac50d73cfdb)
