### ISSUE TITLE
Can't run v2 tests with nunit-console 3.0

### ISSUE THREAD

**Issue by xplicit** [nunit/nunit#485]
I made a test project which uses nunit.framework 2.6.4 from stable nuget package. Then I try to run it using nunint-console 3.0.0-alpha-5a, installed from nuget package and I've got an error:

    NUnit.Console.3.0.0-alpha-5a\tools\nunit-console.exe --framework=net-4.0 nunit26Perf\bin\Debug\nunit26Perf.exe 

    Unable to locate a driver for C:\projects\nunitperf\nunit26Perf\bin\Debug\nunit26Perf.exe

The project reference: 
https://github.com/xplicit/nunitperf/tree/master/nunit26Perf
Logs with error:
https://ci.appveyor.com/project/xplicit/nunitperf/build/1.0.8

**Comment by CharliePoole** [comment]
Are you able to run the project from a regular (zip) install of NUnit?

**Comment by rprouse** [comment]
Or does it work without the `--framework=net-4.0` command line? It would help to narrow it down to the nuget package or the running of 2.6 tests.

**Comment by CharliePoole** [comment]
@xplicit Just as an aside, I hope you are aware that specifying the framework is unnecessary unless you want to  run under a higher level runtime than the one you targeted.

**Comment by xplicit** [comment]
@CharliePoole I'll try this and will write the results. About the `framework` settings: I'm trying to solve two tasks: find the configuration of nunit version and nunit-console settings, which will allow me to run tests for Microsoft Bond in appveyor without the timeout and find the simple project/nunit-console configuration which demonstrates different times when running under appveyor.  So I test various settings to get it :)    

@rprouse I tried remove `--framework=net-4.0`, but this did not help. You can look into new logs, the error is same https://ci.appveyor.com/project/xplicit/nunitperf/build/1.0.11

**Comment by xplicit** [comment]
@CharliePoole the version from the site shows the same error

    curl https://github.com/nunit/nunit/releases/download/3.0.0-alpha-5/NUnit-3.0.0-alpha-5.zip -L -o nunit.zip
    nunit\bin\nunit-console.exe nunit26Perf\bin\Debug\nunit26Perf.exe
    ...
    Unable to locate a driver for C:\projects\nunitperf\nunit26Perf\bin\Debug\nunit26Perf.exe

logs 
https://ci.appveyor.com/project/xplicit/nunitperf/build/1.0.14

**Comment by CharliePoole** [comment]
Turns out that the nuget package and the binary zip are both missing the same two files:
  * nunit.engine.addins
  * nunit.engine.addin.xml
They are present in the msi install for the console.

I'm going to fix this and re-upload the files with suffixes, as I did earlier for the nuget package. I won't call it an alpha 6.

**Comment by CharliePoole** [comment]
This is fixed in the build script for beta 1. The alpha-5 release has been updated with new uploads for the binary zip and the nunit-console nuget package labeled alpha-5b.

**Comment by xplicit** [comment]
Download page http://nunit.org/index.php?p=download for binaries of nunit 3.0 linked to non-existing zip archive

**Comment by ArsenShnurkov** [comment]
i hit this (or similar) thing in my nunit-3.0.0_beta3-r201508190.ebuild

https://gist.githubusercontent.com/ArsenShnurkov/aad5f18f789b12638810/raw/619bc456333a710b5b455ebe4656f071327a57ed/stdin

**Comment by CharliePoole** [comment]
Well, it's likely to be due to a similar cause... either you haven't put the v2 driver in an appropriate directory or the addins file is not pointing to it. What does your install directory for the engine look like?
