### ISSUE TITLE
Expand the usability of `Contains.Key(...).WithValue(...)`

### ISSUE THREAD

**Issue by RenderMichael** [nunit/nunit#4852]
I want to assert on HTTP response headers, but the `DictionaryContainsKeyValuePairConstraint` created by `Contains.Key(...).WithValue(...)` does not work on the type.

Currently the constraint checks for `IDictionary` and (despite the error message) also `IDictionary<TKey, TValue>`.

However, the `HttpHeaders` type implements `IEnumerable<KeyValuePair<string, IEnumerable<string>>>` (and of course the non-generic `IEnumerable` interface implicitly) and nothing else.

Would it be acceptable to expand the checks on this contraint to allow `IEnumerable<KeyValuePair<TKey, TValue>>` as well? I'm happy to work on it if the change would be accepted.

**Comment by RenderMichael** [comment]
It's worth noting that `Contains.Item(new KeyValuePair<string, Enumerable<string>>(key, value))` does the job. However, on top of being unintuitive, hard to type and read, and un-NUnit-like, it doesn't say whether the key was found or not.

It would be helpful to see whether the key was found with a different value, or the key was not found to begin with (which is outside the scope of `Contains.Item`).

**Comment by manfred-brands** [comment]
@RenderMichael I have no objection to add support for `IEnumerable<KeyValuePair<TKey, TValue>>` to `Contains`.
Go ahead

**Comment by RenderMichael** [comment]
Thanks. Opened #4854
