### ISSUE TITLE
Running NUnit from "Gallio Iracus" runner

### ISSUE THREAD

**Issue by mikey189** [nunit/nunit#486]
Hi,

I am trying to run my nunit tests with gallio runner, and the "TestContext.CurrentContext.Test.FullName" property is throwing null reference exception. Do you familiar with this issues ? is it possible to fix it some how ?

Thx

**Comment by rprouse** [comment]
I run NUnit 2.6.x tests under Gallio.Echo without errors although those tests only use the basic NUnit features. What version of NUnit are you using? This is the 3.0 repository, are you using 3.0? 3.0 requires an entirely different runner and will never work in Gallio.

Work on Gallio stopped in July 2012 and the last version of NUnit that they supported was 2.4, so I don't think there is much we can do to help you. I am going to close this issue as invalid, but feel free to get back to us with more information. If there is a good reason, we can re-open the issue. If you need alternatives to Gallio for running your tests, let us know and we can help.
