### ISSUE TITLE
Test process abortion is not reported on CI with dotnet test

### ISSUE THREAD

**Issue by Helco** [nunit/nunit#4878]
While working on some deadlock problems in my main project I saw that a CI runs that should fail - would not. I reduced this problem as much as possible [in this test repo](https://github.com/Helco/TestNUnitNotFailing) with an example CI run [here](https://github.com/Helco/TestNUnitNotFailing/actions/runs/11663722386/job/32472748920).

I am using NUnit 4.2.2 with the NUnit3TestAdapter 4.6.0 and `dotnet test` both locally and on the CI.

The probably useful parts of the log are these - especially noteworthy is that more tests are discovered at the start than reported in the "Total tests".

```
NUnit Adapter 4.6.0.0: Test execution started
Running all tests in /home/runner/work/TestNUnitNotFailing/TestNUnitNotFailing/TestProject1/bin/Debug/net8.0/TestProject1.dll
   NUnit3TestExecutor discovered 2 of 2 NUnit test cases using Current Discovery mode, Non-Explicit run
NUnit Adapter 4.6.0.0: Test execution complete
  Passed Test1 [19 ms]

Test Run Successful.
Total tests: 1
     Passed: 1
```

If I instead run the same `dotnet test` command locally the failure is reported and the command has a non-zero exit code:

```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
NUnit Adapter 4.6.0.0: Test execution started
Running all tests in C:\Develop\prv\TestNUnitNotFailing\TestProject1\bin\Debug\net8.0\TestProject1.dll
   NUnit3TestExecutor discovered 2 of 2 NUnit test cases using Current Discovery mode, Non-Explicit run
Unhandled exception. System.AggregateException: One or more errors occurred. (One or more errors occurred. (Multiple failures or warnings in test:
  1) Test was cancelled, most likely due to a timeout.
  2) Exception during Cancellation: NUnit.Framework.AssertionException: Test was cancelled, most likely due to a timeout.
   at NUnit.Framework.Assert.ReportFailure(String message)
   at NUnit.Framework.Assert.Fail(String message)

(Many more lines of stack traces and inner exceptions removed)

Test Run Aborted.
```

<details>
<summary>This is the test fixture that aborts the process by causing unhandled exceptions after NUnit triggers the cancellation token: </summary>

```csharp
﻿using NUnit.Framework;

namespace TestProject1;

[TestFixture]
[Apartment(ApartmentState.STA), CancelAfter(1000)]
public sealed class TestTestFixture
{
    [SetUp]
    public void Setup()
    {
        TestContext.CurrentContext.CancellationToken.Register(() => Cleanup("Cancellation"));
    }

    [TearDown]
    public void TearDown() => Cleanup("TearDown");

    private static void Cleanup(string reason)
    {
        try
        {
            if (TestContext.CurrentContext.CancellationToken.IsCancellationRequested)
                Assert.Fail("Test was cancelled, most likely due to a timeout.");
        }
        catch (Exception e)
        {
            Assert.Fail($"Exception during {reason}: {e}");
        }
    }

    [Test]
    public async Task T()
    {
        await Task.Delay(30000);
        Assert.Pass();
    }
}
```

</details>

**Comment by OsirisTerje** [comment]
Can you please upload a repro project?

You can a) Add it as a PR to https://github.com/nunit/nunit3-vs-adapter.issues, add it as a separate folder named IssueXXX where the XXX is the issue number, or b) Add it as a zipped attachment here , or c) Add it to your own repo and just post the link. 

Make it as small as you can, it should compile "as is".

**Comment by OsirisTerje** [comment]
It seems the framework crashes and then crashes the testhost itself.  

<img width="854" alt="image" src="https://github.com/user-attachments/assets/e9422b3c-0d70-4cc2-a8f9-b6fbc94403de">

@manfred-brands Any clues ?

**Comment by manfred-brands** [comment]
@Helco @OsirisTerje The error is caused by the `Register` call in the `SetUp` method:

`TestContext.CurrentContext.CancellationToken.Register(() => Cleanup("Cancellation"));`

This will cause the `Cleanup` method to run on a thread outside of `NUnit` control.
The `Cleanup` method then throws exceptions using `Assert.Fail` but as these are called outside NUnit's control, they are not caught by NUnit and result in an `UnobservedTaskException`.

If I comment out the `SetUp` method and replace the Delay with
`await Task.Delay(30000, TestContext.CurrentContext.CancellationToken);`
and then run the test I get:

```
NUnit Adapter 4.6.0.0: Test execution started
Running all tests in D:\Development\Playground\TestNUnitNotFailing\TestProject1\bin\Debug\net8.0\TestProject1.dll
   NUnit3TestExecutor discovered 2 of 2 NUnit test cases using Current Discovery mode, Non-Explicit run
NUnit Adapter 4.6.0.0: Test execution complete
  TestProject1 test failed with 1 error(s) (1.8s)
    D:\Development\Playground\TestNUnitNotFailing\TestProject1\TestTestFixture.cs(27): error TESTERROR:
      T (1s 17ms): Error Message: Multiple failures or warnings in test:
        1) Test was cancelled, most likely due to a timeout.
        2) Exception during TearDown: NUnit.Framework.AssertionException: Test was cancelled, most likely due to a timeo
      ut.
         at NUnit.Framework.Assert.ReportFailure(String message)
         at NUnit.Framework.Assert.Fail(String message)
         at TestProject1.TestTestFixture.Cleanup(String reason) in D:\Development\Playground\TestNUnitNotFailing\TestPro
      ject1\TestTestFixture.cs:line 23

      TearDown : Multiple failures or warnings in test:
        1) Test was cancelled, most likely due to a timeout.
        2) Exception during TearDown: NUnit.Framework.AssertionException: Test was cancelled, most likely due to a timeo
      ut.
         at NUnit.Framework.Assert.ReportFailure(String message)
         at NUnit.Framework.Assert.Fail(String message)
         at TestProject1.TestTestFixture.Cleanup(String reason) in D:\Development\Playground\TestNUnitNotFailing\TestPro
      ject1\TestTestFixture.cs:line 23

...

Test summary: total: 2, failed: 1, succeeded: 1, skipped: 0, duration: 1.8s
Build failed with 1 error(s) in 2.6s
```

Why it behaves differently in CI is likely an OS issue.
@Helco Do you locally use Windows?
The CI uses Ubuntu and the test requires `ApartmentState.STA` which is not available on Linux.
NUnit marks the whole fixture as `NotRunnable`.

@OsirisTerje This doesn't seem the counting as a `Skipped` test, but doesn't show up at all:
`Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: 15 ms - TestProject1.dll (net8.0)`

If I comment out the `Apartment` attribute, the test also fails on Linux.

**Comment by Helco** [comment]
Yes I am using Windows locally and removing the `Apartment`  attribute lets the tests run on CI as well - with the expected failure.
Thanks for the analysis!

**Comment by manfred-brands** [comment]
> Unfortunately without the STA apartment I will run into the limitations mentioned by https://github.com/nunit/nunit/issues/4110.

If you want to use Windows only code you should a `windows` runner on CI instead of `ubuntu`.

But can you elaborate why you need a SingleThreadedTestSynchronizationContext?
Maybe update your example.

**Comment by Helco** [comment]
I was using the STA apartment just to enable the SingleThreadedTestSynchronizationContext, so the code should also run on Linux.

With this context I mirror the behavior of the actual application where 99% is run synchronous on a single thread, running a game loop. The only exception to this is loading files from disk. Most of the time these are not needed right away so should run on the thread pool as isolated actions. The code for applying them has to run on the main thread again in order to not care about synchronization in the other 99% of the application code.

If I was using MTA then awaiting in a test (e.g. scenarios like "File A was requested while being loaded") then any continuation might run on a different thread which is checked by the component in order to throw if used in this incorrect way.

Such a test might look like the following snippet (and [updated repo](https://github.com/Helco/TestNUnitNotFailing/blob/1317a8abaa3a4accc0a5d48c59b9ccec92382ea5/TestProject1/TestTestFixture.cs#L32)). Again a single-threaded synchronization context is necessary so the test starts and ends in the same thread which is how the actual application would run and this behavior would be checked by the `FileLoading` class

```csharp
    [Test]
    public async Task LoadSynchronousWhileAlreadyStartedToLoad()
    {
        var fileLoader = new TestFileLoader();
        FileLoading.LoadAsync(fileLoader);

        // Make sure that the asset is currently loading
        await fileLoader.WasStarted.Task;
        
        var contents = FileLoading.LoadSync(fileLoader);
        Assert.That(contents, Is.EqualTo("The contents of the loaded file"));
    }
```

**Comment by manfred-brands** [comment]
>  any continuation might run on a different thread which is checked by the component in order to throw if used in this incorrect way.

By default continuation with `await` continue on the same thread as the caller.
To indicate your intentions you can use [`ConfigureAwait(true)`](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.configureawait?view=net-8.0#system-threading-tasks-task-configureawait(system-boolean)) to indicate that you want to capture the context and return on it.

See: https://devblogs.microsoft.com/dotnet/configureawait-faq/

**Comment by Helco** [comment]
No, as per the linked FAQ:

> ConfigureAwait(continueOnCapturedContext: false) is used to avoid forcing the callback to be invoked on the original context or scheduler.

Meaning if you are on a multi-threaded synchronization context, not using `ConfigureAwait(false)` will just guarantee that same context to be used for the continuation. The context itself can and will choose any thread to run the continuation. You can test this with the following snippet: 

```csharp
[Test]
public async Task TestConfigureAwaitTrue()
{
    var previousThreadId = Environment.CurrentManagedThreadId;
    await Task.Delay(1).ConfigureAwait(true);
    var currentThreadId = Environment.CurrentManagedThreadId;
    
    Assert.That(previousThreadId, Is.EqualTo(currentThreadId));
}
```

**Comment by manfred-brands** [comment]
@Helco Thanks for that. I stand corrected.

I move this conversation over to #4110.

Can we then close this ticket as the original cause was identified?

**Comment by Helco** [comment]
Sure, thanks for the base class as workaround.
