### ISSUE TITLE
Optimize ToArray()[0] with First() in TestAssert class in TestAssert.cs

### ISSUE THREAD

**Issue by Saurav-shres** [nunit/nunit#4886]
In the TestAssert class, specifically in methods like IsRunnable and IsNotRunnable, the code currently uses ToArray()[0] to access the first element in a collection (result.Children). This approach creates an array unnecessarily, when the First() LINQ method can be used instead to directly get the first element without the added overhead of creating an array.

**Current Code:**
```
if (result.HasChildren)
    result = result.Children.ToArray()[0];
```

**Proposed Improvement:**
Replace the ToArray()[0] with the more efficient First() method from LINQ to avoid unnecessary array allocation.
```
if (result.HasChildren)
    result = result.Children.First();
```

**Comment by stevenaw** [comment]
Great find! The proposed change makes sense to me. Would you like to submit a PR to fix it?
