### ISSUE TITLE
Prepare release version 4.3

### ISSUE THREAD

**Issue by OsirisTerje** [nunit/nunit#4892]
We have 27 closed issues for 4.3.

Currently open issues:  

- [x] #4110 ,  PR in work, approved, waiting for a comment.
- [x] Create release notes

@nunit/framework-team Anything else you think should be included ?   @manfred-brands @stevenaw

**Comment by stevenaw** [comment]
Nothing on my end, thanks @OsirisTerje 

I have my eye on a few things that I hope to do for the following release, but nothing worth holding this one up over.

**Comment by manfred-brands** [comment]
I only have PR #4883 open.

**Comment by mikkelbu** [comment]
I don't have anything for 4.3, but I'm also mostly just "following along" in the framework at moment.

**Comment by jdevries-gen** [comment]
Hey guys!
Just wanted to chime in to note that we are in dire need of this release as it adds .net 9 support :)

**Comment by mikkelbu** [comment]
> Hey guys! Just wanted to chime in to note that we are in dire need of this release as it adds .net 9 support :)

@jdevries-gen You don't need a new release of the framework for using .NET9. Can you say what is failing? (perhaps in a new issue)
![image](https://github.com/user-attachments/assets/3ba91bae-aae3-4283-a653-5e29cbf7ca2a)
