### ISSUE TITLE
Problem with 'await Assert.ThrowsAsync...' method

### ISSUE THREAD

**Issue by SamOxigen** [nunit/nunit#4894]
In my unit test (NUnit test projects) my test throws an error while testing an expected exception outcome. I have created a demo test class that throws the same error and I want to know if anyone had a similar error and how they fixed it.

Meanwhile here are my environment.
Windows 11
I am using Visual Studio 2022 and my project uses NET 8.0 framework.
My nugget package has the following NUnit dependency versions installed:
NUnit --version 3.14.0 (latest stable version in Nugget Package Manage shows: 4.2.2)
NUnit.Analyzers --version 3.9.0 (latest stable version in Nugget Package Manage shows: 4.0.0)
NUnit3TestAdapter --version 4.5.0 (latest stable version in Nugget Package Manage shows: 4.5.0)

I am a little hesitant to update my nugget packages unless the issue below is clearly fixed in newer versions

Below is the test following the error.
`await Assert.ThrowsAsync<DivideByZeroException>(async () => await new myClass().DoSomethingAsync(6, 0));`

> Error CS1061 "DivideByZeroException' does not contain a definition for 'GetAwaiter' and no accessible extension method 'GetAwaiter' accepting a first argument of type 'DivideByZeroException' could be found (are you missing a using directive or an assembly reference?)."

	

And my test class:
```
public class myClass 
    {
        public async Task<double> DoSomethingAsync(int arg1, int arg2)
        {
            try
            {
                double result = 0;
                await Task.Run(() => { result = arg1 / arg2; });
                return result;
            }
            catch (DivideByZeroException) 
            {
                throw;
            }
        }
    }

**Comment by mikkelbu** [comment]
This is an instance of #4384 - i.e. that `Assert.ThrowsAsync` is not awaitable at the moment (see the the other ticket for the longer discussion). I guess the quick fix is to change the assert to
```csharp
Assert.ThrowsAsync<DivideByZeroException>(async () => await new myClass().DoSomethingAsync(6, 0));
```

**Comment by SamOxigen** [comment]
Thanks, that suggestion worked well!
