### ISSUE TITLE
PostTestAttribute

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#49]
NUnit version 2.5.7
Runner: Console and GUI

Feature Request:

I'd love to have the ability to override a test's result (e.g. Pass/Fail/Error) in the [TearDown] method along with the option to overwrite the error message.

Some more background:

I just started with a team that uses NUnit for running for automation testing. Given that NUnit is specifically built for unit testing, I've been surprised just how well it meets our needs. The only hangup I currently have is that we have certain classes of errors that only occur on threads other than the main thread. Without going into details, it's basically impossible for us respond to these errors on the main thread without adding code everywhere to poll if any of these errors have occurred, and if so, Assert.Fail(). Without detecting the errors at all, our code ends up asserting or throwing an exception for something else on the main thread which just ends up obfuscating the real problem in the resulting TestResult.xml file.

I understand why NUnit doesn't pick up assertions/exceptions on different threads, but we could easily workaround this if we had the ability to override the test result and error message in the [TearDown] method. At that point we'd know if any of these errors had occurred and could signal the test as failing and give a more appropriate message.

See discussion at https://bugs.launchpad.net/nunit-3.0/+bug/691455

**Comment by CharliePoole** [comment]
@rprouse I'm in favor of closing this old issue.

**Comment by uchagani** [comment]
resurrecting this as something that I'm running into from an integration test perspective:

Usecase:

We have a bunch of random failed integration tests related to performance that hasn't been a high priority to fix.  The testing team spends a lot of time combing through failed tests and figuring out which test is a real failure and which is related to this performance issue.

The performance issue manifests itself as an alert on our website and we can detect this through our automation framework.

What I would like to do in the teardown is:

If result is not success, check the page for the performance issue alert, log the error, but either pass the test or ignore the result of the test (inconclusive?).

I think it's important to note that NUnit is used a lot in integration test suites.  I'm open to suggestions on another way to do this via extending nunit.

**Comment by CharliePoole** [comment]
This very old issue started life as one thing (TearDown) and was rejected. Then I changed it, proposing a new attribute (PostTest) which would not be constrained by the rules of TearDown. That didn't attract enough interest, so it was eventually closed without action.

So, if you want to revisit it, you should probably say which notion you want to revisit.

**Comment by uchagani** [comment]
I'd like to revisit the PostTest version of this that might allows the user to change the test result itself.

**Comment by CharliePoole** [comment]
Someone on the team would have to decide whether to reopen this, of course. However, even when it was open, it sat for a long time without action... notice the low issue number!

OTOH, it seems to me that it would be pretty easy to create such an attribute yourself. If you decide to try it, look at `MaxTimeAttribute` as a model. It changes a success  to a failure if the test ran more than a certain amount of time.

**Comment by uchagani** [comment]
I need this to run after every test. Would that still be possible with my
own attribute?

**Comment by CharliePoole** [comment]
Definitely possible but maybe not so convenient. NUnit will let you do lots
of things in a custom attribute but you need to apply it on each test you
want it to affect. There is really no general mechanism for injecting extra
steps into __all__ your tests.
