### ISSUE TITLE
Strange null reference after updating to v4.3.0

### ISSUE THREAD

**Issue by rudfoss-rr** [nunit/nunit#4903]
I have a very strange problem that I can't seem to figure out. I have a very simple test that worked fine in NUnit v3.14 (original) and in v4.2.2, but when I updated to v4.3.0 it suddenly fails with an actual value that is `null`.

```csharp
  public void SupportsSubscopes()
  {
    var scope = PermissionScope.New("app");
    Assert.That(scope, Is.Not.Null);
    var expected = PermissionScope.New("app");
    Assert.That(expected, Is.Not.Null);
    Assert.That(scope, Is.EqualTo(expected));
}
```

![image](https://github.com/user-attachments/assets/3071550f-09b8-4e7b-9abe-d6f19d0a6a75)

If I debug the test and evaluate equality explicitly it is `true`, but the `Assert.That` line throws.

![image](https://github.com/user-attachments/assets/9973456a-6e25-479a-b8d6-6e97417646d0)

What could be the problem here? The code looks fine to me, but it seems that NUnit looses track of the actual value at some point. Could this be a bug in NUnit? I've reverted to `4.2.2` and it works fine.

**Comment by OsirisTerje** [comment]
A bit unsure about the class you're having there, does it have implicit operators or something?
You might be hitting #4898 (and #4902) , which is resolved in #4899.   

If you make your code above into a small repro class, we can add it to the tests we have ongoing now, and check it out.

**Comment by rudfoss-rr** [comment]
You're right that it has an implicit operator for string conversion. It works fine with v4.2.2 but broke for v4.3.0. I suspect it is due to the same problem you linked to as it also selects the `string` overload.
![image](https://github.com/user-attachments/assets/64b2499d-b306-41fe-9db1-964dfec66a94)

I rebuilt the test in LINQPad and it fails there as well. This is the complete code using v4.3.0:

```csharp
public record PermissionScope
{
	/// <summary>
	/// The full scope name.
	/// </summary>
	public string Name { get; private init; }
	
	private PermissionScope(string name) { Name = name; }

	public static PermissionScope New(string value) {
		return new(value);
	}
	
	public static implicit operator string(PermissionScope scope) => scope.Name;
}

void Main()
{
	var scope = PermissionScope.New("app");
	Assert.That(scope, Is.Not.Null);
	var expected = PermissionScope.New("app");
	Assert.That(expected, Is.Not.Null);
	Assert.That(scope, Is.EqualTo(expected));
}
```

**Comment by stevenaw** [comment]
Thanks for the report and repro @rudfoss-rr 
I can confirm that this is the same issue and that your repro currently passes when run on the branch to fix it.

The PR which will fix this is https://github.com/nunit/nunit/pull/4899. We will be publishing a 4.3.1 release for this

**Comment by rudfoss-rr** [comment]
Thanks for the quick response guys!

**Comment by OsirisTerje** [comment]
@rudfoss-rr  4.3.1 released now.  Would appreciate if you could confirm it works for you. https://docs.nunit.org/articles/nunit/release-notes/framework.html#nunit-431----dec-21-2024

**Comment by rudfoss-rr** [comment]
> @rudfoss-rr 4.3.1 released now. Would appreciate if you could confirm it works for you. https://docs.nunit.org/articles/nunit/release-notes/framework.html#nunit-431----dec-21-2024

✅Verified working. Thanks!
