### ISSUE TITLE
Assert.ThatAsync fail to catch expected exception

### ISSUE THREAD

**Issue by shlomi-borovitz-greenroad** [nunit/nunit#4907]
Given a simple test to check that an async method throws a certain exception - 

```csharp
namespace TestFailToFail;

public class Tests
{
    [Test]
    public async Task Test1()
    {
        await Assert.ThatAsync(async () => throw new Exception("Ugh"), Throws.Exception);
    }

    [Test]
    public async Task Test2()
    {
        await Assert.ThatAsync(() => Task.FromException(new Exception("Ugh")), Throws.Exception);
    }

    [Test]
    public void Test3()
    {
        Assert.That(() => throw new Exception("Ugh"), Throws.Exception);
    }
}
```

With NUnit 4.2.2 - all tests pass (as expected)
With NUnit 4.3.0 (and also 4.3.1) - both `Test1` and `Test2` fail with the thrown exception. Only the sync version - `Test3` pass

```
 Test1
   Source: UnitTest1.cs line 6
   Duration: 8 ms

  Message: 
System.Exception : Ugh

  Stack Trace: 
<<Test1>b__0_0>d.MoveNext() line 8
--- End of stack trace from previous location ---
<<ThatAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
Constraint.ApplyToAsync[TActual](Func`1 taskDel)
Assert.ThatAsync(AsyncTestDelegate code, IResolveConstraint constraint, NUnitString message, String actualExpression, String constraintExpression)
Tests.Test1() line 8
GenericAdapter`1.GetResult()
AsyncToSyncAdapter.Await[TResult](TestExecutionContext context, Func`1 invoke)
AsyncToSyncAdapter.Await(TestExecutionContext context, Func`1 invoke)
TestMethodCommand.RunTestMethod(TestExecutionContext context)
TestMethodCommand.Execute(TestExecutionContext context)
<>c__DisplayClass3_0.<PerformWork>b__0()
<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
ContextUtils.DoIsolated(ContextCallback callback, Object state)
ContextUtils.DoIsolated[T](Func`1 func)
SimpleWorkItem.PerformWork()
```

**Comment by manfred-brands** [comment]
@shlomi-borovitz-greenroad I can confirm that your tests fail in 4.3.1.

They however pass when I use:
```
[Test]
public async Task Test1()
{
    await Assert.ThatAsync(async () => throw new Exception("Ugh"), Throws.InstanceOf<Exception>());
}

[Test]
public async Task Test2()
{
    await Assert.ThatAsync(() => Task.FromException(new Exception("Ugh")), Throws.InstanceOf<Exception>());
}
```

It looks like we forgot to add an `ApplyToAsync` to `ThrowsExceptionConstraint` for PR #4813.

**Comment by shlomi-borovitz-greenroad** [comment]
> > @manfred-brands Should we release 4.3.2 for this ?
> 
> The standalone `Tnrows.Exception` is a not recommended constraint according to our [documentation](https://docs.nunit.org/articles/nunit/writing-tests/constraints/ThrowsConstraint.html?q=Throws#notes)
> 
> I don't know how much it is used.
> 
> The workaround is to specify the type of the exception.

It also not deprecated 

And while I usually throw more specific exceptions (and then test for those) - I wasn't aware that it is not recommended (I would have - if it was deprecated and would have avoiding it).

I cannot speak for others of course

**Comment by stevenaw** [comment]
Is this just an issue with `Throws.Exception` when combined with the delay constraint, or with either one independently? 

FWIW, in terms of `Throws.Exception` usage, it has seen creeping increased usage in our codebase at work. I suspect it could be because the generality is very easy (broadly usable) to copy/paste around. Would we want to consider a code-level nudge to supplement our hosted docs site? I don't know if we'd actually want to deprecate `Throws.Exception` but perhaps an xmldoc hint could be a useful guide to improving test robustness.

**Comment by OsirisTerje** [comment]
When we have a regression from the former version, I normally believe we should fix and release a hotfix.  
I found more than 1.7K usages on github, so I'll add this to an upcoming 4.3.2 release.  

I also added a repro, which includes checks on the other usages from the documentation @manfred-brands linked to here: https://github.com/nunit/nunit.issues/tree/main/Issue4907

**Comment by shlomi-borovitz-greenroad** [comment]
[heart]         Shlomi Borovitz reacted to your message:
________________________________

**Comment by stevenaw** [comment]
Agreed @OsirisTerje we definitely shouldn't be prescriptive there. Just a kind, helpful hint. Perhaps just something along the lines of "Resolves for any thrown constraint. You may consider using Throws.TypeOf<T>" if you wish to target a specific exception type."

Though _perhaps_ even that almost seems heavy handed in retrospect. Anyone viewing the xmldocs in intellisense would also then have access to discover the specific-typed overloads as well. 

I suppose I don't have a strong preference either way on the xmldoc approach, but I offer it as an idea here if others like it.
