### ISSUE TITLE
Versioning for .NET Framework 4.6.2 version of NUnit v4.3.1 inconsistent in `.csproj` file

### ISSUE THREAD

**Issue by astrohart** [nunit/nunit#4910]
In the past, the reference to `NUnit` in a `.csproj` file was:

```XML
<Reference Include="nunit.framework, Version=4.0.1.0, Culture=neutral, PublicKeyToken=2638cd05610744eb, processorArchitecture=MSIL">
  <HintPath>..\packages\NUnit.4.0.1\lib\net462\nunit.framework.dll</HintPath>
</Reference>
```

Notice the concordance between the version `4.0.1` of the package an the version, `Version=4.0.1.0` of the `Reference` tag.

When I upgrade to `4.3.1` of `NUnit`, I get:

```XML
<Reference Include="nunit.framework, Version=4.4.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb, processorArchitecture=MSIL">
  <HintPath>..\packages\NUnit.4.3.1\lib\net462\nunit.framework.dll</HintPath>
</Reference>
```

There is a different version `Version=4.4.0.0` in the `Reference` XML tag than in the `HintPath` (v `4.3.1`).

Is this by design?  Was there a typo?

**Comment by OsirisTerje** [comment]
This is not correct.  How do you install the package?  In SDK I do get a packagereference with 4.3.1.  
This looks like a package.config file thing, right ?

You're right, the assemblies have got the 4.4.00 version, which is incorrect.
