### ISSUE TITLE
List of classes that have been tested

### ISSUE THREAD

**Issue by yetibrain** [nunit/nunit#493]
Is it possible to get a list of classes that have been tested after a test run?

**Comment by CharliePoole** [comment]
Currently, you would have to run under a coverage tool to get this. I'm interested in adding this in a post-3.0 release of NUnit, so if you would like to spec it out here, that would be very useful.

**Comment by yetibrain** [comment]
The idea is, that NUnit provides a list/report along with a test result list, that shows the modules and classes and possibly also the methods of the code that has been tested by a certain test method. Not because to show the code coverage, but the classes/methods of the tested code. Because then, vice versa you can determine classes and methods of the code being tested and show all test-methods that test this class. If in productive code now a class has to be altered, changed or extended, we would know what tests we would need to run in order to test if the results are still "green" e.g. "passed".

The idea is to get a list of relations between test-methods and the productive classes of the testee being involved in order to know what classes of the testee code are used by what test.

**Comment by yetibrain** [comment]
After all we need a list of tests we have to run when we make changes in a certain testee class:

testee class A -> { Test A, Test F, Test X, ... }
testee class B -> { Test K, Test X, Test Z, ...}
...

To get this list, we'd like to first run all tests with NUnit and collect which classes/methods are called by a certain test. In this NUnit run we'd get a list like this:

Test A -> { testee class R, testee class T, testee class A, ...}
Test B -> { testee class A, testee class Q, testee class B, ...}
...

Afterwards we'd like to invert this list and get the following:

testee class A -> { Test A, Test F, Test X, ... }
testee class B -> { Test K, Test X, Test Z, ...}

When we make changes in a certain testee class, we want to know which tests we need to run.

**Comment by CharliePoole** [comment]
Basically, this requires coverage to be built into NUnit, accessible on a test by test basis... or could it be done at a higher level using a coverage tool?

**Comment by rprouse** [comment]
There isn't support for it in the runners yet, but we did add the TestOf
attribute in NUnit 3.0. This attribute takes the typeof the class that is
being tested and once it is supported in the runners will allow you to
filter and run tests based on the classes being tested.

The docs for this are at, http://www.nunit.org/index.php?p=testOf&r=3.0

This isn't everything you need, but it is a good start without our
including full test coverage in NUnit.

On 18 February 2015 at 11:47, CharliePoole <notifications@github.com> wrote:

> Basically, this requires coverage to be built into NUnit, accessible on a
> test by test basis... or could it be done at a higher level using a
> coverage tool?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nunit/nunit/issues/493#issuecomment-74899035>.
>



-- 

Rob Prouse



I welcome VSRE emails. Learn more at http://vsre.info/

**Comment by CharliePoole** [comment]
What I like about TestOf is that you can use if for class names or for any arbitrary subdivision of the application. Then you could generate reports based on those tags.

I have used this approach with clients using NUnit in the past, by including special tags in the Description attribute. In fact, I wrote an entire reporting system at one client, breaking down all the tests by _what_ they tested. "When I get a chance" I'll have to look back at that code. :-)

To the extent this idea is about history, I would definitely mark it future. If it's just  reporting based on the result of runs, I'm not sure. Probably, if we did it, it would be a separate app though.

**Comment by yetibrain** [comment]
Thanks Robert and Charly for your comments. We will have a look at the TestOf attribute.

**Comment by yetibrain** [comment]
I got 404 when trying to use Robs link  http://www.nunit.org/index.php?p=testOf&r=3.0
To use TestOf attribute requires manual work, i think usually a test method  will call some method of an instantiated class of the productivity code, but what other instances of other classes are used along with the test, is unknown and b.t.w not needed for the final test result.

So i agree with Charly, it seems that this idea should be realized in another app. What could be interesting is Charlies code e. g. Charlies Statement "When I get a chance" I'll have to look back at that code. :-)". If i'd have some code that takes a test DLL as Parameter as NUnit does, filters out all test methods by tracking Suite/Category Parameters and then invokes These methods, but ignores completely the "test result assertions" but rather collects all the types of the productivity code's involved instances and methods, then i could store the Name of a Test along with types of the productivity code. The more Tests run, the more i can realize a reversed view on the collected data, telling what test should run in order to get a productivity class that has become changed, tested entirely again (after changing it). That's the Approach.

**Comment by CharliePoole** [comment]
The original post goes back to before we moved documentation to the wiki. The current URL is https://github.com/nunit/docs/wiki/TestOf-Attribute

I changed Rob's post as well.

**Comment by rprouse** [comment]
Thanks for the idea, but this isn't in keeping with our vision of where we want to take NUnit, so I am closing.
