### ISSUE TITLE
nunitlite exception: couldn't load type "NUnitLite.Runner.TextUI"

### ISSUE THREAD

**Issue by xplicit** [nunit/nunit#494]
Not sure if it's bug or expected behaviour.

Create the empty console project named "nunitlite". Add nuget package "NUnitLite" to it. Compile and run. The exception will be raised  `couldn't load type "NUnitLite.Runner.TextUI"`. The exception is raised because the type is loaded from `nunitlite.exe` file, not `nunitlite.dll`. 

As a simple workaround just rename output assembly from "nunitlite.exe" to "nunitlite1.exe" and nunitlite will run as expected.

**Comment by CharliePoole** [comment]
This doesn't seem like a bug to me. @rprouse what do you think?

Basically, you're trying to load two assemblies with the same name into the same space. It's as if you called your tests nunit.framework.

**Comment by rprouse** [comment]
I am going to close this as expected behavior. This is just the way that .NET works, you cannot have multiple assemblies (EXE or DLL) with the same name loaded into the same process unless both are signed and each one is loaded in a different app domain.
