### ISSUE TITLE
Are you aware of the Gitter chat thing?

### ISSUE THREAD

**Issue by JohanLarsson** [nunit/nunit#500]
Sample:
https://gitter.im/MahApps/MahApps.Metro#

I think only members of the project can create the room.

**Comment by CharliePoole** [comment]
Interesting. Guys, do we want to consider this? I'm afraid that public live chat could be a time sink for us.

**Comment by JohanLarsson** [comment]
I hesitate to ask questions in issues, it feels wrong. Example: does nunit have something for comparing properties and fields of two instances?
Most rooms on Gitter are pretty quiet.

**Comment by CharliePoole** [comment]
Right, we prefer folks don't use the issues for questions, although we'll give short answers. For anything longer, we send them to nunit-discuss on google. We also have nunit-developer in the same place and private mailing lists for committers and 3rd party developers.

So I wonder about the incremental value of yet another channel. Also, chat implies that somebody is there to chat with, whereas mail-lists and forums don't have the expectation that an immediate answer is coming. 

I'd like to hear what others think.

**Comment by rprouse** [comment]
Personally, I like the idea of a group chat for the team and followers of
the project. I'm not sure, but I feel that mailing lists are not used very
much anymore and that most people are turning to places like Gitter. It
seems to be the primary means of communications for the core CLR and FX
teams on github. I also like that you can integrate other services like the
build servers.

If we go with it though, we should probably deprecate the mailing lists to
limit avenues of communications. That in itself is a tough decision.

Rob

On 8 February 2015 at 19:23, CharliePoole <notifications@github.com> wrote:

> Right, we prefer folks don't use the issues for questions, although we'll
> give short answers. For anything longer, we send them to nunit-discuss on
> google. We also have nunit-developer in the same place and private mailing
> lists for committers and 3rd party developers.
>
> So I wonder about the incremental value of yet another channel. Also, chat
> implies that somebody is there to chat with, whereas mail-lists and forums
> don't have the expectation that an immediate answer is coming.
>
> I'd like to hear what others think.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nunit/nunit/issues/500#issuecomment-73442308>.
>



-- 

Rob Prouse



I welcome VSRE emails. Learn more at http://vsre.info/

**Comment by CharliePoole** [comment]
Could you clarify how you see it being used and by whom? I guess what I'm
trying to figure out is how a live chat will help people who want answers
from us, unless some devs are online 24/7. Or are we talking about
self-help?

**Comment by rprouse** [comment]
I am new to Gitter too, but I think we need to not think of it as live
chat, but a better mailing list. It works like a mailing list in that the
conversation is preserved, but facilitates quick discussion type
communications when people are online. It also shows activity on the
project like pull requests and issues.

I am experimenting with other open source projects that I work with, so the
jury is still out, but it seems like a good central hub for communications.
Maybe it doesn't replace the mailing lists, but it could be a low friction
way for people to get in touch or talk with each other.

Rob

On 21 February 2015 at 17:46, CharliePoole <notifications@github.com> wrote:

> Could you clarify how you see it being used and by whom? I guess what I'm
> trying to figure out is how a live chat will help people who want answers
> from us, unless some devs are online 24/7. Or are we talking about
> self-help?
>
> On Sat, Feb 21, 2015 at 2:35 PM, Rob Prouse <notifications@github.com>
> wrote:
>
> > Personally, I like the idea of a group chat for the team and followers of
> > the project. I'm not sure, but I feel that mailing lists are not used
> very
> > much anymore and that most people are turning to places like Gitter. It
> > seems to be the primary means of communications for the core CLR and FX
> > teams on github. I also like that you can integrate other services like
> the
> > build servers.
> >
> > If we go with it though, we should probably deprecate the mailing lists
> to
> > limit avenues of communications. That in itself is a tough decision.
> >
> > Rob
> >
> > On 8 February 2015 at 19:23, CharliePoole <notifications@github.com>
> > wrote:
> >
> > > Right, we prefer folks don't use the issues for questions, although
> we'll
> > > give short answers. For anything longer, we send them to nunit-discuss
> on
> > > google. We also have nunit-developer in the same place and private
> > mailing
> > > lists for committers and 3rd party developers.
> > >
> > > So I wonder about the incremental value of yet another channel. Also,
> > chat
> > > implies that somebody is there to chat with, whereas mail-lists and
> > forums
> > > don't have the expectation that an immediate answer is coming.
> > >
> > > I'd like to hear what others think.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/nunit/nunit/issues/500#issuecomment-73442308>.
> > >
> >
> >
> >
> > --
> >
> > Rob Prouse
> >
> >
> >
> > I welcome VSRE emails. Learn more at http://vsre.info/
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/nunit/nunit/issues/500#issuecomment-75396859>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nunit/nunit/issues/500#issuecomment-75397370>.
>



-- 

Rob Prouse



I welcome VSRE emails. Learn more at http://vsre.info/

**Comment by CharliePoole** [comment]
As another alternative, I have started to feel we might pay more attention
to SO.

**Comment by rprouse** [comment]
Activity on our mailing lists is picking up and I followed the corefx gitter feed for awhile. I don't think this fits our project's needs right now. I am closing, but we can look at this again if the landscape changes.

Thanks for the suggestion.

**Comment by jnm2** [comment]
https://gitter.im/nunit/nunit now exists, by the way. It's linked from [our repo landing page](https://github.com/nunit/nunit#nunit-3-framework) as well as [nunit.org](http://nunit.org/).
