### ISSUE TITLE
Question about reusing TestDataSource attribute for reading different csv files of same format

### ISSUE THREAD

**Issue by melvin12345** [nunit/nunit#505]
Hello: 
I have a C# test solution in which I need to write 10 test cases in NUnit. Each test case reads from a different csv file. Each csv file consists of 2 columns (one input and one output) but many rows (>1000). I am using the TestDataSource attribute such as:

[Test]
[TestCaseSource(typeof(GetTestData), "TestData")]
public void Test1(GetTestData data)
{
…
}

with the following GetTestData class:

public class GetTestData
{
  public string CSVFileName { get; set; }
  public double input { get; set; }
  public double output { get; set; }

  public IEnumerable TestData
  {
    get
    {
      using (var inputStream = new FileStream(CSVFileName, FileMode.Open, FileAccess.Read))
      {
        using (var streamReader = new StreamReader(inputStream))
        {
          string inputLine;
          while ((inputLine = streamReader.ReadLine()) != null)
          {
            var data = inputLine.Split(',');
            yield return new GetTestData
            {
              Intput = Convert.ToDouble(data[0]),
              output = Convert.ToDouble(data[1]),
            };
          }            
        }
      }
    }
  }
}

I want to reuse the GetTestData class in all the test cases since all csv files have the same format. Since the CSVFileName is hardcoded in the class it looks like I will have to create a get data class for each test (GetTestData1, GetTestData2, …), although they all share the same code except for the definition of CSVFileName. 
My question is: How can I take out the CSVFileName variable outside of the class definition so I can reuse the GetTestData class for different csv files? If this is possible, how would the call for each different test look like?

In MSTest all you need to do is add the file name as part of the attribute, as in here:

[TestMethod,
DataSource("Microsoft.VisualStudio.TestTools.DataSource.CSV",
           "CSVFileName1.CSV", 
           "CSVFileName1#CSV",
            DataAccessMethod.Sequential),
DeploymentItem("CSVFileName1.csv")]
public void Test1()
{
…
}

[TestMethod,
DataSource("Microsoft.VisualStudio.TestTools.DataSource.CSV",
           "CSVFileName2.CSV", 
           "CSVFileName2#CSV",
            DataAccessMethod.Sequential),
DeploymentItem("CSVFileName2.csv")]
public void Test2()
{
…
}

…

How can I achieve such simplicity with NUnit?
Help will be much appreciated!

**Comment by CharliePoole** [comment]
This isn't the best place to ask questions (try our nunit-discuss group) but here's what I would do, given the features available in NUnit:

1. Create a separate method for each csv file you want to use. Specify that name in the attribute in place of TestData.

2. Move the code that reads the file and returns the data into a separate method, which takes the file name as an argument. Call that method from each of the individual test case source methods.

This is more complex than MsTest, but allows you to do much more as a tradeoff. We decided to make data sources be code written by the programmer and not directly support files. In nunit 3.0, it's possible to write an custom attribute that does support files directly. In NUnit 2.x, this is more complicated and requires an addin.

**Comment by melvin12345** [comment]
Hi CharliePoole,

Thank you so much for the fast response. 
I am solving the problem as you suggested.

Regards,

Melvin


 

 

 

-----Original Message-----
