### ISSUE TITLE
Drop the .NET 3.5 build

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#512]
@rprouse proposed this via email:

I've been looking at the .NET 3.5 version of the framework. As far as I can tell, the only additional functionality that it provides is the Assert/Assume.That which takes a Lambda returning Boolean.

If I am right, I propose that we drop the .NET 3.5 version of the framework. It seems like a very small increment in functionality compared to maintaining the six projects.

**Comment by CharliePoole** [comment]
We'll wait for a comments first, but if everyone agrees, we would...

 * Drop the 3.5 build entirely

 * Start running the tests of the 2.0 build under 3.5 and include use of lambdas where they work. This should be the case in many situations.

 * Remove all vestiges of 3.5 conditionals from the source code.

**Comment by rprouse** [comment]
Make sure PR #513 is merged before tackling this so we can remove from the installers too.

**Comment by CharliePoole** [comment]
I'm proceeding with this.

**Comment by CharliePoole** [comment]
I decided not to run the 2.0 framework tests under 3.5 because it complicated things with nunitlite. Those few excluded test cases are covered in the higher version tests.

**Comment by still-dreaming-1** [comment]
I'm confused. Does this mean tests cannot be run on the .NET Framework 3.5?

**Comment by CharliePoole** [comment]
No, you can use the 2.0 build of NUnit to run tests under 3.5. We dropped the 3.5 build because it had virtually no added functionality to what we provide in the 2.0 build.
