### ISSUE TITLE
how is --teamcity supposed to work

### ISSUE THREAD

**Issue by jmecosta** [nunit/nunit#518]
hi,

having issues trying to show teamcity messages, i was expecting once we set --temacity to display test progress with teamcity service messges. but i dont see anything. this is the only thing showing up

NUnit Console Runner 3.0.5509
Copyright (C) 2014 Charlie Poole

Test Files:
    E:\prod\src\work\BuildDrop\Work\bin_x64\test\Test..dll

Runtime Environment
   OS Version: Microsoft Windows NT 6.3.9600.0
  CLR Version: 4.0.30319.0

Options
    ProcessModel: Default    DomainUsage: Default
    Execution Runtime: Not Specified
    Work Directory: E:\prod\trimble-connect-desktop\Source
    Internal Trace: Off
    Display TeamCity Service Messages

Agent process 12092 starting
Running under version 4.0.30319.0, Net 4.5

nothing else... can someone tell me how this works?
thanks in advance

**Comment by jmecosta** [comment]
nevermind, this does not work if tests are using 2.6.2

**Comment by CharliePoole** [comment]
So, you're saying that the V3 tests run OK, but V2 tests don't send the teamcity messages? It seems like we should be able to make that work.

**Comment by CharliePoole** [comment]
This is a side effect of #517. 

Since the various events are not being passed back to the console runner, it has no opportunity to generate teamcity service messages.

**Comment by jmecosta** [comment]
V3 are fine, at least messages are generated. I had to modify some of my code to correctly get data from the feed. I will still need verify if everything is fine in our team city jobs. 

If manage to make it work also with v2 it would be cool.

**Comment by jmecosta** [comment]
works fine in teamcity, with v3
