### ISSUE TITLE
where can i find the nunit test runner adapter for vs 2013

### ISSUE THREAD

**Issue by jmecosta** [nunit/nunit#520]

**Comment by rprouse** [comment]
It is a Visual Studio extension, so you can find it in the extension gallery. Just go to Tools - Extensions in Visual Studio and search. We don't have a version that works with NUnit 3 yet, but it should be coming shortly.

**Comment by jmecosta** [comment]
Yep I was looking for the version that works with v3 resharper runner has
issues. Can I build the extension already or are there still code changes
needed?

**Comment by jmecosta** [comment]
anyway i found it and trying it now... thanks...

**Comment by rprouse** [comment]
No, sorry code changes are still required.

**Comment by CharliePoole** [comment]
As Rob says, code changes are needed.

NUnit 3.0 is made to pretty much "look like" NUnit 2.x, but it's an
entirely different internal implementation.

**Comment by jmecosta** [comment]
hi @CharliePoole 

any news when the nunit 3.0 runner will be avaialble?

**Comment by OsirisTerje** [comment]
You can download the CTP's of it here:  https://github.com/nunit/nunit3-vs-adapter/releases

**Comment by jmecosta** [comment]
great thanks, keep forgeting the adapter is in the vs-adapter repo

**Comment by CharliePoole** [comment]
It's also available in the VS gallery as the NUnit3 Test Adapter.
