### ISSUE TITLE
v3 Test Results xml <test-run> Attribute "errors" is missing from v3

### ISSUE THREAD

**Issue by CADbloke** [nunit/nunit#525]
Greetings. I was trying out an XML - HTML Report generator from https://github.com/SongArc/NUnit-HTML-Report-Generator and it crashed with a null reference errror (not your problem) when trying to parse the `"errors"` attribute in the `<test-results>`  node (their Program.cs line 180, fwiw).

The `"errors"` attribute is in the V2 writer @ `<test-results>` `NUnit2XmlOutputWriter.cs` line 101 and `NUnit2XmlResultWriter.cs` line 91 but not in `NUnit3XmlOutputWriter.cs` lines 93-115

Is this omission deliberate and permanent? Should I drop the "errors" attribute from the Report Generator code? I just thought I'd mention it in case "oh, sh..".

As a completely unrelated aside, I got NUnitLite V3 to run inside AutoCAD: http://www.theswamp.org/index.php?topic=39236.msg541082#msg541082 ...because mocking AutoCAD no way.

**Comment by CharliePoole** [comment]
Bear in mind that NUnit 3.0 is a complete remake of NUnit. Among other things, the V3 output format is different from that used in prior releases of NUnit. The V3 format is not yet final.

In NUnit 2.x the <test-results> element provides a summary of the test run. In NUnit 3.0, the <test-run> element serves the same purpose.

NUnit 2.x gives totals for the run as follows: total, errors, failures, not-run, inconclusive, ignored, skipped, invalid. Ignored, skipped and invalid together add up to the not-run value. Note that inconclusive was not always present, but was added a few years back.

NUnit 3.0 gives the following totals: total (new), passed(new), failed, inconclusive, skipped. The four values (excluding total) are the four final test statuses defined in NUnit 3.0. Failed includes errors, failures and invalid tests. Skipped includes ignored tests as well as those skipped for any other reason. Each of these may also include new result types defined by the user as a refinement of one of the basic statuses. Any report needing a more detailed breakdown beyond the four fundamental statuses will need to descend into the detail of the tests to accumulate totals.

Do you want to propose any changes to the XML output or shall we close this?

PS: Thanks for the info about AutoCad. Running inside of other things is one of the big reasons I wrote NUnitLite.

Running inside of other things is one of the key purposes in life of NUnitLite. I'm glad to hear you're using it that way.

**Comment by CADbloke** [comment]
> Do you want to propose any changes to the XML output or shall we close this?

I'm not fussed either way (the errors are very obvious in the runner) so let's close this issue now that I have the answer. Anything I write for NUnit will be for Version 3 so if I know what to write then I have no problem.

> PS: Thanks for the info about AutoCad. Running inside of other things is one of the big reasons I wrote NUnitLite.

Hey, thanks for writing NUnitLite - it completely revolutionised the way I can test my apps. I previously tried mocks but AutoCAD is so huge and complex (and it is an object-oriented transactional database) that it completely stole all my time, leaving no time to write actual production code. Untying all the dependencies with Interfaces introduced levels of indirection you usually only see in Congress, much confuse.  NUnitLite makes it very easy to test behaviors in the actual environment they run in. So easy!

Previously some people used Gallio's AutoCAD plugin but that is not maintained anymore and I certainly didn't want to take it on. I fiddled with a small hand-built test runner but NUnitLite is a no-brainer - it works, it's fast, it's easy, it runs in the debugger, and I already use NUnit so well done there on all counts.

I didn't have much luck running NUnitLite V2 inside AutoCAD but I'll admit I didn't persist for long since V3 is the way forward. AutoCAD runs as a single thread on the UI thread so it's a pig to get foreign things to run in it. Older versions use Fibers too so that adds to the joy. The Joy.

It would be an interesting exercise to get an in-process GUI runner to run inside AutoCAD, it can show modal and modeless dialogues, and tool palettes so it is quite plausible. 

I plan on tidying my adapter and posting the code on Github sometime soon, I'm still ~~gold-plating~~ finishing it. 

cheers
Ewen

**Comment by CADbloke** [comment]
Here's my AutoCAD adapter for NUnit: https://github.com/CADbloke/CADtest
Suggestions etc are more than welcome.

**Comment by CharliePoole** [comment]
This looks great! Thanks for the link. FYI, the latest NUnitLite code uses
a different calling sequence to start the test run. This will show up in
the beta1 release.

**Comment by CADbloke** [comment]
Ah, thanks. I see that at https://github.com/nunit/nunit/commit/6331e7e694439f8cbf000156f138a3e10370ec40

Hey, a link or two is the least I could do - you wrote the framework, I just bolted it on.
