### ISSUE TITLE
Separate NUnitLite runner and autorunner

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#533]
Changes in PR #526 included a new AutoRun class, for use by self-running tests. However, the class still includes some elements from the old runner, which are not appropriate for an autorunner. In particular, other input files are still accepted on the command line although they are ignored with a warning.

We should have a separate runner class for use in running one or more tests under nunitlite. We may want this to be in a separate assembly (an exe) as well.

Additionally, each runner should only accept the options that are relevant to it, which may involve some refactoring of the ConsoleOptions class.

**Comment by oznetmaster** [comment]
Currently, I cannot adapt this at all for my  NETCF environment.

 

Are you writing a separate runner class for use in running one or more tests under nunitlite?  You have removed that capability in the autorun class.

**Comment by oznetmaster** [comment]
I just found TextRunner.  That should work for me.

**Comment by oznetmaster** [comment]
TextRunner appears to have lost a lot of options that TextUI used to have, and that AutoRun still has.

 

For instance, it does not initialize the log, and it does not set the outWriter and errWriter, or process the various other options.

 

Is this intentional, or is it just an oversight?

**Comment by oznetmaster** [comment]
I adapted AutoRun into ConsoleRunner, and now have full capability equivalent to what was available before.

 

After I test it, I will generate a PR for it so that there will be a full console capability.

**Comment by oznetmaster** [comment]
Since really the only current difference between AutoRun and ConsoleRunner is the support for specifying the test assemblies, perhaps it should be the same with just a flag?  No reason to support two basically identical runners.

**Comment by CharliePoole** [comment]
@oznetmaster Please keep comments related to the issue on which you make them. 

Your series of comments here seem to be related to work already done on other issues and to the general direction of the nunitlite runnner. Github gives us what amounts to a separate discussion group for each issue and it seems to help our communications when we take advantage of that for individual issues. For general discussion, we have either the committers maillist or the nunit-developer group, depending on who you want to include as recipients.

This particular issue was created to support exactly the type of execution you are asking for. We'll work on it for the second beta.

**Comment by CADbloke** [comment]
Could / should the `AutoRun` class include a constructor with a parameter that accepts an `ExtendedTextWriter ` derived class so`TextUI ` can use an alternative to `ColorConsoleWriter`? This would mean you could use the `AutoRun.Execute()` method in an environment where there is no System.Console or where it has been [comprehensively broken](http://forums.autodesk.com/t5/net/accoreconsole-exe-in-2015-doesn-t-do-system-console-writeline/m-p/5560267) and/or where there is a non-standard output console. You could call it as `AutoRun(MyWriter).Execute(MyArgs)`

In the case of AutoCAD (and its clones) it could write to its own command line using their `Editor.WriteMessage(string)` method.

Just a thought / suggestion rather than a request for complexification.

**Comment by CharliePoole** [comment]
@CADbloke That seems like something we could easily add. Would you want an ExtendedTextWriter or a TextWriter? If you won't be using color, then wrapping an ExtendedTextWriter around a TextWriter is simple enough - we already have that code.

**Comment by CADbloke** [comment]
The case I mentioned (`Editor.WriteMessage(string)`) it is definitely color-blind. The AutoCAD editor command lline is a kind of primitive console so I guess it would be a version of TextUI (but I guess that's an offline implementation detail) so an ExtendedTextWriter type of wrapper should work fine.

**Comment by CharliePoole** [comment]
NUnitLite is becoming solely a component for use by self-executing assemblies. For that reason, features __not__ related to AutoRun will be removed.

**Comment by oznetmaster** [comment]
I have a real problem with this.  Since the engine does not support CF, this will effectively eliminate any CF devices that have consoles from being able to have console control of their NUnit tests.

I have no problem with this taking place once there is a usable "engine" or equivalent for CF builds that will allow console control (and remote control as well), but to make this change before then seems very premature.

**Comment by CharliePoole** [comment]
@oznetmaster I sent an email to the developer list yesterday describing our general direction for NUnitLite. It would be most useful to continue the discussion there because it involves more than this single issue. If you didn't get a copy let me know and I'll resend to you.

Regarding this issue... It's been here for a long time and you haven't been able to contribute anything toward resolving it in a way that would be helpful to you. The 3.0 release is close and my feeling is that anything we release in 3.0 will need to be supported in the future. I don't want to release a feature that we intend to remove in the future.

What I'm saying is that **NUnitLite** isn't intended to support what you want to do. That's not to say we wouldn't support it in some other way.

You have already told me (in emails and posts) that you have your own CF console runner, your own engine and a kind of server that runs on CF in the background taking test results. Naturally, no change in NUnitLite would prevent you from continuing to use these packages of your own. Other people would not have access to them, of course, but up to now there are no other users asking us for the capability.

We can wait a week or so before acting on this issue. My suggestion is that you consider whether you want to contribute more than your objections to its resolution... that is, some code! If you wanted to create a CF only runner that has the features you need, it could very easily become a part of the CF solution. Up to now, it has seemed that those private packages you maintain are... well, private.

I hope you'll join the discussion on the developer list about the direction of NUnitLite as well as commenting here.

**Comment by oznetmaster** [comment]
I have offered the console based CF runner a number of times, and you expressed no interest in having it added to the CF build.  "no other users asking us for the capability".  So I did not do so.  It is a very minor divergence from the existing autorun, basically putting back some of the things that were taken out when autorun was created.

It is independent of anything I have done with the core/mini engines and asynchronous CF server (currently driven by web sockets).  These are both longer term efforts, and will also be affected by the direction taken with the core engine and the remote execution (different device) of tests.  I have been waiting for decisions on those issues, but they were put into a seeming post 3.0 time frame.

**Comment by oznetmaster** [comment]
For instance, I thought that there was a move to use the FrameworkController for all test execution, even in NUnitLite (at least before I left on vacation).  That seems to have been reconsidered.

I still think it would make sense to do that, and would unify things.  But it was obviously one of those decisions which could go either way.  It does, however, force me to decide whether to go that way anyway, or to do something else.  I was using the FrameworkController in my developmental builds.

**Comment by oznetmaster** [comment]
I never saw the use of the core/mini engine and supporting code in the CF build as part of 3.0.

I had hoped that the console interface would be.

All I am asking is not to remove anything that is needed to support at least the console interface.

I guess I need to know what you are proposing removing in 3.0 to have an intelligent discussion about this.

**Comment by CharliePoole** [comment]
Regarding use of FrameworkController: yes, we have dropped that idea
because it isn't actually needed for **NUnitLite** as we have been defining
it. See the email I mentionned.

**Comment by CharliePoole** [comment]
Re offering your code: It's entirely possible we misunderstood one another.
My understanding is that you wanted to add comparable changes from your
code into NUnitLite, which is a different thing entirely. If you want to
provide a full console runner for CF, you only have to file an issue and/or
PR.

See the separate email about the future of NUnitLite.

We can have an offline discussion about your role in the project as well,
if you like.

**Comment by CharliePoole** [comment]
Re engine for CF: I had hoped we would get it into 3.0 but in the latest
triage we postponed it. This is primarily because I want to move away from
the use of conditional compilation to create a core and/or mini engine. If
we can rely on extensions being present or absent the definition of a
core/mini engine becomes a simple matter of configuration.

It think all the experimentation we have done on various builds of the
engine has paid off but it's in the nature of such experiments that more
stuff is frequently discarded than is used. :-(

Re what I am proposing to remove: See the separate email about NUnitLite
and potentially let's have a Skype chat.

**Comment by oznetmaster** [comment]
Still cannot find this email you are referring to :(

**Comment by oznetmaster** [comment]
This will require that extensions work on CF.  Is that the assumption?  Addins never did.

**Comment by CharliePoole** [comment]
I'll forward it.

**Comment by oznetmaster** [comment]
You did not answer the question about extensions in the CF builds?

**Comment by CharliePoole** [comment]
If we create the engine on CF, then there are two possibilities with regard to extensions:

1. The engine on CF will not use extensions, so they won't be needed. This would limit us to the lowest level of functionality on CF, so it's probably not what we want.

2. Extensions will work and some will be included. You can take a look at the code for the extensions in the engine now - it would be useful in fact - and let us know if you see any obvious problems. I think there should not be since the much more complex facility of mono.addins works on CF.

NUnit Addins never worked on CF because NUnit never worked on CF. We only built the old NUnitLite for CF and it was designed to exclude addins from the beginning. That had nothing to do with being able to make it run but with wanting a much simpler test framework.
