### ISSUE TITLE
TestContext.CurrentContext properties are null

### ISSUE THREAD

**Issue by sjmarsh** [nunit/nunit#545]
We are trying to use a test `[TearDown]` attribute to log results from a test run.

We're having an issue where the properties on `TestContext.CurrentContext` are throwing `NullReferenceExceptions`.

We have created a simple test solution in which we have the following code:

```C#
    [TestFixture]
    public class Class1
    {
        [Test]
        public void ShouldExpectedBehaviour()
        {
            Assert.Pass();
        }

        [TearDown]
        public void TearItDown()
        {
            Assert.IsNotNull(TestContext.CurrentContext);
            Assert.IsNotNull(TestContext.CurrentContext.TestDirectory);
            Assert.IsNotNull(TestContext.CurrentContext.WorkDirectory);
        }
    }
```

We are getting a `NullReferenceException` coming from `TestContext.CurrentContext.TestDirectory`.

**Comment by sjmarsh** [comment]
This is happening in version 3.0.0-alpha-5

**Comment by CharliePoole** [comment]
@rprouse Please take a quick look. TestDirectory is an important property but we don't seem to be testing it at all. Like other props, it should be tested in SetUp and Teardown as well as in the test itself.
If the fix is quick and easy, we can put this in beta1, otherwise beta2.

**Comment by sjmarsh** [comment]
@CharliePoole do you have an estimate on how long this will take to get fixed?

**Comment by rprouse** [comment]
I will look at it this week. As long as I don't run into problems, it will
be fixed by Monday and in the upcoming beta. I will know more once I look
at the code though, so no promises.

**Comment by rprouse** [comment]
@sjmarsh, how are you running these tests? We have tests to check the properties of `TestContext` in a `TearDown`. I added the two properties that you say are null, but they work for me with the current codebase.

Here is a screenshot of a debug session of the tests with the latest code.

![2015-03-19 20_19_55-nunit debugging - microsoft visual studio](https://cloud.githubusercontent.com/assets/493828/6743860/2865257c-ce76-11e4-9f42-2491062e6f28.png)

I also tried with the code you added to the issue above and it passed.

Could it be that you are running with an NUnit 2.x runner or the Visual Studio adapter? None of these correctly support NUnit 3.

I am going to check in the new tests, but will close the issue if we can't reproduce. Is there anything else you can think of to help me reproduce?

**Comment by sjmarsh** [comment]
@rprouse Yeah we were using the ReSharper runner and also tried the Visual Studio adapter.  Both failed.  We just tried using the nunit-console and the tests pass.  Thanks for investigating.

**Comment by rprouse** [comment]
@sjmarsh, no problem, we are going to get a bunch of issues like this until we get the third party runners updated.

**Comment by CharliePoole** [comment]
We need to emphasize in our release notes that third party runners may try to run with 3.0, but that it won't work reliably.
