### ISSUE TITLE
Enable Parallel in NUnitLite/CF (or more) builds

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#546]
I am encountering many cases where I really want to be able to run multiple tests in parallel in the CF environment.

I realize that there is only one processor/one core, but if the tests involve substantial blocking operations, then the ability to run them in parallel is import for certain kinds of stress testing.

Was there a specific reason for disabling parallel in the CF build, aside from testing,coding issues?

How do you feel about putting it in.

I would self assign this if it is felt this is a good idea, or at least not a bad one.

**Comment by CharliePoole** [comment]
When we discussed this earlier, I had understood you to say it wasn't supported in CF 3.5 but that it could be in 3.9. That's the entire reason we didn't enable it in CF. It sounds like we misunderstood you.

If that's the case, we could certainly add it in a future release. Do you want to experiment with it first or should we just make this a feature?

**Comment by oznetmaster** [comment]
I misunderstood what you said back then :(  There is no difference between CF 3.5 and CF 3.9 in terms of supported capabilities.  The only difference here is that 3.9 supports multi-core processors.

 

I thought you indicated you did not want PARALLEL in the CF build.  We should just make it a feature, and I will undertake to make it work correctly.

**Comment by CharliePoole** [comment]
Done. I just put it in the general 3.0 milestone. Once you start working on it, you can decide what actual milestone to move it to.

**Comment by CharliePoole** [comment]
If we're lucky, you can just #define PARALLEL and it will work. More likely, some code that has never been built under CF before will need changing.

**Comment by oznetmaster** [comment]
Not that lucky :(

 

Biggest problem is the in CF, the Monitor class does not support Wait and Pulse.  Need to come up with an alternative.

**Comment by oznetmaster** [comment]
So I have this mostly done.  Passes the existing tests.

 

However, there seem to be no test specifically for parallelization?  Or am I missing something :(
