### ISSUE TITLE
Properties set on a parameterized method are not accessible to TestContext

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#548]
This post tells the story: https://groups.google.com/forum/#!topic/nunit-discuss/MEb7eESqeYI

As a solution, it seems we need to do one of two things:
1. Provide a way to access the parent context.
2. Reflect properties from the parent into the test context of the child.
#1 would be simplest but may be subject to misuse. The user could tunnel all the way up to the assembly level by looking at the prior context. I can imagine tests that do different things depending on who their parent is!
#2 is a bit complicated, since we have to allow for duplicate naming of properties at the higher and the lower level. We could implement it for test cases only, rather than copying all parent properties to all children.

A variant of #2 would be to allow the user to specify that a property is inheritable on a case by case method. At the moment, I like this idea best!

**Comment by MarkKharitonov** [comment]
Any plans to have it fixed? Not having it increases the crappiness level of the code.

**Comment by mikkelbu** [comment]
@MarkKharitonov I don't think that there are any immediate plans. All issues in NUnit are resolved by volunteers, and people tend to solve issues that matter to them or that interests them, and so far none tried to solve this issue.

I've tried to collect all the issues relating to parent textcontext in a project, https://github.com/nunit/nunit/projects/3, so that we have them in one place. Charlie and others have written a lot of useful information in these issues, so I think that the first step would be to go through them all and extract the essence.

**Comment by lars-erik** [comment]
FWIW, I just ran into this and solved it with some dirty reflection in my static value accessor. 🤷‍♂️

    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false)]
    public class TestEventAttribute : PropertyAttribute
    {
        public const string PropertyName = "EventId";

        public TestEventAttribute(string eventId)
            : base(PropertyName, eventId)
        {
        }

        public static Guid Get()
        {
            var test = TestContext.CurrentContext.Test;
            var props = test.Properties;
            if (props.Keys.Count == 0)
            {
                props = new TestContext.PropertyBagAdapter(
                    Type.GetType(test.ClassName)
                        .GetMethod(test.MethodName)
                        .GetCustomAttributes(true)
                        .OfType<TestEventAttribute>()
                        .Select(x => x.Properties)
                        .FirstOrDefault()
                    ?? new PropertyBag()
                );
            }
            if (props.ContainsKey(PropertyName))
            {
                var prop = props[PropertyName].First().ToString();
                return new Guid(prop);
            }
            return Guid.Empty;
        }
    }

**Comment by CharliePoole** [comment]
In a core team discussion, I undertook to review old framework issues authored by me and leave comments that might lead to some action or at least a decision about future action. This is the oldest and first one.

I created this issue because people were asking for it. It's not something I personally need.

I wrote outlined two possible approaches. @mikkelbu started to collect issues around the problems with properties in a GitHub project, but that project is currently empty. The team never picked an approach. It's labelled as an "enhancement" but only has the level of info I'd expect on an "idea". As a user, I wouldn't risk doing a PR on this because the approach was never selected. [By approach, I don't mean technical, but how will this look to users?]

I suggest deciding clearly one of  three things...

1. Not to do this at all. In this case, close the issue. Of course, it has come up a lot and will probably come up again.

2. Allow access to parent test contexts. This requires only a tiny bit of design: naming a property that does it.

3. Allow passing down properties from a higher level to a lower level. This requires more design. When a property is added, we have to know if it's inheritable so the user has to have some way of indicating that. If this can be done cleanly, I think it's the superior solution and it's the one I  would pick because some properties don't make sense when used by a lower-level test. However, this is the option that will take the most work.

As I do these old issues, it would be good to know if the effort seems useful to the team members, in addition to any specific comments. Hopefully, one of you will take ownership.

**Comment by mikkelbu** [comment]
Regarding the project being empty, then it also looked empty when I checked now, but I clicked in the menus, and now it contains: #3067, #1396, #1358, #796, #548 (but I think that there could be more issues). I think your comments are most useful, and hopefully I'll have time to look at this again soon.

**Comment by vpenades** [comment]
@CharliePoole I've also been hit by this issue.

I vote for option 2, that is: "Allow access to parent test contexts"

To me, this approach has two advantages:
- As you said, it's easy to implement.
- It gives access to the values of the properties at all stages, so the user can decide whether a property is "inherited" or not.
