### ISSUE TITLE
LevelOfParallelism

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#550]
NUnitTestAssemblyRunner has the code:

#if PARALLEL
            int levelOfParallelism = GetLevelOfParallelism();

            if (levelOfParallelism > 0)
            {
                Context.Dispatcher = new ParallelWorkItemDispatcher(levelOfParallelism);
                // Assembly does not have IApplyToContext attributes applied
                // when the test is built, so  we do it here.
                // TODO: Generalize this
                if (LoadedTest.Properties.ContainsKey(PropertyNames.ParallelScope))
                    Context.ParallelScope =
                        (ParallelScope)LoadedTest.Properties.Get(PropertyNames.ParallelScope) & ~ParallelScope.Self;
            }
            else
                Context.Dispatcher = new SimpleWorkItemDispatcher();
#endif

It would seem that the ParallelWorkItemDispatcher should only be used if the levelOfParallelism is > 1, not 0.  Otherwise, a lot of overhead is being added for no reason.

**Comment by CharliePoole** [comment]
The special value of 0 is designed to remove that overhead, should it be necessary. In my tests, there is hardly any difference in performance between using 0 and using 1, even though more code seems to be involved in the latter case. 

In the future, we may remove the ability to use 0 as an option and always run using the "parallel" code, with just a single queue on platforms that don't support parallel execution.

**Comment by oznetmaster** [comment]
I am seeing significant difference in performance on the CF platform.  So it may be import there.

 

Not sure what to do about it?

 

Why would you want to run the parallel code when there is only one worker thread specified?

**Comment by CharliePoole** [comment]
* In order to only have one codebase.
* In order to have a separate queue for the STA.

**Comment by oznetmaster** [comment]
Then maybe I should make this change only for the CF build (which does not have STA anyway, and so I have conditioned out all that code)

**Comment by oznetmaster** [comment]
I notice that even if the number of worker threads is set to 0, the EventQueueListener/EventQueue is used, spinning up another thread.

If the number of worker threads is set to 0 to inhibit parallelism, then should the eventqueue mechanism also be disabled?

**Comment by CharliePoole** [comment]
The EventQueue has nothing to do with parallelism. It's a mechanism for
isolating the runner from the test thread when remoting is used so that the
tests changing the CallContext don't pollute the context of the runner.

**Comment by oznetmaster** [comment]
Should it not be used at all in the CF build then?

 

It is currently only included is PARALLEL is set.

**Comment by CharliePoole** [comment]
That's odd. The two  things are separate but may be linked coincidentally because we only use remoting with builds that can be run by remoting. I wouldn't recommend changing this at the same time as you are making other changes.

**Comment by oznetmaster** [comment]
I have noticed another possibly strange behavior.  If WorkItem.IsParallelizable is false. the WorkItem correctly runs on the main thread.  However, any TearDown methods are run on one of the worker threads, with the main thread blocking until the TearDown is completed.

This is true on every build that I have tried.

Is the expected behavior?

**Comment by CharliePoole** [comment]
If you're referring to OneTimeTearDown, then it's expected. TearDown should  be run on the same thread as the test or test case. Can you provide a test that demonstrates the bad behavior?

**Comment by oznetmaster** [comment]
It also appears that putting the Parallelizable attribute on a Test method (SimpleWorkItem) does nothing?  It only seems to affect TextFixtures or CompoundWorkItem).

**Comment by CharliePoole** [comment]
Yes, see note 1 on page http://nunit.org/index.php?p=parallelizable&r=3.0

It turns out that there's a key practical difference between supporting parallel methods within a test class and across test classes. Most users can easily use parallel fixtures by default. Most can't use parallel methods without changing their code to avoid conflicts. There's also a bit of extra work involved on our part.

This issue is documented as #164 which we decided to postpone to a post-3.0 release.

**Comment by oznetmaster** [comment]
“The ParallelizableAttribute may be specified on multiple levels of the tests, with lower-level specifications overriding higher ones. “

 

The ParallelAttribute only applies at the level on which it appears and below. It cannot override settings on higher-level tests.

 

These two statements seem contradictory?

 

“In the current release, parallel execution of methods within a class is not yet implemented.”

Sorry.  I usually only look at notes when there is a reference to them in the actual body of the text.  That is the usual way that notes work.  I did not realize that notes in the NUnit documentation were never referenced in the text :(

**Comment by CharliePoole** [comment]
Yes, it does sound contradictory.  The explanation is that "overriding" means too different things in the two sentences, but I should edit it to say exactly what is meant.

**Comment by CharliePoole** [comment]
How does this look?

http://nunit.org/index.php?p=parallelizable&r=3.0

**Comment by oznetmaster** [comment]
Seems clearer.
