### ISSUE TITLE
TextRunner not passing the NumWorkers option to the ITestAssemblyRunner

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#551]
MakeRunSettings does not add the NumWorkers option value to the runSettingsDictionary.

So this option appears to be currently being ignored by NUnitlite.

**Comment by CharliePoole** [comment]
Hmmm... I thought I recently fixed something about this, but maybe I merely saw it and didn't document it.

**Comment by oznetmaster** [comment]
I have fixed this as part of enabling PARALLEL in the CF build.

**Comment by CharliePoole** [comment]
If you don't want to do a separate PR for this, make sure you reference all the issues you are resolving from the PR you do submit.
