### ISSUE TITLE
Update NuGet Packages to use new icon

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#554]
The MSI installers use the new icon from #217. For the beta, we should update the NuGet packages to be consistent.

**Comment by rprouse** [comment]
I mistakenly pushed the fix for this to master. I didn't see the error when I created the branch :frowning: 

d1b0ea81a6398d1a0fe09dec118a1858a8466649 will fix this issue once nunit/nunit.org#29 is merged and uploaded to nunit.org.

**Comment by CharliePoole** [comment]
The merge and upload are done.
