### ISSUE TITLE
Executed tests should always return a non-zero duration

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#556]
Runners like the vs adapter get confused when a test runs in zero time. In the case of VS, the test is listed as not run, even if it succeeded or failed. We deal with this in the adapter by replacing the duration with the equivalent of a single tick.

It would be  desirable if NUnit returned a non-zero duration in all such cases. This could be the equivalent of a tick, or the lowest representable value in seconds, or some special value that the runner can interpret.

**Comment by CharliePoole** [comment]
@rprouse I'm having second thoughts. Does this belong in NUnit or is it something to fix in each runner that actaully has the problem? Suppose we use one tick and then encounter a runner that gets confused if the duration is less than one ms?

**Comment by CharliePoole** [comment]
Let's hold on this till we can decide which way to go.

**Comment by rprouse** [comment]
I understand your concern and could go either way on this. Conceptually, I think that a test duration should never be zero and should be set to at least one Tick, but I don't have a strong opinion on this and nobody else has commented. 

We could also just decide that if < 1 ms then set to 1 ms. I doubt any test runner including our XML reports at less than a ms granularity, so it could be the best fix.

@CharliePoole, I think this is a fairly easy change, so make the call, close or fix at 1 Tick or 1 ms and we can go with it. I don't think it is worth spending too many cycles worrying about it :smile:

**Comment by CharliePoole** [comment]
I just looked at the XML and I'm surprised to see that it only reports down to 1 ms. We display six places after the decimal point because I thought I would get that much resolution out of the high-resolution timer, possibly down to 1 microsecond. Was I off-base in thinking that? Is it just that I don't have such a machine or is this only a future capability. If it's only for the future, then I don't think we need to allow for it right now.

It's clear we are getting better resolution than from DateTime, because I see results like `duration="0.002000"` which I believe is less than the DateTime.Ticks resolution.

If we are never going to get better than 1 ms resolution on the ticks, then I think we should go back to displaying only 3 decimal places in the XML. If we do that, then 1 ms would make a good choice here. If we stick with 6 places, then .000001 makes sense.

If you can come to a quick resolution on this broader question, please incorporate it with the same issue. If not, let's go back to 3 decimal places and a 1ms minimum and figure on a future change to deal with it. In fact, there is no reason to use a fixed number of decimal places, we could adjust that to the resolution of each machine or even each value if we liked.

**Comment by CharliePoole** [comment]
Exactly. And in fact, older windows machines used to give a resolution of something like 17 ms.

The real question is "Does anyone have a machine that gives a resolution better than 1ms?" If so, we should focus more on this. If not, I think we can be happy with 1ms, at least for the moment.

**Comment by oznetmaster** [comment]
All of my CF machines have a resolution of the high resolution timer that is much greater than 1msec.  I am assuming that pretty much every current computer does as well.

**Comment by CharliePoole** [comment]
You're right! My laptop has a resolution of around 427 nanoseconds, yet the duration recorded in the XML file is limited to 1ms. We're obviously messing this up somewhere.

@rprouse Do you want to work this as part of the current issue, or shall I create a separate one?

**Comment by CharliePoole** [comment]
OK, here it is: we're converting the ticks to seconds as a double and then using TimeSpan.FromSeconds(). The documentation on that method says "The value parameter is converted to milliseconds, which is converted to ticks, and that number of ticks is used to initialize the new TimeSpan. Therefore _value_ will only be considered accurate to the nearest millisecond." Who knew? Well, I didn't anyway. :-(

TimeSpan.FromTicks() uses a fixed definition of ticks: 100 nanoseconds. It has no relevance to StopWatch ticks. That's why we didn't use it.

It looks like we may want to simply store the duration as a double, the way we did for NUnit 2.x. It seemed "right" to use a TimeSpan, but it isn't getting us anything and we convert to seconds in the XML anyway.

**Comment by rprouse** [comment]
@CharliePoole, we may as well fix the TimeSpan resolution issue at the same time even though it is a bit bigger of an issue. It is in the same code.

My only question, is a duration with a resolution of less than 1 ms useful? I don't have a problem supporting it, but I wouldn't find the fact that a test took 400 nanoseconds or 500 nanoseconds to be a useful datapoint. Down to milliseconds is all I would expect. No strong feelings on it, just asking if other people find it useful or are we just providing the info because we can?

**Comment by oznetmaster** [comment]
I have no strong feelings one way or the other.  Although erring on the side of more information usually never hurts.

**Comment by CharliePoole** [comment]
Well, the XML format assumes resolution down to 1 microsecond only. :-)

For most individual tests, it wouldn't matter. A few use cases I can think of are:

1. Tests that are repeated a few thousand times with different data. We had such tests when I worked on a medical equipment application, for example.

2. Many tests currently showing as 0 ms would probably have some non-zero value if we fix this.

3. The VisualStudio Test Explorer displays durations of less than 1 ms as '<1 ms'

4. If we want to do any statistical analysis of test execution, it would be biased if we cut off the values at the low end.

5. With truncated values, the duration of a suite may appear to be quite different from the sum of the test durations. While this is explainable, it could be a bit surprising for the user.

**Comment by oznetmaster** [comment]
I am convinced.  Lets fix it.

**Comment by rprouse** [comment]
You've convinced me to.
