### ISSUE TITLE
NUnitLite Nuget package adds Program.cs to a project that I deleted it from

### ISSUE THREAD

**Issue by CADbloke** [nunit/nunit#566]
Greetings

Congratulations again on the Beta release. :)

ok, I typed all this but upon reflection it may be a much better (and easier) idea to tell the end-user that `Program.cs` should be left alone, regardless of whether you use it or not. I'll leave the issue here for your consideration but addressing it would probably add more complexity than it wouod fix problems. My usage is an edge-case and I've already figured out a fix (I can just ignore it).

*My original typing*...

To reproduce - using https://github.com/CADbloke/CADtest - I upgraded the Nuget packages from Alpha 5 to beta 1(a?). (See also https://github.com/nunit/nunit/issues/564)

I have previously deleted `Program.cs` from this project as it is not a Console Application, the call to NUnit is in [`CADtestRunner.cs`](https://github.com/CADbloke/CADtest/blob/master/CADtest-CS/CADtestRunner.cs) ... yes, it is still set for Alpha 5 - haven't officially upgraded it yet.

IMHO, if the package is installed as an upgrade then it should update an existing `Program.cs` (or any instance of the code that calls NUnitLite's execution) but it shouldn't add a new one. I looked at the Nuget package code and there isn't any PowerShell scripting but perhaps a magic code-fairy could write one that could look through *.cs and replace this  code with (you should test this Regex!)...

Find: `(new ?)?(NUnitLite)?(\.)?(Runner\.)?(?:TextUI\((?:.*?)\)\.Execute\()(nunitArgs)(?:\))`
Replace: `$1$2$3$4AutoRun().Execute($5)`

Note, this throws away any parameters in `TextUI(params)` because `Runner` doesn't have a same `ctor` with parameters

If you repro this with CADtest, please ignore my *why-do-it-the-easy-way* other problem of having two `Program.cs` in the project when I thought this was a bright idea...
````xml
<Compile Include="**\*.cs" Exclude="AssemblyInfo.cs;**\Temp*.cs" />
<Compile Include="Program.cs" />
````
The second line got added by Nuget. I'll fix it when I add a few more AutoCAD versions.

Just for kicks, here is the PowerShell code that RegexBuddy generated for that Regex
````PowerShell
$result = $subject -creplace '(?m)(new ?)?(NUnitLite)?(\.)?(Runner\.)?(?:TextUI\((?:.*?)\)\.Execute\()(nunitArgs)(?:\))', '$1$2$3$4AutoRun().Execute($5)'
````
I would volunteer myself to write a pull request for this but my PowerShell skillz are nearly as weak as my Nuget-Fu. I could cause a lot of damage with https://docs.nuget.org/create/creating-and-publishing-a-package#automatically-running-powershell-scripts-during-package-installation-and-removal

**Comment by CharliePoole** [comment]
I think that changing the user's code is more than we want to get involved with. As noted on #565 we'll most likely be dealing with this through documentation.

**Comment by CADbloke** [comment]
Yup, that's a fair call. :)
