### ISSUE TITLE
Isolate packaging from building

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#568]
Currently some of our packages - e.g. nuget - depend on the presence of a build directory bin\Release with the correct binaries. We should split this process into two stages:

 1. Build all the binaries and save them somewhere.
 2. Use the saved cache of binaries to create packages.

This will allow us to fix issues that are purely related to packaging without changing the assemblies that are included and messing up any references.

In addition, it will be a preliminary step toward implementing issue #11

Some packages already work this way, creating an install image from the binaries and then building packages out of that. We could make all packages use the install image as a first step. Subsequently, we can separate the two stages into different commands. As a final test, we should be able to move the binaries to another directory or even a different machine and create the packages.

**Comment by CharliePoole** [comment]
@rprouse I notice that one side effect of using the WiX support in VS is that we build the msi directly out of the locations where they are created. However, that doesn't seem to be intrinsic to the use of VS. 

Am I right in thinking that? Suppose we want it to root it's source directory in one location but create its output somewhere else. How might we change it to do that? In the NUnit 2.x scripts, we simply pass the output location into the programs as they are run.

**Comment by rprouse** [comment]
@CharliePoole, the output directory is just another variable. We could pass it in, or base it off of solution root. Do you think we should create the installs from and into the package directory?

**Comment by CharliePoole** [comment]
@rprouse I'm thinking of setting up a target that copies the binaries - pretty much what _CreatePackageImage now does, but it might need a few extra files. It would go to a deployment diretory that could be set as a variable. We would zip that up and save it.

The package targets would all operate out of that deployment directory exclusively.

We would add a RePackage target that recreates that directory and goes on to do the packaging.

That's the general outline of how I'm thinking. I'll work out the details as I go. I was a little unsure of how this would impact msi creation, but you cleared that up.
