### ISSUE TITLE
Throws.ArgumentNullException would be nice.

### ISSUE THREAD

**Issue by GeirGrusom** [nunit/nunit#576]
I can now write `Assert.That(Foo, Throws.ArgumentException)` but it would be nice with the more specific `ArgumentNullException` as well.

Perhaps all the exceptions listed [under common exceptions](https://msdn.microsoft.com/en-us/library/system.exception%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) should be in `Throws` as well?

However it is only ArgumentNullException that has bugged me because it is so common.

**Comment by CharliePoole** [comment]
I don't think that entire list is needed, but ArgumentNullException is a good candidate. We should bear in mind that we want to support those exceptions that are most commonly tested for, not just common.
