### ISSUE TITLE
No documentation for recommended usage of TestCaseSourceAttribute

### ISSUE THREAD

**Issue by DanielRose** [nunit/nunit#579]
According to the [documentation](http://www.nunit.org/index.php?p=testCaseSource&r=2.6.4), the recommended usage of TestCaseSource is the constructor which only takes a type:

    TestCaseSourceAttribute(Type sourceType);

However, there is no sample on correct usage in the documentation. Only by looking at the source code of NUnit itself was I able to figure out how to use this:

https://github.com/nunit/nunit/blob/master/src/NUnitFramework/tests/Attributes/TestCaseSourceTests.cs

**Comment by CharliePoole** [comment]
Please review: https://github.com/nunit/nunit/wiki/TestCaseSource-Attribute

**Comment by DanielRose** [comment]
I would write the same cases as in the other syntax. Since I can't edit the wiki:

    [TestCaseSource(typeof(DivideCases))]
    public void DivideTest(int n, int d, int q)
    {
        Assert.AreEqual( q, n / d );
    }

    class DivideCases : IEnumerable
    {
        public IEnumerator GetEnumerator()
        {
            yield return new object[] { 12, 3, 4 };
            yield return new object[] { 12, 2, 6 };
            yield return new object[] { 12, 4, 3 };
        }
    }

**Comment by CharliePoole** [comment]
Good idea - updated.

**Comment by DanielRose** [comment]
Looks good!
