### ISSUE TITLE
TeamCity Service Message Uses Incorrect Test Name with NUnit2Driver

### ISSUE THREAD

**Issue by chris-smith-zocdoc** [nunit/nunit#580]
When the NUnit2Driver is used, the TC service message can contains a test name that double escaped for the `OnTestFinished` events. The `testStarted`event is escaped properly. This causes TC to not recognize the events as belonging to the same test which prevents it from being displayed in the interface. 

Example `--teamcity` output
```
##teamcity[testStarted name='MyTest("foo")' captureStandardOutput='true']
##teamcity[testFinished name='MyTest(&quot;foo&quot;)' duration='0.001']
```

The issue appears to stem from XmlExtensions where it escapes the test name, see https://github.com/nunit/nunit/blob/master/src/NUnitEngine/Addins/nunit.v2.driver/XmlExtensions.cs#L99-L100

This is not issue when using the NUnit3Driver because the xml generation code path is different, see https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/Tests/Test.cs#L319-L320

Removing the call to Escape seems to fix the issue and doesn't appear to break the TestResult.xml file for either the nunit2 or nunit3 format.

**Comment by CharliePoole** [comment]
A test name can contain invalid characters for XML. The quote is not so great a problem but names with < in them can really mess us up. So the XML definitely needs to be escaped.

OTOH, the value needs to be unescaped when used. Any solution to this has to leave the XML output valid while not showing the escaped values on output.

**Comment by CharliePoole** [comment]
Actually, I think the NUnit 3 code path is probably wrong. We just may not have a test for the case where the name contains an invalid character.
