### ISSUE TITLE
TeamCity Service Messages 

### ISSUE THREAD

**Issue by chris-smith-zocdoc** [nunit/nunit#583]
The `--teamcity` option does not support parallel test execution right now. The TC service messages are dependent on the messages which preceded it, but they could have come from another process/thread so TC incorrectly interprets the result. 

We can solve this by setting the [flowId](https://confluence.jetbrains.com/display/TCD8/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-MessageFlowId) in the service message and removing the `testSuiteStarted` and `testSuiteFinished` messages. The name attribute can be adjusted to include the namespace and classname so it will be [interpreted correctly](https://confluence.jetbrains.com/display/TCD8/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-Interpretingtestnames) as belonging to a particular suite/class.

The flowId can be set to the `testId` once testIds are unique https://github.com/nunit/nunit/issues/582

**Comment by CharliePoole** [comment]
The fix to issue #582 is ready to merge. Feel free to review PR #588
