### ISSUE TITLE
Length of generated test names should be limited

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#59]
Since NUnit uses the value of a string argument to a test as part of the name, it's possible for the names to be arbitrarily long. This causes problems, particularly in the Gui, where GDI+ exceptions may be thrown and in the VS adapter, which may either reject the name or truncate it arbitrarily.

Names generated in the framework should be limited to a reasonable length <= 449 characters, the length that is enforced by the adapter. However, we don't want to simply truncate the name after generating it. Ideally, each individual parameter should be truncated in a way that limits the overall length of the name while preserving the general outline of FixtureName(args).TestName(args). 

Since any  truncation may cause duplicate names, which NUnit itself does not mind but which can break some clients like TestExplorer, name generation should include adding a unique value like the test id where needed. Note that it would be possible to use the test id alone for a unique name, but that this would not result in a good user experience in runners (TestExplorer again) that use the test name as a display name.

We may want to provide the raw materials for separating the display name from the "real" unique test name for those runners that want to take advantage of it.

**Comment by CharliePoole** [comment]
Started work on spec at https://github.com/nunit/dev/wiki/Generation-of-Test-Names

**Comment by CharliePoole** [comment]
Spec is now complete. Please review.

**Comment by CharliePoole** [comment]
PR #469 is at least a partial fix to this problem. I'm postponing further action - if any is needed - until the beta.

**Comment by CharliePoole** [comment]
@nunit/core-team Please review the updated spec at https://github.com/nunit/dev/wiki/Generation-of-Test-Names at a high priority.

If we can agree on the approach there, we can quickly close several outstanding issues. If you have read all the boilerplate before, you'll find the new proposal near the end of the page.

**Comment by CharliePoole** [comment]
@nunit/core-team It has been a week and nobody has commented on the proposal for how to resolve this issue. Kindly let me know what you think so we can start implementing it.

**Comment by oznetmaster** [comment]
The proposal seems quite reasonable to me.

**Comment by CharliePoole** [comment]
Moving ahead on this as a feature, following the spec at least initially.

**Comment by CharliePoole** [comment]
The spec at https://github.com/nunit/dev/wiki/Generation-of-Test-Names has been updated to reflect the current status and to remove all discussion about NUnit 2.x problems. It will become a technical note in the documentation when this issue is complete. @nunit/core-team and @nunit/contributors please let me know if you think I've missed something.

**Comment by rprouse** [comment]
Fixed by #912
