### ISSUE TITLE
Unable to select a single Test Fixture from multiple TestFixture attributes for a class

### ISSUE THREAD

**Issue by bpendharkar** [nunit/nunit#594]
I have a class with multiple Test Fixture attributes and I intend to select only one fixture for execution of tests. I do not see any approach to do so with whatever research I have done. It would be great if nunit could support this feature.

e.g.
 [TestFixture(SZRepositoryType.Restricted, UserType.Admin)]
[TestFixture(SZRepositoryType.Regular, UserType.Admin)]
 public class StorageZoneFileFolderOperations {
...
}

Parameters passed to  NUnit.ConsoleRunner.Runner.Main:
"/run:MyNameSpace.StorageZoneFileFolderOperations(SZRepositoryType.Regular,MyNameSpace.UserType.Admin)"   

Result : 
Selected test(s): MyNameSpace.StorageZoneFileFolderOperations(SZRepositoryType.Regular,MyNameSpace.UserType.Admin)

Tests run: 0, Errors: 0, Failures: 0, Inconclusive: 0, Time: 0.0191448436306132
seconds
  Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0
The test did not get executed in this case.

If I just provide a parameter as /run:MyNameSpace.StorageZoneFileFolderOperations , things work fine but all the 2 test fixtures above get executed. I intend to execute only [TestFixture(SZRepositoryType.Regular, UserType.Admin)]

**Comment by CharliePoole** [comment]
In the current beta, in order to select the test you must know it's full name. This is a bit hard to know without a gui, but you can type nunit-console test-dll --explore to see a list of the tests.

Assuming both arguments are enums, I would guess that NUnit is calling the test you want to run
StorageZoneFileFolderOperations(Regular,Admin) but you should verify this.

**Comment by bpendharkar** [comment]
Thanks @CharliePoole 
You are right .. Using (Regular, Admin) works which I had not tried earlier.
I kept on trying with SZRepositoryType.Regular, UserType.Admin which did not work well.
