### ISSUE TITLE
Copyright notices

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#598]
Many file changes include (or are exclusively) changes to the copyright notice.  The current US copyright law no longer requires a year on the copyright notice (and has not for some time).  It would be a lot easier to just make them all say "Copyright (c) Charlie Poole", and never have to touch them again.

**Comment by CharliePoole** [comment]
Six or seven years ago, we did update the year on every file each time we released but we don't do that any longer. The intent of the year in a file copyright notice is to indicate the last time any serious change was made to that file. In the past, we had one year, but more recently I have used a range from the year of creation to the last significant change.

We should really not be updating the year by itself in any case.

I would not want us to make a pass through all the files just to change the header. But if we want to establish a new standard for when changes are made and how, I think this would be a good place to discuss it.

Generally, not being a lawyer, I follow the advice of Karl Fogel's book for most things and of Leonard Rosen's on legal stuff. Both give a form that includes a date, but without explaining exactly what the date should mean. I know that the notice itself is not actually required, so clearly the year isn't either, but it seems to be what most people do. The usual form of the MIT license inclueds a copyright line at the top of the text, and that's what we are using.

**Comment by oznetmaster** [comment]
Actually, very few do the year any more.  For instance, Microsoft has not since the law was changed.

 

The public domain CoreFx sources all start:

 

// Copyright (c) Microsoft. All rights reserved.

// Licensed under the MIT license. See LICENSE file in the project root for full license information.

 

 

No year.

**Comment by CharliePoole** [comment]
A few data points... 

Both the FSF and the Apache Foundation call for using the year in each file when applying their respective licenses.

MonoDevelop uses years in each file.

Here is an answer on SO that recommends towards accumulating years in each file as copyrightable changes are made:

http://stackoverflow.com/questions/3487007/when-to-update-the-year-in-open-source-copyright-notice

**Comment by CharliePoole** [comment]
Hey everyone! It would be great to get some responses here so we can put this idea into practice or close it out. We seem to accumulate these kinds of issues.

**Comment by rprouse** [comment]
Sorry, my opinion is leave it as is. I would rather concentrate on getting the next beta out than worry about formatting and cosmetics :smile:

**Comment by CharliePoole** [comment]
OK, I'm closing this as won't fix. I also updated the coding standard page to specify how the year is to be used.
