### ISSUE TITLE
NUnit does not clean up the ShadowCopyCache

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#608]
When NUnit shadow copies files, it does so to the `%LocalAppData%\NUnit\ShadowCopyCache` directory, but it does not clean up after itself. On a lightly used machine, that directory is currently over 500 MB.

We should either clean up the cache directory at the end of the run, or we should move the cache directly to the user's temp directory so it gets cleaned up by other tools.

This is lower priority now that shadow copy is not the default, but it will become an issue again if we release a GUI.

**Comment by CharliePoole** [comment]
As of release 3.4, we no longer use a private cache directory, so this issue is no longer relevant.
