### ISSUE TITLE
Add integration/regression tests to ensure compatibility with TeamCity

### ISSUE THREAD

**Issue by NikolayPianikov** [nunit/nunit#610]
Tests to ensure nunit sends suitable service messages for general usage scenarios.

**Comment by CharliePoole** [comment]
This issue has been a kind of orphan up to now. Since it had no labels, milestone or assignee, it didn't show up on any of my queries! It's a bit late to get it into the second beta release, so we'll hold it for the next one.

**Comment by NikolayPianikov** [comment]
OK, thanx

**Comment by CharliePoole** [comment]
See my proposal for dealing with this issue on the PR.

**Comment by CharliePoole** [comment]
Issue moved to [nunit/teamcity-event-listener #3](https://github.com/nunit/teamcity-event-listener/issues/3) via [**ZenHub**](https://www.zenhub.com/)
