### ISSUE TITLE
Remove unused --teamcity option from CF build of NUnitLite

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#611]
It's legal to type in --teamcity to the command line and no error appears. However, nothing happens.

While doing this, we should check for other options that are actually unused and disallow them.

**Comment by voloda** [comment]
@CharliePoole I can take care of this one as well. I went thru code and haven't found any other options. Though - any suggestion where to look on top of the obvious?

**Comment by oznetmaster** [comment]
In my CF build, the --teamcity option is inside the #if !NUNITLITE conditional in ConsoleOptions.  Not sure how it got moved outside of it?  Is it allowed in the PORTABLE or SILVERLIGHT NUnitLite builds?

**Comment by oznetmaster** [comment]
Ok, I guess it should be outside the #if !NUNITLITE, and in its own #if !NETCF?  Because it does appear to be used in the PORTABLE and SILVERLIGHT builds?

**Comment by voloda** [comment]
@oznetmaster That is exactly what I did in PR #619

**Comment by CharliePoole** [comment]
Great Volodya! In reviewing options, you need to check if the option is ever actually used. In the case of --teamcity you would see the value being tested and acted on. For others, it would be "acted on" by changing a setting that is passed to the framework. If it sets a flag and that flag is never used, then it should not be a valid entry because it confuses people.
