### ISSUE TITLE
MaxTime doesn't work when used for TestCase

### ISSUE THREAD

**Issue by claudia-alexa-pop** [nunit/nunit#612]
If using [MaxTime] and [TestCase] for a test exceeding the MaxTime, the test will pass, when it should fail.

![nunitbug_maxtime_testcase](https://cloud.githubusercontent.com/assets/12083837/7296659/4502367e-e9ca-11e4-8e62-78523ef42417.png)
![nunitbug_maxtime_testcase_2](https://cloud.githubusercontent.com/assets/12083837/7296676/5f9ddd12-e9ca-11e4-8979-a2d2f3fa98d5.png)

**Comment by CharliePoole** [comment]
The MaxTime attribute doesn't work on a testcase. Unfortunately, it is simply ignored rather than giving an error when used in this way. I have confirmed that the same error happens in the NUnit 3.0 codebase. We'll fix it for the 3.0 release.

**Comment by CharliePoole** [comment]
Ah... turns out it _does_ work in the 3.0 code. I added a test to confirm.
