### ISSUE TITLE
ExpectedResult evaluating to null, not specified value

### ISSUE THREAD

**Issue by msneeden** [nunit/nunit#637]
Possible issue moving to 3.0. Didn't find a reference to this in the upgrade docs, apologies if I missed it.

Following the upgrade from 2.6.4 to 3.0 'TestCase' tests that make use of 'ExpectedResult' are now failing. It appears that Expected always equals null regardless of the specified value.

Simple repro. case - works in 2.6.4, fails in 3.0
```
[TestCase("foo", ExpectedResult = false)]
		public bool Fail(String incoming)
		{
			return incoming.Contains("bar");
		}
```

Results in (3.0):
```
Result Message:	
Expected: null
  But was:  False
```

**Comment by CharliePoole** [comment]
This is intended to work. I'm initially marking it for beta 2, which we are now working to release, because I'm guessing it's trivial. Otherwise, we'll move it to beta 3.

**Comment by msneeden** [comment]
:+1:

**Comment by CharliePoole** [comment]
Even though this test case is similar to others we already have, I added it to the nunit.framework test suite. It passes.

How are you running your tests?

**Comment by constructor-igor** [comment]
Next test fails (via Resharper v8) in nunit v3

```c#
	[TestFixture]
	public class NUnitIssue637
	{
		[TestCase("foo", ExpectedResult = false)]
		public bool Fail(String incoming)
		{
			return incoming.Contains("bar");
		}
	}
```
![image](https://cloud.githubusercontent.com/assets/1849690/7561973/141be6fa-f7d9-11e4-95a9-54a95591682d.png)

**Comment by constructor-igor** [comment]
I checked in current v3 with help of next test:
```c#
[TestCase(5, 2, ExpectedResult = true)]
public bool XEqualToY(int x, int y)
{
    return x == y;
}
```
![image](https://cloud.githubusercontent.com/assets/1849690/7562095/42fbccfa-f7da-11e4-98f3-ded2e4566e6f.png)

**Comment by rprouse** [comment]
Resharper and other 3rd party runners don't support NUnit 3 yet. Tests
appear to run, but you get odd failures like this.

For day to day testing with NUnit 3, the console runner or the new nunit 3
Visual Studio test adapter works.

**Comment by msneeden** [comment]
@CharliePoole I hadn't updated the NUnit test adapter in VS2013 to v3 when reporting the issue. After updating to v3, the scenario passes. Sorry for the confusion!

**Comment by rprouse** [comment]
@msneeden, thanks for confirming. I am closing this as invalid.
