### ISSUE TITLE
Keep CF Build (and other future builds) in Sync

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#640]
As shown in PR #639, we have trouble keeping the CF build in sync with other changes we make. Often a change to the framework, which is tested for the desktop, will end up breaking the build for CF. We fix the individual problems but a solution is needed that makes this less likely to happen.

CF is not used by many people so we may be tempted to play this down. However, it's important for a few reasons:

1. Checking into master is essentially a form of code release. Stuff should just work.
2. This is a "broken window" potentially leading to further problems down the line.
3. We spend a lot of time fixing the problems after the fact.
4. As NUnit grows, we will have other platforms that are outside the "standard" desktop platforms. We will receive contributions that are not tested for those platforms. We need to have an approach that makes sure anything we merge works on all platforms to which it applies.
5. As we add more platforms, we will no longer be able to package everything on one machine. We need to address ways to complete packaging for a platform that includes a platform like CF on a machine that does not support CF.
6. Up to now, our approach has been to say that all developers - at least those that do releases - should install every platforms we support. This is currently not a practical expectation and may become impossible in the future, at least using a single machine.

So I think we have to solve this because it's a problem in itself and also becuase it represents a class of problem we can expect to see more of.

I'm assigning this to myself as a facilitator, but it's really a job for all of us to address. Let's start by posting ideas here.

**Comment by CharliePoole** [comment]
Copying suggestions @rprouse posted to #639 ...

I thought that a newer version of CF (3.9?) was supposed to compile in newer versions of Visual Studio and that we were going to move to it. Is that not the case? I haven't heard anything out of Microsoft for ages, so I'm a bit in the dark.

I think we decided that CF would be packaged separate, so we could also decide to release it on its own cadence. If we did that, we could create a CF branch off master and periodically cross merge changes. We could even treat them as separate projects with Niel leading CF if that makes sense.

**Comment by CharliePoole** [comment]
IDEA: Add CF 3.9 to primary solution

This will help in some ways. It will be technically easier for more folks to build for CF 3.9 since they won't have to install VS2008. However, there are whole categories of errors that arise in CF 3.5 that won't be caught this way...

* Anything having to do with a change to the .csproj file
* Anything related to the version of C# used
* Any classes or methods present in 3.9 but missing in 3.5.

Additionally, anyone who wants to build 3.9 will need to install additional components in VS.

I still think this would help, even if it's not a complete solution.

**Comment by CharliePoole** [comment]
IDEA: Downloadable CF build

One issue with CF is that a developer must install VS2008 and use the emulator to run tests. This is asking a lot for folks who don't have any other reason to use CF.

In the past our builds didn't depend on VS at all. We used the CF runtime and SDK and built from the command-line. We ran the tests from the command-line as well. This worked because CF 3.5 is pretty much a subset of desktop .NET.

Perhaps we could provide a download that included the necessary microsoft components and a script to build and run tests.

**Comment by CharliePoole** [comment]
IDEA: Use static analysis

Rob has talked about creating modules that analyze our code for correctness and conformity to standards. It seems reasonable to create rules about the features to be used in framework code.

As a start, we could simply write down the rules in a standard for everyone to follow.

Of course, the general rule is that you have to only use C# 3.0 features in code that will be built for the compact framework. However, I think most developers tend to forget which features came in with which versions, so a list would be useful.

**Comment by CharliePoole** [comment]
IDEA: CF CI Build

If we could create a downloadable build, we could then download it on Appveyor and run CF tests there.

**Comment by rprouse** [comment]
You mentioned the other platforms like Android and iOS. Those and others
are using the portable framework right now, so if we can keep it that way,
it will reduce our issues to
CF and Silverlight.

Can you use portable libraries with CF 3.9?

**Comment by CharliePoole** [comment]
@rprouse I think that use of a portable library reduces problems but doesn't eliminate them. Essentially, it means that everyone can compile the code and we can test it on the platforms we have. We assume that working on one platform means it will work on all of them. I'm think that's probably right 90% of the time.

Anyway, how do we test the Android and iOS runners, which aren't portable? I don't think we can get away from the fundamental issue that NUnit is developing to a point where you can't test it on a single machine and possibly where no single person can do the testing and release. It would be an interesting challenge to design an approach that allows us to test and release in spite of this.

I don't know if you can use portable libraries with CF 3.9. @oznetmaster ?

**Comment by oznetmaster** [comment]
Also, when we last looked at this, we could not find a device package for CF 3.9 that we could test against.  Device emulators for 3.9 are not automatically installed with VS any more.

**Comment by CharliePoole** [comment]
The CI build now incorporates CF on Appveyor. It does the compile and when #1317 is done will run the tests under unification. I think that this issue will be resolved at the same time.
