### ISSUE TITLE
ConfigurationManager.AppSettings Params Return Null under Beta 1

### ISSUE THREAD

**Issue by levisiebens** [nunit/nunit#646]
I've been using the nunit-console Alpha 3 for some time and deiced to upgrade to the Beta 1. However when I did I've found that my App.config for my tests is no longer being read and any calls to ConfigurationManager.AppSettings return an empty string / null. Is there something that changed which would cause this. I did check the TestContext working directory and output directory, both of which show the correct location (under both Alpha 3 and Beta 1).

I've tried the following configurations below:

Empty String Returned:
nunit.framework (Alpha 3 and Beta 1) with nunit-console (Beta 1)

Proper Value Returned:
nunit.framework (Alpha 3 and Beta 1) with nunit-console (Alpha 3)

Example Code:

public class ScratchTest
    {

        [Test]
        public void MyTest()
        {
            TestContext.Out.WriteLine(ConfigurationManager.AppSettings.Get("Endpoint"));
        }
     }

**Comment by CharliePoole** [comment]
Please indicate how you are running the tests - it makes quite a big difference in the case of configuraiton settings.

**Comment by CharliePoole** [comment]
Oh, sorry... I see you did indicate that it happens when running tests using nunit-console.

**Comment by levisiebens** [comment]
Yes, I'm using nunit-console and the only parameter I'm passing in is a --test to specify the name of the namespace/method to test.

**Comment by CharliePoole** [comment]
I have confirmed this and I am going to try to get it into the beta 2 release, which is coming out today or tomorrow.
