### ISSUE TITLE
Passing 2 or more test assemblies targeting > .NET 2.0 fails

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#648]
**Steps to reproduce:**

1. Compile the NUnit solution
2. Open a cmd window to the bin directory
3. Attempt to test the framework with the following command:

    `nunit-console.exe net-4.5\nunit.framework.tests.dll net-4.5\slow-nunit-tests.dll`

**Expected result:**

Tests run under .NET 4.5

**Actual result:**

```
1) Invalid : D:\src\nunit\nunit\bin\Release\net-4.5\nunit.framework.tests.dll
Could not load file or assembly 'file:///D:\src\nunit\nunit\bin\Release\net-4.5\nunit.framework.tests.dll' or one of its dependencies. This assembly is built by a runtime newer than the currently loaded runtime and cannot be loaded.

2) Invalid : D:\src\nunit\nunit\bin\Release\net-4.5\slow-nunit-tests.dll
Could not load file or assembly 'file:///D:\src\nunit\nunit\bin\Release\net-4.5\slow-nunit-tests.dll' or one of its dependencies. This assembly is built by a runtime newer than the currently loaded runtime and cannot be loaded.
```

**Note:**

Using the same command line with just one assembly works.

**Comment by CharliePoole** [comment]
Makes me realize we never run more than one test at a time in CI. We need an integration suite that does this, but also some sort of unit tests.

I narrowed this down using --process options. Single and Separate work fine. Multiple (the default) fails. I would suspect MultipleProcessTestRunner.
