### ISSUE TITLE
Change TeamCity environment variable "TEAMCITY_PROJECT_NAME" by "TEAMCITY_VERSION"

### ISSUE THREAD

**Issue by NikolayPianikov** [nunit/nunit#655]
We decided that "TEAMCITY_VERSION" is more preferable than "TEAMCITY_PROJECT_NAME". Could I create pull request to make this minor change?

**Comment by rprouse** [comment]
Sure, why the change? 

BTW, would you mind documenting the Team City changes and how to use them?

**Comment by NikolayPianikov** [comment]
Sorry for the delay in response. This question is not relevant at the moment.
