### ISSUE TITLE
Unused parameter in Console.WriteLine found

### ISSUE THREAD

**Issue by constructor-igor** [nunit/nunit#656]
CA2241	Provide correct arguments to formatting methods	Method 'NUnitTestAgent.Main(string[])' calls 'Console.WriteLine(string, object)' and does not provide a format item for argument "1". The provided format string is: '"Exception in RemoteTestAgent"'	nunit-agent	Program.cs	150

https://github.com/nunit/nunit/blob/master/src/NUnitEngine/nunit-agent/Program.cs#L150

![image](https://cloud.githubusercontent.com/assets/1849690/7631282/7eae397a-fa48-11e4-8453-509dc59f640c.png)

**Comment by constructor-igor** [comment]
If I am not mistaken, relevant request was committed.
If yes, the issue can be closed.

**Comment by rprouse** [comment]
You are right, thanks, closing.

**Comment by constructor-igor** [comment]
please, could you suggest other nunit issue for testing or development.

**Comment by rprouse** [comment]
@constructor-igor, take a look at the following,

- #585 - RetryAttribute, I don't think @agray is going to get to it, so feel free to claim it.
- #558 - Installer issue, feel free to take it from me
- #380 - Add build for CF 3.9 to the main solution if you are interested. This would help us keep the CF code up to date.
- #294 - If you have XSL and HTML experience, a first pass at this would be useful
- #23 - Use overridden Equals for IEnumerables, Collections, etc.

If you have a Xamarin license, I could also use some help in the nunit/runners repository.
