### ISSUE TITLE
Parallel Test Execution Within Test Assemblies

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#66]
NUnit 3.0 already includes provision for running tests in parallel but we have no way to control which tests may be run in this way. This feature involves implementing the spec defined at https://github.com/nunit/docs/wiki/Framework-Parallel-Test-Execution

**Comment by agray** [comment]
I would have thought this was relatively easy to implement given the capability exists in the old MbUnit.

Parallel execution of Test cases is an excellent feature of MbUnit and JUnit.  It is a major gaping hole in my opinion that it is not also part of NUnit.

**Comment by CharliePoole** [comment]
Same comment on #164. Consider the same answer given.
