### ISSUE TITLE
How to get /Exclude: working

### ISSUE THREAD

**Issue by klassesen** [nunit/nunit#662]
Unit Tests of my Addin work fine except for /Exclude (and by inference /Include)

[Test][Catgeory("Content")]
* does not execute with /Exclude:Content -- as expected.

[Test][Retry][Category("Content")]
* does execute with /Exclude:Content -- NOT expected.

[Retry] is the addin that I added. I suspect that I need to modify this code

        public NUnit.Core.Test Decorate(NUnit.Core.Test test, MemberInfo member)
        {
            var ignore = GetIgnoreAttribute(member);
            var retryAttr = GetRetryAttribute(member, test);
            if (retryAttr == null | ignore != null) return test;

            NUnitTestMethod nunitTestMethod = test as NUnitTestMethod;
            return nunitTestMethod==null? test : new ExecuteRetryMethod(nunitTestMethod.Method);
        }
Suggestions?

**Comment by klassesen** [comment]
Solved - as usual, asking for help clears the mind and solution appears.. just had to transfer the catgory to the new test.

        public NUnit.Core.Test Decorate(NUnit.Core.Test test, MemberInfo member)
        {
            var ignore = GetIgnoreAttribute(member);
            var retryAttr = GetRetryAttribute(member, test);
            if (retryAttr == null | ignore != null) return test;

            NUnitTestMethod nunitTestMethod = test as NUnitTestMethod;
        
            if( nunitTestMethod==null) return test;
            var newTest= new ExecuteRetryMethod(nunitTestMethod.Method);
            newTest.Categories = test.Categories;
            return newTest;
        }

**Comment by CharliePoole** [comment]
Glad we could help. :-)

Are you aware that NUnit 3.0 eliminates addins in the 2.x style?
