### ISSUE TITLE
Engine does not release test assemblies

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#674]
Because it uses ReflectionOnlyLoad in the primary AppDomain, the engine fails to release test assemblies after examining them. This doesn't have much effect on the console runner but causes problesm with the VS test adapter.

Eventually, we plan to use mono.cecil rather than ReflectionOnlyLoad. In the meantime, we should ensure that a separate AppDomain is used for ReflectionOnlyLoad.

**Comment by OsirisTerje** [comment]
Does this mean we can remove the fix that was done in the adapter, where we load the whole engine in a seperate appdomain ?

**Comment by CharliePoole** [comment]
That's the intent, but it isn't actually tested in the adapter yet.

**Comment by OsirisTerje** [comment]
The question then is:  That fix has not been released, so should we release that fix, or should we remove it and release with this fix ?

**Comment by CharliePoole** [comment]
I thought we only put in the first fix in order to release a working adapter using nunit beta-2, which was to be ctp-3.  Otherwise, there would be no reason to fix an engine problem by a workaround in the adapter.

The engine fix is for beta-3. We originally thought we would be using mono.cecil for that release but I was thinking it may not get done and so did this one.

Do we currently have any working release of the 3.0 adapter?

**Comment by OsirisTerje** [comment]
The fix is not released, we discussed giving it a week or so, to pick up more, but with this fix we should reverse it, but then we need to test that it works for the adapter before we release.   I agree the fix belongs in the engine, but the adapter fix kind of isolates the adapter from the engine.  I'll try to make a new build of the engine, and reverse the changes in the adapter to see if it still works.

**Comment by rprouse** [comment]
Terje,

Are you sure that it is not released? I am running CTP3 on this machine and
am pretty sure I got it from the Gallery. There is also a release on
GitHub, https://github.com/nunit/nunit3-vs-adapter/releases/tag/3.0-ctp-3
and you emailed me on May 22 saying it was released.

Are we talking about something different?

Rob

On 7 June 2015 at 08:31, Terje Sandstrom <notifications@github.com> wrote:

> The fix is not released, we discussed giving it a week or so, to pick up
> more, but with this fix we should reverse it, but then we need to test that
> it works for the adapter before we release. I agree the fix belongs in the
> engine, but the adapter fix kind of isolates the adapter from the engine.
> I'll try to make a new build of the engine, and reverse the changes in the
> adapter to see if it still works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nunit/nunit/issues/674#issuecomment-109747758>.
>



-- 

Rob Prouse



I welcome VSRE emails. Learn more at http://vsre.info/

**Comment by OsirisTerje** [comment]
Right, the appdomain fix is sort of in there, but it doesn't work for Run All, just for selected tests.
This fix https://github.com/nunit/nunit3-vs-adapter/pull/35 was merged to fix that, and we planned to do a release ctp-4 this week, but haven't done so yet.

**Comment by CharliePoole** [comment]
I forgot that fix was posted ctp-3! It seems you should continue as planned so we have a working adapter. Then you can test with the new change and decide what to do next without so much pressure.
