### ISSUE TITLE
TestAgency does not launch agent process correctly if runtime type is not specified (i.e. v4.0)

### ISSUE THREAD

**Issue by NikolayPianikov** [nunit/nunit#687]
Error: Could not load file or assembly 'assembly name'; or one of its dependencies. This assembly is built by a runtime newer than the currently loaded runtime and cannot be loaded.

**Comment by CharliePoole** [comment]
This is a normal error message in certain cases. It should not come up by default but it may come up if you force NUnit to do something like trying to run a 4.5 assembly under 2.0.

What command line was used to result in this message?

**Comment by NikolayPianikov** [comment]
`nunit-console.exe HelloWorld.Tests.dll --noresult --framework=4.0 --workers=10 --verbose`
But it works under NUnit 2.6.4

**Comment by rprouse** [comment]
@NikolayPianikov, is `HelloWorld.Tests.dll` compiled as a .NET 4.5 assembly? If it is, then the error is correct. 

If NUnit 2.6.4 is detecting that the assembly is 4.5 and running it as 4.5 despite the fact that you specified 4.0, then I think that is wrong.

If however HelloWorld.Tests.dll targets .NET 4.0 or earlier, then this is a bug. Can you please confirm which framework it targets?

**Comment by NikolayPianikov** [comment]
HelloWorld.Tests.NUnit2 (mscorlib, Version=4.0.0.0)
ref to
	nunit.framework, Version=2.6.4.14350 (mscorlib, Version=2.0.0.0)

nunit-console.exe HelloWorld.Tests.NUnit2.dll /framework=4.0
ok
nunit-console.exe HelloWorld.Tests.NUnit2.dll /framework=2.0
failed
nunit-console.exe HelloWorld.Tests.NUnit2.dll /framework=4.5
ok
nunit-console.exe HelloWorld.Tests.NUnit2.dll
Execution Runtime: net-3.5
ok

HelloWorld.Tests (mscorlib, Version=4.0.0.0)
ref to
	nunit.framework, Version=3.0.5610.33196 (mscorlib, Version=2.0.0.0)

nunit-console.exe HelloWorld.Tests.dll --framework=4.0
failed

nunit-console.exe HelloWorld.Tests.dll --framework=2.0
failed

nunit-console.exe HelloWorld.Tests.dll --framework=4.5
failed

nunit-console.exe HelloWorld.Tests.dll --framework=4.5
ok

**Comment by rprouse** [comment]
@NikolayPianikov, thanks, that is exactly what we needed. Looks like a bug to me :beetle:

**Comment by NikolayPianikov** [comment]
https://github.com/NikolayPianikov/HelloWorld.git
Could you fork it

**Comment by CharliePoole** [comment]
I'm able to replicate this using NUnit's own tests, which makes it simpler. 

I think the problem is with the user of --framework=4.0 rather than --framework=net-4.0. Could you try that in your environment?

**Comment by CharliePoole** [comment]
Changed title to reflect what I have found. When no runtime is specified, the TestAgency has different code to launch agent under .NET versus Mono. If only the version is specified, it should pick one - the one under which it is currently running, I think.

**Comment by NikolayPianikov** [comment]
@CharliePoole it helps, thank you
