### ISSUE TITLE
Would like to be able to include tests based on namespace not just using categories

### ISSUE THREAD

**Issue by NikolayPianikov** [nunit/nunit#691]
For example 
`nunit-console.exe foo.dll --include=ns:Foo.SimpleTests --exclude=ns:Foo.SimpleTests.Group1`
or something like this [Specifying an Assembly and a Test to be Run](http://nunit.org/index.php?p=consoleCommandLine&r=2.6.4) May be it is working for NUnit 3?

**Comment by NikolayPianikov** [comment]
Ok sorry I see it works via arg --test

**Comment by CharliePoole** [comment]
Yes, these may be unified in a future release.
