### ISSUE TITLE
PlatformAttribute_OperatingSystemBitNess fails when running in 32-bit process

### ISSUE THREAD

**Issue by jcansdale** [nunit/nunit#692]
Test 'NUnit.Framework.Internal.PlatformDetectionTests.PlatformAttribute_OperatingSystemBitNess' failed: 
  Expected: False
  But was:  True
	...\NUnitFramework\tests\Internal\PlatformDetectionTests.cs(498,0): at NUnit.Framework.Internal.PlatformDetectionTests.PlatformAttribute_OperatingSystemBitNess()

**Comment by CharliePoole** [comment]
This is a test bug. In fact, the test only fails in a 32-bit process because PlatformHelper correctly identifies that it's on a 64-bit OS. The intent of the Assert at line 498 is that the OS must be 64 bit if the process is 64 bit. This should be refactored a bit to make it clearer.
