### ISSUE TITLE
NUnit Test Server

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#701]
An Test Server would run continuously on the local or a remote machine. It would accept and queue requests to run tests and report on their status back to the requestor.

While it might seem to do the same thing as nunit-agent, it's a bit different:
1. It's long running.
2. It's a server. (NUnit-Agent actually works as a client, even though it performs a service!)
3. Execution may be delayed so it needs to provide calls for the client to check status.
4. We will need to have some sort of admin client to run it.
5. We will need to have some way of centralizing the information about what servers are available.

We had a rudimentary server at one point in the life of NUnit 2.x. It shared a base class with nunit-agent. We may be able to reuse or re-purpose some of that code.

This is a post-3.0 feature.

**Comment by mklemarczyk** [comment]
+1 I can provide some help with this issue in the future.

**Comment by ChristianPejrup** [comment]
Very interesting idea, we have been talking about doing something similar in my team. We need some test grid (for lack of a better name) where we can execute long running integration tests. 
if there are some concrete tasks I would be happy to lend a hand :-)

**Comment by CharliePoole** [comment]
I doubt this is something we will get into the 3.0 release. More to the point, we wouldn't want to delay the 3.0 release in order to get this feature in.

That said, I can go ahead and restore the old server code in order to let someone else work on it. Give me a few days.

**Comment by ChristianPejrup** [comment]
That's all right, right now i'm personally more excited about seeing the final release of NUnit 3...this is just a cool feature. Until a server exist it should still be possible to do some RPC on another computer and running NUnit.exe commandline.

**Comment by oznetmaster** [comment]
This is basically what I am doing in a small way with my CF builds.  "Server" runs on CF device, and queues request from PC to run tests on the device (which run independently from the server).

**Comment by CharliePoole** [comment]
This issue was written back when the engine, console and framework were all one project. Its actually an engine feature, so I'm moving it to the nunit-console project, which includes the engine.

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit-console #167](https://github.com/nunit/nunit-console/issues/167) via [**ZenHub**](https://www.zenhub.com/)
