### ISSUE TITLE
TeamCity non-equal flowid for 'testStarted' and 'testFinished' messages

### ISSUE THREAD

**Issue by maximpashuk** [nunit/nunit#703]
I am using NUnit.Console Runner 3.0.0-beta2 on assemblies dependent from NUnit 2.6.4 (v2 driver bundled in nuget package)

I get following messges.

##teamcity[testStarted name='NuClear.AdvancedSearch.EntityDataModel.EntityFramework.Tests.EdmxBuilderConceptualModelTests.ShouldExposeAssociationSet' captureStandardOutput='true' flowId='1012']

##teamcity[testFinished name='NuClear.AdvancedSearch.EntityDataModel.EntityFramework.Tests.EdmxBuilderConceptualModelTests.ShouldExposeAssociationSet' duration='1.703' flowId='1-1012']

1012 non-equal to 1-1012, so TeamCity thinks that test not finished at all.

**Comment by CharliePoole** [comment]
I'm thinking this is probably easy to fix so I put it in the beta 3 milestone.

**Comment by CharliePoole** [comment]
@maximpashuk I'm not seeing this problem on the current source. Are you able to build from source and try it?

**Comment by CharliePoole** [comment]
I have confirmed that this problem exists in the beta2 release but has been fixed in the current code, incidental to other issues.
