### ISSUE TITLE
Include Chocolatey packages in releases

### ISSUE THREAD

**Issue by DustinVenegas** [nunit/nunit#707]
Chocolatey is a machine package management, or desired state configuration, tool. It assists with managing machine-level applications similar to apt-get and yum. 

Chocolatey currently has an outdated package for NUnit submitted by an individual contributor. I propose the project includes a set of Chocolatey packages in addition to the NUnit ones. It's possible to contact the Chocolatey administrators and add a few trusted NUnit contributors to maintain the packages. 

To best provide the best experience to Chocolatey users three packages need to be managed. NUnit, NUnit.Install, and NUnit.Portable. This allows other Chocolatey packages to only depend on a version of the placeholder package and users to select if they prefer a bin or Windows installation. For backward compatibility the NUnit package should perform an installation through the NUnit installer. 

Furthermore since NUnit already uses proper semantic versions we do not have to create a new set of packages and can instead just rev the package versions. Users that depend on NUnit2x can specify the major release version during installation. The actual package bundles should continue to be stored as releases on GitHub and will not need to be modified.

**Comment by CharliePoole** [comment]
This duplicates #452 

Thanks for your comments. They will help us on implementing this.

**Comment by CharliePoole** [comment]
Can you explain what you mean by NUnit.install and NUnit.portable?

**Comment by DustinVenegas** [comment]
The "Install" postfix denotes that a package uses a Windows installer under the covers while a "portable" package is just a bin deploy with the ability to add items to the chocolatey bin and path.

**Comment by CharliePoole** [comment]
Thanks. Can you point me to an example package that uses this convention?

**Comment by DustinVenegas** [comment]
> Thanks. Can you point me to an example package that uses this convention?

Sure! Putty has a [virtual package](https://chocolatey.org/packages/putty), [Windows Installer package](https://chocolatey.org/packages/putty.install), and [bin deploy package](https://chocolatey.org/packages/putty.portable). 

Anything that depends on Putty should use the virtual package. The portable and install packages let the user select exactly which they'd like to install. Regretfully it's [not implemented yet](https://github.com/chocolatey/chocolatey/issues/7).
