### ISSUE TITLE
Exclude NUnit root methods in the call stack from code coverage

### ISSUE THREAD

**Issue by NikolayPianikov** [nunit/nunit#709]
The coverage tools show statistics about NUnit. That's not what the user wants in the general case from my point of view. We could just turn off it adding ExcludeFromCodeCoverage attribute before several root methods

**Comment by CharliePoole** [comment]
It's an interesting idea. I see two concerns:

1. Would we have to do this in a large number of places? That could be a maintenance hassle.

2. We like to run code coverage on NUnit itself from time to time.

Let's hold and comment on this as an idea before we decide to make it a new feature.

**Comment by NikolayPianikov** [comment]
1. We could do it only for roots of invocations
for example main() in the nunit-console and in the agents when we start running
2. We can use alternative internal roots of invocations special for this case

**Comment by CharliePoole** [comment]
So does the attribute, when placed on a method, also exclude everything called by that method? If that's the case, how does it get turned off when we enter the code of the SUT?

BTW, I have personally never liked the attribute approach, preferring external filters, which is why I don't understand it very well. :-)

**Comment by NikolayPianikov** [comment]
Yes you are absolutely right, but we are using a thread to start the test (or we can do it) is not it? In this case we could use this approach, but we will have some performance gap and an additional complexity

**Comment by CharliePoole** [comment]
Of course, in general people also want their tests excluded from the
report. But that's either up to them or a matter of filtering their
results, I think.

**Comment by rprouse** [comment]
Thanks for the idea, but this isn't in keeping with our vision of where we want to take NUnit, so I am closing.
