### ISSUE TITLE
Include command information in XML

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#713]
See comments toward end of issue #297, started by @yetibrain.

We should experiment with including (some or all of) the contents of the TestPackage settings in the xml.

**Comment by CharliePoole** [comment]
Here's a proposal for fixing this...

Include a new element <settings> under <test-run>.
Under <settings> include multiple <setting> elements.
Each <setting> element would have name and value attributes.
All package settings, as finally resolved in the engine, would be included. IOW, if the engine decided to use 5 worker threads, we would have
  <settings><setting name="NumberOfWorkers" value="5" />...</settings>

Comments?

**Comment by CharliePoole** [comment]
@nunit/contributors @nunit/core-team @yetibrain
This won't go anywhere unless there are positive comments.

**Comment by constructor-igor** [comment]
@CharliePoole I agree with this proposal

**Comment by rprouse** [comment]
I also agree with this proposal.
