### ISSUE TITLE
Console --test option should include nested classes

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#714]
If I use the option --test:My.Namespace.A, where A is a test fixture, class B, nested in A, is not executed. I have to separately specify --test:My.Namespace.A+B to get it. It seems logical to me that we should include any nested classes when a classname is specified on this option.

This could be considered a feature, enhancement or bug. I made an arbitrary choice.

**Comment by CharliePoole** [comment]
I created this as the lead of the project  at the time, not as a user. I think it's a good idea but not a big priority. 

Since the issue has been out there for five years and no user has even commented, I think it's a candidate for removal.

**Comment by mikkelbu** [comment]
Then I think we should remove it. We can always create a new issue (or reopen this), if a user has the need for this.

Should this issue be in the console repo now? (I guess it was created before the split of the framework and the console)

**Comment by CharliePoole** [comment]
@mikkelbu If done, it would be in the framework project. It's a question of how the framework interprets a Test filter.
