### ISSUE TITLE
Support old names for arguments together with new names

### ISSUE THREAD

**Issue by NikolayPianikov** [nunit/nunit#721]
The NCover uses "/noshadow" to run tests under NUnit
Could we support old names, if it possible

**Comment by CharliePoole** [comment]
In general, we are trying to make a clean break from old version command-line arguments with 3.0. Can you give some more specific reason why this should be different?

I have used ncover myself and the command-line is always specified by me. Does NCover now have some built-in understanding of NUnit? If that's so, won't there be other differences that prevent it from running correctly?

**Comment by NikolayPianikov** [comment]
When I run the NCover it tries to add argument "/noshadow" on one's own. I am using NCover v3.4.18.6937 x64. I dont know about other differences. When I start NUnit from cmd file the NCover does not detect NUnit and does not add argument "/noshadow". Now it is not very important, we have postponed the support of NCover for NUnit 3.

**Comment by CharliePoole** [comment]
OK, I see we were talking about different things. The only NCover I have used is the open source tool. I haven't bought or used the commercial version.

My feeling is that it's up to the NCover developers to ask us for changes or to adapt their product to NUnit 3.0. We treat NUnit 3.0 as almost a new product compared to NUnit 2.x and I think it will be best if they do it as well. This is definitely not the only command-line argument change that may be needed now or in the final release.

**Comment by NikolayPianikov** [comment]
I've created an issue for the NCover team
