### ISSUE TITLE
NUnit packages should be signed

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#729]
Let's see what it takes to get our packages signed using gpg. It will give people assurance that they actually have a real package from us.

Comment here regarding this idea.

**Comment by agray** [comment]
If we did that would it mean projects that nuget nunit would also have to be signed?

**Comment by CharliePoole** [comment]
Not that I'm aware of. This is not about signing assemblies in .NET it's about download of packages.

**Comment by agray** [comment]
Ahh ok.  then +1

**Comment by rprouse** [comment]
As an alternative, we could also provide the MD5 hash for any packages that we release.

**Comment by rprouse** [comment]
I think that downloading from a known good source (our GitHub or NuGet feeds) is probably enough and nobody has requested that I know of.

**Comment by CharliePoole** [comment]
I'm OK either way.
