### ISSUE TITLE
Explicit Tests get run when using --exclude

### ISSUE THREAD

**Issue by stffabi** [nunit/nunit#741]
Running an Assembly with a TestFixture like the following, the Explicit Tests will be run by the console-runner if the --exclude argument is used.

nunit-console.exe NUnitFailers.dll --shadowcopy --exclude=mytest

```
    [TestFixture]
    public class ExplicitTest
    {
        [Test]
        [Explicit]
        public void ExplicitTestCase()
        {
            Assert.Fail("Should never be run, even not if using exclude for categories.");
        }
    }
```

NUnit Console Runner 3.0.5674
Copyright (C) 2014 Charlie Poole

Test Files
    D:\Framework\01_Source.git\NUnitFailers\NUnitFailers\bin\Debug\NUnitFailers.dll

Runtime Environment
   OS Version: Microsoft Windows NT 6.3.9600.0
  CLR Version: 4.0.30319.0

Options
    ProcessModel: Default    DomainUsage: Default
    Execution Runtime: Not Specified
    Work Directory: D:\Framework\01_Source.git\References\NUnit
    Internal Trace: Off

Excluded categories: mytest

Test Run Summary
    Overall result: Failed
   Tests run: 2, Passed: 1, Errors: 0, Failures: 1, Inconclusive: 0
     Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0
  Start time: 2015-07-16 06:25:45Z
    End time: 2015-07-16 06:25:45Z
    Duration: 0.063 seconds

Errors and Failures

1) Failed : NUnitFailers.ExplicitTest
One or more child tests had errors

2) Failed : NUnitFailers.ExplicitTest.ExplicitTestCase
Should never be run, even not if using exclude for categories.
   at NUnit.Framework.Assert.Fail(String message, Object[] args)
   at NUnitFailers.ExplicitTest.ExplicitTestCase() in D:\Framework\01_Source.git\NUnitFailers\NUnitFailers\ExplicitTest.cs:line 17

Results (nunit3) saved as TestResult.xml

**Comment by CharliePoole** [comment]
Confirmed by code inspection. NotFilter has a boolean property TopNode, which causes explicit tests to be skipped when true. The code to actually set TopNode never made it into 3.0. It's a fairly simple fix to TestFilter.cs.
