### ISSUE TITLE
Feature request: Is.SupersetOf() assertion constraint

### ISSUE THREAD

**Issue by ulrichb** [nunit/nunit#753]
See https://bugs.launchpad.net/nunit-3.0/+bug/1184903.

**Comment by CharliePoole** [comment]
This is an issue we neglected to move from launchpad at the time we migrated to GitHub. Thanks to @ulrichb it's here now. I'm marking it for inclusion in 3.0 because it's pretty easy to do.

This would be a good one for somebody who is new to NUnit development, since it merely requires copying and making a few changes to the existing SubSetConstraint, and then adding the appropriate syntax elements to Is, ConstraintExpression and ConstraintFactory.

**Comment by Seddryck** [comment]
I'd be pleased to take it but I'm not sure I've really understood the goal of this new constraint. Is there really a difference between this new constraint "SuperSet" and creating an assertion with a few constraint "Contains" linked with an "And"?

**Comment by CharliePoole** [comment]
@Seddryck Both SuperSet and SubSet could be emulated by the user with Contains constraints, provided that
1. Only a few items are involved
2. They are known to the user
3. There are no duplicates
4. There are no nulls

The existing SubSetConstraint deals with all of those and is generally used by folks with two collections to deal with, one or both of which doesn't meet the above criteria.

I would approach it myself by simply copying the code for CollectionSubsetConstraint and changing things around to reverse the role played by the so-called "actual" and "expected" values. The tests in CollectionSubsetConstraintTests should be duplicated and changed as well. The tests will probably take more work than the implementation in this case.

Each bit of syntax used for subset needs to be replicated for superset. My earlier comment lists the locations where you will find these.

The actual implementation details are handled by the existing CollectionTally class, which I don't think you will need to change.

**Comment by CharliePoole** [comment]
@Seddryck I've added you to the contributors team and will be able to assign this issue to you once you accept.

**Comment by Seddryck** [comment]
@CharliePoole invitation accepted. I'll do this tomorrow, doesn't sound really complex.
