### ISSUE TITLE
Async Task test run hangs when a Windows Forms Form was created in the scope of previous\current test

### ISSUE THREAD

**Issue by Taron-art** [nunit/nunit#756]
Hi all,
I have not tested this issue on NUnit 3.0 but because 2.0 repository is closed, I am posting it here.
NUnit 2.6.4
Here the example of the issue:

```
[TestFixture]
public class Form1Tests
{
    [Test]
    public void Test1()
    {
        new Form1();
    }

    [Test]
    public async Task Test2()
    {
        DomainObject domain = new DomainObject();
        await domain.TestAsync();
    }
}

public class DomainObject
{

    public Task Test()
    {
        return Task.Delay(1000);
    }

    public async Task TestAsync()
    {
        await Test();
    }
}
```

Form1 is the Windows Forms form. If you run these tests one by one, they will pass. However, in a single run it hangs on the second test.
Such test will also fail:

```
    [Test]
    public async Task Test2()
    {
        Form1 form = new Form1();
        await form.TestAsync();
    }
```

There is a workaround - use the "async void" instead of "async Task" in tests, but it is not the best idea... 
Another workaround is to mark all tests that create forms using the [RequiresSTA] attribute however this doesn't work if RequiresSTA is applied for the Test Fixture or Assembly.

**Comment by rprouse** [comment]
I am closing since we have not heard back from you. If you have more information, add it to this issue and we will reopen.

**Comment by kthureen** [comment]
Hello,

This issue remains and is reproducible - please see the attached VS 2013 project.

I am able to reproduce the hang when running the tests from the NUnit 2.6.4 UI and also using the Test Adapter for Visual Studio 2013.

[WindowsFormsApplication2.zip](https://github.com/nunit/nunit/files/1174024/WindowsFormsApplication2.zip)

**Comment by jnm2** [comment]
It deadlocks because you're actually asking it to. This isn't an NUnit problem- a simple console app does the exact same thing.

What's going on here is described in detail at https://github.com/nunit/nunit/issues/2123#issuecomment-293858901 and I provided solutions [lower down](https://github.com/nunit/nunit/issues/2123#issuecomment-293861259).
