### ISSUE TITLE
`NUnit.Framework.Assert' does not contain a definition for `IsNotNullOrEmpty'

### ISSUE THREAD

**Issue by ArsenShnurkov** [nunit/nunit#759]
After updating to NUnit-3.0.0-Beta3 i started receiving this error:
<pre><code>
Errors:

/var/calculate/remote/distfiles/egit-src/deveeldb.git/src/deveeldb-nunit/deveeldb-nunit.csproj (Build) ->
/usr/lib64/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->

	Deveel.Data.Sql.Expressions/SqlBinaryExpressionTests.cs(56,11): error CS0117: `NUnit.Framework.Assert' does not contain a definition for `IsNotNullOrEmpty'
	Deveel.Data.Sql.Objects/SqlLongStringTests.cs(104,11): error CS0117: `NUnit.Framework.Assert' does not contain a definition for `IsNotNullOrEmpty'

	 0 Warning(s)
	 2 Error(s)
</code></pre>

**Comment by CharliePoole** [comment]
See https://github.com/nunit/nunit/issues/197

See also https://github.com/nunit/nunit/wiki/Breaking-Changes
