### ISSUE TITLE
Assert Exception does not validate exception message

### ISSUE THREAD

**Issue by DigitalFlow** [nunit/nunit#764]
Hello everyone,

Edit: Nevermind, just found out that this is intended and that the message attribute specifies the error message if the test fails instead of specifying a comparison message.
You can close this issue. Below just for the record the initial question.

///

I just wrote a unit test which should verify if a specific exception is being thrown when a function is called.
My code for verifying was:

`Assert.Throws<InvalidPluginExecutionException>((() => plugin.Execute(serviceProvider)), expectedExceptionMessage);`

I found out, that this was not verifying the exception message, but only the type of the exception.
In my code, there are some exceptions being thrown, all of the same type, but with varying messages.
When I changed my test data to trigger exceptions of the same type but with different message than the one that I defined, the tests still passed.
Is this behaviour intended?

Edit: I'm using NUnit.Runners v. 2.6.4 (from NuGet).

**Comment by rprouse** [comment]
There is just a mistake in your code. The third parameter is the message that displays if the assertion fails, not the message in the exception. If you use Assert.Throws, it returns the exception that was caught so that you can check the message in a subsequent assert.

Or you can use the Assert.That syntax and add the expected message to the second argument.

```C#
var exception = Assert.Throws<InvalidPluginExecutionException>(
    () => plugin.Execute(serviceProvider));
Assert.AreEqual(exception.Message, expectedExceptionMessage);
```

```C#
Assert.That(() => plugin.Execute(serviceProvider), 
    Throws.InstanceOf<InvalidPluginExecutionException>()
    .With.Message.EqualTo(expectedExceptionMessage));
````
