### ISSUE TITLE
Running tests in parallel

### ISSUE THREAD

**Issue by Alex2357** [nunit/nunit#772]
What am I doing wrong?
I had created 3 projects having just one class
    [TestFixture]
    public class UnitTest1
    {
        [Test]
        public void TestMethod1([Values(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)] int i)
        {
            Thread.Sleep(700 + i * 1000);
        }
    }

I run them using
"C:\Program Files (x86)\NUnit.org\bin\nunit-console.exe" "C:\Work\NunitParallel\Test3Proj\UT1\UT1\bin\Debug\UT1.dll" "C:\Work\NunitParallel\Test3Proj\UT1\UT2\bin\Debug\UT2.dll" "C:\Work\NunitParallel\Test3Proj\UT1\UT3\bin\Debug\UT3.dll" "/result=C:\Work\NunitParallel\nUnit_Tests_par301.xml" /exclude=NotBuild,Selenium,Slow --process=Multiple --workers=3

I see 1 process of nunit-console.exe & 3 processes of nunit-agent.exe. But the time of execution instead of 53s - 156s. What am I doing wrong? I played with different options and still no luck.

**Comment by OsirisTerje** [comment]
Read about the Parallelizable attribute here:  https://github.com/nunit/nunit/wiki/Parallelizable-Attribute 
As you can see it is default off, so just add it to your test classes, and it should work. 
Also be aware of the NUnit discussion list https://groups.google.com/forum/#!forum/nunit-discuss which is intended for user issues.  
I am closing this as it is not a NUnit issue.

**Comment by CharliePoole** [comment]
It looks like @Alex2357 made the assumption that running in multiple processes would cause those processes to run in parallel. It's not an unreasonable expectation but that's not how it works.

You don't say what version of NUnit you are using. If it's 2.x, then there is no way to run tests in parallel using a single execution of NUnit. In fact, NUnit is designed to prevent this from happening. OTOH, if you are using the 3.0 beta, then you can use parallelism within a single assembly as @OsirisTerje points out. However, it only currently works between different fixtures, not between test methods of a fixture. Parallelism beween different assemblies is another matter. It will be in the next beta release.

**Comment by Alex2357** [comment]
Many thanks to OsirisTerje & CharliePoole.
Charlie I hope I understood correctly 2 negations. I understood 
> "**It's a reasonable** expectation but that's not how it works."

Sorry I forgot to mention that I was using version 3. Because Resharper was doing paralleling using by assemblies I was thinking that it should work that way.
Paralleling test fixtures what I was looking for as we have just one testing assembly which I proposed to split into multiple.

**Comment by CharliePoole** [comment]
You understood correctly.

Since you are using 3.0, you can expect to get parallel assembly execution after we
1) Finish issue #304 so that NUnit supports it in a new release, and
2) Create a way for you to access that feature from the adapter in a new adapter release.*

* Note that we only use released versions of NUnit with the adapter. Anything else would be too confusing.

**Comment by OsirisTerje** [comment]
@Alex2357 If you already have all Your tests in a single Assembly, the attribute Method should work for you.  If you know that all textfixtures you have can be run in parallell, you can in fact just search/replace all TextFixture to Parallelizable  :-)

**Comment by Alex2357** [comment]
Thank you Charlie

**Comment by Alex2357** [comment]
@OsirisTerje. That's good feature that I don't need to split. Many thanks.
