### ISSUE TITLE
Upgrade Travis CI from Legacy Infrastructure

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#773]
Lower priority, but when I was on Travis, they suggested we upgrade our build from their legacy infrastructure to their new container based infrastructure.

See http://docs.travis-ci.com/user/migrating-from-legacy/

I pushed this out to 3.2 so that it is not on our critical path.

**Comment by ChrisMaddock** [comment]
@rprouse: I believe this is done, the travis CI builds state:

> This job is running on container-based infrastructure

Apologies if I've missed something!
