### ISSUE TITLE
Assert.That fails when compares int and enum with same values

### ISSUE THREAD

**Issue by constructor-igor** [nunit/nunit#781]
```
  Expected: 11
  But was:  11

   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at PerformanceLab.EnumHelperTests.AssertEnumAndIntTrue() in EnumHelperTests.cs: line 72
```

```c#
        [Test]
        public void AssertEnumAndIntTrue()
        {
            int intValue = 11;
            AssertEnumSample enumValue = (AssertEnumSample)Enum.ToObject(typeof(AssertEnumSample), intValue);
            Assert.That(enumValue, Is.EqualTo(intValue));
        }

        [Flags]
        private enum AssertEnumSample
        {
            Value2 = 2,
            Value8 = 8,
        }
```

**Comment by CharliePoole** [comment]
What happens if you simply cast the int to AssertEnumSample rather than using ToObject? What happens if you reverse the terms of the Asser.That?

**Comment by constructor-igor** [comment]
- test **passes** when add casting **(int)enumValue** ;
- test **fails** when reverse arguments in Assert.That

**Comment by rprouse** [comment]
This seems somewhat arbitrary to me. The only reason it is showing you what looks to be two equal values is that you are assigning an invalid value to the flags enum. If I rewrite the test to use a valid value, the test result is clearer,

```C#
[Flags]
enum AssertEnumSample
{
    Value2 = 2,
    Value8 = 8
}

[Test]
public void TestFlags()
{
    var flags = (AssertEnumSample)10;
    Assert.That(flags, Is.EqualTo(10));
}
```

Gives the error

```
Expected: 10
But was: Value2, Value8
```

To me, this isn't a bug, just the fact that NUnit doesn't automatically convert enums to ints and visa-versa. Personally, I think NUnit does too many implicit conversions and my tendency is to not add new ones. .NET doesn't implicitly convert enums and ints, so I don't think we should. For example, based on the above code, this code does not compile.

```C#
Assert.IsTrue(flags == 10);
```

I am going to close this as won't fix. If you can give me a compelling reason to automatically convert ints and enums, then I might consider reopening.
