### ISSUE TITLE
Package separately for Silverlight

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#783]
Based on some discussions around issue #760, we will remove Silverlight from the zip and nuget distributions and create separate packages. For now at least, we will leave it in the msi, since that is only produced on Windows machines.

Tasks:
1. Remove Silverlight from the binary NUnit zip package.
2. Remove Silverlight from the NUnit nuget package.
3. Remove Silverlight from the NUnitLite nuget package.
4. Create a binary zip with just silverlight.
5. Create a Silverlight NUnit nuget package.
6. Create a Silverlight NUnitLite nuget package.

Naming: we will use nunit.silverlight in the package names.

Future: At some point in the (relatively near) future, we will freeze these packages and stop issuing them. At that point, we can remove silverlight from the msi as well.

**Comment by rprouse** [comment]
As part of this, I would like to remove Silverlight support from the portable framework since we have a full portable framework. This will allow me to re-enable some functionality in portable that is not available because of the Silverlight target.

**Comment by CharliePoole** [comment]
OK. Why don't you create a separate issue though - I may just postpone this one.
