### ISSUE TITLE
Switch configuration files from XML

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#786]
Most of NUnit's current configuration files are XML formatted (the project file, settings, etc). XML files are excessively verbose for our needs and can be difficult and error prone to edit.

We've switched the addin configuration to a simple flat file which prompted us to consider switching the format of our other configuration files to a simpler format. A flat file probably won't work, but JSON is becoming increasingly popular for configuration and project files.

The only issue is that we probably don't want to pull in a full JSON library. Our needs are not very complex, so we can probably find a one file JSON parser to pull in, maybe something like SimpleJSON?

**Comment by rprouse** [comment]
I am not in favour of doing this with existing configuration files now that we have shipped 3.0. I am going to close and we can evaluate on a case by case basis as we add new files.

**Comment by CharliePoole** [comment]
I realize you are the one who added the issue and were probably thinking of it as a 3.0 thing. OTOH, for me it was more like 4.0. In the long term I favor moving away from XML and maybe even in the short term for any new info files we may add.

Is there a reason to close such things that we aren't actually doing anything about? If seeing them as issues makes it too cluttered, then I think we need another place to list and discuss ideas for the future.

**Comment by rprouse** [comment]
@CharliePoole I am fine to reopen given that criteria. I was just trying to clean up some issues that we will likely never implement or where people are not getting back to us.

**Comment by CharliePoole** [comment]
I think it highlights the fact that Idea has become a bit of a grab bag of things. I'll give it some thought.

**Comment by CharliePoole** [comment]
@rprouse You closed once and re-opened after I commented. Since then (June) I have not done anything and don't plan to. Shall we once again close it?
