### ISSUE TITLE
Allow Extensions to provide data through an attribute

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#790]
Currently, Extensions provide only the names of a Type and its containing Assembly. That means no information can be acquired by the engine without first loading the assembly and instantiating the type.

Mono.Addins, which we originally used, allowed the extension to provide data, via an attribute, to the ExtensionNode it created. The host application could examine that data without loading the assembly. In fact, it supported data-only extensions, with no assembly at all.

I had planned to use that facility but had not yet done it. Now that we are using our own addin facility I'd like to add the same capability.

Example of Use:
A result writer addin provides an IResultWriterFactory, which in turn provides an IResultWriter. The factory has a property giving the name of the format supported, like "nunit2." The engine asks the factory for a result writer whenever the name matches what the user requested.

Use of the factory avoids instantiation of the result writer unless it is actually needed but it still requires that the assembly containing the extension be loaded. In fact, all result writer extensions must be loaded if we want to provide a list of available formats!

If the ExtensionNode contained a set of properties, the engine could simply examine the node to see what format it supported and instantiate the writer only if that format were needed. We could eliminate the factory entirely.

In fact, all the currently supported extensions suffer from this same problem. Even though our design for addins allows just-in-time loading, none of them are able to take advantage of it because of the lack of extension-specific information in the node. That's because our plan was to start simply and then take advantage of Mono.Addins to provide this data. That step is blocked now until we create a way for extensions to provide data.

Design Options:
For the ExtensionNode, a Properties dictionary is needed. It would translate property names to values, as we do in other cases. The main question is how the data is identified to be placed into the ExtensionNode.

Option 1: A Name and Value property could be added to ExtensionAttribute. The engine would add the single property to the extension node.

Option 2: A general-purpose attribute ExtensionPropertyAttribute would have a Name and Value members. It could be placed on any extension class, possibly multiple times, and the engine would examine it and add the properties to the extension node.

Option 3: We could publish special attributes derived from ExtensionAttribute supporting one or more properties. Those properties would be stored in a dictionary maintained by the attribute and the attribute's dictionary would be copied to the ExtensionNode dictionary.

Option 4: As a variant of 3, properties in the attribute would be independent but would be marked with a special Attribute signalling that the data should be copied to the ExtensionNode. This is the approach used by Mono.Addins. 

I plan to experiment with each of these. If I had to guess, the most likely candidates right now seem to be a combination of 1 and 3.

**Comment by rprouse** [comment]
Is this issue done now with PR #816?

**Comment by CharliePoole** [comment]
Yes. I just closed it.
