### ISSUE TITLE
Replace CoreEngine by use of Extensions

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#793]
If every feature of the full engine that is excluded by the core engine were made into an extension, we could eliminate the separate core engine build and simply deploy the engine without those extensions in situations we now use the core engine. This could also eliminate the need for any other engine builds, such as the mini-engine we have discussed for CF.

I'm marking this for the RC only to the extent that we should at least address it as an idea before that milestone. We may decide to implement it in 3.0, in a later version or not at all.

**Comment by CharliePoole** [comment]
Discussion of this issue took place offline, unfortunately. :-(

We will keep the existing core engine for NUnit 3.0, since it is used by the VS adapter. For 3.2, we will eliminate a separate core engine build.

Instead of building a core engine with minimal functionality, we will make this a matter of configuration. Functionality that is not included in the current core engine will be encapsulated as an extension. The "core engine" will essentially become the standard engine without any extensions. Intermediate configurations will be possible by controlling which extensions are available.

For example... The current core.engine does not include a runner for executing tests in a separate process. In the future, we would handle this by making the test runner factory extensible (creating a new extension point) and providing the process runner as an extension. In the absence of a process runner extension, running out of process would simply not be possible.

I'm scheduling this as a feature for 3.2.

**Comment by CharliePoole** [comment]
The current core.engine build is 55K in release. The full engine is 94K and also requires the engine api assembly, 17K, for a total of 111K. In addition, both the core and the full engine require mono.cecil. We are currently using the cecil nuget package which weighs in at 274K, far more than our either engine.

Considering the relative sizes, we can easily drop the core engine, which we only use currently for the NUnit3 Visual Studio Adapter. We can then work on reducing the size of the base engine by making parts that we left out of the core engine into extensions. We an also reduce the size of cecil, if desired, by building it ourselves. The source already uses compiler definitions that would allow us to reduce the size by building a read-only version - which is all we need.

I'm ready to move ahead with eliminating the core engine for the 3.0 RC, while holding the rest of this issue for release 3.2. That way, our users won't get into the habit of using it!

**Comment by CharliePoole** [comment]
Update - current assembly sizes as of RC3:

```
Core Engine:
    nunit.engine               103K
    nunit.engine.api           18K
    mono.cecil                 274K

Agents: (Needed if running in a separate process is supported:
    nunit-agent                    9K
    nunit-agent-x86             9K

Addins:
    NUnit projects              11K
    VS project                     11K
    V2 XML Output             16K
    V2 driver                     209K  (3 assemblies)
```

The "Core Engine" group is what the VS adapter uses.

**Comment by CharliePoole** [comment]
@rprouse Should we declare victory on this one?

**Comment by rprouse** [comment]
Probably, I can't think of anything more, can you?

**Comment by CharliePoole** [comment]
I think at this point, having eliminated the core engine, it's a matter of reducing the basic size of the engine by more use of extensions. Before doing that, we will need to be satisfied with how we are distributing extensions to users.

I'm calling this done.
