### ISSUE TITLE
TestDetails

### ISSUE THREAD

**Issue by jho1965us** [nunit/nunit#795]
Access to SetupFixtureAttribute annotated class instance should be available from methods in attribute class that implements ITestAction most likely as a member of TestDetails
This is not the case in 2.6.4

Motivation: some times you want some shared data in your SetupFixture currently you are forced to make this static

As a workaround for I attempted to store the SetupTestFixture class instance in TestContext.CurrentContext.Test.Properties for TestFixture but these properties are not forwarded to the tests TestContext automatic. Instead you need to capture them in the TestFixtureSetUpAttribute annotated method store them in the Fixture class which is available in TestDetails this seems unnecessarily convoluted to me. 
(Missing properties created as separate issue: #796)

**Comment by CharliePoole** [comment]
TestDetails is a class in NUnit 2.6.4, which doesn't exist in NUnit 3.0. Instead, the attribute is passed an ITest instance, which should allow full access to the parents of the test.

I think the new design covers what is asked for here, so I'm closing this issue. Let us know if you see any further issue with the new design.
