### ISSUE TITLE
The bindingRedirect prevents the assembly from being loaded

### ISSUE THREAD

**Issue by MainMa** [nunit/nunit#811]
I'm working on [MockEverything](https://github.com/MainMa/mockeverything) project and am facing a strange problem which manifests itself with NUnit, but not when running a similar test using Visual Studio Unit Testing Framework.

The goal of the project is to be able to tamper third-party assemblies when running unit tests. The [NUnit example](https://github.com/MainMa/mockeverything/tree/master/MockEverythingExample1) shows such a test where App.config files of `Sample`, `Tests` and `TestsWithNUnit` define bindingRedirects to force those projects to use a tampered assembly rather than the one in the GAC.

While `Sample` and `Tests` run perfectly well and the actual assembly stored locally is used instead of the one from the GAC, `TestsWithNUnit` fails with the exception:

> Could not load file or assembly 'System, Version=13.7.0.167, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.

Note: if I remove the App.config file, then the original assembly from the GAC is used: this shows that NUnit doesn't ignore App.config.

Shouldn't NUnit let .NET Framework search for the assemblies? Why is there an issue which doesn't exist when running similar code as a console application or as a test through Visual Studio Unit Testing Framework?

**Comment by MainMa** [comment]
The issue is reproduced by running NUnit-Console version 2.6.4.14350.

**Comment by CharliePoole** [comment]
What are the relative locations of NUnit-Console, your tests and the modified System.dll?

**Comment by MainMa** [comment]
- The location of NUnit-Console is the default one (C:\Program Files (x86)\NUnit 2.6.4\bin\nunit-console). 

- The test assembly (MockEverythingExample1.TestsWithNUnit.dll), its corresponding configuration file (MockEverythingExample1.TestsWithNUnit.dll.config) and the tampered assembly (System.dll) are all stored in the project `/bin/Debug` directory (which is also the current directory in command prompt when calling NUnit-Console).

NUnit is called this way:

    C:\Git\mockeverything\MockEverythingExample1\TestsWithNUnit\bin\Debug>"C:\Program Files (x86)\NUnit 2.6.4\bin\nunit-console" MockEverythingExample1.TestsWithNUnit.dll

**Comment by CharliePoole** [comment]
That's all as it should be. The next question that comes to mind is "Who is trying to load it and in which AppDomain?" Have you looked at the Fusion log?

**Comment by MainMa** [comment]
I tried to reproduce the issue with the latest console runner (3.0.5738), and can confirm that the test runs successfully. I suppose that only 2.6.* version is affected.

As for your question, it looks like the actual runner tries to load the assembly and fails. In all cases, it happens *before* the actual test code is called, and even before calling the method decorated with `[SetUp]` attribute. The fusion log looks like this when executing the tests from the console:

![fuslogvw](https://cloud.githubusercontent.com/assets/5724882/9928331/baabb91c-5d25-11e5-9877-7d4f13289c20.png)

And this is the detailed contents of the selected entity:

    *** Assembly Binder Log Entry  (9/17/2015 @ 10:14:56 AM) ***

    The operation failed.
    Bind result: hr = 0x80070002. The system cannot find the file specified.

    Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
    Running under executable  C:\Program Files (x86)\NUnit 2.6.4\bin\nunit-agent.exe
    --- A detailed error log follows. 

    === Pre-bind state information ===
    LOG: DisplayName = System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
     (Fully-specified)
    LOG: Appbase = file:///C:/Git/mockeverything/MockEverythingExample1/TestsWithNUnit/bin/Debug/
    LOG: Initial PrivatePath = NULL
    LOG: Dynamic Base = NULL
    LOG: Cache Base = C:\Users\Administrator\AppData\Local\Temp\2\nunit20\ShadowCopyCache\5488_635780816967964720
    LOG: AppName = Tests_470764125
    Calling assembly : nunit.core, Version=2.6.4.14350, Culture=neutral, PublicKeyToken=96d09a1eb7f44a77.
    ===
    LOG: This bind starts in LoadFrom load context.
    WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
    LOG: Using application configuration file: C:\Git\mockeverything\MockEverythingExample1\TestsWithNUnit\bin\Debug\MockEverythingExample1.TestsWithNUnit.dll.config
    LOG: Using host configuration file: 
    LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
    LOG: Redirect found in application configuration file: 2.0.0.0 redirected to 13.7.0.167.
    LOG: Post-policy reference: System, Version=13.7.0.167, Culture=neutral, PublicKeyToken=b77a5c561934e089
    LOG: GAC Lookup was unsuccessful.
    LOG: Attempting download of new URL file:///C:/Git/mockeverything/MockEverythingExample1/TestsWithNUnit/bin/Debug/System.DLL.
    LOG: Assembly download was successful. Attempting setup of file: C:\Git\mockeverything\MockEverythingExample1\TestsWithNUnit\bin\Debug\System.dll
    LOG: Entering download cache setup phase.
    LOG: Assembly Name is: System, Version=13.7.0.167, Culture=neutral, PublicKeyToken=b77a5c561934e089
    LOG: Where-ref bind Codebase matches what is found in default context. Keep the result in default context.
    LOG: Switch from LoadFrom context to default context.
    ERR: Setup failed with hr = 0x80131045.
    LOG: Attempting download of new URL file:///C:/Git/mockeverything/MockEverythingExample1/TestsWithNUnit/bin/Debug/System/System.DLL.
    LOG: Attempting download of new URL file:///C:/Git/mockeverything/MockEverythingExample1/TestsWithNUnit/bin/Debug/System.EXE.
    LOG: Attempting download of new URL file:///C:/Git/mockeverything/MockEverythingExample1/TestsWithNUnit/bin/Debug/System/System.EXE.
    LOG: Attempting download of new URL file:///C:/Program Files (x86)/NUnit 2.6.4/bin/lib/System.DLL.
    LOG: Attempting download of new URL file:///C:/Program Files (x86)/NUnit 2.6.4/bin/lib/System/System.DLL.
    LOG: Attempting download of new URL file:///C:/Program Files (x86)/NUnit 2.6.4/bin/lib/System.EXE.
    LOG: Attempting download of new URL file:///C:/Program Files (x86)/NUnit 2.6.4/bin/lib/System/System.EXE.
    LOG: All probing URLs attempted and failed.

So it actually finds the file, but then refuses to load it, showing a generic error message, and searches for the alternatives.

Do you want me to download the source code of the stable  2.6.* release to test the issue in debug mode? If yes, could you please indicate the location of the source code? It looks like the current GitHub project is NUnit 3.0 only, and the official website of NUnit has no links to 2.6.* source.

**Comment by rprouse** [comment]
@MainMa, thanks for confirming that this is no longer an issue in 3.0. I am going to close this issue because we will not be making any additional 2.6 releases and 3.0 will be out very soon.

If you want to see the 2.6 source code, it is here on GitHub at https://github.com/nunit/nunitv2. As I said though, there won't be another release unless we find some serious errrors.
