### ISSUE TITLE
Support nullable types with TestCase

### ISSUE THREAD

**Issue by appel1** [nunit/nunit#814]
For convenience it'd be nice if TestCase supported nullable types so you could have for example a DateTime? parameter instead of having to use TestCaseSource. 

```csharp
[TestCase("2000-01-01")]
public void Foo(DateTime? date)
{ }
```

**Comment by CharliePoole** [comment]
I put this into the RC on the premise that it's a trivial change. If I'm wrong, we should move it to 3.2.
