### ISSUE TITLE
Possible error in Merge Pull Request #797

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#818]
In src\NUnitFramework\\Internal\Execution\CommandBuilder.cs:

		/// <summary>
		/// Builds the set up tear down list.
		/// </summary>
		/// <param name="fixtureType">TypeInfo of the fixture.</param>
		/// <param name="setUpType">Type of the set up attribute.</param>
		/// <param name="tearDownType">Type of the tear down attribute.</param>
		/// <returns>A list of SetUpTearDownItems</returns>
		public static List<SetUpTearDownItem> BuildSetUpTearDownList (Type fixtureType, Type setUpType, Type tearDownType)

The comment indicates that fixtureType should be a TypeInfo, but in fact, it is a Type.

Which is correct?

**Comment by rprouse** [comment]
The XMLDoc is wrong, I pushed a fix.
