### ISSUE TITLE
Test for Debugger in NUnitTestAssemblyRunner probably should not be in CF build

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#822]
Even though it compiles, I am not sure what it would actually do.

Probably should be conditioned out for CF build.

**Comment by CharliePoole** [comment]
Do you mean this code?

if (!System.Diagnostics.Debugger.IsAttached &&
   Settings.Contains(PackageSettings.DebugTests) &&
   (bool)Settings[PackageSettings.DebugTests])
   {
      System.Diagnostics.Debugger.Launch();
   }

**Comment by oznetmaster** [comment]
Yes.

**Comment by rprouse** [comment]
Is having this code in the CF build harmful? I assume that it won't get called, so no harm no foul. It would be interesting to test if you could use it to attach a remote debugger. Doubt it, but it would be cool if we could.

**Comment by oznetmaster** [comment]
Not harmful, since on inspection, the actual options and package settings are not in the CF build, so it cannot be invoked.

However, since the options are conditioned out of the CF build, then the code seemingly should be as well.

A remote debugger cannot be attached by the CF device.

**Comment by CharliePoole** [comment]
I thought that perhaps it would work with an emulator, but I tested and found out it doesn't. The code should be conditioned out under CF.
