### ISSUE TITLE
Strange behavior in CF build after pull request #800 (issue 789)

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#823]
This test was originally conditioned out of the CF build.  It was put back in in the merge.

It fails in my CF build in a strange way:

9) Failed : NUnit.Framework.Attributes.TimeoutTests.TestTimeOutTestCaseWithOutElapsed
  Expected: `<Failed>`
  But was:  `<Failed:Cancelled>`
at NUnit.Framework.Attributes.TimeoutTests.TestTimeOutTestCaseWithOutElapsed()

**Comment by oznetmaster** [comment]
Sorry, should have attached this to issue #789 :(

**Comment by oznetmaster** [comment]
Aside from putting this in the wrong place, isn't the error itself a bit strange?

Shouldn't it be 

9) Failed : NUnit.Framework.Attributes.TimeoutTests.TestTimeOutTestCaseWithOutElapsed
  Expected: '<Failed:Cancelled>'
  But was:  '<Failed>'
at NUnit.Framework.Attributes.TimeoutTests.TestTimeOutTestCaseWithOutElapsed()

**Comment by oznetmaster** [comment]
How can the specific TestCase which is failing be determined?

It does not seem to be available in the results.

Should it be?

**Comment by rprouse** [comment]
I am going to close this issue as a duplicate of #789
