### ISSUE TITLE
Remove unused System.Reflection using statements

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#824]
With the introduction of the wrappers for Type, Method, etc.., there are many source files that now reference System.Reflection but do not use any of the classes in that namespace.

Does it make sense to clean these references up before release?

**Comment by rprouse** [comment]
Yes we should clean it up, but I don't think it needs to be done before the release since it has no effect on the resulting code that is compiled.

**Comment by rprouse** [comment]
I moved out to 3.2, but if someone wants to knock it off before, go for it and we can move it into the appropriate milestone.
