### ISSUE TITLE
Add ability to report test results synchronously to test runners

### ISSUE THREAD

**Issue by remcomulder** [nunit/nunit#830]
With the madness of the new VS release now receding to manageable levels, I’ve been working on integrating NCrunch with NUnit3.

I’m happy to say that so far progress has been good.  I now have a prototype adapter that can discover tests and execute them using NUnit’s FrameworkController.  With the XML reporting of results and the engine living inside NUnit.Framework, it’s looking like I’ll be able to have an implementation that will be highly adaptive to future versions of NUnit, without any reintegration necessary.  This is a very exciting thing for me 

A bit of a roadblock I’ve hit is around the manner in which NUnit reports the results of tests being executed.  It appears that the test results are being passed through a background thread.  This is a showstopper for NCrunch, as NCrunch needs to be able to swap code coverage maps (among other things) between the execution of individual tests/fixtures.  To do this, it needs to have the results reported from the test run entirely synchronously (i.e. on the same thread being used for the physical execution).

I encountered the exact same problem when integrating NCrunch with Gallio and XUnit.  In each case, the only solution was to modify the test framework to include a setting that would disable asynchronous execution and results reporting.

**Comment by CharliePoole** [comment]
I've made this a priority for the RC, always assuming we can make it work within the timeframe.

I think we can make the progress events come to you directly from the test thread, which may not be the same thread on which you called the framework. Do you think that will work?

**Comment by remcomulder** [comment]
That would work great :)

Sorry for the late response here ... for some reason Github didn't notify me of this comment, so I'd just been sitting waiting and hoping we'd get the fix soon.  I'm set to release NCrunch 2.17 very soon and was hoping to include the NUnit3 adapter with this release.  If there's any way we can agree on the setting that will be used in advance, I might be able to take a shot at including the NUnit3 support in this version.

**Comment by CharliePoole** [comment]
I've decided to do a Beta 5 release this weekend and push back the RC a  few weeks. I'll try to get this in, but I can't guarantee it.

**Comment by remcomulder** [comment]
Thanks!  No drama.  I can always move the integration into NCrunch v2.18 (whenever this gets released).  But less versions are always better :)

**Comment by remcomulder** [comment]
Awesome, thanks!
