### ISSUE TITLE
Enumerators not disposed when comparing IEnumerables

### ISSUE THREAD

**Issue by sparrow79** [nunit/nunit#837]
NUnitEqualityComparer does not dispose the IEnumerators used to enumerate the two IEnumerables (or ICollections) to compare, even if they implement IDisposable (e.g. every time they are actually implementations of IEnumerable<T>).

**Comment by rprouse** [comment]
Thanks for the report. I have set the milestone to the next release so that we can confirm and triage the issue.

**Comment by rprouse** [comment]
Fixed by #842
