### ISSUE TITLE
Pull Request #835 (Issue #814) does not build in CF

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#844]
This will not build under CF.

It references TimeSpan.TryParse which is not available in CF

**Comment by oznetmaster** [comment]
This is one of those interesting cases that come up every so often.

Since the CF fix actually works correctly in every build, why have a conditional?

Just use the CF code in all builds.  This has been the philosophy in other situations where the "less efficient" code that is universal is used (for instance, never using LINQ, even though it is available in every version except the NET 2.0 build).

**Comment by rprouse** [comment]
I'm actually wondering if the code should be as simple as the following for all platforms.

```C#
arglist[i] = TimeSpan.Parse((string)arg);
```

The convert code for other data types throws if the string that is being converted is incorrect. The TimeSpan parsing code probably should also so that meaningful errrors surface.

**Comment by CharliePoole** [comment]
I agree. I'll change my branch to work that way.

Charlie
