### ISSUE TITLE
Add new --process:inprocess and --inprocess options

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#847]
We currently use the following values for --process on the command line: Default, Single, Separate and Multiple. Single is sometimes confused with Separate. Single means "don't create a test process but run in the existing NUnit process" while Separate means "create a (single) separate test process".

I'd like to deprecate Single but still support it. I'd replace it with "Inprocess". I would also allow --inprocess to function as as a shortcut for --process:inprocess. Eventually, I would remove the Single option.

Thoughts?

**Comment by rprouse** [comment]
What about just switching `Single` to `Local`?

If not, I don't mind the proposed change.

**Comment by CharliePoole** [comment]
If we think ahead to when we are running on remote machines, then all these
options become Local.

I'm not crazy about the repetition in --process:inprocess but it's how I
always explain --process:single and the short form would take care of the
repetition.

Another possibility might be to do away with --process completely and just
have separate options  for each alternative. But I can't really think would
the options would be.

**Comment by oznetmaster** [comment]
Does everyone know what “inprocess” means?

**Comment by elbaloo** [comment]
@oznetmaster it would mean to run in the same NUnit process, and not in a separate one; same as what 'single' currently means.

**Comment by CharliePoole** [comment]
It's a good question. Always hard to know what people will understand most
readily.

**Comment by rprouse** [comment]
@CharliePoole, based on your comment on Local vs Remote, I am now in favor of InProcess.

**Comment by CharliePoole** [comment]
I'll incorporate this in the branch I'm doing for issue #713
