### ISSUE TITLE
Test Explorer not detecting tests - 2015

### ISSUE THREAD

**Issue by stephenstroud** [nunit/nunit#852]
Using: 
VS 2015 
Dnx Runtime: Beta 8
x86
"NUnitTestAdapter": "2.0.0"
  "NUnit": "3.0.0-beta-4"

Have tried both ways, via Nuget and extensions,.
Created a library class project, added   [TestFixture] ,[Test] and SetUp] attributes to class, rebuilt and cleaned etc. No tests appearing in the test explorer. Any help would be great, thanks

**Comment by CharliePoole** [comment]
I think you're duplicating #575 here with respect to the basic NUnit functionality.

However, you say you are using NUnit 3 with the NUnit 2.0 test adapter, which isn't possible. There is an NUnit3TestAdapter package, which supports NUnit 3.

Basically, you cannot expect any NUnit 2 version (or the 2.0 adapter) to support this usage. You can expect it from NUnit 3 and the NUnit3 adapter, but it's not there yet.

I'm marking this as a duplicate. Feel free to comment if you disagree.

**Comment by stephenstroud** [comment]
Doh!, Ok thanks for the reply, I'll carry on in the other ticket.
