### ISSUE TITLE
Intermittent failures of StopWatchTests

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#865]
These are tests of our substitute StopWatch used in the Portable and Silverlight builds. Occasionally, the expected elapsed times are passed, which is to be expected since it isn't deterministic. We should find a way to test so that this doesn't break the build.

**Comment by oznetmaster** [comment]
This happens on the CF builds as well, in some devices/emulators.

**Comment by CharliePoole** [comment]
We use System.Diagnostics.StopWatch in CF and the test class only verifies that our StopWatch derives from it. We may be seeing other timing issues in tests, which should be documented if there isn't already an issue for it.

**Comment by CharliePoole** [comment]
This is annoying me!
