### ISSUE TITLE
Seems, "List.Contains( object )" doesn't supported by NUnit

### ISSUE THREAD

**Issue by constructor-igor** [nunit/nunit#875]
According to nunit site, List.Contains implemented (at least in 2.4).
Seems, List.Contains is not supported by NUnit 2.4 and 3.0

http://www.nunit.org/index.php?p=collectionConstraints&r=2.4

![image](https://cloud.githubusercontent.com/assets/1849690/10331951/2523f144-6ce2-11e5-8092-703325cb1bb6.png)

**Comment by CharliePoole** [comment]
List.Contains had a short life. It was introduced in 2.4 in March 2007 and removed in 2.4.2 in August of the same year. The corresponding page for 2.4, 2.4.1 and 2.4.2 reflects this as do the  release notes. Several years later, we introduced a new static List class, which serves a different purpose.

Are you actually running NUnit 2.4, which is eight years old? You should have this feature, so long as it's the final release (2.4.0.2) or RC2 (2.4.0.1). Of course,  even if there is some problem with it, it's rather ancient history now. :-)

For NUnit 3.0, List.Contains has never existed and is not in the docs. See https://github.com/nunit/nunit/wiki/CollectionContainsConstraint
