### ISSUE TITLE
Remove SilverLight as a target in the Portable Framework

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#876]
We already have a version of the Framework that targets SilverLight and doing so within the portable framework limits the functionality that is available in portable.

**Comment by CharliePoole** [comment]
@rprouse I experimentally removed Silverlight 5 from the framework targets and it would not build... Could not find "Binding Flags"

This is completely unintuitive to me, so maybe I just don't understand PCLs. Please check whether this is really possible and kill the issue if it isn't.

**Comment by rprouse** [comment]
That is odd. Removing targets should increase the APIs available. I will
take a look.

**Comment by rprouse** [comment]
I am seeing the same thing. Very odd. This isn't worth sweating over so I am going to close.

**Comment by rprouse** [comment]
Reopening, as part of #575, I am merging the .NET Core changes into the portable framework. A result of this is that SL is being removed.
