### ISSUE TITLE
Cannot exclude MacOSX or XBox platforms when running on CF

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#878]
The CF build #if's the MacOSX and XBox platform code out. This doesn't make a difference when including platforms, but any platform exclusions for these will fail because CF sees them as an invalid platform identifier.

**Comment by oznetmaster** [comment]
The condition that was added in ApplyToTestTests.GetMyPlatform for CF can now be removed.

**Comment by CharliePoole** [comment]
I'll put it on my plate for the moment. If I can't get it into the beta, I'll give it back to @rprouse
