### ISSUE TITLE
FixtureTearDown not running when FixtureSetUp failed

### ISSUE THREAD

**Issue by darthKwisatzHaderach** [nunit/nunit#880]
I have two classes: BaseTest and FilteringTests.
FilteringTests are inherited from BaseTest.

In FilteringTests I have method FixtureSetUp.
In BaseTest I have two methods: FixtureSetUp and FixtureTearDown.

FilteringTests have fallen in FixtureSetUp, and I saw a strange behavior.

When I run tests in NUnit 3, I see the following steps:
1. BaseTest OneTimeSetUp
2. FilteringTests OneTimeSetUp (status: failed)
3. BaseTest OneTimeTearDown

But when I run tests in NUnit 2.6.4
1. BaseTest FixtureSetUp
2. FilteringTests FixtureSetUp (status: failed)
3. BaseTest FixtureTearDown - NOT RUNNING

I think this is a bug that the step 3 (BaseTest FixtureTearDown)  is not running in NUnit 2.6.4.

**Comment by CharliePoole** [comment]
That's a difference in the design of NUnit 2 and 3. I agree that the nunit
2 behavior is not the best approach, which is why we changed it in
rewriting NUnit.

This repo is for NUnit 3 and we no longer modify NUnit 2.

**Comment by CharliePoole** [comment]
You may want to refer to https://github.com/nunit/nunit/wiki/SetUp-and-TearDown-Changes which describes this changed behavior.

**Comment by darthKwisatzHaderach** [comment]
Thanks for the answer!
