### ISSUE TITLE
Console.Output.Encoding differs in and outside of an NUnit testing environment (NUnit 2.6.4)

### ISSUE THREAD

**Issue by delcypher** [nunit/nunit#881]
For a while now I've been aware of an issue when running NUnit 2.6.4 under mono and not sure why it's happening.

I reported the bug to the mono developers a while ago ( https://bugzilla.xamarin.com/show_bug.cgi?id=21374 ) but I was wondering if this might actually be a bug in NUnit.

The bug report covers what I've seen in a lot of detail but the general problem is that the `Console.Output.Encoding` object is different when running code in an executable and code from an NUnit test. The difference I see is in an executable, the encoding will not emit a UTF-8 byte order mark but in an NUnit test environment the encoding **will** emit a UTF-8 byte order mark.

Is this deliberate?

**Comment by delcypher** [comment]
Oh I should give context too. I'm running on Linux (kernel 4.2.2) with Mono 4.0.4.

**Comment by CharliePoole** [comment]
Since NUnit intercepts the console output, my guess is that mono determines whether the output is actually to the console and suppresses the byte order mark in that situation.

Is this causing some kind of problem in testing?

**Comment by delcypher** [comment]
> Since NUnit intercepts the console output, my guess is that mono determines whether the output is actually to the console and suppresses the byte order mark in that situation.

What I see is the opposite. When using my library from an NUnit test, ``Console.Out.Encoding`` is set to it emit the UTF-8 BOM. When using my library outside of NUnit (e.g. from an executable) ``Console.Out.Encoding`` is **not** set to emit the UTF-8 BOM.

This is causing a problem in my testing because my library communicates with an external process (which emits an error if it sees a UTF-8 BOM) using ``System.Diagnostics.Process`` and the encoding on standard input sent to the child process differs depending on if I use my library from an NUnit test or from an executable. The (not very obvious) reason why the ``Console.Out.Encoding`` matters here is because Mono's implementation of ``System.Diagnostics.Process`` uses that encoding to setup the encoding on the pipe between the parent and child process.

So what I'm really asking is why ``Console.Out.Encoding`` is different in an NUnit environment from what it is set to in an outside environment.

Does that make sense?

**Comment by CharliePoole** [comment]
Yes, that's what I meant - left out the "not" in my statement. That is the BOM is emitted when the output is redirected. For example, it might be going to a file, in which case the BOM is desired.

You could easily test this hypothesis by writing a simple program that redirects console output to various things: file, pipe, etc.

Since your problem is actually happening (if I understand you correctly) upstream from NUnit, i.e. in a process execution done by your library, which is called as a part of an NUnit test, I'm not sure how NUnit could be affecting this unless it is through the Console.Out.Encoding, which we set differently in various versions of NUnit. If your experiments show that we need to set it in a particular way when intercepting the console, we can try doing that for NUnit 3.0.

**Comment by delcypher** [comment]
> You could easily test this hypothesis by writing a simple program that redirects console output to various things: file, pipe, etc.

Doing this under mono does not change the emission of the UTF-8 BOM


```C#
            using (var FS = new FileStream ("foo.txt", FileMode.Create)) {
                using (var SW = new StreamWriter (FS)) {
                    Console.SetOut(SW);

                    // Mono implementation detail
                    // emitUTF8Identifier is a private Field so use reflection to find out what it's set to
                    BindingFlags bindingFlags = BindingFlags.Instance | BindingFlags.NonPublic;
                    FieldInfo fieldInfo = typeof(UTF8Encoding).GetField ("emitUTF8Identifier", bindingFlags);
                    bool emitIdentifier = (bool)fieldInfo.GetValue (/*process.StandardInput.Encoding*/ Console.Out.Encoding);
                    Console.WriteLine ("emitUTF8Identifier " + emitIdentifier);

                    if (emitIdentifier)
                        throw new InvalidProgramException ("What!!");

                }
```

> Since your problem is actually happening (if I understand you correctly) upstream from NUnit, i.e. in a process execution done by your library, which is called as a part of an NUnit test, I'm not sure how NUnit could be affecting this unless it is through the Console.Out.Encoding, which we set differently in various versions of NUnit.

It is the change of the encoding on ``Console.Out.Encoding`` that **is causing the problem** because Mono's implementation of ``System.Diagnostics.Process`` uses its value to set the encoding for the standard input of the child process.

I'm not really sure who is at fault here (I'm leaning towards mono).

* NUnit: [Emission of the UTF-8 BOM only really seems necessary under Windows because the tools don't handle them properly](https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8). Under Linux or OSX this isn't necessary at all.
* Mono: Reading a global property like ``Console.Out.Encoding`` to control the behaviour of a class seems like a bad idea. It could easily result in race conditions.

**Comment by CharliePoole** [comment]
Lacking other categories, I marked it as a bug with status:confirm. Really, it's a matter of whether we want to change the code to avoid the problem. I'll look at what we changed and why between 2.6.4 and 3.0 if the problem can be avoided easily without harming anything else, we'll fix it.

**Comment by rprouse** [comment]
I am closing since we have not heard back from you. If you have more information, add it to this issue and we will reopen.

**Comment by jnm2** [comment]
I wasn't aware of this issue, but I'm generally in favor of removing byte order marks unless removing them causes a practical difficulty.
