### ISSUE TITLE
Move environment and settings elements to the assembly suite in the result file.

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#887]
This is work that was postponed from #254.

We need to examine all attributes under the current environment element and determine where to move that information which actually varies from process to process. Some info will vary by machine as well but that can wait until we support remote execution.

**Comment by CharliePoole** [comment]
Proposal:

1. Move the entire environment element to the assembly-level test-suite. It will be produced by the framework in the case of NUnit 3.0, by the driver for NUnit 2.x and any other extension drivers.

2. Rename attribute nunit-version to framework-version, since that's what it is

3. Add two attributes to the test run element. (This could be an abbreviated environment element but attributes seem better for just two items)
   * nunit-version (console-version? engine-version?)
   * clr-version

This will result in some duplication when there are multiple assemblies but will serve us better when we run tests on different machines.

**Comment by rprouse** [comment]
Sounds good. I think nunit-version should show the engine version, not the version of the runner.

**Comment by oznetmaster** [comment]
What should it show for non-engine builds (nunitlite)?

**Comment by CharliePoole** [comment]
You would get the same assembly-level environment element as for the
console. That's the main reason I like this move. You wouldn't get a
test-run element at all IIRC.

**Comment by rprouse** [comment]
One thing I don't like is `framework-version` as it could mean any framework. It is probably clear because clr-version comes next, but it is obviously a version, so it could be `nunit-framework`. The engine could insert `nunit-engine` or nunitlite could insert `nunitlite`.

Should you also add `nunit-engine` to the environment element that you are moving down to the assemblies? Once we go multiple machine, the engine version on that machine could be different.

**Comment by oznetmaster** [comment]
Once we go multiple machines, the information about both machines needs to be in the results.

They likely will not be the same.

**Comment by rprouse** [comment]
Information for each machine should be in the environment node that is
being moved to the assembly level.

**Comment by CharliePoole** [comment]
Rob: I used framework thinking it might **not** be an NUnit framework in
the future. In the case of a foreign framework, the driver would have to
provide this.

Neil: If we run on multiple machines then each machine would have a
different assembly-level suite element with it's own environment.

**Comment by CharliePoole** [comment]
I changed the title to reflect that this deals with both the environment element and the settings element. Although some settings are provided by the command-line and are therefore the same for every assembly, many settings have default values, which are only known within the framework.

By moving at least some settings to the assembly level, the engine does not have to know how the particular framework calculates its default.
