### ISSUE TITLE
Extended type conversion for TestCase parameters

### ISSUE THREAD

**Issue by DioF** [nunit/nunit#89]
As .Net only allows attribute parameters to be compile time constant, the set of usable types for parameterized test methods is very small. Currently type conversion for **TestCase** parameters is done using `Convert.ChangeType()`. As these types are built-in types (except for custom enums) there is no way to extend them with `IConvertible` methods.

To be able to use custom types, it would be very handy to have more possibilities to convert the given parameters to the actual parameter's type. I suggest to support at least one of these:
- TypeConverter
- implicit cast operator
- explicit cast operator
- framework interface `ITestCaseParameterConvertible` that is called when converting

Currently, this feature can be achieved by adding a custom `TestCaseProvider` addin, but I believe this should be a core feature.

**Comment by rprouse** [comment]
This issue is marked as an idea/design/discussion but hasn't had contributions in years so I am closing. If anyone is interested in working on this idea, post your interest and the team will consider reopening.
