### ISSUE TITLE
NUnit 3.0 console runner not placing test result xml in --work directory

### ISSUE THREAD

**Issue by mlong072** [nunit/nunit#896]
The NUnit 2.6.4 console runner would place the test result xml file in the directory defined by the /work command line argument; NUnit 3.0 appears to place the test result xml file in the current directory the console runner command is being run from. The following Powershell console output shows me running the command from the "D:\workbench\git\project name\CAT" directory with the --work directory set to "D:\workbench\git\project name\autobuild\logs\nunit". Providing just the filename for the /result argument to the Nunit 2.6.4 console runner would have the result file placed in the working directory. After upgrading to NUnit 3.0 the console runner is placing the result file in the "D:\workbench\git\project name\CAT" instead of the defined work directory. If I provide an explicit path for the --result argument the result file is being created in the xpected location.

Console Output:

```
D:\workbench\git\project name\CAT> & "D:\workbench\git\project name\CAT\packages\NUnit.Console.3.0.0-beta-4\tools\nunit-console.exe" "D:\workbench\git\project name\CAT\Project.Common.Test\bin\Release\Project.Common.Test.dll" --framework=net-4.5 --labels=off --work="D:\workbench\git\project name\autobuild\logs\nunit" --result=Project.Common.Test.xml --include="unit" --exclude="disabled"

NUnit Console Runner 3.0.5715
Copyright (C) 2014 Charlie Poole

Test Files
    D:\workbench\git\project name\CAT\Project.Common.Test\bin\Release\Project.Common.Test.dll

Runtime Environment
   OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
  CLR Version: 4.0.30319.34209

Options
    ProcessModel: Default    DomainUsage: Default
    Execution Runtime: net-4.5
    Work Directory: D:\workbench\git\project name\autobuild\logs\nunit
    Internal Trace: Off

Included categories: unit
Excluded categories: disabled

Test Run Summary
    Overall result: Passed
   Tests run: 2, Passed: 2, Errors: 0, Failures: 0, Inconclusive: 0
     Not run: 0, Invalid: 0, Ignored: 0, Explicit: 0, Skipped: 0
  Start time: 2015-10-15 18:46:19Z
    End time: 2015-10-15 18:46:19Z
    Duration: 0.257 seconds

Results (nunit3) saved as Project.Common.Test.xml
```

**Comment by rprouse** [comment]
Thanks for reporting the issue. I have assigned to the RC release.

**Comment by CharliePoole** [comment]
If it's as trivial as I am guessing, I'll fix it now.
