### ISSUE TITLE
Colors for ColorConsole on grey background are too light

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#899]
When the  background is light grey, the colors used are a bit hard to read. We should fix this.

**Comment by rprouse** [comment]
Probably the same for all light backgrounds. Maybe not as easy a fix as you think. Ideally, we go through all of the 16 different windows background colors and come up with a color theme that works for each. There will likely be overlap, maybe even down to just two themes, use the light versions of colors for dark backgrounds and use the dark versions of colors for light backgrounds.

**Comment by CharliePoole** [comment]
True, I was thinking technically easy. :-)
