### ISSUE TITLE
Writability check could give a friendlier message.

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#901]
We introduced a writability check for result files, which simply tries to write an abbreviated file to the directory, throwing an exception and aborting the runner if it is unable.

We should see if we can give a better message that explains the directory is not writable.

When the directory used was chosen by default (i.e. the current directory is not writable), we should consider having a backup location instead.

**Comment by rvignesh89** [comment]
@CharliePoole could you give a little more details about this enhancement?

**Comment by CharliePoole** [comment]
The console runner calls CheckWritability on each output path specified for saving results, e.g.: TestResult.xml. That method is implemented by various result writer extensions and generally throws some System.IO type of exception. The user has to interpret the exception to figure out what is wrong.

We should catch the exception and make it the inner exception of an NUnitEngineException that has a message saying specifically that the output path specified is not writable. If you want to do it, get that part working and we can consider a backup location after that.

Since this is related to the console runner, it's in the wrong repo. I will move it.

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit-console #110](https://github.com/nunit/nunit-console/issues/110) via [**ZenHub**](https://www.zenhub.com/)
