### ISSUE TITLE
Parallel Test Execution documentation is out of date

### ISSUE THREAD

**Issue by MaceWindu** [nunit/nunit#919]
https://github.com/nunit/dev/wiki/Framework-Parallel-Test-Execution
At least this section is not correct anymore:
```
ParallelizableAttribute
Two Named Properties are supported:

    Scope = ParallelScope for setting ParallelScope using property syntax
    ExclusionGroup = string for ensuring that certain tests do not run together (NYI)

```

**Comment by CharliePoole** [comment]
That's from the dev wiki, used by the developers, and it's a specification for how we plan to implement parallelism. Everything related to an Exclusion Group is NYI (Not yet implemented).

In the actual documentation wiki, there is no general summary of Parallelism but each attribute has a descriptive page:

    https://github.com/nunit/nunit/wiki/Parallelizable-Attribute
    https://github.com/nunit/nunit/wiki/LevelOfParallelism-Attribute

We keep the two wikis separate in an attempt to avoid this sort of confusion. :-)

**Comment by MaceWindu** [comment]
Oh, thanks!
```
Note: In the current release, parallel execution of methods within a class is not yet implemented.
```
Now I could switch to something else :)
