### ISSUE TITLE
Wrap Console in NUnitLite

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#922]
The portable version of NUnitLite passes in a TextWriter/Reader from Console.Out/In. It would be better to wrap the console in an interface and pass it into AutoRun so that we can have the same code for portable and other frameworks. We could abstract this detail out of frameworks that support Console by default using #defines, but it would allow us to have a color console for portable or to pass in different TextWriters/Readers for platforms that don't support a console.

**Comment by CharliePoole** [comment]
I like it.

**Comment by rprouse** [comment]
It would also allow us to do some testing using a mock console.

**Comment by oznetmaster** [comment]
I like it too.

**Comment by CharliePoole** [comment]
I started on this.

@rprouse The thing is, there was already an interface - or at least an abstract class - ExtendedTextWriter, which was being used by TextUI and which you removed in the copy that's in the portable folder. There's also a derived class that translates the extended write commands to simple textwriter commands in addition to the color console implementation.

My plan is to put the interface back in place and then pass a color console writer from the runner. Once this is done, I suspect we may not need a separate copy of TextUI, but I'm doing it in stages first to see if I end up with identical code in the two files.

Not sure what milestone to put this in, however. I'm tempted to try for 3.0.

**Comment by oznetmaster** [comment]
Is it necessary for 3.0?  What are the implications of leaving it for 3.1?

**Comment by rprouse** [comment]
It isn't necessary for 3.0, but it would be a nicer story for .NET Core support. The current problem is that the portable version of NUnitLite does not have access to a console, so I pass in Console.In/Out as a TextReader/Writer. This just makes the AutoRun a bit messy and prevents portable from using the color console.

**Comment by CharliePoole** [comment]
I've done quiet a bit of work on this and have the color console working fine. I eliminated the extra copy of TextUI.cs and AutoRun.cs for portable. Everything works for me in Windows but not in Linux, possibly due to my needing to update to the latest MonoDevelop.

I had hopes it might be ready for 3.0, but I'm setting it aside and leaving it as 3.2.
