### ISSUE TITLE
support canceled tasks

### ISSUE THREAD

**Issue by waynebrantley** [nunit/nunit#924]
In nunit 2.6.4, this will throw a "Sending to this synchronization context is not supported" error.

[Test]
        public async void TestE() {
            CancellationTokenSource source = new CancellationTokenSource();
            source.Token.Register(() => { }, true);
            source.Cancel();
            source.Dispose();
        }

Is this addressed in 3.0?

**Comment by CharliePoole** [comment]
No, it isn't and really cannot be.

You are trying to "retroactively" create a token from inside a running task that was never passed one when it was created. Then you are asking for the task to cancel itself.

You can use a CancellationToken to cancel a task that you create from your tests, but only NUnit can cancel the task that is running your test. Currently, we don't use a CancellationToken to do that, but we probably should in the case of async test methods.

This article helped me understand cancellation:
https://johnbadams.wordpress.com/2012/03/10/understanding-cancellationtokensource-with-tasks/

**Comment by waynebrantley** [comment]
Charlie,
   I am trying to test some software that uses TPL and am getting this error.   Here is a better sample of the same error - this time I create the task inside the test and try to cancel that task.  Same issue.  Basically it seems you cannot ever cancel something inside an NUnit test?


```
[Test]
public async void AsyncError() {
    CancellationTokenSource source = new CancellationTokenSource();
    var token = source.Token;
    int i = 0;

    var t = Task.Factory.StartNew(() => {

        token.Register(() => { Debug.WriteLine("End"); }, true);

        while(i++ < 20 && !token.IsCancellationRequested) {
            Debug.WriteLine(i.ToString()); 
            Thread.Sleep(100); 
        } 
    }, token, TaskCreationOptions.None, TaskScheduler.FromCurrentSynchronizationContext());

    var t1 = Task.Factory.StartNew(() => {
        Thread.Sleep(500);
        source.Cancel();
    });

    try {
        Task.WaitAll(t, t1);
    } finally {
        source.Dispose();
    }
}

```

**Comment by CharliePoole** [comment]
Yes, that's a cleaner example. I can't try this out right now, but I don't think your test method here actually needs to be async. If that's so, it would be help to localize the problem if you would try it as simply (non-async) void.

Of course, I realize you could create an example where the test has to be async, so this is still an issue.

**Comment by waynebrantley** [comment]
Yeah, I am using a 3rd party library that is involved in testing and it is async and giving this issue.  Thanks for looking into this.

**Comment by constructor-igor** [comment]
nunit console shows next error:
```
        <test-case id="0-1052" name="AsyncError" fullname="NUnit_v3_samples.NUnitIssue924.AsyncError" methodname="AsyncError" classname="NUnit_v3_samples.NUnitIssue924" runstate="NotRunnable" seed="589179632" result="Failed" label="Invalid" start-time="2015-11-09 15:16:48Z" end-time="2015-11-09 15:16:48Z" duration="0.003114" asserts="0">
          <properties>
            <property name="_SKIPREASON" value="Async test method must have non-void return type" />
          </properties>
          <failure>
            <message><![CDATA[Async test method must have non-void return type]]></message>
          </failure>
        </test-case>
```

**Comment by CharliePoole** [comment]
@constructor-igor NUnit 3 does not support async void. Even though this issue is in the NUnit 3 repository, it has been about NUnit 2.6.

Since the issue can not really arise and so as to avoid confusion, I'm going to close it now!
