### ISSUE TITLE
Regular expression vs wildcard

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#926]
The current documentation says that the --where options =~ and !~ operators take a regular expression to match against.  However, the example "method =~ /Source.*Test/" implies that they take a wildcard expression.

Which is it, and is that what is really wanted?

**Comment by CharliePoole** [comment]
We definitely only handle regular expressions. I considered file blobs (wildcards) but decided it made things too complicated. I figured the use of the =~ and !~ operators would make it clear as well, but that may not be something our user base is familiar with.

The example may be bad, since it could be valid either as a regular expression or a wildcard. As a regex, the '.' means any char and the '*' means repeat 0 or more times. As a wildcard, the '.' would just be a dot and the '*' would mean zero or more characters.

What change do you suggest?

**Comment by oznetmaster** [comment]
Well, I was not familiar with that notation.  Actually have never seen !~ and =~ before.

I do not care which it is, as long as it is fully documented.

Is the regular expression a .NET regular expression, or a VS editor regular expression, or a javascript regular expression... (they are all different).

**Comment by CharliePoole** [comment]
Regular expressions are a "thing" themselves. Different implementations
only have minor differences. Our's obviously use .NET to match and so work
like .NET.

How you use the regular expression differs a fair bit between languages.
For example, how you say "return true if the input matches the pattern." C#
uses functions. The syntax I used, with special operators, is Perlish.

I take your point though. It does need to be documented. Can you look at
the documentation page and tell me what parts need to be clearer?

**Comment by oznetmaster** [comment]
It is not so obvious, since the VS C# editor is also .NET, but uses a completely different regular expression syntax.

I do not know Perl, so that may be why it was no obvious to me.

I assume we can just either link to the .NET regular expression documentation, or extract it?

Currently, there is no documentation of the actual regular expression syntax that I could find.

**Comment by CharliePoole** [comment]
I wasn't aware that the C# editor used a different syntax for a regular
expression. Maybe it should be called "irregular" then.

As to refrences, O'Reilly "Mastering Regular Expressions" is generally
considered the bible. There are various descriptions on the web, including
Microsoft's own documentation at
https://msdn.microsoft.com/en-us/library/az24scfc%28v=vs.110%29.aspx

I can include some links. I don't want to try replace the existing
documentation. This is basic stuff a programmer should know, IMO, or they
shouldn't be using it!

**Comment by CharliePoole** [comment]
In any case, specific comments about the existing docs would help to finish
this.

**Comment by oznetmaster** [comment]
* --tests= needs a note indicating that test names that have commas in them should be in quotes.
* --where Test Selection Language needs to clarify what regular expression syntax is being used (.NET in this case). Perhaps some relevant examples as well?

**Comment by CharliePoole** [comment]
Updated the page in the wiki.
