### ISSUE TITLE
Rename nunit-console.exe

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#929]
This is an idea I wanted to put up for discussion. I am looking at build systems like [Cake](http://cakebuild.net/) that assume NUnit is in the path or installed as a NuGet package in the tools directory. In either case, those tools cannot determine if the nunit-console.exe that it finds is a v2 or v3 nunit-console, so it does not know which command line parameters to use.

A possible workaround for this would be to rename the console to something unique to NUnit 3. Possibilities are `nunit3-console.exe`, `nunit.console.exe`, `nunit.exe`, `nunit3.exe`, ???

Thoughts?

**Comment by CharliePoole** [comment]
I think a rename might be a good idea in order to assist users. Additionally, the advantage you describe when using Cake or other build  systems would accrue to our users. It would not be an advantage for us, because we generally test using our latest console build, which can have options that the build system knows nothing about. That's why we never used the NAnt or MsBuild tasks that run NUnit.

**Comment by rprouse** [comment]
Does anyone have a preference on the new name? Personally, I lean towards `nunit.exe` or `nunit3.exe` - less typing and a clear break :smile:

**Comment by CharliePoole** [comment]
nunit.exe is the traditional name for the gui and I´d like to reserve
nunit3.exe for that purpose.

I always wanted to use nc.exe but that overlapped both netcat and norton
commander.

What are other folks using for their test framework consoles?

We could always go with nunit3-console of course.

Charlie

**Comment by rprouse** [comment]
- xUnit uses `xunit.console.exe`
- MbUnit uses `gallio.echo.exe` for the console runner and `gallio.icarus.exe` for the GUI runner.
- MSTest uses `MSTest.exe`
- csUnit used `csUnitCmd.exe` :-1: 
- SpecFlow uses `runtests.cmd`

`nunit3-console` is ok by me. I would prefer something shorter like `nunit3` since you tend to run the GUI from a shortcut, but type the console runner. `nunit3-gui`?

I am going to move this to the RC unless anyone has objections. It should be quick to knock off once we decide on a name.

**Comment by CharliePoole** [comment]
How about nunit-cmd then?
