### ISSUE TITLE
Installer complains about .NET even if already installed

### ISSUE THREAD

**Issue by brunoqc** [nunit/nunit#939]
I'm trying to uninstall NUnit using NUnit.3.0.0-beta-5.msi to do a clean install later and I get :
![image](https://cloud.githubusercontent.com/assets/24027/10761663/cf1ee774-7c98-11e5-85e5-4cd1fa4fc46f.png)

I can't install .NET Framework 4 since I already have it :
![image](https://cloud.githubusercontent.com/assets/24027/10761750/27a5b904-7c99-11e5-954f-9331bda50b64.png)

**Comment by rprouse** [comment]
What version of Windows? Do you have any versions of Visual Studio installed?

I am wondering if we should remove the pre-requisite. It is probably unlikely that a .NET developer would attempt to install and run NUnit on a machine without NUnit. Otherwise, we will need to look at the pre-requisite and try to figure out why it is failing. Likely because 2.0 isn't installed?

**Comment by CharliePoole** [comment]
Take a look in your registry under at key HKLM\Software\Microsoft\.NETFramework\Policy\v4.0. There should be an entry with name 30319. Do you have that? If not, what is there? And what other keys do you have under Policy?

**Comment by brunoqc** [comment]
@rprouse 
Windows 10 64-bit.

I have Visual Studio Community 2015, the express edition of Visual C++ 2008 and 2010 and Visual Studion Express 2013.

I don't have .NET 2 installed.

@CharliePoole 
I have HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\policy\v4.0 with the value: 30319-30319

Under policy I have AppPatch, Servicing, Standards, Upgrades, v2.0 and v4.0.

**Comment by CharliePoole** [comment]
That's what you should have - it's what I have, for example.

@rprouse is it possible this works differently on Windows 10?

**Comment by rprouse** [comment]
I have two Windows 10 64-bit machines and it installs fine for me. I see the same things in the registry as @brunoqc and it looks the same as my Win8.1 machine. The only difference I can think of is that I have .NET 2.0 installed.

**Comment by CharliePoole** [comment]
Can you create a package where 4.0 is required (not 2.0) and see if that
installs?

**Comment by rprouse** [comment]
@brunoqc, you mentioned that you have a a v2.0 node under HKLM\Software\Microsoft\.NETFramework\policy, is there a 50727 key under that?

**Comment by brunoqc** [comment]
Yes I have 50727 under HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\policy\v2.0.

**Comment by rprouse** [comment]
@brunoqc, I am putting status confirm on this because I am not able to reproduce on any of my Win10 machines, so I don't think this should hold up the release. Unfortunately I don't have any clean VM's to test on.

You mention uninstall in the issue. Did this happen uninstalling beta 5 so that you could re-install clean? Can you remember the steps you took to help us reproduce?

**Comment by brunoqc** [comment]
Yes I'm trying to reinstall nunit.

I tried to install it a couple of minute before and I wasn't paying much attention. I don't know if the installation failed (I don't see the install path in the installer to confirm) or not so I'm trying to reinstall.

Right now when I start the installer I have the "Change", "Repair" and "Remove" buttons and pressing on any of them results in the .NET requirement problem.

**Comment by rprouse** [comment]
You are the man @brunoqc, I can now reproduce.

1. Install NUnit.3.0.0-beta-5.msi
2. Run the installer again and attempt to repair or uninstall.

For your information, NUnit is installed on your machine. You can find it in C:\Program Files (x86)\NUnit.org

If you want to uninstall, doing so from add/remove programs works.

**Comment by brunoqc** [comment]
> NUnit is installed on your machine. You can find it in C:\Program Files (x86)\NUnit.org

Great, thanks! :+1:
