### ISSUE TITLE
Confirm or modify list of packages for release

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#940]
We've gone around on the issue of what packages we really need. I think we should resolve this for the final release, which probably means for the RC.

Specifics issues to resolve:

1. Separation of Silverlight. This is currently covered by #783. If we complete this, then we'll add a new zip and nupkg for Silverlight and drop silverlight from the existing packages.

2. Msi's. Github doesn't provide release download status, but you can see them here:
    http://www.somsubhra.com/github-release-stats/
    Based on the counts, I would propose we no longer distribute the framework and runner msis.

**Comment by rprouse** [comment]
Silverlight - If we are planning on dropping support for SilverLight in the near future as you state in #783, then I agree that we should release a separate Zip/NuGet  package for it or bite the bullet and drop support for it now. Other than modifying the eye-bleeding XML of NUnit.proj, that should be fairly easy. Should we remove SL from the MSI too and just have a NuGet/Zip to maintain like CF?

Interesting stats for the installs. People just get everything. Personally, I prefer to install just the runners and rely on NuGet for the framework, but even then I tend to download the full install and ignore the framework assemblies.

The only issue I see with dropping the runner and framework MSI's is that it makes it harder to release them at a different pace in the future.

**Comment by CharliePoole** [comment]
You reminded me of something  else - possibly a separate issue.

Our layout on disk is not conducive to installing multiple engines, runners, etc. It's ...

```
nunit.org
   bin
      ... engine and console files
   framework
      VERSION
         PLATFORM
            ... framework files
```

Should we consider something like this ...

```
nunit.org
   nunit-console
      ... console files plus engine
   nunit-gui (future)
      ... gui files plus (possibly a different) engine
   framework
      VERSION
         PLATFORM
            ... framework files
```

I considered creating a separate directory just for the engine at one time but I'm no longer seeing it as so necessary, so long as we have a way to find engines.

**Comment by CharliePoole** [comment]
In our offline discussion we decided to stop releasing the framework and runner msis. I think we should retain the ability to do it for a bit and only stop building them as a part of the main packaging target. The easiest way would be to change the AllPackages item group, replacing PackageAllMsis with PackageMasterMsi.

**Comment by rprouse** [comment]
From an offline conversation,

* new nuget packages and maybe a zip, just like CF. In fact you could
copy and edit CF's.
* remove it from the nunit and nunitlite general nuget packages.
* only remove it from the msi if you have time - I know msi updates
are pretty tedious.
* let's leave it in the zip for now
* we should keep it in the overall solution as well, since it let's us
make sure that changes compile
