### ISSUE TITLE
Breaking API change in ValueSourceAttribute in v3

### ISSUE THREAD

**Issue by RalfKoban** [nunit/nunit#947]
Hello,

it seems that NUnit v3 has a breaking API change for the ValueSourceAttribute which is not documented.
In v2 it was possible to provide names of non-static methods. This made it easy to define an inheritance hierarchy of tests were subclasses (test classes) could provide input for the tests defined in the base class.

In v3 the methods must be static now, similar to the TestCaseSourceAttribute.

It would be great if the ValueSourceAttribute does not need to have static methods.

BR,
Ralf Koban

**Comment by rprouse** [comment]
@RalfKoban, there were a lot of bugs around non-static value sources, so it was decided to remove them in #698. For more information, please see that issue.

We missed this in the [Breaking Changes](https://github.com/nunit/nunit/wiki/Breaking-Changes) documentation. I have updated the breaking changes documentation and the documentation for `ValueSourceAttribute`.
