### ISSUE TITLE
Update copyright in NUnit Console

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#949]
Currently showing 2014, should be updated. Easy fix, we can do it as part of the release. We should probably add it to the notes on how to put out a release.

**Comment by CharliePoole** [comment]
Good point. Also applies to NUnitLite.

This is exactly what I think we should be doing today. I was just starting to do the same myself. 

For the docs, let's do the same unless updating the wiki itself is faster than creating the issue.
