### ISSUE TITLE
NUnitLite XML output is not consistent with the engine's

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#954]
There are four key differences:

1. The engine now has two added attributes in the test-run element. NunitLite does not.

    **Update:** Neither of these is needed in the nunitlite output
      * `engine-version` - because no engine is involved
      * `clr-version` - because nunitlite is running in process with the tests, so it's the same version

2. The engine no longer has an environment element under test-run, it's under test-suite.

3. The engine creates a test-filter element under test-run. NUnitLite does not.

4. The engine creates a settings element under the test-suite for each assembly. NUnitLite does not.

This is an easy fix only if we don't mind adding code in NUnitLite that duplicates the engine and framework. It's possible that only some of the above items will get fixed for the RC.

**Comment by oznetmaster** [comment]
Biggest issue for me is the placement of the environment element, The other could wait if absolutely necessary.

**Comment by CharliePoole** [comment]
@rprouse @oznetmaster The engine puts an engine-version attribute in the test-run element. That doesn't make any sense for NUnitLite. There will be a framework-version in the environment element on the assembly suite, should we simply omit the attribute on test-run?

**Comment by oznetmaster** [comment]
I would think so.

**Comment by rprouse** [comment]
If you mean omit it just in nunitlite, then yes. I think it is useful for
the full framework though.

**Comment by oznetmaster** [comment]
I assumed the question was being asked about nunitlite.

**Comment by CharliePoole** [comment]
I updated the description to reflect the exclusion of the attribute.
