### ISSUE TITLE
Special message for options not supported in a particular NUnitLite build

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#961]
Some options (e.g. --workers) are not supported in the portable build. They simply show up as "invalid option" which may be confusing - it confused me anyway.

We would ideally like to give a special message for these, indicating that they are not supported in the portable build.

While doing this, it would make sense to review just why some options are not supported and consider re-instating them.

**Comment by CharliePoole** [comment]
After doing some initial work, I realized that this applies to more than just the portable build. Ideally, any options that are supported in some builds but not others should give a special message when they are used in a build where they are not supported. Essentially, this means that all builds of NUnitLite should recognize the same options but not necessarily accept them.

This option is probably best handled in coordination with a rewrite of Options.cs.

**Comment by CharliePoole** [comment]
I propose we close this as won't fix. While it was a nice idea, it presents a big maintenance problem if we implement it.

**Comment by rprouse** [comment]
I agree, closing.
