### ISSUE TITLE
Access list of included / excluded categories programmatically during test time

### ISSUE THREAD

**Issue by neverendingqs** [nunit/nunit#963]
Feature request.

Operations in `SetUpFixture` allows a one-time setup for all test fixtures. However, there may be some operations that we want to ignore if certain test categories are excluded.

For example, we may want to generate less data if certain categories are unused.

Accessing the list of included / excluded categories during a test run would help make decisions at runtime.

**Comment by CharliePoole** [comment]
This is another way of accomplishing what is requested in issue #39, so I'm marking it as a duplicate.

In general, we want to avoid the test code (i.e. your SetUpFixture) from knowing about how it was run. In the NUnit architecture, runners know about tests, tests don't know about runners.

Your request would allow you to do procedurally what #39 asks NUnit to do in a descriptive way, simply by placing a category on the fixture or method. The descriptive model seems preferable.

That said, please add any thoughts you have about whether or not the approach in #39 would work for you.
