### ISSUE TITLE
Update Contributors.md

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#973]
Contributors.md was not updated for the RC release. New contributors should be added.

Should we move this to the foot of README.md so it is more visible? Also Contributors.md could be confused with the common CONTRIBUTING.md which give instructions on contributing to the project.

**Comment by rprouse** [comment]
Opps, the content of Contributors.md is already in Readme.md which is a bit redundant. We should keep one or the other up to date and delete the other. I say delete Contributors.md and update Readme.md.

**Comment by CharliePoole** [comment]
Sounds good.

**Comment by rprouse** [comment]
Do we still want to do this? @CharliePoole you deleted them from the README and I deleted the Contributors.md file in another issue. I think we should just point to the GitHub contribution list as the README currently does.

Close?
