### ISSUE TITLE
Add Contributing.md file

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#974]
Add a file to the project with information on how to contribute and how to build the solution.

- Include links to our coding guidelines.
- Include information on how to build on each platform. For example, Linux needs to download the latest version of MonoDevelop and the PCL components from the Xamarin feed. See #784 
- Include information on how to build and run all tests from the command line
- Add links to the various developer documentation in nunit/dev like how to package a release

This document should be mentioned and linked to directly from the README.md which serves as the front page of the GitHub repo.

**Comment by CharliePoole** [comment]
Some of the stuff listed seems to belong in the dev wiki. In particluar how to build. Maybe this should just be a gateway page to what's in that wiki.  Some of the other product wikis could also do this.

**Comment by rprouse** [comment]
If we add this file, it will create a yellow bar and link at the top of the submitting issues page. We could use this to remind people that NUnit 3 does not work with most third party runners. It might reduce a few of those bugs being reported.

https://github.com/blog/1184-contributing-guidelines

![](https://camo.githubusercontent.com/71995d6b0e620a9ef1ded00a04498241c69dd1bf/68747470733a2f2f6769746875622d696d616765732e73332e616d617a6f6e6177732e636f6d2f736b697463682f6973737565732d32303132303931332d3136323533392e6a7067)
