### ISSUE TITLE
Inconsistent return codes depending on ProcessModel

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#983]
Per @NikolayPianikov...

> When --process=InProces, nunit returns -100 for StackOverflow exception
but when --process=Multiple or Separate, nunit returns 0. Is it possible to return -100? TeamCity looks at the negative exit code to raise a build problem

and...

> When --process=InProces, nunit returns -100 for OutOfMemory exception
but when --process=Multiple or Separate, nunit returns 1 for one failed test.
It will be better if nunit console returns the same exit code

When a separate agent is used, it's the agent process that terminates with -100. We used to detect that the agent had died and terminate the console with -100 as well.

However, in NUnit 3.0, we wanted to continue in order to report tests from any other agents, so we trapped the exception that causes us to terminate. We report the problem with the terminated assembly in the XML and on the console output.

That's all well and good, but we need to somehow reflect the failure in the return code as well.

@NikolayPianikov Imagine two assemblies running in two agents. One of them runs to completion with two failures - the normal return code would be 2. The other gets an OutOfMemoryException - the normal return code would be -100. What should nunit-console return?

**Comment by CharliePoole** [comment]
We should also examine whether we can do something better with an OOM that occurs during a particular test, like restarting without that test. That's for the future, however.

**Comment by CharliePoole** [comment]
I'd like to see this done in rc-2. That doesn't necessarily make it possible, however. :-(

**Comment by CharliePoole** [comment]
@rprouse I assigned this to you without telling you. What do you think? :-)

**Comment by rprouse** [comment]
Sure, I will try to get it in time for the RC.

On 4 November 2015 at 18:55, CharliePoole <notifications@github.com> wrote:

> @rprouse <https://github.com/rprouse> I assigned this to you without
> telling you. What do you think? :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nunit/nunit/issues/983#issuecomment-153908540>.
>



-- 

Rob Prouse



I welcome VSRE emails. Learn more at http://vsre.info/

**Comment by NikolayPianikov** [comment]
@CharliePoole related to OutOfMemoryException: I would prefer to receive the number of failed tests

**Comment by CharliePoole** [comment]
@NikolayPianikov As you see, Rob already merged the change, so that's what will be in RC-2. Small changes are possible before the final release, bigger ones later. I'm not sure which this would be or if it is even a change.

Expanding on your statement, it seems as if you want to have the actual failed tests (positive return) reported if the agent is able to get control after an exception and report the reason for failure (like OOM). In the case where that's not possible, the engine sees it only as a communications failure and so has nothing to report. Is that correct?

Please start a new issue if necessary after you have tried this version out.
