### ISSUE TITLE
Update docs for parallel execution

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#986]
We should review these completely. There may be a need for a general section about parallel execution, which could be taken from material in the dev wiki. We should clearly state that parallelism below the fixture level is not yet available.

**Comment by CharliePoole** [comment]
@nunit/core-team This is ready to be closed. Please review the writeup at https://github.com/nunit/nunit/wiki/Parallel-Test-Execution

**Comment by CharliePoole** [comment]
@rprouse Nobody is reviewing this, would you take a look? 

@NikolayPianikov This is something you were concerned about as well. Can your review it?

**Comment by CharliePoole** [comment]
I'm closing this in spite of the lack of reviews. We can update it if necessary.

One issue is whether documentation like this is sufficiently visible in the wiki menu.

**Comment by NikolayPianikov** [comment]
Looks good
