### ISSUE TITLE
V2 driver is passing invalid filter elements to NUnit V2

### ISSUE THREAD

**Issue by flaub** [nunit/nunit#990]
Here's the output I get:

```
$ mono SOME_PATH/bin/nunit3-console.exe SOME_DLL --labels=All --where "class=='SOME_CLASS'"
NUnit Console Runner 3.0.5783
Copyright (C) 2015 Charlie Poole

Runtime Environment
   OS Version: MacOSX 14.5.0.0
  CLR Version: 4.0.30319.17020

Test Files
    SOME_DLL

Test Filters
    Where: class=='SOME_CLASS'


Errors and Failures

1) Error :
Invalid filter element: class
Parameter name: xmlNode
  at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke (System.Runtime.Remoting.Proxies.RealProxy rp, IMessage msg, System.Exception& exc, System.Object[]& out_args) [0x00000] in <filename unknown>:0

Test Run Summary
    Overall result: Failed
   Tests run: 0, Passed: 0, Errors: 0, Failures: 0, Inconclusive: 0
     Not run: 0, Invalid: 0, Ignored: 0, Explicit: 0, Skipped: 0
  Start time: 2015-11-05 11:47:00Z
    End time: 2015-11-05 11:47:00Z
    Duration: 0.007 seconds

Results (nunit3) saved as TestResult.xml
```

It does work when filtering on the category (`cat == XXX`).

**Comment by flaub** [comment]
BTW same goes for `test == XXX`

**Comment by CharliePoole** [comment]
I have tried this with and without the double and single quotes and it works every time!

However, when I try it against a test that uses NUnit 2.6.4, I do get that error. Is that your situation? 

The v2 driver is passing filter elements that V2 does not understand. Using them should give an error, but it should be a much clearer one than what you are getting!

**Comment by CharliePoole** [comment]
I changed the title of the issue to reflect what the problem is.

The driver is translating the filter to NUnit V2 filter elements. It detects the bad filter elements and throws an exception. This is definitely as it should be but the message is only clear if you know how the driver works. It should be an exception type for which we do not display a stack trace and should have an explanatory message like "The class filter cannot be used with NUnit V2 tests"

**Comment by flaub** [comment]
Indeed this was against NUnit 2.6.4. Thanks!

**Comment by flaub** [comment]
Is running v2 tests with the v3 console supported? How do I specify which tests to run against v2?

When I use --test, I get "Invalid filter element: test".

**Comment by rprouse** [comment]
Running v2 tests with the v3 console is supported. The engine looks at the copy of nunit.framework that each assembly is referencing. It then runs each assembly appropriately.

Some of the filters do not work when running v2 tests. We will need to document that. See the code in #922

**Comment by flaub** [comment]
OK, #992 will fix my issue. Thanks!

**Comment by CharliePoole** [comment]
I updated the wiki: https://github.com/nunit/nunit/wiki/Test-Selection-Language
