### ISSUE TITLE
Mono.Options should not be exposed to public directly

### ISSUE THREAD

**Issue by linquize** [nunit/nunit#991]
nunit3 adopts `Mono.Options` classes.
However, this leads to namespace collision of the library user.
The user's app may also ship another copy of `Mono.Options` classes.

Since class `CommandLineOptions` relies on inheriting `Mono.Options` classes,
I suggest to rename the namespace to something like `NUnit.Options` to avoid namespace collision.

**Comment by CharliePoole** [comment]
Good catch! We'll fix it in the next RC.
