### ISSUE TITLE
Enable Warning as Error

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#995]
We constantly have new warnings creeping into the code, often because of missing XML documents, or unused variables on one platform or another. We should fix these warnings, then enable warning as error on all projects to prevent new ones from being introduced.

**Comment by ChrisMaddock** [comment]
@rprouse - Sorry, I always miss checking to see if old issues are assigned to anyone before I start. Mind if I take this on? The remaining changes are minimal.

**Comment by rprouse** [comment]
I don't mind, but you need to make sure it builds without warnings on
Windows and Linux including Mono 3.2.8

**Comment by rprouse** [comment]
Always feel free to clean up warnings though

**Comment by CharliePoole** [comment]
@rprouse I set up the NUnit.System.Linq project to only be built on AppVeyor, since it's not built as part of NUnit but pulled in as a package.

**Comment by ChrisMaddock** [comment]
Thanks @rprouse. It looks like most of the work is already done to be honest, but hopefully enabling this should mean no regressions.

**Comment by ChrisMaddock** [comment]
Ah - I'd naively assumed warnings present would be similar for xbuild and msbuild. Looks like there's more to do that I thought, will chip away further and see how far I get.

**Comment by rprouse** [comment]
Now you see why an apparently easy issue isn't done yet :smile_cat:
