### ISSUE TITLE
Support multiple TestOf attributes per test

### ISSUE THREAD

**Issue by DerekSMorin** [nunit/nunit#999]
Support multiple TestOn attributes per test

https://github.com/nunit/nunit/wiki/TestOf-Attribute

Note: you can currently only have one TestOf attribute per fixture or test.

**Comment by CharliePoole** [comment]
Can you explain why this would be desirable? Should we be encouraging people to write tests that do more than one thing?

**Comment by DerekSMorin** [comment]
Maybe not encouraging - but allowing for differences in the way people work.  Some people have tests that encompass larger functional areas.
I'm converting some old MBUnit tests to NUnit.
Date: Fri, 6 Nov 2015 11:19:53 -0800

**Comment by CharliePoole** [comment]
Fair enough.  We'll see what folks think.

**Comment by CharliePoole** [comment]
@nunit/contributors I flagged this as an idea over a year ago with the comment "Let's see what people think." It has been just sitting ever since. Can we either add it to the backlog or reject it? Do you think we should do this?

**Comment by rprouse** [comment]
Like #100, I don't have a strong opinion on this. I can see the use and I don't see the implementation being much different than allowing multiple categories on a test.

**Comment by CharliePoole** [comment]
I think it only requires changing the attribute usage, since it's not an attribute NUnit uses itself.

**Comment by immeraufdemhund** [comment]
I have had a few scenarios where I think this would be useful, but probably more work than a person should put into it. Such as if I was writing acceptance tests or integration tests that would use a few different classes for a desired outcome than I would possibly want to show that this adds to that code coverage. Where that woudl bite you in the butt is if you use DI and inject in different classes (such as when you add a class to care for functionality) then i'd have to update my test to reflect that this is included. 

Sooo.. yes it would be nice, but I personally would want it to be a little bit smarter if it was to be used such has scanning the class for inheritance and implementations.. I will say that a counter argument to what I just said would be to make my change and run all tests and see what broke (hopefully something!).

**Comment by stevenaw** [comment]
I notice that we also use `TestOf` as a publicly-settable property of type `Type` on [TestAttribute](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Attributes/TestAttribute.cs#L73) and [TestFixtureAttribute](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Attributes/TestFixtureAttribute.cs#L122). Should these properties also be updated for consistency too?

If so, I can see this becoming a breaking change.

**Comment by CharliePoole** [comment]
I don't think we want to go beyond allowing multiple attributes.

**Comment by julealgon** [comment]
Was this just ignored? I see that the attribute is still `AllowMultiple = false`.

I was honestly surprised by the behavior when reading the documentation on this attribute. As someone pointed out, it sounds to me we should leave the decision to the user: there is just no reason to force users to comply with the "1 unit test per real class" approach.

Not allowing multiple of these attributes to me is equivalent to removing the `out` modifier in the language: it's usually a bad practice, but there are uses for it.

**Comment by jnm2** [comment]
I tend to agree. A unit can comprise multiple classes. Classes are the imperfect medium in which units are expressed.

> Was this just ignored?

We typically rely on community members like you to help us gauge what we should put our few hours of time towards. In this instance we've agreed to the proposal and labeled it `help-wanted`, which means we're waiting for a motivated individual to offer a PR. Can I interest you in that? 😃

**Comment by julealgon** [comment]
> We typically rely on community members like you to help us gauge what we should put our few hours of time towards. In this instance we've agreed to the proposal and labeled it help-wanted, which means we're waiting for a motivated individual to offer a PR. Can I interest you in that? 😃

That's a fair point. I didn't spot the `help-wanted` label, so I was just wondering if folks had agree to not do it and was thus puzzled about the reasoning.

I'll see if I can contribute a bit here, since we are relying on NUnit quite extensively in some projects. Thanks for clarifying @jnm2 .

**Comment by jnm2** [comment]
Glad to hear it! If you let us know as soon as you're ready to take it, we can remove the `help wanted` label. (GitHub suggests issues with this label to newcomers.)

**Comment by CharliePoole** [comment]
Aside from merely changing the attribute definition, you should examine how we access the property it creates. Our `PropertyBag` has differing ways of accessing properties that may appear multiple times so it could be that simply allowing multiple attributes will not automatically cause multiple properties to appear on the test. [This will make more sense when you look at the code of the attribute.]

**Comment by jnm2** [comment]
@sunithapatel Fantastic, thanks for jumping in!

The GitHub wikis don't allow pull requests, sadly, so the procedure there is for a contributor like yourself to go ahead and edit the wiki and then post a link back here for review.

**Comment by sunithapatel** [comment]
@jnm2 Sorry, newbie question, but I am not sure what is the correct way to edit the wiki.

Looking at this link: [https://help.github.com/articles/adding-and-editing-wiki-pages-locally/](https://help.github.com/articles/adding-and-editing-wiki-pages-locally/)
it says to clone the wiki locally, make changes in a branch and push that for review since only master branch is publicly visible. Is that what I need to do and then post the link to it here so you can review it?

**Comment by CharliePoole** [comment]
Our process is that we give people write access to the wiki, they change it online and we look at what they did. It relies on trust, obviously, but also on the fact that we can roll back changes. :smile: 

However, if you change the way `TestOfAttribute` works, by allowing multiple copies, we probably don't want to update the documentation till the change is actually released.

**Comment by jnm2** [comment]
I forgot, is it only members who can edit or can anyone edit the wiki?

Something I've done to avoid losing mental context (3.12 will probably be six months from now) is to say, "Starting in version 3.12," in the documentation and document it immediately.

**Comment by CharliePoole** [comment]
We used to have a Contributors team, which, among other things, was allowed to edit the wiki. We gave people that status at the drop of a hat. That's no longer the practice, I understand.

In V2 the docs were littered with comments about what version changes started in. With 3.0, we decided not to do that any longer but to always have the docs show the latest release. If that's still the policy, then "Starting in version 3.12" would need to be removed eventually.

I have sometimes created a new page with "New" prefixed to it for the same reason, but then you still have to go back and move it or copy the new text. It's just faster. Wish there was some automatic way to do this but lacking that I suppose we should use the approach that gives the best information in the case where we forget to go in and update it.

**Comment by jnm2** [comment]
In the back of my mind I'm hoping we find a way to host our docs on nunit.org so that contributors can offer documentation PRs.

**Comment by mikkelbu** [comment]
Merged. Thanks for the contribution @sunithapatel

**Comment by mikkelbu** [comment]
> In V2 the docs were littered with comments about what version changes started in. With 3.0, we decided not to do that any longer but to always have the docs show the latest release. If that's still the policy, then "Starting in version 3.12" would need to be removed eventually.

Actually, I just stumbled upon nunit/docs#91 which proposes the opposite. Personally, I think it is fine to note when different features was introduced, but it will be of less value the older the change, so I have no problem with removing the older "tags".

**Comment by CharliePoole** [comment]
Correct. We did X then we did Y then I proposed Z in an issue that never got resolved. I'd be happy to see us document changed behavior in recent releases only.i

**Comment by CharliePoole** [comment]
Correct. We did X then we did Y then I proposed Z in an issue that never got resolved. I'd be happy to see us document changed behavior in recent releases only.i
